/* Agriculture Paper I (IFoS Paper V). Row: [question, options, answerIndex, explanation]. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Agro-climatic Zones & Cropping Systems', w: 3, q: [
  ['The Planning Commission (1989) divided India into:', ['15 agro-climatic regions', '20 agro-ecological regions', '127 agro-climatic zones', '8 agro-climatic regions'], 0,
    'Based on physiography, soils and climate (Y.K. Alagh). NBSS&LUP gave 20 agro-ecological regions; ICAR’s NARP gave 127 agro-climatic zones.'],
  ['NBSS&LUP delineated India into how many agro-ecological regions?', ['20', '15', '60', '127'], 0,
    'The 20 AERs (and about 60 sub-regions) are based on growing period, soils, physiography and bioclimate.'],
  ['Cropping intensity is:', ['(Gross cropped area ÷ net sown area) × 100', '(Net sown area ÷ geographical area) × 100', '(Irrigated area ÷ gross cropped area) × 100', '(Crop yield ÷ potential yield) × 100'], 0,
    'India’s cropping intensity is about 150%. Multiple cropping raises it; irrigation is the main driver.'],
  ['Sowing the next crop into the standing previous crop shortly before its harvest is:', ['Relay cropping', 'Intercropping', 'Mixed cropping', 'Ratoon cropping'], 0,
    'Example: sowing lentil or lathyrus (utera/paira) into standing rice. Ratooning grows a crop from stubble (sugarcane).'],
  ['A Land Equivalent Ratio (LER) greater than 1.0 shows that:', ['The intercrop is more productive than growing the crops as sole crops', 'The main crop suffered heavy yield loss', 'Sole cropping is more productive', 'The two crops did not compete at all'], 0,
    'LER = Σ (intercrop yield ÷ sole-crop yield). LER 1.3 means 30% more land would be needed as sole crops to match the intercrop yield.'],
  ['Zaid crops are grown:', ['Between the rabi and kharif seasons (about March–June)', 'Only during the south-west monsoon', 'Only in winter (October–March)', 'Only under protected cultivation'], 0,
    'Examples: watermelon, cucumber, muskmelon, moong, fodder crops — usually needing irrigation.'],
  ['The most extensive cropping system of the Indo-Gangetic plains is:', ['Rice–wheat', 'Maize–wheat', 'Cotton–wheat', 'Sugarcane–ratoon–wheat'], 0,
    'About 10 million ha in India. Problems: falling water tables, residue burning, *Phalaris minor*, soil health decline — hence calls for diversification.'],
] },
{ p: 'A1', t: 'Crop Production', w: 3, q: [
  ['For wheat, the most critical stage for irrigation is:', ['Crown root initiation (about 20–25 days after sowing)', 'Tillering', 'Milk stage', 'Dough stage'], 0,
    'Missing the CRI irrigation cuts yield the most. Other critical stages: jointing, flowering, milk and dough.'],
  ['The System of Rice Intensification (SRI) was developed in:', ['Madagascar (Fr. Henri de Laulanié, 1983)', 'The Philippines (IRRI)', 'China (Yuan Longping)', 'Japan'], 0,
    'Young seedlings (8–12 days), single seedling per hill, wide spacing (25 × 25 cm), intermittent irrigation, mechanical weeding, organic inputs.'],
  ['ICRISAT, which works on sorghum, pearl millet, chickpea, pigeonpea and groundnut, is at:', ['Patancheru, Hyderabad', 'Los Baños, Philippines', 'Ibadan, Nigeria', 'Texcoco, Mexico'], 0,
    'IRRI is at Los Baños; IITA at Ibadan; CIMMYT (maize and wheat) at Texcoco, Mexico.'],
  ['Geocarpy — pods developing underground after "pegging" — is seen in:', ['Groundnut', 'Soybean', 'Chickpea', 'Mustard'], 0,
    'After fertilisation the gynophore (peg) elongates and pushes the ovary into the soil. Gypsum at pegging supplies calcium and sulphur for pod filling.'],
  ['Retting of jute is:', ['Microbial breakdown of pectin to free bast fibres', 'Chemical bleaching of fibre', 'Drying of stems in the sun', 'Mechanical decortication'], 0,
    'Bundles are steeped in slow-moving water for 10–20 days. Ribbon retting and microbial consortia reduce time and water use.'],
  ['Which cereal is called the "queen of cereals" for its high genetic yield potential?', ['Maize', 'Rice', 'Wheat', 'Sorghum'], 0,
    'Maize is a C₄ crop grown in all seasons; used as food, feed, fodder, starch and ethanol.'],
  ['The International Year of Millets, proposed by India, was:', ['2023', '2021', '2022', '2024'], 0,
    'Millets (Shree Anna) are nutri-cereals: climate-resilient, low input, rich in fibre, iron and calcium (finger millet is very rich in calcium).'],
] },
{ p: 'A1', t: 'Weed Science', w: 2, q: [
  ['The major weed of wheat in the rice–wheat system that evolved resistance to isoproturon is:', ['*Phalaris minor*', '*Avena fatua*', '*Chenopodium album*', '*Cyperus rotundus*'], 0,
    'Resistance appeared in Punjab and Haryana in the early 1990s. Managed by clodinafop, sulfosulfuron, pinoxaden, zero tillage and crop rotation.'],
  ['The Mexican beetle *Zygogramma bicolorata* is used for biological control of:', ['*Parthenium hysterophorus*', '*Lantana camara*', '*Eichhornia crassipes*', '*Striga asiatica*'], 0,
    'Parthenium (congress grass) causes dermatitis and allergies. Water hyacinth is controlled by *Neochetina* weevils.'],
  ['Glyphosate kills plants by inhibiting:', ['EPSP synthase in the shikimate pathway', 'Acetolactate synthase', 'Photosystem II', 'Acetyl-CoA carboxylase'], 0,
    'Non-selective, systemic, post-emergence. ALS inhibitors: sulfonylureas; PS II inhibitors: atrazine, isoproturon; ACCase inhibitors: clodinafop.'],
  ['2,4-D is widely used in cereals because it:', ['Selectively kills broadleaf (dicot) weeds', 'Kills all grasses', 'Is a soil fumigant', 'Controls only sedges'], 0,
    'A synthetic auxin (phenoxy herbicide). Grasses tolerate it; it also controls *Cyperus* partly.'],
  ['*Orobanche*, a problem in tobacco and mustard, is a:', ['Total root parasite', 'Partial stem parasite', 'Total stem parasite', 'Epiphyte'], 0,
    '*Striga* is a partial root parasite (sorghum, sugarcane); *Cuscuta* is a total stem parasite; *Loranthus* is a partial stem parasite.'],
  ['Atrazine is used as a pre-emergence herbicide mainly in:', ['Maize and sugarcane', 'Rice nursery', 'Wheat', 'Mustard'], 0,
    'A triazine that blocks electron transport at Photosystem II. Maize tolerates it because it detoxifies atrazine (glutathione conjugation).'],
  ['The critical period of crop–weed competition generally falls in:', ['The first one-third to one-quarter of the crop’s duration', 'The last month before harvest', 'The ripening stage only', 'The entire crop period equally'], 0,
    'Weeding within this window gives the highest return. Example: about 30–45 days for wheat and 15–45 days for many kharif crops.'],
] },
{ p: 'A1', t: 'Soil Genesis, Classification & Properties', w: 3, q: [
  ['Black cotton soils of the Deccan are classified in USDA Soil Taxonomy as:', ['Vertisols', 'Alfisols', 'Oxisols', 'Aridisols'], 0,
    'Rich in montmorillonite; deep cracks when dry, sticky when wet (self-mulching). Formed from Deccan basalt. Red soils are mostly Alfisols.'],
  ['The number of soil orders in USDA Soil Taxonomy is:', ['12', '10', '8', '15'], 0,
    'Entisols, Inceptisols, Alfisols, Vertisols, Aridisols, Mollisols, Ultisols, Oxisols, Spodosols, Histosols, Andisols and Gelisols.'],
  ['Most young alluvial soils of the Indo-Gangetic plains fall under:', ['Entisols and Inceptisols', 'Oxisols and Ultisols', 'Spodosols', 'Histosols'], 0,
    'Little profile development. Khadar (new alluvium) and bhangar (old alluvium).'],
  ['Under the USDA system, clay particles are smaller than:', ['0.002 mm', '0.02 mm', '0.05 mm', '0.2 mm'], 0,
    'Sand 2–0.05 mm, silt 0.05–0.002 mm, clay < 0.002 mm (2 µm). The international (Atterberg) system uses 0.02 mm as the silt–sand limit.'],
  ['Among these clay minerals, the highest cation exchange capacity is shown by:', ['Montmorillonite', 'Kaolinite', 'Illite', 'Chlorite'], 0,
    'CEC (cmol/kg): montmorillonite 80–120 (expanding 2:1); illite 10–40 (K fixes the layers); chlorite 10–40; kaolinite 3–15 (1:1, non-expanding). Vermiculite is higher still (100–150).'],
  ['Laterite soils are formed under:', ['High temperature and heavy rainfall with alternate wet and dry seasons', 'Cold humid conifer forests', 'Arid, hot deserts', 'Waterlogged marshes'], 0,
    'Intense leaching removes silica and bases, leaving Fe and Al oxides. They are acidic, poor in N, P, K and Ca, and harden on exposure.'],
  ['Podzolisation occurs mainly under:', ['Cool humid climate with coniferous forests', 'Hot arid climate', 'Tropical grasslands', 'Waterlogged rice fields'], 0,
    'Acid litter mobilises Fe and Al with organic acids from the E horizon to the B horizon (Spodosols). Found in high Himalaya pockets.'],
  ['The C : N ratio of stable soil humus is about:', ['10 : 1', '40 : 1', '80 : 1', '1 : 1'], 0,
    'Materials with C:N above ~30 (straw 80:1, sawdust 400:1) immobilise soil N during decomposition.'],
  ['The average particle density of mineral soils is about:', ['2.65 g/cm³', '1.33 g/cm³', '1.0 g/cm³', '4.0 g/cm³'], 0,
    'Close to quartz. Bulk density is 1.1–1.6 g/cm³; porosity = (1 − BD/PD) × 100.'],
  ['The Soil Health Card scheme was launched in 2015 at:', ['Suratgarh, Rajasthan', 'Pusa, New Delhi', 'Anand, Gujarat', 'Ludhiana, Punjab'], 0,
    'Cards report 12 parameters: N, P, K, S, Zn, Fe, Cu, Mn, B, pH, EC and organic carbon, with fertiliser advice.'],
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, q: [
  ['The nitrogen content of urea is:', ['46%', '21%', '26%', '82%'], 0,
    'Ammonium sulphate 20.6% N (+24% S); CAN 25–26%; anhydrous ammonia 82%.'],
  ['Diammonium phosphate (DAP) contains:', ['18% N and 46% P₂O₅', '46% N and 18% P₂O₅', '16% P₂O₅ and 12% S', '60% K₂O'], 0,
    'SSP has 16% P₂O₅ and about 12% S; MOP (muriate of potash) has 60% K₂O.'],
  ['Neem-coated urea improves N-use efficiency mainly by:', ['Slowing nitrification, so less N is lost by leaching and denitrification', 'Adding extra nitrogen from neem', 'Acidifying the soil', 'Converting urea to nitrate faster'], 0,
    'Neem limonoids inhibit nitrifying bacteria. 100% neem coating was made mandatory in 2015; it also stopped diversion of subsidised urea to industry.'],
  ['"Crop yield is governed by the nutrient present in the least amount relative to need" is:', ['Liebig’s law of the minimum', 'Mitscherlich’s law of diminishing returns', 'Blackman’s law of limiting factors', 'Law of equimarginal returns'], 0,
    'Illustrated by the "Liebig barrel". Mitscherlich: each successive unit of a nutrient gives a smaller increase in yield.'],
  ['Phosphate-solubilising bacteria used as biofertiliser include:', ['*Bacillus megaterium* var. *phosphaticum*', '*Rhizobium leguminosarum*', '*Azotobacter chroococcum*', '*Frankia*'], 0,
    'Also *Pseudomonas striata*. *Azotobacter* is a free-living aerobic N-fixer; *Azospirillum* is associative; *Frankia* nodulates *Casuarina* and *Alnus*.'],
  ['Available phosphorus in neutral to alkaline soils is estimated by:', ['Olsen’s method (0.5 M NaHCO₃)', 'Bray’s method', 'Alkaline KMnO₄ method', 'Neutral normal ammonium acetate'], 0,
    'Bray’s P-1 is used for acid soils; alkaline KMnO₄ (Subbiah & Asija, 1956) for available N; neutral N ammonium acetate for available K.'],
  ['IFFCO’s Nano Urea (liquid), launched in 2021, is applied as:', ['A foliar spray — one 500 ml bottle is claimed to replace one 45 kg bag of urea', 'A soil drench at sowing only', 'A seed coating', 'A fertigation-only product for drip'], 0,
    'Nanoparticles enter through stomata. Field efficiency claims are still debated; it is meant to supplement top-dressed urea.'],
  ['Denitrification losses of fertiliser N are highest in:', ['Waterlogged (anaerobic) soils such as puddled rice fields', 'Well-drained sandy soils', 'Dry alkaline soils', 'Frozen soils'], 0,
    'Denitrifiers reduce nitrate to N₂O and N₂ when O₂ is scarce. Deep placement of urea (urea super-granules) in the reduced zone limits this.'],
  ['Which is a green manure crop commonly grown in situ before rice?', ['*Sesbania aculeata* (dhaincha)', '*Gliricidia sepium*', '*Pongamia pinnata*', '*Leucaena leucocephala*'], 0,
    'Dhaincha and sunhemp (*Crotalaria juncea*) are ploughed in at about 45–60 days. *Gliricidia* and *Pongamia* loppings are green-leaf manures brought from elsewhere.'],
  ['Consider the following statements about Integrated Nutrient Management (INM):\n1. It combines fertilisers, organic manures and biofertilisers.\n2. It aims only to reduce fertiliser costs, not to maintain soil health.\nWhich is/are correct?', ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], 0,
    'INM aims to sustain yields and soil health together. Long-term fertiliser experiments show NPK + FYM maintains yields best.'],
] },
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 2, q: [
  ['A soil with EC > 4 dS/m, ESP < 15 and pH < 8.5 is classified as:', ['Saline', 'Sodic (alkali)', 'Saline–sodic', 'Acid sulphate'], 0,
    'Sodic: ESP > 15, pH > 8.5, EC < 4. Saline–sodic: EC > 4 and ESP > 15. Saline soils are reclaimed by leaching with good-quality water plus drainage.'],
  ['Sodic (alkali) soils are reclaimed mainly by:', ['Applying gypsum and then leaching', 'Applying lime', 'Adding more sodium chloride', 'Deep flooding without drainage'], 0,
    'Ca²⁺ from gypsum replaces exchangeable Na⁺, which is leached out. Pyrite and press mud also work. Acid soils are reclaimed with lime.'],
  ['In the Universal Soil Loss Equation (A = R K LS C P), "K" is the:', ['Soil erodibility factor', 'Rainfall erosivity factor', 'Cropping management factor', 'Support practice factor'], 0,
    'Wischmeier and Smith. R = rainfall erosivity; LS = slope length and steepness; C = cover management; P = conservation practice.'],
  ['The Central Soil Salinity Research Institute (CSSRI) is located at:', ['Karnal', 'Jodhpur', 'Dehradun', 'Bhopal'], 0,
    'CAZRI is at Jodhpur; the Indian Institute of Soil and Water Conservation at Dehradun; the Indian Institute of Soil Science at Bhopal.'],
  ['Bio-drainage uses:', ['Fast-transpiring trees such as *Eucalyptus* to lower a high water table', 'Subsurface drain pipes', 'Earthworms to improve porosity', 'Microbes to break down salts'], 0,
    'Used in canal-command waterlogged areas (e.g., IGNP Rajasthan). Trees are planted in strips along canals.'],
  ['The order of water-erosion stages as severity increases is:', ['Splash → sheet → rill → gully', 'Gully → rill → sheet → splash', 'Rill → splash → gully → sheet', 'Sheet → gully → splash → rill'], 0,
    'Gullies on a large scale form ravines (e.g., Chambal). Controlled with check dams, gully plugs and vegetation.'],
  ['Shelterbelts and windbreaks are mainly used to control:', ['Wind erosion and desiccation in arid areas', 'Waterlogging', 'Soil acidity', 'Salinity by leaching'], 0,
    'They cut wind speed for a distance of roughly 10–20 times the tree height downwind. Species: *Prosopis cineraria*, *Acacia tortilis*, *Tamarix*.'],
] },
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, q: [
  ['Permanent wilting point corresponds to a soil water potential of about:', ['−15 bar (−1.5 MPa)', '−0.33 bar', '−0.1 bar', '−31 bar'], 0,
    'Field capacity ≈ −0.33 bar (−33 kPa). Available water = FC − PWP. Hygroscopic coefficient ≈ −31 bar.'],
  ['The IW/CPE approach to irrigation scheduling uses the ratio of irrigation water depth to:', ['Cumulative pan evaporation', 'Crop water requirement per day', 'Field capacity', 'Soil water depletion'], 0,
    'A fixed depth (e.g., 5–6 cm) is applied when CPE reaches IW ÷ ratio. Ratios of 0.6–1.0 are typical.'],
  ['The relation between duty (D, ha/cumec), base period (B, days) and delta (Δ, metres) is:', ['Δ = 8.64 B ÷ D', 'Δ = 8.64 D ÷ B', 'D = 8.64 B × Δ', 'Δ = B ÷ (8.64 D)'], 0,
    '1 cumec for 1 day = 86,400 m³ = 8.64 ha-m. Higher duty means less water per hectare.'],
  ['Irrigation water with residual sodium carbonate (RSC) above ____ is generally unsuitable.', ['2.5 meq/L', '0.5 meq/L', '10 meq/L', '25 meq/L'], 0,
    'RSC = (CO₃²⁻ + HCO₃⁻) − (Ca²⁺ + Mg²⁺). Below 1.25 safe; 1.25–2.5 marginal. Sodium adsorption ratio (SAR) is the other sodicity index.'],
  ['The highest field application efficiency is usually achieved with:', ['Drip irrigation', 'Sprinkler irrigation', 'Border flooding', 'Furrow irrigation'], 0,
    'Drip ≈ 90% or more, sprinkler ≈ 70–80%, surface methods ≈ 40–60%. Drip also allows fertigation.'],
  ['Pradhan Mantri Krishi Sinchayee Yojana (2015) uses the slogans:', ['"Har Khet Ko Pani" and "More Crop Per Drop"', '"Jai Jawan Jai Kisan"', '"Kisan Pehle"', '"Jal Hi Jeevan"'], 0,
    'Components include Accelerated Irrigation Benefit Programme, watershed development and micro-irrigation.'],
  ['Alternate wetting and drying (AWD) in rice:', ['Saves water and reduces methane emissions without major yield loss', 'Increases methane emissions', 'Requires continuous submergence', 'Is used only in upland rice'], 0,
    'A field water tube shows when water drops about 15 cm below the surface; then re-flood. Keep flooding at flowering.'],
  ['Consumptive use of water by a crop is:', ['Evapotranspiration plus water retained in plant tissue', 'Only deep percolation losses', 'Only surface runoff', 'Water applied minus effective rainfall'], 0,
    'In practice consumptive use ≈ ET, because the water held in plants is only about 1% of ET.'],
] },
{ p: 'A1', t: 'Dryland Farming & Watershed Management', w: 2, q: [
  ['"Dry farming" refers to crop production in areas receiving annual rainfall of:', ['Less than 750 mm', '750–1150 mm', 'More than 1150 mm', 'Less than 250 mm only'], 0,
    'Dryland farming: 750–1150 mm with some crop moisture stress; rainfed farming: more than 1150 mm.'],
  ['The Central Research Institute for Dryland Agriculture (CRIDA) is at:', ['Hyderabad', 'Jodhpur', 'Bengaluru', 'Nagpur'], 0,
    'CRIDA coordinates the All India Coordinated Research Project on Dryland Agriculture and prepares district contingency plans.'],
  ['Sukhomajri, a model of participatory watershed management, is in:', ['Haryana (near Chandigarh)', 'Maharashtra', 'Rajasthan', 'Madhya Pradesh'], 0,
    'Water harvesting ponds cut siltation of Sukhna lake; villagers shared water and protected hills from grazing. Ralegan Siddhi (Anna Hazare) is in Maharashtra.'],
  ['A kaolin spray on crop foliage acts as an anti-transpirant of the:', ['Reflectant type', 'Stomata-closing type', 'Film-forming type', 'Growth-retardant type'], 0,
    'Kaolin reflects radiation, lowering leaf temperature. Stomata-closing: PMA, ABA; film-forming: wax emulsions, silicone; growth retardant: cycocel.'],
  ['Mulching in dryland agriculture mainly helps by:', ['Reducing evaporation and conserving soil moisture', 'Raising soil salinity', 'Increasing runoff', 'Fixing atmospheric nitrogen'], 0,
    'It also moderates soil temperature and suppresses weeds. Examples: straw mulch, dust mulch and plastic mulch.'],
  ['Which crop is best suited to low-rainfall, drought-prone light soils?', ['Pearl millet (bajra)', 'Rice', 'Sugarcane', 'Banana'], 0,
    'Bajra is a C₄ crop that tolerates heat and drought; grown widely in Rajasthan. Sorghum is also drought-hardy ("camel crop").'],
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, q: [
  ['Minimum Support Prices are recommended by the:', ['Commission for Agricultural Costs and Prices (CACP)', 'Food Corporation of India', 'NITI Aayog', 'NABARD'], 0,
    'Set up in 1965 as the Agricultural Prices Commission; renamed CACP in 1985. The Cabinet Committee on Economic Affairs announces MSP for 22 crops (plus FRP for sugarcane).'],
  ['The National Commission on Farmers (M.S. Swaminathan) recommended MSP at:', ['C2 cost + 50%', 'A2 cost + 50%', 'A2 + FL cost only', 'Market price + 10%'], 0,
    'A2 = paid-out costs; A2+FL adds family labour; C2 adds rent and interest on owned land and capital. The government uses 1.5 × (A2+FL).'],
  ['Under PM-KISAN, eligible farmer families receive:', ['₹6,000 per year in three instalments', '₹10,000 per year in two instalments', '₹12,000 per year monthly', '₹5,000 once per crop season'], 0,
    'Launched in February 2019; direct benefit transfer to bank accounts.'],
  ['Farmer premium under PMFBY (2016) for kharif food and oilseed crops is:', ['2% of the sum insured', '1.5% of the sum insured', '5% of the sum insured', 'Nil'], 0,
    'Rabi: 1.5%; annual commercial and horticultural crops: 5%. The rest is paid by the Centre and the state.'],
  ['e-NAM, launched in April 2016, is:', ['A pan-India electronic trading portal linking APMC mandis', 'A crop insurance app', 'A soil testing network', 'A weather forecast service'], 0,
    'Managed by SFAC. It aims for "one nation, one market" with online bidding and payment.'],
  ['NABARD, the apex bank for agriculture and rural development, was set up in:', ['1982', '1969', '1975', '1991'], 0,
    'Set up on the Sivaraman Committee’s recommendation. Regional Rural Banks came in 1975; the Kisan Credit Card in 1998.'],
  ['A scheme launched in 2020 aims to form and promote:', ['10,000 Farmer Producer Organisations (FPOs)', '1,000 cold storages', '100 food parks', '50,000 seed villages'], 0,
    'FPOs aggregate small farmers for input purchase, marketing and bargaining power. Implemented through SFAC, NABARD and NCDC.'],
] },
{ p: 'A1', t: 'Agricultural Extension', w: 2, q: [
  ['The Training and Visit (T&V) system of extension was developed by:', ['Daniel Benor, with World Bank support', 'Everett Rogers', 'Mahatma Gandhi', 'M.S. Swaminathan'], 0,
    'Village extension workers visited contact farmers on a fixed fortnightly schedule and were trained regularly. It was introduced in India in the mid-1970s.'],
  ['The first Krishi Vigyan Kendra (KVK) was set up in 1974 at:', ['Puducherry', 'New Delhi', 'Hyderabad', 'Ludhiana'], 0,
    'Based on the Mohan Singh Mehta Committee (1973). KVKs focus on on-farm testing, frontline demonstrations and vocational training.'],
  ['ATMA (Agricultural Technology Management Agency) works at the level of the:', ['District', 'Village', 'State', 'Nation'], 0,
    'ATMA was piloted under the National Agricultural Technology Project (1998). It is a registered society linking research and extension at district level.'],
  ['In Rogers’ diffusion of innovations, "laggards" make up about:', ['16% of adopters', '2.5% of adopters', '13.5% of adopters', '34% of adopters'], 0,
    'Innovators 2.5%, early adopters 13.5%, early majority 34%, late majority 34%, laggards 16%.'],
  ['The Community Development Programme in India was launched on:', ['2 October 1952', '15 August 1947', '26 January 1950', '2 October 1959'], 0,
    'The block was the unit of development. Its limitations led to the Balwant Rai Mehta Committee (1957) and Panchayati Raj (Nagaur, 2 October 1959).'],
  ['ICAR’s "Lab to Land" programme (1979) aimed to:', ['Transfer improved technology directly to small and marginal farmers and landless labourers', 'Build new laboratories in villages', 'Export farm produce', 'Train scientists abroad'], 0,
    'It was launched in ICAR’s Golden Jubilee year.'],
] },
{ p: 'A1', t: 'Agroforestry & Social Forestry', w: 3, q: [
  ['Growing trees with pasture/fodder and grazing livestock on the same land is:', ['A silvopastoral system', 'An agrisilvicultural system', 'A horti-silvicultural system', 'Taungya'], 0,
    'Agrisilviculture = crops + trees; agrosilvopastoral = crops + trees + livestock (e.g., homegardens).'],
  ['The taungya system originated in:', ['Myanmar (Burma), 1856, under Dietrich Brandis', 'Kerala, 1920', 'Java, 1900', 'Nigeria, 1930'], 0,
    'Farmers raise field crops between young forest-tree rows (e.g., teak) for 2–3 years in return for tending the plantation.'],
  ['India became the first country to adopt a National Agroforestry Policy in:', ['2014', '2006', '1988', '2018'], 0,
    'It was followed by the Sub-Mission on Agroforestry (Har Medh Par Ped) in 2016–17.'],
  ['"Social forestry" was first used as a programme term in India by:', ['The National Commission on Agriculture (1976)', 'The National Forest Policy 1952', 'The Forest Conservation Act 1980', 'The Planning Commission 1951'], 0,
    'Components: farm forestry, extension forestry, reforestation of degraded lands and recreation forestry. Jack Westoby coined the term in 1968.'],
  ['Khejri, the multipurpose tree of the Thar desert, is:', ['*Prosopis cineraria*', '*Prosopis juliflora*', '*Acacia nilotica*', '*Ziziphus mauritiana*'], 0,
    'Leguminous, deep-rooted; fodder (loong), pods (sangri) and it improves crop yields beneath it. It is the state tree of Rajasthan. *P. juliflora* is invasive.'],
  ['The poplar used widely in agroforestry with wheat in Punjab, Haryana and western UP is:', ['*Populus deltoides*', '*Populus ciliata*', '*Populus euphratica*', '*Populus alba*'], 0,
    'A deciduous exotic, so the rabi crop gets winter sunlight. Rotation 6–8 years for plywood and matchwood.'],
  ['The Central Agroforestry Research Institute (ICAR-CAFRI) is at:', ['Jhansi', 'Dehradun', 'Jodhpur', 'Coimbatore'], 0,
    'The Institute of Forest Genetics and Tree Breeding (ICFRE) is at Coimbatore; AFRI (Arid Forest Research Institute) at Jodhpur.'],
  ['*Casuarina equisetifolia* fixes atmospheric nitrogen through symbiosis with:', ['*Frankia* (an actinomycete)', '*Rhizobium*', '*Anabaena*', '*Azotobacter*'], 0,
    'Actinorhizal plants include *Casuarina*, *Alnus*, *Myrica* and *Hippophae*. *Casuarina* is used for coastal shelterbelts and pulpwood.'],
  ['Alley cropping (hedgerow intercropping) typically uses hedges of:', ['*Leucaena leucocephala* or *Gliricidia sepium*', '*Tectona grandis*', '*Pinus roxburghii*', '*Eucalyptus globulus*'], 0,
    'Fast-growing N-fixing shrubs are pruned regularly; loppings serve as mulch/green manure and fodder between crop alleys.'],
] },
{ p: 'A1', t: 'Environment, Organic & Natural Farming', w: 2, q: [
  ['The first Indian state declared fully organic (2016) was:', ['Sikkim', 'Kerala', 'Meghalaya', 'Himachal Pradesh'], 0,
    'Sikkim phased out chemical fertilisers and pesticides. India’s organic certification systems are NPOP (third party, APEDA) and PGS-India (participatory).'],
  ['Zero Budget Natural Farming, based on Jeevamrutha and Beejamrutha, was popularised by:', ['Subhash Palekar', 'Masanobu Fukuoka', 'Albert Howard', 'Rudolf Steiner'], 0,
    'A National Mission on Natural Farming was approved in 2024. Fukuoka wrote *The One-Straw Revolution*; Howard developed Indore composting; Steiner founded biodynamic farming.'],
  ['The earthworm most used for vermicomposting is:', ['*Eisenia fetida*', '*Pheretima posthuma*', '*Lumbricus terrestris*', '*Megascolex* sp.'], 0,
    'An epigeic (surface-dwelling) red worm; *Eudrilus eugeniae* is also used. *Pheretima* and *Lumbricus* live deeper in soil.'],
  ['Flooded rice fields emit methane mainly because of:', ['Methanogenic archaea decomposing organic matter anaerobically', 'Nitrifying bacteria', 'Photorespiration in rice leaves', 'Burning of rice straw only'], 0,
    'Methane escapes largely through aerenchyma of rice plants. AWD, direct seeding and suitable cultivars reduce emissions.'],
  ['The "4 per 1000" initiative (COP21, 2015) aims to:', ['Raise soil organic carbon stocks by 0.4% a year', 'Cut fertiliser use by 4 kg per 1,000 kg of grain', 'Plant 4 trees per 1,000 m²', 'Reduce methane by 4% per decade'], 0,
    'Increasing soil carbon could offset a large share of annual CO₂ emissions and improve soil health and food security.'],
  ['The PUSA decomposer, developed by IARI to curb stubble burning, is a:', ['Microbial (fungal) consortium that speeds up in-situ decomposition of paddy straw', 'Machine that bales straw', 'Chemical defoliant', 'Seed drill for wheat'], 0,
    'Machines such as the Happy Seeder and Super Seeder sow wheat through residue without burning.'],
] }
);
