/* Agriculture Paper II (IFoS Paper VI). Row: [question, options, answerIndex, explanation]. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, q: [
  ['Dwarfing genes (Rht1, Rht2) in Green Revolution wheat came from:', ['Norin 10 (Japan)', 'Dee-geo-woo-gen (Taiwan)', 'Sonora 64 (Mexico)', 'Kalyan Sona (India)'], 0,
    'Norman Borlaug used Norin 10 derivatives at CIMMYT. Rice semi-dwarfing gene sd1 came from Dee-geo-woo-gen (used in IR8).'],
  ['IR8, the "miracle rice" released by IRRI in 1966, owes its semi-dwarf stature to the gene:', ['sd1 from Dee-geo-woo-gen', 'Rht1 from Norin 10', 'Sub1 from FR13A', 'Xa21 from *Oryza longistaminata*'], 0,
    'IR8 = Peta × Dee-geo-woo-gen. Semi-dwarfs respond to fertiliser without lodging.'],
  ['Synthetic varieties are developed in:', ['Cross-pollinated crops by intermating selected lines with good general combining ability', 'Self-pollinated crops by pure-line selection', 'Clonal crops by grafting', 'Apomictic crops only'], 0,
    'They can be advanced by open pollination and farmers can save seed (unlike single-cross hybrids). Composites are made by mixing and intermating varieties.'],
  ['In the three-line hybrid system, the line used to multiply the cytoplasmic male-sterile (A) line is the:', ['B line (maintainer)', 'R line (restorer)', 'C line (tester)', 'F₁ hybrid'], 0,
    'B has the same nuclear genes as A but fertile (normal) cytoplasm. A × R gives the fertile F₁ hybrid.'],
  ['General combining ability (GCA) mainly reflects:', ['Additive gene action', 'Dominance and epistasis', 'Cytoplasmic effects', 'Environmental variance'], 0,
    'Sprague and Tatum (1942). Specific combining ability (SCA) reflects non-additive (dominance, epistatic) gene action.'],
  ['India’s law protecting plant breeders’ and farmers’ rights is the:', ['Protection of Plant Varieties and Farmers’ Rights Act, 2001', 'Seeds Act, 1966', 'Biological Diversity Act, 2002', 'Patents Act, 1970'], 0,
    'A *sui generis* system under TRIPS. Farmers may save, use, exchange and sell farm-saved seed (but not branded seed of a protected variety).'],
  ['Swarna-Sub1 rice carries the Sub1 gene conferring tolerance to:', ['Submergence for about two weeks', 'Salinity', 'Drought', 'Bacterial blight'], 0,
    'Sub1A (from FR13A) keeps the plant quiescent under water. Transferred by marker-assisted backcrossing.'],
  ['Consider the following statements:\n1. Pure-line selection is used mainly in self-pollinated crops.\n2. Mass selection can be used in both self- and cross-pollinated crops.\nWhich is/are correct?', ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], 2,
    'Pure lines are homozygous progeny of one self-fertilised plant. Mass selection picks many plants by phenotype and bulks their seed.'],
] },
{ p: 'A2', t: 'Heterosis, Hybrids & Mutation Breeding', w: 2, q: [
  ['The overdominance hypothesis of heterosis was proposed by:', ['Shull and East', 'Davenport, Bruce and Jones', 'Johannsen', 'Mendel'], 0,
    'Overdominance: the heterozygote (Aa) is superior to both homozygotes. The dominance hypothesis (Davenport 1908, Bruce 1910, Jones 1917) attributes heterosis to masking of harmful recessives.'],
  ['The "father of hybrid rice", who used the wild-abortive (WA) CMS source, is:', ['Yuan Longping', 'Norman Borlaug', 'Gurdev Khush', 'M.S. Swaminathan'], 0,
    'China released hybrid rice in the mid-1970s. Gurdev Khush bred IR36 and IR64 at IRRI.'],
  ['The world’s first commercial cotton hybrid, H-4 (1970), was developed by:', ['C.T. Patel in Gujarat', 'Borlaug in Mexico', 'IRRI', 'CICR, Nagpur'], 0,
    'An intra-hirsutum hybrid bred at the Surat cotton research station. India later developed inter-specific hybrids (e.g., Varalaxmi).'],
  ['Sharbati Sonora wheat was developed by:', ['Mutation of Sonora 64 using radiation', 'Crossing Sonora 64 with rye', 'Anther culture', 'Genetic engineering'], 0,
    'M.S. Swaminathan’s group at IARI selected this amber-grained mutant (1967). Induced-mutation varieties are listed in the FAO/IAEA Mutant Variety Database.'],
  ['Inbreeding depression is most severe in:', ['Naturally cross-pollinated crops such as maize and alfalfa', 'Self-pollinated crops such as wheat and rice', 'Apomictic grasses', 'Clonal crops such as potato only'], 0,
    'Selfing exposes deleterious recessives. Self-pollinated crops are already homozygous and show little depression.'],
  ['Apomixis interests breeders because it could:', ['Fix hybrid vigour so farmers can save hybrid seed', 'Increase genetic variation in every generation', 'Make crops cross-pollinated', 'Eliminate the need for pollination in all crops'], 0,
    'Seeds form without fertilisation, so the F₁ genotype breeds true. Natural apomixis occurs in *Citrus*, mango (nucellar embryos) and many grasses.'],
] },
{ p: 'A2', t: 'Seed Technology', w: 3, q: [
  ['The tag colour of certified seed is:', ['Azure blue', 'Golden yellow', 'White', 'Opal green'], 0,
    'Breeder seed: golden yellow label; foundation: white tag; certified: azure blue tag; truthfully labelled seed: opal green.'],
  ['The correct sequence of seed classes is:', ['Nucleus → Breeder → Foundation → Certified', 'Breeder → Nucleus → Certified → Foundation', 'Foundation → Breeder → Certified → Nucleus', 'Certified → Foundation → Breeder → Nucleus'], 0,
    'Nucleus and breeder seed are produced by the breeder or institute; foundation seed by NSC/SSCs; certified seed is sold to farmers.'],
  ['In the tetrazolium test, living seed tissue turns red because:', ['Dehydrogenases reduce the colourless salt to red formazan', 'Dead cells absorb the dye', 'Chlorophyll reacts with the salt', 'Starch reacts with iodine'], 0,
    '2,3,5-triphenyl tetrazolium chloride. It gives a quick viability estimate (hours instead of days for a germination test).'],
  ['Recalcitrant seeds, which lose viability when dried, include:', ['Mango and cocoa', 'Wheat and rice', 'Tomato and chilli', 'Soybean and groundnut'], 0,
    'Also jackfruit, rubber, litchi, sal (*Shorea robusta*). They cannot be stored in conventional seed banks, so field gene banks and cryopreservation of embryos are used.'],
  ['Harrington’s thumb rules state that seed life doubles for every:', ['1% fall in seed moisture (5–14%) and every 5 °C fall in storage temperature (0–50 °C)', '5% fall in moisture and every 1 °C fall in temperature', '10% fall in moisture only', '10 °C rise in temperature'], 0,
    'Keep orthodox seed dry and cool. Moisture also matters because of insects and fungi above about 12–14%.'],
  ['Stratification breaks seed dormancy by:', ['Moist chilling of seeds for weeks', 'Scratching the hard seed coat', 'Soaking in concentrated sulphuric acid', 'Exposure to far-red light'], 0,
    'Stratification suits embryo dormancy (apple, peach, many temperate trees). Hard seed coats (legumes, teak) need scarification (mechanical, acid or hot water).'],
  ['India’s seed quality regulation is primarily under the:', ['Seeds Act, 1966 and Seeds Rules, 1968', 'Insecticides Act, 1968', 'Essential Commodities Act, 1955 only', 'Plant Quarantine Order, 2003 only'], 0,
    'The Seeds (Control) Order, 1983 was issued under the Essential Commodities Act. Certification is voluntary; labelling is compulsory for notified kinds.'],
  ['The grow-out test (GOT) is used to assess:', ['Genetic purity of a seed lot (especially hybrids)', 'Seed moisture content', 'Seed vigour under cold stress', 'Seed-borne fungi'], 0,
    'Plants are grown to maturity to count off-types and selfed plants. DNA markers (SSR) now provide faster purity testing.'],
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, q: [
  ['Harvest index is:', ['Economic yield ÷ biological yield', 'Grain yield ÷ straw yield', 'Leaf area ÷ ground area', 'Dry matter ÷ days to maturity'], 0,
    'Green Revolution varieties raised harvest index (≈0.45–0.5 in modern wheat and rice) more than total biomass. Leaf area ÷ ground area is LAI.'],
  ['Maleic hydrazide is used to:', ['Inhibit sprouting of stored onion and potato', 'Induce flowering in pineapple', 'Promote rooting of cuttings', 'Break seed dormancy'], 0,
    'Sprayed pre-harvest. Pineapple flowering: ethephon or NAA; rooting: IBA/NAA; dormancy: GA₃ or thiourea.'],
  ['Premature (pre-harvest) fruit drop in mango and apple is reduced by spraying:', ['NAA (an auxin)', 'ABA', 'Ethephon', 'Maleic hydrazide'], 0,
    'Auxins delay formation of the abscission layer. Ethephon promotes abscission and ripening.'],
  ['Chlormequat chloride (CCC, cycocel) is used in cereals mainly to:', ['Shorten the stem and reduce lodging', 'Increase grain protein', 'Induce male sterility', 'Hasten maturity by ripening'], 0,
    'It inhibits gibberellin biosynthesis. Paclobutrazol is another GA inhibitor (used in mango to induce regular flowering).'],
  ['In cereals the flag leaf is important because it:', ['Supplies a large share of the photosynthates for grain filling', 'Stores water for drought', 'Protects the ear from birds', 'Fixes nitrogen'], 0,
    'The ear, flag leaf and upper leaves are the main "source" during grain filling; grains are the "sink".'],
  ['The optimum leaf area index (LAI) is the LAI at which:', ['Crop growth rate is at its maximum', 'All leaves are fully shaded', 'Leaf senescence begins', 'Transpiration is zero'], 0,
    'Beyond it, lower leaves are shaded below compensation point and respiration losses rise (Watson; Donald).'],
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 3, q: [
  ['Amrapali mango is a cross of:', ['Dashehari × Neelum', 'Alphonso × Neelum', 'Langra × Dashehari', 'Neelum × Alphonso'], 0,
    'IARI, 1978: dwarf, regular bearing, suitable for high-density planting. Mallika = Neelum × Dashehari.'],
  ['Spongy tissue is a physiological disorder of the mango variety:', ['Alphonso', 'Dashehari', 'Langra', 'Totapuri'], 0,
    'Non-edible, sour, spongy pulp near the stone, linked to heat and convection during maturity. Mango malformation is caused by *Fusarium mangiferae*.'],
  ['Stone (epicotyl) grafting is a common commercial propagation method for:', ['Mango', 'Guava', 'Banana', 'Grape'], 0,
    'Mango: veneer, softwood and stone grafting. Guava: air layering and stooling. Citrus: T-budding. Banana: suckers and tissue culture.'],
  ['Malling–Merton (MM) series are well-known rootstocks of:', ['Apple', 'Mango', 'Citrus', 'Grape'], 0,
    'Examples: MM 106, MM 111 (semi-vigorous), M 9 (dwarfing). Rootstocks control vigour, precocity and resistance to woolly aphid.'],
  ['Blossom-end rot of tomato is caused by deficiency of:', ['Calcium', 'Boron', 'Iron', 'Magnesium'], 0,
    'Often induced by irregular watering. Calcium moves in the xylem with transpiration, so fruits receive little.'],
  ['The seed plot technique for healthy potato seed production in the plains was developed by:', ['Pushkarnath (CPRI)', 'M.S. Swaminathan', 'B.P. Pal', 'Yuan Longping'], 0,
    'Seed crops are grown in the low-aphid period (October–January) with haulm cutting before aphid build-up. CPRI is at Shimla.'],
  ['Panama wilt of banana is caused by:', ['*Fusarium oxysporum* f. sp. *cubense*', 'Banana bunchy top virus', '*Ralstonia solanacearum*', '*Mycosphaerella musicola*'], 0,
    'Tropical Race 4 threatens Cavendish bananas. Bunchy top virus is spread by the aphid *Pentalonia nigronervosa*; *Mycosphaerella* causes Sigatoka leaf spot.'],
  ['Which is a non-climacteric fruit?', ['Grape', 'Mango', 'Banana', 'Tomato'], 0,
    'Non-climacteric: citrus, grape, pineapple, strawberry, litchi — no rise in respiration and ethylene at ripening, so they must be harvested ripe.'],
] },
{ p: 'A2', t: 'Post-harvest & Food Processing', w: 2, q: [
  ['1-Methylcyclopropene (1-MCP) extends shelf life of fruits by:', ['Blocking ethylene receptors', 'Releasing ethylene slowly', 'Killing surface microbes', 'Removing CO₂'], 0,
    'Used for apples, bananas and flowers. Ethylene absorbers (KMnO₄ sachets) remove ethylene instead.'],
  ['The zero-energy cool chamber (Pusa) keeps produce fresh by:', ['Evaporative cooling through wet brick walls and sand', 'Electric refrigeration', 'Irradiation', 'Vacuum packing'], 0,
    'It lowers temperature by about 10–15 °C and keeps humidity above 90% — cheap on-farm storage.'],
  ['Controlled-atmosphere (CA) storage generally maintains:', ['Low O₂ and raised CO₂ at low temperature', 'High O₂ and low CO₂', 'Pure nitrogen at room temperature', 'High ethylene'], 0,
    'It slows respiration and ripening. Common for apples (e.g., 2–3% O₂, 1–5% CO₂).'],
  ['The international "Radura" logo on food packaging indicates that the food was:', ['Irradiated', 'Organically certified', 'Genetically modified', 'Fair-trade certified'], 0,
    'Low-dose gamma irradiation inhibits sprouting in onion and potato and disinfests grain; higher doses kill pathogens.'],
  ['Operation Greens (2018) initially targeted:', ['Tomato, onion and potato (TOP)', 'Tea, oilseeds and pulses', 'Turmeric, onion and pepper', 'Tomato, okra and peas'], 0,
    'Aim: stabilise prices and cut post-harvest loss; it was later extended to more perishables.'],
  ['High-temperature short-time (HTST) pasteurisation of milk is:', ['72 °C for 15 seconds', '63 °C for 30 seconds', '100 °C for 5 minutes', '135 °C for 2 seconds'], 0,
    'The low-temperature long-time (LTLT) method is 63 °C for 30 minutes; UHT is about 135–140 °C for 2–4 seconds.'],
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, q: [
  ['The relation between Economic Threshold Level (ETL) and Economic Injury Level (EIL) is:', ['ETL is set below EIL so control starts before loss becomes economic', 'ETL is always above EIL', 'They are always equal', 'ETL applies only to diseases'], 0,
    'EIL: the lowest pest density causing damage equal to the cost of control. ETL (action threshold) gives time for control to act.'],
  ['*Trichogramma chilonis* is:', ['An egg parasitoid used against borers and bollworms', 'A predator of aphids', 'A viral biopesticide', 'A fungus infecting whiteflies'], 0,
    'Released as parasitised *Corcyra* egg cards (Trichocards). *Chrysoperla* (green lacewing) is an aphid predator.'],
  ['HaNPV is a biopesticide used against:', ['*Helicoverpa armigera*', '*Spodoptera litura*', 'Rice brown planthopper', 'White grubs'], 0,
    'A nuclear polyhedrosis virus specific to *Helicoverpa*. SlNPV is used against *Spodoptera litura*.'],
  ['Gossyplure is the sex pheromone used against:', ['Pink bollworm of cotton', 'Rice stem borer', 'Fruit fly', 'Diamondback moth'], 0,
    'Pink bollworm (*Pectinophora gossypiella*) became resistant to Bt cotton; pheromone mating disruption (PB-knot/rope) and early crop termination help.'],
  ['"Hopper burn" in rice is caused by:', ['Brown planthopper (*Nilaparvata lugens*)', 'Green leafhopper', 'Rice gall midge', 'Rice hispa'], 0,
    'Circular patches of dried plants. Resurgence occurs after synthetic pyrethroid sprays that kill natural enemies.'],
  ['The fall armyworm (*Spodoptera frugiperda*), which invaded India in 2018, mainly attacks:', ['Maize', 'Wheat', 'Cotton', 'Mustard'], 0,
    'First reported in Karnataka. Larvae have an inverted-Y mark on the head and four dots in a square on the eighth abdominal segment.'],
  ['Organophosphate and carbamate insecticides act by:', ['Inhibiting acetylcholinesterase', 'Blocking sodium channels', 'Inhibiting chitin synthesis', 'Binding nicotinic receptors as agonists'], 0,
    'Pyrethroids keep sodium channels open; neonicotinoids (imidacloprid) act on nicotinic acetylcholine receptors; IGRs such as diflubenzuron inhibit chitin synthesis.'],
  ['The Locust Warning Organisation of India is headquartered at:', ['Jodhpur', 'Bikaner', 'Faridabad', 'Hyderabad'], 0,
    'Under the Directorate of Plant Protection, Quarantine & Storage (Faridabad). The desert locust (*Schistocerca gregaria*) caused a major outbreak in 2019–20.'],
  ['Pesticide registration in India is done by the Central Insecticides Board and Registration Committee under the:', ['Insecticides Act, 1968', 'Environment (Protection) Act, 1986', 'Seeds Act, 1966', 'Food Safety and Standards Act, 2006'], 0,
    'The Act followed the 1958 Kerala food-poisoning tragedy (parathion-contaminated wheat flour).'],
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, q: [
  ['Molya disease of wheat and barley in Rajasthan is caused by:', ['Cereal cyst nematode *Heterodera avenae*', 'Root-knot nematode *Meloidogyne incognita*', 'Ear-cockle nematode *Anguina tritici*', '*Fusarium* wilt'], 0,
    'Patchy stunting and yellowing. Managed by summer ploughing, rotation with non-cereals and resistant varieties (e.g., Raj MR 1 barley).'],
  ['Tundu (yellow ear rot) of wheat results from the association of *Anguina tritici* with:', ['The bacterium *Rathayibacter* (*Clavibacter*) *tritici*', 'The fungus *Tilletia indica*', 'Wheat streak mosaic virus', '*Puccinia striiformis*'], 0,
    'Galls (cockles) mixed with seed spread the nematode; sieving and brine flotation of seed remove them.'],
  ['*Trichoderma* species are used as biocontrol agents mainly through:', ['Mycoparasitism, antibiosis and competition against soil-borne pathogens', 'Nitrogen fixation', 'Killing insects by toxins', 'Producing plant hormones only'], 0,
    'Used as seed and soil treatment against *Rhizoctonia*, *Pythium*, *Fusarium* and *Sclerotium*. *Pseudomonas fluorescens* is a bacterial biocontrol agent.'],
  ['Improved Samba Mahsuri rice carries resistance genes (Xa21, xa13, xa5) against:', ['Bacterial leaf blight', 'Blast', 'Brown planthopper', 'Sheath blight'], 0,
    'Developed by ICAR-IIRR and CCMB through marker-assisted backcrossing. Bacterial blight (*Xanthomonas oryzae* pv. *oryzae*) shows a "kresek" wilting phase.'],
  ['Karnal bunt of wheat, a quarantine concern for exports, is caused by:', ['*Tilletia (Neovossia) indica*', '*Ustilago tritici*', '*Puccinia recondita*', '*Urocystis agropyri*'], 0,
    'Partial bunt: grains partly converted to black, fishy-smelling spore masses. *Urocystis agropyri* causes flag smut.'],
  ['Yellow vein mosaic of okra (bhindi) is transmitted by:', ['Whitefly (*Bemisia tabaci*)', 'Aphids', 'Leafhoppers', 'Mites'], 0,
    'A begomovirus. Whiteflies also spread cotton leaf curl and mungbean yellow mosaic. Resistant varieties: Arka Anamika, Parbhani Kranti.'],
  ['Wheat blast, first reported in South Asia in Bangladesh in 2016, is caused by:', ['*Magnaporthe oryzae* pathotype *Triticum*', '*Puccinia graminis*', '*Blumeria graminis*', '*Bipolaris sorokiniana*'], 0,
    'It came from South America. India responded with a wheat-free zone along the border districts of West Bengal.'],
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, q: [
  ['The National Food Security Act, 2013 covers up to:', ['75% of the rural and 50% of the urban population', '50% of the rural and 75% of the urban population', '100% of the population', 'Only Below Poverty Line households'], 0,
    'Priority households get 5 kg grain per person per month; Antyodaya households 35 kg per household. Free grain continues under PMGKAY for five years from January 2024.'],
  ['Dhanashakti, a biofortified variety released in India, is a high-iron variety of:', ['Pearl millet', 'Rice', 'Wheat', 'Finger millet'], 0,
    'Developed by ICRISAT. Other examples: zinc-rich rice DRR Dhan 45, QPM maize, iron-rich lentil.'],
  ['Quality Protein Maize (QPM) has more lysine and tryptophan because of the gene:', ['opaque-2', 'waxy', 'sugary-1', 'shrunken-2'], 0,
    'Mertz and colleagues (1964) found opaque-2 raises lysine. Modifier genes restore hard endosperm in QPM.'],
  ['Cereal proteins are generally deficient in:', ['Lysine', 'Methionine', 'Cysteine', 'Leucine'], 0,
    'Pulses are rich in lysine but poor in sulphur amino acids (methionine), so cereal + pulse meals are complementary.'],
  ['Neurolathyrism is caused by eating large amounts of:', ['*Lathyrus sativus* (khesari dal) containing ODAP (BOAA)', 'Groundnut with aflatoxin', 'Mustard oil with argemone', 'Maize deficient in niacin'], 0,
    'Spastic paralysis of the legs. Low-ODAP varieties (e.g., Ratan, Prateek) have been developed. Argemone contamination causes epidemic dropsy.'],
  ['The Mid-Day Meal scheme was renamed in 2021 as:', ['PM POSHAN', 'POSHAN Abhiyaan', 'Anna Bhagya', 'Samagra Shiksha'], 0,
    'PM POSHAN provides hot cooked meals in government and aided schools. POSHAN Abhiyaan (2018) is the national nutrition mission.'],
] },
{ p: 'A2', t: 'Plantation, Spice & Medicinal Crops', w: 1, q: [
  ['India’s largest coffee-producing state is:', ['Karnataka', 'Kerala', 'Tamil Nadu', 'Andhra Pradesh'], 0,
    'Karnataka produces about 70% (Kodagu, Chikmagalur, Hassan). The Coffee Board is at Bengaluru.'],
  ['Saffron is obtained from the dried ____ of *Crocus sativus*.', ['Stigmas', 'Petals', 'Anthers', 'Seeds'], 0,
    'Pampore (Kashmir) is the centre of Indian saffron; Kashmir saffron has a GI tag.'],
  ['The "Queen of Spices" is:', ['Small cardamom (*Elettaria cardamomum*)', 'Black pepper', 'Clove', 'Turmeric'], 0,
    'Black pepper (*Piper nigrum*) is the "King of Spices". The Spices Board is at Kochi.'],
  ['The Rubber Board of India is headquartered at:', ['Kottayam', 'Kochi', 'Guwahati', 'Agartala'], 0,
    'Kerala has most of India’s rubber area; Tripura is the second-largest producer.'],
  ['Assam tea is derived from:', ['*Camellia sinensis* var. *assamica*', '*Camellia japonica*', '*Coffea arabica*', '*Ilex paraguariensis*'], 0,
    'The Tea Board is at Kolkata. *Ilex paraguariensis* is yerba mate.'],
] }
);
