/* Botany Paper II (IFoS Paper IV). Row: [question, options, answerIndex, explanation]. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B2', t: 'Cell Biology', w: 2, q: [
  ['The fluid mosaic model of the plasma membrane was proposed by:', ['Singer and Nicolson (1972)', 'Danielli and Davson (1935)', 'Robertson (1959)', 'Gorter and Grendel (1925)'], 0,
    'Proteins float in a fluid lipid bilayer. Danielli–Davson proposed the protein–lipid–protein "sandwich"; Robertson the unit-membrane concept.'],
  ['Crossing over between non-sister chromatids takes place during:', ['Pachytene', 'Leptotene', 'Zygotene', 'Diakinesis'], 0,
    'Leptotene: condensation; Zygotene: synapsis and synaptonemal complex; Pachytene: crossing over; Diplotene: chiasmata visible; Diakinesis: terminalisation.'],
  ['The synaptonemal complex forms during:', ['Zygotene', 'Pachytene', 'Diplotene', 'Metaphase I'], 0,
    'It is a tripartite protein ladder that holds homologues together during synapsis. It dissolves in diplotene.'],
  ['Ribosomes of chloroplasts and mitochondria are of the type:', ['70S', '80S', '60S', '90S'], 0,
    'Prokaryote-type 70S (50S + 30S) ribosomes support the endosymbiotic origin of these organelles. Cytoplasmic eukaryotic ribosomes are 80S (60S + 40S).'],
  ['The glyoxylate cycle, which converts stored fats to sugars in germinating castor seeds, occurs in:', ['Glyoxysomes', 'Peroxisomes of leaves', 'Lysosomes', 'Golgi bodies'], 0,
    'Key enzymes: isocitrate lyase and malate synthase. Leaf peroxisomes take part in photorespiration.'],
  ['Balbiani rings (chromosome puffs) are seen on:', ['Polytene chromosomes', 'Lampbrush chromosomes', 'B-chromosomes', 'Sex chromosomes of plants'], 0,
    'Polytene chromosomes (salivary glands of *Drosophila*, *Chironomus*) are sites of active transcription. Lampbrush chromosomes are found in diplotene oocytes.'],
  ['Colchicine induces polyploidy by:', ['Binding tubulin and preventing spindle formation', 'Inhibiting DNA replication', 'Breaking chromosomes', 'Blocking cytokinesis at the cell plate only'], 0,
    'Chromosomes replicate but do not separate (C-mitosis), doubling the number. Colchicine comes from *Colchicum autumnale*.'],
  ['The endosymbiotic theory for the origin of mitochondria and plastids was popularised by:', ['Lynn Margulis', 'Robert Hooke', 'Rudolf Virchow', 'Christian de Duve'], 0,
    'Evidence: circular DNA, 70S ribosomes, double membranes, division by fission. De Duve discovered lysosomes and peroxisomes.'],
] },
{ p: 'B2', t: 'Genetics', w: 3, q: [
  ['A dihybrid test cross (AaBb × aabb) with independent assortment gives the phenotypic ratio:', ['1 : 1 : 1 : 1', '9 : 3 : 3 : 1', '3 : 1', '1 : 2 : 1'], 0,
    'The test cross reveals the gametes of the heterozygote directly. Linkage makes parental classes exceed 25% each.'],
  ['Complementary gene action (9 : 7) was demonstrated in sweet-pea flower colour by:', ['Bateson and Punnett', 'T.H. Morgan', 'Nilsson-Ehle', 'Correns'], 0,
    'Two dominant genes (C and P) are both needed for purple colour. Nilsson-Ehle showed polygenic inheritance of wheat kernel colour.'],
  ['An F₂ ratio of 15 : 1 indicates:', ['Duplicate dominant genes', 'Recessive epistasis', 'Complementary genes', 'Inhibitory genes'], 0,
    'Example: triangular versus ovoid capsule in *Capsella*. 9 : 3 : 4 = recessive epistasis; 13 : 3 = inhibitory gene; 12 : 3 : 1 = dominant epistasis.'],
  ['The 12 : 3 : 1 ratio for fruit colour in summer squash is an example of:', ['Dominant epistasis', 'Recessive epistasis', 'Duplicate recessive genes', 'Incomplete dominance'], 0,
    'The dominant W (white) masks the Y/y (yellow/green) locus: 12 white, 3 yellow, 1 green.'],
  ['The first genetic linkage map was constructed by:', ['A.H. Sturtevant (1913)', 'T.H. Morgan (1910)', 'C.B. Bridges (1916)', 'Barbara McClintock (1931)'], 0,
    'Sturtevant, Morgan’s student, mapped *Drosophila* X-chromosome genes. 1% recombination = 1 map unit = 1 centiMorgan.'],
  ['Plastid (cytoplasmic) inheritance of leaf variegation was first shown by Correns in:', ['*Mirabilis jalapa*', '*Pisum sativum*', '*Oenothera lamarckiana*', '*Zea mays*'], 0,
    'The progeny resembled the maternal branch regardless of the pollen source, showing maternal inheritance of plastids.'],
  ['The 1970 Southern corn leaf blight epidemic in the USA was linked to widespread use of:', ['Texas (T) cytoplasmic male-sterile cytoplasm', 'Opaque-2 maize', 'Open-pollinated composites', 'Bt maize'], 0,
    'T-cytoplasm was highly susceptible to *Bipolaris maydis* race T. It is the classic lesson against genetic uniformity.'],
  ['Bread wheat (*Triticum aestivum*) is:', ['An allohexaploid, AABBDD (2n = 6x = 42)', 'An autotetraploid, AAAA (2n = 28)', 'A diploid, AA (2n = 14)', 'An allotetraploid, AABB (2n = 28)'], 0,
    'The D genome came from *Aegilops tauschii*. Durum wheat is AABB (2n = 28). Triticale = wheat × rye.'],
  ['The first man-made intergeneric allopolyploid, *Raphanobrassica*, was produced by:', ['G.D. Karpechenko (1927)', 'Blakeslee (1937)', 'Rimpau (1891)', 'Kihara (1930)'], 0,
    'Radish × cabbage (both 2n = 18). The amphidiploid (2n = 36) was fertile but combined cabbage roots with radish leaves.'],
  ['A nullisomic individual has the chromosome number:', ['2n − 2', '2n − 1', '2n + 1', '2n + 2'], 0,
    'Nullisomic = one homologous pair missing. Monosomic 2n − 1; trisomic 2n + 1; tetrasomic 2n + 2. Sears produced a complete nullisomic series in wheat.'],
  ['If the frequency of a recessive allele is 0.3 in a population in Hardy–Weinberg equilibrium, the frequency of heterozygotes is:', ['0.42', '0.09', '0.49', '0.21'], 0,
    'p = 0.7, q = 0.3 → 2pq = 2 × 0.7 × 0.3 = 0.42. q² = 0.09 (recessive homozygotes), p² = 0.49.'],
  ['Acridine dyes such as proflavin mainly cause:', ['Frameshift mutations', 'Transitions only', 'Thymine dimers', 'Chromosome doubling'], 0,
    'Acridines intercalate between bases, causing insertions or deletions. Base analogues (5-BU) and EMS cause transitions; UV forms thymine dimers.'],
  ['"Mutations" described by de Vries in *Oenothera lamarckiana* were later shown to be largely due to:', ['Reciprocal translocations and complex heterozygosity', 'Point mutations in single genes', 'Polyploidy alone', 'Plastid mutations'], 0,
    '*Oenothera* forms rings of chromosomes at meiosis (Renner complexes); balanced lethals keep permanent heterozygosity.'],
] },
{ p: 'B2', t: 'Molecular Biology', w: 3, q: [
  ['Semi-conservative DNA replication was proved by:', ['Meselson and Stahl (1958) using ¹⁵N in *E. coli*', 'Hershey and Chase (1952)', 'Avery, MacLeod and McCarty (1944)', 'Watson and Crick (1953)'], 0,
    'After one generation in ¹⁴N, DNA was hybrid density; after two, half hybrid and half light. Hershey–Chase showed DNA is the genetic material of phage.'],
  ['Which of the following is NOT a stop codon?', ['AUG', 'UAA', 'UAG', 'UGA'], 0,
    'AUG is the start codon (methionine). There are 64 codons: 61 sense codons and 3 stop codons (amber UAG, ochre UAA, opal UGA).'],
  ['The wobble hypothesis, explaining how one tRNA reads more than one codon, was proposed by:', ['Francis Crick (1966)', 'Nirenberg and Matthaei (1961)', 'Har Gobind Khorana (1966)', 'George Gamow (1954)'], 0,
    'Pairing at the 3rd codon base (5′ base of the anticodon) is flexible, e.g., inosine pairs with U, C or A.'],
  ['The *lac* operon of *E. coli* is an example of:', ['An inducible system under negative control', 'A repressible system under positive control', 'A constitutive system', 'A repressible system for amino-acid synthesis'], 0,
    'Jacob and Monod (1961). The repressor binds the operator; allolactose (inducer) inactivates the repressor. The *trp* operon is repressible.'],
  ['In eukaryotes, mRNA is transcribed by:', ['RNA polymerase II', 'RNA polymerase I', 'RNA polymerase III', 'Primase'], 0,
    'Pol I: 28S, 18S and 5.8S rRNA; Pol II: mRNA (and most snRNA); Pol III: tRNA and 5S rRNA.'],
  ['The restriction enzyme *Eco*RI recognises:', ['5′-GAATTC-3′ and leaves sticky ends', '5′-GGATCC-3′ and leaves blunt ends', '5′-AAGCTT-3′ and leaves blunt ends', '5′-CCCGGG-3′ and leaves sticky ends'], 0,
    'It cuts between G and A on each strand, leaving 5′ AATT overhangs. GGATCC = *Bam*HI; AAGCTT = *Hin*dIII; CCCGGG = *Sma*I (blunt).'],
  ['The heat-stable DNA polymerase used in PCR comes from:', ['*Thermus aquaticus*', '*Escherichia coli*', '*Bacillus subtilis*', '*Agrobacterium tumefaciens*'], 0,
    'PCR was invented by Kary Mullis (1983). Each cycle: denaturation (~94 °C), annealing (~55–65 °C), extension (72 °C).'],
  ['Split genes (introns) were discovered by:', ['Phillip Sharp and Richard Roberts (1977)', 'Jacob and Monod', 'Temin and Baltimore', 'Sanger and Gilbert'], 0,
    'Introns are removed by the spliceosome (snRNPs). Temin and Baltimore discovered reverse transcriptase (1970).'],
  ['Transposable elements (Ac–Ds) were discovered in maize by:', ['Barbara McClintock', 'Rosalind Franklin', 'Thomas Morgan', 'Beadle and Tatum'], 0,
    'She explained variegated kernels by "jumping genes"; Nobel Prize 1983. Beadle and Tatum gave the one gene–one enzyme idea (*Neurospora*).'],
  ['Okazaki fragments are:', ['Short DNA pieces made discontinuously on the lagging strand', 'RNA primers on the leading strand', 'Introns removed from pre-mRNA', 'Telomere repeats'], 0,
    'DNA polymerase works only 5′→3′, so the lagging strand is made in fragments, which DNA ligase joins.'],
] },
{ p: 'B2', t: 'Evolution', w: 1, q: [
  ['"Inheritance of acquired characters" was the central idea of:', ['Lamarck — *Philosophie Zoologique* (1809)', 'Darwin — *On the Origin of Species* (1859)', 'de Vries — mutation theory (1901)', 'Weismann — germ plasm theory'], 0,
    'Weismann’s germ plasm theory (he cut tails of mice over generations) argued against Lamarckism.'],
  ['Industrial melanism in the peppered moth (*Biston betularia*) illustrates:', ['Directional natural selection', 'Genetic drift', 'Stabilising selection', 'Founder effect'], 0,
    'Soot-darkened trees favoured dark moths against bird predation; after the Clean Air Acts, pale forms recovered.'],
  ['A random change in allele frequencies, strongest in small populations, is called:', ['Genetic drift (Sewall Wright effect)', 'Gene flow', 'Natural selection', 'Hardy–Weinberg equilibrium'], 0,
    'The founder effect and bottleneck effect are special cases of drift.'],
  ['The Miller–Urey experiment (1953) produced amino acids from:', ['CH₄, NH₃, H₂ and water vapour with electric sparks', 'O₂, N₂ and CO₂ under UV light', 'Clay and sea water heated to 100 °C', 'Nucleotides and lipids'], 0,
    'It simulated a reducing primitive atmosphere. This supports the Oparin–Haldane idea of chemical evolution.'],
] },
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 2, q: [
  ['The pure-line theory was proposed by W. Johannsen (1903) using:', ['*Phaseolus vulgaris* (beans)', '*Pisum sativum*', '*Zea mays*', '*Triticum aestivum*'], 0,
    'Selection within a pure line (progeny of a single self-fertilised homozygote) is ineffective because the variation is environmental.'],
  ['The term "heterosis" was coined by:', ['G.H. Shull (1914)', 'Charles Darwin (1876)', 'E.M. East (1908)', 'D.F. Jones (1917)'], 0,
    'Jones suggested double-cross hybrids in maize (1917). Darwin had noted hybrid vigour earlier.'],
  ['The backcross method is best suited for:', ['Transferring one or a few oligogenic traits (e.g., disease resistance) into a superior variety', 'Improving polygenic yield in populations', 'Creating synthetic varieties', 'Developing clones in vegetatively propagated crops'], 0,
    'Repeated crossing to the recurrent parent recovers its genome (about 99% after six backcrosses), with selection for the donor trait.'],
  ['The coefficient of variation is:', ['(Standard deviation ÷ mean) × 100', 'Variance ÷ mean', 'Mean ÷ standard deviation', 'Standard error × √n'], 0,
    'CV is unit-free, so it compares variability between traits or experiments. A low CV in field trials indicates good experimental precision.'],
  ['For a χ² test of a 9 : 3 : 3 : 1 dihybrid ratio, the degrees of freedom are:', ['3', '4', '1', '2'], 0,
    'df = number of classes − 1 = 4 − 1 = 3. At 5% significance the table value is 7.815.'],
  ['The *t*-test was developed by W.S. Gosset, who published under the pen name:', ['Student', 'Fisher', 'Pearson', 'Snedecor'], 0,
    'Gosset worked at the Guinness brewery. R.A. Fisher developed ANOVA; the F-distribution is named after him (Snedecor).'],
  ['Broad-sense heritability is the ratio of:', ['Genotypic variance to phenotypic variance', 'Additive variance to genotypic variance', 'Environmental variance to phenotypic variance', 'Dominance variance to additive variance'], 0,
    'H² = VG/VP. Narrow-sense heritability h² = VA/VP predicts the response to selection (R = h²S).'],
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 3, q: [
  ['The first stable product of CO₂ fixation in C₄ plants is:', ['Oxaloacetic acid (4-carbon)', '3-Phosphoglyceric acid', 'Malic acid', 'Ribulose bisphosphate'], 0,
    'Hatch and Slack (1966). PEP carboxylase in mesophyll forms OAA; it is converted to malate/aspartate and decarboxylated in bundle-sheath cells (Kranz anatomy) where Rubisco works.'],
  ['In photorespiration, CO₂ is released in the:', ['Mitochondria (glycine → serine)', 'Chloroplast stroma', 'Peroxisome', 'Cytosol'], 0,
    'C₂ cycle: chloroplast (phosphoglycolate) → peroxisome (glycolate → glycine) → mitochondria (2 glycine → serine + CO₂ + NH₃).'],
  ['The oxygen-evolving complex of Photosystem II requires:', ['Manganese, with calcium and chloride', 'Iron and sulphur only', 'Magnesium and copper', 'Molybdenum and nickel'], 0,
    'A Mn₄CaO₅ cluster splits water. PS II reaction centre is P680; PS I is P700.'],
  ['The "red drop" and the Emerson enhancement effect led to the concept of:', ['Two photosystems working in series', 'Cyclic photophosphorylation only', 'Chemiosmosis', 'C₄ photosynthesis'], 0,
    'Quantum yield fell beyond 680 nm but rose when shorter wavelengths were added with far-red light. This led to the Z-scheme (Hill and Bendall, 1960).'],
  ['Making one glucose molecule through the Calvin cycle requires:', ['18 ATP and 12 NADPH', '12 ATP and 18 NADPH', '6 ATP and 6 NADPH', '30 ATP and 12 NADPH'], 0,
    'Per CO₂: 3 ATP + 2 NADPH. ×6 gives 18 ATP + 12 NADPH. C₄ plants need extra ATP (about 30 per glucose) for PEP regeneration.'],
  ['In CAM plants such as pineapple and *Opuntia*:', ['Stomata open at night and CO₂ is stored as malic acid', 'Kranz anatomy separates PEP carboxylase and Rubisco in space', 'Photorespiration is higher than in C₃ plants', 'Rubisco is absent'], 0,
    'CAM separates the two carboxylations in time (night and day), giving very high water-use efficiency in succulents (Crassulaceae).'],
  ['The respiratory quotient (RQ) of fats such as tripalmitin is about:', ['0.7', '1.0', '1.3', '4.0'], 0,
    'RQ = CO₂ released ÷ O₂ consumed. Carbohydrates 1.0; fats about 0.7; proteins about 0.8–0.9; organic acids >1 (malic acid 1.33, oxalic acid 4).'],
  ['Cyanide-resistant respiration via the alternative oxidase generates heat in the inflorescence of:', ['Aroids such as *Arum* and *Symplocarpus*', 'Grasses', 'Legumes', 'Cacti'], 0,
    'Thermogenesis volatilises odours that attract pollinators. The alternative oxidase bypasses complexes III and IV, so less ATP and more heat are produced.'],
  ['The chemiosmotic hypothesis of ATP synthesis was proposed by:', ['Peter Mitchell (1961)', 'Hans Krebs (1937)', 'Melvin Calvin (1950s)', 'Daniel Arnon (1954)'], 0,
    'A proton gradient across the membrane drives ATP synthase (CF₀–CF₁ in chloroplasts). Arnon discovered photophosphorylation.'],
] },
{ p: 'B2', t: 'Water Relations & Mineral Nutrition', w: 2, q: [
  ['The cohesion–tension theory of the ascent of sap was proposed by:', ['Dixon and Joly (1894)', 'J.C. Bose (1923)', 'Godlewski (1884)', 'Strasburger (1891)'], 0,
    'Transpiration pull + cohesion of water molecules + adhesion to xylem walls. Bose proposed the pulsation theory (a vital theory).'],
  ['Opening of stomata is associated with:', ['Active K⁺ uptake into guard cells, lowering their water potential', 'Efflux of K⁺ from guard cells', 'Conversion of sugars to starch in guard cells in daylight', 'A rise in ABA in guard cells'], 0,
    'Blue light activates H⁺-ATPase → K⁺ influx with Cl⁻/malate → water entry → turgid guard cells. ABA causes K⁺ efflux and closure.'],
  ['The criteria of essentiality of plant nutrients were laid down by:', ['Arnon and Stout (1939)', 'Liebig (1840)', 'Sachs and Knop (1860)', 'Hoagland (1938)'], 0,
    'The element must be needed to complete the life cycle, cannot be replaced by another element, and must be directly involved in metabolism.'],
  ['Khaira disease of rice is caused by deficiency of:', ['Zinc', 'Iron', 'Boron', 'Manganese'], 0,
    'Reported by Y.L. Nene (1966) at Pantnagar. Rusty brown spots on leaves of calcareous, waterlogged soils. Corrected with zinc sulphate.'],
  ['Whiptail of cauliflower results from deficiency of:', ['Molybdenum', 'Boron', 'Calcium', 'Copper'], 0,
    'Mo is part of nitrate reductase and nitrogenase. Boron deficiency causes browning/hollow stem in cauliflower and heart rot in sugar beet.'],
  ['Deficiency symptoms appear first on older leaves when the deficient element is phloem-mobile, such as:', ['Nitrogen', 'Calcium', 'Iron', 'Boron'], 0,
    'Mobile: N, P, K, Mg (move from old to young leaves). Immobile: Ca, Fe, B, S, Cu, so symptoms start in young leaves.'],
  ['Nickel is essential to plants as a component of:', ['Urease', 'Nitrate reductase', 'Carbonic anhydrase', 'Cytochrome oxidase'], 0,
    'Without Ni, urea accumulates to toxic levels (leaf-tip necrosis). Zinc is in carbonic anhydrase; copper in cytochrome oxidase and plastocyanin.'],
  ['Water potential of pure water at atmospheric pressure is:', ['Zero', '−1 MPa', '+1 MPa', '−15 bar'], 0,
    'Ψw = Ψs + Ψp (+ Ψm). Solutes make Ψ negative; water moves from higher (less negative) to lower Ψ.'],
] },
{ p: 'B2', t: 'Plant Hormones & Development', w: 3, q: [
  ['The *Avena* curvature test, a bioassay for auxin, was devised by:', ['F.W. Went (1928)', 'Charles Darwin (1880)', 'Kögl and Haagen-Smit (1931)', 'Kurosawa (1926)'], 0,
    'Went collected the growth substance from coleoptile tips in agar blocks. The Darwins studied phototropism in canary grass coleoptiles.'],
  ['In germinating barley grains, gibberellin induces α-amylase synthesis in the:', ['Aleurone layer', 'Scutellum', 'Starchy endosperm', 'Coleorhiza'], 0,
    'GA from the embryo reaches the aleurone, which secretes hydrolases to digest starch. Used in malting. GA was discovered from *Gibberella fujikuroi* (bakanae disease).'],
  ['The Richmond–Lang effect refers to:', ['Delay of leaf senescence by cytokinins', 'Bolting of rosette plants by gibberellins', 'Apical dominance by auxin', 'Stomatal closure by ABA'], 0,
    'Kinetin (Miller & Skoog, 1955, from autoclaved herring sperm DNA) delayed yellowing of detached leaves. Zeatin was isolated from maize (Letham, 1963).'],
  ['The "triple response" of etiolated pea seedlings is a classic bioassay for:', ['Ethylene', 'Auxin', 'Gibberellin', 'Abscisic acid'], 0,
    'Reduced elongation, stem swelling and horizontal growth. Ethephon releases ethylene; it is used for ripening, flowering in pineapple and latex flow.'],
  ['Photoperiodism was discovered by Garner and Allard (1920) using:', ['Maryland Mammoth tobacco', '*Xanthium*', 'Soybean Biloxi', '*Arabidopsis*'], 0,
    'This mutant flowered only in the short days of winter (in a greenhouse). Soybean (Biloxi) was their other short-day example.'],
  ['Short-day plants actually require:', ['An uninterrupted dark period longer than a critical length', 'A light period shorter than 8 hours', 'Low temperature before flowering', 'Continuous light'], 0,
    'A brief flash of red light during the night (night-break) prevents flowering in short-day plants. That is why they are also called long-night plants.'],
  ['Red-light promotion and far-red reversal of lettuce seed germination is mediated by:', ['Phytochrome', 'Cryptochrome', 'Phototropin', 'Chlorophyll a'], 0,
    'Borthwick and Hendricks (1952). Pr (absorbs ~660 nm) ↔ Pfr (absorbs ~730 nm); Pfr is the active form. The last exposure decides the response.'],
  ['The mobile flowering signal "florigen" is now identified as:', ['FT (FLOWERING LOCUS T) protein', 'Gibberellic acid', 'Sucrose', 'Vernalin'], 0,
    'Chailakhyan (1936) postulated florigen. FT is made in leaves under inductive photoperiods and travels in the phloem to the shoot apex.'],
  ['Vernalisation is:', ['Promotion of flowering by prolonged low-temperature treatment', 'Breaking of seed dormancy by light', 'Promotion of flowering by long days', 'Inhibition of flowering by auxin'], 0,
    'The term was coined by Lysenko (1928). The cold is perceived by the shoot apex; winter cereals and biennials need it.'],
  ['Under drought and salinity stress, plants accumulate the osmoprotectant amino acid:', ['Proline', 'Tryptophan', 'Methionine', 'Lysine'], 0,
    'Proline and glycine betaine help osmotic adjustment and protect proteins and membranes. ABA rises and closes stomata.'],
] },
{ p: 'B2', t: 'Enzymes & Nitrogen Metabolism', w: 2, q: [
  ['The Michaelis constant (Km) is:', ['The substrate concentration at which the reaction rate is half of Vmax', 'The maximum rate of the reaction', 'The enzyme concentration at saturation', 'The rate constant of product release'], 0,
    'A low Km means high affinity for the substrate. On a Lineweaver–Burk plot, the x-intercept is −1/Km.'],
  ['A competitive inhibitor:', ['Raises the apparent Km while Vmax stays unchanged', 'Lowers Vmax while Km stays unchanged', 'Lowers both Km and Vmax', 'Binds only the enzyme–substrate complex'], 0,
    'It resembles the substrate and competes for the active site, e.g., malonate inhibits succinate dehydrogenase. Excess substrate overcomes it.'],
  ['In leaves, nitrite reductase is located in the:', ['Chloroplast', 'Cytosol', 'Mitochondrion', 'Vacuole'], 0,
    'Nitrate reductase (cytosol, uses NAD(P)H, contains Mo) makes nitrite; nitrite reductase (plastid, uses ferredoxin) makes ammonium.'],
  ['The main route for assimilating ammonium into amino acids in plants is:', ['GS–GOGAT (glutamine synthetase–glutamate synthase) pathway', 'Urea cycle', 'Glyoxylate cycle', 'Reductive amination by nitrogenase'], 0,
    'GS has high affinity for NH₄⁺. GOGAT transfers the amide group of glutamine to 2-oxoglutarate, forming two glutamates.'],
  ['The peptidyl-transferase activity of the ribosome resides in:', ['23S rRNA — a ribozyme', 'Ribosomal protein L2', 'tRNA', 'Elongation factor Tu'], 0,
    'RNA catalysts (ribozymes) were discovered by Cech and Altman (Nobel 1989).'],
  ['Natural rubber is chemically a:', ['Polyterpene (cis-1,4-polyisoprene)', 'Polysaccharide', 'Alkaloid', 'Phenolic polymer'], 0,
    'Terpenoids are built from isoprene (C₅) units. Alkaloids are nitrogenous (nicotine, morphine); lignin is a phenolic polymer.'],
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 3, q: [
  ['The term "ecosystem" was coined by:', ['A.G. Tansley (1935)', 'E.P. Odum (1953)', 'Ernst Haeckel (1869)', 'R. Lindeman (1942)'], 0,
    'Haeckel coined "ecology". Lindeman founded trophic-dynamic ecology (the "10% law" of energy transfer).'],
  ['Which ecological pyramid is always upright?', ['Pyramid of energy', 'Pyramid of numbers', 'Pyramid of biomass', 'Pyramid of standing crop'], 0,
    'Energy is lost at each transfer (second law of thermodynamics). Biomass pyramids are inverted in open oceans (phytoplankton); number pyramids are inverted in a tree ecosystem.'],
  ['The pioneer community of a xerosere on bare rock is usually:', ['Crustose lichens', 'Mosses', 'Annual grasses', 'Shrubs'], 0,
    'Crustose → foliose lichens → mosses → herbs → shrubs → climax forest. In a hydrosere, phytoplankton are the pioneers.'],
  ['Raunkiaer’s classification of plant life forms is based on:', ['The position of perennating buds relative to the soil surface', 'Leaf size', 'Root depth', 'Type of pollination'], 0,
    'Phanerophytes (buds high in the air) dominate the humid tropics; therophytes (annuals surviving as seed) dominate deserts.'],
  ['The greater variety and density of organisms at the junction of two communities is called:', ['Edge effect', 'Ecotype', 'Ecological niche', 'Keystone effect'], 0,
    'The transition zone is the ecotone (e.g., forest–grassland). Edge species may be more abundant there.'],
  ['A species whose impact on community structure is far greater than its abundance suggests is a:', ['Keystone species', 'Dominant species', 'Pioneer species', 'Indicator species'], 0,
    'Examples: *Ficus* (figs feed many frugivores in lean seasons), sea otters in kelp forests.'],
  ['Allelopathy is:', ['Chemical inhibition of one plant by another through released compounds', 'Mutualism between fungi and roots', 'Competition for light only', 'Predation of seeds by rodents'], 0,
    'Examples: *Parthenium* (parthenin), *Eucalyptus*, black walnut (juglone), *Lantana*.'],
] },
{ p: 'B2', t: 'Plant Geography, Forests & Biodiversity', w: 3, q: [
  ['Champion and Seth (1968) classified Indian forests into:', ['16 major type groups', '6 major type groups', '10 major type groups', '22 major type groups'], 0,
    'The 16 type groups are divided into about 200 forest types. Examples: 3 = tropical moist deciduous, 5 = tropical dry deciduous, 11 = montane wet temperate.'],
  ['Biodiversity hotspot criteria (Myers; Conservation International) require:', ['At least 1,500 endemic vascular plant species and loss of at least 70% of original habitat', 'At least 500 endemic vertebrates and 50% habitat loss', 'Presence of at least one national park', 'At least 30% forest cover'], 0,
    'India has parts of 4 of the 36 hotspots: Himalaya, Indo-Burma, Western Ghats–Sri Lanka and Sundaland (Nicobar Islands).'],
  ['Vivipary (germination while still attached to the parent) is characteristic of the mangrove genus:', ['*Rhizophora*', '*Avicennia*', '*Sonneratia*', '*Nypa*'], 0,
    'The propagule falls and lodges in mud. *Avicennia* and *Sonneratia* have prominent pneumatophores; *Avicennia* shows crypto-vivipary.'],
  ['India’s national gene bank for plant genetic resources is maintained by NBPGR at:', ['New Delhi', 'Hyderabad', 'Shimla', 'Bengaluru'], 0,
    'Long-term storage at −18 °C. The Svalbard Global Seed Vault in Norway is a back-up for the world’s gene banks.'],
  ['Which is NOT an IUCN "threatened" category?', ['Near Threatened', 'Critically Endangered', 'Endangered', 'Vulnerable'], 0,
    'Threatened = CR + EN + VU. Near Threatened is a separate category; so are Least Concern and Data Deficient.'],
  ['*Nepenthes khasiana*, India’s only native pitcher plant, is endemic to:', ['Meghalaya', 'Sikkim', 'Kerala', 'Arunachal Pradesh'], 0,
    'Listed in CITES Appendix I. The pitcher is a modified leaf lamina and the lid develops from the leaf apex; trapped insects supply nitrogen.'],
  ['Sacred groves known as "Devrai" are found in:', ['Maharashtra', 'Kerala', 'Meghalaya', 'Rajasthan'], 0,
    'Kerala: Kavu/Sarpakavu; Meghalaya: Law Kyntang (Mawphlang); Rajasthan: Oran; Karnataka: Devarakadu. These are community-protected forest patches.'],
  ['Shola forests with adjoining montane grasslands occur in:', ['High ranges of the Western Ghats (e.g., Nilgiris, Anamalai)', 'The Terai belt', 'Rann of Kutch', 'Andaman Islands'], 0,
    'Southern montane wet temperate forests: stunted evergreen trees in valleys, grasslands on slopes. They are major watersheds of peninsular rivers.'],
] },
{ p: 'B2', t: 'Biotechnology & GM Crops', w: 2, q: [
  ['Bollgard II Bt cotton carries the genes:', ['cry1Ac and cry2Ab', 'cry1Ac only', 'cry3A and cry9C', 'vip3A only'], 0,
    'Bt cotton (Bollgard I, cry1Ac) was approved in India in 2002 and Bollgard II in 2006. Pink bollworm has since evolved resistance.'],
  ['Golden Rice is enriched in:', ['β-carotene (provitamin A)', 'Iron', 'Zinc', 'Lysine'], 0,
    'It carries phytoene synthase (from daffodil, later maize) and crtI (from *Erwinia uredovora*) in the endosperm.'],
  ['In India, GM crops are approved for environmental release by:', ['Genetic Engineering Appraisal Committee (GEAC) under MoEFCC', 'ICAR', 'FSSAI', 'Department of Agriculture'], 0,
    'GEAC works under the Rules 1989 of the Environment (Protection) Act, 1986. The Review Committee on Genetic Manipulation (RCGM) is under DBT.'],
  ['The barnase–barstar system in GM mustard DMH-11 is used for:', ['Male sterility and fertility restoration for hybrid seed', 'Insect resistance', 'Herbicide tolerance only', 'Improved oil quality'], 0,
    'Barnase (from *Bacillus amyloliquefaciens*) kills tapetal cells; barstar restores fertility in the F₁. Developed at Delhi University (Deepak Pental). The bar gene gives glufosinate tolerance as a marker.'],
  ['India’s first genome-edited rice varieties released by ICAR in 2025 are:', ['DRR Dhan 100 (Kamala) and Pusa DST Rice 1', 'Swarna-Sub1 and IR64', 'Pusa Basmati 1121 and 1509', 'Improved Samba Mahsuri and DRR Dhan 45'], 0,
    'Developed by SDN-1 editing, which India exempted from GM rules in 2022. Kamala (from Samba Mahsuri) is higher yielding and matures earlier; Pusa DST Rice 1 (edited DST gene) yields better on saline and alkaline soils.'],
  ['The Cartagena Protocol deals with:', ['Safe transboundary movement of living modified organisms (LMOs)', 'Access and benefit sharing of genetic resources', 'Trade in endangered species', 'Protection of wetlands'], 0,
    'Adopted 2000, in force 2003, under the CBD. Access and benefit sharing is the Nagoya Protocol (2010); endangered species trade is CITES.'],
  ['The first commercially sold genetically engineered whole food (1994) was:', ['Flavr Savr tomato', 'Bt maize', 'Roundup Ready soybean', 'Golden Rice'], 0,
    'Antisense polygalacturonase slowed softening, giving longer shelf life.'],
] }
);
