/* Botany Paper I (IFoS Paper III). Row: [question, options, answerIndex, explanation].
 * Options are shuffled at display time unless they are statement codes ("1 and 2 only", "Both ..."). */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Microbiology', w: 2, q: [
  ['The genome of Tobacco Mosaic Virus (TMV) is:', ['Single-stranded, positive-sense RNA', 'Double-stranded DNA', 'Double-stranded RNA', 'Single-stranded DNA'], 0,
    'TMV: rigid rod (~300 × 18 nm), ~2130 identical coat-protein subunits helically wound round one +ssRNA of ~6400 nucleotides.'],
  ['Viroids differ from viruses in that they:', ['Are naked circular RNA molecules without a protein coat', 'Contain both DNA and RNA', 'Have a lipid envelope', 'Are infectious proteins lacking nucleic acid'], 0,
    'Viroids (T.O. Diener, 1971; Potato spindle tuber viroid) are small circular ssRNA with no capsid. Infectious proteins are prions.'],
  ['Teichoic acids are characteristic of:', ['Gram-positive bacterial cell walls', 'Gram-negative outer membranes', 'Fungal cell walls', 'Archaeal cell membranes'], 0,
    'Gram-positive walls: thick peptidoglycan + teichoic acids. Gram-negative: thin peptidoglycan + outer membrane with lipopolysaccharide.'],
  ['Transfer of bacterial DNA from one cell to another by a bacteriophage is called:', ['Transduction', 'Transformation', 'Conjugation', 'Transfection'], 0,
    'Transduction: Zinder & Lederberg (1952) in Salmonella. Transformation: Griffith (1928). Conjugation: Lederberg & Tatum (1946).'],
  ['Leghaemoglobin in legume root nodules:', ['Keeps free O₂ low around nitrogenase while supplying O₂ for bacteroid respiration', 'Fixes atmospheric nitrogen directly', 'Transports ammonia to the xylem', 'Gives the nodule a green colour for photosynthesis'], 0,
    'Nitrogenase is irreversibly damaged by O₂. Leghaemoglobin (pink) binds O₂, buffering it at very low free concentration.'],
  ['Phytoplasmas, such as the agent of little leaf of brinjal, are:', ['Wall-less prokaryotes sensitive to tetracycline', 'RNA viruses spread by aphids', 'Fungi with coenocytic hyphae', 'Nematodes living in phloem'], 0,
    'Phytoplasmas lack a cell wall (so penicillin has no effect) and live in phloem. Little leaf of brinjal is spread by the leafhopper Hishimonus phycitis.'],
  ['The Ti plasmid used as a plant transformation vector comes from:', ['*Agrobacterium tumefaciens*', '*Agrobacterium rhizogenes*', '*Escherichia coli*', '*Bacillus thuringiensis*'], 0,
    'Ti (tumour-inducing) plasmid causes crown gall; its T-DNA integrates into the plant genome. *A. rhizogenes* carries the Ri plasmid (hairy root).'],
  ['Heterocysts of *Nostoc* and *Anabaena* are specialised for:', ['Nitrogen fixation', 'Asexual spore formation', 'Storage of cyanophycean starch', 'Gas vacuole buoyancy'], 0,
    'Heterocysts have thick walls and lack PS II (no O₂ evolution), creating the anaerobic interior nitrogenase needs.'],
] },
{ p: 'B1', t: 'Plant Pathology', w: 3, q: [
  ['The Irish famine of 1845–47 was caused by:', ['Late blight of potato — *Phytophthora infestans*', 'Early blight — *Alternaria solani*', 'Wart disease — *Synchytrium endobioticum*', 'Bacterial wilt — *Ralstonia solanacearum*'], 0,
    '*Phytophthora infestans* is an oomycete (water mould), not a true fungus. Its epidemics wiped out Ireland’s staple crop.'],
  ['The Bengal famine of 1943 is associated with:', ['Brown spot of rice — *Helminthosporium (Bipolaris) oryzae*', 'Blast of rice — *Pyricularia oryzae*', 'Bacterial leaf blight — *Xanthomonas oryzae*', 'Rice tungro virus'], 0,
    'Brown spot (*Cochliobolus miyabeanus*, anamorph *Bipolaris oryzae*) caused heavy losses of the 1942 rice crop in Bengal.'],
  ['Citrus canker is caused by:', ['*Xanthomonas citri* (a bacterium)', '*Phytophthora* spp. (gummosis)', 'Citrus tristeza virus', '*Candidatus* Liberibacter (greening)'], 0,
    'Canker: raised corky lesions with a yellow halo on leaves, twigs and fruit; spread by rain splash and the leaf miner. Controlled with copper sprays and streptocycline.'],
  ['Loose smut of wheat needs systemic seed treatment (e.g., carboxin) because the pathogen:', ['Survives as dormant mycelium inside the embryo', 'Survives on alternate hosts', 'Is soil-borne as sclerotia', 'Is carried by aphid vectors'], 0,
    '*Ustilago tritici* infects at flowering and stays inside the embryo; surface fungicides cannot reach it. Solar heat treatment (Luthra) is the older remedy.'],
  ['On barberry, *Puccinia graminis tritici* produces:', ['Pycniospores (spermatia) and aeciospores', 'Urediniospores and teliospores', 'Basidiospores only', 'Teliospores only'], 0,
    'Heteroecious, macrocyclic rust: pycnia (upper leaf surface) and aecia (lower surface) on barberry; uredinia and telia on wheat; basidiospores from germinating teliospores infect barberry.'],
  ['Red rot, the "cancer of sugarcane", is caused by:', ['*Colletotrichum falcatum*', '*Ustilago scitaminea*', '*Fusarium moniliforme*', '*Cercospora* sp.'], 0,
    'Red rot: red internal tissue with white cross-bands and an alcoholic smell. Whip smut of sugarcane is *Sporisorium (Ustilago) scitamineum*.'],
  ['Which is NOT one of Koch’s postulates?', ['The pathogen must grow only on living host tissue', 'The pathogen must be associated with all diseased plants', 'It must be isolated and grown in pure culture', 'Inoculated into a healthy host, it must reproduce the same disease'], 0,
    'Fourth postulate: the same pathogen must be re-isolated. Obligate parasites (rusts, mildews, viruses) cannot meet the pure-culture step in practice.'],
  ['Tikka disease of groundnut is caused by:', ['*Cercospora arachidicola* and *C. personata*', '*Puccinia arachidis*', '*Sclerotium rolfsii*', '*Aspergillus niger*'], 0,
    'Early leaf spot (*C. arachidicola*) and late leaf spot (*Phaeoisariopsis/Cercospora personata*). *Puccinia arachidis* causes groundnut rust; *A. niger* causes collar rot.'],
  ['Bordeaux mixture, first used against downy mildew of grapevine, contains:', ['Copper sulphate and lime', 'Sulphur and lime', 'Copper sulphate and sodium carbonate', 'Mercuric chloride and lime'], 0,
    'Discovered by P.M.A. Millardet (1882–85) in Bordeaux, France. Copper sulphate + sodium carbonate is Burgundy mixture.'],
  ['Green ear disease of pearl millet (bajra) is caused by:', ['*Sclerospora graminicola* (downy mildew)', '*Claviceps fusiformis* (ergot)', '*Tolyposporium penicillariae* (smut)', '*Puccinia penniseti* (rust)'], 0,
    'The oomycete converts floral parts into leafy structures (phyllody). Ergot of bajra is *Claviceps fusiformis*.'],
  ['Rice tungro virus is transmitted by:', ['Green leafhopper (*Nephotettix virescens*)', 'Brown planthopper (*Nilaparvata lugens*)', 'Whitefly (*Bemisia tabaci*)', 'Thrips'], 0,
    'Tungro (RTBV + RTSV) causes yellow-orange discolouration and stunting. Brown planthopper transmits grassy stunt and ragged stunt viruses.'],
  ['Ergot of rye is important because its sclerotia:', ['Contain toxic alkaloids derived from lysergic acid', 'Produce aflatoxin B1', 'Cause lathyrism', 'Release hydrocyanic acid'], 0,
    '*Claviceps purpurea* replaces grains with sclerotia (ergots); ergotism ("St. Anthony’s fire"). Ergot alkaloids are also used medicinally (ergometrine).'],
  ['Consider the following statements:\n1. Powdery mildews are mostly ectoparasites with superficial mycelium.\n2. Downy mildews are caused by oomycetes such as *Plasmopara* and *Peronospora*.\nWhich is/are correct?', ['1 only', '2 only', 'Both 1 and 2', 'Neither 1 nor 2'], 2,
    'Powdery mildews (Erysiphales, Ascomycota) grow on the surface and send haustoria into epidermal cells. Downy mildews are oomycetes with internal mycelium.'],
] },
{ p: 'B1', t: 'Algae', w: 2, q: [
  ['F.E. Fritsch, in "The Structure and Reproduction of the Algae", grouped algae into:', ['11 classes', '5 classes', '7 classes', '15 classes'], 0,
    'Fritsch (1935, 1945) used pigments, reserve food, flagella and reproduction to recognise 11 classes (e.g., Chlorophyceae, Phaeophyceae, Rhodophyceae).'],
  ['Isogamy, anisogamy and oogamy all occur within the genus:', ['*Chlamydomonas*', '*Spirogyra*', '*Volvox*', '*Ectocarpus*'], 0,
    'E.g., *C. reinhardtii* isogamous, *C. braunii* anisogamous, *C. coccifera* oogamous. *Spirogyra* shows conjugation; *Volvox* is oogamous.'],
  ['Floridean starch is the reserve food of:', ['Rhodophyceae (red algae)', 'Phaeophyceae (brown algae)', 'Chlorophyceae (green algae)', 'Bacillariophyceae (diatoms)'], 0,
    'Red algae: phycoerythrin, floridean starch, no flagellated stages. Brown algae store laminarin and mannitol; green algae store true starch.'],
  ['Agar-agar is commercially extracted from:', ['*Gelidium* and *Gracilaria*', '*Laminaria* and *Macrocystis*', '*Ulva* and *Chlorella*', '*Sargassum* and *Fucus*'], 0,
    'Agar and carrageenan (*Chondrus crispus*) come from red algae; algin/alginates come from brown algae (*Laminaria*, *Macrocystis*).'],
  ['Diatomaceous earth is formed from:', ['Silica cell walls (frustules) of diatoms', 'Calcium carbonate shells of coralline algae', 'Cellulose walls of green algae', 'Chitin walls of fungi'], 0,
    'Diatom frustules have two overlapping silica halves (epitheca and hypotheca). Diatomite is used in filtration, insulation and polishes.'],
  ['A triphasic life cycle (gametophyte → carposporophyte → tetrasporophyte) is typical of:', ['*Polysiphonia*', '*Chara*', '*Ulothrix*', '*Fucus*'], 0,
    'Red algae such as *Polysiphonia* have a diploid carposporophyte parasitic on the female gametophyte, followed by a free-living tetrasporophyte.'],
  ['In *Chara*, the sex organs on a node are arranged with:', ['The nucule (oogonium) above the globule (antheridium)', 'The globule above the nucule', 'Both side by side at the same level', 'Sex organs on separate plants only'], 0,
    'Remember "N above G". The globule is a complex, multicellular antheridium; *Chara* is often called stonewort because of lime encrustation.'],
  ['*Fucus* shows which type of life cycle?', ['Diplontic — only the gametes are haploid', 'Haplontic — only the zygote is diploid', 'Isomorphic diplohaplontic', 'Heteromorphic with a dominant gametophyte'], 0,
    'Meiosis in *Fucus* occurs during gamete formation in conceptacles. *Ulothrix* and *Chlamydomonas* are haplontic; *Ectocarpus* is isomorphic diplohaplontic.'],
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 2, q: [
  ['In Ainsworth’s (1973) classification, fungi with no known sexual stage are placed in:', ['Deuteromycotina', 'Zygomycotina', 'Mastigomycotina', 'Basidiomycotina'], 0,
    'Eumycota has five subdivisions: Mastigomycotina, Zygomycotina, Ascomycotina, Basidiomycotina and Deuteromycotina (Fungi Imperfecti).'],
  ['Clamp connections are characteristic of the dikaryotic mycelium of:', ['Basidiomycetes', 'Ascomycetes', 'Zygomycetes', 'Oomycetes'], 0,
    'Clamps keep the two nuclei (n + n) together during cell division. Ascomycetes form a comparable crozier (hook) only at ascus formation.'],
  ['The Hartig net is a feature of:', ['Ectomycorrhiza', 'Arbuscular mycorrhiza', 'Orchid mycorrhiza', 'Lichens'], 0,
    'Ectomycorrhizal hyphae form a mantle round the root and a Hartig net between cortical cells (e.g., *Pinus*, *Eucalyptus*). Arbuscular mycorrhiza (*Glomus*) forms arbuscules and vesicles inside cells.'],
  ['Lichens are good bio-indicators of air pollution because they are highly sensitive to:', ['Sulphur dioxide', 'Carbon dioxide', 'Nitrogen gas', 'Ozone in the stratosphere'], 0,
    'Lichens absorb water and solutes over their whole surface and have no cuticle; SO₂ destroys the algal chlorophyll. Lichen deserts form in industrial cities.'],
  ['Heterothallism in fungi was discovered by A.F. Blakeslee (1904) in:', ['Mucorales (*Mucor*/*Rhizopus*)', 'Yeast', '*Neurospora*', '*Agaricus*'], 0,
    'Blakeslee showed that zygospores form only when + and − strains meet.'],
  ['Aflatoxins, carcinogenic contaminants of groundnut and maize, are produced by:', ['*Aspergillus flavus*', '*Penicillium notatum*', '*Fusarium graminearum*', '*Claviceps purpurea*'], 0,
    'Aflatoxin B1 is a potent liver carcinogen. It builds up when produce is harvested late or stored damp, so dry pods and grain well and store them cool.'],
  ['Commercial penicillin is produced mainly from:', ['*Penicillium chrysogenum*', '*Penicillium notatum*', '*Aspergillus niger*', '*Streptomyces griseus*'], 0,
    'Fleming (1928) discovered penicillin in *P. notatum*; high-yielding *P. chrysogenum* strains are used industrially. *Streptomyces griseus* gives streptomycin.'],
] },
{ p: 'B1', t: 'Bryophytes', w: 2, q: [
  ['In bryophytes, the dominant, independent phase of the life cycle is:', ['The haploid gametophyte', 'The diploid sporophyte', 'The protonema only', 'The zygote'], 0,
    'The sporophyte (foot, seta, capsule) remains attached to and dependent on the gametophyte. In pteridophytes the sporophyte is dominant.'],
  ['Which bryophyte has the simplest sporophyte, lacking foot, seta and elaters?', ['*Riccia*', '*Marchantia*', '*Funaria*', '*Anthoceros*'], 0,
    'The *Riccia* sporophyte is just a capsule embedded in the thallus. *Marchantia* has foot, seta, capsule and elaters.'],
  ['An intercalary meristem at the base of the sporophyte, a columella and stomata on the capsule are features of:', ['*Anthoceros*', '*Riccia*', '*Sphagnum*', '*Porella*'], 0,
    'The *Anthoceros* sporophyte grows continuously and is partly photosynthetic, which is why it is seen as a link towards pteridophytes.'],
  ['On germination, a *Funaria* spore forms a green, branched, filamentous stage called:', ['Protonema', 'Prothallus', 'Gemma', 'Calyptra'], 0,
    'Buds on the protonema grow into leafy gametophores. A prothallus is the gametophyte of ferns.'],
  ['*Sphagnum* (peat moss) holds large amounts of water because of its:', ['Dead hyaline cells with pores and spiral thickenings', 'Thick waxy cuticle', 'Well-developed xylem', 'Mucilage canals in the rhizoids'], 0,
    'Leaves have living green chlorophyllose cells between large dead hyaline cells; *Sphagnum* also acidifies its surroundings. Used as a packing and nursery medium.'],
  ['Gemma cups for vegetative reproduction are found in:', ['*Marchantia*', '*Riccia*', '*Anthoceros*', '*Funaria*'], 0,
    'Gemmae are splashed out of the cups by raindrops and grow into new thalli.'],
] },
{ p: 'B1', t: 'Pteridophytes', w: 2, q: [
  ['A stele suspended in an air cavity by radially elongated endodermal cells (trabeculae) is characteristic of:', ['*Selaginella*', '*Lycopodium*', '*Equisetum*', '*Pteris*'], 0,
    'Trabeculae are elongated endodermal cells with Casparian strips; the stele of *Selaginella* is protostelic.'],
  ['Heterospory, a step towards the seed habit, occurs in:', ['*Selaginella*', '*Lycopodium*', '*Equisetum*', '*Psilotum*'], 0,
    'Also in *Marsilea*, *Salvinia*, *Azolla* and *Isoetes*. Retention of the megaspore within the megasporangium in *Selaginella* approaches the seed habit.'],
  ['The stelar theory was proposed by:', ['Van Tieghem and Douliot (1886)', 'Zimmermann (1930)', 'Hanstein (1868)', 'Schmidt (1924)'], 0,
    'Zimmermann gave the telome theory; Hanstein the histogen theory; Schmidt the tunica–corpus theory.'],
  ['*Rhynia*, known from the Rhynie chert of Scotland, is significant as:', ['One of the earliest vascular plants (Devonian) with a protostele and no true leaves or roots', 'The earliest seed plant', 'A Carboniferous tree fern', 'A living fossil gymnosperm'], 0,
    'Psilophytes such as *Rhynia* had dichotomous leafless axes and terminal sporangia, the basis of the telome concept.'],
  ['Spores bearing four ribbon-like, hygroscopic elaters are produced by:', ['*Equisetum*', '*Marchantia*', '*Selaginella*', '*Marsilea*'], 0,
    'In *Equisetum* the elaters come from the outer spore wall; in *Marchantia* elaters are separate cells in the capsule.'],
  ['The water fern used as a biofertiliser in rice because of its symbiotic cyanobacterium is:', ['*Azolla*', '*Salvinia*', '*Marsilea*', '*Isoetes*'], 0,
    '*Azolla* leaf cavities hold *Anabaena azollae*, which fixes nitrogen and can supply about 30–40 kg N/ha to paddy.'],
  ['An amphiphloic siphonostele (solenostele) is found in the rhizome of:', ['*Marsilea*', '*Lycopodium*', '*Rhynia*', '*Psilotum*'], 0,
    'Amphiphloic means phloem both outside and inside the xylem ring. *Lycopodium* has a plectostele (protostele); *Psilotum* an actinostele.'],
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, q: [
  ['Motile, multiflagellate sperms among living seed plants are found in:', ['*Cycas* and *Ginkgo*', '*Pinus* and *Cedrus*', '*Gnetum* and *Ephedra*', '*Taxus* and *Podocarpus*'], 0,
    'This is a link to pteridophyte ancestry. *Cycas* sperms are among the largest in the plant kingdom; other conifers have non-motile male gametes.'],
  ['The endosperm of gymnosperms such as *Pinus* is:', ['Haploid — it is the female gametophyte formed before fertilisation', 'Triploid — formed by triple fusion', 'Diploid — formed from the nucellus', 'Absent'], 0,
    'Gymnosperms have no double fertilisation, so there is no triple fusion.'],
  ['Vessels in the secondary xylem, a feature linking gymnosperms to angiosperms, occur in:', ['*Gnetum* (Gnetales)', '*Cycas*', '*Pinus*', '*Ginkgo*'], 0,
    'Gnetales (*Gnetum*, *Ephedra*, *Welwitschia*) also have compound strobili and a perianth-like envelope around the ovule.'],
  ['The tallest living trees in the world are:', ['*Sequoia sempervirens* (coast redwood)', '*Sequoiadendron giganteum* (giant sequoia)', '*Eucalyptus regnans*', '*Pinus roxburghii*'], 0,
    'Coast redwood "Hyperion" is about 116 m tall. *Sequoiadendron giganteum* is the most massive (by volume); *E. regnans* is the tallest flowering plant.'],
  ['Ephedrine, used to treat asthma, comes from:', ['*Ephedra*', '*Taxus*', '*Ginkgo*', '*Cycas*'], 0,
    'Ephedra is Gnetales. *Taxus* gives taxol (anticancer); *Ginkgo* extracts are used for circulation and memory.'],
  ['*Cycas* coralloid roots are:', ['Negatively geotropic roots with cyanobacteria (*Anabaena*/*Nostoc*) in the cortex', 'Mycorrhizal roots with *Glomus*', 'Nodules with *Rhizobium*', 'Pneumatophores for aeration'], 0,
    'The cyanobacteria live in a middle cortical layer and fix nitrogen. *Cycas beddomei* is endemic to the Seshachalam hills (Eastern Ghats).'],
  ['*Welwitschia mirabilis*, which keeps only two strap-shaped leaves throughout its life, is native to:', ['The Namib desert (Namibia/Angola)', 'The Thar desert', 'The Atacama desert', 'The Gobi desert'], 0,
    'A long-lived gnetophyte; individual plants may be over 1,000 years old.'],
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 3, q: [
  ['In Bentham and Hooker’s *Genera Plantarum* (1862–83), gymnosperms were placed:', ['Between dicotyledons and monocotyledons', 'Before dicotyledons', 'After monocotyledons', 'Outside seed plants'], 0,
    'Its main drawback. The system is still used to arrange herbaria in India (e.g., the Central National Herbarium, Howrah).'],
  ['Treating catkin-bearing Amentiferae as the most primitive dicots is a feature of the system of:', ['Engler and Prantl', 'Bentham and Hooker', 'Hutchinson', 'Takhtajan'], 0,
    '*Die Natürlichen Pflanzenfamilien* treated simple, unisexual, apetalous flowers as primitive. Hutchinson and Takhtajan considered Magnoliales/Ranales primitive.'],
  ['The 2016 version of the Angiosperm Phylogeny Group classification is:', ['APG IV', 'APG II', 'APG III', 'APG V'], 0,
    'APG I (1998), II (2003), III (2009), IV (2016). It is based mainly on molecular (DNA sequence) phylogenies.'],
  ['Under the ICN, botanical nomenclature of most plants begins with:', ['Linnaeus’s *Species Plantarum*, 1 May 1753', 'Linnaeus’s *Systema Naturae*, 1735', 'De Candolle’s *Prodromus*, 1824', 'Bentham & Hooker, 1862'], 0,
    'Starting point for the principle of priority. The binomial system became standard from *Species Plantarum*.'],
  ['A specimen chosen from the original material to serve as type when no holotype was designated is a:', ['Lectotype', 'Isotype', 'Neotype', 'Paratype'], 0,
    'Isotype = duplicate of the holotype; neotype = chosen when all original material is lost; paratype = other specimens cited in the protologue.'],
  ['Tetradynamous stamens (four long, two short) are characteristic of:', ['Brassicaceae', 'Lamiaceae', 'Fabaceae', 'Solanaceae'], 0,
    'Brassicaceae (Cruciferae): cruciform corolla, siliqua fruit and a false septum (replum). Lamiaceae has didynamous stamens (two long, two short).'],
  ['The cyathium inflorescence is characteristic of:', ['*Euphorbia* (Euphorbiaceae)', '*Ficus* (Moraceae)', '*Salvia* (Lamiaceae)', '*Helianthus* (Asteraceae)'], 0,
    'Cup-like involucre with one central female flower and many reduced male flowers. *Ficus* has a hypanthodium; Asteraceae a capitulum.'],
  ['Verticillaster inflorescence and gynobasic style are found together in:', ['Lamiaceae', 'Malvaceae', 'Poaceae', 'Brassicaceae'], 0,
    'Lamiaceae (Labiatae): square stems, opposite aromatic leaves, bilabiate corolla, didynamous stamens.'],
  ['A bicarpellary, syncarpous ovary placed obliquely on the thalamus is diagnostic of:', ['Solanaceae', 'Liliaceae', 'Fabaceae', 'Asteraceae'], 0,
    'Solanaceae (e.g., *Solanum*, *Datura*): swollen axile placentae; berry or capsule.'],
  ['Monadelphous stamens with reniform, monothecous anthers characterise:', ['Malvaceae', 'Fabaceae', 'Asteraceae', 'Cucurbitaceae'], 0,
    'Filaments are fused into a staminal tube around the style. Asteraceae has syngenesious stamens (anthers fused); Papilionoideae is diadelphous (9)+1.'],
  ['The translator mechanism linking pollinia of adjacent anthers is found in:', ['Asclepiadoideae (e.g., *Calotropis*)', 'Orchidaceae', 'Poaceae', 'Malvaceae'], 0,
    'In the milkweeds (now a subfamily of Apocynaceae) a gynostegium forms and a corpusculum with two arms carries pollinia from neighbouring anthers.'],
  ['The Botanical Survey of India, headquartered at Kolkata, was established in:', ['1890', '1916', '1947', '1864'], 0,
    'BSI was set up in 1890 under Sir George King. The Zoological Survey of India dates from 1916; the Forest Department from 1864.'],
] },
{ p: 'B1', t: 'Plant Anatomy', w: 3, q: [
  ['In *Dracaena*, the secondary vascular bundles produced by the anomalous cambium are:', ['Amphivasal (xylem surrounds phloem)', 'Amphicribral (phloem surrounds xylem)', 'Collateral open', 'Bicollateral'], 0,
    'Monocot secondary growth: a cambium outside the primary bundles cuts off amphivasal (leptocentric) bundles inward and a little parenchyma outward.'],
  ['Four phloem wedges projecting into the secondary xylem are characteristic of the stem of:', ['*Bignonia*', '*Boerhavia*', '*Dracaena*', '*Salvadora*'], 0,
    'At four points the cambium makes less xylem and more phloem, forming furrows filled with phloem. This is an anomaly of cambial activity.'],
  ['Interxylary (included) phloem is characteristic of:', ['*Salvadora*', '*Bignonia*', '*Dracaena*', '*Nyctanthes*'], 0,
    'The cambium periodically cuts off phloem strands inward, which become embedded in the xylem. Also seen in *Leptadenia* and *Strychnos*.'],
  ['Tyloses are:', ['Balloon-like ingrowths of parenchyma into vessel lumens through pits', 'Crystals of calcium oxalate in phloem', 'Lignified bands in the endodermis', 'Resin ducts in pine wood'], 0,
    'Tyloses block vessels in heartwood, increasing durability (e.g., white oak and teak) and reducing permeability to preservatives.'],
  ['Casparian strips of the endodermis are made mainly of:', ['Suberin (with lignin)', 'Cellulose', 'Pectin', 'Callose'], 0,
    'They block the apoplastic path in radial and transverse walls, forcing water and solutes through the symplast into the stele.'],
  ['Wood in which large vessels form in early wood and small vessels in late wood, making a distinct ring, is called:', ['Ring-porous', 'Diffuse-porous', 'Non-porous', 'Semi-ring-porous only'], 0,
    'Examples: *Quercus*, *Tectona* (ring- to semi-ring-porous). Diffuse-porous: *Mangifera* and many tropical woods. Non-porous (no vessels): conifers.'],
  ['The quiescent centre of the root apex was described by:', ['F.A.L. Clowes', 'J. Hanstein', 'A. Schmidt', 'Van Tieghem'], 0,
    'The quiescent centre is a group of slowly dividing cells between the root cap and the proximal meristem. It acts as a reserve of initials.'],
  ['The tunica–corpus theory of shoot apex organisation was proposed by:', ['A. Schmidt (1924)', 'J. Hanstein (1868)', 'Nägeli (1858)', 'Clowes (1961)'], 0,
    'Tunica: outer layers with anticlinal divisions; corpus: inner mass dividing in all planes. Hanstein proposed the histogen theory (dermatogen, periblem, plerome).'],
  ['Cork cambium (phellogen) produces cork on the outside and, on the inside:', ['Phelloderm', 'Secondary phloem', 'Secondary xylem', 'Epidermis'], 0,
    'Periderm = phellem (cork) + phellogen + phelloderm. Lenticels allow gas exchange through the periderm.'],
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 3, q: [
  ['A mature *Polygonum*-type embryo sac consists of:', ['7 cells and 8 nuclei', '8 cells and 8 nuclei', '8 cells and 7 nuclei', '6 cells and 7 nuclei'], 0,
    'Monosporic 8-nucleate type: 3 antipodals + egg + 2 synergids + 1 central cell (with 2 polar nuclei) = 7 cells, 8 nuclei. It is found in about 70% of angiosperms.'],
  ['Double fertilisation was discovered by S.G. Nawaschin (1898) in:', ['*Lilium* and *Fritillaria*', '*Zea mays*', '*Arabidopsis*', '*Capsella*'], 0,
    'One sperm fuses with the egg (syngamy) and the other with the polar nuclei (triple fusion) to form the triploid primary endosperm nucleus.'],
  ['The liquid "water" of tender coconut represents:', ['Free-nuclear endosperm', 'Cellular endosperm', 'Nucellar fluid', 'Helobial endosperm'], 0,
    'Nuclear endosperm with free nuclei; wall formation from the periphery forms the white kernel (cellular endosperm).'],
  ['Ruminate endosperm (irregular infolded surface) is found in:', ['*Areca catechu* and *Myristica fragrans*', '*Zea mays* and *Oryza sativa*', '*Pisum* and *Cicer*', '*Petunia* and *Datura*'], 0,
    'The seed coat or perisperm grows into the endosperm. Examples: betel nut, nutmeg, also Annonaceae.'],
  ['The effect of pollen on maternal tissues such as the fruit wall is termed:', ['Metaxenia', 'Xenia', 'Parthenocarpy', 'Apomixis'], 0,
    'Xenia (Focke, 1881) is the effect of pollen on the endosperm or embryo (e.g., maize kernel colour). Metaxenia (Swingle, 1928) is the effect on the pericarp or seed coat (e.g., date palm fruit size).'],
  ['Nucellar polyembryony in *Citrus* is an example of:', ['Adventive embryony (sporophytic apomixis)', 'Diplospory', 'Apospory', 'Parthenogenesis from a reduced egg'], 0,
    'Embryos arise directly from nucellus cells, so nucellar seedlings are true-to-type and virus-free. This is valuable for rootstocks.'],
  ['The highly resistant substance forming the exine of pollen grains is:', ['Sporopollenin', 'Pectocellulose', 'Callose', 'Suberin'], 0,
    'Sporopollenin resists acids, alkalis and decay, which is why pollen fossilises well (palynology, pollen analysis).'],
  ['Ubisch bodies (orbicules), involved in pollen wall formation, are produced by the:', ['Tapetum', 'Endothecium', 'Middle layers', 'Epidermis of the anther'], 0,
    'The tapetum nourishes microspores and secretes callase, sporopollenin precursors and pollenkitt. It may be secretory or amoeboid.'],
  ['"Test-tube fertilisation" of ovules was first achieved (Kanta, Rangaswamy & Maheshwari, 1962) in:', ['*Papaver somniferum*', '*Datura innoxia*', '*Nicotiana tabacum*', '*Zea mays*'], 0,
    'Pollen was placed directly on cultured ovules, bypassing stigma and style. P. Maheshwari is regarded as the father of Indian plant embryology.'],
  ['Sporophytic self-incompatibility, where pollen behaviour depends on the genotype of the parent plant, occurs in:', ['*Brassica*', '*Nicotiana*', '*Petunia*', '*Prunus*'], 0,
    'Sporophytic SI (Brassicaceae, Asteraceae) acts at the stigma surface. Gametophytic SI (Solanaceae, Rosaceae) depends on the pollen’s own S-allele and acts in the style.'],
  ['Persistent nucellus in the seed (perisperm) is found in:', ['Black pepper (*Piper nigrum*)', 'Castor', 'Maize', 'Pea'], 0,
    'Perisperm is persistent nucellus (diploid, maternal), seen in Piperaceae, Nymphaeaceae and *Beta* (beet). It is not the same as endosperm, which is triploid.'],
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 3, q: [
  ['N.I. Vavilov proposed that cultivated plants originated in:', ['8 main centres of origin', '3 main centres', '12 main centres', '5 main centres'], 0,
    'His 8 centres (with sub-centres) include the Hindustani (Indo-Burma) centre: rice, mango, black pepper, cotton (*G. arboreum*), brinjal and more.'],
  ['Which crop did NOT originate in the Hindustani (Indian) centre?', ['Maize', 'Rice', 'Mango', 'Black pepper'], 0,
    'Maize is from Mesoamerica (Mexico). Other New World crops: potato, tomato, chilli, groundnut, tobacco, rubber, cashew.'],
  ['Natural rubber is obtained from the latex of:', ['*Hevea brasiliensis* (Euphorbiaceae)', '*Ficus elastica* (Moraceae)', '*Manilkara zapota* (Sapotaceae)', '*Calotropis procera*'], 0,
    'Para rubber from Brazil. *Manilkara* latex gives chicle (chewing gum base). Kerala is India’s main rubber state; the Rubber Board is at Kottayam.'],
  ['Quinine, the antimalarial alkaloid, is extracted from the bark of:', ['*Cinchona* (Rubiaceae)', '*Rauvolfia serpentina*', '*Artemisia annua*', '*Azadirachta indica*'], 0,
    'Cinchona plantations exist in the Nilgiris and Darjeeling (Mungpoo). *Artemisia annua* gives artemisinin (Tu Youyou, Nobel 2015).'],
  ['Reserpine, used for hypertension, comes from the roots of:', ['*Rauvolfia serpentina*', '*Withania somnifera*', '*Catharanthus roseus*', '*Papaver somniferum*'], 0,
    'Sarpagandha (Apocynaceae). *Catharanthus roseus* gives vinblastine and vincristine (anticancer); *Withania* is ashwagandha.'],
  ['Paclitaxel (taxol) is obtained from:', ['*Taxus* (yew) — in India *Taxus wallichiana*', '*Cinchona officinalis*', '*Podophyllum hexandrum*', '*Digitalis purpurea*'], 0,
    'Originally from Pacific yew (*T. brevifolia*) bark. *Podophyllum* gives podophyllotoxin; *Digitalis* gives digoxin (cardiac).'],
  ['Coir is obtained from the ____ of coconut.', ['Mesocarp', 'Endocarp', 'Epicarp', 'Endosperm'], 0,
    'Coir is a fruit fibre from the fibrous mesocarp; the hard shell is the endocarp. Jute and flax are bast fibres; cotton is a seed-surface fibre.'],
  ['*Santalum album* (sandalwood) is best described as a:', ['Root hemiparasite', 'Total stem parasite', 'Epiphyte', 'Insectivorous plant'], 0,
    'Sandal forms haustoria on roots of host plants (e.g., *Cajanus*, *Casuarina*) but is photosynthetic. Spike disease (a phytoplasma) is its major threat.'],
  ['Guggul, a gum-resin used in Ayurveda, is obtained from the critically endangered:', ['*Commiphora wightii*', '*Boswellia serrata*', '*Acacia senegal*', '*Pterocarpus santalinus*'], 0,
    '*Boswellia serrata* gives salai guggul (frankincense); *Acacia senegal* gives gum arabic; *Pterocarpus santalinus* is red sanders, endemic to the Eastern Ghats.'],
  ['The non-edible seed oil tree promoted for biodiesel and also used in agroforestry in India is:', ['*Pongamia pinnata* (karanj)', '*Tectona grandis*', '*Dalbergia sissoo*', '*Shorea robusta*'], 0,
    'Pongamia is a leguminous, nitrogen-fixing, drought-hardy tree. *Jatropha curcas* is another biodiesel candidate. Sal seed fat is used as a cocoa-butter substitute.'],
] },
{ p: 'B1', t: 'Morphogenesis & Tissue Culture', w: 2, q: [
  ['The concept of cellular totipotency was put forward by:', ['G. Haberlandt (1902)', 'F.C. Steward (1958)', 'Murashige & Skoog (1962)', 'P.R. White (1934)'], 0,
    'Haberlandt could not grow plants from single cells. Steward (1958) proved totipotency by regenerating carrot plants from phloem cells.'],
  ['According to Skoog and Miller (1957), a high cytokinin : auxin ratio in the medium promotes:', ['Shoot formation', 'Root formation', 'Callus only, without organs', 'Somatic embryo abortion'], 0,
    'High auxin : cytokinin favours roots; intermediate ratios favour callus. This is the basis of hormonal control of organogenesis (worked out in tobacco pith).'],
  ['Haploid plants from anther culture were first obtained by Guha and Maheshwari (1964) in:', ['*Datura innoxia*', '*Nicotiana tabacum*', '*Oryza sativa*', '*Brassica napus*'], 0,
    'Androgenic haploids, after chromosome doubling with colchicine, give homozygous (doubled-haploid) lines in one generation.'],
  ['The "pomato" was produced by:', ['Somatic hybridisation (protoplast fusion) of potato and tomato', 'Grafting tomato on potato rootstock', 'Sexual crossing followed by embryo rescue', 'Agrobacterium-mediated transformation'], 0,
    'Melchers et al. (1978). Protoplasts are fused with PEG or electrofusion. Grafting also gives a "pomato" plant but not a hybrid.'],
  ['Meristem-tip culture yields virus-free plants because:', ['The apical dome has no vascular tissue and dividing cells stay largely free of virus', 'Culture media contain antiviral antibiotics', 'Viruses cannot survive in the dark', 'Cytokinins destroy virus particles'], 0,
    'Morel and Martin (1952) freed dahlia of viruses this way. It is often combined with thermotherapy; widely used in potato, banana and sugarcane.'],
  ['Synthetic (artificial) seeds are usually:', ['Somatic embryos encapsulated in sodium alginate gel', 'Seeds coated with fungicide', 'Pollen grains in agar', 'Apomictic seeds from wild relatives'], 0,
    'Calcium alginate beads form when sodium alginate drops fall into calcium chloride solution. They are useful for germplasm exchange and storage.'],
  ['Genetic variation arising in plants regenerated from tissue culture was termed "somaclonal variation" by:', ['Larkin and Scowcroft (1981)', 'Haberlandt (1902)', 'Steward (1958)', 'Morel (1960)'], 0,
    'It is useful for selecting disease- and stress-tolerant lines, but unwanted when true-to-type clones are needed.'],
] }
);
