/* General English (IFoS Paper I). Row: [question, options, answerIndex, explanation]. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'EN', t: 'Grammar — Agreement & Tense', w: 3, q: [
  ['Choose the correct option: "One of the forest guards ___ absent today."', ['is', 'are', 'were', 'have been'], 0,
    '"One of + plural noun" takes a singular verb, because the subject is "one".'],
  ['Choose the correct option: "Neither the Range Officer nor his assistants ___ present at the inspection."', ['were', 'was', 'is', 'has been'], 0,
    'With "neither…nor" and "either…or", the verb agrees with the nearer subject ("assistants").'],
  ['Choose the correct option: "Each of the trainees ___ given a field kit."', ['was', 'were', 'are', 'have been'], 0,
    '"Each", "every", "either", "neither" used as subjects take singular verbs.'],
  ['Choose the correct option: "The number of forest fires ___ risen sharply this year."', ['has', 'have', 'are', 'were'], 0,
    '"The number of" is singular; "a number of" (= many) is plural: "A number of fires have been reported."'],
  ['Choose the correct option: "If I ___ in your place, I would accept the posting."', ['were', 'was', 'am', 'had been being'], 0,
    'The subjunctive "were" is used for hypothetical present conditions (second conditional), with all persons.'],
  ['Choose the correct option: "He has been working in this division ___ 2019."', ['since', 'for', 'from', 'by'], 0,
    '"Since" with a point of time; "for" with a period ("for six years"). Both usually go with the perfect tense.'],
  ['Choose the correct option: "She is one of those officers who ___ always willing to help."', ['are', 'is', 'was', 'has been'], 0,
    'The relative pronoun "who" refers to "those officers" (plural), so the verb is plural.'],
  ['Choose the correct option: "Scarcely had he reached the camp ___ it began to rain."', ['when', 'than', 'then', 'that'], 0,
    'Fixed pairs: scarcely/hardly…when; no sooner…than. Note the inversion "had he reached".'],
  ['Choose the correct option: "He said that he ___ tired after the long patrol."', ['was', 'is', 'will be', 'has been'], 0,
    'Sequence of tenses: a past reporting verb is followed by a past tense in the reported clause (unless it states a universal truth).'],
  ['Choose the correct option: "Unless you work hard, you ___ fail."', ['will', 'will not', 'would not', 'do not'], 0,
    '"Unless" already means "if not", so no second negative: "Unless you work hard, you will fail."'],
  ['Choose the correct option: "The jury ___ divided in their opinions."', ['were', 'was', 'is', 'has'], 0,
    'A collective noun takes a plural verb when the members act separately (note "their opinions"); singular when acting as one body.'],
  ['Identify the correct sentence:', ['The news is encouraging.', 'The news are encouraging.', 'The newses are encouraging.', 'A news are encouraging.'], 0,
    '"News", "information", "advice", "furniture", "equipment" are uncountable and singular: "a piece of news".'],
] },
{ p: 'EN', t: 'Grammar — Sentence Correction', w: 3, q: [
  ['Identify the correct sentence:', ['I look forward to meeting you.', 'I look forward to meet you.', 'I am looking forward to meet you.', 'I look forward for meeting you.'], 0,
    '"To" in "look forward to", "be used to", "object to", "with a view to" is a preposition, so it takes the -ing form.'],
  ['Identify the correct sentence:', ['Despite working hard, he failed.', 'Despite of working hard, he failed.', 'In spite working hard, he failed.', 'Despite he worked hard, he failed.'], 0,
    '"Despite" takes no "of"; "in spite of" needs "of". Neither introduces a full clause — use "although" for that.'],
  ['Identify the correct sentence:', ['He is senior to me by two years.', 'He is senior than me by two years.', 'He is senior from me by two years.', 'He is more senior than me by two years.'], 0,
    'Latin comparatives (senior, junior, superior, inferior, prior, prefer) take "to", not "than".'],
  ['Identify the correct sentence:', ['I prefer tea to coffee.', 'I prefer tea than coffee.', 'I prefer tea over than coffee.', 'I prefer more tea than coffee.'], 0,
    '"Prefer X to Y". With infinitives: "I prefer to walk rather than drive."'],
  ['Identify the correct sentence:', ['He denied taking the files.', 'He denied to take the files.', 'He denied that to take the files.', 'He denied for taking the files.'], 0,
    'Verbs such as deny, avoid, admit, enjoy, finish, mind, risk and suggest are followed by a gerund.'],
  ['Identify the correct sentence:', ['Walking through the forest, we saw a herd of gaur.', 'Walking through the forest, a herd of gaur was seen.', 'Walking through the forest, a herd of gaur saw us walking.', 'While walking through forest, herd of gaur was seen by us.'], 0,
    'Avoid dangling modifiers: the subject of the main clause must be the one doing the action of the participle (we were walking).'],
  ['Identify the sentence with correct parallel structure:', ['The officer was asked to survey the area, prepare a map and submit a report.', 'The officer was asked to survey the area, preparing a map and a report submission.', 'The officer was asked surveying the area, to prepare a map and submitting a report.', 'The officer was asked to survey the area, a map preparation and report.'], 0,
    'Items in a series must share the same grammatical form (here, three infinitives).'],
  ['Identify the correct sentence:', ['Hardly had I entered the room when the phone rang.', 'Hardly I had entered the room when the phone rang.', 'Hardly had I entered the room than the phone rang.', 'Hardly did I entered the room when the phone rang.'], 0,
    'Negative adverbs placed first (hardly, scarcely, never, seldom, not only) cause inversion of the auxiliary and subject.'],
  ['Identify the correct sentence:', ['Not only did he plant the saplings but he also watered them.', 'Not only he planted the saplings but also watered them.', 'He not only planted the saplings but he watered also them.', 'Not only did he planted the saplings but also watered them.'], 0,
    'Fronted "not only" needs inversion ("did he plant"). Alternatively: "He not only planted the saplings but also watered them."'],
  ['Identify the correct sentence:', ['Between you and me, the plan will fail.', 'Between you and I, the plan will fail.', 'Between yourself and I, the plan will fail.', 'Among you and me, the plan will fail.'], 0,
    'A preposition takes the object pronoun ("me"). "Between" is for two, "among" for more than two.'],
] },
{ p: 'EN', t: 'Vocabulary — Synonyms & Antonyms', w: 2, q: [
  ['Synonym of UBIQUITOUS:', ['Omnipresent', 'Rare', 'Ancient', 'Hostile'], 0, 'Ubiquitous: found everywhere, e.g., "Plastic is now ubiquitous in forest litter."'],
  ['Synonym of SANGUINE:', ['Optimistic', 'Bloodthirsty', 'Gloomy', 'Indifferent'], 0, 'Sanguine: hopeful, confident. (It comes from the Latin for blood, but in modern use means optimistic.)'],
  ['Synonym of OBDURATE:', ['Stubborn', 'Obedient', 'Obscure', 'Gentle'], 0, 'Obdurate: refusing to change one’s opinion; unmoved by persuasion.'],
  ['Synonym of LACONIC:', ['Terse', 'Talkative', 'Lazy', 'Cheerful'], 0, 'Laconic: using very few words. Antonyms: verbose, garrulous, loquacious.'],
  ['Antonym of EPHEMERAL:', ['Permanent', 'Fleeting', 'Transient', 'Brief'], 0, 'Ephemeral: lasting a very short time (like mayflies). Its antonyms: permanent, enduring, perennial.'],
  ['Antonym of PROFLIGATE:', ['Frugal', 'Wasteful', 'Extravagant', 'Reckless'], 0, 'Profligate: recklessly wasteful. Frugal/thrifty is the opposite.'],
  ['Antonym of GARRULOUS:', ['Taciturn', 'Talkative', 'Chatty', 'Voluble'], 0, 'Garrulous: excessively talkative. Taciturn: habitually silent, reserved.'],
  ['Synonym of MITIGATE:', ['Alleviate', 'Aggravate', 'Instigate', 'Imitate'], 0, 'Mitigate: make less severe — e.g., "mitigate human–wildlife conflict". Aggravate is the opposite.'],
  ['Synonym of SYLVAN:', ['Wooded', 'Silvery', 'Marshy', 'Rocky'], 0, 'Sylvan: of or relating to woods (Latin silva, forest — as in silviculture).'],
  ['Synonym of DELETERIOUS:', ['Harmful', 'Delightful', 'Beneficial', 'Deliberate'], 0, 'Deleterious: causing harm — "the deleterious effects of invasive species".'],
  ['Antonym of MAGNANIMOUS:', ['Petty', 'Generous', 'Noble', 'Forgiving'], 0, 'Magnanimous: generous and forgiving, especially towards a rival. Opposite: petty, mean-spirited.'],
  ['Synonym of NASCENT:', ['Emerging', 'Dying', 'Mature', 'Nasty'], 0, 'Nascent: just coming into existence — "a nascent carbon market".'],
  ['Synonym of OBSEQUIOUS:', ['Servile', 'Obvious', 'Stubborn', 'Rude'], 0, 'Obsequious: excessively eager to please or obey; fawning.'],
  ['Synonym of ALACRITY:', ['Eagerness', 'Alarm', 'Laziness', 'Sadness'], 0, 'Alacrity: brisk and cheerful readiness — "She accepted the challenge with alacrity."'],
  ['Antonym of PUSILLANIMOUS:', ['Courageous', 'Timid', 'Cowardly', 'Fearful'], 0, 'Pusillanimous: lacking courage. Its antonyms: brave, bold, courageous.'],
] },
{ p: 'EN', t: 'Idioms & Phrases', w: 2, q: [
  ['"To bell the cat" means:', ['To undertake a risky task for the common good', 'To catch a thief', 'To make a loud noise', 'To dress up a pet'], 0, 'From Aesop’s fable of the mice who wanted a bell on the cat but none dared to tie it.'],
  ['"A white elephant" is:', ['A costly possession that is of little use', 'A rare animal', 'A great honour', 'A peace offering'], 0, '"The new stadium became a white elephant for the town."'],
  ['"To bite the bullet" means:', ['To face something unpleasant with courage', 'To be shot', 'To eat hurriedly', 'To give up a fight'], 0, 'Said to come from soldiers biting a bullet during surgery without anaesthesia.'],
  ['"A red herring" is:', ['Something that misleads or distracts from the real issue', 'A rare fish', 'A dangerous situation', 'A reward for honesty'], 0, 'Common in debates and detective stories.'],
  ['"Hobson’s choice" means:', ['No real choice — take what is offered or nothing', 'A very wide choice', 'A difficult moral choice', 'A choice made by vote'], 0, 'After Thomas Hobson, a stable owner who offered only the horse nearest the door.'],
  ['"To be out of the woods" means:', ['To be out of danger or difficulty', 'To be lost', 'To leave the forest service', 'To be exposed'], 0, '"The patient is recovering but not yet out of the woods."'],
  ['"Unable to see the wood for the trees" means:', ['Too absorbed in details to see the overall picture', 'Having poor eyesight', 'Being in a dense forest', 'Refusing to cut trees'], 0, 'A classic trap in précis and answer writing — keep the central theme in view.'],
  ['"Barking up the wrong tree" means:', ['Pursuing a mistaken course or accusing the wrong person', 'Speaking loudly', 'Climbing a tree', 'Complaining without reason'], 0, 'From hunting dogs barking at a tree the quarry has already left.'],
  ['"To throw in the towel" means:', ['To admit defeat; give up', 'To start a fight', 'To clean up', 'To celebrate a win'], 0, 'From boxing, when a trainer throws a towel into the ring to stop the fight.'],
  ['"To cry wolf" means:', ['To raise a false alarm', 'To be afraid of animals', 'To weep loudly', 'To warn genuinely'], 0, 'From Aesop’s shepherd boy; later genuine warnings are ignored.'],
  ['"Achilles’ heel" means:', ['A weak or vulnerable point', 'A strong defence', 'A foot injury', 'A fast runner'], 0, 'From Greek myth: Achilles was invulnerable except at his heel.'],
  ['"To turn over a new leaf" means:', ['To change one’s behaviour for the better', 'To read a new book', 'To start gardening', 'To change one’s job'], 0, '"Leaf" here means a page of a book.'],
] },
{ p: 'EN', t: 'One-word Substitution', w: 2, q: [
  ['The scientific study of trees and woody plants:', ['Dendrology', 'Ornithology', 'Pedology', 'Mycology'], 0, 'Ornithology: birds; pedology: soils; mycology: fungi; entomology: insects; herpetology: reptiles and amphibians.'],
  ['The practice of controlling the establishment, growth, composition and quality of forests:', ['Silviculture', 'Horticulture', 'Apiculture', 'Sericulture'], 0, 'Apiculture: bee-keeping; sericulture: silk; horticulture: fruits, vegetables and flowers; pisciculture: fish.'],
  ['A person who hates mankind:', ['Misanthrope', 'Philanthropist', 'Misogynist', 'Anthropologist'], 0, 'Misogynist: one who hates women; philanthropist: one who loves and helps mankind.'],
  ['Government by a small group of powerful people:', ['Oligarchy', 'Monarchy', 'Anarchy', 'Plutocracy'], 0, 'Plutocracy: rule by the wealthy; anarchy: absence of government; theocracy: rule by religious leaders.'],
  ['A speech delivered without preparation:', ['Extempore', 'Verbatim', 'Soliloquy', 'Monologue'], 0, 'Verbatim: word for word; soliloquy: speaking one’s thoughts aloud alone, as in a play.'],
  ['Animals that are active at night:', ['Nocturnal', 'Diurnal', 'Crepuscular', 'Arboreal'], 0, 'Diurnal: active by day; crepuscular: active at dawn and dusk; arboreal: living in trees.'],
  ['A roundabout, indirect way of speaking:', ['Circumlocution', 'Eloquence', 'Brevity', 'Tautology'], 0, 'Tautology: saying the same thing twice in different words ("free gift").'],
  ['That which cannot be read:', ['Illegible', 'Ineligible', 'Inaudible', 'Invisible'], 0, 'Ineligible: not qualified; inaudible: cannot be heard.'],
  ['Plants that grow in water or very wet conditions:', ['Hydrophytes', 'Xerophytes', 'Halophytes', 'Epiphytes'], 0, 'Xerophytes: dry habitats; halophytes: saline habitats (mangroves); epiphytes: grow on other plants.'],
  ['One who walks in sleep:', ['Somnambulist', 'Somniloquist', 'Insomniac', 'Funambulist'], 0, 'Somniloquist: talks in sleep; insomniac: cannot sleep; funambulist: tightrope walker.'],
] },
{ p: 'EN', t: 'Prepositions & Articles', w: 2, q: [
  ['Fill in: "He is ___ honest officer."', ['an', 'a', 'the', 'no article'], 0, 'Use "an" before a vowel sound: an honest, an hour, an MLA; but "a university", "a one-horned rhino".'],
  ['Fill in: "The tiger was killed ___ a poacher ___ a snare."', ['by, with', 'with, by', 'by, by', 'from, with'], 0, '"By" marks the doer; "with" marks the instrument.'],
  ['Fill in: "He was accused ___ theft of timber."', ['of', 'for', 'with', 'about'], 0, 'Accused of; charged with; convicted of; acquitted of.'],
  ['Fill in: "We must abstain ___ burning crop residue."', ['from', 'of', 'to', 'against'], 0, 'Abstain from; refrain from; desist from; prevent from.'],
  ['Fill in: "I agree ___ your proposal, but I do not agree ___ you on the budget."', ['to, with', 'with, to', 'on, to', 'to, to'], 0, 'Agree to a proposal or plan; agree with a person; agree on a point.'],
  ['Fill in: "All contractors must comply ___ the working plan."', ['with', 'to', 'by', 'for'], 0, 'Comply with; conform to; abide by.'],
  ['Fill in: "She is good ___ mathematics and fond ___ music."', ['at, of', 'in, of', 'at, with', 'on, for'], 0, 'Good at; fond of; interested in; proficient in.'],
  ['Fill in: "Mount Everest is ___ highest peak in ___ world."', ['the, the', 'a, the', 'the, a', 'no article, the'], 0, 'Superlatives and unique things take "the".'],
] },
{ p: 'EN', t: 'Voice & Narration', w: 1, q: [
  ['Passive of "They are planting saplings along the canal.":', ['Saplings are being planted along the canal by them.', 'Saplings were planted along the canal by them.', 'Saplings are planted along the canal by them.', 'Saplings have been planting along the canal by them.'], 0, 'Present continuous passive: is/are + being + past participle.'],
  ['Passive of "Who wrote this working plan?":', ['By whom was this working plan written?', 'Who was written this working plan?', 'By whom this working plan was written?', 'Whom wrote this working plan?'], 0, 'In passive questions, "who" becomes "by whom" and the auxiliary comes before the subject.'],
  ['Indirect speech of: She said to me, "Please help me."', ['She requested me to help her.', 'She said to me that please help her.', 'She told me that I help her.', 'She requested me that I should help me.'], 0, 'Imperatives become "requested/ordered/advised + object + to-infinitive"; "please" is dropped.'],
  ['Indirect speech of: "Let us conserve water," said the officer.', ['The officer proposed that they should conserve water.', 'The officer said let us conserve water.', 'The officer told to conserve water.', 'The officer proposed that let them conserve water.'], 0, '"Let us" expressing a proposal becomes "proposed/suggested that + subject + should".'],
  ['Passive of the command "Close the gate.":', ['Let the gate be closed.', 'The gate is closed.', 'The gate was closed.', 'Let close the gate.'], 0, 'Imperative passive: Let + object + be + past participle. Or: "You are requested/ordered to close the gate."'],
] },
{ p: 'EN', t: 'Confusable Words & Spelling', w: 2, q: [
  ['Choose the correct word: "The new policy will ___ tribal livelihoods."', ['affect', 'effect', 'afect', 'effectuate'], 0, '"Affect" is usually the verb (to influence); "effect" is usually the noun (result). "Effect" as a verb means to bring about.'],
  ['Choose the correct word: "Please buy some ___ for the office."', ['stationery', 'stationary', 'stationory', 'stationarry'], 0, 'Stationery (paper, pens) — remember "e for envelope". Stationary means not moving.'],
  ['Choose the correct word: "Honesty is a guiding ___ of public service."', ['principle', 'principal', 'principel', 'principality'], 0, 'Principle: a rule or belief. Principal: head of a school, or main ("principal reason"), or capital sum of a loan.'],
  ['Choose the correct word: "The officer was ___ about the informant’s identity."', ['discreet', 'discrete', 'discrate', 'discret'], 0, 'Discreet: careful, prudent. Discrete: separate, distinct ("discrete data").'],
  ['Choose the correctly spelt word:', ['Accommodation', 'Accomodation', 'Acommodation', 'Accommadation'], 0, 'Double "c" and double "m". Similarly: committee, embarrass, millennium, occurrence.'],
  ['Choose the correctly spelt word:', ['Conscientious', 'Consciencious', 'Conscientous', 'Consientious'], 0, 'Conscientious: diligent, careful. Related: conscience, conscious.'],
  ['Choose the correct word: "Monsoon failure poses an ___ threat to the kharif crop."', ['imminent', 'eminent', 'immanent', 'emanent'], 0, 'Imminent: about to happen. Eminent: distinguished. Immanent: inherent.'],
  ['Choose the correct word: "Nothing can ___ the need for field experience."', ['supplant', 'supplement', 'supplicate', 'supple'], 0, 'Supplant: replace. Supplement: add to. Supplicate: plead humbly.'],
] },
{ p: 'EN', t: 'Précis & Comprehension Technique', w: 2, q: [
  ['A précis should normally be about ___ of the original passage.', ['One-third', 'One-half', 'Two-thirds', 'One-tenth'], 0, 'Aim for about one-third. If the question specifies a word count, keep close to it and state the count at the end.'],
  ['A précis is normally written in:', ['Third person, reported speech, past tense for narration', 'First person, direct speech', 'Second person, imperative mood', 'The same words as the passage'], 0, 'It is an objective summary. Do not add your own opinions, examples or quotations from the passage.'],
  ['Which should be LEFT OUT of a précis?', ['Illustrations, examples and repetitions', 'The central idea', 'Key supporting arguments', 'The author’s conclusion'], 0, 'Keep the thesis, the main arguments and the conclusion; drop examples, figures of speech and repetition.'],
  ['A good title for a précis should be:', ['Short and express the central theme', 'A full sentence summarising all points', 'The first line of the passage', 'Humorous to attract attention'], 0, 'It can be a phrase — for example, "Forests as Water Towers".'],
  ['Read: "Forests regulate the water cycle. Their litter and roots hold rain, recharge aquifers and release water slowly, so streams flow even in the dry months. When catchments are cleared, floods and droughts both become more frequent."\nThe central idea is that forests:', ['Moderate water flow, reducing both floods and dry-season scarcity', 'Increase annual rainfall everywhere', 'Cause floods when they grow too dense', 'Are important only in the monsoon'], 0, 'The passage links forest cover to steadier stream flow; "increase rainfall" is not stated — do not import outside knowledge into comprehension answers.'],
  ['In the same passage, the word "catchments" most nearly means:', ['Areas from which rainfall drains into a stream or river', 'Nets for catching fish', 'Dams built on rivers', 'Village ponds'], 0, 'A catchment (watershed) is the land draining to a common outlet. Infer meaning from context.'],
  ['In comprehension answers, you should generally:', ['Answer in your own words, based only on the passage', 'Copy long sentences from the passage', 'Add your own knowledge and examples', 'Write as long an answer as possible'], 0, 'Examiners reward understanding shown through paraphrase, and penalise lifting and irrelevance.'],
] }
);
