/* General Knowledge (IFoS Paper II). Row: [question, options, answerIndex, explanation].
 * Current-affairs rows reflect events up to 2025; re-check anything time-sensitive before the exam. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'GK', t: 'Polity & Constitution', w: 3, q: [
  ['Which Directive Principle directs the State to protect and improve the environment and safeguard forests and wildlife?', ['Article 48A', 'Article 47', 'Article 51A(g)', 'Article 39(b)'], 0,
    'Article 48A (and the Fundamental Duty in Article 51A(g)) were added by the 42nd Amendment (1976). Article 47 deals with nutrition, public health and prohibition.'],
  ['The 42nd Amendment (1976) moved "Forests" and "Protection of wild animals and birds" from the State List to the:', ['Concurrent List', 'Union List', 'Eleventh Schedule', 'Residuary powers'], 0,
    'Forests became Entry 17A and wildlife protection Entry 17B of List III. Education and weights & measures were also moved to the Concurrent List.'],
  ['The Supreme Court has read the right to a clean and healthy environment into:', ['Article 21', 'Article 19(1)(g)', 'Article 32', 'Article 14'], 0,
    'Cases include Subhash Kumar (1991) and M.C. Mehta. Article 32 is the right to constitutional remedies — Ambedkar called it the "heart and soul" of the Constitution.'],
  ['Tribal areas of Assam, Meghalaya, Tripura and Mizoram are administered under the:', ['Sixth Schedule', 'Fifth Schedule', 'Seventh Schedule', 'Ninth Schedule'], 0,
    'Autonomous District Councils manage land, forests (other than reserved forests) and customs. The Fifth Schedule covers Scheduled Areas in other states.'],
  ['The Panchayats (Extension to Scheduled Areas) Act, PESA, was enacted in:', ['1996', '1993', '2006', '1992'], 0,
    'It gives Gram Sabhas in Fifth Schedule areas ownership of minor forest produce and a say in land acquisition. The 73rd Amendment dates from 1992 (in force 1993).'],
  ['The Eleventh Schedule, listing 29 subjects for Panchayats, was added by the:', ['73rd Amendment', '74th Amendment', '42nd Amendment', '61st Amendment'], 0,
    'It includes social forestry and farm forestry, minor forest produce, fuel and fodder. The 74th Amendment added the Twelfth Schedule (18 subjects) for municipalities.'],
  ['Anti-defection provisions are in the:', ['Tenth Schedule', 'Eighth Schedule', 'Ninth Schedule', 'Fourth Schedule'], 0,
    'Added by the 52nd Amendment (1985). The 91st Amendment (2003) removed the "split" exception and capped ministries at 15% of the House.'],
  ['The Finance Commission is constituted under:', ['Article 280', 'Article 270', 'Article 312', 'Article 324'], 0,
    'Article 312 creates All-India Services (the IFS was created in 1966 under it); Article 324 is the Election Commission.'],
  ['The National Green Tribunal was set up under the NGT Act of:', ['2010', '2002', '1986', '2016'], 0,
    'It hears civil cases on environment, forests and biodiversity. India was the third country, after Australia and New Zealand, to set up such a tribunal.'],
  ['Who certifies whether a Bill is a Money Bill?', ['The Speaker of the Lok Sabha', 'The President', 'The Chairman of the Rajya Sabha', 'The Finance Minister'], 0,
    'Article 110. The Speaker’s decision is final (though its judicial review has been debated). The Rajya Sabha can only delay a Money Bill by 14 days.'],
] },
{ p: 'GK', t: 'History & Environmental History', w: 2, q: [
  ['India’s first Forest Policy was issued in:', ['1894', '1865', '1927', '1952'], 0,
    'The first Indian Forest Act was passed in 1865, followed by 1878 and 1927. Independent India’s policies date from 1952 and 1988.'],
  ['The first Inspector General of Forests in India (1864) was:', ['Dietrich Brandis', 'Hugh Cleghorn', 'Berthold Ribbentrop', 'William Schlich'], 0,
    'Brandis, a German botanist, is called the father of tropical forestry. Cleghorn was an early Conservator in Madras.'],
  ['The Imperial Forest Research Institute at Dehradun was established in:', ['1906', '1878', '1926', '1947'], 0,
    'It began as the Imperial Forest School (1878). The present FRI building was inaugurated in 1929.'],
  ['The Chipko movement began in the early 1970s in the:', ['Chamoli district of present-day Uttarakhand', 'Western Ghats of Karnataka', 'Silent Valley, Kerala', 'Aravalli hills, Rajasthan'], 0,
    'Leaders: Chandi Prasad Bhatt, Sunderlal Bahuguna; Gaura Devi led the women of Reni village (1974). The Appiko movement (1983) was its Karnataka counterpart.'],
  ['Amrita Devi Bishnoi and 363 Bishnois gave their lives to protect khejri trees in 1730 at:', ['Khejarli, near Jodhpur', 'Reni, Chamoli', 'Silent Valley', 'Sariska'], 0,
    'The Amrita Devi Bishnoi Wildlife Protection Award commemorates them.'],
  ['The Silent Valley movement was against a hydroelectric project on the river:', ['Kunthipuzha', 'Periyar', 'Narmada', 'Bhagirathi'], 0,
    'The project was abandoned and Silent Valley National Park (Kerala) was declared in 1984. It protects the lion-tailed macaque habitat.'],
  ['In Kautilya’s *Arthashastra*, the superintendent of forest produce was the:', ['Kupyadhyaksha', 'Sitadhyaksha', 'Sulkadhyaksha', 'Nagaradhyaksha'], 0,
    'Sitadhyaksha looked after crown agriculture; Sulkadhyaksha collected tolls. The text also describes elephant forests (hastivana).'],
  ['Which Ashokan edict lists animals that must not be killed?', ['Pillar Edict V', 'Rock Edict XIII', 'Kalinga Rock Edict I', 'Minor Rock Edict I'], 0,
    'Rock Edict XIII describes the Kalinga war and Ashoka’s remorse.'],
  ['The Harappan city added to the UNESCO World Heritage list in 2021 is:', ['Dholavira', 'Lothal', 'Rakhigarhi', 'Kalibangan'], 0,
    'In Kutch, Gujarat, it is known for its water conservation system of reservoirs. Ramappa Temple (Telangana) was also inscribed in 2021.'],
  ['The Champaran Satyagraha (1917) was against the forced cultivation of:', ['Indigo', 'Opium', 'Cotton', 'Jute'], 0,
    'Under the "tinkathia" system, peasants had to grow indigo on 3/20 of their land. It was Gandhi’s first satyagraha in India.'],
] },
{ p: 'GK', t: 'Indian & World Geography', w: 3, q: [
  ['The Tropic of Cancer does NOT pass through:', ['Odisha', 'Jharkhand', 'Tripura', 'Chhattisgarh'], 0,
    'It passes through eight states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura and Mizoram.'],
  ['The highest peak of peninsular India is:', ['Anamudi', 'Doddabetta', 'Mahendragiri', 'Dhupgarh'], 0,
    'Anamudi (2,695 m) is in the Anamalai hills of Kerala (Eravikulam National Park, home of the Nilgiri tahr).'],
  ['The only floating national park in the world, Keibul Lamjao, is on:', ['Loktak Lake, Manipur', 'Dal Lake, Kashmir', 'Chilika Lake, Odisha', 'Wular Lake, Kashmir'], 0,
    'Floating vegetation mats (phumdis) support the endangered sangai (brow-antlered deer), Manipur’s state animal.'],
  ['India’s first Ramsar sites, designated in 1981, were:', ['Chilika Lake and Keoladeo National Park', 'Sundarbans and Loktak', 'Wular and Sambhar', 'Vembanad and Ashtamudi'], 0,
    'The Ramsar Convention (1971) is named after Ramsar, Iran. Keoladeo (Bharatpur) is also on the Montreux Record, as Loktak is.'],
  ['A positive Indian Ocean Dipole (IOD) generally:', ['Favours good Indian summer monsoon rainfall', 'Causes drought in India', 'Has no link with the monsoon', 'Causes western disturbances'], 0,
    'Positive IOD: warmer western Indian Ocean than eastern. It can offset El Niño, as in 1997 when the monsoon stayed normal despite a strong El Niño.'],
  ['Winter rain and snowfall in north-west India come mainly from:', ['Western disturbances', 'The retreating monsoon', 'Tropical cyclones from the Bay of Bengal', 'Loo winds'], 0,
    'Extratropical low-pressure systems from the Mediterranean carried by the subtropical westerly jet. Valuable for rabi wheat.'],
  ['The Western Ghats were inscribed as a UNESCO World Heritage Site in:', ['2012', '2004', '1987', '2016'], 0,
    'It was inscribed as a serial natural site of 39 component sites across Kerala, Karnataka, Tamil Nadu and Maharashtra.'],
  ['The Great Green Wall initiative aims to fight desertification across:', ['The Sahel region of Africa', 'The Gobi desert', 'The Thar desert', 'Australia’s outback'], 0,
    'Led by the African Union. India’s Aravalli Green Wall project (2023) is inspired by it.'],
  ['The largest river basin lying within India is that of the:', ['Ganga', 'Godavari', 'Indus', 'Brahmaputra'], 0,
    'The Ganga basin covers about a quarter of India’s area. The Godavari is the largest peninsular river ("Dakshin Ganga").'],
  ['Kaziranga National Park, famous for the one-horned rhinoceros, lies on the banks of the:', ['Brahmaputra', 'Ganga', 'Teesta', 'Barak'], 0,
    'A UNESCO World Heritage Site (1985) and a tiger reserve, holding about two-thirds of the world’s greater one-horned rhinos.'],
] },
{ p: 'GK', t: 'Indian Economy', w: 2, q: [
  ['The inflation target set for the RBI’s Monetary Policy Committee is:', ['4% CPI inflation, with a band of ±2%', '2% WPI inflation', '6% CPI inflation, with ±1%', '5% GDP deflator'], 0,
    'Under the amended RBI Act (2016). The MPC has six members; the Governor has a casting vote.'],
  ['The GST Council is provided for in:', ['Article 279A', 'Article 280', 'Article 265', 'Article 110'], 0,
    'GST was introduced by the 101st Amendment (2016) and launched on 1 July 2017.'],
  ['NITI Aayog replaced the Planning Commission on:', ['1 January 2015', '15 August 2014', '1 April 2015', '26 January 2016'], 0,
    'The Prime Minister chairs it. It follows "cooperative federalism" and does not allocate funds as the Planning Commission did.'],
  ['Under RBI priority-sector norms, domestic scheduled commercial banks must lend to agriculture:', ['18% of adjusted net bank credit', '40% of adjusted net bank credit', '10% of total deposits', '25% of total assets'], 0,
    'The overall priority-sector target is 40% of ANBC, with 18% for agriculture (including about 10% for small and marginal farmers).'],
  ['Fiscal deficit is:', ['Total expenditure minus revenue receipts and non-debt capital receipts', 'Revenue expenditure minus revenue receipts', 'Fiscal deficit minus interest payments', 'Exports minus imports'], 0,
    'Revenue deficit = revenue expenditure − revenue receipts; primary deficit = fiscal deficit − interest payments.'],
  ['The UN framework for integrating natural capital such as forests into national accounts is:', ['SEEA (System of Environmental-Economic Accounting)', 'SNA-GDP core', 'HDI', 'SDG Index'], 0,
    'MoSPI publishes "EnviStats India" with SEEA-based forest, water and energy accounts.'],
] },
{ p: 'GK', t: 'Environment & Climate', w: 3, q: [
  ['India’s net-zero emissions target year, announced at COP26 (Glasgow), is:', ['2070', '2050', '2060', '2047'], 0,
    'Part of the "Panchamrit" pledges. China targets 2060; the EU and UK 2050.'],
  ['India’s updated NDC (2022) commits to an additional carbon sink through forest and tree cover of:', ['2.5–3 billion tonnes of CO₂ equivalent by 2030', '1 billion tonnes by 2025', '5 billion tonnes by 2050', '10 billion tonnes by 2070'], 0,
    'Other NDC goals: cut emission intensity of GDP by 45% from 2005 levels, and 50% of installed power capacity from non-fossil sources, both by 2030.'],
  ['The Kigali Amendment (2016) to the Montreal Protocol aims to phase down:', ['Hydrofluorocarbons (HFCs)', 'Chlorofluorocarbons (CFCs)', 'Methane', 'Carbon dioxide'], 0,
    'HFCs do not harm ozone but are powerful greenhouse gases. India’s freeze year is 2028.'],
  ['The "30 × 30" target of the Kunming–Montreal Global Biodiversity Framework (2022) means:', ['Conserving 30% of land and 30% of oceans by 2030', 'Planting 30 billion trees by 2030', 'Cutting pesticide use by 30% by 2030', 'Restoring 30 million ha by 2030'], 0,
    'Adopted at CBD COP15. The framework has 23 targets. It also aims to restore 30% of degraded ecosystems.'],
  ['The International Big Cat Alliance launched by India (2023) covers:', ['Seven big cats — tiger, lion, leopard, snow leopard, puma, jaguar, cheetah', 'Only tiger and lion', 'Five Asian cats', 'All 40 wild cat species'], 0,
    'Launched at Mysuru to mark 50 years of Project Tiger. Its headquarters are in India.'],
  ['India’s cheetah reintroduction began on 17 September 2022 at:', ['Kuno National Park, Madhya Pradesh', 'Gandhi Sagar Wildlife Sanctuary', 'Desert National Park, Rajasthan', 'Banni grasslands, Gujarat'], 0,
    'Cheetahs came from Namibia (2022) and South Africa (2023). Gandhi Sagar (MP) became the second site in 2025.'],
  ['COP30 of the UNFCCC (November 2025) was held in:', ['Belém, Brazil', 'Baku, Azerbaijan', 'Dubai, UAE', 'Bonn, Germany'], 0,
    'In the Amazon region. COP28 (Dubai, 2023) completed the first Global Stocktake; COP29 (Baku, 2024) agreed the new climate finance goal.'],
  ['The New Collective Quantified Goal (NCQG) on climate finance agreed at COP29 commits developed countries to lead in mobilising at least:', ['USD 300 billion a year by 2035', 'USD 100 billion a year by 2025', 'USD 1 trillion a year by 2030', 'USD 50 billion a year by 2030'], 0,
    'It also calls on all actors to scale up finance to USD 1.3 trillion a year by 2035. The earlier goal was USD 100 billion a year.'],
  ['"Blue carbon" refers to carbon captured by:', ['Coastal and marine ecosystems such as mangroves, seagrasses and salt marshes', 'Glaciers', 'Deep aquifers', 'Blue-green algae in rice fields only'], 0,
    'These ecosystems store carbon in sediments for very long periods. India’s MISHTI scheme (2023) promotes mangrove planting.'],
  ['The Green Credit Programme, notified in October 2023, is a:', ['Market-based incentive for voluntary environmental actions such as tree plantation', 'Loan scheme for electric vehicles', 'Carbon tax on industries', 'Subsidy for solar pumps'], 0,
    'Notified under the Environment (Protection) Act, 1986; ICFRE administers it. It is linked to Mission LiFE.'],
  ['The UN declared 2026 as the International Year of:', ['Rangelands and Pastoralists', 'Millets', 'Camelids', 'Glaciers’ Preservation'], 0,
    'Millets 2023; Camelids 2024; Glaciers’ Preservation 2025. Rangelands matter for IFoS topics such as grazing, silvopasture and grassland ecology.'],
] },
{ p: 'GK', t: 'Forest & Wildlife Status (ISFR, Census)', w: 3, q: [
  ['As per ISFR 2023, India’s total forest and tree cover is about:', ['25.17% of the geographical area', '21.76% of the geographical area', '33% of the geographical area', '19.5% of the geographical area'], 0,
    'Forest cover is 21.76% and tree cover 3.41%. The National Forest Policy 1988 goal is 33%.'],
  ['As per ISFR 2023, the state with the largest forest cover by area is:', ['Madhya Pradesh', 'Arunachal Pradesh', 'Chhattisgarh', 'Odisha'], 0,
    'Order by area: Madhya Pradesh, Arunachal Pradesh, Chhattisgarh. By percentage, Mizoram and Lakshadweep top the list.'],
  ['The 2022 All India Tiger Estimation put India’s tiger population (mean estimate) at about:', ['3,682', '2,967', '3,167', '4,500'], 0,
    '3,167 was the minimum number camera-trapped; 3,682 is the mean estimate (range 3,167–3,925), about 75% of the world’s wild tigers. Madhya Pradesh has the most.'],
  ['Which state has the largest mangrove cover in India?', ['West Bengal', 'Gujarat', 'Odisha', 'Andhra Pradesh'], 0,
    'Mostly the Sundarbans. Gujarat is second; Bhitarkanika (Odisha) is the second-largest mangrove ecosystem.'],
  ['Asiatic lions in the wild are found only in:', ['The Gir landscape of Saurashtra, Gujarat', 'Kuno National Park', 'Sariska Tiger Reserve', 'Chandraprabha Sanctuary'], 0,
    'Numbers have grown steadily and lions now range beyond Gir into coastal Saurashtra (Amreli, Bhavnagar). Translocation to a second home has long been debated.'],
] },
{ p: 'GK', t: 'Science & Technology', w: 2, q: [
  ['Chandrayaan-3’s Vikram lander touched down near the lunar south pole on:', ['23 August 2023', '14 July 2023', '22 July 2019', '2 September 2023'], 0,
    'India became the first country to land near the lunar south pole. 23 August is now National Space Day.'],
  ['Aditya-L1, India’s solar observatory, is stationed near:', ['The Sun–Earth Lagrange point L1', 'The Moon', 'The Sun–Earth L2 point', 'A low Earth orbit'], 0,
    'It reached a halo orbit around L1 (about 1.5 million km from Earth) in January 2024 and studies the solar corona and solar wind.'],
  ['The 2024 Nobel Prize in Chemistry was awarded for:', ['Computational protein design and protein-structure prediction', 'CRISPR-Cas9 genome editing', 'Lithium-ion batteries', 'Quantum dots'], 0,
    'David Baker (design); Demis Hassabis and John Jumper (AlphaFold). CRISPR won in 2020; lithium-ion batteries in 2019; quantum dots in 2023.'],
  ['The 2025 Nobel Prize in Chemistry was awarded for the development of:', ['Metal–organic frameworks (MOFs)', 'Click chemistry', 'Green fluorescent protein', 'Asymmetric organocatalysis'], 0,
    'Awarded to Susumu Kitagawa, Richard Robson and Omar Yaghi. MOFs are porous materials that can capture CO₂ and harvest water from air.'],
  ['The ozone layer that absorbs harmful ultraviolet radiation lies mainly in the:', ['Stratosphere', 'Troposphere', 'Mesosphere', 'Thermosphere'], 0,
    'Ozone at ground level (troposphere) is a pollutant that also damages crops. The Vienna Convention (1985) and Montreal Protocol (1987) protect the ozone layer.'],
  ['India’s first Dark Sky Reserve (2022) is at:', ['Hanle, Ladakh', 'Mount Abu, Rajasthan', 'Spiti, Himachal Pradesh', 'Munnar, Kerala'], 0,
    'Part of Changthang Wildlife Sanctuary, home to the Indian Astronomical Observatory.'],
  ['Vitamin B12 contains the metal:', ['Cobalt', 'Iron', 'Magnesium', 'Zinc'], 0,
    'Cyanocobalamin. Chlorophyll contains magnesium; haemoglobin contains iron.'],
] }
);
