/* Personality Test (IFoS interview): forest law, policy, forestry facts and officer-like judgement.
 * Row: [question, options, answerIndex, explanation]. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'PT', t: 'Forest & Wildlife Laws', w: 3, q: [
  ['Under the Indian Forest Act, 1927, the category with the highest degree of protection is:', ['Reserved forest', 'Protected forest', 'Village forest', 'Unclassed forest'], 0,
    'In reserved forests all activities are prohibited unless permitted; in protected forests activities are allowed unless prohibited. Village forests are managed for village communities.'],
  ['After the Wildlife (Protection) Amendment Act, 2022, the Act has:', ['Four schedules — Schedule IV lists CITES specimens', 'Six schedules as before', 'Two schedules only', 'Five schedules including vermin'], 0,
    'Schedule I: highest protection; II: lesser protection; III: protected plants; IV: CITES Appendix specimens. The vermin schedule was removed; the Centre can notify vermin.'],
  ['Section 2 of the Forest (Conservation) Act, 1980 requires:', ['Prior approval of the Central Government for using forest land for non-forest purposes', 'Consent of the Gram Sabha for all forest felling', 'Approval of the State Legislature for new reserved forests', 'Permission of the Supreme Court for mining leases'], 0,
    'Approval comes in two stages (in-principle, then final) through the Forest Advisory Committee and Regional Empowered Committees, with conditions such as compensatory afforestation and NPV payment.'],
  ['The Forest (Conservation) Amendment Act, 2023 renamed the 1980 Act as:', ['Van (Sanrakshan Evam Samvardhan) Adhiniyam, 1980', 'Van Suraksha Adhiniyam, 2023', 'Bharatiya Van Adhiniyam, 2023', 'Vanya Jeev Sanrakshan Adhiniyam, 1980'], 0,
    'It exempts strategic linear projects within 100 km of international borders, LoC or LAC, some security infrastructure, and allows zoos, safaris and eco-tourism in forests. Critics fear dilution of the Godavarman definition of "forest".'],
  ['Under the Forest Rights Act, 2006, "Other Traditional Forest Dwellers" must show residence for at least:', ['Three generations (75 years) before 13 December 2005', 'One generation (25 years)', '50 years before 1980', 'Ten years before 2006'], 0,
    'Scheduled Tribes need only have lived in and depended on the forest before 13 December 2005. The Gram Sabha initiates the claim process.'],
  ['The maximum area that can be recognised as an individual forest right under FRA is:', ['4 hectares', '1 hectare', '10 hectares', 'No limit'], 0,
    'Recognition is limited to land actually occupied, up to 4 ha. Community Forest Resource rights (Section 3(1)(i)) have no such cap.'],
  ['Section 3(2) of FRA allows diversion of forest land for public facilities (schools, dispensaries, tanks) up to:', ['1 hectare, with fewer than 75 trees per hectare felled', '5 hectares with Gram Sabha consent', '10 hectares with central approval', '0.5 hectare without any conditions'], 0,
    'Thirteen listed facilities. The Divisional Forest Officer approves, with a Gram Sabha recommendation.'],
  ['Under the Compensatory Afforestation Fund Act, 2016, the share of money credited to state funds is:', ['90%', '50%', '10%', '75%'], 0,
    '10% goes to the National Fund. Money comes from compensatory afforestation charges and net present value (NPV) paid by user agencies.'],
  ['In the landmark *T.N. Godavarman Thirumulpad* case (1996), the Supreme Court held that "forest":', ['Should be understood in its dictionary sense, whatever the ownership or classification', 'Means only notified reserved forests', 'Means only land owned by the Forest Department', 'Excludes private plantations in all cases'], 0,
    'It widened the scope of the Forest (Conservation) Act and began the "continuing mandamus" on forest governance (including the CEC and CAMPA).'],
  ['Conservation reserves and community reserves were added to the Wildlife (Protection) Act by the amendment of:', ['2002', '1991', '2006', '2022'], 0,
    'Community reserves can be declared on private or community land with the community’s consent. The 2006 amendment created the NTCA and the Wildlife Crime Control Bureau.'],
  ['Eco-sensitive zones around protected areas are notified under the:', ['Environment (Protection) Act, 1986', 'Wildlife (Protection) Act, 1972', 'Indian Forest Act, 1927', 'Biological Diversity Act, 2002'], 0,
    'They act as buffers regulating industry and mining around parks and sanctuaries; 10 km was the default in 2002 guidelines, with site-specific widths notified.'],
  ['The National Biodiversity Authority, set up under the Biological Diversity Act, 2002, is based at:', ['Chennai', 'New Delhi', 'Dehradun', 'Kolkata'], 0,
    'Three tiers: NBA, State Biodiversity Boards and local Biodiversity Management Committees, which prepare People’s Biodiversity Registers.'],
] },
{ p: 'PT', t: 'Forest Policy & Institutions', w: 3, q: [
  ['The National Forest Policy, 1988 aims for forest or tree cover over:', ['One-third of the geographical area, and two-thirds in hills', 'One-fourth of the area', 'Half the area in the plains', '20% of the area'], 0,
    'The 1988 policy made ecological balance and people’s needs primary, with revenue secondary. It called for people’s participation, leading to JFM.'],
  ['Joint Forest Management in India began as an experiment at:', ['Arabari, West Bengal (1971)', 'Sukhomajri, Haryana (1975)', 'Ralegan Siddhi, Maharashtra (1980)', 'Jhabua, Madhya Pradesh (1990)'], 0,
    'Forester A.K. Banerjee gave villagers a share of sal-coppice produce for protecting it. National JFM guidelines were issued on 1 June 1990.'],
  ['The Forest Survey of India, which publishes the biennial India State of Forest Report, is headquartered at:', ['Dehradun', 'Bhopal', 'Nagpur', 'Shimla'], 0,
    'ISFR has been published since 1987. Dehradun also houses ICFRE, FRI, WII and IGNFA.'],
  ['Project Tiger was launched in 1973 at:', ['Jim Corbett National Park', 'Kanha National Park', 'Sundarbans', 'Ranthambore'], 0,
    'Kailash Sankhala was its first director. NTCA was created in 2006 to run it. Project Elephant followed in 1992.'],
  ['The Green India Mission is one of the eight national missions under:', ['The National Action Plan on Climate Change (2008)', 'The National Forest Policy 1988', 'The Paris Agreement', 'CAMPA'], 0,
    'Aims to increase forest and tree cover and improve forest quality, with ecosystem services and livelihoods.'],
  ['Under the Bonn Challenge, India has pledged to restore by 2030:', ['26 million hectares of degraded land', '5 million hectares', '50 million hectares', '100 million hectares'], 0,
    'The target was raised from 21 million ha at UNCCD COP14 (New Delhi, 2019).'],
  ['REDD+ refers to:', ['Reducing emissions from deforestation and forest degradation, plus conservation, sustainable management and enhancement of forest carbon stocks', 'Renewable energy for developing countries', 'A UN programme for desert greening', 'Rural employment in forest areas'], 0,
    'Developed under the UNFCCC. India has emphasised the "plus" part — conservation and sustainable management.'],
  ['Pradhan Mantri Van Dhan Yojana (2018), implemented by TRIFED, promotes:', ['Value addition and marketing of minor forest produce by tribal self-help groups', 'Timber exports', 'Tiger tourism', 'Urban forests'], 0,
    'Van Dhan Vikas Kendras cluster tribal gatherers. The MSP for MFP scheme provides price support.'],
  ['The Aravalli Green Wall project (2023) proposes a green belt about 5 km wide across:', ['Gujarat, Rajasthan, Haryana and Delhi', 'Punjab, Haryana and Himachal', 'Madhya Pradesh and Maharashtra', 'Rajasthan only'], 0,
    'It aims to check desertification spreading east from the Thar and to restore degraded Aravalli land.'],
  ['MISHTI, announced in the Union Budget 2023–24, promotes:', ['Mangrove plantation along the coast and on salt pans', 'Millet processing', 'Solar irrigation', 'Urban lakes'], 0,
    'Mangrove Initiative for Shoreline Habitats & Tangible Incomes. It is paired with Amrit Dharohar for Ramsar wetlands.'],
  ['A forest Working Plan is usually prepared for a period of:', ['10 years', '1 year', '25 years', '50 years'], 0,
    'Prepared under the National Working Plan Code. It prescribes silvicultural systems, felling cycles and protection for each working circle.'],
] },
{ p: 'PT', t: 'Silviculture & Forest Protection', w: 3, q: [
  ['The world’s oldest teak plantation, Conolly’s Plot, is at:', ['Nilambur, Kerala', 'Dandeli, Karnataka', 'Allapalli, Maharashtra', 'Konni, Kerala'], 0,
    'Raised in the 1840s under H.V. Conolly (Collector of Malabar) by Chathu Menon.'],
  ['The teak defoliator is:', ['*Hyblaea puera*', '*Hoplocerambyx spinicornis*', '*Eutectona machaeralis*', '*Hypsipyla robusta*'], 0,
    '*Eutectona machaeralis* is the teak skeletoniser; *Hoplocerambyx spinicornis* is the sal heartwood borer; *Hypsipyla* bores shoots of Meliaceae (toon, mahogany).'],
  ['Spike disease of sandalwood is caused by:', ['A phytoplasma', 'A fungus', 'A nematode', 'A bacterium with a cell wall'], 0,
    'Leaves become small and crowded ("spiked") and the tree dies in a few years. Spread by insect vectors; infected trees must be removed.'],
  ['Which tree generally does NOT coppice?', ['Chir pine (*Pinus roxburghii*)', 'Teak (*Tectona grandis*)', 'Sal (*Shorea robusta*)', '*Eucalyptus*'], 0,
    'Most conifers cannot resprout from stumps, so they are regenerated from seed (e.g., uniform shelterwood). Teak and sal are managed as coppice in some working circles.'],
  ['The selection system of silviculture is most suitable for:', ['Uneven-aged forests on steep hill slopes where continuous cover is needed', 'Even-aged plantations of fast-growing species', 'Coppice forests of eucalyptus', 'Agroforestry on farmland'], 0,
    'Mature trees are removed singly or in small groups, keeping the canopy intact against erosion. Clear felling suits even-aged plantations.'],
  ['The rotation of maximum volume production is reached when:', ['Mean annual increment (MAI) is at its maximum, where MAI equals current annual increment', 'Current annual increment first starts rising', 'The tree reaches maximum height', 'The tree begins seeding'], 0,
    'Financial rotation is usually shorter; technical rotation depends on the size needed for the product (e.g., poles or saw logs).'],
  ['The invasive tree threatening the Banni grasslands of Kutch is:', ['*Prosopis juliflora*', '*Acacia nilotica*', '*Prosopis cineraria*', '*Salvadora persica*'], 0,
    'Introduced to check desertification, it now suppresses native grasses and water. *Lantana camara*, *Chromolaena* and *Mikania* are major invasives in forests.'],
  ['The Indian Forest (Amendment) Act, 2017 removed from the definition of "tree":', ['Bamboo grown in non-forest areas', 'Teak grown on private land', 'All fruit trees', 'Eucalyptus'], 0,
    'Farmers can now grow, fell and transport bamboo from non-forest land without felling or transit permits. The National Bamboo Mission supports value chains.'],
  ['The Supreme Court (2021) ordered undergrounding or diverters on power lines mainly to protect the:', ['Great Indian Bustard', 'Lesser florican', 'Indian vulture', 'Sarus crane'], 0,
    'Collision with overhead power lines is the main cause of death of this critically endangered bird in Rajasthan and Gujarat (M.K. Ranjitsinh case).'],
  ['Forest fires in the chir pine forests of Uttarakhand spread mainly because:', ['Dry, resinous pine needles accumulate on the forest floor in summer', 'Pine trees ignite spontaneously', 'Lightning is very frequent in winter', 'Monsoon winds carry sparks'], 0,
    'Most fires are surface fires in April–June. Measures: fire lines, controlled burning, needle collection for briquettes, community fire watchers, and FSI’s satellite fire alerts.'],
] },
{ p: 'PT', t: 'Situational Judgement (Officer-like Qualities)', w: 2, q: [
  ['Villagers’ cattle repeatedly graze in a newly planted regeneration area in your range. The best first step is to:', ['Meet the villagers and the JFM committee, explain the damage, arrange fodder alternatives and closure rules, and enforce the law if they persist', 'Seize all cattle immediately and file cases', 'Ignore it — grazing is a traditional right', 'Fence the area without talking to anyone'], 0,
    'Boards look for firmness with empathy: dialogue, alternatives and participation first, legal action as a last resort.'],
  ['A forest fire breaks out at night in your range and staff are short. You should:', ['Mobilise fire watchers, the JFM committee and villagers, cut fire lines, inform seniors and the district administration, and lead from the front while keeping everyone safe', 'Wait for morning when visibility improves', 'Send a report and wait for instructions', 'Ask villagers to handle it alone'], 0,
    'Quick decisions, coordination, leadership and safety are the key officer-like qualities.'],
  ['A local politician pressures you to overlook illegal felling by his supporters. You should:', ['Politely refuse, act as the law requires, record everything and keep seniors informed', 'Agree quietly to avoid trouble', 'Go to the media immediately', 'Take leave until the matter settles'], 0,
    'Integrity and rule of law, handled tactfully and with proper documentation.'],
  ['An elephant has damaged crops and a crowd is blocking the highway demanding compensation. You should:', ['Talk to them calmly, start ex-gratia processing at once under the rules, explain prevention measures (early warning, barriers, rapid response teams) and coordinate with police', 'Order a lathi-charge to clear the road', 'Promise compensation far above the norms', 'Stay away until the crowd disperses'], 0,
    'Show empathy, speed and a long-term view: people’s support is essential for conservation.'],
  ['Tribal families are collecting minor forest produce inside a sanctuary. You should first:', ['Check their recognised rights under FRA and help them collect sustainably within the law', 'Evict them at once', 'Fine everyone found inside', 'Close the sanctuary to all people'], 0,
    'FRA recognises rights to MFP. Relocation from critical wildlife habitat is allowed only with informed consent and fair rehabilitation.'],
  ['You find evidence that a subordinate is taking bribes from timber traders. You should:', ['Secure the evidence, start action under the conduct rules, inform vigilance and tighten checking systems', 'Warn him privately and forget it', 'Publicly humiliate him in front of staff', 'Transfer him to another range quietly'], 0,
    'Fair process, zero tolerance and system correction together.'],
  ['During the interview you are asked a question whose answer you do not know. You should:', ['Say honestly that you do not know, and if possible say how you would find out', 'Guess confidently', 'Change the topic', 'Argue that the question is unfair'], 0,
    'Boards value honesty and composure over bluffing.'],
  ['A board member strongly disagrees with your view on a development project in a forest. You should:', ['Acknowledge valid points, calmly give your reasons with facts and stay open to other views', 'Give up your view at once', 'Argue until the member agrees', 'Stay silent'], 0,
    'Show balance and conviction without rigidity.'],
  ['A leopard has strayed into a town and a crowd is gathering. The correct approach is to:', ['Control the crowd with police, keep an escape route open for the animal, and use a trained team to tranquilise only if needed, following the SOP', 'Let people chase it back into the forest', 'Shoot it immediately', 'Wait until it attacks someone'], 0,
    'The standard operating procedures for human–leopard conflict put crowd management first — most conflicts become worse because of crowds.'],
  ['A road project needs diversion of 20 ha of forest. As DFO you should:', ['Examine alternatives to reduce diversion, process it under the forest conservation law with FRA compliance and Gram Sabha consent, and ensure compensatory afforestation and mitigation such as animal passages', 'Refuse all development in forests', 'Approve it immediately to avoid delay', 'Ask the contractor to start work while papers are processed'], 0,
    'Balance development with conservation, following due process.'],
] },
{ p: 'PT', t: 'Current Forestry & Environment Issues', w: 2, q: [
  ['The Great Nicobar Island development project has raised concerns mainly about:', ['Felling of tropical rainforest, leatherback turtle nesting at Galathea Bay and the rights of the Shompen tribe', 'Desertification in Rajasthan', 'Glacier retreat', 'Coal mining in Chhattisgarh'], 0,
    'The project includes a transshipment port, airport and township. Other concerns: seismic risk, coral reefs and endemic species such as the Nicobar megapode.'],
  ['India’s Carbon Credit Trading Scheme, 2023 was notified under the:', ['Energy Conservation Act, 2001 (as amended in 2022)', 'Environment (Protection) Act, 1986', 'Forest (Conservation) Act, 1980', 'Air Act, 1981'], 0,
    'The Bureau of Energy Efficiency administers it. The separate Green Credit Programme was notified under the Environment (Protection) Act.'],
  ['The first activity for which a Green Credit methodology was notified is:', ['Tree plantation on degraded land', 'Solar rooftop installation', 'Electric vehicle use', 'Mangrove removal'], 0,
    'State forest departments identify degraded land; participants fund plantation and earn credits after a set period of survival and growth.'],
  ['FSI’s forest fire alert system mainly uses:', ['Satellite fire detections from MODIS and VIIRS sensors', 'Ground patrols only', 'Weather balloons', 'Radio collars on animals'], 0,
    'Alerts go to forest officers by SMS and email, and there is also a pre-fire danger-rating forecast.'],
  ['Which pair is correctly matched (conservation project and focal species)?', ['Project Cheetah — Kuno National Park', 'Project Elephant — Gir', 'Project Snow Leopard — Sundarbans', 'Project Dolphin — Thar desert'], 0,
    'Project Dolphin (2020) is for the Gangetic river dolphin; the snow leopard programme covers the Himalayan states.'],
] }
);
