/* PYQ-linked MCQs — IFoS 2025 Agriculture Paper I (topic-level PYQs from the volume anchors). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Soil Genesis, Classification & Properties', w: 3, pyq: 'IFoS-2025-A1-Q1a', q: [
  ['Soil structure refers to:', ['The arrangement of soil particles into aggregates (peds)', 'The proportion of sand, silt and clay', 'The colour of soil', 'The depth of soil'], 0,
    'Texture is the particle-size distribution; structure is how particles are grouped.'],
  ['Prismatic soil structure is characterised by:', ['Vertically elongated peds with flat tops, typical of subsoils in arid and semi-arid regions', 'Thin horizontal plates', 'Small rounded crumbs', 'Single loose grains'], 0,
    'It often forms in clayey B horizons that shrink and crack on drying.'],
  ['Columnar structure, with rounded tops, is typical of:', ['B horizons of sodic (natric) soils', 'Forest surface soils', 'Sand dunes', 'Peat soils'], 0,
    'Sodium dispersion rounds the tops of the prisms.'],
  ['Granular and crumb structures are most common in:', ['Surface horizons rich in organic matter and biological activity', 'Compacted subsoils', 'Sodic B horizons', 'Rock'], 0,
    'Crumbs are more porous than granules.'],
  ['Platy structure usually indicates:', ['Compaction or an eluvial (E) horizon', 'High organic matter', 'Good drainage', 'Sodicity'], 0,
    'Plates restrict root growth and water movement.'],
  ['Glomalin, a glue-like glycoprotein that stabilises soil aggregates, is produced by:', ['Arbuscular mycorrhizal fungi', 'Earthworms', 'Nitrifying bacteria', 'Plant roots only'], 0,
    'Polysaccharides from microbes and roots also bind aggregates.'],
  ['Aggregate stability is commonly expressed as:', ['Mean weight diameter (MWD) from wet sieving', 'Bulk density', 'Cation exchange capacity', 'pH'], 0,
    'Yoder’s wet-sieving apparatus is used.'],
  ['Which cation promotes flocculation and good structure, and which disperses soil?', ['Calcium flocculates; sodium disperses', 'Sodium flocculates; calcium disperses', 'Both disperse', 'Both flocculate'], 0,
    'This is why gypsum improves sodic soils.'],
  ['In rice cultivation, puddling:', ['Deliberately destroys soil structure to reduce percolation and ease transplanting', 'Improves aggregate stability', 'Increases drainage', 'Is done only in dry soil'], 0,
    'It creates a hardpan that can hamper the next crop (e.g., wheat).'],
  ['Structureless soils are described as:', ['Single-grain (e.g., loose sand) or massive (e.g., dense clay)', 'Granular', 'Blocky', 'Prismatic'], 0,
    'Neither has distinct peds.'],
] },
{ p: 'A1', t: 'Agroforestry & Social Forestry', w: 3, pyq: 'IFoS-2025-A1-Q1b', q: [
  ['Hedgerow intercropping (alley cropping) means:', ['Growing crops in alleys between hedgerows of fast-growing, often N-fixing, woody species that are pruned periodically', 'Growing crops under a closed forest', 'Planting hedges around the farm boundary only', 'Growing two crops in alternate rows'], 0,
    'Prunings are used as mulch, green manure or fodder.'],
  ['Alley cropping was developed mainly at:', ['IITA, Ibadan (B.T. Kang and co-workers)', 'ICRISAT, Hyderabad', 'CIMMYT, Mexico', 'IRRI, Philippines'], 0,
    'Worked out in the humid tropics of West Africa in the 1970s–80s.'],
  ['Contour hedgerows on slopes in the "SALT" system stand for:', ['Sloping Agricultural Land Technology', 'Soil and Land Treatment', 'Saline Agriculture Land Technique', 'Small Area Land Tillage'], 0,
    'Developed in the Philippines; hedgerows gradually form natural terraces.'],
  ['The main benefit of hedgerow prunings in alley cropping is:', ['Adding nitrogen and organic matter to the crop alleys', 'Increasing soil salinity', 'Removing all weeds permanently', 'Increasing runoff'], 0,
    'Legume prunings can supply a significant share of the crop’s N.'],
  ['A major limitation of alley cropping, especially in drier areas, is:', ['Competition of hedgerows with crops for water, nutrients and light', 'Excess nitrogen', 'Too little labour needed', 'Frost damage to hedges'], 0,
    'Frequent pruning also needs a lot of labour.'],
  ['Alley cropping is most successful in:', ['Humid and sub-humid tropics', 'Arid deserts', 'Cold temperate uplands', 'Saline coastal flats'], 0,
    'Adequate rainfall reduces tree–crop competition for water.'],
  ['Species commonly used for hedgerows include:', ['*Leucaena*, *Gliricidia*, *Sesbania* and *Calliandra*', '*Pinus* and *Cedrus*', '*Eucalyptus* only', 'Teak and sal'], 0,
    'They coppice well and fix nitrogen.'],
  ['Over time, contour hedgerows on slopes:', ['Trap soil and form natural terraces', 'Increase erosion', 'Lower soil fertility always', 'Make the slope steeper'], 0,
    'Sediment builds up on the uphill side of each hedge.'],
  ['Hedgerows in alley cropping are usually spaced:', ['A few metres apart (commonly about 4–6 m)', '50 m apart', '0.5 m apart', 'Randomly'], 0,
    'Spacing balances crop area against hedgerow benefits.'],
  ['Hedgerows are pruned mainly to:', ['Reduce shading and competition and supply mulch or fodder', 'Kill the hedge', 'Increase shading', 'Produce timber'], 0,
    'Pruning height is usually low (around 0.5–1 m).'],
] },
{ p: 'A1', t: 'Agro-climatic Zones & Cropping Systems', w: 3, pyq: 'IFoS-2025-A1-Q1c', q: [
  ['Which is a biotic factor affecting crop production?', ['Insect pests, diseases and weeds', 'Rainfall', 'Soil texture', 'Day length'], 0,
    'Beneficial biotic factors include pollinators and soil microbes.'],
  ['Cardinal temperatures of a crop are its:', ['Minimum, optimum and maximum temperatures for growth or a process', 'Day and night temperatures', 'Soil and air temperatures', 'Average monthly temperatures'], 0,
    'Growth stops below the minimum and above the maximum.'],
  ['If Tmax is 30 °C and Tmin is 20 °C with a base temperature of 10 °C, the growing degree days for that day are:', ['15', '25', '10', '5'], 0,
    'GDD = (Tmax + Tmin)/2 − Tbase = 25 − 10 = 15.'],
  ['Edaphic factors are those related to:', ['Soil', 'Climate', 'Topography', 'Living organisms'], 0,
    'E.g., soil depth, texture, pH, fertility and drainage.'],
  ['Physiographic (topographic) factors affect crops mainly through:', ['Altitude, slope and aspect, which change temperature, moisture and erosion', 'Pest attack', 'Market prices', 'Seed quality'], 0,
    'South-facing slopes in the Himalaya are warmer and drier.'],
  ['Strong winds harm crops mainly by:', ['Causing lodging and increasing water loss', 'Increasing photosynthesis', 'Reducing evaporation', 'Adding nutrients'], 0,
    'Windbreaks and resistant varieties reduce damage.'],
  ['Chilling injury is a risk for:', ['Tropical crops such as banana and mango at low, above-freezing temperatures', 'Wheat in winter', 'Temperate apples', 'Barley'], 0,
    'Chilling damages membranes of cold-sensitive species.'],
  ['Pollinators such as bees are an example of:', ['A beneficial biotic factor', 'An abiotic factor', 'An edaphic factor', 'A harmful factor'], 0,
    'Crops such as mustard, sunflower and many fruits gain yield from bee pollination.'],
  ['Light affects crops through its:', ['Intensity, quality (wavelength) and duration', 'Weight', 'Colour of the soil', 'Salinity'], 0,
    'Duration controls photoperiodic responses.'],
  ['Allelopathy from crop residues or weeds is an example of:', ['A biotic (chemical) interaction affecting crops', 'A climatic factor', 'An edaphic factor only', 'A physiographic factor'], 0,
    'E.g., residues of sunflower or sorghum can inhibit the next crop.'],
] },
{ p: 'A1', t: 'Crop Production', w: 3, pyq: 'IFoS-2025-A1-Q1d', q: [
  ['Short-duration varieties help in drylands mainly by:', ['Completing the life cycle within the limited period of soil moisture', 'Needing more water', 'Growing taller', 'Producing more straw'], 0,
    'They escape terminal drought.'],
  ['Sahbhagi Dhan is:', ['A short-duration, drought-tolerant rice variety for rainfed uplands', 'A long-duration basmati variety', 'A wheat variety', 'A hybrid maize'], 0,
    'Matures in roughly 105–110 days.'],
  ['Short-duration rice varieties in Punjab and Haryana help reduce stubble burning because:', ['Earlier harvest leaves more time for residue management before wheat sowing', 'They produce no straw', 'Their straw cannot burn', 'They are grown in winter'], 0,
    'E.g., PR 126 matures much earlier than older long-duration varieties like Pusa 44.'],
  ['Compared with Pusa Basmati 1121, Pusa Basmati 1509 is valued mainly for its:', ['Shorter duration, saving water and time', 'Longer duration', 'Red grain', 'Tall stature'], 0,
    'Both are IARI basmati varieties.'],
  ['Extra-short-duration pigeonpea allows:', ['A pigeonpea–wheat rotation in north India', 'Growing pigeonpea only in summer', 'Pigeonpea to be ratooned for years', 'Pigeonpea without rain'], 0,
    'It matures early enough to vacate the field for wheat.'],
  ['A general trade-off of short-duration varieties is:', ['Lower maximum yield potential than long-duration varieties in good conditions', 'Higher water use', 'Always lower quality', 'Greater lodging'], 0,
    'Yield per day of crop duration can still be higher.'],
  ['Short-duration varieties support intensification by:', ['Allowing more crops per year on the same land', 'Reducing the number of crops', 'Needing fallow periods', 'Needing more land'], 0,
    'They are central to multiple cropping.'],
  ['In contingency planning after a late monsoon onset, farmers are advised to:', ['Switch to short-duration varieties or crops', 'Sow long-duration varieties', 'Wait for the next year', 'Double the seed rate of long-duration crops'], 0,
    'District contingency plans list suitable options.'],
  ['Short-duration varieties can lower irrigation needs because:', ['They spend fewer days in the field, so total crop water use falls', 'They need no water', 'They transpire more', 'They grow only in rainy weather'], 0,
    'This matters for groundwater-stressed regions.'],
  ['Short-duration rice in coastal areas helps farmers avoid:', ['Late-season cyclones and salinity build-up', 'Frost', 'Snow', 'Winter drought'], 0,
    'Timing harvest before risky periods reduces losses.'],
] },
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'IFoS-2025-A1-Q1e', q: [
  ['Water has CO₃²⁻ 1.0, HCO₃⁻ 5.0, Ca²⁺ 2.0 and Mg²⁺ 1.5 meq/L. Its RSC is:', ['2.5 meq/L', '9.5 meq/L', '−2.5 meq/L', '1.0 meq/L'], 0,
    'RSC = (1.0 + 5.0) − (2.0 + 1.5) = 2.5 meq/L — borderline/unsuitable.'],
  ['305 mg/L of bicarbonate equals:', ['5 meq/L', '305 meq/L', '61 meq/L', '0.5 meq/L'], 0,
    'meq/L = mg/L ÷ equivalent weight; HCO₃⁻ = 61. (CO₃²⁻ 30, Ca²⁺ 20, Mg²⁺ 12.2, Na⁺ 23.)'],
  ['Water with RSC below 1.25 meq/L is generally:', ['Safe for irrigation', 'Unsuitable', 'Toxic to all crops', 'Only for rice'], 0,
    '1.25–2.5 is marginal; above 2.5 unsuitable without treatment.'],
  ['A negative RSC value means that:', ['Calcium and magnesium exceed carbonate and bicarbonate, so there is no sodicity hazard from carbonates', 'The water is highly sodic', 'The water is saline', 'The water has no calcium'], 0,
    'Negative values are usually reported as nil RSC.'],
  ['High-RSC water increases soil sodicity because:', ['Calcium and magnesium precipitate as carbonates, leaving sodium to dominate exchange sites', 'It adds calcium', 'It lowers pH', 'It removes sodium'], 0,
    'The soil pH and ESP rise over time.'],
  ['The concept of residual sodium carbonate was proposed by:', ['Eaton (1950)', 'Richards (1954)', 'Wilcox (1955)', 'Scofield (1936)'], 0,
    'Richards (USSL Handbook 60) gave the EC–SAR classification.'],
  ['The gypsum needed to neutralise 1 meq/L of RSC in 1,000 m³ of irrigation water is about:', ['86 kg (pure gypsum)', '8.6 kg', '860 kg', '1 kg'], 0,
    'The equivalent weight of gypsum (CaSO₄·2H₂O) is 86.'],
  ['Water has Na⁺ 10, Ca²⁺ 3 and Mg²⁺ 1 meq/L. Its sodium adsorption ratio (SAR) is about:', ['7.1', '2.5', '10', '40'], 0,
    'SAR = Na ÷ √[(Ca + Mg)/2] = 10 ÷ √2 ≈ 7.1.'],
  ['High-RSC groundwater is a widespread problem in parts of:', ['Haryana, Punjab, Rajasthan and western UP', 'Kerala and Goa', 'Assam and Meghalaya', 'Andaman Islands'], 0,
    'Gypsum beds in water channels are one remedy.'],
  ['RSC is expressed in:', ['Milliequivalents per litre (meq/L)', 'dS/m', 'mg/kg', 'Percent'], 0,
    'EC is expressed in dS/m (salinity).'],
] },
{ p: 'A1', t: 'Agroforestry & Social Forestry', w: 3, pyq: 'IFoS-2025-A1-Q2a', q: [
  ['The World Agroforestry Centre (ICRAF) is headquartered at:', ['Nairobi, Kenya', 'New Delhi', 'Bogor, Indonesia', 'Rome'], 0,
    'CIFOR (forestry research) is at Bogor.'],
  ['Agroforestry, as defined by Lundgren and Raintree (1982), involves:', ['Deliberate growing of woody perennials with crops and/or animals, with ecological and economic interactions', 'Only forest plantations', 'Only fruit orchards', 'Only grazing in forests'], 0,
    'The key word is interaction between the components.'],
  ['A widely used classification of agroforestry systems (structural, functional, socio-economic, ecological) was given by:', ['P.K.R. Nair', 'Dietrich Brandis', 'Norman Borlaug', 'M.S. Swaminathan'], 0,
    'Structurally: agrisilvicultural, silvopastoral and agrosilvopastoral systems.'],
  ['"Extension forestry" refers to planting trees:', ['Along roads, canals, railway lines and on village common lands', 'On farmers’ own fields', 'Inside reserved forests', 'Only in cities'], 0,
    'Farm forestry is tree growing by farmers on their own land.'],
  ['A major criticism of social forestry in the 1980s was that:', ['Farm eucalyptus plantations served markets rather than fuel and fodder needs of the poor', 'Too many native trees were planted', 'It reduced timber supply', 'It was fully community-led'], 0,
    'Lessons from this shaped later participatory approaches such as JFM.'],
  ['Relaxing felling and transit rules for farm-grown trees helps agroforestry because it:', ['Makes harvest and sale easier, raising returns to farmers', 'Stops tree planting', 'Increases forest diversion', 'Reduces farm income'], 0,
    'The National Agroforestry Policy (2014) called for such reforms.'],
  ['Agroforestry contributes to India’s climate goals mainly by:', ['Increasing tree cover outside forests and adding to the carbon sink', 'Increasing methane', 'Reducing forest cover', 'Replacing crops entirely'], 0,
    'India’s NDC includes an additional carbon sink through forest and tree cover.'],
  ['A silvopastoral system is especially suited to:', ['Degraded, marginal lands used for grazing', 'Irrigated rice land', 'Urban plots', 'Flooded fields'], 0,
    'Trees provide fodder and shade; grasses cover the soil.'],
  ['Trees on farm bunds (boundary planting) are popular because they:', ['Use little crop land while giving timber, fuel and fodder', 'Need the whole field', 'Always shade crops completely', 'Cannot be harvested'], 0,
    'Species include poplar, eucalyptus, *Melia dubia* and teak.'],
  ['Social forestry aims primarily to:', ['Meet local needs for fuel, fodder and small timber and reduce pressure on forests', 'Maximise timber exports', 'Replace natural forests', 'Protect only wildlife'], 0,
    'It also provides employment and environmental benefits.'],
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: 'IFoS-2025-A1-Q2b', q: [
  ['Fulvic acid is the humus fraction that is soluble in:', ['Both alkali and acid', 'Alkali but not acid', 'Neither alkali nor acid', 'Only water'], 0,
    'Humic acid dissolves in alkali but precipitates in acid; humin is insoluble in both.'],
  ['Soil organic carbon is commonly estimated by the:', ['Walkley–Black wet oxidation method (dichromate)', 'Olsen method', 'Kjeldahl method', 'Bray method'], 0,
    'Kjeldahl estimates total nitrogen.'],
  ['Soil organic matter is often estimated from organic carbon by multiplying by:', ['1.724 (van Bemmelen factor)', '0.58', '10', '2.65'], 0,
    'It assumes organic matter contains about 58% carbon.'],
  ['Soil microbial biomass carbon is measured by the:', ['Chloroform fumigation–extraction method', 'Hydrometer method', 'Tensiometer', 'Pipette method'], 0,
    'Fumigation kills microbes, releasing their carbon for extraction.'],
  ['Dehydrogenase activity in soil is used as an index of:', ['Overall microbial activity', 'Soil texture', 'Soil colour', 'Salinity'], 0,
    'Urease and phosphatase activities indicate specific nutrient cycling processes.'],
  ['The term "rhizosphere" was coined by:', ['Lorenz Hiltner (1904)', 'Selman Waksman', 'Sergei Winogradsky', 'Louis Pasteur'], 0,
    'The rhizosphere has far more microbes than bulk soil (high R:S ratio).'],
  ['The "priming effect" in soil refers to:', ['Faster decomposition of native organic matter after adding fresh organic material', 'Seed priming', 'Liming effect', 'Nitrogen fixation'], 0,
    'Fresh inputs stimulate microbes that also attack older organic matter.'],
  ['The earthy smell of moist soil comes mainly from geosmin produced by:', ['Actinomycetes such as *Streptomyces*', 'Earthworms', 'Plant roots', 'Nitrifying bacteria'], 0,
    'Actinomycetes are also sources of many antibiotics.'],
  ['Soil organic matter raises cation exchange capacity mainly because humus:', ['Has a very large surface area with many negatively charged groups', 'Is positively charged', 'Is inert', 'Contains sand'], 0,
    'Humus CEC can exceed 200 cmol/kg.'],
  ['Soil respiration (CO₂ evolution) is a measure of:', ['Biological activity of soil organisms and roots', 'Soil texture', 'Soil pH', 'Bulk density'], 0,
    'It rises with temperature, moisture and fresh organic inputs.'],
] },
{ p: 'A1', t: 'Environment, Organic & Natural Farming', w: 2, pyq: 'IFoS-2025-A1-Q2c', q: [
  ['Rising atmospheric CO₂ ("CO₂ fertilisation") benefits which crops more?', ['C₃ crops such as wheat, rice and pulses', 'C₄ crops such as maize and sorghum', 'Both equally', 'Neither'], 0,
    'C₄ photosynthesis is already nearly CO₂-saturated.'],
  ['Terminal heat stress in wheat mainly harms:', ['Grain filling, when temperatures exceed about 30 °C', 'Germination', 'Tillering in December', 'Root growth only'], 0,
    'Timely sowing and heat-tolerant varieties help.'],
  ['Global studies estimate that each 1 °C rise in temperature reduces wheat yield by roughly:', ['6%', '0.1%', '50%', '25%'], 0,
    'Estimates vary by region; heat during grain filling is critical.'],
  ['A rise in night-time temperature reduces rice yield mainly by:', ['Increasing respiration losses and reducing grain filling', 'Increasing photosynthesis', 'Reducing pests', 'Improving pollination'], 0,
    'Field data from the Philippines linked warmer nights to lower yields.'],
  ['Ground-level ozone affects crops by:', ['Damaging leaf tissue and reducing photosynthesis and yield', 'Increasing yield', 'Fixing nitrogen', 'Reducing pests'], 0,
    'It is formed from vehicle and industrial pollutants in sunlight.'],
  ['Climate change is expected to affect insect pests by:', ['Expanding their range and increasing the number of generations per year', 'Eliminating all pests', 'Reducing their reproduction everywhere', 'Having no effect'], 0,
    'Warmer winters allow more survival.'],
  ['Sea-level rise threatens coastal agriculture mainly through:', ['Salinity intrusion into soils and groundwater', 'Increasing freshwater supply', 'Reducing cyclones', 'Lowering temperatures'], 0,
    'Salt-tolerant varieties and embankments are adaptation measures.'],
  ['An adaptation measure for climate change in agriculture is:', ['Adjusting sowing dates and using heat- and drought-tolerant varieties', 'Increasing residue burning', 'Using more flood irrigation everywhere', 'Growing one crop only'], 0,
    'Crop diversification and conservation agriculture also help.'],
  ['Mitigation in agriculture means:', ['Reducing greenhouse-gas emissions or increasing carbon sequestration', 'Adjusting to higher temperatures', 'Relocating farms', 'Increasing fertiliser use'], 0,
    'Adaptation reduces harm; mitigation tackles the cause.'],
  ['Increased frequency of extreme rainfall events mainly increases the risk of:', ['Floods, waterlogging and soil erosion', 'Frost', 'Snowfall', 'Wind erosion only'], 0,
    'Rainfall is becoming more concentrated in fewer heavy events.'],
] },
{ p: 'A1', t: 'Crop Production', w: 3, pyq: 'IFoS-2025-A1-Q3a', q: [
  ['The optimum sowing time for timely sown irrigated wheat in the north-western plains is:', ['First half of November', 'September', 'Late December', 'February'], 0,
    'Late sowing (December) exposes grain filling to heat.'],
  ['The usual seed rate for timely sown wheat is about:', ['100 kg/ha', '25 kg/ha', '250 kg/ha', '10 kg/ha'], 0,
    'About 125 kg/ha is used for late sowing.'],
  ['Row spacing commonly recommended for wheat is:', ['20–22.5 cm', '60 cm', '5 cm', '1 m'], 0,
    'Closer spacing (about 18 cm) is used for late sowing.'],
  ['A typical fertiliser recommendation for irrigated wheat is about:', ['120 : 60 : 40 kg N : P₂O₅ : K₂O per ha', '20 : 10 : 0', '300 : 150 : 100', '0 : 0 : 60'], 0,
    'Half the N at sowing, the rest at first irrigation; adjust to soil tests.'],
  ['With ample water, irrigated wheat is usually irrigated at about:', ['Six stages — CRI, tillering, jointing, flowering, milk and dough', 'One stage only', 'Every day', 'Only after harvest'], 0,
    'If water is limited, CRI is the most important.'],
  ['Sulfosulfuron is used in wheat mainly to control:', ['*Phalaris minor* and some broadleaf weeds', 'Wild rice', 'Water hyacinth', 'Nutsedge only'], 0,
    'A sulfonylurea (ALS inhibitor).'],
  ['HD 2967, a popular wheat variety, was developed by:', ['IARI, New Delhi', 'IRRI', 'CIMMYT only', 'CRRI, Cuttack'], 0,
    '"HD" varieties come from IARI; "DBW" from IIWBR, Karnal; "PBW" from PAU, Ludhiana.'],
  ['Zero-till wheat after rice is sown with machines such as:', ['Zero-till drill or Happy Seeder', 'Rotavator only', 'Mouldboard plough', 'Transplanter'], 0,
    'Saves time, fuel and water, and allows timely sowing.'],
  ['Yellow (stripe) rust of wheat is favoured by:', ['Cool, humid weather, especially in the northern hills and north-western plains', 'Hot, dry weather', 'Waterlogging only', 'Heavy nitrogen at harvest'], 0,
    'Caused by *Puccinia striiformis*; resistant varieties are the main control.'],
  ['Durum wheat (*Triticum durum*) is preferred for pasta because:', ['Its hard, high-protein grain with yellow pigment makes good semolina', 'It is soft and starchy', 'It has red grain', 'It has no gluten'], 0,
    'It is grown mainly in central India (e.g., Madhya Pradesh).'],
] },
{ p: 'A1', t: 'Weed Science', w: 2, pyq: 'IFoS-2025-A1-Q3b', q: [
  ['Which is a typical characteristic of successful weeds?', ['Prolific seed production with long seed dormancy and viability', 'Very few seeds', 'No dormancy', 'Slow growth'], 0,
    'Also rapid growth, vegetative spread, adaptability and crop mimicry.'],
  ['*Lantana camara* was introduced to India in 1807 as:', ['An ornamental plant, at the Calcutta Botanic Garden', 'A fodder crop', 'A timber tree', 'A medicinal crop'], 0,
    'It now covers large areas of Indian forests, reducing native plant diversity.'],
  ['*Lantana* affects forest biodiversity partly by:', ['Forming dense thickets, releasing allelochemicals and increasing fire risk', 'Improving native regeneration', 'Fixing nitrogen for trees', 'Feeding all herbivores'], 0,
    'Removal methods include the cut-rootstock method.'],
  ['*Chromolaena odorata*, a serious invader of the Western Ghats and North-East, is commonly called:', ['Siam weed (locally "communist pacha")', 'Water hyacinth', 'Carrot grass', 'Mile-a-minute'], 0,
    'It smothers forest edges and plantations.'],
  ['*Mikania micrantha* ("mile-a-minute") is harmful because it:', ['Climbs over and smothers trees and crops', 'Is a small grass', 'Only grows in water', 'Is edible'], 0,
    'A rust fungus, *Puccinia spegazzinii*, has been released for its biocontrol.'],
  ['*Ageratina adenophora* (Crofton weed) is a major invader in:', ['The Himalaya and Nilgiri hills', 'The Thar desert', 'Coastal mangroves', 'Indo-Gangetic plains only'], 0,
    'It suppresses native vegetation in hill grasslands.'],
  ['The aquatic weed *Salvinia molesta* has been controlled biologically with the weevil:', ['*Cyrtobagous salviniae*', '*Neochetina eichhorniae*', '*Zygogramma bicolorata*', '*Trichogramma chilonis*'], 0,
    '*Neochetina* is used on water hyacinth; *Zygogramma* on Parthenium.'],
  ['Exotic weeds threaten biodiversity mainly by:', ['Outcompeting native species and altering habitats', 'Increasing native species', 'Improving soil only', 'Having no impact'], 0,
    'Invasive species are a major driver of biodiversity loss.'],
  ['Seed dormancy helps weeds persist because:', ['Seeds germinate over many years, escaping one-time control', 'All seeds germinate together', 'Seeds die quickly', 'Seeds cannot survive in soil'], 0,
    'This builds a large weed seed bank in soil.'],
  ['Integrated management of invasive weeds combines:', ['Prevention, mechanical removal, biological control, herbicides and restoration with native species', 'Only burning', 'Only herbicides', 'Ignoring the problem'], 0,
    'Restoration prevents re-invasion of cleared areas.'],
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: 'IFoS-2025-A1-Q3c', q: [
  ['Ammonia volatilisation from urea is highest when urea is:', ['Surface-applied on alkaline or calcareous soils in warm weather', 'Deep-placed in acid soil', 'Applied to cold, wet soil and incorporated', 'Applied as neem-coated urea in split doses'], 0,
    'Urease converts urea to ammonium carbonate; high pH releases NH₃ gas.'],
  ['Urease inhibitors such as NBPT reduce nitrogen loss by:', ['Slowing urea hydrolysis, reducing ammonia volatilisation', 'Stopping nitrification', 'Increasing leaching', 'Fixing nitrogen'], 0,
    'Nitrification inhibitors act on a later step.'],
  ['Nitrate leaching is most severe in:', ['Sandy soils with heavy rainfall or excess irrigation', 'Clay soils in dry weather', 'Soils with no crops ever', 'Frozen soils'], 0,
    'Nitrate moves with drainage water below the root zone.'],
  ['The correct sequence of denitrification is:', ['NO₃⁻ → NO₂⁻ → NO → N₂O → N₂', 'N₂ → NH₃ → NO₃⁻', 'NH₄⁺ → NO₂⁻ → NO₃⁻', 'N₂O → NO₃⁻ → NH₄⁺'], 0,
    'Carried out by facultative anaerobes such as *Pseudomonas*, *Paracoccus* and *Bacillus*.'],
  ['Denitrification is favoured by:', ['Low oxygen, available carbon, nitrate and warm temperatures', 'High oxygen and dry soil', 'Low temperature and no carbon', 'Absence of nitrate'], 0,
    'Waterlogged soils after fertiliser application are hot spots.'],
  ['Nitrogen use efficiency of applied fertiliser in lowland rice in India is typically about:', ['30–40%', '90–100%', '5%', '70–80%'], 0,
    'Losses through volatilisation, denitrification and leaching are large.'],
  ['Slow-release or coated fertilisers (e.g., sulphur- or polymer-coated urea) reduce N losses by:', ['Releasing nitrogen gradually to match crop uptake', 'Releasing all N at once', 'Increasing volatilisation', 'Stopping plant uptake'], 0,
    'They are costlier than ordinary urea.'],
  ['Deep placement of urea (e.g., urea super-granules) in rice reduces N loss mainly by:', ['Keeping N in the reduced soil layer away from floodwater losses', 'Increasing ammonia volatilisation', 'Placing N on the leaves', 'Oxidising N'], 0,
    'Floodwater pH rises during the day, favouring volatilisation.'],
  ['Incorporating straw with a wide C:N ratio just before sowing can cause:', ['Temporary immobilisation of soil nitrogen by microbes', 'Immediate release of nitrogen', 'Nitrogen fixation', 'Higher nitrate'], 0,
    'Extra N or time for decomposition avoids crop N deficiency.'],
  ['Which practice best improves N use efficiency?', ['Split application based on crop need, using tools like the leaf colour chart', 'Applying all N at sowing', 'Broadcasting urea on floodwater at noon', 'Applying N after harvest'], 0,
    'Right source, rate, time and place (4R nutrient stewardship).'],
] },
{ p: 'A1', t: 'Environment, Organic & Natural Farming', w: 2, pyq: 'IFoS-2025-A1-Q4a', q: [
  ['Peri-urban soils irrigated with untreated sewage often accumulate:', ['Heavy metals such as cadmium, lead, nickel and chromium', 'Only nitrogen', 'Only sand', 'Only calcium'], 0,
    'Vegetables grown there can carry metals into the food chain.'],
  ['The fern *Pteris vittata* is a hyperaccumulator of:', ['Arsenic', 'Nitrogen', 'Sodium', 'Carbon'], 0,
    '*Noccaea (Thlaspi) caerulescens* accumulates zinc and cadmium.'],
  ['Maximum residue limits (MRLs) of pesticides in foods in India are set by:', ['FSSAI', 'NABARD', 'ICAR alone', 'NITI Aayog'], 0,
    'Pesticide registration is done by CIB&RC.'],
  ['A growing soil-pollution concern from plastic mulch films and packaging is:', ['Accumulation of plastic fragments and microplastics in soils', 'Excess nitrogen', 'Higher organic matter', 'Reduced salinity'], 0,
    'Biodegradable mulches and proper collection reduce this.'],
  ['Bioremediation of polluted soil uses:', ['Micro-organisms to degrade or immobilise pollutants', 'Only chemicals', 'Burning the soil', 'Adding more pollutants'], 0,
    'Phytoremediation uses plants; soil washing uses physical/chemical extraction.'],
  ['Continued irrigation with saline groundwater mainly leads to:', ['Salt build-up and secondary salinisation of soils', 'Improved soil structure', 'Acidification', 'Higher organic carbon'], 0,
    'Leaching with good water and drainage are needed.'],
  ['Acid mine drainage pollutes water and soil through:', ['Oxidation of sulphide minerals, producing acidity and dissolving metals', 'Addition of lime', 'Sediment only', 'Excess nitrogen'], 0,
    'Common around coal and metal mines.'],
  ['Sewage sludge (biosolids) can be used on farmland only if:', ['Heavy-metal and pathogen levels are within safety standards', 'It is applied fresh without treatment', 'It is used on vegetables eaten raw', 'It contains industrial waste'], 0,
    'It is a source of organic matter and nutrients when treated.'],
  ['Eutrophication of water bodies near farmland is caused mainly by:', ['Runoff of nitrogen and phosphorus from fertilisers and manures', 'Pesticide residues only', 'Sediment only', 'Cold water'], 0,
    'Leads to algal blooms and oxygen depletion.'],
  ['Pesticide residues in vegetables are best reduced by:', ['Observing waiting periods, using IPM and washing produce', 'Spraying just before harvest', 'Using higher doses', 'Mixing several pesticides'], 0,
    'The pre-harvest interval lets residues decline below MRLs.'],
] },
{ p: 'A1', t: 'Agro-climatic Zones & Cropping Systems', w: 3, pyq: 'IFoS-2025-A1-Q4b', q: [
  ['Punjab and Haryana fall in which Planning Commission agro-climatic region?', ['Trans-Gangetic Plains', 'Upper Gangetic Plains', 'Western Dry Region', 'Central Plateau and Hills'], 0,
    'The Upper Gangetic Plains region covers western and central UP.'],
  ['The 15th agro-climatic region of the Planning Commission is the:', ['Islands region', 'Western Himalayan region', 'Eastern Plateau and Hills', 'Gujarat Plains and Hills'], 0,
    'It covers Andaman & Nicobar and Lakshadweep.'],
  ['Which is one of the 15 Planning Commission agro-climatic regions?', ['West Coast Plains and Ghats', 'Deccan Desert Region', 'Central Himalayan Plateau', 'Northern Island Region'], 0,
    'Others include the East Coast Plains and Hills, and the Southern Plateau and Hills.'],
  ['Leaf reddening in cotton (especially Bt cotton) is commonly linked to:', ['Deficiency of nitrogen and magnesium, often with moisture stress, causing anthocyanin build-up', 'Excess potassium', 'Too much rain in winter', 'Boron toxicity only'], 0,
    'Low temperature late in the season also contributes.'],
  ['Leaf reddening in cotton is commonly corrected by foliar sprays of:', ['Magnesium sulphate and urea', 'Copper sulphate and lime', 'Zinc and iron chelates only', 'Gibberellic acid'], 0,
    'Recommendations are often about 1% MgSO₄ with 2% urea.'],
  ['Reddening and curling of cotton leaf edges ("hopper burn") is caused by:', ['Leafhoppers (jassids)', 'Aphids only', 'Pink bollworm', 'Whitefly honeydew'], 0,
    '*Amrasca biguttula biguttula* injects toxic saliva while feeding.'],
  ['Jute retting is fastest in:', ['Clean, slow-moving, warm water (about 30–34 °C)', 'Stagnant saline water', 'Cold running water', 'Dry soil'], 0,
    'Temperature strongly affects the retting microbes.'],
  ['"Ribbon retting" of jute:', ['Retts stripped bark ribbons in small tanks, saving water and time', 'Burns the stems', 'Uses no microbes', 'Retts whole plants in rivers only'], 0,
    'Useful where large water bodies are scarce.'],
  ['CRIJAF SONA, developed by ICAR-CRIJAF, is:', ['A microbial formulation that speeds jute retting and improves fibre quality', 'A jute variety', 'A herbicide', 'A spinning machine'], 0,
    'ICAR-Central Research Institute for Jute and Allied Fibres, Barrackpore.'],
  ['Over-retting of jute:', ['Weakens the fibre', 'Improves fibre strength', 'Has no effect', 'Increases fibre length'], 0,
    'Under-retting leaves bark attached, giving "croppy" fibre.'],
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: 'IFoS-2025-A1-Q4c', q: [
  ['The most widespread micronutrient deficiency in Indian soils is of:', ['Zinc', 'Molybdenum', 'Chlorine', 'Nickel'], 0,
    'Boron and iron deficiencies are also common in some regions.'],
  ['Micronutrient deficiencies have increased with intensive agriculture mainly because of:', ['High removal by high-yielding crops, use of high-analysis NPK fertilisers and less organic manure', 'More use of FYM', 'Lower yields', 'Less irrigation'], 0,
    'Old fertilisers and manures supplied micronutrients as impurities.'],
  ['High soil pH generally reduces the availability of:', ['Zinc, iron, manganese, copper and boron', 'Molybdenum', 'Calcium', 'Sodium'], 0,
    'Molybdenum becomes more available as pH rises.'],
  ['"Lime-induced chlorosis" in calcareous soils is due mainly to:', ['Iron deficiency caused by high pH and bicarbonate', 'Excess nitrogen', 'Magnesium toxicity', 'Sodium deficiency'], 0,
    'Seen in sugarcane, groundnut, citrus and fruit trees on calcareous soils.'],
  ['Zinc deficiency in flooded rice soils is promoted by:', ['High bicarbonate, high pH and P–Zn interaction', 'Low pH and good aeration', 'High organic matter always', 'Low phosphorus'], 0,
    'Khaira disease of rice is Zn deficiency.'],
  ['Boron deficiency is most common in:', ['Sandy, leached, low-organic-matter soils', 'Heavy clays rich in organic matter', 'Saline soils only', 'Peat soils only'], 0,
    'Boron leaches easily.'],
  ['Available zinc, iron, copper and manganese in soils are extracted with:', ['DTPA (Lindsay and Norvell, 1978)', 'Hot water', 'Olsen’s reagent', 'Ammonium acetate only'], 0,
    'Critical limit for DTPA-Zn is about 0.6 mg/kg.'],
  ['Zincated urea is a fertiliser that:', ['Supplies zinc along with nitrogen', 'Contains no nitrogen', 'Is used to kill weeds', 'Supplies only sulphur'], 0,
    'Notified under the Fertiliser Control Order to tackle Zn deficiency.'],
  ['Low soil organic matter increases micronutrient deficiency because:', ['Organic matter forms natural chelates that keep micronutrients available', 'Organic matter fixes micronutrients permanently', 'Organic matter is toxic', 'It has no effect'], 0,
    'FYM and compost also supply micronutrients directly.'],
  ['A common, cost-effective way to correct zinc deficiency is:', ['Soil application of zinc sulphate (often once in two to three seasons) or foliar sprays', 'Adding lime', 'Burning straw', 'Deep ploughing only'], 0,
    'Residual effects of soil-applied Zn last for more than one crop.'],
] },
{ p: 'A1', t: 'Agricultural Extension', w: 2, pyq: 'IFoS-2025-A1-Q5a', q: [
  ['In Leagans’ (1967) model, extension programme planning begins with:', ['Collection of facts about the situation', 'Evaluation', 'Implementation', 'Budgeting'], 0,
    'Steps: collect facts → analyse the situation → identify problems → set objectives → develop a plan of work → carry it out → evaluate → reconsider.'],
  ['In Leagans’ sequence, the step immediately after identifying problems is:', ['Determining objectives', 'Evaluation', 'Collection of facts', 'Reconsideration'], 0,
    'Objectives state what change is wanted.'],
  ['The last step in Leagans’ planning cycle leads to:', ['Reconsideration, which starts the next planning cycle', 'Closure of the programme forever', 'Collection of taxes', 'Printing of reports only'], 0,
    'Programme planning is a continuous process.'],
  ['A "plan of work" in extension specifies:', ['What will be done, by whom, when, where and how', 'Only the budget', 'Only the objectives', 'Only farmer names'], 0,
    'It turns the programme into actionable tasks.'],
  ['A "calendar of work" lists:', ['Planned activities arranged by month or season', 'Farmers’ birthdays', 'Market prices', 'Weather records only'], 0,
    'It helps timely execution.'],
  ['A basic principle of extension programme planning is that it should:', ['Be based on the felt needs of people and involve them', 'Be imposed by officials alone', 'Ignore local situations', 'Never change'], 0,
    'Flexibility and participation are key.'],
  ['Under ATMA, the district-level strategic plan for research and extension is the:', ['SREP (Strategic Research and Extension Plan)', 'DPR', 'PRA', 'SWOT'], 0,
    'Prepared with farmer participation to set district priorities.'],
  ['Participatory Rural Appraisal (PRA), useful for situation analysis, was popularised by:', ['Robert Chambers', 'Everett Rogers', 'Daniel Benor', 'Kurt Lewin'], 0,
    'Tools include resource maps, seasonal calendars and transect walks.'],
  ['"Programme" in extension differs from "plan of work" in that the programme:', ['States the situation, problems, objectives and solutions', 'Lists daily tasks only', 'Is a budget', 'Is a weather forecast'], 0,
    'The plan of work details how the programme will be carried out.'],
  ['Evaluation in programme planning helps mainly to:', ['Judge results against objectives and improve the next programme', 'Punish staff', 'Replace planning', 'Increase costs'], 0,
    'It closes the planning cycle.'],
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2025-A1-Q5b', q: [
  ['Mixed farming means:', ['Crop production combined with livestock on the same farm', 'Growing two crops together', 'Farming by many families jointly', 'Growing only fodder'], 0,
    'Crops feed animals, and animals supply manure and draught power.'],
  ['A specialised farm is one where:', ['A single enterprise provides at least half of the farm income', 'Many enterprises contribute equally', 'Only livestock are kept', 'The state owns the land'], 0,
    'A diversified farm has several enterprises, none dominant.'],
  ['Ranching refers to:', ['Grazing livestock on large natural pastures without crop cultivation', 'Growing plantation crops', 'Keeping poultry in cages', 'Fish farming'], 0,
    'Common in the Americas and Australia.'],
  ['The Central State Farm at Suratgarh (Rajasthan), set up in 1956 with Soviet help, is an example of:', ['State farming', 'Cooperative farming', 'Peasant farming', 'Contract farming'], 0,
    'State farms are owned and run by the government with hired labour.'],
  ['Collective farming (as in the former USSR’s kolkhozes) involves:', ['Pooling land and resources under collective management, with members sharing output', 'Individual ownership only', 'Corporate plantations', 'Tenancy'], 0,
    'Cooperative joint farming in India was a voluntary variant.'],
  ['Peasant farming is characterised by:', ['Small owner-operated farms using mainly family labour', 'Large corporate estates', 'State ownership', 'Pure ranching'], 0,
    'It is the dominant form in India.'],
  ['Plantation farming is typical of crops such as:', ['Tea, coffee and rubber', 'Wheat and rice', 'Mustard and gram', 'Maize and sorghum'], 0,
    'Large estates with processing and hired labour.'],
  ['Capitalist farming involves:', ['Large farms run for profit with hired labour and capital investment', 'Subsistence farming', 'Farming only for family consumption', 'Shifting cultivation'], 0,
    'Common in commercial agriculture.'],
  ['Diversified farming mainly helps to:', ['Spread risk and use resources throughout the year', 'Increase risk', 'Reduce income sources', 'Avoid livestock'], 0,
    'It also provides regular income and employment.'],
  ['Subsistence farming aims mainly at:', ['Meeting the needs of the farm family, with little surplus for sale', 'Export production', 'Industrial raw materials only', 'Maximising market sales'], 0,
    'Still common among smallholders in rainfed and tribal areas.'],
] },
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 2, pyq: 'IFoS-2025-A1-Q5c', q: [
  ['A contour bund is built:', ['Along the contour line to hold runoff and let it infiltrate', 'Up and down the slope', 'Only around wells', 'Only in flooded fields'], 0,
    'It suits low-rainfall areas with permeable soils.'],
  ['The vertical interval between successive bunds generally:', ['Increases as land slope increases', 'Decreases as slope increases', 'Is the same on all slopes', 'Depends only on crop'], 0,
    'Horizontal spacing becomes shorter on steeper slopes.'],
  ['A waste weir (surplus outlet) in a bund is provided to:', ['Safely drain excess water without breaching the bund', 'Store water permanently', 'Irrigate crops', 'Stop all runoff'], 0,
    'It is usually stone-pitched or grassed.'],
  ['Bunds are stabilised by planting:', ['Grasses and legumes such as *Cenchrus* or *Stylosanthes* on them', 'Tall trees only', 'Nothing', 'Weeds'], 0,
    'Vegetation protects bunds from erosion and gives fodder.'],
  ['Contour bunds are not advisable on heavy black (Vertisol) soils in high-rainfall areas because:', ['Water stagnates behind them, causing waterlogging', 'They are too cheap', 'They dry the soil', 'They increase soil fertility'], 0,
    'Graded bunds or broad bed and furrows are used instead.'],
  ['Peripheral bunds around a field mainly:', ['Retain water within the field and mark boundaries', 'Drain water quickly', 'Irrigate neighbours', 'Stop wind erosion only'], 0,
    'Common in rice fields.'],
  ['A drawback of bunding is that it:', ['Takes a small part of the cultivable area', 'Always causes erosion', 'Reduces infiltration', 'Increases runoff'], 0,
    'Growing fodder grasses on bunds offsets this loss.'],
  ['Bunds need regular maintenance because:', ['Rain can cause breaches that must be repaired promptly', 'They grow by themselves', 'They move downhill', 'They dissolve in sunlight'], 0,
    'A single breach can release accumulated water and cause gullying.'],
  ['The main benefit of bunding in drylands is:', ['More soil moisture and less runoff and soil loss, raising crop yields', 'More waterlogging', 'Lower infiltration', 'Faster drainage of rainwater'], 0,
    'A key in-situ moisture conservation measure.'],
  ['Graded bunds are laid out with:', ['A slight longitudinal slope to a safe outlet', 'No slope at all', 'A steep slope', 'Random alignment'], 0,
    'They are also called channel terraces in some texts.'],
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2025-A1-Q5d', q: [
  ['The national apex body for cooperative agricultural marketing in India, set up in 1958, is:', ['NAFED', 'NABARD', 'NCDC', 'FCI'], 0,
    'National Agricultural Cooperative Marketing Federation of India.'],
  ['CAMPCO is a cooperative dealing mainly in:', ['Arecanut and cocoa', 'Milk', 'Fertilisers', 'Sugar'], 0,
    'Based in Karnataka, with members in Karnataka and Kerala.'],
  ['The "Anand pattern" is a three-tier cooperative model for:', ['Dairy (village society → district union → state federation)', 'Fertiliser production', 'Tea plantations', 'Fisheries'], 0,
    'Pioneered by Amul in Gujarat.'],
  ['Cooperative marketing benefits small farmers mainly by:', ['Pooling produce to increase bargaining power and reduce middlemen', 'Increasing commission charges', 'Delaying payments', 'Reducing prices'], 0,
    'Grading, storage and pledge loans are added services.'],
  ['A common problem of marketing cooperatives in India is:', ['Weak management, political interference and poor member loyalty', 'Too much profit', 'Excess capital', 'No demand'], 0,
    'Professional management and member participation are remedies.'],
  ['The National Cooperative Development Corporation (NCDC), set up in 1963, mainly:', ['Finances and promotes cooperatives', 'Regulates banks', 'Procures wheat', 'Issues seed licences'], 0,
    'It supports marketing, processing and storage cooperatives.'],
  ['The Union Ministry of Cooperation was created in:', ['2021', '1958', '1991', '2014'], 0,
    'It oversees cooperatives, including multi-state societies.'],
  ['Pledge finance by marketing cooperatives allows farmers to:', ['Take loans against stored produce and sell later at better prices', 'Sell only at harvest', 'Avoid storage', 'Pay higher commissions'], 0,
    'Linking credit with marketing is a key cooperative principle.'],
  ['HOPCOMS in Bengaluru is a cooperative for marketing:', ['Fruits and vegetables', 'Milk', 'Silk', 'Coffee'], 0,
    'It procures from growers and sells through its own retail outlets.'],
  ['Multi-state cooperative societies are governed by the:', ['Multi-State Cooperative Societies Act, 2002 (amended 2023)', 'Companies Act only', 'APMC Act', 'Seeds Act'], 0,
    'State-level societies are governed by state cooperative laws.'],
] },
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'IFoS-2025-A1-Q5e', q: [
  ['The critical stages for irrigating groundnut are:', ['Flowering, pegging and pod development', 'Germination only', 'Harvest only', 'Seedling stage only'], 0,
    'Moisture in the pegging zone is vital for pod formation.'],
  ['For rice, the most critical stages for water stress are:', ['Panicle initiation and flowering', 'Maturity only', 'Nursery only', 'Tillering only'], 0,
    'Stress at flowering causes spikelet sterility.'],
  ['For sorghum, the critical stages for irrigation are:', ['Booting and flowering (with grain filling)', 'Germination only', 'Harvest', 'Seedling only'], 0,
    'Sorghum otherwise tolerates drought well.'],
  ['For chickpea, one irrigation is best given at:', ['Pre-flowering or pod development', 'Sowing only', 'Harvest', 'Germination only'], 0,
    'Excess irrigation causes excessive vegetative growth.'],
  ['The critical phase for irrigating sugarcane is the:', ['Formative (tillering) phase', 'Ripening phase', 'Harvesting phase', 'Germination only'], 0,
    'Stress then reduces tiller number and final cane yield.'],
  ['For cotton, the most critical stages for irrigation are:', ['Flowering and boll development', 'Germination only', 'Picking', 'Seedling'], 0,
    'Stress causes shedding of squares and bolls.'],
  ['For sunflower, irrigation is critical at:', ['Star-bud, flowering and seed-filling stages', 'Germination only', 'Harvest only', 'Pre-sowing'], 0,
    'Seed filling needs good moisture for oil content.'],
  ['For mustard, irrigation is most beneficial at:', ['Pre-flowering (branching) and pod-filling stages', 'Harvest', 'Germination only', 'Seedling stage only'], 0,
    'One or two irrigations are usually enough.'],
  ['For potato, the critical stages for irrigation are:', ['Stolon formation, tuber initiation and tuber bulking', 'Planting only', 'Dehaulming', 'Harvest'], 0,
    'Uneven moisture causes growth cracks and malformed tubers.'],
  ['Scheduling irrigation by critical stages is most useful when:', ['Water is limited and must be applied where it gives the highest return', 'Water is unlimited', 'Crops are dormant', 'Soil is waterlogged'], 0,
    'It is simple and needs no instruments.'],
] },
{ p: 'A1', t: 'Agricultural Extension', w: 2, pyq: 'IFoS-2025-A1-Q6a', q: [
  ['mKrishi, a mobile agro-advisory platform, was developed by:', ['Tata Consultancy Services (TCS)', 'ITC', 'ICAR only', 'IFFCO'], 0,
    'It gives personalised advice on crops, weather and prices on mobile phones.'],
  ['Kisan Call Centres, launched in 2004, can be reached on:', ['The toll-free number 1800-180-1551', '100', '108', '1912'], 0,
    'Farmers get answers in local languages from agricultural experts.'],
  ['The mKisan portal (2013) of the Department of Agriculture is used to:', ['Send SMS advisories to registered farmers', 'Sell tractors', 'Pay subsidies', 'Register land'], 0,
    'Advisories come from scientists and officials at various levels.'],
  ['e-Choupal, a network of village internet kiosks for farmers, was started by:', ['ITC (2000)', 'TCS', 'Reliance', 'NABARD'], 0,
    'It also helps ITC procure produce directly.'],
  ['The "Meghdoot" mobile app provides:', ['Weather-based crop and livestock advisories', 'Loans', 'Seeds', 'Land records'], 0,
    'Developed by IMD, ICAR and partners (2019).'],
  ['Digital Green is known for:', ['Farmer-to-farmer video-based extension', 'Satellite launches', 'Fertiliser production', 'Crop insurance'], 0,
    'Local farmers appear in short videos shown to village groups.'],
  ['A major limitation of ICT-based extension in India is:', ['The digital divide — poor connectivity, low digital literacy and language barriers', 'Too many extension workers', 'Excess electricity', 'Farmers’ lack of interest in information'], 0,
    'Combining ICT with human intermediaries helps.'],
  ['A key advantage of ICT in extension is:', ['Timely, low-cost, location-specific information that can reach many farmers', 'Replacing all field visits', 'Higher costs', 'Only one-way communication'], 0,
    'Two-way platforms let farmers ask questions.'],
  ['The Kisan Suvidha app (2016) gives farmers information on:', ['Weather, market prices, input dealers, plant protection and advisories', 'Only land records', 'Only loans', 'Only fertiliser subsidies'], 0,
    'A single app for several services.'],
  ['ICT-based extension works best when:', ['Combined with local extension workers and farmer groups', 'Used alone without human contact', 'Only in English', 'Only for large farmers'], 0,
    'Blended approaches build trust and adoption.'],
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2025-A1-Q6b', q: [
  ['Two enterprises are "supplementary" when:', ['One can be expanded without reducing the other, by using idle resources', 'Expanding one always reduces the other', 'Expanding one increases the other', 'They cannot be combined'], 0,
    'E.g., a small poultry unit using family labour spare after crop work.'],
  ['Two enterprises are "complementary" when:', ['Increasing one also increases the output of the other', 'Increasing one reduces the other', 'They have no relation', 'They use no common resources'], 0,
    'E.g., a legume crop raising yield of the following cereal.'],
  ['Enterprises are "competitive" when:', ['They compete for the same limited resources, so more of one means less of the other', 'Both can increase together', 'They are supplementary', 'They use no inputs'], 0,
    'E.g., two crops competing for the same land in the same season.'],
  ['A cash-flow budget helps a farmer to:', ['Plan the timing of expenses and receipts to avoid cash shortages', 'Measure soil fertility', 'Estimate rainfall', 'Choose seed variety'], 0,
    'Useful for planning credit needs.'],
  ['An enterprise budget shows:', ['Costs and returns of a single activity such as one crop or livestock unit', 'The whole farm’s accounts', 'Only fixed costs', 'Only labour use'], 0,
    'Enterprise budgets are building blocks of whole-farm plans.'],
  ['A major limitation of farm planning in India is:', ['Uncertainty of weather and prices, and lack of farm records', 'Too many records', 'Guaranteed prices for all crops', 'Very large farms'], 0,
    'Small, fragmented holdings and limited credit add to the difficulty.'],
  ['Linear programming in farm planning is limited by its assumption that:', ['Relationships between inputs and outputs are linear with constant returns', 'All variables are random', 'There are no constraints', 'Prices are unknown'], 0,
    'Real farm responses often show diminishing returns.'],
  ['Building a safety margin into a farm plan is important because:', ['Farming faces yield and price risks', 'Prices are always stable', 'Weather is predictable', 'Credit is unlimited'], 0,
    'Insurance, savings and diversification are risk tools.'],
  ['The objective of farm planning is usually to:', ['Maximise net income within resource limits while meeting family needs', 'Maximise costs', 'Minimise production', 'Use all inputs regardless of cost'], 0,
    'Farmers may also value food security and low risk.'],
  ['Farm planning is limited in practice when farmers:', ['Lack reliable data and skills to prepare and follow plans', 'Keep detailed records', 'Have access to extension', 'Use budgeting tools'], 0,
    'Extension support can bridge this gap.'],
] },
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 2, pyq: 'IFoS-2025-A1-Q6c', q: [
  ['U-shaped gullies form where:', ['Surface soil and subsoil are equally erodible (or the subsoil is weaker), so banks cave vertically', 'The subsoil is much more resistant than the topsoil', 'There is no runoff', 'The gully is stabilised'], 0,
    'Such gullies have near-vertical side walls.'],
  ['V-shaped gullies form where:', ['The subsoil is more resistant than the surface soil', 'Both layers are equally erodible', 'Rock is at the surface', 'There is no slope'], 0,
    'V-shaped is the most common gully form.'],
  ['Trapezoidal gullies form where:', ['The gully bottom rests on resistant material while the banks keep eroding', 'The subsoil is very weak', 'There is no bottom layer', 'Runoff is absent'], 0,
    'They have a flat, wide floor.'],
  ['Gullies are also classified as active or inactive based on:', ['Whether erosion and head-cutting are still continuing', 'Their colour', 'Crop grown nearby', 'Soil pH'], 0,
    'Active gullies advance by head-cutting.'],
  ['The usual stages of gully development are:', ['Formation, development (head-cutting and widening), healing and stabilisation', 'Stabilisation, formation, development', 'Healing, formation, deposition', 'Deposition only'], 0,
    'Most soil is lost in the development stage.'],
  ['Headcut erosion in a gully refers to:', ['Upslope advance of the gully head by waterfall erosion', 'Deposition at the mouth', 'Growth of vegetation', 'Sheet erosion'], 0,
    'Stabilising the gully head is the first priority in control.'],
  ['Continuous and discontinuous gullies differ in that discontinuous gullies:', ['Occur as separate short sections with fans between them', 'Form one long channel', 'Are always stabilised', 'Occur only on flat land'], 0,
    'They may later join into a continuous gully.'],
  ['The Chambal ravines, a severe case of gully erosion, lie mainly in:', ['Madhya Pradesh, Rajasthan and Uttar Pradesh', 'Kerala and Tamil Nadu', 'Assam and Meghalaya', 'Punjab and Himachal'], 0,
    'Ravines also occur along the Yamuna, Mahi and Sabarmati.'],
  ['Drop spillways in gully control are used to:', ['Lower water safely from a higher to a lower level without scouring', 'Store water permanently', 'Divert water to fields', 'Increase flow speed'], 0,
    'Other structures include check dams, chute spillways and gully plugs.'],
  ['Long-term stabilisation of gullies relies on:', ['Vegetating the gully bed and catchment along with structures', 'Removing all vegetation', 'Increasing runoff', 'Deep ploughing of gully banks'], 0,
    'Structures buy time for vegetation to establish.'],
] },
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'IFoS-2025-A1-Q7a', q: [
  ['In the USSL (Richards, 1954) classification, "C3-S1" water has:', ['High salinity and low sodium hazard', 'Low salinity and high sodium hazard', 'Low salinity and low sodium hazard', 'Very high salinity and very high sodium hazard'], 0,
    'C classes: C1 < 250, C2 250–750, C3 750–2,250, C4 > 2,250 µS/cm. S classes by SAR.'],
  ['An EC of 1 dS/m in irrigation water corresponds roughly to total dissolved salts of:', ['640 mg/L', '64 mg/L', '6,400 mg/L', '10 mg/L'], 0,
    'A common conversion factor (it varies with salt composition).'],
  ['Water with EC below 250 µS/cm (class C1) is:', ['Low-salinity water safe for most crops', 'Highly saline', 'Unsuitable for irrigation', 'Only for salt-tolerant crops'], 0,
    'C4 water needs salt-tolerant crops and good drainage.'],
  ['Which crop is highly tolerant of salinity?', ['Barley', 'Bean', 'Carrot', 'Onion'], 0,
    'Sugar beet, cotton and date palm are also tolerant; beans and many vegetables are sensitive.'],
  ['The Maas–Hoffman model describes crop response to salinity as:', ['No yield loss up to a threshold EC, then a linear decline', 'A steady rise in yield', 'Sudden death at any salinity', 'No effect of salinity'], 0,
    'Each crop has its own threshold and slope.'],
  ['If irrigation water EC is 2 dS/m and the crop tolerates drainage water EC of 8 dS/m, the leaching requirement is:', ['25%', '4%', '50%', '75%'], 0,
    'LR = ECiw ÷ ECdw = 2 ÷ 8.'],
  ['Chloride in irrigation water is especially harmful to:', ['Tree crops such as citrus and stone fruits, causing leaf burn', 'Barley', 'Cotton', 'Date palm'], 0,
    'Sprinkler irrigation increases leaf absorption of Na and Cl.'],
  ['A strategy for using saline groundwater is:', ['Cyclic use or blending with good-quality canal water', 'Using it only on sensitive crops', 'Never leaching', 'Applying it at germination only'], 0,
    'Good-quality water is kept for sensitive stages such as germination.'],
  ['The KRL series wheat varieties from CSSRI, Karnal are bred for:', ['Tolerance of salinity and sodicity', 'Drought in hills', 'Heat in the south', 'Rust in Nilgiris'], 0,
    'CSR series rice varieties are also salt-tolerant.'],
  ['Sodium hazard of irrigation water is assessed mainly by:', ['Sodium adsorption ratio (SAR)', 'EC only', 'pH only', 'Temperature'], 0,
    'High SAR water disperses soil, reducing infiltration.'],
] },
{ p: 'A1', t: 'Dryland Farming & Watershed Management', w: 2, pyq: 'IFoS-2025-A1-Q7b', q: [
  ['The Neeranchal National Watershed Project (2016) was supported by the:', ['World Bank', 'Asian Development Bank', 'FAO', 'JICA'], 0,
    'It aimed to strengthen PMKSY watershed components.'],
  ['The Hariyali guidelines (2003) for watershed development gave a central role to:', ['Gram Panchayats', 'Private companies', 'Only state departments', 'Central ministries only'], 0,
    'Later replaced by the Common Guidelines (2008).'],
  ['In watershed treatment planning, land is often divided into:', ['Arable land, non-arable land and drainage lines', 'Only arable land', 'Only forest land', 'Only rivers'], 0,
    'Each gets different treatments (bunds, afforestation/pasture, check dams).'],
  ['Hiware Bazar, known for watershed-based village development, is in:', ['Maharashtra', 'Rajasthan', 'Tamil Nadu', 'Bihar'], 0,
    'In Ahmednagar district, like Ralegan Siddhi.'],
  ['The success of watershed projects depends most on:', ['People’s participation and local institutions', 'Only engineering structures', 'Only external funding', 'Only government staff'], 0,
    'Social fencing (voluntary restraint on grazing and felling) is often vital.'],
  ['Watershed works can be converged with MGNREGA mainly for:', ['Labour-intensive soil and water conservation works', 'Buying tractors', 'Seed distribution', 'Crop insurance'], 0,
    'MGNREGA funds much of the earthwork in rural areas.'],
  ['Silt monitoring in watershed projects helps to:', ['Measure reduction in sediment yield after treatment', 'Count farmers', 'Estimate crop prices', 'Measure temperature'], 0,
    'Lower sediment yield means less soil loss from the catchment.'],
  ['The smallest planning unit in India’s watershed hierarchy is the:', ['Micro-watershed', 'River basin', 'Catchment', 'Water resource region'], 0,
    'Hierarchy: region → basin → catchment → sub-catchment → watershed → sub-watershed → micro-watershed.'],
  ['Watershed management that involves trees on upper slopes, pastures on middle slopes and crops on lower land follows the principle of:', ['Land use according to capability', 'Random land use', 'Maximum cropping everywhere', 'No planning'], 0,
    'Steeper, shallower land is kept under permanent cover.'],
  ['A watershed can be defined as:', ['An area that drains to a common outlet', 'Any irrigated field', 'A single village', 'A forest reserve'], 0,
    'Its boundary follows the ridge line.'],
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2025-A1-Q7c', q: [
  ['Contract farming is:', ['An agreement between farmers and a buyer, before production, on quantity, quality and price', 'Farming on leased land only', 'Farming by the government', 'Cooperative joint farming'], 0,
    'The buyer often provides inputs, technology and credit.'],
  ['The Model Contract Farming Act circulated to states in 2018 is the:', ['Agricultural Produce and Livestock Contract Farming and Services (Promotion & Facilitation) Act', 'APMC Act, 2003', 'Seeds Act, 1966', 'Essential Commodities Act, 1955'], 0,
    'It keeps contract farming outside APMC regulation and provides for dispute settlement.'],
  ['The central law of 2020 on price assurance and farm-service agreements was:', ['Repealed in 2021', 'Upheld and expanded', 'Never passed', 'Made applicable only to exports'], 0,
    'It was one of the three farm laws repealed after farmer protests.'],
  ['A well-known early example of contract farming in India is:', ['PepsiCo’s potato and tomato contracts in Punjab from 1989', 'The Green Revolution', 'The Anand pattern', 'Zamindari'], 0,
    'Broiler integration and gherkin production are other examples.'],
  ['A key benefit of contract farming for farmers is:', ['An assured market and price, with access to inputs and technology', 'Higher risk', 'No quality standards', 'Lower income always'], 0,
    'Companies gain an assured supply of uniform produce.'],
  ['A major risk of contract farming for farmers is:', ['Unequal bargaining power, with rejection of produce on quality grounds or delayed payment', 'Guaranteed prices always above market', 'Too many buyers', 'Excess information'], 0,
    'Clear contracts and quick dispute resolution are needed.'],
  ['"Side-selling" in contract farming means:', ['Farmers selling contracted produce to other buyers when market prices are higher', 'Selling to the contracting firm', 'Selling seeds', 'Selling land'], 0,
    'It weakens trust between farmers and firms.'],
  ['Contract farming of gherkins for export is concentrated in:', ['Karnataka and Andhra Pradesh', 'Punjab', 'Assam', 'Himachal Pradesh'], 0,
    'Companies supply seeds and technical guidance.'],
  ['Under the model contract farming law, disputes are to be settled mainly through:', ['Local authorities such as the Sub-Divisional Magistrate, with conciliation first', 'Civil courts only', 'Police', 'Panchayats only'], 0,
    'The aim is quick, local resolution.'],
  ['Contract farming can exclude small farmers because:', ['Firms may prefer larger farmers for lower transaction costs', 'Small farmers produce better quality', 'Contracts are illegal', 'Small farmers are always preferred'], 0,
    'FPOs can help small farmers enter contracts collectively.'],
] },
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'IFoS-2025-A1-Q8a', q: [
  ['If readily available water in the root zone is 60 mm and crop ET is 5 mm/day, the irrigation interval is about:', ['12 days', '5 days', '60 days', '1 day'], 0,
    'Interval = allowable depletion ÷ daily ETc.'],
  ['Irrigation must be more frequent on:', ['Sandy soils with low water-holding capacity', 'Clay loams', 'Deep alluvial soils', 'Soils rich in organic matter'], 0,
    'Smaller, more frequent irrigations suit light soils.'],
  ['If net irrigation requirement is 60 mm and application efficiency is 60%, the gross irrigation needed is:', ['100 mm', '36 mm', '60 mm', '120 mm'], 0,
    'Gross = net ÷ efficiency = 60 ÷ 0.60.'],
  ['Conveyance efficiency refers to:', ['The share of water diverted that reaches the field', 'The share stored in the root zone', 'Uniformity of water across the field', 'Crop yield per unit water'], 0,
    'Canal lining improves it.'],
  ['Gypsum (resistance) blocks estimate soil moisture by measuring:', ['Electrical resistance, which changes with the moisture of the block', 'Soil colour', 'Soil temperature', 'Leaf water potential'], 0,
    'They work better in drier ranges than tensiometers.'],
  ['The pressure-plate apparatus is used to determine:', ['Soil moisture retention at field capacity and wilting point', 'Soil pH', 'Soil texture', 'Nutrient content'], 0,
    'Samples are equilibrated at −0.33 and −15 bar.'],
  ['Deficit irrigation means:', ['Deliberately applying less water than full crop demand, mainly at less sensitive stages', 'Applying excess water', 'No irrigation at all', 'Flooding at every stage'], 0,
    'It saves water with small yield penalties when well managed.'],
  ['In rice, irrigating a few days after ponded water disappears (rather than keeping it continuously flooded):', ['Saves water with little or no yield loss on suitable soils', 'Always halves yields', 'Increases methane emissions', 'Is not possible'], 0,
    'Similar in principle to alternate wetting and drying.'],
  ['Allowable soil-water depletion before irrigation should be smaller during:', ['Critical growth stages such as flowering', 'Maturity', 'Dormancy', 'After harvest'], 0,
    'Stress then causes the largest yield loss.'],
  ['Soil-moisture sensors linked to automated controllers enable:', ['Irrigation scheduling based on real-time soil moisture', 'Fertiliser manufacturing', 'Pest identification', 'Weather control'], 0,
    'Such sensor-based systems are part of precision irrigation.'],
] }
);
