/* PYQ-linked MCQs — IFoS 2018 Agriculture Paper II, Q5–Q8 (verbatim PYQs). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Insect Pests & IPM', w: 2, pyq: 'IFoS-2018-A2-Q5a', q: [
  ['The maximum residue limit (MRL) of a pesticide is:', ['The highest legally permitted residue level in a food commodity', 'The dose to be sprayed per hectare', 'The lethal dose for pests', 'The toxicity class'], 0,
    'MRLs in India are set by FSSAI; Codex sets international MRLs.'],
  ['The pre-harvest interval (waiting period) is:', ['The minimum time between the last pesticide spray and harvest', 'The time between two sprays', 'The time from sowing to spraying', 'The shelf life of the pesticide'], 0,
    'Keeping to it lets residues fall below the MRL.'],
  ['A simple household way to reduce surface pesticide residues on vegetables is:', ['Washing in a dilute salt solution and then in clean water', 'Storing them in the refrigerator unwashed', 'Coating them with oil', 'Adding more pesticide'], 0,
    'Peeling, blanching and cooking reduce residues further.'],
  ['Acceptable daily intake (ADI) is:', ['The amount of a chemical that can be eaten daily over a lifetime without appreciable risk', 'The dose that kills half the test animals', 'The spray dose', 'The MRL'], 0,
    'MRLs are set so that total intake stays below the ADI.'],
  ['To keep residues low in vegetables close to harvest, farmers should prefer:', ['Short-persistence chemicals or biopesticides such as NSKE 5%', 'Long-persistence systemic insecticides', 'Mixing several pesticides', 'Doubling the dose'], 0,
    'Neem seed kernel extract (NSKE) leaves little harmful residue.'],
  ['IPM reduces pesticide residues by:', ['Using pheromone traps, biological control and resistant varieties, and spraying only when needed', 'Spraying on a fixed calendar', 'Using only chemicals', 'Increasing spray frequency'], 0,
    'Economic thresholds decide when to spray.'],
  ['Pesticides in India are registered for use on specific crops under:', ['The Insecticides Act, 1968, through the CIB&RC', 'The Seeds Act, 1966', 'The Essential Commodities Act', 'The Forest Act'], 0,
    'Using unregistered ("off-label") pesticides raises the risk of residue violations.'],
  ['Residues of pesticides in food across India are monitored under:', ['The scheme "Monitoring of Pesticide Residues at National Level" (MPRNL)', 'MGNREGA', 'PM-KISAN', 'e-NAM'], 0,
    'Samples of vegetables, fruits, milk and water are tested.'],
  ['Pesticide residues are highest when:', ['Vegetables are harvested soon after spraying', 'The waiting period is followed', 'Biopesticides are used', 'Vegetables are washed and cooked'], 0,
    'Frequent-picking crops such as okra and brinjal are at risk.'],
  ['Growing vegetables organically avoids residues of:', ['Synthetic pesticides', 'All natural compounds', 'Water', 'Nutrients'], 0,
    'Certified organic produce follows NPOP standards.']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2018-A2-Q5b', q: [
  ['The seed plot technique for potato was developed by:', ['CPRI, Shimla (Pushkarnath)', 'IARI, New Delhi', 'ICRISAT', 'IRRI'], 0,
    'It allowed healthy seed potato to be produced in the north Indian plains.'],
  ['The seed plot technique is based on:', ['Growing the seed crop during the low-aphid period (October–December) in the plains', 'Growing potato only in summer', 'Using true potato seed only', 'Spraying herbicides'], 0,
    'Aphids spread the main potato viruses.'],
  ['The main aphid vector of potato viruses is:', ['*Myzus persicae*', '*Aphis gossypii* only', '*Bemisia tabaci*', '*Thrips tabaci*'], 0,
    'It is the green peach aphid.'],
  ['The major aphid-borne viruses of potato are:', ['Potato leaf roll virus (PLRV) and potato virus Y (PVY)', 'TMV only', 'Cucumber mosaic virus only', 'Tomato spotted wilt virus only'], 0,
    'They cause "degeneration" of seed stocks.'],
  ['Haulms are cut (dehaulming) in the seed plot technique when:', ['The aphid count reaches about 20 per 100 compound leaves', 'The crop starts flowering', 'The tubers start forming', 'The first frost comes'], 0,
    'Early dehaulming stops viruses moving to the tubers.'],
  ['Before the seed plot technique, seed potato in India was produced mainly in:', ['High hills, where aphids are few', 'Coastal plains', 'Deserts', 'Islands'], 0,
    'Hill seed was expensive and in short supply.'],
  ['During the seed crop, virus-infected plants are:', ['Rogued out regularly', 'Left to grow', 'Given more fertiliser', 'Irrigated more'], 0,
    'Systemic insecticides also keep aphids down.'],
  ['After harvest, seed tubers produced by this technique are stored in:', ['Cold stores at about 2–4 °C', 'Open heaps in summer', 'Water tanks', 'Sealed plastic at room temperature'], 0,
    'Cold storage prevents sprouting and rotting.'],
  ['Modern disease-free seed potato programmes also use:', ['Tissue-culture plantlets and aeroponic mini-tubers', 'Only farm-saved seed', 'Only true potato seed', 'Only grafting'], 0,
    'CPRI has developed aeroponic seed production.'],
  ['The seed plot technique made seed production possible in:', ['Punjab, Haryana, western UP and similar plains', 'Only Kerala', 'Only Himachal Pradesh', 'Only Rajasthan'], 0,
    'Punjab is now a major seed potato supplier.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'IFoS-2018-A2-Q5c', q: [
  ['In germinating cereal grains, gibberellin from the embryo acts on the:', ['Aleurone layer, which then makes α-amylase', 'Pericarp', 'Root cap', 'Coleoptile tip only'], 0,
    'The enzyme breaks down endosperm starch into sugars.'],
  ['The classic system for studying GA action in seeds is:', ['Barley aleurone', 'Pea stem', 'Oat coleoptile', 'Tobacco callus'], 0,
    'Half-seeds without embryos respond to added GA.'],
  ['GA switches on α-amylase genes by causing the breakdown of:', ['DELLA repressor proteins, which frees the transcription factor GAMYB', 'Auxin', 'Chlorophyll', 'Starch'], 0,
    'DELLAs are degraded through the 26S proteasome.'],
  ['The gibberellin receptor is:', ['GID1', 'TIR1', 'ETR1', 'PYR/PYL'], 0,
    'TIR1 is the auxin receptor; PYR/PYL are ABA receptors.'],
  ['The hormone that opposes GA and keeps seeds dormant is:', ['Abscisic acid', 'Cytokinin', 'Auxin', 'Ethylene'], 0,
    'The ABA:GA balance decides whether a seed germinates.'],
  ['GA can replace the need for:', ['Light or cold stratification in some dormant seeds', 'Water for germination', 'Oxygen', 'An embryo'], 0,
    'Lettuce seeds need red light, which GA can replace.'],
  ['Besides α-amylase, GA induces aleurone cells to produce:', ['Proteases, β-glucanases and ribonucleases', 'Chlorophyll', 'Lignin', 'Cellulose'], 0,
    'These mobilise all endosperm reserves.'],
  ['In the malting industry, GA is used to:', ['Speed up and even out barley germination', 'Stop germination', 'Kill microbes', 'Colour the malt'], 0,
    'Malt enzymes are needed for brewing.'],
  ['Paclobutrazol inhibits seed germination because it:', ['Blocks gibberellin biosynthesis', 'Adds ABA', 'Kills the embryo', 'Hardens the seed coat'], 0,
    'Growth retardants act mostly on the GA pathway.'],
  ['Gibberellins were first discovered from a fungus that causes:', ['Bakanae ("foolish seedling") disease of rice', 'Late blight of potato', 'Rust of wheat', 'Wilt of tomato'], 0,
    'The fungus is *Gibberella fujikuroi* (Kurosawa, 1926).']
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 2, pyq: 'IFoS-2018-A2-Q5d', q: [
  ['Mango malformation occurs in two forms:', ['Vegetative malformation and floral malformation', 'Fruit rot and leaf spot', 'Root rot and stem canker', 'Black tip and spongy tissue'], 0,
    'Floral malformation causes the greater yield loss.'],
  ['The most widely accepted cause of mango malformation is the fungus:', ['*Fusarium mangiferae*', '*Colletotrichum gloeosporioides*', '*Oidium mangiferae*', '*Botryodiplodia theobromae*'], 0,
    '*Colletotrichum* causes anthracnose; *Oidium* causes powdery mildew.'],
  ['The mite suspected of carrying the malformation pathogen is:', ['*Aceria mangiferae*', '*Tetranychus urticae*', '*Aceria cajani*', '*Polyphagotarsonemus latus*'], 0,
    'Mite damage may create entry points for the fungus.'],
  ['Floral malformation produces:', ['Compact, crowded panicles with many male flowers and little or no fruit set', 'Extra-large fruits', 'Normal panicles', 'Early ripening'], 0,
    'Malformed panicles often stay on the tree.'],
  ['Vegetative malformation appears mainly as:', ['A bunchy top of seedlings and young plants, with short internodes and small leaves', 'Leaf yellowing only', 'Stem canker', 'Fruit drop'], 0,
    'It is common in nurseries.'],
  ['Mango malformation is most serious in:', ['North India, including Punjab and Uttar Pradesh', 'Kerala', 'Andaman Islands', 'Konkan coast only'], 0,
    'Cooler flowering-season temperatures favour it.'],
  ['A long-standing recommendation to reduce floral malformation is spraying:', ['NAA (about 200 ppm) in early October', 'Urea at flowering', 'Copper sulphate at harvest', 'GA₃ in May'], 0,
    'Removing early malformed panicles (deblossoming) also helps.'],
  ['Malformation spreads to new orchards mainly through:', ['Infected grafts and scions from diseased trees', 'Wind-borne seeds', 'Irrigation water alone', 'Pollinating bees'], 0,
    'Scions should come only from healthy mother trees.'],
  ['Management of mango malformation includes:', ['Pruning affected shoots and panicles, then spraying a fungicide and an acaricide', 'Heavy irrigation', 'Extra nitrogen', 'Leaving affected parts on the tree'], 0,
    'Burning pruned material cuts down the inoculum.'],
  ['Mango malformation is also linked to a hormonal imbalance involving:', ['Increased ethylene', 'Excess gibberellin only', 'Lack of chlorophyll', 'Excess boron'], 0,
    'This is why NAA and other regulators are tried in its control.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: 'IFoS-2018-A2-Q5e', q: [
  ['Orange carrots are an important source of:', ['β-carotene (provitamin A)', 'Vitamin C only', 'Vitamin B₁₂', 'Iron only'], 0,
    'β-carotene is converted to vitamin A in the intestine.'],
  ['Guava is especially rich in:', ['Vitamin C (ascorbic acid)', 'Vitamin D', 'Vitamin B₁₂', 'Vitamin K only'], 0,
    'It often has several times more vitamin C than oranges.'],
  ['Vitamin A deficiency causes:', ['Night blindness and xerophthalmia', 'Scurvy', 'Rickets', 'Beri-beri'], 0,
    'Scurvy results from vitamin C deficiency.'],
  ['In guava fruit, vitamin C is most concentrated in:', ['The skin and outer flesh', 'The seeds', 'The central pulp', 'The stalk'], 0,
    'Eating the fruit with its skin gives the most benefit.'],
  ['Guava is a good source of pectin, which makes it valuable for:', ['Jelly making', 'Pickling only', 'Oil extraction', 'Wine only'], 0,
    'Pectin also provides dietary fibre.'],
  ['Black (Asiatic) carrots are rich in:', ['Anthocyanins', 'Lycopene', 'Chlorophyll', 'Capsaicin'], 0,
    'They are used to make kanji, a fermented drink.'],
  ['Pink-fleshed guava varieties such as Lalit also contain:', ['Lycopene', 'Caffeine', 'Nicotine', 'Solanine'], 0,
    'Lycopene is an antioxidant.'],
  ['Guava is often called:', ['The "apple of the tropics" or "poor man’s apple"', 'The "king of fruits"', 'The "queen of spices"', 'The "golden fibre"'], 0,
    'Mango is called the king of fruits.'],
  ['Carrots also provide:', ['Dietary fibre and potassium', 'Vitamin B₁₂', 'Large amounts of protein', 'Starch as the main nutrient'], 0,
    'They are low in calories.'],
  ['A popular Indian guava variety is:', ['Allahabad Safeda', 'Alphonso', 'Nagpur Mandarin', 'Robusta'], 0,
    'Lucknow-49 (Sardar) is another.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: 'IFoS-2018-A2-Q6a', q: [
  ['To treat 50 ha at 800 litres of spray per hectare, the total spray volume needed is:', ['40,000 litres', '4,000 litres', '800 litres', '16,000 litres'], 0,
    '50 × 800 = 40,000 L.'],
  ['For 40,000 L of spray at 0.01% concentration, the active ingredient needed is:', ['4 litres', '40 litres', '0.4 litre', '400 litres'], 0,
    '40,000 × 0.01 ÷ 100 = 4 L of a.i.'],
  ['The amount of Malathion 50 EC needed to supply 4 L of active ingredient is:', ['8 litres', '4 litres', '2 litres', '16 litres'], 0,
    '50 EC has 50% a.i., so 4 × 100 ÷ 50 = 8 L.'],
  ['The general formula for the amount of pesticide formulation needed is:', ['(Required concentration × spray volume) ÷ % a.i. in the formulation', 'Spray volume × % a.i.', 'Area ÷ concentration', '% a.i. ÷ spray volume'], 0,
    'Use the same units throughout.'],
  ['For one hectare at 800 L/ha and 0.01%, the Malathion 50 EC needed is:', ['160 mL', '80 mL', '1.6 L', '16 mL'], 0,
    '800 × 0.01 ÷ 100 = 0.08 L a.i.; 0.08 × 2 = 0.16 L.'],
  ['A 0.01% spray equals:', ['100 ppm', '10 ppm', '1,000 ppm', '1 ppm'], 0,
    '1% = 10,000 ppm.'],
  ['To make a 0.01% spray from Malathion 50 EC, each litre of water needs:', ['0.2 mL of the formulation', '2 mL', '20 mL', '0.02 mL'], 0,
    '0.1 mL of a.i. per litre, doubled for a 50% formulation.'],
  ['"EC" in Malathion 50 EC stands for:', ['Emulsifiable concentrate', 'Easy concentrate', 'Extra coated', 'Emulsion cream'], 0,
    'It forms a milky emulsion when mixed with water.'],
  ['If Malathion 25 EC were used instead of 50 EC for the same 50 ha, the amount needed would be:', ['16 litres', '8 litres', '4 litres', '32 litres'], 0,
    'Half the a.i. strength needs twice the product.'],
  ['Malathion is an organophosphate that kills insects by:', ['Inhibiting acetylcholinesterase', 'Blocking chitin synthesis', 'Acting as a juvenile hormone', 'Blocking sodium channels only'], 0,
    'Acetylcholine then builds up at the nerve synapses.']
] },
{ p: 'A2', t: 'Post-harvest & Food Processing', w: 2, pyq: 'IFoS-2018-A2-Q6b', q: [
  ['The main problem in marketing fruits and vegetables is their:', ['Perishability, leading to heavy post-harvest losses', 'Long shelf life', 'Low demand', 'Uniform quality'], 0,
    'A weak cold chain makes the losses worse.'],
  ['Seasonal gluts of fruits and vegetables lead to:', ['Price crashes and distress sales', 'Stable prices', 'Shortages', 'Higher producer share'], 0,
    'Tomato and onion prices swing widely for this reason.'],
  ['The producer’s share of the consumer’s rupee for fruits and vegetables is low because of:', ['Many intermediaries and high marketing costs', 'Direct sales', 'Low transport costs', 'Excess cold storage'], 0,
    'Farmers often get a third or less of the retail price.'],
  ['Cold storage capacity in India is used mostly for:', ['Potato', 'Mango', 'Grapes', 'Leafy vegetables'], 0,
    'Most of it is in Uttar Pradesh and West Bengal.'],
  ['Operation Greens (2018) originally targeted:', ['Tomato, onion and potato (TOP)', 'Wheat, rice and maize', 'Tea, coffee and rubber', 'Milk, eggs and fish'], 0,
    'It was later extended to more perishables.'],
  ['Direct farmer-to-consumer markets in Andhra Pradesh are called:', ['Rythu Bazaars', 'Uzhavar Sandhai', 'Apni Mandi', 'Haats only'], 0,
    'Uzhavar Sandhai (Tamil Nadu) and Apni Mandi (Punjab) are similar.'],
  ['Lack of grading and poor packaging of fruits leads to:', ['Lower prices and more transit damage', 'Higher prices', 'Longer shelf life', 'Better quality'], 0,
    'Corrugated fibreboard (CFB) boxes cut damage.'],
  ['The National Horticulture Board, which supports post-harvest infrastructure, was set up in:', ['1984', '2005', '1965', '1991'], 0,
    'It funds cold storages and pack houses.'],
  ['Special trains for moving perishables from producing areas to markets, launched in 2020, were called:', ['Kisan Rail', 'Vande Bharat', 'Rajdhani', 'Garib Rath'], 0,
    'Freight subsidies were given for fruits and vegetables.'],
  ['A remedy for price instability in perishables is:', ['Processing, cold chains and better market information', 'Banning storage', 'More middlemen', 'Stopping transport'], 0,
    'Processing turns surpluses into longer-lasting products.']
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 3, pyq: 'IFoS-2018-A2-Q6c', q: [
  ['Pruning is:', ['The careful removal of plant parts to improve shape, vigour, fruiting and quality', 'Removing fruits at harvest', 'Adding fertiliser', 'Grafting'], 0,
    'Training shapes the young tree; pruning maintains it.'],
  ['"Heading back" means:', ['Cutting back the end of a shoot, which stimulates the buds below to grow', 'Removing a whole shoot at its base', 'Removing roots', 'Bending branches'], 0,
    'It produces a bushier plant.'],
  ['"Thinning out" means:', ['Removing an entire shoot or branch at its point of origin', 'Cutting the tip of a shoot', 'Removing leaves only', 'Removing fruits only'], 0,
    'It opens the canopy to light and air.'],
  ['Grapevines need heavy annual pruning because:', ['Fruit is borne on current-season shoots arising from last season’s canes', 'Fruit is borne on old wood', 'They fruit on roots', 'They are evergreen'], 0,
    'Pruning controls the number of fruiting buds.'],
  ['In peninsular India, grapes are usually:', ['Pruned twice a year (back pruning in April and forward pruning in October) for one crop', 'Pruned once in December', 'Never pruned', 'Pruned only after harvest'], 0,
    'This is the double-pruning, single-cropping system.'],
  ['Apple bears fruit mainly on:', ['Spurs, which pruning aims to keep healthy', 'New succulent shoots only', 'Roots', 'Leaves'], 0,
    'Too much pruning removes spurs and reduces yield.'],
  ['Mango trees generally need:', ['Little regular pruning, but old orchards can be rejuvenated by heading back', 'Heavy annual pruning', 'Root pruning each year', 'Summer pruning of all shoots'], 0,
    'Rejuvenation is done after harvest.'],
  ['Crop regulation (bahar treatment) in guava is done by:', ['Withholding water and pruning, so the tree flowers in the chosen season', 'Heavy irrigation all year', 'Adding lime', 'Removing all leaves'], 0,
    'Winter-season fruit is of better quality.'],
  ['Pruning cuts on fruit trees are often protected with:', ['Bordeaux paste', 'Urea solution', 'Salt water', 'Lime water only'], 0,
    'It prevents fungal infection through the wounds.'],
  ['Deciduous fruit trees such as apple, pear and peach are pruned mainly:', ['In winter, during dormancy', 'At flowering', 'At fruit set', 'Just before harvest'], 0,
    'Dormant pruning causes the least stress.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 3, pyq: 'IFoS-2018-A2-Q6d', q: [
  ['Biological control of plant diseases is:', ['Using living organisms to suppress plant pathogens', 'Using chemical fungicides', 'Breeding resistant varieties only', 'Burning crop residues'], 0,
    'It is a key part of integrated disease management.'],
  ['The mechanisms of biocontrol include:', ['Antibiosis, competition, mycoparasitism and induced resistance', 'Only fertiliser supply', 'Only physical barriers', 'Only chemical toxicity'], 0,
    'An agent may use several mechanisms at once.'],
  ['*Trichoderma viride* and *T. harzianum* are used mainly against:', ['Soil-borne pathogens such as *Rhizoctonia*, *Fusarium*, *Pythium* and *Sclerotium*', 'Viruses', 'Insects', 'Weeds'], 0,
    'Seed is usually treated at about 4 g per kg.'],
  ['*Trichoderma* attacks other fungi (mycoparasitism) using:', ['Chitinases and β-1,3-glucanases', 'Nitrogenase', 'Rubisco', 'Amylase'], 0,
    'It coils around the host hyphae and digests them.'],
  ['*Pseudomonas fluorescens* is widely used against:', ['Rice blast and sheath blight, and bacterial wilts', 'Aphids', 'Weeds', 'Nematodes only'], 0,
    'It produces antibiotics and siderophores and induces systemic resistance.'],
  ['Crown gall is controlled biologically by *Agrobacterium radiobacter* strain K84 through:', ['The bacteriocin agrocin 84', 'Nitrogen fixation', 'Mycoparasitism', 'Cross protection'], 0,
    'It is one of the most successful commercial biocontrol agents.'],
  ['*Ampelomyces quisqualis* is a hyperparasite of:', ['Powdery mildews', 'Rusts', 'Bacterial wilts', 'Viruses'], 0,
    'It parasitises the mildew colonies.'],
  ['*Coniothyrium minitans* controls *Sclerotinia* by:', ['Parasitising and destroying its sclerotia', 'Producing auxin', 'Fixing nitrogen', 'Killing insects'], 0,
    'It reduces soil inoculum.'],
  ['Cross protection, used against citrus tristeza virus, involves:', ['Inoculating plants with a mild strain to protect them from severe strains', 'Spraying antibiotics', 'Grafting onto resistant rootstocks only', 'Heat treatment'], 0,
    'It is one of the few practical controls for virus diseases.'],
  ['"Take-all decline" in continuous wheat is a classic example of:', ['A disease-suppressive soil, linked to DAPG-producing *Pseudomonas*', 'Chemical control', 'Resistant varieties', 'Crop rotation'], 0,
    'Suppressive soils build up naturally after several crops.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 3, pyq: 'IFoS-2018-A2-Q7a', q: [
  ['Bacterial wilt of tomato, brinjal and chilli is caused by:', ['*Ralstonia solanacearum*', '*Fusarium oxysporum* f. sp. *lycopersici*', '*Xanthomonas campestris*', '*Erwinia carotovora*'], 0,
    'It has a very wide host range.'],
  ['Fusarium wilt of tomato is caused by:', ['*Fusarium oxysporum* f. sp. *lycopersici*', '*Ralstonia solanacearum*', '*Pseudomonas syringae*', '*Alternaria solani*'], 0,
    '*Verticillium* also causes wilts in vegetables.'],
  ['A quick field test that distinguishes bacterial wilt from fungal wilt is:', ['The ooze test — milky streams flow from a cut stem placed in water', 'Smelling the leaves', 'Measuring plant height', 'Checking the soil pH'], 0,
    'Fungal wilts give no bacterial ooze.'],
  ['Plants with bacterial wilt typically:', ['Wilt suddenly while still green, often without yellowing', 'Turn yellow slowly from the lower leaves', 'Show powdery growth', 'Develop galls'], 0,
    'Fusarium wilt usually starts with yellowing of the lower leaves.'],
  ['Both fungal and bacterial wilts cause:', ['Brown discoloration of the vascular tissue', 'Leaf spots only', 'Root galls', 'Fruit cracking only'], 0,
    'The pathogens block the xylem vessels.'],
  ['Bacterial wilt is favoured by:', ['Hot, humid weather and moist soils', 'Cold, dry weather', 'Saline soils only', 'Frost'], 0,
    'Fusarium wilt is favoured by warm, light, acid soils.'],
  ['A useful measure against bacterial wilt in brinjal is:', ['Grafting onto resistant rootstocks such as *Solanum torvum*', 'Spraying fungicides', 'Heavy nitrogen', 'Waterlogging the field'], 0,
    'Resistant varieties and crop rotation also help.'],
  ['Arka Rakshak, an IIHR tomato hybrid, resists:', ['Leaf curl virus, bacterial wilt and early blight', 'Fusarium wilt only', 'Late blight only', 'Nematodes only'], 0,
    'It was the first triple disease-resistant tomato hybrid in India.'],
  ['Fusarium wilt of vegetables is managed by:', ['Soil solarisation, *Trichoderma*, fungicide drenching and resistant varieties', 'Antibiotics', 'Insecticides', 'Deep flooding only'], 0,
    'Fusarium survives for years in the soil as chlamydospores.'],
  ['Bacterial wilt of cucurbits, spread by cucumber beetles, is caused by:', ['*Erwinia tracheiphila*', '*Ralstonia solanacearum*', '*Fusarium oxysporum*', '*Pythium*'], 0,
    'Controlling the beetles prevents the disease.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: 'IFoS-2018-A2-Q7b', q: [
  ['A parasitoid is an insect that:', ['Develops in or on a single host and eventually kills it, while the adult lives free', 'Eats many prey in its lifetime', 'Feeds only on plants', 'Lives with its host without harming it'], 0,
    'A predator consumes many prey over its life.'],
  ['*Trichogramma chilonis* is:', ['An egg parasitoid, released on "Tricho-cards"', 'A predator of aphids', 'A larval predator', 'A weed-feeding beetle'], 0,
    'It is widely used against sugarcane and cotton borers.'],
  ['The green lacewing *Chrysoperla carnea* is:', ['A predator, whose larvae are called "aphid lions"', 'An egg parasitoid', 'A plant pest', 'A pollinator only'], 0,
    'It feeds on aphids, whiteflies and small larvae.'],
  ['Ladybird beetles (coccinellids) are:', ['Predators of aphids and scale insects', 'Parasitoids', 'Pests of rice', 'Weeds'], 0,
    '*Cryptolaemus montrouzieri* is the "mealybug destroyer".'],
  ['*Bracon hebetor* is:', ['A larval ectoparasitoid', 'A predator', 'An egg parasitoid', 'A plant pathogen'], 0,
    'It develops outside the body of its caterpillar host.'],
  ['Compared with their hosts or prey, parasitoids are usually:', ['Smaller, while predators are usually larger than their prey', 'Larger, while predators are smaller', 'The same size as predators', 'Plants'], 0,
    'One host supports the whole development of a parasitoid.'],
  ['Most insect parasitoids belong to the orders:', ['Hymenoptera and Diptera', 'Coleoptera and Lepidoptera', 'Orthoptera and Hemiptera', 'Odonata and Isoptera'], 0,
    'Tachinid flies are the main dipteran parasitoids.'],
  ['A hyperparasitoid is:', ['A parasitoid that develops on another parasitoid', 'A very large predator', 'A pesticide', 'A plant'], 0,
    'Hyperparasitoids can reduce the success of biocontrol.'],
  ['The vedalia beetle *Rodolia cardinalis*, used against cottony cushion scale, is an example of:', ['A predator used in classical biological control', 'A parasitoid', 'A pathogen', 'A pesticide'], 0,
    'Its success in California (1888) launched classical biocontrol.'],
  ['An idiobiont parasitoid, unlike a koinobiont, is one that:', ['Stops the host developing further once it attacks', 'Lets the host keep growing', 'Never kills the host', 'Feeds on plants'], 0,
    'Egg and pupal parasitoids are often idiobionts.']
] },
{ p: 'A2', t: 'Floriculture & Landscaping', w: 2, pyq: 'IFoS-2018-A2-Q7c', q: [
  ['A formal garden is:', ['Symmetrical and geometric, with straight lines and clipped plants', 'Irregular and natural', 'A vegetable plot', 'A wild forest'], 0,
    'Mughal and French gardens are formal.'],
  ['An informal garden is:', ['Asymmetrical and naturalistic, with curved paths and irregular planting', 'Strictly symmetrical', 'Always square', 'Made only of hedges'], 0,
    'Japanese and English landscape gardens are informal.'],
  ['The Mughal charbagh is:', ['A four-part garden divided by water channels', 'A rock garden', 'A kitchen garden', 'A bonsai collection'], 0,
    'Shalimar Bagh and Nishat Bagh in Srinagar are examples.'],
  ['Topiary, the art of clipping shrubs into shapes, is a feature of:', ['Formal gardens', 'Informal gardens', 'Wild gardens', 'Kitchen gardens'], 0,
    'Shrubs such as *Duranta* and *Clerodendrum inerme* are used.'],
  ['The Japanese garden style is:', ['Informal and symbolic, often with rocks, water and moss', 'Formal and geometric', 'Always symmetrical', 'Without plants'], 0,
    'Zen dry gardens (karesansui) use raked gravel.'],
  ['The English landscape garden style, popularised by "Capability" Brown, is:', ['Informal, with rolling lawns, lakes and tree clumps', 'Formal, with parterres', 'A charbagh', 'Terraced and symmetrical'], 0,
    'It developed in the 18th century.'],
  ['The formal French garden of Versailles was designed by:', ['André Le Nôtre', 'Capability Brown', 'Nek Chand', 'Edwin Lutyens'], 0,
    'It is known for parterres and long vistas.'],
  ['Nek Chand’s Rock Garden in Chandigarh is an example of:', ['An informal garden', 'A formal Mughal garden', 'A botanical garden', 'A kitchen garden'], 0,
    'It is built from recycled waste materials.'],
  ['In formal gardens, balance is achieved by:', ['Symmetry — mirror-image planting on either side of an axis', 'Asymmetry', 'Random planting', 'No design'], 0,
    'Informal gardens use asymmetrical (occult) balance.'],
  ['The formal garden at Rashtrapati Bhavan, renamed Amrit Udyan in 2023, is in:', ['The Mughal style', 'The Japanese style', 'The English landscape style', 'The wild-garden style'], 0,
    'It was designed by Edwin Lutyens.']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2018-A2-Q7d', q: [
  ['Seed dormancy is:', ['A state in which a viable seed fails to germinate even under favourable conditions', 'Death of the seed', 'Germination on the plant', 'Fast germination'], 0,
    'It stops seeds germinating at the wrong time.'],
  ['Physiologically, germination is complete when:', ['The radicle emerges through the seed coat', 'The seed absorbs water', 'The first leaf opens', 'The plant flowers'], 0,
    'Seed technologists count normal seedlings instead.'],
  ['Hard-seededness (physical dormancy) in legumes is broken by:', ['Scarification — mechanical abrasion, acid or hot water', 'Cold storage only', 'Darkness', 'Adding ABA'], 0,
    'It lets water into the seed.'],
  ['Physiological dormancy is often broken by:', ['Cold stratification, after-ripening or gibberellin', 'Scarification only', 'Burning', 'Freezing in water'], 0,
    'Many temperate seeds need a moist cold period.'],
  ['The hormone that maintains seed dormancy is:', ['Abscisic acid', 'Gibberellin', 'Cytokinin', 'Ethylene'], 0,
    'Gibberellin promotes germination.'],
  ['In epigeal germination, as in bean and castor:', ['The cotyledons are pushed above the soil', 'The cotyledons stay below the soil', 'There are no cotyledons', 'The seed never germinates'], 0,
    'Pea and maize show hypogeal germination.'],
  ['Lack of dormancy in wheat or rice at harvest can lead to:', ['Pre-harvest sprouting in wet weather', 'Better grain quality', 'Higher yield', 'Longer storage'], 0,
    'A short dormancy is desirable in cereals.'],
  ['Lettuce seeds that need red light to germinate are called:', ['Positively photoblastic', 'Negatively photoblastic', 'Non-photoblastic', 'Recalcitrant'], 0,
    'Phytochrome perceives the red light.'],
  ['The Baskin and Baskin classification of dormancy includes:', ['Physiological, morphological, morphophysiological, physical and combinational dormancy', 'Only physical dormancy', 'Only chemical dormancy', 'Only light dormancy'], 0,
    'Morphological dormancy means the embryo is underdeveloped.'],
  ['Standard germination tests follow the rules of:', ['ISTA (International Seed Testing Association)', 'FAO only', 'WHO', 'OECD only'], 0,
    'Seeds are tested on paper or sand at set temperatures.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 3, pyq: 'IFoS-2018-A2-Q8a', q: [
  ['A major structural constraint on Indian food production is:', ['Small and fragmented holdings — over 85% of farmers are small or marginal', 'Too many large farms', 'Excess irrigation everywhere', 'Surplus labour on large farms'], 0,
    'The average holding is about 1.1 ha (Agriculture Census 2015–16).'],
  ['About half of India’s net sown area is:', ['Rainfed', 'Irrigated by canals', 'Under greenhouses', 'Fallow'], 0,
    'Rainfed yields are low and unstable.'],
  ['Over-exploitation of groundwater is most serious in:', ['Punjab, Haryana and Rajasthan', 'Kerala', 'Assam', 'Goa'], 0,
    'Free power and paddy procurement drive over-pumping.'],
  ['Imbalanced fertiliser use in India is mainly:', ['Excessive nitrogen relative to phosphorus and potassium', 'Excessive potassium', 'Excess micronutrients', 'No fertiliser use at all'], 0,
    'Subsidised urea is a major reason.'],
  ['The most widespread micronutrient deficiency in Indian soils is that of:', ['Zinc', 'Copper', 'Molybdenum', 'Chlorine'], 0,
    'Boron and iron deficiencies are also common.'],
  ['Low seed replacement rates limit yields because:', ['Farmers reuse old seed instead of buying quality seed of improved varieties', 'Seed is too cheap', 'Hybrids are banned', 'There is too much certified seed'], 0,
    'Replacement is especially low in pulses and oilseeds.'],
  ['Climate change threatens food production through:', ['Heat waves, erratic rainfall and more frequent droughts and floods', 'Only cooler temperatures', 'More stable weather', 'Lower CO₂'], 0,
    'Terminal heat is a major risk for wheat.'],
  ['Post-harvest losses are highest in:', ['Fruits and vegetables', 'Cereals stored in silos', 'Oilseeds', 'Pulses'], 0,
    'Weak cold chains and handling are the main causes.'],
  ['Land degradation reducing productivity includes:', ['Erosion, salinity, waterlogging and nutrient depletion', 'Afforestation', 'Mulching', 'Terracing'], 0,
    'A large part of India’s land is degraded to some degree.'],
  ['A key institutional constraint for small farmers is:', ['Poor access to credit, markets and extension services', 'Too many advisers', 'Surplus market access', 'Excess insurance'], 0,
    'FPOs and digital services aim to close these gaps.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: 'IFoS-2018-A2-Q8b', q: [
  ['The pulse beetle, the main pest of stored pulses, is:', ['*Callosobruchus chinensis* or *C. maculatus*', '*Sitophilus oryzae*', '*Tribolium castaneum*', '*Trogoderma granarium*'], 0,
    'It infests pods in the field and multiplies in store.'],
  ['The rice weevil *Sitophilus oryzae* is:', ['An internal feeder whose larvae develop inside the grain', 'A pest of flour only', 'A field pest of leaves', 'A predator'], 0,
    'It attacks rice, wheat, maize and sorghum.'],
  ['The khapra beetle (*Trogoderma granarium*) is:', ['A serious stored-grain pest whose larvae do the damage, and a major quarantine pest', 'A beneficial insect', 'A pest of green leaves', 'A pollinator'], 0,
    'Its larvae can survive long periods without food.'],
  ['The lesser grain borer is:', ['*Rhyzopertha dominica*', '*Sitotroga cerealella*', '*Corcyra cephalonica*', '*Callosobruchus chinensis*'], 0,
    'Adults and larvae bore into whole grains.'],
  ['The Angoumois grain moth (*Sitotroga cerealella*) infests:', ['Paddy, maize and wheat, starting in the field and continuing in store', 'Only flour', 'Only pulses', 'Only oilseeds'], 0,
    'The larvae feed inside the grain.'],
  ['The red flour beetle (*Tribolium castaneum*) is a:', ['Secondary pest that feeds on flour and broken grain', 'Primary pest of whole grain', 'Field pest', 'Predator'], 0,
    'Secondary pests follow damage by primary pests.'],
  ['A simple way to protect stored pulses from bruchids is to:', ['Coat the seed with edible oil (about 1%) or mix in neem leaves', 'Store the seed moist', 'Store the seed in open heaps', 'Expose the seed to rain'], 0,
    'Oil coating stops egg-laying and hatching.'],
  ['Safe storage of grain requires drying it to about:', ['10–12% moisture', '20–25% moisture', '30% moisture', '40% moisture'], 0,
    'Dry grain resists insects and moulds.'],
  ['The fumigant widely used in grain stores (by trained operators) is:', ['Aluminium phosphide, which releases phosphine', 'DDT', 'Urea', 'Copper sulphate'], 0,
    'It is extremely toxic, and the store must be sealed.'],
  ['The Pusa bin, designed by IARI, is:', ['A mud-brick storage bin with a polythene lining', 'A metal silo', 'A cold store', 'A fumigation chamber'], 0,
    'Hermetic bags such as PICS bags also protect grain.']
] },
{ p: 'A2', t: 'Post-harvest & Food Processing', w: 3, pyq: 'IFoS-2018-A2-Q8c', q: [
  ['The main principles of post-harvest management of fruits are to reduce:', ['Respiration, water loss, ethylene action and microbial decay', 'Colour development', 'Sugar content', 'Fruit size'], 0,
    'Low temperature slows all of these.'],
  ['Pre-cooling of fruits after harvest removes:', ['Field heat', 'Pesticides', 'Sugars', 'Colour'], 0,
    'Forced-air cooling, hydrocooling and room cooling are used.'],
  ['Harvest maturity of fruits is judged by indices such as:', ['TSS, firmness, colour and days from flowering', 'Plant height', 'Leaf number', 'Root length'], 0,
    'Mature mangoes sink in water (specific gravity above one).'],
  ['Chilling injury occurs in tropical fruits such as banana when they are stored below about:', ['13 °C', '25 °C', '30 °C', '40 °C'], 0,
    'Symptoms include skin browning and failure to ripen.'],
  ['Controlled-atmosphere storage of apples uses:', ['Low oxygen and raised carbon dioxide at low temperature', 'Pure oxygen', 'High ethylene', 'Warm, humid air'], 0,
    'It slows respiration and ripening for months.'],
  ['Waxing fruits such as citrus and apple mainly:', ['Reduces moisture loss and improves appearance', 'Speeds ripening', 'Adds sugar', 'Kills fruit flies'], 0,
    'Approved food-grade waxes are used.'],
  ['Potassium permanganate sachets in fruit packages act as:', ['Ethylene absorbers', 'Colouring agents', 'Fungicides only', 'Sweeteners'], 0,
    'They delay ripening during transport.'],
  ['Hot-water treatment of mango (about 52 °C for 5 minutes) helps control:', ['Anthracnose and stem-end rot', 'Mango hopper', 'Malformation', 'Fruit cracking'], 0,
    'Vapour heat treatment is used against fruit flies for export.'],
  ['The Zero Energy Cool Chamber developed by IARI works by:', ['Evaporative cooling through wet sand between double brick walls', 'Refrigeration', 'Solar heating', 'Chemical cooling'], 0,
    'It keeps produce cooler and humid without electricity.'],
  ['The usual sequence of operations in a fruit pack house is:', ['Sorting → washing → grading → treating/waxing → packing', 'Packing → sorting → harvesting', 'Waxing → harvesting → sorting', 'Grading → harvesting → washing'], 0,
    'Corrugated fibreboard boxes reduce transit damage.']
] }
);
