/* PYQ-linked MCQs — IFoS 2018 Botany Paper I (verbatim PYQs). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Microbiology', w: 2, pyq: 'IFoS-2018-B1-Q1a', q: [
  ['Peptidoglycan (murein) in the cell wall is found in:', ['Bacteria, but not Archaea', 'Archaea only', 'Both Bacteria and Archaea', 'Neither group'], 0,
    'Archaea have pseudomurein, S-layers or other polymers, never true murein.'],
  ['Membrane lipids of Archaea consist of:', ['Isoprenoid chains ether-linked to glycerol-1-phosphate', 'Fatty acids ester-linked to glycerol-3-phosphate', 'Sterols only', 'Sphingolipids only'], 0,
    'Bacteria and eukaryotes use ester-linked fatty acids on glycerol-3-phosphate.'],
  ['Carl Woese separated Archaea from Bacteria on the basis of:', ['16S rRNA sequence comparison', 'Cell shape', 'Gram staining', 'Type of flagella'], 0,
    'His 1977–1990 work led to the three-domain system: Bacteria, Archaea, Eukarya.'],
  ['The initiator tRNA of Archaea carries:', ['Unformylated methionine, as in eukaryotes', 'N-formylmethionine, as in bacteria', 'Leucine', 'Selenocysteine'], 0,
    'Only Bacteria (and organelles) start protein synthesis with fMet.'],
  ['Archaeal RNA polymerase resembles:', ['Eukaryotic RNA polymerase II, with many subunits', 'The simple bacterial core enzyme', 'A single-subunit phage polymerase', 'Reverse transcriptase'], 0,
    'Archaeal promoters also have a TATA box bound by a TBP homologue.'],
  ['Antibiotics such as penicillin, streptomycin and chloramphenicol generally:', ['Act on Bacteria but not on Archaea', 'Act on Archaea but not on Bacteria', 'Act equally on both', 'Act on neither'], 0,
    'The drug targets (murein, bacterial-type ribosomes) differ in Archaea.'],
  ['Biological methanogenesis is carried out only by:', ['Archaea', 'Bacteria', 'Fungi', 'Cyanobacteria'], 0,
    'Methanogens (e.g., *Methanobacterium*) live in rice fields, wetlands and the rumen.'],
  ['Which of these is an archaeon?', ['*Halobacterium salinarum*', '*Escherichia coli*', '*Bacillus subtilis*', '*Streptomyces griseus*'], 0,
    'Extreme halophiles, methanogens and thermoacidophiles (*Sulfolobus*) are Archaea.'],
  ['True histone homologues that wrap DNA into nucleosome-like particles occur in:', ['Many Archaea, but not Bacteria', 'Bacteria only', 'Neither group', 'Only viruses'], 0,
    'Bacteria compact DNA with other nucleoid proteins such as HU.'],
  ['A feature shared by Bacteria and Archaea, which sets them apart from eukaryotes, is:', ['No nucleus and 70S ribosomes', 'Ether-linked lipids', 'Peptidoglycan walls', 'Mitochondria'], 0,
    'Both are prokaryotes; the differences lie in their lipids, walls and gene expression machinery.']
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 2, pyq: 'IFoS-2018-B1-Q1b', q: [
  ['The cell wall of oomycetes such as *Phytophthora* is made mainly of:', ['Cellulose and β-glucans, with little or no chitin', 'Chitin', 'Peptidoglycan', 'Silica'], 0,
    'Chitin is the typical wall polymer of true fungi.'],
  ['The vegetative hyphae of oomycetes are:', ['Diploid', 'Haploid', 'Dikaryotic', 'Triploid'], 0,
    'Meiosis occurs in the gametangia; true fungi are mostly haploid or dikaryotic.'],
  ['Oomycete zoospores have:', ['Two heterokont flagella: an anterior tinsel and a posterior whiplash', 'One posterior whiplash flagellum', 'No flagella', 'Many equal flagella'], 0,
    'Tinsel flagella with tripartite hairs mark the Stramenopiles.'],
  ['Current classification places Oomycota in:', ['Stramenopiles (Heterokonta), with brown algae and diatoms', 'Kingdom Fungi, with Ascomycota', 'Plantae', 'Monera'], 0,
    'The resemblance to fungi is convergent; molecular data link them to brown algae.'],
  ['Lysine is synthesised in oomycetes by:', ['The diaminopimelic acid (DAP) pathway, as in plants', 'The α-aminoadipic acid (AAA) pathway, as in true fungi', 'Both pathways equally', 'Neither pathway'], 0,
    'This biochemical difference is a classic argument against calling them fungi.'],
  ['Mitochondrial cristae in oomycetes are:', ['Tubular', 'Flat and plate-like, as in true fungi', 'Absent', 'Discoid'], 0,
    'Tubular cristae are shared with other stramenopiles.'],
  ['Sexual reproduction in *Albugo* is:', ['Oogamous, giving thick-walled oospores', 'Isogamous', 'By basidiospores', 'By ascospores'], 0,
    'Oospores give the group its name, Oomycetes ("egg fungi").'],
  ['*Albugo candida* causes:', ['White rust of crucifers', 'Late blight of potato', 'Downy mildew of grapes', 'Black stem rust of wheat'], 0,
    'Downy mildew of grapes is caused by another oomycete, *Plasmopara viticola*.'],
  ['*Phytophthora infestans* causes:', ['Late blight of potato', 'Early blight of potato', 'Wart of potato', 'Black scurf of potato'], 0,
    'Early blight is caused by *Alternaria solani*, a true fungus.'],
  ['Metalaxyl, a phenylamide fungicide, is specifically effective against:', ['Oomycetes such as *Phytophthora*, *Pythium* and downy mildews', 'Rusts', 'Smuts', 'Powdery mildews'], 0,
    'Its narrow target range again shows how different oomycetes are from true fungi.']
] },
{ p: 'B1', t: 'Algae', w: 2, pyq: 'IFoS-2018-B1-Q1c', q: [
  ['The photosynthetic pigments of Rhodophyta are:', ['Chlorophyll *a*, phycoerythrin and phycocyanin', 'Chlorophylls *a* and *b*', 'Chlorophylls *a* and *c* with fucoxanthin', 'Chlorophyll *b* only'], 0,
    'Chlorophyta have chlorophylls *a* and *b*, as land plants do.'],
  ['The reserve food of Chlorophyta is:', ['Starch, stored inside the chloroplast (often around pyrenoids)', 'Floridean starch in the cytoplasm', 'Laminarin', 'Mannitol only'], 0,
    'Green algae share plastid starch with land plants.'],
  ['Floridean starch, the reserve of red algae, is stored:', ['In the cytoplasm, outside the plastid', 'Inside the thylakoids', 'In the nucleus', 'In the pyrenoid only'], 0,
    'It is an amylopectin-like glucan.'],
  ['Flagella in Rhodophyta are:', ['Absent at all stages of the life cycle', 'Two and equal', 'Two and unequal', 'Many'], 0,
    'Green algae have flagellated zoospores and gametes.'],
  ['The male gametes of red algae are:', ['Non-motile spermatia', 'Biflagellate antherozoids', 'Multiflagellate sperms', 'Amoeboid cells'], 0,
    'Spermatia are carried to the trichogyne by water currents.'],
  ['The female sex organ of red algae is:', ['A carpogonium with a trichogyne', 'An oogonium without a trichogyne', 'An archegonium', 'A conceptacle'], 0,
    'After fertilisation it gives rise to a carposporophyte.'],
  ['The life cycle of *Polysiphonia* is:', ['Triphasic: gametophyte, carposporophyte and tetrasporophyte', 'Diphasic', 'Monophasic haplontic', 'Monophasic diplontic'], 0,
    'Most green algae have haplontic or diplohaplontic two-phase cycles.'],
  ['Pit connections between adjacent cells are characteristic of:', ['Red algae (Florideophyceae)', 'Green algae', 'Diatoms', 'Blue-green algae'], 0,
    'They are plugged cytoplasmic connections left after incomplete cell division.'],
  ['Agar and carrageenan are commercial products of:', ['Rhodophyta (e.g., *Gelidium*, *Gracilaria*, *Kappaphycus*)', 'Chlorophyta', 'Diatoms', 'Cyanobacteria'], 0,
    'Alginates come from brown algae.'],
  ['The thylakoids in a red algal chloroplast are:', ['Single and unstacked, with phycobilisomes on their surface', 'Stacked into grana', 'In bands of three', 'Absent'], 0,
    'Green algae have thylakoids in stacks of two to six or more.']
] },
{ p: 'B1', t: 'Bryophytes', w: 2, pyq: 'IFoS-2018-B1-Q1d', q: [
  ['The peristome of a moss capsule is located:', ['At the mouth of the capsule, beneath the operculum', 'At the base of the seta', 'In the foot', 'On the calyptra'], 0,
    'It is a ring of teeth exposed when the operculum falls off.'],
  ['The main role of the peristome is to:', ['Regulate spore dispersal by hygroscopic movements', 'Photosynthesise', 'Absorb water from the soil', 'Anchor the sporophyte'], 0,
    'It releases spores gradually rather than all at once.'],
  ['The peristome of *Funaria* is:', ['Double (diplolepidous), with 16 outer and 16 inner teeth', 'Single, with 32 teeth', 'Absent', 'Single, with four teeth'], 0,
    'The inner teeth form the endostome and the outer ones the exostome.'],
  ['Arthrodontous peristome teeth are formed from:', ['Thickened remnants of cell walls, not whole cells', 'Entire dead cells', 'Living cells', 'Elaters'], 0,
    'Most mosses, including *Funaria* and *Bryum*, are arthrodontous.'],
  ['A nematodontous peristome made of whole cells occurs in:', ['*Polytrichum* and *Tetraphis*', '*Funaria*', '*Bryum*', '*Sphagnum*'], 0,
    '*Tetraphis* has only four teeth.'],
  ['Peristome teeth develop from:', ['The inner layers of the amphithecium', 'The columella', 'The foot', 'The calyptra'], 0,
    'Peristome formulae count the cells of the outer, primary and inner peristomial layers.'],
  ['A peristome is absent in:', ['*Sphagnum*, which discharges spores explosively', '*Funaria*', '*Polytrichum*', '*Bryum*'], 0,
    'Its capsule shrinks and blows off the operculum by an "air-gun" mechanism.'],
  ['In dry weather the peristome teeth of *Funaria*:', ['Bend outwards, allowing spores to escape', 'Close tightly over the mouth', 'Fall off', 'Absorb water'], 0,
    'They close in moist air, so spores are released when conditions favour dispersal.'],
  ['The operculum of a moss capsule is shed after:', ['The breakdown of the annulus', 'The rupture of the calyptra', 'The decay of the foot', 'The withering of the seta'], 0,
    'The annulus is a ring of thin-walled cells between the operculum and the theca.'],
  ['The capsule of *Andreaea* opens by:', ['Four longitudinal slits, with no peristome', 'An operculum and peristome', 'Explosive discharge', 'Decay of the capsule wall'], 0,
    'This primitive dehiscence is unlike that of true mosses (Bryopsida).']
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, pyq: 'IFoS-2018-B1-Q1e', q: [
  ['Coralloid roots are found in:', ['*Cycas*', '*Pinus*', '*Gnetum*', '*Ephedra*'], 0,
    'They occur in all cycads, including *Zamia* and *Encephalartos*.'],
  ['Coralloid roots harbour:', ['Cyanobacteria such as *Anabaena* and *Nostoc*', '*Rhizobium*', '*Frankia*', 'Ectomycorrhizal fungi'], 0,
    '*Frankia* forms nodules in *Casuarina* and *Alnus*.'],
  ['Coralloid roots grow:', ['Upwards towards the soil surface (apogeotropic)', 'Deep down (positively geotropic)', 'Horizontally at great depth', 'From the stem as aerial roots'], 0,
    'Growing near the surface gives the cyanobiont access to light and air.'],
  ['Their branching pattern is:', ['Repeatedly dichotomous, giving a coral-like cluster', 'Racemose', 'Absent', 'Whorled'], 0,
    'The coral-like shape gives them their name.'],
  ['The cyanobacteria inside a coralloid root lie in:', ['A distinct algal zone in the middle cortex', 'The xylem', 'The pith', 'The root cap'], 0,
    'The zone lies between the inner and outer cortex.'],
  ['The main role of coralloid roots is:', ['Fixing atmospheric nitrogen for the plant', 'Storing water', 'Secreting resin', 'Absorbing phosphorus only'], 0,
    'The cyanobacteria fix N₂ in their heterocysts.'],
  ['Lenticels on coralloid roots help in:', ['Gaseous exchange (aeration)', 'Water storage', 'Seed dispersal', 'Pollination'], 0,
    'The cyanobiont needs oxygen and CO₂ exchange.'],
  ['Compared with free-living *Nostoc*, the symbiotic *Nostoc* in coralloid roots has:', ['A higher frequency of heterocysts', 'No heterocysts', 'The same frequency of heterocysts', 'Only akinetes'], 0,
    'More heterocysts means more nitrogen fixation for the host.'],
  ['Coralloid roots arise:', ['As branches of lateral roots near the soil surface', 'From the primary root tip only', 'From leaves', 'From the ovule'], 0,
    'Precoralloid roots become coralloid once the cyanobiont invades.'],
  ['Coralloid roots lack:', ['Root hairs', 'A cortex', 'Vascular tissue', 'An epidermis'], 0,
    'They are specialised for symbiosis, not absorption.']
] },
{ p: 'B1', t: 'Plant Pathology', w: 3, pyq: 'IFoS-2018-B1-Q2a', q: [
  ['Loose smut of wheat is caused by:', ['*Ustilago segetum* var. *tritici* (*U. nuda tritici*)', '*Tilletia caries*', '*Ustilago hordei*', '*Urocystis agropyri*'], 0,
    '*Urocystis agropyri* causes flag smut of wheat.'],
  ['Covered smut (bunt, stinking smut) of wheat is caused by:', ['*Tilletia caries* and *T. foetida*', '*Ustilago segetum* var. *tritici*', '*Puccinia graminis*', '*Neovossia indica*'], 0,
    'In barley, covered smut is caused by *Ustilago hordei*.'],
  ['The inoculum of loose smut is:', ['Internally seed-borne, as dormant mycelium in the embryo', 'Soil-borne', 'Externally seed-borne only', 'Carried by insects'], 0,
    'Surface seed dressings therefore do not control it.'],
  ['Loose smut infects wheat plants:', ['At flowering, when spores land on the stigma or ovary', 'At seedling emergence, through the coleoptile', 'Through the roots', 'After harvest, in storage'], 0,
    'Infected seed looks normal but carries the fungus to the next crop.'],
  ['Bunt infects wheat plants:', ['At seedling emergence, from spores on the seed or in soil, through the coleoptile', 'At flowering', 'Through the roots at maturity', 'Through insect wounds'], 0,
    'It is externally seed-borne and soil-borne, so seed dressing works.'],
  ['An ear affected by loose smut shows:', ['Black, powdery spore masses that blow away, leaving a bare rachis', 'Grains replaced by bunt balls inside an intact pericarp', 'Healthy grains with leaf stripes', 'Galls on the leaves'], 0,
    'Smutted ears emerge slightly earlier than healthy ones.'],
  ['In bunt, the infected grains:', ['Become bunt balls that keep the grain shape and smell fishy', 'Are replaced by loose powder', 'Germinate on the ear', 'Stay healthy'], 0,
    'The fishy smell is trimethylamine.'],
  ['Loose smut is best managed by:', ['Solar heat or hot-water seed treatment, or systemic fungicides such as carboxin or tebuconazole', 'Copper dusting of the seed surface only', 'Sulphur sprays at flowering', 'Crop rotation alone'], 0,
    'The fungus must be killed inside the embryo.'],
  ['Bunt is controlled mainly by:', ['Seed treatment with fungicides and clean seed', 'Hot-water treatment only', 'Removing alternate hosts', 'Late sowing'], 0,
    'Surface-borne spores are easily reached by seed dressings.'],
  ['Karnal bunt (partial bunt) of wheat is caused by:', ['*Tilletia indica* (*Neovossia indica*)', '*Ustilago segetum* var. *tritici*', '*Puccinia striiformis*', '*Urocystis agropyri*'], 0,
    'Only part of the grain is converted to a black, fishy-smelling spore mass.']
] },
{ p: 'B1', t: 'Pteridophytes', w: 3, pyq: 'IFoS-2018-B1-Q2b', q: [
  ['The most primitive type of stele is the:', ['Protostele (haplostele)', 'Siphonostele', 'Dictyostele', 'Eustele'], 0,
    'A solid core of xylem surrounded by phloem, as in *Rhynia*.'],
  ['An actinostele, with star-shaped xylem, is found in the stem of:', ['*Psilotum*', '*Pteris*', '*Marsilea*', '*Osmunda*'], 0,
    'The actinostele is a modified protostele.'],
  ['A plectostele, with xylem in parallel plates alternating with phloem, occurs in:', ['*Lycopodium*', '*Adiantum*', '*Equisetum*', '*Marsilea*'], 0,
    'It is another modified protostele.'],
  ['Polystely, with many separate protosteles in one stem, occurs in:', ['*Selaginella* (e.g., *S. laevigata*)', '*Pteris*', '*Equisetum*', '*Osmunda*'], 0,
    '*S. kraussiana* is distelic.'],
  ['According to Jeffrey’s extrastelar theory, the pith of a siphonostele originated from:', ['Cortex invading the stele through leaf and branch gaps', 'Conversion of the central tracheids', 'The phloem', 'The endodermis'], 0,
    'The rival intrastelar theory derives the pith from the central xylem itself.'],
  ['An amphiphloic siphonostele (solenostele) is seen in the rhizome of:', ['*Marsilea*', '*Osmunda*', '*Rhynia*', '*Psilotum*'], 0,
    '*Osmunda* has an ectophloic siphonostele, with phloem outside only.'],
  ['A dictyostele results from:', ['Overlapping leaf gaps that split the siphonostele into meristeles', 'The fusion of several protosteles', 'The loss of the pith', 'Secondary growth'], 0,
    'Dictyosteles occur in *Pteris*, *Dryopteris* and *Adiantum*.'],
  ['A polycyclic stele, with two or more concentric vascular rings, is found in:', ['*Pteridium aquilinum*', '*Psilotum*', '*Rhynia*', '*Lycopodium*'], 0,
    'It is the most complex stele among ferns.'],
  ['Leaf gaps are characteristic of the stele in:', ['Pteropsida (macrophyllous ferns), not Lycopsida', 'Lycopsida only', 'Both groups', 'Neither group'], 0,
    'Microphyllous lycopods have leaf traces but no leaf gaps.'],
  ['The general trend in stelar evolution among pteridophytes is:', ['From a solid protostele to dissected steles with more conducting surface', 'From a dictyostele back to a protostele', 'Loss of the xylem', 'No change'], 0,
    'Larger plants with bigger leaves needed more efficient conduction.']
] },
{ p: 'B1', t: 'Algae', w: 2, pyq: 'IFoS-2018-B1-Q2c', q: [
  ['Fucoxanthin, which gives brown algae their colour, is found in:', ['Phaeophyceae and diatoms', 'Chlorophyceae', 'Rhodophyceae', 'Cyanophyceae'], 0,
    'It is a xanthophyll that absorbs blue-green light.'],
  ['Chlorophyll *c* is found in:', ['Brown algae, diatoms and dinoflagellates', 'Green algae', 'Red algae', 'Blue-green algae'], 0,
    'These groups acquired their plastids by secondary endosymbiosis of a red alga.'],
  ['Among algae, chlorophyll *b* is found in:', ['Chlorophyceae and Euglenophyceae', 'Phaeophyceae', 'Rhodophyceae', 'Bacillariophyceae'], 0,
    'The plastids of euglenoids came from a green alga.'],
  ['Phycobilins (phycoerythrin, phycocyanin) are found in:', ['Cyanophyceae and Rhodophyceae', 'Chlorophyceae', 'Phaeophyceae', 'Bacillariophyceae'], 0,
    'They are water-soluble and housed in phycobilisomes.'],
  ['Phycoerythrin mainly absorbs:', ['Green light, which lets red algae grow at depth', 'Red light', 'Far-red light only', 'Ultraviolet light only'], 0,
    'Green and blue light penetrate deepest into seawater.'],
  ['Peridinin is the characteristic carotenoid of:', ['Dinoflagellates', 'Green algae', 'Red algae', 'Brown algae'], 0,
    'Peridinin–chlorophyll–protein complexes harvest light in dinoflagellates.'],
  ['Chlorophyll *d*, which absorbs far-red light, is best known from:', ['The cyanobacterium *Acaryochloris marina* (earlier reported in red algae)', 'Green algae', 'Brown algae', 'Euglenoids'], 0,
    'It lets *Acaryochloris* use light filtered through other algae.'],
  ['Complementary chromatic adaptation (Gaidukov phenomenon) in cyanobacteria means:', ['Changing the ratio of phycoerythrin to phycocyanin according to light colour', 'Losing chlorophyll in the dark', 'Forming heterocysts', 'Moving towards light'], 0,
    'Cells grown in green light make more phycoerythrin.'],
  ['The pigment present in the reaction centre of all photosynthetic algae is:', ['Chlorophyll *a*', 'Chlorophyll *b*', 'Chlorophyll *c*', 'Phycoerythrin'], 0,
    'Accessory pigments pass their absorbed energy to it.'],
  ['Siphonaxanthin, which absorbs green light, is characteristic of:', ['Deep-water siphonous green algae such as *Codium*', 'Brown kelps', 'Diatoms', 'Blue-green algae'], 0,
    'It extends light harvesting in green algae living at depth.']
] },
{ p: 'B1', t: 'Microbiology', w: 2, pyq: 'IFoS-2018-B1-Q3a', q: [
  ['Microbes suit industrial production because they:', ['Grow fast, have a high surface-to-volume ratio, use cheap substrates and are easy to modify genetically', 'Grow slowly and are large', 'Cannot mutate', 'Need sunlight'], 0,
    'Their products can also be scaled up in fermenters.'],
  ['Citric acid is produced commercially by:', ['*Aspergillus niger*', '*Saccharomyces cerevisiae*', '*Penicillium chrysogenum*', '*Streptomyces griseus*'], 0,
    'It is used as a food acidulant and preservative.'],
  ['Streptomycin is obtained from:', ['*Streptomyces griseus*', '*Penicillium chrysogenum*', '*Bacillus subtilis*', '*Aspergillus niger*'], 0,
    'Selman Waksman’s group discovered it in 1943.'],
  ['Recombinant human insulin (1982) was first produced commercially in:', ['*Escherichia coli*', '*Bacillus thuringiensis*', '*Aspergillus niger*', 'Plant cells'], 0,
    'The A and B chains were made separately and then joined.'],
  ['Cyclosporin A, an immunosuppressant used in organ transplants, comes from the fungus:', ['*Tolypocladium inflatum*', '*Monascus purpureus*', '*Aspergillus niger*', '*Rhizopus*'], 0,
    'It prevents rejection by suppressing T-cells.'],
  ['Cholesterol-lowering statins were first obtained from:', ['Fungi such as *Monascus purpureus* and *Aspergillus terreus*', '*Streptococcus*', '*Escherichia coli*', 'Yeast'], 0,
    'Lovastatin inhibits HMG-CoA reductase.'],
  ['Streptokinase, used to dissolve blood clots, is produced by:', ['*Streptococcus*', '*Streptomyces*', '*Penicillium*', '*Trichoderma*'], 0,
    'It activates plasminogen to plasmin.'],
  ['The biodegradable plastic polyhydroxybutyrate (PHB) is made by bacteria such as:', ['*Cupriavidus necator* (*Ralstonia eutropha*)', '*Lactobacillus*', '*Clostridium tetani*', '*Mycobacterium*'], 0,
    'PHB is stored as a carbon reserve when nutrients are unbalanced.'],
  ['Xanthan gum, a food thickener, is produced by:', ['*Xanthomonas campestris*', '*Aspergillus oryzae*', '*Bacillus subtilis*', '*Rhizobium*'], 0,
    'It is an extracellular polysaccharide.'],
  ['Spinosad, a bio-insecticide, is made by fermentation of:', ['*Saccharopolyspora spinosa*', '*Bacillus thuringiensis*', '*Trichoderma viride*', '*Beauveria bassiana*'], 0,
    'It is an actinomycete product acting on insect nerve receptors.']
] },
{ p: 'B1', t: 'Bryophytes', w: 2, pyq: 'IFoS-2018-B1-Q3b', q: [
  ['Bower’s theory of progressive sterilisation takes the most primitive bryophyte sporophyte to be that of:', ['*Riccia*', '*Funaria*', '*Anthoceros*', '*Polytrichum*'], 0,
    'In *Riccia* nearly all internal tissue is sporogenous.'],
  ['The sporophyte of *Riccia* consists of:', ['A capsule only, with no foot or seta', 'Foot, seta and capsule', 'Foot and capsule', 'Seta only'], 0,
    'Its wall layer is the only sterile tissue.'],
  ['In *Riccia*, a few sporogenous cells degenerate to act as:', ['Nurse cells that nourish the developing spores', 'Elaters', 'A columella', 'Seta cells'], 0,
    'This is the first sign of sterilisation of sporogenous tissue.'],
  ['The sporophyte of *Marchantia* has:', ['Foot, seta and capsule, with elaters among the spores', 'A capsule only', 'Foot and capsule, without elaters', 'A columella'], 0,
    'More sterile tissue shows a further step of sterilisation.'],
  ['Elaters are:', ['Elongated sterile cells with spiral thickenings that help disperse spores', 'Fertile spores', 'Glandular hairs', 'Photosynthetic cells'], 0,
    'Their hygroscopic twisting loosens the spore mass.'],
  ['In *Anthoceros*, the sterile cells mixed with the spores are:', ['Multicellular pseudo-elaters without spiral bands', 'True spiral elaters', 'Absent', 'Peristome teeth'], 0,
    'They are also derived from sterilised sporogenous cells.'],
  ['The *Anthoceros* sporophyte keeps growing because of:', ['A basal intercalary meristem between the foot and the capsule', 'An apical cell', 'A lateral cambium', 'A cork cambium'], 0,
    'It also has a columella and stomata — signs of an advanced sporophyte.'],
  ['A sterile central columella in the capsule is found in:', ['*Anthoceros* and mosses', '*Riccia*', '*Marchantia*', 'All liverworts'], 0,
    'The columella is a large block of sterilised tissue.'],
  ['A basal elaterophore bearing a tuft of elaters occurs in:', ['*Pellia*', '*Riccia*', '*Funaria*', '*Sphagnum*'], 0,
    'In *Riccardia* the elaterophore is apical.'],
  ['The opposing view — that *Riccia*’s simple sporophyte is a reduced form rather than a primitive one — was supported by:', ['Goebel, Church and Kashyap', 'F. O. Bower', 'W. Zimmermann', 'Charles Darwin'], 0,
    'It is called the theory of progressive reduction.']
] },
{ p: 'B1', t: 'Microbiology', w: 2, pyq: 'IFoS-2018-B1-Q3c', q: [
  ['The genome of tobacco mosaic virus is:', ['Single-stranded, positive-sense RNA of about 6,400 nucleotides', 'Double-stranded DNA', 'Single-stranded DNA', 'Double-stranded RNA'], 0,
    'It acts directly as messenger RNA after entering the cell.'],
  ['The TMV particle is:', ['A rigid rod about 300 nm long and 18 nm wide', 'An icosahedron 20 nm across', 'An enveloped sphere', 'A tailed phage'], 0,
    'The RNA runs in a helix inside the protein tube.'],
  ['The TMV capsid is made of:', ['About 2,130 identical coat-protein subunits in a helix', '60 subunits forming an icosahedron', 'A lipid envelope', 'Two protein types'], 0,
    'Each subunit has 158 amino acids (about 17.5 kDa).'],
  ['By weight, TMV is about:', ['95% protein and 5% RNA', '50% protein and 50% RNA', '5% protein and 95% RNA', 'Mostly lipid'], 0,
    'The RNA is well protected inside the protein coat.'],
  ['TMV enters host cells through:', ['Mechanical wounds, since it has no specific insect vector', 'The stylets of aphids only', 'Open stomata', 'Fungal zoospores'], 0,
    'It spreads on hands, tools and rubbing leaves; it is very stable outside the host.'],
  ['TMV moves from cell to cell through:', ['Plasmodesmata, aided by its 30-kDa movement protein', 'Xylem vessels', 'Sieve plates only', 'Stomata'], 0,
    'Long-distance spread is through the phloem.'],
  ['The experiment showing that TMV RNA alone determines the progeny virus was done by:', ['Fraenkel-Conrat and Singer (1957)', 'Hershey and Chase', 'Stanley', 'Ivanovsky'], 0,
    'Reconstituted hybrid viruses produced progeny matching the RNA donor.'],
  ['Who crystallised TMV in 1935?', ['W. M. Stanley', 'D. Ivanovsky', 'M. W. Beijerinck', 'F. C. Bawden'], 0,
    'Ivanovsky showed filterability (1892); Beijerinck called it "contagium vivum fluidum".'],
  ['On *Nicotiana glutinosa*, TMV produces:', ['Local necrotic lesions (a hypersensitive response due to the *N* gene)', 'Systemic mosaic', 'Wilting', 'Galls'], 0,
    'Counting local lesions was used to assay virus concentration.'],
  ['The typical symptom of TMV in susceptible tobacco is:', ['Mosaic — light and dark green mottling of leaves', 'Wilting', 'Root galls', 'White powdery growth'], 0,
    'Leaves may also be distorted and blistered.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 3, pyq: 'IFoS-2018-B1-Q4a', q: [
  ['The female cone of *Pinus* consists of:', ['Spirally arranged bract scales, each with an ovuliferous scale in its axil', 'Microsporophylls', 'Whorled leafy sporophylls', 'A single megasporophyll'], 0,
    'Each bract scale plus ovuliferous scale is a seed-scale complex.'],
  ['Each ovuliferous scale of *Pinus* bears:', ['Two ovules on the upper surface, with micropyles facing the cone axis', 'One ovule on the lower surface', 'Four ovules', 'Many ovules'], 0,
    'Each seed develops a wing from the scale tissue.'],
  ['The ovule of *Pinus* is:', ['Orthotropous and unitegmic', 'Anatropous and bitegmic', 'Campylotropous', 'Circinotropous'], 0,
    'Its single integument has three layers.'],
  ['From pollination, a female cone of *Pinus* takes about how long to shed seed?', ['About two years, with fertilisation about a year after pollination', 'One month', 'One week', 'Ten years'], 0,
    'Pollen tubes grow very slowly through the nucellus.'],
  ['In the *Pinus* female cone, the bract scale is:', ['Small and fused at its base to the larger ovuliferous scale', 'Larger than the ovuliferous scale', 'Absent', 'Completely fused and invisible'], 0,
    'In *Pseudotsuga* the bract is long and projects from the cone.'],
  ['According to Florin, the ovuliferous scale of conifers is:', ['A reduced, flattened fertile dwarf shoot in the axil of the bract', 'A megasporophyll', 'An outgrowth of the bract scale', 'An integument'], 0,
    'This is the most widely accepted interpretation.'],
  ['Evidence that the ovuliferous scale is a shoot includes:', ['Its vascular bundles are inverted relative to those of the bract scale', 'It has stomata', 'It has resin canals', 'It is green'], 0,
    'The inversion shows it arises in the axil of the bract, like a branch.'],
  ['Fossil conifers that support Florin’s interpretation are:', ['*Lebachia* and *Voltzia* (Voltziales)', '*Rhynia*', '*Lepidodendron*', '*Calamites*'], 0,
    'They show axillary fertile short shoots with sterile scales and ovules.'],
  ['In the megaspore tetrad of *Pinus*, the functional megaspore is:', ['The chalazal one of a linear tetrad', 'The micropylar one', 'All four', 'None'], 0,
    'It forms the female gametophyte (endosperm) and archegonia.'],
  ['At pollination in *Pinus*, pollen enters the ovule by:', ['A pollination drop secreted at the micropyle', 'Nectar from the ovuliferous scale', 'Resin from the bract', 'Insect visits'], 0,
    'The drop is withdrawn, drawing the pollen onto the nucellus.']
] },
{ p: 'B1', t: 'Pteridophytes', w: 2, pyq: 'IFoS-2018-B1-Q4b', q: [
  ['Which feature of *Selaginella* is a step towards the seed habit?', ['Heterospory, with gametophytes developing inside the spores', 'Homospory', 'A free-living photosynthetic gametophyte', 'Isomorphic alternation of generations'], 0,
    'Seeds evolved from heterosporous ancestors.'],
  ['In *Selaginella rupestris*, the megasporangium:', ['Often has one functional megaspore, and the embryo starts developing while it is still on the plant', 'Holds many megaspores', 'Has no megaspores', 'Holds only microspores'], 0,
    'This comes closest to retaining the megaspore, as in a seed.'],
  ['The number of megaspores in a typical *Selaginella* megasporangium is:', ['Four (one tetrad)', 'Sixty-four', 'Eight', 'Hundreds'], 0,
    'The other megaspore mother cells degenerate.'],
  ['*Selaginella* microspores begin to germinate:', ['Inside the microsporangium, before being shed', 'Only after long dormancy', 'Never', 'Only on the megaspore wall'], 0,
    'Early germination shortens the gametophyte phase.'],
  ['The gametophytes of *Selaginella* are:', ['Much reduced and endosporic, living on the food stored in the spore', 'Free-living and photosynthetic', 'Subterranean and mycorrhizal', 'Large and epiphytic'], 0,
    'Seed plants carry this reduction further.'],
  ['*Selaginella* falls short of the true seed habit mainly because:', ['Its megasporangium has no integument and the embryo has no dormancy inside a seed coat', 'It is homosporous', 'It has no megaspores', 'Its fertilisation needs no water'], 0,
    'The megaspore is usually shed before fertilisation too.'],
  ['Fertilisation in *Selaginella* requires:', ['Water, for the motile biflagellate antherozoids', 'A pollen tube', 'Wind', 'Insects'], 0,
    'Seed plants later freed fertilisation from water.'],
  ['Heterospory evolved:', ['Independently in several lineages, e.g., *Selaginella*, *Isoetes*, *Marsilea*, *Salvinia*, *Azolla*', 'Only once', 'Never in ferns', 'Only in mosses'], 0,
    'It is a classic example of convergent evolution.'],
  ['A fossil lycopod whose megasporangium was enclosed in an integument-like outgrowth is:', ['*Lepidocarpon*', '*Rhynia*', '*Calamites*', '*Psilophyton*'], 0,
    'It is the lycopod closest to a true seed.'],
  ['The ligule of *Selaginella* is:', ['A small membranous outgrowth on the upper side of each leaf base', 'A root', 'A sporangium', 'A rhizophore'], 0,
    'It is thought to keep young leaves and sporangia moist.']
] },
{ p: 'B1', t: 'Plant Pathology', w: 3, pyq: 'IFoS-2018-B1-Q4c', q: [
  ['Systemic acquired resistance (SAR) is:', ['Long-lasting, broad-spectrum resistance throughout the plant, induced by a local infection', 'Short-lived resistance only at the infection site', 'Race-specific resistance from one R gene', 'Chemical injury to the pathogen'], 0,
    'It primes uninfected parts of the plant against later attack.'],
  ['The key signal molecule required for SAR is:', ['Salicylic acid', 'Jasmonic acid', 'Ethylene', 'Gibberellin'], 0,
    'Salicylic acid builds up in both infected and distant leaves.'],
  ['Transgenic *NahG* plants cannot develop SAR because they:', ['Degrade salicylic acid with salicylate hydroxylase', 'Overproduce salicylic acid', 'Lack chlorophyll', 'Lack ethylene receptors'], 0,
    'This proved that salicylic acid is required for SAR.'],
  ['The master regulator of salicylic-acid-dependent SAR is:', ['NPR1', 'DELLA', 'PIN1', 'FLC'], 0,
    'NPR1 moves to the nucleus and activates the PR genes.'],
  ['SAR marker genes encode:', ['Pathogenesis-related (PR) proteins, such as PR-1, β-1,3-glucanase and chitinase', 'Photosystem proteins', 'Storage proteins', 'Histones'], 0,
    'PR-2 is a β-1,3-glucanase and PR-3 is a chitinase.'],
  ['The volatile, mobile form of salicylic acid implicated in long-distance SAR signalling is:', ['Methyl salicylate', 'Jasmonic acid', 'Abscisic acid', 'Ethylene'], 0,
    'In distant leaves, SABP2 converts it back to salicylic acid.'],
  ['A commercial activator of SAR is:', ['Acibenzolar-S-methyl (BTH)', 'Mancozeb', 'Carbendazim', 'Glyphosate'], 0,
    'It mimics salicylic acid and has no direct antimicrobial action.'],
  ['Induced systemic resistance (ISR), unlike SAR, is triggered by:', ['Beneficial root bacteria (PGPR), through jasmonic acid and ethylene signalling', 'Salicylic acid and PR proteins', 'Viruses only', 'Chewing insects only'], 0,
    'ISR usually does not involve PR protein accumulation.'],
  ['In the 1970s, White showed that injecting tobacco with aspirin (acetylsalicylic acid):', ['Induced resistance to TMV', 'Killed the plants', 'Caused mosaic symptoms', 'Increased TMV spread'], 0,
    'This was the first clue to the role of salicylic acid in plant defence.'],
  ['Salicylic-acid-mediated defence works best against:', ['Biotrophic and hemibiotrophic pathogens', 'Necrotrophic pathogens only', 'Nematodes only', 'Abiotic stress only'], 0,
    'Jasmonic acid and ethylene defences are more effective against necrotrophs.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: 'IFoS-2018-B1-Q5a', q: [
  ['The inflorescence of Asteraceae is:', ['A capitulum (head) surrounded by an involucre of bracts', 'An umbel', 'A spike', 'A cyathium'], 0,
    'Many small florets are packed on a common receptacle.'],
  ['In Asteraceae, the calyx is often modified into:', ['A pappus of hairs or scales that helps wind dispersal', 'Spines only', 'Showy petals', 'Nectaries'], 0,
    'The pappus is well seen in *Taraxacum* (dandelion).'],
  ['The stamens of Asteraceae are:', ['Syngenesious — anthers united, filaments free — and epipetalous', 'Monadelphous', 'Diadelphous', 'Polyadelphous'], 0,
    'The anthers form a tube around the style.'],
  ['The ovary of Asteraceae is:', ['Bicarpellary, syncarpous, inferior and unilocular, with one basal ovule', 'Superior and multilocular', 'Apocarpous', 'Half-inferior with many ovules'], 0,
    'The single-seeded fruit reflects extreme reduction.'],
  ['The fruit of Asteraceae is a:', ['Cypsela', 'Capsule', 'Berry', 'Legume'], 0,
    'It is a one-seeded dry fruit from an inferior ovary.'],
  ['Pollen is presented in Asteraceae by:', ['A brush or piston mechanism, in which the style pushes pollen out of the anther tube', 'Explosive anthers', 'Pollinia', 'Wind-shaken pendulous anthers'], 0,
    'This is secondary pollen presentation.'],
  ['The capitulum of Asteraceae is a pseudanthium, which means that:', ['Many small florets act together as one "flower" for pollinators', 'It is a false fruit', 'It is a single flower', 'It is a modified leaf'], 0,
    'Ray florets attract insects while disc florets produce seed.'],
  ['The reserve carbohydrate characteristic of many Asteraceae is:', ['Inulin', 'Starch only', 'Glycogen', 'Floridean starch'], 0,
    'Dahlia tubers and chicory roots store inulin.'],
  ['In APG IV, Asteraceae belongs to the order:', ['Asterales, among the campanulid asterids', 'Rosales', 'Magnoliales', 'Poales'], 0,
    'Its advanced position is confirmed by molecular phylogeny.'],
  ['Asteraceae is regarded as advanced among dicots because it has:', ['Epigyny, sympetaly, a reduced one-seeded ovary and a head inflorescence with division of labour', 'Free petals and many carpels', 'Hypogynous flowers with many stamens', 'Spirally arranged floral parts'], 0,
    'Asteraceae and Orchidaceae are the two largest angiosperm families.']
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 1, pyq: 'IFoS-2018-B1-Q5b', q: [
  ['The Nemec phenomenon refers to:', ['Pollen grains developing into embryo-sac-like structures', 'Embryos arising from synergids', 'Double fertilisation', 'Endosperm haustoria'], 0,
    'It was described by the Czech botanist Bohumil Němec.'],
  ['Němec first reported embryo-sac-like pollen grains in:', ['*Hyacinthus orientalis*', '*Zea mays*', '*Arabidopsis thaliana*', '*Pinus roxburghii*'], 0,
    'Such grains are an abnormal (teratological) form of development.'],
  ['In such pollen grains the nucleus:', ['Divides three times, giving an 8-nucleate structure like a Polygonum-type embryo sac', 'Divides once, as in normal pollen', 'Undergoes meiosis', 'Never divides'], 0,
    'The male gametophyte follows the female developmental path.'],
  ['The significance of the Nemec phenomenon is that it shows:', ['The microspore can follow a megaspore-like path — micro- and megaspores are homologous', 'Double fertilisation', 'Apomixis', 'Polyembryony'], 0,
    'The fate of a spore is not fixed irreversibly.'],
  ['The Nemec phenomenon is best described as:', ['A rare teratological development of the male gametophyte', 'A normal step in all angiosperms', 'A type of fertilisation', 'A seed dispersal mechanism'], 0,
    'It is abnormal and seen only occasionally.'],
  ['At shedding, a normal angiosperm pollen grain is:', ['Two-celled or three-celled', 'Eight-nucleate', 'Seven-celled', 'Four-celled'], 0,
    'It has a vegetative cell and a generative cell (or two sperm cells).'],
  ['The typical Polygonum-type embryo sac is:', ['Monosporic, 8-nucleate and 7-celled', 'Bisporic, 4-nucleate', 'Tetrasporic, 16-nucleate', 'Monosporic, 4-nucleate'], 0,
    'It has an egg apparatus, a central cell and three antipodals.'],
  ['A related switch of microspore fate, producing haploid plants from pollen, is:', ['Androgenesis in anther or pollen culture', 'Gynogenesis', 'Parthenocarpy', 'Apospory'], 0,
    'Guha and Maheshwari first obtained it in *Datura* in 1964.'],
  ['Embryogenic development of microspores in culture is induced by:', ['Stress treatments such as cold, heat or starvation at the uninucleate stage', 'Pollination', 'High light', 'Mature three-celled pollen alone'], 0,
    'Stress diverts them from the normal gametophytic pathway.'],
  ['The Nemec phenomenon and androgenesis both illustrate:', ['The developmental plasticity of the microspore', 'A fixed cell fate', 'Male sterility', 'Double fertilisation'], 0,
    'This plasticity underlies doubled-haploid breeding.']
] },
{ p: 'B1', t: 'Plant Anatomy', w: 1, pyq: 'IFoS-2018-B1-Q5c', q: [
  ['Cortical vascular bundles are an anomaly because in a normal dicot stem vascular bundles are:', ['Confined to the stele, in a ring', 'Scattered in the cortex', 'Absent', 'Only in the pith'], 0,
    'In cortical bundles, extra strands run through the cortex.'],
  ['Cortical bundles with inverted orientation are found in the stem of:', ['*Nyctanthes* and *Calycanthus*', '*Helianthus*', '*Cucurbita*', '*Zea*'], 0,
    'Both have four-angled stems.'],
  ['An "inverted" cortical bundle has:', ['Xylem towards the outside and phloem towards the centre', 'Xylem and phloem on the same radius in normal order', 'Phloem on both sides', 'Xylem surrounding the phloem'], 0,
    'This is the reverse of a normal collateral bundle.'],
  ['The number of cortical bundles in the *Nyctanthes* stem is:', ['Four, one in each corner of the quadrangular stem', 'One', 'Many and scattered', 'None'], 0,
    'They lie in the cortex at the four ridges.'],
  ['Cortical bundles commonly represent:', ['Leaf traces that run a long way through the cortex before joining the stele', 'Medullary bundles', 'Root traces', 'Resin ducts'], 0,
    'Some are cauline bundles that belong to the stem itself.'],
  ['Cortical bundles develop from:', ['Procambial strands differentiating in the cortex, outside the main ring', 'The secondary vascular cambium', 'The pericycle', 'The cork cambium'], 0,
    'They are primary in origin.'],
  ['A cortical vascular system supplying the succulent cortex is well developed in:', ['Cacti such as *Opuntia*', 'Grasses', 'Conifers', 'Ferns'], 0,
    'The thick water-storing cortex needs its own supply.'],
  ['Medullary (pith) bundles, by contrast, are found in:', ['*Boerhaavia*', '*Nyctanthes*', '*Calycanthus*', '*Helianthus*'], 0,
    'They also occur in *Achyranthes* and *Piper*.'],
  ['Bicollateral vascular bundles, with phloem on both sides of the xylem, are characteristic of:', ['Cucurbitaceae', 'The cortical bundles of *Nyctanthes*', 'Monocot stems', 'Conifers'], 0,
    'The inner phloem faces the pith.'],
  ['A likely function of cortical bundles is to:', ['Supply the thick cortex and leaves and add support at the stem angles', 'Store starch only', 'Replace the stele', 'Form cork'], 0,
    'They supplement the normal vascular ring.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 2, pyq: 'IFoS-2018-B1-Q5d', q: [
  ['Botanical gardens contribute to plant conservation mainly through:', ['Ex situ conservation — living collections, seed banks and propagation', 'In situ conservation in natural habitats', 'Timber production', 'Recreation only'], 0,
    'They also support reintroduction into the wild.'],
  ['The global network of botanic gardens for conservation is:', ['Botanic Gardens Conservation International (BGCI)', 'IUCN', 'FAO', 'CITES'], 0,
    'BGCI was founded in 1987 and is based in Kew, UK.'],
  ['Under the Global Strategy for Plant Conservation (CBD), Target 8 aimed for at least 75% of threatened plants to be:', ['In ex situ collections, preferably in their country of origin', 'Traded internationally', 'Moved to new continents', 'Kept only as herbarium specimens'], 0,
    'This was the 2011–2020 target; botanic gardens were the main agents.'],
  ['The Acharya Jagadish Chandra Bose Indian Botanic Garden at Howrah was founded in 1787 by:', ['Robert Kyd', 'William Roxburgh', 'Joseph Hooker', 'N. Wallich'], 0,
    'It is known for its Great Banyan Tree.'],
  ['The Millennium Seed Bank, one of the largest ex situ plant collections, is run by:', ['Royal Botanic Gardens, Kew', 'The Svalbard vault only', 'NBPGR, New Delhi', 'The FAO'], 0,
    'It stores seeds of wild plant species.'],
  ['Rubber seedlings sent to Asia (Ceylon and Singapore) from 1876 were raised at:', ['Royal Botanic Gardens, Kew', 'The Indian Botanic Garden, Howrah', 'Peradeniya', 'Buitenzorg (Bogor)'], 0,
    'Botanical gardens have long served plant introduction.'],
  ['The Jeevani drug and a benefit-sharing agreement with the Kani tribe came from work at:', ['TBGRI (JNTBGRI), Palode, Kerala', 'NBRI, Lucknow', 'BSI, Kolkata', 'CIMAP, Lucknow'], 0,
    'The source plant is arogyapacha (*Trichopus zeylanicus*).'],
  ['Methods used by botanical gardens for conservation include:', ['Living collections, seed banking, tissue culture and cryopreservation', 'Only herbarium sheets', 'Only in situ reserves', 'Only field gene banks abroad'], 0,
    'Micropropagation helps multiply rare species.'],
  ['The Botanical Survey of India, established in 1890, is headquartered at:', ['Kolkata', 'Dehradun', 'Lucknow', 'Chennai'], 0,
    'It runs several botanic gardens and herbaria.'],
  ['Botanical gardens also help conservation by:', ['Public education and training in plant taxonomy', 'Promoting invasive species', 'Selling wild-collected plants', 'Replacing forests'], 0,
    'Awareness is a key conservation tool.']
] },
{ p: 'B1', t: 'Morphogenesis & Tissue Culture', w: 2, pyq: 'IFoS-2018-B1-Q5e', q: [
  ['Haploid plants from anther culture were first obtained by:', ['Guha and Maheshwari (1964) in *Datura innoxia*', 'Steward (1958) in carrot', 'Skoog and Miller (1957)', 'Murashige and Skoog (1962)'], 0,
    'This opened the way to doubled-haploid breeding.'],
  ['Doubling the chromosomes of a haploid with colchicine gives:', ['A doubled haploid — a completely homozygous line', 'A triploid', 'An aneuploid', 'A heterozygous hybrid'], 0,
    'All loci become homozygous in one step.'],
  ['The main breeding advantage of haploids is that they:', ['Give homozygous lines in one generation, saving years of selfing', 'Increase heterozygosity', 'Cause sterility', 'Increase heterosis'], 0,
    'Conventional inbreeding takes six to eight generations.'],
  ['The best stage of microspore for androgenesis is usually:', ['Uninucleate, just before or at the first pollen mitosis', 'Mature three-celled pollen', 'The pollen mother cell', 'The tetrad'], 0,
    'At this stage the microspore can still switch to embryogenic growth.'],
  ['Gynogenic haploids are obtained by culturing:', ['Unfertilised ovaries or ovules', 'Anthers', 'Root tips', 'Leaves'], 0,
    'This is used in onion and sugar beet.'],
  ['The "bulbosum method" for haploid barley works by:', ['Elimination of *Hordeum bulbosum* chromosomes after crossing with *H. vulgare*', 'Anther culture', 'Colchicine treatment', 'Irradiated pollen'], 0,
    'Wheat × maize crosses give wheat haploids in the same way.'],
  ['Haploids are useful in mutation studies because:', ['Recessive mutations show immediately, with no dominant allele to mask them', 'They are larger', 'They are more fertile', 'They are polyploid'], 0,
    'Selection for recessive traits is quick.'],
  ['A major problem in anther culture of cereals (rice, wheat, barley) is:', ['A high proportion of albino plantlets', 'Too many green plants', 'Polyploidy only', 'No response at all'], 0,
    'The albinos lack functional chloroplasts.'],
  ['Maize haploid-inducer lines such as Stock 6 produce:', ['Maternal haploids in vivo', 'Tetraploids', 'Hybrids only', 'Apomicts'], 0,
    'This is widely used in modern maize breeding.'],
  ['Haploid plants are usually:', ['Weak, small and sterile, because meiosis is irregular', 'Vigorous and fully fertile', 'Polyploid', 'Apomictic'], 0,
    'Chromosome doubling restores fertility.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 3, pyq: 'IFoS-2018-B1-Q6a', q: [
  ['Cronquist’s system was set out in:', ['*An Integrated System of Classification of Flowering Plants* (1981)', '*Genera Plantarum* (1862–83)', '*Species Plantarum* (1753)', '*Die Natürlichen Pflanzenfamilien*'], 0,
    'Bentham and Hooker wrote *Genera Plantarum*; Engler and Prantl the last.'],
  ['Cronquist divided the Magnoliophyta into two classes:', ['Magnoliopsida (dicots) and Liliopsida (monocots)', 'Gymnospermae and Angiospermae', 'Polypetalae and Gamopetalae', 'Eudicots and magnoliids'], 0,
    'Division Magnoliophyta contains all flowering plants.'],
  ['Cronquist’s system has how many subclasses?', ['Eleven — six in dicots and five in monocots', 'Seven', 'Twenty', 'Three'], 0,
    'Dicots: Magnoliidae, Hamamelidae, Caryophyllidae, Dilleniidae, Rosidae, Asteridae.'],
  ['Cronquist regarded which subclass as the most primitive dicots?', ['Magnoliidae', 'Asteridae', 'Rosidae', 'Hamamelidae'], 0,
    'He saw Magnoliales as the ancestral stock of angiosperms.'],
  ['The monocot subclasses in Cronquist’s system are:', ['Alismatidae, Arecidae, Commelinidae, Zingiberidae and Liliidae', 'Magnoliidae and Rosidae', 'Asteridae and Dilleniidae', 'Only Liliidae'], 0,
    'Liliidae includes the orchids.'],
  ['The Cronquist subclass marked by betalain pigments and free-central placentation is:', ['Caryophyllidae', 'Rosidae', 'Asteridae', 'Magnoliidae'], 0,
    'He used chemical characters along with morphology.'],
  ['Cronquist’s classification is based on:', ['Phylogenetic principles using morphology, anatomy, embryology and phytochemistry', 'A single artificial character', 'DNA sequences only', 'Plant habit only'], 0,
    'It predates the DNA-based APG system.'],
  ['A merit of Cronquist’s system is that it:', ['Was widely adopted in floras and herbaria and integrated many kinds of evidence', 'Used only molecular data', 'Classified only gymnosperms', 'Ignored chemistry'], 0,
    'It was the standard system for decades before APG.'],
  ['A demerit of Cronquist’s system, as shown by molecular data, is that:', ['Some groups, such as dicots and Hamamelidae, are not monophyletic', 'It has too few families', 'It uses no phylogenetic reasoning', 'It puts monocots first'], 0,
    'Wind-pollinated Hamamelidae was an artificial grouping.'],
  ['Cronquist thought angiosperms arose from:', ['Seed ferns (pteridosperms)', 'Gnetales', 'Bryophytes', 'Green algae directly'], 0,
    'The origin of angiosperms remains Darwin’s "abominable mystery".']
] },
{ p: 'B1', t: 'Morphogenesis & Tissue Culture', w: 3, pyq: 'IFoS-2018-B1-Q6b', q: [
  ['Totipotency is:', ['The ability of a single cell to divide and regenerate a whole plant', 'The ability of a cell to divide only once', 'Loss of the nucleus', 'Programmed cell death'], 0,
    'Every living plant cell carries the full genetic programme.'],
  ['The concept of totipotency was put forward in 1902 by:', ['Gottlieb Haberlandt', 'F. C. Steward', 'F. Skoog', 'T. Murashige'], 0,
    'He is called the father of plant tissue culture.'],
  ['Haberlandt could not get his cultured cells to divide mainly because:', ['Plant growth regulators were not yet known', 'He used animal cells', 'Contamination alone', 'He grew them in the dark'], 0,
    'Auxins and cytokinins were discovered decades later.'],
  ['Steward (1958) demonstrated totipotency by:', ['Growing whole carrot plants from phloem cells cultured in coconut milk', 'Regenerating tobacco from anthers', 'Fusing protoplasts', 'Grafting carrots'], 0,
    'The cells formed embryoids that grew into plants.'],
  ['Vasil and Hildebrandt (1965) regenerated a whole tobacco plant from:', ['A single isolated cell', 'An anther', 'A seed', 'A leaf cutting'], 0,
    'This was the most direct proof of totipotency.'],
  ['Coconut milk promotes cell division in culture because it contains:', ['Cytokinins such as zeatin', 'Only sugars', 'Ethylene', 'Abscisic acid'], 0,
    'It is the liquid endosperm of coconut.'],
  ['Skoog and Miller (1957) showed that a high auxin-to-cytokinin ratio favours:', ['Root formation', 'Shoot formation', 'Flowering', 'Senescence'], 0,
    'A low ratio favours shoots; an intermediate ratio gives callus.'],
  ['The formation of callus from a differentiated explant involves:', ['Dedifferentiation', 'Redifferentiation', 'Senescence', 'Meiosis'], 0,
    'Callus cells then redifferentiate into organs or embryos.'],
  ['Somatic embryos differ from adventitious shoots in being:', ['Bipolar, with both shoot and root poles', 'Unipolar', 'Always haploid', 'Formed from zygotes'], 0,
    'They develop like zygotic embryos.'],
  ['A practical use of totipotency is:', ['Micropropagation of elite clones and regeneration of transgenic plants', 'Chemical weed control', 'Soil testing', 'Seed dormancy'], 0,
    'Protoplast fusion and somaclonal variation also depend on it.']
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 2, pyq: 'IFoS-2018-B1-Q6c', q: [
  ['In helobial endosperm, the first division of the primary endosperm nucleus is:', ['Followed by a wall, giving a large micropylar and a small chalazal chamber', 'Free-nuclear throughout', 'Followed by vertical walls only', 'Absent'], 0,
    'Development then proceeds mostly free-nuclear, especially in the micropylar chamber.'],
  ['Helobial endosperm is named after:', ['The order Helobiae (Alismatales)', 'The genus *Helianthus*', 'Heliotropism', 'The sun'], 0,
    'It is most common in monocots.'],
  ['Helobial endosperm is intermediate between:', ['The nuclear and cellular types', 'The ruminate and smooth types', 'Diploid and triploid endosperm', 'Perisperm and endosperm'], 0,
    'It starts cellular and continues free-nuclear.'],
  ['In helobial endosperm, the first wall is laid down:', ['Transversely, separating micropylar and chalazal chambers', 'Longitudinally', 'Nowhere', 'In many planes at once'], 0,
    'The two chambers develop unequally.'],
  ['In helobial endosperm, the chalazal chamber usually:', ['Stays small, with few nuclear divisions', 'Forms most of the endosperm', 'Becomes the embryo', 'Is absent'], 0,
    'The micropylar chamber forms the bulk of the endosperm.'],
  ['Helobial endosperm is found in:', ['*Eremurus* and *Asphodelus*', 'Coconut', '*Petunia*', 'Maize'], 0,
    'Coconut has nuclear endosperm; *Petunia* has cellular.'],
  ['The most common type of endosperm in angiosperms is:', ['Nuclear', 'Cellular', 'Helobial', 'Ruminate'], 0,
    'The liquid endosperm of coconut is free-nuclear.'],
  ['In cellular endosperm:', ['Every nuclear division is followed by wall formation from the start', 'No walls ever form', 'Only the chalazal chamber is cellular', 'Walls form after hundreds of free nuclei'], 0,
    'Examples are *Petunia*, *Datura* and *Impatiens*.'],
  ['In the Polygonum-type embryo sac, the endosperm is:', ['Triploid (3n)', 'Diploid', 'Haploid', 'Pentaploid'], 0,
    'It forms from the fusion of two polar nuclei with one sperm.'],
  ['Ruminate endosperm, with an irregular infolded surface, is found in:', ['Areca nut and nutmeg', 'Wheat', 'Pea', 'Mustard'], 0,
    'The seed coat grows inward into the endosperm.']
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 3, pyq: 'IFoS-2018-B1-Q7a', q: [
  ['Polyembryony means:', ['More than one embryo in a single seed', 'Many seeds in a fruit', 'A fruit without seeds', 'Many ovules in an ovary'], 0,
    'Leeuwenhoek first noticed it in *Citrus* seeds in 1719.'],
  ['Adventive (nucellar) embryony, common in *Citrus* and mango, produces embryos from:', ['Nucellus cells, which are genetically identical to the mother plant', 'The zygote', 'The synergids', 'The antipodals'], 0,
    'Nucellar embryos are clones of the mother plant.'],
  ['Cleavage polyembryony, in which the proembryo splits into several embryos, is common in:', ['Gymnosperms such as *Pinus*', '*Citrus*', 'Mango', 'Wheat'], 0,
    'All the resulting embryos are genetically identical.'],
  ['A *Citrus* seed may contain:', ['Several embryos — one zygotic and the rest nucellar', 'Exactly one embryo', 'No embryo', 'Always two zygotic embryos'], 0,
    'The nucellar embryos often outgrow the zygotic one.'],
  ['Nucellar seedlings are valued in *Citrus* because they:', ['Give uniform, virus-free rootstocks true to the mother plant', 'Are always hybrids', 'Are sterile', 'Are haploid'], 0,
    'Most viruses are not transmitted through nucellar tissue.'],
  ['True polyembryony (Ernst) refers to embryos arising:', ['In the same embryo sac', 'In different embryo sacs of the same ovule', 'In different ovules', 'In different fruits'], 0,
    'Embryos from different embryo sacs of one ovule are called false polyembryony.'],
  ['Embryos that develop from unfertilised synergids are usually:', ['Haploid', 'Diploid', 'Triploid', 'Tetraploid'], 0,
    'They carry only the maternal set of chromosomes.'],
  ['A polyembryonic mango variety used as rootstock is:', ['Olour (or Kurukkan)', 'Alphonso', 'Dashehari', 'Langra'], 0,
    'Most north Indian commercial varieties are monoembryonic.'],
  ['Polyembryony can be induced artificially through:', ['Somatic embryogenesis in tissue culture, giving many embryos from one explant', 'Removing the stigma', 'Watering heavily', 'Storing seeds cold'], 0,
    'Growth regulators such as 2,4-D induce embryogenic callus.'],
  ['Nucellar embryony is a form of:', ['Apomixis (sporophytic apomixis)', 'Double fertilisation', 'Parthenocarpy', 'Meiotic recombination'], 0,
    'It produces seeds without fertilisation of the embryo.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 3, pyq: 'IFoS-2018-B1-Q7b', q: [
  ['Cinnamon is obtained from:', ['*Cinnamomum verum*, Lauraceae — dried inner bark', '*Cinnamomum camphora*, Lauraceae — leaves', '*Syzygium aromaticum*, Myrtaceae — buds', '*Myristica fragrans*, Myristicaceae — seed'], 0,
    'Cassia bark comes from *C. cassia*.'],
  ['Clove is obtained from:', ['*Syzygium aromaticum*, Myrtaceae — dried unopened flower buds', '*Piper nigrum*, Piperaceae — fruits', '*Elettaria cardamomum* — capsules', '*Crocus sativus* — stigmas'], 0,
    'Its main flavour compound is eugenol.'],
  ['Saffron is obtained from:', ['*Crocus sativus*, Iridaceae — dried stigmas and style tops', '*Carthamus tinctorius*, Asteraceae — florets', '*Curcuma longa*, Zingiberaceae — rhizome', '*Bixa orellana* — seeds'], 0,
    'Pampore (Kashmir) saffron has a GI tag.'],
  ['Nutmeg is obtained from:', ['*Myristica fragrans*, Myristicaceae — seed kernel', '*Cinnamomum verum* — bark', '*Syzygium aromaticum* — buds', '*Pimenta dioica* — berries'], 0,
    'Mace comes from the same fruit.'],
  ['Mace is:', ['The dried red aril around the nutmeg seed', 'Bark', 'A stigma', 'A flower bud'], 0,
    'Nutmeg and mace come from the same fruit.'],
  ['Lesser (small) cardamom is obtained from:', ['*Elettaria cardamomum*, Zingiberaceae — dried capsules and seeds', '*Amomum subulatum* — large cardamom', '*Piper longum* — spikes', '*Zingiber officinale* — rhizome'], 0,
    'It is called the "queen of spices"; black pepper is the "king".'],
  ['The main flavour compound of cinnamon bark oil is:', ['Cinnamaldehyde', 'Eugenol', 'Crocin', 'Piperine'], 0,
    'Cinnamon leaf oil is rich in eugenol.'],
  ['The compound that gives clove oil its antiseptic and pain-relieving properties is:', ['Eugenol', 'Menthol', 'Capsaicin', 'Curcumin'], 0,
    'It is used in dentistry.'],
  ['The colour, bitter taste and aroma of saffron come respectively from:', ['Crocin, picrocrocin and safranal', 'Curcumin, piperine and eugenol', 'Anthocyanin, tannin and menthol', 'Carotene, caffeine and vanillin'], 0,
    'About 150,000 flowers yield one kilogram of saffron.'],
  ['Myristicin, which can be toxic in large doses, is found in:', ['Nutmeg', 'Cardamom', 'Clove', 'Saffron'], 0,
    'It is a mild psychoactive compound.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: 'IFoS-2018-B1-Q7c', q: [
  ['An epicalyx is characteristic of:', ['Malvaceae (e.g., *Hibiscus*)', 'Solanaceae', 'Both families', 'Neither family'], 0,
    'It is a whorl of bracteoles below the calyx.'],
  ['The stamens of Malvaceae are:', ['Monadelphous, forming a staminal column, with one-celled kidney-shaped anthers', 'Five, free and epipetalous', 'Diadelphous', 'Syngenesious'], 0,
    'The one-celled (monothecous) anthers are a key feature.'],
  ['The stamens of Solanaceae are:', ['Five, epipetalous and alternating with the corolla lobes', 'Monadelphous in a column', 'Diadelphous', 'Numerous and free'], 0,
    'Anthers often open by apical pores (e.g., *Solanum*).'],
  ['The gynoecium of Solanaceae is:', ['Bicarpellary and syncarpous, set obliquely, with swollen axile placentas', 'Pentacarpellary', 'Monocarpellary', 'Inferior'], 0,
    'The oblique septum is diagnostic.'],
  ['The gynoecium of Malvaceae is:', ['Five- to many-carpellary, syncarpous and superior, with axile placentation', 'Bicarpellary and oblique', 'Monocarpellary', 'Inferior'], 0,
    'The style branches match the number of carpels.'],
  ['Twisted aestivation of petals is characteristic of:', ['Malvaceae', 'Solanaceae', 'Fabaceae', 'Asteraceae'], 0,
    'Solanaceae usually has valvate or plicate corollas.'],
  ['The floral formula ⊕ ⚥ K(5) C(5) A5 G(2), with epipetalous stamens, belongs to:', ['Solanaceae', 'Malvaceae', 'Brassicaceae', 'Fabaceae'], 0,
    'Malvaceae: ⊕ ⚥ Epi-K K(5) C5 A(∞) G(5–∞).'],
  ['The pollen of Malvaceae is typically:', ['Large and spiny (echinate)', 'Small and smooth', 'In pollinia', 'In tetrads'], 0,
    'Spiny pollen suits insect pollination.'],
  ['The fruit of Solanaceae is:', ['A berry (tomato, brinjal) or a capsule (*Datura*)', 'A legume', 'A cypsela', 'A siliqua'], 0,
    'Malvaceae usually has a capsule (cotton, okra) or a schizocarp.'],
  ['In *Physalis* (Solanaceae), the calyx:', ['Enlarges and encloses the fruit like a lantern (accrescent)', 'Falls early', 'Is absent', 'Becomes a pappus'], 0,
    'A persistent calyx is typical of Solanaceae.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 2, pyq: 'IFoS-2018-B1-Q8a', q: [
  ['Tea is obtained from:', ['*Camellia sinensis*, Theaceae — young leaves and buds', '*Coffea arabica*, Rubiaceae — seeds', '*Theobroma cacao* — seeds', '*Ilex paraguariensis* — leaves'], 0,
    'Fine plucking takes "two leaves and a bud".'],
  ['The correct order of steps in making black tea is:', ['Withering → rolling → fermentation (oxidation) → drying (firing)', 'Steaming → rolling → drying', 'Drying → rolling → withering', 'Fermentation → withering → steaming'], 0,
    'Rolling breaks the cells so enzymes can act.'],
  ['"Fermentation" in tea processing is really:', ['Enzymatic oxidation of catechins by polyphenol oxidase', 'Alcoholic fermentation by yeast', 'Lactic acid fermentation', 'Bacterial decay'], 0,
    'No microbes are involved.'],
  ['Green tea is made by:', ['Steaming or pan-firing soon after plucking to inactivate polyphenol oxidase', 'Full oxidation', 'Partial oxidation', 'Fermenting with yeast'], 0,
    'Its catechins therefore stay unoxidised.'],
  ['Oolong tea is:', ['Partly oxidised (semi-fermented)', 'Unoxidised', 'Fully oxidised', 'Made from roots'], 0,
    'Its character lies between green and black tea.'],
  ['White tea is made from:', ['Young buds and leaves that are only withered and dried', 'Old leaves that are fully oxidised', 'Roasted stems', 'Fermented flowers'], 0,
    'It is the least processed tea.'],
  ['The colour, briskness and body of black tea come mainly from:', ['Theaflavins and thearubigins', 'Chlorophyll', 'Caffeine alone', 'Starch'], 0,
    'Both form by oxidation of catechins.'],
  ['In tea manufacture, CTC stands for:', ['Crush, tear, curl', 'Cut, toast, cool', 'Clean, test, crush', 'Cure, tie, cut'], 0,
    'CTC gives granular tea that brews strong and fast.'],
  ['The amino acid unique to tea that gives it a savoury taste is:', ['L-theanine', 'Lysine', 'Tryptophan', 'Glycine'], 0,
    'Caffeine is the main stimulant.'],
  ['The first product in India to get a Geographical Indication (2004–05) was:', ['Darjeeling tea', 'Basmati rice', 'Mysore silk', 'Alphonso mango'], 0,
    'The Assam variety is *C. sinensis* var. *assamica*.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: 'IFoS-2018-B1-Q8b', q: [
  ['In Asclepiadaceae, the gynostegium is formed by:', ['The fusion of stamens with the stigma head', 'Fused petals', 'Fused sepals', 'Fused bracts'], 0,
    'It is the central column of the flower.'],
  ['A pollinium is:', ['The pollen of one anther cell held together as a waxy mass', 'A single pollen grain', 'A pollen tube', 'An empty anther'], 0,
    'The whole mass is carried by one insect visit.'],
  ['A pollinarium (translator) consists of:', ['Two pollinia from adjacent anthers joined by arms to a central corpusculum', 'One pollinium', 'Four free pollen grains', 'A stamen and a petal'], 0,
    'The corpusculum clips onto an insect’s leg.'],
  ['In *Calotropis*, the corpusculum lies:', ['At the angle of the stigma head, between two adjacent anthers', 'On a petal', 'At the base of the ovary', 'On a sepal'], 0,
    'Each corpusculum sits over a guide rail formed by the anther wings.'],
  ['Pollination in Asclepiadaceae happens when:', ['An insect’s leg slips into the guide rail, picks up a pollinarium and later inserts a pollinium into another flower’s stigmatic chamber', 'Wind carries loose pollen', 'Pollen falls onto the stigma of the same flower', 'Water carries pollen'], 0,
    'It is one of the most specialised insect pollination mechanisms.'],
  ['A corona in Asclepiadaceae is:', ['A ring of appendages arising from the corolla or the staminal column', 'A whorl of bracts', 'A fruit wall', 'A root outgrowth'], 0,
    'It is prominent in *Calotropis*.'],
  ['The gynoecium of Asclepiadaceae has:', ['Two free ovaries whose styles are united into a stigma head', 'One inferior ovary', 'Five fused ovaries', 'Many free carpels'], 0,
    'The ovaries are apocarpous, but the styles are joined at the top.'],
  ['The fruit of Asclepiadaceae is:', ['A pair of follicles with comose (hairy-tufted) seeds', 'A berry', 'A drupe', 'A cypsela'], 0,
    'The coma of silky hairs helps wind dispersal.'],
  ['Plants of Asclepiadaceae usually contain:', ['Milky latex', 'Resin ducts only', 'Betalains', 'Raphides only'], 0,
    'The latex is often toxic, e.g., in *Calotropis*.'],
  ['In APG classification, Asclepiadaceae is:', ['Merged into Apocynaceae as subfamily Asclepiadoideae', 'Merged into Solanaceae', 'Moved to the monocots', 'Kept as a separate order'], 0,
    'Molecular data showed it evolved within Apocynaceae.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 2, pyq: 'IFoS-2018-B1-Q8c', q: [
  ['The idea of "petroleum plants" (hydrocarbon crops) was championed by:', ['Melvin Calvin', 'Norman Borlaug', 'M. S. Swaminathan', 'G. Haberlandt'], 0,
    'He proposed growing latex-bearing plants for liquid fuel.'],
  ['Hydrocarbon-rich latex that Calvin studied for fuel came from:', ['*Euphorbia lathyris* and *E. tirucalli*', '*Oryza sativa*', '*Triticum aestivum*', '*Pinus roxburghii*'], 0,
    'Their latex is rich in terpenoid hydrocarbons.'],
  ['The "diesel tree", whose oleoresin can be used almost directly in diesel engines, is:', ['*Copaifera langsdorffii*', '*Tectona grandis*', '*Shorea robusta*', '*Dalbergia sissoo*'], 0,
    'It is a Brazilian legume tree.'],
  ['An Indian non-edible oilseed promoted for biodiesel is:', ['*Jatropha curcas*', '*Arachis hypogaea*', '*Sesamum indicum*', '*Cocos nucifera*'], 0,
    '*Pongamia pinnata* (karanja) is another.'],
  ['The alga known for producing large amounts of hydrocarbons (botryococcenes) is:', ['*Botryococcus braunii*', '*Chlorella vulgaris*', '*Ulva lactuca*', '*Spirulina platensis*'], 0,
    'Hydrocarbons can make up a large share of its dry weight.'],
  ['Latex hydrocarbons in *Euphorbia* are mainly:', ['Terpenoids (isoprenoids)', 'Proteins', 'Nucleic acids', 'Cellulose'], 0,
    'Terpenoids are built from isoprene (C₅) units.'],
  ['Compared with *Hevea* rubber, *Euphorbia lathyris* latex hydrocarbons are:', ['Of much lower molecular weight, so they can be cracked into fuel', 'Of higher molecular weight', 'Made of protein', 'Inorganic'], 0,
    '*Hevea* rubber is high-molecular-weight cis-1,4-polyisoprene.'],
  ['Guayule, an alternative source of natural rubber, is:', ['*Parthenium argentatum*', '*Ficus elastica*', '*Manihot glaziovii*', '*Hevea brasiliensis*'], 0,
    'It is a desert shrub of the family Asteraceae.'],
  ['Hydrocarbon plants appeal as energy crops because they:', ['Grow on marginal or arid land and provide renewable fuel', 'Need prime irrigated land', 'Release fossil carbon', 'Cannot be grown in India'], 0,
    'Their yields, however, remain low compared with oilseed crops.'],
  ['Most latex-bearing hydrocarbon plants belong to:', ['Euphorbiaceae, Apocynaceae (including Asclepiadaceae) and Moraceae', 'Poaceae', 'Fabaceae only', 'Pinaceae'], 0,
    '*Calotropis* has also been tested as a hydrocarbon source.']
] }
);
