/* PYQ-linked MCQs — CSE 2026 Agriculture Paper I, Section A (Q1–Q4). 10 MCQs per sub-question.
 * Block field `pyq` = id in mcq/pyq/registry.js. Row: [question, options, answerIndex, explanation]. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Environment, Organic & Natural Farming', w: 2, pyq: 'CSE-2026-A1-Q1a', q: [
  ['By volume, the largest source of pollution of India’s rivers is:', ['Untreated municipal sewage', 'Industrial effluents', 'Agricultural runoff', 'Thermal power plant discharge'], 0,
    'CPCB assessments show only a fraction of urban sewage is treated; the rest enters rivers and drains, raising BOD and faecal coliforms.'],
  ['CPCB primary water-quality criteria for outdoor bathing require BOD (5-day, 20 °C) not more than:', ['3 mg/L', '10 mg/L', '30 mg/L', '0.3 mg/L'], 0,
    'Class B (bathing): DO ≥ 5 mg/L, BOD ≤ 3 mg/L, pH 6.5–8.5, faecal coliform within prescribed MPN limits.'],
  ['The BIS acceptable limit for nitrate in drinking water is:', ['45 mg/L', '10 mg/L', '100 mg/L', '1.5 mg/L'], 0,
    'IS 10500. High nitrate (often from fertiliser and sewage) causes methaemoglobinaemia ("blue-baby syndrome") in infants.'],
  ['In most freshwater lakes, the nutrient that usually limits algal growth and drives eutrophication is:', ['Phosphorus', 'Potassium', 'Calcium', 'Sulphur'], 0,
    'P from fertiliser runoff, detergents and sewage triggers algal blooms; control measures target P loading.'],
  ['Arsenic in groundwater of the Ganga–Brahmaputra plains (West Bengal, Bihar) is mainly:', ['Geogenic — released from alluvial sediments under reducing conditions', 'From arsenical pesticides sprayed on crops', 'From tannery effluents', 'From coal-fired power plants'], 0,
    'Arsenic bound to iron oxides in young alluvium is released when they are reduced. BIS limit: 0.01 mg/L. Fluoride is another geogenic pollutant.'],
  ['India’s first comprehensive pollution-control law, which created the Central and State Pollution Control Boards, is the:', ['Water (Prevention and Control of Pollution) Act, 1974', 'Environment (Protection) Act, 1986', 'Air (Prevention and Control of Pollution) Act, 1981', 'National Green Tribunal Act, 2010'], 0,
    'The boards set up under the Water Act later also got powers under the Air Act (1981).'],
  ['A low-cost way to treat village wastewater using reeds such as *Typha* and *Phragmites* is a:', ['Constructed wetland', 'Activated sludge plant', 'Reverse osmosis unit', 'Chlorination tank'], 0,
    'Plant roots and attached microbes remove organic matter, nutrients and some metals; used under Swachh Bharat (Grameen) greywater management.'],
  ['Which farm practice most directly reduces nitrate leaching to groundwater?', ['Split application of nitrogen matched to crop demand', 'Applying all nitrogen as basal at sowing', 'Excess irrigation after fertiliser application', 'Leaving land fallow and bare after harvest'], 0,
    'Also: nitrification inhibitors, neem-coated urea, cover crops and soil-test-based doses.'],
  ['Biomagnification along food chains is most pronounced for:', ['Persistent, fat-soluble organochlorines such as DDT', 'Water-soluble nitrate', 'Readily biodegradable detergents', 'Dissolved carbon dioxide'], 0,
    'They resist degradation and accumulate in fatty tissue, so concentrations rise at higher trophic levels.'],
  ['"Zero Liquid Discharge" (ZLD), mandated for some highly polluting industries, means:', ['All wastewater is treated and recycled, and no liquid effluent is released', 'Effluent is diluted before release', 'Effluent is released only at night', 'Effluent is injected into deep wells'], 0,
    'CPCB has pushed ZLD for sectors such as textiles, tanneries and distilleries in river-basin clean-up plans.'],
] },
{ p: 'A1', t: 'Agro-climatic Zones & Cropping Systems', w: 3, pyq: 'CSE-2026-A1-Q1b', q: [
  ['A farming system differs from a cropping system in that it:', ['Integrates all farm enterprises (crops, livestock, fish, trees) and their interactions as one unit', 'Deals only with the sequence of crops on a field', 'Deals only with crop varieties', 'Excludes the farm household'], 0,
    'A cropping system is a sub-system of the farming system, which also covers livestock, trees, fish and the household’s resources.'],
  ['The key principle of an Integrated Farming System (IFS) is:', ['Recycling by-products of one component as inputs for another', 'Growing one crop on the whole farm', 'Maximising purchased inputs', 'Separating crop and livestock enterprises'], 0,
    'E.g., dung → biogas/compost → fields; crop residues → fodder; pond silt → manure.'],
  ['Farming Systems Research (FSR) is characterised by being:', ['On-farm, farmer-participatory and interdisciplinary, studying the whole farm', 'Confined to research stations', 'Focused on one commodity only', 'Driven only by input dealers'], 0,
    'It starts with a diagnosis of farmers’ constraints and tests solutions on their own farms.'],
  ['Kuttanad’s below-sea-level farming system, recognised by FAO as a GIAHS, is in:', ['Kerala', 'West Bengal', 'Odisha', 'Goa'], 0,
    'India’s GIAHS sites include Saffron heritage of Kashmir, Koraput traditional agriculture (Odisha) and Kuttanad (Kerala).'],
  ['The Zabo (Ruza) system — forest at the top, water-harvesting ponds, cattle yard and paddy below — is practised in:', ['Nagaland', 'Rajasthan', 'Kerala', 'Punjab'], 0,
    'An indigenous integrated system of Kikruma village (Phek district) combining forestry, water conservation, animal husbandry and rice–fish.'],
  ['"Podu" is the local name for shifting cultivation in:', ['The Eastern Ghats of Andhra Pradesh and Odisha', 'Assam', 'Kashmir', 'Punjab'], 0,
    'Called jhum in the North-East, bewar/dahiya in Madhya Pradesh and kumri in the Western Ghats.'],
  ['The Apatani rice–fish system is practised in the:', ['Ziro valley of Arunachal Pradesh', 'Kuttanad region of Kerala', 'Sundarbans', 'Kolleru lake area'], 0,
    'Terraced wet-rice fields with fish (and millet on bunds) managed with an intricate traditional irrigation network.'],
  ['"Baranaja", a traditional mixed-cropping system of the Garhwal Himalaya, literally means:', ['Twelve grains', 'Rain-fed grain', 'Hill terrace', 'Seed exchange'], 0,
    'About twelve crops (millets, pulses, amaranth) grown together — insurance against weather risk and a balanced diet.'],
  ['Khadin, an indigenous runoff-farming system, is associated with:', ['The Jaisalmer region of Rajasthan', 'The Nilgiri hills', 'The Kashmir valley', 'The Konkan coast'], 0,
    'An earthen bund across a slope traps runoff; after the water recedes, rabi crops grow on the moist, silt-enriched bed.'],
  ['In a rice–fish–duck system, ducks mainly contribute by:', ['Eating weeds and insects and adding manure', 'Fixing atmospheric nitrogen', 'Raising the water temperature', 'Pollinating the rice'], 0,
    'An example of complementarity among components, lowering pesticide and fertiliser needs.'],
] },
{ p: 'A1', t: 'Agroforestry & Social Forestry', w: 3, pyq: 'CSE-2026-A1-Q1c', q: [
  ['Which trait is LEAST desirable in a tree for agroforestry with field crops?', ['A dense, spreading crown with shallow lateral roots', 'A deep taproot', 'A light, open crown', 'Tolerance of pruning or lopping'], 0,
    'Good agroforestry trees are fast-growing, deep-rooted, light-crowned, often N-fixing, coppice well and are not strongly allelopathic.'],
  ['*Melia dubia* (Malabar neem) is promoted in agroforestry mainly because it:', ['Grows very fast and yields plywood/pulpwood in about 6–8 years', 'Fixes more nitrogen than any legume', 'Is a conifer tolerant of snow', 'Produces edible fruit'], 0,
    'Popular with farmers in Karnataka, Tamil Nadu and Andhra Pradesh for its short rotation and market for peeler logs.'],
  ['Poplar suits wheat-based agroforestry in north-west India because:', ['It is leafless in winter, so the rabi crop receives sunlight', 'It fixes atmospheric nitrogen', 'It needs no irrigation at all', 'It repels all insect pests'], 0,
    '*Populus deltoides* is planted in blocks or boundaries; rotation about 6–8 years for plywood and matchwood.'],
  ['Clonal eucalyptus farm forestry for the paper industry was pioneered in India by a company at:', ['Bhadrachalam', 'Kozhikode', 'Dehradun', 'Nagpur'], 0,
    'Clones selected for growth and pulp quality are multiplied by rooted cuttings and supplied to farmers under buy-back arrangements.'],
  ['*Grewia optiva* (bhimal) is valued in Himalayan agroforestry mainly for:', ['Nutritious lopped fodder in winter and bast fibre', 'Heavy structural timber', 'Rubber latex', 'Edible oil'], 0,
    'A traditional fodder tree on field bunds in Himachal and Uttarakhand; bark gives fibre for ropes.'],
  ['Mimosine, a toxic amino acid that limits its use as fodder, is found in:', ['*Leucaena leucocephala*', '*Gliricidia sepium*', '*Dalbergia sissoo*', '*Ailanthus excelsa*'], 0,
    'Ruminants in areas where rumen bacteria degrade mimosine tolerate it better; it is usually fed mixed with other fodder.'],
  ['*Dalbergia sissoo* (shisham) is best described as:', ['A nitrogen-fixing leguminous timber tree of the north Indian plains', 'An exotic conifer', 'A non-legume fodder shrub', 'A mangrove species'], 0,
    'Used on farm boundaries and canal banks; valued for furniture timber. Die-back/wilt has affected plantations.'],
  ['*Ailanthus excelsa* (maharukh) in arid-zone agroforestry provides:', ['Lopped fodder in the lean season and soft wood for matchsticks and packing', 'Durable railway-sleeper timber', 'Tannin-rich bark only', 'Edible nuts'], 0,
    'Fast-growing and drought-hardy, grown in Rajasthan and Gujarat.'],
  ['Babul (*Acacia nilotica*) is favoured for field bunds and degraded land because it:', ['Tolerates saline–alkali soils and gives fuel, fodder pods, gum and small timber', 'Needs high rainfall', 'Has no thorns', 'Is leafless all year'], 0,
    'Traditional "babul bans" (babul groves) in Madhya Pradesh and Gujarat combine trees with crops and grazing.'],
  ['*Gmelina arborea* (gamhar) is planted in agroforestry chiefly for:', ['Fast-growing light timber for furniture, packing cases and plywood', 'Latex', 'Edible fruit', 'Nitrogen fixation'], 0,
    'Coppices well and suits boundary planting in eastern and central India.'],
] },
{ p: 'A1', t: 'Weed Science', w: 2, pyq: 'CSE-2026-A1-Q1d', q: [
  ['Weed seeds with a pappus, such as *Sonchus* and *Tridax*, are dispersed mainly by:', ['Wind (anemochory)', 'Water (hydrochory)', 'Ants (myrmecochory)', 'Explosive capsules'], 0,
    'Pappus (modified calyx) acts like a parachute; typical of Asteraceae weeds.'],
  ['Irrigation water spreads weeds mainly by:', ['Carrying floating seeds and vegetative fragments from channels into fields', 'Killing the crop', 'Changing soil pH', 'Increasing soil temperature'], 0,
    'Keeping channel banks weed-free and using screens at inlets reduces this spread.'],
  ['*Prosopis juliflora* spreads rapidly through grazing lands mainly because:', ['Livestock eat its pods and pass viable seeds in dung', 'Its seeds are wind-dispersed', 'It spreads only by root suckers', 'Birds carry its seeds long distances'], 0,
    'Passage through the gut also scarifies the hard seed coat, improving germination.'],
  ['*Parthenium hysterophorus* is widely believed to have entered India with:', ['Imported food grain (PL-480 wheat) in the 1950s', 'Ornamental imports in the 1990s', 'Migratory birds', 'Ship ballast in the 1800s'], 0,
    'First noticed around Pune in 1955; now a major weed of wastelands and crops. Biocontrol: *Zygogramma bicolorata*.'],
  ['Purple nutsedge (*Cyperus rotundus*) spreads mainly through:', ['Underground tubers ("nuts") and rhizomes', 'Wind-borne seeds with pappus', 'Stolons above ground only', 'Bulbils on leaves'], 0,
    'Tubers survive tillage and remain dormant; it is among the world’s worst weeds.'],
  ['Crop mimicry, as in *Echinochloa crus-galli* in rice, helps the weed by:', ['Escaping hand weeding because it looks like the crop when young', 'Fixing nitrogen', 'Repelling insects', 'Maturing after the crop'], 0,
    '*Phalaris minor* similarly mimics wheat seedlings.'],
  ['*Oxalis corniculata* disperses its seeds by:', ['Explosive dehiscence of capsules (autochory)', 'Wind', 'Water', 'Animal fur'], 0,
    'Self-dispersal throws seeds a short distance; it also spreads by creeping stems.'],
  ['Well-decomposed compost helps reduce weed spread because:', ['High temperatures during composting kill most weed seeds', 'Compost contains herbicides', 'Weeds cannot grow in fertile soil', 'Compost raises soil pH above 9'], 0,
    'Fresh, undecomposed farmyard manure is a common carrier of viable weed seeds.'],
  ['Dispersal of seeds by ants is called:', ['Myrmecochory', 'Anemochory', 'Hydrochory', 'Ornithochory'], 0,
    'Such seeds often carry a fleshy elaiosome that attracts ants. Ornithochory = by birds (e.g., *Lantana*).'],
  ['Combine harvesters contribute to weed spread mainly by:', ['Carrying weed seeds from field to field and region to region', 'Burying weed seeds too deep to germinate', 'Killing weed seeds by heat', 'Spreading only aquatic weeds'], 0,
    'Cleaning machines before moving between fields is a preventive measure (e.g., against *Phalaris minor*).'],
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: 'CSE-2026-A1-Q1e', q: [
  ['The secondary nutrients are:', ['Calcium, magnesium and sulphur', 'Nitrogen, phosphorus and potassium', 'Iron, zinc and copper', 'Boron, molybdenum and chlorine'], 0,
    'Needed in moderate amounts — less than N, P, K but far more than micronutrients.'],
  ['Calcium is a structural component of the:', ['Middle lamella, as calcium pectate', 'Chlorophyll molecule', 'Cytochrome oxidase', 'Nitrogenase enzyme'], 0,
    'It also stabilises membranes and acts as a second messenger. Magnesium is the central atom of chlorophyll.'],
  ['Bitter pit of apple is associated with deficiency of:', ['Calcium', 'Nitrogen', 'Potassium', 'Iron'], 0,
    'Calcium is immobile in the phloem, so deficiency shows in fruits and young tissues (also blossom-end rot of tomato, tip burn of lettuce).'],
  ['Interveinal chlorosis beginning on OLDER leaves, with veins staying green, usually indicates deficiency of:', ['Magnesium', 'Iron', 'Calcium', 'Sulphur'], 0,
    'Mg is mobile and moves to young leaves. Iron deficiency causes similar interveinal chlorosis but on YOUNG leaves.'],
  ['Sulphur deficiency differs from nitrogen deficiency in that yellowing first appears on:', ['Younger leaves', 'Older leaves', 'Roots only', 'Flowers only'], 0,
    'S is relatively immobile in the plant; N is mobile, so N deficiency starts on older leaves.'],
  ['Sulphur is a constituent of the amino acids:', ['Cysteine, cystine and methionine', 'Lysine and tryptophan', 'Glycine and alanine', 'Leucine and valine'], 0,
    'Also of glucosinolates (pungency of mustard), allyl sulphides (onion, garlic), coenzyme A and ferredoxin.'],
  ['Crops with the highest sulphur requirement are:', ['Oilseeds such as mustard, and crucifers', 'Cereals such as rice', 'Sugarcane', 'Millets'], 0,
    'S raises oil content and yield of oilseeds; pulses also respond well.'],
  ['Gypsum (CaSO₄·2H₂O) supplies approximately:', ['23% calcium and 18% sulphur', '40% calcium and 5% sulphur', '10% calcium and 30% sulphur', '60% calcium and no sulphur'], 0,
    'Used as a Ca and S source (e.g., groundnut at pegging) and as an amendment for sodic soils.'],
  ['Dolomitic limestone is preferred for acid soils low in magnesium because it:', ['Supplies both calcium and magnesium while neutralising acidity', 'Supplies sulphur only', 'Acidifies the soil further', 'Supplies nitrogen'], 0,
    'Dolomite is CaMg(CO₃)₂. Epsom salt (MgSO₄·7H₂O) is a soluble Mg source for foliar or soil use.'],
  ['Groundnut needs calcium in the pegging zone because:', ['Developing pods absorb calcium directly from the soil; deficiency gives empty pods ("pops")', 'Calcium is needed only by roots', 'Calcium kills soil fungi completely', 'Calcium fixes nitrogen in pods'], 0,
    'Hence gypsum is applied at flowering/pegging, around 400–500 kg/ha in many recommendations.'],
] },
{ p: 'A1', t: 'Environment, Organic & Natural Farming', w: 2, pyq: 'CSE-2026-A1-Q2a', q: [
  ['Within Indian agriculture, the largest source of greenhouse-gas emissions is:', ['Enteric fermentation in livestock (methane)', 'Burning of crop residues', 'Manure management', 'Tractor fuel use'], 0,
    'India’s national inventories show enteric methane as the biggest share, followed by agricultural soils (N₂O) and rice cultivation (CH₄).'],
  ['Nitrous oxide from agricultural soils is produced mainly by:', ['Microbial nitrification and denitrification of applied nitrogen', 'Burning of crop residues only', 'Photosynthesis', 'Livestock respiration'], 0,
    'N₂O has a 100-year global warming potential of roughly 265–300 times CO₂ and also depletes ozone.'],
  ['Over a 100-year horizon, methane’s global warming potential is about ___ times that of CO₂.', ['28', '3', '300', '1,000'], 0,
    'IPCC AR5 gives 28 (AR6 about 27–30). Methane is short-lived, so cutting it gives quick climate benefits.'],
  ['Ration balancing in dairy animals helps mitigation mainly by:', ['Improving feed efficiency and cutting enteric methane per litre of milk', 'Increasing the number of animals', 'Replacing all roughage with water', 'Stopping rumination'], 0,
    'Other options: better-quality fodder, feed additives (e.g., tannins), and fewer, more productive animals.'],
  ['Dicyandiamide (DCD) reduces N₂O emissions by:', ['Inhibiting nitrification (the ammonia-oxidising step)', 'Fixing atmospheric nitrogen', 'Adding carbon to soil', 'Killing methanogens'], 0,
    'Other nitrification inhibitors: nitrapyrin, DMPP; neem coating works similarly.'],
  ['Which practice sequesters carbon in agricultural soils?', ['Zero tillage with residue retention', 'Burning crop residues', 'Intensive ploughing every season', 'Leaving soil bare in the off-season'], 0,
    'Conservation agriculture, cover crops, agroforestry and organic manures build soil organic carbon.'],
  ['Compared with puddled transplanted rice, direct-seeded rice (DSR) generally:', ['Emits less methane because fields are not kept continuously flooded', 'Emits more methane', 'Needs more water', 'Cannot be weeded'], 0,
    'DSR also saves labour and water, but needs good weed management.'],
  ['Anaerobic digestion of cattle dung in biogas plants helps mitigation because:', ['Methane is captured and burnt as fuel instead of escaping, and slurry replaces some fertiliser', 'It produces nitrous oxide for sale', 'It increases enteric fermentation', 'It stops rice cultivation'], 0,
    'Burning methane to CO₂ lowers warming impact; it also replaces fuelwood and LPG.'],
  ['Crop-residue burning in Punjab and Haryana mainly concerns:', ['Rice straw after the kharif harvest (October–November)', 'Wheat straw in December', 'Sugarcane trash in July', 'Cotton sticks in May'], 0,
    'Short window before wheat sowing; alternatives include Happy/Super Seeder, bio-decomposers and ex-situ use (biomass power, CBG).'],
  ['ICAR’s flagship project on climate-resilient agriculture, launched in 2011, is:', ['NICRA (National Innovations in Climate Resilient Agriculture)', 'NATP', 'NAIP', 'RKVY'], 0,
    'It runs technology demonstration villages and district contingency plans with CRIDA as the lead institute.'],
] },
{ p: 'A1', t: 'Agro-climatic Zones & Cropping Systems', w: 3, pyq: 'CSE-2026-A1-Q2b', q: [
  ['Precision farming is best defined as:', ['Managing within-field variability by applying the right input at the right place, time and amount', 'Using only organic inputs', 'Growing crops under greenhouses', 'Growing a single high-yielding variety'], 0,
    'Site-specific management based on measured variability in soil, crop and yield.'],
  ['Variable rate technology (VRT) means:', ['Applying inputs at rates that change across a field according to mapped needs', 'Changing crop varieties every year', 'Spraying at a fixed rate everywhere', 'Irrigating at night only'], 0,
    'Rates come from prescription maps (soil test, yield maps) or on-the-go sensors.'],
  ['India’s own regional satellite navigation system usable for precision agriculture is:', ['NavIC (IRNSS)', 'GLONASS', 'Galileo', 'BeiDou'], 0,
    'NavIC (Navigation with Indian Constellation) provides positioning over India and about 1,500 km around it.'],
  ['The main constraint to precision farming in India is:', ['Small, fragmented holdings (average about 1 ha) and limited capital', 'Lack of sunlight', 'Excess mechanisation', 'Too many large farms'], 0,
    'Other constraints: costly equipment, low digital literacy, weak data infrastructure. Custom hiring and FPOs can help.'],
  ['The leaf colour chart (LCC) helps farmers to:', ['Decide the need and timing of nitrogen top-dressing from leaf greenness', 'Identify insect pests', 'Measure soil pH', 'Estimate grain moisture'], 0,
    'A low-cost precision nutrient tool developed with IRRI for rice (and maize); saves N without yield loss.'],
  ['Hand-held GreenSeeker sensors estimate crop nitrogen need using:', ['NDVI from red and near-infrared reflectance', 'Soil electrical conductivity', 'Leaf temperature', 'Sap pH'], 0,
    'The sensor’s own light source makes readings independent of sunlight.'],
  ['NDVI (Normalised Difference Vegetation Index) is calculated as:', ['(NIR − Red) ÷ (NIR + Red)', '(Red − NIR) ÷ (Red + NIR)', 'NIR × Red', '(Blue − Green) ÷ (Blue + Green)'], 0,
    'Healthy vegetation reflects strongly in NIR and absorbs red, giving NDVI close to +1.'],
  ['The "Namo Drone Didi" scheme provides agricultural drones to:', ['Women self-help groups, to offer spraying and other services to farmers', 'Large corporate farms', 'Only state agriculture departments', 'Agricultural universities'], 0,
    'Approved in 2023 to give drones to women SHGs for rental services such as fertiliser and pesticide application.'],
  ['AgriStack under the Digital Agriculture Mission (2024) includes:', ['A farmers’ registry, geo-referenced village maps and a crop-sown registry', 'A national seed bank', 'A fertiliser subsidy portal only', 'A futures trading platform'], 0,
    'Digital public infrastructure for targeted services, crop surveys and credit/insurance.'],
  ['A key environmental benefit of precision nutrient management is:', ['Higher input-use efficiency with less nutrient loss to water and air', 'More fertiliser use per hectare', 'Complete elimination of pests', 'Higher soil salinity'], 0,
    'Matching supply to demand cuts nitrate leaching and N₂O emissions and raises profit.'],
] },
{ p: 'A1', t: 'Dryland Farming & Watershed Management', w: 2, pyq: 'CSE-2026-A1-Q2c', q: [
  ['A Geographic Information System (GIS) is best described as a system to:', ['Capture, store, analyse and display geo-referenced spatial data in layers', 'Forecast weather only', 'Measure soil pH in the field', 'Pump groundwater'], 0,
    'Layers (soils, slope, land use, drainage) can be combined and queried for planning.'],
  ['In GIS, raster data differ from vector data in that raster data:', ['Represent space as a grid of cells, like a satellite image', 'Use only points, lines and polygons', 'Cannot store elevation', 'Are always hand-drawn'], 0,
    'Vector data suit boundaries, roads and streams; raster suits continuous surfaces like elevation or NDVI.'],
  ['Identifying land suitable for a crop by combining soil, slope and rainfall layers is called:', ['Overlay analysis', 'Buffer analysis', 'Geocoding', 'Georeferencing'], 0,
    'Weighted overlay is widely used for land suitability and site selection for water-harvesting structures.'],
  ['Micro-watershed boundaries are delineated in GIS mainly from:', ['A digital elevation model (DEM) and the derived drainage network', 'Census population data', 'Road maps', 'Market locations'], 0,
    'Flow direction and flow accumulation derived from the DEM define ridge lines and outlets.'],
  ['In Strahler’s stream ordering, two second-order streams join to form a:', ['Third-order stream', 'Second-order stream', 'Fourth-order stream', 'First-order stream'], 0,
    'Order increases only when two streams of the same order meet. Stream order helps prioritise treatment.'],
  ['ISRO’s geoportal that provides land-use/land-cover maps and watershed data is:', ['Bhuvan', 'Mausam', 'Kisan Suvidha', 'e-NAM'], 0,
    'Used for planning and monitoring watershed projects (e.g., geotagging of structures under WDC-PMKSY).'],
  ['Marking a protective strip 30 m wide along streams in GIS is done by:', ['Buffer analysis', 'Overlay analysis', 'Interpolation', 'Classification'], 0,
    'Buffers define riparian zones, set-backs and zones of influence.'],
  ['Land-use/land-cover change in a watershed over time is found by:', ['Change detection between satellite images of different dates', 'A single soil-test report', 'Counting households', 'Measuring rainfall at one station'], 0,
    'Helps assess the impact of watershed treatment on vegetation and water bodies.'],
  ['In land capability classification (USDA), land suitable for regular cultivation falls in classes:', ['I to IV', 'V to VIII', 'I only', 'VI to VIII'], 0,
    'Classes V–VIII suit pasture, forestry or wildlife. GIS maps capability classes to plan land use in a micro-watershed.'],
  ['Slope maps derived from a DEM are important in watershed planning mainly to:', ['Choose conservation measures and suitable land uses for each slope class', 'Measure crop yield', 'Estimate fertiliser prices', 'Find groundwater salinity'], 0,
    'E.g., contour bunds on gentle slopes, terraces on steeper land, forestry on very steep slopes.'],
] },
{ p: 'A1', t: 'Agroforestry & Social Forestry', w: 3, pyq: 'CSE-2026-A1-Q3a', q: [
  ['Poplar plantations are usually raised from:', ['Stem cuttings (one-year-old nursery-rooted "entire transplants")', 'Seeds sown directly in the field', 'Air layers', 'Tissue-culture plantlets only'], 0,
    'Poplars and willows root easily from hardwood cuttings.'],
  ['Teak is most commonly planted out in the field as:', ['Stumps (root–shoot cuttings) from nursery seedlings', 'Grafted plants', 'Air layers', 'Leaf cuttings'], 0,
    'Stumps with a short shoot and a pruned taproot establish well and are easy to transport.'],
  ['The auxin most widely used to induce rooting in cuttings of forest trees is:', ['Indole-3-butyric acid (IBA)', 'Gibberellic acid', 'Abscisic acid', 'Ethephon'], 0,
    'IBA is stable and effective; NAA is also used, often in combination.'],
  ['Mist chambers are used for rooting clonal eucalyptus cuttings mainly because they:', ['Keep humidity high so leafy cuttings do not dry out before rooting', 'Supply nitrogen', 'Keep the cuttings in darkness', 'Sterilise the soil'], 0,
    'Mini-cuttings from clonal hedges root in mist/poly-houses with IBA treatment.'],
  ['Clonal seed orchards of forest trees are usually established by:', ['Grafting or budding scions of selected plus trees onto rootstocks', 'Sowing unselected seed', 'Coppicing old trees', 'Layering branches'], 0,
    'Grafts keep the plus tree’s genotype and flower early, supplying genetically improved seed.'],
  ['Micropropagation is especially valuable for bamboos because:', ['They flower gregariously at long intervals, so seed is rarely available', 'Their seeds are always sterile', 'They cannot be grown from rhizomes', 'They are annual plants'], 0,
    'Tissue culture (e.g., *Dendrocalamus strictus*, *Bambusa* spp.) gives large numbers of uniform planting stock.'],
  ['A major risk of large monoclonal plantations is:', ['A narrow genetic base, making the whole plantation vulnerable to one pest or disease', 'Too much genetic variation', 'Slow early growth', 'Inability to coppice'], 0,
    'Deploying several unrelated clones in mosaics reduces this risk.'],
  ['Cuttings that continue to grow like the branch they were taken from (e.g., plagiotropically) show:', ['Topophysis', 'Apical dominance', 'Photoperiodism', 'Vernalisation'], 0,
    'Hence orthotropic (upright) shoots are preferred for propagating timber trees.'],
  ['Clonal hedge orchards are kept regularly pruned mainly to:', ['Maintain juvenile shoots that root easily', 'Produce seed', 'Reduce water use', 'Encourage flowering'], 0,
    'Rooting ability declines with maturity; hedging keeps shoots physiologically juvenile.'],
  ['Compared with seed propagation, a limitation of vegetative propagation in forestry is that it:', ['Needs more skill and infrastructure, and cannot create new genetic combinations', 'Always gives weaker plants', 'Cannot capture the traits of superior trees', 'Is impossible in hardwoods'], 0,
    'Its advantage is capturing the full genetic gain of selected trees; breeding still needs sexual recombination.'],
] },
{ p: 'A1', t: 'Crop Production', w: 3, pyq: 'CSE-2026-A1-Q3b', q: [
  ['A sugarcane ratoon is:', ['The crop that regrows from the stubble after the plant crop is harvested', 'A newly planted crop from setts', 'A sugarcane intercrop', 'A seedling raised in a nursery'], 0,
    'Ratoons occupy roughly half the cane area in India and usually yield less than plant crops.'],
  ['Stubble shaving in a ratoon crop means:', ['Cutting the stubble at or just below ground level so buds sprout from below ground', 'Burning the trash', 'Removing all roots', 'Earthing up the plant'], 0,
    'Underground buds give vigorous, well-anchored tillers.'],
  ['"Off-barring" in ratoon management refers to:', ['Ploughing close to the stubble rows on both sides to cut old roots and loosen the soil', 'Removing the water shoots', 'Tying the canes together', 'Applying herbicide on the rows'], 0,
    'It aerates the soil and stimulates new root growth; fertiliser is then placed and covered.'],
  ['Gaps in a ratoon crop are best filled:', ['Early, within about a month, with pre-sprouted setts or polybag settlings', 'After six months', 'Only with seed', 'Never — gaps do not reduce yield'], 0,
    'Late gap-filling plants are suppressed by the established clumps.'],
  ['Compared with the plant crop, a sugarcane ratoon usually needs:', ['About 25% more nitrogen, applied early', 'No nitrogen at all', 'Half the nitrogen', 'Nitrogen only at harvest'], 0,
    'Ratoons have an older, shallower root system and immobilisation from trash, so early and higher N is advised.'],
  ['Ratoon stunting disease (RSD) of sugarcane is caused by:', ['The bacterium *Leifsonia xyli* subsp. *xyli*', 'A fungus, *Colletotrichum falcatum*', 'A virus spread by aphids', 'A root-knot nematode'], 0,
    'It shows no clear external symptoms except stunting, worse in ratoons. Controlled by hot-water (50 °C, 2 h) or moist hot-air treatment of seed cane.'],
  ['In subtropical India, ratoons started in winter (December–January) often sprout poorly because:', ['Low temperatures suppress bud sprouting', 'Days are too long', 'Soils are waterlogged', 'There is too much sunlight'], 0,
    'Harvesting the plant crop in February–March gives better ratoons in the north.'],
  ['Trash mulching in a ratoon crop is recommended because it:', ['Conserves moisture, suppresses weeds and adds organic matter', 'Kills the stubble', 'Raises soil salinity', 'Attracts termites to protect the crop'], 0,
    'Burning trash wastes nutrients and organic matter and pollutes the air.'],
  ['A key advantage of ratooning sugarcane is:', ['Saving the cost of seed cane and land preparation, with an earlier harvest', 'Always higher yield than the plant crop', 'Complete freedom from pests', 'Higher sugar recovery in every case'], 0,
    'Seed cane is a major cost; ratoons also mature earlier, helping mills start crushing sooner.'],
  ['Ratoon yield declines over successive ratoons mainly because of:', ['Gaps, pest and disease build-up and soil compaction', 'Improvement in soil structure', 'Better root growth', 'Lower weed pressure'], 0,
    'Hence usually only 1–2 ratoons are kept in the subtropics, more in the tropics with good management.'],
] },
{ p: 'A1', t: 'Weed Science', w: 2, pyq: 'CSE-2026-A1-Q3c', q: [
  ['Tembotrione, a post-emergence herbicide for maize, belongs to the group:', ['HPPD inhibitors (bleaching herbicides)', 'ALS inhibitors', 'Synthetic auxins', 'Dinitroanilines'], 0,
    'It inhibits carotenoid synthesis indirectly, causing bleaching of weeds; maize tolerates it by metabolising it (often with a safener).'],
  ['A post-emergence herbicide commonly recommended in greengram (moong) and soybean is:', ['Imazethapyr', 'Atrazine', '2,4-D ester', 'Paraquat as an overall spray'], 0,
    'An imidazolinone (ALS inhibitor) controlling many grasses and broadleaves in legumes. Pendimethalin is used pre-emergence.'],
  ['Quizalofop-ethyl, used in cotton and pulses, controls mainly:', ['Grassy weeds — it is an ACCase-inhibiting graminicide', 'Broadleaf weeds only', 'Sedges only', 'Parasitic weeds'], 0,
    'Aryloxyphenoxypropionates ("fops") are safe on broadleaf crops.'],
  ['Halosulfuron-methyl is used in sugarcane mainly to control:', ['Purple nutsedge (*Cyperus rotundus*)', 'Wild oat', '*Phalaris minor*', 'Water hyacinth'], 0,
    'A sulfonylurea effective against sedges; 2,4-D also suppresses sedges and broadleaves in cane.'],
  ['Pendimethalin kills weeds by:', ['Inhibiting microtubule assembly and cell division in germinating seedlings', 'Blocking photosystem II', 'Inhibiting EPSP synthase', 'Acting as a synthetic auxin'], 0,
    'A dinitroaniline applied pre-emergence to the soil surface; widely used in pulses, cotton, vegetables and wheat.'],
  ['To apply atrazine at 1.0 kg a.i./ha using atrazine 50 WP, the product needed per hectare is:', ['2.0 kg', '0.5 kg', '1.0 kg', '5.0 kg'], 0,
    'Product = dose of a.i. ÷ fraction of a.i. = 1.0 ÷ 0.50 = 2.0 kg per hectare.'],
  ['The nozzle best suited to uniform herbicide spraying is the:', ['Flat-fan nozzle', 'Hollow-cone nozzle', 'Solid-stream nozzle', 'Swirl nozzle for fogging'], 0,
    'Flat-fan nozzles give an even band with less drift; hollow cones suit insecticides and fungicides.'],
  ['Glyphosate can be used in a standing cotton crop in India only as:', ['A directed/shielded inter-row spray that avoids crop foliage', 'An overall spray on the crop', 'A seed treatment', 'A pre-emergence soil spray under the crop'], 0,
    'Glyphosate is non-selective; herbicide-tolerant cotton is not approved for cultivation in India.'],
  ['Pre-emergence herbicides work best when applied:', ['On moist soil within about 2–3 days after sowing, before weeds emerge', 'After the crop canopy closes', 'On dry, cloddy soil a month after sowing', 'Only after the first irrigation at 40 days'], 0,
    'They need moisture to form a treated layer in the germination zone.'],
  ['Metribuzin, used in sugarcane, potato and soybean, acts by:', ['Inhibiting photosystem II electron transport', 'Inhibiting ALS', 'Inhibiting ACCase', 'Inhibiting cellulose synthesis'], 0,
    'A triazinone. Atrazine (triazine) has the same mode of action.'],
] },
{ p: 'A1', t: 'Soil Genesis, Classification & Properties', w: 3, pyq: 'CSE-2026-A1-Q4a', q: [
  ['Soil consistency is best defined as:', ['The resistance of soil to deformation or rupture, governed by cohesion and adhesion at a given moisture', 'The arrangement of soil particles into aggregates', 'The proportion of sand, silt and clay', 'The colour of the soil'], 0,
    'It changes with water content; structure and texture are different properties.'],
  ['As soil moisture increases, consistency changes in the order:', ['Hard → friable → plastic → sticky', 'Sticky → plastic → friable → hard', 'Plastic → hard → sticky → friable', 'Friable → hard → sticky → plastic'], 0,
    'At very high moisture the soil behaves like a viscous liquid.'],
  ['The plasticity index of a soil is:', ['Liquid limit minus plastic limit', 'Plastic limit minus shrinkage limit', 'Liquid limit plus plastic limit', 'Field capacity minus wilting point'], 0,
    'It is the moisture range over which the soil stays plastic (Atterberg limits).'],
  ['The plastic limit is the lowest moisture content at which soil can be rolled into a thread of about ___ diameter without crumbling.', ['3 mm', '10 mm', '1 cm', '0.1 mm'], 0,
    'About 1/8 inch. Below this moisture the soil crumbles (friable/semisolid).'],
  ['In the Casagrande test, the liquid limit is the moisture at which the groove closes after:', ['25 blows', '5 blows', '100 blows', '50 blows'], 0,
    'The liquid limit marks the change from plastic to liquid (flowing) behaviour.'],
  ['The highest plasticity index is shown by soils rich in:', ['Montmorillonite', 'Kaolinite', 'Quartz sand', 'Gibbsite'], 0,
    'Expanding 2:1 clays have large surface area and hold much water — typical of Vertisols.'],
  ['Tillage is best done when the soil is in the ___ state.', ['Friable', 'Sticky', 'Hard', 'Liquid'], 0,
    'Friable soil crumbles easily into a good tilth; tilling wet (plastic/sticky) soil causes clods and compaction.'],
  ['The stickiness of wet soil to implements is due mainly to:', ['Adhesion', 'Cohesion only', 'Soil air', 'Soil temperature'], 0,
    'Adhesion is attraction of water films to other surfaces; cohesion is attraction between soil particles.'],
  ['A soil with a plasticity index close to zero is:', ['Sandy (non-plastic)', 'Heavy clay', 'Vertisol', 'Peat'], 0,
    'Sands lack the fine, platy clay particles needed for plastic behaviour.'],
  ['The shrinkage limit is the moisture content:', ['Below which further drying causes no further decrease in soil volume', 'At which soil starts to flow', 'At which soil becomes plastic', 'Equal to field capacity'], 0,
    'Shrink–swell behaviour is marked in Vertisols, causing deep cracks when dry.'],
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: 'CSE-2026-A1-Q4b', q: [
  ['Nitrification is the microbial conversion of:', ['Ammonium to nitrite and then nitrate', 'Nitrate to nitrogen gas', 'Organic nitrogen to ammonium', 'Nitrogen gas to ammonia'], 0,
    'Ammonification gives NH₄⁺; denitrification returns N₂/N₂O; fixation converts N₂ to NH₃.'],
  ['The first step of nitrification (NH₄⁺ → NO₂⁻) is carried out mainly by:', ['*Nitrosomonas* (and ammonia-oxidising archaea)', '*Nitrobacter*', '*Rhizobium*', '*Pseudomonas denitrificans*'], 0,
    '*Nitrobacter* (and *Nitrospira*) oxidise nitrite to nitrate.'],
  ['Nitrifying bacteria are:', ['Chemolithoautotrophs — they get energy by oxidising ammonium or nitrite and fix CO₂', 'Photoautotrophs', 'Obligate anaerobes', 'Parasites of plant roots'], 0,
    'Being aerobic, they need oxygen; nitrification stops in waterlogged soil.'],
  ['Nitrification of ammonium fertilisers tends to:', ['Acidify the soil because it releases H⁺ ions', 'Make the soil alkaline', 'Have no effect on pH', 'Increase soil salinity sharply'], 0,
    'Long-term ammonium sulphate or urea use lowers pH unless limed.'],
  ['Nitrification proceeds fastest at soil temperatures of about:', ['25–35 °C', '0–5 °C', '45–55 °C', 'Below freezing'], 0,
    'It slows sharply below about 5 °C and above about 40 °C.'],
  ['Nitrification is strongly inhibited when soil pH is:', ['Below about 5.5 (strongly acidic)', 'Between 6.5 and 8', 'Exactly 7', 'Around 7.5'], 0,
    'Liming acid soils speeds up nitrification.'],
  ['Nitrapyrin (N-Serve) slows nitrification by acting on:', ['*Nitrosomonas* (ammonia oxidation)', '*Nitrobacter*', 'Denitrifiers', 'Urease'], 0,
    'Keeping N as NH₄⁺ longer reduces leaching and denitrification losses.'],
  ['Nitrite may accumulate after heavy urea application in alkaline soils because:', ['Free ammonia inhibits *Nitrobacter* more than *Nitrosomonas*', 'Nitrite is fixed by clay', 'Nitrifiers stop working in alkaline soil', 'Urease is absent'], 0,
    'Nitrite is toxic to roots and can be lost as gases.'],
  ['Biological nitrification inhibition (BNI) — root release of compounds that suppress nitrifiers — is well documented in:', ['*Brachiaria humidicola*', 'Rice', 'Mustard', 'Tomato'], 0,
    'This tropical forage grass releases brachialactone; BNI traits are being bred into sorghum and wheat.'],
  ['Nitrate is lost from soil more easily than ammonium because:', ['Nitrate is an anion not held by negatively charged soil colloids, so it leaches', 'Nitrate is volatile', 'Ammonium is always taken up first', 'Nitrate is fixed in clay lattices'], 0,
    'Ammonium (a cation) is held on exchange sites; nitrate moves with drainage water.'],
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: 'CSE-2026-A1-Q4c', q: [
  ['A main reason available P rises when soils are flooded is:', ['Reduction of ferric phosphates to more soluble ferrous forms', 'Loss of phosphorus to the air', 'Increase in soil oxygen', 'Formation of calcium phosphate'], 0,
    'Under anaerobic conditions Fe³⁺ is reduced to Fe²⁺, releasing phosphate bound to iron (e.g., strengite).'],
  ['After submergence, the pH of both acid and alkaline soils tends to move towards:', ['Neutral (about 6.5–7)', 'pH 4', 'pH 10', 'It never changes'], 0,
    'Acid soils rise (reduction consumes H⁺); alkaline soils fall (CO₂ build-up). Near-neutral pH favours P availability.'],
  ['Occluded phosphorus becomes available on flooding because:', ['The iron-oxide coatings enclosing it are reduced and dissolved', 'Microbes fix it from the air', 'It is converted into nitrate', 'Rice roots secrete phosphorus'], 0,
    'Occluded P is locked inside Fe oxide coatings and is normally unavailable.'],
  ['In calcareous soils, flooding increases P availability partly because:', ['Accumulating CO₂ lowers pH and dissolves calcium phosphates', 'Calcium is washed away completely', 'Soil temperature rises above 50 °C', 'Oxygen increases'], 0,
    'Carbonic acid formed from CO₂ increases the solubility of Ca-P compounds.'],
  ['Diffusion of phosphate to roots in flooded soil increases mainly because:', ['Water-filled pores provide continuous pathways', 'Roots stop growing', 'Soil becomes compact', 'Phosphate becomes gaseous'], 0,
    'Phosphate moves to roots mostly by diffusion, which is faster in wetter soil.'],
  ['After flooding, the usual order in which microbes use electron acceptors is:', ['O₂ → NO₃⁻ → Mn⁴⁺ → Fe³⁺ → SO₄²⁻ → CO₂', 'SO₄²⁻ → O₂ → Fe³⁺ → NO₃⁻', 'Fe³⁺ → O₂ → CO₂ → NO₃⁻', 'CO₂ → SO₄²⁻ → Fe³⁺ → O₂'], 0,
    'Redox potential falls step by step; methane forms last, when CO₂ becomes the electron acceptor.'],
  ['Organic acids produced during anaerobic decomposition raise P availability by:', ['Chelating Fe, Al and Ca and competing for P-sorption sites', 'Oxidising iron', 'Raising soil oxygen', 'Precipitating phosphate'], 0,
    'Addition of green manure to flooded rice fields enhances this effect.'],
  ['In the rice–wheat system, the common recommendation for P fertiliser is to:', ['Apply it to the wheat crop, as rice benefits from residual P and flooding-induced release', 'Apply all P to rice only', 'Skip P for both crops permanently', 'Apply P only as a foliar spray to rice'], 0,
    'Flooded rice often responds less to P than upland wheat on the same soil.'],
  ['When a flooded rice field is drained, P availability can fall again because:', ['Ferrous iron re-oxidises to amorphous ferric oxides that strongly adsorb P', 'Phosphate turns into nitrate', 'Soil pH becomes neutral', 'Microbes release more P'], 0,
    'Freshly formed amorphous Fe oxides have very high P-sorption capacity.'],
  ['The thin surface layer of a flooded soil that stays oxidised is typically:', ['A few millimetres to about 1 cm thick', 'About 1 metre thick', 'The entire plough layer', 'Absent in all flooded soils'], 0,
    'Oxygen diffusing from floodwater keeps Fe³⁺ there, while the layer below is reduced.'],
] }
);
