/* PYQ-linked MCQs — CSE 2026 Agriculture Paper II, Section A (Q1–Q4). 10 MCQs per sub-question. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: 'CSE-2026-A2-Q1a', q: [
  ['Somatic hybridisation is the production of hybrids by:', ['Fusing protoplasts of two different plants', 'Crossing flowers of two varieties', 'Grafting two species', 'Inducing mutations with radiation'], 0,
    'It can bypass sexual incompatibility between distant species.'],
  ['Plant protoplasts are isolated by digesting cell walls with:', ['Cellulase and pectinase in an osmoticum such as mannitol', 'Trypsin in water', 'Amylase in saline', 'Lipase in alcohol'], 0,
    'The osmoticum keeps wall-less protoplasts from bursting.'],
  ['The most widely used chemical fusogen for protoplasts is:', ['Polyethylene glycol (PEG), often with high Ca²⁺ and high pH', 'Colchicine', 'Ethidium bromide', 'Sodium azide'], 0,
    'Electrofusion (an electric field followed by short pulses) is the main physical method.'],
  ['The first interspecific somatic hybrid plant (*Nicotiana glauca* + *N. langsdorffii*) was produced by:', ['Carlson and co-workers (1972)', 'Haberlandt (1902)', 'Murashige and Skoog (1962)', 'Guha and Maheshwari (1964)'], 0,
    'It confirmed that protoplast fusion could give fertile hybrid plants.'],
  ['A fused cell containing two different nuclei in a common cytoplasm is a:', ['Heterokaryon', 'Cybrid', 'Synkaryon', 'Haploid'], 0,
    'When the nuclei fuse, it becomes a synkaryon (true hybrid cell).'],
  ['A cybrid (cytoplasmic hybrid) carries:', ['The nucleus of one parent with cytoplasm from both or from the other parent', 'Nuclei of both parents fused', 'No nucleus', 'Only chloroplasts'], 0,
    'Cybrids are used to transfer cytoplasmic traits such as CMS (e.g., Ogura CMS in *Brassica*).'],
  ['Protoplast viability is commonly tested by staining with:', ['Fluorescein diacetate (FDA)', 'Iodine', 'Safranin', 'Gram stain'], 0,
    'Living cells with intact membranes and active esterases fluoresce green.'],
  ['A useful application of somatic hybridisation has been:', ['Transferring disease resistance from wild *Solanum* species into potato', 'Producing seedless watermelon', 'Making triticale', 'Fixing nitrogen in cereals'], 0,
    'E.g., *S. brevidens* resistance to potato leafroll virus.'],
  ['Hybrid cells after fusion can be selected by:', ['Complementation of mutants, fluorescent labelling or flow sorting', 'Colchicine treatment', 'Seed dormancy tests', 'Pollen viability tests'], 0,
    'E.g., two different albino or nitrate-reductase mutants complement each other only in the hybrid.'],
  ['A major limitation of somatic hybridisation is:', ['Genomic instability, chromosome elimination and sterility of regenerants', 'It always gives sterile seeds', 'It works only in animals', 'It needs no tissue culture'], 0,
    'Only some species regenerate plants readily from protoplasts.'],
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'CSE-2026-A2-Q1b', q: [
  ['A major cause of seed deterioration during storage is:', ['Lipid peroxidation by free radicals that damages membranes', 'Increase in enzyme activity', 'Accumulation of chlorophyll', 'Gain in dry weight'], 0,
    'Damaged membranes leak solutes, a key sign of ageing.'],
  ['Increased leakage of electrolytes from aged seeds is measured by the:', ['Electrical conductivity test', 'Tetrazolium test only', 'Grow-out test', 'Cold test'], 0,
    'Higher conductivity of soak water means lower vigour (a standard test in peas).'],
  ['Aged seeds show lower dehydrogenase activity, which appears as:', ['Weaker red staining in the tetrazolium test', 'Stronger red staining', 'Blue colour with iodine', 'No change'], 0,
    'Dehydrogenases reduce tetrazolium to red formazan in living tissue.'],
  ['Oilseeds such as groundnut lose viability faster in storage mainly because:', ['Their high oil content is prone to oxidation and free fatty acid build-up', 'They have hard seed coats', 'They contain no enzymes', 'They are too dry'], 0,
    'Keep oilseeds at lower moisture (about 8–9%) than cereals.'],
  ['The accelerated ageing test for seed vigour exposes seeds to:', ['High temperature (about 40–45 °C) and near-100% relative humidity for a few days', 'Freezing for a week', 'Darkness at room temperature', 'Dry heat at 100 °C'], 0,
    'High-vigour lots germinate well after this stress.'],
  ['During prolonged storage, non-enzymatic browning between reducing sugars and proteins (the Maillard reaction):', ['Contributes to loss of seed quality', 'Increases germination', 'Repairs DNA', 'Has no role in seeds'], 0,
    'It occurs even at low moisture over long periods.'],
  ['In aged seeds, DNA and RNA:', ['Accumulate damage, and protein synthesis during germination declines', 'Double in amount', 'Are unaffected', 'Convert to lipids'], 0,
    'Repair capacity also declines, so germination slows or fails.'],
  ['Storage fungi such as *Aspergillus* and *Penicillium* damage stored seed mainly when:', ['Seed moisture and relative humidity are high', 'Seeds are very dry', 'Temperature is below 0 °C', 'Seeds are hermetically sealed and dry'], 0,
    'They raise free fatty acids, cause heating and can produce mycotoxins.'],
  ['Late embryogenesis abundant (LEA) proteins help seed longevity by:', ['Protecting cell structures during desiccation', 'Speeding up respiration', 'Breaking seed dormancy', 'Digesting food reserves'], 0,
    'Along with sugars (e.g., raffinose-family oligosaccharides) they help form a protective glassy state.'],
  ['Deterioration is slowest when seeds are stored:', ['Dry and cool, e.g., in moisture-proof containers at low temperature', 'Moist and warm', 'In open sacks in humid rooms', 'In direct sunlight'], 0,
    'This follows Harrington’s rules on moisture and temperature.'],
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'CSE-2026-A2-Q1c', q: [
  ['Most phosphorus and potassium reach plant roots by:', ['Diffusion', 'Mass flow', 'Root interception only', 'Leaf uptake'], 0,
    'Nitrate, calcium and magnesium move mostly by mass flow with transpiration water.'],
  ['Iron and manganese availability to plants is highest in:', ['Acid soils', 'Calcareous alkaline soils', 'Sodic soils', 'Soils at pH 9'], 0,
    'At high pH these metals form insoluble oxides/hydroxides; molybdenum behaves the opposite way.'],
  ['Active ion uptake by roots declines in waterlogged soil mainly because:', ['Lack of oxygen reduces root respiration and ATP supply', 'Too much light reaches roots', 'Soil temperature rises', 'Ions become gaseous'], 0,
    'Ion transport against gradients needs metabolic energy.'],
  ['Purpling of young maize leaves in cold soils early in the season is often due to:', ['Reduced phosphorus uptake at low soil temperature', 'Excess nitrogen', 'Boron toxicity', 'Too much iron'], 0,
    'Low temperature slows diffusion and root growth.'],
  ['Heavy phosphate application inducing zinc deficiency is an example of:', ['Nutrient interaction (antagonism)', 'Synergism', 'Mass flow', 'Luxury consumption'], 0,
    'Other antagonisms: K vs Mg, K vs Ca, Ca vs B.'],
  ['Arbuscular mycorrhizal fungi improve nutrient absorption mainly of:', ['Phosphorus (and zinc) by extending the absorbing surface beyond the depletion zone', 'Nitrogen gas', 'Carbon dioxide', 'Sodium'], 0,
    'Hyphae explore soil beyond the root-hair zone.'],
  ['Active uptake of ions by root cells is driven mainly by:', ['Plasma-membrane H⁺-ATPase creating a proton gradient', 'Transpiration pull alone', 'Gravity', 'Photosynthesis in roots'], 0,
    'The proton gradient powers carriers and channels for nutrient ions.'],
  ['Plants with high root cation-exchange capacity (many dicots) tend to absorb relatively more:', ['Divalent cations such as Ca²⁺', 'Monovalent cations such as K⁺', 'Anions such as nitrate', 'Silicon'], 0,
    'Monocots with lower root CEC take up relatively more K⁺.'],
  ['A higher transpiration rate increases nutrient absorption mainly through:', ['Mass flow of dissolved nutrients to roots', 'Diffusion only', 'Root interception only', 'Leaf absorption'], 0,
    'Mass flow carries nutrients present in the soil solution along with water.'],
  ['Dry soil reduces nutrient uptake mainly because:', ['Diffusion and mass flow slow down as water films thin', 'Nutrients become gases', 'Root respiration increases', 'Soil pH rises to 10'], 0,
    'Water is the medium for both movement processes.'],
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: 'CSE-2026-A2-Q1d', q: [
  ['A clone is:', ['A group of plants derived from one plant by asexual (vegetative) reproduction', 'A group of plants from one self-pollinated seed', 'A hybrid between two inbreds', 'A population of mutants'], 0,
    'All members have the same genotype, apart from rare somatic mutations.'],
  ['Clones of vegetatively propagated, naturally cross-pollinated crops such as potato are:', ['Highly heterozygous but genetically uniform', 'Homozygous and uniform', 'Homozygous and variable', 'Heterozygous and variable within the clone'], 0,
    'Heterozygosity is fixed because there is no sexual reproduction.'],
  ['Selection within a clone is generally ineffective because:', ['All plants have the same genotype, so variation is environmental', 'Clones are always sterile', 'Clones mutate every generation', 'Clones cannot be propagated'], 0,
    'The exception is a bud sport (somatic mutation).'],
  ['In clonal crops, hybrid vigour is:', ['Fixed and maintained through vegetative propagation', 'Lost in the next generation', 'Absent', 'Present only in seeds'], 0,
    'This is why clonal hybrids of sugarcane or banana keep their performance.'],
  ['A new clone arising from a somatic mutation in a bud is called a:', ['Bud sport', 'Somatic hybrid', 'Cybrid', 'Apomict'], 0,
    'Many apple, grape and citrus cultivars (e.g., colour sports) are bud sports.'],
  ['A problem specific to clonal propagation is:', ['Build-up of viruses over cycles, causing degeneration', 'Segregation of traits', 'Loss of heterozygosity', 'Seed dormancy'], 0,
    'Virus-free stock is produced by meristem culture and certification.'],
  ['Clonal selection is the main breeding method in:', ['Potato, sugarcane, banana and apple', 'Wheat and rice', 'Maize hybrids', 'Mustard'], 0,
    'Superior clones selected from mixed populations or seedling progenies are multiplied vegetatively.'],
  ['Sugarcane "Co" varieties grown by farmers are:', ['Clones multiplied from setts', 'Pure lines from seed', 'F₁ seed hybrids', 'Synthetic varieties'], 0,
    'New variability comes from crosses (at the Sugarcane Breeding Institute, Coimbatore); the chosen seedling becomes a clone.'],
  ['Clonal fidelity of tissue-culture plants is checked using:', ['Molecular markers such as SSR or ISSR', 'Seed germination tests', 'Chi-square tests only', 'Leaf colour charts'], 0,
    'This detects somaclonal variants before large-scale release.'],
  ['Genetic variation for breeding clonal crops is created mainly by:', ['Sexual hybridisation, mutation or somaclonal variation, followed by clonal selection', 'Selfing clones repeatedly', 'Grafting only', 'Keeping clones in cold storage'], 0,
    'Once a superior genotype is found, it is fixed at once by vegetative propagation.'],
] },
{ p: 'A2', t: 'Heterosis, Hybrids & Mutation Breeding', w: 2, pyq: 'CSE-2026-A2-Q1e', q: [
  ['Physical mutagens include:', ['X-rays, gamma rays, neutrons and ultraviolet light', 'EMS and sodium azide', 'Colchicine', 'Acridine dyes'], 0,
    'Ionising radiations cause breaks and point mutations; UV is non-ionising and mainly forms pyrimidine dimers.'],
  ['Ethyl methanesulphonate (EMS) is:', ['An alkylating agent that mainly causes G:C → A:T transitions', 'A base analogue of thymine', 'An intercalating dye', 'An ionising radiation'], 0,
    'EMS is the most widely used chemical mutagen in plants (and for TILLING populations).'],
  ['The usual source of gamma rays for mutation breeding is:', ['Cobalt-60', 'Uranium-235', 'Carbon-14', 'Iodine-131'], 0,
    'Caesium-137 is also used. Seeds are irradiated in gamma chambers.'],
  ['Ultraviolet light causes mutations mainly by forming:', ['Pyrimidine (thymine) dimers', 'Double-strand breaks only', 'Base analogues', 'Polyploidy'], 0,
    'UV has low penetration, so it suits pollen and micro-organisms more than seeds.'],
  ['5-Bromouracil causes mutations because it:', ['Mimics thymine and pairs wrongly through tautomeric shifts', 'Alkylates guanine', 'Intercalates between bases', 'Breaks chromosomes'], 0,
    'It causes transitions. 2-Aminopurine is another base analogue.'],
  ['Nitrous acid causes mutations by:', ['Deaminating bases (e.g., cytosine to uracil)', 'Forming thymine dimers', 'Inserting between bases', 'Breaking the sugar–phosphate backbone only'], 0,
    'Deamination changes base pairing, giving transitions.'],
  ['Sodium azide is a particularly effective chemical mutagen in:', ['Barley', 'Humans', 'Bacteriophage only', 'Animals only'], 0,
    'It acts through an organic metabolite (azidoalanine) formed in the plant cell.'],
  ['In mutation breeding, the dose of mutagen is often chosen near the:', ['LD₅₀ or GR₅₀ (dose killing or halving growth of 50% of seedlings)', 'LD₁₀₀', 'Zero dose', 'Dose that causes no effect'], 0,
    'Too high a dose causes excessive damage; too low gives few mutations.'],
  ['Induced mutation in plants by X-rays was first demonstrated by:', ['L.J. Stadler (1928) in barley and maize', 'H.J. Muller (1927) in pea', 'Hugo de Vries (1901)', 'Gregor Mendel (1866)'], 0,
    'Muller showed X-ray mutagenesis in *Drosophila* in 1927.'],
  ['The "TG" series of groundnut varieties from BARC, Trombay, were developed by:', ['Radiation-induced mutation', 'Somatic hybridisation', 'Genetic engineering', 'Interspecific grafting'], 0,
    'BARC has released many mutant varieties of groundnut, pulses and other crops.'],
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, pyq: 'CSE-2026-A2-Q2a', q: [
  ['Vertical (race-specific) resistance is usually:', ['Controlled by one or a few major genes and effective against some races only', 'Polygenic and effective against all races', 'Due only to environment', 'Found only in wild species'], 0,
    'Van der Plank (1963). Horizontal resistance is polygenic and race-non-specific, and usually more durable.'],
  ['The gene-for-gene hypothesis was proposed by H.H. Flor based on work with:', ['Flax and flax rust', 'Wheat and stem rust', 'Potato and late blight', 'Rice and blast'], 0,
    'For each resistance gene in the host there is a matching avirulence gene in the pathogen.'],
  ['Pisatin is a phytoalexin produced by:', ['Pea', 'Bean', 'Potato', 'Soybean'], 0,
    'Phaseollin: bean; rishitin: potato; glyceollin: soybean. Phytoalexins are induced antimicrobial compounds.'],
  ['The hypersensitive response (HR) protects plants mainly by:', ['Rapid death of cells at the infection site, starving biotrophic pathogens', 'Increasing growth rate', 'Closing all stomata permanently', 'Producing more pollen'], 0,
    'Often triggered when a resistance protein recognises a pathogen effector (ETI).'],
  ['Structural defences against pathogens include:', ['Thick cuticle, wax, lignified walls, callose papillae and tyloses', 'Phytoalexins only', 'PR proteins only', 'Higher nitrogen content'], 0,
    'They may be pre-formed or induced after attack.'],
  ['Pathogenesis-related (PR) proteins such as chitinases and β-1,3-glucanases act by:', ['Degrading fungal cell walls', 'Increasing photosynthesis', 'Blocking stomata', 'Transporting sugars'], 0,
    'They accumulate during systemic acquired resistance.'],
  ['The wheat–rye 1B/1R translocation carrying rust resistance genes came from:', ['Rye (*Secale cereale*)', 'Barley', '*Aegilops tauschii*', 'Oats'], 0,
    'It carried Sr31, Lr26, Yr9 and Pm8.'],
  ['Stem rust race Ug99 (Uganda, 1999) was alarming because it:', ['Overcame the widely used resistance gene Sr31', 'Infected only barley', 'Was a virus', 'Could not spread by wind'], 0,
    'This led to a global effort to breed new, durable stem-rust resistance.'],
  ['Disease tolerance means that the plant:', ['Is infected but suffers little yield loss', 'Is never infected', 'Escapes infection by early maturity', 'Kills the pathogen immediately'], 0,
    'Disease escape: avoiding infection in time or space; resistance: limiting the pathogen.'],
  ['Gene pyramiding for disease resistance aims to:', ['Combine several resistance genes in one variety for more durable protection', 'Remove resistance genes', 'Increase disease severity', 'Make the variety susceptible to test pathogens'], 0,
    'Marker-assisted selection makes pyramiding practical.'],
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: 'CSE-2026-A2-Q2b', q: [
  ['The inner mitochondrial membrane is folded into:', ['Cristae', 'Thylakoids', 'Grana', 'Cisternae'], 0,
    'Folding increases the surface area for the electron transport chain and ATP synthase.'],
  ['Enzymes of the Krebs cycle are located mainly in the mitochondrial:', ['Matrix', 'Outer membrane', 'Intermembrane space', 'Cytosol'], 0,
    'Succinate dehydrogenase is the exception — it is bound to the inner membrane (complex II).'],
  ['A phospholipid characteristic of the inner mitochondrial membrane is:', ['Cardiolipin', 'Lecithin only', 'Cholesterol', 'Sphingomyelin'], 0,
    'It helps keep the membrane impermeable to protons and supports respiratory complexes.'],
  ['The stalked F₁ particles (oxysomes) on the inner mitochondrial membrane are the site of:', ['ATP synthesis', 'DNA replication', 'Protein synthesis', 'Fatty acid storage'], 0,
    'They are the F₁ heads of ATP synthase; F₀ forms the proton channel.'],
  ['The outer mitochondrial membrane is relatively permeable to small molecules because it contains:', ['Porins', 'Cardiolipin', 'Cytochromes', 'ATP synthase'], 0,
    'The inner membrane is highly selective.'],
  ['Cytoplasmic male sterility in crops is usually linked to:', ['Rearranged mitochondrial genes', 'Chloroplast genes', 'Nuclear genes only', 'Ribosomal RNA genes'], 0,
    'Novel mitochondrial open reading frames disrupt pollen development; nuclear restorer genes suppress them.'],
  ['Under the modern P/O values, oxidation of one NADH through the electron transport chain yields about:', ['2.5 ATP', '1.5 ATP', '3.5 ATP', '6 ATP'], 0,
    'FADH₂ yields about 1.5 ATP (older textbooks give 3 and 2).'],
  ['Mitochondria are believed to have evolved from:', ['An α-proteobacterium engulfed by an ancestral host cell', 'A cyanobacterium', 'A virus', 'The nucleus'], 0,
    'Evidence: own circular DNA, 70S ribosomes, double membrane, division by fission.'],
  ['Mitochondrial DNA in plants is typically:', ['Inherited maternally in most crops', 'Inherited only from the male parent', 'Identical to nuclear DNA', 'Absent'], 0,
    'Hence CMS is transmitted through the female parent.'],
  ['Besides ATP production, mitochondria take part in:', ['Photorespiration (glycine to serine), programmed cell death and amino-acid metabolism', 'Photosynthetic light reactions', 'Cell-wall synthesis', 'Pollen tube growth only'], 0,
    'Glycine decarboxylase in leaf mitochondria releases CO₂ during photorespiration.'],
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: 'CSE-2026-A2-Q2c', q: [
  ['The most abundant type of DNA marker in plant genomes is:', ['Single nucleotide polymorphisms (SNPs)', 'RFLPs', 'Isozymes', 'Morphological markers'], 0,
    'SNPs suit high-throughput genotyping chips and sequencing.'],
  ['Microsatellites (SSRs) are popular markers because they are:', ['Co-dominant, multi-allelic and PCR-based', 'Dominant and random', 'Based on protein bands', 'Visible to the naked eye'], 0,
    'They are highly reproducible and informative for mapping and variety identification.'],
  ['RAPD markers are limited mainly because they are:', ['Dominant and poorly reproducible', 'Co-dominant', 'Too expensive', 'Protein-based'], 0,
    'They use short random primers; results vary between laboratories.'],
  ['The first DNA-based marker system used for genome mapping was:', ['RFLP (restriction fragment length polymorphism)', 'SNP', 'SSR', 'KASP'], 0,
    'RFLPs need hybridisation (Southern blotting) and more DNA.'],
  ['In marker-assisted backcrossing, "background selection" aims to:', ['Speed recovery of the recurrent parent’s genome', 'Find the target gene only', 'Increase linkage drag', 'Create new mutations'], 0,
    'Foreground selection tracks the target gene; recombinant selection reduces linkage drag.'],
  ['A QTL (quantitative trait locus) is:', ['A chromosome region associated with variation in a quantitative trait', 'A gene for flower colour', 'A type of mutation', 'A single nucleotide'], 0,
    'QTL mapping links markers to traits such as yield or drought tolerance.'],
  ['A "functional" (perfect) marker is one that:', ['Lies within the gene and detects the causal polymorphism itself', 'Is 50 cM away from the gene', 'Is based on plant height', 'Is randomly located'], 0,
    'It cannot be separated from the trait by recombination.'],
  ['Genomic selection differs from marker-assisted selection in that it:', ['Uses genome-wide markers to predict breeding values for complex traits', 'Uses only one marker', 'Needs no genotyping', 'Is applied only to disease resistance'], 0,
    'It is suited to polygenic traits with many small-effect loci.'],
  ['An advantage of marker-assisted selection is that plants can be selected:', ['At the seedling stage, independent of the environment', 'Only after harvest', 'Only in the presence of the pathogen', 'Only for dominant genes'], 0,
    'Recessive genes and hard-to-score traits can also be tracked.'],
  ['DNA fingerprinting with SSR markers is used in the seed industry to:', ['Test the genetic purity of hybrid seed lots quickly', 'Measure seed moisture', 'Estimate germination', 'Grade seeds by size'], 0,
    'It is faster than the traditional grow-out test.'],
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: 'CSE-2026-A2-Q3a', q: [
  ['Narrow-sense heritability is the ratio of:', ['Additive genetic variance to phenotypic variance', 'Total genetic variance to phenotypic variance', 'Environmental variance to genetic variance', 'Dominance variance to additive variance'], 0,
    'h² = VA ÷ VP. Broad-sense H² = VG ÷ VP.'],
  ['Using the breeder’s equation, if the selection differential is 10 units and narrow-sense heritability is 0.4, the expected response is:', ['4 units', '10 units', '0.4 units', '25 units'], 0,
    'R = h² × S = 0.4 × 10 = 4.'],
  ['High heritability together with high genetic advance for a trait usually indicates:', ['Additive gene action, so simple selection will work', 'Non-additive gene action', 'No genetic variation', 'Strong environmental effect only'], 0,
    'High heritability with low genetic advance suggests non-additive effects.'],
  ['The regression of offspring on mid-parent values estimates:', ['Narrow-sense heritability', 'Broad-sense heritability', 'Environmental variance', 'Dominance variance'], 0,
    'Regression on a single parent estimates half the narrow-sense heritability.'],
  ['The heritability of a trait:', ['Varies with the population and environment in which it is measured', 'Is a fixed constant for that trait in all populations', 'Is always 1', 'Cannot exceed 0.1'], 0,
    'It is a property of a population in a given environment, not of the trait alone.'],
  ['Heritability values range from:', ['0 to 1', '−1 to +1', '1 to 100', '0 to infinity'], 0,
    'Often expressed as a percentage (0–100%).'],
  ['In the formula for genetic advance (GA = k × σP × h²), k at 5% selection intensity is:', ['2.06', '1.00', '0.05', '5.00'], 0,
    'k is the standardised selection differential.'],
  ['Phenotypic variance can be partitioned as:', ['VP = VG + VE (plus G × E interaction)', 'VP = VG − VE', 'VP = VA × VD', 'VP = VE only'], 0,
    'VG = VA (additive) + VD (dominance) + VI (epistasis).'],
  ['For low-heritability traits such as grain yield, breeders rely more on:', ['Progeny testing, family selection and replicated multi-location trials', 'Selecting single plants by eye', 'Ignoring the environment', 'Mass selection in one season only'], 0,
    'These reduce the influence of environment on selection decisions.'],
  ['In vegetatively propagated crops, broad-sense heritability is relevant to selection because:', ['Clones transmit the whole genotype, including non-additive effects', 'Only additive effects are passed on', 'Clones segregate', 'Environment has no effect on clones'], 0,
    'In sexually propagated crops, only additive effects are reliably transmitted.'],
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'CSE-2026-A2-Q3b', q: [
  ['Isolation distance is most critical in seed production of:', ['Cross-pollinated crops such as maize and pearl millet', 'Self-pollinated crops such as wheat', 'Clonal crops such as potato', 'Apomictic grasses'], 0,
    'Self-pollinated crops need only a few metres to avoid mechanical mixture.'],
  ['Rogueing in a seed crop means:', ['Removing off-types, other varieties, diseased plants and objectionable weeds', 'Irrigating the field', 'Applying fertiliser', 'Harvesting early'], 0,
    'Done at vegetative, flowering and maturity stages.'],
  ['The Indian Minimum Seed Certification Standards prescribe an isolation distance for certified seed of wheat of about:', ['3 m', '200 m', '400 m', '1 km'], 0,
    'Wheat is self-pollinated, so a small distance to prevent mechanical mixing is enough.'],
  ['Detasselling in hybrid maize seed production is done to:', ['Prevent self-pollination of the female parent', 'Increase plant height', 'Protect from insects', 'Improve grain colour'], 0,
    'Tassels are removed from female rows before pollen shedding; CMS lines avoid this labour.'],
  ['Staggered sowing of the parental lines in hybrid seed production is done to:', ['Synchronise their flowering', 'Save seed', 'Reduce isolation distance', 'Avoid rogueing'], 0,
    'The male must shed pollen when the female is receptive.'],
  ['"Supplementary pollination" by rope pulling or shaking is a standard practice in seed production of:', ['Hybrid rice', 'Wheat varieties', 'Potato', 'Sugarcane'], 0,
    'It improves pollen dispersal from the restorer rows; GA₃ spray improves panicle exsertion in the A line.'],
  ['Seed reaches its maximum dry weight and vigour at:', ['Physiological maturity', 'Flowering', 'Milk stage', 'Early dough stage'], 0,
    'Harvesting later exposes seed to field weathering; harvesting too early lowers quality.'],
  ['Field inspections for seed certification are carried out by:', ['The State Seed Certification Agency', 'The seed dealer', 'The farmer alone', 'The Food Corporation of India'], 0,
    'Inspections check isolation, off-types, diseases and weeds at key stages.'],
  ['In Indian standards, the minimum genetic purity of certified seed of most varieties is:', ['99.0%', '90%', '100%', '95%'], 0,
    'Foundation seed needs 99.5%; breeder seed should be genetically 100% pure.'],
  ['A key principle in seed production of any crop is:', ['Maintaining genetic purity by using the right seed class, isolation and rogueing', 'Using farm-saved grain as seed', 'Mixing varieties to increase yield', 'Skipping field inspections'], 0,
    'Cross-pollinated crops additionally need isolation, planting ratios and synchronised flowering.'],
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: 'CSE-2026-A2-Q3c', q: [
  ['A hallmark of cytoplasmic inheritance is that:', ['Reciprocal crosses give different results, usually following the maternal parent', 'F₂ shows a 3:1 ratio', 'Traits are always sex-linked', 'Both parents contribute equally'], 0,
    'Genes lie in plastids or mitochondria, which are mostly transmitted through the egg.'],
  ['Shell coiling in the snail *Limnaea* is an example of:', ['A maternal effect of the mother’s nuclear genotype, not cytoplasmic inheritance', 'Plastid inheritance', 'Sex-linked inheritance', 'Polygenic inheritance'], 0,
    'The phenotype depends on the mother’s genotype, but the genes are nuclear and segregate normally in later generations.'],
  ['Biparental plastid inheritance is seen in:', ['*Pelargonium* (geranium) and *Oenothera*', 'Maize', 'Wheat', 'Rice'], 0,
    'In most angiosperms plastids are inherited maternally.'],
  ['A test used to confirm cytoplasmic inheritance is that the trait:', ['Persists even after repeated backcrossing to the male (pollen) parent', 'Disappears after one backcross', 'Segregates 1:1 in the test cross', 'Appears only in males'], 0,
    'Substitution backcrossing replaces the nucleus but keeps the cytoplasm.'],
  ['Sex-influenced traits are:', ['Expressed in both sexes, but dominance differs between males and females', 'Expressed only in one sex', 'Controlled by genes on the Y chromosome', 'Controlled by cytoplasmic genes'], 0,
    'Examples: pattern baldness in humans, horns in some sheep breeds.'],
  ['Sex-influenced traits are controlled by genes located on:', ['Autosomes', 'The X chromosome only', 'The Y chromosome only', 'Mitochondria'], 0,
    'Sex hormones alter their expression.'],
  ['Sex-limited traits are:', ['Expressed in only one sex, although both sexes carry the genes', 'Expressed equally in both sexes', 'Always recessive', 'Found only in plants'], 0,
    'Examples: milk yield in cattle, beard growth in men, cock-feathering in poultry.'],
  ['Milk yield in dairy cattle is an example of a:', ['Sex-limited trait', 'Sex-linked trait', 'Cytoplasmic trait', 'Sex-influenced trait with equal expression'], 0,
    'Bulls carry and pass on genes for milk yield, evaluated through their daughters (progeny testing).'],
  ['Leaf variegation in *Mirabilis jalapa* (Correns) shows inheritance through:', ['Plastids from the maternal parent', 'Y-linked genes', 'Paternal mitochondria', 'Dominant nuclear genes'], 0,
    'Seeds from green branches give green plants regardless of pollen source.'],
  ['Cytoplasmic genes do not show Mendelian ratios mainly because:', ['Organelles are distributed to daughter cells without meiotic segregation and mostly through one parent', 'They are always dominant', 'They are located on autosomes', 'They are lost in every generation'], 0,
    'Many copies per cell and random sorting-out also occur.'],
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'CSE-2026-A2-Q4a', q: [
  ['Seed replacement rate (SRR) is:', ['The percentage of area sown with fresh quality seed instead of farm-saved seed', 'The rate of seed germination', 'The rate of seed deterioration', 'The seed rate per hectare'], 0,
    'Low SRR in self-pollinated crops limits the market for their seed.'],
  ['The SATHI portal (2023) was launched to:', ['Trace seed from production to sale and curb spurious seed', 'Pay crop insurance', 'Book tractors', 'Sell fertiliser'], 0,
    'Seed Traceability, Authentication and Holistic Inventory — QR-coded seed lots.'],
  ['The maximum sale price of Bt cotton seed is regulated under the:', ['Cotton Seed Price (Control) Order, 2015', 'Seeds Act, 1966', 'PPV&FR Act, 2001', 'Insecticides Act, 1968'], 0,
    'Issued under the Essential Commodities Act; the Centre notifies prices and trait value each year.'],
  ['A basic reason seed marketing is risky is that seed:', ['Is perishable, seasonal and has demand that depends on the monsoon', 'Never loses viability', 'Has steady demand all year', 'Can be sold as grain at the same price'], 0,
    'Unsold seed must be carried over at a cost or sold as grain at a loss.'],
  ['Carry-over seed can be sold in the next season only after:', ['Re-testing for germination and revalidation of the label', 'Changing the variety name', 'Adding fertiliser', 'Mixing with fresh seed'], 0,
    'Certification tags have a validity period; seed must meet standards again.'],
  ['Hybrid seed markets for maize, cotton and vegetables are dominated by:', ['Private seed companies', 'Only state agriculture departments', 'Farmers’ own saved seed', 'Food Corporation of India'], 0,
    'Hybrids must be bought every season, giving higher margins; the public sector is strong in varieties of self-pollinated crops.'],
  ['Spurious or counterfeit seed hurts the seed market mainly by:', ['Destroying farmers’ trust and causing crop losses', 'Lowering seed prices fairly', 'Improving competition', 'Increasing germination'], 0,
    'Strong labelling, traceability and enforcement are needed.'],
  ['Truthfully labelled (TL) seed differs from certified seed in that:', ['Its quality is declared by the producer and it is not certified by a certification agency', 'It has no label at all', 'It is always breeder seed', 'It cannot be sold legally'], 0,
    'It must still meet minimum germination and purity for notified kinds.'],
  ['Demand forecasting for seed is difficult mainly because:', ['Area sown and crop choice change with monsoon rainfall and prices', 'Seed demand never changes', 'Farmers never buy seed', 'There are no crop statistics'], 0,
    'Seed rolling plans help match production to expected demand.'],
  ['"Seed village" schemes improve seed availability by:', ['Training farmers in a village to produce quality seed for local use and sale', 'Importing seed', 'Closing private seed firms', 'Distributing grain as seed'], 0,
    'They raise the seed replacement rate at low cost.'],
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'CSE-2026-A2-Q4b', q: [
  ['Maximum available water capacity is usually found in:', ['Loam and silt loam soils', 'Coarse sands', 'Gravels', 'Pure clays'], 0,
    'Sands hold little water; clays hold a lot, but much of it is held too tightly (below the wilting point).'],
  ['Adding organic matter to a sandy soil:', ['Increases its available water capacity', 'Decreases water holding', 'Makes it saline', 'Has no effect'], 0,
    'Humus absorbs water and improves aggregation.'],
  ['Available water capacity 150 mm per metre of soil with a 0.8 m root zone gives a total available water of:', ['120 mm', '150 mm', '187 mm', '80 mm'], 0,
    '150 mm/m × 0.8 m = 120 mm.'],
  ['Salinity reduces the water available to plants because:', ['Dissolved salts lower the soil water’s osmotic potential ("physiological drought")', 'Salts evaporate water', 'Salts increase soil depth', 'Salts improve root growth'], 0,
    'Roots must work harder to take up water from saline soil.'],
  ['Soil compaction reduces water available to crops mainly by:', ['Reducing pore space and restricting root growth', 'Increasing macropores', 'Adding organic matter', 'Raising field capacity'], 0,
    'Hardpans also limit rooting depth.'],
  ['Good soil aggregation increases water availability because it:', ['Creates a range of pore sizes that store water and allow infiltration', 'Seals the surface', 'Reduces infiltration', 'Removes micropores'], 0,
    'Structure affects both entry and storage of water.'],
  ['Soils rich in montmorillonite:', ['Hold much water, but a large part is unavailable because it is held tightly', 'Hold no water', 'Drain like sand', 'Contain no clay'], 0,
    'Typical of Vertisols.'],
  ['Hysteresis in soil water retention means that, at the same matric potential, soil:', ['Holds more water while drying than while wetting', 'Holds more water while wetting than drying', 'Holds equal water in both', 'Holds no water'], 0,
    'Caused by the "ink-bottle" effect and trapped air.'],
  ['Deeper rooting increases the water available to a crop because:', ['A larger soil volume can be exploited', 'Root hairs die', 'Soil becomes saline', 'Transpiration stops'], 0,
    'Deep-rooted crops such as pigeonpea and sorghum tolerate drought better.'],
  ['Available water is defined as the water held between:', ['Field capacity and the permanent wilting point', 'Saturation and field capacity', 'Wilting point and oven-dry', 'Hygroscopic coefficient and air-dry'], 0,
    'Water between saturation and field capacity drains away by gravity.'],
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'CSE-2026-A2-Q4c', q: [
  ['Seed priming is:', ['Controlled hydration to start pre-germination metabolism without radicle emergence, followed by re-drying', 'Coating seeds with fungicide only', 'Storing seeds at low temperature', 'Removing the seed coat'], 0,
    'Primed seeds germinate faster and more uniformly.'],
  ['Osmopriming commonly uses solutions of:', ['Polyethylene glycol (PEG)', 'Sulphuric acid', 'Mercury compounds', 'Pure ethanol'], 0,
    'Hydropriming uses water; halopriming uses salts such as KNO₃; biopriming uses beneficial microbes.'],
  ['Seed pelleting is especially useful for:', ['Very small or irregular seeds (e.g., tobacco, carrot, lettuce) to allow precision sowing', 'Large seeds like coconut', 'Vegetatively propagated crops', 'Seeds that are already round'], 0,
    'Pelleting changes the size and shape; film coating adds a thin polymer layer with chemicals.'],
  ['Seed hardening (repeated soaking and drying) is recommended in drylands to:', ['Improve tolerance to early drought', 'Break dormancy of legumes', 'Increase seed size', 'Kill weeds'], 0,
    'It improves establishment under moisture stress.'],
  ['Biopriming involves treating seeds with:', ['Beneficial microbes such as *Trichoderma* or *Pseudomonas* during hydration', 'Radiation', 'Growth retardants', 'Hot water only'], 0,
    'Combines the benefits of priming with biological disease protection.'],
  ['A limitation of primed seed is that it:', ['Usually has a shorter storage life', 'Never germinates', 'Is always infected', 'Cannot be sown by machine'], 0,
    'Primed seed is best sown within a limited period.'],
  ['A specific-gravity separator upgrades a seed lot by:', ['Removing light, poorly filled and damaged seeds', 'Adding weight to seeds', 'Coating seeds', 'Priming seeds'], 0,
    'Size grading and density grading remove weak seeds and improve lot quality.'],
  ['A benefit of seed enhancement for farmers is:', ['Faster, more uniform emergence and better stand establishment', 'Lower yields', 'Higher seed rate', 'Longer time to emergence'], 0,
    'Especially valuable for costly hybrid seed and under stress.'],
  ['Film coating of seed with polymers mainly serves to:', ['Hold protective chemicals and colour on the seed evenly with little dust', 'Change seed shape', 'Break dormancy', 'Increase seed size by 10 times'], 0,
    'It reduces dust exposure during handling and sowing.'],
  ['Halopriming uses:', ['Salt solutions such as potassium nitrate', 'Only pure water', 'Polyethylene glycol', 'Solid matrix'], 0,
    'Matrix priming (matripriming) uses moist solid carriers.'],
] }
);
