/* PYQ-linked MCQs — IFoS 2025 Botany Paper I (topic-level PYQs from the volume anchors). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Bryophytes', w: 2, pyq: 'IFoS-2025-B1-Q1a', q: [
  ['Rhizoids of mosses differ from those of liverworts in being:', ['Multicellular with oblique cross-walls', 'Unicellular and smooth', 'Unicellular and tuberculate', 'Absent'], 0,
    'Liverworts have unicellular rhizoids (smooth and tuberculate types in *Marchantia*).'],
  ['Leaves of mosses usually differ from those of leafy liverworts in that moss leaves:', ['Are spirally arranged and often have a midrib (costa)', 'Are in two rows and lobed without a midrib', 'Are absent', 'Are always underground'], 0,
    'Leafy liverworts have two lateral rows plus a row of underleaves (amphigastria) and no midrib.'],
  ['Elaters are present in the capsule of:', ['Liverworts such as *Marchantia* and *Pellia*, but not mosses', 'Mosses only', 'Both mosses and liverworts equally', 'Neither group'], 0,
    'Mosses disperse spores through the peristome instead.'],
  ['A columella in the sporophyte capsule is characteristic of:', ['Mosses (and hornworts), but not liverworts', 'Liverworts only', 'Ferns', 'Algae'], 0,
    'The central sterile columella is absent from liverwort capsules.'],
  ['The seta of a liverwort sporophyte elongates:', ['After the capsule has matured, rapidly by cell elongation', 'Before the capsule matures, by cell division', 'Never', 'Only in water'], 0,
    'In mosses the seta elongates early, before capsule maturation.'],
  ['Oil bodies in cells are a distinctive feature of:', ['Liverworts', 'Mosses', 'Hornworts', 'Lichens'], 0,
    'They are membrane-bound bodies of terpenoid oils, useful in liverwort taxonomy.'],
  ['Stomata on the sporophyte (in the apophysis region of the capsule) occur in:', ['Mosses, but not liverworts', 'Liverworts only', 'Neither', 'Only in *Riccia*'], 0,
    'Hornworts also have stomata on the sporophyte.'],
  ['In mosses, the calyptra:', ['Is carried up as a cap on top of the capsule', 'Stays at the base of the seta', 'Is absent', 'Forms the peristome'], 0,
    'In liverworts the calyptra ruptures and remains around the base of the sporophyte.'],
  ['The protonema is:', ['Prominent and filamentous in mosses, but reduced and short-lived in liverworts', 'Prominent in liverworts only', 'Absent in mosses', 'A stage of the sporophyte'], 0,
    'Buds on the moss protonema form leafy gametophores.'],
  ['Which is a leafy liverwort?', ['*Porella*', '*Funaria*', '*Polytrichum*', '*Sphagnum*'], 0,
    '*Funaria*, *Polytrichum* and *Sphagnum* are mosses; *Marchantia* and *Riccia* are thalloid liverworts.'],
] },
{ p: 'B1', t: 'Microbiology', w: 2, pyq: 'IFoS-2025-B1-Q1c', q: [
  ['Cyanobacteria resemble bacteria in having:', ['A prokaryotic cell with no nucleus, 70S ribosomes and a peptidoglycan wall', 'A membrane-bound nucleus', 'Chloroplasts', 'Mitochondria'], 0,
    'This is why they are now placed with bacteria rather than algae.'],
  ['Cyanobacteria resemble algae and plants in:', ['Oxygenic photosynthesis using chlorophyll a and two photosystems', 'Having chloroplasts with double membranes', 'Having flagellated gametes', 'Having a nucleus'], 0,
    'Photosynthetic bacteria such as green sulphur bacteria do not release oxygen.'],
  ['Phycobilisomes containing phycocyanin and phycoerythrin link cyanobacteria with:', ['Red algae', 'Green algae', 'Brown algae', 'Diatoms'], 0,
    'Red algal chloroplasts are thought to derive from a cyanobacterium.'],
  ['In cyanobacteria, the thylakoids lie:', ['Free in the cytoplasm, not enclosed in chloroplasts', 'Inside chloroplasts', 'Inside the nucleus', 'In mitochondria'], 0,
    'Prokaryotes lack membrane-bound organelles.'],
  ['The reserve food of cyanobacteria is:', ['Cyanophycean starch (glycogen-like) and cyanophycin granules', 'Floridean starch', 'Laminarin', 'True starch in pyrenoids'], 0,
    'Cyanophycin is a nitrogen reserve (arginine–aspartate polymer).'],
  ['Cyanobacteria move, where they move at all, by:', ['Gliding, since they lack flagella', 'Flagella', 'Cilia', 'Pseudopodia'], 0,
    'Absence of flagellated stages is another difference from most algae.'],
  ['Nitrogen fixation by cyanobacteria reflects their:', ['Bacterial (prokaryotic) nature — no eukaryotic alga fixes N₂ on its own', 'Algal nature', 'Plant nature', 'Fungal nature'], 0,
    'Nitrogenase occurs only in prokaryotes.'],
  ['Thick-walled resting cells formed by cyanobacteria such as *Nostoc* and *Anabaena* are:', ['Akinetes', 'Heterocysts', 'Hormogonia', 'Zoospores'], 0,
    'Hormogonia are short motile filaments for vegetative spread; heterocysts fix nitrogen.'],
  ['Fritsch treated cyanobacteria as the algal class:', ['Myxophyceae (Cyanophyceae)', 'Rhodophyceae', 'Chlorophyceae', 'Phaeophyceae'], 0,
    'Modern systems place them in the domain Bacteria (phylum Cyanobacteria).'],
  ['Chloroplasts of plants are believed to have originated from:', ['Endosymbiotic cyanobacteria', 'Mitochondria', 'Viruses', 'Fungi'], 0,
    'Evidence: circular DNA, 70S ribosomes and double membranes.'],
] },
{ p: 'B1', t: 'Microbiology', w: 2, pyq: 'IFoS-2025-B1-Q1d', q: [
  ['Industrial ethanol by fermentation is produced mainly with:', ['*Saccharomyces cerevisiae* (and the bacterium *Zymomonas mobilis*)', '*Aspergillus niger*', '*Bacillus licheniformis*', '*Trichoderma reesei*'], 0,
    'Molasses and grain are common substrates; ethanol blending in petrol uses this route.'],
  ['Citric acid is produced commercially by fermentation with:', ['*Aspergillus niger*', '*Saccharomyces cerevisiae*', '*Penicillium chrysogenum*', '*Lactobacillus*'], 0,
    'It is used as a food acidulant and preservative.'],
  ['The antibiotic bacitracin is produced by:', ['*Bacillus licheniformis*', '*Streptomyces griseus*', '*Penicillium notatum*', '*Aspergillus flavus*'], 0,
    'A polypeptide antibiotic used on skin infections.'],
  ['Cellulase enzymes for industry are produced mainly by:', ['*Trichoderma reesei*', '*Rhizobium*', '*Saccharomyces*', '*Acetobacter*'], 0,
    'Used in textiles, detergents, juice processing and second-generation ethanol.'],
  ['Streptomycin is obtained from:', ['*Streptomyces griseus*', '*Bacillus subtilis*', '*Penicillium chrysogenum*', '*Aspergillus niger*'], 0,
    'Discovered by Waksman’s group (1943).'],
  ['Vinegar (acetic acid) is produced by oxidation of ethanol with:', ['*Acetobacter*', '*Lactobacillus*', '*Aspergillus*', '*Clostridium*'], 0,
    'An aerobic bacterial process.'],
  ['Lactic acid bacteria used in curd and silage belong to the genus:', ['*Lactobacillus*', '*Rhizobium*', '*Azotobacter*', '*Streptomyces*'], 0,
    'They ferment sugars to lactic acid, lowering pH.'],
  ['Fungal α-amylase for starch processing is produced by:', ['*Aspergillus oryzae*', '*Rhizobium*', '*Anabaena*', '*Nostoc*'], 0,
    'Bacterial amylases come from *Bacillus* species.'],
  ['The cholesterol-lowering statin lovastatin is produced by:', ['*Aspergillus terreus* (and *Monascus purpureus*)', '*Saccharomyces*', '*Trichoderma*', '*Penicillium chrysogenum*'], 0,
    'Red yeast rice made with *Monascus* contains monacolin K (lovastatin).'],
  ['Microbes suit industrial production because they:', ['Grow fast on cheap substrates, can be genetically improved and give high yields in fermenters', 'Grow only on costly media', 'Cannot be scaled up', 'Need sunlight'], 0,
    'Downstream processing then purifies the product.'],
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, pyq: 'IFoS-2025-B1-Q1e', q: [
  ['Seed ferns (Pteridospermales / Cycadofilicales) are best described as:', ['Extinct plants with fern-like fronds that bore true seeds', 'Living ferns with spores', 'Early angiosperms', 'Bryophytes with seeds'], 0,
    'They flourished in the Carboniferous and Permian.'],
  ['Seeds were first shown to be borne on the fronds of *Lyginopteris* by:', ['Oliver and Scott (1904)', 'Darwin (1859)', 'Linnaeus (1753)', 'Zimmermann (1930)'], 0,
    'This established the group Pteridospermae.'],
  ['*Lagenostoma* is the seed of:', ['*Lyginopteris*', '*Medullosa*', '*Glossopteris*', '*Cycas*'], 0,
    'It has a cupule and a lagenostome (pollen chamber).'],
  ['*Medullosa* is notable for its:', ['Polystelic stem, with seeds of the *Trigonocarpus* type', 'Single protostele', 'Lack of secondary wood', 'Flowers'], 0,
    'A Carboniferous seed fern of coal swamps.'],
  ['The *Glossopteris* flora is characteristic of:', ['The Permian of Gondwana, including the Lower Gondwana coals of India', 'The Tertiary of Europe', 'The Cambrian of Scotland', 'The Quaternary of Siberia'], 0,
    'Its distribution across southern continents supported continental drift.'],
  ['The stem genus *Lyginopteris* was earlier described under the name:', ['*Lyginodendron*', '*Calamites*', '*Lepidodendron*', '*Sigillaria*'], 0,
    '*Calamites*, *Lepidodendron* and *Sigillaria* are pteridophytes.'],
  ['*Caytonia*, sometimes discussed as a possible angiosperm precursor, is a:', ['Mesozoic seed fern (Caytoniales)', 'Modern cycad', 'Carboniferous horsetail', 'Moss'], 0,
    'Its cupules enclosing ovules were once compared to carpels.'],
  ['A key character of seed ferns is:', ['Fern-like leaves with secondary wood and seeds borne on the fronds', 'Flowers and fruits', 'Absence of vascular tissue', 'Motile spores only'], 0,
    'They combine fern and seed-plant features.'],
  ['The evolutionary importance of seed ferns is that they:', ['Link ferns with seed plants and are possible ancestors of later seed plants', 'Are ancestors of bryophytes', 'Are the first land plants', 'Are living fossils still common today'], 0,
    'Some are considered ancestral to cycads and possibly angiosperms.'],
  ['Pollen organs of *Lyginopteris* are known as:', ['*Crossotheca* (and related synangia)', '*Trigonocarpus*', '*Lepidostrobus*', '*Calamostachys*'], 0,
    '*Lepidostrobus* and *Calamostachys* are cones of *Lepidodendron* and *Calamites*.'],
] },
{ p: 'B1', t: 'Bryophytes', w: 2, pyq: 'IFoS-2025-B1-Q2a', q: [
  ['Bryophytes act as pioneers on bare rock mainly by:', ['Trapping dust and organic matter to start soil formation after lichens', 'Fixing nitrogen in root nodules', 'Growing tall trees', 'Burning organic matter'], 0,
    'They are an early stage of the xerosere.'],
  ['*Sphagnum* peatlands are ecologically important because they:', ['Store huge amounts of carbon', 'Release oxygen only', 'Increase soil erosion', 'Have no water'], 0,
    'Peatlands hold a large share of global soil carbon.'],
  ['Peat formation in *Sphagnum* bogs is favoured by:', ['Acidic, waterlogged and cool conditions that slow decomposition', 'Warm, dry conditions', 'Alkaline, well-drained soils', 'Frequent fires'], 0,
    'Dead moss accumulates faster than it decays.'],
  ['The "moss bag" technique uses mosses to:', ['Monitor atmospheric heavy-metal pollution', 'Grow vegetables', 'Store water for irrigation', 'Measure rainfall'], 0,
    'Mosses absorb metals from air and rain over their whole surface.'],
  ['"Copper mosses" such as *Mielichhoferia* are significant as:', ['Indicators of copper-rich substrates', 'Sources of copper fertiliser', 'Food plants', 'Timber'], 0,
    'Such indicator species can guide mineral prospecting.'],
  ['Moss carpets on forest floors help watersheds by:', ['Holding water, reducing runoff and checking erosion', 'Increasing surface runoff', 'Drying the soil', 'Blocking infiltration'], 0,
    'Some mosses hold many times their dry weight in water.'],
  ['Feather mosses (e.g., *Pleurozium*) in boreal forests contribute to nitrogen supply through:', ['Associated nitrogen-fixing cyanobacteria', 'Root nodules', 'Nitrate fertiliser', 'Lightning'], 0,
    'This is a major N input in boreal ecosystems.'],
  ['Epiphyllous liverworts on leaves in the humid tropics indicate:', ['Very high atmospheric humidity', 'Drought', 'Salinity', 'Fire'], 0,
    'They are sensitive to changes in forest microclimate.'],
  ['Bryophytes are sensitive indicators of air pollution because they:', ['Lack a protective cuticle and absorb water and solutes directly', 'Have thick bark', 'Have deep roots', 'Grow only indoors'], 0,
    'SO₂ and heavy metals damage them readily.'],
  ['Moss mats help seedlings of vascular plants by:', ['Providing a moist seedbed and sheltered microhabitat', 'Shading them completely', 'Removing all nutrients', 'Producing toxins'], 0,
    'They also host many small invertebrates.'],
] },
{ p: 'B1', t: 'Algae', w: 2, pyq: 'IFoS-2025-B1-Q2b', q: [
  ['The thallus of *Laminaria* is differentiated into:', ['Holdfast (hapteron), stipe and lamina (blade)', 'Rhizoids, leaves and flowers', 'Nucule and globule', 'Protonema and gametophore'], 0,
    'It is a large kelp of cold seas.'],
  ['Growth in *Laminaria* comes mainly from:', ['An intercalary meristem at the junction of stipe and lamina', 'An apical cell only', 'Root tips', 'A cambium in the holdfast'], 0,
    'New blade tissue is added from below as old tissue wears away at the tip.'],
  ['Sieve-tube-like conducting cells in the medulla of *Laminaria* are called:', ['Trumpet hyphae', 'Tracheids', 'Vessels', 'Laticifers'], 0,
    'They have sieve plates and conduct photosynthates.'],
  ['The life cycle of *Laminaria* shows:', ['Heteromorphic alternation — a large diploid sporophyte and microscopic haploid gametophytes', 'Isomorphic alternation', 'A diplontic cycle', 'Only asexual reproduction'], 0,
    'The gametophytes are dioecious and filamentous.'],
  ['Meiosis in *Laminaria* occurs in:', ['Unilocular sporangia in sori on the lamina, producing zoospores', 'The oogonium', 'The holdfast', 'The antheridium'], 0,
    'Sori contain sporangia interspersed with sterile paraphyses.'],
  ['Sexual reproduction in *Laminaria* is:', ['Oogamous, with the egg retained at the mouth of the oogonium', 'Isogamous', 'Anisogamous with motile eggs', 'By conjugation'], 0,
    'Sperms are released from antheridia on male gametophytes.'],
  ['The sperm attractant (pheromone) of *Laminaria* is:', ['Lamoxirene', 'Sirenin', 'Trisporic acid', 'Ectocarpene only'], 0,
    'Sirenin is the attractant of *Allomyces*; trisporic acid is the Mucorales sex hormone.'],
  ['*Laminaria* is economically important as a source of:', ['Alginates, iodine and food (kombu)', 'Agar', 'Carrageenan', 'Diatomite'], 0,
    'Agar and carrageenan come from red algae.'],
  ['The brown colour of *Laminaria* is due to:', ['Fucoxanthin', 'Phycoerythrin', 'Phycocyanin', 'Chlorophyll b'], 0,
    'Phaeophyceae have chlorophylls a and c with fucoxanthin.'],
  ['The reserve foods of *Laminaria* are:', ['Laminarin and mannitol', 'Floridean starch', 'True starch', 'Glycogen'], 0,
    'Laminarin is a β-1,3-glucan.'],
] },
{ p: 'B1', t: 'Plant Pathology', w: 3, pyq: 'IFoS-2025-B1-Q3b', q: [
  ['Late leaf spot of groundnut differs from early leaf spot in having:', ['Darker, nearly black lesions, mainly on the lower leaf surface, without a prominent yellow halo', 'Brown spots with a bright yellow halo on the upper surface', 'Only stem lesions', 'Only pod rot'], 0,
    'Early leaf spot (*Cercospora arachidicola*) appears earlier, about a month after sowing.'],
  ['The perfect (sexual) stages of the tikka pathogens are:', ['*Mycosphaerella arachidis* (early) and *M. berkeleyi* (late)', '*Puccinia arachidis*', '*Sclerotium rolfsii*', '*Aspergillus niger*'], 0,
    'Late leaf spot is now also named *Nothopassalora personata*.'],
  ['The primary inoculum of tikka disease comes mainly from:', ['Infected crop debris and volunteer groundnut plants', 'Seed only', 'Aphid vectors', 'Irrigation water only'], 0,
    'Crop rotation and removal of debris reduce it.'],
  ['Secondary spread of tikka within a crop is by:', ['Conidia carried by wind, rain splash and insects', 'Root contact only', 'Seed transmission only', 'Nematodes'], 0,
    'Repeated cycles build up severe defoliation.'],
  ['Tikka disease is favoured by:', ['High humidity, prolonged leaf wetness and temperatures around 25–30 °C', 'Dry, hot weather', 'Frost', 'Low humidity'], 0,
    'Rainy-season groundnut is most affected.'],
  ['Tikka reduces groundnut yield mainly through:', ['Premature defoliation, cutting photosynthesis and pod filling', 'Root rot', 'Seed abortion only', 'Flower drop only'], 0,
    'Losses are large when both leaf spots and rust occur together.'],
  ['A groundnut variety known for resistance to late leaf spot and rust is:', ['GPBD 4', 'TMV 2', 'JL 24', 'TAG 24'], 0,
    'Released by UAS Dharwad; widely used as a resistance source.'],
  ['A fungicide spray commonly recommended against tikka is:', ['Carbendazim + mancozeb, or chlorothalonil / tebuconazole', 'Streptocycline', 'Carbofuran', 'Glyphosate'], 0,
    'Sprays start at first appearance and are repeated at intervals.'],
  ['Intercropping groundnut with pearl millet can lower tikka because the tall crop:', ['Acts as a barrier to spore movement and changes the microclimate', 'Kills the fungus directly', 'Adds fungicide to soil', 'Increases leaf wetness'], 0,
    'A cultural component of integrated disease management.'],
  ['The name "tikka" refers to the:', ['Spots (marks) formed on groundnut leaves', 'Pod rot', 'Stem breaking', 'Seed colour'], 0,
    'From the Hindi word for a mark on the forehead.'],
] },
{ p: 'B1', t: 'Pteridophytes', w: 2, pyq: 'IFoS-2025-B1-Q3c', q: [
  ['*Ophioglossum* (adder’s-tongue fern) is:', ['A eusporangiate fern', 'A leptosporangiate fern', 'A moss', 'A seed plant'], 0,
    'Family Ophioglossaceae, with *Botrychium* (grape fern, moonwort).'],
  ['In *Ophioglossum*, each leaf consists of:', ['A sterile lamina and a fertile spike arising from its base', 'Only a fertile spike', 'A sporocarp', 'Sori on the lower surface'], 0,
    'The spike bears two rows of large sunken sporangia.'],
  ['Sporangia of *Ophioglossum*:', ['Are large, have a multilayered wall, many spores and no annulus, and open by a transverse slit', 'Have an annulus and few spores', 'Are borne in sori with indusia', 'Are microscopic'], 0,
    'These are classic eusporangiate features.'],
  ['*Ophioglossum reticulatum* is famous for having:', ['The highest chromosome number known in plants (2n ≈ 1260)', 'No chromosomes', 'The smallest genome', 'Only two chromosomes'], 0,
    'Its haploid number is about 630.'],
  ['The gametophyte of *Ophioglossum* is:', ['Subterranean, non-green and mycorrhizal', 'Green and heart-shaped', 'Aquatic', 'Parasitic on flowering plants'], 0,
    'It may live for years underground.'],
  ['*Ophioglossum* is:', ['Homosporous', 'Heterosporous', 'Seed-bearing', 'Without spores'], 0,
    'All spores are of one kind.'],
  ['An unusual feature of *Ophioglossum* leaves compared with most ferns is:', ['Reticulate (net) venation', 'Absence of veins', 'Circinate vernation always', 'Needle-like form'], 0,
    'Most ferns have open, dichotomous venation.'],
  ['Eusporangiate sporangia differ from leptosporangiate sporangia in that they:', ['Develop from a group of initial cells and have a multilayered wall', 'Develop from a single initial cell', 'Always have an annulus', 'Produce very few spores'], 0,
    'Leptosporangiate ferns (e.g., *Pteris*, *Dryopteris*) have a one-layered wall and a stalk.'],
  ['The morphological nature of the fertile spike of *Ophioglossum* is debated; one view regards it as:', ['Two fused basal pinnae of the leaf', 'A separate stem', 'A root outgrowth', 'A flower'], 0,
    'Another view treats it as a ventral lobe of the leaf.'],
  ['Which genus belongs to Ophioglossaceae along with *Ophioglossum*?', ['*Botrychium*', '*Marsilea*', '*Azolla*', '*Equisetum*'], 0,
    '*Marsilea* and *Azolla* are heterosporous water ferns.'],
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 2, pyq: 'IFoS-2025-B1-Q4a', q: [
  ['Soft-rot fungi break down host tissue mainly with:', ['Pectinases (e.g., polygalacturonase) and cellulases', 'Amylases only', 'Lipases only', 'Nitrogenase'], 0,
    'These cell-wall-degrading enzymes dissolve the middle lamella.'],
  ['Patulin contamination is a concern mainly in:', ['Apple juice and apple products (from *Penicillium expansum*)', 'Rice', 'Milk', 'Groundnut oil'], 0,
    'Rotting apples used for juice are the usual source.'],
  ['Fumonisins in maize are produced by:', ['*Fusarium verticillioides*', '*Aspergillus flavus*', '*Claviceps purpurea*', '*Penicillium chrysogenum*'], 0,
    'Linked to oesophageal cancer and livestock disease.'],
  ['Deoxynivalenol ("vomitoxin") is produced mainly by:', ['*Fusarium graminearum*', '*Aspergillus niger*', '*Rhizopus stolonifer*', '*Puccinia graminis*'], 0,
    'It contaminates wheat and barley affected by head blight.'],
  ['Victorin, a host-specific toxin, is produced by the pathogen of:', ['Victoria blight of oats', 'Late blight of potato', 'Rice blast', 'Wheat stem rust'], 0,
    'Only oat varieties carrying a particular resistance gene (from Victoria) were susceptible.'],
  ['Fusicoccin causes wilting because it:', ['Activates the plasma-membrane H⁺-ATPase, keeping stomata open', 'Blocks xylem vessels', 'Destroys chlorophyll', 'Stops root growth'], 0,
    'Produced by *Fusicoccum amygdali*; a tool in stomatal research.'],
  ['Ochratoxin A is produced by:', ['*Aspergillus ochraceus* and *Penicillium verrucosum*', '*Fusarium graminearum*', '*Claviceps purpurea*', '*Rhizopus*'], 0,
    'A kidney toxin found in stored cereals and coffee.'],
  ['α-Amanitin from the death cap mushroom (*Amanita phalloides*) is toxic because it:', ['Inhibits RNA polymerase II', 'Inhibits photosynthesis', 'Blocks ATP synthase', 'Destroys cell walls'], 0,
    'It causes severe liver damage.'],
  ['The immunosuppressant cyclosporin is obtained from the fungus:', ['*Tolypocladium inflatum*', '*Penicillium notatum*', '*Aspergillus flavus*', '*Saccharomyces cerevisiae*'], 0,
    'Used to prevent rejection in organ transplants.'],
  ['*Trichoderma* suppresses plant-pathogenic fungi partly through its:', ['Chitinases and glucanases that digest pathogen cell walls', 'Nitrogen fixation', 'Photosynthesis', 'Toxins that kill crop roots'], 0,
    'Mycoparasitism and competition also contribute.'],
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 2, pyq: 'IFoS-2025-B1-Q4b', q: [
  ['The mycelium of Zygomycetes is typically:', ['Coenocytic and aseptate', 'Septate with dolipores', 'Absent', 'Made of yeast cells only'], 0,
    'Septa form only to delimit reproductive structures.'],
  ['Sexual reproduction in Zygomycetes is by:', ['Gametangial copulation forming a thick-walled zygospore', 'Oogamy', 'Formation of basidiospores', 'Formation of asci'], 0,
    'The zygospore is a resistant resting spore.'],
  ['The correct sequence in zygospore formation is:', ['Progametangia → gametangia + suspensors → fusion → zygosporangium with zygospore', 'Zygospore → gametangia → progametangia', 'Sporangium → gametangia → conidia', 'Ascus → ascospore → zygospore'], 0,
    'Progametangia grow towards each other under hormonal control.'],
  ['The sex hormone that controls zygophore formation in Mucorales is:', ['Trisporic acid', 'Sirenin', 'Antheridiol', 'Lamoxirene'], 0,
    'Antheridiol acts in the water mould *Achlya*.'],
  ['Asexual reproduction in *Rhizopus* and *Mucor* is by:', ['Non-motile sporangiospores formed in sporangia', 'Zoospores', 'Conidia on conidiophores only', 'Basidiospores'], 0,
    'Spores are dispersed by air.'],
  ['*Rhizopus* differs from *Mucor* in having:', ['Stolons and rhizoids', 'Septate hyphae', 'Clamp connections', 'No sporangia'], 0,
    '*Mucor* lacks stolons and rhizoids.'],
  ['*Pilobolus* is known as the "shotgun fungus" because it:', ['Shoots its whole sporangium towards light', 'Explodes in water', 'Produces sound', 'Releases gas'], 0,
    'Sporangia land on grass and pass through herbivores to dung.'],
  ['*Rhizopus stolonifer* causes:', ['Soft rot of sweet potato and fruits, and black bread mould', 'Wheat rust', 'Rice blast', 'Powdery mildew'], 0,
    'A common post-harvest pathogen.'],
  ['On germination, a zygospore usually forms a:', ['Germ sporangium, after meiosis', 'Basidium', 'Ascus', 'Mushroom'], 0,
    'The haploid spores then grow into new mycelia.'],
  ['Insect-pathogenic fungi of the genus *Entomophthora* belong to:', ['Zygomycetes (Entomophthorales)', 'Basidiomycetes', 'Oomycetes', 'Deuteromycetes only'], 0,
    'They cause epidemics in aphids and flies.'],
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 3, pyq: 'IFoS-2025-B1-Q5a', q: [
  ['Adventive embryony is classed as sporophytic apomixis because:', ['The embryo arises directly from a diploid somatic cell (nucellus or integument) outside the embryo sac', 'The embryo arises from an unreduced egg', 'The embryo arises from a sperm', 'No embryo is formed'], 0,
    'Gametophytic apomixis (apospory, diplospory) involves an unreduced embryo sac.'],
  ['Haploid parthenogenesis is the development of an embryo from:', ['An unfertilised, reduced (haploid) egg', 'An unreduced egg', 'The nucellus', 'A synergid after fertilisation'], 0,
    'It gives haploid plants.'],
  ['Haploid parthenogenesis is called "non-recurrent" because:', ['The resulting haploid plants are usually sterile and cannot repeat the process', 'It happens every generation', 'It produces diploid seeds', 'It needs no egg'], 0,
    'Recurrent apomixis (from unreduced cells) can repeat each generation.'],
  ['Diploid parthenogenesis, as in *Taraxacum*, arises from:', ['An unreduced egg in an embryo sac formed without meiosis', 'A reduced egg', 'Nucellar cells', 'Pollen'], 0,
    'Diplospory and apospory produce such unreduced embryo sacs.'],
  ['The "bulbosum method" produces haploid barley through:', ['Elimination of *Hordeum bulbosum* chromosomes after crossing', 'Anther culture', 'Colchicine treatment', 'Irradiation of pollen'], 0,
    'Wheat × maize crosses give wheat haploids in a similar way.'],
  ['In maize, in-vivo haploids are produced using:', ['Haploid-inducer lines (derived from Stock 6) as the pollen parent', 'Somatic hybridisation', 'Mutation breeding only', 'Grafting'], 0,
    'Haploids are then doubled to give doubled-haploid lines.'],
  ['Pseudogamy in some apomicts means that:', ['Pollination is still needed, usually for endosperm formation, though the embryo is not fertilised', 'Pollen is never produced', 'The embryo forms from pollen', 'Seeds form without any endosperm'], 0,
    'Common in apomictic Rosaceae and grasses.'],
  ['In polyembryonic *Citrus*, the zygotic embryo is often:', ['Suppressed or outcompeted by nucellar embryos', 'The only surviving embryo', 'Absent in all seeds', 'Triploid'], 0,
    'This is why seedlings are mostly true-to-type.'],
  ['Gynogenesis refers to:', ['Development of a haploid plant from the female gametophyte (egg or other cells)', 'Development from pollen', 'Fusion of two eggs', 'Development of endosperm'], 0,
    'Androgenesis is development from the male gametophyte (e.g., anther culture).'],
  ['Doubled haploids are valuable in breeding because they:', ['Give completely homozygous lines in one generation', 'Are always sterile', 'Increase heterozygosity', 'Cannot be used in crosses'], 0,
    'They save several generations of selfing.'],
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 3, pyq: 'IFoS-2025-B1-Q5b', q: [
  ['Microspores are formed from microspore mother cells by:', ['Meiosis, producing tetrads', 'Mitosis only', 'Fusion', 'Budding'], 0,
    'Each tetrad separates into four haploid microspores.'],
  ['The first mitosis in a microspore is asymmetric and produces:', ['A large vegetative cell and a small generative cell', 'Two equal cells', 'Two sperms', 'Four nuclei'], 0,
    'The generative cell lies inside the vegetative cell.'],
  ['The generative cell gives rise to:', ['Two male gametes (sperm cells)', 'The pollen tube', 'The exine', 'The tapetum'], 0,
    'This division occurs in the pollen grain or in the pollen tube.'],
  ['Pollen shed at the three-celled stage is typical of:', ['Grasses (Poaceae) and crucifers (Brassicaceae)', 'Most Liliaceae', 'All gymnosperms', 'Pteridophytes'], 0,
    'About 70% of angiosperms shed two-celled pollen.'],
  ['In most dicots, cytokinesis during microsporogenesis is:', ['Simultaneous — walls form after both meiotic divisions', 'Successive — a wall forms after meiosis I', 'Absent', 'Only in the tapetum'], 0,
    'Successive cytokinesis (dyad stage) is common in monocots.'],
  ['The callose wall around microspore tetrads is dissolved by callase secreted by the:', ['Tapetum', 'Endothecium', 'Epidermis', 'Connective'], 0,
    'Timing of callase release is critical; its failure can cause male sterility.'],
  ['Pollen grains remain united as tetrads at maturity in:', ['*Typha* and members of Ericaceae', 'Wheat', 'Mango', 'Maize'], 0,
    'Such compound pollen is also seen in some other families.'],
  ['The "male germ unit" refers to:', ['The two sperm cells physically linked with the vegetative nucleus', 'The anther wall', 'The tapetum', 'The pollen tube tip'], 0,
    'It moves together through the pollen tube.'],
  ['The fluorochromatic reaction (FCR) test for pollen viability uses:', ['Fluorescein diacetate, whose fluorescence shows intact membranes and active esterases', 'Iodine', 'Acetocarmine only', 'Methylene blue'], 0,
    'Developed by Heslop-Harrison.'],
  ['Pollen tube growth is by:', ['Tip growth, with a calcium gradient at the growing tip', 'Growth along its whole length', 'Cell division at the base', 'Swelling of the exine'], 0,
    'Pectin-rich wall material is added at the tip.'],
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 3, pyq: 'IFoS-2025-B1-Q5d', q: [
  ['Indigo dye is obtained from the leaves of:', ['*Indigofera tinctoria*', '*Lawsonia inermis*', '*Bixa orellana*', '*Curcuma longa*'], 0,
    'Its cultivation drove the Champaran indigo movement.'],
  ['Henna colour comes from lawsone in the leaves of:', ['*Lawsonia inermis*', '*Indigofera tinctoria*', '*Rubia cordifolia*', '*Butea monosperma*'], 0,
    'Used for hair and skin; family Lythraceae.'],
  ['Annatto (bixin), a food colour, is obtained from the seeds of:', ['*Bixa orellana*', '*Crocus sativus*', '*Curcuma longa*', '*Mallotus philippensis*'], 0,
    'The seed coat gives orange-red colour for cheese and butter.'],
  ['Indian madder (manjistha), a red dye, comes from the roots of:', ['*Rubia cordifolia*', '*Butea monosperma*', '*Acacia catechu*', '*Lawsonia inermis*'], 0,
    'Contains anthraquinone pigments such as purpurin.'],
  ['The yellow-orange dye traditionally used for Holi comes from the flowers of:', ['*Butea monosperma* (palash, flame of the forest)', '*Tectona grandis*', '*Shorea robusta*', '*Madhuca longifolia*'], 0,
    'The dye is made by boiling or soaking the flowers.'],
  ['Haematoxylin, a biological stain, is extracted from the heartwood of:', ['*Haematoxylum campechianum* (logwood)', '*Tectona grandis*', '*Santalum album*', '*Pterocarpus santalinus*'], 0,
    'Red sanders (*Pterocarpus santalinus*) heartwood gives santalin, a red dye.'],
  ['Kamala dye is obtained from the glandular hairs on the fruits of:', ['*Mallotus philippensis*', '*Bixa orellana*', '*Indigofera*', '*Crocus sativus*'], 0,
    'An orange dye for silk and wool; also used as an anthelmintic.'],
  ['Catechu (katha), used as a dye and for tannin, comes from the heartwood of:', ['*Acacia catechu* (khair)', '*Acacia nilotica*', '*Dalbergia sissoo*', '*Albizia lebbeck*'], 0,
    'Also used in paan and in leather tanning.'],
  ['The colouring principle of turmeric is:', ['Curcumin, from the rhizome', 'Crocin, from the stigma', 'Bixin, from the seed', 'Indigotin, from the leaves'], 0,
    'Crocin is the colour of saffron; bixin of annatto.'],
  ['Natural dyes are regaining importance mainly because they are:', ['Eco-friendly and non-toxic compared with many synthetic dyes', 'Cheaper than all synthetic dyes', 'Available in unlimited colours', 'Completely light-fast'], 0,
    'Mordants (e.g., alum) are used to fix them to fibres.'],
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 3, pyq: 'IFoS-2025-B1-Q5e', q: [
  ['A herbarium is:', ['A collection of pressed, dried and labelled plant specimens arranged in a system of classification', 'A garden of living medicinal plants', 'A seed bank', 'A greenhouse'], 0,
    'It is the basic reference for plant identification and naming.'],
  ['The standard size of a herbarium sheet is about:', ['41 × 29 cm', '10 × 10 cm', '1 × 1 m', '5 × 3 cm'], 0,
    'About 16.5 × 11.5 inches.'],
  ['India’s Central National Herbarium (CAL) is at:', ['Howrah, under the Botanical Survey of India', 'Dehradun', 'Lucknow', 'Chennai'], 0,
    'It is one of Asia’s oldest and largest herbaria.'],
  ['Among the largest herbaria in the world is that of:', ['The Royal Botanic Gardens, Kew', 'The Taj Mahal gardens', 'Lalbagh', 'Ooty'], 0,
    'Kew holds several million specimens, including many Indian types.'],
  ['Standard abbreviations (acronyms) for herbaria worldwide are listed in:', ['Index Herbariorum', 'Index Kewensis', 'Flora of British India', 'Species Plantarum'], 0,
    'E.g., K for Kew, CAL for the Central National Herbarium.'],
  ['A virtual herbarium is:', ['An online database of digitised specimen images and label data', 'A herbarium without specimens', 'A garden seen through video', 'A seed catalogue'], 0,
    'Examples: JSTOR Global Plants and GBIF-linked collections.'],
  ['A major advantage of virtual herbaria is that they:', ['Give worldwide access to specimens and reduce handling of fragile sheets', 'Replace the need for any physical specimens', 'Are always free of errors', 'Grow plants digitally'], 0,
    'Physical specimens remain essential for DNA and detailed study.'],
  ['A herbarium label must record at least:', ['Collector, collection number, date, locality (with GPS) and habitat', 'The price of the specimen', 'The weather forecast', 'The herbarium’s budget'], 0,
    'Label data make the specimen scientifically useful.'],
  ['Holotypes kept in herbaria are important because they:', ['Fix the application of a scientific name', 'Are used for cooking', 'Show the most common form only', 'Can be discarded after publication'], 0,
    'Type specimens anchor names under the ICN.'],
  ['Herbarium specimens are protected from insect damage today mainly by:', ['Deep-freezing and pest-monitoring, instead of toxic poisons', 'Soaking in water', 'Keeping them in sunlight', 'Storing them in soil'], 0,
    'Mercuric chloride was used earlier but is hazardous.'],
] },
{ p: 'B1', t: 'Plant Anatomy', w: 3, pyq: 'IFoS-2025-B1-Q6a', q: [
  ['*Boerhavia diffusa* belongs to the family:', ['Nyctaginaceae', 'Salvadoraceae', 'Bignoniaceae', 'Asparagaceae'], 0,
    'Punarnava, a common medicinal herb.'],
  ['The young stem of *Boerhavia* shows vascular bundles arranged in:', ['About three rings, the innermost being medullary bundles', 'A single ring', 'Scattered as in monocots', 'Only in the cortex'], 0,
    'Medullary bundles in the pith are one of its anomalies.'],
  ['Secondary growth in *Boerhavia* is anomalous because:', ['Successive (accessory) cambia form outside the normal ring, producing new rings of bundles', 'It has no cambium', 'Phloem forms inside xylem everywhere', 'It shows monocot-type growth'], 0,
    'The bundles are embedded in lignified conjunctive tissue.'],
  ['*Salvadora persica* (the toothbrush tree, miswak) grows typically in:', ['Arid and saline areas', 'Tropical rain forests', 'Alpine meadows', 'Freshwater swamps'], 0,
    'Family Salvadoraceae.'],
  ['In *Salvadora*, included (interxylary) phloem arises because:', ['The cambium periodically forms phloem towards the inside, which becomes embedded in xylem', 'The pith turns into phloem', 'Phloem migrates from the cortex', 'Xylem forms outside phloem'], 0,
    'The cambium then resumes normal activity, trapping phloem islands.'],
  ['Other plants showing included phloem are:', ['*Leptadenia* and *Strychnos*', 'Wheat and rice', '*Pinus* and *Cycas*', '*Marchantia* and *Funaria*'], 0,
    '*Combretum* is another example.'],
  ['Normal secondary growth in dicot stems involves:', ['A single cambium ring producing xylem inwards and phloem outwards', 'Several cambia producing phloem inwards', 'No cambium', 'Only primary tissues'], 0,
    'Anomalies depart from this pattern in position, activity or number of cambia.'],
  ['One suggested adaptive value of included phloem in xerophytes is:', ['Protection of phloem within hard xylem from drought and damage', 'Faster photosynthesis', 'Seed dispersal', 'Pollination'], 0,
    'In climbers, anomalous growth adds flexibility.'],
  ['Which pair is correctly matched?', ['*Boerhavia* — medullary bundles and successive cambia', '*Salvadora* — phloem wedges', '*Bignonia* — included phloem', '*Dracaena* — medullary bundles'], 0,
    '*Bignonia* has phloem wedges; *Salvadora* has included phloem; *Dracaena* has monocot secondary growth.'],
  ['Conjunctive tissue in stems with anomalous growth is:', ['The tissue formed between successive vascular rings', 'The epidermis', 'The root cap', 'The leaf mesophyll'], 0,
    'It is often lignified parenchyma or sclerenchyma.'],
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 3, pyq: 'IFoS-2025-B1-Q6b', q: [
  ['The Legume Phylogeny Working Group (2017) divided Fabaceae into:', ['Six subfamilies', 'Three subfamilies', 'Two subfamilies', 'Ten subfamilies'], 0,
    'Traditional mimosoids are now a clade within Caesalpinioideae.'],
  ['Papilionoideae (Faboideae) have:', ['Vexillary (descendingly imbricate) aestivation and diadelphous (9)+1 stamens', 'Valvate aestivation and many free stamens', 'Ascending imbricate aestivation and 10 free stamens', 'Actinomorphic flowers in heads'], 0,
    'The standard petal is outermost.'],
  ['In Caesalpinioideae (traditional sense), the corolla aestivation is:', ['Ascending imbricate, with the posterior petal innermost', 'Vexillary', 'Valvate', 'Twisted'], 0,
    'Stamens are usually 10 and free.'],
  ['Mimosoid legumes (e.g., *Acacia*, *Mimosa*) have:', ['Small actinomorphic flowers with valvate aestivation and many conspicuous stamens, in heads or spikes', 'Zygomorphic flowers with a keel', 'Diadelphous stamens', 'Ascending imbricate aestivation'], 0,
    'The showy part is the stamens rather than the petals.'],
  ['The floral formula of Papilionoideae is:', ['% ⚥ K₍₅₎ C₁₊₂₊₍₂₎ A₍₉₎₊₁ G₁', '⊕ ⚥ K₅ C₅ A∞ G₍₅₎', '% ⚥ K₅ C₅ A₁₀ G₁ (all free, ascending imbricate)', '⊕ ⚥ P₃₊₃ A₃₊₃ G₍₃₎'], 0,
    'Standard (1), wings (2), keel of two fused petals.'],
  ['In the papilionaceous corolla, the keel is formed by:', ['Fusion of the two anterior petals', 'The single posterior petal', 'The two lateral petals', 'The sepals'], 0,
    'The two lateral petals are the wings.'],
  ['The placentation in the monocarpellary ovary of Fabaceae is:', ['Marginal', 'Axile', 'Free central', 'Basal'], 0,
    'The fruit is a legume (pod) opening along both sutures.'],
  ['Which plant belongs to the traditional Caesalpinioideae?', ['*Tamarindus indica*', '*Acacia nilotica*', '*Cicer arietinum*', '*Mimosa pudica*'], 0,
    'Also *Cassia*, *Bauhinia*, *Saraca*; *Acacia* and *Mimosa* are mimosoids; *Cicer* is papilionoid.'],
  ['A characteristic of most Papilionoideae of agricultural importance is:', ['Root nodules with nitrogen-fixing rhizobia', 'Parasitic habit', 'Absence of fruits', 'Aquatic habit'], 0,
    'Pulses, fodder legumes and green manures belong here.'],
  ['Which is a papilionoid legume used for timber?', ['*Dalbergia sissoo*', '*Tamarindus indica*', '*Acacia catechu*', '*Albizia lebbeck*'], 0,
    'Rosewood (*D. latifolia*) and *Pterocarpus* are also papilionoid timbers.'],
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 3, pyq: 'IFoS-2025-B1-Q6c', q: [
  ['The edible fig (*Ficus carica*) inflorescence is a:', ['Syconium (hypanthodium)', 'Capitulum', 'Umbel', 'Spadix'], 0,
    'Tiny flowers line the inside of a hollow receptacle.'],
  ['Figs are pollinated by:', ['Fig wasps (e.g., *Blastophaga psenes*)', 'Bats', 'Wind', 'Water'], 0,
    'An obligate mutualism; caprification uses wild caprifigs to supply wasps.'],
  ['The main stimulant alkaloid in tea is:', ['Caffeine (theine)', 'Nicotine', 'Morphine', 'Quinine'], 0,
    'Tea also contains theobromine and theophylline in small amounts.'],
  ['Black tea differs from green tea in that its leaves are:', ['Withered, rolled and oxidised ("fermented") to form theaflavins and thearubigins', 'Steamed immediately to stop oxidation', 'Never dried', 'Roasted like coffee beans'], 0,
    'Green tea keeps catechins because enzymes are inactivated early.'],
  ['CTC tea refers to leaves processed by:', ['Crush, tear, curl', 'Cut, toast, cool', 'Clean, treat, cure', 'Crop, tie, carry'], 0,
    'Gives strong, quick-brewing tea, common in Assam.'],
  ['Palm oil is extracted from the ___ of *Elaeis guineensis*.', ['Fleshy mesocarp', 'Kernel only', 'Leaves', 'Trunk'], 0,
    'Palm kernel oil comes from the kernel (endosperm).'],
  ['The high-yielding "tenera" oil palm is a hybrid of:', ['Dura × Pisifera', 'Dura × Dura', 'Pisifera × Pisifera', 'Coconut × oil palm'], 0,
    'Tenera fruits have a thin shell and thick mesocarp.'],
  ['India’s National Mission on Edible Oils – Oil Palm (2021) focuses especially on:', ['The North-East and the Andaman and Nicobar Islands', 'Punjab and Haryana', 'Rajasthan only', 'Ladakh'], 0,
    'It aims to cut edible-oil imports.'],
  ['Cloves are the dried ___ of *Syzygium aromaticum*.', ['Unopened flower buds', 'Fruits', 'Seeds', 'Bark'], 0,
    'Family Myrtaceae; the main aromatic compound is eugenol.'],
  ['Oats (*Avena sativa*) are valued nutritionally for their:', ['Soluble fibre (β-glucan), which helps lower cholesterol', 'Very high gluten', 'Caffeine', 'Vitamin B12'], 0,
    'Oats are also grown widely as winter fodder in India.'],
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 3, pyq: 'IFoS-2025-B1-Q7a', q: [
  ['The term "ethnobotany" was coined by:', ['J.W. Harshberger (1896)', 'Linnaeus (1753)', 'Darwin (1859)', 'Vavilov (1926)'], 0,
    'It studies the relationship between people and plants.'],
  ['The father of Indian ethnobotany is:', ['S.K. Jain', 'P. Maheshwari', 'Birbal Sahni', 'M.S. Swaminathan'], 0,
    'He led early systematic ethnobotanical surveys in tribal India.'],
  ['The Traditional Knowledge Digital Library (TKDL) was set up to:', ['Prevent wrongful patents on traditional knowledge (biopiracy)', 'Sell herbal products', 'Train tribal healers', 'Store seeds'], 0,
    'A CSIR–AYUSH database shared with patent offices.'],
  ['A US patent on the wound-healing use of turmeric was revoked in 1997 because:', ['It was shown to be prior traditional knowledge in India', 'Turmeric is toxic', 'It was never used', 'It was a synthetic drug'], 0,
    'Neem-based patents were also challenged successfully.'],
  ['The Kani tribe benefit-sharing model is linked to the plant:', ['*Trichopus zeylanicus* (arogyapacha), used for the drug Jeevani', '*Rauvolfia serpentina*', '*Taxus wallichiana*', '*Catharanthus roseus*'], 0,
    'Developed by TBGRI (Kerala); a pioneering access-and-benefit-sharing case.'],
  ['Mahua (*Madhuca longifolia*) is important to tribal communities for:', ['Edible flowers, fermented drink and seed fat', 'Rubber latex', 'Timber only', 'Dye only'], 0,
    'A key non-timber forest product in central India.'],
  ['People’s Biodiversity Registers help ethnobotany by:', ['Documenting local knowledge of plants and their uses', 'Registering land ownership', 'Recording rainfall', 'Listing only timber trees'], 0,
    'Prepared by Biodiversity Management Committees under the Biological Diversity Act.'],
  ['Access and benefit sharing for genetic resources and traditional knowledge is governed internationally by the:', ['Nagoya Protocol', 'Kyoto Protocol', 'Montreal Protocol', 'Cartagena Protocol'], 0,
    'In India through the Biological Diversity Act, 2002.'],
  ['India’s national research project that expanded ethnobotanical surveys in the 1980s was the:', ['All India Coordinated Research Project on Ethnobiology', 'National Agricultural Technology Project', 'Green India Mission', 'Project Tiger'], 0,
    'Coordinated through the Ministry of Environment.'],
  ['Ethnobotany helps drug discovery mainly by:', ['Pointing to plants with a long history of traditional use for screening', 'Replacing clinical trials', 'Providing synthetic chemicals', 'Studying only crops'], 0,
    'E.g., reserpine from *Rauvolfia*, used in folk medicine for centuries.'],
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 3, pyq: 'IFoS-2025-B1-Q8a', q: [
  ['The oldest botanical garden still at its original site is at:', ['Padua, Italy (1545)', 'Kew, England (1759)', 'Howrah, India (1787)', 'Lalbagh, Bengaluru (1760)'], 0,
    'The Orto Botanico di Padova is a UNESCO World Heritage Site.'],
  ['The Acharya Jagadish Chandra Bose Indian Botanic Garden at Howrah was founded in 1787 by:', ['Robert Kyd', 'William Roxburgh', 'Joseph Hooker', 'Nathaniel Wallich'], 0,
    'It is famous for the Great Banyan tree.'],
  ['Lalbagh botanical garden in Bengaluru was begun by:', ['Hyder Ali (1760)', 'Robert Kyd', 'The Wodeyars in 1900', 'Lord Curzon'], 0,
    'Tipu Sultan expanded it.'],
  ['The Millennium Seed Bank, among the largest wild-plant seed banks, is run by:', ['Royal Botanic Gardens, Kew (at Wakehurst)', 'The Svalbard government', 'NBPGR', 'FAO'], 0,
    'Svalbard stores back-up seeds of crops, not mainly wild plants.'],
  ['A primary conservation role of botanical gardens is:', ['Ex-situ conservation of living plants, especially threatened species', 'Timber production', 'Crop insurance', 'Mining'], 0,
    'They also do research, education, seed banking and reintroduction.'],
  ['The Global Strategy for Plant Conservation (2011–2020) aimed to keep at least ___ of threatened plant species in ex-situ collections.', ['75%', '10%', '25%', '100%'], 0,
    'Preferably in the country of origin, with 20% available for recovery programmes.'],
  ['The international network that links botanical gardens for conservation is:', ['Botanic Gardens Conservation International (BGCI)', 'IUCN Red List', 'CITES', 'Ramsar'], 0,
    'It supports the Global Strategy for Plant Conservation.'],
  ['The Botanic Garden of the Indian Republic, set up by BSI in 2002, is at:', ['Noida', 'Shillong', 'Ooty', 'Port Blair'], 0,
    'It focuses on ex-situ conservation of Indian flora.'],
  ['Botanical gardens support education mainly through:', ['Labelled living collections, theme gardens and public programmes', 'Selling timber', 'Only research papers', 'Closed collections'], 0,
    'An "ideal" garden combines conservation, research and public awareness.'],
  ['Reintroduction programmes run by botanical gardens involve:', ['Returning propagated threatened plants to suitable wild habitats', 'Introducing invasive species', 'Removing native plants', 'Planting only exotics'], 0,
    'Tissue culture and seed banking provide the planting material.'],
] }
);
