/* PYQ-linked MCQs — IFoS 2017 Botany Paper I, Q1–Q4 (verbatim PYQs). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Microbiology', w: 2, pyq: 'IFoS-2017-B1-Q1a', q: [
  ['A nucleus enclosed by a nuclear envelope is found in:', ['Eukaryotes only', 'Prokaryotes only', 'Both', 'Neither'], 0,
    'Prokaryotic DNA lies in an unbounded nucleoid.'],
  ['Cytoplasmic ribosomes are:', ['70S in prokaryotes and 80S in eukaryotes', '80S in prokaryotes and 70S in eukaryotes', '70S in both', '80S in both'], 0,
    'Mitochondria and chloroplasts also have 70S ribosomes.'],
  ['The bacterial chromosome is usually:', ['A single circular DNA molecule, not wrapped in histones', 'Several linear chromosomes with histones', 'RNA', 'Enclosed in a nucleus'], 0,
    'Bacteria often carry extra small circular plasmids.'],
  ['Membrane-bound organelles such as mitochondria, ER and Golgi bodies are:', ['Absent in prokaryotes', 'Present in prokaryotes', 'Absent in eukaryotes', 'Found only in viruses'], 0,
    'Some bacteria have internal membranes, but not true organelles.'],
  ['Prokaryotes usually divide by:', ['Binary fission', 'Mitosis', 'Meiosis', 'Budding only'], 0,
    'Eukaryotes use mitosis and meiosis.'],
  ['A bacterial flagellum differs from a eukaryotic one in being:', ['A rotating protein (flagellin) filament, not a 9+2 microtubule structure', 'Made of 9+2 microtubules', 'Made of actin', 'Enclosed in the membrane'], 0,
    'Eukaryotic flagella beat by bending, not rotating.'],
  ['In prokaryotes, transcription and translation are:', ['Coupled — ribosomes translate mRNA while it is still being made', 'Separated by the nuclear envelope', 'Carried out in mitochondria', 'Not needed'], 0,
    'In eukaryotes, mRNA is processed in the nucleus first.'],
  ['Sterols in the cell membrane are typical of:', ['Eukaryotes', 'Most bacteria', 'Archaea', 'Viruses'], 0,
    '*Mycoplasma* is an exception: it takes up sterols from its host.'],
  ['Typical prokaryotic cells measure about:', ['1–10 µm', '10–100 µm', '1 mm', '10 nm'], 0,
    'Most eukaryotic cells are 10–100 µm.'],
  ['Prokaryotes have homologues of cytoskeletal proteins, such as:', ['FtsZ (tubulin-like) and MreB (actin-like)', 'Myosin only', 'Keratin', 'Histone H1'], 0,
    'FtsZ forms the ring at the site of cell division.']
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 2, pyq: 'IFoS-2017-B1-Q1b', q: [
  ['Aflatoxins are produced mainly by:', ['*Aspergillus flavus* and *A. parasiticus*', '*Penicillium chrysogenum*', '*Claviceps purpurea*', '*Fusarium graminearum*'], 0,
    'The name comes from "*A. fla*vus toxin".'],
  ['Crops most often contaminated with aflatoxin include:', ['Groundnut, maize, cottonseed and chillies', 'Tea and coffee only', 'Apples only', 'Leafy vegetables'], 0,
    'Warm, humid storage favours the fungus.'],
  ['The most toxic and commonest aflatoxin is:', ['Aflatoxin B₁', 'Aflatoxin G₂', 'Aflatoxin M₂', 'Patulin'], 0,
    'It is a Group 1 human carcinogen (IARC).'],
  ['Aflatoxin B₁ mainly damages the:', ['Liver, causing liver cancer', 'Skin only', 'Bones', 'Eyes'], 0,
    'Its epoxide binds to DNA and causes mutations.'],
  ['Aflatoxin M₁ is found in:', ['Milk of animals fed contaminated feed', 'Rice straw', 'Water', 'Soil only'], 0,
    'It is a hydroxylated product of B₁.'],
  ['Aflatoxins were discovered after the 1960 outbreak of:', ['"Turkey X" disease in England, from contaminated groundnut meal', 'Ergotism in France', 'The Irish potato famine', 'The Bengal famine'], 0,
    'About 100,000 turkeys died.'],
  ['The letters B and G in aflatoxin names come from their:', ['Blue and green fluorescence under UV light', 'Bacterial and fungal origin', 'Bitter and green taste', 'Discoverers’ names'], 0,
    'UV fluorescence is used to screen for contamination.'],
  ['In groundnut, aflatoxin contamination in the field is favoured by:', ['Drought stress at pod filling and damage to pods', 'Heavy irrigation', 'Cold weather', 'Early harvest of dry pods'], 0,
    'Stressed pods are more easily invaded.'],
  ['A key storage practice against aflatoxin is:', ['Drying produce quickly to safe moisture and storing it dry', 'Storing it moist in sealed bags', 'Adding water before storage', 'Storing it in warm, humid rooms'], 0,
    'Groundnut kernels are best kept below about 8% moisture.'],
  ['Biological control of aflatoxin in the field uses:', ['Non-toxigenic (atoxigenic) strains of *A. flavus* to outcompete toxic strains', '*Trichogramma*', 'Bt toxins', 'Mycorrhizal fungi'], 0,
    'Products such as Aflasafe are used in Africa.']
] },
{ p: 'B1', t: 'Algae', w: 2, pyq: 'IFoS-2017-B1-Q1c', q: [
  ['Red algae appear red because phycoerythrin:', ['Absorbs blue-green light and reflects red light', 'Absorbs red light', 'Reflects green light', 'Absorbs no light'], 0,
    'Its colour masks the green of chlorophyll *a*.'],
  ['Phycobilins are:', ['Open-chain tetrapyrroles bound to proteins (phycobiliproteins)', 'Carotenoids', 'Porphyrins with magnesium', 'Flavonoids'], 0,
    'Chlorophyll is a closed tetrapyrrole ring.'],
  ['In red algae, phycobilisomes are attached to:', ['The outer (stromal) surface of the thylakoids', 'The cell wall', 'The nucleus', 'The pyrenoid only'], 0,
    'They pass energy to photosystem II.'],
  ['Within a phycobilisome, energy flows in the order:', ['Phycoerythrin → phycocyanin → allophycocyanin → chlorophyll *a*', 'Chlorophyll *a* → phycoerythrin', 'Allophycocyanin → phycoerythrin', 'Carotene → phycocyanin'], 0,
    'Each pigment absorbs at a longer wavelength than the one before.'],
  ['Red algae growing in deep water usually have:', ['A higher ratio of phycoerythrin to chlorophyll', 'No phycoerythrin', 'More chlorophyll *b*', 'Only carotenoids'], 0,
    'Only blue-green light reaches such depths.'],
  ['The chlorophyll found in red algae is:', ['Chlorophyll *a* only', 'Chlorophylls *a* and *b*', 'Chlorophylls *a* and *c*', 'Bacteriochlorophyll'], 0,
    'Chlorophyll *d* was once reported but is now linked to cyanobacteria.'],
  ['The carotenoids of red algae include:', ['β-carotene, lutein and zeaxanthin', 'Fucoxanthin', 'Peridinin', 'Siphonaxanthin'], 0,
    'Fucoxanthin belongs to brown algae and diatoms.'],
  ['The freshwater red alga *Batrachospermum* often looks bluish or olive-green because it:', ['Has relatively more phycocyanin', 'Lacks chlorophyll', 'Has fucoxanthin', 'Has no phycobilins'], 0,
    'Not all red algae look red.'],
  ['Phycoerythrin from red algae is used in laboratories as:', ['A fluorescent label in flow cytometry and immunoassays', 'A food thickener', 'A fertiliser', 'An antibiotic'], 0,
    'It fluoresces brightly and is water-soluble.'],
  ['The pigments of red algal plastids, similar to those of cyanobacteria, support the view that red algae:', ['Arose from primary endosymbiosis of a cyanobacterium', 'Arose from brown algae', 'Are fungi', 'Have no plastids'], 0,
    'Red algae, green algae and glaucophytes form the Archaeplastida.']
] },
{ p: 'B1', t: 'Microbiology', w: 3, pyq: 'IFoS-2017-B1-Q1d', q: [
  ['Ammonification is:', ['The release of ammonia from organic nitrogen by decomposers', 'The oxidation of ammonia to nitrate', 'The reduction of nitrate to N₂', 'The fixation of N₂'], 0,
    '*Bacillus*, *Clostridium*, *Pseudomonas*, actinomycetes and fungi all do it.'],
  ['The first step of nitrification, ammonium to nitrite, is carried out by:', ['*Nitrosomonas* (and *Nitrosococcus*, *Nitrosospira*)', '*Nitrobacter*', '*Rhizobium*', '*Pseudomonas denitrificans*'], 0,
    'NH₄⁺ → NO₂⁻.'],
  ['The second step of nitrification, nitrite to nitrate, is carried out by:', ['*Nitrobacter* (and *Nitrospira*)', '*Nitrosomonas*', '*Azotobacter*', '*Clostridium*'], 0,
    'NO₂⁻ → NO₃⁻.'],
  ['Nitrifying bacteria are:', ['Aerobic chemoautotrophs', 'Anaerobic heterotrophs', 'Photosynthetic', 'Parasites'], 0,
    'They get energy by oxidising nitrogen compounds and fix CO₂.'],
  ['Denitrification is:', ['The reduction of nitrate to N₂ or N₂O under low-oxygen conditions', 'The oxidation of ammonium', 'N₂ fixation', 'Mineralisation of organic N'], 0,
    'It is a major cause of nitrogen loss from waterlogged soils.'],
  ['A bacterium well known for denitrification is:', ['*Pseudomonas denitrificans* (also *Thiobacillus denitrificans*, *Paracoccus*)', '*Nitrosomonas*', '*Rhizobium leguminosarum*', '*Azospirillum*'], 0,
    'They use nitrate instead of oxygen for respiration.'],
  ['Denitrification is favoured by:', ['Waterlogging, low oxygen and plenty of organic carbon', 'Well-aerated dry soils', 'Low organic matter and high oxygen', 'Freezing'], 0,
    'Flooded rice fields lose nitrogen this way.'],
  ['Nitrification inhibitors include:', ['Nitrapyrin, DCD and neem-based products', 'Urea', 'Gypsum', 'Lime'], 0,
    'Slowing nitrification keeps N as ammonium, which leaches less.'],
  ['Anammox bacteria (Planctomycetes such as *Brocadia*) convert:', ['Ammonium and nitrite directly to N₂ without oxygen', 'N₂ to ammonia', 'Nitrate to ammonium', 'Organic N to ammonia'], 0,
    'Anammox means anaerobic ammonium oxidation.'],
  ['"Comammox" *Nitrospira*, discovered in 2015, can:', ['Oxidise ammonia all the way to nitrate in one organism', 'Fix nitrogen', 'Denitrify', 'Make ammonia from nitrate'], 0,
    'It changed the old view that two separate groups are always needed.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, pyq: 'IFoS-2017-B1-Q1e', q: [
  ['The pollen grain of *Pinus* has:', ['Two air sacs (wings) that aid wind dispersal', 'No exine', 'Spines for insect dispersal', 'A single large pore'], 0,
    'The sacci make the grain buoyant.'],
  ['The first division of the *Pinus* microspore gives:', ['A small first prothallial cell and a large embryonal cell', 'Two equal cells', 'A tube cell and sperms', 'Four cells'], 0,
    'The prothallial cell is pressed against the wall.'],
  ['The second division of the embryonal cell gives:', ['A second prothallial cell and an antheridial cell', 'Two sperms', 'A tube cell and a stalk cell', 'A body cell only'], 0,
    'The two prothallial cells soon degenerate.'],
  ['At the time of pollination, the *Pinus* pollen grain is:', ['Four-celled — two prothallial cells, a generative (antheridial) cell and a tube cell', 'One-celled', 'Two-celled', 'Eight-celled'], 0,
    'It is shed at this stage.'],
  ['The generative (antheridial) cell of *Pinus* divides to form:', ['A stalk cell and a body cell', 'Two sperms directly', 'Two tube cells', 'Two prothallial cells'], 0,
    'This happens in the pollen chamber.'],
  ['The body cell of *Pinus* finally forms:', ['Two non-motile male gametes of unequal size', 'Many motile sperms', 'One motile sperm', 'A tube nucleus'], 0,
    'Only one gamete fertilises the egg.'],
  ['The prothallial cells of *Pinus* pollen represent:', ['The vestigial vegetative tissue of the male gametophyte', 'Male gametes', 'Food storage cells of the ovule', 'Parts of the sporophyte'], 0,
    'Angiosperm pollen has lost them completely.'],
  ['The *Pinus* pollen tube carries non-motile gametes to the egg. This is called:', ['Siphonogamy', 'Zoidogamy', 'Apogamy', 'Oogamy only'], 0,
    'In *Cycas*, the pollen tube is haustorial and releases motile sperms.'],
  ['Microsporangia in the *Pinus* male cone are:', ['Two, on the lower (abaxial) surface of each microsporophyll', 'Many, on the upper surface', 'One, at the tip', 'Absent'], 0,
    'Male cones form in clusters at the base of new shoots.'],
  ['The interval between pollination and fertilisation in *Pinus* is about:', ['One year', 'One day', 'One week', 'Five years'], 0,
    'The pollen tube grows slowly through the nucellus.']
] },
{ p: 'B1', t: 'Algae', w: 2, pyq: 'IFoS-2017-B1-Q2a', q: [
  ['Primary endosymbiosis of a cyanobacterium gave rise to the plastids of:', ['Glaucophytes, red algae and green algae (with land plants) — the Archaeplastida', 'Brown algae only', 'Diatoms only', 'Dinoflagellates only'], 0,
    'These plastids have two envelope membranes.'],
  ['Glaucophytes such as *Cyanophora* are important in algal phylogeny because their plastids (cyanelles):', ['Still have a peptidoglycan wall, like cyanobacteria', 'Have four membranes', 'Lack chlorophyll', 'Contain fucoxanthin'], 0,
    'This is a clear relic of their bacterial ancestry.'],
  ['Brown algae and diatoms obtained their plastids by:', ['Secondary endosymbiosis of a red alga', 'Primary endosymbiosis', 'Engulfing a green alga', 'Engulfing a fungus'], 0,
    'Their plastids have four membranes.'],
  ['Euglenoids and chlorarachniophytes obtained their plastids by:', ['Secondary endosymbiosis of a green alga', 'Secondary endosymbiosis of a red alga', 'Primary endosymbiosis', 'Tertiary endosymbiosis of diatoms'], 0,
    'Euglenoid plastids have three membranes.'],
  ['A nucleomorph — a remnant nucleus of an engulfed alga — is found in:', ['Cryptophytes and chlorarachniophytes', 'Red algae', 'Green algae', 'Cyanobacteria'], 0,
    'It is the strongest evidence for secondary endosymbiosis.'],
  ['Phylogenomic studies show that land plants evolved from:', ['Charophyte green algae, with the Zygnematophyceae as their closest relatives', 'Red algae', 'Brown algae', 'Diatoms'], 0,
    '*Chara* and *Coleochaete* were long seen as close relatives.'],
  ['Algae fall into three broad pigment lines. These are:', ['Chlorophyll *a*+*b* (green), *a*+*c* (brown/chromist) and *a*+phycobilins (red)', 'Only one line', 'Chlorophyll *b*+*c* and *d*', 'Carotene only'], 0,
    'Pigments reflect the origin of each group’s plastid.'],
  ['F. E. Fritsch classified algae into eleven classes mainly on the basis of:', ['Pigments, reserve food and flagellation', 'Habitat only', 'Cell size', 'Economic use'], 0,
    'This was set out in *The Structure and Reproduction of the Algae* (1935, 1945).'],
  ['Blue-green algae are now classified as:', ['Bacteria (Cyanobacteria)', 'Green algae', 'Red algae', 'Fungi'], 0,
    'They are prokaryotes.'],
  ['Some dinoflagellates, such as *Karenia*, gained their plastids by:', ['Tertiary endosymbiosis of a haptophyte', 'Primary endosymbiosis', 'Engulfing a cyanobacterium directly', 'Horizontal gene transfer from fungi'], 0,
    'Dinoflagellates have repeatedly swapped plastids.']
] },
{ p: 'B1', t: 'Bryophytes', w: 3, pyq: 'IFoS-2017-B1-Q2b', q: [
  ['The first division of a bryophyte zygote is:', ['Transverse, giving an epibasal and a hypobasal cell', 'Longitudinal', 'Free-nuclear', 'Meiotic'], 0,
    'The two cells go on to form different parts of the sporophyte.'],
  ['In *Marchantia*, the hypobasal cell gives rise to:', ['The foot and seta', 'The capsule', 'The calyptra', 'The spores'], 0,
    'The epibasal cell forms the capsule.'],
  ['In *Riccia*, the embryo develops into:', ['Only a capsule, with no foot or seta', 'Foot, seta and capsule', 'A protonema', 'A gemma'], 0,
    'Only its outer layer stays sterile, as the capsule wall.'],
  ['In *Anthoceros*, the archesporium arises from the:', ['Amphithecium', 'Endothecium', 'Foot', 'Seta'], 0,
    'The endothecium forms the columella — unusual among bryophytes.'],
  ['In *Funaria*, the endothecium gives rise to:', ['The archesporium and the columella', 'The capsule wall only', 'The peristome', 'The foot'], 0,
    'The amphithecium forms the wall layers and peristome.'],
  ['The young *Funaria* sporophyte grows by means of:', ['An apical cell with two cutting faces', 'A basal meristem', 'A cambium', 'Free nuclear division'], 0,
    'Growth later becomes intercalary.'],
  ['The calyptra covering a young moss capsule is derived from the:', ['Venter of the archegonium (gametophyte tissue)', 'Sporophyte foot', 'Seta', 'Protonema'], 0,
    'It is torn off and carried up as the seta elongates.'],
  ['The apophysis of the *Funaria* capsule is:', ['Photosynthetic and bears stomata', 'Where spores form', 'The foot', 'The peristome'], 0,
    'It makes the sporophyte partly self-supporting.'],
  ['The bryophyte sporophyte is:', ['Dependent on the gametophyte, at least partly', 'Always free-living', 'The dominant generation', 'Haploid'], 0,
    'The *Anthoceros* sporophyte is green and the most independent.'],
  ['The spores of bryophytes are formed by:', ['Meiosis of spore mother cells into tetrads', 'Mitosis of gametophyte cells', 'Fusion of gametes', 'Budding'], 0,
    'They are haploid and grow into the gametophyte.']
] },
{ p: 'B1', t: 'Plant Pathology', w: 3, pyq: 'IFoS-2017-B1-Q2c', q: [
  ['The gene-for-gene hypothesis was proposed by:', ['H. H. Flor, working on flax rust (*Melampsora lini*)', 'Van der Plank', 'Stakman', 'Jones and Dangl'], 0,
    'For each host resistance gene there is a matching pathogen avirulence gene.'],
  ['Pathogen-associated molecular patterns (PAMPs), such as bacterial flagellin, are recognised by:', ['Pattern-recognition receptors (PRRs) such as FLS2', 'NLR resistance proteins inside the cell', 'Ribosomes', 'Chloroplasts'], 0,
    'This triggers PAMP-triggered immunity (PTI).'],
  ['Pathogen effectors that suppress PTI are recognised by:', ['Intracellular NB-LRR (NLR) resistance proteins, triggering effector-triggered immunity', 'Cell-wall cellulose', 'Stomata', 'Auxin receptors'], 0,
    'ETI is stronger and often ends in a hypersensitive response.'],
  ['The "zigzag model" of plant immunity was proposed by:', ['Jones and Dangl (2006)', 'Flor', 'Van der Plank', 'Kuć'], 0,
    'It describes PTI, effector-triggered susceptibility and ETI.'],
  ['The guard hypothesis states that a resistance protein:', ['Monitors a host target of the effector and responds when it is modified', 'Binds the effector directly always', 'Makes the pathogen’s effectors', 'Blocks stomata'], 0,
    'RIN4, guarded by RPS2 and RPM1, is the classic example.'],
  ['Bacterial pathogens inject effectors into plant cells through the:', ['Type III secretion system, encoded by *hrp* genes', 'Flagellum', 'Cell wall pores', 'Plasmodesmata'], 0,
    '*Pseudomonas syringae* and *Xanthomonas* use it.'],
  ['TAL effectors of *Xanthomonas* cause disease by:', ['Binding host promoters and switching on susceptibility genes such as SWEET sugar transporters', 'Degrading cell walls', 'Producing toxins only', 'Blocking xylem'], 0,
    'Rice resistance genes such as *xa13* work by altering these promoters.'],
  ['The hypersensitive response (HR) is:', ['Rapid, localised death of cells around the infection site, which confines the pathogen', 'Wilting of the whole plant', 'Increased growth', 'Leaf yellowing only'], 0,
    'It is especially effective against biotrophs.'],
  ['The first plant resistance gene to be cloned (1992) was:', ['*Hm1* of maize, which detoxifies HC-toxin', '*Pto* of tomato', '*Xa21* of rice', '*Mla* of barley'], 0,
    '*Pto* (1993) was the first cloned R gene against a bacterium.'],
  ['Many fungal pathogens enter host tissue using:', ['Appressoria and cell-wall-degrading enzymes', 'Stomatal closure', 'Photosynthesis', 'Root nodules'], 0,
    'The rice blast fungus builds high turgor in its appressorium.']
] },
{ p: 'B1', t: 'Microbiology', w: 2, pyq: 'IFoS-2017-B1-Q2d', q: [
  ['Most antibiotics in clinical use are produced by bacteria of the genus:', ['*Streptomyces*', '*Escherichia*', '*Lactobacillus*', '*Rhizobium*'], 0,
    'Examples include tetracycline and chloramphenicol.'],
  ['The antibiotics bacitracin and polymyxin come from:', ['*Bacillus* species', '*Streptomyces* only', 'Fungi', 'Algae'], 0,
    'They act on bacterial walls and membranes.'],
  ['Vitamin B₁₂ is produced commercially by fermentation with:', ['*Pseudomonas denitrificans* and *Propionibacterium*', 'Yeast', '*Aspergillus niger*', 'Plants'], 0,
    'Only bacteria and archaea can make vitamin B₁₂.'],
  ['Phosphate-solubilising bacteria used as biofertilisers include:', ['*Bacillus megaterium* var. *phosphaticum* and *Pseudomonas striata*', '*Nitrosomonas*', '*Clostridium tetani*', '*Salmonella*'], 0,
    'They release bound phosphate with organic acids.'],
  ['Free-living nitrogen-fixing bacteria used as biofertilisers include:', ['*Azotobacter* and *Azospirillum*', '*Nitrobacter*', '*Lactobacillus*', '*Streptococcus*'], 0,
    '*Rhizobium* is the symbiotic nitrogen fixer of legumes.'],
  ['The bacterium used to transfer genes into plants is:', ['*Agrobacterium tumefaciens*', '*Escherichia coli*', '*Bacillus subtilis*', '*Streptomyces*'], 0,
    'Its Ti plasmid carries T-DNA into the plant genome.'],
  ['Lactic acid is produced industrially by:', ['*Lactobacillus delbrueckii*', '*Acetobacter aceti*', '*Clostridium acetobutylicum*', '*Corynebacterium*'], 0,
    'It is used in foods and to make biodegradable plastic (PLA).'],
  ['Vinegar (acetic acid) is made from alcohol by:', ['*Acetobacter aceti*', '*Lactobacillus*', '*Saccharomyces*', '*Streptomyces*'], 0,
    'Ethanol is oxidised to acetic acid.'],
  ['Glutamic acid for monosodium glutamate (MSG) is produced by:', ['*Corynebacterium glutamicum*', '*Escherichia coli*', '*Bacillus thuringiensis*', '*Rhizobium*'], 0,
    'It also makes lysine for animal feed.'],
  ['Taq polymerase, essential for PCR, comes from:', ['*Thermus aquaticus*', '*Escherichia coli*', '*Bacillus subtilis*', '*Agrobacterium*'], 0,
    'It stays stable at the high temperatures used in PCR.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 3, pyq: 'IFoS-2017-B1-Q3a', q: [
  ['Simple polyembryony in gymnosperms results from:', ['Fertilisation of several archegonia, each forming an embryo', 'Splitting of one proembryo', 'Nucellar budding', 'Synergid embryos'], 0,
    'It occurs in both *Cycas* and *Pinus*.'],
  ['Cleavage polyembryony results from:', ['One zygote whose proembryo splits into several embryos', 'Several archegonia being fertilised', 'Fusion of embryos', 'Apomixis'], 0,
    'The embryos from one zygote are genetically identical.'],
  ['In *Pinus*, cleavage polyembryony happens when:', ['The four cells of the embryonal tier separate, each forming an embryo', 'The rosette tier forms seeds', 'The suspensor dies', 'Pollen fuses'], 0,
    'So one zygote can give four embryos.'],
  ['The *Pinus* proembryo consists of:', ['Sixteen cells in four tiers of four', 'Two cells', 'Hundreds of free nuclei', 'One large cell'], 0,
    'The tiers are: open, rosette, suspensor and embryonal.'],
  ['A major difference between *Cycas* and *Pinus* embryogeny is that in *Cycas*:', ['There is a long free-nuclear phase with hundreds of nuclei before walls form', 'Only four free nuclei form', 'There is no suspensor', 'The embryo has many cotyledons'], 0,
    'In *Pinus* only four free nuclei form before walls appear.'],
  ['The suspensor in gymnosperm embryos:', ['Elongates and pushes the embryo into the nutritive female gametophyte', 'Forms the root', 'Becomes the seed coat', 'Makes pollen'], 0,
    'It is very long and coiled in *Pinus*.'],
  ['In a mature *Pinus* or *Cycas* seed, usually:', ['Only one embryo survives, the others aborting', 'All embryos survive', 'No embryo survives', 'Two embryos always survive'], 0,
    'Competition among embryos leaves one winner.'],
  ['The embryo of *Cycas* has:', ['Two cotyledons', 'Many cotyledons', 'No cotyledons', 'One cotyledon'], 0,
    '*Pinus* embryos have several cotyledons (polycotyledonous).'],
  ['The nutritive tissue for the gymnosperm embryo is the:', ['Haploid female gametophyte ("endosperm")', 'Triploid endosperm', 'Nucellus only', 'Integument'], 0,
    'It forms before fertilisation, unlike angiosperm endosperm.'],
  ['"Rosette embryos" in *Pinus* sometimes develop from:', ['The rosette tier of the proembryo', 'The pollen tube', 'The nucellus', 'The integument'], 0,
    'They usually abort.']
] },
{ p: 'B1', t: 'Pteridophytes', w: 2, pyq: 'IFoS-2017-B1-Q3b', q: [
  ['The sporophyte of *Psilotum* has:', ['No true roots — a rhizome with rhizoids and dichotomously branched aerial stems', 'True roots and large leaves', 'A single unbranched stem with megaphylls', 'Cones like *Equisetum*'], 0,
    'It is called the "whisk fern".'],
  ['The "leaves" of *Psilotum* are:', ['Small scale-like enations without a vascular supply', 'Large compound fronds', 'Needles', 'Absent altogether'], 0,
    'In *Tmesipteris* the leaves have a single vein.'],
  ['The aerial stem of *Psilotum* has:', ['A protostele (actinostele) with exarch xylem', 'A dictyostele', 'A eustele', 'Scattered bundles'], 0,
    'The rhizome has a simpler protostele.'],
  ['The sporangia of *Psilotum* are:', ['Fused in threes to form a trilocular synangium', 'Single and free', 'Borne in cones', 'Inside sori under leaves'], 0,
    'The synangia sit on short lateral branches.'],
  ['*Psilotum* is:', ['Homosporous', 'Heterosporous', 'Seed-bearing', 'Without spores'], 0,
    'It produces a single kind of spore.'],
  ['The gametophyte of *Psilotum* is:', ['Subterranean, non-green, branched and dependent on mycorrhizal fungi', 'Green and heart-shaped', 'Reduced inside the spore', 'Aquatic'], 0,
    'Some polyploid forms even have tracheids in the gametophyte.'],
  ['The antherozoids of *Psilotum* are:', ['Multiflagellate', 'Biflagellate', 'Non-motile', 'Amoeboid'], 0,
    'Water is needed for fertilisation.'],
  ['*Psilotum* was once treated as a living relative of:', ['*Rhynia* and the Psilophytales', 'Mosses', 'Seed ferns', 'Cycads'], 0,
    'Its simple, rootless body looked like that of early land plants.'],
  ['Molecular phylogeny now places Psilotaceae:', ['Among the ferns, as sister to Ophioglossaceae', 'With the lycopods', 'With the mosses', 'With the gymnosperms'], 0,
    'Its simple body is now seen as a reduction, not a primitive state.'],
  ['The other living genus of Psilotaceae is:', ['*Tmesipteris*', '*Lycopodium*', '*Equisetum*', '*Isoetes*'], 0,
    'It grows as an epiphyte, mainly in Australasia.']
] },
{ p: 'B1', t: 'Microbiology', w: 2, pyq: 'IFoS-2017-B1-Q3c', q: [
  ['Transduction is the transfer of bacterial DNA from one cell to another by:', ['A bacteriophage', 'Direct cell contact', 'Uptake of free DNA', 'Plasmid replication only'], 0,
    'Conjugation needs cell contact; transformation uses free DNA.'],
  ['Transduction was discovered in *Salmonella* (phage P22) by:', ['Zinder and Lederberg (1952)', 'Griffith', 'Avery, MacLeod and McCarty', 'Hershey and Chase'], 0,
    'Lederberg and Tatum had discovered conjugation in 1946.'],
  ['In generalised transduction:', ['Any bacterial gene can be carried, because the phage packages random host DNA', 'Only genes next to the prophage are carried', 'No DNA is carried', 'Only plasmids are carried'], 0,
    'Phages P1 and P22 are generalised transducers.'],
  ['In specialised (restricted) transduction:', ['Only genes near the prophage insertion site are carried', 'Any gene can be carried', 'RNA is carried', 'The whole chromosome is carried'], 0,
    'Lambda carries *gal* or *bio* genes.'],
  ['Phage lambda integrates into the *E. coli* chromosome between the:', ['*gal* and *bio* genes', '*lac* and *trp* genes', 'Origin and terminus', '*recA* and *lexA* genes'], 0,
    'This is why it carries only these nearby genes.'],
  ['In abortive transduction, the introduced DNA:', ['Is neither integrated nor replicated, so only one daughter cell inherits it', 'Integrates normally', 'Destroys the host', 'Replicates as a plasmid'], 0,
    'It shows up as tiny, slow-growing colonies.'],
  ['Transduction, unlike transformation, is not blocked by DNase because:', ['The DNA is protected inside the phage coat', 'DNase does not act on DNA', 'No DNA is involved', 'The bacteria make DNase inhibitors'], 0,
    'This test tells the two processes apart.'],
  ['Cotransduction frequency is used to:', ['Map genes that lie close together', 'Count phages', 'Measure bacterial growth', 'Test antibiotics'], 0,
    'Genes that are often transduced together must be close.'],
  ['The diphtheria toxin gene, carried by a phage into *Corynebacterium diphtheriae*, is an example of:', ['Lysogenic conversion', 'Transformation', 'Conjugation', 'Mutation'], 0,
    'The prophage changes the phenotype of its host.'],
  ['The three ways bacteria exchange genes are:', ['Transformation, transduction and conjugation', 'Mitosis, meiosis and fission', 'Budding, spores and fission', 'Fusion, grafting and layering'], 0,
    'Griffith first showed transformation in 1928.']
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 3, pyq: 'IFoS-2017-B1-Q3d', q: [
  ['Ectomycorrhizae are recognised by:', ['A fungal mantle around the root and a Hartig net between cortical cells', 'Arbuscules inside cells', 'Coils inside cells only', 'Nodules'], 0,
    'The fungus does not enter the cortical cells.'],
  ['Ectomycorrhizae are common in:', ['*Pinus*, *Eucalyptus*, oaks and dipterocarps', 'Wheat and rice', 'Mustard', 'Grasses'], 0,
    'The fungi are mostly basidiomycetes such as *Pisolithus* and *Amanita*.'],
  ['Arbuscular mycorrhizae (AM) form:', ['Arbuscules and vesicles inside root cortical cells', 'A mantle and Hartig net', 'Pelotons in orchids only', 'Root nodules'], 0,
    'The fungi belong to Glomeromycota (e.g., *Rhizophagus*, *Glomus*).'],
  ['About what share of land plants form arbuscular mycorrhizae?', ['About 70–80%', 'About 5%', 'About 20%', 'All'], 0,
    'Most crops, except crucifers and chenopods, are AM hosts.'],
  ['Orchid seeds need mycorrhizal fungi (such as *Tulasnella*) because:', ['The tiny seeds have almost no food reserves', 'Their seed coat is too hard', 'They need nitrogen fixation', 'They are dormant for years'], 0,
    'The fungus feeds the seedling until it can photosynthesise.'],
  ['The main benefit of mycorrhizae to crops is:', ['Better uptake of phosphorus (and zinc, copper and water)', 'Nitrogen fixation', 'Pest control only', 'Faster flowering only'], 0,
    'The hyphae explore far more soil than roots can.'],
  ['*Pisolithus tinctorius* is used to inoculate:', ['Pine and eucalyptus seedlings in forest nurseries', 'Rice nurseries', 'Wheat fields', 'Orchid flasks'], 0,
    'Inoculated seedlings survive better on poor sites.'],
  ['AM fungi are mass-produced on host roots because they:', ['Are obligate symbionts that cannot be grown alone in culture', 'Grow easily on agar', 'Are bacteria', 'Need no host'], 0,
    'Inoculum is raised on hosts such as maize or sorghum.'],
  ['Glomalin, produced by AM fungal hyphae, improves soil by:', ['Binding soil particles into stable aggregates', 'Fixing nitrogen', 'Killing pathogens', 'Adding salts'], 0,
    'It is a sticky glycoprotein.'],
  ['The term "mycorrhiza" was coined in 1885 by:', ['A. B. Frank', 'H. A. de Bary', 'S. Winogradsky', 'M. W. Beijerinck'], 0,
    'It means "fungus-root".']
] },
{ p: 'B1', t: 'Pteridophytes', w: 3, pyq: 'IFoS-2017-B1-Q4a', q: [
  ['The telome theory was proposed by:', ['W. Zimmermann', 'F. O. Bower', 'E. C. Jeffrey', 'D. H. Scott'], 0,
    'He developed it in the 1930s and refined it in 1952.'],
  ['A telome is:', ['The terminal segment of a dichotomously branched axis', 'The internode between two branchings', 'A leaf scar', 'A spore'], 0,
    'A mesome is the internode between two dichotomies.'],
  ['The elementary processes of the telome theory are:', ['Overtopping, planation, syngenesis (webbing), reduction and recurvation', 'Mitosis, meiosis and fusion', 'Pollination and fertilisation', 'Secondary growth only'], 0,
    'Different combinations of these explain different organs.'],
  ['According to the telome theory, megaphylls (fern leaves) arose by:', ['Overtopping, planation and webbing of telome trusses', 'Reduction only', 'Enations from the stem surface', 'Fusion of sporangia'], 0,
    'The side branches were flattened into one plane and then filled in.'],
  ['According to Zimmermann, microphylls of lycopods arose by:', ['Reduction of single telomes', 'Overtopping and webbing', 'Recurvation', 'Planation of many telomes'], 0,
    'Bower’s enation theory offers another explanation.'],
  ['The umbrella-like sporangiophore of *Equisetum* is explained by:', ['Recurvation of fertile telomes', 'Planation', 'Reduction only', 'Webbing only'], 0,
    'The sporangia bend back towards the axis.'],
  ['The plant that best represents a simple "telome plant" is:', ['*Rhynia*', '*Pinus*', '*Marchantia*', '*Selaginella*'], 0,
    'It had leafless dichotomous axes with terminal sporangia.'],
  ['The enation theory, an alternative explanation for microphylls, was proposed by:', ['F. O. Bower', 'W. Zimmermann', 'E. C. Jeffrey', 'W. H. Lang'], 0,
    'It sees microphylls as outgrowths from the stem surface.'],
  ['In the telome theory, fertile telomes are those that:', ['Bear sporangia at their tips', 'Bear leaves', 'Form roots', 'Form nodes'], 0,
    'Sterile telomes (phylloids) became leaf-like.'],
  ['The telome theory can also explain complex steles through:', ['Syngenesis — fusion of the vascular strands of telomes', 'Secondary growth', 'Leaf gaps only', 'Reduction'], 0,
    'Fused telomes give lobed and dissected steles.']
] },
{ p: 'B1', t: 'Plant Pathology', w: 3, pyq: 'IFoS-2017-B1-Q4b', q: [
  ['Black stem rust of wheat is caused by:', ['*Puccinia graminis* f. sp. *tritici*', '*Puccinia triticina*', '*Puccinia striiformis*', '*Ustilago tritici*'], 0,
    '*P. triticina* causes brown (leaf) rust; *P. striiformis* causes yellow (stripe) rust.'],
  ['Stem rust is called macrocyclic because it:', ['Produces all five spore stages', 'Has only urediniospores', 'Has no teliospores', 'Grows only on large plants'], 0,
    'The stages are pycniospores, aeciospores, urediniospores, teliospores and basidiospores.'],
  ['Stem rust is heteroecious — it needs:', ['Two different hosts: wheat and barberry (*Berberis*)', 'Only wheat', 'Only barberry', 'Wheat and maize'], 0,
    'Pycnia and aecia form on barberry.'],
  ['Stem rust symptoms on wheat are:', ['Elongated reddish-brown pustules on stems and leaf sheaths, later turning black', 'White powdery patches', 'Yellow stripes on leaves', 'Black grains'], 0,
    'The black stage is the teliospore stage.'],
  ['The repeating spore stage that spreads stem rust through the wheat crop is the:', ['Urediniospore', 'Teliospore', 'Basidiospore', 'Pycniospore'], 0,
    'Urediniospores are dikaryotic and wind-borne.'],
  ['Teliospores of stem rust are:', ['Two-celled, thick-walled and dark, and form basidia after dormancy', 'Single-celled and colourless', 'Formed on barberry', 'Motile'], 0,
    'Basidiospores from them infect barberry.'],
  ['K. C. Mehta showed that stem rust in India survives the summer:', ['As urediniospores on wheat in the Nilgiri and Palni hills, not on barberry', 'On barberry in the plains', 'In the soil', 'In stored grain'], 0,
    'Wind carries the spores north to the plains each season.'],
  ['The stem rust race Ug99, first found in Uganda in 1999, is dangerous because it overcame:', ['The widely used resistance gene *Sr31*', 'All fungicides', 'Barberry eradication', 'Crop rotation'], 0,
    'Breeders have since used other *Sr* genes.'],
  ['Stem rust is controlled mainly by:', ['Resistant varieties, with triazole fungicides such as propiconazole when needed', 'Hot-water seed treatment', 'Soil fumigation', 'Flooding'], 0,
    'Barberry was removed on a large scale in the USA.'],
  ['Pycniospores (spermatia) of stem rust:', ['Serve to fertilise receptive hyphae, restoring the dikaryon', 'Infect wheat directly', 'Are the resting stage', 'Are produced on wheat'], 0,
    'They form in pycnia on the upper surface of barberry leaves.']
] },
{ p: 'B1', t: 'Microbiology', w: 2, pyq: 'IFoS-2017-B1-Q4c', q: [
  ['In the lytic cycle, a phage:', ['Multiplies inside the host and bursts (lyses) it', 'Integrates into the host chromosome and stays dormant', 'Never infects the host', 'Only attaches to the host'], 0,
    'In the lysogenic cycle, the phage genome is carried as a prophage.'],
  ['Phage T4 is:', ['Virulent — it follows only the lytic cycle', 'Temperate', 'An RNA phage', 'A plant virus'], 0,
    'Lambda is the classic temperate phage.'],
  ['The T4 phage has:', ['An icosahedral head holding double-stranded DNA and a contractile tail with fibres', 'An RNA genome in a rod', 'A lipid envelope', 'No tail'], 0,
    'Its genome is about 169 kb.'],
  ['The steps of T4 multiplication are:', ['Adsorption → penetration → synthesis → assembly → lysis', 'Lysis → adsorption → assembly', 'Integration → dormancy → induction', 'Assembly → penetration → adsorption'], 0,
    'The whole cycle takes about 25–30 minutes at 37 °C.'],
  ['During penetration by T4:', ['The tail sheath contracts and the DNA is injected into the cell', 'The whole phage enters the cell', 'Only protein enters the cell', 'The cell wall dissolves completely'], 0,
    'The empty protein coat stays outside.'],
  ['T4 DNA resists the host’s restriction enzymes because it contains:', ['Glucosylated 5-hydroxymethylcytosine instead of cytosine', 'Uracil', 'No cytosine at all', 'RNA'], 0,
    'The modified base is not recognised by many restriction enzymes.'],
  ['At the end of the lytic cycle, the host cell is broken open by:', ['Phage-encoded lysozyme and holin', 'Host DNase', 'Heat', 'Antibiotics'], 0,
    'About 100–200 new phages are released per cell.'],
  ['A prophage can be induced to enter the lytic cycle by:', ['UV light, which activates RecA and leads to cleavage of the λ cI repressor', 'Adding glucose', 'Cooling the cells', 'Adding more phage'], 0,
    'DNA damage signals that the host may die.'],
  ['The one-step growth curve of phages was worked out by:', ['Ellis and Delbrück (1939)', 'Twort', 'd’Hérelle', 'Luria'], 0,
    'It shows a latent period followed by a sudden burst.'],
  ['Hershey and Chase (1952) used phage T2 to show that:', ['DNA, not protein, is the genetic material', 'Protein is the genetic material', 'RNA is the genetic material of all phages', 'Phages have no genes'], 0,
    'They labelled the DNA with ³²P and the protein with ³⁵S.']
] },
{ p: 'B1', t: 'Bryophytes', w: 2, pyq: 'IFoS-2017-B1-Q4d', q: [
  ['Bryophytes are called the "amphibians of the plant kingdom" because they:', ['Live on land but need water for fertilisation', 'Live only in water', 'Live only in deserts', 'Have both roots and gills'], 0,
    'Their sperms must swim to the archegonium.'],
  ['Land plants are thought to have evolved from:', ['Charophycean green algae', 'Red algae', 'Brown algae', 'Fungi'], 0,
    '*Coleochaete* and *Chara* show several land-plant-like features.'],
  ['Adaptations that allowed plants to live on land include:', ['A cuticle, stomata, spores with sporopollenin walls and protected embryos', 'Flagellated leaves', 'Gills', 'Loss of all protective layers'], 0,
    'Retaining the embryo gives the name "embryophytes".'],
  ['The earliest evidence of land plants is:', ['Cryptospores from the Ordovician (about 470 million years ago)', 'Angiosperm pollen from the Cretaceous', 'Coal from the Carboniferous', 'Seeds from the Devonian'], 0,
    'These spores resemble those of liverworts.'],
  ['The earliest known vascular plant fossil is:', ['*Cooksonia* (Silurian)', '*Pinus*', '*Archaefructus*', '*Glossopteris*'], 0,
    'It had simple dichotomous axes with terminal sporangia.'],
  ['The Rhynie chert of Scotland preserves early Devonian land plants such as:', ['*Rhynia* and *Aglaophyton*', '*Pinus* and *Cedrus*', 'Mosses only', 'Flowering plants'], 0,
    'Its cells are preserved in fine detail.'],
  ['In *Coleochaete*, the zygote is retained on the parent and nourished through transfer cells. This is seen as:', ['A model for the origin of embryo retention in land plants', 'Proof that algae have seeds', 'A form of parasitism', 'An unrelated feature'], 0,
    'Linda Graham stressed its importance.'],
  ['In bryophytes, the dominant, free-living generation is the:', ['Gametophyte', 'Sporophyte', 'Embryo', 'Protonema only'], 0,
    'In vascular plants the sporophyte dominates.'],
  ['The interpolation (antithetic) theory holds that the sporophyte:', ['Is a new phase inserted between gametophyte generations', 'Is a modified gametophyte', 'Evolved from fungi', 'Is haploid'], 0,
    'The homologous theory treats both generations as modified versions of the same plant body.'],
  ['The ancestral land-plant life cycle, as in bryophytes, is best described as:', ['A dominant haploid gametophyte with a dependent diploid sporophyte', 'A diploid-only cycle', 'A haploid-only cycle', 'Two independent diploid generations'], 0,
    'The sporophyte became dominant later, in vascular plants.']
] }
);
