/* PYQ-linked MCQs — IFoS 2025 Agriculture Paper II (topic-level PYQs from the volume anchors). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: 'IFoS-2025-A2-Q1a', q: [
  ['Heritable variation differs from non-heritable variation in that it:', ['Is caused by genotype differences and passes to offspring', 'Is caused only by environment', 'Disappears in the next generation', 'Cannot be selected'], 0,
    'Only heritable variation responds to selection.'],
  ['The genotypic coefficient of variation (GCV) is calculated as:', ['(√VG ÷ mean) × 100', '(VG ÷ VP) × 100', '(VE ÷ mean) × 100', 'Mean ÷ √VG'], 0,
    'The phenotypic coefficient (PCV) uses √VP instead.'],
  ['A large gap between PCV and GCV for a trait indicates:', ['Strong environmental influence on the trait', 'High heritability', 'No genetic variation', 'Pure additive effects'], 0,
    'Selection on phenotype would then be less effective.'],
  ['Transgressive segregation refers to:', ['Segregants in F₂ or later generations that fall outside the range of both parents', 'Plants identical to the F₁', 'Mutants from radiation', 'Clones'], 0,
    'It results from combining favourable alleles from both parents.'],
  ['Stability analysis of genotypes across environments (regression approach) was proposed by:', ['Eberhart and Russell (1966)', 'Johannsen (1903)', 'Harlan and de Wet (1971)', 'Sprague and Tatum (1942)'], 0,
    'A stable genotype has regression near 1 and small deviations.'],
  ['Mahalanobis D² statistics are used in breeding to:', ['Measure genetic divergence and choose diverse parents', 'Estimate heritability', 'Calculate LD₅₀', 'Test seed purity'], 0,
    'Crosses between divergent clusters are expected to give more heterosis and variability.'],
  ['Which is a method of creating new variation?', ['Hybridisation, mutation, polyploidy and genetic engineering', 'Pure-line selection only', 'Clonal propagation', 'Seed storage'], 0,
    'Selection only sorts existing variation.'],
  ['Genotype × environment interaction means that:', ['The relative performance of genotypes changes from one environment to another', 'All genotypes perform the same everywhere', 'Environment has no effect', 'Only genotype matters'], 0,
    'It is why multi-location trials are needed.'],
  ['Continuous variation (as in plant height or yield) is usually controlled by:', ['Many genes with small effects plus the environment', 'A single gene', 'Cytoplasmic genes only', 'No genes'], 0,
    'Discontinuous (qualitative) variation is usually controlled by one or a few major genes.'],
  ['Plant introduction adds variation to a breeding programme by:', ['Bringing in germplasm from other regions or countries', 'Mutating local varieties', 'Hybridising within a pure line', 'Cloning local plants'], 0,
    'Introductions are quarantined through NBPGR in India.'],
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2025-A2-Q1b', q: [
  ['The National Seeds Corporation (NSC) was set up in:', ['1963', '1985', '2001', '1947'], 0,
    'It produces and markets foundation and certified seed of many crops.'],
  ['The State Farms Corporation of India (SFCI) was:', ['Merged with the National Seeds Corporation', 'Converted into FCI', 'Closed in 1970', 'Made part of NABARD'], 0,
    'The merger was approved in 2016.'],
  ['"Mahabeej" is the state seed corporation of:', ['Maharashtra', 'Madhya Pradesh', 'Karnataka', 'Gujarat'], 0,
    'Many states have their own seed corporations.'],
  ['Breeder seed in India is produced mainly by:', ['ICAR institutes and state agricultural universities', 'Private dealers', 'Farmers alone', 'FCI'], 0,
    'Coordinated under the AICRP on National Seed Project.'],
  ['The ICAR institute for seed science research is at:', ['Mau, Uttar Pradesh (ICAR-IISS)', 'Ludhiana', 'Hyderabad', 'Shimla'], 0,
    'Indian Institute of Seed Science.'],
  ['The Central Seed Testing Laboratory function in India is performed by the:', ['National Seed Research and Training Centre (NSRTC), Varanasi', 'NBPGR only', 'FCI laboratory', 'FSSAI'], 0,
    'It acts as a referral laboratory and trains seed analysts.'],
  ['Bharatiya Beej Sahakari Samiti Ltd (BBSSL), set up in 2023, is a:', ['National multi-state cooperative for quality seed production and marketing', 'Private seed company', 'Seed testing lab', 'Crop insurance company'], 0,
    'Promoted by cooperatives such as IFFCO, KRIBHCO, NAFED and NDDB.'],
  ['Seed certification in states is done by:', ['State Seed Certification Agencies', 'NSC', 'Seed dealers', 'Gram Panchayats'], 0,
    'They follow the Indian Minimum Seed Certification Standards.'],
  ['The Central Seed Committee under the Seeds Act, 1966:', ['Advises the government on seed matters, including notification of varieties', 'Sells seeds', 'Produces breeder seed', 'Imports seeds'], 0,
    'The Central Seed Certification Board advises on certification.'],
  ['The main role of public seed institutions is to:', ['Ensure supply of quality seed of public varieties, especially for self-pollinated crops, at fair prices', 'Replace all private firms', 'Produce only hybrids', 'Export all seed'], 0,
    'The private sector dominates hybrids and vegetables.'],
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'IFoS-2025-A2-Q1c', q: [
  ['Most water loss by transpiration occurs through:', ['Stomata (about 90% or more)', 'Cuticle', 'Lenticels', 'Roots'], 0,
    'Cuticular and lenticular transpiration are minor.'],
  ['Transpiration increases when:', ['Light and temperature rise, humidity falls and wind increases', 'Humidity is high and air still', 'Stomata close', 'Soil water is depleted'], 0,
    'The vapour pressure deficit between leaf and air drives transpiration.'],
  ['The transpiration ratio (water transpired per unit dry matter produced) is:', ['Lower in C₄ plants (about 250–350) than in C₃ plants (about 450–950)', 'Higher in C₄ than C₃', 'The same in all plants', 'Zero in CAM plants'], 0,
    'CAM plants have the lowest ratios.'],
  ['Transpiration can be measured in the laboratory with a:', ['Potometer', 'Tensiometer', 'Hydrometer', 'Barometer'], 0,
    'A potometer measures water uptake by a cut shoot; porometers measure stomatal conductance.'],
  ['A benefit of transpiration to plants is:', ['Cooling leaves and moving water and nutrients from roots to shoots', 'Adding water to the soil', 'Increasing salinity', 'Stopping photosynthesis'], 0,
    'It is sometimes called a "necessary evil" because of the water it costs.'],
  ['Many dicot leaves have more stomata on the:', ['Lower (abaxial) surface', 'Upper surface only', 'Petiole', 'Leaf margin'], 0,
    'Such leaves are hypostomatic; many grasses have stomata on both surfaces.'],
  ['A thick boundary layer of still air around a leaf:', ['Reduces transpiration', 'Increases transpiration', 'Has no effect', 'Opens stomata'], 0,
    'Hairs and sunken stomata thicken the boundary layer.'],
  ['Guttation differs from transpiration in that it:', ['Releases liquid water through hydathodes, driven by root pressure', 'Releases water vapour through stomata', 'Occurs only in bright sun', 'Occurs only in dry soil'], 0,
    'It is seen at leaf tips early in humid mornings.'],
  ['Stomata close under water stress mainly in response to:', ['Abscisic acid', 'Gibberellin', 'Cytokinin', 'Auxin'], 0,
    'Roots in drying soil send ABA signals to leaves.'],
  ['Transpiration efficiency (dry matter produced per unit water transpired) is improved by:', ['Traits that raise photosynthesis relative to water loss, such as C₄ photosynthesis', 'Wide-open stomata at noon', 'High leaf temperature', 'Thin cuticles'], 0,
    'Carbon isotope discrimination is used to select for it in wheat and groundnut.'],
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: 'IFoS-2025-A2-Q1d', q: [
  ['In secondary cell walls, the thickest layer is usually:', ['S2', 'S1', 'S3', 'The primary wall'], 0,
    'S2 largely determines the strength of wood fibres.'],
  ['Plasmodesmata contain a central tube derived from ER called the:', ['Desmotubule', 'Microtubule', 'Tonoplast', 'Phragmoplast'], 0,
    'They connect the cytoplasm of neighbouring cells.'],
  ['Bordered pits with a torus and margo are characteristic of:', ['Conifer tracheids', 'Angiosperm vessels only', 'Parenchyma cells', 'Phloem sieve tubes'], 0,
    'The torus can seal the pit to prevent air spread.'],
  ['The membrane surrounding the plant vacuole is the:', ['Tonoplast', 'Plasma membrane', 'Nuclear envelope', 'Thylakoid'], 0,
    'The vacuole stores water, ions and metabolites and maintains turgor.'],
  ['Amyloplasts are plastids that store:', ['Starch', 'Oil', 'Protein', 'Pigments'], 0,
    'Elaioplasts store oil, proteinoplasts store protein, and chromoplasts hold carotenoid pigments.'],
  ['The cell plate that forms the new wall during plant cell division is assembled from vesicles of the:', ['Golgi apparatus, guided by the phragmoplast', 'Mitochondria', 'Chloroplasts', 'Nucleolus'], 0,
    'It grows outward until it joins the parent wall.'],
  ['The nucleolus is the site of:', ['Ribosomal RNA synthesis and ribosome assembly', 'DNA replication only', 'Photosynthesis', 'Lipid synthesis'], 0,
    'It forms at the nucleolar organiser region.'],
  ['Rough endoplasmic reticulum differs from smooth ER in having:', ['Ribosomes attached and a role in protein synthesis', 'No membranes', 'Chlorophyll', 'DNA'], 0,
    'Smooth ER is involved in lipid synthesis.'],
  ['Peroxisomes in leaves take part in:', ['Photorespiration (glycolate to glycine)', 'Krebs cycle', 'Starch storage', 'Protein synthesis'], 0,
    'They contain catalase to break down hydrogen peroxide.'],
  ['Chromoplasts give colour to:', ['Ripe fruits and flower petals (e.g., tomato, carrot, marigold)', 'Roots of all plants', 'Seeds only', 'Leaves only'], 0,
    'They accumulate carotenoids such as lycopene and β-carotene.'],
] },
{ p: 'A2', t: 'Heterosis, Hybrids & Mutation Breeding', w: 2, pyq: 'IFoS-2025-A2-Q1e', q: [
  ['India’s first maize hybrids were released in:', ['1961', '1947', '1985', '2001'], 0,
    'E.g., Ganga 1, Ganga 101, Ranjit and Deccan — double-cross hybrids.'],
  ['India’s first sorghum hybrid, CSH 1, was released in:', ['1964', '1990', '1950', '2005'], 0,
    'Based on the CK60A cytoplasmic male-sterile line.'],
  ['India’s first pearl millet hybrid, HB 1 (1965), was based on the CMS line:', ['Tift 23A', 'CK60A', 'WA', 'PET1'], 0,
    'Downy mildew later affected hybrids on this single cytoplasm.'],
  ['India released its first hybrid rice varieties in:', ['1994', '1966', '1976', '2010'], 0,
    'E.g., APHR 1, APHR 2, MGR 1 and KRH 1.'],
  ['Hybrid rice typically yields about ___ more than the best inbred varieties.', ['15–20%', '100%', '1–2%', '60%'], 0,
    'Higher seed cost and seed-production difficulties limit adoption.'],
  ['Hybrid wheat has been difficult to commercialise mainly because:', ['Wheat is self-pollinated with low outcrossing, making hybrid seed production costly', 'Wheat has no heterosis at all', 'Wheat cannot be crossed', 'Wheat is apomictic'], 0,
    'Efficient male-sterility systems and better outcrossing are needed.'],
  ['Heterobeltiosis is heterosis measured over the:', ['Better parent', 'Mid-parent', 'Standard check variety', 'Poorer parent'], 0,
    'Standard (economic) heterosis is measured over the best commercial variety.'],
  ['Maize hybrids now grown in India are mostly:', ['Single-cross hybrids', 'Double-cross hybrids', 'Composites', 'Synthetics only'], 0,
    'Single crosses are more uniform and higher yielding.'],
  ['Seed yield in hybrid rice seed production is low mainly because:', ['Rice is self-pollinated with limited pollen transfer from the restorer (R) to the male-sterile (A) line', 'Rice has no pollen', 'Rice is wind-pollinated over long distances', 'Rice flowers at night'], 0,
    'Supplementary pollination and GA₃ sprays help.'],
  ['Farmers must buy hybrid seed every season because:', ['F₂ plants segregate and lose the uniformity and vigour of the F₁', 'Hybrid seed cannot germinate', 'Hybrids are sterile', 'It is required by law'], 0,
    'Apomixis research aims to fix hybrid vigour.'],
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: 'IFoS-2025-A2-Q2a', q: [
  ['Mendel’s laws were rediscovered in 1900 by:', ['de Vries, Correns and von Tschermak', 'Darwin and Wallace', 'Morgan and Sturtevant', 'Watson and Crick'], 0,
    'Mendel had published in 1866.'],
  ['The "Vilmorin isolation principle" (1856), testing single plants by their progeny, was used in:', ['Sugar beet', 'Wheat', 'Rice', 'Maize'], 0,
    'An early form of progeny testing that raised beet sugar content.'],
  ['The first transgenic plants (tobacco with a kanamycin-resistance gene) were produced in:', ['1983', '1953', '1996', '2010'], 0,
    'By several groups using *Agrobacterium* vectors.'],
  ['Recombinant DNA technology began with the work of:', ['Cohen and Boyer (1973)', 'Mendel (1866)', 'Borlaug (1960s)', 'Mullis (1983)'], 0,
    'They joined DNA from different sources and cloned it in bacteria.'],
  ['Large-scale commercial cultivation of GM crops began in:', ['1996', '1983', '1973', '2006'], 0,
    'E.g., herbicide-tolerant soybean and Bt maize and cotton in the USA.'],
  ['The Imperial Agricultural Research Institute was set up at Pusa (Bihar) in 1905 and later moved to:', ['New Delhi (1936)', 'Kolkata', 'Mumbai', 'Kanpur'], 0,
    'It is now IARI, "Pusa Institute".'],
  ['Early improved wheat varieties such as Pusa 4 and Pusa 12 were bred by:', ['Albert and Gabrielle Howard', 'M.S. Swaminathan', 'Norman Borlaug', 'B.P. Pal'], 0,
    'Albert Howard is also known for the Indore method of composting.'],
  ['"Nobilisation" of sugarcane at Coimbatore (e.g., Co 205, 1918) involved crossing noble cane with:', ['Wild *Saccharum spontaneum*', 'Maize', 'Sorghum only', 'Bamboo'], 0,
    'By C.A. Barber and T.S. Venkatraman; it gave hardy, high-yielding canes.'],
  ['The Green Revolution in India in the late 1960s was based mainly on:', ['Semi-dwarf, fertiliser-responsive wheat and rice varieties with irrigation and fertiliser', 'GM crops', 'Hybrid wheat', 'Organic farming'], 0,
    'Led by scientists such as M.S. Swaminathan with Norman Borlaug.'],
  ['Genetic engineering differs from conventional breeding mainly in that it can:', ['Transfer genes across species barriers', 'Use only crossing', 'Only select existing plants', 'Never change DNA'], 0,
    'Genome editing now allows precise changes without foreign DNA.'],
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: 'IFoS-2025-A2-Q2b', q: [
  ['NBPGR, India’s national agency for plant genetic resources, was established in:', ['1976', '1905', '1947', '2002'], 0,
    'It handles exploration, introduction, quarantine and conservation.'],
  ['"Base collections" in a gene bank are:', ['Long-term collections stored at about −18 °C, not used for routine distribution', 'Working collections used by breeders daily', 'Field plantings', 'Herbarium sheets'], 0,
    'Active collections are kept at about 4 °C for medium-term use and distribution.'],
  ['A "core collection" is:', ['A small subset (about 10%) of a collection that captures most (about 70%) of its diversity', 'All accessions of a gene bank', 'Only wild relatives', 'Only elite varieties'], 0,
    'Concept of Frankel and Brown (1984), to make evaluation manageable.'],
  ['The Svalbard Global Seed Vault, opened in 2008, stores:', ['Safety back-up duplicates of seeds from gene banks worldwide', 'Only Norwegian crops', 'Living plants', 'DNA sequences only'], 0,
    'It is built into permafrost rock in Norway.'],
  ['Genetic erosion refers to:', ['Loss of genetic diversity, e.g., when landraces are replaced by a few modern varieties', 'Soil erosion', 'Mutation', 'Hybridisation'], 0,
    'Collecting and conserving landraces counters it.'],
  ['Pre-breeding means:', ['Transferring useful genes from wild or unadapted germplasm into usable breeding lines', 'Breeding before sowing', 'Seed treatment', 'Selecting only elite lines'], 0,
    'It bridges gene banks and breeding programmes.'],
  ['"Passport data" of a germplasm accession records:', ['Its origin, collection site, date and basic identity', 'Its market price', 'Its yield in a farmer’s field only', 'Its DNA sequence'], 0,
    'Characterisation and evaluation data are added later.'],
  ['On-farm conservation of landraces:', ['Keeps crops evolving in farmers’ fields under local selection', 'Stores seeds in cold rooms', 'Uses tissue culture only', 'Discourages farmer participation'], 0,
    'It complements ex-situ gene banks.'],
  ['Unique germplasm in India can be registered with:', ['ICAR’s Plant Germplasm Registration Committee (through NBPGR)', 'The patent office only', 'FSSAI', 'The Seeds Act committee only'], 0,
    'Registration recognises the developers of novel germplasm.'],
  ['Using conserved germplasm effectively requires mainly:', ['Characterisation and evaluation of accessions for useful traits', 'Keeping it unused', 'Destroying duplicates', 'Selling it abroad'], 0,
    'Evaluation data guide breeders to useful sources.'],
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'IFoS-2025-A2-Q2c', q: [
  ['Which is a C₄ crop?', ['Pearl millet', 'Wheat', 'Rice', 'Chickpea'], 0,
    'Maize, sorghum, sugarcane, finger millet and amaranth are also C₄.'],
  ['C₄ crops generally have an optimum temperature for photosynthesis of about:', ['30–40 °C', '5–10 °C', '15–20 °C only', 'Below 0 °C'], 0,
    'C₃ crops have lower optima (about 15–25 °C).'],
  ['The CO₂ compensation point of C₄ plants is:', ['Very low (near 0–10 ppm)', 'About 50 ppm, like C₃ plants', 'Above 400 ppm', 'Undefined'], 0,
    'C₃ plants have compensation points around 40–100 ppm.'],
  ['At cool temperatures, the quantum yield of C₃ plants compared with C₄ plants is:', ['Higher, because photorespiration is low and C₄ has an extra ATP cost', 'Lower', 'Equal', 'Zero'], 0,
    'C₄ plants gain the advantage as temperature rises.'],
  ['C₄ plants usually have higher water-use efficiency because they:', ['Can fix CO₂ with partly closed stomata', 'Have more stomata open', 'Transpire more', 'Lack Rubisco'], 0,
    'PEP carboxylase has high affinity for bicarbonate.'],
  ['C₄ crops also show higher nitrogen-use efficiency because:', ['They need less Rubisco protein for the same photosynthesis', 'They fix nitrogen', 'They absorb more nitrate', 'They need no nitrogen'], 0,
    'Rubisco holds a large share of leaf nitrogen in C₃ plants.'],
  ['Photosynthesis of C₄ plants usually:', ['Does not saturate even at full sunlight', 'Saturates at very low light', 'Stops at noon', 'Needs shade'], 0,
    'C₃ leaves saturate at lower light intensities.'],
  ['Under warmer, drier climates, the crop type expected to cope better is generally:', ['C₄ crops such as sorghum and millets', 'C₃ crops such as wheat', 'Both equally', 'Neither'], 0,
    'But C₃ crops benefit more from rising CO₂.'],
  ['In NADP-ME type C₄ plants such as maize, bundle-sheath chloroplasts are:', ['Agranal (lacking grana), with reduced photosystem II activity', 'Granal with high PS II', 'Absent', 'Identical to mesophyll chloroplasts'], 0,
    'This limits O₂ production where Rubisco works.'],
  ['Which is a C₃ crop?', ['Groundnut', 'Sugarcane', 'Sorghum', 'Maize'], 0,
    'Most pulses, oilseeds, cotton and potato are C₃.'],
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: 'IFoS-2025-A2-Q3a', q: [
  ['The gene pool concept (primary, secondary and tertiary gene pools) was proposed by:', ['Harlan and de Wet (1971)', 'Vavilov (1926)', 'Frankel and Brown (1984)', 'Johannsen (1903)'], 0,
    'It classifies relatives by ease of crossing with the crop.'],
  ['The primary gene pool (GP-1) includes:', ['Forms that cross easily with the crop and give fertile hybrids', 'Only distantly related genera', 'Organisms that cannot cross at all', 'Only transgenic sources'], 0,
    'GP-1A = cultivated forms; GP-1B = wild or weedy forms of the same species.'],
  ['The secondary gene pool (GP-2) includes species that:', ['Can be crossed with the crop, but hybrids are partly sterile or weak', 'Cross freely with fully fertile hybrids', 'Cannot be crossed by any method', 'Are the crop itself'], 0,
    'Gene transfer is possible with some effort.'],
  ['Transferring genes from the tertiary gene pool (GP-3) usually needs:', ['Special techniques such as embryo rescue, bridging species or chromosome doubling', 'Simple crossing', 'Selection only', 'No technique'], 0,
    'Hybrids are often lethal or completely sterile.'],
  ['Genetic engineering has, in effect, created a "quaternary" gene pool consisting of:', ['Genes from any organism that can be moved by transformation', 'Only wild relatives', 'Only cultivated varieties', 'Only mutants'], 0,
    'E.g., Bt genes from bacteria.'],
  ['*Oryza nivara* was the source of rice resistance to:', ['Grassy stunt virus', 'Blast', 'Bacterial blight', 'Brown spot'], 0,
    'Found after screening thousands of IRRI accessions; used in IR varieties.'],
  ['A "bridging species" helps to:', ['Transfer genes between two species that cannot be crossed directly', 'Increase seed dormancy', 'Test seed viability', 'Produce clones'], 0,
    'The crop is crossed with the bridge species, and the hybrid with the donor.'],
  ['Crop wild relatives are valuable to breeders mainly as sources of:', ['Resistance to pests, diseases and stresses', 'High uniform yield', 'Seed colour only', 'Nothing useful'], 0,
    'Many modern disease-resistance genes came from wild relatives.'],
  ['Hybrids between a crop and species of its secondary gene pool are often:', ['Partly sterile, needing backcrosses to restore fertility', 'Fully fertile and vigorous always', 'Impossible to produce', 'Identical to the crop'], 0,
    'Backcrossing recovers the crop type while keeping the target trait.'],
  ['The gene pool concept guides germplasm work by showing:', ['How easily useful genes can be transferred from each group of relatives', 'The price of seed', 'Which fertiliser to use', 'Where to sell produce'], 0,
    'It helps set collection and conservation priorities.'],
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, pyq: 'IFoS-2025-A2-Q3b', q: [
  ['Multiline varieties, first proposed by Jensen and Borlaug, are:', ['Mixtures of near-isogenic lines carrying different resistance genes', 'Single pure lines', 'Hybrids', 'Mutants'], 0,
    'They slow epidemics by diluting susceptible tissue.'],
  ['KML 7406, released in India in 1981, is a:', ['Multiline wheat variety', 'Hybrid maize', 'Bt cotton', 'Rice mutant'], 0,
    'Based on Kalyan Sona with different rust-resistance genes.'],
  ['Painter (1951) classified insect-resistance mechanisms as:', ['Non-preference (antixenosis), antibiosis and tolerance', 'Escape, avoidance and death', 'Vertical, horizontal and diagonal', 'Hypersensitivity only'], 0,
    'Antibiosis harms the insect’s growth or survival; tolerance lets the plant yield despite attack.'],
  ['Screening for disease resistance often uses "spreader rows" of:', ['A highly susceptible variety to ensure plenty of inoculum', 'A resistant variety', 'A weed', 'Bare soil'], 0,
    'Hot-spot locations and artificial epiphytotics are also used.'],
  ['Adult-plant resistance genes such as *Lr34*/*Yr18* in wheat are valued because they:', ['Give durable, partial ("slow-rusting") resistance to several rusts', 'Give complete immunity to all races', 'Work only in seedlings', 'Cause yield loss'], 0,
    'They are race-non-specific.'],
  ['Durable resistance (Johnson, 1981) is resistance that:', ['Stays effective after long use over large areas in favourable environments', 'Lasts only one season', 'Is controlled by one major gene always', 'Is found only in wild plants'], 0,
    'Often polygenic or based on adult-plant resistance.'],
  ['Transgenic papaya varieties that rescued Hawaii’s papaya industry are resistant to:', ['Papaya ringspot virus (coat-protein-mediated)', 'Fruit fly', 'Powdery mildew', 'Nematodes'], 0,
    'Varieties such as SunUp and Rainbow were released in 1998.'],
  ['The "boom-and-bust cycle" in resistance breeding refers to:', ['Wide spread of a variety with a single resistance gene, followed by breakdown as new pathogen races evolve', 'Price cycles', 'Rainfall cycles', 'Seed dormancy cycles'], 0,
    'Gene pyramiding and deployment strategies aim to break this cycle.'],
  ['Regional gene deployment means:', ['Using different resistance genes in different regions to slow pathogen spread', 'Using the same gene everywhere', 'Removing resistance genes', 'Planting only susceptible varieties'], 0,
    'Useful for airborne rusts that move across regions.'],
  ['Brown planthopper resistance in rice is controlled by several *Bph* genes, with donors such as:', ['PTB 33 and other traditional varieties', 'IR8 only', 'Wheat varieties', 'Maize inbreds'], 0,
    'New biotypes can overcome single genes, so multiple genes are combined.'],
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: 'IFoS-2025-A2-Q3c', q: [
  ['Incomplete dominance is shown by flower colour in *Mirabilis jalapa*, where red × white gives:', ['Pink F₁ and a 1 : 2 : 1 F₂ ratio', 'Red F₁ and 3 : 1 F₂', 'White F₁ only', 'Red and white spots on the same flower'], 0,
    'The heterozygote is intermediate, so phenotype and genotype ratios match.'],
  ['Codominance is seen in:', ['The AB blood group in humans, where both A and B antigens are expressed', 'Pink flowers of *Mirabilis*', 'Tall pea plants', 'Seed shape in pea'], 0,
    'MN blood groups and roan coat colour in cattle are other examples.'],
  ['A 2 : 1 ratio instead of 3 : 1 in the F₂ usually indicates:', ['A recessive lethal effect of a dominant allele (as in yellow mice)', 'Complete dominance', 'Incomplete dominance', 'Linkage'], 0,
    'Homozygous dominant individuals die (Cuénot’s yellow mice).'],
  ['At the molecular level, complete dominance often arises because:', ['One functional allele produces enough product (haplosufficiency)', 'Recessive alleles are always deleted', 'Dominant alleles have more DNA', 'Both alleles are silenced'], 0,
    'Loss-of-function alleles are therefore usually recessive.'],
  ['A test cross is used to:', ['Find whether a dominant-phenotype individual is homozygous or heterozygous', 'Produce hybrids', 'Measure heritability', 'Test seed purity'], 0,
    'It is a cross with the homozygous recessive.'],
  ['Mendel studied how many contrasting traits in the garden pea?', ['Seven', 'Three', 'Twelve', 'Twenty'], 0,
    'Including seed shape, seed colour, flower colour and plant height.'],
  ['Overdominance refers to:', ['The heterozygote performing better than both homozygotes', 'One allele fully masking another', 'Both alleles expressed equally', 'Absence of dominance'], 0,
    'Proposed as one explanation of heterosis.'],
  ['Multiple alleles are illustrated by:', ['The ABO blood group and the S-alleles of self-incompatibility', 'Two genes controlling one trait', 'Linked genes', 'Cytoplasmic genes'], 0,
    'Any diploid individual carries only two of them.'],
  ['Pleiotropy means that:', ['One gene affects several different traits', 'Several genes affect one trait', 'Genes are linked', 'A gene is absent'], 0,
    'Polygeny is the reverse — many genes for one trait.'],
  ['In complete dominance, a monohybrid F₂ gives a genotypic ratio of:', ['1 : 2 : 1', '3 : 1', '9 : 3 : 3 : 1', '1 : 1'], 0,
    'The phenotypic ratio is 3 : 1.'],
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: 'IFoS-2025-A2-Q4a', q: [
  ['Polygenic (quantitative) inheritance of wheat kernel colour was demonstrated by:', ['Nilsson-Ehle', 'Mendel', 'Morgan', 'Correns'], 0,
    'With two gene pairs, the F₂ shows a 1 : 4 : 6 : 4 : 1 ratio of colour classes.'],
  ['If 1/64 of F₂ plants resemble one extreme parent in a polygenic trait, the number of gene pairs is:', ['3', '2', '4', '6'], 0,
    'Fraction at each extreme = (1/4)ⁿ; (1/4)³ = 1/64.'],
  ['Epistasis differs from dominance in that epistasis is:', ['An interaction between genes at different loci', 'An interaction between alleles of the same gene', 'Cytoplasmic', 'Environmental'], 0,
    'Dominance is intra-allelic; epistasis is inter-allelic.'],
  ['Penetrance refers to:', ['The proportion of individuals with a genotype that show the expected phenotype', 'The degree to which a trait is expressed', 'The number of alleles', 'The rate of mutation'], 0,
    'Expressivity is the degree or intensity of expression.'],
  ['Linked genes differ from independently assorting genes in that linked genes:', ['Are on the same chromosome and tend to be inherited together', 'Are on different chromosomes', 'Always segregate 9 : 3 : 3 : 1', 'Are cytoplasmic'], 0,
    'Recombination between them depends on distance.'],
  ['Qualitative traits differ from quantitative traits in that qualitative traits:', ['Show discrete classes and are controlled by one or a few major genes', 'Show continuous variation', 'Are strongly affected by environment', 'Need biometrical analysis'], 0,
    'E.g., flower colour versus yield.'],
  ['Autosomal inheritance differs from X-linked inheritance in that autosomal traits:', ['Appear equally in both sexes and reciprocal crosses give the same result', 'Appear mostly in males', 'Pass only from mothers', 'Pass only from fathers to sons'], 0,
    'X-linked recessive traits are more common in males.'],
  ['"Multiple genes" differs from "multiple alleles" in that multiple genes:', ['Are different loci affecting the same trait', 'Are different forms of one gene', 'Are always linked', 'Are cytoplasmic'], 0,
    'Multiple alleles are alternative forms at one locus.'],
  ['Extranuclear (cytoplasmic) inheritance differs from nuclear inheritance in that it:', ['Usually follows the maternal parent and does not give Mendelian ratios', 'Shows 3 : 1 ratios', 'Is always sex-linked', 'Is controlled by autosomes'], 0,
    'Chloroplast and mitochondrial genes are involved.'],
  ['Variable expressivity is illustrated when individuals with the same genotype:', ['Show the trait with different intensities', 'All show the trait identically', 'Never show the trait', 'Change sex'], 0,
    'Environment and modifier genes contribute.'],
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2025-A2-Q4b', q: [
  ['Under Indian standards, the isolation distance for certified seed of maize (open-pollinated and hybrid) is about:', ['200 m', '3 m', '10 m', '2 km'], 0,
    'Foundation seed needs about 400 m; maize is wind-pollinated.'],
  ['Isolation in cross-pollinated seed crops can also be achieved by:', ['Time isolation — different sowing dates so flowering does not overlap', 'Using more fertiliser', 'Irrigating more', 'Changing seed colour'], 0,
    'Barrier crops and border rows may also help in some crops.'],
  ['In hybrid maize seed production, "shedders" in female rows are:', ['Female-parent plants shedding pollen because tassels were not removed in time', 'Male plants', 'Diseased plants', 'Weeds'], 0,
    'Field standards set a maximum permissible percentage of shedders.'],
  ['Field standards for seed crops specify limits for:', ['Isolation, off-types, shedders, objectionable weeds and designated diseases', 'Market price', 'Soil pH only', 'Farmer’s income'], 0,
    'Seed standards (after harvest) cover purity, germination and moisture.'],
  ['Field inspections of hybrid seed crops are scheduled especially at:', ['Flowering, when off-types and shedders can be identified', 'Only at sowing', 'Only after harvest', 'Only in storage'], 0,
    'Several inspections are made from pre-flowering to pre-harvest.'],
  ['Cross-pollinated crops need larger isolation distances than self-pollinated crops because:', ['Foreign pollen carried by wind or insects can contaminate the seed crop', 'Their seeds are larger', 'They need more water', 'They are always hybrids'], 0,
    'Genetic purity would otherwise fall.'],
  ['An "objectionable weed" in seed certification is one that:', ['Has seeds hard to separate from crop seed or is harmful', 'Is any weed', 'Is a crop plant', 'Grows only in forests'], 0,
    'E.g., wild oat in wheat; *Cuscuta* in lucerne.'],
  ['"Off-types" in a seed crop are:', ['Plants that differ from the variety’s description', 'Diseased plants only', 'Weeds', 'Seedlings'], 0,
    'They are removed by rogueing.'],
  ['Seed standards differ from field standards in that seed standards cover:', ['Physical purity, germination, moisture and other distinguishable varieties in the seed lot', 'Isolation distance', 'Planting ratio', 'Shedders'], 0,
    'Both must be met for certification.'],
  ['Border rows of the male parent around a hybrid seed plot help by:', ['Adding pollen and trapping stray foreign pollen', 'Reducing yield', 'Attracting pests', 'Shading the field'], 0,
    'They can be used to reduce the isolation distance needed in some crops.'],
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 3, pyq: 'IFoS-2025-A2-Q4c', q: [
  ['Cytoplasmic male sterility in onion (S cytoplasm) was discovered by Jones and Clarke in the variety:', ['Italian Red', 'Pusa Red', 'Nasik Red', 'Bellary Red'], 0,
    'It made commercial hybrid onions possible (1943).'],
  ['In carrot, a widely used male sterility is the:', ['Petaloid CMS, where stamens turn into petal-like structures', 'Ogura CMS', 'Tift 23A', 'WA'], 0,
    'Brown-anther type CMS is another carrot system.'],
  ['Ogura CMS used for hybrid cabbage and cauliflower originally came from:', ['Radish', 'Onion', 'Carrot', 'Tomato'], 0,
    'Cold-induced chlorosis linked to radish chloroplasts was removed by protoplast fusion.'],
  ['CMS in chilli (*Capsicum annuum*) was first reported by:', ['Peterson (1958)', 'Jones (1943)', 'Burton (1958)', 'Ogura (1968)'], 0,
    'Genetic male sterility (e.g., *ms-10*) is also used in chilli.'],
  ['Most tomato hybrids are produced by:', ['Hand emasculation and pollination', 'CMS only', 'Chemical hybridising agents only', 'Apomixis'], 0,
    'Each fruit gives many seeds, so hand crossing is economical.'],
  ['Brinjal hybrids are commonly produced by hand emasculation because:', ['Each pollination gives many seeds, making it economical', 'Brinjal has no pollen', 'Brinjal is apomictic', 'CMS is illegal'], 0,
    'The same applies to tomato and chilli.'],
  ['An alternative to male sterility for hybrid seed in cabbage is:', ['Self-incompatibility', 'Apomixis', 'Cleistogamy', 'Parthenocarpy'], 0,
    'SI lines cannot set seed with their own pollen, so they are pollinated by the other parent.'],
  ['"Positional sterility" in some tomato lines refers to:', ['An exserted stigma that prevents self-pollination although pollen is viable', 'Complete lack of pollen', 'Sterile ovules', 'Cytoplasmic sterility'], 0,
    'It is a form of functional male sterility.'],
  ['Genetic male sterility is used for hybrid seed in:', ['Muskmelon (e.g., *ms-1*)', 'Wheat only', 'Rice only', 'Potato only'], 0,
    'Fertile segregants must be removed from female rows.'],
  ['A marker gene linked to a male-sterility gene helps seed producers by:', ['Identifying sterile plants early, before flowering', 'Increasing yield', 'Removing sterility', 'Changing flower colour permanently'], 0,
    'Seedling markers save the labour of rogueing fertile plants later.'],
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 3, pyq: 'IFoS-2025-A2-Q5a', q: [
  ['A plug-tray nursery raises seedlings in:', ['Individual cells of trays filled with soilless media', 'Open soil beds', 'Water only', 'Plastic bags filled with clay'], 0,
    'Each seedling gets its own root plug.'],
  ['A common medium for plug trays is a mixture of cocopeat, vermiculite and perlite in the ratio:', ['3 : 1 : 1', '1 : 3 : 3', '1 : 1 : 5', '5 : 0 : 0'], 0,
    'The mix is light, sterile, and holds water and air well.'],
  ['The main advantage of plug-tray seedlings is:', ['Uniform, healthy seedlings with an intact root ball and little transplanting shock', 'Lower germination', 'More soil-borne disease', 'Greater seed use'], 0,
    'They also save costly hybrid seed.'],
  ['Cocopeat is washed or buffered before use mainly to:', ['Remove excess salts (lower EC)', 'Add nitrogen', 'Increase pH to 9', 'Add weed seeds'], 0,
    'Unwashed cocopeat can have high sodium and potassium.'],
  ['Plug-tray nurseries are usually raised under:', ['Shade nets, polyhouses or insect-proof nets', 'Full sun without protection', 'Water tanks', 'Forest canopy'], 0,
    'Insect-proof nets keep out virus vectors such as whiteflies and thrips.'],
  ['Seedlings are hardened before transplanting by:', ['Gradually reducing water and exposing them to outdoor conditions', 'Adding more nitrogen', 'Keeping them in darkness', 'Increasing humidity'], 0,
    'Hardening improves survival in the field.'],
  ['Tomato and chilli seedlings from plug trays are usually transplanted at about:', ['25–30 days old', '5 days old', '90 days old', '6 months old'], 0,
    'Older seedlings become root-bound in the cells.'],
  ['Plug-tray nurseries reduce damping-off mainly because:', ['Sterile soilless media and controlled watering limit soil-borne pathogens such as *Pythium*', 'They use more soil', 'They are kept waterlogged', 'They use no media'], 0,
    'Damping-off is a major loss in open nursery beds.'],
  ['Nutrients in plug-tray nurseries are commonly supplied by:', ['Fertigation with water-soluble fertilisers', 'Farmyard manure only', 'No nutrients', 'Heavy basal urea'], 0,
    'Soilless media contain few nutrients.'],
  ['Plug-tray nurseries are especially valuable for:', ['High-value hybrid vegetables such as tomato, capsicum, chilli and cucurbits', 'Wheat', 'Rice direct seeding', 'Sugarcane setts'], 0,
    'Commercial hi-tech nurseries now supply many farmers.'],
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, pyq: 'IFoS-2025-A2-Q5b', q: [
  ['Early blight of tomato and potato, with concentric "target-board" spots, is caused by:', ['*Alternaria solani*', '*Phytophthora infestans*', '*Ralstonia solanacearum*', '*Fusarium oxysporum*'], 0,
    'It usually starts on older leaves.'],
  ['JHULSACAST, developed by ICAR-CPRI, is a:', ['Forecasting model for potato late blight', 'Potato variety', 'Fungicide', 'Storage method'], 0,
    'It uses weather data to advise when to spray.'],
  ['Bacterial wilt of solanaceous crops is quickly diagnosed in the field by:', ['The ooze (streaming) test — milky bacterial ooze from a cut stem in water', 'Leaf spots with rings', 'Powdery growth on leaves', 'Root galls'], 0,
    'Caused by *Ralstonia solanacearum*; no effective chemical control.'],
  ['Damping-off of tomato and chilli seedlings is caused mainly by:', ['*Pythium* species (and *Rhizoctonia*)', '*Alternaria solani*', 'Viruses', 'Nematodes'], 0,
    'Seed treatment and well-drained nursery beds reduce it.'],
  ['Fusarium wilt of tomato is caused by:', ['*Fusarium oxysporum* f. sp. *lycopersici*', '*Ralstonia solanacearum*', '*Alternaria solani*', '*Xanthomonas*'], 0,
    'Vascular browning; resistant varieties and crop rotation help.'],
  ['Die-back and fruit rot (anthracnose) of chilli is caused by:', ['*Colletotrichum capsici*', '*Phytophthora infestans*', '*Pythium*', '*Erwinia*'], 0,
    'Sunken lesions on ripe fruits with black acervuli.'],
  ['Phomopsis blight and fruit rot of brinjal is caused by:', ['*Phomopsis vexans*', '*Alternaria solani*', '*Colletotrichum capsici*', '*Fusarium solani*'], 0,
    'Seed-borne; hot-water or fungicide seed treatment helps.'],
  ['Bacterial leaf spot of tomato and chilli is caused by:', ['*Xanthomonas* (*X. vesicatoria* / *X. euvesicatoria*)', '*Alternaria solani*', '*Pythium*', '*Fusarium*'], 0,
    'Spreads by rain splash; copper sprays and clean seed help.'],
  ['Black scurf of potato, with black sclerotia on tubers, is caused by:', ['*Rhizoctonia solani*', '*Streptomyces scabies*', '*Phytophthora infestans*', '*Alternaria solani*'], 0,
    'Tuber seed treatment reduces it.'],
  ['Common scab of potato is caused by:', ['*Streptomyces scabies* (an actinomycete)', '*Rhizoctonia solani*', '*Pythium*', 'A virus'], 0,
    'Favoured by dry, alkaline soils; keeping soil moist at tuber initiation reduces it.'],
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: 'IFoS-2025-A2-Q5c', q: [
  ['"Storage fungi", which damage grain and pulses in store, include:', ['*Aspergillus* and *Penicillium* species', '*Alternaria* and *Fusarium* only', 'Rusts', 'Downy mildews'], 0,
    'Field fungi such as *Alternaria*, *Fusarium* and *Cladosporium* need higher moisture and decline in storage.'],
  ['Field fungi differ from storage fungi in that field fungi:', ['Need high seed moisture (about 20% or more) and invade before harvest', 'Grow at 13–15% moisture in store', 'Produce aflatoxin in dry grain', 'Never affect seeds'], 0,
    'Storage fungi grow at lower moisture levels in store.'],
  ['A safe moisture content for storing pulse seeds is about:', ['9–10%', '20%', '30%', '2%'], 0,
    'Lower moisture limits both fungi and insects.'],
  ['Storage fungi generally do not grow when the relative humidity of the store is below about:', ['65–70%', '95%', '100%', '85%'], 0,
    'Seed moisture comes into equilibrium with store humidity.'],
  ['The black mould seen on stored pulses and onions is often caused by:', ['*Aspergillus niger*', '*Rhizopus* only', '*Fusarium* only', 'Rusts'], 0,
    '*A. niger* is also used to make citric acid.'],
  ['Storage fungi harm seeds mainly by:', ['Reducing germination, causing discoloration and heating, and producing mycotoxins', 'Increasing germination', 'Adding nutrients', 'Improving flavour'], 0,
    'Aflatoxin contamination is a food-safety risk.'],
  ['Seed-borne fungi are detected in seed-health testing mainly by the:', ['Blotter test (ISTA)', 'Tetrazolium test', 'Conductivity test', 'Grow-out test'], 0,
    'Seeds are incubated on moist blotters and examined for fungal growth.'],
  ['Pulse seed for sowing is commonly treated against seed-borne fungi with:', ['Thiram or carbendazim, or *Trichoderma* as a bio-agent', 'Urea', 'Gypsum', 'Glyphosate'], 0,
    'Treatment also protects seedlings from soil-borne pathogens.'],
  ['Aflatoxin contamination is generally greater in:', ['Groundnut and maize than in most pulses', 'Pulses than groundnut', 'Fresh vegetables', 'Fruits'], 0,
    'Groundnut and maize are major aflatoxin risks in India.'],
  ['Drying pulses well before storage helps mainly because it:', ['Keeps moisture too low for storage fungi and insects to thrive', 'Increases seed size', 'Adds protein', 'Kills all bacteria permanently'], 0,
    'Proper drying is the cheapest protection.'],
] },
{ p: 'A2', t: 'Post-harvest & Food Processing', w: 2, pyq: 'IFoS-2025-A2-Q5d', q: [
  ['Botulinum toxin, the most potent known toxin, is produced by:', ['*Clostridium botulinum*, especially in improperly canned foods', '*Staphylococcus aureus*', '*Bacillus cereus*', '*Aspergillus flavus*'], 0,
    'It is a neurotoxin; proper canning (heat) destroys the spores.'],
  ['Food poisoning from *Staphylococcus aureus* is difficult to prevent by reheating because its enterotoxin is:', ['Heat-stable', 'Destroyed at 40 °C', 'Only present in raw vegetables', 'A virus'], 0,
    'Good hygiene prevents contamination in the first place.'],
  ['"Fried rice syndrome" (vomiting after eating reheated rice) is caused by toxin of:', ['*Bacillus cereus*', '*Clostridium botulinum*', '*Salmonella*', '*Rhizopus*'], 0,
    'The emetic toxin cereulide survives reheating.'],
  ['Endotoxins differ from exotoxins in that endotoxins are:', ['Lipopolysaccharides of the Gram-negative bacterial cell wall', 'Proteins secreted by bacteria', 'Produced by fungi only', 'Harmless'], 0,
    'Exotoxins are secreted proteins (e.g., botulinum toxin).'],
  ['The insecticidal Cry proteins of *Bacillus thuringiensis* are:', ['δ-endotoxins (crystal proteins) that act on insect gut cells', 'Mycotoxins', 'Plant hormones', 'Antibiotics'], 0,
    'They are highly specific to certain insect groups.'],
  ['Microcystin, a toxin in polluted lakes and reservoirs, is produced by:', ['The cyanobacterium *Microcystis*', 'Diatoms', 'Green algae', 'Fungi'], 0,
    'It damages the liver; blooms follow eutrophication.'],
  ['Tabtoxin, which causes wildfire disease of tobacco, is produced by:', ['*Pseudomonas syringae* pv. *tabaci*', '*Xanthomonas*', '*Agrobacterium*', '*Erwinia*'], 0,
    'It causes chlorotic haloes around lesions.'],
  ['Citrinin is a mycotoxin produced by species of:', ['*Penicillium* and *Monascus*', '*Clostridium*', '*Bacillus*', '*Microcystis*'], 0,
    'It is a kidney toxin found in stored grains and red yeast rice.'],
  ['Mycotoxin risk in food is best reduced by:', ['Timely harvest, proper drying and good storage', 'Cooking at high heat only', 'Adding sugar', 'Freezing after contamination'], 0,
    'Many mycotoxins survive cooking.'],
  ['Coronatine, produced by some *Pseudomonas syringae* strains, acts by:', ['Mimicking the plant hormone jasmonate to suppress host defences', 'Killing insects', 'Fixing nitrogen', 'Producing antibiotics'], 0,
    'It also reopens stomata to help bacterial entry.'],
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: 'IFoS-2025-A2-Q5e', q: [
  ['Under the National Food Security Act, 2013, pregnant women and lactating mothers are entitled to maternity benefit of at least:', ['₹6,000', '₹600', '₹60,000', '₹1,000'], 0,
    'Delivered through the Pradhan Mantri Matru Vandana Yojana.'],
  ['NFSA requires ration cards to be issued in the name of:', ['The eldest woman (aged 18 or more) of the household as head', 'The eldest man only', 'Any child', 'The village head'], 0,
    'A provision to empower women.'],
  ['Before foodgrains were made free under the NFSA, the central issue prices were:', ['₹3, ₹2 and ₹1 per kg for rice, wheat and coarse grains', '₹10, ₹8 and ₹5 per kg', 'Market prices', '₹1 for all grains'], 0,
    'From January 2023, NFSA grains have been provided free.'],
  ['If entitled foodgrains are not supplied, NFSA provides for a:', ['Food Security Allowance', 'Loan waiver', 'Land grant', 'Crop insurance claim'], 0,
    'Paid by the state government.'],
  ['Grievance redressal under NFSA includes:', ['District Grievance Redressal Officers and State Food Commissions', 'Only courts', 'Only the police', 'No mechanism'], 0,
    'Vigilance committees and social audits are also provided.'],
  ['"One Nation One Ration Card" enables:', ['Beneficiaries to draw their ration from any fair price shop in the country', 'Only one card per state', 'Cash instead of grain', 'Free grain for all'], 0,
    'Useful for migrant workers.'],
  ['NFSA provides nutritional support for children aged 6 months to 14 years through:', ['Anganwadis (ICDS) and school mid-day meals', 'Only cash transfers', 'Private schools only', 'Hospitals only'], 0,
    'Take-home rations and hot cooked meals are given.'],
  ['Identification of eligible households under NFSA is done by:', ['State governments, within coverage limits set by the Centre', 'The Centre alone', 'Private agencies', 'Gram Sabhas alone'], 0,
    'Coverage ratios are fixed state-wise.'],
  ['NFSA shifted India’s food policy from a welfare approach to a:', ['Rights-based approach, making food a legal entitlement', 'Market-based approach', 'Voluntary approach', 'Import-based approach'], 0,
    'Beneficiaries can claim entitlements through grievance systems.'],
  ['Transparency under NFSA is supported by:', ['Placing PDS records in the public domain and conducting social audits', 'Keeping all records secret', 'Removing vigilance committees', 'Stopping computerisation'], 0,
    'End-to-end computerisation of TPDS was also undertaken.'],
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 3, pyq: 'IFoS-2025-A2-Q6a', q: [
  ['The most popular commercial pomegranate variety in India is:', ['Bhagwa (Kesar)', 'Alphonso', 'Kinnow', 'Thompson Seedless'], 0,
    'Known for deep red arils and skin; Ganesh and Mridula are others.'],
  ['ICAR’s National Research Centre on Pomegranate is at:', ['Solapur, Maharashtra', 'Lucknow', 'Bengaluru', 'Shimla'], 0,
    'It released the biofortified variety Solapur Lal (high Fe, Zn and vitamin C).'],
  ['Pomegranate is commonly propagated by:', ['Air layering (gootee) and hardwood cuttings', 'Seed only', 'Grafting on mango', 'Budding on citrus'], 0,
    'Tissue culture plants are also used.'],
  ['"Bahar treatment" in pomegranate refers to:', ['Regulating the flowering season by withholding water (Ambe, Mrig or Hasta bahar)', 'Pruning roots', 'Spraying pesticides', 'Harvesting early'], 0,
    'The choice of bahar depends on water availability and market.'],
  ['The most destructive disease of pomegranate in India is:', ['Bacterial blight (oily spot) caused by *Xanthomonas axonopodis* pv. *punicae*', 'Late blight', 'Citrus canker', 'Powdery mildew of wheat'], 0,
    'It devastated orchards in Maharashtra and Karnataka.'],
  ['Fruit cracking in pomegranate is linked mainly to:', ['Irregular irrigation and boron deficiency', 'Excess shade', 'Low nitrogen only', 'Cold winters only'], 0,
    'Regular drip irrigation and boron sprays reduce cracking.'],
  ['The anar butterfly (*Deudorix* / *Virachola isocrates*) damages pomegranate by:', ['Boring into developing fruits', 'Eating roots', 'Sucking leaves', 'Rolling leaves'], 0,
    'Bagging fruits is an effective protective measure.'],
  ['Pomegranate suits arid and semi-arid regions because it:', ['Tolerates drought and moderate salinity', 'Needs heavy rainfall', 'Grows only in snow', 'Needs waterlogged soils'], 0,
    'Drip irrigation gives better quality and yields.'],
  ['The leading pomegranate-producing state in India is:', ['Maharashtra', 'Punjab', 'Kerala', 'Assam'], 0,
    'Karnataka, Gujarat and Andhra Pradesh are other important producers.'],
  ['A key challenge for pomegranate in arid regions is:', ['Scarcity of irrigation water and saline groundwater', 'Too much rain', 'Frost every month', 'Excess fertility'], 0,
    'High temperature also causes sunscald on fruits.'],
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: 'IFoS-2025-A2-Q6b', q: [
  ['Among cereals and millets, finger millet (ragi) is outstanding for its content of:', ['Calcium', 'Vitamin C', 'Vitamin B12', 'Fat'], 0,
    'About 300–350 mg calcium per 100 g, far more than rice or wheat.'],
  ['Pearl millet (bajra) is especially rich in:', ['Iron and zinc', 'Vitamin D', 'Lycopene', 'Caffeine'], 0,
    'Biofortified varieties raise iron further.'],
  ['Millets suit people with coeliac disease because they are:', ['Gluten-free', 'High in gluten', 'Low in fibre', 'Rich in lactose'], 0,
    'They also have a lower glycaemic index than polished rice.'],
  ['"Kodua poisoning" from kodo millet is caused by:', ['Cyclopiazonic acid produced by fungi on infected grain', 'Excess protein', 'Pesticide residue', 'Gluten'], 0,
    'Proper drying and sorting of grain prevent it.'],
  ['Which is a small millet?', ['Barnyard millet', 'Maize', 'Wheat', 'Rice'], 0,
    'Others: kodo, little (kutki), foxtail, proso and browntop millets.'],
  ['The Indian Institute of Millets Research, declared a Global Centre of Excellence for millets in 2023, is at:', ['Hyderabad', 'Jodhpur', 'Dharwad', 'Coimbatore'], 0,
    'Budget 2023 called millets "Shree Anna".'],
  ['Pearl millet flour has a short shelf life mainly because:', ['Lipase activity and high fat cause rapid rancidity', 'It has no fat', 'It absorbs no moisture', 'It contains gluten'], 0,
    'Heat treatment of grain before milling helps.'],
  ['Antinutritional factors that can reduce mineral absorption from millets include:', ['Phytates and tannins', 'Vitamins', 'Dietary fibre only', 'Protein'], 0,
    'Soaking, germination, fermentation and malting reduce them.'],
  ['Millets are climate-resilient mainly because they:', ['Are hardy, often C₄, short-duration crops that tolerate drought and poor soils', 'Need heavy irrigation', 'Grow only in cold climates', 'Need high fertiliser'], 0,
    'They are grown mostly in rainfed areas.'],
  ['Under the NFSA, millets (coarse grains) can be distributed through the PDS:', ['Yes — coarse grains are included, and states can procure and distribute them', 'No, only rice and wheat are allowed', 'Only in cities', 'Only for export'], 0,
    'Several states distribute ragi, jowar or bajra through the PDS.'],
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2025-A2-Q6c', q: [
  ['Acid scarification to break hard-seed dormancy uses:', ['Concentrated sulphuric acid for a set time, followed by thorough washing', 'Dilute acetic acid for a week', 'Hydrochloric acid spray on plants', 'Nitric acid in soil'], 0,
    'Used for some legumes and tree seeds.'],
  ['Teak seed dormancy is commonly overcome by:', ['Alternate soaking and drying of the fruits', 'Freezing for a month', 'Acid treatment for a day', 'Keeping them in darkness'], 0,
    'The hard, thick mesocarp limits germination.'],
  ['Freshly harvested rice seed dormancy can be broken by:', ['Dry heat treatment (around 50 °C for a few days)', 'Freezing', 'Soaking in salt water', 'Keeping it moist in the dark'], 0,
    'Soaking in dilute nitric acid is another method.'],
  ['Potato tuber dormancy can be broken by:', ['Gibberellic acid, thiourea or carbon disulphide treatment', 'Maleic hydrazide', 'Cold storage at 2 °C', 'ABA treatment'], 0,
    'Maleic hydrazide does the opposite — it prolongs dormancy.'],
  ['Dormancy in freshly harvested groundnut (Virginia types) can be broken with:', ['Ethrel (ethylene-releasing)', 'ABA', 'Maleic hydrazide', 'Cycocel'], 0,
    'Ethylene promotes germination in groundnut.'],
  ['"Double dormancy" in some tree and shrub seeds needs:', ['Both scarification (for the seed coat) and stratification (for the embryo)', 'Only light', 'Only heat', 'No treatment'], 0,
    'Two separate blocks must be removed in sequence.'],
  ['Positively photoblastic seeds are those that:', ['Need light to germinate', 'Germinate only in darkness', 'Need fire', 'Need no water'], 0,
    'Mediated by phytochrome.'],
  ['Red-grained wheats are generally less prone to pre-harvest sprouting than white-grained wheats because they:', ['Have stronger seed dormancy linked to grain-colour genes', 'Have thicker husks', 'Mature later', 'Contain no starch'], 0,
    'Dormancy protects grain quality when rain falls at harvest.'],
  ['To tell whether ungerminated seeds in a germination test are dormant or dead, analysts use the:', ['Tetrazolium test', 'Conductivity test', 'Grow-out test', 'Blotter test'], 0,
    'Viable dormant seeds stain red.'],
  ['Hot-water treatment for hard-coated seeds (e.g., *Acacia*) works by:', ['Softening or cracking the impermeable seed coat so water can enter', 'Killing the embryo', 'Adding nutrients', 'Stopping respiration'], 0,
    'Seeds are placed in hot water that is allowed to cool.'],
] },
{ p: 'A2', t: 'Post-harvest & Food Processing', w: 2, pyq: 'IFoS-2025-A2-Q7a', q: [
  ['Operation Greens was extended in 2021 from tomato, onion and potato to cover:', ['22 perishable commodities', 'Only cereals', 'Only exports', 'Only pulses'], 0,
    'It had first been extended temporarily to all fruits and vegetables in 2020.'],
  ['The national portal for daily prices and arrivals in agricultural markets is:', ['Agmarknet', 'Bhuvan', 'Meghdoot', 'SATHI'], 0,
    'Run by the Directorate of Marketing and Inspection.'],
  ['Kisan Rail, started in 2020, is meant mainly to:', ['Move perishables quickly and cheaply over long distances', 'Carry fertilisers only', 'Transport tractors', 'Carry passengers'], 0,
    'It helps farmers reach distant markets.'],
  ['Export promotion of fresh fruits and vegetables is handled mainly by:', ['APEDA', 'FCI', 'NABARD', 'CACP'], 0,
    'Agricultural and Processed Food Products Export Development Authority.'],
  ['AGMARK grading of farm produce is done under the:', ['Agricultural Produce (Grading and Marking) Act, 1937', 'Seeds Act, 1966', 'FSS Act, 2006', 'APMC Act'], 0,
    'Grading allows sale by description and better prices.'],
  ['Onion price spikes are moderated mainly by:', ['Buffer stocks (e.g., NAFED under the Price Stabilisation Fund), trade measures and better storage', 'Banning onion cultivation', 'Increasing exports during shortages', 'Removing all storage'], 0,
    'Bottom-ventilated storage structures cut losses.'],
  ['The National Centre for Cold-chain Development (NCCD) promotes:', ['Integrated cold chains for perishable produce', 'Seed storage only', 'Fertiliser storage', 'Grain procurement'], 0,
    'Cold chains reduce losses and extend market reach.'],
  ['Horticultural produce is especially hard to market because it is:', ['Perishable, bulky and seasonal, with volatile prices', 'Non-perishable', 'Always in short supply', 'Not traded'], 0,
    'Farmers often get a small share of the consumer price.'],
  ['The Mission for Integrated Development of Horticulture (MIDH) supports:', ['Production, post-harvest management, processing and marketing of horticultural crops', 'Only irrigation dams', 'Only wheat', 'Only forestry'], 0,
    'It includes the National Horticulture Mission and related schemes.'],
  ['The main aim of "TOP" price stabilisation is to:', ['Protect both farmers and consumers from sharp price swings in tomato, onion and potato', 'Maximise traders’ profits', 'Ban imports', 'Fix retail prices by law'], 0,
    'Through storage, processing and better logistics.'],
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 3, pyq: 'IFoS-2025-A2-Q7b', q: [
  ['Okra (bhindi) belongs to the family:', ['Malvaceae', 'Solanaceae', 'Cucurbitaceae', 'Fabaceae'], 0,
    '*Abelmoschus esculentus*.'],
  ['For kharif okra, the seed rate is about ___, lower than for the summer crop.', ['8–10 kg/ha', '50 kg/ha', '1 kg/ha', '100 kg/ha'], 0,
    'Summer okra needs about 18–20 kg/ha because of poorer germination and closer spacing.'],
  ['The usual spacing for kharif okra is about:', ['60 × 30 cm', '10 × 10 cm', '2 × 2 m', '1 × 1 m'], 0,
    'Summer okra is sown closer (about 45 × 30 cm).'],
  ['Okra seeds are often soaked in water before sowing because:', ['Their hard seed coat slows germination', 'They need no water', 'Soaking kills pests completely', 'It changes their colour'], 0,
    'Soaking for about 12–24 hours speeds emergence.'],
  ['The major viral disease of okra in the rainy season is:', ['Yellow vein mosaic, spread by whitefly', 'Late blight', 'Leaf rust', 'Tungro'], 0,
    'Resistant varieties include Arka Anamika and Parbhani Kranti.'],
  ['Pusa Sawani, an early IARI okra variety, was notable for:', ['Tolerance to yellow vein mosaic and suitability for both seasons', 'Very long duration', 'Red pods', 'Being a hybrid'], 0,
    'Newer varieties have largely replaced it.'],
  ['The shoot and fruit borer of okra is:', ['*Earias vittella*', '*Helicoverpa armigera* only', '*Leucinodes orbonalis*', '*Plutella xylostella*'], 0,
    '*Leucinodes orbonalis* is the brinjal shoot and fruit borer; *Plutella* is the diamondback moth.'],
  ['Okra pods are harvested:', ['Tender, about 5–7 days after flowering, every 2–3 days', 'When fully mature and dry', 'Once at the end of the season', 'Before flowering'], 0,
    'Delayed picking gives fibrous pods.'],
  ['Enation leaf curl of okra is a:', ['Viral disease spread by whitefly', 'Fungal disease', 'Nutrient deficiency', 'Insect bite'], 0,
    'Causes leaf curling and outgrowths (enations) on veins.'],
  ['Okra is valued nutritionally for its:', ['Mucilage and dietary fibre, plus vitamins and minerals', 'High fat', 'High caffeine', 'Gluten'], 0,
    'Mucilage is also used industrially.'],
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'IFoS-2025-A2-Q7c', q: [
  ['Vernalisation usually requires exposure to temperatures of about:', ['0–10 °C for several weeks', '30–35 °C', 'Below −20 °C', '20–25 °C for one day'], 0,
    'The effective range and duration vary with species and variety.'],
  ['Devernalisation is:', ['Reversal of the vernalisation effect by high temperature soon after cold treatment', 'Extra cold treatment', 'Flowering in short days', 'Seed dormancy'], 0,
    'Once stabilised, vernalisation is not reversed.'],
  ['In *Arabidopsis*, vernalisation promotes flowering by:', ['Epigenetically silencing the repressor gene FLOWERING LOCUS C (FLC)', 'Activating FLC', 'Destroying phytochrome', 'Producing auxin'], 0,
    'Silencing involves VIN3 and histone methylation, and is remembered through mitosis.'],
  ['Winter wheat differs from spring wheat in that winter wheat:', ['Needs vernalisation to flower normally', 'Needs no cold', 'Flowers only in short days', 'Is a perennial'], 0,
    'Most Indian wheats are spring types.'],
  ['Biennial vegetables such as cabbage, carrot and sugar beet need cold to:', ['Bolt and flower (for seed production)', 'Germinate', 'Form roots', 'Resist pests'], 0,
    'Seed crops of these are grown in the hills for this reason.'],
  ['In some rosette plants, the cold requirement for bolting can be replaced by:', ['Gibberellin application', 'Auxin', 'Cytokinin', 'ABA'], 0,
    'Shown by Anton Lang.'],
  ['The hypothetical substance "vernalin" was proposed by:', ['Melchers', 'Went', 'Lysenko', 'Garner'], 0,
    'Grafting experiments suggested a transmissible stimulus.'],
  ['Lysenko’s term for the vernalisation of seeds was:', ['Jarovization', 'Stratification', 'Scarification', 'Priming'], 0,
    'He soaked and chilled winter-wheat seed to sow it in spring.'],
  ['Winter annuals such as winter wheat typically need:', ['Vernalisation followed by long days to flower', 'Only short days', 'No environmental cue', 'Only high temperature'], 0,
    'Cold and photoperiod act in sequence.'],
  ['The cold stimulus in vernalisation is perceived by:', ['The shoot apex (dividing cells)', 'The leaves only', 'The roots only', 'The flowers'], 0,
    'Photoperiod, by contrast, is perceived by the leaves.'],
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: 'IFoS-2025-A2-Q8a', q: [
  ['The Food Corporation of India was set up in:', ['1965, under the Food Corporations Act, 1964', '1947', '1991', '2013'], 0,
    'It handles procurement, storage and distribution for the central pool.'],
  ['The Shanta Kumar Committee (2015) on restructuring FCI recommended, among other things:', ['Reducing NFSA coverage to about 40% and moving towards cash transfers', 'Increasing NFSA coverage to 100%', 'Abolishing MSP', 'Stopping all procurement'], 0,
    'It also noted that only a small share of farmers sold to procurement agencies.'],
  ['The Targeted Public Distribution System (TPDS) was introduced in:', ['1997', '1965', '2013', '1950'], 0,
    'It followed the Revamped PDS of 1992.'],
  ['Wheat procurement for the central pool is concentrated mainly in:', ['Punjab, Haryana and Madhya Pradesh', 'Kerala and Tamil Nadu', 'Assam and Bihar', 'Himachal and Sikkim'], 0,
    'Rice procurement is high in Punjab, Chhattisgarh, Telangana and others.'],
  ['The "economic cost" of FCI includes:', ['Procurement price plus procurement incidentals and distribution costs', 'Only the MSP', 'Only transport', 'Only storage'], 0,
    'The gap with the issue price is the food subsidy.'],
  ['Under the WTO Agreement on Agriculture, the "de minimis" limit of product-specific support for developing countries is:', ['10% of the value of production', '5%', '25%', '50%'], 0,
    'It is 5% for developed countries.'],
  ['The "peace clause" agreed at the WTO Bali Ministerial (2013) concerns:', ['Public stockholding for food security programmes', 'Tariffs on cars', 'Fishing subsidies only', 'Patents'], 0,
    'It protects such programmes from challenge while a permanent solution is negotiated.'],
  ['Open-ended procurement at MSP has been criticised for:', ['Encouraging rice–wheat monocropping and large stocks above buffer norms', 'Reducing farm incomes', 'Lowering food security', 'Discouraging wheat production'], 0,
    'Crop diversification and decentralised procurement are suggested responses.'],
  ['Food subsidy in India is essentially the difference between:', ['The economic cost of grains and the price at which they are issued to beneficiaries', 'MSP and market price', 'Import and export prices', 'Retail and wholesale price'], 0,
    'It is one of the largest items of government spending.'],
  ['Decentralised procurement (DCP) helps food policy by:', ['Letting states procure and distribute locally, saving transport and widening procurement', 'Centralising all procurement', 'Ending PDS', 'Increasing imports'], 0,
    'It also supports farmers in states with little central procurement.'],
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: 'IFoS-2025-A2-Q8b', q: [
  ['Chilli leaves curling UPWARD are typically caused by:', ['Thrips (*Scirtothrips dorsalis*)', 'Mites', 'Aphids', 'Whitefly only'], 0,
    'Downward curling with a leathery look is typical of mites (e.g., the broad mite).'],
  ['The broad (yellow) mite causing downward leaf curl in chilli is:', ['*Polyphagotarsonemus latus*', '*Tetranychus urticae*', '*Scirtothrips dorsalis*', '*Bemisia tabaci*'], 0,
    'Together, thrips and mites cause the chilli "murda" complex.'],
  ['Thrips are important vectors of:', ['Tospoviruses such as peanut bud necrosis and tomato spotted wilt virus', 'Rice tungro', 'Banana bunchy top', 'Yellow vein mosaic of okra'], 0,
    'Managing thrips also reduces these diseases.'],
  ['Sticky traps of which colour are especially attractive to thrips?', ['Blue', 'Yellow', 'Red', 'Black'], 0,
    'Yellow traps attract whiteflies, aphids and leafminers.'],
  ['A specialist predator used against spider mites in protected cultivation is:', ['*Phytoseiulus persimilis*', '*Trichogramma chilonis*', '*Chrysoperla carnea* only', '*Bracon hebetor*'], 0,
    'Other predatory mites (*Neoseiulus*, *Amblyseius*) and *Orius* bugs are used against thrips.'],
  ['Many insecticides fail against mites mainly because:', ['Mites are arachnids that need specific acaricides', 'Mites are immune to all chemicals', 'Mites live only in soil', 'Mites are insects'], 0,
    'Synthetic pyrethroids can even cause mite resurgence by killing their predators.'],
  ['A low-cost, relatively safe option for managing mites in many crops is:', ['Wettable sulphur or neem-based products', 'DDT', 'Carbofuran', 'Glyphosate'], 0,
    'Rotate modes of action to delay resistance.'],
  ['Mite outbreaks are favoured by:', ['Hot, dry weather and dusty conditions', 'Cool, wet weather', 'Frequent heavy rain', 'Shade and high humidity only'], 0,
    'Overhead irrigation or sprinkling can suppress mites.'],
  ['The two-spotted spider mite, a pest of vegetables and ornamentals, is:', ['*Tetranychus urticae*', '*Polyphagotarsonemus latus*', '*Aceria* sp.', '*Scirtothrips dorsalis*'], 0,
    'It produces fine webbing on the underside of leaves.'],
  ['An IPM programme for thrips and mites includes:', ['Monitoring with traps, removing weed hosts, conserving and releasing natural enemies, and selective pesticides only when needed', 'Calendar spraying of broad-spectrum insecticides', 'Only one chemical used repeatedly', 'No monitoring'], 0,
    'Selective chemicals protect predators and delay resistance.'],
] }
);
