/* PYQ-linked MCQs — IFoS 2017 Agriculture Paper II, Q5–Q8 (verbatim PYQs; some marks illegible in source). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Floriculture & Landscaping', w: 2, pyq: 'IFoS-2017-A2-Q5a', q: [
  ['Pinching in carnation means:', ['Removing the growing tip to make the plant branch', 'Removing flowers', 'Removing roots', 'Removing leaves only'], 0,
    'More branches mean more flowering stems.'],
  ['Carnation (*Dianthus caryophyllus*) belongs to the family:', ['Caryophyllaceae', 'Asteraceae', 'Rosaceae', 'Liliaceae'], 0,
    'It is a leading cut flower worldwide.'],
  ['The first pinch in carnation is usually given:', ['About 4–6 weeks after planting, at the 5–6 node stage', 'At flowering', 'At harvest', 'Before planting'], 0,
    'About 4–5 pairs of leaves are left on the stem.'],
  ['The three pinching systems in carnation are:', ['Single pinch, pinch-and-a-half and double pinch', 'Early, late and none', 'Root, shoot and leaf pinch', 'Summer, winter and spring pinch'], 0,
    'They control the timing and spread of flowering.'],
  ['A single pinch in carnation gives:', ['One early, concentrated flush of flowers', 'Flowers spread over a long period', 'No flowers', 'Only one flower'], 0,
    'All the laterals develop at the same time.'],
  ['A double pinch, in which the laterals are pinched again:', ['Gives more flowers, later and over a longer period', 'Gives fewer flowers', 'Stops flowering', 'Gives one early flush only'], 0,
    'Pinch-and-a-half pinches only half the laterals.'],
  ['In standard carnations, disbudding means:', ['Removing the side buds so that the terminal bud forms one large flower', 'Removing the terminal bud', 'Removing all buds', 'Removing leaves'], 0,
    'In spray types, the terminal bud is removed instead.'],
  ['Spray carnations are produced by:', ['Removing the terminal bud so that several side buds open together', 'Keeping only the terminal bud', 'Not pinching at all', 'Removing all side shoots'], 0,
    'Each stem carries several smaller flowers.'],
  ['In India, commercial carnations are mostly grown:', ['Under polyhouses, e.g., around Bengaluru, Pune and in Himachal Pradesh', 'In open fields in the Thar desert', 'In mangrove swamps', 'Only in Kerala plains'], 0,
    'They need cool, bright conditions.'],
  ['Calyx splitting in carnation, a disorder that lowers flower quality, is linked to:', ['Low and fluctuating temperatures (and boron deficiency)', 'Excess sunlight only', 'Insects', 'Viruses'], 0,
    'Calyx bands are used to prevent it.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: 'IFoS-2017-A2-Q5b', q: [
  ['A preventive measure against stored-grain pests is:', ['Cleaning and disinfesting stores and bags before loading new grain', 'Storing moist grain', 'Mixing old and new grain', 'Keeping stores open to rain'], 0,
    'Residual infestation is a major source of new attack.'],
  ['For prophylaxis in godowns, malathion or deltamethrin is sprayed:', ['On walls, floors and bag surfaces, not directly on the grain', 'Directly into the grain', 'On the farmers', 'In the field only'], 0,
    'This kills insects moving into or across the stacks.'],
  ['The main curative treatment for infested stored grain is:', ['Fumigation with aluminium phosphide (phosphine) under gas-proof covers', 'Spraying water', 'Sun-drying only', 'Adding urea'], 0,
    'Exposure usually lasts five to seven days.'],
  ['Methyl bromide is now largely restricted because it:', ['Depletes the ozone layer (Montreal Protocol)', 'Is ineffective', 'Is too cheap', 'Is edible'], 0,
    'It is allowed mainly for quarantine and pre-shipment use.'],
  ['Hermetic storage kills stored-grain insects by:', ['Using up oxygen and raising carbon dioxide in the sealed container', 'Heating the grain', 'Adding pesticides', 'Letting in light'], 0,
    'PICS bags work on this principle.'],
  ['CAP storage used by the FCI means:', ['Cover and plinth — grain stacked on raised plinths under covers', 'Cold air preservation', 'Controlled atmosphere packing', 'Central agricultural procurement'], 0,
    'It is a cheap but risky form of storage.'],
  ['Phosphine resistance has been reported in:', ['*Rhyzopertha dominica* and *Tribolium castaneum*', 'Honeybees', 'Earthworms', 'Rice plants'], 0,
    'Poorly sealed fumigation encourages resistance.'],
  ['Sun-drying pulses before storage helps because:', ['Heat kills the eggs and larvae of pulse beetles', 'It adds moisture', 'It adds nutrients', 'It attracts insects'], 0,
    'It also lowers moisture to a safe level.'],
  ['Traps used to monitor insects in stored grain include:', ['Probe traps and pheromone traps', 'Light traps in the field only', 'Yellow sticky traps on crops', 'Fish nets'], 0,
    'Monitoring shows when treatment is needed.'],
  ['A traditional botanical protectant for stored grain is:', ['Dried neem leaves mixed with the grain', 'Common salt', 'Diesel', 'Cement'], 0,
    'Coating pulses with edible oil also works.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 3, pyq: 'IFoS-2017-A2-Q5c', q: [
  ['*Fusarium* and *Verticillium* are both:', ['Soil-borne fungi that cause vascular wilts', 'Leaf-spotting bacteria', 'Viruses', 'Nematodes'], 0,
    'They block the xylem and cause wilting.'],
  ['*Fusarium oxysporum* survives in soil for many years as:', ['Chlamydospores', 'Microsclerotia', 'Oospores', 'Teliospores'], 0,
    '*Verticillium dahliae* survives as microsclerotia.'],
  ['*Verticillium* wilt is favoured by:', ['Cooler temperatures (about 20–25 °C)', 'Very hot weather (above 35 °C)', 'Dry, frosty weather', 'Flooding only'], 0,
    '*Fusarium* wilt is favoured by warmer soils (about 27–30 °C).'],
  ['Crop rotation works better against *Fusarium* than *Verticillium* because:', ['*Fusarium oxysporum* forms are host-specific, while *Verticillium dahliae* has a very wide host range', '*Fusarium* has no spores', '*Verticillium* dies quickly', 'Neither survives in soil'], 0,
    '*V. dahliae* attacks cotton, potato, tomato, brinjal and many weeds.'],
  ['Resistance genes used in tomato are:', ['*Ve* against *Verticillium* and *I* genes against *Fusarium* races', '*Sr31* against rust', '*Xa21* against blight', '*Bt* against insects'], 0,
    'Resistant varieties are the cheapest control.'],
  ['Soil solarisation helps manage vascular wilts by:', ['Killing propagules in the upper soil layer with solar heat', 'Adding fungicide', 'Adding nitrogen', 'Increasing soil moisture'], 0,
    'It is best done in the hottest months.'],
  ['Biological agents used against wilt fungi include:', ['*Trichoderma* and *Pseudomonas fluorescens*', 'Bt', 'Neem oil only', 'Ladybird beetles'], 0,
    'They are applied to seed, nursery soil and field soil.'],
  ['Grafting watermelon onto bottle gourd rootstock helps control:', ['Fusarium wilt', 'Powdery mildew', 'Aphids', 'Fruit flies'], 0,
    'Grafting is also used in tomato and brinjal.'],
  ['Fusarium wilt is often less severe when:', ['Soil pH is raised to near neutral and nitrate rather than ammonium nitrogen is used', 'Soil is made very acidic', 'Heavy ammonium doses are applied', 'Root-knot nematodes are present'], 0,
    'Liming acid soils reduces the disease.'],
  ['Root-knot nematodes (*Meloidogyne*) make wilts worse because they:', ['Wound roots, letting wilt fungi in and breaking resistance', 'Kill the fungi', 'Feed on leaves only', 'Have no effect'], 0,
    'This combination is called a disease complex.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: 'IFoS-2017-A2-Q5d', q: [
  ['*Bacillus thuringiensis* kills insects mainly through:', ['Crystal (Cry) δ-endotoxins formed during sporulation', 'Fungal hyphae', 'Viral particles', 'Nematode attack'], 0,
    'It is a Gram-positive, spore-forming bacterium.'],
  ['Bt var. *kurstaki* is most effective against:', ['Caterpillars (Lepidoptera)', 'Mosquito larvae', 'Beetle grubs', 'Aphids'], 0,
    'Bt var. *israelensis* kills mosquito and blackfly larvae.'],
  ['Bt toxins work when:', ['Ingested, dissolved in the alkaline insect midgut, activated and bound to gut receptors', 'They touch the insect’s skin', 'The insect breathes them in', 'They are sprayed on eggs'], 0,
    'Pores in the gut lining lead to septicaemia and death.'],
  ['Bt is safe for humans and other vertebrates because:', ['They lack the gut receptors, and their acidic stomachs do not activate the toxin', 'Bt is not a toxin', 'Vertebrates are immune to all bacteria', 'Bt is killed by sunlight before eating'], 0,
    'This selectivity is its main advantage.'],
  ['Bt was first isolated in 1901 from diseased silkworms by:', ['Ishiwata in Japan', 'Berliner in Germany', 'Pasteur in France', 'Koch in Germany'], 0,
    'Berliner named it after Thuringia in 1911.'],
  ['Milky disease of Japanese beetle grubs is caused by:', ['*Paenibacillus popilliae*', '*Bacillus thuringiensis*', '*Serratia marcescens*', '*Escherichia coli*'], 0,
    'It turns the grubs’ blood milky white.'],
  ['*Lysinibacillus* (*Bacillus*) *sphaericus* is used to control:', ['Mosquito larvae', 'Caterpillars', 'Aphids', 'Termites'], 0,
    'It persists longer in polluted water than Bt var. *israelensis*.'],
  ['*Photorhabdus* and *Xenorhabdus* bacteria kill insects as:', ['Symbionts carried by entomopathogenic nematodes', 'Free-living soil bacteria only', 'Plant pathogens', 'Viruses'], 0,
    'The nematodes release them inside the insect.'],
  ['Bt sprays are best applied in the evening because:', ['Sunlight (UV) quickly breaks down the toxin', 'Insects sleep at night', 'Dew makes it toxic', 'It needs darkness to grow'], 0,
    'Larvae must also eat the treated leaves soon after spraying.'],
  ['Besides Cry toxins, some Bt strains produce vegetative insecticidal proteins (Vip), which:', ['Are secreted during vegetative growth and act on different gut receptors', 'Are the same as Cry toxins', 'Kill plants', 'Are antibiotics'], 0,
    'Vip3A is used in some Bt cotton and maize varieties.']
] },
{ p: 'A2', t: 'Post-harvest & Food Processing', w: 3, pyq: 'IFoS-2017-A2-Q5e', q: [
  ['Fruit preservation works by:', ['Destroying or inhibiting microbes and enzymes with heat, cold, drying, chemicals, sugar or acid', 'Adding water', 'Speeding up ripening', 'Adding microbes that spoil food'], 0,
    'Each method targets microbial growth and enzyme action.'],
  ['Canning was invented by:', ['Nicolas Appert (about 1810)', 'Louis Pasteur', 'Peter Durand only', 'Clarence Birdseye'], 0,
    'He is called the father of canning.'],
  ['Jam sets into a gel because of the right balance of:', ['Pectin, sugar and acid', 'Salt and oil', 'Starch and water', 'Protein and fat'], 0,
    'The best pH for setting is about 3.0–3.2.'],
  ['Jam must contain total soluble solids of about:', ['65–68%', '10%', '30%', '90%'], 0,
    'High sugar concentration prevents microbial growth.'],
  ['A fruit squash must contain at least:', ['25% fruit juice and 40% total soluble solids', '5% juice and 10% TSS', '100% juice', 'No juice'], 0,
    'It is diluted before drinking.'],
  ['Potassium metabisulphite (KMS) is used to preserve:', ['Light-coloured fruit products, but not deeply coloured ones', 'Only red fruits', 'Only meat', 'Only milk'], 0,
    'Its sulphur dioxide bleaches anthocyanins.'],
  ['Sodium benzoate is preferred for:', ['Coloured products such as jamun or kokum squash', 'Light-coloured products only', 'Canned vegetables', 'Dried fruits'], 0,
    'It works best in acidic foods.'],
  ['Grapes are dipped in ethyl oleate and potassium carbonate before making raisins to:', ['Speed up drying by breaking down the waxy skin layer', 'Add sugar', 'Kill insects', 'Colour them'], 0,
    'It also gives a better colour.'],
  ['Irradiation of mangoes for export is done mainly to:', ['Meet quarantine rules by killing fruit fly and seed weevil pests', 'Ripen them', 'Colour them', 'Add vitamins'], 0,
    'Low doses leave no radioactivity.'],
  ['Aam papad (mango leather) and aonla murabba are examples of:', ['Traditional preserved fruit products using drying and sugar', 'Fermented drinks', 'Frozen foods', 'Canned vegetables'], 0,
    'These are value-added products for rural enterprise.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: 'IFoS-2017-A2-Q6a', q: [
  ['The most destructive insect pest of cauliflower and other crucifers worldwide is:', ['Diamondback moth (*Plutella xylostella*)', 'Pink bollworm', 'Brown planthopper', 'Fruit fly'], 0,
    'It has developed resistance to many insecticides.'],
  ['Diamondback moth was the first insect to evolve field resistance to:', ['*Bacillus thuringiensis* sprays', 'DDT', 'Neem', 'Pyrethrum'], 0,
    'This was reported in Hawaii.'],
  ['A trap crop recommended by IIHR for diamondback moth in cauliflower and cabbage is:', ['Indian mustard, two rows for every 25 rows of the main crop', 'Maize', 'Marigold only', 'Rice'], 0,
    'The moths prefer to lay eggs on mustard.'],
  ['An important larval parasitoid of diamondback moth is:', ['*Cotesia plutellae* (*C. vestalis*)', '*Trichogramma chilonis* only', '*Encarsia formosa*', '*Rodolia cardinalis*'], 0,
    '*Diadegma semiclausum* is used in the hills.'],
  ['The cabbage butterfly (*Pieris brassicae*) damages cauliflower by:', ['Gregarious caterpillars feeding on the leaves', 'Sucking sap', 'Boring into roots', 'Spreading viruses only'], 0,
    'It is common in the hills and in north India in winter.'],
  ['The aphids that infest cauliflower include:', ['*Brevicoryne brassicae* and *Lipaphis erysimi*', '*Aphis gossypii* only', '*Myzus persicae* only', 'None'], 0,
    'They suck sap and make the curds sticky.'],
  ['The cabbage head borer (*Hellula undalis*) damages plants by:', ['Boring into the growing point, often killing the young plant or making it branch', 'Feeding only on flowers', 'Sucking sap', 'Eating roots'], 0,
    'It is serious in early-planted cauliflower.'],
  ['The painted bug (*Bagrada hilaris*) mainly attacks:', ['Crucifer seedlings and young plants, by sucking sap', 'Rice grains', 'Mango flowers', 'Stored pulses'], 0,
    'Damaged seedlings wilt and dry.'],
  ['Eco-friendly sprays against caterpillars on cauliflower include:', ['Bt formulations and neem seed kernel extract (NSKE 5%)', 'DDT', 'Methyl bromide', 'Endosulfan'], 0,
    'They spare natural enemies.'],
  ['Pheromone traps in cauliflower fields are used to:', ['Monitor and mass-trap diamondback moth males', 'Kill aphids', 'Attract bees', 'Repel birds'], 0,
    'Catches show when to spray.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: 'IFoS-2017-A2-Q6b', q: [
  ['For 1,000 litres of spray at 0.02% strength, the active ingredient needed is:', ['0.2 litre (200 mL)', '2 litres', '20 litres', '0.02 litre'], 0,
    '1,000 × 0.02 ÷ 100 = 0.2 L.'],
  ['The amount of Chlorpyriphos 20 EC needed to supply 0.2 L of active ingredient is:', ['1 litre', '0.2 litre', '4 litres', '2 litres'], 0,
    '0.2 × 100 ÷ 20 = 1 L.'],
  ['To make a 0.02% spray from Chlorpyriphos 20 EC, each litre of water needs:', ['1 mL of the formulation', '10 mL', '0.1 mL', '100 mL'], 0,
    '1 L of product in 1,000 L of water.'],
  ['A 0.02% concentration equals:', ['200 ppm', '20 ppm', '2,000 ppm', '2 ppm'], 0,
    '1% = 10,000 ppm.'],
  ['If a 50 EC formulation were used for the same 1,000 L at 0.02%, the amount needed would be:', ['0.4 litre', '1 litre', '2.5 litres', '0.2 litre'], 0,
    '0.2 × 100 ÷ 50 = 0.4 L.'],
  ['For 500 litres of spray at 0.02% using Chlorpyriphos 20 EC, the amount needed is:', ['0.5 litre', '1 litre', '2 litres', '0.1 litre'], 0,
    'Half the spray volume needs half the product.'],
  ['For 1,000 litres at 0.05% using a 20 EC formulation, the amount needed is:', ['2.5 litres', '1 litre', '5 litres', '0.5 litre'], 0,
    '1,000 × 0.05 ÷ 100 = 0.5 L a.i.; 0.5 × 100 ÷ 20 = 2.5 L.'],
  ['For 1,000 litres at 0.04% using a 20 EC formulation, the amount needed is:', ['2 litres', '4 litres', '1 litre', '0.8 litre'], 0,
    '0.4 L a.i. ÷ 0.2 = 2 L.'],
  ['Chlorpyriphos belongs to the insecticide group:', ['Organophosphates', 'Synthetic pyrethroids', 'Neonicotinoids', 'Carbamates'], 0,
    'It inhibits acetylcholinesterase.'],
  ['The quantity of formulation needed is found by:', ['Spray volume × required concentration ÷ % active ingredient in the formulation', 'Spray volume × % a.i.', 'Area ÷ concentration', 'Concentration ÷ spray volume'], 0,
    'Keep all quantities in the same units.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: 'IFoS-2017-A2-Q6c', q: [
  ['A major constraint in food grain procurement is that it is:', ['Concentrated in a few states and in wheat and rice', 'Spread evenly across all crops', 'Absent in Punjab', 'Limited to pulses'], 0,
    'Farmers elsewhere often sell below MSP.'],
  ['The Decentralised Procurement (DCP) scheme, begun in 1997–98, lets:', ['States procure, store and distribute grain themselves', 'Only FCI procure', 'Private firms only procure', 'No state procure'], 0,
    'It aims to spread procurement and cut transport costs.'],
  ['The High-Level Committee on restructuring FCI (2015) was chaired by:', ['Shanta Kumar', 'M. S. Swaminathan', 'Ashok Dalwai', 'Ramesh Chand'], 0,
    'It found that only about 6% of farmers sold grain at MSP to procurement agencies.'],
  ['The maximum moisture allowed in paddy at procurement is about:', ['17%', '5%', '30%', '40%'], 0,
    'Wetter grain is liable to rot or be rejected.'],
  ['A major storage constraint in grain procurement is:', ['Too little scientific storage, forcing use of open CAP storage with losses', 'Too many silos', 'Too little grain', 'No need for storage'], 0,
    'Steel silos under public–private partnership are being built.'],
  ['Under the custom-milled rice (CMR) system:', ['Paddy procured by agencies is milled by private millers, who deliver the rice to the central pool', 'Farmers mill their own rice', 'FCI owns all mills', 'Paddy is exported unmilled'], 0,
    'Delays and quality problems are common.'],
  ['Old huller mills are a processing constraint because they:', ['Give low rice outturn and many broken grains', 'Give very high outturn', 'Need no power', 'Produce brown rice only'], 0,
    'Modern rubber-roll mills improve recovery.'],
  ['Large central grain stocks beyond buffer norms lead to:', ['High storage costs and losses', 'Lower costs', 'Better quality always', 'Nothing'], 0,
    'Excess stocks are sold through the Open Market Sale Scheme.'],
  ['"One Nation One Ration Card" improves distribution by:', ['Letting ration-card holders draw their grain from any fair-price shop in India', 'Stopping PDS', 'Giving cash instead of grain', 'Restricting migrants'], 0,
    'It especially helps migrant workers.'],
  ['Post-harvest losses of food grains in India occur mainly during:', ['Threshing, drying, storage and transport', 'Sowing', 'Irrigation', 'Flowering'], 0,
    'Good storage and handling can cut them sharply.']
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 2, pyq: 'IFoS-2017-A2-Q7a', q: [
  ['Olericulture is the science of growing:', ['Vegetables', 'Fruits', 'Flowers', 'Spices'], 0,
    'The word comes from the Latin *oleris*, "pot herb".'],
  ['Pomology is the science of growing:', ['Fruits', 'Vegetables', 'Flowers', 'Trees for timber'], 0,
    'Floriculture deals with flowers.'],
  ['Compared with fruit crops, vegetable crops are mostly:', ['Herbaceous and short-lived (annuals or biennials)', 'Woody perennials', 'Trees living for decades', 'Grown only by grafting'], 0,
    'Most fruit crops are woody perennials.'],
  ['Most vegetables are propagated by seed, but exceptions include:', ['Potato, sweet potato and garlic, propagated vegetatively', 'Tomato', 'Brinjal', 'Cauliflower'], 0,
    'Vegetative propagation keeps these clones true to type.'],
  ['Fruit crops are usually propagated vegetatively (grafting, budding, layering) to:', ['Keep the variety true to type and shorten the juvenile period', 'Increase genetic variation', 'Make them seedless', 'Reduce yield'], 0,
    'Seedling trees are variable and slow to bear.'],
  ['Horticulturally, tomato is a vegetable, but botanically it is a:', ['Fruit (a berry)', 'Root', 'Stem', 'Leaf'], 0,
    'Culinary use decides the horticultural category.'],
  ['India’s rank in world production of fruits and vegetables is:', ['Second, after China', 'First', 'Tenth', 'Fifth'], 0,
    'India leads in mango, banana and papaya.'],
  ['The ICAR institute dedicated to vegetable research is:', ['IIVR, Varanasi', 'CISH, Lucknow', 'NRC Banana, Tiruchirappalli', 'CITH, Srinagar'], 0,
    'IIHR, Bengaluru works on both fruits and vegetables.'],
  ['Vegetables usually raised in a nursery and transplanted include:', ['Tomato, brinjal, chilli and cole crops', 'Carrot and radish', 'Peas and beans', 'Potato'], 0,
    'Root crops are sown directly.'],
  ['Skills central to pomology rather than olericulture include:', ['Orchard layout, training and pruning of trees', 'Nursery transplanting only', 'Seed production of annuals only', 'Hydroponics only'], 0,
    'Fruit trees remain in the field for decades.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 3, pyq: 'IFoS-2017-A2-Q7b', q: [
  ['Powdery mildews are caused by:', ['Erysiphales (Ascomycota), which grow as white powdery patches on the leaf surface', 'Oomycetes, with downy growth on the underside', 'Bacteria', 'Viruses'], 0,
    'Their mycelium stays on the surface, sending haustoria into epidermal cells.'],
  ['Downy mildews are caused by:', ['Oomycetes (Peronosporales), whose sporangiophores emerge through stomata on the lower leaf surface', 'Erysiphales', 'Rust fungi', 'Bacteria'], 0,
    'They grow inside the leaf between the cells.'],
  ['Powdery mildews are favoured by:', ['Warm, dry days with cool nights', 'Continuous rain', 'Flooding', 'Freezing weather'], 0,
    'Free water can actually hinder their spores.'],
  ['Downy mildews are favoured by:', ['Cool, humid, wet conditions', 'Hot, dry weather', 'Drought', 'Strong sunlight'], 0,
    'Their zoospores need free water.'],
  ['A "blight" is:', ['A symptom — rapid browning and death of leaves, shoots or whole plants', 'Always a fungus', 'Always a virus', 'A nutrient deficiency'], 0,
    'Blights can be caused by fungi, oomycetes or bacteria.'],
  ['Examples of blights include:', ['Late blight of potato, early blight of tomato and bacterial leaf blight of rice', 'Powdery mildew of pea', 'Green ear of pearl millet', 'White rust of mustard'], 0,
    'Their pathogens are *Phytophthora*, *Alternaria* and *Xanthomonas*.'],
  ['Powdery mildews are usually controlled with:', ['Sulphur, dinocap or triazole fungicides', 'Metalaxyl', 'Antibiotics', 'Copper only'], 0,
    'Sulphur is cheap and effective.'],
  ['Downy mildews are usually controlled with:', ['Metalaxyl, mancozeb or Bordeaux mixture', 'Sulphur', 'Streptomycin', 'Carbendazim only'], 0,
    'Metalaxyl is specific to oomycetes.'],
  ['Green ear disease of pearl millet, a downy mildew, is caused by:', ['*Sclerospora graminicola*', '*Erysiphe polygoni*', '*Blumeria graminis*', '*Oidium mangiferae*'], 0,
    'The flowers turn into leafy structures.'],
  ['The late blight epidemic of potato in the 1840s caused:', ['The Irish potato famine', 'The Bengal famine', 'The Dust Bowl', 'The Green Revolution'], 0,
    'It was caused by *Phytophthora infestans*.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: 'IFoS-2017-A2-Q7c', q: [
  ['Augmentative biological control means:', ['Increasing natural enemy numbers by releasing them, inoculatively or inundatively', 'Importing new natural enemies from abroad for permanent establishment', 'Killing natural enemies', 'Using only chemicals'], 0,
    'Introducing exotic enemies for permanent establishment is classical biocontrol.'],
  ['An inoculative release involves:', ['Releasing a few natural enemies early, so their offspring provide control later in the season', 'Releasing huge numbers for immediate kill', 'Spraying insecticides', 'Releasing sterile insects'], 0,
    'Control depends on the natural enemies reproducing.'],
  ['An inundative release involves:', ['Releasing large numbers for quick control, like a living insecticide, without relying on their reproduction', 'Releasing a few natural enemies', 'Importing enemies once', 'Protecting habitats'], 0,
    'Repeated *Trichogramma* releases are the classic example.'],
  ['*Encarsia formosa*, used in greenhouses against whitefly, is usually released:', ['Inoculatively, early in the crop', 'Inundatively only', 'As a classical introduction only', 'Never'], 0,
    'It multiplies on the whitefly population.'],
  ['*Phytoseiulus persimilis* is released in greenhouses to control:', ['Spider mites', 'Aphids', 'Caterpillars', 'Whiteflies'], 0,
    'It is a predatory mite.'],
  ['*Trichogramma* egg parasitoids are mass-reared in the laboratory on eggs of:', ['The rice moth *Corcyra cephalonica*', 'Silkworm', 'Housefly', 'Honeybee'], 0,
    'The parasitised eggs are glued onto "Tricho-cards".'],
  ['Conservation biological control means:', ['Changing practices and habitats to protect and encourage natural enemies already present', 'Releasing reared enemies', 'Importing enemies', 'Spraying broad-spectrum insecticides'], 0,
    'Examples are flowering border plants and selective pesticides.'],
  ['The Indian institute responsible for biological control research and natural enemy supply is:', ['NBAIR, Bengaluru', 'NBPGR, New Delhi', 'NBFGR, Lucknow', 'NBAGR, Karnal'], 0,
    'It is the National Bureau of Agricultural Insect Resources.'],
  ['Releasing *Cryptolaemus montrouzieri* against mealybugs in orchards is an example of:', ['Augmentative release of a predator', 'Chemical control', 'Cultural control', 'Host-plant resistance'], 0,
    'It is used in grapes, citrus and coffee.'],
  ['The main difference between inoculative and inundative releases is:', ['Inoculative relies on the natural enemies’ reproduction; inundative relies on the released individuals themselves', 'Both rely on reproduction', 'Neither uses natural enemies', 'Inundative uses fewer individuals'], 0,
    'Inundative releases need mass production facilities.']
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 3, pyq: 'IFoS-2017-A2-Q8a', q: [
  ['When selecting a site for an orchard, the key factors are:', ['Climate, soil depth and drainage, water supply, and access to markets', 'Only land price', 'Only nearness to a city', 'Only soil colour'], 0,
    'Mistakes are costly because orchards last for decades.'],
  ['The hexagonal layout accommodates about how many more trees than the square layout?', ['About 15% more', 'About 50% more', 'The same number', 'Fewer trees'], 0,
    'Trees are placed at the corners of equilateral triangles.'],
  ['In the quincunx layout, a fifth tree is planted:', ['At the centre of each square, usually as a short-lived filler', 'Outside the orchard', 'On the roads', 'Nowhere'], 0,
    'Fillers such as papaya or guava give early income.'],
  ['On hill slopes, orchards are laid out using the:', ['Contour system', 'Square system', 'Rectangular system', 'Random system'], 0,
    'Trees are planted along contour terraces.'],
  ['Windbreaks around an orchard are planted:', ['On the side facing the prevailing wind, a year or two before the fruit trees', 'In the middle of the orchard', 'After the trees bear fruit', 'Only on the downwind side'], 0,
    'Jamun, mulberry and eucalyptus are common windbreak species.'],
  ['The conventional spacing for mango orchards is about:', ['10 m × 10 m', '1 m × 1 m', '30 m × 30 m', '3 m × 3 m'], 0,
    'High-density planting of Amrapali uses about 2.5 m × 2.5 m.'],
  ['Planting pits for mango are typically:', ['About 1 m × 1 m × 1 m, filled with topsoil and farmyard manure', 'About 10 cm deep', 'Not needed', 'Filled with sand only'], 0,
    'Pits are dug and filled before the monsoon.'],
  ['Self-incompatible apple varieties such as Delicious need:', ['Pollinizer varieties planted among them, plus beehives', 'No pollination', 'Hand pollination only', 'Wind pollination only'], 0,
    'Roughly one pollinizer tree to every eight or nine is common.'],
  ['Choosing early, mid-season and late varieties in an orchard helps to:', ['Spread the harvest and marketing period', 'Reduce yield', 'Increase pests', 'Make pruning harder'], 0,
    'It avoids a glut at one time.'],
  ['An orchard plan must also provide for:', ['Irrigation and drainage channels, roads, fencing and a packing area', 'Only trees', 'Only a well', 'Nothing else'], 0,
    'Good planning lowers running costs for decades.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 3, pyq: 'IFoS-2017-A2-Q8b', q: [
  ['Kwashiorkor is caused mainly by:', ['Protein deficiency with a relatively adequate calorie intake', 'Excess protein', 'Vitamin C deficiency', 'Iodine deficiency'], 0,
    'Cicely Williams described it in Ghana in 1933.'],
  ['Kwashiorkor is recognised by:', ['Oedema, "flaky-paint" skin, a moon face and a fatty liver', 'Severe wasting without oedema', 'Night blindness', 'Goitre'], 0,
    'The oedema can hide the underlying weight loss.'],
  ['Marasmus is caused by:', ['A severe deficiency of both energy and protein', 'Excess calories', 'Protein deficiency alone with enough calories', 'Iron deficiency'], 0,
    'It causes extreme wasting — an "old man’s face" with no oedema.'],
  ['Stunting in children is measured by:', ['Low height-for-age', 'Low weight-for-height', 'Low weight-for-age', 'High BMI'], 0,
    'Wasting is low weight-for-height; underweight is low weight-for-age.'],
  ['According to NFHS-5 (2019–21), the share of stunted children under five in India is about:', ['35%', '5%', '60%', '15%'], 0,
    'Wasting was about 19% and underweight about 32% (check the latest survey).'],
  ['A mid-upper arm circumference (MUAC) below 11.5 cm in a child aged 6–59 months indicates:', ['Severe acute malnutrition', 'Normal nutrition', 'Obesity', 'Mild anaemia'], 0,
    'Such children are referred to nutrition rehabilitation centres.'],
  ['India’s oldest programme to tackle child malnutrition, launched in 1975, is:', ['ICDS (anganwadi services)', 'MGNREGA', 'PM-KISAN', 'PMFBY'], 0,
    'POSHAN Abhiyaan (2018) and PM POSHAN (school meals) followed.'],
  ['Combining cereals and pulses improves protein quality because:', ['Cereals lack lysine and pulses lack methionine, so each makes up for the other', 'Both lack all amino acids', 'Pulses have no protein', 'Cereals have no protein'], 0,
    'Dal–rice and khichdi are good examples.'],
  ['Quality protein maize (QPM) contains more lysine and tryptophan because of the gene:', ['*opaque-2*', '*Sub1*', '*Rht*', '*Bt*'], 0,
    'It improves the protein value of maize-based diets.'],
  ['The Gomez classification of malnutrition is based on:', ['Weight-for-age compared with a reference', 'Height only', 'Blood tests', 'Skin colour'], 0,
    'It grades malnutrition as mild, moderate or severe.']
] },
{ p: 'A2', t: 'Floriculture & Landscaping', w: 2, pyq: 'IFoS-2017-A2-Q8c', q: [
  ['Chrysanthemum is a:', ['Short-day plant of the family Asteraceae', 'Long-day plant of Rosaceae', 'Day-neutral grass', 'Bulbous monocot'], 0,
    'It is called the "Queen of the East".'],
  ['Pinching in chrysanthemum is done to:', ['Remove the growing tip and produce more laterals, giving a bushy plant with many flowers', 'Get one large flower', 'Kill the plant', 'Delay rooting'], 0,
    'It is standard for spray and pot mums.'],
  ['Disbudding in chrysanthemum means:', ['Removing side buds so the terminal (crown) bud forms one large bloom', 'Removing the terminal bud only', 'Removing all leaves', 'Removing the roots'], 0,
    'This produces "standard" or exhibition blooms.'],
  ['"Stopping" in chrysanthemum refers to:', ['Pinching at a set time to control when the crown bud forms', 'Stopping irrigation', 'Stopping fertiliser', 'Stopping growth permanently'], 0,
    'Growers speak of the first and second crown buds.'],
  ['The cascade form of chrysanthemum is made by:', ['Training small-flowered varieties to trail downwards along a wire frame', 'Growing one large bloom', 'Growing in water', 'Grafting onto roses'], 0,
    'It is popular in Japan and at flower shows.'],
  ['Tall standard chrysanthemums with large blooms need:', ['Staking with bamboo or wire supports', 'No support', 'Grafting', 'Shading only'], 0,
    'Heavy blooms can bend or break the stems.'],
  ['Flowering of chrysanthemum out of season can be induced by:', ['Covering the plants with black cloth to give short days', 'Giving long days with lights', 'Heavy irrigation', 'Removing leaves'], 0,
    'Night-break lighting delays flowering.'],
  ['Chrysanthemums are usually propagated by:', ['Terminal cuttings and suckers', 'Seed only', 'Grafting', 'Bulbs'], 0,
    'This keeps varieties true to type.'],
  ['Removing unwanted basal shoots and suckers in chrysanthemum is called:', ['De-shooting', 'Pinching', 'Disbudding', 'Stopping'], 0,
    'It directs energy to the main stems.'],
  ['Training forms of chrysanthemum include:', ['Standard, spray, bush, cascade and bonsai', 'Only standard', 'Only bonsai', 'Espalier only'], 0,
    'Each form suits a different use or show class.']
] }
);
