/* PYQ-linked MCQs — IFoS 2018 Agriculture Paper II, Q1–Q4 (verbatim PYQs). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: 'IFoS-2018-A2-Q1a', q: [
  ['The "powerhouse of the cell" is the:', ['Mitochondrion', 'Nucleus', 'Golgi body', 'Ribosome'], 0,
    'It makes most of the cell’s ATP by aerobic respiration.'],
  ['The folds of the inner mitochondrial membrane, called cristae, serve to:', ['Increase the surface area for the electron transport chain and ATP synthase', 'Store starch', 'Hold the mitochondrial DNA', 'Make ribosomes'], 0,
    'Very active cells, such as those of flight muscle, have densely packed cristae.'],
  ['The outer mitochondrial membrane is freely permeable to small molecules because of:', ['Porins', 'Aquaporins only', 'Cellulose', 'Chitin'], 0,
    'The inner membrane is highly impermeable.'],
  ['The electron transport chain and ATP synthase are located in the:', ['Inner mitochondrial membrane', 'Outer membrane', 'Matrix', 'Intermembrane space only'], 0,
    'ATP synthase particles are also called oxysomes or F₁ particles.'],
  ['The mitochondrial matrix contains:', ['Krebs cycle enzymes, circular DNA and 70S ribosomes', 'Chlorophyll', 'Cellulose', 'Glycolytic enzymes only'], 0,
    'Glycolysis takes place in the cytosol.'],
  ['A phospholipid characteristic of the inner mitochondrial membrane is:', ['Cardiolipin', 'Cholesterol', 'Lecithin only', 'Sphingomyelin only'], 0,
    'It is also found in bacterial membranes, which supports their bacterial origin.'],
  ['Mitochondria are believed to have evolved from:', ['Endosymbiotic α-proteobacteria', 'Cyanobacteria', 'Viruses', 'Fungi'], 0,
    'Chloroplasts evolved from cyanobacteria.'],
  ['In most plants, mitochondrial DNA is inherited:', ['Maternally, through the egg cytoplasm', 'Paternally only', 'From both parents equally', 'Not at all'], 0,
    'Cytoplasmic male sterility genes are carried in mitochondrial DNA.'],
  ['The vital stain used to show mitochondria in living cells is:', ['Janus green B', 'Safranin', 'Iodine', 'Methylene blue only'], 0,
    'It stays oxidised (coloured) only in active mitochondria.'],
  ['The term "mitochondrion" was coined by:', ['C. Benda (1898)', 'R. Brown', 'C. de Duve', 'G. Palade'], 0,
    'Altmann had earlier called them "bioblasts".']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 3, pyq: 'IFoS-2018-A2-Q1b', q: [
  ['Mendel worked out his laws using:', ['The garden pea (*Pisum sativum*), with seven contrasting characters', 'Fruit flies', 'Maize', 'Four o’clock plants'], 0,
    'His paper was read in 1865 and published in 1866.'],
  ['When a pure tall pea is crossed with a pure dwarf pea, all F₁ plants are tall. This illustrates:', ['The law of dominance', 'The law of independent assortment', 'Incomplete dominance', 'Linkage'], 0,
    'The dwarf allele is hidden, not lost.'],
  ['The law of segregation states that:', ['The two alleles of a gene separate into different gametes', 'Genes on different chromosomes are linked', 'All genes are dominant', 'Traits blend in offspring'], 0,
    'A monohybrid F₂ shows a 3:1 phenotypic ratio.'],
  ['The genotypic ratio in the F₂ of a monohybrid cross is:', ['1:2:1', '3:1', '9:3:3:1', '1:1'], 0,
    'Homozygous dominant : heterozygous : homozygous recessive.'],
  ['The law of independent assortment is shown by the F₂ phenotypic ratio of a dihybrid cross:', ['9:3:3:1', '3:1', '1:2:1', '1:1:1:1'], 0,
    'Mendel used round/wrinkled and yellow/green seeds.'],
  ['A test cross of a dihybrid F₁ (*RrYy*) with a double recessive gives the ratio:', ['1:1:1:1', '9:3:3:1', '3:1', '1:2:1'], 0,
    'Each of the four gamete types is equally frequent.'],
  ['In *Mirabilis jalapa*, red × white gives pink F₁ plants and a 1:2:1 F₂. This is:', ['Incomplete dominance', 'Complete dominance', 'Codominance', 'Epistasis'], 0,
    'The phenotypic and genotypic ratios are the same.'],
  ['The ABO blood groups, where both *Iᴬ* and *Iᴮ* are expressed together, show:', ['Codominance', 'Incomplete dominance', 'Complete dominance', 'Linkage'], 0,
    'Both alleles show fully in the heterozygote.'],
  ['Mendel’s work was rediscovered in 1900 by:', ['Hugo de Vries, Carl Correns and Erich von Tschermak', 'Morgan, Sturtevant and Bridges', 'Watson and Crick', 'Bateson and Punnett'], 0,
    'Bateson later coined the word "genetics".'],
  ['A major exception to the law of independent assortment is:', ['Linkage of genes on the same chromosome', 'Dominance', 'Segregation', 'Mutation'], 0,
    'Sutton and Boveri placed Mendel’s factors on chromosomes (1902–03).']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2018-A2-Q1c', q: [
  ['The generation sequence of seed classes in India is:', ['Nucleus → breeder → foundation → certified', 'Certified → foundation → breeder → nucleus', 'Breeder → nucleus → certified → foundation', 'Foundation → certified → breeder'], 0,
    'Certified seed is what farmers buy.'],
  ['Certified seed is produced from:', ['Foundation seed', 'Nucleus seed', 'Grain from the market', 'Truthfully labelled seed'], 0,
    'In some cases certified seed is multiplied for one further generation.'],
  ['The tag colour for certified seed in India is:', ['Blue (azure blue)', 'Golden yellow', 'White', 'Opal green'], 0,
    'Breeder seed: golden yellow; foundation: white; truthfully labelled: opal green.'],
  ['Seed certification in India is carried out under the:', ['Seeds Act, 1966, by State Seed Certification Agencies', 'Insecticides Act, 1968', 'Essential Commodities Act only', 'Forest Act'], 0,
    'Certification is voluntary; labelling of notified kinds is compulsory.'],
  ['The minimum isolation distance for certified seed of rice or wheat is:', ['Three metres', 'Two hundred metres', 'One kilometre', 'None'], 0,
    'They are self-pollinated, so little isolation is needed.'],
  ['The minimum isolation distance for certified seed of open-pollinated maize is:', ['Two hundred metres', 'Three metres', 'Ten metres', 'Five kilometres'], 0,
    'Foundation seed of maize needs 400 m.'],
  ['Roguing in a seed crop means:', ['Removing off-type, diseased and weed plants', 'Adding fertiliser', 'Irrigating', 'Harvesting early'], 0,
    'It keeps the seed genetically pure.'],
  ['Field inspections for certification are usually made at:', ['Pre-flowering, flowering and pre-harvest stages', 'Sowing only', 'After harvest only', 'Never'], 0,
    'Hybrids and cross-pollinated crops need more inspections.'],
  ['The grow-out test (GOT) is used to check:', ['Genetic purity, especially of hybrid seed', 'Seed moisture', 'Seed weight', 'Germination only'], 0,
    'Plants grown from a sample are compared with the true type.'],
  ['At initial certification, a seed lot’s certificate is normally valid for:', ['Nine months from the date of testing', 'Ten years', 'One week', 'Indefinitely'], 0,
    'It can be revalidated after retesting.']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2018-A2-Q1d', q: [
  ['Harrington’s thumb rule says that the storage life of seed roughly doubles for every:', ['1% fall in seed moisture (between 5 and 14%) or 5 °C fall in temperature', '10% rise in moisture', '10 °C rise in temperature', '1% rise in moisture'], 0,
    'Moisture and temperature are the key factors in storage.'],
  ['The "sum rule" for safe seed storage is that relative humidity (%) plus temperature (°F) should not exceed:', ['100', '50', '200', '150'], 0,
    'Cool, dry stores keep seed longest.'],
  ['The basic machine used in seed cleaning is the:', ['Air-screen cleaner', 'Combine harvester', 'Rotavator', 'Sprayer'], 0,
    'It separates seed from impurities by size and weight.'],
  ['A specific gravity separator grades seed by:', ['Density (weight for the same size)', 'Colour', 'Length only', 'Shape only'], 0,
    'Light, immature or insect-damaged seeds are removed.'],
  ['An indented cylinder separator separates seeds by:', ['Length', 'Colour', 'Density', 'Moisture'], 0,
    'Short seeds lodge in the indents and are lifted out.'],
  ['A spiral separator removes:', ['Round seeds from flat or irregular ones', 'Dust only', 'Water', 'Heavy stones'], 0,
    'It is used for crops such as mustard and soybean.'],
  ['Mechanical damage to seed during threshing is greater when the seed is:', ['Very dry and brittle', 'At optimum moisture', 'Fully mature and moist', 'Treated with fungicide'], 0,
    'Cracks lower germination and let fungi in.'],
  ['The main storage fungi that reduce seed viability are:', ['*Aspergillus* and *Penicillium*', '*Puccinia* and *Ustilago*', '*Phytophthora* and *Pythium*', '*Albugo* and *Peronospora*'], 0,
    'They grow when seed moisture and humidity are high.'],
  ['Seed to be stored in moisture-proof containers must be dried to:', ['A lower moisture content than seed kept in cloth or jute bags', 'A higher moisture content', 'Any moisture level', 'Above 20% moisture'], 0,
    'Moist seed in a sealed container deteriorates quickly.'],
  ['Long-term storage of orthodox seed in the NBPGR National Genebank is at:', ['About −18 °C, with seed dried to about 3–7% moisture', 'Room temperature', '+10 °C, with 20% moisture', '+40 °C'], 0,
    'This keeps seed viable for decades.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'IFoS-2018-A2-Q1e', q: [
  ['Nitrogenase needs the metals:', ['Molybdenum and iron', 'Zinc and copper', 'Manganese only', 'Calcium only'], 0,
    'The MoFe protein holds the site where N₂ is reduced.'],
  ['Nitrate reductase needs:', ['Molybdenum', 'Nickel', 'Zinc', 'Cobalt'], 0,
    'Molybdenum deficiency causes nitrate to accumulate.'],
  ['Carbonic anhydrase contains:', ['Zinc', 'Iron', 'Copper', 'Magnesium'], 0,
    'Alcohol dehydrogenase is another zinc enzyme.'],
  ['Urease, which hydrolyses urea, needs:', ['Nickel', 'Zinc', 'Manganese', 'Boron'], 0,
    'Nickel was the last element to be accepted as essential for plants.'],
  ['Rubisco is activated by carbamylation together with:', ['Mg²⁺', 'Ca²⁺', 'Fe²⁺', 'Na⁺'], 0,
    'Stromal Mg²⁺ rises in the light.'],
  ['The oxygen-evolving complex of photosystem II contains a cluster of:', ['Manganese and calcium (Mn₄CaO₅)', 'Iron and sulphur', 'Copper only', 'Zinc only'], 0,
    'It splits water to release O₂.'],
  ['Cytochrome oxidase contains:', ['Iron (haem) and copper', 'Zinc and nickel', 'Molybdenum only', 'Magnesium only'], 0,
    'It passes electrons to oxygen in respiration.'],
  ['Superoxide dismutase occurs in forms containing:', ['Cu/Zn, Mn or Fe', 'Molybdenum only', 'Nickel only', 'Boron only'], 0,
    'It detoxifies superoxide radicals.'],
  ['Polyphenol oxidase and ascorbate oxidase are:', ['Copper enzymes', 'Zinc enzymes', 'Iron enzymes', 'Nickel enzymes'], 0,
    'Polyphenol oxidase causes browning of cut fruit.'],
  ['Metal ions help enzyme activity by:', ['Binding substrates (e.g., Mg–ATP), carrying electrons and stabilising enzyme structure', 'Acting only as food reserves', 'Replacing amino acids', 'Blocking active sites'], 0,
    'Metals held tightly form metalloenzymes; loosely bound ones activate enzymes.']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2018-A2-Q2a', q: [
  ['Compared with self-pollinated crops, seed production in cross-pollinated crops needs:', ['Much larger isolation distances', 'Smaller isolation distances', 'No isolation', 'No roguing'], 0,
    'Maize foundation seed needs 400 m; rice and wheat need 3 m.'],
  ['Genetic contamination during seed production is most likely in:', ['Cross-pollinated crops such as maize, pearl millet and sunflower', 'Self-pollinated crops such as wheat', 'Vegetatively propagated crops', 'Apomictic crops'], 0,
    'Foreign pollen can reach them from neighbouring fields.'],
  ['Which of these is mainly self-pollinated?', ['Groundnut', 'Maize', 'Pearl millet', 'Sunflower'], 0,
    'Rice, wheat, pea and soybean are also self-pollinated.'],
  ['Which of these is an often cross-pollinated crop, needing moderate isolation?', ['Pigeonpea', 'Wheat', 'Rice', 'Pea'], 0,
    'Cotton, sorghum and safflower are also often cross-pollinated.'],
  ['In hybrid maize seed production, female rows are:', ['Detasselled before pollen is shed', 'Sprayed with urea', 'Left untouched', 'Harvested first'], 0,
    'Male sterility can replace detasselling.'],
  ['In maize seed fields, "shedders" are:', ['Female-row plants that shed pollen, and must be removed', 'Seed-dispersing machines', 'Insects', 'Weeds'], 0,
    'Shedders would self-pollinate the female rows.'],
  ['In hybrid rice seed production, restorer (R) to male-sterile (A) rows are usually planted in a ratio of about:', ['2:8 to 2:10', '1:1', '10:2', '4:4'], 0,
    'The A line gives the hybrid seed.'],
  ['GA₃ is sprayed in hybrid rice seed plots to:', ['Improve panicle exsertion from the flag-leaf sheath', 'Kill weeds', 'Delay flowering', 'Increase tillering'], 0,
    'Rope-pulling is also used to spread pollen.'],
  ['Maintaining varietal purity is generally easier in:', ['Self-pollinated crops', 'Cross-pollinated crops', 'Both equally', 'Neither'], 0,
    'Self-pollinated varieties are homozygous and breed true.'],
  ['Seed of cross-pollinated varieties is maintained by:', ['Growing a large population in isolation to avoid genetic drift', 'Selfing a single plant', 'Cloning', 'Mutating'], 0,
    'Small populations lose variation and vigour.']
] },
{ p: 'A2', t: 'Heterosis, Hybrids & Mutation Breeding', w: 3, pyq: 'IFoS-2018-A2-Q2b', q: [
  ['Heterosis breeding exploits:', ['The vigour of F₁ hybrids', 'New mutations', 'Polyploidy', 'Apomixis'], 0,
    'Hybrid seed must be bought fresh each season.'],
  ['Mutation breeding works by:', ['Inducing new heritable variation with physical or chemical mutagens', 'Crossing two parents', 'Selecting within pure lines', 'Grafting'], 0,
    'It is useful when the needed variation is not available.'],
  ['Hybrid vigour declines in the F₂ generation because of:', ['Segregation and increased homozygosity (inbreeding depression)', 'New mutations', 'Chromosome doubling', 'Apomixis'], 0,
    'This is why farmers cannot save hybrid seed.'],
  ['A commonly used physical mutagen is:', ['Gamma rays from cobalt-60', 'EMS', 'Colchicine', 'Sodium azide'], 0,
    'X-rays and neutrons are also used.'],
  ['A commonly used chemical mutagen that causes mainly GC→AT transitions is:', ['Ethyl methanesulphonate (EMS)', 'Colchicine', 'Gibberellic acid', 'Ethrel'], 0,
    'It alkylates guanine.'],
  ['In mutation breeding, selection for recessive mutants usually starts in the:', ['M₂ generation', 'M₁ generation', 'F₁ generation', 'M₅ generation'], 0,
    'Recessive mutations become homozygous only after selfing.'],
  ['Sharbati Sonora, an amber-grained wheat, was developed by:', ['Gamma irradiation of Sonora 64', 'Crossing wheat with rye', 'Tissue culture', 'Genetic engineering'], 0,
    'It is an early Indian mutant variety.'],
  ['The Trombay groundnut (TG) varieties were developed at BARC by:', ['Mutation breeding', 'Heterosis breeding', 'Genetic engineering', 'Apomixis'], 0,
    'Many TG varieties are popular with farmers.'],
  ['Large-scale hybrid seed production needs:', ['Male sterility, self-incompatibility or cheap emasculation', 'Only mutagens', 'Only tissue culture', 'Nothing special'], 0,
    'This is the main practical limit of heterosis breeding.'],
  ['Mutation breeding is best suited to:', ['Improving one or two traits in an otherwise good variety', 'Combining many traits from two parents', 'Producing F₁ hybrids', 'Making polyploids'], 0,
    'Most induced mutations are recessive and harmful, so screening must be large.']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: 'IFoS-2018-A2-Q2c', q: [
  ['The sugar in RNA is:', ['Ribose', 'Deoxyribose', 'Glucose', 'Fructose'], 0,
    'Deoxyribose in DNA lacks the 2′-OH group.'],
  ['The base found in RNA in place of thymine is:', ['Uracil', 'Cytosine', 'Adenine', 'Guanine'], 0,
    'Uracil pairs with adenine.'],
  ['DNA is usually double-stranded, while RNA is usually:', ['Single-stranded, though it can fold into double-stranded regions', 'Triple-stranded', 'Always double-stranded', 'Circular only'], 0,
    'tRNA folds into a cloverleaf.'],
  ['RNA is less stable than DNA, mainly because of:', ['Its 2′-OH group, which makes it prone to hydrolysis', 'Thymine', 'Its double helix', 'Histones'], 0,
    'This is one reason DNA became the main genetic material.'],
  ['The most abundant type of RNA in a cell is:', ['rRNA (ribosomal RNA)', 'mRNA', 'tRNA', 'snRNA'], 0,
    'It makes up about 80% of cellular RNA.'],
  ['Which of these has RNA as its genetic material?', ['Tobacco mosaic virus', 'Bacteriophage T4', '*E. coli*', 'Maize'], 0,
    'Influenza and HIV viruses also have RNA genomes.'],
  ['Chargaff’s rule (A = T, G = C) applies to:', ['Double-stranded DNA', 'Single-stranded RNA', 'Proteins', 'Lipids'], 0,
    'Single-stranded nucleic acids do not follow it.'],
  ['B-DNA, the common form, is a:', ['Right-handed helix with about 10 base pairs per turn and a diameter of about 2 nm', 'Left-handed helix', 'Single strand', 'Triple helix'], 0,
    'Z-DNA is left-handed.'],
  ['RNA can act as an enzyme. An example is:', ['The peptidyl transferase activity of 23S rRNA', 'DNA polymerase', 'Rubisco', 'Amylase'], 0,
    'Catalytic RNAs are called ribozymes.'],
  ['DNA occurs mainly in the nucleus but is also found in:', ['Mitochondria and chloroplasts', 'Ribosomes', 'Vacuoles', 'Cell walls'], 0,
    'RNA is made in the nucleus and works mostly in the cytoplasm.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'IFoS-2018-A2-Q2d', q: [
  ['Enzymes are:', ['Biological catalysts, mostly proteins, that lower the activation energy of reactions', 'Light-absorbing molecules', 'Storage lipids', 'Structural carbohydrates'], 0,
    'Plant pigments absorb light; enzymes catalyse reactions.'],
  ['Plant pigments are:', ['Molecules that absorb particular wavelengths of light', 'Catalysts', 'Hormones only', 'Minerals'], 0,
    'They include chlorophylls, carotenoids, anthocyanins, betalains and phycobilins.'],
  ['Chlorophyll consists of:', ['A porphyrin ring with a central magnesium atom and a phytol tail', 'A protein chain', 'An isoprene chain only', 'A sugar ring'], 0,
    'The phytol tail anchors it in the thylakoid membrane.'],
  ['Carotenoids are:', ['C₄₀ tetraterpenoids that harvest light and protect against photo-damage', 'Proteins', 'Flavonoids', 'Alkaloids'], 0,
    'They include carotenes and xanthophylls.'],
  ['Anthocyanins are:', ['Water-soluble flavonoid pigments stored in the vacuole, whose colour changes with pH', 'Fat-soluble pigments in chloroplasts', 'Nitrogen-containing betalains', 'Enzymes'], 0,
    'They are redder in acid and bluer in alkaline conditions.'],
  ['Betalains, found in beetroot and bougainvillea, are:', ['Nitrogen-containing pigments that never occur together with anthocyanins', 'Carotenoids', 'Chlorophylls', 'Flavonoids'], 0,
    'They are confined to the order Caryophyllales.'],
  ['Phytochrome is:', ['A chromoprotein photoreceptor that switches between red and far-red forms', 'An enzyme of glycolysis', 'A storage pigment', 'A carotenoid'], 0,
    'It controls germination, flowering and shade responses.'],
  ['Enzymes are grouped into how many main classes under the IUBMB system?', ['Seven, with translocases added in 2018', 'Three', 'Twelve', 'Two'], 0,
    'The others are oxidoreductases, transferases, hydrolases, lyases, isomerases and ligases.'],
  ['The Michaelis constant (Km) is:', ['The substrate concentration at which the reaction rate is half of Vmax', 'The maximum rate', 'The enzyme concentration', 'The pH optimum'], 0,
    'A low Km means high affinity for the substrate.'],
  ['The "induced fit" model of enzyme action was proposed by:', ['Daniel Koshland', 'Emil Fischer', 'Leonor Michaelis', 'Hans Krebs'], 0,
    'Fischer proposed the earlier "lock and key" model.']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2018-A2-Q3a', q: [
  ['Maintenance breeding aims to:', ['Keep a released variety genetically pure and true to type', 'Create new varieties', 'Increase mutation rates', 'Produce hybrids'], 0,
    'It produces nucleus and breeder seed.'],
  ['Maintenance breeding and breeder seed production are the responsibility of:', ['The breeder or institution that developed the variety', 'Seed retailers', 'Farmers only', 'Seed certification agencies'], 0,
    'Certification agencies inspect foundation and certified seed.'],
  ['The causes of genetic deterioration of varieties were listed by Kadam (1942). They include:', ['Mechanical mixtures, natural crossing, mutations and developmental variation', 'Only high fertiliser use', 'Only irrigation', 'Only storage pests'], 0,
    'Selective influence of diseases is another cause.'],
  ['In a self-pollinated crop, nucleus seed is usually maintained by:', ['Selecting typical plants, growing progeny rows and bulking the uniform rows', 'Random bulking', 'Mass mutagenesis', 'Open pollination'], 0,
    'Off-type rows are rejected entirely.'],
  ['In a cross-pollinated variety, maintenance requires:', ['A large population grown in isolation, with sib-mating or half-sib selection', 'Selfing one plant', 'Cloning', 'Mutating the seed'], 0,
    'Large populations prevent genetic drift.'],
  ['A cytoplasmic male sterile A-line is maintained by crossing it with:', ['Its maintainer B-line', 'Its restorer R-line', 'Any variety', 'Itself'], 0,
    'The B-line has normal cytoplasm but the same nuclear genes.'],
  ['A restorer R-line is maintained by:', ['Selfing or sibbing in isolation', 'Crossing with the A-line', 'Crossing with the B-line', 'Mutation'], 0,
    'It carries the fertility-restoring (*Rf*) genes.'],
  ['Removing off-types during maintenance is called:', ['Negative selection (roguing)', 'Positive selection', 'Mutation', 'Hybridisation'], 0,
    'Positive selection picks the typical plants.'],
  ['Maintenance breeding matters because it:', ['Ensures farmers get genuine seed with the variety’s original yield and traits', 'Increases genetic variation', 'Replaces seed certification', 'Reduces yield'], 0,
    'Without it, varieties would deteriorate within a few generations.'],
  ['Nucleus seed is multiplied into:', ['Breeder seed', 'Certified seed directly', 'Truthfully labelled seed', 'Grain'], 0,
    'Breeder seed is then used to produce foundation seed.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 3, pyq: 'IFoS-2018-A2-Q3b', q: [
  ['Typical transpiration ratios (grams of water per gram of dry matter) are about:', ['C₃ 500, C₄ 250 and CAM 50', 'C₃ 250, C₄ 500 and CAM 1,000', 'All about 100', 'C₃ 50, C₄ 250 and CAM 500'], 0,
    'A lower transpiration ratio means higher water-use efficiency.'],
  ['C₄ plants can photosynthesise with partly closed stomata because:', ['PEP carboxylase has a high affinity for HCO₃⁻ and works at low CO₂', 'Rubisco has no oxygenase activity', 'They have no stomata', 'They do not respire'], 0,
    'Less stomatal opening means less water lost.'],
  ['The CO₂ compensation point of C₄ plants is:', ['Very low (about 0–10 ppm)', 'Much higher than in C₃ plants', 'The same as in C₃ plants', 'Above 1,000 ppm'], 0,
    'C₃ plants have compensation points of about 40–100 ppm.'],
  ['Which of these are C₄ crops?', ['Maize, sorghum, sugarcane and pearl millet', 'Wheat, rice, barley and soybean', 'Pea, potato, gram and mustard', 'Tomato, brinjal, chilli and okra'], 0,
    'The C₃ crops listed are wheat, rice, barley and soybean.'],
  ['Photorespiration in C₄ plants is:', ['Negligible, because CO₂ is concentrated around Rubisco', 'Higher than in C₃ plants', 'The same as in C₃ plants', 'Their main source of ATP'], 0,
    'This keeps their photosynthesis efficient in heat.'],
  ['The optimum temperature for photosynthesis is:', ['Higher in C₄ plants (about 30–40 °C) than in C₃ plants (about 15–25 °C)', 'Lower in C₄ plants', 'The same in both', 'Below 10 °C in C₄ plants'], 0,
    'C₄ crops do well in hot, dry climates.'],
  ['Carbon isotope discrimination (Δ¹³C) is used in C₃ breeding to select for:', ['High transpiration efficiency (low Δ)', 'High photorespiration', 'Disease resistance', 'Grain colour'], 0,
    'The Australian wheat Drysdale was bred using this trait.'],
  ['The δ¹³C value of C₄ plants is about:', ['−12‰, compared with about −28‰ in C₃ plants', '−28‰, the same as C₃', '+10‰', '−50‰'], 0,
    'PEP carboxylase discriminates less against ¹³C.'],
  ['C₄ plants also use nitrogen more efficiently because they:', ['Need less Rubisco per unit of photosynthesis', 'Fix atmospheric N₂', 'Have no chlorophyll', 'Need no proteins'], 0,
    'Rubisco is a large nitrogen sink in C₃ leaves.'],
  ['Water-use efficiency is the inverse of:', ['The transpiration ratio', 'Photosynthetic rate', 'Leaf area index', 'Harvest index'], 0,
    'WUE = dry matter produced per unit of water transpired.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'IFoS-2018-A2-Q3c', q: [
  ['Transpiration was called "a necessary evil" by:', ['Curtis', 'Blackman', 'Dixon', 'Hill'], 0,
    'It is harmful as water loss but useful in other ways.'],
  ['Of the water absorbed by a plant, the share lost by transpiration is about:', ['95–99%', '10%', '50%', '1%'], 0,
    'Only a small fraction is used in metabolism and growth.'],
  ['Transpiration is useful because it:', ['Cools leaves and drives the ascent of sap and mineral transport', 'Makes starch', 'Fixes nitrogen', 'Produces oxygen'], 0,
    'The transpiration pull explains the cohesion–tension theory.'],
  ['The cohesion–tension theory of the ascent of sap was proposed by:', ['Dixon and Joly', 'Curtis', 'Münch', 'Priestley'], 0,
    'Münch proposed the pressure-flow theory of phloem transport.'],
  ['Transpiration is "evil" because:', ['It wastes water and causes wilting and yield loss under drought', 'It cools the leaf', 'It helps absorb minerals', 'It aids sap flow'], 0,
    'Crops lose huge amounts of water this way.'],
  ['Most transpiration takes place through:', ['Stomata', 'The cuticle', 'Lenticels', 'Roots'], 0,
    'Stomatal transpiration is about 90% of the total.'],
  ['Kaolin sprayed on leaves acts as:', ['A reflective antitranspirant', 'A stomata-opening agent', 'A fertiliser', 'A fungicide'], 0,
    'Film-forming and stomata-closing antitranspirants also exist.'],
  ['Transpiration increases with:', ['High temperature, low humidity, wind and light', 'High humidity and still air', 'Darkness', 'Low temperature'], 0,
    'These raise the vapour pressure difference between leaf and air.'],
  ['Stomata open when guard cells:', ['Take up K⁺ and become turgid', 'Lose K⁺', 'Lose water', 'Make starch'], 0,
    'Blue light activates guard-cell proton pumps.'],
  ['Guttation differs from transpiration in that it:', ['Releases liquid water through hydathodes under root pressure', 'Releases water vapour through stomata', 'Occurs only in dry air', 'Occurs only in roots'], 0,
    'It is seen on leaf tips in the early morning.']
] },
{ p: 'A2', t: 'Heterosis, Hybrids & Mutation Breeding', w: 3, pyq: 'IFoS-2018-A2-Q3d', q: [
  ['The main value of male sterility in hybrid seed production is that it:', ['Removes the need for hand emasculation, cutting the cost of hybrid seed', 'Increases self-pollination', 'Reduces heterosis', 'Increases seed dormancy'], 0,
    'It makes hybrids practical in crops with small flowers.'],
  ['Cytoplasmic male sterility (CMS) is controlled by:', ['Mitochondrial genes', 'Nuclear genes only', 'Chloroplast genes only', 'The environment only'], 0,
    'It is inherited through the mother.'],
  ['In cytoplasmic-genetic male sterility (CGMS), fertility in the hybrid is restored by:', ['Nuclear restorer (*Rf*) genes from the R-line', 'Chemical sprays', 'Irradiation', 'The maintainer line'], 0,
    'This is the basis of the three-line (A, B, R) system.'],
  ['Genetic (nuclear) male sterility is hard to use because:', ['The sterile line cannot be maintained true — fertile segregants must be removed', 'It is controlled by mitochondria', 'It always restores itself', 'It needs no maintainer'], 0,
    'About half the plants in the female rows must be rogued.'],
  ['Two-line hybrid rice uses:', ['Environment-sensitive genic male sterility (PGMS or TGMS)', 'CMS with a maintainer', 'Hand emasculation', 'Chemical mutagens'], 0,
    'The line is sterile in one environment and fertile in another.'],
  ['The Texas (T) cytoplasm of maize fell out of use after the 1970 US epidemic of:', ['Southern corn leaf blight (*Bipolaris maydis* race T)', 'Maize rust', 'Downy mildew', 'Maize streak virus'], 0,
    'It showed the danger of relying on a single cytoplasm.'],
  ['The "wild abortive" (WA) cytoplasm is the basis of:', ['Three-line hybrid rice, pioneered in China by Yuan Longping', 'Hybrid maize in the USA', 'Hybrid wheat', 'Hybrid cotton'], 0,
    'China first grew hybrid rice commercially in the 1970s.'],
  ['The pearl millet male-sterile line Tift 23A, developed by Burton, led to:', ['India’s first pearl millet hybrid, HB-1', 'Hybrid rice', 'Hybrid wheat', 'Bt cotton'], 0,
    'HB-1 was released in 1965.'],
  ['Chemical hybridising agents (gametocides) are used to:', ['Induce male sterility temporarily by spraying before flowering', 'Restore fertility', 'Increase pollen production', 'Kill weeds'], 0,
    'Examples are ethephon and FW-450.'],
  ['The types of male sterility include:', ['Genetic, cytoplasmic, cytoplasmic-genetic, chemically induced and environment-sensitive', 'Only cytoplasmic', 'Only chemical', 'Only genetic'], 0,
    'Transgenic systems such as barnase–barstar are another type.']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: 'IFoS-2018-A2-Q4a', q: [
  ['A cell wall made of cellulose is found in:', ['Plant cells, but not animal cells', 'Animal cells only', 'Both', 'Neither'], 0,
    'It gives plant cells a fixed shape.'],
  ['Plastids such as chloroplasts are found in:', ['Plant cells', 'Animal cells', 'Both', 'Neither'], 0,
    'Chromoplasts and leucoplasts are also plastids.'],
  ['A large central vacuole bounded by the tonoplast is typical of:', ['Mature plant cells', 'Animal cells', 'Bacteria', 'Viruses'], 0,
    'Animal cells have small, temporary vacuoles.'],
  ['Centrioles are:', ['Present in animal cells but absent in higher plant cells', 'Present in all plant cells', 'Absent in animal cells', 'Found only in bacteria'], 0,
    'Plant spindles form without centrioles.'],
  ['Cytokinesis in plant cells takes place by:', ['Forming a cell plate from the phragmoplast', 'Furrowing of the membrane', 'Budding', 'Fragmentation'], 0,
    'Animal cells divide by a cleavage furrow.'],
  ['The main storage carbohydrate is:', ['Starch in plant cells and glycogen in animal cells', 'Glycogen in plant cells', 'Cellulose in animal cells', 'Chitin in both'], 0,
    'Starch is stored in amyloplasts.'],
  ['Neighbouring plant cells are connected through:', ['Plasmodesmata', 'Gap junctions', 'Desmosomes', 'Tight junctions'], 0,
    'Gap junctions connect animal cells.'],
  ['Glyoxysomes, which convert fats to sugars in germinating seeds, are found in:', ['Plant cells', 'Animal cells', 'Both equally', 'Viruses'], 0,
    'Animals cannot turn fat into sugar in net terms.'],
  ['True lysosomes are typical of:', ['Animal cells; in plants the vacuole does much of the digestive work', 'Plant cells only', 'Bacteria', 'Chloroplasts'], 0,
    'The plant vacuole contains hydrolytic enzymes.'],
  ['Structures found in both plant and animal cells include:', ['Mitochondria, ribosomes, the ER and Golgi bodies', 'Cell walls and chloroplasts', 'Centrioles and cell walls', 'Plastids and plasmodesmata'], 0,
    'Both are eukaryotic cells.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'IFoS-2018-A2-Q4b', q: [
  ['In germinating oilseeds, stored triacylglycerols are first broken down by:', ['Lipases, into fatty acids and glycerol', 'Amylases', 'Proteases', 'Cellulases'], 0,
    'The fatty acids then go through β-oxidation.'],
  ['In plants, β-oxidation of fatty acids occurs mainly in:', ['Glyoxysomes (peroxisomes)', 'Mitochondria only', 'Chloroplasts', 'The nucleus'], 0,
    'In animals it occurs mainly in mitochondria.'],
  ['Each turn of β-oxidation removes:', ['Two carbons as acetyl-CoA', 'One carbon as CO₂', 'Three carbons as pyruvate', 'Six carbons as glucose'], 0,
    'Palmitate (C16) gives eight acetyl-CoA in seven turns.'],
  ['In plant peroxisomes, the first step of β-oxidation is catalysed by:', ['Acyl-CoA oxidase, producing H₂O₂', 'Acyl-CoA dehydrogenase, producing FADH₂', 'Lipase', 'Catalase'], 0,
    'Catalase then breaks down the H₂O₂.'],
  ['Acetyl-CoA from β-oxidation in seeds enters the:', ['Glyoxylate cycle', 'Calvin cycle', 'Urea cycle', 'Pentose phosphate pathway only'], 0,
    'The cycle bypasses the two CO₂-releasing steps of the Krebs cycle.'],
  ['The two enzymes unique to the glyoxylate cycle are:', ['Isocitrate lyase and malate synthase', 'Rubisco and PEP carboxylase', 'Hexokinase and aldolase', 'Nitrate and nitrite reductase'], 0,
    'They let two acetyl-CoA molecules make one succinate.'],
  ['The main significance of β-oxidation with the glyoxylate cycle in seeds is that it:', ['Converts stored fat into sugar (sucrose) for the growing seedling', 'Makes fat from sugar', 'Fixes nitrogen', 'Makes chlorophyll'], 0,
    'Seedlings cannot photosynthesise until their leaves open.'],
  ['Succinate from the glyoxylate cycle is converted to sucrose through:', ['Gluconeogenesis', 'Glycolysis', 'Photosynthesis', 'Fermentation'], 0,
    'Sucrose is carried to the growing axis.'],
  ['Glyoxysomes were discovered in castor bean endosperm by:', ['Breidenbach and Beevers (1967)', 'Calvin and Benson', 'Hatch and Slack', 'Krebs'], 0,
    'Castor seed is rich in oil.'],
  ['Seeds in which β-oxidation is especially important during germination include:', ['Castor, sunflower, groundnut and pumpkin', 'Wheat and rice', 'Maize and barley', 'Pea and bean only'], 0,
    'Cereals mainly store starch.']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2018-A2-Q4c', q: [
  ['Orthodox seeds are those that:', ['Tolerate drying to low moisture (about 5%) and storage at low temperature', 'Die if dried', 'Cannot be stored', 'Germinate on the plant'], 0,
    'Most cereals, pulses and oilseeds are orthodox.'],
  ['Recalcitrant seeds are those that:', ['Lose viability if dried below a fairly high moisture content (about 20–30%)', 'Survive drying to 5%', 'Stay dormant for centuries', 'Germinate only after fire'], 0,
    'They cannot be stored in conventional seed banks.'],
  ['The terms "orthodox" and "recalcitrant" seeds were introduced by:', ['E. H. Roberts (1973)', 'J. Harrington', 'C. Baskin', 'G. Haberlandt'], 0,
    'Intermediate seeds were recognised later.'],
  ['Which of these has recalcitrant seeds?', ['Mango', 'Wheat', 'Rice', 'Chickpea'], 0,
    'Jackfruit, cocoa, rubber and litchi are also recalcitrant.'],
  ['Which of these has orthodox seeds?', ['Wheat', 'Jackfruit', 'Cocoa', 'Litchi'], 0,
    'Wheat seed can be stored for decades in cold, dry conditions.'],
  ['Seeds of coffee, papaya and neem are usually classed as:', ['Intermediate', 'Orthodox', 'Recalcitrant', 'Apomictic'], 0,
    'They tolerate some drying but not freezing storage.'],
  ['Recalcitrant seeds cannot be stored at sub-zero temperatures because:', ['Their high water content forms damaging ice crystals', 'They are too dry', 'They lack embryos', 'They are always dormant'], 0,
    'Cryopreservation of excised embryonic axes is an alternative.'],
  ['Germplasm of recalcitrant species is usually conserved in:', ['Field gene banks, in vitro cultures and cryopreserved embryonic axes', 'Ordinary seed banks at −18 °C', 'Paper envelopes at room temperature', 'Sealed tins at 40 °C'], 0,
    'NBPGR runs in vitro and cryo gene banks.'],
  ['Recalcitrant seeds are typical of:', ['Large-seeded tropical trees from moist habitats', 'Desert annuals', 'Weeds of cereals', 'Grasses only'], 0,
    'Their seeds are shed moist and germinate quickly.'],
  ['The Svalbard Global Seed Vault stores:', ['Duplicate samples of orthodox seeds', 'Recalcitrant seeds', 'Live plants', 'Pollen only'], 0,
    'It is kept at about −18 °C inside permafrost.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 3, pyq: 'IFoS-2018-A2-Q4d', q: [
  ['The yield components of wheat are:', ['Productive ears per m², grains per ear and 1,000-grain weight', 'Plant height and leaf colour', 'Root length and nodules', 'Pods per plant and oil content'], 0,
    'Yield = ears/m² × grains/ear × grain weight.'],
  ['The yield components of rice are:', ['Panicles per m², filled grains per panicle and 1,000-grain (test) weight', 'Nodules per plant', 'Siliquae per plant', 'Bolls per plant'], 0,
    'The percentage of filled spikelets is also important.'],
  ['The yield components of pulses such as chickpea are:', ['Pods per plant, seeds per pod and 100-seed weight', 'Tillers per plant only', 'Oil content only', 'Panicles per m²'], 0,
    'Pulse seed weight is usually expressed per 100 seeds.'],
  ['For oilseeds such as mustard, oil yield depends on:', ['Seed yield (siliquae per plant × seeds per siliqua × seed weight) × oil content', 'Only plant height', 'Only root depth', 'Only leaf number'], 0,
    'Oil content is typically about 38–42% in mustard.'],
  ['Harvest index is:', ['Economic yield ÷ biological yield × 100', 'Biological yield ÷ economic yield', 'Leaf area ÷ land area', 'Grain weight ÷ grain number'], 0,
    'Semi-dwarf wheats and rices have higher harvest indices.'],
  ['Yield component compensation means that:', ['An increase in one component is often offset by a decrease in another', 'All components always increase together', 'Components are unrelated to yield', 'Yield depends on one component'], 0,
    'For example, more tillers can mean fewer grains per ear.'],
  ['Leaf area index (LAI) is:', ['Total one-sided leaf area per unit of ground area', 'Leaf number per plant', 'Leaf weight', 'Leaf colour'], 0,
    'An optimum LAI maximises crop growth rate.'],
  ['Crop growth rate (CGR) is:', ['The increase in dry matter per unit ground area per unit time', 'Plant height per day', 'Leaf number per day', 'Grain yield per plant'], 0,
    'Net assimilation rate expresses the same gain per unit leaf area.'],
  ['In groundnut, a key yield parameter besides pods per plant is:', ['Shelling percentage', 'Number of tillers', 'Panicle length', 'Boll weight'], 0,
    'It is the kernel weight as a percentage of pod weight.'],
  ['Grain filling in cereals depends on:', ['The balance between source (photosynthesis) and sink (grain) capacity', 'Only root growth', 'Only soil pH', 'Only plant height'], 0,
    'The flag leaf is a major source in wheat and rice.']
] }
);
