/* PYQ-linked MCQs — IFoS 2017 Agriculture Paper I, Q5–Q7 (verbatim PYQs; Q8 missing in source). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'IFoS-2017-A1-Q5a', q: [
  ['Compared with flood irrigation, drip irrigation typically saves about:', ['30–60% of water', '1–2% of water', 'No water', 'Over 95% of water'], 0,
    'The exact saving depends on the crop and soil.'],
  ['Drip irrigation often raises yields by about:', ['20–50%', '0%', '200–300%', 'It always lowers yield'], 0,
    'The root zone stays close to field capacity.'],
  ['Water productivity ("more crop per drop") is expressed as:', ['Yield per unit of water used', 'Water per hectare', 'Yield per hectare', 'Rainfall per year'], 0,
    'Drip and sprinklers raise it.'],
  ['Weeds are fewer under drip irrigation because:', ['Only the area near the plants is wetted', 'Drip water contains herbicide', 'The soil is flooded', 'The soil is sterilised'], 0,
    'The dry areas between rows stay mostly weed-free.'],
  ['Fertigation through drip can save about what share of fertiliser?', ['Up to about 25–30%', 'None', 'All of it', 'Over 80%'], 0,
    'Nutrients are placed exactly where the roots are.'],
  ['Subsurface drip irrigation (SDI) places laterals:', ['Below the soil surface, reducing evaporation further', 'On top of the canopy', 'In open channels', 'Only in greenhouses'], 0,
    'It suits sugarcane and other long-duration crops.'],
  ['Sprinklers can protect crops from frost because:', ['Freezing water releases latent heat onto the plants', 'Water cools plants', 'They add fertiliser', 'They kill insects'], 0,
    'This is common in orchards and potato fields.'],
  ['Sprinkler irrigation suits crops such as wheat and groundnut on light soils because it:', ['Allows light, frequent irrigation without runoff', 'Floods the field', 'Needs no pump', 'Works only in clay soils'], 0,
    'It is widely used in Rajasthan.'],
  ['Sugarcane under drip is usually planted in:', ['Paired rows, with one lateral serving each pair', 'Single wide rows without laterals', 'Broadcast', 'Pits only'], 0,
    'Pairing cuts the length of laterals needed.'],
  ['A reason drip raises productivity besides saving water is:', ['Crops avoid water stress, and nutrients are used better', 'It raises soil salinity', 'It creates waterlogging', 'It removes nutrients'], 0,
    'It also helps grow crops on poor, sloping or sandy land.']
] },
{ p: 'A1', t: 'Agro-climatic Zones & Cropping Systems', w: 3, pyq: 'IFoS-2017-A1-Q5b', q: [
  ['A cropping pattern is:', ['The yearly sequence and spatial arrangement of crops on an area', 'The management of a single crop', 'The design of an irrigation system', 'A type of soil'], 0,
    'A cropping system adds the management and interactions with resources.'],
  ['In intercropping, the crop sown at its full optimum population is called the:', ['Base crop', 'Component crop', 'Catch crop', 'Trap crop'], 0,
    'The intercrop fills gaps between its rows.'],
  ['Row intercropping differs from mixed intercropping in that:', ['The crops are sown in definite rows or row ratios', 'The seeds are mixed and broadcast', 'Only one crop is grown', 'The crops are grown in different seasons'], 0,
    'Strip intercropping uses wider strips of each crop.'],
  ['A classic dryland intercrop that pairs a tall cereal with a legume is:', ['Pearl millet + pigeonpea', 'Rice + wheat', 'Sugarcane + banana', 'Tea + rubber'], 0,
    'The two crops mature at different times.'],
  ['In relay cropping:', ['The next crop is sown into the standing crop shortly before it is harvested', 'Crops are sown together at the same time', 'Only one crop is grown', 'The field is left fallow'], 0,
    'Examples are lentil or lathyrus sown into rice (paira cropping).'],
  ['Sowing potato or onion between rows of autumn-planted sugarcane is an example of:', ['Intercropping', 'Relay cropping', 'Ratoon cropping', 'Sequential cropping'], 0,
    'The short crop is harvested before the cane closes its canopy.'],
  ['Intercrops use resources better when the crops differ in:', ['Height, rooting depth and duration', 'Nothing at all', 'Only colour', 'Only seed size'], 0,
    'This is called complementarity.'],
  ['The index that compares land use by intercrops and sole crops while accounting for crop duration is the:', ['Area-time equivalency ratio (ATER)', 'Harvest index', 'Leaf area index', 'Cropping intensity'], 0,
    'The land equivalent ratio (LER) ignores duration.'],
  ['"Aggressivity" and "competitive ratio" in intercropping measure:', ['How much one component crop out-competes the other', 'Soil fertility', 'Water use', 'Market price'], 0,
    'They help choose compatible crops and row ratios.'],
  ['A main advantage of intercropping for small farmers is:', ['Insurance against total crop failure and higher total returns', 'More risk', 'Less income', 'More weeds always'], 0,
    'It also improves the family diet.']
] },
{ p: 'A1', t: 'Environment, Organic & Natural Farming', w: 2, pyq: 'IFoS-2017-A1-Q5c', q: [
  ['A major agricultural cause of groundwater pollution is:', ['Nitrate leaching from excess nitrogen fertiliser', 'Planting trees', 'Mulching', 'Contour bunding'], 0,
    'It is serious in intensively farmed Punjab.'],
  ['Phosphorus runoff from fields into lakes causes:', ['Eutrophication', 'Salinisation', 'Acid rain', 'Desertification'], 0,
    'Algal blooms then deplete oxygen.'],
  ['The WHO guideline limit for nitrate in drinking water is:', ['50 mg/L (as nitrate)', '1 mg/L', '500 mg/L', '5,000 mg/L'], 0,
    'The Indian (BIS) limit is 45 mg/L.'],
  ['Irrigation with untreated sewage can contaminate crops with:', ['Heavy metals and pathogens', 'Only extra nutrients', 'Nothing harmful', 'Only water'], 0,
    'Leafy vegetables near cities are most at risk.'],
  ['Pesticide runoff into water bodies harms:', ['Fish and other aquatic life, and can bioaccumulate', 'Only weeds', 'Nothing', 'Only soil'], 0,
    'Persistent chemicals move up the food chain.'],
  ['In West Bengal, arsenic-contaminated groundwater used for irrigation leads to:', ['Arsenic build-up in rice grain and soils', 'Higher yields only', 'Cleaner rice', 'No effect'], 0,
    'It adds to the health risk from drinking water.'],
  ['Riparian buffer strips of vegetation along streams help by:', ['Trapping sediment, nutrients and pesticides before they reach water', 'Increasing runoff', 'Adding fertiliser', 'Raising water temperature'], 0,
    'Grass and tree strips are both used.'],
  ['Measures that reduce nitrate pollution from farms include:', ['Split N application, nitrification inhibitors and soil-test-based doses', 'Doubling N doses', 'Flood irrigation after fertiliser', 'Burning residues'], 0,
    'Neem-coated urea also helps.'],
  ['Constructed wetlands in farm drainage systems:', ['Remove nutrients and pollutants from drainage water', 'Increase pollution', 'Store pesticides', 'Increase salinity'], 0,
    'Plants and microbes do the cleaning.'],
  ['Return flows from irrigated fields often carry:', ['Dissolved salts, nutrients and agrochemicals', 'Only pure water', 'Only sediment', 'Only oxygen'], 0,
    'This degrades downstream water quality.']
] },
{ p: 'A1', t: 'Environment, Organic & Natural Farming', w: 3, pyq: 'IFoS-2017-A1-Q5d', q: [
  ['The earthworm species most commonly used for vermicomposting are:', ['*Eisenia fetida*, *Eudrilus eugeniae* and *Perionyx excavatus*', '*Lumbricus terrestris* only', '*Pheretima posthuma* only', 'Nematodes'], 0,
    'They are surface-dwelling (epigeic) species.'],
  ['Composting earthworms are called epigeic because they:', ['Live and feed in surface litter', 'Burrow very deep', 'Live in water', 'Feed only on roots'], 0,
    'Deep-burrowing worms are called anecic.'],
  ['Compared with farmyard manure, vermicompost generally has:', ['Higher N, P and K (roughly 1.5–2% N, 1% P₂O₅ and 1.5% K₂O)', 'No nutrients', 'Lower nutrients', 'Only carbon'], 0,
    'Values vary with the feed material.'],
  ['Vermicomposting works best at:', ['About 20–30 °C, in shade, with moist (but not waterlogged) material', 'Above 50 °C', 'Freezing temperatures', 'In full sun on dry material'], 0,
    'Worms die in heat and in dry conditions.'],
  ['Vermicompost is usually ready in about:', ['45–60 days', 'One day', 'One year', 'Five years'], 0,
    'It is dark, crumbly and odourless.'],
  ['Besides nutrients, vermicompost contains:', ['Growth-promoting substances, humic acids and beneficial microbes', 'Pesticides', 'Heavy metals only', 'Salts only'], 0,
    'These improve plant growth beyond the nutrient effect.'],
  ['Vermiwash is:', ['The liquid collected from a vermicompost unit, used as a foliar spray', 'A pesticide', 'A type of soil', 'Worm food'], 0,
    'It contains nutrients, hormones and microbes.'],
  ['Vermicompost improves soil by:', ['Improving structure, aeration and water-holding capacity', 'Compacting it', 'Increasing salinity', 'Reducing microbes'], 0,
    'Worm casts form stable aggregates.'],
  ['Vermicomposting supports sustainable agriculture because it:', ['Recycles farm and household waste into valuable manure', 'Uses chemical fertilisers', 'Creates pollution', 'Needs costly machines'], 0,
    'It is also a source of rural income.'],
  ['The earthworm was called the "intestine of the earth" by:', ['Aristotle', 'Darwin', 'Liebig', 'Howard'], 0,
    'Darwin’s 1881 book showed how worms build soil.']
] },
{ p: 'A1', t: 'Dryland Farming & Watershed Management', w: 3, pyq: 'IFoS-2017-A1-Q5e', q: [
  ['Water harvesting is:', ['Collecting and storing rainwater or runoff for later productive use', 'Pumping groundwater only', 'Draining wetlands', 'Irrigating from canals'], 0,
    'It can be in-situ (in the field) or ex-situ (in ponds and tanks).'],
  ['The khadin system of water harvesting is traditional in:', ['Jaisalmer, western Rajasthan', 'Kerala', 'Assam', 'Punjab'], 0,
    'It was developed by the Paliwal Brahmins.'],
  ['Kunds or tankas are:', ['Covered underground tanks that store rainwater for drinking, in Rajasthan and Gujarat', 'Open canals', 'Tube wells', 'Terraces'], 0,
    'The catchment around them is often plastered.'],
  ['Johads in Alwar district were revived by Tarun Bharat Sangh, led by:', ['Rajendra Singh, the "Waterman of India"', 'Anna Hazare', 'Sunderlal Bahuguna', 'Medha Patkar'], 0,
    'He won the Stockholm Water Prize in 2015.'],
  ['Ralegan Siddhi, a model of watershed development, is associated with:', ['Anna Hazare', 'Rajendra Singh', 'Popatrao Pawar', 'Chandi Prasad Bhatt'], 0,
    'Hiware Bazar, led by Popatrao Pawar, is another model.'],
  ['Zings in Ladakh and kuhls in Himachal Pradesh are:', ['Traditional systems that divert glacier or stream water to fields', 'Types of seed', 'Grain stores', 'Terrace walls only'], 0,
    'They are managed by the communities themselves.'],
  ['The Jal Shakti Abhiyan’s campaign for rainwater conservation is called:', ['"Catch the Rain"', '"Per Drop More Crop"', '"Har Ghar Jal" only', '"Namami Gange"'], 0,
    'Its slogan is "catch the rain, where it falls, when it falls".'],
  ['Telangana’s programme to restore village tanks is:', ['Mission Kakatiya', 'Jalyukt Shivar', 'Neeru-Chettu', 'Mukhyamantri Jal Swavlamban'], 0,
    'Jalyukt Shivar is Maharashtra’s programme.'],
  ['Many water-conservation works in villages are built under:', ['MGNREGA', 'PM-KISAN', 'The Soil Health Card scheme', 'e-NAM'], 0,
    'Farm ponds, check dams and tank desilting are typical works.'],
  ['The Atal Bhujal Yojana focuses on:', ['Community-led groundwater management in water-stressed blocks', 'Building large dams', 'River interlinking', 'Urban drainage'], 0,
    'It is supported by the World Bank.']
] },
{ p: 'A1', t: 'Farm Mechanisation', w: 2, pyq: 'IFoS-2017-A1-Q6a', q: [
  ['A short-term effect of farm mechanisation is:', ['Timely operations, less drudgery and lower labour costs', 'Soil compaction over decades', 'Permanent loss of all rural jobs', 'Collapse of cropping intensity'], 0,
    'Timeliness alone can raise yields noticeably.'],
  ['A long-term effect of heavy mechanisation can be:', ['Soil compaction and hardpan formation', 'Better soil structure always', 'More earthworms', 'Less fuel use'], 0,
    'Heavy tractors compact the subsoil.'],
  ['The effect of mechanisation on farm employment:', ['Varies — machines replace some labour, but higher cropping intensity can create other work', 'Is always strongly positive', 'Is always zero', 'Always eliminates all jobs'], 0,
    'Tractors and threshers displaced labour; tube wells created more work.'],
  ['A long-term environmental problem linked to combine harvesting of rice is:', ['Loose straw left in fields, leading to residue burning', 'More soil organic matter', 'Less air pollution', 'Better wheat sowing'], 0,
    'Straw management machines were introduced to tackle it.'],
  ['Mechanisation raises cropping intensity mainly by:', ['Shortening the turnaround time between crops', 'Reducing yields', 'Leaving land fallow', 'Delaying sowing'], 0,
    'Quick land preparation allows an extra crop.'],
  ['The ICAR institute for agricultural engineering is:', ['CIAE, Bhopal', 'IARI, New Delhi', 'NDRI, Karnal', 'CRIDA, Hyderabad'], 0,
    'It designs tools and machines, including women-friendly ones.'],
  ['Drudgery-reducing tools for women farmers include:', ['Improved weeders, seed drills and paddy transplanters', 'Heavier hand hoes', 'Bullock ploughs only', 'Sickles only'], 0,
    'Women do much of the weeding and transplanting.'],
  ['Mechanised rice transplanting uses seedlings raised in:', ['Mat-type nurseries', 'Wet-bed nurseries only', 'Pots', 'Open fields without a nursery'], 0,
    'The mat of seedlings is fed into the machine.'],
  ['Long-term mechanisation increases dependence on:', ['Fossil fuels and capital', 'Bullocks', 'Manual labour', 'Rainfall only'], 0,
    'This raises costs when fuel prices rise.'],
  ['Studies across Indian states show that higher farm power availability per hectare is associated with:', ['Higher land productivity', 'Lower yields', 'No relation to yields', 'More fallow land'], 0,
    'Punjab has both high farm power and high yields.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2017-A1-Q6b', q: [
  ['The main functions of a farm manager are:', ['Planning, organising, directing, controlling and decision-making', 'Only ploughing', 'Only marketing', 'Only book-keeping'], 0,
    'The manager also bears the risk.'],
  ['The usual steps in farm decision-making are:', ['Identify the problem → collect information → analyse alternatives → decide → act → evaluate', 'Act → decide → identify the problem', 'Evaluate first, then act', 'Decide without information'], 0,
    'The farmer bears the responsibility for the outcome.'],
  ['Intensive agriculture means:', ['Using more inputs per unit of land to raise output', 'Using less land and fewer inputs', 'Leaving land fallow', 'Growing only one crop'], 0,
    'Good management is essential to keep it profitable.'],
  ['In intensive farming, an input is used most profitably where:', ['Its marginal value product equals its marginal cost (MVP/MFC = 1)', 'Total output is highest', 'The input is cheapest', 'Average output is highest'], 0,
    'Beyond that point, each extra unit loses money.'],
  ['The types of risk a farm manager faces include:', ['Production, price, financial, institutional and personal risks', 'Only weather', 'Only price', 'None'], 0,
    'Different tools manage different risks.'],
  ['The crop insurance scheme launched in 2016 is:', ['Pradhan Mantri Fasal Bima Yojana (PMFBY)', 'PM-KISAN', 'NAIS', 'RKVY'], 0,
    'Farmers pay a small, fixed share of the premium.'],
  ['Farm managers reduce risk by:', ['Diversifying enterprises, insuring crops and using contracts', 'Growing one crop only', 'Avoiding records', 'Borrowing without planning'], 0,
    'Keeping cash reserves also helps.'],
  ['The law of variable proportions says that as more of one input is added to fixed inputs:', ['Output first rises faster, then slower, and may finally fall', 'Output always rises steadily', 'Output never changes', 'Output falls from the start'], 0,
    'Managers use it to find the best input level.'],
  ['In intensive agriculture, the farm manager must stress timeliness because:', ['Delays in sowing or spraying cause large yield losses', 'Time does not matter', 'Crops wait indefinitely', 'Inputs are free'], 0,
    'Tight crop sequences leave little slack.'],
  ['Farm records help a farm manager to:', ['Measure performance and plan improvements', 'Hide losses', 'Avoid planning', 'Increase risk'], 0,
    'You cannot manage what you do not measure.']
] },
{ p: 'A1', t: 'Agricultural Extension', w: 2, pyq: 'IFoS-2017-A1-Q6c', q: [
  ['Most rural working women in India are employed in:', ['Agriculture and allied activities', 'Manufacturing', 'IT services', 'Mining'], 0,
    'Their contribution is often unpaid and unrecorded.'],
  ['The Mahila Kisan Sashaktikaran Pariyojana (MKSP), launched in 2011, is part of:', ['DAY-NRLM', 'MGNREGA', 'PM-KISAN', 'PMFBY'], 0,
    'It builds the skills and livelihoods of women farmers.'],
  ['MGNREGA requires that women make up at least:', ['One-third of the beneficiaries', 'One-tenth', 'Half', 'None'], 0,
    'Women’s participation has often exceeded half.'],
  ['The ICAR institute devoted to women in agriculture is located at:', ['Bhubaneswar (CIWA)', 'Karnal', 'Jhansi', 'Jodhpur'], 0,
    'It is the Central Institute for Women in Agriculture.'],
  ['National Women Farmers’ Day (Mahila Kisan Diwas) is observed on:', ['15 October', '5 June', '23 December', '16 October'], 0,
    '23 December is Kisan Diwas; 16 October is World Food Day.'],
  ['Allied activities that offer good employment for rural women include:', ['Dairying, mushroom growing, apiculture, sericulture and food processing', 'Only ploughing', 'Only mining', 'Only construction'], 0,
    'They can be done near home.'],
  ['Many central agricultural schemes earmark for women at least:', ['30% of the funds or beneficiaries', '5%', '100%', 'None'], 0,
    'This is part of gender budgeting.'],
  ['A major constraint faced by women farmers is:', ['Lack of land ownership, credit and extension support', 'Too much credit', 'Excess landholding', 'Too many advisers'], 0,
    'Land titles are needed for many loans and schemes.'],
  ['The "Namo Drone Didi" scheme (2023) aims to:', ['Train women’s self-help groups to provide drone services to farmers', 'Give free land to women', 'Build dairy plants', 'Distribute seeds only'], 0,
    'Groups earn by offering spraying services (a recent scheme).'],
  ['Drudgery reduction for women farmers matters because:', ['Women do much of the labour-intensive weeding, transplanting and harvesting', 'Women do no farm work', 'Machines are always available', 'It has no effect on health'], 0,
    'Better tools raise both productivity and wellbeing.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2017-A1-Q6d', q: [
  ['Price falls hurt small and marginal farmers most because they:', ['Must sell soon after harvest, lacking storage and credit', 'Have large surpluses', 'Can wait for better prices', 'Have many buyers'], 0,
    'Such distress sales happen at the lowest prices of the year.'],
  ['Farm prices fluctuate sharply because demand for most farm products is:', ['Price-inelastic, so small supply changes cause big price changes', 'Very elastic', 'Unrelated to supply', 'Fixed by law'], 0,
    'This is the basis of King’s law.'],
  ['The cobweb theory explains:', ['Cycles in which farmers respond to last season’s price, causing alternating gluts and shortages', 'Seed dormancy', 'Crop rotation', 'Irrigation scheduling'], 0,
    'Onion and potato prices show such cycles.'],
  ['Crops most prone to wild price swings in India include:', ['Tomato, onion and potato', 'Wheat under MSP procurement', 'Rice under procurement', 'Tea'], 0,
    'They are perishable and have limited processing outlets.'],
  ['Farmers can manage price risk through:', ['Futures and forward contracts, contract farming and MSP procurement', 'Growing one crop only', 'Selling immediately', 'Borrowing from moneylenders'], 0,
    'NCDEX is India’s main agricultural commodity exchange.'],
  ['Madhya Pradesh’s Bhavantar Bhugtan Yojana (2017) paid farmers:', ['The difference between MSP (or a model price) and the market price', 'A fixed income', 'Crop insurance', 'Free seeds'], 0,
    'It is a price deficiency payment.'],
  ['Warehouse receipt financing helps small farmers by:', ['Letting them borrow against stored produce instead of selling at harvest', 'Forcing immediate sale', 'Increasing storage losses', 'Raising interest rates'], 0,
    'They can sell later when prices recover.'],
  ['The main crop insurance schemes in India mostly cover:', ['Yield losses, not price falls', 'Price falls only', 'Both fully', 'Neither'], 0,
    'Price risk needs other instruments.'],
  ['PM-KISAN, launched in 2019, provides eligible farmer families with:', ['₹6,000 a year in three instalments', '₹60,000 a month', 'Free fertiliser', 'Free machinery'], 0,
    'It gives income support regardless of prices.'],
  ['Falling terms of trade for agriculture mean that:', ['Prices farmers receive rise more slowly than prices they pay', 'Farm prices rise faster than input prices', 'Farmers’ incomes rise automatically', 'Prices are stable'], 0,
    'Small farmers feel this squeeze the most.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2017-A1-Q7a', q: [
  ['A key finding of Census 2011 about the rural workforce was that:', ['Agricultural labourers (about 144 million) outnumbered cultivators (about 119 million) for the first time', 'Cultivators doubled', 'Agricultural labour disappeared', 'All farmers became landowners'], 0,
    'Landlessness and casual work have grown.'],
  ['Problems of landless agricultural labourers include:', ['Low wages, seasonal unemployment, indebtedness and lack of social security', 'High wages and job security', 'Excess landholding', 'Surplus savings'], 0,
    'Many migrate for work in the lean season.'],
  ['MGNREGA (2005) guarantees each rural household:', ['100 days of wage employment a year', '365 days of work', '10 days of work', 'Free land'], 0,
    'Work must be given within 15 days of a demand.'],
  ['Minimum wages for agricultural workers are fixed under the:', ['Minimum Wages Act, 1948 (now the Code on Wages, 2019)', 'Factories Act', 'Seeds Act', 'Companies Act'], 0,
    'States set the actual wage rates.'],
  ['Bonded labour was abolished by the:', ['Bonded Labour System (Abolition) Act, 1976', 'MGNREGA', 'Land Acquisition Act', 'Right to Education Act'], 0,
    'Freed labourers receive rehabilitation support.'],
  ['A contributory pension scheme for unorganised workers, including farm labourers, launched in 2019 is:', ['PM Shram Yogi Maan-dhan', 'PM-KISAN', 'Atal Bhujal Yojana', 'Ujjwala'], 0,
    'It pays ₹3,000 a month after age 60.'],
  ['The national database of unorganised workers, launched in 2021, is:', ['e-Shram', 'e-NAM', 'Jan Dhan', 'DigiLocker'], 0,
    'Registration links workers to welfare schemes.'],
  ['Land reforms help landless labourers through:', ['Distribution of ceiling-surplus land', 'Consolidation of large estates', 'Leasing land to companies', 'Raising land prices'], 0,
    'Tenancy reforms have also helped in some states.'],
  ['The National Food Security Act, 2013 helps landless labourers by:', ['Providing subsidised food grain through the public distribution system', 'Giving cash only', 'Giving land', 'Providing jobs'], 0,
    'It covers up to 75% of the rural population.'],
  ['Social security for unorganised workers is now covered by the:', ['Code on Social Security, 2020', 'Factories Act only', 'Indian Penal Code', 'Seeds Act'], 0,
    'It replaced the Unorganised Workers’ Social Security Act, 2008.']
] },
{ p: 'A1', t: 'Agricultural Extension', w: 3, pyq: 'IFoS-2017-A1-Q7b', q: [
  ['The first Krishi Vigyan Kendra was set up in 1974 at:', ['Puducherry', 'New Delhi', 'Ludhiana', 'Hyderabad'], 0,
    'It was run by Tamil Nadu Agricultural University.'],
  ['KVKs were recommended by the ICAR committee headed by:', ['Mohan Singh Mehta (1973)', 'M. S. Swaminathan', 'Verghese Kurien', 'B. Sivaraman'], 0,
    'The idea was "learning by doing".'],
  ['The core mandate of a KVK includes:', ['On-farm testing, frontline demonstrations and capacity development', 'Selling fertiliser only', 'Running banks', 'Law enforcement'], 0,
    'KVKs also act as district knowledge and resource centres.'],
  ['On-farm testing (OFT) by KVKs is done to:', ['Check how well a technology suits local farming conditions', 'Sell seeds', 'Collect taxes', 'Train only scientists'], 0,
    'Tests are run on farmers’ own fields.'],
  ['Frontline demonstrations (FLDs) aim to:', ['Show farmers the production potential of new technologies on their fields', 'Test laboratory chemicals', 'Train students only', 'Sell machinery'], 0,
    'ICAR began FLDs in oilseeds in 1990–91.'],
  ['KVKs are administered by ICAR through:', ['Agricultural Technology Application Research Institutes (ATARIs), organised by zones', 'District collectors only', 'NABARD', 'Private companies only'], 0,
    'There are 11 ATARIs.'],
  ['Each KVK is headed by a senior scientist and has about:', ['Six subject-matter specialists', 'Fifty scientists', 'One clerk only', 'No staff'], 0,
    'Specialists cover agronomy, horticulture, animal science and more.'],
  ['Besides training, KVKs produce and supply:', ['Quality seed, planting material and bio-products', 'Tractors', 'Fertiliser factories', 'Insurance policies'], 0,
    'This gets new varieties to farmers faster.'],
  ['The ARYA programme run through KVKs aims to:', ['Attract and retain rural youth in agriculture', 'Build roads', 'Promote exports only', 'Close KVKs'], 0,
    'It trains youth in agri-enterprises.'],
  ['There are now roughly how many KVKs in India?', ['About 730', 'About 50', 'About 5,000', 'About 10'], 0,
    'Most districts have one (count changes — check the latest).']
] },
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 2, pyq: 'IFoS-2017-A1-Q7c', q: [
  ['A wasteland is:', ['Degraded land that could be brought under vegetation with reasonable effort', 'Any unused government land', 'Only desert', 'Only urban land'], 0,
    'Some categories, such as snow cover, are hard to reclaim.'],
  ['According to the Wastelands Atlas of India (2019), wastelands cover about:', ['17% of the country’s area', '2%', '50%', '75%'], 0,
    'About 56 million hectares (2015–16 data — check updates).'],
  ['Wasteland categories include:', ['Gullies and ravines, waterlogged, saline or alkaline land, degraded forest, sands and mining wastes', 'Only irrigated farmland', 'Only forests', 'Only lakes'], 0,
    'The atlas uses satellite data to map them.'],
  ['The National Wastelands Development Board was set up in:', ['1985', '1965', '2000', '2015'], 0,
    'Its work later passed to the Department of Land Resources.'],
  ['The Chambal ravines are reclaimed mainly by:', ['Peripheral bunding, gully plugging and afforestation', 'Deep ploughing', 'Burning', 'Salt application'], 0,
    'Ravines are also levelled in places for farming.'],
  ['A hardy tree widely used on sodic wastelands is:', ['*Prosopis juliflora*', 'Teak', 'Rubber', 'Sandalwood'], 0,
    'It is planted in auger holes filled with gypsum and FYM.'],
  ['Silvipasture on wastelands combines:', ['Fodder trees with grasses such as *Cenchrus* and legumes such as *Stylosanthes*', 'Rice and wheat', 'Tea and coffee', 'Sugarcane and banana'], 0,
    'It provides fodder and fuel from poor land.'],
  ['The Integrated Wastelands Development Programme is now part of:', ['The watershed component of PMKSY', 'MGNREGA only', 'PM-KISAN', 'NFSM'], 0,
    'It was earlier merged into the IWMP (2009).'],
  ['Mine spoils are reclaimed by:', ['Replacing topsoil and planting grasses, legumes and hardy trees', 'Leaving them bare', 'Covering them with concrete', 'Adding salt'], 0,
    'Amendments such as organic matter help plants establish.'],
  ['Developing wastelands helps agriculture by:', ['Adding productive land for fodder, fuel and crops, and reducing pressure on farmland', 'Reducing land availability', 'Increasing erosion', 'Removing forests'], 0,
    'Nearly all of the land can be made productive with the right measures.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 3, pyq: 'IFoS-2017-A1-Q7d', q: [
  ['Contract farming is:', ['An agreement made before production between farmers and a buyer on price, quantity and quality', 'Leasing land to a company', 'Government procurement at MSP', 'Buying land for farming'], 0,
    'The farmer keeps ownership of the land.'],
  ['An early, well-known contract farming venture in India was:', ['PepsiCo’s tomato and potato contracts in Punjab (from 1989)', 'The Green Revolution', 'Operation Flood', 'The Bhoodan movement'], 0,
    'Contract broiler farming has since spread widely.'],
  ['A major merit of contract farming for farmers is:', ['An assured market and price, with inputs and technical advice', 'Always higher land prices', 'Freedom from quality standards', 'No need for inputs'], 0,
    'It can reduce market risk.'],
  ['A major demerit of contract farming is:', ['Unequal bargaining power and rejection of produce on quality grounds', 'An assured market', 'Access to technology', 'Credit support'], 0,
    'Delayed payments and disputes are also reported.'],
  ['Contract farming differs from corporate farming in that:', ['Land ownership stays with the farmer', 'The company owns the land', 'The government owns the land', 'No contract is signed'], 0,
    'Corporate farming means the company farms directly.'],
  ['Contract broiler farming in south India (e.g., Suguna, Venky’s) works by:', ['The company supplying chicks, feed and veterinary care, while farmers raise birds for a fee', 'Farmers buying all inputs themselves', 'The government running farms', 'Farmers selling eggs only'], 0,
    'It is one of the largest contract farming systems in India.'],
  ['The Model Contract Farming Act released by the Centre in 2018 is formally the:', ['Model Agricultural Produce and Livestock Contract Farming and Services Act', 'APMC Act', 'Seeds Act', 'Essential Commodities Act'], 0,
    'States may adopt it.'],
  ['The 2020 central law on contract farming (Farmers’ Agreement on Price Assurance and Farm Services Act):', ['Was repealed in December 2021', 'Is still in force', 'Was never passed', 'Applies only to rice'], 0,
    'It was one of the three repealed farm laws.'],
  ['Contract farming may exclude small farmers because:', ['Companies prefer dealing with fewer, larger suppliers', 'Small farmers produce too much', 'Contracts are illegal for them', 'They have too much land'], 0,
    'FPOs can help small farmers join contracts collectively.'],
  ['A risk of contract farming for the environment is:', ['Promotion of monocultures and intensive input use', 'Greater crop diversity', 'Lower input use always', 'Reduced pollution always'], 0,
    'Contracts often specify a single crop and variety.']
] }
);
