/* PYQ-linked MCQs — CSE 2026 Agriculture Paper II, Section B (Q5–Q8). 10 MCQs per sub-question.
 * Q7(a) and Q8(b) are cut off in the source; MCQs cover the parts that are legible plus the core of the topic. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Floriculture & Landscaping', w: 2, pyq: 'CSE-2026-A2-Q5a', q: [
  ['Topiary is the art of:', ['Training and clipping plants into ornamental shapes such as animals or geometric forms', 'Growing miniature trees in shallow pots', 'Arranging cut flowers', 'Growing plants without soil'], 0,
    'Growing miniature trees in pots is bonsai; soil-less growing is hydroponics.'],
  ['An ideal topiary plant is:', ['Evergreen, small-leaved, densely branched and tolerant of frequent clipping', 'Deciduous with large leaves', 'Sparsely branched and fast-growing', 'An annual that dies after flowering'], 0,
    'Small leaves give a fine, even surface; dense branching fills the shape.'],
  ['Which plant is commonly used for topiary in Indian gardens?', ['*Clerodendrum inerme*', '*Musa paradisiaca*', '*Carica papaya*', '*Ricinus communis*'], 0,
    'Also *Duranta erecta*, *Ficus benjamina*, *Murraya paniculata*, *Bougainvillea*; in temperate gardens *Buxus* and *Taxus*.'],
  ['Wire frames are used in topiary mainly to:', ['Guide the shape while the plant grows and is clipped', 'Support fruit load', 'Keep animals away', 'Carry irrigation water'], 0,
    'Frames speed up shaping, especially for complex forms.'],
  ['Which trait makes a plant UNSUITABLE for topiary?', ['Large leaves and sparse branching', 'Evergreen habit', 'Small leaves', 'Ability to regrow after clipping'], 0,
    'Large leaves look ragged when clipped.'],
  ['Topiary is a typical feature of:', ['Formal gardens', 'Wild gardens', 'Rock gardens only', 'Water gardens only'], 0,
    'Formal gardens use symmetry, clipped hedges and geometric beds (e.g., Mughal and European styles).'],
  ['Topiary plants are best clipped:', ['Regularly during active growth to keep the outline sharp', 'Once in ten years', 'Only when flowering', 'Never'], 0,
    'Light, frequent trimming encourages dense branching.'],
  ['A "standard" (lollipop) topiary is:', ['A single clear stem topped by a clipped ball or shape', 'A plant with many stems at ground level', 'A creeper on a wall', 'A potted cactus'], 0,
    'Side shoots on the stem are removed.'],
  ['Topiary differs from a hedge mainly in that topiary:', ['Shapes individual plants into artistic forms', 'Is always a boundary', 'Uses only fruit trees', 'Is never pruned'], 0,
    'A hedge is a line of plants clipped as a barrier or screen.'],
  ['Topiary as a garden art dates back to:', ['Roman gardens', 'The Green Revolution', '20th-century Japan only', 'The Harappan civilisation'], 0,
    'It was revived in Renaissance and later European formal gardens.'],
] },
{ p: 'A2', t: 'Floriculture & Landscaping', w: 2, pyq: 'CSE-2026-A2-Q5b', q: [
  ['A moon garden is designed to be enjoyed:', ['At night, by moonlight', 'Only in winter', 'Only by bees', 'Underwater'], 0,
    'It uses white or pale flowers, silvery foliage and night-scented plants.'],
  ['Plants chosen for a moon garden typically have:', ['White or pale flowers, silvery foliage or night-blooming fragrance', 'Dark red flowers that close at night', 'Only green foliage', 'Thorny stems'], 0,
    'Pale colours reflect moonlight; fragrance attracts night pollinators such as moths.'],
  ['*Cestrum nocturnum*, a favourite of moon gardens, is commonly called:', ['Queen of the night (raat ki rani)', 'Morning glory', 'Sunflower', 'Marigold'], 0,
    'Its small tubular flowers release strong fragrance after dusk.'],
  ['*Ipomoea alba* is called moonflower because its flowers:', ['Open at dusk and stay open through the night', 'Open only at noon', 'Are blue', 'Never open'], 0,
    'Large white, fragrant flowers.'],
  ['*Nyctanthes arbor-tristis* (parijat/night jasmine) suits a moon garden because it:', ['Flowers at night and drops its flowers at dawn', 'Flowers only at noon', 'Has no scent', 'Is a cactus'], 0,
    'The orange-tubed white flowers carpet the ground by morning.'],
  ['A terrace (rooftop) garden needs:', ['Waterproofing, a drainage layer and lightweight growing media', 'Heavy clay soil', 'No drainage', 'Only large trees'], 0,
    'Structural load must be checked before building one.'],
  ['Lightweight media for terrace gardens include:', ['Cocopeat, perlite, vermiculite and compost', 'Pure clay', 'Gravel only', 'Cement'], 0,
    'They reduce weight while holding water and air.'],
  ['A root-barrier membrane in a terrace garden:', ['Prevents roots from damaging the waterproofing and roof slab', 'Adds nutrients', 'Stops rainfall', 'Increases weight'], 0,
    'Laid above the waterproofing layer.'],
  ['An environmental benefit of terrace gardens in cities is:', ['Reducing heat island effect, insulating buildings and slowing stormwater runoff', 'Increasing air pollution', 'Raising roof temperature', 'Increasing flooding'], 0,
    'They also provide fresh vegetables and habitat.'],
  ['Silvery-foliage plants such as dusty miller (*Senecio cineraria*) are used in moon gardens because they:', ['Reflect moonlight and stay visible at night', 'Bloom only in the day', 'Need darkness to grow', 'Repel moths'], 0,
    '*Artemisia* is another silvery choice.'],
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 3, pyq: 'CSE-2026-A2-Q5c', q: [
  ['A good-quality cauliflower curd is:', ['Compact, white or creamy, and free from riceyness, fuzziness and bracts', 'Loose and yellow', 'Leafy and purple', 'Soft and hollow'], 0,
    'Curd weight, compactness and colour are the main quality indices.'],
  ['"Riceyness" in cauliflower curds refers to:', ['A granular, velvety surface caused by early development of flower buds', 'Rice weevil damage', 'Rotting of the curd', 'A purple tinge'], 0,
    'Often due to high temperature during curd development or unsuited varieties.'],
  ['"Buttoning" in cauliflower is:', ['Premature formation of very small curds', 'Oversized curds', 'Hollow stems', 'Leaf spot'], 0,
    'Caused by planting old seedlings, nitrogen shortage or stress, especially in early varieties.'],
  ['Brown, water-soaked patches on cauliflower curds and hollow stems usually indicate deficiency of:', ['Boron', 'Nitrogen', 'Iron', 'Sulphur'], 0,
    'Molybdenum deficiency causes whiptail (narrow, strap-like leaves).'],
  ['Blanching of cauliflower means:', ['Tying or folding leaves over the curd to keep it white', 'Dipping curds in hot water', 'Spraying bleach', 'Harvesting at night'], 0,
    'Sunlight turns curds yellowish.'],
  ['Head splitting in cabbage is mainly caused by:', ['Sudden heavy watering after a dry spell, especially in mature heads', 'Low temperatures', 'Excess boron', 'Insect damage only'], 0,
    'Timely harvest and regular irrigation reduce splitting.'],
  ['A good-quality cabbage head is:', ['Solid, compact and heavy for its size, with fresh colour', 'Loose and light', 'Split and cracked', 'Yellow and soft'], 0,
    'Head compactness (solidity) is a key index.'],
  ['Broccoli should be harvested when:', ['The bud clusters are tight, compact and green, before flowers open', 'The flowers are fully open and yellow', 'The leaves turn yellow', 'The plant has set seed'], 0,
    'Yellowing buds mean over-maturity.'],
  ['Broccoli is valued for health because it contains:', ['Glucosinolates that give sulforaphane', 'Capsaicin', 'Lycopene only', 'Caffeine'], 0,
    'Sulforaphane is linked to anticancer activity.'],
  ['Broccoli yellows quickly after harvest mainly because of:', ['Its high respiration rate and chlorophyll breakdown, sped by warmth and ethylene', 'Low respiration', 'Excess boron', 'Cold storage'], 0,
    'Rapid cooling and high humidity keep it green.'],
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: 'CSE-2026-A2-Q5d', q: [
  ['Roughly what share of India’s net sown area is irrigated?', ['About half', 'About one-tenth', 'About 90%', 'Almost all'], 0,
    'The rest depends on rainfall, so production swings with the monsoon.'],
  ['The generally recommended NPK use ratio for India, which high urea use distorts, is:', ['4:2:1', '1:1:1', '10:1:1', '2:4:1'], 0,
    'Actual use has often been far wider (e.g., well above 6:2:1) because urea is cheap.'],
  ['A major soil-related constraint to raising food grain yields is:', ['Declining soil organic carbon and multi-nutrient deficiencies', 'Excess soil organic matter', 'Too much potassium everywhere', 'Soil acidity everywhere'], 0,
    'Zinc, sulphur and boron deficiencies are widespread.'],
  ['Falling groundwater tables threaten grain production most in:', ['The north-west (Punjab, Haryana)', 'Kerala', 'Assam', 'The Andaman Islands'], 0,
    'Intensive rice–wheat on tube-well irrigation has depleted aquifers.'],
  ['The "yield gap" in agriculture refers to:', ['The difference between yields achieved on research farms and in farmers’ fields', 'The difference in yields between two years', 'The loss after harvest', 'The gap between rows'], 0,
    'Closing yield gaps is a major route to more production.'],
  ['Low seed replacement rates limit production mainly because:', ['Farmers keep using old, low-yielding seed instead of quality seed of improved varieties', 'Seeds are too cheap', 'There are too many varieties', 'Seeds cannot be stored'], 0,
    'Quality seed alone can raise yields by 15–20%.'],
  ['Post-harvest losses are generally higher for:', ['Fruits and vegetables than for cereals', 'Cereals than for fruits', 'Pulses than for vegetables', 'Rice than for tomato'], 0,
    'Perishability and weak cold chains cause the difference.'],
  ['Climate change threatens grain production mainly through:', ['Heat stress, erratic rainfall and more frequent extreme events', 'Longer winters only', 'More stable monsoons', 'Lower CO₂ levels'], 0,
    'Terminal heat stress in wheat is a clear example.'],
  ['Small and fragmented landholdings limit production mainly because they:', ['Make mechanisation, investment and credit harder', 'Always give lower yields per hectare', 'Stop irrigation completely', 'Prevent the use of seed'], 0,
    'Small farms can have high yields per hectare but face scale and access problems.'],
  ['Which is an institutional (non-technical) constraint to grain production?', ['Limited access to credit, extension and markets', 'Soil texture', 'Day length', 'Crop genetics'], 0,
    'Both technology and institutions need attention.'],
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'CSE-2026-A2-Q5e', q: [
  ['Osmoprotectants (compatible solutes) include:', ['Proline, glycine betaine, trehalose and polyols such as mannitol', 'Sodium chloride and sulphuric acid', 'Auxins and gibberellins', 'Chlorophyll and carotene'], 0,
    'They accumulate to high levels without disturbing metabolism.'],
  ['Osmoprotectants help under salt and drought stress mainly by:', ['Lowering cell osmotic potential to keep water uptake and turgor, and protecting proteins and membranes', 'Increasing transpiration', 'Opening stomata wider', 'Breaking cell walls'], 0,
    'This is called osmotic adjustment; some solutes also scavenge reactive oxygen species.'],
  ['Proline is synthesised from glutamate by the key enzyme:', ['Δ¹-pyrroline-5-carboxylate synthetase (P5CS)', 'Rubisco', 'Nitrate reductase', 'ACC synthase'], 0,
    'P5CS expression rises sharply under stress.'],
  ['Glycine betaine is synthesised in plants from:', ['Choline, via choline monooxygenase and betaine aldehyde dehydrogenase', 'Glucose via glycolysis', 'Tryptophan', 'Fatty acids'], 0,
    'Crops like rice accumulate little; transgenic lines with *codA* (choline oxidase) make it.'],
  ['"Compatible" solutes are so called because they:', ['Do not interfere with normal enzyme activity even at high concentrations', 'Combine with salts', 'Are toxic in small amounts', 'Only occur in animals'], 0,
    'Unlike inorganic ions, which disturb enzymes at high levels.'],
  ['Trehalose is especially known for:', ['Stabilising membranes and proteins during desiccation (e.g., in resurrection plants)', 'Colouring flowers', 'Stimulating flowering', 'Fixing nitrogen'], 0,
    'It is a non-reducing disaccharide.'],
  ['Osmotic adjustment means:', ['Active accumulation of solutes in cells so that turgor is kept at lower water potential', 'Loss of solutes from cells', 'Increase in cell water potential', 'Closure of all stomata'], 0,
    'It keeps growth and stomatal opening going longer under stress.'],
  ['Foliar application of glycine betaine to crops is used to:', ['Improve tolerance to drought, salt and temperature stress', 'Kill weeds', 'Induce flowering', 'Ripen fruits'], 0,
    'It is taken up and moves to growing tissues.'],
  ['Mannitol is a polyol osmoprotectant notably found in:', ['Celery and brown algae', 'Wheat', 'Maize', 'Rice'], 0,
    'Pinitol is another polyol found in legumes such as soybean.'],
  ['Under salt stress, besides osmotic effects, plants suffer from:', ['Specific ion toxicity (Na⁺, Cl⁻) and nutrient imbalance', 'Excess nitrogen fixation', 'Lower light interception only', 'Faster flowering only'], 0,
    'Tolerant plants exclude Na⁺ or store it in vacuoles and use compatible solutes in the cytoplasm.'],
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 3, pyq: 'CSE-2026-A2-Q6a', q: [
  ['High-density planting (HDP) of fruit trees means:', ['Planting more trees per hectare than conventional spacing, with size controlled by rootstocks, training and pruning', 'Growing only one tree per hectare', 'Growing fruit trees in greenhouses only', 'Planting trees without spacing'], 0,
    'Goals: early bearing, higher yield per hectare and efficient use of inputs.'],
  ['Amrapali mango is suited to high-density planting at about:', ['2.5 m × 2.5 m (about 1,600 plants/ha)', '10 m × 10 m', '20 m × 20 m', '1 m × 1 m'], 0,
    'It is dwarf and a regular bearer; conventional mango spacing is about 10 m × 10 m.'],
  ['A strongly dwarfing citrus rootstock used for high-density planting is:', ['Flying Dragon (a *Poncirus trifoliata* selection)', 'Rough lemon', 'Rangpur lime', 'Sweet orange seedling'], 0,
    'Troyer citrange is semi-dwarfing. Rough lemon and Rangpur lime are vigorous.'],
  ['The "meadow orchard" system of very high-density planting with regular pruning was developed for:', ['Guava', 'Coconut', 'Mango only', 'Date palm'], 0,
    'CISH, Lucknow; plants are kept small by pruning after each crop.'],
  ['Paclobutrazol is used in high-density mango orchards mainly to:', ['Check vegetative growth and induce regular flowering (it inhibits gibberellin synthesis)', 'Kill insects', 'Increase tree height', 'Ripen fruits'], 0,
    'Applied as a soil drench around the trunk at recommended doses.'],
  ['Canopy management in high-density orchards aims to:', ['Keep trees small and open so light reaches the whole canopy', 'Let trees grow as tall as possible', 'Stop all pruning', 'Increase shading'], 0,
    'Training systems such as open-centre or modified leader are used.'],
  ['"Mottle leaf" of citrus, with yellow patches between veins and small leaves, is caused by deficiency of:', ['Zinc', 'Nitrogen', 'Calcium', 'Molybdenum'], 0,
    'Corrected by zinc sulphate sprays.'],
  ['Rangpur lime is valued as a citrus rootstock for:', ['Vigour and drought tolerance', 'Extreme dwarfing', 'Resistance to all diseases', 'Producing seedless fruit'], 0,
    'It is widely used for mandarins and sweet oranges in India.'],
  ['Drip irrigation with fertigation suits high-density orchards because it:', ['Delivers water and nutrients precisely to each tree’s root zone', 'Floods the whole orchard', 'Needs no filters', 'Uses more water'], 0,
    'Close spacing needs careful, frequent nutrient and water supply.'],
  ['A limitation of high-density orcharding is:', ['High initial cost and the need for skilled canopy management', 'Delayed fruiting', 'Lower yields per hectare', 'No need for pruning'], 0,
    'Poor management leads to overcrowding and lower fruit quality.'],
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'CSE-2026-A2-Q6b', q: [
  ['In plants, chlorophyll biosynthesis begins with δ-aminolevulinic acid (ALA) formed from:', ['Glutamate (the C₅ pathway)', 'Glycine and succinyl-CoA', 'Acetyl-CoA', 'Tryptophan'], 0,
    'Animals and many bacteria make ALA from glycine and succinyl-CoA (Shemin pathway).'],
  ['The enzyme that inserts magnesium into protoporphyrin IX is:', ['Mg-chelatase', 'Ferrochelatase', 'Rubisco', 'Chlorophyllase'], 0,
    'Ferrochelatase inserts iron instead, leading to haem.'],
  ['Angiosperm seedlings grown in darkness are yellow (etiolated) because:', ['Conversion of protochlorophyllide to chlorophyllide needs light (light-dependent POR)', 'They lack magnesium', 'Chlorophyll is destroyed in the dark', 'Carotenoids are absent'], 0,
    'Gymnosperms and algae also have a light-independent enzyme and can green in the dark.'],
  ['Chlorophyll b is formed from chlorophyll(ide) a by the enzyme:', ['Chlorophyll(ide) a oxygenase (CAO)', 'Phytoene synthase', 'Lycopene cyclase', 'Mg-chelatase'], 0,
    'The phytol tail is attached by chlorophyll synthase.'],
  ['The first committed step of carotenoid biosynthesis is catalysed by:', ['Phytoene synthase', 'Lycopene cyclase', 'Mg-chelatase', 'Chlorophyll synthase'], 0,
    'Two GGPP molecules join to form phytoene, which is desaturated to lycopene.'],
  ['Plastid carotenoids are built from isoprene units supplied mainly by the:', ['MEP (methylerythritol phosphate) pathway', 'Mevalonate pathway in the cytosol', 'Shikimate pathway', 'Calvin cycle directly'], 0,
    'The cytosolic mevalonate pathway supplies sterols and some other terpenoids.'],
  ['The xanthophyll cycle (violaxanthin ↔ zeaxanthin) helps plants by:', ['Dissipating excess light energy as heat under high light', 'Absorbing far-red light', 'Fixing CO₂', 'Transporting sugars'], 0,
    'Zeaxanthin forms under excess light; it reverts to violaxanthin in low light.'],
  ['Iron deficiency causes chlorosis even though iron is not part of chlorophyll because iron is:', ['Needed for enzymes of chlorophyll synthesis and for chloroplast development', 'A component of carotene', 'Needed only by roots', 'Toxic to chlorophyll'], 0,
    'Deficiency shows as interveinal chlorosis of young leaves.'],
  ['Chilling temperatures reduce leaf greening mainly because they:', ['Slow enzymes of pigment synthesis and damage chloroplast development', 'Increase chlorophyll synthesis', 'Destroy carotenoids only', 'Have no effect'], 0,
    'Light intensity and quality, nitrogen, magnesium and water status also affect pigments.'],
  ['The yellow and orange colours of autumn leaves appear mainly because:', ['Chlorophyll breaks down and unmasks carotenoids; some leaves also make anthocyanins', 'New chlorophyll is made', 'Carotenoids are destroyed', 'Leaves take up soil pigments'], 0,
    'Red colours come from anthocyanins made in cool, sunny weather.'],
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: 'CSE-2026-A2-Q6c', q: [
  ['"Hidden hunger" refers to:', ['Deficiency of micronutrients such as iron, zinc, vitamin A and iodine', 'Lack of calories only', 'Hunger in hidden places', 'Overeating'], 0,
    'People may get enough calories yet lack vitamins and minerals.'],
  ['According to NFHS-5 (2019–21), about ___ of children aged 6–59 months in India are anaemic.', ['67%', '17%', '35%', '90%'], 0,
    'About 57% of women aged 15–49 were also anaemic.'],
  ['According to NFHS-5, the share of children under five who are stunted is about:', ['35%', '10%', '60%', '5%'], 0,
    'Stunting (low height for age) reflects chronic undernutrition.'],
  ['Phytates in cereal- and pulse-based diets contribute to deficiency by:', ['Binding iron and zinc and lowering their absorption', 'Adding extra iron', 'Increasing vitamin A', 'Improving protein quality'], 0,
    'Soaking, fermentation and germination reduce phytates.'],
  ['A major cause of nutrient deficiencies in India is:', ['Low dietary diversity, poverty, poor sanitation and infections', 'Excess vegetable consumption', 'High meat intake everywhere', 'Too much iodised salt'], 0,
    'Women’s education and status, and infant feeding practices also matter.'],
  ['Iodine deficiency disorders in India are tackled mainly through:', ['Universal salt iodisation', 'Iron tablets', 'Vitamin A syrup', 'Fortified oil'], 0,
    'Goitre and cretinism were common in endemic belts.'],
  ['Fortified rice distributed through the PDS is enriched with:', ['Iron, folic acid and vitamin B12', 'Vitamin C only', 'Calcium only', 'Iodine and fluoride'], 0,
    'Fortified kernels are blended with ordinary rice.'],
  ['The programme launched in 2018 to reduce anaemia across age groups is:', ['Anaemia Mukt Bharat', 'Swachh Bharat', 'Jal Jeevan Mission', 'PM-KISAN'], 0,
    'It uses iron–folic acid supplements, deworming, testing and behaviour change.'],
  ['The "double burden of malnutrition" means:', ['Undernutrition and overweight/obesity existing together in a population', 'Two meals a day', 'Double food prices', 'Two types of vitamin deficiency'], 0,
    'Seen increasingly in urban India.'],
  ['Biofortification differs from fortification in that:', ['Nutrients are raised in the crop itself through breeding or agronomy, not added during processing', 'It adds vitamins to packaged food', 'It uses only tablets', 'It lowers nutrient content'], 0,
    'Examples: zinc-rich wheat and rice, iron-rich pearl millet.'],
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 3, pyq: 'CSE-2026-A2-Q7a', q: [
  ['Which mango variety is a regular bearer?', ['Neelum', 'Dashehari', 'Langra', 'Alphonso'], 0,
    'Amrapali (Dashehari × Neelum) and many south Indian varieties are also regular; Dashehari, Langra, Chausa and Alphonso tend to bear in alternate years.'],
  ['Polyembryonic mango varieties are used as rootstocks because:', ['Their nucellar seedlings are uniform and true-to-type', 'They are always dwarf', 'They produce no fruit', 'They resist all diseases'], 0,
    'Examples: Olour, Bappakai, Chandrakaran.'],
  ['Mango grafts are best transplanted in most of India:', ['At the onset of the monsoon (July–August)', 'In peak summer (May)', 'In severe winter (January)', 'At any time without irrigation'], 0,
    'In heavy-rainfall areas, planting is done towards the end of the monsoon.'],
  ['The conventional spacing for mango orchards is about:', ['10 m × 10 m', '2 m × 2 m', '30 m × 30 m', '1 m × 1 m'], 0,
    'Dwarf varieties like Amrapali can be planted at much closer spacing.'],
  ['Banding the trunk with polythene sheets in December controls mango mealy bug (*Drosicha mangiferae*) by:', ['Stopping nymphs from climbing up the tree', 'Killing adults on leaves', 'Attracting natural enemies', 'Poisoning the roots'], 0,
    'Nymphs hatch in soil in winter and crawl up trunks; summer ploughing exposes eggs.'],
  ['Mango hoppers damage the crop mainly by:', ['Sucking sap from inflorescences, causing flower drop, and secreting honeydew that leads to sooty mould', 'Boring into the stone', 'Eating the roots', 'Rotting fruits in storage'], 0,
    'Sprays at the panicle emergence stage are critical.'],
  ['Mango fruit fly (*Bactrocera dorsalis*) is monitored and controlled with traps containing:', ['Methyl eugenol', 'Gossyplure', 'Neem oil only', 'Copper sulphate'], 0,
    'Methyl eugenol attracts male flies; field sanitation of fallen fruit also helps.'],
  ['The mango stone weevil is a major concern for exports because it:', ['Develops inside the stone and is a quarantine pest for importing countries', 'Causes leaf spots', 'Only attacks roots', 'Is a fungus'], 0,
    'Irradiation and hot-water treatment are used to meet quarantine rules.'],
  ['Paclobutrazol soil drench in mango helps mainly by:', ['Inducing early, regular flowering by checking vegetative growth', 'Increasing tree height', 'Killing mealy bugs', 'Ripening fruits'], 0,
    'It inhibits gibberellin biosynthesis; used within recommended doses.'],
  ['A spray of potassium nitrate in mango is used mainly to:', ['Induce flowering, especially in tropical conditions', 'Kill fruit flies', 'Delay ripening', 'Prevent sunburn'], 0,
    'Widely used in the Philippines and parts of South India.'],
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: 'CSE-2026-A2-Q7b', q: [
  ['According to PLFS 2023–24, about ___ of India’s workforce is employed in agriculture and allied activities.', ['46%', '15%', '70%', '25%'], 0,
    'Agriculture’s share in gross value added is much smaller (under 20%), so incomes per worker are low.'],
  ['Growth in agriculture is considered especially effective for poverty reduction because:', ['Most poor people depend on it for livelihoods, so gains reach them directly', 'It employs few people', 'It has no links with other sectors', 'Poor people live only in cities'], 0,
    'Studies (e.g., World Development Report 2008) found agricultural growth reduces poverty more than growth in other sectors.'],
  ['NITI Aayog estimated that between 2013–14 and 2022–23 about ___ people moved out of multidimensional poverty.', ['24.8 crore', '2.5 crore', '100 crore', '50 lakh'], 0,
    'The headcount ratio fell from about 29% to about 11%.'],
  ['MGNREGA guarantees:', ['At least 100 days of wage employment a year to every rural household whose adults volunteer for unskilled manual work', 'Free food grains', 'Free land', 'Crop insurance'], 0,
    'Works include water conservation and land development, which also help agriculture.'],
  ['DAY-NRLM promotes rural livelihoods mainly through:', ['Women’s self-help groups and their federations', 'Large corporate farms', 'Import subsidies', 'Urban housing'], 0,
    'Deendayal Antyodaya Yojana – National Rural Livelihoods Mission (2011).'],
  ['Allied sectors such as dairy, poultry and fisheries matter for poverty reduction because they:', ['Grow faster and give income to landless and marginal households, including women', 'Need large landholdings', 'Employ nobody', 'Are only for exports'], 0,
    'Livestock is a key asset of the rural poor.'],
  ['"Disguised unemployment" in agriculture means:', ['More people work on the farm than needed, so extra workers add almost nothing to output', 'Workers hiding from officials', 'Seasonal migration only', 'Full employment'], 0,
    'Moving surplus labour into non-farm jobs raises incomes.'],
  ['A major structural cause of rural poverty is:', ['Small, fragmented holdings with low productivity and limited assets', 'Too much irrigation', 'High farm prices', 'Excess credit'], 0,
    'Low education, health and social exclusion add to it.'],
  ['Rural non-farm employment helps reduce poverty by:', ['Diversifying household income beyond crop farming', 'Increasing dependence on rainfall', 'Reducing wages', 'Stopping migration entirely'], 0,
    'Agro-processing and services linked to agriculture are important sources.'],
  ['The poverty-reducing effect of agriculture is strongest when growth comes from:', ['Higher productivity of small farms and higher farm wages', 'Only large farms', 'Imports of food', 'Reduced employment'], 0,
    'Broad-based growth spreads benefits widely.'],
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'CSE-2026-A2-Q7c', q: [
  ['A hard, water-impermeable seed coat causes:', ['Physical dormancy, as in many legumes', 'Morphological dormancy', 'Secondary dormancy', 'Photodormancy'], 0,
    'Broken by scarification (mechanical, acid or hot water).'],
  ['Morphological dormancy is due to:', ['An underdeveloped embryo that must grow before germination', 'A hard seed coat', 'Chemical inhibitors only', 'High temperature'], 0,
    'Seen in some Apiaceae (e.g., celery); combined with physiological dormancy it is morphophysiological dormancy.'],
  ['Secondary dormancy is:', ['Dormancy induced after dispersal by unfavourable conditions such as high temperature or lack of light', 'Dormancy present at maturity', 'Lack of an embryo', 'A disease of seeds'], 0,
    'Primary dormancy is present when the seed is shed.'],
  ['After-ripening refers to:', ['Loss of dormancy during a period of dry storage', 'Ripening of fruits after harvest', 'Seed coat hardening', 'Germination in the field'], 0,
    'Common in cereals and many weeds.'],
  ['Rice varieties with some seed dormancy are useful because they:', ['Avoid pre-harvest sprouting when rain falls at harvest', 'Germinate faster in the nursery', 'Need no storage', 'Yield more straw'], 0,
    'Too much dormancy, however, delays nursery sowing.'],
  ['The hormone balance that mainly controls seed dormancy is:', ['Abscisic acid (promotes dormancy) versus gibberellin (promotes germination)', 'Auxin versus ethylene only', 'Cytokinin versus ethylene only', 'Brassinosteroid versus jasmonate only'], 0,
    'GA₃ treatment is used to break physiological dormancy.'],
  ['Groundnut types with fresh-seed dormancy (useful against sprouting in the field) are:', ['Virginia types', 'Spanish types', 'Valencia types', 'All bunch types equally'], 0,
    'Spanish-Valencia types usually lack dormancy and can sprout before harvest.'],
  ['Germination inhibitors that cause chemical dormancy are often found in:', ['Seed coats and fruit coverings (e.g., phenolics, coumarin, ABA)', 'Only the embryo axis', 'The soil only', 'Pollen'], 0,
    'Leaching in running water removes them (e.g., beet, some tree seeds).'],
  ['Potassium nitrate (KNO₃) is used in germination testing to:', ['Help break dormancy in freshly harvested seeds of some species', 'Kill seed-borne fungi', 'Coat the seed', 'Increase seed size'], 0,
    'Prescribed in ISTA rules for several crops.'],
  ['Dormancy imposed by a seed coat that mechanically restricts the embryo is overcome by:', ['Scarification or removing/weakening the coat', 'Keeping seeds completely dry', 'Storing at high temperature only', 'Adding abscisic acid'], 0,
    'Chilling (stratification) is used for embryo (physiological) dormancy.'],
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: 'CSE-2026-A2-Q8a', q: [
  ['Storage insects and moulds multiply fastest when grain moisture is above about ___ and temperature is 25–35 °C.', ['12%', '5%', '2%', '1%'], 0,
    'High relative humidity (above about 70%) also favours infestation.'],
  ['Which is a secondary (external) storage pest?', ['Red flour beetle (*Tribolium castaneum*)', 'Rice weevil (*Sitophilus oryzae*)', 'Lesser grain borer (*Rhyzopertha dominica*)', 'Pulse beetle (*Callosobruchus chinensis*)'], 0,
    'Secondary pests feed on broken grain and flour; primary pests attack whole, sound grain.'],
  ['The Angoumois grain moth is:', ['*Sitotroga cerealella*', '*Corcyra cephalonica*', '*Trogoderma granarium*', '*Tribolium castaneum*'], 0,
    '*Corcyra* is the rice moth (also used to rear *Trichogramma*); *Trogoderma* is the khapra beetle.'],
  ['The khapra beetle (*Trogoderma granarium*) is especially feared because it:', ['Is a serious pest of stored grain and a major quarantine pest in international trade', 'Attacks only living plants', 'Is harmless', 'Only feeds on fruits'], 0,
    'Larvae can survive long periods without food in cracks.'],
  ['The fumigant most widely used for stored grain is:', ['Phosphine, released from aluminium phosphide', 'DDT', 'Carbofuran', 'Glyphosate'], 0,
    'Fumigation must be done in airtight conditions by trained operators; resistance is a concern.'],
  ['Hermetic storage bags control storage insects by:', ['Cutting off oxygen so insects die, without chemicals', 'Heating grain to 100 °C', 'Releasing insecticides', 'Keeping grain wet'], 0,
    'Examples include multi-layer PICS bags.'],
  ['Coating pulse seeds with edible oil protects against the pulse beetle mainly by:', ['Interfering with egg laying and egg hatching', 'Making seeds heavier', 'Increasing moisture', 'Attracting predators'], 0,
    'Neem leaves and inert dusts are other traditional protectants.'],
  ['Before storing new grain, stores should be:', ['Cleaned and disinfested (e.g., malathion spray on walls and floor)', 'Left with old grain residues', 'Kept damp', 'Filled without drying the grain'], 0,
    'Residual infestation is the main source of new attacks.'],
  ['"Hot spots" in stored grain are caused by:', ['Insect and mould activity that raises local temperature and moisture', 'Direct sunlight only', 'Cold air', 'Fumigation'], 0,
    'They spread spoilage; regular temperature checks help detect them.'],
  ['CAP storage in India refers to:', ['Cover and plinth storage of bagged grain on raised platforms under covers', 'Cold-air packaging', 'Controlled atmosphere packaging for fruits', 'Central agricultural procurement'], 0,
    'Used by FCI when covered warehouse space is short; losses are higher than in proper godowns or silos.'],
] },
{ p: 'A2', t: 'Floriculture & Landscaping', w: 2, pyq: 'CSE-2026-A2-Q8b', q: [
  ['In standard carnations, disbudding means:', ['Removing side buds to leave one large terminal flower per stem', 'Removing the terminal bud', 'Removing all leaves', 'Cutting the roots'], 0,
    'Spray carnations keep side buds and remove the terminal bud instead, giving several smaller flowers.'],
  ['Pinching in carnation is done mainly to:', ['Increase the number of flowering shoots and regulate the time of flowering', 'Kill pests', 'Reduce yield', 'Ripen seeds'], 0,
    'Single, one-and-a-half and double pinch systems spread harvests over time.'],
  ['Carnation is propagated commercially mainly by:', ['Rooted terminal cuttings', 'Seed', 'Bulbs', 'Grafting'], 0,
    'Cuttings from virus-free mother stock give uniform plants.'],
  ['The most serious soil-borne disease of carnation is:', ['Fusarium wilt (*Fusarium oxysporum* f. sp. *dianthi*)', 'Late blight', 'Citrus canker', 'Rice blast'], 0,
    'Soil sterilisation and clean planting material are key.'],
  ['Calyx splitting in carnation is a physiological disorder linked to:', ['Sharp fluctuations in temperature, especially cool nights', 'High nitrogen only', 'Insect attack', 'Viral infection'], 0,
    'Rubber bands or rings around the calyx can reduce splitting in susceptible varieties.'],
  ['Carnations for cut flowers grow best in:', ['A cool, moderate climate, often in naturally ventilated polyhouses', 'Hot desert conditions', 'Waterlogged soils', 'Deep shade'], 0,
    'Grown in Himachal Pradesh, Kashmir, the Nilgiris, Pune and Bengaluru areas.'],
  ['Support nets are laid in carnation beds to:', ['Keep the tall stems straight', 'Keep birds away', 'Shade the plants', 'Hold irrigation pipes'], 0,
    'Several layers of netting are raised as the crop grows.'],
  ['For distant markets, standard carnations are harvested at the:', ['"Paint-brush" stage, when petals just show above the calyx', 'Fully open stage', 'Tight green bud stage with no colour', 'Seed-set stage'], 0,
    'Bud-cut flowers are opened later in solutions.'],
  ['Carnation vase life is improved by pulsing with silver thiosulphate (STS) because carnation is:', ['Highly sensitive to ethylene', 'Insensitive to ethylene', 'A bulbous plant', 'A tropical fruit'], 0,
    'STS blocks ethylene action; sugar and biocides are also used in holding solutions.'],
  ['Carnation belongs to the genus:', ['*Dianthus* (*D. caryophyllus*)', '*Rosa*', '*Gerbera*', '*Chrysanthemum*'], 0,
    'Family Caryophyllaceae.'],
] },
{ p: 'A2', t: 'Post-harvest & Food Processing', w: 2, pyq: 'CSE-2026-A2-Q8c', q: [
  ['PM Kisan SAMPADA Yojana is an umbrella scheme for:', ['Food processing infrastructure such as food parks, cold chains and agro-processing clusters', 'Crop insurance', 'Direct income support', 'Soil health cards'], 0,
    'Run by the Ministry of Food Processing Industries.'],
  ['PMFME (2020) supports:', ['Formalisation and upgrading of micro food-processing enterprises, using a One District One Product approach', 'Only large multinational firms', 'Fertiliser plants', 'Seed production'], 0,
    'It offers credit-linked subsidy, training and branding support.'],
  ['The Production Linked Incentive Scheme for Food Processing Industry (PLISFPI, 2021) aims to:', ['Build globally competitive Indian food brands and boost processing capacity and exports', 'Subsidise imports', 'Fix MSP', 'Fund irrigation'], 0,
    'Incentives are linked to incremental sales.'],
  ['100% FDI in trading (including e-commerce) of food products manufactured or produced in India is allowed through the:', ['Government approval route', 'Automatic route with no conditions', 'Prohibited list', 'State government route only'], 0,
    '100% FDI in food processing manufacturing is under the automatic route.'],
  ['Mega Food Parks were designed to:', ['Provide common infrastructure linking farms, collection centres and processing units in a cluster', 'Serve as tourist parks', 'Grow crops for export only', 'Store fertiliser'], 0,
    'Hub-and-spoke model with primary processing centres near farms.'],
  ['National institutes for food technology education (NIFTEM) are located at:', ['Kundli (Haryana) and Thanjavur (Tamil Nadu)', 'Mysuru and Pune', 'Ludhiana and Hisar', 'Delhi and Kolkata'], 0,
    'CFTRI (Mysuru) is a CSIR laboratory.'],
  ['Food safety standards in India are set under the:', ['Food Safety and Standards Act, 2006 (FSSAI)', 'Seeds Act, 1966', 'Insecticides Act, 1968', 'Essential Commodities Act only'], 0,
    'FSSAI replaced several earlier laws such as the Prevention of Food Adulteration Act.'],
  ['Operation Greens was launched to:', ['Stabilise supply and prices of tomato, onion and potato and cut post-harvest loss', 'Increase green cover in cities', 'Promote organic farming only', 'Fund green energy'], 0,
    'It supports processing, storage and transport of these crops.'],
  ['A major reason for promoting food processing in India is:', ['Reducing post-harvest losses and adding value to farm produce', 'Increasing imports', 'Reducing farm incomes', 'Lowering rural employment'], 0,
    'It creates jobs and gives farmers more market outlets.'],
  ['Loans for food and agro-processing units can qualify for:', ['Priority sector lending by banks', 'No bank credit', 'Only foreign loans', 'Only microfinance'], 0,
    'Under RBI priority-sector norms, subject to limits and conditions.'],
] }
);
