/* PYQ-linked MCQs — CSE 2026 Agriculture Paper I, Section B (Q5–Q8). 10 MCQs per sub-question. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 2, pyq: 'CSE-2026-A1-Q5a', q: [
  ['The two broad approaches to soil conservation are:', ['Biological (agronomic/vegetative) and engineering (mechanical) measures', 'Chemical and nuclear measures', 'Irrigation and drainage only', 'Fertiliser and pesticide use'], 0,
    'Agronomic: contour farming, strip cropping, mulching, cover crops. Mechanical: bunds, terraces, check dams, waterways.'],
  ['Strip cropping controls erosion by:', ['Alternating strips of erosion-permitting and close-growing, erosion-resisting crops across the slope', 'Growing one crop on the whole slope', 'Ploughing up and down the slope', 'Burning crop residues'], 0,
    'Close-growing strips (legumes, grasses) slow runoff and trap soil from the row-crop strips.'],
  ['Graded bunds rather than contour bunds are preferred where:', ['Rainfall is high (over about 600 mm) and soils are less permeable, so excess water must be drained safely', 'Rainfall is very low and soils are sandy', 'Land is completely flat', 'The area is under forest'], 0,
    'Contour bunds hold water in place (low rainfall, permeable soils); graded bunds lead it slowly to a safe outlet.'],
  ['Bench terracing is used mainly on:', ['Steep hill slopes, converting them into a series of level steps', 'Flat alluvial plains', 'Sand dunes', 'Waterlogged valleys'], 0,
    'Common in the Himalaya and North-East; costly, so used where cultivation on slopes is unavoidable.'],
  ['Vetiver grass is used as a vegetative barrier because:', ['Its dense, deep fibrous roots and stiff stems form hedges that trap sediment', 'It fixes nitrogen', 'It is an annual that dies after one season', 'It spreads aggressively as a weed'], 0,
    '*Chrysopogon zizanioides* hedges on the contour act as living filters.'],
  ['Conservation tillage is usually defined as tillage leaving at least ___ of the soil surface covered by residue after planting.', ['30%', '5%', '75%', '100%'], 0,
    'Residue cover shields soil from raindrop impact and slows runoff.'],
  ['Mulching reduces water erosion mainly by:', ['Absorbing raindrop impact and slowing runoff', 'Increasing runoff speed', 'Making soil hydrophobic', 'Removing organic matter'], 0,
    'Raindrop splash detaches particles; a cover of mulch dissipates that energy.'],
  ['Gully control commonly uses:', ['Check dams, gully plugs and brushwood dams with vegetation', 'Deep ploughing of the gully', 'Burning vegetation around the gully', 'Clearing all trees from the catchment'], 0,
    'Structures reduce flow velocity and trap silt; vegetation then stabilises the deposits.'],
  ['Farm ponds support soil conservation by:', ['Harvesting runoff, cutting peak flows and erosion downstream, and providing life-saving irrigation', 'Draining groundwater', 'Increasing salinity', 'Replacing contour bunds entirely'], 0,
    'They are a key component of watershed and dryland programmes.'],
  ['The ICAR institute leading research on soil and water conservation is at:', ['Dehradun (ICAR-IISWC)', 'Karnal', 'Jodhpur', 'Bhopal'], 0,
    'Indian Institute of Soil and Water Conservation, with regional centres across India. CSSRI Karnal works on salinity; CAZRI Jodhpur on arid zones.'],
] },
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'CSE-2026-A1-Q5b', q: [
  ['Under the soil-moisture depletion approach, most field crops are irrigated when available soil moisture is depleted by about:', ['50%', '10%', '90%', '100%'], 0,
    'Sensitive crops/stages may need irrigation at 25–40% depletion; hardy crops can go further.'],
  ['Tensiometers are reliable for irrigation scheduling only up to a soil-water tension of about:', ['0.8 bar (80 kPa)', '15 bar', '31 bar', '5 bar'], 0,
    'Beyond this, air enters the porous cup. Useful for vegetables and orchards on light soils.'],
  ['With an IW/CPE ratio of 1.0 and a 6 cm irrigation depth, you irrigate when cumulative pan evaporation reaches:', ['6 cm', '3 cm', '12 cm', '1 cm'], 0,
    'CPE = IW ÷ ratio = 6 ÷ 1.0 = 6 cm. A ratio of 0.75 would mean irrigating at 8 cm CPE.'],
  ['For maize, the most critical stage for water stress is:', ['Tasselling and silking', 'Germination', 'Physiological maturity', 'Early vegetative stage only'], 0,
    'Stress then reduces pollination and kernel set sharply.'],
  ['The Crop Water Stress Index (CWSI) is based on:', ['The canopy–air temperature difference measured by infrared thermometry', 'Leaf colour', 'Soil pH', 'Root length'], 0,
    'Stressed plants transpire less, so their canopies become warmer.'],
  ['Crop evapotranspiration (ETc) is estimated as:', ['Kc × ETo', 'ETo ÷ Kc', 'Rainfall − ETo', 'Pan evaporation × soil depth'], 0,
    'ETo (reference ET) is usually computed by FAO Penman–Monteith; Kc varies with crop stage.'],
  ['The evaporation pan used as a standard for irrigation scheduling is the:', ['USWB Class A pan', 'Piche evaporimeter', 'Sunken Colorado pan only', 'Lysimeter'], 0,
    'A 121 cm diameter, 25.4 cm deep open pan; pan values are converted with a pan coefficient.'],
  ['Soil at 20% moisture (w/w) has field capacity 30%, bulk density 1.5 g/cm³ and a 60 cm root zone. The irrigation depth needed to reach field capacity is:', ['9 cm', '6 cm', '18 cm', '3 cm'], 0,
    'd = (0.30 − 0.20) × 1.5 × 60 cm = 9 cm.'],
  ['Time domain reflectometry (TDR) measures soil moisture through:', ['The dielectric constant of the soil, which depends mainly on water content', 'Neutron scattering', 'Soil colour', 'Soil temperature'], 0,
    'The neutron probe uses slowing of fast neutrons by hydrogen in water.'],
  ['The "feel and appearance" method of irrigation scheduling is:', ['A quick, low-cost field method that needs experience', 'The most accurate laboratory method', 'Based on satellite images', 'Used only in greenhouses'], 0,
    'Soil squeezed in the hand is judged against charts for each texture class.'],
] },
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'CSE-2026-A1-Q5c', q: [
  ['In a drip system, a sand (media) filter is used mainly to remove:', ['Organic matter and algae from open-well or canal water', 'Dissolved salts', 'Nitrate', 'Air bubbles'], 0,
    'Screen or disc filters follow it to remove fine inorganic particles.'],
  ['The usual order of pipes in a drip system from the head unit is:', ['Main line → sub-main → laterals → emitters', 'Laterals → main line → emitters → sub-main', 'Emitters → laterals → main line', 'Sub-main → emitters → main line'], 0,
    'The head unit (pump, filters, fertiliser injector, valves, gauges) feeds the main line.'],
  ['Pressure-compensating drippers are useful because they:', ['Deliver nearly the same discharge over a range of pressures, e.g., on slopes or long laterals', 'Need no filtration', 'Work without a pump in all cases', 'Increase the discharge as pressure rises'], 0,
    'This improves uniformity of water application.'],
  ['Typical discharge of a drip emitter is about:', ['2–8 litres per hour', '50–100 litres per hour', '0.01 litre per hour', '500 litres per hour'], 0,
    '4 L/h emitters are common for row crops and orchards.'],
  ['Drip systems usually operate at a pressure of about:', ['1–1.5 kg/cm²', '10–15 kg/cm²', '0.01 kg/cm²', '50 kg/cm²'], 0,
    'Much lower than sprinkler systems, which saves energy.'],
  ['A venturi injector draws fertiliser into a drip system by:', ['Creating suction through a pressure drop at a constriction', 'Using an electric pump only', 'Gravity from a hilltop tank', 'Mixing fertiliser in the well'], 0,
    'Fertigation delivers nutrients directly to the root zone in small, frequent doses.'],
  ['Flush valves at the ends of laterals and sub-mains are used to:', ['Periodically flush out sediment that settles in the pipes', 'Control fertiliser dose', 'Measure pressure', 'Release air only'], 0,
    'Regular flushing helps prevent emitter clogging.'],
  ['Chlorination of a drip system mainly prevents clogging by:', ['Bacterial slime and algae', 'Calcium carbonate precipitates', 'Sand particles', 'Air locks'], 0,
    'Acid injection (e.g., HCl) is used to dissolve chemical precipitates such as calcium carbonate.'],
  ['An air-release/vacuum-relief valve in a drip system:', ['Prevents air locks and stops soil being sucked into emitters when the system shuts down', 'Adds fertiliser', 'Filters water', 'Measures discharge'], 0,
    'Installed at high points and at the head unit.'],
  ['Subsurface drip irrigation (SDI) differs from surface drip in that:', ['Laterals are buried below the soil surface, reducing evaporation and weed growth', 'It uses sprinklers', 'It floods the field', 'It needs no filters'], 0,
    'Used in sugarcane and other long-duration crops; root intrusion must be managed.'],
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'CSE-2026-A1-Q5d', q: [
  ['The Fair and Remunerative Price (FRP) of sugarcane is fixed under the:', ['Sugarcane (Control) Order, 1966', 'APMC Act', 'Seeds Act, 1966', 'Insecticides Act, 1968'], 0,
    'Issued under the Essential Commodities Act; the Centre fixes FRP on CACP’s recommendation. Some states add a State Advised Price (SAP).'],
  ['Under PM-AASHA, the "Price Deficiency Payment" component means:', ['Paying farmers the difference between MSP and the market price, without physical procurement', 'Buying all produce at MSP', 'Paying a fixed amount per hectare', 'Subsidising fertiliser prices'], 0,
    'PM-AASHA (2018) also includes the Price Support Scheme and a pilot for private procurement.'],
  ['The Market Intervention Scheme (MIS) is used for:', ['Perishable commodities not covered by MSP, when prices crash', 'Wheat and rice only', 'Export promotion', 'Fertiliser distribution'], 0,
    'Implemented at the request of a state, with losses shared between Centre and state.'],
  ['The Price Stabilisation Fund is used mainly to:', ['Build buffer stocks of perishables such as onion, potato and pulses to moderate prices', 'Pay crop insurance claims', 'Fund irrigation projects', 'Give interest subvention on loans'], 0,
    'Stocks are released into the market when prices spike.'],
  ['The Open Market Sale Scheme (OMSS) of FCI is used to:', ['Sell surplus wheat or rice in the open market to cool prices', 'Buy produce from farmers at MSP', 'Export food grains', 'Import pulses'], 0,
    'It also reduces the cost of holding excess central-pool stocks.'],
  ['Stock limits on traders to curb hoarding are imposed under the:', ['Essential Commodities Act, 1955', 'Seeds Act, 1966', 'Forest Rights Act, 2006', 'Consumer Protection Act only'], 0,
    'A traditional tool of price control on the demand–supply side.'],
  ['Using export restrictions as a price-policy tool mainly aims to:', ['Increase domestic supply and restrain consumer prices', 'Raise farm-gate prices', 'Increase foreign exchange earnings', 'Reduce production'], 0,
    'Such restrictions protect consumers but can reduce farmers’ gains.'],
  ['"Inter-crop price parity", considered by CACP, refers to:', ['Keeping relative prices of competing crops balanced so crop choice is not distorted', 'Equal prices for all crops', 'Parity between farm and industrial wages', 'Prices in neighbouring countries only'], 0,
    'CACP also considers cost of production, demand–supply, price trends, terms of trade and effects on consumers.'],
  ['Under Decentralised Procurement (DCP), food grains are:', ['Procured, stored and distributed by the state government itself, with the Centre bearing eligible costs', 'Procured only by FCI', 'Imported by the states', 'Sold only through private traders'], 0,
    'DCP (from 1997–98) encourages procurement in more states and saves transport costs.'],
  ['The main objective of agricultural price policy is to:', ['Assure remunerative prices to farmers while keeping food affordable for consumers', 'Maximise traders’ margins', 'Fix all retail prices', 'Discourage crop diversification'], 0,
    'Instruments include MSP, procurement, buffer stocks, PDS, trade policy and market intervention.'],
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'CSE-2026-A1-Q5e', q: [
  ['Farm planning is best described as:', ['Deciding the combination of enterprises and practices that best meets farm goals within available resources', 'Only keeping farm accounts', 'Buying the cheapest inputs', 'Growing whatever neighbours grow'], 0,
    'It covers what, how and how much to produce, and when.'],
  ['The first step in farm planning is:', ['Taking an inventory of farm resources (land, labour, capital, water)', 'Selling the produce', 'Applying for a loan', 'Buying machinery'], 0,
    'Then: define goals and problems, list alternatives, budget them, choose, implement, and monitor.'],
  ['Linear programming is used in farm planning to:', ['Find the enterprise combination that maximises profit within resource constraints', 'Forecast rainfall', 'Measure soil fertility', 'Estimate crop water needs'], 0,
    'It handles several activities and constraints (land, labour, capital, water) at once.'],
  ['Partial budgeting is appropriate when:', ['A small change is being considered, such as adding one enterprise or a new practice', 'The whole farm is being reorganised', 'No records are available', 'Only market prices matter'], 0,
    'It compares added returns + reduced costs with added costs + reduced returns.'],
  ['Complete (whole-farm) budgeting is used when:', ['The entire farm organisation is being planned afresh or changed substantially', 'Changing a single input', 'Checking daily expenses', 'Estimating one crop’s yield'], 0,
    'It projects total costs and returns for all enterprises together.'],
  ['A good farm plan should be:', ['Flexible and make efficient use of resources while allowing for risk', 'Rigid and unchangeable', 'Based on one crop only', 'Independent of market conditions'], 0,
    'It should also be simple enough for the farmer to follow.'],
  ['Farm records are essential for planning because they:', ['Show past costs, yields and returns needed to budget alternatives', 'Replace the need for planning', 'Are needed only for taxes', 'Show only land area'], 0,
    'Inventory, production, labour and financial records together.'],
  ['The scale of finance used by banks for crop loans is fixed by the:', ['District Level Technical Committee (DLTC)', 'Reserve Bank of India for each village', 'Farmers individually', 'Gram Panchayat only'], 0,
    'It reflects cost of cultivation per hectare in the district; farm plans help set credit limits (e.g., Kisan Credit Card).'],
  ['Including crop insurance and diversification in a farm plan mainly helps to:', ['Manage risk and uncertainty', 'Increase input costs', 'Reduce yields', 'Avoid record-keeping'], 0,
    'Yield and price risks are major threats to farm income.'],
  ['Choosing crops in which the farm has a relative cost advantage follows the principle of:', ['Comparative advantage', 'Diminishing returns', 'Substitution only', 'Time comparison only'], 0,
    'Regions and farms should specialise where their relative costs are lowest.'],
] },
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'CSE-2026-A1-Q6a', q: [
  ['Boron in irrigation water needs special attention because:', ['The range between deficiency and toxicity is narrow', 'Boron is not essential for plants', 'Boron always improves yields', 'Boron is removed easily by any irrigation'], 0,
    'A few tenths of a mg/L can harm sensitive crops.'],
  ['In the widely used boron classification (USDA Handbook 60 / Scofield), irrigation water with boron above about ___ is unsuitable even for tolerant crops.', ['3.75 mg/L', '0.33 mg/L', '1.0 mg/L', '0.1 mg/L'], 0,
    'Class limits differ for sensitive, semi-tolerant and tolerant crops; for sensitive crops water above about 1.25 mg/L is unsuitable.'],
  ['In the same classification, "excellent" water for boron-sensitive crops has boron below about:', ['0.33 mg/L', '1.0 mg/L', '2.0 mg/L', '3.75 mg/L'], 0,
    'For semi-tolerant crops the excellent limit is about 0.67 mg/L and for tolerant crops about 1.0 mg/L.'],
  ['Which crop is highly tolerant of boron in irrigation water?', ['Date palm', 'Lemon', 'Walnut', 'Beans'], 0,
    'Also sugar beet, lucerne, cotton and asparagus are fairly tolerant.'],
  ['Which crop is boron-sensitive?', ['Citrus (lemon, orange)', 'Date palm', 'Sugar beet', 'Asparagus'], 0,
    'Stone fruits, avocado, walnut and beans are also sensitive.'],
  ['Boron toxicity usually shows first as:', ['Yellowing and burning of tips and margins of older leaves', 'Purple colour of young stems', 'Interveinal chlorosis of young leaves', 'Wilting of roots only'], 0,
    'Boron moves with the transpiration stream and accumulates at leaf tips and margins.'],
  ['Reclaiming boron-affected soils is difficult because:', ['Boron is adsorbed and leaches slowly, needing much more water than soluble salts', 'Boron is volatile', 'Boron forms insoluble gypsum', 'Boron is fixed permanently in organic matter'], 0,
    'Leaching boron may need about three times the water needed to leach the same fraction of salts.'],
  ['Available boron in soils is usually extracted with:', ['Hot water (Berger and Truog method)', '0.5 M NaHCO₃', 'Neutral normal ammonium acetate', 'DTPA'], 0,
    'DTPA is used for Zn, Fe, Cu and Mn; NaHCO₃ (Olsen) for P.'],
  ['Boron deficiency often reduces fruit and seed set because boron is needed for:', ['Pollen germination and pollen-tube growth', 'Chlorophyll synthesis', 'Nitrogen fixation only', 'Root respiration'], 0,
    'It is also needed for cell-wall formation and sugar transport.'],
  ['A complete appraisal of irrigation-water quality considers:', ['Salinity (EC), sodicity (SAR/RSC) and specific-ion toxicity such as boron and chloride', 'Colour of the water only', 'Water temperature only', 'Only the source of the water'], 0,
    'Boron is the classic specific-ion hazard alongside Na and Cl.'],
] },
{ p: 'A1', t: 'Environment, Organic & Natural Farming', w: 2, pyq: 'CSE-2026-A1-Q6b', q: [
  ['Distillery spentwash is characterised by:', ['Very high BOD/COD, low pH and high potassium and organic matter', 'Low BOD and high pH', 'High chromium only', 'Pure water with dissolved oxygen'], 0,
    'Diluted, treated spentwash (or biocompost made with press mud) can supply K, but raw use causes salinity and pollution.'],
  ['The most hazardous heavy metal in tannery effluents is:', ['Chromium, especially hexavalent Cr(VI)', 'Zinc', 'Iron', 'Calcium'], 0,
    'Tannery clusters (e.g., Vellore–Ranipet, Kanpur) have contaminated soils and groundwater; effluents are also high in salts.'],
  ['"Itai-itai" disease is caused by chronic exposure to:', ['Cadmium', 'Mercury', 'Arsenic', 'Lead'], 0,
    'Minamata disease is from methylmercury. Both came from industrial pollution entering the food chain.'],
  ['Long-term irrigation with sodium-rich industrial effluent mainly causes:', ['Soil dispersion, crusting and poor infiltration (sodicity)', 'Improved soil structure', 'Higher soil organic carbon only', 'Lower soil pH'], 0,
    'High Na displaces Ca and Mg on exchange sites.'],
  ['Liming metal-contaminated acid soils reduces metal uptake by crops because:', ['A higher pH lowers the solubility of most heavy metals', 'Lime adds heavy metals', 'Lime makes metals volatile', 'Lime increases metal solubility'], 0,
    'Other options: organic amendments that bind metals, phytoremediation and growing non-food crops.'],
  ['A concern when applying large doses of fly ash to soil is:', ['Boron toxicity and heavy-metal loading', 'Nitrogen overload', 'Excess organic matter', 'Soil acidification in all soils'], 0,
    'Low doses can improve texture of sandy or clayey soils and supply some micronutrients.'],
  ['Press mud from sugar factories is useful as a soil amendment because it:', ['Supplies organic matter, calcium and phosphorus and helps reclaim sodic soils', 'Contains chromium', 'Is highly acidic', 'Sterilises the soil'], 0,
    'Often composted with spentwash to make biocompost.'],
  ['Under the Environment (Protection) Rules, the general standard for BOD of effluent discharged on land for irrigation is:', ['100 mg/L', '30 mg/L', '350 mg/L', '5 mg/L'], 0,
    'For discharge into inland surface water the limit is 30 mg/L.'],
  ['Pulp and paper mill effluents are of concern mainly because of:', ['Lignin-derived colour and chlorinated organic compounds from bleaching', 'High potassium only', 'Radioactivity', 'Pesticide residues'], 0,
    'Adsorbable organic halides (AOX) are toxic; elemental-chlorine-free bleaching reduces them.'],
  ['*Brassica juncea* (Indian mustard) is used in phytoremediation because it:', ['Accumulates heavy metals such as lead and cadmium in its shoots', 'Fixes nitrogen', 'Degrades plastics', 'Neutralises acidity'], 0,
    'Metal-rich biomass is then harvested and disposed of safely.'],
] },
{ p: 'A1', t: 'Dryland Farming & Watershed Management', w: 2, pyq: 'CSE-2026-A1-Q6c', q: [
  ['The most important constraint of dryland agriculture is:', ['Erratic, uncertain rainfall with long dry spells', 'Excess irrigation water', 'Very high soil fertility', 'Too much mechanisation'], 0,
    'Other constraints: low-fertility shallow soils, erosion, low investment and poor adoption of technology.'],
  ['Rainfed land in India covers roughly ___ of the net sown area.', ['About half', 'About one-tenth', 'About 90%', 'About one-fifth'], 0,
    'It produces a large share of pulses, oilseeds, millets and cotton; it also supports most livestock.'],
  ['When the monsoon onset is delayed, a standard contingency measure is to:', ['Sow short-duration varieties or switch to alternative crops', 'Sow long-duration varieties later', 'Leave land fallow for the whole year', 'Apply more fertiliser at sowing'], 0,
    'District contingency plans list crop and variety options for each delay period.'],
  ['During a mid-season dry spell, a recommended practice is to:', ['Thin the crop stand and mulch to conserve moisture', 'Apply heavy doses of nitrogen', 'Increase plant population', 'Plough deeply between rows'], 0,
    'Reducing plant population lowers water demand; weeding removes competition.'],
  ['The broad bed and furrow (BBF) system was developed by ICRISAT mainly for:', ['Vertisols, to drain excess water and conserve moisture', 'Sand dunes', 'Saline coastal soils', 'Peat soils'], 0,
    'Beds about 1.5 m wide separated by furrows improve drainage in heavy black soils.'],
  ['Compartmental bunding in dryland fields is used to:', ['Hold rainwater in small compartments so it infiltrates in place', 'Drain water quickly off the field', 'Irrigate by flooding', 'Prevent all runoff from the whole watershed'], 0,
    'Common for rabi sorghum on Vertisols of Karnataka and Maharashtra.'],
  ['Intercropping pigeonpea with sorghum or pearl millet in drylands mainly provides:', ['Insurance against crop failure and better use of moisture over time', 'Higher water use at sowing only', 'Complete weed control', 'More uniform crop maturity'], 0,
    'The crops have different durations and rooting depths, spreading risk.'],
  ['Alternate land-use systems for marginal drylands include:', ['Agroforestry, silvipasture and horti-pasture', 'Continuous cereal monocropping', 'Rice–wheat', 'Paddy under flooding'], 0,
    'They give income and cover on land unsuited to arable cropping.'],
  ['Water harvested in farm ponds in drylands is best used for:', ['Life-saving irrigation at critical crop stages', 'Flooding the whole field', 'Industrial use', 'Fish only'], 0,
    'Even one irrigation at flowering or grain filling can raise yields substantially.'],
  ['Ridges and furrows or tied ridges in drylands mainly help by:', ['Holding rainwater in furrows for in-situ moisture conservation', 'Increasing runoff', 'Raising soil salinity', 'Reducing infiltration'], 0,
    'Tied ridges have cross-ties in furrows that stop water from running off.'],
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'CSE-2026-A1-Q7a', q: [
  ['In Indian farm-management cost concepts, net income is gross income minus:', ['Cost C2 (all paid-out and imputed costs)', 'Cost A1 only', 'Cost of seed only', 'Family labour cost only'], 0,
    'Farm business income = gross income − cost A1 (or A2); family labour income = gross income − cost B2.'],
  ['The three basic production decisions on a farm are:', ['What to produce, how to produce and how much to produce', 'Where to sell, whom to hire and when to rest', 'Which bank, which insurer and which trader', 'Which caste, which village and which season'], 0,
    'These relate to enterprise choice, input combination and the level of output.'],
  ['The profit-maximising level of a variable input is where:', ['Its marginal value product equals its price', 'Total output is maximum', 'Average product is maximum', 'Input use is zero'], 0,
    'Beyond this point, the extra return is less than the extra cost.'],
  ['The least-cost combination of two inputs is where:', ['The marginal rate of technical substitution equals the inverse ratio of their prices', 'Both inputs are used equally', 'The cheaper input is used alone', 'Total cost is maximum'], 0,
    'Principle of substitution between inputs.'],
  ['Allocating limited capital so that the last rupee earns the same return in every use follows the principle of:', ['Equi-marginal returns', 'Diminishing returns only', 'Comparative advantage only', 'Opportunity cost only'], 0,
    'It guides how to divide scarce resources among enterprises.'],
  ['A farm has fixed costs of ₹60,000; the output price is ₹2,000 per quintal and variable cost is ₹1,400 per quintal. Break-even output is:', ['100 quintals', '30 quintals', '43 quintals', '150 quintals'], 0,
    'Break-even = fixed cost ÷ (price − variable cost per unit) = 60,000 ÷ 600 = 100 q.'],
  ['Negotiable warehouse receipts help farmers raise profits mainly by:', ['Letting them store produce and borrow against it instead of selling at harvest-time low prices', 'Guaranteeing MSP for all crops', 'Replacing crop insurance', 'Eliminating storage losses completely'], 0,
    'Issued by warehouses registered with WDRA (Warehousing Development and Regulatory Authority).'],
  ['Which factor most directly raises farm profit when prices are given?', ['Higher yields and lower cost per unit of output', 'Using more inputs than needed', 'Delaying all operations', 'Selling immediately at harvest regardless of price'], 0,
    'Other factors: farm size, enterprise mix, labour and machine efficiency, timeliness and marketing.'],
  ['Timeliness of operations affects farm profit mainly because:', ['Late sowing, weeding or irrigation cuts yields without cutting costs', 'It lowers input prices', 'It reduces taxes', 'It has no effect on yield'], 0,
    'E.g., each week’s delay in wheat sowing after mid-November reduces yield.'],
  ['Opportunity cost of family labour used on the farm is:', ['The income that labour could have earned in its next-best use', 'Always zero', 'The price of fertiliser', 'The land revenue paid'], 0,
    'Imputed costs such as family labour and owned land are included in cost B2/C2.'],
] },
{ p: 'A1', t: 'Agricultural Extension', w: 2, pyq: 'CSE-2026-A1-Q7b', q: [
  ['The key difference between extension education and extension service is that:', ['Education is the process/discipline of changing people’s behaviour through teaching; service is the organisation that delivers it', 'They are identical', 'Service is only research', 'Education deals only with inputs'], 0,
    'Extension service = government departments, KVKs, ATMA and other agencies; extension education = the applied science behind their methods.'],
  ['Extension education aims to bring desirable changes in people’s:', ['Knowledge, skills and attitudes', 'Land holdings only', 'Caste and religion', 'Market prices'], 0,
    'Changes in KSA lead to adoption of improved practices and better living.'],
  ['Extension education is called an applied behavioural science because it:', ['Applies findings from sociology, psychology, communication and economics to change behaviour, and tests them systematically', 'Studies only crop yields', 'Deals only with farm machinery', 'Uses no scientific method'], 0,
    'It has its own research base on adoption, communication and programme evaluation.'],
  ['"Learning by doing" as an extension principle means:', ['Farmers learn best by practising the technology themselves, e.g., in demonstrations', 'Farmers should only read books', 'Only scientists should try new practices', 'Learning happens only in classrooms'], 0,
    'Other principles: felt needs, participation, cultural difference, adaptability, whole family, satisfaction.'],
  ['A method demonstration shows farmers:', ['How to carry out a practice step by step, such as seed treatment', 'The final yield of a new variety', 'Market prices', 'Weather forecasts'], 0,
    'A result demonstration shows the outcome of a practice compared with the old one.'],
  ['The basic philosophy of extension is to:', ['Help people to help themselves', 'Give free inputs forever', 'Make farmers dependent on officials', 'Replace farmers’ knowledge entirely'], 0,
    'Self-reliance through education is the goal.'],
  ['The Source–Message–Channel–Receiver (SMCR) model of communication was given by:', ['David Berlo', 'Everett Rogers', 'Harold Lasswell', 'Wilbur Schramm'], 0,
    'Lasswell’s model asks who says what in which channel to whom with what effect.'],
  ['In Rogers’ adoption process, the stage at which a farmer tries an innovation on a small scale is:', ['Trial', 'Awareness', 'Interest', 'Adoption'], 0,
    'Stages: awareness → interest → evaluation → trial → adoption.'],
  ['Which is an example of a mass extension method?', ['Radio or TV farm programmes', 'Farm and home visits', 'Method demonstration to a group', 'Personal letter to one farmer'], 0,
    'Individual methods: farm visits, office calls; group methods: demonstrations, field days, meetings.'],
  ['Which is an example of an extension SERVICE (rather than education as a discipline)?', ['A Krishi Vigyan Kendra delivering training and demonstrations in a district', 'A theory of diffusion of innovations', 'A communication model', 'A principle of learning'], 0,
    'KVKs, ATMA, state departments and NGOs are service organisations.'],
] },
{ p: 'A1', t: 'Dryland Farming & Watershed Management', w: 2, pyq: 'CSE-2026-A1-Q7c', q: [
  ['Treatment in watershed programmes normally follows the:', ['Ridge-to-valley sequence', 'Valley-to-ridge sequence', 'Random order', 'Village-to-city sequence'], 0,
    'Upper reaches are treated first so that downstream structures are not silted up.'],
  ['Integrated watershed management combines:', ['Soil and water conservation, crop and livestock development, afforestation and livelihoods for the landless', 'Only check dams', 'Only tree planting', 'Only road building'], 0,
    'It targets both natural-resource conservation and household income.'],
  ['The Integrated Watershed Management Programme (IWMP, 2009–10) is now implemented as:', ['The Watershed Development Component of PMKSY (WDC-PMKSY)', 'MGNREGA only', 'National Horticulture Mission', 'Soil Health Card scheme'], 0,
    'WDC-PMKSY 2.0 runs under the Department of Land Resources.'],
  ['The Watershed Development Fund built from beneficiaries’ contributions is used for:', ['Maintaining the created assets after the project ends', 'Paying salaries of officials', 'Buying fertilisers for all farmers', 'Construction of roads only'], 0,
    'Encourages community ownership and sustainability.'],
  ['Kothapally, a model of consortium-based watershed development, is associated with:', ['ICRISAT, in Telangana', 'CAZRI, in Rajasthan', 'IARI, in Delhi', 'CSSRI, in Haryana'], 0,
    'It combined water harvesting, improved crops and farmer participation, and raised groundwater and incomes.'],
  ['Percolation tanks are built mainly to:', ['Recharge groundwater by holding runoff over permeable strata', 'Store water for drinking only', 'Drain waterlogged land', 'Generate electricity'], 0,
    'Wells downstream benefit from raised water tables.'],
  ['Livelihood support for landless households in watershed projects is usually provided through:', ['Self-help group based enterprises such as dairy, goat rearing and small businesses', 'Allotting irrigation water only to them', 'Exempting them from the project', 'Only compensation payments'], 0,
    'The landless benefit little from land treatment, so separate livelihood components are included.'],
  ['A key indicator of livelihood impact of a watershed project is:', ['Rise in cropping intensity and household income with less distress migration', 'Number of meetings held', 'Number of officials trained', 'Length of roads built'], 0,
    'Also: groundwater levels, fodder availability, vegetative cover and reduced soil loss.'],
  ['People’s participation in watershed projects is organised through:', ['Watershed committees, user groups and self-help groups', 'Only the district collector', 'Private contractors alone', 'The state police'], 0,
    'Common guidelines stress community planning, execution and maintenance.'],
  ['"Nala bunds" in watershed development are:', ['Small earthen or masonry bunds across drainage lines to store water and trap silt', 'Bunds along the field boundary', 'Canal lining', 'Terrace risers'], 0,
    'They slow runoff and increase recharge.'],
] },
{ p: 'A1', t: 'Agricultural Extension', w: 2, pyq: 'CSE-2026-A1-Q8a', q: [
  ['The main difference between monitoring and evaluation is that monitoring is:', ['Continuous tracking of inputs, activities and outputs during implementation', 'A one-time assessment of long-term impact', 'Done only by external experts', 'Done only after the programme ends'], 0,
    'Evaluation is periodic and judges effectiveness, outcomes and impact.'],
  ['Evaluation carried out before a programme starts, to judge its feasibility, is:', ['Ex-ante evaluation', 'Ex-post evaluation', 'Terminal evaluation', 'Concurrent evaluation'], 0,
    'Concurrent (ongoing) during implementation; terminal at completion; ex-post some time after completion.'],
  ['Formative evaluation is conducted:', ['During implementation, to improve the programme', 'Only at the end, to judge overall success', 'Before any planning', 'Only by donors'], 0,
    'Summative evaluation judges overall worth at the end (Scriven’s terms).'],
  ['The "with and without" approach in impact evaluation compares:', ['Participants with a comparable group that did not get the programme', 'The same farmers before and after only', 'Two unrelated districts at random', 'Officials with farmers'], 0,
    'Combining "before–after" with "with–without" (difference-in-differences) gives a stronger estimate.'],
  ['Bennett’s hierarchy for evaluating extension programmes rises from inputs and activities to:', ['Changes in knowledge, attitudes, skills, practices and finally end results', 'Only the number of meetings held', 'Budget spent only', 'Staff promotions'], 0,
    'Levels: inputs, activities, participation, reactions, KASA change, practice change, end results.'],
  ['A baseline survey is needed mainly to:', ['Record the situation before the programme so that change can be measured later', 'Select staff', 'Print publicity material', 'Fix market prices'], 0,
    'Without a baseline, impact claims are weak.'],
  ['A logical framework (logframe) for a programme links:', ['Goal, purpose, outputs and activities with indicators and assumptions', 'Only the budget and staff', 'Only the farmers’ names', 'Only weather data'], 0,
    'It provides the basis for both monitoring and evaluation.'],
  ['Participatory evaluation involves:', ['Farmers and other stakeholders in judging the programme’s performance', 'Only external consultants', 'Only the funding agency', 'Only computer simulation'], 0,
    'It builds ownership and captures local views on benefits and problems.'],
  ['Good indicators for monitoring should be:', ['Specific, measurable, achievable, relevant and time-bound (SMART)', 'Vague and general', 'Unrelated to objectives', 'Impossible to measure'], 0,
    'E.g., "number of farmers adopting zero tillage in 2026–27".'],
  ['Terminal evaluation is carried out:', ['At the end of a programme to assess what it achieved', 'Before starting a programme', 'Daily by field staff', 'Only when a programme fails'], 0,
    'Ex-post evaluation, some years later, looks at sustained impact.'],
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'CSE-2026-A1-Q8b', q: [
  ['"Uzhavar Sandhai" farmers’ markets are run in:', ['Tamil Nadu', 'Punjab', 'Andhra Pradesh', 'Odisha'], 0,
    'Andhra Pradesh: Rythu Bazaars; Punjab: Apni Mandis; Odisha: Krushak Bazaars. They allow direct farmer-to-consumer sale.'],
  ['The main rationale of farmers’ markets is to:', ['Remove intermediaries so farmers get a higher share and consumers pay less', 'Increase the number of middlemen', 'Promote exports only', 'Replace MSP'], 0,
    'Direct sale also gives consumers fresh produce and farmers quick cash.'],
  ['Producer’s share in the consumer’s rupee is:', ['(Price received by farmer ÷ price paid by consumer) × 100', 'Consumer price − farm price', 'Marketing cost ÷ farm price', 'Farm price × quantity sold'], 0,
    'Farmers’ markets typically raise this share for fruits and vegetables.'],
  ['"Price spread" refers to:', ['The difference between the price paid by the consumer and the price received by the farmer', 'The range of prices across states', 'The MSP minus market price', 'The profit of the farmer'], 0,
    'It is made up of marketing costs and intermediaries’ margins.'],
  ['Shepherd’s formula for marketing efficiency is:', ['(Value of goods sold ÷ total marketing cost) − 1', 'Marketing cost ÷ farm price', 'Producer’s share × 100', 'Consumer price ÷ quantity'], 0,
    'Higher values indicate a more efficient marketing channel.'],
  ['Direct marketing by farmers outside regulated APMC yards was enabled by the model laws of:', ['2003 (Model APMC Act) and 2017 (Model APLM Act)', '1966 (Seeds Act)', '1955 (Essential Commodities Act)', '2013 (Food Security Act)'], 0,
    'States that adopted these provisions allowed farmers’ markets, private markets and direct purchase.'],
  ['Gramin Agricultural Markets (GrAMs), announced in 2018, aim to:', ['Upgrade rural haats into local markets linked to e-NAM', 'Build export zones', 'Set up cold chains only in cities', 'Replace APMCs'], 0,
    'Rural haats are close to small farmers, reducing transport costs.'],
  ['A key limitation of farmers’ markets is:', ['Limited volume and space, suiting mainly perishables sold locally', 'They always raise consumer prices', 'They need export licences', 'They cannot sell vegetables'], 0,
    'Genuine farmers must be identified (e.g., ID cards) to keep traders out.'],
  ['Consumers benefit from farmers’ markets mainly through:', ['Fresher produce at lower prices', 'Higher prices', 'Imported goods', 'Longer supply chains'], 0,
    'Prices are often set daily by market committees below retail levels.'],
  ['Intermediaries (commission agents, retailers) are affected by farmers’ markets mainly through:', ['Loss of part of their margins and business', 'Guaranteed profits', 'No effect at all', 'Higher commissions'], 0,
    'Stakeholder effects: farmers gain share, consumers gain prices, intermediaries lose margin, government eases price pressure.'],
] },
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 2, pyq: 'CSE-2026-A1-Q8c', q: [
  ['The process that moves most soil during wind erosion is:', ['Saltation (bouncing particles)', 'Suspension', 'Surface creep', 'Splash'], 0,
    'Saltation accounts for roughly 50–75% of movement, suspension 3–40%, surface creep 5–25%.'],
  ['Soil particles most easily moved by wind are about:', ['0.1 mm (fine sand)', '2 mm (gravel)', '0.001 mm (fine clay)', '10 mm'], 0,
    'Larger grains are too heavy; very fine particles are held by cohesion unless disturbed.'],
  ['The Wind Erosion Equation (Woodruff and Siddoway, 1965) estimates soil loss as a function of:', ['Soil erodibility, ridge roughness, climate, field length and vegetative cover', 'Rainfall erosivity only', 'Slope length and steepness only', 'Crop price and yield'], 0,
    'E = f(I, K, C, L, V).'],
  ['The area protected downwind of a windbreak extends to about:', ['10–20 times the windbreak height', '1–2 times its height', '100 times its height', 'Only its own width'], 0,
    'Density and orientation (perpendicular to prevailing wind) matter.'],
  ['Wind strip cropping means:', ['Alternating strips of crops and fallow or close-growing crops at right angles to the prevailing wind', 'Growing crops along the wind direction', 'Planting trees in circles', 'Strips on the contour for water erosion only'], 0,
    'Narrow strips reduce the distance over which wind can pick up soil.'],
  ['Emergency tillage to control wind erosion aims to:', ['Roughen the surface with clods and ridges perpendicular to the wind', 'Make the surface smooth and fine', 'Remove all residues', 'Plough along the wind direction'], 0,
    'Clods and ridges trap moving particles and reduce surface wind speed.'],
  ['Stubble mulching controls wind erosion by:', ['Keeping crop residues anchored on the surface to reduce wind speed at the soil', 'Burning stubble', 'Burying all residues', 'Watering the soil'], 0,
    'Standing stubble is more effective than flattened residue.'],
  ['Sand dunes in western Rajasthan are stabilised (CAZRI method) by:', ['Protecting them from grazing, erecting micro-windbreaks in a checkerboard and planting trees, shrubs and grasses', 'Flooding them with canal water', 'Levelling them with bulldozers only', 'Spraying them with oil'], 0,
    'Species used include *Prosopis juliflora*, *Acacia tortilis*, *Calligonum polygonoides* and grasses such as *Lasiurus sindicus*.'],
  ['Sewan grass (*Lasiurus sindicus*) is valued in the Thar for:', ['Stabilising sandy soils and providing nutritious fodder', 'Timber', 'Fibre for ropes only', 'Oil extraction'], 0,
    'A perennial, drought-hardy grass of the best rangelands of western Rajasthan.'],
  ['Wind erosion is most serious in India in:', ['The arid and semi-arid north-west (western Rajasthan, Kutch and adjoining Haryana and Punjab)', 'The Western Ghats', 'The Brahmaputra valley', 'Kerala'], 0,
    'Low rainfall, sandy soils, strong summer winds and sparse cover combine there.'],
] }
);
