/* PYQ-linked MCQs — IFoS 2017 Agriculture Paper I, Q1–Q4 (verbatim PYQs). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Agro-climatic Zones & Cropping Systems', w: 2, pyq: 'IFoS-2017-A1-Q1a', q: [
  ['Mean annual rainfall in arid western Rajasthan is mostly:', ['Below about 400 mm, and highly erratic', 'Above 1,500 mm', 'About 1,000 mm and reliable', 'Over 2,500 mm'], 0,
    'The coefficient of variation of rainfall is very high there.'],
  ['The length of growing period (LGP) in arid western Rajasthan is usually:', ['Less than 90 days', '150–210 days', 'Over 270 days', 'The whole year'], 0,
    'Only short-duration crops can mature in time.'],
  ['Farmers in the arid western zone prefer crops such as:', ['Pearl millet, moth bean, clusterbean and sesame', 'Rice, jute and sugarcane', 'Tea and rubber', 'Banana and coconut'], 0,
    'These crops are short-duration and drought-hardy.'],
  ['A climatic hazard of the western arid zone in summer is:', ['Very high temperatures (over 45 °C) and hot winds (loo) that cause wind erosion', 'Heavy snowfall', 'Cyclones every month', 'Continuous rain'], 0,
    'Shelterbelts and stubble mulching reduce wind erosion.'],
  ['In arid regions, potential evapotranspiration (PET):', ['Far exceeds rainfall, giving a large water deficit', 'Equals rainfall', 'Is less than rainfall', 'Is zero'], 0,
    'Aridity indices (Thornthwaite) are based on this deficit.'],
  ['On the Vertisols of the western plateau (Maharashtra), a major rabi crop grown on stored moisture is:', ['Rabi sorghum', 'Rice', 'Jute', 'Tea'], 0,
    'Cotton and soybean dominate the kharif season.'],
  ['India’s largest producer of castor is:', ['Gujarat', 'Kerala', 'Punjab', 'Assam'], 0,
    'Gujarat also leads in cumin and isabgol with Rajasthan.'],
  ['Cumin and isabgol (*Plantago ovata*) are rabi crops of:', ['Gujarat and Rajasthan', 'Kerala and Tamil Nadu', 'Assam and Bengal', 'Himachal and Uttarakhand'], 0,
    'The cool, dry winters suit these seed spices.'],
  ['A winter hazard for mustard in Rajasthan is:', ['Frost', 'Flooding', 'Cyclones', 'Hailstorms every week'], 0,
    'Light irrigation before a frost night protects the crop.'],
  ['The ICAR institute for arid-zone research is located at:', ['Jodhpur (CAZRI)', 'Hyderabad (CRIDA)', 'Karnal (CSSRI)', 'Dehradun (IISWC)'], 0,
    'CAZRI works on sand-dune stabilisation and arid land use.']
] },
{ p: 'A1', t: 'Crop Production', w: 2, pyq: 'IFoS-2017-A1-Q1b', q: [
  ['Edaphic factors are:', ['Soil-related factors such as texture, structure, pH, organic matter and soil organisms', 'Climatic factors only', 'Topographic factors only', 'Biotic factors above ground only'], 0,
    'They strongly influence crop growth.'],
  ['Most crops grow best at a soil pH of about:', ['6.5–7.5', '4.0–4.5', '9.0–10.0', '2.0–3.0'], 0,
    'Most nutrients are readily available in this range.'],
  ['The soil texture generally best for crops is:', ['Loam — a balance of sand, silt and clay', 'Pure sand', 'Heavy clay', 'Gravel'], 0,
    'Loam holds water and nutrients yet drains well.'],
  ['Soil organic matter supports sustainable agriculture mainly by:', ['Improving structure, water-holding capacity and nutrient supply', 'Increasing salinity', 'Compacting the soil', 'Reducing microbial activity'], 0,
    'It also feeds soil organisms.'],
  ['Earthworms are called "ecosystem engineers" because they:', ['Mix and aerate soil and improve its structure', 'Fix nitrogen', 'Photosynthesise', 'Kill all pests'], 0,
    'Darwin wrote about them in 1881.'],
  ['A bulk density above about 1.6 g/cm³ in a mineral soil usually:', ['Restricts root growth', 'Improves aeration', 'Increases infiltration', 'Has no effect'], 0,
    'Compaction forms hardpans under repeated tillage.'],
  ['An ecological principle of sustainable agriculture is that:', ['Crop diversity increases the stability of the system', 'Monoculture is always most stable', 'Soil life is unimportant', 'External inputs should always be maximised'], 0,
    'Rotations and intercropping put this into practice.'],
  ['Including legumes in crop rotations helps sustainability by:', ['Adding nitrogen through biological fixation', 'Removing all nutrients', 'Increasing salinity', 'Attracting more pests'], 0,
    'They also break the cycles of cereal pests and diseases.'],
  ['A hardpan in rice–wheat fields can be broken by:', ['Deep tillage or chiselling', 'More puddling', 'Heavy irrigation', 'Burning residues'], 0,
    'Puddling for rice forms the plough pan in the first place.'],
  ['Sustainable agriculture, in the spirit of the Brundtland report, aims to:', ['Meet present needs without compromising the ability of future generations to meet theirs', 'Maximise short-term profit only', 'Use only chemical inputs', 'Abandon modern science'], 0,
    'It balances economic, social and environmental goals.']
] },
{ p: 'A1', t: 'Weed Science', w: 3, pyq: 'IFoS-2017-A1-Q1c', q: [
  ['The weed that first evolved herbicide resistance in Indian wheat is:', ['*Phalaris minor* (littleseed canarygrass)', '*Avena ludoviciana*', '*Chenopodium album*', '*Cyperus rotundus*'], 0,
    'Its resistance to isoproturon was confirmed in the early 1990s.'],
  ['Isoproturon resistance in *Phalaris minor* is mainly due to:', ['Enhanced herbicide metabolism by cytochrome P450 enzymes (non-target-site resistance)', 'A mutated target site in ALS', 'A thicker cuticle', 'Seed dormancy'], 0,
    'Non-target-site resistance can extend to herbicides with other modes of action.'],
  ['Isoproturon kills weeds by:', ['Inhibiting photosystem II', 'Inhibiting ACCase', 'Inhibiting ALS', 'Mimicking auxin'], 0,
    'It is a substituted urea herbicide.'],
  ['Clodinafop-propargyl and fenoxaprop, introduced against resistant *Phalaris*, act by:', ['Inhibiting acetyl-CoA carboxylase (ACCase)', 'Inhibiting photosystem II', 'Inhibiting EPSPS', 'Mimicking auxin'], 0,
    'They belong to the aryloxyphenoxypropionate ("fop") group.'],
  ['Sulfosulfuron and metsulfuron-methyl act by inhibiting:', ['Acetolactate synthase (ALS)', 'Photosystem II', 'ACCase', 'Microtubules'], 0,
    'ALS makes branched-chain amino acids.'],
  ['*Phalaris minor* populations in Punjab and Haryana have since developed:', ['Multiple resistance to PSII, ACCase and ALS herbicides', 'No further resistance', 'Resistance only to 2,4-D', 'Susceptibility to all herbicides'], 0,
    'This has made herbicide rotation and mixtures essential.'],
  ['A cultural practice that reduces *Phalaris minor* in wheat is:', ['Zero tillage, which reduces its emergence', 'Late sowing in January', 'Very low seed rates', 'Wide row spacing'], 0,
    'Early sowing, higher seed rates and narrow rows also help.'],
  ['The main cause of herbicide resistance evolving is:', ['Repeated use of herbicides with the same mode of action', 'Crop rotation', 'Hand weeding', 'Using clean seed'], 0,
    'High weed seed banks speed up selection.'],
  ['A broadleaf weed of wheat reported to have evolved resistance to metsulfuron-methyl in Punjab is:', ['*Rumex dentatus*', '*Phalaris minor*', '*Avena fatua*', '*Echinochloa colona*'], 0,
    'ALS resistance evolves quickly under repeated use.'],
  ['The best long-term strategy against herbicide resistance in wheat is:', ['Integrated weed management with rotations of herbicides and crops', 'Doubling the herbicide dose', 'Using one herbicide every year', 'Stopping all weed control'], 0,
    'Breaking the rice–wheat rotation also helps.']
] },
{ p: 'A1', t: 'Agro-climatic Zones & Cropping Systems', w: 3, pyq: 'IFoS-2017-A1-Q1d', q: [
  ['Crop diversification means:', ['Shifting from one dominant crop to a wider mix of crops and enterprises', 'Growing only one crop', 'Increasing fertiliser only', 'Using only one variety'], 0,
    'An example is replacing some rice with maize, pulses or horticulture.'],
  ['Horizontal diversification, as opposed to vertical diversification, means:', ['Adding more crops or enterprises', 'Adding value through processing', 'Selling land', 'Reducing crops'], 0,
    'Vertical diversification moves up the value chain.'],
  ['Agricultural intensification means:', ['Raising output per unit of land through higher cropping intensity, inputs and technology', 'Expanding the cropped area into forests', 'Reducing inputs', 'Leaving land fallow'], 0,
    'Sustainable intensification tries to avoid environmental harm.'],
  ['Punjab and Haryana promote diversification away from paddy mainly to:', ['Save groundwater', 'Increase paddy area', 'Increase straw burning', 'Reduce maize area'], 0,
    'Water tables in central Punjab are falling fast.'],
  ['An Integrated Farming System (IFS) combines:', ['Crops, livestock, fish, poultry and trees on one farm', 'Only one crop', 'Only fish', 'Only trees'], 0,
    'The waste of one enterprise is used by another.'],
  ['A major benefit of diversification for small farmers is:', ['Lower risk, more stable income and better nutrition', 'Greater risk', 'Lower income', 'Loss of soil health'], 0,
    'Different enterprises rarely fail together.'],
  ['High-value agriculture includes:', ['Horticulture, dairying, poultry and fisheries', 'Only cereals', 'Only pulses', 'Only fodder'], 0,
    'Rising incomes increase demand for these foods.'],
  ['The Simpson index is used in agriculture to measure:', ['Crop diversification', 'Soil pH', 'Rainfall', 'Yield'], 0,
    'It rises as more crops share the area.'],
  ['The rice–wheat cropping system of the Indo-Gangetic Plains in India covers about:', ['10 million hectares', '1 million hectares', '50 million hectares', '100 million hectares'], 0,
    'It is the main source of India’s food grain stocks.'],
  ['Diversifying crop rotations also helps by:', ['Breaking pest and disease cycles and improving soil health', 'Increasing pest build-up', 'Reducing soil organic matter', 'Increasing herbicide resistance'], 0,
    'Monocultures favour specialised pests.']
] },
{ p: 'A1', t: 'Agroforestry & Social Forestry', w: 3, pyq: 'IFoS-2017-A1-Q1e', q: [
  ['The term "social forestry" was popularised in India by the:', ['National Commission on Agriculture (1976)', 'Forest Act of 1927', 'Green Revolution', 'Planning Commission in 1951'], 0,
    'It aimed to meet rural needs for fuel, fodder and small timber.'],
  ['The components of social forestry are:', ['Farm forestry, community forestry and extension forestry (roadsides, canal banks, railway lines)', 'Only reserved forests', 'Only national parks', 'Only plantations of teak'], 0,
    'Agroforestry is closely related.'],
  ['In a changing climate, agroforestry helps mainly by:', ['Storing carbon in trees and soil (carbon sequestration)', 'Releasing more CO₂', 'Increasing erosion', 'Reducing biodiversity'], 0,
    'It also makes farms more resilient.'],
  ['Windbreaks and shelterbelts help crops by:', ['Reducing wind speed, evaporation and soil erosion', 'Increasing wind speed', 'Increasing evaporation', 'Shading all crops completely'], 0,
    'Their effect extends several times the tree height downwind.'],
  ['Joint Forest Management (JFM) was launched by a Government of India resolution in:', ['1990', '1952', '2006', '1980'], 0,
    'It shares forest management and benefits with village communities.'],
  ['The National Forest Policy (1988) aims to bring under forest or tree cover:', ['One-third (33%) of the country’s area', 'One-tenth', 'Half', 'Two-thirds'], 0,
    'Current forest and tree cover is about a quarter of the area.'],
  ['Trees outside forests (TOF), including agroforestry, are important because they:', ['Supply much of the country’s timber and fuelwood and reduce pressure on forests', 'Do not store carbon', 'Reduce farm incomes', 'Always compete with crops'], 0,
    'The Forest Survey of India assesses them regularly.'],
  ['Under its NDC, India aims to create an additional carbon sink through forest and tree cover of:', ['2.5–3 billion tonnes of CO₂ equivalent by 2030', '100 million tonnes by 2050', '10 billion tonnes by 2025', 'No target'], 0,
    'Agroforestry is key to meeting it (NDC target — check updates).'],
  ['In the arid west, shelterbelts have often been planted with:', ['*Prosopis juliflora*, *Acacia tortilis* and neem', 'Rubber', 'Tea', 'Coconut'], 0,
    'Drought-hardy species survive there.'],
  ['Social forestry reduces pressure on natural forests by:', ['Supplying fuelwood, fodder and small timber near villages', 'Banning all tree cutting', 'Importing wood', 'Reducing village populations'], 0,
    'Rural people depend heavily on fuelwood.']
] },
{ p: 'A1', t: 'Crop Production', w: 3, pyq: 'IFoS-2017-A1-Q2a', q: [
  ['In north India, chickpea is best sown in:', ['Mid-October to early November', 'June–July', 'January', 'March–April'], 0,
    'Rainfed crops are sown earlier, in the first half of October.'],
  ['The usual spacing for chickpea is about:', ['30 cm between rows and 10 cm between plants', '10 cm × 5 cm', '90 cm × 60 cm', '60 cm × 60 cm'], 0,
    'Rows may be widened to 45 cm in fertile soils.'],
  ['The seed rate of desi chickpea is about:', ['75–80 kg/ha', '10 kg/ha', '200 kg/ha', '5 kg/ha'], 0,
    'Bold-seeded kabuli types need about 100–120 kg/ha.'],
  ['Chickpea seed is usually treated before sowing with:', ['*Rhizobium* and phosphate-solubilising bacteria, plus a fungicide or *Trichoderma* against wilt', 'Urea only', 'Gypsum', 'Nothing'], 0,
    'The fungicide is applied first, then the bioinoculants.'],
  ['The fertiliser dose for chickpea is typically about:', ['20 kg N + 40–60 kg P₂O₅ per hectare, often with sulphur', '120 kg N + 60 kg P₂O₅', 'No nutrients at all', '200 kg N only'], 0,
    'Only a starter dose of N is needed.'],
  ['"Nipping" in chickpea, done at about 30–40 days, means:', ['Pinching off the shoot tips to encourage branching', 'Removing flowers', 'Removing pods', 'Cutting roots'], 0,
    'More branches mean more pods.'],
  ['If irrigation is available for chickpea, one light irrigation is most useful at:', ['Pre-flowering or pod development', 'Sowing only', 'Harvest', 'After harvest'], 0,
    'Heavy irrigation causes excessive vegetative growth.'],
  ['A pre-emergence herbicide commonly used in chickpea is:', ['Pendimethalin', '2,4-D', 'Glyphosate after emergence', 'Atrazine'], 0,
    'Weeds must be kept down in the first 30–60 days.'],
  ['The major soil-borne disease of chickpea is wilt, caused by:', ['*Fusarium oxysporum* f. sp. *ciceris*', '*Ascochyta rabiei*', '*Puccinia*', '*Xanthomonas*'], 0,
    '*Ascochyta rabiei* causes blight.'],
  ['India’s average chickpea yield is about:', ['1 tonne per hectare', '5 tonnes per hectare', '0.1 tonne per hectare', '10 tonnes per hectare'], 0,
    'Good management can give 2–2.5 t/ha (average varies by year).']
] },
{ p: 'A1', t: 'Crop Production', w: 3, pyq: 'IFoS-2017-A1-Q2b', q: [
  ['Timely sowing of wheat in the north-western plains is done in:', ['The first half of November', 'June', 'February', 'August'], 0,
    'Late sowing extends into December.'],
  ['The recommended row spacing for timely sown wheat is about:', ['20–22.5 cm', '60 cm', '90 cm', '5 cm'], 0,
    'Late-sown wheat is planted closer, at about 18 cm.'],
  ['The seed rate for timely sown irrigated wheat is about:', ['100 kg/ha', '20 kg/ha', '300 kg/ha', '10 kg/ha'], 0,
    'Late sowing needs about 125 kg/ha.'],
  ['Semi-dwarf wheat should be sown at about 5 cm depth because:', ['Its *Rht* genes give a short coleoptile', 'Its seeds are large', 'It needs darkness', 'It germinates slowly'], 0,
    'Deep sowing gives poor emergence.'],
  ['The fertiliser dose for timely sown irrigated wheat in the north-west is about:', ['120–150 kg N, 60 kg P₂O₅ and 40 kg K₂O per hectare', '20 kg N only', 'No fertiliser', '300 kg N only'], 0,
    'Half of the N is applied at sowing and the rest with early irrigations.'],
  ['The irrigation stages of wheat, in order, are:', ['Crown root initiation, tillering, jointing, flowering, milk and dough', 'Only at sowing', 'Only at harvest', 'Only at flowering'], 0,
    'When water is short, crown root initiation gets top priority.'],
  ['Broadleaf weeds in wheat are commonly controlled with:', ['Metsulfuron-methyl or 2,4-D at about 30–35 days after sowing', 'Atrazine', 'Butachlor', 'Pendimethalin after emergence only'], 0,
    'Grass weeds need separate herbicides.'],
  ['In the rice–wheat system, a common micronutrient deficiency in wheat is that of:', ['Zinc, corrected with zinc sulphate', 'Molybdenum', 'Chlorine', 'Nickel'], 0,
    'About 25 kg ZnSO₄ per hectare is a common dose.'],
  ['To avoid terminal heat stress in wheat, farmers should:', ['Sow on time, e.g., using zero-till or Happy Seeder right after rice', 'Sow in January', 'Stop irrigation', 'Use only tall varieties'], 0,
    'Delayed sowing pushes grain filling into hot weather.'],
  ['India’s average wheat yield is roughly:', ['3.5 tonnes per hectare, with Punjab near 5 t/ha', '1 tonne per hectare', '10 tonnes per hectare', '0.5 tonne per hectare'], 0,
    'Figures change year to year — check the latest estimates.']
] },
{ p: 'A1', t: 'Crop Production', w: 2, pyq: 'IFoS-2017-A1-Q2c', q: [
  ['Lucerne (*Medicago sativa*) is known as the:', ['"Queen of fodders"', '"King of cereals"', '"Golden fibre"', '"Poor man’s meat"'], 0,
    'It is a perennial, protein-rich legume fodder.'],
  ['In north India, lucerne is usually sown in:', ['October–November', 'May–June', 'January–February', 'August'], 0,
    'It then gives cuts for several years.'],
  ['The seed rate of lucerne is about:', ['12–20 kg/ha', '100 kg/ha', '1 kg/ha', '200 kg/ha'], 0,
    'Seed is sown in rows about 25–30 cm apart or broadcast.'],
  ['Lucerne seed should be inoculated with:', ['*Sinorhizobium* (*Ensifer*) *meliloti*', '*Rhizobium leguminosarum*', '*Bradyrhizobium japonicum*', '*Azotobacter*'], 0,
    'Lucerne needs its own specific rhizobia.'],
  ['The fertiliser requirement of lucerne is:', ['A small starter dose of N with generous phosphorus (and potassium)', 'Very high nitrogen', 'No phosphorus', 'Only micronutrients'], 0,
    'It is very sensitive to soil acidity, so lime is applied on acid soils.'],
  ['The first cut of lucerne is usually taken about:', ['50–60 days after sowing, with later cuts every 25–30 days', '10 days after sowing', '200 days after sowing', 'Only once a year'], 0,
    'It can give eight to twelve cuts a year.'],
  ['The annual green fodder yield of lucerne can reach about:', ['60–100 tonnes per hectare', '5 tonnes per hectare', '500 tonnes per hectare', '1 tonne per hectare'], 0,
    'Yields depend on irrigation and the number of cuts.'],
  ['The most troublesome parasitic weed of lucerne is:', ['Dodder (*Cuscuta*)', '*Striga*', '*Orobanche* only', '*Phalaris minor*'], 0,
    'Clean, dodder-free seed is essential.'],
  ['The crude protein content of lucerne fodder is about:', ['18–22%', '2–3%', '50%', '80%'], 0,
    'It is excellent for dairy animals.'],
  ['Feeding large amounts of fresh, lush lucerne to cattle can cause:', ['Bloat', 'Rickets', 'Milk fever only', 'Blindness'], 0,
    'Mixing it with dry fodder reduces the risk.']
] },
{ p: 'A1', t: 'Crop Production', w: 2, pyq: 'IFoS-2017-A1-Q2d', q: [
  ['Sunflower can be grown in kharif, rabi and spring because it is:', ['Photo-insensitive', 'A strict short-day plant', 'A strict long-day plant', 'Frost-tolerant only'], 0,
    'This gives farmers great flexibility.'],
  ['The spacing for hybrid sunflower is about:', ['60 cm × 30 cm', '10 cm × 10 cm', '150 cm × 150 cm', '20 cm × 5 cm'], 0,
    'Varieties may be planted at 45 cm × 20 cm.'],
  ['The seed rate of hybrid sunflower is about:', ['5–6 kg/ha', '50 kg/ha', '100 kg/ha', '1 kg/ha'], 0,
    'Varieties need about 8–10 kg/ha.'],
  ['Sunflower is:', ['Cross-pollinated, mainly by honeybees, because it is protandrous', 'Strictly self-pollinated', 'Wind-pollinated only', 'Apomictic'], 0,
    'Keeping about five beehives per hectare improves seed set.'],
  ['To improve seed set in sunflower, borax is sprayed at the:', ['Ray floret (early flowering) stage', 'Seedling stage', 'Harvest', 'After harvest'], 0,
    'Boron deficiency causes poorly filled heads.'],
  ['Besides N, P and K, sunflower responds well to:', ['Sulphur', 'Sodium', 'Chlorine', 'Nickel'], 0,
    'Sulphur raises oil content.'],
  ['The critical stages for irrigating sunflower are:', ['Bud initiation (star stage), flowering and seed filling', 'Sowing only', 'Harvest only', 'Pre-sowing only'], 0,
    'Stress at flowering causes empty seeds.'],
  ['The oil content of sunflower seed is about:', ['35–45%, rich in linoleic acid', '5%', '80%', '15%'], 0,
    'High-oleic varieties are also available.'],
  ['India’s first sunflower hybrid, released in 1980, was:', ['BSH-1', 'KBSH-1', 'Morden', 'MSFH-8'], 0,
    'Karnataka is India’s largest sunflower producer.'],
  ['Sunflower is native to:', ['North America', 'India', 'Africa', 'Australia'], 0,
    'It reached India through Russia, where it was bred for oil.']
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: 'IFoS-2017-A1-Q3a', q: [
  ['The criteria of essentiality for plant nutrients were set out by:', ['Arnon and Stout (1939)', 'Liebig', 'Mitscherlich', 'Sprengel'], 0,
    'The element must be needed to complete the life cycle, not replaceable, and directly involved.'],
  ['The number of elements now accepted as essential for higher plants is:', ['Seventeen', 'Ten', 'Twenty-five', 'Six'], 0,
    'They are C, H, O, N, P, K, Ca, Mg, S, Fe, Mn, Zn, Cu, B, Mo, Cl and Ni.'],
  ['Macronutrients are those required in plant tissue at more than about:', ['1,000 mg/kg (0.1%) of dry matter', '1 mg/kg', '10 mg/kg', '100% of dry matter'], 0,
    'Micronutrients are usually below 100 mg/kg.'],
  ['Elements that are beneficial but not essential for all plants include:', ['Sodium, silicon, cobalt and selenium', 'Nitrogen and phosphorus', 'Iron and zinc', 'Boron and molybdenum'], 0,
    'Silicon benefits rice and sugarcane.'],
  ['Deficiency symptoms first appear on older leaves for:', ['Mobile nutrients such as N, P, K and Mg', 'Immobile nutrients such as Ca and B', 'All nutrients equally', 'No nutrients'], 0,
    'Immobile nutrients show deficiency on young leaves first.'],
  ['Kraus and Kraybill (1918), working on tomato, showed that:', ['A high C:N ratio in the plant favours flowering and fruiting, and a low one favours vegetative growth', 'C:N ratio has no effect on growth', 'Only N matters', 'Only carbon matters'], 0,
    'This explains why excess N delays flowering.'],
  ['The C:N ratio of stable soil humus is about:', ['10–12:1', '80:1', '200:1', '1:1'], 0,
    'Soil microbes themselves have a C:N ratio of about 8:1.'],
  ['Legume residues decompose quickly and release nitrogen because they have:', ['A narrow C:N ratio (about 20:1 or less)', 'A wide C:N ratio', 'No nitrogen', 'Much lignin'], 0,
    'Cereal straw, with a wide ratio, immobilises N.'],
  ['A mature, good-quality compost usually has a C:N ratio of about:', ['15–20:1', '100:1', '1:1', '60:1'], 0,
    'Immature compost with a wide ratio can starve crops of N.'],
  ['The C:N ratio matters for crop productivity because it:', ['Governs whether nitrogen is released or locked up when residues decompose', 'Sets soil pH', 'Sets rainfall', 'Controls pests only'], 0,
    'Timing residue incorporation around it avoids N deficiency.']
] },
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 3, pyq: 'IFoS-2017-A1-Q3b', q: [
  ['A saline soil has:', ['ECe above 4 dS/m, ESP below 15 and pH below 8.5', 'ESP above 15 and pH above 8.5', 'pH below 5', 'No soluble salts'], 0,
    'White salt crusts often form on the surface.'],
  ['A sodic (alkali) soil has:', ['ESP above 15 and pH above 8.5, with ECe below 4 dS/m', 'ECe above 4 and ESP below 15', 'pH below 6', 'High organic matter'], 0,
    'Dispersed clay makes it hard and poorly permeable.'],
  ['Saline soils are reclaimed mainly by:', ['Leaching with good-quality water, with adequate drainage', 'Adding gypsum only', 'Adding salt', 'Deep flooding without drainage'], 0,
    'Without drainage, salts return.'],
  ['Sodic soils are reclaimed mainly by applying:', ['Gypsum, according to the soil’s gypsum requirement', 'Lime', 'Common salt', 'Urea'], 0,
    'Calcium replaces sodium on the exchange sites; pressmud and pyrite are alternatives.'],
  ['The preferred first crop on newly reclaimed sodic soil is:', ['Rice, which tolerates sodicity and ponded water', 'Chickpea', 'Groundnut', 'Pigeonpea'], 0,
    'A rice–wheat sequence is then usually followed.'],
  ['Salt-tolerant rice varieties developed by CSSRI, Karnal include:', ['CSR 30 and CSR 36', 'IR 8 and Jaya', 'Pusa Basmati 1 only', 'Swarna only'], 0,
    'CSSRI is the Central Soil Salinity Research Institute.'],
  ['In sodic soils, rice seedlings are transplanted:', ['Older (about 35–40 days), with 3–4 seedlings per hill at closer spacing', 'Very young and singly', 'Only by direct seeding', 'Without any preparation'], 0,
    'Older seedlings withstand stress better.'],
  ['Nutrient management in sodic soils usually includes:', ['About 25% extra nitrogen and zinc sulphate', 'No nitrogen', 'Extra sodium', 'Only potassium'], 0,
    'High pH increases ammonia loss and zinc deficiency.'],
  ['A green manure crop suited to reclaiming sodic soils is:', ['Dhaincha (*Sesbania aculeata*)', 'Sunflower', 'Groundnut', 'Wheat'], 0,
    'It tolerates sodicity and adds organic matter.'],
  ['In furrow-irrigated saline soils, seeds are sown:', ['On the sides of the ridges, below the salty tops', 'On the tops of the ridges', 'In standing water', 'Anywhere'], 0,
    'Salts accumulate where water evaporates, on the ridge tops.']
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: 'IFoS-2017-A1-Q3c', q: [
  ['In acid soils (below about pH 5.5), phosphorus is fixed mainly by:', ['Iron and aluminium, as insoluble Fe and Al phosphates', 'Calcium', 'Sodium', 'Nitrogen'], 0,
    'Strengite and variscite are such minerals.'],
  ['In alkaline and calcareous soils, phosphorus is fixed mainly as:', ['Calcium phosphates, which change towards apatite over time', 'Iron phosphates', 'Aluminium phosphates', 'Sodium phosphates'], 0,
    'Dicalcium phosphate converts slowly into less soluble forms.'],
  ['Phosphorus is most available at a soil pH of about:', ['6–7', '4', '9', '11'], 0,
    'Fixation by Fe, Al and Ca is lowest there.'],
  ['Liming an acid soil improves phosphorus availability by:', ['Raising pH and reducing Fe and Al activity', 'Adding phosphorus', 'Lowering pH', 'Adding sodium'], 0,
    'Over-liming can cause Ca-phosphate fixation.'],
  ['Rock phosphate is most effective as a direct fertiliser in:', ['Acid soils (pH below about 5.5)', 'Calcareous soils', 'Saline soils', 'Neutral soils only'], 0,
    'Soil acidity helps dissolve it.'],
  ['Phosphate is also adsorbed on:', ['Clay minerals and iron and aluminium oxides, by ligand exchange', 'Sand grains only', 'Organic nitrogen', 'Air'], 0,
    'Kaolinitic, oxide-rich soils fix large amounts.'],
  ['Crops usually recover only about what share of applied phosphorus in the first season?', ['15–20%', '80–90%', '50–60%', '100%'], 0,
    'Much of the rest stays in the soil as residual P.'],
  ['Band placement of phosphorus near the seed:', ['Reduces fixation compared with broadcasting', 'Increases fixation', 'Has no effect', 'Causes leaching'], 0,
    'Less contact with soil means less fixation.'],
  ['Available phosphorus in neutral and alkaline soils is estimated by:', ['Olsen’s method (0.5 M NaHCO₃, pH 8.5)', 'Bray’s P1 method only', 'Kjeldahl digestion', 'Walkley–Black method'], 0,
    'Bray’s P1 method is used for acid soils.'],
  ['Biological ways to release fixed phosphorus include:', ['Phosphate-solubilising microbes and mycorrhizal fungi', 'Adding salt', 'Burning residues', 'Deep flooding'], 0,
    'Organic acids from microbes dissolve bound phosphate.']
] },
{ p: 'A1', t: 'Weed Science', w: 2, pyq: 'IFoS-2017-A1-Q3d', q: [
  ['Soil solarisation means:', ['Covering moist soil with transparent polythene in hot weather to heat it', 'Burning the soil surface', 'Adding black mulch in winter', 'Drying soil in shade'], 0,
    'The heat kills weed seeds, pathogens and pests.'],
  ['Soil solarisation was developed by:', ['Katan and colleagues in Israel (1976)', 'Borlaug in Mexico', 'Swaminathan in India', 'Liebig in Germany'], 0,
    'It is non-chemical and cheap to apply.'],
  ['Transparent rather than black polythene is used because it:', ['Lets sunlight through and traps the heat in the soil', 'Blocks all light', 'Cools the soil', 'Is cheaper'], 0,
    'Black film heats itself more than the soil below.'],
  ['During solarisation, the top 5–10 cm of soil typically reaches:', ['About 45–55 °C', 'About 20 °C', 'About 100 °C', 'Below freezing'], 0,
    'Several weeks at these temperatures kill many organisms.'],
  ['The soil must be moist during solarisation because moisture:', ['Conducts heat better and makes seeds and pathogens more heat-sensitive', 'Cools the soil', 'Stops heating', 'Is not needed'], 0,
    'The field is irrigated before the film is laid.'],
  ['Solarisation usually lasts:', ['About 4–6 weeks during the hottest months', 'One day', 'One year', 'A few hours'], 0,
    'In north India, April to June is best.'],
  ['Soil solarisation controls:', ['Annual weeds, soil-borne pathogens such as *Fusarium* and *Rhizoctonia*, and nematodes', 'Only insects on leaves', 'Only viruses in the air', 'Nothing'], 0,
    'It is valuable in nurseries and vegetable beds.'],
  ['Solarisation is less effective against:', ['Deep-rooted perennials such as *Cyperus rotundus* and hard-seeded weeds', 'Annual grasses', 'Small-seeded broadleaves', 'Damping-off fungi'], 0,
    'Their propagules survive below the heated layer.'],
  ['Solarisation often increases crop growth because it also:', ['Releases available nutrients such as ammonium and nitrate', 'Adds pesticides', 'Reduces nutrients', 'Increases salinity'], 0,
    'This is called the "increased growth response".'],
  ['A limitation of soil solarisation is:', ['The cost of plastic film, the land being out of use and the disposal of plastic', 'It poisons the soil', 'It needs cold weather', 'It is illegal'], 0,
    'It works best in hot, sunny regions.']
] },
{ p: 'A1', t: 'Dryland Farming & Watershed Management', w: 3, pyq: 'IFoS-2017-A1-Q4a', q: [
  ['The All India Coordinated Research Project on Dryland Agriculture (AICRPDA) began in:', ['1970', '1990', '2005', '1947'], 0,
    'It led to CRIDA being set up in 1985.'],
  ['A "dust mulch" in dryland farming is made by:', ['Shallow cultivation of the soil surface to break capillaries and reduce evaporation', 'Spreading plastic sheets', 'Adding sand', 'Flooding the field'], 0,
    'It is an old dry-farming technique.'],
  ['Choosing crops by the length of growing period means that where LGP is under 90 days, farmers should grow:', ['Very short-duration crops such as pearl millet, cowpea or clusterbean', 'Sugarcane', 'Long-duration cotton', 'Two crops of rice'], 0,
    'Longer LGPs allow intercropping or double cropping.'],
  ['Tied ridges help dryland crops by:', ['Holding rainwater in small basins between ridges', 'Draining water away quickly', 'Increasing runoff', 'Preventing germination'], 0,
    'They increase in-situ moisture conservation.'],
  ['In dry areas, plant population should generally be:', ['Somewhat lower than under irrigation, to match limited moisture', 'Much higher than under irrigation', 'The same as under irrigation', 'Zero'], 0,
    'Too many plants exhaust stored moisture early.'],
  ['Kaolin (about 6%) sprayed on dryland crops acts as:', ['A reflectant antitranspirant', 'A fertiliser', 'A herbicide', 'A fungicide'], 0,
    'It reflects sunlight and cools the leaves.'],
  ['Alternate land-use systems for drylands include:', ['Agri-horticulture (e.g., ber, aonla) and silvipasture (e.g., with *Cenchrus* grass)', 'Rice–wheat monoculture', 'Sugarcane plantations', 'Tea gardens'], 0,
    'They suit land too poor for arable crops.'],
  ['In deep Vertisols with assured rain, a traditional dryland system is:', ['Keeping land fallow in kharif and growing a rabi crop on the stored moisture', 'Rice in kharif and rice in rabi', 'Sugarcane throughout', 'Tea'], 0,
    'Rabi sorghum and chickpea are typical crops.'],
  ['Drought-hardy crops suited to drylands include:', ['Pearl millet, sorghum, horsegram and castor', 'Rice and sugarcane', 'Banana and coconut', 'Tea and coffee'], 0,
    'They combine short duration with deep roots or tolerance.'],
  ['Dryland technologies are best applied through:', ['An integrated watershed approach', 'Isolated single fields only', 'Irrigation projects only', 'Urban planning'], 0,
    'The watershed is the natural unit of runoff management.']
] },
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 3, pyq: 'IFoS-2017-A1-Q4b', q: [
  ['Land degradation, as defined by the UNCCD, is:', ['A reduction in the land’s ability to provide ecosystem goods and services', 'Any change in land ownership', 'Urban growth only', 'An increase in crop yields'], 0,
    'It includes both soil and vegetation decline.'],
  ['The most widespread process of land degradation in India is:', ['Water erosion', 'Wind erosion', 'Salinisation', 'Mining'], 0,
    'Vegetation degradation and wind erosion follow.'],
  ['According to ISRO’s Desertification and Land Degradation Atlas (2021), the share of India’s area undergoing degradation is about:', ['30%', '5%', '60%', '90%'], 0,
    'It covers about 98 million hectares (2018–19 data — check updates).'],
  ['Wind erosion is the dominant degradation process in:', ['Western Rajasthan and Gujarat', 'Kerala', 'Assam', 'Sikkim'], 0,
    'Loose sandy soils and strong winds combine there.'],
  ['Secondary salinisation in canal command areas is caused by:', ['Rising water tables from seepage and over-irrigation', 'Heavy rainfall', 'Forest cover', 'Terracing'], 0,
    'The Indira Gandhi canal area is an example.'],
  ['Human causes of land degradation include:', ['Deforestation, overgrazing, faulty irrigation and mining', 'Afforestation', 'Contour bunding', 'Mulching'], 0,
    'Short-cycle shifting cultivation adds to it in the north-east.'],
  ['Nutrient depletion and loss of soil organic carbon are forms of:', ['Chemical and biological degradation', 'Physical expansion', 'Improvement', 'Wind deposition'], 0,
    'They reduce productivity even without visible erosion.'],
  ['India has committed to restoring degraded land by 2030 amounting to:', ['26 million hectares', '1 million hectares', '100 million hectares', '5 million hectares'], 0,
    'This is under the Bonn Challenge and land degradation neutrality (check updates).'],
  ['India hosted the 14th Conference of Parties (COP14) of the UNCCD in:', ['2019, in New Delhi', '2015, in Paris', '2010, in Mumbai', '2023, in Dubai'], 0,
    'It adopted the Delhi Declaration.'],
  ['Land degradation neutrality means:', ['Degradation is balanced by restoration so there is no net loss of healthy land', 'Stopping all farming', 'Converting all land to forest', 'Letting land degrade naturally'], 0,
    'It is Target 15.3 of the Sustainable Development Goals.']
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: 'IFoS-2017-A1-Q4c', q: [
  ['Integrated Nutrient Management (INM) combines:', ['Fertilisers, organic manures, biofertilisers, crop residues and green manures', 'Only chemical fertilisers', 'Only organic manures', 'Only irrigation'], 0,
    'It aims at balanced, sustained soil fertility.'],
  ['INM is needed today mainly because of:', ['Falling fertiliser response, multi-nutrient deficiencies and declining soil organic carbon', 'Excess soil organic matter', 'Too little use of nitrogen', 'Rising soil fertility everywhere'], 0,
    'Deficiencies of S, Zn and B have spread.'],
  ['Long-term fertiliser experiments in India show that yields are best sustained by:', ['NPK combined with farmyard manure', 'Nitrogen alone', 'No fertiliser', 'Phosphorus alone'], 0,
    'Nitrogen alone leads to declining yields.'],
  ['*Azolla*, used as a biofertiliser in rice, fixes nitrogen through its symbiont:', ['*Anabaena azollae*', '*Rhizobium*', '*Frankia*', '*Azotobacter*'], 0,
    'It can supply about 20–40 kg N per hectare.'],
  ['Blue-green algae (BGA) are used as a biofertiliser mainly in:', ['Rice fields', 'Wheat fields', 'Orchards', 'Deserts'], 0,
    'They fix nitrogen in flooded conditions.'],
  ['The Soil Health Card scheme was launched in:', ['2015', '2005', '1995', '2022'], 0,
    'Cards give field-specific fertiliser advice.'],
  ['The soil test crop response (STCR) approach recommends fertiliser doses for:', ['A targeted yield, based on soil test values', 'Maximum possible doses', 'Equal doses for all fields', 'No fertiliser'], 0,
    'It was developed by Ramamoorthy and colleagues.'],
  ['The Nutrient Based Subsidy (NBS) scheme for P and K fertilisers began in:', ['2010', '1991', '2000', '2020'], 0,
    'Urea remains outside NBS, under fixed prices.'],
  ['Green manuring with dhaincha (*Sesbania*) before rice:', ['Adds organic matter and a substantial amount of nitrogen', 'Adds salts', 'Lowers soil fertility', 'Increases erosion'], 0,
    'It is ploughed in at about 45–60 days.'],
  ['A key benefit of INM is that it:', ['Improves nutrient use efficiency and soil health while sustaining yields', 'Always reduces yield', 'Needs no planning', 'Increases pollution'], 0,
    'It also cuts fertiliser costs.']
] },
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 3, pyq: 'IFoS-2017-A1-Q4d', q: [
  ['Agronomic measures of soil and water conservation, as opposed to mechanical ones, use:', ['Crops, vegetation and farming practices', 'Earthworks such as terraces and check dams', 'Concrete structures', 'Machines only'], 0,
    'They are cheaper and are often combined with mechanical measures.'],
  ['Contour farming means:', ['Ploughing and sowing across the slope, along the contour', 'Ploughing up and down the slope', 'Leaving land bare', 'Burning stubble'], 0,
    'Furrows across the slope slow runoff.'],
  ['In strip cropping:', ['Erosion-permitting crops alternate with erosion-resisting crops in strips', 'One crop covers the whole field', 'Crops are grown only on bunds', 'Only trees are grown'], 0,
    'Types include contour, field, buffer and wind strip cropping.'],
  ['An example of an erosion-permitting crop is:', ['Widely spaced maize or sorghum', 'Groundnut', 'Cowpea', 'Grasses'], 0,
    'Close-growing crops such as groundnut and cowpea resist erosion.'],
  ['Cover crops such as cowpea and horsegram reduce erosion by:', ['Covering the soil and breaking the impact of raindrops', 'Increasing runoff', 'Loosening the soil', 'Removing organic matter'], 0,
    'They also add organic matter.'],
  ['Conservation tillage leaves at least what share of the soil surface covered with residue after planting?', ['30%', '5%', '100%', '0%'], 0,
    'Zero tillage is the extreme form.'],
  ['Crop residue mulch reduces erosion by:', ['Reducing raindrop splash and runoff and increasing infiltration', 'Increasing runoff', 'Compacting the soil', 'Adding salts'], 0,
    'It also conserves moisture.'],
  ['To control wind erosion, strip crops are laid out:', ['At right angles to the prevailing wind', 'Parallel to the wind', 'Randomly', 'In circles'], 0,
    'Windbreaks and stubble mulching help too.'],
  ['Vegetative barriers such as vetiver hedges on the contour:', ['Slow runoff and trap sediment, gradually forming terraces', 'Increase erosion', 'Block all rainfall', 'Replace crops'], 0,
    'They are cheaper than earthen bunds.'],
  ['Traditional farmer practices for soil conservation include:', ['Stone bunds, trash lines and live hedges', 'Up-and-down ploughing', 'Burning slopes', 'Clearing all trees'], 0,
    'Such practices are recorded as indigenous technical knowledge.']
] }
);
