/* PYQ-linked MCQs — IFoS 2025 Botany Paper II (topic-level PYQs from the volume anchors). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B2', t: 'Cell Biology', w: 2, pyq: 'IFoS-2025-B2-Q1a', q: [
  ['Cadherins are cell-adhesion proteins whose binding depends on:', ['Calcium ions', 'Magnesium ions', 'ATP', 'Sodium ions'], 0,
    'Loss of E-cadherin helps cancer cells detach and spread.'],
  ['Integrins link the cell’s cytoskeleton to:', ['Extracellular matrix proteins such as fibronectin', 'Other cells via gap junctions only', 'DNA', 'Ribosomes'], 0,
    'They are transmembrane receptors that also transmit signals.'],
  ['Desmosomes anchor to which cytoskeletal element inside the cell?', ['Intermediate filaments', 'Microtubules', 'Actin only', 'Centrioles'], 0,
    'Adherens junctions link to actin filaments.'],
  ['In plants, adjacent cells are held together mainly by the:', ['Pectin-rich middle lamella', 'Cadherins', 'Desmosomes', 'Tight junctions'], 0,
    'Calcium cross-links pectins (the "egg-box" model).'],
  ['Calcium strengthens adhesion between plant cells by:', ['Cross-linking demethylated pectin chains', 'Dissolving cellulose', 'Forming tight junctions', 'Activating cadherins'], 0,
    'Pectin methylesterase removes methyl groups, allowing Ca²⁺ bridges.'],
  ['Gap junctions in animals are functionally similar to which structures in plants?', ['Plasmodesmata', 'Stomata', 'Lenticels', 'Pits in xylem'], 0,
    'Both allow direct cytoplasmic communication between neighbouring cells.'],
  ['Gap junction channels are built from proteins called:', ['Connexins', 'Claudins', 'Integrins', 'Selectins'], 0,
    'Claudins and occludins form tight junctions.'],
  ['Tight junctions mainly:', ['Seal neighbouring cells so fluids cannot leak between them', 'Allow ions to pass freely between cells', 'Anchor intermediate filaments', 'Attach cells to the basal lamina'], 0,
    'Found in epithelia such as the gut lining.'],
  ['Hemidesmosomes attach epithelial cells to the:', ['Basal lamina, through integrins', 'Neighbouring cells, through cadherins', 'Cell wall', 'Nucleus'], 0,
    'They are "half desmosomes" facing the extracellular matrix.'],
  ['Cell separation in the abscission zone of leaves and fruits involves:', ['Enzymatic breakdown of the middle lamella by polygalacturonase and cellulase', 'Formation of tight junctions', 'Increased calcium pectate', 'Lignification of cell walls'], 0,
    'Ethylene promotes and auxin delays these enzymes.'],
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 3, pyq: 'IFoS-2025-B2-Q1b', q: [
  ['Complex IV (cytochrome c oxidase) transfers electrons to:', ['Oxygen, forming water', 'NAD⁺', 'Ubiquinone', 'FAD'], 0,
    'It is the terminal oxidase of the respiratory chain.'],
  ['Which respiratory complex does NOT pump protons?', ['Complex II (succinate dehydrogenase)', 'Complex I', 'Complex III', 'Complex IV'], 0,
    'Hence FADH₂ from succinate gives less ATP than NADH.'],
  ['The mobile carrier that shuttles electrons from complexes I and II to complex III is:', ['Ubiquinone (coenzyme Q)', 'Cytochrome c', 'Plastocyanin', 'Ferredoxin'], 0,
    'Cytochrome c carries electrons from complex III to complex IV.'],
  ['Oligomycin inhibits ATP synthesis by acting on:', ['The F₀ part of ATP synthase', 'Complex I', 'Complex III', 'Cytochrome c'], 0,
    'Rotenone blocks complex I, antimycin A complex III, and cyanide complex IV.'],
  ['Uncouplers such as 2,4-dinitrophenol:', ['Dissipate the proton gradient, so respiration continues but ATP is not made', 'Increase ATP synthesis', 'Block electron flow completely', 'Inhibit glycolysis only'], 0,
    'The energy is released as heat; thermogenin (UCP1) does this naturally in brown fat.'],
  ['The binding-change mechanism of ATP synthase (rotary catalysis) was proposed by:', ['Paul Boyer', 'Peter Mitchell', 'Hans Krebs', 'Melvin Calvin'], 0,
    'Boyer shared the 1997 Nobel Prize with John Walker, who solved the F₁ structure.'],
  ['With modern P/O values, complete aerobic oxidation of one glucose yields about:', ['30–32 ATP', '2 ATP', '8 ATP', '100 ATP'], 0,
    'Older textbooks give 36–38.'],
  ['The only substrate-level phosphorylation in the Krebs cycle is catalysed by:', ['Succinyl-CoA synthetase', 'Citrate synthase', 'Isocitrate dehydrogenase', 'Fumarase'], 0,
    'It forms GTP or ATP (in plants ATP).'],
  ['Plant mitochondria can oxidise external NAD(P)H using:', ['Rotenone-insensitive (type II) NAD(P)H dehydrogenases on the inner membrane', 'Complex IV directly', 'Chloroplast enzymes', 'Peroxisomes'], 0,
    'These bypass complex I and so conserve less energy.'],
  ['ATP synthesis in mitochondria is driven directly by:', ['The flow of protons back into the matrix through ATP synthase', 'Light energy', 'Electron flow through ATP synthase', 'Glucose binding to ATP synthase'], 0,
    'Chemiosmosis: electron transport builds the proton gradient that ATP synthase uses.'],
] },
{ p: 'B2', t: 'Genetics', w: 3, pyq: 'IFoS-2025-B2-Q1c', q: [
  ['Sex-linked inheritance was first demonstrated by T.H. Morgan (1910) using:', ['White-eye mutation in *Drosophila*', 'Seed colour in pea', 'Coat colour in mice', 'Flower colour in *Mirabilis*'], 0,
    'Reciprocal crosses gave different results, tracing the gene to the X chromosome.'],
  ['"Criss-cross inheritance" of an X-linked recessive trait means it passes from:', ['Father to daughter to grandson', 'Father to son', 'Mother to daughter only', 'Grandfather to grandfather'], 0,
    'Carrier daughters pass it to half their sons.'],
  ['Genes located only on the Y chromosome (holandric genes) are passed:', ['From father to all sons', 'From mother to all daughters', 'From father to daughters', 'Equally to both sexes'], 0,
    'Females never inherit Y-linked traits.'],
  ['In birds, sex-linked genes are carried on the:', ['Z chromosome, with females being ZW', 'X chromosome, with females XX', 'Y chromosome only', 'Autosomes'], 0,
    'Females are the heterogametic sex, so the pattern is reversed compared with mammals.'],
  ['Which plant has well-studied XY sex chromosomes?', ['*Silene latifolia* (*Melandrium album*)', 'Pea', 'Maize', 'Wheat'], 0,
    'Papaya and *Coccinia* also have sex chromosome systems.'],
  ['The inactive X chromosome seen as a condensed body in female mammalian cells is the:', ['Barr body', 'Nucleolus', 'Centromere', 'Polytene band'], 0,
    'Mary Lyon proposed random X inactivation.'],
  ['Haemophilia and red–green colour blindness in humans are:', ['X-linked recessive traits', 'Y-linked traits', 'Autosomal dominant traits', 'Mitochondrial traits'], 0,
    'Far more common in males, who have one X.'],
  ['A woman heterozygous for an X-linked recessive gene is called a:', ['Carrier', 'Hemizygote', 'Holandric', 'Homozygote'], 0,
    'Males are hemizygous for X-linked genes.'],
  ['A cross of a colour-blind man with a normal (non-carrier) woman gives:', ['All sons normal and all daughters carriers', 'All sons colour-blind', 'Half the daughters colour-blind', 'All children colour-blind'], 0,
    'Sons get his Y; daughters get his X with the allele.'],
  ['Sex-linked traits differ from sex-limited traits in that sex-linked genes:', ['Lie on sex chromosomes', 'Are expressed in only one sex', 'Lie on autosomes', 'Are cytoplasmic'], 0,
    'Sex-limited genes are usually autosomal but expressed in one sex.'],
] },
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 2, pyq: 'IFoS-2025-B2-Q1d', q: [
  ['A Type I error in hypothesis testing is:', ['Rejecting a null hypothesis that is actually true', 'Accepting a false null hypothesis', 'Using the wrong test', 'Having too many samples'], 0,
    'Its probability is the significance level α; a Type II error (β) accepts a false null hypothesis.'],
  ['The power of a statistical test is:', ['1 − β, the probability of rejecting a false null hypothesis', 'α', 'The sample size', 'The mean'], 0,
    'Power rises with sample size and effect size.'],
  ['A paired t-test is used when:', ['Observations are paired, e.g., the same plots before and after a treatment', 'Two independent groups are compared', 'More than two means are compared', 'Data are categorical'], 0,
    'It analyses the differences within pairs.'],
  ['For a t-test comparing two independent samples of 10 and 12 observations, the degrees of freedom are:', ['20', '22', '21', '10'], 0,
    'df = n₁ + n₂ − 2 = 10 + 12 − 2.'],
  ['To compare the means of more than two treatments in one test, the usual method is:', ['Analysis of variance (F-test)', 'Paired t-test', 'Chi-square goodness of fit', 'Correlation'], 0,
    'Developed by R.A. Fisher; significant F is followed by a critical-difference test.'],
  ['A chi-square test of independence on a 2 × 3 contingency table has degrees of freedom:', ['2', '6', '5', '1'], 0,
    'df = (rows − 1) × (columns − 1) = 1 × 2.'],
  ['At the 5% level of significance, the null hypothesis is rejected when:', ['The p-value is less than 0.05', 'The p-value is greater than 0.05', 'The sample size is less than 5', 'The mean is 5'], 0,
    'The result is then called statistically significant.'],
  ['A Z-test is appropriate for comparing means when:', ['Samples are large (commonly n > 30) or the population variance is known', 'Samples are very small with unknown variance', 'Data are counts in categories', 'There are more than two groups'], 0,
    'For small samples with unknown variance, use the t-test.'],
  ['In field experiments, the critical difference (CD) is used to:', ['Judge whether two treatment means differ significantly after a significant F-test', 'Estimate plot size', 'Measure soil fertility', 'Replace replication'], 0,
    'CD = t × SE of the difference between means.'],
  ['The null hypothesis in a test of significance usually states that:', ['There is no real difference or effect', 'The treatments differ greatly', 'The sample is biased', 'The experiment has failed'], 0,
    'The test measures how likely the observed data are if the null hypothesis is true.'],
] },
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 2, pyq: 'IFoS-2025-B2-Q1e', q: [
  ['Genetic (nuclear) male-sterile lines controlled by a recessive gene are maintained by crossing:', ['*msms* (sterile) × *Msms* (fertile heterozygote), giving a 1:1 progeny', '*msms* × *msms*', '*msms* × *MsMs* (all progeny fertile)', 'Sterile × any unrelated variety'], 0,
    'The fertile half must be rogued out in hybrid seed plots, which is laborious.'],
  ['Two-line hybrid rice uses:', ['Environment-sensitive genic male sterility (TGMS/PGMS)', 'Cytoplasmic male sterility with a maintainer', 'Chemical emasculation only', 'Self-incompatibility'], 0,
    'The same line is sterile in one environment and fertile (self-multiplying) in another.'],
  ['CMS without fertility restoration can still be used for hybrids in crops where:', ['The economic product is vegetative (e.g., forage, some vegetables), so F₁ seed set is not needed', 'Grain is harvested', 'Fruits need seed', 'Oil is extracted from seed'], 0,
    'In grain crops, restorer (Rf) genes are essential.'],
  ['In cytoplasmic–genetic male sterility (CGMS), fertility of the hybrid is restored by:', ['A nuclear restorer (Rf) gene from the male parent', 'The maintainer line', 'Chemical sprays', 'Changing the cytoplasm'], 0,
    'This is the A-B-R system.'],
  ['Chemical hybridising agents (gametocides) are used to:', ['Induce male sterility temporarily for hybrid seed production', 'Increase pollen production', 'Break dormancy', 'Kill weeds'], 0,
    'Examples tried include ethrel, maleic hydrazide and certain arsenicals.'],
  ['In gametophytic male sterility, pollen fertility depends on:', ['The genotype of the pollen grain itself', 'The genotype of the parent plant', 'The cytoplasm of the egg', 'Soil conditions'], 0,
    'In sporophytic sterility, the parent plant’s genotype decides.'],
  ['Male sterility often results from abnormal development of the:', ['Tapetum', 'Endosperm', 'Ovary wall', 'Stigma'], 0,
    'The tapetum nourishes developing pollen.'],
  ['The first CMS line widely used for pearl millet hybrids was:', ['Tift 23A, developed by Glenn Burton', 'CK60A', 'WA cytoplasm', 'PET1'], 0,
    'CK60A (milo-kafir) is used in sorghum; WA in rice; PET1 in sunflower.'],
  ['The main practical advantage of male sterility in hybrid seed production is that it:', ['Removes the need for hand emasculation', 'Increases self-pollination', 'Lowers yields', 'Makes crops homozygous'], 0,
    'This makes large-scale hybrid seed production economical.'],
  ['The CMS source used for hybrid sunflower worldwide is:', ['PET1 (from *Helianthus petiolaris*)', 'Texas cytoplasm', 'Ogura', 'Tift 23A'], 0,
    'Ogura CMS (from radish) is used in *Brassica*.'],
] },
{ p: 'B2', t: 'Genetics', w: 3, pyq: 'IFoS-2025-B2-Q2a', q: [
  ['Seedless watermelon is produced as a:', ['Triploid, from a tetraploid × diploid cross', 'Haploid', 'Tetraploid', 'Diploid mutant'], 0,
    'Triploids are sterile, so seeds do not develop.'],
  ['*Brassica napus* (2n = 38, AACC) arose from hybridisation of:', ['*B. rapa* (AA) and *B. oleracea* (CC)', '*B. nigra* and *B. rapa*', '*B. juncea* and *B. carinata*', 'Radish and cabbage'], 0,
    'Described in U’s triangle (Nagaharu U, 1935).'],
  ['Down syndrome in humans is caused by:', ['Trisomy of chromosome 21', 'Monosomy X', 'Deletion of chromosome 5p', 'Triploidy'], 0,
    'Monosomy X is Turner syndrome; 5p deletion is cri-du-chat.'],
  ['The Bar-eye phenotype in *Drosophila* results from:', ['Duplication of a chromosome segment (region 16A)', 'Deletion', 'Inversion', 'Translocation'], 0,
    'Unequal crossing over creates further copies (double-bar).'],
  ['Crossing over within a paracentric inversion loop produces at anaphase I:', ['A dicentric bridge and an acentric fragment', 'Normal chromosomes only', 'A ring chromosome only', 'Polyploid cells'], 0,
    'This explains reduced fertility of inversion heterozygotes.'],
  ['A reciprocal translocation heterozygote typically shows at meiosis:', ['A ring or cross-shaped configuration of four chromosomes and semi-sterility', 'Univalents only', 'A single bivalent', 'Polytene chromosomes'], 0,
    'Alternate segregation gives viable gametes; adjacent segregation gives unbalanced ones.'],
  ['A Robertsonian translocation is:', ['Fusion of two acrocentric chromosomes at their centromeres', 'Loss of a telomere', 'Duplication of a gene', 'Inversion of a centromere'], 0,
    'It reduces chromosome number without losing major genes.'],
  ['"Pseudodominance" appears when a recessive allele is expressed because of a:', ['Deletion on the homologous chromosome', 'Duplication', 'Polyploidy', 'Point mutation in the dominant allele always'], 0,
    'The recessive allele becomes effectively hemizygous.'],
  ['A plant with 2n + 1 chromosomes is a:', ['Trisomic', 'Monosomic', 'Triploid', 'Tetrasomic'], 0,
    'Blakeslee studied the 12 primary trisomics of *Datura*.'],
  ['Euploidy differs from aneuploidy in that euploidy involves:', ['Change in whole sets of chromosomes', 'Loss or gain of single chromosomes', 'Structural changes only', 'Point mutations'], 0,
    'Polyploids are euploids; trisomics and monosomics are aneuploids.'],
] },
{ p: 'B2', t: 'Molecular Biology', w: 3, pyq: 'IFoS-2025-B2-Q2b', q: [
  ['A multigene family is a group of genes that:', ['Share sequence similarity because they arose by duplication of an ancestral gene', 'Are all on different organisms', 'Code for unrelated proteins', 'Are never expressed'], 0,
    'Examples: globins, histones, rRNA genes, actins and tubulins.'],
  ['Pseudogenes are:', ['Non-functional copies of genes that have accumulated disabling mutations', 'Highly expressed genes', 'Genes in chloroplasts only', 'Genes for rRNA'], 0,
    'Processed pseudogenes lack introns and arise by reverse transcription.'],
  ['Ribosomal RNA genes in eukaryotes are organised as:', ['Tandem repeats at the nucleolus organiser region (NOR)', 'Single copies', 'Genes inside mitochondria only', 'Random scattered copies'], 0,
    'Many copies meet the huge demand for ribosomes.'],
  ['The small subunit of Rubisco is encoded by:', ['A nuclear multigene family (*rbcS*)', 'A single chloroplast gene', 'Mitochondrial DNA', 'A plasmid'], 0,
    'The large subunit (*rbcL*) is encoded in the chloroplast genome.'],
  ['Members of a multigene family are kept similar in sequence by:', ['Concerted evolution through gene conversion and unequal crossing over', 'Natural selection only', 'Random mutation', 'Horizontal gene transfer only'], 0,
    'This keeps tandem repeats such as rRNA genes nearly identical.'],
  ['After duplication, one gene copy acquiring a new function is called:', ['Neofunctionalisation', 'Pseudogenisation', 'Subfunctionalisation', 'Concerted evolution'], 0,
    'Subfunctionalisation divides the ancestral functions between copies.'],
  ['Plant disease-resistance (R) genes of the NBS-LRR type:', ['Form large multigene families, often in clusters', 'Are always single-copy', 'Are found only in chloroplasts', 'Code for storage proteins'], 0,
    'Clustering favours generation of new resistance specificities.'],
  ['Storage proteins such as maize zeins are encoded by:', ['Multigene families', 'One gene only', 'Mitochondrial genes', 'Viral genes'], 0,
    'Wheat gliadins and glutenins are also multigene families.'],
  ['In humans, the α-globin and β-globin gene clusters lie on:', ['Different chromosomes (16 and 11)', 'The same chromosome', 'The X chromosome', 'Mitochondrial DNA'], 0,
    'They are expressed at different developmental stages (embryonic, fetal, adult).'],
  ['Histone genes occur in many copies mainly because:', ['Large amounts of histone protein are needed during DNA replication in S phase', 'Histones are not needed', 'They are pseudogenes', 'They code for rRNA'], 0,
    'They are often arranged in tandem clusters.'],
] },
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 2, pyq: 'IFoS-2025-B2-Q2c', q: [
  ['After three backcrosses (BC₃) to the recurrent parent, the expected recovery of its genome is:', ['93.75%', '75%', '87.5%', '99.2%'], 0,
    'F₁ 50% → BC₁ 75% → BC₂ 87.5% → BC₃ 93.75% (each backcross halves the donor share).'],
  ['The backcross method was first proposed by:', ['Harlan and Pope (1922)', 'Johannsen (1903)', 'Nilsson-Ehle (1908)', 'Shull (1914)'], 0,
    'They suggested it for transferring genes into barley.'],
  ['When the gene being transferred by backcrossing is recessive:', ['A generation of selfing is needed after backcrosses to identify carriers', 'No selection is needed', 'It cannot be transferred', 'The donor becomes the recurrent parent'], 0,
    'Heterozygous carriers look like the recurrent parent.'],
  ['"Linkage drag" in backcross breeding refers to:', ['Unwanted donor genes transferred along with the target gene', 'Slower plant growth', 'Loss of the target gene', 'A type of mutation'], 0,
    'Recombinant selection with markers reduces it.'],
  ['In the pedigree method, selection begins in the:', ['F₂ generation, with records of each plant’s ancestry kept', 'F₆ generation only', 'Parental generation', 'Backcross generation'], 0,
    'Plants and progeny rows are selected until lines are homozygous (around F₆–F₈).'],
  ['The pedigree method is best suited for:', ['Traits with high heritability that can be scored on single plants', 'Low-heritability yield only', 'Clonal crops', 'Apomictic crops'], 0,
    'For low-heritability traits, selection is delayed until later generations.'],
  ['A disadvantage of the pedigree method is that it:', ['Is labour-intensive and needs detailed record keeping', 'Cannot be used in self-pollinated crops', 'Always fails', 'Needs no field space'], 0,
    'The bulk method is cheaper but less informed.'],
  ['The bulk method differs from the pedigree method in that:', ['Early segregating generations are grown as a bulk without individual selection', 'It keeps full pedigree records', 'It is used only for clonal crops', 'It uses backcrosses'], 0,
    'Natural selection acts on the bulk; single plants are chosen later.'],
  ['In backcross breeding, the parent that contributes the target trait is the:', ['Donor (non-recurrent) parent', 'Recurrent parent', 'Maintainer', 'Restorer'], 0,
    'The recurrent parent is the adapted variety to be improved.'],
  ['Both the pedigree and backcross methods are used mainly in:', ['Self-pollinated crops', 'Clonally propagated crops', 'Apomictic grasses', 'Sterile hybrids'], 0,
    'Backcrossing is also used in cross-pollinated crops, e.g., to improve inbred lines.'],
] },
{ p: 'B2', t: 'Molecular Biology', w: 3, pyq: 'IFoS-2025-B2-Q3a', q: [
  ['The *trp* operon of *E. coli* is:', ['Repressible — tryptophan acts as a co-repressor', 'Inducible by tryptophan', 'Always on', 'Regulated only by cAMP'], 0,
    'It is also regulated by attenuation (Yanofsky).'],
  ['Catabolite repression of the *lac* operon works through:', ['cAMP–CAP (CRP), which is needed for strong transcription when glucose is low', 'The lac repressor only', 'Tryptophan', 'Sigma factor loss'], 0,
    'This is positive control; the repressor gives negative control.'],
  ['In eukaryotes, enhancers are:', ['DNA sequences that increase transcription and can act at a distance and in either orientation', 'RNA molecules', 'Parts of the ribosome', 'Only found in introns'], 0,
    'They bind activator proteins that interact with the promoter complex.'],
  ['Histone acetylation generally:', ['Loosens chromatin and promotes transcription', 'Condenses chromatin and silences genes', 'Degrades DNA', 'Stops replication'], 0,
    'DNA methylation of promoters usually silences genes.'],
  ['RNA interference (RNAi), recognised by the 2006 Nobel Prize to Fire and Mello, silences genes by:', ['Small RNAs guiding degradation or blocking of complementary mRNA', 'Mutating DNA', 'Deleting chromosomes', 'Blocking replication'], 0,
    'siRNAs and miRNAs act through RISC.'],
  ['Alternative splicing allows:', ['One gene to produce several different proteins', 'Genes to move between chromosomes', 'Faster DNA replication', 'Removal of exons only'], 0,
    'Different exon combinations give protein isoforms.'],
  ['Riboswitches regulate gene expression by:', ['An mRNA region changing shape when it binds a small metabolite', 'Protein repressors binding DNA', 'Histone modification', 'DNA methylation'], 0,
    'Common in bacteria; a thiamine pyrophosphate riboswitch occurs in plants.'],
  ['ABA-responsive genes in plants often contain which promoter element?', ['ABRE (ABA-responsive element)', 'TATA box only', 'Shine–Dalgarno sequence', 'Operator'], 0,
    'Heat-shock genes carry heat-shock elements (HSE).'],
  ['Genomic imprinting, seen in plant endosperm, means that:', ['A gene’s expression depends on whether it came from the mother or the father', 'All genes are silenced', 'Genes are expressed equally from both parents', 'Genes are deleted'], 0,
    'Imprinting is linked to DNA methylation differences.'],
  ['In positive control of an operon:', ['A regulatory protein must bind to switch transcription on', 'A repressor switches transcription off', 'No protein is involved', 'Transcription is always on'], 0,
    'In negative control, a repressor must be removed for transcription.'],
] },
{ p: 'B2', t: 'Cell Biology', w: 2, pyq: 'IFoS-2025-B2-Q3b', q: [
  ['Polytene chromosomes were first observed by:', ['E.G. Balbiani (1881) in *Chironomus*', 'T.H. Morgan', 'Barbara McClintock', 'Walter Sutton'], 0,
    'They are well known from *Drosophila* salivary glands.'],
  ['Polytene chromosomes form by:', ['Repeated DNA replication without cell division, with the copies staying aligned', 'Fusion of many nuclei', 'Crossing over', 'Meiosis'], 0,
    'Homologues also remain paired (somatic pairing).'],
  ['"Puffs" on polytene chromosomes are sites of:', ['Active transcription, often induced by the hormone ecdysone', 'DNA damage', 'Centromeres', 'Inactive heterochromatin'], 0,
    'Large puffs are Balbiani rings.'],
  ['In *Drosophila* salivary glands, the centromeric regions of all chromosomes fuse to form the:', ['Chromocentre', 'Nucleolus', 'Kinetochore plate', 'Telomere'], 0,
    'Chromosome arms radiate from it.'],
  ['Polytene chromosomes also occur in some plant tissues, such as the:', ['Suspensor cells and antipodals', 'Root cap only', 'Pollen tube', 'Guard cells'], 0,
    'E.g., the suspensor of *Phaseolus*.'],
  ['B chromosomes are:', ['Supernumerary, dispensable chromosomes, often heterochromatic, not needed for normal growth', 'Essential chromosomes of every species', 'Sex chromosomes', 'Mitochondrial chromosomes'], 0,
    'Also called accessory chromosomes; well studied in maize and rye.'],
  ['B chromosomes often increase in number over generations because of:', ['Meiotic or mitotic drive, such as non-disjunction at pollen mitosis in rye', 'Mendelian segregation', 'Their loss in every cell', 'Crossing over with A chromosomes'], 0,
    'Such accumulation is a form of selfish inheritance.'],
  ['High numbers of B chromosomes usually:', ['Reduce plant vigour and fertility', 'Increase yield greatly', 'Have no effect at all', 'Make the plant polyploid'], 0,
    'Low numbers are usually tolerated.'],
  ['The bands and interbands of polytene chromosomes were used by C.B. Bridges to make:', ['Detailed cytological maps of *Drosophila* chromosomes', 'Maps of plant genomes', 'DNA sequences', 'Protein structures'], 0,
    'Deletions and rearrangements could be located on these maps.'],
  ['Lampbrush chromosomes differ from polytene chromosomes in that they:', ['Are meiotic chromosomes in diplotene oocytes with transcribing lateral loops', 'Are formed by endoreduplication', 'Occur in salivary glands', 'Have no genes'], 0,
    'Both are giant chromosomes showing active transcription.'],
] },
{ p: 'B2', t: 'Evolution', w: 1, pyq: 'IFoS-2025-B2-Q3c', q: [
  ['The "RNA world" hypothesis proposes that early life:', ['Used RNA both to store genetic information and to catalyse reactions', 'Used proteins only', 'Used DNA and proteins from the start', 'Had no genetic material'], 0,
    'The term was coined by Walter Gilbert (1986).'],
  ['Catalytic RNA (ribozymes) was discovered by:', ['Thomas Cech (self-splicing intron) and Sidney Altman (RNase P)', 'Watson and Crick', 'Meselson and Stahl', 'Miller and Urey'], 0,
    'They shared the 1989 Nobel Prize in Chemistry.'],
  ['The finding that peptide bond formation in ribosomes is catalysed by rRNA supports the RNA world because:', ['Protein synthesis itself is carried out by RNA', 'Ribosomes contain DNA', 'Proteins make rRNA', 'Ribosomes lack RNA'], 0,
    'Proteins may have been added to ribosomes later.'],
  ['DNA may have replaced RNA as the genetic material because DNA:', ['Is more stable (no 2′-OH) and uses thymine, which allows repair of cytosine deamination', 'Is less stable', 'Can catalyse reactions better', 'Uses uracil'], 0,
    'Deaminated cytosine becomes uracil, which is easily recognised as damage in DNA.'],
  ['Common cofactors such as ATP, NAD, FAD and coenzyme A are seen as "molecular fossils" of the RNA world because:', ['They contain ribonucleotide parts', 'They are proteins', 'They contain DNA', 'They are lipids'], 0,
    'They may be relics of RNA-based metabolism.'],
  ['The transition from RNA to DNA genomes needed an enzyme like:', ['Reverse transcriptase', 'RNA polymerase only', 'Restriction endonuclease', 'Ligase only'], 0,
    'Ribonucleotide reductase also makes deoxyribonucleotides from ribonucleotides.'],
  ['Montmorillonite clay is proposed to have helped the RNA world by:', ['Catalysing polymerisation of activated nucleotides into RNA chains', 'Producing proteins', 'Making DNA', 'Releasing oxygen'], 0,
    'Experiments by Ferris and co-workers showed chains of dozens of nucleotides.'],
  ['In vitro selection (SELEX) experiments support the RNA world by showing that:', ['RNA molecules with new catalytic abilities can evolve in the laboratory', 'Proteins cannot evolve', 'DNA cannot replicate', 'RNA is always inert'], 0,
    'Ribozymes that copy short RNA templates have been made this way.'],
  ['RNA viruses and viroids are sometimes cited in RNA-world discussions because they:', ['Show that RNA alone can serve as heritable genetic material', 'Contain no nucleic acid', 'Are made of DNA', 'Are cellular organisms'], 0,
    'Viroids are naked RNA replicated by host enzymes.'],
  ['A key weakness of RNA as a long-term genetic store is that it is:', ['Chemically less stable because of its 2′-hydroxyl group', 'Double-stranded always', 'Unable to pair bases', 'Too large to replicate'], 0,
    'The 2′-OH makes RNA prone to hydrolysis.'],
] },
{ p: 'B2', t: 'Plant Hormones & Development', w: 3, pyq: 'IFoS-2025-B2-Q4a', q: [
  ['The brassinosteroid receptor BRI1 is a:', ['Leucine-rich repeat receptor kinase at the plasma membrane', 'Nuclear steroid receptor', 'G-protein-coupled receptor', 'Ion channel'], 0,
    'Unlike animal steroid receptors, it acts at the cell surface.'],
  ['The auxin receptor TIR1 is:', ['An F-box protein that targets Aux/IAA repressors for degradation', 'A plasma-membrane ion channel', 'A kinase in the chloroplast', 'A DNA-binding transcription factor'], 0,
    'Auxin acts as a "molecular glue" between TIR1 and Aux/IAA proteins.'],
  ['Gibberellin is perceived by GID1, which leads to:', ['Degradation of DELLA growth-repressor proteins', 'Stabilisation of DELLA proteins', 'Closure of stomata', 'Ethylene production'], 0,
    'Green Revolution *Rht* dwarfing genes encode altered DELLA proteins.'],
  ['Ethylene receptors such as ETR1 are located on the:', ['Endoplasmic reticulum membrane', 'Nucleus', 'Cell wall', 'Chloroplast'], 0,
    'They act as negative regulators: ethylene binding switches off their inhibition of the response.'],
  ['ABA receptors of the PYR/PYL/RCAR family act by:', ['Inhibiting PP2C phosphatases, releasing SnRK2 kinases that trigger ABA responses', 'Activating auxin transport', 'Degrading DELLA proteins', 'Opening stomata'], 0,
    'This core pathway drives stomatal closure.'],
  ['Cytokinin receptors (e.g., AHK4/CRE1) are:', ['Histidine kinases of a two-component signalling system', 'F-box proteins', 'Ion channels', 'Nuclear steroid receptors'], 0,
    'Similar to bacterial two-component systems.'],
  ['Common second messengers in cell signalling include:', ['cAMP, IP₃, diacylglycerol and Ca²⁺', 'DNA and RNA', 'Glucose and sucrose', 'Chlorophyll and carotene'], 0,
    'Ca²⁺ is a major second messenger in plants.'],
  ['G-protein-coupled receptors (GPCRs) transmit signals by:', ['Activating heterotrimeric G proteins inside the cell', 'Phosphorylating DNA', 'Opening nuclear pores', 'Binding ribosomes'], 0,
    'They are the largest receptor family in animals; plants have fewer.'],
  ['Blue light for phototropism is perceived by:', ['Phototropins', 'Phytochromes', 'Chlorophyll a', 'Carotenoids only'], 0,
    'Cryptochromes also sense blue light; phytochromes sense red/far-red.'],
  ['MAP kinase cascades in signalling serve mainly to:', ['Amplify and relay signals through sequential phosphorylation', 'Synthesise ATP', 'Store starch', 'Replicate DNA'], 0,
    'They act in stress, defence and hormone responses.'],
] },
{ p: 'B2', t: 'Cell Biology', w: 2, pyq: 'IFoS-2025-B2-Q4b', q: [
  ['The most abundant protein of the animal extracellular matrix is:', ['Collagen', 'Keratin', 'Actin', 'Haemoglobin'], 0,
    'It gives tensile strength to connective tissues.'],
  ['The plant cell wall can be seen as the plant equivalent of the extracellular matrix, made mainly of:', ['Cellulose microfibrils in a matrix of hemicelluloses, pectins and proteins', 'Collagen and elastin', 'Chitin and keratin', 'Lipids only'], 0,
    'Secondary walls add lignin.'],
  ['Cellulose is synthesised by:', ['Rosette-shaped cellulose synthase (CESA) complexes in the plasma membrane', 'The Golgi apparatus', 'Ribosomes', 'Chloroplasts'], 0,
    'Microfibrils are spun directly into the wall.'],
  ['Hemicelluloses and pectins are synthesised in the:', ['Golgi apparatus', 'Plasma membrane', 'Nucleus', 'Mitochondria'], 0,
    'They are carried to the wall in secretory vesicles.'],
  ['Extensins are:', ['Hydroxyproline-rich structural glycoproteins of the plant cell wall', 'Enzymes of glycolysis', 'Chlorophyll proteins', 'Storage lipids'], 0,
    'They strengthen walls, including in response to wounding.'],
  ['Arabinogalactan proteins (AGPs) in plant walls are involved in:', ['Signalling, cell expansion and pollen-tube guidance', 'Photosynthesis', 'Nitrogen fixation', 'Starch storage'], 0,
    'They are heavily glycosylated proteins.'],
  ['Fibronectin binds integrins through the amino-acid motif:', ['RGD (Arg–Gly–Asp)', 'KDEL', 'TATA', 'AUG'], 0,
    'Synthetic RGD peptides block this attachment.'],
  ['The basement membrane (basal lamina) is made mainly of:', ['Laminin and type IV collagen', 'Cellulose', 'Lignin', 'Chitin'], 0,
    'It underlies epithelial cells.'],
  ['Expansins promote plant cell growth by:', ['Loosening cell walls in acidic conditions (acid growth)', 'Making cellulose', 'Adding lignin', 'Closing plasmodesmata'], 0,
    'Auxin-induced proton pumping lowers wall pH and activates expansins.'],
  ['Lignin in secondary walls mainly provides:', ['Rigidity, water-proofing and resistance to decay', 'Flexibility for growth', 'Photosynthetic pigment', 'Energy storage'], 0,
    'It is a phenolic polymer from monolignols.'],
] },
{ p: 'B2', t: 'Genetics', w: 3, pyq: 'IFoS-2025-B2-Q4c', q: [
  ['In a three-point test cross, the gene in the middle is identified from:', ['The double-crossover classes, which are the least frequent', 'The most frequent classes', 'The parental classes only', 'The F₁ phenotype'], 0,
    'The middle gene is the one that switches position in double crossovers.'],
  ['The coefficient of coincidence is:', ['Observed double crossovers ÷ expected double crossovers', 'Expected ÷ observed single crossovers', 'Map distance × 100', '1 − recombination frequency'], 0,
    'Interference = 1 − coefficient of coincidence.'],
  ['In a test cross, 100 of 1,000 progeny are recombinants. The map distance between the two genes is:', ['10 cM', '1 cM', '100 cM', '0.1 cM'], 0,
    'Recombination frequency = 100 ÷ 1000 = 10% = 10 map units.'],
  ['The maximum recombination frequency observed between two genes is:', ['50%', '100%', '25%', '75%'], 0,
    'Genes far apart on a chromosome behave as if unlinked.'],
  ['Mapping functions such as Haldane’s correct for:', ['Undetected multiple crossovers between distant genes', 'Mutation rates', 'Selection', 'Sample size'], 0,
    'Observed recombination underestimates true map distance for distant loci.'],
  ['Ordered tetrad analysis in *Neurospora* allows mapping of:', ['A gene’s distance from its centromere', 'Only plasmid genes', 'Mitochondrial genes only', 'Gene expression levels'], 0,
    'Second-division segregation patterns reveal crossovers between gene and centromere.'],
  ['Genetic maps differ from physical maps in that genetic maps are based on:', ['Recombination frequencies', 'Base-pair distances', 'Chromosome banding only', 'Protein sizes'], 0,
    'Recombination rates vary along chromosomes, so the two maps do not match exactly.'],
  ['Fluorescence in situ hybridisation (FISH) is used to:', ['Locate DNA sequences physically on chromosomes', 'Measure recombination frequency', 'Sequence proteins', 'Count cells'], 0,
    'A labelled probe binds its target sequence on chromosome spreads.'],
  ['Positive interference means that:', ['One crossover reduces the chance of another nearby', 'Crossovers always occur together', 'No crossovers occur', 'Recombination exceeds 50%'], 0,
    'Coefficient of coincidence is then less than 1.'],
  ['Human genes were first assigned to chromosomes using:', ['Somatic-cell hybrids (human–mouse) that lose human chromosomes', 'Pedigree analysis of plants', 'Tetrad analysis', 'Pure-line selection'], 0,
    'Correlating a human protein with a retained chromosome assigned the gene.'],
] },
{ p: 'B2', t: 'Plant Hormones & Development', w: 3, pyq: 'IFoS-2025-B2-Q5b', q: [
  ['Which is a day-neutral plant?', ['Tomato', 'Wheat', '*Xanthium*', 'Chrysanthemum'], 0,
    'Cucumber and many maize varieties are also day-neutral.'],
  ['Which is a long-day plant?', ['Wheat', 'Soybean', 'Rice (most traditional varieties)', 'Chrysanthemum'], 0,
    'Barley, spinach, radish and *Hyoscyamus niger* are also long-day plants.'],
  ['The photoperiodic stimulus is perceived by the:', ['Leaves', 'Roots', 'Shoot apex only', 'Flowers'], 0,
    'A signal (FT protein) then moves to the shoot apex.'],
  ['In *Arabidopsis* (a long-day plant), flowering is triggered when the protein CONSTANS:', ['Accumulates in the light at the end of long days and switches on FT', 'Is degraded in long days', 'Blocks FT', 'Acts only in roots'], 0,
    'This is the "external coincidence" model.'],
  ['A night-break with red light in a short-day plant:', ['Prevents flowering, and a following far-red flash reverses the effect', 'Promotes flowering', 'Has no effect', 'Kills the plant'], 0,
    'Shows that phytochrome measures the length of the dark period.'],
  ['Year-round flowering of chrysanthemum for the cut-flower trade is achieved by:', ['Black cloth (long nights) to induce flowering and night lighting to delay it', 'Heavy nitrogen doses', 'Growth retardants alone', 'Cold treatment'], 0,
    'Chrysanthemum is a short-day plant.'],
  ['Photoperiod-insensitive varieties were important in the Green Revolution because they:', ['Can be grown across many latitudes and sowing dates', 'Flower only in long days', 'Need vernalisation', 'Grow only in the tropics'], 0,
    'E.g., photoperiod-insensitive wheat and rice varieties.'],
  ['The critical day length of a plant is the:', ['Day length above or below which it will flower', 'Longest day of the year', 'Length of its growing season', 'Time from sowing to harvest'], 0,
    'Long-day plants flower above it; short-day plants below it.'],
  ['Most traditional rice varieties of the monsoon season are:', ['Short-day plants that flower as days shorten after September', 'Long-day plants', 'Day-neutral only', 'Plants needing vernalisation'], 0,
    'Photoperiod-sensitive varieties flower at a fixed time regardless of sowing date.'],
  ['The photoreceptor mainly involved in photoperiodic time measurement is:', ['Phytochrome (with cryptochromes)', 'Chlorophyll', 'Carotenoids', 'Phototropin only'], 0,
    'It works together with the circadian clock.'],
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 3, pyq: 'IFoS-2025-B2-Q5c', q: [
  ['Rubisco in plants has the subunit structure:', ['L₈S₈ — eight large and eight small subunits', 'L₂ only', 'S₄ only', 'L₄S₄'], 0,
    'Large subunits (catalytic) come from chloroplast *rbcL*; small subunits from nuclear *rbcS*.'],
  ['Rubisco must be activated by:', ['Carbamylation of a lysine with CO₂ and binding of Mg²⁺', 'Phosphorylation by ATP only', 'Binding of O₂', 'Cleavage into subunits'], 0,
    'Light raises stromal pH and Mg²⁺, favouring activation.'],
  ['Rubisco activase:', ['Uses ATP to remove inhibitory sugar phosphates from Rubisco’s active sites', 'Fixes CO₂ itself', 'Makes RuBP', 'Is found in mitochondria'], 0,
    'It is heat-sensitive, limiting photosynthesis at high temperatures.'],
  ['The oxygenase reaction of Rubisco produces:', ['2-phosphoglycolate and 3-PGA', 'Two molecules of 3-PGA', 'Oxaloacetate', 'Malate'], 0,
    '2-Phosphoglycolate is recycled through photorespiration.'],
  ['As temperature rises, Rubisco’s oxygenase activity relative to carboxylation:', ['Increases', 'Decreases', 'Stays the same', 'Stops'], 0,
    'CO₂ solubility falls faster than O₂, and specificity for CO₂ declines.'],
  ['Rubisco is a slow enzyme, catalysing only about ___ reactions per second per active site.', ['3', '3,000', '300,000', '0.001'], 0,
    'Plants compensate by making huge amounts of it.'],
  ['Carboxyarabinitol-1-phosphate (CA1P) is:', ['A natural night-time inhibitor of Rubisco in some plants', 'A product of photosynthesis', 'A C₄ acid', 'A chlorophyll precursor'], 0,
    'It is removed in the light with the help of Rubisco activase.'],
  ['The substrate of Rubisco in the Calvin cycle is:', ['Ribulose-1,5-bisphosphate', 'Phosphoenolpyruvate', 'Glucose', 'Pyruvate'], 0,
    'PEP is the substrate of PEP carboxylase in C₄ and CAM plants.'],
  ['C₄ plants overcome Rubisco’s oxygenase problem by:', ['Concentrating CO₂ around Rubisco in bundle-sheath cells', 'Having a different Rubisco that ignores O₂', 'Keeping stomata open all night', 'Lacking Rubisco'], 0,
    'Cyanobacteria and algae use carboxysomes or pyrenoids for the same purpose.'],
  ['Projects to raise crop photosynthesis (e.g., the C₄ rice project) aim mainly to:', ['Reduce photorespiration by concentrating CO₂ at Rubisco', 'Remove Rubisco', 'Increase transpiration', 'Stop the Calvin cycle'], 0,
    'Engineering faster or more CO₂-specific Rubisco is another route.'],
] },
{ p: 'B2', t: 'Plant Geography, Forests & Biodiversity', w: 3, pyq: 'IFoS-2025-B2-Q5d', q: [
  ['Sovereign rights of states over their biological resources were recognised by the:', ['Convention on Biological Diversity (1992)', 'Ramsar Convention', 'CITES', 'Kyoto Protocol'], 0,
    'Before this, genetic resources were widely treated as the "common heritage of mankind".'],
  ['Article 27.3(b) of the WTO TRIPS Agreement requires members to protect plant varieties by:', ['Patents or an effective sui generis system, or both', 'Only patents', 'Only trade secrets', 'No protection'], 0,
    'India chose a sui generis law — the PPV&FR Act, 2001.'],
  ['Section 3(j) of India’s Patents Act excludes from patentability:', ['Plants and animals (other than micro-organisms) and essentially biological processes', 'All chemical inventions', 'All software', 'All medical devices'], 0,
    'Section 3(p) excludes inventions that are traditional knowledge.'],
  ['India’s first Geographical Indication (2004) was:', ['Darjeeling tea', 'Basmati rice', 'Alphonso mango', 'Pochampalli ikat'], 0,
    'Registered under the Geographical Indications of Goods Act, 1999.'],
  ['The International Treaty on Plant Genetic Resources for Food and Agriculture (ITPGRFA, 2001) set up:', ['A multilateral system for access and benefit sharing of major crops, and recognised farmers’ rights', 'A ban on GM crops', 'A tiger conservation fund', 'A carbon market'], 0,
    'Covered crops are listed in its Annex I.'],
  ['Under the Biological Diversity Act, 2002, applying for IPR on an invention based on Indian biological resources requires:', ['Prior approval of the National Biodiversity Authority', 'No approval', 'Only state government approval', 'A court order'], 0,
    'The Act (amended 2023) links IPR to access and benefit sharing.'],
  ['The 1997 US patent on "basmati rice lines and grains" granted to RiceTec was:', ['Largely challenged and narrowed after India objected', 'Upheld in full', 'Never granted', 'Granted to India'], 0,
    'A well-known biopiracy controversy.'],
  ['UPOV is:', ['An international union for protection of new plant varieties (breeders’ rights)', 'A UN food agency', 'A seed bank', 'A GI registry'], 0,
    'India is not a member; its PPV&FR Act also protects farmers’ rights.'],
  ['Farmers’ rights under India’s PPV&FR Act include the right to:', ['Save, use, sow, exchange and sell farm-saved seed (not branded seed of protected varieties)', 'Sell branded seed of any protected variety', 'Patent traditional varieties abroad', 'Avoid all seed laws'], 0,
    'Farmers can also register traditional varieties and receive rewards for conservation.'],
  ['Biopiracy refers to:', ['Commercial use or patenting of biological resources or traditional knowledge without consent or benefit sharing', 'Stealing seeds from a shop', 'Illegal logging only', 'Poaching animals only'], 0,
    'The CBD and Nagoya Protocol aim to prevent it.'],
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 3, pyq: 'IFoS-2025-B2-Q5e', q: [
  ['Anammox is:', ['Anaerobic oxidation of ammonium with nitrite, releasing N₂', 'Aerobic nitrification', 'Nitrogen fixation', 'Ammonification of proteins'], 0,
    'Carried out by specialised bacteria; important in oceans and wastewater treatment.'],
  ['The largest reservoir of nitrogen is the:', ['Atmosphere (about 78% N₂)', 'Ocean', 'Soil', 'Living organisms'], 0,
    'Most organisms cannot use N₂ until it is fixed.'],
  ['The phosphorus cycle differs from the nitrogen cycle in that it has:', ['No significant atmospheric (gaseous) phase', 'A large atmospheric reservoir', 'Faster cycling', 'Microbial fixation from air'], 0,
    'Its main reservoir is rocks and sediments; it is a sedimentary cycle.'],
  ['Phosphorus enters ecosystems mainly through:', ['Weathering of phosphate rocks such as apatite', 'Fixation from air', 'Lightning', 'Rainfall'], 0,
    'Guano and rock phosphate are mined for fertiliser.'],
  ['Human production of reactive nitrogen by the Haber–Bosch process has:', ['Roughly doubled nitrogen inputs to land ecosystems', 'Had no effect', 'Reduced nitrogen availability', 'Removed nitrogen from the air completely'], 0,
    'This contributes to eutrophication and N₂O emissions.'],
  ['Denitrification returns nitrogen to the atmosphere as:', ['N₂ and N₂O', 'NH₃ only', 'NO₃⁻', 'Amino acids'], 0,
    'It happens under low-oxygen conditions.'],
  ['Mycorrhizal fungi are especially important in the phosphorus cycle because they:', ['Extend roots’ reach for immobile phosphate in soil', 'Fix nitrogen', 'Release phosphorus into the air', 'Produce phosphate rock'], 0,
    'Phosphate moves slowly in soil by diffusion.'],
  ['Nitrogen and carbon cycles are called gaseous cycles, whereas phosphorus and sulphur (mostly) are:', ['Sedimentary cycles', 'Atmospheric cycles', 'Closed cycles', 'Non-cycles'], 0,
    'Sulphur has a minor gaseous component (SO₂, H₂S).'],
  ['Ammonification is:', ['Release of ammonium from organic matter by decomposers', 'Conversion of nitrate to N₂', 'Fixation of N₂', 'Uptake of nitrate by plants'], 0,
    'It is also called mineralisation of nitrogen.'],
  ['Much of the phosphorus lost from land ends up in:', ['Ocean sediments, returning to land only over geological time', 'The atmosphere', 'Living plants permanently', 'Glaciers'], 0,
    'This makes phosphorus a finite resource for agriculture.'],
] },
{ p: 'B2', t: 'Biotechnology & GM Crops', w: 2, pyq: 'IFoS-2025-B2-Q6a', q: [
  ['Which is an indirect (vector-mediated) method of plant gene transfer?', ['*Agrobacterium*-mediated transformation', 'Particle bombardment', 'Electroporation', 'PEG-mediated protoplast uptake'], 0,
    'Direct methods introduce DNA without a biological vector.'],
  ['The particle gun (biolistics) was developed by:', ['John Sanford and co-workers (1987)', 'Mary-Dell Chilton', 'Kary Mullis', 'Herbert Boyer'], 0,
    'DNA-coated gold or tungsten microparticles are shot into cells.'],
  ['*Agrobacterium vir* genes are induced by:', ['Phenolic compounds such as acetosyringone released by wounded plant cells', 'Auxin', 'Light', 'Nitrogen fertiliser'], 0,
    'Acetosyringone is added to improve transformation of monocots such as rice.'],
  ['The T-DNA transferred by *Agrobacterium* is defined by:', ['25-bp border repeats', 'Promoters only', 'Introns', 'Telomeres'], 0,
    'Any DNA placed between the borders can be transferred.'],
  ['In a binary vector system:', ['T-DNA with the gene of interest is on one plasmid, and *vir* genes are on a separate helper Ti plasmid', 'Both are in the plant genome', 'Only viruses are used', 'No bacteria are needed'], 0,
    'Binary vectors are small and easy to handle in *E. coli*.'],
  ['The "floral dip" method of transformation is widely used in:', ['*Arabidopsis thaliana*', 'Rice', 'Maize', 'Sugarcane'], 0,
    'Flowers are dipped in *Agrobacterium* suspension; transgenic seeds are selected later.'],
  ['Which is a selectable marker gene used in plant transformation?', ['*nptII*, giving kanamycin resistance', '*gus*', '*gfp*', 'Luciferase'], 0,
    '*hpt* (hygromycin) and *bar* (glufosinate) are others; *gus*, *gfp* and luciferase are reporters.'],
  ['The GUS reporter gene (*uidA*) is detected by:', ['Blue staining with X-Gluc', 'Green fluorescence', 'Light emission', 'Red colour with tetrazolium'], 0,
    'GFP gives green fluorescence; luciferase gives light.'],
  ['Electroporation introduces DNA into protoplasts by:', ['Brief electric pulses that make temporary pores in the membrane', 'Shooting particles', 'Using bacteria', 'Using viruses'], 0,
    'Protoplasts then regenerate walls and plants.'],
  ['Monocots were once hard to transform with *Agrobacterium*; this was overcome mainly by:', ['Using acetosyringone, immature embryos and super-binary vectors, alongside biolistics', 'Using only seeds', 'Avoiding tissue culture', 'Using chloroplast genes'], 0,
    'Rice and maize are now routinely transformed with *Agrobacterium*.'],
] },
{ p: 'B2', t: 'Enzymes & Nitrogen Metabolism', w: 2, pyq: 'IFoS-2025-B2-Q6b', q: [
  ['A holoenzyme is:', ['An apoenzyme together with its cofactor', 'An enzyme without its cofactor', 'An RNA enzyme', 'A denatured enzyme'], 0,
    'The protein part alone is the apoenzyme.'],
  ['A prosthetic group differs from a coenzyme in that it is:', ['Tightly (often covalently) bound to the enzyme', 'Loosely bound and dissociable', 'Always a metal ion', 'Never organic'], 0,
    'E.g., haem in cytochromes; FAD in some flavoproteins.'],
  ['Coenzyme A is derived from:', ['Pantothenic acid (vitamin B₅)', 'Riboflavin (B₂)', 'Thiamine (B₁)', 'Niacin (B₃)'], 0,
    'NAD⁺ comes from niacin, FAD from riboflavin, TPP from thiamine, PLP from pyridoxine.'],
  ['Thiamine pyrophosphate (TPP) is the coenzyme for:', ['Decarboxylation of α-keto acids such as pyruvate', 'Transamination', 'Carboxylation by biotin', 'Hydrolysis of proteins'], 0,
    'Pyruvate dehydrogenase and transketolase need TPP.'],
  ['Pyridoxal phosphate (PLP), from vitamin B₆, is the coenzyme for:', ['Transamination reactions in amino-acid metabolism', 'Carboxylation', 'Oxidation of NADH', 'Glycolysis only'], 0,
    'Transaminases move amino groups between amino and keto acids.'],
  ['Since 2018, the IUBMB classification recognises how many main enzyme classes?', ['Seven', 'Six', 'Five', 'Four'], 0,
    'Oxidoreductases, transferases, hydrolases, lyases, isomerases, ligases, and translocases (added in 2018).'],
  ['The induced-fit model of enzyme action was proposed by:', ['Daniel Koshland', 'Emil Fischer', 'Leonor Michaelis', 'Hans Krebs'], 0,
    'Fischer proposed the older lock-and-key model.'],
  ['A non-competitive inhibitor:', ['Lowers Vmax while Km stays unchanged', 'Raises Km while Vmax stays unchanged', 'Lowers both Km and Vmax', 'Has no effect on Vmax'], 0,
    'It binds a site other than the active site.'],
  ['Allosteric enzymes typically show:', ['Sigmoid (S-shaped) kinetics and regulation by effectors at sites other than the active site', 'Hyperbolic kinetics only', 'No regulation', 'Activity only at 0 °C'], 0,
    'They often catalyse committed steps of pathways.'],
  ['Isozymes are:', ['Different molecular forms of an enzyme that catalyse the same reaction', 'Enzymes that catalyse different reactions', 'Inactive enzymes', 'Non-protein enzymes'], 0,
    'Isozyme patterns were used as early genetic markers.'],
] },
{ p: 'B2', t: 'Plant Geography, Forests & Biodiversity', w: 3, pyq: 'IFoS-2025-B2-Q6c', q: [
  ['The acronym HIPPO summarises the main threats to biodiversity as:', ['Habitat loss, Invasive species, Pollution, human Population and Overharvesting', 'Heat, Ice, Pests, Pathogens, Oxygen', 'Hunting, Industry, Plantation, Poverty, Ozone', 'Hybrids, Irrigation, Pesticides, Politics, Oil'], 0,
    'Habitat loss is the leading cause of plant extinctions.'],
  ['*Saussurea costus* (kuth), overharvested for its roots, is listed in CITES:', ['Appendix I', 'Appendix II', 'Appendix III', 'Not listed'], 0,
    'Appendix I bans commercial international trade.'],
  ['A plant invader that threatens forest understoreys across India is:', ['*Lantana camara*', '*Shorea robusta*', '*Tectona grandis*', '*Dalbergia sissoo*'], 0,
    '*Chromolaena odorata*, *Mikania micrantha* and *Prosopis juliflora* are other major invaders.'],
  ['Climate warming is expected to push many Himalayan plant species:', ['Upslope, shrinking alpine habitats', 'Downslope into plains', 'Into oceans', 'Nowhere; they are unaffected'], 0,
    'Species at summits may have nowhere left to go.'],
  ['Cryopreservation of germplasm is done in liquid nitrogen at about:', ['−196 °C', '−18 °C', '0 °C', '−50 °C'], 0,
    'Used for recalcitrant seeds, embryos, pollen and shoot tips.'],
  ['Medicinal Plants Conservation Areas (MPCAs) are an example of:', ['In-situ conservation of wild medicinal plant populations', 'Ex-situ seed banking', 'Tissue culture labs', 'Herbarium collections'], 0,
    'Established in several states with community participation.'],
  ['The Red Data Book of Indian Plants was published by:', ['The Botanical Survey of India', 'NBPGR', 'ICAR', 'FAO'], 0,
    'It documents threatened plants of India.'],
  ['The National Medicinal Plants Board, set up in 2000, works under the:', ['Ministry of AYUSH', 'Ministry of Agriculture', 'Ministry of Commerce', 'Ministry of Mines'], 0,
    'It supports conservation, cultivation and trade of medicinal plants.'],
  ['Field gene banks are used for:', ['Crops with recalcitrant seeds or that are vegetatively propagated, e.g., mango, banana, coconut', 'Wheat and rice only', 'Microbes only', 'Pollen only'], 0,
    'They keep living plants in the field.'],
  ['Which is an example of in-situ conservation?', ['A biosphere reserve', 'A seed bank', 'A cryobank', 'A botanical garden'], 0,
    'In-situ keeps species in their natural habitats with ecological processes intact.'],
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 3, pyq: 'IFoS-2025-B2-Q7a', q: [
  ['Primary succession differs from secondary succession in that primary succession starts on:', ['Bare areas with no soil, such as rock or new volcanic land', 'Abandoned fields with soil', 'Burnt forests', 'Cut-over forests'], 0,
    'Secondary succession is faster because soil and seed banks remain.'],
  ['The monoclimax theory, holding that each climatic region has one climax, was proposed by:', ['F.E. Clements', 'A.G. Tansley', 'R.H. Whittaker', 'E.P. Odum'], 0,
    'Tansley proposed the polyclimax theory; Whittaker the climax-pattern hypothesis.'],
  ['The facilitation, tolerance and inhibition models of succession were proposed by:', ['Connell and Slatyer (1977)', 'Clements (1916)', 'Lindeman (1942)', 'Odum (1969)'], 0,
    'In facilitation, early species make the site suitable for later ones.'],
  ['A typical hydrosere proceeds in the order:', ['Phytoplankton → submerged → floating → reed swamp → sedge meadow → woodland → forest', 'Forest → reed swamp → phytoplankton', 'Lichens → mosses → herbs → shrubs', 'Grassland → desert → forest'], 0,
    'Lichens → mosses → herbs → shrubs is the xerosere on rock.'],
  ['Succession driven by changes the organisms themselves make to the site is called:', ['Autogenic succession', 'Allogenic succession', 'Retrogressive succession', 'Cyclic succession'], 0,
    'Allogenic succession is driven by external factors such as siltation or climate.'],
  ['As succession approaches climax, the ratio of gross production to standing biomass (P/B):', ['Decreases', 'Increases', 'Stays constant', 'Becomes infinite'], 0,
    'Mature systems store more biomass per unit of production (Odum, 1969).'],
  ['A grassland kept from developing into forest by grazing or fire is a:', ['Disclimax (biotic climax)', 'Climatic climax', 'Pioneer community', 'Hydrosere'], 0,
    'Many Indian grasslands and savannas are maintained this way.'],
  ['A sere developing on sand is called a:', ['Psammosere', 'Halosere', 'Lithosere', 'Hydrosere'], 0,
    'Halosere: saline habitats; lithosere: rock.'],
  ['During succession, species diversity generally:', ['Increases, often peaking before or near climax', 'Decreases steadily', 'Stays constant', 'Falls to zero'], 0,
    'Nutrient cycles also become more closed.'],
  ['Each intermediate community in a succession is called a:', ['Seral stage', 'Climax', 'Ecotone', 'Niche'], 0,
    'The whole sequence is a sere.'],
] },
{ p: 'B2', t: 'Biotechnology & GM Crops', w: 2, pyq: 'IFoS-2025-B2-Q7c', q: [
  ['The usual stages of micropropagation are:', ['Stock-plant preparation, establishment, multiplication, rooting and hardening', 'Sowing, weeding, harvesting', 'Pollination, fertilisation, seed set', 'Grafting, budding, layering'], 0,
    'Murashige described stages I–III; stage 0 and stage IV (acclimatisation) were added later.'],
  ['The micropropagation route that gives the most genetically stable plants is:', ['Axillary (shoot) bud proliferation', 'Callus-mediated organogenesis', 'Protoplast culture', 'Cell suspension culture'], 0,
    'Callus phases increase the risk of somaclonal variation.'],
  ['Explants are surface-sterilised commonly with:', ['70% ethanol followed by sodium hypochlorite or mercuric chloride', 'Distilled water only', 'Fertiliser solution', 'Auxin solution'], 0,
    'Then rinsed several times in sterile water.'],
  ['Shoot multiplication in micropropagation is usually promoted by:', ['A cytokinin such as BAP', 'Abscisic acid', 'Ethylene', 'High auxin alone'], 0,
    'Rooting is then induced with auxins such as IBA or NAA.'],
  ['Browning of explants in culture is caused by:', ['Oxidation of released phenolics, reduced with activated charcoal, antioxidants or PVP', 'Excess light only', 'Bacterial contamination only', 'Too much agar'], 0,
    'Common in woody species such as teak and mango.'],
  ['Hyperhydricity (vitrification) in cultures is:', ['A glassy, water-soaked abnormality of shoots, linked to high humidity and cytokinin', 'Normal rooting', 'Seed formation', 'Callus browning'], 0,
    'Lowering humidity and cytokinin and improving aeration help.'],
  ['Hardening of tissue-culture plants means:', ['Gradually lowering humidity so plantlets adapt to outdoor conditions', 'Putting them in a freezer', 'Adding more sugar', 'Spraying herbicide'], 0,
    'In-vitro leaves have weak cuticles and poorly functioning stomata.'],
  ['A crop in India where tissue-culture plantlets are widely used commercially is:', ['Banana (e.g., Grand Naine)', 'Wheat', 'Mustard', 'Pearl millet'], 0,
    'Also sugarcane, potato, orchids, teak and bamboo.'],
  ['Temporary immersion bioreactors in micropropagation are used to:', ['Lower costs and raise multiplication by periodically bathing cultures in liquid medium', 'Freeze cultures', 'Sterilise explants', 'Store seeds'], 0,
    'Liquid systems avoid the cost of agar and allow automation.'],
  ['Tissue-culture raised plants sold in India are certified under:', ['The National Certification System for Tissue Culture Raised Plants (NCS-TCP) of DBT', 'The Seeds Act only', 'FSSAI', 'The Insecticides Act'], 0,
    'Tests check virus freedom and genetic fidelity.'],
] },
{ p: 'B2', t: 'Enzymes & Nitrogen Metabolism', w: 2, pyq: 'IFoS-2025-B2-Q8b', q: [
  ['The Fe protein (dinitrogenase reductase) of nitrogenase is encoded by:', ['*nifH*', '*nifD*', '*nifK*', '*nodA*'], 0,
    '*nifD* and *nifK* encode the MoFe protein (dinitrogenase).'],
  ['The best-studied *nif* gene cluster (about 20 genes) is that of:', ['*Klebsiella pneumoniae*', '*Escherichia coli*', '*Bacillus subtilis*', '*Saccharomyces*'], 0,
    'It was the model for understanding nitrogenase assembly and regulation.'],
  ['In many bacteria, *nif* genes are switched on by NifA and inhibited by:', ['NifL, which responds to oxygen and fixed nitrogen', 'NifH', 'Leghaemoglobin', 'NodD'], 0,
    'Fixation stops when oxygen or ammonium is abundant, saving ATP.'],
  ['The overall nitrogenase reaction consumes about how much ATP per N₂ reduced?', ['16 ATP', '2 ATP', '100 ATP', 'No ATP'], 0,
    'N₂ + 8H⁺ + 8e⁻ + 16 ATP → 2NH₃ + H₂ + 16 ADP + 16 Pi.'],
  ['Nitrogenase activity is commonly measured by the:', ['Acetylene reduction assay', 'Tetrazolium test', 'Kjeldahl method only', 'Chlorophyll fluorescence'], 0,
    'Nitrogenase reduces acetylene to ethylene, measured by gas chromatography.'],
  ['Rhizobial *nod* genes such as *nodABC* are needed for:', ['Synthesis of Nod factors that trigger nodule formation', 'Nitrogenase structure', 'Leghaemoglobin synthesis', 'Photosynthesis'], 0,
    'The regulator *nodD* is activated by flavonoids from the legume root.'],
  ['Uptake hydrogenase (*hup*) genes improve nitrogen fixation efficiency by:', ['Recycling the H₂ released by nitrogenase to recover energy', 'Producing more H₂', 'Blocking nitrogenase', 'Fixing CO₂'], 0,
    'Hup⁺ strains can give better legume yields.'],
  ['Nitrogenase is irreversibly inactivated by:', ['Oxygen', 'Nitrogen gas', 'Water', 'Light'], 0,
    'Organisms protect it by heterocysts, leghaemoglobin or high respiration.'],
  ['The metal cofactor at the active site of the usual nitrogenase is:', ['An iron–molybdenum cofactor (FeMo-co)', 'Copper', 'Zinc', 'Manganese'], 0,
    'Alternative nitrogenases use vanadium or only iron.'],
  ['Transferring *nif* genes into cereals is difficult mainly because:', ['Nitrogenase needs many genes, a low-oxygen environment and much energy', 'Cereals lack DNA', 'Nitrogenase is a single small protein', 'Cereals already fix nitrogen'], 0,
    'Current work targets plastids or mitochondria and engineered associative bacteria.'],
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 3, pyq: 'IFoS-2025-B2-Q8c', q: [
  ['The main regulatory (rate-limiting) enzyme of glycolysis is:', ['Phosphofructokinase', 'Hexokinase only', 'Aldolase', 'Enolase'], 0,
    'It is inhibited by ATP and citrate.'],
  ['Plants have, in addition to ATP-dependent PFK, an enzyme that phosphorylates fructose-6-phosphate using:', ['Pyrophosphate (PPi-PFK)', 'GTP', 'NADPH', 'Light'], 0,
    'It gives plants flexibility under low ATP, e.g., during hypoxia.'],
  ['ATP is formed by substrate-level phosphorylation in glycolysis at the steps catalysed by:', ['Phosphoglycerate kinase and pyruvate kinase', 'Hexokinase and PFK', 'Aldolase and triose phosphate isomerase', 'Enolase only'], 0,
    'Net gain: 2 ATP and 2 NADH per glucose.'],
  ['The first enzyme of the oxidative pentose phosphate pathway is:', ['Glucose-6-phosphate dehydrogenase', 'Transketolase', 'Pyruvate kinase', 'Citrate synthase'], 0,
    'This phase produces NADPH and ribulose-5-phosphate.'],
  ['The main products of the pentose phosphate pathway are:', ['NADPH and pentose sugars (ribose-5-phosphate)', 'ATP only', 'Pyruvate and lactate', 'Acetyl-CoA'], 0,
    'NADPH is used in biosynthesis; ribose-5-phosphate in nucleotides.'],
  ['The pentose phosphate pathway supplies erythrose-4-phosphate for the:', ['Shikimate pathway (aromatic amino acids, lignin, phenolics)', 'Krebs cycle', 'Glyoxylate cycle', 'Urea cycle'], 0,
    'Links carbohydrate metabolism to secondary metabolism.'],
  ['The non-oxidative phase of the pentose phosphate pathway is catalysed by:', ['Transketolase and transaldolase', 'Hexokinase and PFK', 'PEP carboxylase', 'Rubisco'], 0,
    'It interconverts 3-, 4-, 5-, 6- and 7-carbon sugars.'],
  ['Activity of the pentose phosphate pathway often increases in:', ['Infected, wounded or differentiating tissues', 'Dormant seeds only', 'Dead cells', 'Only in darkness'], 0,
    'Extra NADPH and phenolic precursors support defence.'],
  ['In non-green plastids of roots, the pentose phosphate pathway provides NADPH for:', ['Nitrite reduction and fatty-acid synthesis', 'Photosynthesis', 'ATP synthase', 'Starch breakdown only'], 0,
    'Leaves get NADPH from the light reactions instead.'],
  ['Pyruvate from glycolysis enters mitochondria and is converted to acetyl-CoA by:', ['Pyruvate dehydrogenase complex', 'Lactate dehydrogenase', 'Pyruvate kinase', 'Alcohol dehydrogenase'], 0,
    'Under anaerobic conditions, pyruvate goes to ethanol or lactate instead.'],
] }
);
