/* PYQ-linked MCQs — IFoS 2018 Agriculture Paper I, Q1–Q4 (verbatim PYQs). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Agro-climatic Zones & Cropping Systems', w: 3, pyq: 'IFoS-2018-A1-Q1a', q: [
  ['The Planning Commission (1988–89) divided India into how many agro-climatic regions?', ['Fifteen', 'Twenty', 'One hundred and twenty-seven', 'Eight'], 0,
    'This was done for regional planning in the Seventh Plan.'],
  ['Under the ICAR National Agricultural Research Project (NARP), India was divided into about:', ['127 agro-climatic zones', '15 zones', '20 zones', '60 zones'], 0,
    'NARP zones are smaller subdivisions used for research planning.'],
  ['NBSS&LUP delineated India into how many agro-ecological regions (AERs), based on soils, physiography and growing period?', ['Twenty', 'Fifteen', 'Eight', 'Ninety'], 0,
    'These were later split into about 60 agro-ecological sub-regions.'],
  ['The dominant cropping system of the Trans-Gangetic Plains (Punjab, Haryana) is:', ['Rice–wheat', 'Pearl millet–mustard', 'Rice–rice', 'Coconut-based'], 0,
    'It is highly productive but depletes groundwater.'],
  ['The Western Himalayan region is known for:', ['Temperate fruits such as apple, with maize- and rice-based systems', 'Rice–rice systems', 'Coconut and spices', 'Pearl millet and clusterbean'], 0,
    'It covers Jammu & Kashmir, Himachal Pradesh and Uttarakhand.'],
  ['The Western Dry region (western Rajasthan) mainly grows:', ['Pearl millet, clusterbean and moth bean', 'Rice and jute', 'Tea and oranges', 'Coconut and arecanut'], 0,
    'Low, erratic rainfall favours hardy, short-duration crops.'],
  ['The Eastern Plateau and Hills region (Chhota Nagpur, Chhattisgarh) is dominated by:', ['Rainfed upland rice and other kharif crops', 'Irrigated rice–wheat', 'Apple orchards', 'Saffron'], 0,
    'Low cropping intensity and acid soils are major constraints there.'],
  ['The Island region (Andaman & Nicobar, Lakshadweep) is dominated by:', ['Coconut, arecanut and spices', 'Wheat and mustard', 'Cotton', 'Pearl millet'], 0,
    'Humid tropical conditions suit plantation crops.'],
  ['The West Coast Plains and Ghats region is noted for:', ['Rice, coconut, rubber and spices', 'Pearl millet and sorghum', 'Wheat and barley', 'Apple and walnut'], 0,
    'Heavy monsoon rain supports plantation agriculture.'],
  ['The Gujarat Plains and Hills region is important for:', ['Groundnut and cotton', 'Tea and jute', 'Saffron and apple', 'Rubber'], 0,
    'Saurashtra is India’s groundnut bowl.']
] },
{ p: 'A1', t: 'Dryland Farming & Watershed Management', w: 3, pyq: 'IFoS-2018-A1-Q1b', q: [
  ['Rainfed farming means:', ['Growing crops that depend entirely on rainfall, without irrigation', 'Growing crops only in winter', 'Growing crops under full canal irrigation', 'Hydroponics'], 0,
    'About half of India’s net sown area is rainfed.'],
  ['In the Indian classification, farming in areas with annual rainfall below 750 mm and frequent crop failure is called:', ['Dry farming', 'Dryland farming', 'Rainfed farming', 'Wetland farming'], 0,
    'Dryland farming covers 750–1,150 mm; rainfed farming covers over 1,150 mm.'],
  ['The ICAR institute leading research on rainfed agriculture is:', ['CRIDA, Hyderabad', 'CAZRI, Jodhpur', 'IARI, New Delhi', 'NDRI, Karnal'], 0,
    'CRIDA also coordinates the national climate-resilient agriculture project, NICRA.'],
  ['The broad bed and furrow (BBF) system, developed by ICRISAT, is most suited to:', ['Vertisols (black soils)', 'Sandy desert soils', 'Peat soils', 'Laterite hills'], 0,
    'It drains excess water and stores moisture in these soils.'],
  ['Compartmental bunding in dryland fields is used for:', ['In-situ conservation of rainwater', 'Draining the field', 'Weed control', 'Applying fertiliser'], 0,
    'Small basins hold rain where it falls.'],
  ['Farm ponds in rainfed areas are used for:', ['Harvesting runoff for life-saving irrigation', 'Fish only', 'Disposing of salts', 'Storing fertiliser'], 0,
    'One protective irrigation at a critical stage can save the crop.'],
  ['A dryland intercropping system that stabilises yields is:', ['Sorghum + pigeonpea', 'Rice + wheat', 'Sugarcane + banana', 'Tea + coffee'], 0,
    'If one crop fails, the other still gives some yield.'],
  ['Mulching in rainfed farming mainly helps by:', ['Reducing evaporation and conserving soil moisture', 'Increasing runoff', 'Raising soil salinity', 'Removing organic matter'], 0,
    'Crop residues and polythene are both used as mulch.'],
  ['Seed hardening (soaking seed in water or salt solution and drying it before sowing) helps dryland crops by:', ['Improving germination and early drought tolerance', 'Killing weeds', 'Increasing seed size', 'Fixing nitrogen'], 0,
    'It is widely recommended for sorghum and pearl millet.'],
  ['Off-season (summer) tillage in rainfed areas helps by:', ['Improving infiltration of early monsoon rain and reducing weeds and pests', 'Increasing evaporation', 'Compacting the soil', 'Adding salts'], 0,
    'It opens the soil before the rains arrive.']
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 2, pyq: 'IFoS-2018-A1-Q1c', q: [
  ['Lignocellulosic materials such as crop residues are made mainly of:', ['Cellulose, hemicellulose and lignin', 'Protein and fat', 'Starch only', 'Chitin'], 0,
    'Their breakdown supplies soil organic matter.'],
  ['The component of plant residues most resistant to decomposition is:', ['Lignin', 'Sugars', 'Starch', 'Proteins'], 0,
    'Lignin-derived compounds contribute to stable humus.'],
  ['Lignin in residues is degraded most effectively by:', ['White-rot fungi such as *Phanerochaete chrysosporium*', 'Nitrogen-fixing bacteria', 'Algae', 'Earthworms alone'], 0,
    'Cellulose is broken down by fungi such as *Trichoderma*.'],
  ['Residues with a wide C:N ratio, such as cereal straw, when added to soil:', ['Cause temporary immobilisation of soil nitrogen', 'Release nitrogen immediately', 'Raise soil salinity', 'Have no effect on nitrogen'], 0,
    'Microbes use soil N while decomposing carbon-rich material.'],
  ['Net mineralisation of nitrogen is expected when residue C:N ratio is below about:', ['20–25:1', '80:1', '100:1', '200:1'], 0,
    'Wheat straw has a C:N ratio of about 80–100:1.'],
  ['Humus improves soil by:', ['Raising cation exchange capacity, water-holding capacity and aggregation', 'Lowering CEC', 'Making soil saline', 'Reducing microbial activity'], 0,
    'It also buffers soil pH.'],
  ['Burning rice straw in the field:', ['Loses nitrogen, sulphur and organic carbon and pollutes the air', 'Adds nitrogen to soil', 'Improves soil structure over time', 'Has no environmental effect'], 0,
    'It is a major cause of winter smog in north India.'],
  ['The PUSA decomposer, developed by IARI, is:', ['A fungal consortium that speeds up in-situ decomposition of crop residues', 'A chemical herbicide', 'A tractor-drawn plough', 'A nitrogen fertiliser'], 0,
    'It is sprayed on stubble to avoid burning.'],
  ['Composting of wide C:N residues is speeded up by:', ['Adding a nitrogen source (dung, urea) and microbial inoculants', 'Keeping the heap dry', 'Adding salt', 'Sterilising the heap'], 0,
    'This narrows the C:N ratio for the microbes.'],
  ['Most cultivated Indian soils are:', ['Low in organic carbon (often below 0.5%)', 'Very high in organic carbon', 'Peaty', 'Rich in humus everywhere'], 0,
    'High temperatures speed up the oxidation of soil organic matter.']
] },
{ p: 'A1', t: 'Agro-climatic Zones & Cropping Systems', w: 3, pyq: 'IFoS-2018-A1-Q1d', q: [
  ['Multiple cropping means:', ['Growing two or more crops on the same field in a year', 'Growing one crop over several years', 'Growing crops only in pots', 'Rotating fields among farmers'], 0,
    'It includes both sequential cropping and intercropping.'],
  ['Cropping intensity is calculated as:', ['(Gross cropped area ÷ net sown area) × 100', '(Net sown area ÷ gross cropped area) × 100', 'Yield ÷ area', 'Irrigated area ÷ total area'], 0,
    'India’s cropping intensity is about 155% (recent estimates — check the latest figure).'],
  ['Growing crops one after another on the same field within a year is:', ['Sequential cropping', 'Intercropping', 'Mixed cropping', 'Alley cropping'], 0,
    'Rice–wheat is a double-cropping sequence.'],
  ['Sowing lentil or lathyrus into a standing rice crop shortly before its harvest is:', ['Relay (utera/paira) cropping', 'Ratoon cropping', 'Strip cropping', 'Mixed cropping'], 0,
    'The next crop uses residual moisture.'],
  ['Raising a second crop from the stubble regrowth of the previous crop, as in sugarcane, is:', ['Ratoon cropping', 'Relay cropping', 'Intercropping', 'Alley cropping'], 0,
    'It saves on planting material and time.'],
  ['A land equivalent ratio (LER) greater than one in an intercrop shows that:', ['The intercrop uses land more efficiently than sole crops', 'The sole crops are better', 'Both give equal yields', 'The crops failed'], 0,
    'LER is the sum of the relative yields of the component crops.'],
  ['Mixed cropping differs from intercropping in that mixed cropping:', ['Sows seeds of different crops together, without a definite row arrangement', 'Always uses rows', 'Uses only one crop', 'Is only done in orchards'], 0,
    'Intercropping follows a set row ratio.'],
  ['Multistorey cropping in coconut gardens combines coconut with:', ['Crops such as black pepper, cocoa, banana and pineapple in different canopy layers', 'Wheat and mustard', 'Rice only', 'Sugarcane only'], 0,
    'It makes use of light at several levels.'],
  ['Strip cropping on sloping land is mainly used to:', ['Control soil erosion', 'Increase salinity', 'Grow a single crop', 'Save fertiliser'], 0,
    'Erosion-resisting strips alternate with erosion-permitting crops.'],
  ['The main significance of multiple cropping is that it:', ['Increases production per unit area and time, and spreads risk', 'Always reduces yield', 'Needs no inputs', 'Suits only deserts'], 0,
    'It is vital in a land-scarce country like India.']
] },
{ p: 'A1', t: 'Crop Production', w: 2, pyq: 'IFoS-2018-A1-Q1e', q: [
  ['Rice and soybean are generally:', ['Short-day plants', 'Long-day plants', 'Day-neutral plants', 'Not affected by day length'], 0,
    'Wheat and barley are long-day plants.'],
  ['Winter wheat needs a cold period to flower. This is called:', ['Vernalisation', 'Photoperiodism', 'Stratification', 'Scarification'], 0,
    'Spring wheats grown in India need little or no vernalisation.'],
  ['Terminal heat stress (above about 30 °C) during grain filling in wheat:', ['Shortens grain filling and reduces grain weight', 'Increases yield', 'Has no effect', 'Only improves quality'], 0,
    'Timely sowing helps avoid it in north India.'],
  ['The concept that growth is limited by the nutrient in shortest supply is:', ['Liebig’s law of the minimum', 'Shelford’s law of tolerance', 'Mitscherlich’s law', 'Hardy–Weinberg law'], 0,
    'Blackman extended it to limiting factors in photosynthesis.'],
  ['Shelford’s law of tolerance states that a species’ distribution is controlled by:', ['Both the minimum and maximum limits of a factor it can tolerate', 'Only the most abundant factor', 'Only light', 'Only soil type'], 0,
    'Too much of a factor can limit a species as much as too little.'],
  ['Tea is grown on:', ['Acid soils, around pH 4.5–5.5, with high rainfall', 'Alkaline soils above pH 8.5', 'Saline soils', 'Arid sandy soils'], 0,
    'This limits it to the hills of Assam, Darjeeling and the Nilgiris.'],
  ['Air temperature falls with altitude by roughly:', ['6.5 °C per 1,000 m', '1 °C per 1,000 m', '20 °C per 1,000 m', 'Zero'], 0,
    'This decides how crop belts are zoned in the hills.'],
  ['Growing degree days (heat units) are used to:', ['Predict crop phenology and maturity from accumulated temperature', 'Measure rainfall', 'Measure soil pH', 'Count pests'], 0,
    'GDD = Σ (mean daily temperature − base temperature).'],
  ['Rising atmospheric CO₂ benefits the growth of:', ['C₃ crops such as wheat and rice more than C₄ crops', 'C₄ crops more than C₃ crops', 'Neither', 'Only CAM plants'], 0,
    'C₄ photosynthesis is already nearly CO₂-saturated.'],
  ['Frost is a major hazard for:', ['Potato, mustard and chickpea in north Indian winters', 'Rice in kharif', 'Coconut in Kerala', 'Rubber in Kerala'], 0,
    'Light irrigation and smoking protect crops on frosty nights.']
] },
{ p: 'A1', t: 'Agroforestry & Social Forestry', w: 3, pyq: 'IFoS-2018-A1-Q2a', q: [
  ['Agroforestry is:', ['Deliberately growing woody perennials with crops and/or livestock on the same land', 'Clear-felling forests for crops', 'Growing trees only in forests', 'Growing crops in greenhouses'], 0,
    'It combines ecological and economic benefits.'],
  ['India’s National Agroforestry Policy was adopted in:', ['2014, making India the first country with such a policy', '1988', '2006', '2020'], 0,
    'It was followed by the Sub-Mission on Agroforestry (2016–17).'],
  ['Poplar-based agroforestry in Punjab, Haryana and western UP mainly supplies:', ['Wood for plywood and matchwood', 'Fodder only', 'Fruits', 'Oilseeds'], 0,
    'Wheat is grown under the leafless poplars in winter.'],
  ['The khejri tree (*Prosopis cineraria*) supports rural livelihoods in Rajasthan by providing:', ['Leaf fodder (loong), edible pods (sangri) and fuelwood, while improving soil', 'Timber for export only', 'Rubber', 'Tea'], 0,
    'It is the state tree of Rajasthan.'],
  ['The taungya system, which originated in Myanmar, involves:', ['Growing crops between rows of young forest plantations', 'Grazing animals in forests', 'Home gardens', 'Growing trees on field bunds only'], 0,
    'Farmers get land for crops while tending the tree seedlings.'],
  ['Kerala’s homegardens are an example of:', ['Multi-tier agroforestry with trees, crops and livestock', 'Monocropping', 'Shifting cultivation', 'Plantation forestry'], 0,
    'They provide food, income and fuel all year round.'],
  ['Silvopasture combines:', ['Trees with pasture and livestock', 'Trees with fish', 'Crops with fish', 'Crops with poultry only'], 0,
    'Fodder trees such as *Leucaena* and *Albizia* are common.'],
  ['The ICAR institute for agroforestry research is located at:', ['Jhansi', 'Dehradun', 'Jodhpur', 'Bengaluru'], 0,
    'It is the Central Agroforestry Research Institute (CAFRI).'],
  ['Agroforestry improves rural livelihoods mainly by:', ['Diversifying income, supplying fuel, fodder and timber, and reducing risk', 'Increasing dependence on one crop', 'Reducing employment', 'Increasing soil erosion'], 0,
    'Trees act as a savings bank that can be cut in hard times.'],
  ['The "Har Medh Par Ped" (a tree on every field bund) approach is part of:', ['The Sub-Mission on Agroforestry', 'The PM-KISAN scheme', 'The Soil Health Card scheme', 'e-NAM'], 0,
    'It promotes trees on farm boundaries.']
] },
{ p: 'A1', t: 'Weed Science', w: 3, pyq: 'IFoS-2018-A1-Q2b', q: [
  ['The basic principles of weed management are:', ['Prevention, eradication and control, combined in integrated management', 'Irrigation, drainage and tillage', 'Harvesting, threshing and storage', 'Breeding, selection and testing'], 0,
    'Integrated weed management (IWM) combines several methods.'],
  ['Preventive weed control includes:', ['Using clean seed, weed-free manure and clean implements', 'Spraying herbicides after emergence', 'Hand weeding at flowering', 'Releasing insects'], 0,
    'It is cheap but needs constant vigilance.'],
  ['Eradication of a weed means:', ['Complete removal, including its seeds and vegetative parts', 'Reducing it below the economic threshold', 'Mowing once', 'Burning the crop'], 0,
    'It is rarely practical except for small, new infestations.'],
  ['A demerit of mechanical weeding (hand weeding, hoeing) is that it is:', ['Labour-intensive, slow and costly on large areas', 'Harmful to the environment', 'Likely to leave herbicide residues', 'Likely to cause herbicide resistance'], 0,
    'Its merit is that it leaves no chemical residue.'],
  ['A cultural method of weed control is:', ['Crop rotation, competitive varieties, optimum spacing and the stale seedbed technique', 'Spraying 2,4-D', 'Releasing grass carp', 'Using flame weeders'], 0,
    'It makes the crop more competitive than the weeds.'],
  ['The main merit of chemical weed control is that it is:', ['Quick and cost-effective over large areas', 'Always free of residues', 'Never linked to resistance', 'Harmless to all non-target organisms'], 0,
    'Its demerits include resistance, residues and environmental harm.'],
  ['*Phalaris minor* in the rice–wheat system of Punjab developed resistance to:', ['Isoproturon', 'Glyphosate', '2,4-D', 'Paraquat'], 0,
    'Resistance was first seen in the early 1990s; herbicide rotation followed.'],
  ['The Mexican beetle *Zygogramma bicolorata* is used for biological control of:', ['*Parthenium hysterophorus*', 'Water hyacinth', '*Lantana camara*', '*Cyperus rotundus*'], 0,
    'Biological control is slow and host-specific.'],
  ['The critical period of crop–weed competition is:', ['The stage when weed control gives the greatest yield benefit, often the first third of crop duration', 'The harvest stage', 'The seed storage period', 'The fallow period'], 0,
    'Weeding must be done in this window.'],
  ['The main advantage of integrated weed management (IWM) is that it:', ['Is sustainable and delays herbicide resistance', 'Uses only one method', 'Avoids all cultural practices', 'Always costs more'], 0,
    'It lowers the reliance on any single method.']
] },
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 3, pyq: 'IFoS-2018-A1-Q2c', q: [
  ['Runoff is:', ['The part of precipitation that flows over the land surface into streams', 'Water that infiltrates into the soil', 'Water lost as vapour', 'Groundwater'], 0,
    'It is the main agent of water erosion.'],
  ['Runoff increases with:', ['Higher rainfall intensity, steeper slopes and less vegetation cover', 'Higher infiltration capacity', 'Dense forest cover', 'Flat, sandy land'], 0,
    'Wet soil (high antecedent moisture) also increases runoff.'],
  ['The Universal Soil Loss Equation (USLE) is:', ['A = R × K × LS × C × P', 'A = R + K + L + S', 'A = C × I × A ÷ 360', 'A = ET × Kc'], 0,
    'It was developed by Wischmeier and Smith.'],
  ['In USLE, the factor R stands for:', ['Rainfall erosivity (EI₃₀)', 'Runoff coefficient', 'Soil resistance', 'Root density'], 0,
    'EI₃₀ is storm energy multiplied by the maximum 30-minute intensity.'],
  ['In USLE, K is:', ['Soil erodibility', 'Crop coefficient', 'Kinetic energy of rain', 'Potassium content'], 0,
    'Silty soils low in organic matter have high K values.'],
  ['LS in USLE stands for:', ['The slope length and steepness factor', 'Land slope in degrees only', 'Leaf surface', 'Loss of soil in tonnes'], 0,
    'Longer and steeper slopes give more soil loss.'],
  ['In USLE, the support-practice factor P equals one when:', ['No conservation practice (contouring, strip cropping, terracing) is used', 'Terracing is done', 'The land is forested', 'Mulch is applied'], 0,
    'C is the cover-management factor.'],
  ['The rational formula for peak runoff is Q = CIA/360, where:', ['C is the runoff coefficient, I the rainfall intensity (mm/h) and A the area (ha)', 'C is the crop factor, I infiltration and A altitude', 'C is clay, I irrigation and A aspect', 'C is carbon, I iron and A aluminium'], 0,
    'Q is in cubic metres per second.'],
  ['The usual progression of water erosion is:', ['Splash → sheet → rill → gully', 'Gully → rill → sheet → splash', 'Sheet → splash → gully → rill', 'Rill → splash → sheet → gully'], 0,
    'Sheet erosion is the least visible but removes fertile topsoil.'],
  ['The SCS curve number method is used to estimate:', ['Direct runoff from rainfall', 'Soil pH', 'Crop evapotranspiration', 'Nutrient uptake'], 0,
    'The curve number depends on soil group, land use and antecedent moisture.']
] },
{ p: 'A1', t: 'Environment, Organic & Natural Farming', w: 2, pyq: 'IFoS-2018-A1-Q2d', q: [
  ['Minamata disease is caused by:', ['Methylmercury', 'Cadmium', 'Lead', 'Arsenic'], 0,
    'It was first seen in Japan, from contaminated fish.'],
  ['Itai-itai disease is caused by:', ['Cadmium', 'Mercury', 'Fluoride', 'Nitrate'], 0,
    'It causes severe bone and kidney damage.'],
  ['Blue baby syndrome (methaemoglobinaemia) results from:', ['High nitrate in drinking water', 'Fluoride', 'Arsenic', 'Low iron'], 0,
    'The BIS limit for nitrate in drinking water is 45 mg/L.'],
  ['Fluorosis is caused by drinking water with fluoride above about:', ['1.5 mg/L', '0.01 mg/L', '100 mg/L', '0.1 mg/L'], 0,
    'It causes mottled teeth and skeletal deformities.'],
  ['Arsenic contamination of groundwater is a serious problem in:', ['West Bengal and the Ganga–Brahmaputra delta', 'Kerala coast', 'Ladakh', 'Goa'], 0,
    'It causes skin lesions and cancers (arsenicosis).'],
  ['Acid rain is caused mainly by:', ['Sulphur dioxide and nitrogen oxides', 'Carbon monoxide', 'Methane', 'Ozone'], 0,
    'It damages leaves, soils and freshwater life.'],
  ['Ground-level ozone harms crops by:', ['Damaging leaf cells, causing stippling and lower yields', 'Adding nitrogen', 'Increasing photosynthesis', 'Improving grain quality'], 0,
    'Peroxyacetyl nitrate (PAN) is another photochemical oxidant.'],
  ['The thinning of eggshells in fish-eating birds was caused by:', ['Biomagnification of DDT', 'Nitrate runoff', 'Acid rain', 'Noise'], 0,
    'Persistent pesticides concentrate up the food chain.'],
  ['Eutrophication of lakes, caused by nutrient runoff, leads to:', ['Algal blooms, oxygen depletion and fish kills', 'Clearer water', 'More dissolved oxygen', 'Fewer algae'], 0,
    'Phosphorus and nitrogen are the main culprits.'],
  ['Lichens are good indicators of:', ['Sulphur dioxide air pollution', 'Soil salinity', 'Heavy rainfall', 'Soil nitrogen'], 0,
    'They disappear from polluted cities.']
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: 'IFoS-2018-A1-Q3a', q: [
  ['Plants absorb nitrogen mainly as:', ['Nitrate (NO₃⁻) and ammonium (NH₄⁺)', 'N₂ gas', 'Urea only', 'Amino acids only'], 0,
    'Urea is first hydrolysed to ammonium in the soil.'],
  ['Phosphorus is absorbed mainly as:', ['H₂PO₄⁻ (and HPO₄²⁻)', 'PO₄³⁻ only', 'Organic P only', 'P₂O₅'], 0,
    'The dominant form depends on soil pH.'],
  ['Boron is taken up by plants mainly as:', ['Uncharged boric acid (H₃BO₃)', 'B³⁺', 'Borax crystals', 'BO₄⁵⁻'], 0,
    'Molybdenum is taken up as molybdate (MoO₄²⁻).'],
  ['Phosphorus availability in soil is highest at a pH of about:', ['6.0–7.0', '4.0', '9.0', '10.5'], 0,
    'It is fixed by Fe and Al in acid soils and by Ca in alkaline soils.'],
  ['Heavy phosphorus fertilisation can induce a deficiency of:', ['Zinc', 'Nitrogen', 'Potassium', 'Chlorine'], 0,
    'This P–Zn antagonism is common in rice and maize.'],
  ['Excess potassium can reduce the uptake of:', ['Magnesium (and calcium)', 'Phosphorus', 'Nitrogen', 'Boron'], 0,
    'Mulder’s chart shows such antagonisms and synergisms.'],
  ['The critical nutrient concentration is the tissue level:', ['Below which yield falls significantly (for example by 10%)', 'At which the plant dies', 'That is toxic', 'Found in the seed'], 0,
    'It is used in plant tissue analysis.'],
  ['DRIS (Diagnosis and Recommendation Integrated System) diagnoses nutrient status using:', ['Ratios between nutrients, such as N/P and N/K', 'Single nutrient concentrations only', 'Soil colour', 'Leaf area'], 0,
    'Ratios vary less with plant age than single concentrations do.'],
  ['The generally recommended NPK consumption ratio for India is:', ['4:2:1', '1:1:1', '10:1:1', '2:4:1'], 0,
    'Actual use is skewed towards nitrogen.'],
  ['The basic cation saturation ratio (BCSR) concept emphasises:', ['An ideal ratio of Ca, Mg and K on the soil exchange complex', 'Only soil pH', 'Only organic matter', 'Only nitrogen'], 0,
    'The concept is associated with Bear and Albrecht.']
] },
{ p: 'A1', t: 'Dryland Farming & Watershed Management', w: 3, pyq: 'IFoS-2018-A1-Q3b', q: [
  ['A contingency crop plan is:', ['A set of alternative crops, varieties and practices for aberrant weather', 'A fixed cropping calendar', 'An insurance policy', 'A fertiliser schedule'], 0,
    'It covers delayed monsoon, mid-season drought and early withdrawal.'],
  ['District agriculture contingency plans in India are prepared by:', ['CRIDA with ICAR institutes and state agricultural universities', 'IMD alone', 'NABARD', 'The Finance Ministry'], 0,
    'They are available for most districts.'],
  ['If the monsoon is delayed by three to four weeks in a dryland area, the plan usually recommends:', ['Switching to short-duration crops or varieties, e.g., pearl millet, horsegram or sunflower', 'Sowing long-duration cotton', 'Leaving the land fallow for the year', 'Sowing sugarcane'], 0,
    'Short-duration crops mature before the soil dries out.'],
  ['For a mid-season drought, recommended measures include:', ['Thinning, weeding, mulching and protective irrigation', 'Heavy nitrogen top-dressing', 'Deep ploughing', 'Adding more plants'], 0,
    'The aim is to reduce the crop’s water demand.'],
  ['If the monsoon withdraws early, farmers are advised to:', ['Give life-saving irrigation and harvest at physiological maturity', 'Delay harvest', 'Apply more nitrogen', 'Replant the crop'], 0,
    'Residual moisture can then be used for a rabi crop.'],
  ['Under a delayed monsoon, pearl millet can be raised by:', ['Transplanting seedlings from a nursery', 'Sowing only in October', 'Using rice seed', 'Growing it in water'], 0,
    'Transplanting saves several weeks of field time.'],
  ['A foliar spray used to help dryland crops recover from mid-season drought is:', ['2% urea or potassium nitrate', 'Common salt', 'Gypsum slurry', 'Lime'], 0,
    'It supplies nutrients when root uptake is poor.'],
  ['Real-time contingency plans use:', ['Monsoon forecasts and agromet advisories from IMD', 'Stock market data', 'Soil colour', 'Crop prices only'], 0,
    'Advisories are issued district-wise twice a week.'],
  ['Crops that grow on residual soil moisture after the monsoon include:', ['Chickpea and safflower', 'Rice', 'Jute', 'Sugarcane'], 0,
    'They are sown in rabi on stored moisture.'],
  ['Community seed banks support contingency planning by:', ['Keeping seed of alternative crops ready for resowing', 'Storing fertilisers', 'Storing pesticides', 'Selling land'], 0,
    'Seed availability is often the main bottleneck.']
] },
{ p: 'A1', t: 'Environment, Organic & Natural Farming', w: 3, pyq: 'IFoS-2018-A1-Q3c', q: [
  ['Greenhouse gases warm the Earth by:', ['Absorbing and re-emitting outgoing long-wave (infrared) radiation', 'Reflecting all sunlight', 'Absorbing ultraviolet only', 'Blocking visible light'], 0,
    'They are largely transparent to incoming short-wave radiation.'],
  ['Without the natural greenhouse effect, Earth’s mean surface temperature would be about:', ['−18 °C instead of about 15 °C', '50 °C', '0 °C', '30 °C'], 0,
    'Water vapour makes the largest contribution to the natural effect.'],
  ['The most important greenhouse gas emitted by human activities is:', ['Carbon dioxide', 'Water vapour', 'Ozone', 'Nitrogen'], 0,
    'Fossil fuels and land-use change are its main sources.'],
  ['Over 100 years, one tonne of methane warms the planet about how many times as much as one tonne of CO₂?', ['About 28 times', 'Once', 'About 300 times', 'About 23,000 times'], 0,
    'N₂O is about 273 times and SF₆ about 23,000 times (IPCC AR5–AR6).'],
  ['Flooded rice fields emit methane because:', ['Methanogenic archaea break down organic matter in the absence of oxygen', 'Rice plants produce it in photosynthesis', 'Fertiliser releases it', 'Water contains methane'], 0,
    'The gas escapes largely through the rice plant’s aerenchyma.'],
  ['The largest source of methane in Indian agriculture is:', ['Enteric fermentation in ruminant livestock', 'Tractors', 'Pesticides', 'Irrigation pumps'], 0,
    'Rice cultivation is the second largest.'],
  ['Nitrous oxide from agriculture comes mainly from:', ['Nitrification and denitrification of nitrogen fertilisers', 'Photosynthesis', 'Rice husk', 'Irrigation water'], 0,
    'Over-application of N makes the losses worse.'],
  ['Alternate wetting and drying (AWD) in rice mainly reduces:', ['Methane emissions and water use', 'Yield', 'Nitrogen uptake', 'Grain quality'], 0,
    'Direct-seeded rice also cuts methane emissions.'],
  ['Neem-coated urea reduces greenhouse emissions by:', ['Slowing nitrification, which lowers N₂O and nitrate losses', 'Releasing methane', 'Increasing volatilisation', 'Killing earthworms'], 0,
    'All urea in India has been neem-coated since 2015.'],
  ['The greenhouse gas with the highest global warming potential listed under the Kyoto Protocol is:', ['Sulphur hexafluoride (SF₆)', 'Methane', 'Carbon dioxide', 'Nitrous oxide'], 0,
    'It is used as an insulator in electrical switchgear.']
] },
{ p: 'A1', t: 'Weed Science', w: 2, pyq: 'IFoS-2018-A1-Q3d', q: [
  ['Water hyacinth (*Eichhornia crassipes*) is a:', ['Free-floating aquatic weed', 'Submerged weed', 'Marginal grass', 'Terrestrial parasite'], 0,
    'It is often called the world’s worst aquatic weed.'],
  ['*Hydrilla verticillata* is a:', ['Submerged aquatic weed', 'Free-floating weed', 'Emergent weed', 'Parasitic weed'], 0,
    'It clogs canals and reservoirs.'],
  ['*Typha* (cattail) and *Phragmites* are:', ['Emergent aquatic weeds', 'Submerged weeds', 'Free-floating weeds', 'Algae'], 0,
    'They root in mud and grow above the water.'],
  ['Water hyacinth is controlled biologically by:', ['*Neochetina eichhorniae* and *N. bruchi* weevils', '*Zygogramma bicolorata*', 'Grass carp', '*Cyrtobagous salviniae*'], 0,
    'The weevils feed on the leaves and petioles.'],
  ['*Salvinia molesta* is controlled biologically by the weevil:', ['*Cyrtobagous salviniae*', '*Neochetina bruchi*', '*Agasicles hygrophila*', '*Zygogramma bicolorata*'], 0,
    'It was a notable success in Kerala.'],
  ['Alligator weed (*Alternanthera philoxeroides*) is controlled by the flea beetle:', ['*Agasicles hygrophila*', '*Neochetina eichhorniae*', '*Cyrtobagous salviniae*', '*Zygogramma bicolorata*'], 0,
    'It grows both on land and in water.'],
  ['Grass carp (*Ctenopharyngodon idella*) is used to control:', ['Submerged aquatic weeds', 'Terrestrial weeds', 'Parasitic weeds', 'Insect pests'], 0,
    'It feeds heavily on soft submerged plants.'],
  ['The herbicide commonly used against water hyacinth is:', ['2,4-D', 'Atrazine', 'Isoproturon', 'Pendimethalin'], 0,
    'Glyphosate is used on emergent weeds.'],
  ['Aquatic weeds cause problems by:', ['Clogging canals, raising evaporation losses, depleting oxygen and harbouring mosquitoes', 'Improving water quality', 'Increasing fish yields', 'Reducing evaporation'], 0,
    'They also hamper navigation and hydropower.'],
  ['Harvested water hyacinth can be usefully turned into:', ['Compost, biogas, paper and handicrafts', 'Fuel oil directly', 'Cement', 'Glass'], 0,
    'Using it helps pay for mechanical removal.']
] },
{ p: 'A1', t: 'Crop Production', w: 3, pyq: 'IFoS-2018-A1-Q4a', q: [
  ['In India, pulses are mostly grown:', ['Under rainfed conditions on marginal lands', 'Under assured irrigation on the best lands', 'In greenhouses', 'Only in hills'], 0,
    'Moisture stress is therefore a major yield constraint.'],
  ['India is the world’s:', ['Largest producer, consumer and importer of pulses', 'Largest exporter of pulses', 'Smallest pulse producer', 'Largest producer of soybean'], 0,
    'Demand has outpaced domestic production.'],
  ['The pulse crop that contributes about half of India’s pulse production is:', ['Chickpea (gram)', 'Pigeonpea', 'Lentil', 'Mungbean'], 0,
    'Pigeonpea is second in importance.'],
  ['The most serious insect pest of chickpea and pigeonpea is:', ['Pod borer *Helicoverpa armigera*', 'Brown planthopper', 'Stem borer of rice', 'Pink bollworm'], 0,
    'It damages flowers and pods.'],
  ['Sterility mosaic disease of pigeonpea is transmitted by:', ['The eriophyid mite *Aceria cajani*', 'Whitefly', 'Aphids', 'Nematodes'], 0,
    'Affected plants produce no flowers or pods.'],
  ['Yellow mosaic disease of mungbean and urdbean is spread by:', ['The whitefly *Bemisia tabaci*', 'Thrips', 'Leafhoppers', 'Mites'], 0,
    'Resistant varieties are the main defence.'],
  ['Fusarium wilt is a major soil-borne disease of:', ['Chickpea and pigeonpea', 'Rice', 'Wheat', 'Sugarcane'], 0,
    'Resistant varieties and crop rotation help manage it.'],
  ['A physiological constraint on pulse yields is:', ['Indeterminate growth, heavy flower drop and a low harvest index', 'Very high harvest index', 'Excess nodulation', 'C₄ photosynthesis'], 0,
    'Breeding aims for determinate, compact plant types.'],
  ['The programme launched in 2007–08 that includes a pulses component is:', ['The National Food Security Mission', 'Operation Flood', 'The Green India Mission', 'Mission Indradhanush'], 0,
    'It aims to raise pulse area and productivity.'],
  ['The UN declared which year the International Year of Pulses?', ['2016', '2008', '2023', '2013'], 0,
    '2023 was the International Year of Millets.']
] },
{ p: 'A1', t: 'Plant Propagation & Micropropagation', w: 2, pyq: 'IFoS-2018-A1-Q4b', q: [
  ['Plant propagation means:', ['Multiplying plants by seed (sexual) or by vegetative parts (asexual)', 'Only sowing seeds', 'Only grafting', 'Harvesting crops'], 0,
    'Vegetative methods include cuttings, layering, grafting, budding and tissue culture.'],
  ['The main advantages of micropropagation are:', ['Rapid, year-round, true-to-type and disease-free multiplication in little space', 'Low cost and no skilled labour', 'Always new genetic variation', 'No need for a laboratory'], 0,
    'Its drawbacks are high cost and the risk of somaclonal variation.'],
  ['The most widely micropropagated plantation crop in India is:', ['Banana (e.g., Grand Naine)', 'Coconut', 'Rice', 'Wheat'], 0,
    'Tissue-culture banana gives uniform bunches and early harvest.'],
  ['Tissue-culture plants of small cardamom are valued because they are free of:', ['Katte (cardamom mosaic virus)', 'Bunchy top', 'Leaf curl', 'Grassy shoot'], 0,
    'Katte spreads through infected suckers.'],
  ['In oil palm, clones from somatic embryogenesis sometimes show the "mantled" abnormality, which is:', ['An epigenetic somaclonal variation that causes fruit abnormalities', 'A viral disease', 'A nutrient deficiency', 'An insect attack'], 0,
    'It is linked to loss of DNA methylation at the *Karma* transposon.'],
  ['The standard commercial propagation method for rubber is:', ['Bud grafting (brown or green budding) onto seedling rootstocks', 'Seed only', 'Tissue culture only', 'Air layering'], 0,
    'High-yielding clones are multiplied this way.'],
  ['Tea is commonly propagated commercially by:', ['Single-node leaf cuttings of selected clones', 'Tissue culture only', 'Grafting only', 'Bulbs'], 0,
    'Clonal tea gives uniform bushes.'],
  ['Coconut cannot easily be propagated vegetatively, so germplasm is often exchanged by:', ['Embryo culture', 'Stem cuttings', 'Grafting', 'Layering'], 0,
    'Embryos are cultured from the seed nut.'],
  ['Mass propagation of *Coffea arabica* by somatic embryogenesis is valuable because:', ['It multiplies elite hybrids that would not breed true from seed', 'Coffee has no seeds', 'It is cheaper than seed for all uses', 'Coffee cannot be grafted'], 0,
    'F₁ hybrids segregate if grown from seed.'],
  ['Meristem culture combined with thermotherapy is used to:', ['Eliminate viruses from planting material', 'Make haploids', 'Make polyploids', 'Produce seeds'], 0,
    'It is used in banana, potato and sugarcane.']
] },
{ p: 'A1', t: 'Soil Genesis, Classification & Properties', w: 3, pyq: 'IFoS-2018-A1-Q4c', q: [
  ['Jenny’s (1941) soil-forming equation is:', ['S = f(cl, o, r, p, t) — climate, organisms, relief, parent material and time', 'S = R × K × LS × C × P', 'S = ET × Kc', 'S = pH + EC'], 0,
    'The five factors act together to form soil.'],
  ['The father of pedology, who first treated soil as an independent natural body, was:', ['V. V. Dokuchaev', 'Hans Jenny', 'Justus von Liebig', 'C. F. Marbut'], 0,
    'He worked on the Russian chernozems.'],
  ['The "active" factors of soil formation are:', ['Climate and organisms', 'Parent material and time', 'Relief and time', 'Parent material and relief'], 0,
    'Parent material, relief and time are passive factors.'],
  ['Laterisation occurs in:', ['Hot, humid tropics, where silica is leached and Fe and Al oxides accumulate', 'Cold, humid regions', 'Deserts', 'Waterlogged soils only'], 0,
    'Laterites are common in Kerala and the Western Ghats.'],
  ['Podzolisation occurs mainly under:', ['Cool, humid climates with acid litter (e.g., conifers), leaching Fe and Al to form an E horizon', 'Hot deserts', 'Grasslands of semi-arid zones', 'Mangroves'], 0,
    'Chelating organic acids move iron and aluminium down the profile.'],
  ['Calcification is typical of:', ['Semi-arid and arid regions, where CaCO₃ accumulates in the subsoil', 'Humid tropics', 'Waterlogged soils', 'Alpine meadows'], 0,
    'Low rainfall cannot leach the carbonates.'],
  ['Gleisation (gleying) produces grey-blue mottled soils because of:', ['Prolonged waterlogging and reduction of iron', 'Excess lime', 'High temperature', 'Wind erosion'], 0,
    'Reduced ferrous iron gives the grey colour.'],
  ['A sequence of different soils from hilltop to valley on the same parent material is called a:', ['Catena (toposequence)', 'Chronosequence', 'Lithosequence', 'Climosequence'], 0,
    'Milne introduced the term in 1935 in East Africa.'],
  ['Simonson’s generalised theory explains soil formation through:', ['Additions, removals, transfers and transformations', 'Weathering only', 'Erosion only', 'Deposition only'], 0,
    'Together these processes create soil horizons.'],
  ['The Vertisols (black cotton soils) of the Deccan developed mainly from:', ['Basalt of the Deccan Traps', 'Granite', 'Alluvium', 'Sandstone'], 0,
    'They are rich in montmorillonite clay, which swells and cracks.']
] },
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 3, pyq: 'IFoS-2018-A1-Q4d', q: [
  ['On steep hill slopes (roughly 16–33%) cultivated for crops, the key conservation measure is:', ['Bench terracing', 'Contour bunding', 'Deep ploughing up and down the slope', 'Burning vegetation'], 0,
    'Terraces convert the slope into a series of level steps.'],
  ['Contour bunding is suited to:', ['Gentle slopes (up to about 6%) in low-rainfall areas', 'Very steep slopes above 50%', 'Flat irrigated land', 'Waterlogged soils'], 0,
    'Graded bunds are used where rainfall is higher.'],
  ['Staggered contour trenches on steep slopes are mainly used for:', ['Afforestation and harvesting runoff', 'Rice paddies', 'Drainage of wetlands', 'Salt leaching'], 0,
    'Seedlings are planted on the trench berms.'],
  ['Gullies in hilly areas are stabilised by:', ['Check dams — brushwood, loose-boulder or gabion structures', 'Deep ploughing', 'Removing all vegetation', 'Urea application'], 0,
    'They slow the flow and trap sediment.'],
  ['A grass widely used as a vegetative barrier for soil conservation is:', ['Vetiver (*Chrysopogon zizanioides*)', '*Parthenium*', 'Water hyacinth', '*Lantana*'], 0,
    'Its deep, dense roots hold soil.'],
  ['Shifting cultivation (jhum) in north-east India causes:', ['Severe soil erosion and fertility loss when fallow periods are short', 'Soil improvement', 'No erosion', 'Salinity'], 0,
    'Fallow cycles have shortened from 15–20 years to 3–5 years.'],
  ['Sloping Agricultural Land Technology (SALT) involves:', ['Hedgerows of nitrogen-fixing shrubs on the contour with crops between them', 'Terracing with concrete', 'Monocropping up and down the slope', 'Burning the hedgerows'], 0,
    'The hedgerows trap soil and supply green manure.'],
  ['Half-moon terraces on hill slopes are made for:', ['Individual fruit trees', 'Rice paddies', 'Roads', 'Fish ponds'], 0,
    'They collect water around each tree.'],
  ['Grassed waterways are used to:', ['Carry excess runoff safely off fields without causing erosion', 'Grow rice', 'Store water permanently', 'Leach salts'], 0,
    'They are often built at the outlets of terraces.'],
  ['Land with very steep slopes (e.g., above about 33%) is best put under:', ['Forest or permanent pasture, not cultivation', 'Intensive row crops', 'Rice paddies', 'Sugarcane'], 0,
    'Land capability classes VI–VII suit grazing and forestry.']
] }
);
