/* PYQ-linked MCQs — IFoS 2018 Botany Paper II (verbatim PYQs). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B2', t: 'Cell Biology', w: 3, pyq: 'IFoS-2018-B2-Q1a', q: [
  ['The nucleosome core particle consists of:', ['About 147 bp of DNA wrapped around a histone octamer of H2A, H2B, H3 and H4 (two each)', 'DNA wrapped around H1 alone', 'RNA wrapped around histones', 'A tetramer of H1'], 0,
    'The DNA makes about 1.65 left-handed turns around the octamer.'],
  ['Histone H1 (the linker histone):', ['Binds linker DNA where it enters and leaves the nucleosome, forming a chromatosome', 'Is part of the octamer core', 'Is absent from plants', 'Binds RNA only'], 0,
    'The chromatosome holds about 166 bp of DNA.'],
  ['The "beads-on-a-string" structure seen under the electron microscope is the:', ['10 nm fibre', '30 nm fibre', '300 nm loop', 'Metaphase chromatid'], 0,
    'The beads are nucleosomes and the string is linker DNA.'],
  ['In the solenoid model of the 30 nm fibre, each turn has about:', ['Six nucleosomes', 'One nucleosome', 'Sixty nucleosomes', 'No nucleosomes'], 0,
    'H1 helps stabilise the 30 nm fibre.'],
  ['Histones bind DNA tightly because they are rich in:', ['Lysine and arginine, which are positively charged', 'Aspartate and glutamate', 'Cysteine', 'Tryptophan'], 0,
    'Their positive charges neutralise the phosphate backbone of DNA.'],
  ['The nucleosome model was proposed in 1974 by:', ['Roger Kornberg', 'James Watson', 'Robert Feulgen', 'Walther Flemming'], 0,
    'Ada and Donald Olins imaged the "beads" in the same period.'],
  ['Heterochromatin, compared with euchromatin, is:', ['More condensed, largely transcriptionally inactive and late-replicating', 'Less condensed and highly active', 'Free of histones', 'Found only in bacteria'], 0,
    'Constitutive heterochromatin surrounds centromeres and telomeres.'],
  ['Acetylation of histone tails by histone acetyltransferases generally:', ['Loosens chromatin and activates transcription', 'Condenses chromatin and silences genes', 'Degrades DNA', 'Removes the histones'], 0,
    'Histone deacetylases (HDACs) reverse this and repress genes.'],
  ['Higher-order chromatin loops are anchored to the nuclear scaffold at:', ['Scaffold or matrix attachment regions (SARs/MARs)', 'Telomeres only', 'Ribosomes', 'Plasmodesmata'], 0,
    'Each loop is roughly 40–90 kb long.'],
  ['Overall, DNA in a metaphase chromosome is compacted roughly:', ['10,000-fold', 'Seven-fold', 'Forty-fold', 'Two-fold'], 0,
    'Nucleosomes give about seven-fold and the 30 nm fibre about forty-fold compaction.']
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 2, pyq: 'IFoS-2018-B2-Q1b', q: [
  ['Chloroplast dimorphism is characteristic of:', ['C₄ plants', 'C₃ plants', 'All algae', 'CAM plants only'], 0,
    'The mesophyll and bundle sheath chloroplasts differ in structure and function.'],
  ['In NADP-ME type C₄ plants such as maize and sugarcane, bundle sheath chloroplasts are:', ['Agranal or poorly granal, with large starch grains', 'Richly granal', 'Absent', 'Identical to mesophyll chloroplasts'], 0,
    'Mesophyll chloroplasts have well-developed grana.'],
  ['The wreath-like layer of bundle sheath cells around veins in C₄ leaves is called:', ['Kranz anatomy', 'Palisade tissue', 'Spongy tissue', 'Bulliform tissue'], 0,
    '"Kranz" is German for wreath.'],
  ['In C₄ leaves, PEP carboxylase is located in the:', ['Cytosol of mesophyll cells', 'Bundle sheath chloroplasts', 'Mitochondria', 'Vacuole'], 0,
    'It fixes HCO₃⁻ into oxaloacetate.'],
  ['In C₄ leaves, Rubisco is concentrated in the:', ['Bundle sheath chloroplasts', 'Mesophyll cytosol', 'Epidermis', 'Xylem'], 0,
    'There, CO₂ released from C₄ acids is refixed.'],
  ['Bundle sheath chloroplasts of NADP-ME species produce little O₂ because they:', ['Are deficient in photosystem II', 'Lack photosystem I', 'Lack chlorophyll', 'Lack Rubisco'], 0,
    'Low O₂ further suppresses photorespiration.'],
  ['Agranal bundle sheath chloroplasts get most of their NADPH from:', ['Decarboxylation of malate by NADP-malic enzyme', 'Water splitting', 'The glyoxylate cycle', 'Nitrate reduction'], 0,
    'Malate from the mesophyll carries both CO₂ and reducing power.'],
  ['In NADP-ME grasses such as maize, bundle sheath chloroplasts sit:', ['Centrifugally, towards the outer wall', 'Centripetally, towards the vascular bundle', 'Randomly', 'Only in the mesophyll'], 0,
    'NAD-ME types have centripetal, granal bundle sheath chloroplasts.'],
  ['Single-cell C₄ plants such as *Bienertia* and *Suaeda aralocaspica* show:', ['Two kinds of chloroplasts in separate parts of the same cell', 'No chloroplasts', 'Kranz anatomy', 'Only C₃ chloroplasts'], 0,
    'They achieve C₄ photosynthesis without Kranz anatomy.'],
  ['C₄ chloroplast dimorphism and Kranz anatomy together raise the CO₂ level around Rubisco to about:', ['Ten times the atmospheric level', 'Half the atmospheric level', 'The same as air', 'Zero'], 0,
    'This all but eliminates photorespiration.']
] },
{ p: 'B2', t: 'Molecular Biology', w: 3, pyq: 'IFoS-2018-B2-Q1c', q: [
  ['The 5′ cap of eukaryotic mRNA is:', ['7-methylguanosine joined by a 5′–5′ triphosphate bridge', 'A poly(A) stretch', 'A CCA sequence', 'A lariat'], 0,
    'It is added while transcription is still going on.'],
  ['The 5′ cap:', ['Protects mRNA from 5′ exonucleases and helps nuclear export and ribosome binding', 'Signals transcription termination', 'Codes for methionine', 'Removes introns'], 0,
    'The cap-binding protein eIF4E recruits the ribosome.'],
  ['The poly(A) tail is added:', ['By poly(A) polymerase after cleavage downstream of the AAUAAA signal', 'By RNA polymerase II during transcription', 'In the cytoplasm only', 'By DNA ligase'], 0,
    'It improves mRNA stability and translation.'],
  ['Introns are removed from nuclear pre-mRNA by:', ['The spliceosome, made of snRNPs (U1, U2, U4, U5, U6) and proteins', 'Ribosomes', 'DNA polymerase', 'Restriction enzymes'], 0,
    'U1 recognises the 5′ splice site and U2 the branch point.'],
  ['Most nuclear introns begin and end with:', ['GU at the 5′ end and AG at the 3′ end', 'AG at the 5′ end and GU at the 3′ end', 'AUG and UAA', 'TATA and CAAT'], 0,
    'This is the GU–AG rule.'],
  ['During splicing, the intron is released as:', ['A lariat, joined at a branch-point adenosine', 'A linear fragment', 'A circle joined at a cytosine', 'Double-stranded RNA'], 0,
    'The 2′-OH of the branch-point A attacks the 5′ splice site.'],
  ['Alternative splicing allows:', ['One gene to produce several different proteins', 'Two genes to make one protein', 'DNA to be copied', 'Ribosomes to be made'], 0,
    'Exons can be included or skipped.'],
  ['RNA editing in plant mitochondria and chloroplasts most often changes:', ['C to U', 'A to G', 'U to C only', 'G to T'], 0,
    'It often restores conserved amino acids in the encoded proteins.'],
  ['Self-splicing group I introns, as in *Tetrahymena* rRNA, showed that:', ['RNA can act as an enzyme (ribozyme)', 'Proteins are always required for splicing', 'DNA can splice itself', 'Introns are never removed'], 0,
    'Thomas Cech shared the 1989 Nobel Prize for this.'],
  ['Most bacterial mRNAs, compared with eukaryotic mRNAs:', ['Have no cap and no introns, and are translated while being transcribed', 'Have a cap and a poly(A) tail', 'Are spliced in the nucleus', 'Are exported to the cytoplasm'], 0,
    'Bacteria have no nuclear envelope to separate the two processes.']
] },
{ p: 'B2', t: 'Cell Biology', w: 2, pyq: 'IFoS-2018-B2-Q1d', q: [
  ['The signal hypothesis for protein targeting to the ER was proposed by:', ['Günter Blobel', 'George Palade', 'Christian de Duve', 'Albert Claude'], 0,
    'He received the 1999 Nobel Prize.'],
  ['A protein is directed to the ER by:', ['An N-terminal hydrophobic signal sequence recognised by the signal recognition particle (SRP)', 'A C-terminal KDEL sequence', 'A nuclear localisation signal', 'A mannose-6-phosphate tag'], 0,
    'SRP pauses translation until the ribosome docks on the ER.'],
  ['The ribosome–nascent chain complex docks on the ER membrane at:', ['The SRP receptor and the Sec61 translocon', 'The nuclear pore', 'The Golgi', 'The plasma membrane'], 0,
    'The polypeptide passes through the Sec61 channel.'],
  ['The signal peptide is removed in the ER lumen by:', ['Signal peptidase', 'Trypsin', 'Pepsin', 'The proteasome'], 0,
    'Cleavage releases the mature protein into the lumen.'],
  ['N-linked glycosylation in the ER attaches a preformed oligosaccharide to:', ['Asparagine in an Asn-X-Ser/Thr sequence', 'Serine only', 'Lysine', 'Cysteine'], 0,
    'The oligosaccharide is transferred from a dolichol carrier.'],
  ['Soluble ER-resident proteins in plants are retained by the C-terminal signal:', ['HDEL or KDEL', 'SKL', 'PKKKRKV', 'KKXX on the lumen side'], 0,
    'Escaped proteins are returned from the Golgi.'],
  ['The ER chaperone BiP is a member of the:', ['HSP70 family', 'Actin family', 'Tubulin family', 'Histone family'], 0,
    'Calnexin and calreticulin act on glycoproteins.'],
  ['Misfolded proteins in the ER are:', ['Sent back to the cytosol and degraded by proteasomes (ERAD)', 'Always secreted', 'Stored for ever', 'Sent to the nucleus'], 0,
    'Too many trigger the unfolded protein response (UPR).'],
  ['In a multi-pass membrane protein, a stop-transfer sequence:', ['Halts translocation and anchors that segment in the ER membrane', 'Ends translation', 'Signals nuclear import', 'Cleaves the protein'], 0,
    'Alternating start- and stop-transfer sequences produce several membrane spans.'],
  ['Proteins made on free cytosolic ribosomes are targeted to:', ['The cytosol, nucleus, mitochondria, chloroplasts and peroxisomes', 'The ER lumen', 'The Golgi', 'The cell exterior'], 0,
    'Import into these organelles happens after translation.']
] },
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 2, pyq: 'IFoS-2018-B2-Q1e', q: [
  ['The probability of any event lies:', ['Between zero and one, inclusive', 'Between −1 and +1', 'Between one and ten', 'Above one'], 0,
    'An impossible event has probability zero; a certain one has probability one.'],
  ['For a set of mutually exclusive and exhaustive outcomes, the probabilities add up to:', ['One', 'Zero', 'Half', 'Infinity'], 0,
    'One of the outcomes must occur.'],
  ['For mutually exclusive events A and B, the probability of A or B is:', ['P(A) + P(B)', 'P(A) × P(B)', 'P(A) − P(B)', 'P(A) ÷ P(B)'], 0,
    'This is the addition rule.'],
  ['For independent events A and B, the probability of both occurring is:', ['P(A) × P(B)', 'P(A) + P(B)', 'P(A) − P(B)', 'Always one'], 0,
    'This is the multiplication (product) rule.'],
  ['In the cross *Aa* × *Aa*, the probability of an *aa* offspring is:', ['1/4', '1/2', '3/4', '1/8'], 0,
    'Each parent gives *a* with a probability of 1/2, and 1/2 × 1/2 = 1/4.'],
  ['In the cross *AaBb* × *AaBb* (independent genes), the probability of an *aabb* offspring is:', ['1/16', '1/4', '9/16', '3/16'], 0,
    '1/4 × 1/4 = 1/16.'],
  ['The probability of exactly two girls among three children is:', ['3/8', '1/8', '1/2', '1/4'], 0,
    'Binomial: 3C2 × (1/2)² × (1/2) = 3/8.'],
  ['The probability that two children are both boys is:', ['1/4', '1/2', '3/4', '1/8'], 0,
    'The births are independent: 1/2 × 1/2.'],
  ['In genetics and breeding, probability is used mainly to:', ['Predict the outcomes of crosses and test whether observed ratios fit expectations', 'Measure plant height', 'Name species', 'Count chromosomes directly'], 0,
    'It underlies the chi-square test and sampling theory.'],
  ['The chi-square test in genetics compares:', ['Observed frequencies with expected frequencies', 'Two means', 'Two variances', 'Correlation between traits'], 0,
    'A small χ² value means the data fit the expected ratio.']
] },
{ p: 'B2', t: 'Cell Biology', w: 3, pyq: 'IFoS-2018-B2-Q2a', q: [
  ['Cyclin-dependent kinases (CDKs) are active only when:', ['Bound to a cyclin (and suitably phosphorylated)', 'Free of cyclins', 'Bound to DNA', 'Degraded'], 0,
    'Cyclin levels rise and fall through the cycle; CDK levels stay fairly constant.'],
  ['M-phase promoting factor (MPF) consists of:', ['A mitotic cyclin (cyclin B) with CDK1', 'Cyclin D with CDK4', 'p53 with p21', 'Tubulin with actin'], 0,
    'MPF was first detected in frog oocytes.'],
  ['In plants, the G1/S transition is driven by:', ['D-type cyclins with CDKA phosphorylating the RBR protein, which releases E2F', 'Cyclin B with CDKB degrading E2F', 'Auxin alone', 'Ethylene'], 0,
    'E2F then switches on the genes for DNA replication.'],
  ['The restriction point (START in yeast) is the:', ['Commitment point in late G1 after which the cell completes the cycle', 'Start of mitosis', 'End of cytokinesis', 'Beginning of G0'], 0,
    'It depends on growth signals and cell size.'],
  ['Exit from mitosis requires:', ['Degradation of mitotic cyclins by the anaphase-promoting complex (APC/C)', 'Synthesis of more cyclin B', 'Inactivation of the proteasome', 'DNA replication'], 0,
    'APC/C tags cyclins with ubiquitin.'],
  ['Wee1 and Cdc25 regulate CDK1 by:', ['Wee1 adding inhibitory phosphates and Cdc25 removing them', 'Both activating it', 'Both degrading cyclins', 'Wee1 activating and Cdc25 inhibiting it'], 0,
    'Cdc25 dephosphorylation triggers entry into mitosis.'],
  ['The spindle assembly checkpoint delays anaphase until:', ['All kinetochores are attached to spindle microtubules', 'DNA is replicated', 'Cyclins are made', 'The nuclear envelope reforms'], 0,
    'It inhibits APC/C–Cdc20.'],
  ['CDK inhibitors in plants include:', ['KRP/ICK proteins', 'Histones', 'Auxins', 'Expansins'], 0,
    'They correspond to p21/p27 in animals.'],
  ['Plant-specific B-type CDKs (CDKB) are mainly active during:', ['The G2/M transition', 'G1', 'G0', 'The S phase only'], 0,
    'They are unique to plants.'],
  ['The 2001 Nobel Prize for discovering key regulators of the cell cycle went to:', ['Hartwell, Hunt and Nurse', 'Watson, Crick and Wilkins', 'Blackburn, Greider and Szostak', 'Kornberg alone'], 0,
    'Hunt discovered cyclins; Nurse identified CDK1 (cdc2).']
] },
{ p: 'B2', t: 'Cell Biology', w: 2, pyq: 'IFoS-2018-B2-Q2b', q: [
  ['A uniporter carries:', ['A single solute in one direction', 'Two solutes in the same direction', 'Two solutes in opposite directions', 'Water only'], 0,
    'An example is the glucose transporter GLUT1.'],
  ['A symporter carries:', ['Two solutes in the same direction', 'One solute only', 'Two solutes in opposite directions', 'Only ions out of the cell'], 0,
    'The H⁺/sucrose symporter loads sucrose into the phloem.'],
  ['An antiporter carries:', ['Two solutes in opposite directions', 'Two solutes in the same direction', 'One solute', 'Proteins'], 0,
    'The Na⁺/H⁺ antiporter SOS1 pumps Na⁺ out of root cells.'],
  ['Co-transport by symporters and antiporters in plants is powered mainly by:', ['The proton-motive force from the plasma-membrane P-type H⁺-ATPase', 'Direct ATP hydrolysis by each carrier', 'Light alone', 'Gravity'], 0,
    'This is secondary active transport.'],
  ['On the plant vacuole membrane (tonoplast), the primary proton pumps are:', ['The V-type H⁺-ATPase and the H⁺-pyrophosphatase', 'The P-type H⁺-ATPase only', 'The Na⁺/K⁺-ATPase', 'Aquaporins'], 0,
    'Antiporters such as NHX then load Na⁺ into the vacuole.'],
  ['Carrier-mediated transport differs from simple diffusion in showing:', ['Saturation kinetics (Km, Vmax) and specificity', 'A linear rise with concentration', 'No specificity', 'No need for membrane proteins'], 0,
    'Carriers can be competitively inhibited.'],
  ['Compared with channels, carriers:', ['Move far fewer molecules per second, because each cycle involves a change in shape', 'Are much faster', 'Carry only water', 'Need no energy for any transport'], 0,
    'Channels can pass millions of ions per second.'],
  ['Nitrate is taken up by root cells mainly through:', ['H⁺/NO₃⁻ symport', 'A uniporter driven by ATP', 'Antiport with sucrose', 'Endocytosis'], 0,
    'Two protons enter with each nitrate ion.'],
  ['The Na⁺/K⁺-ATPase of animal cells is:', ['A primary active antiporter (3 Na⁺ out, 2 K⁺ in per ATP)', 'A uniporter', 'A symporter', 'A channel'], 0,
    'It uses ATP directly.'],
  ['Co-transport means:', ['The coupled movement of two solutes by one carrier (symport or antiport)', 'Movement through an open channel', 'Endocytosis', 'Diffusion through the lipid bilayer'], 0,
    'The downhill movement of one solute drives the uphill movement of the other.']
] },
{ p: 'B2', t: 'Genetics', w: 3, pyq: 'IFoS-2018-B2-Q3a', q: [
  ['Crossing over takes place at:', ['Pachytene of prophase I, between non-sister chromatids', 'Leptotene, between sister chromatids', 'Anaphase II', 'Interphase'], 0,
    'Chiasmata become visible at diplotene.'],
  ['Synapsis of homologous chromosomes is mediated by:', ['The synaptonemal complex', 'The centromere', 'The spindle', 'The nucleolus'], 0,
    'It forms during zygotene.'],
  ['Meiotic recombination begins with double-strand breaks made by:', ['Spo11', 'DNA ligase', 'Topoisomerase I', 'RNA polymerase'], 0,
    'Break repair gives crossovers or non-crossovers.'],
  ['The four-stranded crossover intermediate proposed in 1964 is the:', ['Holliday junction', 'Okazaki fragment', 'Replication fork', 'Lariat'], 0,
    'Its resolution decides whether flanking markers recombine.'],
  ['Linkage was first reported in sweet pea by:', ['Bateson and Punnett', 'Morgan and Sturtevant', 'Mendel', 'Beadle and Tatum'], 0,
    'They called it "coupling and repulsion".'],
  ['One map unit (centimorgan) equals:', ['1% recombination frequency', '50% recombination frequency', '1 kb of DNA', '1 chromosome'], 0,
    'Sturtevant made the first linkage map (*Drosophila*) in 1913.'],
  ['The maximum recombination frequency between two genes is:', ['50%', '100%', '25%', '75%'], 0,
    'Unlinked genes also give 50%, so the two cases look the same.'],
  ['In a three-point test cross, the middle gene is identified from the:', ['Double-crossover classes, which are the rarest', 'Parental classes, which are the commonest', 'Single-crossover classes only', 'Total number of progeny'], 0,
    'The gene that differs in the double crossovers is the middle one.'],
  ['Interference is calculated as:', ['1 − coefficient of coincidence', 'Coefficient of coincidence + 1', 'Recombination frequency × 2', 'Map distance ÷ 100'], 0,
    'Coincidence = observed ÷ expected double crossovers.'],
  ['For widely separated genes, recombination frequency underestimates map distance because:', ['Double (even-numbered) crossovers go undetected', 'Crossing over stops', 'Chiasmata are absent', 'Linkage is complete'], 0,
    'Mapping functions such as Haldane’s correct for this.']
] },
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 3, pyq: 'IFoS-2018-B2-Q3b', q: [
  ['Mass selection involves:', ['Selecting plants by phenotype and bulking their seed for the next generation', 'Testing progeny rows of single plants', 'Crossing two inbreds', 'Backcrossing'], 0,
    'It is the oldest method, used in both self- and cross-pollinated crops.'],
  ['The pure-line theory came from Johannsen’s work (1903) on:', ['Beans (*Phaseolus vulgaris*)', 'Maize', 'Wheat', 'Peas'], 0,
    'Selection within a pure line is ineffective, because its variation is environmental.'],
  ['In the pedigree method:', ['Records of ancestry are kept and single plants are selected from F₂ onwards', 'F₂–F₅ are grown in bulk without selection', 'The F₁ is backcrossed repeatedly', 'Only mutants are used'], 0,
    'It is the most widely used method for self-pollinated crops.'],
  ['In the bulk method:', ['Segregating generations are grown in bulk and selection is delayed', 'Each plant’s progeny is recorded', 'A single trait is transferred', 'Hybrids are made every year'], 0,
    'Natural selection can act during the bulk generations.'],
  ['The backcross method is best for:', ['Transferring one or a few traits (e.g., disease resistance) into an elite variety', 'Creating new polyploids', 'Improving quantitative traits in general', 'Making synthetic varieties'], 0,
    'The elite variety is the recurrent parent.'],
  ['Single seed descent (SSD):', ['Advances generations quickly by keeping one seed per plant', 'Selects on yield in F₂', 'Uses mutagens', 'Needs cytoplasmic male sterility'], 0,
    'It suits off-season nurseries and rapid generation advance.'],
  ['The term "heterosis" was coined by:', ['G. H. Shull (1914)', 'Charles Darwin', 'R. A. Fisher', 'N. I. Vavilov'], 0,
    'Shull also developed the inbred–hybrid method in maize.'],
  ['Heterobeltiosis is the superiority of the F₁ over:', ['The better parent', 'The mid-parent value', 'A standard check variety', 'The worse parent'], 0,
    'Superiority over a check variety is standard (economic) heterosis.'],
  ['The dominance hypothesis of heterosis says that hybrid vigour comes from:', ['Masking of harmful recessive alleles of each parent by dominant alleles of the other', 'Heterozygotes being superior at a single locus', 'Cytoplasmic effects only', 'Polyploidy'], 0,
    'The overdominance hypothesis credits heterozygote superiority itself.'],
  ['The three-line system of hybrid seed production uses:', ['A cytoplasmic male sterile A-line, a maintainer B-line and a restorer R-line', 'Three pure lines crossed together', 'Three chemical sprays', 'Three generations of selfing'], 0,
    'It is used in rice, sorghum, pearl millet and sunflower.']
] },
{ p: 'B2', t: 'Biotechnology & GM Crops', w: 3, pyq: 'IFoS-2018-B2-Q4a', q: [
  ['Murashige’s stages of micropropagation run:', ['Stage 0 mother-plant preparation → I establishment → II multiplication → III rooting → IV acclimatisation', 'I rooting → II establishment → III hardening', 'Hardening → rooting → multiplication', 'Callus → protoplast → seed'], 0,
    'Each stage has its own medium and conditions.'],
  ['Stage I (establishment) aims to:', ['Obtain an aseptic, growing culture after surface sterilisation of the explant', 'Root the shoots', 'Harden the plants', 'Multiply shoots rapidly'], 0,
    'Sodium hypochlorite or mercuric chloride is used for sterilisation.'],
  ['Stage II (multiplication) usually uses a medium rich in:', ['Cytokinin (e.g., BAP) for axillary shoot proliferation', 'Auxin alone for rooting', 'Abscisic acid', 'Ethylene'], 0,
    'Shoots are subcultured every few weeks.'],
  ['Stage III (rooting) usually uses:', ['Auxin such as IBA or NAA with little or no cytokinin', 'High cytokinin', 'Gibberellin only', 'No sugar and no hormones'], 0,
    'Rooted plantlets are then ready for transfer.'],
  ['Stage IV (acclimatisation or hardening) is needed because in vitro plantlets have:', ['Poor cuticle and poorly functioning stomata', 'Too much chlorophyll', 'Thick bark', 'Deep roots'], 0,
    'Humidity is lowered gradually in the greenhouse.'],
  ['Hyperhydricity (vitrification) in cultures means:', ['Glassy, water-soaked, brittle shoots', 'Contamination by fungi', 'Browning by phenolics', 'Rapid rooting'], 0,
    'Lowering humidity or cytokinin helps prevent it.'],
  ['Browning of explants, caused by oxidised phenolics, is reduced by:', ['Activated charcoal, ascorbic acid or PVP', 'More light', 'Higher temperature', 'More sucrose'], 0,
    'It is common in woody species.'],
  ['The micropropagation route least likely to cause somaclonal variation is:', ['Axillary shoot proliferation', 'Indirect organogenesis through callus', 'Long-term cell suspension', 'Protoplast culture'], 0,
    'A callus phase increases genetic instability.'],
  ['Meristem-tip culture is used mainly to:', ['Produce virus-free plants', 'Produce haploids', 'Induce polyploidy', 'Produce hybrids'], 0,
    'Morel and Martin (1952) first freed dahlia of viruses this way.'],
  ['In India, virus indexing and quality of commercial tissue-culture plants are certified under:', ['The National Certification System for Tissue Culture Raised Plants (NCS-TCP), DBT', 'The Seeds Act only', 'FSSAI', 'The Bureau of Indian Standards only'], 0,
    'Banana, potato and sugarcane are major commercial crops.']
] },
{ p: 'B2', t: 'Molecular Biology', w: 3, pyq: 'IFoS-2018-B2-Q4b', q: [
  ['In prokaryotes, the ribosome finds the start codon by base-pairing between:', ['The Shine–Dalgarno sequence and the 3′ end of 16S rRNA', 'The 5′ cap and 18S rRNA', 'The poly(A) tail and 23S rRNA', 'The TATA box and 5S rRNA'], 0,
    'The Shine–Dalgarno sequence (AGGAGG) lies a few bases upstream of AUG.'],
  ['The initiator tRNA in bacteria carries:', ['N-formylmethionine (fMet)', 'Unformylated methionine', 'Valine', 'Leucine'], 0,
    'Eukaryotes use a special Met-tRNAi that is not formylated.'],
  ['IF2 in bacterial translation initiation:', ['Binds GTP and brings fMet-tRNA to the 30S subunit', 'Blocks the A site', 'Keeps the 30S and 50S subunits apart', 'Releases the peptide'], 0,
    'IF3 keeps the subunits apart and IF1 blocks the A site.'],
  ['At the start of translation, the initiator tRNA sits in the:', ['P site', 'A site', 'E site', 'Outside the ribosome'], 0,
    'All other aminoacyl-tRNAs enter at the A site.'],
  ['The 70S initiation complex forms when:', ['The 50S subunit joins the 30S complex and IF2 hydrolyses its GTP', 'Two 30S subunits join', 'mRNA is capped', 'The poly(A) tail binds'], 0,
    'The initiation factors are then released.'],
  ['In eukaryotes, the start codon is usually found by:', ['The 43S complex binding the 5′ cap and scanning to the first AUG in a good context', 'A Shine–Dalgarno sequence', 'Random binding', 'The poly(A) tail alone'], 0,
    'Kozak described this scanning model.'],
  ['The eukaryotic factor that binds the mRNA 5′ cap is:', ['eIF4E', 'eIF2', 'IF3', 'EF-Tu'], 0,
    'It is part of the eIF4F complex.'],
  ['eIF2 brings Met-tRNAi to the small subunit, and its phosphorylation:', ['Reduces global translation under stress', 'Increases translation', 'Adds the 5′ cap', 'Removes introns'], 0,
    'This is a major control point of eukaryotic translation.'],
  ['Bacterial mRNAs can be translated from several start sites because they are often:', ['Polycistronic, with a Shine–Dalgarno sequence before each gene', 'Monocistronic and capped', 'Always spliced', 'Single-stranded DNA'], 0,
    'Most eukaryotic mRNAs are monocistronic.'],
  ['Cap-independent initiation in some viral and cellular mRNAs uses:', ['Internal ribosome entry sites (IRES)', 'The Shine–Dalgarno sequence', 'Introns', 'Telomeres'], 0,
    'Many plant and animal viruses exploit IRES.']
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 3, pyq: 'IFoS-2018-B2-Q5a', q: [
  ['Plant Rubisco is made of:', ['Eight large subunits (chloroplast *rbcL*) and eight small subunits (nuclear *rbcS*)', 'Two identical subunits', 'Four large subunits only', 'One large subunit'], 0,
    'This L₈S₈ form is found in plants and green algae.'],
  ['Rubisco is regarded as:', ['The most abundant protein on Earth', 'The rarest plant enzyme', 'A membrane pump', 'A storage protein only'], 0,
    'It can be up to half of the soluble protein in leaves.'],
  ['The carboxylation of one RuBP by Rubisco gives:', ['Two molecules of 3-phosphoglycerate', 'One oxaloacetate', 'Pyruvate', 'Glucose'], 0,
    'This is the first step of the Calvin cycle.'],
  ['The oxygenase activity of Rubisco produces:', ['One 3-phosphoglycerate and one 2-phosphoglycolate', 'Two 3-phosphoglycerate', 'Malate', 'Glycine directly'], 0,
    'Recycling phosphoglycolate is photorespiration.'],
  ['Rubisco becomes catalytically active by:', ['Carbamylation of an active-site lysine by CO₂, with Mg²⁺', 'Phosphorylation by ATP', 'Binding to DNA', 'Glycosylation'], 0,
    'Rubisco activase removes inhibitory sugar phosphates.'],
  ['In the light, Rubisco activity rises because the stroma:', ['Becomes more alkaline (about pH 8) and richer in Mg²⁺', 'Becomes acidic', 'Loses Mg²⁺', 'Fills with oxygen only'], 0,
    'Protons pumped into the lumen raise stromal pH.'],
  ['The turnover of Rubisco is:', ['Very slow — only a few CO₂ molecules per second per site', 'Very fast', 'Instantaneous', 'Unrelated to temperature'], 0,
    'Plants make it in huge amounts to compensate.'],
  ['A night-time inhibitor of Rubisco in many plants is:', ['2-carboxyarabinitol 1-phosphate (CA1P)', 'Ribulose 1,5-bisphosphate', 'NADPH', 'ATP'], 0,
    'It binds the active site in the dark.'],
  ['The oxygenase activity of Rubisco, relative to carboxylation, rises with:', ['Higher temperature', 'Lower temperature', 'Higher CO₂', 'Darkness'], 0,
    'CO₂ solubility falls faster than O₂ solubility as temperature rises.'],
  ['C₄ and CAM pathways improve Rubisco efficiency by:', ['Concentrating CO₂ around it, which suppresses oxygenation', 'Changing its subunit structure', 'Removing it from leaves', 'Increasing O₂ around it'], 0,
    'C₄ separates the steps in space; CAM separates them in time.']
] },
{ p: 'B2', t: 'Secondary Metabolites', w: 2, pyq: 'IFoS-2018-B2-Q5b', q: [
  ['The three main classes of plant secondary metabolites are:', ['Terpenoids, phenolics and nitrogen-containing compounds', 'Proteins, lipids and sugars', 'Nucleic acids, vitamins and minerals', 'Hormones, enzymes and pigments only'], 0,
    'Alkaloids, cyanogenic glycosides and glucosinolates contain nitrogen.'],
  ['Terpenoids are built from:', ['Five-carbon isoprene units made by the mevalonate and MEP pathways', 'Amino acids', 'Fatty acids', 'Nucleotides'], 0,
    'The mevalonate pathway is cytosolic; the MEP pathway is plastidic.'],
  ['Most plant phenolics are made by the:', ['Shikimic acid and phenylpropanoid pathways (starting with PAL)', 'Mevalonate pathway', 'Calvin cycle', 'Urea cycle'], 0,
    'PAL (phenylalanine ammonia-lyase) is the entry enzyme.'],
  ['Azadirachtin, an insect antifeedant, is a limonoid from:', ['Neem (*Azadirachta indica*)', 'Tobacco', 'Pyrethrum', 'Periwinkle'], 0,
    'It disrupts insect feeding and moulting.'],
  ['Pyrethrins, natural insecticides, come from:', ['*Tanacetum* (*Chrysanthemum*) *cinerariifolium* flowers', 'Neem seeds', 'Tobacco leaves', '*Derris* roots'], 0,
    'They act on insect sodium channels.'],
  ['Paclitaxel (Taxol), an anticancer drug, is a diterpenoid from:', ['*Taxus* (yew)', '*Catharanthus roseus*', '*Artemisia annua*', '*Rauvolfia serpentina*'], 0,
    'It stabilises microtubules and blocks cell division.'],
  ['Vinblastine and vincristine, used against leukaemia, come from:', ['*Catharanthus roseus*', '*Taxus baccata*', '*Papaver somniferum*', '*Cinchona*'], 0,
    'They are terpenoid indole alkaloids.'],
  ['Artemisinin, an antimalarial sesquiterpene lactone, comes from:', ['*Artemisia annua*', '*Cinchona officinalis*', '*Withania somnifera*', '*Digitalis purpurea*'], 0,
    'Tu Youyou shared the 2015 Nobel Prize for its discovery.'],
  ['Phytoalexins are:', ['Antimicrobial compounds made after infection, such as pisatin in pea', 'Growth hormones', 'Storage proteins', 'Photosynthetic pigments'], 0,
    'Rishitin in potato and camalexin in *Arabidopsis* are others.'],
  ['The "mustard oil bomb" defence of crucifers releases toxic isothiocyanates when:', ['Myrosinase meets glucosinolates in damaged tissue', 'Cyanogenic glycosides meet water', 'Alkaloids are exposed to light', 'Tannins bind proteins'], 0,
    'The enzyme and substrate are kept in separate cells until tissue is damaged.']
] },
{ p: 'B2', t: 'Plant Geography, Forests & Biodiversity', w: 2, pyq: 'IFoS-2018-B2-Q5c', q: [
  ['An endemic species is one that:', ['Is found naturally only in a particular geographic area', 'Occurs worldwide', 'Is introduced from elsewhere', 'Is extinct'], 0,
    'Endemism is high on islands and isolated mountains.'],
  ['Palaeoendemics, unlike neoendemics, are:', ['Old relict species that were once more widespread', 'Recently evolved species', 'Introduced weeds', 'Hybrids'], 0,
    'Neoendemics have evolved recently and not yet spread.'],
  ['Regions of India with high plant endemism include:', ['The Western Ghats, north-east India, the Himalaya and the Andaman and Nicobar Islands', 'The Indo-Gangetic plains', 'The Thar desert only', 'Urban areas'], 0,
    'All of these overlap with biodiversity hotspots.'],
  ['The three IUCN "threatened" categories are:', ['Critically Endangered, Endangered and Vulnerable', 'Extinct, Extinct in the Wild and Endangered', 'Near Threatened, Least Concern and Data Deficient', 'Rare, Common and Abundant'], 0,
    'Critically Endangered is the highest risk of extinction in the wild.'],
  ['The Red Data Book of Indian plants is compiled by:', ['The Botanical Survey of India', 'The Zoological Survey of India', 'The Forest Survey of India', 'ICAR'], 0,
    'It lists threatened plant species of India.'],
  ['The pitcher plant *Nepenthes khasiana* is endemic to:', ['Meghalaya', 'Kerala', 'Rajasthan', 'Andaman Islands'], 0,
    'It is threatened and listed in CITES Appendix I.'],
  ['*Paphiopedilum druryi*, a critically endangered orchid, is endemic to:', ['The southern Western Ghats', 'The Himalaya', 'The Sundarbans', 'The Aravallis'], 0,
    'It was nearly wiped out by overcollection.'],
  ['The major causes of species endangerment are summed up as:', ['Habitat loss, invasive species, pollution, population growth and overexploitation', 'Photosynthesis', 'Mutation alone', 'Seed dormancy'], 0,
    'Climate change adds to these pressures.'],
  ['Narrow endemics are especially vulnerable because they have:', ['A small range, small populations and often low genetic diversity', 'Wide ranges', 'Huge populations', 'Many habitats'], 0,
    'One local disturbance can wipe them out.'],
  ['A plant listed as "Extinct in the Wild" is one that:', ['Survives only in cultivation or captivity', 'Has died out everywhere', 'Is common', 'Has not been assessed'], 0,
    'Botanical gardens can hold such species.']
] },
{ p: 'B2', t: 'Plant Geography, Forests & Biodiversity', w: 3, pyq: 'IFoS-2018-B2-Q5d', q: [
  ['The concept of biodiversity hotspots was introduced in 1988 by:', ['Norman Myers', 'E. O. Wilson', 'Raymond Dasmann', 'Walter Rosen'], 0,
    'Conservation International later adopted it.'],
  ['To qualify as a hotspot, a region must have:', ['At least 1,500 endemic vascular plants and have lost at least 70% of its original habitat', 'At least 100 endemic birds', 'More than 50% forest cover', 'A national park'], 0,
    'These are Conservation International’s criteria.'],
  ['The number of biodiversity hotspots recognised worldwide is:', ['36', '25', '12', '50'], 0,
    'The North American Coastal Plain was added in 2016.'],
  ['The four hotspots that include parts of India are:', ['Himalaya, Indo-Burma, Western Ghats–Sri Lanka and Sundaland', 'Himalaya, Western Ghats, Thar and Deccan', 'Indo-Burma, Madagascar, Sundaland and Himalaya', 'Only the Western Ghats'], 0,
    'Parts of north-east India fall in both the Himalaya and Indo-Burma hotspots.'],
  ['The Nicobar Islands belong to the:', ['Sundaland hotspot', 'Indo-Burma hotspot', 'Western Ghats hotspot', 'Himalaya hotspot'], 0,
    'The Andaman Islands are counted in Indo-Burma.'],
  ['Hotspots together cover about what share of Earth’s land surface?', ['About 2.5%', 'About 25%', 'About 50%', 'About 10%'], 0,
    'Yet they hold about half of all endemic plant species.'],
  ['The Western Ghats became a UNESCO natural World Heritage Site in:', ['2012', '1992', '2002', '2020'], 0,
    'The listing covers several clusters of sites.'],
  ['The Kasturirangan High-Level Working Group (2013) proposed declaring as ecologically sensitive about:', ['37% of the Western Ghats', '64% of the Western Ghats', 'All of the Western Ghats', '5% of the Western Ghats'], 0,
    'The Gadgil panel (WGEEP, 2011) had proposed far wider protection. Notification is still pending — check current status.'],
  ['A fund that supports civil-society conservation in hotspots is:', ['The Critical Ecosystem Partnership Fund (CEPF)', 'The IMF', 'The World Trade Organization', 'NABARD'], 0,
    'The Western Ghats and Indo-Burma have received CEPF grants.'],
  ['Conservation measures in Indian hotspots include:', ['Protected areas, biosphere reserves and eco-sensitive zones', 'Clearing forests for plantations', 'Introducing exotic species', 'Removing all people'], 0,
    'Community conserved areas and sacred groves also help.']
] },
{ p: 'B2', t: 'Enzymes & Nitrogen Metabolism', w: 2, pyq: 'IFoS-2018-B2-Q5e', q: [
  ['A plot of reaction rate against substrate concentration for an allosteric enzyme is:', ['Sigmoidal, because of cooperative binding', 'Hyperbolic, as in Michaelis–Menten kinetics', 'A straight line', 'Flat'], 0,
    'Small changes in substrate cause large changes in rate in the steep region.'],
  ['Allosteric effectors bind at:', ['A regulatory site distinct from the active site', 'The active site only', 'The substrate', 'The cell wall'], 0,
    'Binding changes the enzyme’s shape and activity.'],
  ['Allosteric enzymes are usually:', ['Multimeric, with several subunits', 'Single small polypeptides', 'RNA molecules', 'Lipids'], 0,
    'Subunit interactions allow cooperativity.'],
  ['Feedback inhibition means:', ['The end product of a pathway inhibits the first committed enzyme', 'The substrate inhibits the last enzyme', 'The enzyme destroys itself', 'Light inhibits the enzyme'], 0,
    'For example, isoleucine inhibits threonine deaminase.'],
  ['The concerted (symmetry) model of allostery was proposed by:', ['Monod, Wyman and Changeux (1965)', 'Koshland, Némethy and Filmer', 'Michaelis and Menten', 'Lineweaver and Burk'], 0,
    'The sequential (KNF) model was proposed in 1966.'],
  ['A Hill coefficient greater than one indicates:', ['Positive cooperativity', 'Negative cooperativity', 'No cooperativity', 'Enzyme denaturation'], 0,
    'Haemoglobin has a Hill coefficient of about 2.8.'],
  ['Effectors that alter an enzyme’s substrate affinity (K₀.₅), not its Vmax, are called:', ['K-type effectors', 'V-type effectors', 'Coenzymes', 'Apoenzymes'], 0,
    'V-type effectors change Vmax.'],
  ['In plants, ADP-glucose pyrophosphorylase, the key enzyme of starch synthesis, is:', ['Activated by 3-PGA and inhibited by Pi', 'Activated by Pi and inhibited by 3-PGA', 'Unregulated', 'Activated by light directly'], 0,
    'A high 3-PGA to Pi ratio signals surplus photosynthate.'],
  ['PEP carboxylase in C₄ and CAM plants is:', ['Activated by glucose-6-phosphate and inhibited by malate', 'Activated by malate', 'Inhibited by glucose-6-phosphate', 'Not regulated'], 0,
    'Phosphorylation also makes it less sensitive to malate.'],
  ['A homotropic allosteric effect is one in which:', ['The substrate itself acts as the effector', 'A different molecule acts as the effector', 'Temperature changes the rate', 'pH denatures the enzyme'], 0,
    'Heterotropic effectors are molecules other than the substrate.']
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 3, pyq: 'IFoS-2018-B2-Q6a', q: [
  ['The chloroplast ATP synthase (CF₀CF₁) is located in the:', ['Thylakoid membrane, with CF₁ facing the stroma', 'Inner envelope, with CF₁ facing the lumen', 'Outer envelope', 'Stroma, free'], 0,
    'ATP is released into the stroma for the Calvin cycle.'],
  ['In the mitochondrion, the F₁ part of ATP synthase faces the:', ['Matrix', 'Intermembrane space', 'Cytosol', 'Outer membrane'], 0,
    'Protons flow back from the intermembrane space.'],
  ['The subunit composition of F₁ is:', ['α₃β₃γδε', 'α₂β₂', 'A ring of c subunits', 'a, b and b′'], 0,
    'The catalytic sites lie mainly on the β subunits.'],
  ['The F₀ part of ATP synthase contains:', ['A ring of c subunits that rotates as protons pass, plus a and b subunits', 'Three β subunits', 'Cytochrome *c*', 'Plastocyanin'], 0,
    'Spinach chloroplast ATP synthase has 14 c subunits in its ring.'],
  ['The binding-change mechanism of ATP synthesis was proposed by:', ['Paul Boyer', 'Peter Mitchell', 'Melvin Calvin', 'Hans Krebs'], 0,
    'Boyer and John Walker shared the 1997 Nobel Prize.'],
  ['The chemiosmotic theory, which explains how a proton gradient drives ATP synthesis, was proposed by:', ['Peter Mitchell (1961)', 'Paul Boyer', 'Robert Hill', 'Daniel Arnon'], 0,
    'Mitchell received the 1978 Nobel Prize.'],
  ['Jagendorf’s "acid bath" experiment showed that isolated thylakoids:', ['Make ATP in the dark when a pH gradient is imposed across them', 'Need light for all ATP synthesis', 'Cannot make ATP', 'Use NADPH to make ATP'], 0,
    'Thylakoids were soaked at pH 4 and moved to pH 8 with ADP and Pi.'],
  ['During photophosphorylation, protons pass through CF₀ from the:', ['Thylakoid lumen to the stroma', 'Stroma to the lumen', 'Cytosol to the stroma', 'Lumen to the cytosol'], 0,
    'Light-driven electron transport makes the lumen acidic.'],
  ['During ATP synthesis, the γ subunit:', ['Rotates inside the α₃β₃ hexamer in 120° steps, one per ATP', 'Stays fixed', 'Leaves the enzyme', 'Binds ADP directly'], 0,
    'Its rotation changes the conformation of each β subunit in turn.'],
  ['Uncouplers such as 2,4-dinitrophenol stop ATP synthesis because they:', ['Carry protons across the membrane and dissipate the gradient', 'Block the c ring', 'Destroy chlorophyll', 'Inhibit Rubisco'], 0,
    'Electron transport continues, but no ATP is made.']
] },
{ p: 'B2', t: 'Plant Hormones & Development', w: 3, pyq: 'IFoS-2018-B2-Q6b', q: [
  ['Climacteric fruits show:', ['A burst of respiration and ethylene production at the onset of ripening', 'No change in respiration', 'Ripening only on the plant', 'No response to ethylene'], 0,
    'Tomato, banana, mango and apple are climacteric.'],
  ['Which of these is a non-climacteric fruit?', ['Grape', 'Banana', 'Tomato', 'Mango'], 0,
    'Citrus, strawberry and pineapple are also non-climacteric.'],
  ['The ethylene biosynthesis pathway is:', ['Methionine → SAM → ACC (by ACC synthase) → ethylene (by ACC oxidase)', 'Tryptophan → IAA → ethylene', 'Mevalonate → GA → ethylene', 'Adenine → zeatin → ethylene'], 0,
    'Methionine is recycled through the Yang cycle.'],
  ['The ethylene surge during climacteric ripening is:', ['Autocatalytic (system 2) — ethylene promotes its own synthesis', 'Always inhibited by ethylene', 'Unrelated to ACC', 'Independent of genes'], 0,
    'System 1 ethylene is the low, self-inhibitory basal level.'],
  ['Softening of ripening fruit is caused by enzymes such as:', ['Polygalacturonase, pectin methylesterase and expansins', 'Rubisco', 'Nitrogenase', 'Amylase only'], 0,
    'They loosen the pectin and cellulose of the cell wall.'],
  ['The Flavr Savr tomato (1994), the first GM whole food on sale, had delayed softening because of:', ['Antisense suppression of polygalacturonase', 'A *Bt* gene', 'Overexpression of ACC synthase', 'Chloroplast transformation'], 0,
    'It was developed by Calgene.'],
  ['1-Methylcyclopropene (1-MCP) delays ripening by:', ['Blocking ethylene receptors', 'Releasing ethylene', 'Adding auxin', 'Removing water'], 0,
    'It is widely used to store apples.'],
  ['The tomato *rin* (*ripening inhibitor*) gene encodes:', ['A MADS-box transcription factor', 'An ethylene receptor', 'Polygalacturonase', 'Rubisco'], 0,
    '*Never-ripe* (*Nr*) is a mutant ethylene receptor.'],
  ['The red colour of ripe tomato is due to the build-up of:', ['Lycopene', 'Anthocyanin', 'Chlorophyll', 'Betalain'], 0,
    'Chloroplasts change into chromoplasts as chlorophyll breaks down.'],
  ['A safe, approved way to ripen mangoes and bananas commercially, instead of banned calcium carbide, is:', ['Controlled ethylene gas in ripening chambers', 'Spraying DDT', 'Heating with charcoal smoke', 'Coating with wax only'], 0,
    'FSSAI allows ethylene gas (up to 100 ppm) for artificial ripening.']
] },
{ p: 'B2', t: 'Enzymes & Nitrogen Metabolism', w: 3, pyq: 'IFoS-2018-B2-Q7a', q: [
  ['Nitrogenase consists of:', ['An Fe protein (dinitrogenase reductase) and an MoFe protein (dinitrogenase)', 'A single haem protein', 'Rubisco and PEP carboxylase', 'Nitrate reductase and nitrite reductase'], 0,
    'Electrons flow from the Fe protein to the MoFe protein.'],
  ['The overall reaction of nitrogenase is:', ['N₂ + 8H⁺ + 8e⁻ + 16 ATP → 2NH₃ + H₂ + 16 ADP + 16 Pi', 'N₂ + 3H₂ → 2NH₃ without ATP', 'NO₃⁻ → NO₂⁻', 'NH₃ → NO₃⁻'], 0,
    'H₂ is an unavoidable by-product.'],
  ['Leghaemoglobin in root nodules:', ['Keeps free O₂ low while supplying O₂ for bacteroid respiration', 'Fixes N₂ directly', 'Stores nitrate', 'Makes ATP by photosynthesis'], 0,
    'Nitrogenase is irreversibly damaged by oxygen.'],
  ['Rhizobia start nodulation after sensing root exudates rich in:', ['Flavonoids, which switch on their *nod* genes', 'Ethylene', 'Nitrate', 'Starch'], 0,
    'The *nod* genes make Nod factors.'],
  ['Nod factors are:', ['Lipochitooligosaccharides that cause root hair curling and cortical cell division', 'Proteins that fix nitrogen', 'Plant hormones', 'Antibiotics'], 0,
    'Rhizobia enter the root through an infection thread.'],
  ['Inside the nodule, rhizobia differentiate into:', ['Bacteroids enclosed in symbiosomes', 'Spores', 'Heterocysts', 'Akinetes'], 0,
    'The symbiosome membrane comes from the plant.'],
  ['Ammonia from nitrogen fixation is first assimilated by:', ['The GS–GOGAT pathway into glutamine and glutamate', 'The Calvin cycle', 'The urea cycle', 'Nitrate reductase'], 0,
    'GS stands for glutamine synthetase.'],
  ['Tropical legumes such as soybean and cowpea export fixed nitrogen from nodules mainly as:', ['Ureides (allantoin and allantoic acid)', 'Amides only', 'Nitrate', 'Free ammonia'], 0,
    'Temperate legumes such as pea export amides like asparagine.'],
  ['Nodulation and nitrogen fixation are strongly suppressed by:', ['High levels of soil nitrate', 'Adequate molybdenum', 'Neutral soil pH', 'Good photosynthate supply'], 0,
    'Mo, Fe and Co are needed for effective fixation.'],
  ['Nodules that keep a persistent meristem and grow elongated, as in pea and alfalfa, are called:', ['Indeterminate nodules', 'Determinate nodules', 'Stem nodules', 'Leaf nodules'], 0,
    'Soybean and common bean form round determinate nodules.']
] },
{ p: 'B2', t: 'Water Relations & Mineral Nutrition', w: 3, pyq: 'IFoS-2018-B2-Q7b', q: [
  ['The main hormone signal for stomatal closure under water deficit is:', ['Abscisic acid (ABA)', 'Gibberellin', 'Cytokinin', 'Auxin'], 0,
    'ABA triggers K⁺ and anion efflux from guard cells.'],
  ['Osmotic adjustment under drought involves the build-up of:', ['Compatible solutes such as proline, glycine betaine and sugars', 'Toxic ions', 'Starch in guard cells only', 'Lignin'], 0,
    'It keeps turgor at lower water potentials.'],
  ['A common morphological response to water deficit is:', ['A higher root-to-shoot ratio with deeper roots', 'Larger, thinner leaves', 'Fewer roots', 'More stomata per leaf'], 0,
    'Roots keep growing while shoot growth slows.'],
  ['Leaf rolling in drought-stressed grasses is caused by:', ['Bulliform (motor) cells losing turgor', 'Guard cells swelling', 'Xylem collapse', 'Phloem loading'], 0,
    'Rolling reduces the exposed leaf area and transpiration.'],
  ['"Drought escape" means:', ['Completing the life cycle before severe drought sets in', 'Tolerating very low water potential', 'Storing water in fleshy tissue', 'Closing stomata permanently'], 0,
    'Desert ephemerals and early-maturing crop varieties escape drought.'],
  ['Dehydration avoidance, unlike dehydration tolerance, means:', ['Keeping tissue water potential high, e.g., by deep roots and stomatal closure', 'Surviving desiccation of tissues', 'Growing only in water', 'Dying early'], 0,
    'Tolerance relies on osmotic adjustment and protective proteins.'],
  ['LEA proteins and dehydrins help plants by:', ['Protecting membranes and proteins during dehydration', 'Fixing nitrogen', 'Opening stomata', 'Absorbing light'], 0,
    'They are abundant in maturing seeds too.'],
  ['CAM plants save water because they:', ['Open their stomata at night and close them during the day', 'Keep stomata open all day', 'Have no stomata', 'Transpire more'], 0,
    'Examples are pineapple, *Opuntia* and *Agave*.'],
  ['Xerophytic leaf features that reduce water loss include:', ['A thick cuticle, sunken stomata and hairy surfaces', 'A thin cuticle and many exposed stomata', 'Large air spaces', 'Floating leaves'], 0,
    'Examples are *Nerium* and *Calotropis*.'],
  ['"Resurrection plants" such as *Selaginella lepidophylla* and *Craterostigma* can:', ['Survive near-complete desiccation and revive when rewetted', 'Grow only underwater', 'Never lose water', 'Fix nitrogen'], 0,
    'This is the extreme form of dehydration tolerance.']
] },
{ p: 'B2', t: 'Plant Geography, Forests & Biodiversity', w: 3, pyq: 'IFoS-2018-B2-Q8a', q: [
  ['The standard classification of Indian forests is by:', ['Champion and Seth (1968), with 16 type groups', 'Warming', 'Whittaker', 'Puri alone'], 0,
    'It recognises about 200 forest types.'],
  ['Tropical wet evergreen forests of India:', ['Receive over 250 cm of rain and are tall, multi-storeyed and rich in dipterocarps', 'Receive under 70 cm of rain', 'Are dominated by conifers', 'Occur above 3,500 m'], 0,
    'They occur in the Western Ghats, north-east India and the Andamans.'],
  ['Tropical moist deciduous forests are dominated by:', ['Sal and teak', 'Rhododendron and juniper', '*Prosopis* and *Acacia*', 'Mangroves'], 0,
    'They receive roughly 100–200 cm of rain.'],
  ['Tropical thorn forests with *Acacia*, *Prosopis* and *Euphorbia* occur where annual rainfall is:', ['Below about 70 cm', 'Above 250 cm', 'Between 150 and 200 cm', 'Over 400 cm'], 0,
    'They cover large parts of Rajasthan and Gujarat.'],
  ['According to Forest Survey of India forest-type mapping, the most extensive forest type group in India is:', ['Tropical dry deciduous', 'Tropical wet evergreen', 'Alpine scrub', 'Littoral and swamp'], 0,
    'Tropical moist deciduous forests come second.'],
  ['The dominant tree of the Sundarbans mangroves, from which they take their name, is:', ['*Heritiera fomes* (sundari)', '*Tectona grandis*', '*Shorea robusta*', '*Cedrus deodara*'], 0,
    '*Rhizophora*, *Avicennia* and *Sonneratia* are other mangroves.'],
  ['Shola forests with grasslands are found in the:', ['Nilgiris and other high hills of the southern Western Ghats', 'Thar desert', 'Sundarbans', 'Ladakh'], 0,
    'They are montane wet temperate forests.'],
  ['Himalayan moist temperate forests are dominated by:', ['Oaks, deodar, blue pine, fir and spruce', 'Sal and teak', 'Mangroves', '*Prosopis*'], 0,
    'Chir pine dominates the subtropical belt below them.'],
  ['The treeline in the western Himalaya is often formed by:', ['*Betula utilis* (bhojpatra) with *Rhododendron* and *Juniperus* scrub above', 'Teak', 'Sal', 'Mangroves'], 0,
    'Alpine meadows and scrub take over above the treeline.'],
  ['The alpine meadows of Uttarakhand are locally called:', ['Bugyals', 'Sholas', 'Terai', 'Duars'], 0,
    'They are rich in medicinal herbs and grazed in summer.']
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 3, pyq: 'IFoS-2018-B2-Q8b', q: [
  ['The monoclimax theory, in which climate alone decides the single climax of a region, was proposed by:', ['F. E. Clements', 'A. G. Tansley', 'R. H. Whittaker', 'E. P. Odum'], 0,
    'Clements set out succession theory in 1916.'],
  ['The polyclimax theory, which allows several climaxes controlled by soil, topography and fire, was put forward by:', ['A. G. Tansley', 'F. E. Clements', 'H. C. Cowles', 'E. Warming'], 0,
    'Tansley also coined the term "ecosystem" (1935).'],
  ['The climax-pattern hypothesis, which treats climax as a continuum of vegetation, is due to:', ['R. H. Whittaker', 'F. E. Clements', 'C. Elton', 'R. Lindeman'], 0,
    'He saw climax vegetation as varying continuously along environmental gradients.'],
  ['A climax community is characterised by:', ['Stability, self-perpetuation and a gross production to respiration ratio near one', 'Rapid change', 'Few species and simple food chains', 'Net biomass accumulation'], 0,
    'It is in balance with its environment.'],
  ['Succession that starts in a saline habitat, such as an estuary or salt marsh, is called a:', ['Halosere', 'Xerosere', 'Lithosere', 'Psammosere'], 0,
    'A hydrosere starts in fresh water.'],
  ['On newly formed estuarine mudflats in the Sundarbans, the pioneers include:', ['The wild rice grass *Porteresia coarctata* and *Avicennia*/*Sonneratia*', '*Heritiera fomes*', 'Sal', 'Teak'], 0,
    'They trap silt and raise the mudflat level.'],
  ['In estuarine succession, *Heritiera* and other landward mangroves appear:', ['Later, on higher and less saline ground', 'First, on new mud', 'Never', 'Only in fresh water'], 0,
    'Terrestrial forest follows as the land rises further.'],
  ['Mangroves such as *Avicennia* have pneumatophores, which are:', ['Negatively geotropic breathing roots', 'Prop roots', 'Storage roots', 'Tendrils'], 0,
    'They supply oxygen to roots in waterlogged mud.'],
  ['Vivipary in *Rhizophora* means that:', ['The seed germinates while the fruit is still attached to the parent tree', 'Seeds are dispersed by wind', 'Seeds need fire to germinate', 'The plant has no seeds'], 0,
    'The heavy propagule drops and lodges in the mud.'],
  ['A disclimax is a community that:', ['Is held in place by continued disturbance such as grazing or fire', 'Is the true climatic climax', 'Occurs only in water', 'Has no plants'], 0,
    'Fire-maintained grasslands are an example.']
] }
);
