/* PYQ-linked MCQs — IFoS 2018 Agriculture Paper I, Q5–Q8 (verbatim PYQs). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'IFoS-2018-A1-Q5a', q: [
  ['Consumptive use of water by a crop is:', ['Evapotranspiration plus the small amount of water retained in plant tissue', 'Only the water applied by irrigation', 'Only deep percolation', 'Only runoff'], 0,
    'The retained water is about 1%, so consumptive use is usually taken as equal to ET.'],
  ['Evapotranspiration (ET) is:', ['Evaporation from the soil plus transpiration from the plants', 'Transpiration only', 'Rainfall minus runoff', 'Irrigation minus drainage'], 0,
    'Transpiration dominates once the canopy closes.'],
  ['The FAO-recommended method for reference evapotranspiration (ET₀) is:', ['FAO Penman–Monteith', 'Blaney–Criddle only', 'Thornthwaite only', 'The gravimetric method'], 0,
    'ET₀ refers to a well-watered hypothetical grass surface.'],
  ['Crop evapotranspiration is estimated as:', ['ETc = Kc × ET₀', 'ETc = ET₀ ÷ Kc', 'ETc = rainfall × Kc', 'ETc = Kc + ET₀'], 0,
    'Kc is the crop coefficient.'],
  ['The crop coefficient (Kc) is highest at:', ['The mid-season stage (full canopy, flowering)', 'Sowing', 'Harvest', 'Seed storage'], 0,
    'It is low at the initial stage and declines at maturity.'],
  ['Crop water use efficiency (WUE) is:', ['Yield per unit of water evapotranspired (e.g., kg/ha-mm)', 'Water applied per hectare', 'Yield per hectare', 'Water lost to runoff'], 0,
    'Field WUE divides yield by the total water applied.'],
  ['The most accurate direct method of measuring ET is the:', ['Lysimeter', 'Rain gauge', 'Barometer', 'Anemometer'], 0,
    'It measures the full water balance of a soil block.'],
  ['With a USWB Class A pan, ET₀ is estimated as:', ['ET₀ = Kp × pan evaporation', 'ET₀ = pan evaporation ÷ 2 always', 'ET₀ = rainfall', 'ET₀ = Kc × rainfall'], 0,
    'Kp, the pan coefficient, is usually 0.6–0.85.'],
  ['The most critical stage for irrigating wheat is:', ['Crown root initiation (about 20–25 days after sowing)', 'Grain ripening', 'Before sowing', 'After harvest'], 0,
    'Missing this irrigation causes large yield losses.'],
  ['Water use efficiency can be raised by:', ['Drip irrigation, mulching and irrigating at critical stages', 'Flooding fields continuously', 'Irrigating at noon with sprinklers in strong wind', 'Over-irrigating'], 0,
    'Deficit irrigation can also save water with a small yield loss.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2018-A1-Q5b', q: [
  ['Farm planning is:', ['Deciding in advance how to organise the farm’s resources for the best returns', 'Buying land', 'Harvesting crops', 'Marketing produce only'], 0,
    'It covers crops, livestock, inputs, labour and credit.'],
  ['The usual steps in farm planning are:', ['Resource inventory → choice of enterprises → budgeting → implementation → review', 'Harvest → sowing → budgeting', 'Selling → buying → planning', 'Borrowing → spending → saving'], 0,
    'The plan is revised each season.'],
  ['A mathematical tool for finding the most profitable enterprise mix under resource limits is:', ['Linear programming', 'Chi-square test', 'Regression only', 'Pie chart'], 0,
    'The simplex method was developed by George Dantzig.'],
  ['Partial budgeting is used when:', ['Only a small change in the farm plan is being considered', 'The whole farm is being reorganised', 'Land is being sold', 'The farm is closing'], 0,
    'It compares added returns plus reduced costs with added costs plus reduced returns.'],
  ['A good farm plan should be:', ['Flexible, simple, profitable and provide for risk', 'Rigid and complex', 'Based on one crop only', 'Unrelated to resources'], 0,
    'It must suit the farmer’s own goals and skills.'],
  ['The equi-marginal principle says that a limited resource should be allocated so that:', ['Its marginal return is equal in all uses', 'It is spent on one crop only', 'Its average return is highest', 'It is never used'], 0,
    'This maximises total returns.'],
  ['The principle of comparative advantage suggests that a farmer should:', ['Grow the enterprises that give the highest returns relative to other options', 'Grow what the neighbours grow', 'Grow everything', 'Grow only food crops'], 0,
    'It explains regional crop specialisation.'],
  ['Advance planning of inputs and credit is helped by:', ['The Kisan Credit Card scheme', 'The Right to Education Act', 'The Motor Vehicles Act', 'The Aadhaar Act'], 0,
    'It gives farmers timely, flexible credit.'],
  ['Soil Health Cards support farm planning by:', ['Giving field-specific fertiliser recommendations', 'Giving crop insurance', 'Setting MSP', 'Registering land'], 0,
    'They are based on soil testing.'],
  ['The law of diminishing returns in farm planning states that:', ['Beyond a point, each extra unit of an input adds less output', 'Output always rises in proportion to input', 'Inputs have no effect', 'Output falls from the first unit'], 0,
    'It guides how much of an input to use.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2018-A1-Q5c', q: [
  ['Cooperative farming means:', ['Farmers pooling land and resources, managing them jointly and sharing the proceeds', 'Each farmer working alone', 'State ownership of all land', 'Contract farming with companies'], 0,
    'Shares are usually based on land and labour contributed.'],
  ['In cooperative better farming:', ['Members farm individually but buy inputs and sell produce jointly', 'All land is pooled and owned by the society', 'The state owns the land', 'Tenants cultivate society land'], 0,
    'It is the loosest form of cooperative farming.'],
  ['In cooperative joint farming:', ['Land is pooled and cultivated jointly, but members keep ownership', 'Land ownership passes to the society', 'Only marketing is joint', 'Only credit is joint'], 0,
    'Members are paid wages and a dividend on their land.'],
  ['In collective farming:', ['Ownership of land passes to the society, as in Soviet kolkhozes', 'Members keep full ownership', 'Only inputs are shared', 'Farming is private'], 0,
    'It has been largely rejected in India.'],
  ['Cooperative farming helps small and marginal farmers mainly through:', ['Economies of scale, better bargaining power and access to credit and machines', 'Increasing land fragmentation', 'Reducing their income', 'Eliminating markets'], 0,
    'Pooled holdings can use tractors and irrigation efficiently.'],
  ['The Anand pattern of dairy cooperatives began with:', ['The Kaira District Cooperative Milk Producers’ Union (AMUL), 1946', 'NABARD', 'The Grameen Bank', 'Mother Dairy only'], 0,
    'Verghese Kurien later led Operation Flood.'],
  ['India’s first cooperative law was the:', ['Co-operative Credit Societies Act, 1904', 'Companies Act, 1956', 'APMC Act', 'Essential Commodities Act'], 0,
    'It was based on Frederick Nicholson’s recommendations.'],
  ['Farmer Producer Organisations (FPOs) are:', ['Registered groups of farmers that aggregate produce and inputs for collective business', 'Government departments', 'Private banks', 'Fertiliser companies'], 0,
    'A central scheme launched in 2020 aims to form 10,000 FPOs.'],
  ['A common reason why cooperative farming has had limited success in India is:', ['Strong attachment to individual land ownership and weak management', 'Too much trust among members', 'Too many large farms', 'Absence of small farmers'], 0,
    'Dairy and sugar cooperatives are the notable successes.'],
  ['India created a separate Union Ministry of Cooperation in:', ['2021', '1991', '2004', '2014'], 0,
    'It is meant to strengthen the cooperative movement.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 3, pyq: 'IFoS-2018-A1-Q5d', q: [
  ['Minimum support prices are recommended by the:', ['Commission for Agricultural Costs and Prices (CACP)', 'Food Corporation of India', 'NABARD', 'Reserve Bank of India'], 0,
    'It began in 1965 as the Agricultural Prices Commission.'],
  ['Since 2018–19, MSPs have been fixed at no less than:', ['1.5 times the A2+FL cost of production', '1.5 times the C2 cost', 'Twice the A1 cost', 'The market price'], 0,
    'The Swaminathan Commission had recommended C2 plus 50%.'],
  ['The cost concept A2 + FL includes:', ['Paid-out costs plus the imputed value of family labour', 'Only rent on owned land', 'Only interest on capital', 'Only depreciation'], 0,
    'C2 adds the rent on owned land and interest on owned capital.'],
  ['The price for sugarcane set by the central government is called the:', ['Fair and Remunerative Price (FRP)', 'MSP', 'Issue price', 'State Advised Price (SAP)'], 0,
    'Some states set a higher SAP.'],
  ['The Food Corporation of India, which procures grain at MSP, was set up in:', ['1965', '1991', '1947', '2005'], 0,
    'It also maintains buffer stocks for the public distribution system.'],
  ['PM-AASHA (2018) includes:', ['Price Support Scheme, Price Deficiency Payment Scheme and Private Procurement pilot', 'Crop insurance only', 'Irrigation subsidy', 'Seed distribution'], 0,
    'It aims to ensure that farmers actually receive MSP.'],
  ['Instruments of agricultural price policy include:', ['MSP and procurement, buffer stocks, PDS, trade tariffs and the market intervention scheme', 'Only income tax', 'Only land reforms', 'Only irrigation'], 0,
    'Together they stabilise prices for producers and consumers.'],
  ['The Price Stabilisation Fund (2015) was set up mainly for:', ['Onion, potato and pulses', 'Wheat and rice', 'Tea and coffee', 'Rubber'], 0,
    'It finances buffer stocks to curb price volatility.'],
  ['The market intervention scheme (MIS) supports:', ['Perishable commodities not covered by MSP, when prices crash', 'Only wheat', 'Only sugarcane', 'Imports'], 0,
    'It is implemented at the request of states.'],
  ['The main objectives of agricultural price policy are:', ['Remunerative prices for farmers, fair prices for consumers and price stability', 'Only maximum exports', 'Only low prices', 'Only high prices'], 0,
    'Balancing these goals is the policy challenge.']
] },
{ p: 'A1', t: 'Agricultural Extension', w: 2, pyq: 'IFoS-2018-A1-Q5e', q: [
  ['Participatory Rural Appraisal (PRA) was popularised by:', ['Robert Chambers', 'Everett Rogers', 'M. S. Swaminathan', 'Norman Borlaug'], 0,
    'It grew out of Rapid Rural Appraisal (RRA).'],
  ['A PRA tool in which villagers draw houses, castes and facilities is:', ['Social mapping', 'Soil testing', 'Laboratory analysis', 'Satellite imaging'], 0,
    'Resource maps show land, water and forests.'],
  ['A transect walk in PRA is:', ['A systematic walk through the village with local people to observe resources and problems', 'A marathon', 'A market survey', 'A laboratory test'], 0,
    'It shows land use and problems along a cross-section.'],
  ['A seasonal calendar in PRA shows:', ['How work, rainfall, pests, income and illness vary over the year', 'Only festival dates', 'Only school holidays', 'Only rainfall'], 0,
    'It helps time interventions.'],
  ['Under ATMA, bottom-up planning is done through the:', ['Strategic Research and Extension Plan (SREP)', 'Five-Year Plan only', 'Annual budget of the RBI', 'State election manifesto'], 0,
    'Farmer groups and advisory committees feed into it.'],
  ['"Felt needs", as opposed to "real needs", are:', ['Needs recognised by the people themselves', 'Needs identified only by experts', 'Needs that do not exist', 'Government targets'], 0,
    'Extension starts with felt needs and moves towards real needs.'],
  ['Farmer Field Schools, first used for rice IPM in Indonesia (1989), are:', ['Season-long, field-based group learning by farmers', 'University degree courses', 'Radio programmes', 'Laboratory training'], 0,
    'Farmers learn by observing and experimenting.'],
  ['The main benefit of farmers’ participation in planning is:', ['Greater relevance, local ownership and sustainability of programmes', 'Faster top-down decisions', 'Lower relevance', 'Less adoption'], 0,
    'People support what they help to create.'],
  ['The 73rd Constitutional Amendment (1992) strengthened participatory planning through:', ['Panchayati Raj institutions and the gram sabha', 'Municipal corporations', 'State assemblies', 'The Planning Commission'], 0,
    'Agriculture is among the 29 subjects in the Eleventh Schedule.'],
  ['ICAR’s "Farmer FIRST" programme (2016) stresses:', ['Farmer-scientist partnership and farmers’ innovations', 'Only laboratory research', 'Only export crops', 'Only large farms'], 0,
    'FIRST stands for Farm, Innovations, Resources, Science and Technology.']
] },
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'IFoS-2018-A1-Q6a', q: [
  ['The application efficiency of drip irrigation is typically about:', ['90% or more', '40%', '60%', '20%'], 0,
    'Sprinklers reach about 70–80%, surface methods about 40–60%.'],
  ['Drip irrigation is best suited to:', ['Widely spaced crops such as orchards, vegetables and sugarcane', 'Wetland rice', 'Broadcast wheat', 'Pastures'], 0,
    'Water is applied only to the root zone.'],
  ['A major problem of drip irrigation is:', ['Clogging of emitters and high initial cost', 'Heavy runoff', 'Waterlogging', 'Deep percolation'], 0,
    'Filters and acid treatment prevent clogging.'],
  ['Applying fertilisers through a drip system is called:', ['Fertigation', 'Chemigation of herbicides', 'Foliar feeding', 'Broadcasting'], 0,
    'It improves nutrient use efficiency.'],
  ['Emitters in drip systems typically discharge about:', ['2–8 litres per hour', '200 litres per hour', '0.01 litre per hour', '1,000 litres per hour'], 0,
    'Low discharge keeps the soil near field capacity.'],
  ['Sprinkler irrigation is especially suited to:', ['Undulating land and light sandy soils', 'Heavy clay soils with standing water', 'Wetland rice', 'Saline irrigation water'], 0,
    'No land levelling is needed.'],
  ['A demerit of sprinkler irrigation is:', ['Wind drift and evaporation losses, and a higher risk of foliar diseases', 'It needs land levelling', 'It causes waterlogging', 'It cannot be used for field crops'], 0,
    'Saline water sprayed on leaves can also scorch them.'],
  ['A rain gun is:', ['A high-discharge sprinkler that covers a large area', 'A drip emitter', 'A tensiometer', 'A weather radar'], 0,
    'It suits tall crops such as sugarcane.'],
  ['Drip irrigation can use slightly saline water more safely than surface irrigation because:', ['Frequent, small applications keep salts pushed to the edge of the wetted zone', 'It removes salts from the water', 'It needs no water', 'Salts evaporate'], 0,
    'Salts collect at the wetting front, away from the roots.'],
  ['Micro-irrigation is promoted in India under:', ['The "Per Drop More Crop" component of PMKSY', 'MGNREGA only', 'PM-KISAN', 'Jan Dhan Yojana'], 0,
    'Subsidies are given for drip and sprinkler systems.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2018-A1-Q6b', q: [
  ['Opportunity cost is:', ['The return from the next best alternative that is given up', 'The price paid for inputs', 'The cost of transport', 'The total cost of production'], 0,
    'Every choice has an opportunity cost.'],
  ['If wheat gives a net return of ₹40,000/ha and mustard ₹35,000/ha on the same land, the opportunity cost of growing wheat is:', ['₹35,000', '₹40,000', '₹75,000', '₹5,000'], 0,
    'It is the return from mustard that is given up.'],
  ['Using the opportunity-cost principle, a farmer should grow a crop when:', ['Its net return exceeds that of the best alternative', 'Its gross return is high, whatever the cost', 'Neighbours grow it', 'Its seed is cheap'], 0,
    'The net gain over the alternative is the true profit.'],
  ['The opportunity cost of family labour is:', ['The wage it could earn elsewhere', 'Zero', 'The price of seed', 'The rent of land'], 0,
    'CACP includes it as imputed family labour (FL).'],
  ['The opportunity cost of owned land is measured by:', ['Its rental value', 'Its purchase price', 'Land revenue only', 'Zero'], 0,
    'It is included in cost C2.'],
  ['The opportunity cost of owned capital is:', ['The interest it could earn elsewhere', 'Its depreciation', 'Zero', 'Its purchase price'], 0,
    'It is also included in cost C2.'],
  ['The opportunity-cost principle underlies:', ['The principle of comparative advantage in choosing enterprises', 'The law of the minimum', 'Photoperiodism', 'Mendel’s laws'], 0,
    'Regions specialise in crops with the lowest opportunity cost.'],
  ['Economic profit differs from accounting profit because it deducts:', ['Opportunity costs of owned resources as well as paid-out costs', 'Only paid-out costs', 'Nothing', 'Only taxes'], 0,
    'A farm can show accounting profit yet economic loss.'],
  ['When irrigation water is scarce, its opportunity cost is:', ['The value of the output it could produce in its best alternative use', 'Zero', 'Always the canal fee', 'Unrelated to crops'], 0,
    'Scarce water should go to the highest-value use.'],
  ['Ignoring opportunity costs leads farmers to:', ['Overestimate the profitability of their current enterprise', 'Always make the best choice', 'Reduce risk', 'Increase comparative advantage'], 0,
    'This is why family labour and owned land must be costed.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 3, pyq: 'IFoS-2018-A1-Q6c', q: [
  ['Marketing functions are usually grouped into:', ['Exchange, physical and facilitating functions', 'Sowing, weeding and harvesting', 'Saving, lending and borrowing', 'Import, export and tax'], 0,
    'This classification is due to Kohls.'],
  ['Buying and selling are:', ['Exchange functions', 'Physical functions', 'Facilitating functions', 'Production functions'], 0,
    'They transfer ownership of the produce.'],
  ['Storage, transport and processing are:', ['Physical functions', 'Exchange functions', 'Facilitating functions', 'Financial functions only'], 0,
    'They add time, place and form utility.'],
  ['Grading, financing, risk-bearing and market information are:', ['Facilitating functions', 'Exchange functions', 'Physical functions', 'Production functions'], 0,
    'They make the other functions work smoothly.'],
  ['Grading and certification of farm produce in India is done under:', ['AGMARK, under the Agricultural Produce (Grading and Marking) Act, 1937', 'The ISI mark only', 'The Seeds Act', 'The Insecticides Act'], 0,
    'It certifies quality for consumers.'],
  ['Regulated markets in India were established under:', ['State APMC Acts', 'The Companies Act', 'The Essential Commodities Act only', 'The Forest Act'], 0,
    'They aim to stop malpractices and ensure fair prices.'],
  ['The electronic National Agriculture Market (e-NAM) was launched in:', ['April 2016', 'April 2006', 'January 2020', 'August 1995'], 0,
    'It links APMC mandis on one online trading platform.'],
  ['Shepherd’s formula measures marketing efficiency as:', ['Value of goods sold ÷ total marketing cost, minus one', 'Price ÷ quantity', 'Yield ÷ area', 'Cost ÷ profit'], 0,
    'A higher value means a more efficient market.'],
  ['The price spread is the difference between:', ['The price paid by the consumer and the price received by the producer', 'The MSP and market price', 'Wholesale and export prices', 'The cost and yield'], 0,
    'The producer’s share in the consumer’s rupee is its complement.'],
  ['Negotiable warehouse receipts are regulated by the:', ['Warehousing Development and Regulatory Authority (WDRA)', 'SEBI', 'FSSAI', 'NABARD'], 0,
    'Farmers can borrow against produce stored in accredited warehouses.']
] },
{ p: 'A1', t: 'Agricultural Extension', w: 2, pyq: 'IFoS-2018-A1-Q6d', q: [
  ['An extension programme is:', ['A statement of the situation, objectives, problems and solutions', 'A single demonstration', 'A radio talk', 'A seed packet'], 0,
    'This is Kelsey and Hearne’s definition.'],
  ['The first step in programme planning is:', ['Collecting facts and analysing the situation', 'Evaluation', 'Execution', 'Writing a report'], 0,
    'Problems and objectives follow from the situation analysis.'],
  ['A plan of work specifies:', ['What will be done, by whom, when, where and how', 'Only the budget', 'Only the objectives', 'Only the results'], 0,
    'It turns the programme into action.'],
  ['Evaluation carried out during a programme to improve it is:', ['Formative evaluation', 'Summative evaluation', 'Ex-post evaluation', 'Baseline survey'], 0,
    'Summative evaluation judges results at the end.'],
  ['A baseline survey is done:', ['Before the programme, to set a benchmark for later comparison', 'Only at the end', 'Never', 'After ten years'], 0,
    'Change can then be measured against it.'],
  ['Standard criteria for evaluating programmes include:', ['Relevance, effectiveness, efficiency, impact and sustainability', 'Only the number of meetings', 'Only the money spent', 'Only the staff employed'], 0,
    'These are the OECD-DAC criteria.'],
  ['A principle of extension programme planning is that it should be:', ['Based on people’s felt needs, with their participation, and be flexible', 'Imposed from above', 'Fixed and unchangeable', 'Planned without facts'], 0,
    'Planning is a continuous process.'],
  ['The logical framework (logframe) approach links:', ['Inputs, activities, outputs, outcomes and impact with indicators', 'Only budgets', 'Only rainfall data', 'Only staff lists'], 0,
    'It is widely used to design and monitor projects.'],
  ['Ex-ante evaluation is done:', ['Before a programme is implemented', 'After it ends', 'Only during it', 'Never'], 0,
    'Ex-post evaluation is done after completion.'],
  ['PERT and CPM are tools used in programme planning for:', ['Scheduling activities and identifying the critical path', 'Soil testing', 'Pest control', 'Weather forecasting'], 0,
    'They help keep programmes on time.']
] },
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'IFoS-2018-A1-Q7a', q: [
  ['Agricultural drainage is:', ['Removing excess water from the soil surface and root zone', 'Adding irrigation water', 'Storing rainwater', 'Mulching'], 0,
    'It restores aeration for root growth.'],
  ['Surface drainage is done by:', ['Open ditches and land shaping', 'Buried perforated pipes', 'Mole ploughing', 'Pumping from tube wells'], 0,
    'It removes ponded water.'],
  ['Subsurface drainage includes:', ['Tile or perforated pipe drains, mole drains and vertical (tube well) drainage', 'Open field ditches only', 'Contour bunds', 'Farm ponds'], 0,
    'It lowers a high water table.'],
  ['Mole drains are:', ['Unlined channels formed in clay subsoil by a mole plough', 'Concrete pipes', 'Surface ditches', 'Tube wells'], 0,
    'They work only in stable clay soils.'],
  ['Bio-drainage uses:', ['Fast-growing trees with high transpiration, such as eucalyptus, to lower the water table', 'Earthworms', 'Bacteria in pipes', 'Chemical drying agents'], 0,
    'It has been tried in canal commands of Haryana and Rajasthan.'],
  ['Waterlogging in canal command areas often leads to:', ['Secondary salinisation of soils', 'Improved aeration', 'Lower water tables', 'Soil acidification only'], 0,
    'Rising groundwater brings salts to the surface.'],
  ['The drainage coefficient is:', ['The depth of water to be removed from an area in 24 hours', 'The slope of a drain', 'The number of drains', 'The diameter of a pipe'], 0,
    'It is used to design drain capacity.'],
  ['Drain spacing for subsurface drainage is commonly worked out with:', ['Hooghoudt’s equation', 'The USLE', 'Darcy–Weisbach only', 'The Penman equation'], 0,
    'It uses soil hydraulic conductivity and the desired water-table depth.'],
  ['Good drainage benefits crops by:', ['Improving aeration, root growth, soil warming and salt leaching', 'Reducing oxygen', 'Raising the water table', 'Increasing salinity'], 0,
    'It also allows timely field operations.'],
  ['In India, land is generally regarded as waterlogged when the water table is within about:', ['Two metres of the surface', 'Ten metres', 'Fifty metres', 'Twenty metres'], 0,
    'Most crop roots suffer when the water table stays this shallow.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2018-A1-Q7b', q: [
  ['A farm budget is:', ['An estimate of the costs, returns and net income of a farm plan', 'A bank passbook', 'A land record', 'A crop insurance policy'], 0,
    'It turns a farm plan into money terms.'],
  ['The three main types of farm budget are:', ['Partial, enterprise and complete (whole-farm) budgets', 'Annual, monthly and weekly', 'Seed, fertiliser and pesticide', 'Cash, credit and barter'], 0,
    'A cash-flow budget tracks the timing of income and expenses.'],
  ['In a partial budget, the credit (gain) side lists:', ['Added returns and reduced costs', 'Added costs and reduced returns', 'Only added costs', 'Only fixed costs'], 0,
    'The change is worthwhile if the gains exceed the losses.'],
  ['A complete (whole-farm) budget is prepared when:', ['The whole farm is being reorganised or a new farm is planned', 'A minor change is made', 'Only one input is changed', 'The farm is sold'], 0,
    'It covers all enterprises together.'],
  ['An enterprise budget shows:', ['The costs and returns of one enterprise per unit (e.g., per hectare)', 'The whole farm’s accounts', 'Only household spending', 'Only loans'], 0,
    'It is the building block of whole-farm budgets.'],
  ['Gross margin is:', ['Gross returns minus variable costs', 'Gross returns minus all costs', 'Fixed costs minus variable costs', 'Yield minus seed rate'], 0,
    'It is used to compare enterprises.'],
  ['The break-even output is:', ['Fixed costs ÷ (price − variable cost per unit)', 'Variable cost ÷ price', 'Price × quantity', 'Fixed cost × price'], 0,
    'Beyond it, the enterprise makes a profit.'],
  ['Farm budgeting is important to farmers because it:', ['Helps compare alternatives, estimate credit needs and reduce risk', 'Guarantees profit', 'Removes the need for records', 'Fixes market prices'], 0,
    'Banks often ask for a budget before lending.'],
  ['A cash-flow budget helps a farmer to:', ['Plan when money will be needed and when it will come in', 'Measure soil pH', 'Estimate rainfall', 'Choose seed varieties'], 0,
    'It shows months of cash shortage in advance.'],
  ['A limitation of farm budgeting is that it:', ['Depends on estimates of prices and yields, which are uncertain', 'Needs no data', 'Always gives exact results', 'Cannot be used for crops'], 0,
    'Sensitivity analysis tests how robust the plan is.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: 'IFoS-2018-A1-Q7c', q: [
  ['The three traditional approaches to studying agricultural marketing are:', ['Functional, institutional and commodity approaches', 'Genetic, chemical and physical approaches', 'Historical, legal and medical approaches', 'Seed, soil and water approaches'], 0,
    'Newer approaches include behavioural-systems and managerial ones.'],
  ['The commodity approach studies marketing by:', ['Following a product from producer to consumer', 'Studying only wholesalers', 'Studying only functions', 'Studying only prices'], 0,
    'Examples are studies of rice or onion marketing chains.'],
  ['The institutional approach focuses on:', ['Agencies such as wholesalers, retailers, commission agents and cooperatives', 'Only commodities', 'Only prices', 'Only consumers'], 0,
    'It asks who performs marketing and how.'],
  ['The functional approach studies:', ['Marketing functions — exchange, physical and facilitating', 'Only the crop', 'Only the farm', 'Only the government'], 0,
    'It asks what activities marketing involves.'],
  ['The structure–conduct–performance (SCP) paradigm in market analysis is associated with:', ['Joe S. Bain', 'Adam Smith', 'Karl Marx', 'John Maynard Keynes'], 0,
    'Market structure is taken to shape conduct and performance.'],
  ['A major problem in marketing farm produce in India is:', ['Too many intermediaries and a low producer share of the consumer’s rupee', 'Too few consumers', 'Excess storage capacity', 'Very high farmer bargaining power'], 0,
    'Other problems include poor grading and weak market information.'],
  ['Distress sale by small farmers right after harvest happens mainly because of:', ['Urgent cash needs and lack of storage and credit', 'High prices', 'Too much storage', 'Government orders'], 0,
    'Pledge loans against stored produce help avoid it.'],
  ['Malpractices in unregulated markets include:', ['Faulty weighing, unauthorised deductions and secret price settlement', 'Transparent auctions', 'Standard weights', 'Online payment'], 0,
    'Regulated markets were created to curb these.'],
  ['Measures to improve agricultural marketing include:', ['Regulated markets, cooperative marketing, warehouses, e-NAM and market information', 'Adding more intermediaries', 'Closing markets', 'Banning storage'], 0,
    'FPOs also help farmers bargain collectively.'],
  ['The apex national cooperative for agricultural marketing is:', ['NAFED', 'NABARD', 'FCI', 'NDDB'], 0,
    'It also procures pulses and oilseeds for the government.']
] },
{ p: 'A1', t: 'Agricultural Extension', w: 2, pyq: 'IFoS-2018-A1-Q7d', q: [
  ['A typical self-help group (SHG) has:', ['About 10–20 members who save regularly and lend to one another', 'Over 200 members', 'One member', 'Only men'], 0,
    'Most rural SHGs in India are women’s groups.'],
  ['The SHG–Bank Linkage Programme was started in 1992 by:', ['NABARD', 'The RBI alone', 'The World Bank', 'SEBI'], 0,
    'It is among the world’s largest microfinance programmes.'],
  ['The national rural livelihoods mission that organises poor women into SHGs is:', ['DAY-NRLM (Aajeevika)', 'MGNREGA', 'PMAY-G', 'PMGSY'], 0,
    'It was launched in 2011.'],
  ['Kerala’s state-wide women’s SHG network is:', ['Kudumbashree', 'SEWA', 'Amul', 'Lijjat'], 0,
    'It was launched in 1998.'],
  ['The Grameen Bank model of group lending was developed by:', ['Muhammad Yunus in Bangladesh', 'Ela Bhatt', 'Verghese Kurien', 'Amartya Sen'], 0,
    'He shared the 2006 Nobel Peace Prize.'],
  ['SEWA, a union of self-employed women, was founded in 1972 by:', ['Ela Bhatt', 'Muhammad Yunus', 'Medha Patkar', 'Aruna Roy'], 0,
    'It is based in Ahmedabad.'],
  ['The "panchasutra" of a good SHG includes:', ['Regular meetings, regular savings, internal lending, timely repayment and proper accounts', 'Only taking loans', 'Only attending training', 'Only buying seed'], 0,
    'These norms decide eligibility for bank credit.'],
  ['SHGs empower rural women economically by:', ['Giving access to credit, building savings and supporting micro-enterprises', 'Keeping them away from markets', 'Replacing banks entirely', 'Reducing their income'], 0,
    'They also raise women’s role in household decisions.'],
  ['Joint liability groups (JLGs), promoted by NABARD, are especially useful for:', ['Tenant farmers and sharecroppers without land titles', 'Large landowners', 'Corporate farms', 'Government employees'], 0,
    'Group guarantee replaces collateral.'],
  ['SHGs contribute to social empowerment of women by:', ['Building confidence, leadership and collective voice', 'Increasing isolation', 'Removing their property rights', 'Reducing literacy'], 0,
    'Many SHG leaders go on to serve in panchayats.']
] },
{ p: 'A1', t: 'Farm Mechanisation', w: 2, pyq: 'IFoS-2018-A1-Q8a', q: [
  ['Selective mechanisation means:', ['Mechanising only those operations where labour is short or timeliness is critical', 'Mechanising every farm operation', 'Banning machines', 'Using only animal power'], 0,
    'It avoids displacing labour where it is plentiful.'],
  ['Farm power availability in India is roughly:', ['2.5–3 kW per hectare', '20 kW per hectare', '0.1 kW per hectare', '50 kW per hectare'], 0,
    'Recent estimates are near the lower end — check the latest figure.'],
  ['India is the world’s largest manufacturer of:', ['Tractors (by number)', 'Combine harvesters', 'Rice transplanters', 'Cotton pickers'], 0,
    'Most Indian tractors are in the 30–50 hp range.'],
  ['Custom hiring centres for farm machinery are promoted under:', ['The Sub-Mission on Agricultural Mechanisation (SMAM)', 'PM-KISAN', 'The Soil Health Card scheme', 'e-NAM'], 0,
    'Small farmers can rent machines they cannot afford to buy.'],
  ['A key advantage of mechanisation is:', ['Timely operations, less drudgery and higher productivity', 'More labour needed per hectare', 'Lower cropping intensity', 'Higher cost per unit of output always'], 0,
    'Timeliness matters most in the rice–wheat system.'],
  ['A disadvantage of mechanisation in India is:', ['Displacement of labour and poor fit with small, fragmented holdings', 'Better timeliness', 'Less drudgery', 'Higher cropping intensity'], 0,
    'Machines also raise fuel dependence.'],
  ['A combine harvester:', ['Harvests, threshes and cleans the grain in one operation', 'Only cuts the crop', 'Only sows seed', 'Only sprays pesticides'], 0,
    'It leaves loose straw behind in the field.'],
  ['The Happy Seeder is used to:', ['Sow wheat directly into rice stubble without burning it', 'Harvest rice', 'Transplant rice', 'Spray pesticides'], 0,
    'It cuts the straw and leaves it as mulch.'],
  ['A zero-till seed drill:', ['Sows seed without prior ploughing', 'Ploughs the field deeply', 'Harvests grain', 'Levels the land'], 0,
    'It saves fuel and time and conserves soil moisture.'],
  ['Laser land levelling mainly improves:', ['Uniform water distribution and irrigation efficiency', 'Pest control', 'Seed quality', 'Grain colour'], 0,
    'It can save a sizeable share of irrigation water.']
] },
{ p: 'A1', t: 'Agricultural Extension', w: 2, pyq: 'IFoS-2018-A1-Q8b', q: [
  ['Indigenous technical knowledge (ITK) is:', ['Knowledge developed by local communities through generations of experience', 'Knowledge from laboratories only', 'Imported technology', 'Patented industrial technology'], 0,
    'It is usually passed on orally.'],
  ['A common ITK practice for protecting stored grain is:', ['Mixing neem leaves or ash with the grain', 'Adding DDT', 'Storing grain in wet sacks', 'Keeping grain in sunlight all the time'], 0,
    'Neem repels storage insects.'],
  ['The Apatani rice–fish farming of Ziro valley (Arunachal Pradesh) is an example of:', ['An indigenous integrated farming system', 'A modern research station', 'Contract farming', 'Hydroponics'], 0,
    'It combines rice, fish and millet on terraced fields.'],
  ['The Zabo system of Nagaland is an indigenous practice of:', ['Integrated water harvesting, forestry, farming and livestock', 'Seed treatment', 'Grain storage', 'Weather forecasting'], 0,
    '"Zabo" means impounding water.'],
  ['Bamboo drip irrigation is a traditional practice from:', ['Meghalaya', 'Punjab', 'Rajasthan', 'Tamil Nadu'], 0,
    'Bamboo pipes carry spring water to betel-leaf and areca plants.'],
  ['ITK is useful for formulating programmes because it is:', ['Low-cost, locally adapted and readily accepted by farmers', 'Always scientifically proven', 'Universally applicable', 'Expensive'], 0,
    'Blending it with science improves adoption.'],
  ['A limitation of ITK is that it is often:', ['Location-specific and not scientifically validated', 'Universally applicable', 'Always written down', 'Costly'], 0,
    'ICAR documented and began validating ITK in the early 2000s.'],
  ['The Honey Bee Network, which documents grassroots innovations, was started by:', ['Anil K. Gupta', 'M. S. Swaminathan', 'Verghese Kurien', 'Robert Chambers'], 0,
    'The National Innovation Foundation grew out of it.'],
  ['India’s Traditional Knowledge Digital Library (TKDL) protects ITK by:', ['Documenting it so that it cannot be wrongly patented', 'Selling it to companies', 'Keeping it secret', 'Banning its use'], 0,
    'It was set up by CSIR in 2001.'],
  ['A traditional preparation from five cow products used in organic farming is:', ['Panchagavya', 'Bordeaux mixture', 'Urea–molasses block', 'Lime-sulphur'], 0,
    'It combines dung, urine, milk, curd and ghee.']
] },
{ p: 'A1', t: 'Water Management & Irrigation', w: 3, pyq: 'IFoS-2018-A1-Q8c', q: [
  ['By the soil-moisture depletion approach, field crops are usually irrigated when:', ['About 50% of available soil moisture has been used', '100% has been used', '5% has been used', 'The soil is waterlogged'], 0,
    'Sensitive crops are irrigated at a lower depletion.'],
  ['The IW/CPE approach schedules irrigation based on:', ['The ratio of irrigation water depth to cumulative pan evaporation', 'Soil colour', 'Plant height', 'Calendar dates only'], 0,
    'For example, 6 cm of water is applied when CPE reaches 75 mm (IW/CPE = 0.8).'],
  ['The critical growth stage approach irrigates:', ['At the stages most sensitive to water stress', 'Only at sowing', 'Only at harvest', 'Every day'], 0,
    'In maize the critical stage is tasselling to silking.'],
  ['In rice, the stages most sensitive to water stress are:', ['Panicle initiation and flowering', 'Seed ripening', 'Nursery only', 'After harvest'], 0,
    'Drought at flowering causes spikelet sterility.'],
  ['A tensiometer measures:', ['Soil moisture tension, reliably up to about 0.8 bar', 'Soil pH', 'Rainfall', 'Wind speed'], 0,
    'It is best suited to crops needing moist soil, such as vegetables.'],
  ['Available soil water is:', ['Water held between field capacity and permanent wilting point', 'Water above field capacity', 'Water below wilting point', 'Groundwater'], 0,
    'Field capacity is about −0.033 MPa; wilting point is about −1.5 MPa.'],
  ['Plant-based indicators for timing irrigation include:', ['Leaf water potential, canopy temperature and the crop water stress index', 'Soil colour', 'Seed size', 'Grain protein'], 0,
    'Infrared thermometers measure canopy temperature.'],
  ['Soil moisture can be measured by:', ['Gravimetric sampling, neutron probes, TDR and gypsum blocks', 'A barometer', 'A thermometer', 'A pH meter'], 0,
    'The gravimetric method is the standard for calibration.'],
  ['Sunflower is sometimes used as an indicator plant for irrigation because it:', ['Wilts visibly when soil moisture is low', 'Never wilts', 'Changes colour with pH', 'Fixes nitrogen'], 0,
    'This is the indicator-plant method.'],
  ['The feel-and-appearance method of judging soil moisture is:', ['Squeezing soil by hand and comparing its behaviour with a guide', 'A laboratory test', 'A satellite method', 'A chemical test'], 0,
    'It is simple and cheap but subjective.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 3, pyq: 'IFoS-2018-A1-Q8d', q: [
  ['Farm management is:', ['The science of organising and managing farm resources for maximum continuous profit', 'Only keeping farm accounts', 'Only marketing', 'Only crop breeding'], 0,
    'It applies economic principles at the level of the individual farm.'],
  ['Farm management deals mainly with:', ['Decisions at the level of the individual farm (micro level)', 'National policy', 'International trade', 'Global climate'], 0,
    'It is an applied, interdisciplinary subject.'],
  ['The three basic decisions in farm management are:', ['What to produce, how to produce and how much to produce', 'When to sell land, buy land and rent land', 'Whom to hire, fire and pay', 'Which bank, loan and rate'], 0,
    'They correspond to product–product, factor–factor and factor–product relationships.'],
  ['In the factor–product relationship, the optimum level of an input is reached where:', ['The marginal value product equals the price of the input', 'Total product is highest', 'Average product is highest', 'The input is free'], 0,
    'This is the profit-maximising level.'],
  ['In the factor–factor relationship, the least-cost combination of inputs is where:', ['The marginal rate of technical substitution equals the inverse of their price ratio', 'Both inputs are used equally', 'One input is not used', 'Input prices are equal'], 0,
    'This minimises the cost of producing a given output.'],
  ['In the product–product relationship, the best combination of two enterprises is where:', ['The marginal rate of product substitution equals the inverse of their price ratio', 'Both are produced in equal amounts', 'Only one is produced', 'Prices are equal'], 0,
    'It is found on the production possibility curve.'],
  ['Principles of farm management include:', ['Diminishing returns, cost, substitution, opportunity cost, equi-marginal returns and comparative advantage', 'Only Mendel’s laws', 'Only Newton’s laws', 'Only photoperiodism'], 0,
    'Combining enterprises and time comparison are others.'],
  ['Farm records and accounts help a farmer to:', ['Analyse the farm business, find weak points and plan better', 'Avoid all taxes', 'Raise market prices', 'Change the weather'], 0,
    'Inventories and cash accounts are basic records.'],
  ['Systematic Farm Management Studies in India began in:', ['1954–55', '1991–92', '1970–71', '1947–48'], 0,
    'The Comprehensive Cost of Cultivation Scheme followed in 1970–71.'],
  ['Farm management is characterised as:', ['An applied, interdisciplinary science using economics, agronomy and management', 'A purely theoretical science', 'A branch of physics', 'A branch of law only'], 0,
    'Its goal is the efficient use of scarce farm resources.']
] }
);
