/* PYQ-linked MCQs — IFoS 2017 Botany Paper II (verbatim PYQs). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 3, pyq: 'IFoS-2017-B2-Q1a', q: [
  ['Complex I of the mitochondrial electron transport chain is:', ['NADH dehydrogenase (NADH–ubiquinone oxidoreductase)', 'Succinate dehydrogenase', 'Cytochrome *c* oxidase', 'ATP synthase'], 0,
    'It pumps four protons for each pair of electrons.'],
  ['Complex II, which does not pump protons, is:', ['Succinate dehydrogenase, which is also a Krebs cycle enzyme', 'Cytochrome *bc*₁', 'NADH dehydrogenase', 'Cytochrome oxidase'], 0,
    'It passes electrons from FADH₂ to ubiquinone.'],
  ['Complex III (cytochrome *bc*₁) transfers electrons from:', ['Ubiquinol to cytochrome *c*, using the Q cycle', 'NADH to ubiquinone', 'Cytochrome *c* to O₂', 'Succinate to FAD'], 0,
    'It pumps protons into the intermembrane space.'],
  ['Complex IV (cytochrome *c* oxidase):', ['Reduces O₂ to water', 'Oxidises NADH', 'Makes ATP', 'Reduces ubiquinone'], 0,
    'It contains haem iron and copper centres.'],
  ['The two mobile electron carriers of the chain are:', ['Ubiquinone (in the membrane) and cytochrome *c* (on its outer surface)', 'NAD⁺ and FAD', 'Plastocyanin and ferredoxin', 'ATP and ADP'], 0,
    'They shuttle electrons between the complexes.'],
  ['Match the inhibitor with its site:', ['Rotenone — complex I; antimycin A — complex III; cyanide — complex IV; oligomycin — ATP synthase', 'Rotenone — complex IV; cyanide — complex I', 'Oligomycin — complex II; antimycin — complex I', 'Cyanide — ATP synthase'], 0,
    'Such inhibitors helped work out the sequence of carriers.'],
  ['Plant mitochondria have a cyanide-resistant alternative oxidase (AOX), which:', ['Passes electrons from ubiquinol directly to O₂ without pumping protons', 'Makes extra ATP', 'Replaces ATP synthase', 'Needs cyanide to work'], 0,
    'The energy is released as heat.'],
  ['The heat produced by the alternative oxidase warms the flowering spadix of:', ['Aroids such as *Arum* and *Symplocarpus*', 'Wheat', 'Rose', 'Pine'], 0,
    'The heat helps volatilise scents that attract pollinators.'],
  ['Plant mitochondria also have rotenone-insensitive NAD(P)H dehydrogenases that:', ['Oxidise NAD(P)H without pumping protons', 'Make ATP directly', 'Fix CO₂', 'Split water'], 0,
    'They are found on both sides of the inner membrane.'],
  ['The approximate P/O ratios are:', ['About 2.5 for NADH and 1.5 for FADH₂', 'Three for both', 'One for both', 'Four for NADH and two for FADH₂'], 0,
    'The older textbook values were 3 and 2.']
] },
{ p: 'B2', t: 'Genetics', w: 2, pyq: 'IFoS-2017-B2-Q1b', q: [
  ['In humans, maleness is determined by:', ['The *SRY* gene on the Y chromosome', 'The number of X chromosomes alone', 'Temperature', 'The mother’s diet'], 0,
    'SRY switches on testis development.'],
  ['In *Drosophila*, sex is determined by:', ['The ratio of X chromosomes to autosome sets (X:A), acting through the *Sxl* gene', 'The presence of a Y chromosome', 'Temperature', 'The number of autosomes only'], 0,
    'Bridges proposed this "genic balance" theory.'],
  ['In *Melandrium* (*Silene latifolia*), sex is determined by:', ['An XY system with a strongly male-determining Y chromosome', 'The X:A ratio', 'Temperature', 'A single autosomal gene'], 0,
    'The Y carries genes that promote stamens and suppress the gynoecium.'],
  ['In cucumber, femaleness is promoted by:', ['Ethylene, via ACC synthase genes such as *F* (*CsACS1G*) and *M* (*CsACS2*)', 'Gibberellin', 'Auxin alone', 'Darkness'], 0,
    'Gibberellin promotes male flowers.'],
  ['In maize, the *tasselseed* (*ts*) mutation:', ['Converts the tassel into a female (seed-bearing) inflorescence', 'Makes the plant sterile', 'Removes the ear', 'Makes all flowers male'], 0,
    'Combining it with *barren stalk* (*ba*) can turn maize dioecious.'],
  ['The first sex-determining gene identified in a plant (2014) was *OGI* of persimmon (*Diospyros lotus*), which:', ['Makes a small RNA that silences the feminising gene *MeGI*', 'Codes for ethylene', 'Is on an autosome', 'Controls fruit colour'], 0,
    'It sits on the Y chromosome.'],
  ['In papaya, sex is controlled by:', ['Young sex chromosomes: XX female, XY male and XYʰ hermaphrodite', 'Temperature only', 'The X:A ratio', 'Ethylene only'], 0,
    'The male-specific region of the Y is small and recent.'],
  ['In the liverwort *Marchantia*, sex is determined in the haploid gametophyte by:', ['U (female) and V (male) sex chromosomes', 'An XY system in the sporophyte', 'Temperature', 'Light'], 0,
    'This is the UV system of haploid organisms.'],
  ['In the marine worm *Bonellia*, sex is determined by:', ['The environment — larvae that settle on a female become males', 'The X:A ratio', 'Chromosomes only', 'Diet only'], 0,
    'This is a classic case of environmental sex determination.'],
  ['In birds, females are:', ['ZW (heterogametic)', 'ZZ', 'XX', 'XO'], 0,
    'Males are ZZ.']
] },
{ p: 'B2', t: 'Genetics', w: 1, pyq: 'IFoS-2017-B2-Q1c', q: [
  ['Accessory (B) chromosomes are:', ['Extra, dispensable chromosomes present in addition to the normal A set', 'Sex chromosomes', 'Chromosomes of chloroplasts', 'Normal autosomes'], 0,
    'Plants can live normally without them.'],
  ['B chromosomes are commonly found in:', ['Maize, rye and many grasses', 'Humans only', 'Bacteria', 'Viruses'], 0,
    'They are known from over a thousand plant species.'],
  ['B chromosomes are usually:', ['Largely heterochromatic and poor in functional genes', 'Rich in essential genes', 'Always longer than A chromosomes', 'Found only in gametes'], 0,
    'They do not pair with the A chromosomes.'],
  ['B chromosomes are inherited:', ['In a non-Mendelian way, often by "drive" that increases their frequency', 'Strictly by Mendel’s laws', 'Only through the mother', 'Never'], 0,
    'This is why they are sometimes called selfish chromosomes.'],
  ['In maize, B chromosomes accumulate because:', ['They undergo non-disjunction at the second pollen mitosis, and the sperm carrying them preferentially fertilises the egg', 'They are lost at meiosis', 'They are needed for fertility', 'They are carried by chloroplasts'], 0,
    'This combination is their drive mechanism.'],
  ['Large numbers of B chromosomes usually:', ['Reduce vigour and fertility', 'Increase yield', 'Have no effect at all', 'Make plants polyploid'], 0,
    'A few Bs are usually harmless.'],
  ['The number of B chromosomes:', ['Varies between individuals of the same population', 'Is fixed in a species', 'Is always two', 'Is always zero in plants'], 0,
    'Some cells or tissues may lack them.'],
  ['In maize genetics, B–A translocations have been used to:', ['Locate genes on particular chromosome arms', 'Make hybrids', 'Produce haploids only', 'Control pests'], 0,
    'Roman developed the method in 1947.'],
  ['B chromosomes differ from sex chromosomes in that they are:', ['Not needed for normal development or sex determination', 'Always needed for sex determination', 'Present only in males', 'Present only in females'], 0,
    'They are extra genetic material.'],
  ['B chromosomes are significant in studying:', ['Genome evolution and selfish DNA', 'Photosynthesis', 'Nitrogen fixation', 'Seed dormancy only'], 0,
    'They may arise from fragments of A chromosomes.']
] },
{ p: 'B2', t: 'Biotechnology & GM Crops', w: 3, pyq: 'IFoS-2017-B2-Q1d', q: [
  ['The GM crop approved for commercial cultivation in India in 2002 is:', ['Bt cotton', 'Bt brinjal', 'Golden rice', 'HT soybean'], 0,
    'It carries *cry* genes from *Bacillus thuringiensis*.'],
  ['GM crops in India are approved by the:', ['Genetic Engineering Appraisal Committee (GEAC), under the Environment Ministry', 'ICAR alone', 'FSSAI alone', 'The Seed Certification Agency'], 0,
    'It works under the 1989 Rules of the Environment (Protection) Act, 1986.'],
  ['Bt brinjal was placed under a moratorium in India in:', ['2010', '2002', '2015', '2020'], 0,
    'It is grown in Bangladesh.'],
  ['A major merit of Bt cotton in India was:', ['Fewer insecticide sprays against bollworms and higher yields in its early years', 'Resistance to all pests', 'Lower seed prices', 'Tolerance to drought'], 0,
    'India became a leading cotton exporter.'],
  ['A major problem with Bt cotton in India has been:', ['Resistance of the pink bollworm to Bt proteins (Cry1Ac and Cry2Ab)', 'Loss of all yield', 'Toxicity to humans', 'Resistance of weeds'], 0,
    'Resistance became widespread by about 2015.'],
  ['The "refuge" strategy with Bt crops means:', ['Growing some non-Bt plants so susceptible insects survive and resistance is delayed', 'Spraying more insecticide', 'Growing only Bt plants', 'Irrigating more'], 0,
    'In "refuge in bag", the non-Bt seed is mixed into the packet.'],
  ['GM mustard DMH-11, approved for environmental release by GEAC in 2022, uses:', ['The barnase–barstar system for hybrid seed production', 'A Bt gene', 'A herbicide-tolerance gene only', 'Golden rice genes'], 0,
    'Its commercial release is before the Supreme Court — check the current status.'],
  ['Other concerns about GM crops include:', ['Gene flow to relatives, effects on non-target organisms and high seed cost', 'Only better yields', 'Lower pesticide use only', 'No concerns at all'], 0,
    'Illegal herbicide-tolerant Bt cotton has also spread.'],
  ['India’s rules on genome editing (2022) exempt from GM regulation:', ['SDN-1 and SDN-2 edited plants without foreign DNA', 'All transgenic plants', 'Bt cotton', 'Plants with foreign genes'], 0,
    'Two genome-edited rice varieties were released in 2025.'],
  ['The Bt toxin gene in Bollgard cotton comes from:', ['*Bacillus thuringiensis*', '*Agrobacterium tumefaciens*', '*Escherichia coli*', '*Streptomyces*'], 0,
    'Cry proteins destroy the gut lining of susceptible caterpillars.']
] },
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 3, pyq: 'IFoS-2017-B2-Q1e', q: [
  ['The chi-square statistic is calculated as:', ['Σ (O − E)² ÷ E', 'Σ (O − E) ÷ O', 'Σ O ÷ E', '(O + E)²'], 0,
    'O is the observed and E the expected frequency.'],
  ['The chi-square test was developed by:', ['Karl Pearson (1900)', 'R. A. Fisher', 'W. S. Gosset', 'Francis Galton'], 0,
    'Gosset ("Student") developed the t-test.'],
  ['For a goodness-of-fit test with *n* classes, the degrees of freedom are:', ['*n* − 1', '*n*', '*n* + 1', '2*n*'], 0,
    'A 3:1 ratio has two classes, so one degree of freedom.'],
  ['The table value of χ² at 5% for one degree of freedom is:', ['3.84', '5.99', '7.82', '1.96'], 0,
    '5.99 and 7.82 are the values for two and three degrees of freedom.'],
  ['The table value of χ² at 5% for testing a 9:3:3:1 ratio (three degrees of freedom) is:', ['7.82', '3.84', '5.99', '9.49'], 0,
    'Four classes give three degrees of freedom.'],
  ['If the calculated χ² is less than the table value at 5%, then:', ['The deviation is due to chance, and the expected ratio is accepted', 'The expected ratio is rejected', 'The experiment is invalid', 'More data are always needed'], 0,
    'The null hypothesis is not rejected.'],
  ['Observed 290 tall : 110 dwarf against an expected 3:1 (300:100) gives χ² of about:', ['1.33 — a good fit', '13.3 — a poor fit', '0.13', '33.3'], 0,
    '(10² ÷ 300) + (10² ÷ 100) = 0.33 + 1 = 1.33.'],
  ['Yates’ correction is applied when:', ['There is one degree of freedom and some expected frequencies are small', 'There are many classes', 'Data are percentages', 'Samples are very large'], 0,
    'It subtracts 0.5 from each |O − E|.'],
  ['The degrees of freedom for an r × c contingency table are:', ['(r − 1)(c − 1)', 'r × c', 'r + c', 'r − c'], 0,
    'A 2 × 2 table has one degree of freedom.'],
  ['The chi-square test should be applied to:', ['Actual counts (frequencies), not percentages or means', 'Percentages only', 'Means', 'Standard deviations'], 0,
    'Using percentages gives misleading results.']
] },
{ p: 'B2', t: 'Genetics', w: 3, pyq: 'IFoS-2017-B2-Q2a', q: [
  ['Euploidy differs from aneuploidy in that euploidy involves:', ['Whole sets of chromosomes, while aneuploidy involves single chromosomes', 'Single chromosomes', 'Gene mutations only', 'Loss of the nucleus'], 0,
    'Polyploids are euploids.'],
  ['A trisomic has the chromosome number:', ['2*n* + 1', '2*n* − 1', '2*n* − 2', '3*n*'], 0,
    'A monosomic is 2*n* − 1 and a nullisomic is 2*n* − 2.'],
  ['Bread wheat (AABBDD) is an example of:', ['An allohexaploid', 'An autotetraploid', 'A monoploid', 'A trisomic'], 0,
    'It arose from hybridisation of three diploid species.'],
  ['Triploid dessert bananas (AAA) are:', ['Autotriploids, and therefore seedless', 'Allohexaploids', 'Haploids', 'Aneuploids'], 0,
    'Seedless watermelons are also triploid.'],
  ['Colchicine induces polyploidy by:', ['Binding tubulin and preventing spindle formation', 'Breaking chromosomes', 'Causing point mutations', 'Blocking DNA replication'], 0,
    'The chromosomes divide but the cell does not.'],
  ['Karpechenko’s *Raphanobrassica* (1927) showed that:', ['Allopolyploidy can create a new fertile species from a sterile hybrid', 'Aneuploids are fertile', 'Deletions are harmless', 'Polyploids cannot be made'], 0,
    'Doubling the hybrid’s chromosomes restored fertility.'],
  ['The four types of structural chromosome change are:', ['Deletion, duplication, inversion and translocation', 'Monosomy, trisomy, nullisomy and polyploidy', 'Transition, transversion, insertion and silent', 'Mitosis, meiosis, fission and fusion'], 0,
    'Structural changes alter gene order or number.'],
  ['The Bar-eye phenotype of *Drosophila* is caused by:', ['A duplication', 'A deletion', 'An inversion', 'Trisomy'], 0,
    'Unequal crossing over can create double-Bar.'],
  ['The Philadelphia chromosome of chronic myeloid leukaemia results from:', ['A reciprocal translocation between chromosomes 9 and 22', 'Trisomy 21', 'A deletion in 5p', 'An inversion of chromosome 1'], 0,
    'It creates the BCR–ABL fusion gene.'],
  ['The nullisomic series of Chinese Spring wheat, developed by E. R. Sears, is used to:', ['Assign genes to particular chromosomes', 'Make hybrids', 'Make haploids', 'Control rust'], 0,
    'Polyploid wheat tolerates the loss of a chromosome pair.']
] },
{ p: 'B2', t: 'Genetics', w: 3, pyq: 'IFoS-2017-B2-Q2b', q: [
  ['At pachytene, a reciprocal translocation heterozygote forms:', ['A cross-shaped figure of four paired chromosomes', 'A loop', 'A bridge', 'Normal bivalents only'], 0,
    'All four chromosomes pair along homologous segments.'],
  ['At metaphase I, a translocation heterozygote shows:', ['A ring or chain of four chromosomes', 'Only bivalents', 'Univalents only', 'A dicentric bridge'], 0,
    'The shape depends on where chiasmata form.'],
  ['In a translocation heterozygote, only alternate segregation gives viable gametes, so the plant shows:', ['About 50% pollen sterility (semi-sterility)', 'Complete fertility', 'Complete sterility', 'Increased fertility'], 0,
    'Adjacent segregation gives gametes with duplications and deficiencies.'],
  ['*Oenothera lamarckiana* shows a ring of 14 chromosomes at meiosis because it is:', ['A complex translocation heterozygote (Renner complexes)', 'A polyploid', 'A haploid', 'A trisomic'], 0,
    'This explained de Vries’s so-called "mutations".'],
  ['In a paracentric inversion heterozygote, a crossover inside the inversion loop produces at anaphase I:', ['A dicentric bridge and an acentric fragment', 'Normal chromatids only', 'A ring of four', 'Univalents'], 0,
    'The inversion does not include the centromere.'],
  ['In a pericentric inversion heterozygote, a crossover inside the loop produces:', ['Chromatids with duplications and deficiencies, but no bridge', 'A dicentric bridge', 'An acentric fragment', 'Normal gametes only'], 0,
    'The inversion includes the centromere.'],
  ['Inversions act as "crossover suppressors" because:', ['Recombinant chromatids from the inverted region give inviable gametes', 'Chiasmata cannot form', 'Chromosomes do not pair', 'DNA is not replicated'], 0,
    'Muller’s ClB method used this property.'],
  ['At pachytene, a heterozygote for a duplication or deletion shows:', ['An unpaired loop (buckle) in the bivalent', 'A cross-shaped figure', 'A ring of four', 'A bridge'], 0,
    'The extra or missing segment has nothing to pair with.'],
  ['A Robertsonian translocation is:', ['The fusion of two acrocentric chromosomes at their centromeres', 'The loss of a whole chromosome', 'An inversion', 'A duplication'], 0,
    'It lowers the chromosome number without losing much DNA.'],
  ['Semi-sterility in a plant suggests that it is:', ['A translocation heterozygote', 'A pure line', 'A haploid', 'A hybrid with no chromosome changes'], 0,
    'Its pollen is about half sterile.']
] },
{ p: 'B2', t: 'Molecular Biology', w: 2, pyq: 'IFoS-2017-B2-Q3a', q: [
  ['The "RNA world" hypothesis, named by Walter Gilbert (1986), proposes that:', ['Early life used RNA both to store information and to catalyse reactions', 'DNA came before RNA', 'Proteins came first', 'Life began with lipids alone'], 0,
    'DNA and proteins took over these roles later.'],
  ['The discovery that RNA can act as an enzyme (ribozyme) earned the 1989 Nobel Prize for:', ['Thomas Cech and Sidney Altman', 'Watson and Crick', 'Kornberg and Ochoa', 'Nirenberg and Khorana'], 0,
    'Cech worked on self-splicing *Tetrahymena* rRNA; Altman on RNase P.'],
  ['The peptidyl transferase activity of the ribosome is carried out by:', ['The large-subunit rRNA (23S in bacteria)', 'A ribosomal protein', 'tRNA', 'mRNA'], 0,
    'This makes the ribosome itself a ribozyme.'],
  ['The Miller–Urey experiment (1953) showed that:', ['Amino acids can form from simple gases in a simulated early atmosphere', 'DNA can replicate without enzymes', 'Cells arise spontaneously', 'RNA is unstable'], 0,
    'Energy was supplied by electric sparks.'],
  ['Evidence that RNA came before DNA includes the fact that:', ['Deoxyribonucleotides are made from ribonucleotides by ribonucleotide reductase', 'DNA is less stable', 'RNA has thymine', 'DNA makes RNA without enzymes'], 0,
    'The building blocks of DNA are made from those of RNA.'],
  ['DNA replaced RNA as the main genetic material because DNA is:', ['More stable — no 2′-OH, and thymine allows repair of cytosine deamination', 'More catalytic', 'Single-stranded', 'Shorter'], 0,
    'Stable storage allowed genomes to grow larger.'],
  ['Viroids, which may be relics of the RNA world, are:', ['Small, circular, non-coding RNAs that infect plants without any protein coat', 'DNA viruses', 'Bacteria', 'Prions'], 0,
    'Diener described potato spindle tuber viroid in 1971.'],
  ['Coenzymes such as ATP, NAD⁺, FAD and coenzyme A contain ribonucleotides. They are seen as:', ['Molecular fossils of an RNA-based metabolism', 'Recent inventions', 'Proteins', 'Lipids'], 0,
    'Their nucleotide parts are not needed for their chemistry.'],
  ['Reverse transcriptase, which copies RNA into DNA, occurs in:', ['Retroviruses, retrotransposons and telomerase', 'All bacteria', 'Chloroplasts only', 'Ribosomes'], 0,
    'It shows that information can flow from RNA to DNA.'],
  ['Spiegelman’s experiments with Qβ replicase showed that:', ['RNA molecules can evolve in a test tube under selection', 'DNA cannot mutate', 'Proteins can replicate', 'RNA cannot be copied'], 0,
    'Faster-replicating short RNAs took over ("Spiegelman’s monster").']
] },
{ p: 'B2', t: 'Genetics', w: 2, pyq: 'IFoS-2017-B2-Q3b', q: [
  ['Papaya plants occur in three sex forms:', ['Male, female and hermaphrodite', 'Male and female only', 'Hermaphrodite only', 'Monoecious only'], 0,
    'This three-way system is a classic example of tripartite sex determination.'],
  ['Hofmeyr and Storey explained papaya sex by a single gene with three alleles. The male genotype is:', ['*M₁m*', '*M₂m*', '*mm*', '*M₁M₂*'], 0,
    'Hermaphrodites are *M₂m* and females are *mm*.'],
  ['In papaya, the genotypes *M₁M₁*, *M₁M₂* and *M₂M₂* are:', ['Lethal — the zygotes abort', 'All male', 'All female', 'All hermaphrodite'], 0,
    'This distorts the segregation ratios.'],
  ['Selfing a hermaphrodite papaya (*M₂m*) gives:', ['Two hermaphrodites to one female', 'Three hermaphrodites to one female', 'All hermaphrodite', 'One male to one female'], 0,
    'The *M₂M₂* quarter dies.'],
  ['Crossing a female (*mm*) with a male (*M₁m*) papaya gives:', ['One female to one male', 'All male', 'All female', 'Two hermaphrodites to one female'], 0,
    'This is typical of dioecious varieties.'],
  ['Molecular studies show that papaya sex chromosomes are:', ['XX in females, XY in males and XYʰ in hermaphrodites', 'ZW in females', 'XO in males', 'Absent'], 0,
    'The Y is a young, recently evolved sex chromosome.'],
  ['In the squirting cucumber (*Ecballium elaterium*), sex is controlled by three alleles in the order of dominance:', ['*aᴰ* (male) > *a⁺* (monoecious) > *aᵈ* (female)', '*aᵈ* > *a⁺* > *aᴰ*', '*a⁺* > *aᴰ* > *aᵈ*', 'They are codominant'], 0,
    'Different allele combinations give dioecious or monoecious plants.'],
  ['Gynodioecious papaya varieties (female and hermaphrodite plants only) are preferred because:', ['Every plant bears fruit, since there are no males', 'They are all male', 'They produce no fruit', 'They need no pollination'], 0,
    'Coorg Honey Dew and Red Lady are examples.'],
  ['High summer temperatures can make hermaphrodite papaya plants:', ['Temporarily female-sterile (sex reversal towards maleness)', 'Female', 'Die', 'Seedless'], 0,
    'Sex expression is sensitive to the environment.'],
  ['Papaya seedlings are often planted three per pit because:', ['Their sex cannot be seen until flowering, so extra males can then be removed', 'They need support', 'They grow slowly', 'It is traditional'], 0,
    'About one male per ten females is kept for pollination.']
] },
{ p: 'B2', t: 'Genetics', w: 3, pyq: 'IFoS-2017-B2-Q4a', q: [
  ['A transition mutation is:', ['A change from one purine to another, or one pyrimidine to another', 'A purine replaced by a pyrimidine', 'The insertion of a base', 'The deletion of a base'], 0,
    'A purine–pyrimidine swap is a transversion.'],
  ['Frameshift mutations are caused by:', ['Insertion or deletion of bases in numbers that are not multiples of three', 'Base substitutions', 'Silent changes', 'Methylation'], 0,
    'Acridine dyes such as proflavin cause them.'],
  ['Watson and Crick suggested that spontaneous mutations can arise from:', ['Tautomeric shifts that let bases mispair', 'Ribosome errors', 'Protein misfolding', 'Membrane damage'], 0,
    'Rare enol and imino forms pair with the wrong bases.'],
  ['5-Bromouracil causes mutations because:', ['It is a thymine analogue that can pair with guanine, causing AT ↔ GC transitions', 'It breaks DNA strands', 'It inserts extra bases', 'It forms thymine dimers'], 0,
    '2-Aminopurine is another base analogue.'],
  ['EMS causes mutations mainly by:', ['Ethylating guanine to O⁶-ethylguanine, which pairs with thymine (GC → AT)', 'Deaminating cytosine', 'Forming dimers', 'Intercalating between bases'], 0,
    'It is the most widely used chemical mutagen in plant breeding.'],
  ['Nitrous acid causes mutations by:', ['Deaminating bases — cytosine to uracil and adenine to hypoxanthine', 'Alkylating guanine', 'Breaking both strands', 'Forming dimers'], 0,
    'The deaminated bases pair wrongly.'],
  ['Ultraviolet light damages DNA mainly by forming:', ['Pyrimidine (thymine) dimers', 'Double-strand breaks', 'Alkylated bases', 'Frameshifts'], 0,
    'Photolyase or nucleotide excision repair removes them.'],
  ['Ionising radiation such as gamma rays mainly causes:', ['Double-strand breaks and chromosome aberrations', 'Thymine dimers only', 'Tautomeric shifts only', 'Methylation'], 0,
    'It is widely used for mutation breeding.'],
  ['A nonsense mutation:', ['Changes a codon into a stop codon, shortening the protein', 'Changes one amino acid', 'Has no effect on the protein', 'Adds amino acids'], 0,
    'A missense mutation changes an amino acid; a silent one changes none.'],
  ['Barbara McClintock showed that mutations in maize kernel colour can be caused by:', ['Transposable elements (*Ac*/*Ds*) inserting into genes', 'Viruses', 'Radiation only', 'Hybridisation'], 0,
    'She received the Nobel Prize in 1983.']
] },
{ p: 'B2', t: 'Biotechnology & GM Crops', w: 3, pyq: 'IFoS-2017-B2-Q4b', q: [
  ['*Agrobacterium*-mediated transformation transfers:', ['T-DNA from the Ti plasmid into the plant genome', 'The whole bacterial chromosome', 'Ribosomes', 'Proteins only'], 0,
    'T-DNA is flanked by 25 bp border repeats.'],
  ['The *vir* genes of *Agrobacterium* are switched on by:', ['Phenolic compounds such as acetosyringone from wounded plant cells', 'Light', 'Auxin', 'Cold'], 0,
    'Acetosyringone is often added to co-cultivation media.'],
  ['The binary vector system has:', ['T-DNA and the *vir* genes on two separate plasmids', 'No T-DNA', 'Two chromosomes', 'Only a selectable marker'], 0,
    'The small T-DNA plasmid is easy to engineer.'],
  ['The gene gun (biolistics), developed by Sanford (1987), delivers DNA on:', ['Gold or tungsten microparticles', 'Viruses', 'Bacteria', 'Pollen tubes'], 0,
    'It works in species hard to transform with *Agrobacterium*.'],
  ['Electroporation introduces DNA into protoplasts by:', ['Short electric pulses that open temporary pores in the membrane', 'Heat shock', 'Viruses', 'Ultrasound only'], 0,
    'PEG treatment is another way to get DNA into protoplasts.'],
  ['The "floral dip" method (Clough and Bent, 1998) transforms *Arabidopsis* by:', ['Dipping flowers in an *Agrobacterium* suspension, so that seeds are transformed', 'Bombarding leaves', 'Injecting roots', 'Grafting'], 0,
    'It needs no tissue culture.'],
  ['Common selectable marker genes in plant transformation include:', ['*nptII* (kanamycin), *hpt* (hygromycin) and *bar* (phosphinothricin)', '*Bt* only', '*Sub1*', '*Rht*'], 0,
    'Only transformed cells survive on the selective medium.'],
  ['Chloroplast transformation is attractive because:', ['Transgenes are expressed at high levels and are not spread by pollen', 'It is easy in all crops', 'It gives haploids', 'It needs no selection'], 0,
    'Plastid genes are usually inherited maternally.'],
  ['Microinjection delivers DNA:', ['Directly into cells or nuclei with a fine glass needle', 'Using bacteria', 'Using pollen', 'Using electric pulses'], 0,
    'It is slow and used mainly for special purposes.'],
  ['CRISPR–Cas9 components can be delivered into plant cells:', ['By *Agrobacterium*, biolistics or as preassembled ribonucleoproteins (RNPs)', 'Only by grafting', 'Only through the soil', 'Only by cross-pollination'], 0,
    'RNP delivery can give edited plants without foreign DNA.']
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 2, pyq: 'IFoS-2017-B2-Q5a', q: [
  ['The term "allelopathy" was coined in 1937 by:', ['Hans Molisch', 'E. L. Rice', 'A. G. Tansley', 'E. P. Odum'], 0,
    'Rice later wrote the standard book on it.'],
  ['Allelopathy is:', ['The effect of one plant on another through chemicals it releases', 'Competition for light only', 'Parasitism', 'Pollination'], 0,
    'The effect is usually inhibitory.'],
  ['Juglone, a classic allelochemical, is produced by:', ['Walnut (*Juglans*)', 'Rice', 'Wheat', 'Pea'], 0,
    'Few plants grow under walnut trees.'],
  ['Sorgoleone, exuded by the root hairs of sorghum:', ['Suppresses weeds', 'Fixes nitrogen', 'Attracts pollinators', 'Promotes weed growth'], 0,
    'Sorghum residues are used as weed-suppressing mulch.'],
  ['*Parthenium hysterophorus* spreads partly because it releases the allelochemical:', ['Parthenin', 'Juglone', 'Sorgoleone', 'Momilactone'], 0,
    'It also causes dermatitis in people.'],
  ['Allelochemicals are released by:', ['Volatilisation, leaching from leaves, root exudation and decay of residues', 'Photosynthesis only', 'Pollination', 'Seed dispersal'], 0,
    'Many are phenolics or terpenoids.'],
  ['The sparse undergrowth in *Eucalyptus* plantations is partly due to:', ['Allelopathic phenolics and volatile terpenes', 'Nitrogen fixation', 'Excess water', 'Soil acidity only'], 0,
    'Competition for water adds to the effect.'],
  ['Allelopathic rice varieties release:', ['Momilactones, which suppress weeds such as barnyard grass', 'Juglone', 'Parthenin', 'Nicotine'], 0,
    'They may help reduce herbicide use.'],
  ['Autotoxicity, in which a plant inhibits its own species, causes:', ['Replant problems, e.g., in alfalfa and asparagus', 'Better yields', 'Faster germination', 'Nothing'], 0,
    'Crop rotation helps avoid it.'],
  ['The invasive shrub *Lantana camara* suppresses native plants partly through:', ['Allelopathic compounds such as lantadenes', 'Nitrogen fixation', 'Pollination', 'Shade only'], 0,
    'It has invaded large areas of Indian forest.']
] },
{ p: 'B2', t: 'Biotechnology & GM Crops', w: 2, pyq: 'IFoS-2017-B2-Q5b', q: [
  ['Plant varieties in India are protected under the:', ['Protection of Plant Varieties and Farmers’ Rights (PPV&FR) Act, 2001', 'Patents Act, 1970', 'Seeds Act, 1966', 'Trade Marks Act'], 0,
    'The PPV&FR Authority was set up in 2005.'],
  ['TRIPS Article 27.3(b) requires WTO members to protect plant varieties by:', ['Patents, an effective sui generis system, or both', 'Only patents', 'Only trade secrets', 'Nothing'], 0,
    'India chose a sui generis system (PPV&FR).'],
  ['UPOV is the:', ['International Union for the Protection of New Varieties of Plants (1961)', 'UN Office for Plants', 'World Seed Bank', 'Indian patent office'], 0,
    'India is not a UPOV member.'],
  ['Under the PPV&FR Act, farmers may:', ['Save, use, sow, resow, exchange, share and sell their farm produce, including seed, but not branded seed', 'Only buy seed', 'Not save any seed', 'Sell branded seed of protected varieties'], 0,
    'This farmers’ right is unique to India’s law.'],
  ['Protection under the PPV&FR Act lasts for:', ['Fifteen years for field crops and eighteen years for trees and vines', 'Five years for all', 'Fifty years', 'For ever'], 0,
    'Extant varieties are protected for fifteen years from notification.'],
  ['Under Section 3(j) of India’s Patents Act, the following cannot be patented:', ['Plants, animals, seeds and essentially biological processes', 'Microorganisms', 'Chemical fertilisers', 'Machines'], 0,
    'Microorganisms can be patented.'],
  ['The US patent on turmeric for wound healing was revoked in 1997 after a challenge by:', ['CSIR, citing traditional knowledge', 'ICAR', 'NABARD', 'WHO'], 0,
    'A European patent on a neem fungicide was also revoked.'],
  ['Geographical Indications in India are registered under:', ['The Geographical Indications of Goods Act, 1999', 'The Patents Act', 'The Seeds Act', 'The PPV&FR Act'], 0,
    'Darjeeling tea was the first GI.'],
  ['Under the Biological Diversity Act, 2002, anyone seeking IPR based on Indian biological resources must get approval from:', ['The National Biodiversity Authority', 'The Supreme Court', 'ICAR', 'The Patent Office alone'], 0,
    'It also governs access and benefit-sharing.'],
  ['In the 2019 PepsiCo potato case, the key issue was:', ['Farmers’ rights under the PPV&FR Act to grow a registered variety (FL-2027)', 'A patent on potato genes', 'Pesticide residues', 'A trade mark on chips'], 0,
    'PepsiCo withdrew the suits; the variety’s registration was then challenged before the PPV&FR Authority and courts — check the current status.']
] },
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 3, pyq: 'IFoS-2017-B2-Q5c', q: [
  ['RFLP, the first DNA marker, is:', ['Hybridisation-based and codominant', 'PCR-based and dominant', 'A protein marker', 'A morphological marker'], 0,
    'Botstein and colleagues used it for mapping in 1980.'],
  ['RAPD markers are:', ['PCR-based with random decamer primers, and usually dominant', 'Hybridisation-based and codominant', 'Protein-based', 'Always multi-allelic and codominant'], 0,
    'They are cheap but poorly reproducible.'],
  ['SSR (microsatellite) markers are favoured because they are:', ['Codominant, highly polymorphic and multi-allelic', 'Dominant and rare', 'Protein-based', 'Invisible'], 0,
    'They are short tandem repeats of 1–6 bases.'],
  ['AFLP (Vos et al., 1995) combines:', ['Restriction digestion with selective PCR amplification', 'Protein electrophoresis', 'Microscopy', 'Field observation only'], 0,
    'It detects many loci at once.'],
  ['The most abundant type of marker in genomes, used in high-throughput arrays, is the:', ['Single-nucleotide polymorphism (SNP)', 'RFLP', 'RAPD', 'Isozyme'], 0,
    'Genotyping-by-sequencing detects thousands of SNPs.'],
  ['A codominant marker can:', ['Distinguish heterozygotes from homozygotes', 'Only show presence or absence', 'Never be used in breeding', 'Only mark sex'], 0,
    'This is important in backcross breeding.'],
  ['Swarna-Sub1 rice was developed by marker-assisted backcrossing to transfer:', ['The *Sub1A* submergence-tolerance gene from FR13A', 'A *Bt* gene', 'The semi-dwarf gene *sd1*', 'A *Xa21* gene only'], 0,
    'It survives up to about two weeks under water.'],
  ['Improved Samba Mahsuri rice combines the bacterial blight resistance genes:', ['*Xa21*, *xa13* and *xa5*', '*Sub1* and *Saltol*', '*Pi54* only', '*Bt* and *bar*'], 0,
    'It was developed by IIRR and CCMB.'],
  ['Combining several resistance genes into one variety with the help of markers is called:', ['Gene pyramiding', 'Gene silencing', 'Mutation breeding', 'Hybridisation only'], 0,
    'It makes resistance more durable.'],
  ['QTL mapping identifies:', ['Chromosome regions controlling quantitative traits', 'Only single-gene traits', 'Chloroplast genes', 'Plant pathogens'], 0,
    'Markers linked to QTLs are then used in selection.']
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 2, pyq: 'IFoS-2017-B2-Q5d', q: [
  ['As accessory pigments, carotenoids:', ['Absorb blue light (about 400–500 nm) and pass the energy to chlorophyll', 'Absorb only red light', 'Fix CO₂', 'Split water'], 0,
    'They widen the range of light used in photosynthesis.'],
  ['Carotenoids protect the photosynthetic apparatus by:', ['Quenching triplet chlorophyll and singlet oxygen', 'Absorbing water', 'Making ATP', 'Transporting sugars'], 0,
    'Mutants without carotenoids bleach in the light.'],
  ['The xanthophyll cycle converts violaxanthin to zeaxanthin in:', ['High light, helping dissipate excess energy as heat (NPQ)', 'Darkness', 'Low light only', 'Roots'], 0,
    'Violaxanthin de-epoxidase catalyses the conversion.'],
  ['The plant hormone derived from carotenoids is:', ['Abscisic acid (ABA)', 'Auxin', 'Gibberellin', 'Cytokinin'], 0,
    'It is made via xanthoxin from 9-cis-epoxy carotenoids.'],
  ['Strigolactones, which regulate shoot branching and signal to mycorrhizal fungi, are derived from:', ['β-Carotene', 'Tryptophan', 'Adenine', 'Methionine'], 0,
    'The enzymes D27, CCD7 and CCD8 are involved.'],
  ['The red colour of tomato comes from lycopene, and the red colour of chilli from:', ['Capsanthin', 'Anthocyanin', 'Betanin', 'Chlorophyll'], 0,
    'β-carotene gives carrots their orange colour.'],
  ['The first committed step of carotenoid synthesis is catalysed by:', ['Phytoene synthase (PSY)', 'Rubisco', 'PAL', 'Chalcone synthase'], 0,
    'It joins two GGPP molecules into phytoene.'],
  ['Golden Rice makes β-carotene in its grain by expressing:', ['*psy* (phytoene synthase) and bacterial *crtI*', 'A *Bt* gene', '*Sub1*', 'Chalcone synthase'], 0,
    'Its yellow colour comes from provitamin A.'],
  ['Herbicides such as norflurazon and fluridone cause white (bleached) leaves by:', ['Inhibiting phytoene desaturase, blocking carotenoid synthesis', 'Blocking photosystem II directly', 'Inhibiting amino acid synthesis', 'Blocking auxin'], 0,
    'Without carotenoids, chlorophyll is destroyed by light.'],
  ['Carotenoids are located in:', ['Plastids — chloroplasts and chromoplasts', 'Vacuoles', 'The nucleus', 'Cell walls'], 0,
    'Water-soluble anthocyanins are stored in vacuoles.']
] },
{ p: 'B2', t: 'Evolution', w: 2, pyq: 'IFoS-2017-B2-Q5e', q: [
  ['Homologous organs:', ['Have the same origin but may serve different functions', 'Have different origins but the same function', 'Are always vestigial', 'Are found only in animals'], 0,
    'Examples are the forelimbs of vertebrates.'],
  ['Thorns of *Bougainvillea* and tendrils of *Cucurbita* are:', ['Homologous — both are modified axillary shoots', 'Analogous', 'Vestigial', 'Unrelated'], 0,
    'They develop from the same position.'],
  ['Potato tubers (stems) and sweet potato tubers (roots) are:', ['Analogous organs', 'Homologous organs', 'Vestigial organs', 'Atavistic'], 0,
    'Analogous organs point to convergent evolution.'],
  ['Examples of vestigial structures in plants are:', ['Staminodes and scale leaves', 'Functional stamens', 'Green leaves', 'Roots'], 0,
    'They are reduced, non-functional remnants.'],
  ['Seed ferns (pteridosperms) are important fossil evidence because they:', ['Link ferns and seed plants, having fern-like leaves and seeds', 'Are angiosperms', 'Are mosses', 'Are algae'], 0,
    '*Archaeopteryx* plays a similar linking role for reptiles and birds.'],
  ['The biogenetic law ("ontogeny recapitulates phylogeny") was proposed by:', ['Ernst Haeckel', 'Karl von Baer', 'Lamarck', 'Darwin'], 0,
    'In its strict form it is now considered an oversimplification.'],
  ['Molecular evidence for evolution includes:', ['The near-universal genetic code and similar sequences of proteins such as cytochrome *c*', 'Differences in flower colour', 'Fossil footprints', 'Soil types'], 0,
    'The more closely related two species are, the more similar their sequences.'],
  ['Darwin’s finches of the Galápagos provide evidence from:', ['Biogeography and adaptive radiation', 'Fossils', 'Embryology', 'Vestigial organs'], 0,
    'Their beaks are adapted to different foods.'],
  ['Industrial melanism in the peppered moth (*Biston betularia*) is:', ['An example of natural selection observed in action', 'A case of inheritance of acquired characters', 'A mutation caused by smoke', 'Unrelated to selection'], 0,
    'Dark moths increased in soot-darkened woods.'],
  ['Fossils are dated using radioactive isotopes such as:', ['Carbon-14 for recent remains and potassium–argon for very old rocks', 'Oxygen-16', 'Nitrogen-14', 'Hydrogen-1'], 0,
    'Carbon-14 is useful only up to about 50,000 years.']
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 3, pyq: 'IFoS-2017-B2-Q6a', q: [
  ['The Calvin cycle is called autocatalytic because:', ['It regenerates its CO₂ acceptor (RuBP), and extra triose phosphate can be used to build up more of it', 'It needs no ATP', 'It makes its own enzymes', 'It runs in the dark only'], 0,
    'This lets the cycle speed up when light increases.'],
  ['The lag (induction) period of photosynthesis when a leaf is moved from dark to light reflects:', ['The autocatalytic build-up of Calvin cycle intermediates', 'Stomatal closure', 'Chlorophyll synthesis', 'Respiration'], 0,
    'The cycle must first refill its pools.'],
  ['For every three CO₂ fixed, the Calvin cycle yields a net:', ['One triose phosphate, while five of six are used to regenerate RuBP', 'Three glucose', 'Six triose phosphates', 'Nothing'], 0,
    'The net triose phosphate is exported to make sucrose or starch.'],
  ['The three phases of the Calvin cycle are:', ['Carboxylation, reduction and regeneration', 'Glycolysis, Krebs cycle and ETC', 'Absorption, transport and storage', 'Oxidation, hydration and cleavage'], 0,
    'Rubisco catalyses carboxylation.'],
  ['The Calvin cycle was worked out using ¹⁴CO₂ and *Chlorella* by:', ['Calvin, Benson and Bassham', 'Hatch and Slack', 'Hill and Bendall', 'Emerson and Arnold'], 0,
    'Calvin received the 1961 Nobel Prize.'],
  ['The first stable product of CO₂ fixation is:', ['3-PGA in C₃ plants and oxaloacetate in C₄ plants', 'Glucose in both', 'Malate in C₃ plants', 'Pyruvate in both'], 0,
    'C₄ plants are named after their four-carbon first product.'],
  ['The C₄ pathway was worked out in 1966 by:', ['Hatch and Slack', 'Calvin and Benson', 'Arnon', 'Mitchell'], 0,
    'Kortschak had seen early C₄ labelling in sugarcane.'],
  ['The energy cost of fixing one CO₂ is:', ['3 ATP + 2 NADPH in C₃ plants, and 5 ATP + 2 NADPH in C₄ plants', 'The same in both', 'Lower in C₄ plants', '1 ATP in both'], 0,
    'The extra 2 ATP regenerate PEP through pyruvate orthophosphate dikinase.'],
  ['C₄ photosynthesis is more efficient than C₃:', ['At high light, high temperature and low CO₂, because photorespiration is avoided', 'In all conditions', 'Only in cool, shady conditions', 'Never'], 0,
    'In cool climates C₃ plants can be as efficient or more so.'],
  ['At full sunlight, photosynthesis in C₄ plants:', ['Rarely reaches light saturation, unlike C₃ plants', 'Saturates at low light', 'Stops', 'Equals respiration'], 0,
    'This gives C₄ crops their high yield potential.']
] },
{ p: 'B2', t: 'Plant Hormones & Development', w: 3, pyq: 'IFoS-2017-B2-Q6b', q: [
  ['IBA and NAA are widely used in horticulture to:', ['Promote rooting of cuttings', 'Break seed dormancy', 'Ripen fruits', 'Increase sugar content'], 0,
    'Cuttings are dipped in their solutions or powders.'],
  ['GA₃ is sprayed on Thompson Seedless grapes to:', ['Elongate the bunches and enlarge the berries', 'Ripen them', 'Kill pests', 'Reduce size'], 0,
    'Seedless grapes make little gibberellin of their own.'],
  ['Ethephon is used in pineapple to:', ['Induce uniform flowering', 'Increase leaf size', 'Delay flowering', 'Kill weeds'], 0,
    'It releases ethylene in the plant.'],
  ['In cucurbits, ethephon sprays at the seedling stage:', ['Increase female flowers', 'Increase male flowers', 'Kill the plants', 'Stop flowering'], 0,
    'Gibberellin increases male flowers.'],
  ['Paclobutrazol is applied to mango to:', ['Induce flowering, especially in the "off" year, by blocking gibberellin synthesis', 'Increase vegetative growth', 'Ripen fruits', 'Delay flowering'], 0,
    'It helps overcome alternate bearing.'],
  ['NAA sprays in apple and mango are used to:', ['Prevent pre-harvest fruit drop', 'Increase fruit drop', 'Ripen fruits', 'Kill weeds'], 0,
    'At higher doses NAA is used to thin fruits.'],
  ['Chlormequat chloride (CCC) is used in wheat to:', ['Shorten stems and prevent lodging', 'Increase plant height', 'Break dormancy', 'Ripen grain'], 0,
    'It is a gibberellin biosynthesis inhibitor.'],
  ['Mepiquat chloride is used in cotton to:', ['Check excessive vegetative growth and improve boll retention', 'Increase plant height', 'Ripen bolls', 'Kill bollworms'], 0,
    'It keeps the canopy compact.'],
  ['Maleic hydrazide sprayed before harvest is used to:', ['Suppress sprouting of onion and potato in storage', 'Promote sprouting', 'Ripen tubers', 'Kill weeds'], 0,
    'It inhibits cell division.'],
  ['CPPU (forchlorfenuron), a cytokinin-like compound, is used to:', ['Increase fruit size in grapes and kiwifruit', 'Ripen bananas', 'Break dormancy', 'Kill insects'], 0,
    'Cytokinins also delay leaf senescence.']
] },
{ p: 'B2', t: 'Plant Hormones & Development', w: 3, pyq: 'IFoS-2017-B2-Q7a', q: [
  ['Phytochrome was discovered through work on lettuce seed germination by:', ['Borthwick and Hendricks (1952)', 'Went', 'Darwin', 'Garner and Allard'], 0,
    'Red light promoted germination and far-red reversed it.'],
  ['Phytochrome is:', ['A homodimeric chromoprotein with a linear tetrapyrrole chromophore (phytochromobilin)', 'A carotenoid', 'A lipid', 'A flavonoid'], 0,
    'Each monomer is about 125 kDa.'],
  ['The two interconvertible forms of phytochrome are:', ['Pr, absorbing red light (about 660 nm), and Pfr, absorbing far-red light (about 730 nm)', 'Pb and Pg', 'Only Pr', 'Pa and Pb'], 0,
    'Pfr is the biologically active form.'],
  ['The phytochrome chromophore is attached to the protein through:', ['A thioether bond to a cysteine residue', 'An ionic bond', 'A peptide bond', 'A disulphide bond'], 0,
    'It sits in the GAF domain.'],
  ['*Arabidopsis* has five phytochromes (PHYA–PHYE). Of these:', ['phyA is light-labile, while phyB is light-stable and dominant in light', 'All are light-labile', 'phyB is light-labile', 'None are active'], 0,
    'phyA mediates very-low-fluence responses.'],
  ['Active Pfr acts partly by moving into the nucleus and:', ['Promoting the degradation of PIF transcription factors', 'Making chlorophyll directly', 'Binding auxin', 'Fixing CO₂'], 0,
    'PIFs repress many light-regulated genes.'],
  ['A brief flash of red light in the middle of the long night:', ['Prevents flowering in short-day plants, an effect reversed by far-red light', 'Promotes flowering in short-day plants', 'Has no effect', 'Kills the plant'], 0,
    'The night break works through phytochrome.'],
  ['The flowering signal ("florigen") that moves from leaf to shoot apex is:', ['The FT protein', 'Phytochrome', 'Auxin', 'Starch'], 0,
    'CONSTANS switches on *FT* in long days.'],
  ['Light with a low red to far-red ratio, such as under a canopy, triggers:', ['Shade avoidance — stem elongation and early flowering', 'Dwarfing', 'Dormancy', 'Root growth only'], 0,
    'The response is mediated mainly by phyB.'],
  ['The phytochrome chromophore is made in the:', ['Plastid, from haem via biliverdin', 'Nucleus', 'Vacuole', 'Mitochondrion'], 0,
    'It joins the apoprotein in the cytosol.']
] },
{ p: 'B2', t: 'Plant Hormones & Development', w: 3, pyq: 'IFoS-2017-B2-Q7b', q: [
  ['Hard seed coats of *Acacia* and *Leucaena* are made permeable by:', ['Scarification with concentrated sulphuric acid, hot water or abrasion', 'Cold storage', 'Darkness', 'Drying'], 0,
    'This is a physical treatment for physical dormancy.'],
  ['Stratification, used for seeds of apple, peach and rose, means:', ['Keeping seeds moist at about 0–5 °C for several weeks', 'Soaking in acid', 'Heating to 60 °C', 'Drying in the sun'], 0,
    'Chilling lowers ABA and raises GA in the embryo.'],
  ['ISTA rules recommend moistening the substrate with this chemical to break dormancy in germination tests:', ['Potassium nitrate (0.2%)', 'Sodium chloride', 'Copper sulphate', 'Urea'], 0,
    'GA₃ and prechilling are other permitted treatments.'],
  ['Soaking seeds in running water breaks dormancy caused by:', ['Water-soluble germination inhibitors in the seed coat or fruit', 'A hard seed coat', 'An immature embryo', 'Light'], 0,
    'This is called leaching.'],
  ['Freshly harvested cereal grains lose dormancy during dry storage. This is called:', ['After-ripening', 'Stratification', 'Scarification', 'Vernalisation'], 0,
    'It takes weeks to months depending on the variety.'],
  ['Water uptake by a germinating seed is typically:', ['Triphasic: rapid imbibition, a plateau (lag), then renewed uptake with radicle growth', 'Constant', 'Absent', 'Only after radicle emergence'], 0,
    'Metabolism resumes in phase II.'],
  ['Early protein synthesis during germination uses:', ['Stored mRNAs from seed maturation, then newly made mRNAs', 'Only new DNA', 'Chloroplast proteins', 'No mRNA'], 0,
    'This lets the seed start working quickly.'],
  ['During germination of oily seeds, the respiratory quotient (RQ) is:', ['Less than one, because fats are being oxidised', 'Exactly one', 'Greater than one', 'Zero'], 0,
    'Carbohydrate respiration gives an RQ of about one.'],
  ['Reserve mobilisation during germination involves:', ['Amylases, proteases and lipases breaking down stored starch, proteins and fats', 'Photosynthesis only', 'Lignin synthesis', 'Cell wall thickening'], 0,
    'The products feed the growing embryo.'],
  ['Germination is considered complete when:', ['The radicle emerges', 'Water is absorbed', 'The first leaf unfolds', 'The plant flowers'], 0,
    'Seedling growth follows.']
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 3, pyq: 'IFoS-2017-B2-Q8a', q: [
  ['Phytoremediation is:', ['Using plants (and their microbes) to remove, break down or contain pollutants', 'Using chemicals to kill plants', 'Planting trees for timber', 'Burning waste'], 0,
    'It is cheap and solar-powered, but slow.'],
  ['In phytoextraction:', ['Plants take up pollutants and store them in harvestable shoots', 'Pollutants are fixed in the soil', 'Pollutants are released as gas', 'Pollutants are destroyed by fire'], 0,
    'Hyperaccumulators are the best candidates.'],
  ['The Chinese brake fern *Pteris vittata* is a hyperaccumulator of:', ['Arsenic', 'Nickel', 'Zinc', 'Lead only'], 0,
    '*Alyssum* accumulates nickel and *Noccaea caerulescens* zinc and cadmium.'],
  ['Rhizofiltration uses plant roots to:', ['Absorb pollutants from water', 'Release pollutants', 'Break down plastics', 'Clean the air'], 0,
    'Sunflowers were used to remove radionuclides from ponds near Chernobyl.'],
  ['Phytostabilisation:', ['Immobilises pollutants in the root zone to stop them spreading', 'Removes all pollutants', 'Volatilises pollutants', 'Burns pollutants'], 0,
    'It is used on mine tailings.'],
  ['Phytovolatilisation converts pollutants into volatile forms. An example is:', ['Selenium released by *Brassica* species', 'Nickel stored in *Alyssum*', 'Lead held in roots', 'Arsenic in fronds'], 0,
    'Transgenic plants with *merA* can volatilise mercury.'],
  ['Constructed wetlands with *Phragmites* and *Typha* are used to:', ['Treat sewage and wastewater', 'Grow rice', 'Store drinking water', 'Produce timber'], 0,
    'Root-zone microbes break down organic pollutants.'],
  ['Phytoremediation is not a complete solution because:', ['It is slow, works only to root depth, fails at high concentrations and leaves contaminated biomass for disposal', 'It is too fast', 'It works everywhere', 'It costs too much in all cases'], 0,
    'It is best combined with other methods.'],
  ['Another risk of phytoremediation is that:', ['Accumulated metals may enter the food chain through grazing animals', 'Plants become too big', 'It creates new pollutants', 'It needs no monitoring'], 0,
    'Sites must be fenced and biomass carefully handled.'],
  ['Studies of indoor air-cleaning plants since NASA’s 1989 study show that, in real buildings:', ['Their effect is small compared with ventilation', 'They remove all pollutants', 'They make the air toxic', 'They work only at night'], 0,
    'Plants alone cannot solve air pollution.']
] },
{ p: 'B2', t: 'Plant Geography, Forests & Biodiversity', w: 3, pyq: 'IFoS-2017-B2-Q8b', q: [
  ['Rodgers and Panwar (1988, WII) divided India into how many biogeographic zones?', ['Ten', 'Five', 'Twenty', 'Fifteen'], 0,
    'Examples are Trans-Himalaya, Western Ghats, Deccan Peninsula and the Islands.'],
  ['An early phytogeographic division of India into botanical provinces was made by:', ['D. Chatterjee (1939)', 'Champion and Seth', 'Rodgers and Panwar', 'Hooker only'], 0,
    'Hooker and Clarke (1906) had given an earlier scheme.'],
  ['A region with high temperature and rainfall, little snowfall, and rich in *Rhododendron*, oaks, orchids and ferns is most likely the:', ['Eastern Himalaya', 'Western Himalaya', 'Thar desert', 'Deccan plateau'], 0,
    'The Eastern Himalaya is wetter and warmer than the Western.'],
  ['Compared with the Eastern Himalaya, the Western Himalaya is:', ['Drier, with conifers such as deodar and blue pine and fewer orchids', 'Wetter, with more orchids', 'Tropical evergreen', 'Without forests'], 0,
    'Rainfall decreases from east to west along the Himalaya.'],
  ['The Indian state with the largest number of orchid species is:', ['Arunachal Pradesh', 'Rajasthan', 'Punjab', 'Gujarat'], 0,
    'It has over 600 orchid species.'],
  ['The Malabar (Western Ghats) region is known for:', ['Tropical evergreen forests with high endemism', 'Cold desert', 'Thorn forests', 'Alpine meadows'], 0,
    'It is part of a global biodiversity hotspot.'],
  ['The arid Indus plain and Thar region have xerophytic vegetation including:', ['*Prosopis cineraria*, *Capparis decidua* and *Calligonum*', 'Rhododendrons and oaks', 'Mangroves', 'Tree ferns'], 0,
    'Rainfall there is below about 25 cm in the driest parts.'],
  ['The Deccan region is dominated by:', ['Dry deciduous forests with teak and *Hardwickia*', 'Alpine meadows', 'Mangroves', 'Wet evergreen forests'], 0,
    'It lies in the rain shadow of the Western Ghats.'],
  ['The flora of the Andaman and Nicobar Islands has strong affinities with:', ['Malaysia and south-east Asia', 'Africa', 'Europe', 'Australia only'], 0,
    'Tropical evergreen forests and mangroves dominate.'],
  ['The Trans-Himalaya (Ladakh) region is a:', ['Cold desert with sparse alpine steppe vegetation', 'Tropical rainforest', 'Mangrove swamp', 'Deciduous forest'], 0,
    'It lies in the rain shadow of the Great Himalaya.']
] }
);
