/* PYQ-linked MCQs — IFoS 2017 Botany Paper I, Q5–Q8 (verbatim PYQs). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: 'IFoS-2017-B1-Q5a', q: [
  ['An author citation in a plant name is:', ['The name of the author(s) who validly published the name, written after it', 'The name of the collector', 'The herbarium where the specimen is kept', 'The date of collection'], 0,
    'For example, *Oryza sativa* L.'],
  ['The abbreviation "L." after a plant name stands for:', ['Linnaeus', 'Lamarck', 'Lindley', 'Link'], 0,
    'Lamarck is abbreviated "Lam." and Lindley "Lindl.".'],
  ['In *Cajanus cajan* (L.) Millsp., the author in parentheses shows that:', ['Linnaeus first described the species under another genus, and Millspaugh transferred it', 'Both authors wrote together', 'The name is illegitimate', 'Millspaugh collected the type'], 0,
    'Linnaeus originally named it *Cytisus cajan*.'],
  ['The connecting word "ex" in an author citation means that:', ['The first author proposed the name, but the second validly published it', 'Both published it together', 'The name was rejected', 'The name is a synonym'], 0,
    'An example is *Rauvolfia serpentina* (L.) Benth. ex Kurz.'],
  ['The connecting word "in" in an author citation means that:', ['The first author published the name in a work edited or written by the second', 'The name was proposed but never published', 'The name was rejected', 'The name is a hybrid'], 0,
    'Only the first author is part of the formal citation.'],
  ['"emend." (emendavit) in a citation indicates that:', ['A later author changed the description or circumscription without changing the type', 'The name was rejected', 'The name is a nomen nudum', 'The name was conserved'], 0,
    'It records an altered concept of the taxon.'],
  ['A "nomen nudum" is:', ['A name published without a description or diagnosis, so it is not validly published', 'A conserved name', 'A hybrid name', 'A cultivar name'], 0,
    'It has no standing in nomenclature.'],
  ['Standard abbreviations of plant author names are given by:', ['Brummitt and Powell’s *Authors of Plant Names* and IPNI', 'The ISTA rules', 'The Seeds Act', 'The Red Data Book'], 0,
    'Using standard forms avoids confusion.'],
  ['Rules for author citation are laid down in the:', ['International Code of Nomenclature for algae, fungi, and plants (ICN)', 'ICZN', 'The Biological Diversity Act', 'CITES'], 0,
    'The ICN is revised after each International Botanical Congress.'],
  ['Author citations are useful because they:', ['Make names precise, separate homonyms and point to the original publication', 'Show where a plant grows', 'Give the plant’s uses', 'Show its chromosome number'], 0,
    'They are essential in taxonomic literature.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 3, pyq: 'IFoS-2017-B1-Q5b', q: [
  ['Vavilov located centres of origin by finding regions with:', ['The greatest genetic diversity of a crop and its wild relatives', 'The highest crop yields', 'The largest cultivated area', 'The oldest cities'], 0,
    'This is the differential phytogeographic method.'],
  ['Vavilov originally proposed:', ['Eight main centres, with three subcentres', 'Twelve megacentres', 'Four centres', 'Twenty centres'], 0,
    'Zhukovsky later proposed twelve megacentres.'],
  ['In Vavilov’s scheme, the Hindustan (Indian) centre is the origin of:', ['Mango, brinjal and cucumber', 'Potato and tomato', 'Wheat and barley', 'Maize and beans'], 0,
    'Black pepper and several millets are also placed here.'],
  ['The South American (Peru–Ecuador–Bolivia) centre gave:', ['Potato and tomato', 'Rice and sugarcane', 'Coffee and sorghum', 'Olive and cabbage'], 0,
    'Wild potato diversity is richest in the Andes.'],
  ['The South Mexican and Central American centre gave:', ['Maize, common bean and upland cotton', 'Rice and tea', 'Wheat and lentil', 'Olive and cabbage'], 0,
    'Maize was domesticated from teosinte in Mexico.'],
  ['The Mediterranean centre gave:', ['Olive, cabbage and lettuce', 'Potato and tomato', 'Rice and mango', 'Coffee and teff'], 0,
    'Many vegetable and forage crops come from here.'],
  ['The Abyssinian (Ethiopian) centre is known for:', ['Arabica coffee, teff and a wide diversity of durum wheat', 'Potato', 'Soybean', 'Maize'], 0,
    'Sorghum diversity is also high there.'],
  ['The Chinese centre gave:', ['Soybean, tea and several citrus fruits', 'Potato and tomato', 'Olive and grape', 'Maize and beans'], 0,
    'It is Vavilov’s largest independent centre.'],
  ['The Near Eastern (Asia Minor) centre gave:', ['Emmer and einkorn wheat, rye and lentil', 'Rice and sugarcane', 'Potato and tomato', 'Maize and cotton'], 0,
    'It lies in the Fertile Crescent.'],
  ['Besides centres of origin, Vavilov formulated the:', ['Law of homologous series in variation (1920)', 'Law of the minimum', 'Hardy–Weinberg law', 'Law of tolerance'], 0,
    'Related species show parallel series of variation.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 3, pyq: 'IFoS-2017-B1-Q5c', q: [
  ['Cotton fibre is obtained from:', ['Seed hairs (epidermal outgrowths of the seed coat) of *Gossypium*', 'Stem bast', 'Leaves', 'Fruit mesocarp'], 0,
    'It is a surface fibre, nearly pure cellulose.'],
  ['Jute fibre is obtained from:', ['Secondary phloem (bast) of *Corchorus capsularis* and *C. olitorius*', 'Seed hairs', 'Leaves', 'Roots'], 0,
    'The stems are retted in water to free the fibres.'],
  ['Coir is obtained from the:', ['Mesocarp (husk) of coconut', 'Seed hairs of coconut', 'Leaves of coconut', 'Stem of coconut'], 0,
    'Kerala is India’s main coir-producing state.'],
  ['Sisal, a hard leaf fibre, comes from:', ['*Agave sisalana*', '*Linum usitatissimum*', '*Crotalaria juncea*', '*Boehmeria nivea*'], 0,
    'Leaf fibres are used for ropes and twine.'],
  ['Flax (linen) fibre is obtained from:', ['The stem bast of *Linum usitatissimum*', 'The seed hairs of *Linum*', 'The leaves of *Agave*', 'The fruit of *Ceiba*'], 0,
    'Linseed oil comes from the same species.'],
  ['Sunn hemp fibre comes from:', ['*Crotalaria juncea* (stem bast)', '*Cannabis sativa* only', '*Agave americana*', '*Musa textilis*'], 0,
    'It is also grown as a green manure crop.'],
  ['Ramie, which has some of the longest plant fibre cells, comes from:', ['*Boehmeria nivea* (stem bast)', '*Gossypium hirsutum*', '*Cocos nucifera*', '*Ceiba pentandra*'], 0,
    'It is also called China grass.'],
  ['Mesta (kenaf) fibre is obtained from:', ['*Hibiscus cannabinus* (stem bast)', '*Hibiscus rosa-sinensis* leaves', '*Corchorus* seeds', '*Agave* roots'], 0,
    '*H. sabdariffa* (roselle) also gives mesta fibre.'],
  ['Kapok floss, used for stuffing pillows and life jackets, comes from:', ['Hairs on the inner fruit wall of *Ceiba pentandra*', 'Cotton seeds', 'Jute stems', 'Coconut husk'], 0,
    'It is light and water-resistant but hard to spin.'],
  ['Manila hemp (abaca) comes from:', ['The leaf sheaths of *Musa textilis*', 'The stems of *Cannabis*', 'The seeds of *Gossypium*', 'The fruits of *Cocos*'], 0,
    'It is a strong fibre used for marine ropes.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, pyq: 'IFoS-2017-B1-Q5d', q: [
  ['The Mesozoic Era is called the "Age of Gymnosperms" because it was dominated by:', ['Cycads, ginkgos, conifers and cycadeoids', 'Angiosperms', 'Bryophytes', 'Algae'], 0,
    'Angiosperms took over only in the Late Cretaceous.'],
  ['The periods of the Mesozoic Era are:', ['Triassic, Jurassic and Cretaceous', 'Cambrian, Ordovician and Silurian', 'Devonian, Carboniferous and Permian', 'Palaeogene, Neogene and Quaternary'], 0,
    'The Mesozoic lasted from about 252 to 66 million years ago.'],
  ['The Bennettitales (cycadeoids), such as *Williamsonia* and *Cycadeoidea*, are notable for their:', ['Flower-like strobili, often bisporangiate', 'Winged pollen', 'Motile sperms only', 'Lack of leaves'], 0,
    'They were once suggested as angiosperm ancestors.'],
  ['*Williamsonia sewardiana* and *Pentoxylon* are well-known fossils from the:', ['Rajmahal Hills of Jharkhand', 'Siwaliks', 'Thar desert', 'Western Ghats'], 0,
    'Birbal Sahni described much of this flora.'],
  ['Pentoxylales, described by Birbal Sahni, are named after their:', ['Five vascular strands (steles) in the stem', 'Five leaves', 'Five seeds', 'Five petals'], 0,
    'They are a small group of Mesozoic seed plants.'],
  ['The Caytoniales, Mesozoic seed ferns with ovules in cupules, have been proposed as:', ['Possible ancestors of angiosperms', 'The ancestors of mosses', 'Algae', 'Fungi'], 0,
    'Their cupule has been compared to the carpel.'],
  ['The earliest definite angiosperm fossils date from the:', ['Early Cretaceous (about 130 million years ago)', 'Triassic', 'Jurassic', 'Permian'], 0,
    '*Archaefructus* from China is one of the oldest.'],
  ['A living "fossil" that flourished in the Mesozoic is:', ['*Ginkgo biloba*', '*Oryza sativa*', '*Helianthus annuus*', '*Zea mays*'], 0,
    'Ginkgoales were diverse in the Jurassic.'],
  ['The Birbal Sahni Institute of Palaeosciences is located in:', ['Lucknow', 'Dehradun', 'Kolkata', 'Pune'], 0,
    'It was founded in 1946.'],
  ['The Glossopteris flora, with *Glossopteris* and *Gangamopteris*, is characteristic of:', ['Gondwana, mainly in the Permian and continuing into the early Triassic', 'The Cretaceous of Europe', 'The Quaternary', 'The Cambrian'], 0,
    'Its distribution supported the idea of continental drift.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 1, pyq: 'IFoS-2017-B1-Q5e', q: [
  ['The inflorescence of banana (Musaceae) is:', ['A large terminal spike (spadix) with big coloured bracts (spathes)', 'An umbel', 'A capitulum', 'A cyathium'], 0,
    'It hangs down from the top of the pseudostem.'],
  ['In banana, flowers are borne in:', ['Clusters ("hands") in the axils of bracts, in two rows', 'Single flowers along the stem', 'Heads', 'Umbels'], 0,
    'Each hand of female flowers becomes a hand of fruits.'],
  ['On a banana inflorescence, the arrangement of flowers is:', ['Female flowers at the base, neutral or bisexual in the middle and male at the tip', 'Male at the base, female at the tip', 'All bisexual', 'All male'], 0,
    'The male part forms the "bell" or male bud.'],
  ['The banana inflorescence emerges by growing up through the:', ['Pseudostem, made of rolled leaf sheaths', 'Rhizome only', 'Roots', 'Leaf blades'], 0,
    'The true stem remains underground until flowering.'],
  ['Edible bananas form fruit without fertilisation. This is:', ['Parthenocarpy', 'Apomixis', 'Polyembryony', 'Vivipary'], 0,
    'Most dessert bananas are seedless triploids (AAA).'],
  ['Removing the male bud after the last hand has formed is called:', ['Denavelling', 'Desuckering', 'Detopping', 'Detasselling'], 0,
    'It can increase bunch weight.'],
  ['Banana flowers are:', ['Zygomorphic and epigynous, with five fertile stamens and one staminode', 'Actinomorphic and hypogynous', 'Without perianth', 'Tetramerous'], 0,
    'The ovary is inferior and three-celled.'],
  ['A banana pseudostem:', ['Flowers once and then dies (monocarpic)', 'Flowers every year', 'Never flowers', 'Flowers only when grafted'], 0,
    'Suckers from the rhizome carry the plant on.'],
  ['In wild bananas, flowers are pollinated mainly by:', ['Bats and birds', 'Wind', 'Water', 'Ants'], 0,
    'The large bracts and plentiful nectar attract them.'],
  ['The family Musaceae belongs to the order:', ['Zingiberales', 'Poales', 'Arecales', 'Liliales'], 0,
    'Zingiberaceae and Cannaceae are in the same order.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 3, pyq: 'IFoS-2017-B1-Q6a', q: [
  ['Bentham and Hooker’s classification was published in:', ['*Genera Plantarum* (1862–1883), in three volumes', '*Species Plantarum*', '*Die Natürlichen Pflanzenfamilien*', '*Flora of British India* only'], 0,
    'It was based on specimens in the Kew herbarium.'],
  ['Bentham and Hooker’s system is a:', ['Natural system, based on overall resemblance and made before evolution was widely accepted', 'Phylogenetic system based on DNA', 'Artificial sexual system', 'Numerical system'], 0,
    'It was prepared largely independently of Darwin’s ideas.'],
  ['Bentham and Hooker divided seed plants into three classes:', ['Dicotyledons, Gymnospermae and Monocotyledons', 'Magnoliopsida and Liliopsida', 'Polypetalae and Gamopetalae only', 'Algae, fungi and plants'], 0,
    'The gymnosperms were placed between the dicots and monocots.'],
  ['Dicotyledons in Bentham and Hooker’s system are divided into:', ['Polypetalae, Gamopetalae and Monochlamydeae', 'Thalamiflorae and Disciflorae only', 'Rosidae and Asteridae', 'Eudicots and magnoliids'], 0,
    'The division depends on the petals.'],
  ['The three series of Polypetalae are:', ['Thalamiflorae, Disciflorae and Calyciflorae', 'Inferae, Heteromerae and Bicarpellatae', 'Microspermae and Epigynae', 'Glumaceae and Apocarpae'], 0,
    'The Ranales stand at the start of Thalamiflorae.'],
  ['The three series of Gamopetalae are:', ['Inferae, Heteromerae and Bicarpellatae', 'Thalamiflorae, Disciflorae and Calyciflorae', 'Coronarieae and Calycinae', 'Nudiflorae and Glumaceae'], 0,
    'Asteraceae falls in Inferae.'],
  ['Bentham and Hooker recognised about how many families of seed plants?', ['202', '100', '300', '415'], 0,
    'There were 165 dicot, 34 monocot and 3 gymnosperm families.'],
  ['A major merit of Bentham and Hooker’s system is that:', ['Its descriptions came from direct study of specimens, so it is practical for identification', 'It is based on molecular data', 'It is fully phylogenetic', 'It places gymnosperms first'], 0,
    'Many Indian herbaria still arrange specimens by it.'],
  ['A major demerit of Bentham and Hooker’s system is that:', ['Gymnosperms are placed between dicots and monocots, and Monochlamydeae is an artificial group', 'It has too few families', 'It uses DNA', 'It ignores flowers'], 0,
    'Related families such as Urticaceae were separated by it.'],
  ['In Bentham and Hooker’s system, the monocots begin with the series:', ['Microspermae (including orchids)', 'Glumaceae (grasses)', 'Apocarpae', 'Coronarieae'], 0,
    'Placing the advanced orchids first is considered a flaw.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: 'IFoS-2017-B1-Q6b', q: [
  ['The corolla of Fabaceae (Papilionoideae) is:', ['Papilionaceous — a standard, two wings and a keel of two fused petals', 'Tubular', 'Cruciform', 'Absent'], 0,
    'The standard is also called the vexillum.'],
  ['The aestivation of the papilionaceous corolla is:', ['Descending imbricate (vexillary)', 'Twisted', 'Valvate', 'Ascending imbricate'], 0,
    'The standard overlaps the wings, which overlap the keel.'],
  ['The stamens of Papilionoideae are usually:', ['Diadelphous, (9)+1', 'Monadelphous in a column', 'Syngenesious', 'Fused with the stigma'], 0,
    'The free stamen lies opposite the standard.'],
  ['The gynoecium of Fabaceae is:', ['Monocarpellary and unilocular, with marginal placentation', 'Bicarpellary and apocarpous', 'Tricarpellary and syncarpous', 'Inferior'], 0,
    'It develops into a legume (pod).'],
  ['In Asclepiadaceae, unlike Fabaceae, the stamens are:', ['Fused with the stigma head to form a gynostegium', 'Diadelphous', 'Free and numerous', 'Absent'], 0,
    'Pollen is carried in pollinia.'],
  ['The fruit is:', ['A legume in Fabaceae and a pair of follicles in Asclepiadaceae', 'A capsule in both', 'A berry in both', 'A follicle in Fabaceae and a legume in Asclepiadaceae'], 0,
    'Asclepiad seeds carry a tuft of silky hairs (coma).'],
  ['The floral formula % ⚥ K(5) C1+2+(2) A(9)+1 G1 belongs to:', ['Fabaceae (Papilionoideae)', 'Asclepiadaceae', 'Solanaceae', 'Brassicaceae'], 0,
    '"%" shows that the flower is zygomorphic.'],
  ['An economically important plant of Fabaceae is:', ['*Cicer arietinum* (chickpea)', '*Calotropis procera*', '*Solanum tuberosum*', '*Brassica juncea*'], 0,
    'Other examples are groundnut and soybean.'],
  ['An economically important plant of Asclepiadaceae is:', ['*Gymnema sylvestre* (gurmar), used against diabetes', '*Pisum sativum*', '*Arachis hypogaea*', '*Glycine max*'], 0,
    '*Hemidesmus indicus* (Indian sarsaparilla) is another.'],
  ['Bees pollinating pea-type (papilionaceous) flowers:', ['Press down the keel, so the stamens and style spring up against their bodies', 'Collect pollinia on their legs', 'Pierce the ovary', 'Visit only at night'], 0,
    'Asclepiads use the translator mechanism instead.']
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 2, pyq: 'IFoS-2017-B1-Q6c', q: [
  ['The term "palynology" was coined by:', ['Hyde and Williams (1944)', 'G. Erdtman', 'L. von Post', 'P. Maheshwari'], 0,
    'It is the study of pollen and spores.'],
  ['The founder of modern pollen morphology, who introduced acetolysis, was:', ['Gunnar Erdtman', 'Lennart von Post', 'Hyde', 'Heslop-Harrison'], 0,
    'Acetolysis removes the contents and leaves the exine clear.'],
  ['The outer pollen wall (exine) is made of:', ['Sporopollenin, one of the most resistant natural polymers', 'Cellulose', 'Pectin', 'Lignin only'], 0,
    'The intine is made of cellulose and pectin.'],
  ['Pollen survives in sediments for millions of years because:', ['Sporopollenin resists decay', 'Pollen is alive', 'Pollen is mineralised', 'Pollen is made of silica'], 0,
    'This makes pollen valuable in geology and archaeology.'],
  ['The study of pollen in honey to find its botanical and geographical source is:', ['Melissopalynology', 'Aeropalynology', 'Forensic palynology', 'Copropalynology'], 0,
    'It helps detect adulterated or mislabelled honey.'],
  ['Aeropalynology helps in medicine by:', ['Identifying allergenic pollen in the air', 'Diagnosing cancer', 'Measuring blood sugar', 'Treating infections'], 0,
    '*Parthenium* and *Prosopis juliflora* pollen are major allergens in India.'],
  ['Pollen analysis of peat and lake sediments, begun by Lennart von Post (1916), is used to:', ['Reconstruct past vegetation and climate', 'Date rocks by radioactivity', 'Measure soil pH', 'Find oil directly'], 0,
    'Pollen diagrams show how vegetation changed over time.'],
  ['In the oil industry, fossil pollen and spores are used for:', ['Dating and correlating rock strata (biostratigraphy)', 'Refining oil', 'Pumping oil', 'Measuring oil viscosity'], 0,
    'Characteristic spores mark particular rock layers.'],
  ['Tricolpate pollen (three furrows) is characteristic of:', ['Eudicots', 'Monocots', 'Gymnosperms', 'Ferns'], 0,
    'Monocots and basal angiosperms usually have monosulcate pollen.'],
  ['Erdtman’s NPC system classifies pollen by the:', ['Number, position and character of the apertures', 'Nucleus, protein and colour', 'Size, shape and weight', 'Species, plant and country'], 0,
    'Aperture features are useful in taxonomy.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 2, pyq: 'IFoS-2017-B1-Q6d', q: [
  ['The term "ethnobotany" was coined in 1895 by:', ['J. W. Harshberger', 'S. K. Jain', 'Richard Schultes', 'Linnaeus'], 0,
    'It is the study of how people use plants.'],
  ['The father of Indian ethnobotany is:', ['S. K. Jain', 'Birbal Sahni', 'P. Maheshwari', 'M. S. Swaminathan'], 0,
    'He led ethnobotanical surveys among Indian tribes.'],
  ['Reserpine, an antihypertensive drug, came from the traditionally used plant:', ['*Rauvolfia serpentina*', '*Digitalis purpurea*', '*Cinchona officinalis*', '*Papaver somniferum*'], 0,
    'It was used in Indian medicine for snakebite and insanity.'],
  ['Quinine was developed from the traditional use of:', ['*Cinchona* bark for fevers in Peru', 'Willow bark for pain', 'Foxglove for dropsy', 'Poppy for sleep'], 0,
    'It was the main antimalarial for centuries.'],
  ['Aspirin was derived from salicin, found in:', ['Willow (*Salix*) bark, a folk pain remedy', '*Cinchona* bark', '*Digitalis* leaves', '*Taxus* bark'], 0,
    'It was synthesised as acetylsalicylic acid in 1897.'],
  ['Digoxin for heart failure came from William Withering’s study (1785) of a folk remedy using:', ['Foxglove (*Digitalis*)', 'Willow', 'Opium poppy', 'Neem'], 0,
    'The remedy had been used for dropsy.'],
  ['Tubocurarine, a muscle relaxant used in surgery, came from:', ['Curare, an Amazonian arrow poison from *Chondrodendron tomentosum*', 'Snake venom', 'Neem oil', 'Tea leaves'], 0,
    'It blocks nerve-muscle transmission.'],
  ['Artemisinin was developed from:', ['Qinghao (*Artemisia annua*), used in traditional Chinese medicine', 'Neem', 'Tulsi', 'Turmeric'], 0,
    'Tu Youyou shared the 2015 Nobel Prize for it.'],
  ['Forskolin, a drug lead from Ayurvedic medicine, comes from:', ['*Coleus forskohlii* (*Plectranthus barbatus*)', '*Ocimum sanctum*', '*Withania somnifera*', '*Aloe vera*'], 0,
    'It raises cellular cyclic AMP.'],
  ['Ethnobotany speeds up drug discovery because:', ['Plants with a history of traditional use are more likely to contain active compounds', 'It avoids all testing', 'It uses only synthetic chemicals', 'It ignores local knowledge'], 0,
    'Benefit-sharing with communities is now required under the Biological Diversity Act.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 3, pyq: 'IFoS-2017-B1-Q7a', q: [
  ['Liquorice (*Glycyrrhiza glabra*, Fabaceae) contains:', ['Glycyrrhizin, a sweet compound used against coughs and ulcers', 'Reserpine', 'Sinigrin', 'Amygdalin'], 0,
    'It is about 50 times sweeter than sugar.'],
  ['*Psoralea corylifolia* (bakuchi, Fabaceae) is used to treat leucoderma because it contains:', ['Psoralens (furanocoumarins)', 'Morphine', 'Caffeine', 'Pectin'], 0,
    'Psoralens make the skin sensitive to UV light.'],
  ['*Mucuna pruriens* (velvet bean, Fabaceae) is a source of:', ['L-DOPA, used in Parkinson’s disease', 'Quinine', 'Nicotine', 'Artemisinin'], 0,
    'L-DOPA is the precursor of dopamine.'],
  ['Physostigmine (eserine), used in glaucoma, comes from the Calabar bean:', ['*Physostigma venenosum* (Fabaceae)', '*Prunus dulcis*', '*Brassica nigra*', '*Rosa damascena*'], 0,
    'It inhibits acetylcholinesterase.'],
  ['The blue dye indigo is obtained from:', ['*Indigofera tinctoria* (Fabaceae)', '*Rosa* (Rosaceae)', '*Brassica* (Brassicaceae)', '*Malus* (Rosaceae)'], 0,
    'Its colourless precursor is indican.'],
  ['Bitter almonds (*Prunus dulcis* var. *amara*, Rosaceae) are toxic because they contain:', ['Amygdalin, a cyanogenic glycoside', 'Glycyrrhizin', 'Sinigrin', 'Psoralen'], 0,
    'Amygdalin releases hydrogen cyanide when crushed.'],
  ['Rose oil (attar) from *Rosa damascena* (Rosaceae) is rich in:', ['Geraniol and citronellol', 'Eugenol', 'Menthol', 'Capsaicin'], 0,
    'Kannauj in Uttar Pradesh is famous for attar.'],
  ['Apple (*Malus domestica*, Rosaceae) pomace is a commercial source of:', ['Pectin', 'Rubber', 'Starch only', 'Morphine'], 0,
    'Pectin is used to set jams and jellies.'],
  ['The pungency of mustard (*Brassica juncea*, Brassicaceae) comes from:', ['Allyl isothiocyanate, released from sinigrin', 'Capsaicin', 'Piperine', 'Gingerol'], 0,
    'The enzyme myrosinase releases it when seeds are crushed.'],
  ['"Double-zero" (canola-quality) rapeseed–mustard varieties are low in:', ['Erucic acid in the oil and glucosinolates in the meal', 'Oil content', 'Protein', 'Fibre'], 0,
    'High erucic acid is undesirable in edible oil.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 3, pyq: 'IFoS-2017-B1-Q7b', q: [
  ['The three levels of biodiversity are:', ['Genetic, species and ecosystem diversity', 'Cell, tissue and organ diversity', 'Soil, water and air diversity', 'Local, national and global diversity'], 0,
    'All three must be conserved.'],
  ['Species diversity within a single habitat is called:', ['Alpha diversity', 'Beta diversity', 'Gamma diversity', 'Delta diversity'], 0,
    'Beta diversity compares habitats; gamma is regional diversity (Whittaker).'],
  ['In situ conservation means conserving species:', ['In their natural habitats, e.g., national parks, sanctuaries, biosphere reserves and sacred groves', 'In seed banks', 'In botanical gardens only', 'In laboratories'], 0,
    'It conserves ecological processes as well.'],
  ['Ex situ conservation includes:', ['Seed banks, field gene banks, botanical gardens and cryobanks', 'National parks', 'Sacred groves', 'Biosphere reserve core zones'], 0,
    'It is vital for species whose habitats are lost.'],
  ['Cryopreservation stores plant material at:', ['About −196 °C in liquid nitrogen', '−18 °C in a freezer', '4 °C in a refrigerator', 'Room temperature'], 0,
    'At this temperature metabolism practically stops.'],
  ['Cryoprotectants used before freezing include:', ['DMSO, glycerol, sucrose and PVS2 solution', 'Salt', 'Urea', 'Pesticides'], 0,
    'They prevent damaging ice crystals from forming.'],
  ['Cryopreservation is especially useful for conserving:', ['Recalcitrant-seeded and vegetatively propagated species, pollen and embryos', 'Only orthodox seeds', 'Only animals', 'Only soil'], 0,
    'Examples are shoot tips of banana and embryonic axes of jackfruit.'],
  ['A cryopreservation technique that encloses tissues in alginate beads and dries them before freezing is:', ['Encapsulation–dehydration', 'Air layering', 'Grafting', 'Hydroponics'], 0,
    'Vitrification with PVS2 is another common method.'],
  ['A biosphere reserve is divided into:', ['A core zone, a buffer zone and a transition zone', 'Only a core zone', 'Farms and cities', 'Three national parks'], 0,
    'Human activity is allowed mainly in the transition zone.'],
  ['India’s first biosphere reserve, set up in 1986, was:', ['Nilgiri', 'Sundarbans', 'Nanda Devi', 'Gulf of Mannar'], 0,
    'It covers parts of Tamil Nadu, Kerala and Karnataka.']
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 3, pyq: 'IFoS-2017-B1-Q7c', q: [
  ['Apomixis is:', ['The formation of seed without meiosis and fertilisation', 'Normal sexual seed formation', 'Seedless fruit formation', 'Germination on the plant'], 0,
    'The term was coined by Winkler (1908).'],
  ['In diplospory, the embryo sac develops from:', ['The megaspore mother cell, without normal meiosis', 'A nucellar cell', 'The zygote', 'The pollen'], 0,
    'It occurs in *Taraxacum* and *Antennaria*.'],
  ['In apospory, the embryo sac develops from:', ['A somatic nucellar cell', 'The megaspore mother cell after meiosis', 'The synergid', 'The antipodal cell'], 0,
    'It occurs in *Hieracium*, *Pennisetum* and *Panicum*.'],
  ['Adventive embryony, in which embryos arise directly from the nucellus or integument, is seen in:', ['*Citrus* and mango', 'Wheat', 'Maize', 'Pea'], 0,
    'This is sporophytic apomixis.'],
  ['In gametophytic apomixis, the unreduced egg develops into an embryo without fertilisation. This is called:', ['Parthenogenesis', 'Double fertilisation', 'Apogamy only', 'Syngamy'], 0,
    'The embryo is genetically identical to the mother plant.'],
  ['In pseudogamous apomicts, pollination is still needed to:', ['Fertilise the central cell and form the endosperm', 'Fertilise the egg', 'Form the seed coat', 'Nothing'], 0,
    'Examples are *Panicum* and *Poa*.'],
  ['An apomict that can also reproduce sexually is:', ['A facultative apomict', 'An obligate apomict', 'A sterile hybrid', 'A cleistogamous plant'], 0,
    'Most apomicts are facultative.'],
  ['Apospory in *Pennisetum squamulatum* is controlled by:', ['A dominant apospory-specific genomic region (ASGR) that behaves as one locus', 'Many recessive genes', 'Cytoplasmic genes', 'The environment only'], 0,
    'The ASGR carries a *BABY BOOM*-like gene.'],
  ['"Synthetic apomixis" was achieved in rice in 2019 by:', ['Combining MiMe (mitosis instead of meiosis) with egg-cell expression of *BBM1*', 'Irradiating pollen', 'Grafting', 'Colchicine treatment'], 0,
    'It produced clonal seeds from hybrid rice.'],
  ['The main breeding value of apomixis is that it can:', ['Fix hybrid vigour, since seed is produced clonally', 'Increase variation each generation', 'Make plants sterile', 'Reduce yields'], 0,
    'Farmers could then save hybrid seed.']
] },
{ p: 'B1', t: 'Plant Anatomy', w: 3, pyq: 'IFoS-2017-B1-Q8a', q: [
  ['In normal secondary growth of a dicot stem:', ['A cambium ring produces secondary xylem inwards and secondary phloem outwards', 'Several cambia form in the cortex', 'Xylem forms outside the phloem', 'No cambium is formed'], 0,
    'Anomalous growth departs from this pattern.'],
  ['In *Boerhaavia*, anomalous secondary growth involves:', ['Medullary bundles and successive rings of accessory cambium', 'Phloem wedges', 'Included phloem only', 'A secondary thickening meristem'], 0,
    'Successive cambia also occur in *Achyranthes* and *Amaranthus*.'],
  ['In *Bignonia*, the stem xylem appears furrowed, often cross-shaped, because:', ['At four places the cambium makes more phloem and less xylem (phloem wedges)', 'There are medullary bundles', 'There are several cambia', 'There is no cambium'], 0,
    'The phloem pushes in as wedges.'],
  ['In *Aristolochia*, the secondary xylem is:', ['Divided into segments by broad parenchymatous rays', 'Continuous without rays', 'Absent', 'Outside the phloem'], 0,
    'The cambium in the ray regions forms only parenchyma.'],
  ['Included (interxylary) phloem, with phloem strands embedded in the secondary xylem, is found in:', ['*Salvadora* and *Leptadenia*', '*Helianthus*', '*Cucurbita*', '*Zea*'], 0,
    'The cambium briefly produces phloem inwards.'],
  ['The fleshy root of beetroot (*Beta vulgaris*) shows:', ['Concentric rings of vascular tissue formed by successive cambia', 'A single normal ring', 'Phloem wedges', 'Medullary bundles only'], 0,
    'The rings show as coloured bands in a cut root.'],
  ['Secondary growth in monocots such as *Dracaena* occurs through:', ['A secondary thickening meristem outside the vascular region, forming secondary (amphivasal) bundles', 'A normal cambium ring', 'Cork cambium only', 'Apical meristem only'], 0,
    'Most monocots have no secondary growth.'],
  ['Anomalous secondary growth in climbers (lianas) is thought to:', ['Make the stem flexible while protecting its conducting tissue', 'Make the stem brittle', 'Stop water movement', 'Reduce photosynthesis'], 0,
    'Stems must twist without breaking.'],
  ['Medullary vascular bundles are a feature of:', ['*Boerhaavia* and *Achyranthes*', '*Helianthus*', '*Pinus*', '*Cucurbita*'], 0,
    'They lie in the pith, inside the main ring.'],
  ['Anomalous secondary growth is best defined as:', ['Secondary growth that departs from the normal single-cambium pattern in position, activity or products', 'Any secondary growth', 'Primary growth only', 'Growth of roots only'], 0,
    'It is common in climbers and succulent roots.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 2, pyq: 'IFoS-2017-B1-Q8b', q: [
  ['A botanical garden differs from an ordinary garden in that it:', ['Keeps documented, labelled collections of living plants for research, conservation and education', 'Grows only ornamental flowers', 'Is always private', 'Has no scientific records'], 0,
    'Each plant has an accession record.'],
  ['The oldest academic botanical garden still at its original site is:', ['Orto Botanico di Padova, Italy (1545)', 'Kew Gardens', 'New York Botanical Garden', 'Singapore Botanic Gardens'], 0,
    'It is a UNESCO World Heritage Site.'],
  ['Royal Botanic Gardens, Kew became a UNESCO World Heritage Site in:', ['2003', '1987', '2015', '1972'], 0,
    'Singapore Botanic Gardens was listed in 2015.'],
  ['An internationally reputed botanical garden in the USA is:', ['Missouri Botanical Garden', 'Kew', 'Padua', 'Peradeniya'], 0,
    'The New York Botanical Garden is another.'],
  ['"Order beds" in a botanical garden are used to:', ['Show plant families arranged according to a system of classification', 'Grow vegetables', 'Store seeds', 'Exhibit machines'], 0,
    'They help students learn taxonomy.'],
  ['An "Index Seminum" published by botanical gardens is:', ['A list of seeds offered for exchange with other gardens', 'A list of employees', 'A price list', 'A weather record'], 0,
    'It supports free exchange of plant material.'],
  ['In education, an ideal botanical garden provides:', ['Labelled plants, a herbarium, a library, guided walks and training courses', 'Only recreation', 'Only sales of plants', 'Only picnics'], 0,
    'It serves as an outdoor classroom.'],
  ['The Lloyd Botanical Garden, known for Himalayan plants, is in:', ['Darjeeling', 'Ooty', 'Shillong', 'Srinagar'], 0,
    'It was established in 1878.'],
  ['The CSIR institute in Lucknow that also maintains a botanical garden is:', ['National Botanical Research Institute (NBRI)', 'CIMAP', 'CDRI', 'IITR'], 0,
    'It grew out of the National Botanic Gardens set up in 1953.'],
  ['Singapore Botanic Gardens played a key role in developing:', ['The rubber industry of south-east Asia (H. N. Ridley)', 'The tea industry of Assam', 'The coffee industry of Brazil', 'Cotton breeding'], 0,
    'Ridley developed the tapping method used today.']
] },
{ p: 'B1', t: 'Morphogenesis & Tissue Culture', w: 3, pyq: 'IFoS-2017-B1-Q8c', q: [
  ['Micropropagation is:', ['Rapid clonal multiplication of plants in vitro from small explants', 'Propagation by seed', 'Grafting in the field', 'Hybridisation'], 0,
    'It gives large numbers of uniform plants.'],
  ['The most widely used plant tissue culture medium was developed by:', ['Murashige and Skoog (1962)', 'Gamborg', 'White', 'Nitsch'], 0,
    'It was first designed for tobacco callus.'],
  ['Callus is:', ['An unorganised mass of dividing cells formed from an explant, usually under auxin', 'A differentiated shoot', 'A seed', 'A root nodule'], 0,
    '2,4-D is often used to induce it.'],
  ['Callus usually originates from:', ['Cambial or wounded cells that dedifferentiate', 'Only epidermal cells', 'Pollen', 'Dead xylem'], 0,
    'Wounding the explant stimulates cell division.'],
  ['Uses of callus culture include:', ['Regenerating plants, selecting somaclonal variants and producing secondary metabolites', 'Only making seeds', 'Only killing pathogens', 'Only fertiliser production'], 0,
    'Cell suspensions are started from friable callus.'],
  ['The term "somaclonal variation" was coined by:', ['Larkin and Scowcroft (1981)', 'Haberlandt', 'Skoog', 'Cocking'], 0,
    'It means variation among plants regenerated from culture.'],
  ['Protoplasts are isolated by digesting cell walls with:', ['Cellulase and pectinase (macerozyme)', 'Trypsin', 'Amylase', 'Lipase'], 0,
    'E. C. Cocking first isolated them enzymatically in 1960.'],
  ['Protoplast fusion is induced by:', ['Polyethylene glycol (PEG), electrofusion, or high pH with high calcium', 'Heat alone', 'Light', 'Auxin'], 0,
    'Fused products are then selected and regenerated.'],
  ['The first interspecific somatic hybrid plant was produced by Carlson (1972) between:', ['*Nicotiana glauca* and *N. langsdorffii*', 'Potato and tomato', 'Wheat and rye', 'Rice and maize'], 0,
    'Melchers produced the "pomato" (potato + tomato) in 1978.'],
  ['A demerit of protoplast fusion is that:', ['The hybrids are often sterile, unstable and hard to regenerate', 'It always gives fertile plants', 'It needs no laboratory', 'It cannot overcome crossing barriers'], 0,
    'Its merit is combining species that cannot be crossed sexually, or making cybrids.']
] }
);
