/* PYQ-linked MCQs — IFoS 2017 Agriculture Paper II, Q1–Q4 (verbatim PYQs; some marks illegible in source). 10 MCQs per PYQ. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: 'IFoS-2017-A2-Q1a', q: [
  ['A new plant cell wall begins at cytokinesis as:', ['A cell plate formed from Golgi-derived vesicles guided by the phragmoplast', 'An outgrowth of the old wall', 'Cellulose secreted by the nucleus', 'A layer of lignin'], 0,
    'The cell plate grows outwards until it meets the parent wall.'],
  ['The cell plate develops into the:', ['Middle lamella, rich in pectin (calcium pectate)', 'Secondary wall', 'Plasma membrane', 'Cuticle'], 0,
    'It cements neighbouring cells together.'],
  ['The primary cell wall is laid down:', ['While the cell is still growing, and is thin and flexible', 'Only after the cell dies', 'Only in xylem vessels', 'Outside the middle lamella'], 0,
    'It contains cellulose, hemicelluloses, pectins and proteins.'],
  ['The secondary cell wall is:', ['Deposited inside the primary wall after growth stops, often lignified, in layers S1, S2 and S3', 'The same as the middle lamella', 'Formed before the primary wall', 'Made only of pectin'], 0,
    'It gives strength to fibres and tracheary elements.'],
  ['Cellulose microfibrils are made by:', ['Cellulose synthase complexes ("rosettes") in the plasma membrane', 'The Golgi apparatus', 'The nucleus', 'Chloroplasts'], 0,
    'Hemicelluloses and pectins are made in the Golgi.'],
  ['The direction in which cellulose microfibrils are laid down is guided by:', ['Cortical microtubules beneath the plasma membrane', 'Mitochondria', 'Ribosomes', 'Vacuoles'], 0,
    'Microfibril orientation controls the direction of cell expansion.'],
  ['Wall thickening by adding new layers on the inner surface is called:', ['Apposition', 'Intussusception', 'Plasmolysis', 'Imbibition'], 0,
    'Intussusception means inserting new material into the existing wall.'],
  ['According to the acid-growth hypothesis, auxin loosens cell walls by:', ['Stimulating proton pumping, which acidifies the wall and activates expansins', 'Adding lignin', 'Removing water', 'Thickening the middle lamella'], 0,
    'Turgor pressure then drives cell expansion.'],
  ['Plasmodesmata form where:', ['Strands of endoplasmic reticulum are trapped in the developing cell plate', 'The wall is lignified', 'Cells die', 'Pits are absent'], 0,
    'They connect the cytoplasm of neighbouring cells.'],
  ['Thin areas of the primary wall with many plasmodesmata are called:', ['Primary pit fields', 'Bordered pits only', 'Lenticels', 'Stomata'], 0,
    'Pits form over them in the secondary wall.']
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: 'IFoS-2017-A2-Q1b', q: [
  ['An allopolyploid is a polyploid that:', ['Contains genomes from two or more different species', 'Has multiple copies of one genome', 'Lacks one chromosome', 'Has half the normal chromosome number'], 0,
    'Autopolyploids have extra sets of the same genome.'],
  ['A doubled interspecific hybrid that behaves like a fertile diploid is called an:', ['Amphidiploid', 'Autotriploid', 'Aneuploid', 'Haploid'], 0,
    'Doubling gives each chromosome a partner for pairing.'],
  ['Triticale, the first man-made cereal, is an allopolyploid of:', ['Wheat (*Triticum*) and rye (*Secale*)', 'Wheat and barley', 'Rice and maize', 'Oat and rye'], 0,
    'Hexaploid triticale (AABBRR) is the most widely grown.'],
  ['U’s triangle (1935) explains the origin of *Brassica juncea* (AABB) from:', ['*B. rapa* (AA) × *B. nigra* (BB)', '*B. oleracea* × *B. nigra*', '*B. rapa* × *B. oleracea*', '*B. napus* × *B. carinata*'], 0,
    '*B. napus* is AACC and *B. carinata* is BBCC.'],
  ['The D genome of bread wheat came from:', ['*Aegilops tauschii*', '*Triticum urartu*', '*Secale cereale*', '*Hordeum vulgare*'], 0,
    'The A genome came from *T. urartu*.'],
  ['Cultivated upland cotton (*Gossypium hirsutum*) is:', ['An allotetraploid (AADD)', 'A diploid', 'An autotetraploid', 'A haploid'], 0,
    '*G. barbadense* is also AADD; *G. arboreum* and *G. herbaceum* are diploid.'],
  ['Synthetic hexaploid wheats (made by CIMMYT) are used to:', ['Bring new diversity from *Aegilops tauschii* into bread wheat', 'Make haploids', 'Produce hybrid wheat', 'Reduce yield'], 0,
    'They are sources of disease and drought resistance.'],
  ['Allopolyploidy helps crop improvement by:', ['Transferring useful genes from wild species and creating new crops', 'Always reducing yield', 'Causing sterility only', 'Removing genomes'], 0,
    'Rust resistance genes have come into wheat from *Aegilops*.'],
  ['Cultivated groundnut (*Arachis hypogaea*) is:', ['An allotetraploid (AABB)', 'A diploid', 'A hexaploid', 'A triploid'], 0,
    'Its narrow genetic base is widened using wild diploids.'],
  ['The fertility of a sterile interspecific F₁ hybrid can be restored by:', ['Doubling its chromosomes with colchicine', 'Selfing it', 'Irradiating it', 'Grafting it'], 0,
    'This is how new allopolyploids are made.']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2017-A2-Q1c', q: [
  ['The main attributes of seed quality are:', ['Genetic purity, physical purity, germination, vigour, moisture and health', 'Colour only', 'Size only', 'Price only'], 0,
    'A good seed lot must be good on all of them.'],
  ['Seed quality is usually highest when seed is harvested at:', ['Physiological maturity (maximum dry weight)', 'Flowering', 'Milk stage', 'Long after maturity in the field'], 0,
    'Leaving seed in the field too long exposes it to weathering.'],
  ['Rain on mature seed in the field ("weathering") is especially damaging in:', ['Soybean', 'Rice under water', 'Groundnut kept underground', 'Potato tubers'], 0,
    'It causes swelling, cracking and loss of vigour.'],
  ['Pre-harvest factors affecting seed quality include:', ['Mother-plant nutrition, weather during seed development, pests, diseases and isolation', 'Only the storage bag', 'Only the price', 'Only the transport'], 0,
    'Seed quality starts in the field.'],
  ['Seed should be dried at temperatures no higher than about:', ['40–43 °C', '80 °C', '100 °C', '150 °C'], 0,
    'Higher temperatures kill the embryo or cause cracks.'],
  ['The tetrazolium (TZ) test checks seed viability by:', ['Living tissues reducing colourless tetrazolium salt to red formazan', 'Measuring seed weight', 'Measuring seed colour naturally', 'Counting seedlings after two weeks'], 0,
    'Results are ready within a day.'],
  ['Seed vigour tests include:', ['Accelerated ageing, electrical conductivity and seedling vigour index', 'The purity test only', 'The moisture test only', 'The weight test only'], 0,
    'Vigour predicts field emergence better than germination alone.'],
  ['The seedling vigour index (Abdul-Baki and Anderson, 1973) is calculated as:', ['Germination (%) × seedling length (or dry weight)', 'Seed weight × moisture', 'Purity × moisture', 'Germination ÷ purity'], 0,
    'Higher values mean more vigorous seed.'],
  ['Seed-borne diseases such as loose smut affect seed quality by:', ['Carrying the pathogen to the next crop', 'Improving germination', 'Increasing vigour', 'Having no effect'], 0,
    'Seed health testing detects them.'],
  ['Larger, heavier seeds within a lot usually:', ['Give more vigorous seedlings', 'Always fail to germinate', 'Have no advantage', 'Are always diseased'], 0,
    'Grading by size improves the uniformity of stands.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'IFoS-2017-A2-Q1d', q: [
  ['Metal-activated enzymes differ from metalloenzymes in that:', ['Their metal ion is loosely bound and can be removed easily', 'Their metal is tightly bound', 'They contain no metal', 'They are all oxidases'], 0,
    'In metalloenzymes the metal is a fixed part of the structure.'],
  ['Pyruvate kinase requires:', ['K⁺ together with Mg²⁺', 'Only Zn²⁺', 'Only Cu²⁺', 'No metal'], 0,
    'Potassium activates more than 60 plant enzymes.'],
  ['Starch synthase is activated by:', ['K⁺', 'Na⁺', 'Cl⁻', 'Ni²⁺'], 0,
    'Potassium deficiency reduces starch formation.'],
  ['Most kinases that use ATP (e.g., hexokinase) require:', ['Mg²⁺, which forms the Mg–ATP complex', 'Fe²⁺', 'Cu²⁺', 'Mo'], 0,
    'The Mg–ATP complex is the true substrate.'],
  ['PEP carboxylase requires:', ['Mg²⁺', 'Cu²⁺', 'Ni²⁺', 'Mo'], 0,
    'It is the primary CO₂-fixing enzyme of C₄ and CAM plants.'],
  ['Arginase and the NAD-malic enzyme are activated by:', ['Mn²⁺', 'K⁺', 'Cl⁻', 'Zn²⁺'], 0,
    'Manganese also activates several Krebs cycle enzymes.'],
  ['α-Amylase requires:', ['Ca²⁺ for its activity and stability', 'Mo', 'Ni²⁺', 'Co²⁺'], 0,
    'Calcium binds tightly and stabilises the enzyme structure.'],
  ['Catalase and peroxidase contain:', ['Iron in a haem group', 'Copper', 'Zinc', 'Molybdenum'], 0,
    'They break down hydrogen peroxide.'],
  ['Plastocyanin, the mobile electron carrier between the cytochrome *b*₆*f* complex and photosystem I, contains:', ['Copper', 'Iron', 'Manganese', 'Magnesium'], 0,
    'Copper deficiency impairs photosynthesis.'],
  ['The ion needed for water splitting in photosystem II, besides manganese and calcium, is:', ['Chloride (Cl⁻)', 'Sodium', 'Nickel', 'Cobalt'], 0,
    'Chlorine is essential in only tiny amounts.']
] },
{ p: 'A2', t: 'Heterosis, Hybrids & Mutation Breeding', w: 2, pyq: 'IFoS-2017-A2-Q1e', q: [
  ['Chemically induced male sterility uses:', ['Chemical hybridising agents (gametocides) that kill or block pollen without harming the female organs', 'Mutagens that change DNA permanently', 'Mitochondrial genes', 'Irradiation'], 0,
    'The effect is temporary and not inherited.'],
  ['Gametocides are usually applied:', ['Before meiosis in the pollen mother cells', 'After fertilisation', 'At harvest', 'At germination'], 0,
    'Timing is critical for complete sterility.'],
  ['An example of a chemical hybridising agent is:', ['Ethephon (ethrel)', 'Urea', 'Gypsum', 'Potash'], 0,
    'Others include FW-450, maleic hydrazide and sintofen.'],
  ['FW-450 is:', ['Sodium α,β-dichloroisobutyrate, a gametocide', 'A fertiliser', 'A herbicide for rice', 'An insecticide'], 0,
    'It was used experimentally in cotton and other crops.'],
  ['Commercial hybrid wheat in France has been produced using the chemical hybridising agent:', ['Sintofen (Croisor)', 'Glyphosate', 'Atrazine', '2,4-D'], 0,
    'Wheat lacks a convenient CMS system.'],
  ['The main advantage of chemical male sterility is that:', ['Any line can serve as the female parent — no maintainer or restorer lines are needed', 'Sterility is inherited', 'It is always 100% effective', 'It never harms plants'], 0,
    'It speeds up the testing of hybrid combinations.'],
  ['A major limitation of chemical male sterility is:', ['Incomplete sterility, damage to the plant and reduced female fertility', 'Permanent sterility', 'Very low cost', 'No dependence on weather'], 0,
    'Its effect varies with dose, stage and weather.'],
  ['An ideal chemical hybridising agent should:', ['Sterilise pollen selectively, be non-toxic and leave no harmful residues', 'Kill the whole plant', 'Reduce seed set on female plants', 'Persist in the soil for years'], 0,
    'It should also work over a range of doses and stages.'],
  ['The effectiveness of a gametocide is checked by:', ['Pollen stainability tests and seed set on bagged heads', 'Measuring plant height', 'Soil testing', 'Leaf colour'], 0,
    'Bagged heads should set no seed if sterility is complete.'],
  ['Chemically induced sterility differs from cytoplasmic male sterility in that it:', ['Must be applied afresh each season and is not inherited', 'Is inherited through the mother', 'Needs a restorer line', 'Is always permanent'], 0,
    'CMS is carried in the mitochondria.']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 3, pyq: 'IFoS-2017-A2-Q2a', q: [
  ['Dominance differs from epistasis in that dominance involves:', ['Interaction between alleles at the same locus, while epistasis involves genes at different loci', 'Genes at different loci', 'Only sex chromosomes', 'Only cytoplasmic genes'], 0,
    'The masked gene in epistasis is called hypostatic.'],
  ['The term "epistasis" was introduced by:', ['William Bateson (1909)', 'Mendel', 'Morgan', 'de Vries'], 0,
    'It means "standing upon".'],
  ['A 9:3:4 ratio in the F₂ indicates:', ['Recessive epistasis', 'Dominant epistasis', 'Complementary genes', 'Duplicate genes'], 0,
    'Coat colour in mice is the classic example.'],
  ['A 12:3:1 ratio, as in fruit colour of summer squash, indicates:', ['Dominant epistasis', 'Recessive epistasis', 'Complementary genes', 'Codominance'], 0,
    'The dominant white allele masks yellow and green.'],
  ['A 9:7 ratio, first seen in sweet pea flower colour, indicates:', ['Complementary gene action', 'Dominant epistasis', 'Duplicate dominant genes', 'Incomplete dominance'], 0,
    'Both dominant genes are needed for purple flowers.'],
  ['A 15:1 ratio, as in capsule shape of shepherd’s purse (*Capsella*), indicates:', ['Duplicate dominant genes', 'Complementary genes', 'Recessive epistasis', 'Codominance'], 0,
    'Either dominant gene alone gives the triangular capsule.'],
  ['A 13:3 ratio, as in feather colour of certain poultry crosses, indicates:', ['Dominant and recessive (inhibitory) epistasis', 'Complementary genes', 'Duplicate recessive genes', 'Additive genes'], 0,
    'A dominant inhibitor suppresses colour.'],
  ['A 9:6:1 ratio, as in fruit shape of summer squash, indicates:', ['Duplicate genes with cumulative effect', 'Dominant epistasis', 'Complementary genes', 'Codominance'], 0,
    'The three shapes are disc, spherical and elongated.'],
  ['Comb shape in poultry (walnut, rose, pea, single) shows that two interacting genes can:', ['Produce a new phenotype and keep the 9:3:3:1 ratio', 'Give a 3:1 ratio', 'Show no interaction', 'Be sex-linked'], 0,
    'Bateson and Punnett described it.'],
  ['In epistasis, the gene whose expression is masked is called:', ['Hypostatic', 'Epistatic', 'Dominant', 'Codominant'], 0,
    'The masking gene is epistatic.']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2017-A2-Q2b', q: [
  ['Pure live seed (PLS) is calculated as:', ['(Physical purity % × germination %) ÷ 100', 'Purity % + germination %', 'Germination % − purity %', 'Purity % ÷ germination %'], 0,
    'It gives the share of a lot that is both pure and viable.'],
  ['Sample A has 98% purity and 80% germination; sample B has 90% purity and 95% germination. Which should be recommended?', ['Sample B (PLS 85.5%, against 78.4% for A)', 'Sample A (higher purity)', 'Both are equal', 'Neither'], 0,
    'PLS, not purity or germination alone, decides seed value.'],
  ['A seed lot with 95% purity and 90% germination has a PLS of:', ['85.5%', '95%', '90%', '185%'], 0,
    '95 × 90 ÷ 100 = 85.5.'],
  ['If the recommended seed rate is 100 kg/ha for seed of 100% PLS, the rate for a lot with 80% PLS is:', ['125 kg/ha', '80 kg/ha', '100 kg/ha', '180 kg/ha'], 0,
    'Actual rate = recommended rate × 100 ÷ PLS.'],
  ['In a purity analysis, a seed sample is separated into:', ['Pure seed, other crop seed, weed seed and inert matter', 'Big and small seeds only', 'Dead and alive seeds', 'Coloured and white seeds'], 0,
    'Each is expressed as a percentage by weight.'],
  ['In a germination test, the seedlings counted as germinated are:', ['Normal seedlings only', 'All seedlings, including abnormal ones', 'Hard seeds', 'Dead seeds'], 0,
    'Abnormal seedlings would not establish in the field.'],
  ['The minimum germination for certified seed of wheat in India is:', ['85%', '50%', '95%', '70%'], 0,
    'For paddy it is 80%.'],
  ['The minimum physical purity for certified seed of most cereals is:', ['98%', '80%', '90%', '100%'], 0,
    'This is set in the Indian Minimum Seed Certification Standards.'],
  ['Hard seeds in legumes are:', ['Seeds that stay hard and do not take up water during the test', 'Dead seeds', 'Normal seedlings', 'Inert matter'], 0,
    'They are reported separately in the germination result.'],
  ['PLS is important for growers because it:', ['Shows how much of the seed they pay for will actually produce plants', 'Gives the seed colour', 'Gives the seed price', 'Shows the variety name'], 0,
    'It lets seed lots be compared fairly.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 3, pyq: 'IFoS-2017-A2-Q2c', q: [
  ['Non-cyclic photophosphorylation involves:', ['Both photosystems, producing ATP, NADPH and O₂', 'Only PSI, producing only ATP', 'Only PSII, producing only NADPH', 'No light'], 0,
    'Electrons flow from water to NADP⁺.'],
  ['Cyclic photophosphorylation involves:', ['Only PSI, with electrons returning from ferredoxin to the cytochrome *b*₆*f* complex, producing only ATP', 'Both photosystems, producing NADPH', 'Only PSII', 'Water splitting'], 0,
    'No NADPH or O₂ is formed.'],
  ['Photophosphorylation in isolated chloroplasts was discovered in 1954 by:', ['Daniel Arnon', 'Melvin Calvin', 'Robert Hill', 'Peter Mitchell'], 0,
    'He showed that chloroplasts make ATP in the light.'],
  ['The Z-scheme of photosynthetic electron flow was proposed by:', ['Hill and Bendall (1960)', 'Calvin and Benson', 'Hatch and Slack', 'Emerson'], 0,
    'It links two photosystems in series.'],
  ['The reaction-centre chlorophylls of PSII and PSI are:', ['P680 and P700', 'P700 and P680', 'P430 and P870', 'P550 and P600'], 0,
    'The numbers are their absorption peaks in nanometres.'],
  ['Cyclic electron flow is important because it:', ['Adjusts the ATP:NADPH ratio to meet the Calvin cycle’s needs', 'Produces oxygen', 'Fixes nitrogen', 'Reduces NADP⁺'], 0,
    'It is especially active in the bundle sheath of NADP-ME C₄ plants.'],
  ['In non-cyclic flow, electrons pass from PSI via ferredoxin to NADP⁺ through the enzyme:', ['Ferredoxin–NADP⁺ reductase (FNR)', 'Rubisco', 'ATP synthase', 'Catalase'], 0,
    'NADPH is formed on the stromal side.'],
  ['The herbicide DCMU (diuron) blocks:', ['Electron transfer from QA to QB in PSII, stopping non-cyclic but not cyclic flow', 'PSI only', 'ATP synthase', 'Rubisco'], 0,
    'It is a classic tool in photosynthesis research.'],
  ['Emerson’s enhancement effect (1957) showed that:', ['Red and far-red light together give more photosynthesis than the sum of each alone', 'Only blue light works', 'Photosynthesis needs no light', 'Green light is best'], 0,
    'It pointed to two cooperating photosystems.'],
  ['Water is split in PSII according to the equation:', ['2H₂O → 4H⁺ + 4e⁻ + O₂', 'H₂O → H₂ + O', 'CO₂ + H₂O → sugar', '2H₂O → 2H₂ + O₂'], 0,
    'The oxygen-evolving complex catalyses it.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: 'IFoS-2017-A2-Q3a', q: [
  ['Diffusion is:', ['The net movement of molecules from a region of higher to lower concentration (chemical potential)', 'The movement of water only across a membrane', 'Active transport', 'Movement against a concentration gradient'], 0,
    'It needs no membrane.'],
  ['Osmosis is:', ['The movement of water across a selectively permeable membrane from higher to lower water potential', 'The movement of solutes only', 'Diffusion of gases in air', 'Active uptake of ions'], 0,
    'It is a special case of diffusion.'],
  ['The rate of diffusion is described by:', ['Fick’s law', 'Boyle’s law', 'Ohm’s law', 'Mendel’s law'], 0,
    'Rate depends on the concentration gradient, area and distance.'],
  ['Water potential (ψ) of a plant cell is the sum of:', ['Solute potential and pressure potential (plus matric potential)', 'Only pressure potential', 'Only solute potential', 'Temperature and light'], 0,
    'Pure water at atmospheric pressure has ψ = 0.'],
  ['The solute potential of a solution is:', ['Always negative, and it becomes more negative as solutes are added', 'Always positive', 'Zero', 'Unrelated to solutes'], 0,
    'Van’t Hoff: ψs = −CiRT.'],
  ['A cell placed in a hypertonic solution:', ['Loses water and becomes plasmolysed', 'Gains water and bursts', 'Stays unchanged', 'Gains solutes'], 0,
    'At incipient plasmolysis, turgor pressure is zero.'],
  ['Imbibition differs from osmosis in that it is:', ['The uptake of water by colloids such as dry seeds and wood, without a membrane', 'Movement through a membrane', 'Active transport', 'Loss of water'], 0,
    'It can generate great pressure.'],
  ['Water moves rapidly across membranes through:', ['Aquaporins', 'Ion channels only', 'Ribosomes', 'Plasmodesmata only'], 0,
    'They greatly speed up osmotic water flow.'],
  ['Osmotic pressure was first measured with a membrane osmometer by:', ['Wilhelm Pfeffer (1877)', 'Adolf Fick', 'Jacobus van’t Hoff', 'Stephen Hales'], 0,
    'Van’t Hoff later explained the results.'],
  ['Water moving into a cell is called:', ['Endosmosis', 'Exosmosis', 'Guttation', 'Transpiration'], 0,
    'Water moving out is called exosmosis.']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: 'IFoS-2017-A2-Q3b', q: [
  ['Sex-limited characters are:', ['Expressed in only one sex, although the genes are present in both', 'Carried on the Y chromosome', 'Expressed equally in both sexes', 'Controlled by mitochondria'], 0,
    'Milk yield in cattle is the classic example.'],
  ['Sex-influenced characters are:', ['Expressed in both sexes, but dominant in one sex and recessive in the other', 'Expressed in one sex only', 'X-linked', 'Y-linked'], 0,
    'Pattern baldness in humans is an example.'],
  ['Both sex-limited and sex-influenced genes are usually:', ['Autosomal', 'X-linked', 'Y-linked', 'Mitochondrial'], 0,
    'Sex hormones modify their expression.'],
  ['A person heterozygous for the pattern-baldness allele (*Bb*) is:', ['Bald if male, but not if female', 'Bald if female only', 'Bald in both sexes', 'Bald in neither sex'], 0,
    'The allele is dominant in males and recessive in females.'],
  ['In Dorset × Suffolk sheep crosses, heterozygous (*Hh*) animals are:', ['Horned if male, hornless if female', 'Always horned', 'Always hornless', 'Horned if female only'], 0,
    'Horns are a sex-influenced trait.'],
  ['Dairy bulls are selected by progeny testing because milk yield is:', ['Sex-limited — bulls carry the genes but cannot show the trait', 'X-linked', 'Not inherited', 'Sex-influenced'], 0,
    'Their daughters’ yields reveal their breeding value.'],
  ['Cock-feathering in poultry, seen only in males of genotype *hh*, is an example of:', ['A sex-limited trait', 'A sex-linked trait', 'Codominance', 'Epistasis'], 0,
    'Hens are hen-feathered whatever their genotype.'],
  ['Sex-linked characters, unlike sex-limited ones, are:', ['Controlled by genes on the sex chromosomes', 'Autosomal', 'Expressed in one sex only', 'Not inherited'], 0,
    'Colour blindness and haemophilia are X-linked.'],
  ['X-linked recessive traits show:', ['Criss-cross inheritance, from mother to son', 'Only father-to-son transmission', 'No pattern', 'Equal frequency in both sexes'], 0,
    'Affected males are far more common than affected females.'],
  ['Genes carried only on the Y chromosome are called:', ['Holandric genes', 'Epistatic genes', 'Hypostatic genes', 'Complementary genes'], 0,
    'They pass from father to son only.']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2017-A2-Q3c', q: [
  ['"Synchrony" (nicking) in hybrid seed production means:', ['The male parent shedding pollen at the same time as the female’s stigmas are receptive', 'Both parents being the same height', 'Sowing both parents on the same day always', 'Harvesting both parents together'], 0,
    'Without it, seed set on the female is poor.'],
  ['Synchrony is most often achieved by:', ['Staggered sowing of the parents', 'Increasing the seed rate', 'Removing the male parent', 'Delaying harvest'], 0,
    'The later-flowering parent is sown first.'],
  ['In hybrid rice seed production, the restorer (R) line is often sown:', ['In two or three staggered batches to extend the pollen supply', 'Once, after the A line flowers', 'Not at all', 'Only in the next season'], 0,
    'This covers the whole flowering period of the A line.'],
  ['When flowering is out of step, the late parent can be speeded up or the early one delayed by:', ['Adjusting nitrogen, irrigation or GA₃ sprays', 'Changing the variety', 'Replanting both', 'Harvesting early'], 0,
    'Extra nitrogen tends to delay flowering.'],
  ['The planting ratio in hybrid seed production is:', ['The ratio of female to male rows', 'The ratio of seed to fertiliser', 'The ratio of plants to weeds', 'The ratio of fields to farmers'], 0,
    'More female rows mean more hybrid seed per hectare.'],
  ['A common female-to-male row ratio in hybrid maize seed production is about:', ['4:1 or 6:2', '1:4', '1:1', '20:1'], 0,
    'The ratio depends on how much pollen the male line sheds.'],
  ['The planting ratio depends on:', ['The male parent’s pollen output, relative plant heights, wind and pollinator activity', 'Only seed price', 'Only soil pH', 'Only rainfall'], 0,
    'A prolific pollen parent allows more female rows.'],
  ['Male-parent border rows are planted around a hybrid seed plot to:', ['Supply extra pollen and act as a barrier to foreign pollen', 'Increase female rows', 'Reduce isolation', 'Feed birds'], 0,
    'They also improve pollination at the edges.'],
  ['After pollination, the male rows in a hybrid seed field are often:', ['Removed, to avoid mixing their seed with the hybrid seed', 'Harvested together with the female rows', 'Left for the next year', 'Sprayed with fertiliser'], 0,
    'Only the female rows yield hybrid seed.'],
  ['In rice hybrid seed production, flag-leaf clipping helps by:', ['Removing a barrier so pollen moves freely to the A-line panicles', 'Increasing leaf area', 'Delaying flowering', 'Adding nitrogen'], 0,
    'Rope pulling at anthesis also spreads pollen.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 3, pyq: 'IFoS-2017-A2-Q4a', q: [
  ['Red light converts phytochrome from:', ['Pr to the active Pfr form', 'Pfr to Pr', 'Pr to chlorophyll', 'Pfr to carotene'], 0,
    'Far-red light reverses the change.'],
  ['Processes mediated by phytochrome include:', ['Seed germination, de-etiolation, photoperiodic flowering and shade avoidance', 'Only root growth', 'Only nitrogen fixation', 'Only water uptake'], 0,
    'It also controls anthocyanin synthesis and tuberisation.'],
  ['Photomorphogenesis refers to:', ['Light-controlled development, such as a seedling greening and opening its leaves', 'Growth in darkness', 'Photosynthesis', 'Phototropism only'], 0,
    'Growth in darkness (etiolation) is skotomorphogenesis.'],
  ['Very-low-fluence responses (VLFR), which are not reversible by far-red light, are mediated mainly by:', ['phyA', 'phyB', 'Cryptochrome', 'Phototropin'], 0,
    'They respond to extremely small amounts of light.'],
  ['Low-fluence responses (LFR), which are classically red/far-red reversible, are mediated mainly by:', ['phyB', 'phyA', 'UVR8', 'Zeitlupe'], 0,
    'Lettuce seed germination is a classic LFR.'],
  ['Etiolated (dark-grown) seedlings contain large amounts of:', ['phyA, which is rapidly degraded in light', 'phyB only', 'Chlorophyll', 'Cryptochrome only'], 0,
    'phyA helps them detect the first light at the soil surface.'],
  ['Potato tuberisation is promoted by:', ['Short days, perceived by phytochrome in the leaves', 'Long days', 'Continuous light', 'Red light at night'], 0,
    'The leaf signal travels to the stolons.'],
  ['*Arabidopsis phyB* mutants are:', ['Elongated and early-flowering, as if always in shade', 'Dwarf and late-flowering', 'Unable to germinate', 'Albino'], 0,
    'They cannot sense a high red to far-red ratio.'],
  ['The reciprocity law (response depends only on total light dose) holds for:', ['Low-fluence responses', 'High-irradiance responses', 'All light responses', 'None'], 0,
    'High-irradiance responses depend on duration and intensity.'],
  ['High-irradiance responses (HIR), such as anthocyanin synthesis in seedlings, need:', ['Prolonged exposure to fairly intense light', 'A single flash', 'Darkness', 'No light'], 0,
    'Far-red HIR is mediated by phyA.']
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: 'IFoS-2017-A2-Q4b', q: [
  ['A key advantage of DNA markers over morphological markers is that they:', ['Are not affected by the environment or plant stage', 'Are always visible to the eye', 'Depend on weather', 'Are few in number'], 0,
    'Morphological traits often vary with the environment.'],
  ['DNA markers can be scored:', ['From any tissue at the seedling stage', 'Only at flowering', 'Only from seeds', 'Only after harvest'], 0,
    'This lets breeders select early and save time and space.'],
  ['Compared with morphological or isozyme markers, DNA markers are:', ['Practically unlimited in number and spread across the genome', 'Few and clustered', 'Only on one chromosome', 'Only in chloroplasts'], 0,
    'Dense maps can be built with them.'],
  ['DNA markers are usually "neutral", meaning that they:', ['Do not affect the plant’s phenotype', 'Always change yield', 'Cause diseases', 'Are lethal'], 0,
    'Morphological markers may have unwanted effects.'],
  ['A limitation of biochemical markers (isozymes and seed proteins) is that they:', ['Show limited polymorphism and are tissue- or stage-specific', 'Are unlimited', 'Are unaffected by tissue', 'Are all codominant DNA markers'], 0,
    'They were widely used before DNA markers.'],
  ['DNA markers help transfer a recessive gene by backcrossing because:', ['Carriers can be identified without progeny testing', 'Recessive genes are always visible', 'Selfing is not needed ever', 'Markers change dominance'], 0,
    'This saves a generation at each backcross.'],
  ['In marker-assisted backcrossing, "background selection" is used to:', ['Recover the recurrent parent’s genome faster', 'Select the target gene only', 'Create mutations', 'Find disease symptoms'], 0,
    'It can save two or three backcross generations.'],
  ['SSR markers can test the genetic purity of hybrid seed:', ['Quickly in the laboratory, instead of a season-long grow-out test', 'Only after a field season', 'Never', 'Only for inbreds'], 0,
    'A true hybrid shows the bands of both parents.'],
  ['DNA fingerprinting with markers is useful for:', ['Identifying varieties and protecting breeders’ rights', 'Measuring yield directly', 'Estimating rainfall', 'Soil testing'], 0,
    'It supports DUS testing and settles disputes.'],
  ['DNA markers are not affected by:', ['Dominance and epistasis between genes', 'Their position in the genome', 'The DNA extraction method', 'PCR conditions'], 0,
    'Morphological markers can be masked by gene interactions.']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: 'IFoS-2017-A2-Q4c', q: [
  ['Seed quality in India is regulated mainly under:', ['The Seeds Act, 1966 and the Seeds Rules, 1968', 'The Insecticides Act, 1968', 'The Patents Act', 'The Forest Act'], 0,
    'The Seed (Control) Order, 1983 adds licensing of dealers.'],
  ['Seed certification in India is:', ['Voluntary, while truthful labelling of notified kinds is compulsory', 'Compulsory for all seed', 'Banned', 'Done only by private firms'], 0,
    'Truthfully labelled seed carries an opal-green label.'],
  ['The Seed (Control) Order, 1983 was issued under the:', ['Essential Commodities Act', 'Seeds Act', 'Environment Protection Act', 'Companies Act'], 0,
    'It requires seed dealers to be licensed.'],
  ['The first State Seed Certification Agency was set up in 1970 in:', ['Maharashtra', 'Punjab', 'Kerala', 'Bihar'], 0,
    'Every state now has one.'],
  ['The National Seeds Corporation was established in:', ['1963', '1991', '2005', '1947'], 0,
    'It was India’s first public seed company.'],
  ['The Central Seed Testing Laboratory functions at:', ['NSRTC, Varanasi', 'IARI, New Delhi only', 'ICRISAT, Hyderabad', 'NDRI, Karnal'], 0,
    'It is the National Seed Research and Training Centre.'],
  ['The standards used in India for seed certification are the:', ['Indian Minimum Seed Certification Standards (IMSCS)', 'ISTA rules only', 'OECD standards only', 'BIS food standards'], 0,
    'They were first published in 1971 and revised in 2013.'],
  ['India joined the OECD Seed Schemes in 2008 to:', ['Certify seed for international trade', 'Import all seed', 'Ban exports', 'Replace the Seeds Act'], 0,
    'It helps Indian seed reach export markets.'],
  ['Policy-level advice on seed certification in India comes from the:', ['Central Seed Certification Board', 'NABARD', 'FCI', 'RBI'], 0,
    'It was set up under the Seeds Act.'],
  ['The SATHI portal (2023) is meant to:', ['Trace seed from production to sale and curb spurious seed', 'Sell fertilisers', 'Provide crop insurance', 'Register land'], 0,
    'SATHI stands for Seed Traceability, Authentication and Holistic Inventory (recent — check status).']
] }
);
