/* Concept sets for Agriculture I — Soil reaction, soil biology, soil physics and soils of India. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Problem Soils & Soil Conservation', w: 2, pyq: ['CSE-2022-A1-m24', 'IFoS-2020-A1-m27', 'CSE-2015-A1-m21', 'CSE-2017-A1-m16', 'IFoS-2004-A1-m12', 'CSE-2003-A1-m09', 'CSE-1995-A1-m14', 'CSE-1998-A1-m12', 'CSE-2015-A1-m16', 'CSE-1992-A1-m11'], q: [
  ['Acid soils form mainly through:', ['Leaching of basic cations under high rainfall, acidic parent rocks and acid-forming fertilisers', 'Accumulation of sodium salts', 'Low rainfall and high evaporation', 'Addition of lime'], 0,
    'Ammonium sulphate is strongly acid-forming.'],
  ['In strongly acid soils, crops suffer mainly from:', ['Aluminium and manganese toxicity and phosphorus fixation', 'Sodium toxicity', 'Boron excess', 'Too much calcium'], 0,
    'Calcium, magnesium and molybdenum deficiencies also occur.'],
  ['Legume nodulation in acid soils is poor because:', ['Low pH and Al toxicity hamper rhizobia and Mo supply', 'There is too much calcium', 'Nitrogen is excessive', 'Soils are too dry'], 0,
    'Liming restores nodulation.'],
  ['Acid soils are reclaimed by:', ['Liming with calcium carbonate or dolomite', 'Adding gypsum', 'Adding sulphur', 'Adding urea'], 0,
    'Dolomite also supplies magnesium; basic slag and press mud are alternatives.'],
  ['Lime requirement is commonly determined by the:', ['SMP buffer method', 'Leaching requirement formula', 'Olsen method', 'Kjeldahl method'], 0,
    'Leaching requirement (EC_iw/EC_dw) is for saline soils.'],
  ['In India, acid soils are most extensive in:', ['The North-East, Kerala, Odisha and Jharkhand', 'Punjab and Haryana', 'Rajasthan', 'Gujarat'], 0,
    'Roughly a third of cultivated land is acidic (estimates vary).'],
  ['Redox potential (Eh) in flooded soils:', ['Falls as oxygen is used up, and nitrate, Mn, Fe and sulphate are reduced in turn', 'Rises steadily', 'Stays constant', 'Becomes strongly positive'], 0,
    'Methane forms at the lowest Eh.'],
  ['After flooding, the pH of both acid and alkaline soils tends to:', ['Move towards neutrality (about 6.5–7)', 'Become strongly acid', 'Become strongly alkaline', 'Stay unchanged'], 0,
    'Reduction of Fe and Mn raises pH of acid soils; CO₂ lowers that of alkaline soils.'],
  ['Acid sulphate soils develop when:', ['Pyrite-rich sediments are drained and oxidised, forming sulphuric acid', 'Lime is added', 'Sodium accumulates', 'Soils are flooded continuously'], 0,
    'They occur in coastal Kerala (Kuttanad).'],
  ['Phosphorus availability in acid soils is low because P is fixed by:', ['Iron and aluminium', 'Sodium', 'Calcium only', 'Nitrogen'], 0,
    'In alkaline soils it is fixed by calcium.']
] },
{ p: 'A1', t: 'Soil Genesis, Classification & Properties', w: 2, pyq: ['IFoS-2010-A1-m21', 'IFoS-2015-A1-m18', 'CSE-2008-A1-m09', 'IFoS-2011-A1-m24', 'IFoS-2019-A1-m24', 'CSE-2014-A1-m24', 'IFoS-2024-A1-m28'], q: [
  ['The most numerous microorganisms in soil are:', ['Bacteria', 'Fungi', 'Algae', 'Protozoa'], 0,
    'Fungi often dominate biomass, especially in acid soils.'],
  ['The earthy smell of moist soil is due to geosmin produced by:', ['Actinomycetes', 'Earthworms', 'Algae', 'Viruses'], 0,
    '*Streptomyces* is a common soil actinomycete.'],
  ['Earthworms improve soil by:', ['Burrowing, mixing organic matter and forming stable casts', 'Compacting soil', 'Fixing nitrogen directly', 'Killing all microbes'], 0,
    'Darwin studied them; they are called ecosystem engineers.'],
  ['The rhizosphere effect, described by Hiltner (1904), is:', ['Higher microbial activity around roots than in bulk soil', 'Lower microbial numbers near roots', 'Root death', 'Soil compaction'], 0,
    'It is expressed as the R:S ratio.'],
  ['Soil biological properties are good early indicators of soil health because they:', ['Respond quickly to management changes', 'Never change', 'Depend only on parent rock', 'Are unrelated to fertility'], 0,
    'E.g. microbial biomass carbon, soil respiration, dehydrogenase activity.'],
  ['Soil sickness after repeated monocropping is caused mainly by:', ['Build-up of pathogens, nematodes and toxic residues', 'Excess organic matter', 'Too many earthworms', 'Low salinity'], 0,
    'Crop rotation, solarisation and organic amendments are remedies.'],
  ['Bio-inoculants improve soil health by:', ['Adding beneficial microbes that fix N, solubilise P and suppress pathogens', 'Adding heavy metals', 'Killing microbes', 'Increasing salinity'], 0,
    'PGPR and *Trichoderma* are examples.'],
  ['Soil fungi are especially important for:', ['Decomposing lignin and cellulose and forming mycorrhizae', 'Fixing nitrogen', 'Producing geosmin', 'Photosynthesis'], 0,
    'White-rot fungi break down lignin.'],
  ['A biological practice that improves soil is:', ['Green manuring and crop rotation with legumes', 'Burning stubble', 'Continuous fallow', 'Excess tillage'], 0,
    'Mulching and composting are others.'],
  ['Nematodes in soil include:', ['Both plant parasites and beneficial free-living forms', 'Only beneficial forms', 'Only nitrogen fixers', 'Only algae'], 0,
    'Root-knot nematodes are serious pests.']
] },
{ p: 'A1', t: 'Soil Genesis, Classification & Properties', w: 2, pyq: ['IFoS-2006-A1-m11', 'CSE-1996-A1-m12', 'CSE-2014-A1-m25', 'CSE-1993-A1-m13', 'IFoS-2004-A1-m13', 'IFoS-2002-A1-m07', 'CSE-2000-A1-m06'], q: [
  ['The particle density of most mineral soils is about:', ['2.65 g/cm³', '1.0 g/cm³', '1.3 g/cm³', '5.0 g/cm³'], 0,
    'Bulk density is usually 1.1–1.6 g/cm³.'],
  ['A soil with bulk density 1.325 g/cm³ and particle density 2.65 g/cm³ has a porosity of:', ['50%', '25%', '75%', '10%'], 0,
    'Porosity = (1 − BD/PD) × 100.'],
  ['Water available to plants is the:', ['Capillary water held between field capacity and the permanent wilting point', 'Hygroscopic water', 'Gravitational water', 'Water vapour'], 0,
    'Hygroscopic water is held too tightly; gravitational water drains away.'],
  ['Field capacity corresponds to a soil water potential of about:', ['−0.033 MPa', '−1.5 MPa', '−3.1 MPa', '0 MPa'], 0,
    'Permanent wilting point is about −1.5 MPa.'],
  ['Hydraulic conductivity of soil is described by:', ['Darcy\'s law', 'Stokes\' law', 'Boyle\'s law', 'Fick\'s law'], 0,
    'Sandy soils conduct water fastest; clays slowest.'],
  ['Permeability differs from hydraulic conductivity in that permeability:', ['Is a property of the soil pores alone, independent of the fluid', 'Depends on the fluid viscosity', 'Is the same thing', 'Applies only to air'], 0,
    'Hydraulic conductivity depends on both soil and water properties.'],
  ['Water absorption and retention of a sandy soil can be improved by:', ['Adding organic matter, tank silt or clay and mulching', 'Removing organic matter', 'Deep ploughing every week', 'Adding sand'], 0,
    'Minimum tillage also helps keep structure.'],
  ['Atmospheric drought differs from soil drought in that it:', ['Results from low humidity and high evaporative demand even when soil has water', 'Means no water in the soil', 'Occurs only at night', 'Happens only in winter'], 0,
    'Plants can wilt in hot, dry winds despite moist soil.'],
  ['In the USDA system, clay particles are those smaller than:', ['0.002 mm', '0.05 mm', '2 mm', '0.2 mm'], 0,
    'Silt is 0.05–0.002 mm; sand is 2–0.05 mm.'],
  ['Stokes\' law is used in soil science for:', ['Particle-size (mechanical) analysis by settling velocity', 'Water flow', 'Nutrient uptake', 'Soil colour'], 0,
    'Larger particles settle faster.']
] },
{ p: 'A1', t: 'Soil Genesis, Classification & Properties', w: 2, pyq: ['CSE-2025-A1-m22', 'IFoS-2002-A1-m02', 'IFoS-2021-A1-m10', 'IFoS-2022-A1-m13'], q: [
  ['ICAR groups Indian soils into:', ['Eight major groups — alluvial, black, red and yellow, laterite, arid, saline–alkaline, peaty–marshy and forest–mountain', 'Three groups', 'Twelve orders only', 'Two groups'], 0,
    'Alluvial soils cover the largest area.'],
  ['The largest soil group of India by area is:', ['Alluvial soils', 'Black soils', 'Laterite soils', 'Desert soils'], 0,
    'Newer khadar and older bhangar alluvium are distinguished.'],
  ['Black (regur) soils are characterised by:', ['Montmorillonite clay, high shrink–swell and deep cracks on drying', 'Low clay and high sand', 'High iron oxide and acidity', 'High organic matter like peat'], 0,
    'They are Vertisols, good for cotton.'],
  ['Red soils owe their colour to:', ['Iron oxides', 'Organic matter', 'Calcium carbonate', 'Sodium'], 0,
    'They are generally low in N, P and organic matter.'],
  ['Laterite soils form under:', ['High rainfall and temperature with intense leaching, leaving Fe and Al oxides', 'Arid conditions', 'Waterlogging only', 'Cold climates'], 0,
    'They are acidic and suit plantation crops.'],
  ['In USDA Soil Taxonomy, black cotton soils belong to the order:', ['Vertisols', 'Alfisols', 'Aridisols', 'Oxisols'], 0,
    'Most Indian soils are Inceptisols and Entisols.'],
  ['Land capability classification groups land into:', ['Eight classes; I–IV suitable for cultivation, V–VIII not', 'Four classes all arable', 'Ten classes by soil colour', 'Two classes'], 0,
    'Klingebiel and Montgomery (USDA) devised it.'],
  ['In land capability subclasses, the letter "e" indicates a limitation due to:', ['Erosion', 'Wetness', 'Soil root-zone', 'Climate'], 0,
    'w = wetness, s = soil limitations, c = climate.'],
  ['Class VIII land in land capability classification is best used for:', ['Wildlife, recreation and watershed protection', 'Intensive cropping', 'Paddy', 'Orchards'], 0,
    'It has severe limitations.'],
  ['The national institute for soil survey and land-use planning is located in:', ['Nagpur (NBSS&LUP)', 'Bhopal', 'Karnal', 'Dehradun'], 0,
    'IISS Bhopal works on soil science; CSSRI Karnal on salinity.']
] }
);
