/* Concept sets for Agriculture II — Crop physiology: respiration, photosynthesis, growth regulators, growth and development, mineral nutrition. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 3, pyq: ['CSE-2024-A2-m20', 'CSE-2016-A2-m20', 'CSE-2015-A2-m24', 'CSE-2006-A2-m18', 'IFoS-2005-A2-m24', 'IFoS-2001-A2-m20', 'CSE-2000-A2-m27', 'CSE-1998-A2-m14', 'CSE-1993-A2-m24', 'CSE-1990-A2-m28', 'CSE-1989-A2-m29', 'CSE-1990-A2-m24', 'CSE-2012-A2-m19', 'CSE-2016-A2-m18', 'CSE-2014-A2-m21', 'CSE-2023-A2-m21'], q: [
  ['The two phases of aerobic respiration are:', ['Glycolysis in the cytosol, then the Krebs cycle and electron transport in mitochondria', 'Light and dark reactions', 'Calvin cycle and glycolysis', 'Fermentation and photolysis'], 0,
    'Overall: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy.'],
  ['Anaerobic respiration in waterlogged roots produces mainly:', ['Ethanol and CO₂, with only 2 ATP per glucose', 'Lactic acid and 38 ATP', 'Oxygen', 'Starch'], 0,
    'Pyruvate decarboxylase and alcohol dehydrogenase regenerate NAD⁺.'],
  ['The Pasteur effect is:', ['Slowing of glycolysis and fermentation when oxygen is available', 'Speeding of photosynthesis by light', 'Ripening by ethylene', 'Germination by gibberellin'], 0,
    'Aerobic respiration makes far more ATP, so less glucose is needed.'],
  ['Photosynthesis differs from respiration in that photosynthesis:', ['Is anabolic, light-driven and releases O₂ in chloroplasts', 'Is catabolic and goes on day and night', 'Consumes O₂ in mitochondria', 'Releases CO₂'], 0,
    'Respiration is catabolic and happens in all living cells.'],
  ['Oxidative decarboxylation of pyruvate gives:', ['Acetyl-CoA, CO₂ and NADH, catalysed by pyruvate dehydrogenase', 'Lactate', 'Glucose', 'Ethanol only'], 0,
    'The complex needs TPP, lipoic acid, CoA, FAD and NAD⁺.'],
  ['Another oxidative decarboxylation in the Krebs cycle converts:', ['α-ketoglutarate to succinyl-CoA', 'Citrate to isocitrate', 'Fumarate to malate', 'Malate to oxaloacetate'], 0,
    'Isocitrate dehydrogenase also releases CO₂.'],
  ['Alcohol dehydrogenase catalyses:', ['Acetaldehyde + NADH → ethanol + NAD⁺', 'Pyruvate → acetaldehyde + CO₂', 'Glucose → pyruvate', 'Ethanol → acetyl-CoA'], 0,
    'Pyruvate decarboxylase (with TPP) forms acetaldehyde.'],
  ['The pentose phosphate pathway supplies:', ['NADPH and ribose-5-phosphate', 'Ethanol', 'ATP only', 'Oxygen'], 0,
    'It runs in the cytosol and plastids.'],
  ['Respiration is essential for crops because it:', ['Supplies ATP and carbon skeletons for growth and maintenance', 'Only wastes sugar', 'Produces oxygen', 'Fixes nitrogen'], 0,
    'Maintenance respiration rises with temperature.'],
  ['Seeds germinating under flooding often rot because:', ['Low oxygen forces fermentation, giving little energy and toxic products', 'They photosynthesise too much', 'They absorb too little water', 'They lack enzymes'], 0,
    'Some rice varieties tolerate anaerobic germination.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 3, pyq: ['CSE-2005-A2-m16', 'CSE-1998-A2-m13', 'IFoS-2021-A2-m20', 'IFoS-2006-A2-m21', 'CSE-2025-A2-m20', 'IFoS-2005-A2-m23', 'CSE-1994-A2-m13', 'CSE-1989-A2-m34', 'CSE-2004-A2-m19', 'CSE-2000-A2-m25', 'CSE-2015-A2-m25'], q: [
  ['The light reactions of photosynthesis take place in the:', ['Thylakoid membranes, producing ATP, NADPH and O₂', 'Stroma, fixing CO₂', 'Cytosol', 'Mitochondria'], 0,
    'The Calvin cycle in the stroma uses that ATP and NADPH.'],
  ['Blackman\'s law of limiting factors (1905) states that:', ['The rate of a process is limited by the factor in shortest supply', 'All factors act equally', 'Light is always limiting', 'Temperature never limits'], 0,
    'Raising other factors has no effect until the limiting one is raised.'],
  ['The light compensation point is the light intensity at which:', ['Photosynthesis equals respiration', 'Photosynthesis is maximum', 'Leaves die', 'Stomata close'], 0,
    'Above the saturation point more light gives no gain.'],
  ['Chlorophylls absorb most strongly in:', ['Blue and red light', 'Green light', 'Infrared', 'Ultraviolet only'], 0,
    'Green light is largely reflected.'],
  ['Carotenoids in photosynthesis act as:', ['Accessory pigments and protectors against photo-oxidation', 'The reaction-centre pigment', 'CO₂ acceptors', 'Enzymes'], 0,
    'Chlorophyll a is the primary reaction-centre pigment.'],
  ['Photosynthesis of leaves in the field is commonly measured with an:', ['Infrared gas analyser (IRGA) measuring CO₂ exchange', 'Ammeter', 'Barometer', 'Hygrometer'], 0,
    'Oxygen electrodes and ¹⁴C uptake are other methods.'],
  ['Rising atmospheric CO₂ is expected to benefit:', ['C₃ crops more than C₄ crops', 'C₄ crops more than C₃ crops', 'Neither', 'Only CAM plants'], 0,
    'Higher temperatures, however, raise photorespiration and stress.'],
  ['The Calvin cycle needs, for each CO₂ fixed:', ['3 ATP and 2 NADPH', '1 ATP and 1 NADPH', '5 ATP and 2 NADPH', 'No energy'], 0,
    'C₄ plants need extra ATP for regenerating PEP.'],
  ['Magnesium is essential for photosynthesis because it:', ['Is the central atom of chlorophyll', 'Splits water', 'Is part of RuBisCO\'s active site only', 'Carries electrons in PSI'], 0,
    'Nitrogen is also part of chlorophyll.'],
  ['The overall photosynthetic equation shows that the oxygen released comes from:', ['Water', 'Carbon dioxide', 'Glucose', 'Chlorophyll'], 0,
    '6CO₂ + 12H₂O → C₆H₁₂O₆ + 6O₂ + 6H₂O.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 3, pyq: ['CSE-2025-A2-m22', 'IFoS-2021-A2-m21', 'CSE-2020-A2-m18', 'CSE-2020-A2-m22', 'CSE-2017-A2-m19', 'CSE-2002-A2-m20', 'IFoS-2023-A2-m30', 'IFoS-2015-A2-m22', 'CSE-2012-A2-m17', 'IFoS-2006-A2-m22', 'CSE-1991-A2-m27', 'CSE-1995-A2-m16', 'CSE-1993-A2-m29', 'CSE-1989-A2-m35', 'CSE-2023-A2-m18', 'CSE-2018-A2-m18', 'CSE-2006-A2-m17', 'CSE-2001-A2-m24', 'CSE-1992-A2-m39', 'CSE-1999-A2-m16', 'CSE-1992-A2-m37', 'IFoS-2020-A2-m24', 'IFoS-2002-A2-m16', 'CSE-1998-A2-m16', 'CSE-1997-A2-m22', 'IFoS-2024-A2-m28', 'IFoS-2016-A2-m20', 'CSE-1998-A2-m15', 'IFoS-2022-A2-m26', 'IFoS-2006-A2-m23', 'IFoS-2014-A2-m13', 'IFoS-2009-A2-m07', 'IFoS-2023-A2-m31', 'CSE-2020-A2-m19', 'IFoS-2019-A2-m15', 'CSE-2018-A2-m19', 'CSE-2013-A2-m28', 'CSE-2007-A2-m22', 'IFoS-2003-A2-m23', 'IFoS-2024-A2-m29'], q: [
  ['Plant growth regulators differ from plant hormones in that PGRs:', ['Include synthetic compounds as well as natural hormones', 'Are only natural', 'Are always inhibitors', 'Work only in animals'], 0,
    'Hormones are natural, made in one part and active elsewhere in small amounts.'],
  ['Which is a synthetic auxin widely used for rooting cuttings?', ['IBA (indole-3-butyric acid)', 'Kinetin', 'GA₃', 'Ethephon'], 0,
    'NAA prevents fruit drop; 2,4-D is a selective herbicide.'],
  ['Gibberellins are synthesised through:', ['The terpenoid pathway via GGPP and ent-kaurene', 'Tryptophan', 'Methionine', 'Adenine'], 0,
    'Uses include larger grape berries, malting and breaking dormancy.'],
  ['Cytokinins mainly:', ['Promote cell division and delay senescence', 'Close stomata', 'Promote abscission', 'Cause dormancy'], 0,
    'They are made mainly in root tips.'],
  ['Abscisic acid is synthesised from:', ['Carotenoids, via xanthoxin', 'Tryptophan', 'Mevalonate directly to GA', 'Adenine'], 0,
    'It closes stomata and maintains dormancy under stress.'],
  ['Ethephon is used in agriculture because it:', ['Releases ethylene in plant tissues, promoting ripening and flowering', 'Supplies nitrogen', 'Kills insects', 'Blocks ethylene'], 0,
    'Chemically it is 2-chloroethylphosphonic acid.'],
  ['Brassinosteroids are plant steroids that:', ['Promote cell elongation and stress tolerance', 'Inhibit all growth', 'Act only as pesticides', 'Cause wilting'], 0,
    'Salicylic acid mediates systemic acquired resistance.'],
  ['Maleic hydrazide is used to:', ['Suppress sprouting of onion and potato in storage', 'Induce flowering', 'Promote rooting', 'Break seed dormancy'], 0,
    'Other retardants: chlormequat (CCC), paclobutrazol, daminozide.'],
  ['Growth retardants such as CCC are used in cereals to:', ['Shorten stems and reduce lodging', 'Increase plant height', 'Delay germination', 'Increase tillers by elongation'], 0,
    'They block gibberellin biosynthesis.'],
  ['Pheromones (once called "ecto-hormones") differ from hormones in that they:', ['Act as chemical signals between individuals of the same species', 'Act inside the organism that makes them', 'Are only plant products', 'Are enzymes'], 0,
    'Insect sex pheromones are used in pest monitoring and mating disruption.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 3, pyq: ['IFoS-2025-A2-Q7c', 'CSE-2021-A2-m20', 'IFoS-2015-A2-m27', 'CSE-2014-A2-m23', 'IFoS-2013-A2-m29', 'IFoS-2010-A2-m19', 'CSE-2001-A2-m23', 'CSE-2000-A2-m26', 'CSE-1993-A2-m28', 'CSE-2025-A2-m21', 'IFoS-2024-A2-m22', 'CSE-2014-A2-m20', 'CSE-1997-A2-m23', 'CSE-1993-A2-m25', 'IFoS-2003-A2-m22', 'CSE-1995-A2-m15', 'CSE-1994-A2-m12', 'IFoS-2021-A2-m22', 'IFoS-2000-A2-m11', 'CSE-1995-A2-m17', 'IFoS-2015-A2-m26', 'CSE-2001-A2-m26', 'CSE-1993-A2-m31', 'IFoS-2015-A2-m24', 'IFoS-2013-A2-m28', 'IFoS-2014-A2-m15', 'CSE-1995-A2-m18', 'IFoS-2009-A2-m09', 'CSE-1992-A2-m33', 'CSE-2026-A2-Q6b', 'CSE-1992-A2-m36', 'CSE-2025-A2-m23', 'IFoS-2023-A2-m32', 'CSE-2020-A2-m20'], q: [
  ['Growth differs from development in that growth is:', ['An irreversible increase in size or mass, while development includes differentiation and phase change', 'Only cell death', 'The same as development', 'Reversible shrinkage'], 0,
    'Development runs from germination to senescence.'],
  ['The sigmoid growth curve has phases:', ['Lag, log (exponential) and stationary', 'Only exponential', 'Linear only', 'Decline then rise'], 0,
    'Most crops and organs follow it.'],
  ['The practical use of apical dominance includes:', ['Pinching or topping to promote branching, as in chrysanthemum and carnation', 'Increasing plant height only', 'Stopping flowering', 'Breaking dormancy'], 0,
    'Auxin from the apex suppresses lateral buds.'],
  ['Vernalisation is:', ['Promotion of flowering by a period of low temperature (about 0–10 °C)', 'Breaking seed dormancy by light', 'Flowering under long days', 'Fruit ripening'], 0,
    'Winter cereals and biennials need it; high temperature soon after can devernalise.'],
  ['The vernalisation stimulus is perceived by:', ['Actively dividing cells of the shoot apex', 'Mature leaves', 'Roots', 'Flowers'], 0,
    'Photoperiod is perceived by leaves.'],
  ['The hormone "florigen" proposed by Chailakhyan is now identified mainly with:', ['The FT protein moving from leaves to the shoot apex', 'Gibberellin only', 'Auxin', 'Ethylene'], 0,
    'Vernalin was a hypothetical cold-induced substance (Melchers).'],
  ['Climacteric fruits differ from non-climacteric fruits in that they:', ['Show a rise in respiration and ethylene during ripening and can ripen after harvest', 'Do not ripen after harvest', 'Have no ethylene', 'Never soften'], 0,
    'Mango, banana, tomato and apple are climacteric; citrus, grape and strawberry are not.'],
  ['Ripening of climacteric fruits can be delayed by:', ['Cold storage, controlled atmosphere and 1-MCP', 'Ethephon', 'Warm storage', 'Calcium carbide'], 0,
    'Potassium permanganate absorbs ethylene in packs.'],
  ['Phototropism differs from geotropism in that the stimulus is:', ['Light rather than gravity', 'Touch', 'Water', 'Chemicals'], 0,
    'Phototropins sense blue light; amyloplast statoliths sense gravity.'],
  ['Blossom-end rot of tomato is a physiological disorder due to:', ['Calcium deficiency in the fruit, often with irregular watering', 'A virus', 'A fungus', 'Excess boron'], 0,
    'Black heart of potato results from oxygen shortage in storage.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 3, pyq: ['CSE-2026-A2-Q6c', 'CSE-2018-A2-m15', 'CSE-2015-A2-m21', 'CSE-2025-A2-m17', 'CSE-2013-A2-m27', 'CSE-2017-A2-m23', 'CSE-2019-A2-m20', 'CSE-2020-A2-m17', 'CSE-1992-A2-m32', 'CSE-2017-A2-m20'], q: [
  ['Arnon and Stout\'s criteria of essentiality require that an element:', ['Is needed to complete the life cycle, cannot be replaced by another, and acts directly in metabolism', 'Is present in plant ash', 'Increases yield when added', 'Is abundant in soil'], 0,
    'Seventeen elements meet these criteria, including nickel.'],
  ['Which group lists only micronutrients?', ['Fe, Mn, Zn, Cu, B, Mo, Cl, Ni', 'N, P, K', 'Ca, Mg, S', 'C, H, O'], 0,
    'Macronutrients are needed in much larger amounts.'],
  ['In the biochemical classification of nutrients, N and S are grouped as:', ['Constituents of organic compounds (proteins, amino acids)', 'Elements in ionic form only', 'Redox-active chelates', 'Ester-forming elements'], 0,
    'P and B form esters; K, Mg, Ca act largely as ions; Fe, Cu, Zn, Mo work in redox enzymes.'],
  ['Potassium\'s main roles include:', ['Enzyme activation and osmotic regulation of stomata', 'Forming proteins', 'Being part of chlorophyll', 'Forming cell walls'], 0,
    'Nitrogen is in proteins, nucleic acids and chlorophyll.'],
  ['Deficiency symptoms appear first on older leaves for:', ['Mobile nutrients such as N, P, K and Mg', 'Immobile nutrients such as Ca, B and Fe', 'All nutrients equally', 'Only micronutrients'], 0,
    'Immobile nutrients show symptoms on young leaves.'],
  ['Nitrogen deficiency differs from sulphur deficiency in that N deficiency:', ['Yellows older leaves first, while S deficiency yellows younger leaves', 'Yellows young leaves only', 'Causes purple stems only', 'Has no symptoms'], 0,
    'S is less mobile in the plant.'],
  ['Plant tissue analysis diagnoses nutrient status by comparing with:', ['Critical concentrations or sufficiency ranges', 'Soil colour', 'Leaf size alone', 'Rainfall'], 0,
    'DRIS uses nutrient ratios.'],
  ['Symbiotic nitrogen fixation differs from asymbiotic fixation in that it:', ['Occurs in partnership with a host, as *Rhizobium* in legume nodules', 'Is done by free-living *Azotobacter*', 'Needs no nitrogenase', 'Happens only in water'], 0,
    'Both use the enzyme nitrogenase.'],
  ['In humans, iron deficiency mainly causes:', ['Anaemia', 'Goitre', 'Night blindness', 'Rickets'], 0,
    'Iodine deficiency: goitre; vitamin A: night blindness.'],
  ['Visual diagnosis of deficiencies has the limitation that:', ['Symptoms may appear only after yield loss and can be confused with other causes', 'It is always accurate', 'It needs a laboratory', 'It works before symptoms appear'], 0,
    'Hidden hunger is better detected by tissue and soil tests.']
] }
);
