/* Concept sets for Agriculture II — Genetics and cell biology: GM crops, chromosomes, linkage, cell division and basic genetic terms. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Cell Biology & Genetics', w: 3, pyq: ['IFoS-2023-A2-m15', 'CSE-2020-A2-m04', 'CSE-2019-A2-m05', 'CSE-2015-A2-m03', 'CSE-2013-A2-m04', 'CSE-2011-A2-m02', 'CSE-2002-A2-m05', 'CSE-2014-A2-m08', 'IFoS-2013-A2-m12', 'IFoS-2019-A2-m06', 'IFoS-2012-A2-m10', 'CSE-2005-A2-m03', 'CSE-2009-A2-m23', 'IFoS-2001-A2-m17', 'CSE-1999-A2-m09', 'CSE-2003-A2-m11', 'CSE-2002-A2-m01', 'IFoS-2013-A2-m25'], q: [
  ['A genetically modified (transgenic) crop is one that:', ['Carries a gene introduced by genetic engineering, often from another species', 'Was bred by mass selection', 'Is a natural mutant', 'Is grown organically'], 0,
    'Bt cotton carries *cry* genes from *Bacillus thuringiensis*.'],
  ['*Agrobacterium*-mediated gene transfer works because the bacterium:', ['Transfers T-DNA from its Ti plasmid into the plant genome', 'Injects proteins only', 'Fuses with plant cells', 'Shoots DNA-coated particles'], 0,
    'Disarmed Ti plasmids carry the desired genes and selectable markers.'],
  ['A direct method of gene transfer is:', ['Particle bombardment (gene gun)', '*Agrobacterium* infection', 'Viral vectors', 'Conjugation'], 0,
    'Electroporation and PEG-mediated protoplast uptake are other direct methods.'],
  ['Particle bombardment is especially useful for:', ['Cereals and other plants that respond poorly to *Agrobacterium*', 'Only dicots', 'Only animals', 'Only bacteria'], 0,
    'Gold or tungsten particles coated with DNA are fired into cells.'],
  ['A biosafety concern with GM crops is:', ['Gene flow to wild relatives and evolution of resistant pests', 'Higher yields', 'Lower pesticide use', 'Better nutrition'], 0,
    'Allergenicity and effects on non-target organisms are also assessed.'],
  ['In India, environmental release of GM crops is approved by:', ['The Genetic Engineering Appraisal Committee (GEAC)', 'FSSAI', 'NBPGR', 'The Seed Corporation'], 0,
    'Bt cotton (2002) is the only GM crop grown widely.'],
  ['A benefit of Bt cotton is:', ['Reduced bollworm damage and insecticide use', 'Resistance to all pests', 'Drought immunity', 'Higher fibre length always'], 0,
    'Pink bollworm has since developed resistance in many areas.'],
  ['Gene cloning involves:', ['Inserting a DNA fragment into a vector and multiplying it in a host', 'Cutting plants into pieces', 'Grafting', 'Selfing'], 0,
    'Restriction enzymes and ligase are the basic tools.'],
  ['Biotechnology aids plant breeding through:', ['Tissue culture, molecular markers, transgenics and genome editing', 'Only irrigation', 'Only fertiliser', 'Only mechanisation'], 0,
    'It speeds and widens the breeder\'s options.'],
  ['Selectable marker genes in transformation, such as *nptII*, are used to:', ['Identify transformed cells, e.g. by kanamycin resistance', 'Increase yield', 'Kill the plant', 'Cause sterility'], 0,
    'Marker-free methods are now preferred for release.']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 3, pyq: ['CSE-2020-A2-m01', 'IFoS-2019-A2-m05', 'IFoS-2015-A2-m12', 'CSE-2006-A2-m01', 'CSE-2005-A2-m05', 'CSE-2024-A2-m04', 'CSE-2020-A2-m02', 'CSE-2018-A2-m01', 'IFoS-2004-A2-m12', 'IFoS-2023-A2-m13', 'IFoS-2020-A2-m15', 'IFoS-2019-A2-m03', 'CSE-2022-A2-m03', 'CSE-2012-A2-m02', 'CSE-2010-A2-m15', 'IFoS-2010-A2-m18', 'CSE-2000-A2-m01'], q: [
  ['By centromere position, a chromosome with the centromere in the middle is:', ['Metacentric', 'Acrocentric', 'Telocentric', 'Submetacentric'], 0,
    'Submetacentric is off-centre; acrocentric near one end; telocentric at the end.'],
  ['Heterochromatin differs from euchromatin in being:', ['Densely packed and largely inactive in transcription', 'Loosely packed and active', 'Absent in plants', 'Made of RNA'], 0,
    'Constitutive heterochromatin is common at centromeres and telomeres.'],
  ['Lampbrush chromosomes are found in:', ['Oocytes at the diplotene stage', 'Salivary glands of *Drosophila*', 'Root tips', 'Pollen grains'], 0,
    'Polytene chromosomes occur in dipteran salivary glands.'],
  ['B chromosomes are:', ['Supernumerary, non-essential chromosomes found in some individuals', 'Sex chromosomes', 'Normal autosomes', 'Mitochondrial DNA'], 0,
    'They are common in maize and rye.'],
  ['A deletion is:', ['Loss of a chromosome segment', 'Duplication of a segment', 'Reversal of a segment', 'Exchange between non-homologues'], 0,
    'Duplications add segments; inversions reverse them; translocations exchange them.'],
  ['A paracentric inversion:', ['Does not include the centromere', 'Includes the centromere', 'Is an exchange between non-homologues', 'Is a loss of segment'], 0,
    'Crossing over within it gives dicentric bridges and acentric fragments at anaphase I.'],
  ['Reciprocal translocation heterozygotes typically show:', ['A cross-shaped pairing at pachytene and ring or chain quadrivalents', 'Normal bivalents only', 'Univalents only', 'No pairing'], 0,
    'They show about 50% pollen sterility.'],
  ['Aneuploidy is:', ['Gain or loss of one or a few chromosomes (e.g. 2n−1, 2n+1)', 'Doubling of whole sets', 'A single extra set', 'Haploidy'], 0,
    'Euploidy involves whole sets (haploid, triploid, tetraploid).'],
  ['A monosomic and a trisomic are written as:', ['2n − 1 and 2n + 1', '2n + 1 and 2n − 1', 'n and 3n', '4n and 2n'], 0,
    'Nullisomics are 2n − 2.'],
  ['The nucleosome model of chromatin was proposed by:', ['Kornberg (1974)', 'Watson and Crick', 'Morgan', 'McClintock'], 0,
    'About 146 bp of DNA wraps around a histone octamer.']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: ['IFoS-2023-A2-m12', 'IFoS-2021-A2-m08', 'CSE-2010-A2-m01', 'CSE-2000-A2-m08', 'CSE-1994-A2-m04', 'CSE-1994-A2-m05', 'CSE-2015-A2-m02', 'CSE-1994-A2-m08', 'IFoS-2001-A2-m04', 'CSE-1997-A2-m05', 'IFoS-2011-A2-m09', 'IFoS-2024-A2-m05'], q: [
  ['Linkage is:', ['The tendency of genes on the same chromosome to be inherited together', 'Independent assortment', 'Exchange of segments between homologues', 'Loss of a chromosome'], 0,
    'Crossing over breaks linkage and creates recombinants.'],
  ['Crossing over occurs at:', ['Pachytene of prophase I, between non-sister chromatids', 'Anaphase II', 'Mitotic metaphase', 'Interphase'], 0,
    'Chiasmata seen at diplotene are its visible result.'],
  ['Linkage is detected from a test-cross when:', ['Parental classes greatly exceed recombinant classes', 'All four classes are equal', 'Only recombinants appear', 'There is no progeny'], 0,
    'Independent assortment gives 1:1:1:1.'],
  ['Recombination frequency of 10% between two genes corresponds to a map distance of:', ['10 centimorgans', '1 centimorgan', '100 centimorgans', '0.1 centimorgans'], 0,
    'One map unit = 1% recombination.'],
  ['Coupling and repulsion phases refer to:', ['Whether dominant alleles of two linked genes are on the same or on different homologues', 'Types of mutation', 'Sex chromosomes', 'Types of polyploidy'], 0,
    'Bateson and Punnett first described them in sweet pea.'],
  ['Transposable elements were discovered in maize by:', ['Barbara McClintock', 'T. H. Morgan', 'Watson', 'Mendel'], 0,
    'She studied *Ac*–*Ds* elements causing kernel colour spots.'],
  ['IS (insertion sequence) elements differ from Tn (transposon) elements in that IS elements:', ['Carry only genes for their own transposition', 'Carry antibiotic resistance genes', 'Are RNA', 'Cannot move'], 0,
    'Composite transposons have IS elements flanking other genes.'],
  ['Transposons contribute to genetic variation by:', ['Inserting into genes and promoting rearrangements', 'Preventing mutation', 'Stopping recombination', 'Fixing nitrogen'], 0,
    'They are major components of plant genomes.'],
  ['Ribozymes are:', ['RNA molecules with catalytic activity', 'Protein enzymes on ribosomes', 'DNA enzymes', 'Lipids'], 0,
    'Their discovery supported the RNA world hypothesis.'],
  ['Morgan\'s work on *Drosophila* showed that:', ['Genes are arranged linearly on chromosomes and can be mapped by recombination', 'Genes are in the cytoplasm', 'DNA is a protein', 'All genes assort independently'], 0,
    'Sturtevant made the first linkage map in 1913.']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 2, pyq: ['CSE-2005-A2-m13', 'CSE-1998-A2-m11', 'CSE-2012-A2-m18', 'IFoS-2003-A2-m26', 'IFoS-2023-A2-m25', 'CSE-2023-A2-m16', 'CSE-2024-A2-m16', 'CSE-1999-A2-m18', 'CSE-1996-A2-m17', 'CSE-2019-A2-m21', 'CSE-2011-A2-m21', 'IFoS-2005-A2-m22', 'CSE-2005-A2-m12', 'CSE-1999-A2-m17', 'CSE-1998-A2-m12', 'IFoS-2022-A2-m03'], q: [
  ['Mitosis differs from meiosis in that mitosis:', ['Produces two genetically identical diploid cells', 'Halves the chromosome number', 'Involves crossing over', 'Produces four gametes'], 0,
    'Meiosis gives four haploid cells and generates variation.'],
  ['The stages of interphase in order are:', ['G₁ → S → G₂', 'S → G₁ → G₂', 'G₂ → S → G₁', 'M → G₁ → S'], 0,
    'DNA is replicated in S phase.'],
  ['The fluid mosaic model of the plasma membrane was given by:', ['Singer and Nicolson (1972)', 'Robertson (1959)', 'Danielli and Davson (1935)', 'Hooke (1665)'], 0,
    'Proteins float in a fluid lipid bilayer.'],
  ['Prokaryotic cells differ from eukaryotic cells in lacking:', ['A membrane-bound nucleus and organelles', 'Ribosomes', 'DNA', 'A plasma membrane'], 0,
    'They have 70S ribosomes; eukaryotes have 80S in the cytoplasm.'],
  ['The "powerhouse of the cell" is the:', ['Mitochondrion', 'Chloroplast', 'Golgi body', 'Nucleus'], 0,
    'It makes ATP by oxidative phosphorylation.'],
  ['Thylakoids stacked into grana are found in:', ['Chloroplasts', 'Mitochondria', 'Nucleus', 'Vacuole'], 0,
    'Light reactions occur on thylakoid membranes.'],
  ['Plant cells differ from animal cells in having:', ['Cell wall, plastids and a large central vacuole', 'Centrioles', 'Lysosomes only', 'No mitochondria'], 0,
    'Animal cells have centrioles and lack walls.'],
  ['Ribosomes are the site of:', ['Protein synthesis', 'Lipid storage', 'Photosynthesis', 'DNA replication'], 0,
    'Rough ER is studded with ribosomes.'],
  ['DNA differs from RNA in containing:', ['Deoxyribose and thymine, usually as a double helix', 'Ribose and uracil', 'Only one strand always', 'No phosphate'], 0,
    'RNA is usually single-stranded.'],
  ['Cytokinesis in plant cells occurs by:', ['Formation of a cell plate from the phragmoplast', 'Furrowing of the membrane', 'Budding', 'Fusion'], 0,
    'Animal cells divide by a cleavage furrow.']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 1, pyq: ['CSE-2005-A2-m14', 'CSE-1991-A2-m23', 'CSE-2005-A2-m15', 'CSE-1991-A2-m24', 'CSE-1992-A2-m29', 'CSE-1992-A2-m31', 'CSE-1994-A2-m11', 'CSE-1994-A2-m10', 'CSE-1994-A2-m09', 'IFoS-2010-A2-m10', 'CSE-1994-A2-m06', 'CSE-1996-A2-m09'], q: [
  ['Genotype differs from phenotype in that genotype is:', ['The genetic make-up, while phenotype is the observable expression', 'The observable trait', 'The environment', 'The same thing'], 0,
    'Phenotype = genotype + environment + interaction.'],
  ['A homozygous individual has:', ['Identical alleles at a locus (AA or aa)', 'Different alleles (Aa)', 'No alleles', 'Three alleles'], 0,
    'Heterozygotes (Aa) segregate on selfing.'],
  ['A maintainer line (B line) in hybrid seed production is:', ['Isogenic to the male-sterile line but with normal cytoplasm, keeping the A line sterile when crossed', 'A restorer of fertility', 'A wild relative', 'A hybrid'], 0,
    'The restorer (R) line restores fertility in the F₁.'],
  ['A biparental cross differs from a single cross in that biparental crossing:', ['Intermates selected F₂ plants to break linkages and widen variation', 'Uses two inbreds once', 'Uses mutants', 'Is selfing'], 0,
    'It is used in self-pollinated crop breeding.'],
  ['Random genetic drift is most effective in:', ['Small populations', 'Very large populations', 'Clonal crops only', 'Polyploids only'], 0,
    'Founder effects and bottlenecks are forms of drift.'],
  ['Goldschmidt differed from Darwin in proposing that evolution can occur through:', ['"Hopeful monsters" — large macromutations', 'Gradual small variations only', 'Use and disuse', 'Special creation'], 0,
    'Darwin emphasised gradual natural selection.'],
  ['The modern definition of a gene is:', ['A DNA sequence coding for a functional product (protein or RNA)', 'A whole chromosome', 'A protein', 'A cell'], 0,
    'Benzer split the gene into cistron, recon and muton.'],
  ['To obtain a desired homozygous combination from two parents, the breeder should:', ['Cross them and select among segregating generations', 'Grow them separately', 'Mutate both', 'Graft them'], 0,
    'Homozygous recombinants appear from F₂ onward.'],
  ['In summer squash, a 12:3:1 ratio of white:yellow:green fruit shows:', ['Dominant epistasis', 'Complementary genes', 'Recessive epistasis', 'Independent assortment without interaction'], 0,
    'The dominant white allele masks the colour genes.'],
  ['Darwinism differs from modern evolutionary theory mainly in lacking:', ['Knowledge of Mendelian genetics and mutation', 'Natural selection', 'Variation', 'Struggle for existence'], 0,
    'The synthetic theory combined the two.']
] }
);
