/* Concept sets for Agriculture II — Horticulture: vegetables, banana and papaya, propagation, fruit physiology, plantation/spice/medicinal crops and fruit crops. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 2, pyq: ['IFoS-2022-A2-m10', 'IFoS-2021-A2-m11', 'IFoS-2020-A2-m17', 'CSE-2019-A2-m09', 'CSE-2019-A2-m11', 'CSE-2019-A2-m12', 'IFoS-2019-A2-m07', 'CSE-2009-A2-m14', 'CSE-2006-A2-m08', 'CSE-2004-A2-m07', 'IFoS-2003-A2-m14', 'IFoS-2003-A2-m15', 'IFoS-2003-A2-m16', 'IFoS-2003-A2-m17', 'CSE-2002-A2-m06', 'CSE-2020-A2-m08', 'CSE-2013-A2-m15', 'CSE-2005-A2-m09', 'CSE-1993-A2-m12', 'CSE-2006-A2-m05', 'CSE-2007-A2-m05', 'CSE-1990-A2-m13', 'CSE-1992-A2-m09', 'CSE-1995-A2-m07', 'IFoS-2023-A2-m20', 'IFoS-2005-A2-m11', 'CSE-2006-A2-m09'], q: [
  ['Among world vegetable producers, India ranks:', ['Second, after China', 'First', 'Tenth', 'Fifth'], 0,
    'Time-sensitive; India is also second in fruits.'],
  ['Kharif onion is important in India mainly because it:', ['Fills the supply gap in the lean season and steadies prices', 'Is the main crop by area', 'Is grown only for seed', 'Has no market'], 0,
    'Rabi onion is the main crop; Agrifound Dark Red is a kharif variety.'],
  ['Bulbing in temperate onion types is induced by:', ['Long days', 'Short days', 'Low light', 'Flooding'], 0,
    'Tropical Indian types bulb under shorter days.'],
  ['Fruit set in tomato is poor when temperatures exceed about:', ['32 °C', '15 °C', '20 °C', '10 °C'], 0,
    'The optimum is about 21–24 °C.'],
  ['Arka Rakshak, a tomato hybrid from IIHR, is notable for:', ['Resistance to leaf curl virus, bacterial wilt and early blight', 'Seedlessness', 'Purple colour', 'Long shelf life only'], 0,
    'Determinate varieties need no staking; indeterminate ones are staked.'],
  ['Cauliflower curds are kept white by:', ['Blanching — tying the inner leaves over the curd', 'Spraying ethephon', 'Full sun exposure', 'Removing leaves'], 0,
    'Snowball types are late, cool-season cauliflowers.'],
  ['"Whiptail" of cauliflower is caused by deficiency of:', ['Molybdenum', 'Boron', 'Zinc', 'Calcium'], 0,
    'Boron deficiency causes browning (hollow stem); buttoning is premature small curds.'],
  ['Truck gardening differs from market gardening in that it:', ['Grows vegetables on a larger scale for distant markets', 'Supplies only the family', 'Is done in pots', 'Grows only flowers'], 0,
    'Market gardens supply nearby city markets.'],
  ['A kitchen garden is planned so that:', ['Perennials are at one end and vegetables are sown in succession for year-round supply', 'Only one crop is grown', 'Only trees are planted', 'Plants are watered once a year'], 0,
    'It improves household nutrition.'],
  ['Garlic needs:', ['Cool weather during growth and longer days for bulb development', 'Very hot weather throughout', 'Flooded fields', 'Short days for bulbing'], 0,
    'Sweet potato, by contrast, is a warm-season crop.']
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 2, pyq: ['IFoS-2021-A2-m11', 'IFoS-2020-A2-m17', 'CSE-2024-A2-m10', 'IFoS-2021-A2-m12', 'CSE-2014-A2-m10', 'CSE-1991-A2-m08', 'CSE-2011-A2-m13', 'IFoS-2000-A2-m10', 'CSE-2000-A2-m11', 'CSE-1992-A2-m15', 'CSE-1992-A2-m14'], q: [
  ['Edible bananas originated in:', ['South-East Asia (Indo-Malaysian region)', 'Africa', 'South America', 'Europe'], 0,
    'They come from *Musa acuminata* (A) and *M. balbisiana* (B).'],
  ['Grand Naine and Robusta belong to the banana genome group:', ['AAA (Cavendish)', 'AAB', 'ABB', 'BB'], 0,
    'Poovan and Nendran are AAB; Monthan is ABB.'],
  ['Banana is best planted with:', ['Sword suckers or tissue-culture plantlets', 'Water suckers', 'Seeds', 'Leaf cuttings'], 0,
    'Sword suckers have narrow leaves and a strong corm.'],
  ['Banana bunchy top virus is spread by:', ['The banana aphid *Pentalonia nigronervosa*', 'Whiteflies', 'Mealybugs', 'Nematodes'], 0,
    'Infected plants have bunched, narrow upright leaves.'],
  ['Panama wilt of banana is caused by:', ['*Fusarium oxysporum* f. sp. *cubense*', '*Ralstonia solanacearum*', '*Mycosphaerella*', 'A virus'], 0,
    'Tropical Race 4 threatens Cavendish worldwide.'],
  ['Black sigatoka of banana is caused by:', ['*Mycosphaerella* (*Pseudocercospora*) *fijiensis*', '*Fusarium*', 'Banana bract mosaic virus', '*Erwinia*'], 0,
    'It causes leaf streaks and early leaf death.'],
  ['Bananas suffer chilling injury below about:', ['12 °C', '25 °C', '30 °C', '0 °C only'], 0,
    'They need a warm humid climate.'],
  ['Papaya plants may be:', ['Male, female or hermaphrodite', 'Only bisexual', 'Only male', 'Only female'], 0,
    'Gynodioecious varieties (e.g. Coorg Honey Dew) have female and hermaphrodite plants.'],
  ['Sex reversal (intersex) in papaya male plants is favoured by:', ['Temperature changes, especially high temperature', 'Flooding', 'Pruning', 'Darkness'], 0,
    'Male trees may bear some fruit after reversal.'],
  ['Papain is obtained from:', ['The latex of unripe papaya fruits', 'Papaya seeds', 'Ripe pulp', 'Leaves only'], 0,
    'Papaya ring spot virus is the major disease, spread by aphids.']
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 3, pyq: ['IFoS-2021-A2-m10', 'CSE-2011-A2-m08', 'CSE-2013-A2-m13', 'CSE-1995-A2-m08', 'CSE-2018-A2-m06', 'IFoS-2004-A2-m15', 'CSE-2025-A2-m07', 'CSE-2016-A2-m09', 'IFoS-2003-A2-m09', 'CSE-1998-A2-m08', 'CSE-2010-A2-m02', 'CSE-1993-A2-m11', 'CSE-2001-A2-m17', 'CSE-2011-A2-m07', 'CSE-1990-A2-m12', 'CSE-2023-A2-m13', 'CSE-1998-A2-m03'], q: [
  ['Fruit plants are usually propagated vegetatively because:', ['Seedlings are not true to type and take longer to bear', 'Seeds never germinate', 'It is cheaper always', 'Vegetative plants never get disease'], 0,
    'Rootstocks also add vigour control and soil or disease tolerance.'],
  ['Air layering (gootee) is the usual method for:', ['Litchi', 'Mango', 'Citrus', 'Apple'], 0,
    'Guava is also layered or budded.'],
  ['Mango is commercially propagated by:', ['Veneer or softwood grafting', 'Seeds only', 'Stem cuttings', 'Tissue culture only'], 0,
    'Inarching was used earlier.'],
  ['T-budding (shield budding) is common in:', ['Citrus and rose', 'Coconut', 'Banana', 'Pineapple'], 0,
    'Patch budding is used in ber and some trees with thick bark.'],
  ['Apple clonal rootstocks are raised mainly by:', ['Stooling (mound layering)', 'Seeds', 'Leaf cuttings', 'Air layering'], 0,
    'M9 is dwarfing; MM106 resists woolly apple aphid.'],
  ['Nucellar seedlings in citrus and polyembryonic mangoes are valued because they are:', ['True to type and virus-free, giving uniform rootstocks', 'Hybrids', 'Haploids', 'Always dwarf'], 0,
    'Polyembryonic mangoes include Kurukkan and Olour.'],
  ['Grapes and pomegranate are usually propagated by:', ['Hardwood stem cuttings', 'Air layering', 'Budding', 'Seeds'], 0,
    'Fig is also raised from cuttings.'],
  ['A chimera in horticulture is:', ['A plant with tissues of different genotypes, as in some variegated plants', 'A hybrid of two species', 'A virus-infected plant', 'A tetraploid'], 0,
    'Periclinal, mericlinal and sectorial chimeras occur.'],
  ['Micropropagation is widely used for:', ['Banana, strawberry and potato to give uniform, disease-free planting material', 'Wheat', 'Rice', 'Mango only'], 0,
    'Fast multiplication and year-round supply are advantages.'],
  ['Apomixis is useful in horticulture because it gives:', ['Uniform, true-to-type seedlings for rootstocks', 'More variation', 'Seedless fruits', 'Larger flowers'], 0,
    'Apomictic seed is clonal.']
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 2, pyq: ['CSE-2012-A2-m07', 'CSE-1993-A2-m10', 'IFoS-2003-A2-m12', 'CSE-2000-A2-m18', 'CSE-2019-A2-m08', 'IFoS-2003-A2-m03', 'CSE-2009-A2-m08', 'CSE-1992-A2-m13', 'IFoS-2011-A2-m21', 'CSE-2000-A2-m14', 'CSE-2025-A2-m08'], q: [
  ['Stenospermocarpy, as in Thompson Seedless grape, means:', ['Fertilisation occurs but the embryo aborts, leaving seed traces', 'Fruit forms without pollination', 'Fruit forms after pollination without fertilisation', 'Many seeds form'], 0,
    'Vegetative parthenocarpy (banana, pineapple) needs no pollination.'],
  ['Parthenocarpy can be induced in tomato and grapes by:', ['Auxins and gibberellins', 'Ethylene', 'Abscisic acid', 'Cytokinin alone'], 0,
    'GA₃ also enlarges grape berries.'],
  ['Dioecious horticultural crops include:', ['Date palm, kiwifruit and spinach', 'Cucumber and pumpkin', 'Mango and guava', 'Tomato and brinjal'], 0,
    'Cucurbits, coconut and walnut are monoecious.'],
  ['Pre-harvest fruit drop in apple and citrus is reduced by spraying:', ['NAA (an auxin)', 'Ethephon', 'Abscisic acid', 'Maleic hydrazide'], 0,
    'Ethephon instead promotes ripening and abscission.'],
  ['Flowering in pineapple can be induced by:', ['Ethephon (ethylene) or calcium carbide', 'Gibberellin', 'Auxin at high dose', 'Cytokinin'], 0,
    'Ethephon also ripens banana and mango.'],
  ['Paclobutrazol is used in mango to:', ['Promote regular flowering and check excess vegetative growth', 'Increase tree height', 'Delay flowering', 'Kill weeds'], 0,
    'It is a gibberellin-biosynthesis inhibitor (growth retardant).'],
  ['Litchi is commercially propagated by:', ['Air layering (gootee)', 'Seeds', 'Budding', 'Hardwood cuttings'], 0,
    'Fruit cracking is linked to boron/calcium shortage and moisture swings.'],
  ['The litchi mite causes:', ['Erinose — velvety brown growth on leaf undersides', 'Fruit fly damage', 'Root galls', 'Bark splitting'], 0,
    'It is *Aceria litchii*.'],
  ['Granulation in citrus fruits is:', ['Drying and hardening of juice sacs, common in large fruits from young vigorous trees', 'A fungal rot', 'An insect injury', 'Seed sprouting'], 0,
    'Late harvest increases it.'],
  ['Citrus decline is best managed by:', ['Healthy budwood on tolerant rootstocks, drainage, balanced nutrition and vector control', 'More flooding', 'Removing all leaves', 'Heavy nitrogen only'], 0,
    'Causes include *Phytophthora*, tristeza, greening and nematodes.']
] },
{ p: 'A2', t: 'Plantation, Spice & Medicinal Crops', w: 2, pyq: ['CSE-2022-A2-m10', 'CSE-2011-A2-m12', 'CSE-2006-A2-m09', 'CSE-2009-A2-m07', 'CSE-2017-A2-m09', 'CSE-2011-A2-m10'], q: [
  ['Seed spices of India include:', ['Coriander, cumin, fennel, fenugreek and ajwain', 'Pepper, cardamom and clove', 'Ginger and turmeric', 'Cinnamon and nutmeg'], 0,
    'Rajasthan and Gujarat grow most seed spices; NRC on Seed Spices is at Ajmer.'],
  ['Cashew was introduced to India by:', ['The Portuguese in the 16th century', 'The British in the 19th century', 'Arab traders in ancient times', 'The Dutch in the 20th century'], 0,
    'It was first planted along the Goa coast.'],
  ['The ICAR research centre for cashew is at:', ['Puttur (Karnataka)', 'Kasaragod', 'Calicut', 'Ooty'], 0,
    'Kasaragod hosts CPCRI (coconut, arecanut).'],
  ['Aloe vera gel is used mainly in:', ['Cosmetics and skin care, while aloin from leaf latex is a laxative', 'Rubber making', 'Fibre', 'Timber'], 0,
    'It is propagated by suckers.'],
  ['India is the leading producer of natural menthol from:', ['*Mentha arvensis* (Japanese mint)', '*Mentha piperita*', '*Ocimum*', '*Cymbopogon*'], 0,
    'Lemongrass, palmarosa and vetiver are other aromatic crops.'],
  ['The National Medicinal Plants Board promotes:', ['Conservation, cultivation and trade of medicinal plants', 'Only exports', 'Only allopathic drugs', 'Only forest timber'], 0,
    'Ashwagandha, isabgol and safed musli are major cultivated medicinals.'],
  ['Sarpagandha (*Rauvolfia serpentina*) is used for:', ['High blood pressure and insomnia, from root alkaloids such as reserpine', 'Malaria', 'Diabetes only', 'Cough'], 0,
    'Wild collection has made it threatened.'],
  ['Blister blight of tea is caused by:', ['*Exobasidium vexans*', '*Cephaleuros parasiticus*', '*Phytophthora*', '*Colletotrichum*'], 0,
    'Red rust of tea is caused by the alga *Cephaleuros*.'],
  ['Aromatic plants are distinguished from medicinal plants by:', ['Their essential oils used in perfumes, flavours and aromatherapy', 'Having no chemicals', 'Being always trees', 'Being annual weeds'], 0,
    'Many plants are both.'],
  ['India\'s cashew industry relies partly on:', ['Imported raw cashew nuts from Africa for processing', 'Only domestic nuts', 'Exports of raw nuts', 'Cashew apple only'], 0,
    'India is a top processor and exporter of kernels.']
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 2, pyq: ['CSE-2023-A2-m06', 'CSE-2007-A2-m07', 'CSE-2005-A2-m08', 'CSE-1998-A2-m09', 'CSE-1994-A2-m07', 'CSE-2026-A2-Q7b', 'CSE-2021-A2-m08', 'CSE-2019-A2-m09'], q: [
  ['Guava is valued for growing on:', ['Poor, saline or alkaline soils where many fruits fail', 'Only rich alluvium', 'Waterlogged soils', 'Peat soils'], 0,
    'Popular varieties include Allahabad Safeda and Lucknow-49.'],
  ['Crop regulation (bahar treatment) in guava aims to:', ['Shift flowering to a season giving better fruit quality and price', 'Kill the tree', 'Stop flowering', 'Increase plant height'], 0,
    'Ambe, mrig and hasth bahars are the flowering seasons.'],
  ['Guava wilt, a major disease, is associated mainly with:', ['*Fusarium* and soil problems such as high pH and poor drainage', 'A virus', 'Aphids', 'Frost'], 0,
    'Resistant rootstocks are being developed.'],
  ['Sapota (chiku) is usually grafted onto:', ['Khirni (*Manilkara hexandra*)', 'Mango', 'Guava', 'Rough lemon'], 0,
    'Kalipatti and Cricket Ball are popular varieties.'],
  ['Sapota grows best in:', ['Warm, humid coastal tropics', 'Cold hills', 'Dry deserts', 'Temperate valleys'], 0,
    'It fruits almost round the year in such climates.'],
  ['In peninsular India, grapes are pruned:', ['Twice a year — back pruning and forward (fruit) pruning', 'Once in five years', 'Never', 'Only in winter'], 0,
    'The bower (pandal) system is a common training method.'],
  ['Fruit cultivation is important for India because it:', ['Gives higher income per hectare, nutrition, exports and employment', 'Needs no labour', 'Replaces all cereals', 'Has no markets'], 0,
    'It also uses wastelands and drylands.'],
  ['Apple in India is grown mainly in:', ['Jammu & Kashmir and Himachal Pradesh', 'Kerala', 'Gujarat', 'Odisha'], 0,
    'Nashik in Maharashtra is the grape capital.'],
  ['The mango is believed to have originated in:', ['The Indo-Burma region', 'South America', 'Africa', 'Europe'], 0,
    'Tomato comes from the Andes of South America; grapes from Asia Minor.'],
  ['Domestication of the tomato occurred in:', ['Mexico and Central America, from Andean wild ancestors', 'India', 'China', 'Egypt'], 0,
    'It reached Europe in the 16th century.']
] }
);
