/* Concept sets for Agriculture II — remaining short-note PYQs: floral biology, organelles, photosynthesis types, gene concepts, tissue culture, biotechnology, agro-climate, fertilisers, sustainable farming, crop packages, farm economics, institutions and mixed revision. Time-sensitive facts are marked. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Plant Breeding Methods', w: 2, pyq: ['IFoS-2016-A2-m03', 'IFoS-2014-A2-m03', 'IFoS-2011-A2-m08', 'IFoS-2013-A2-m09', 'IFoS-2004-A2-m09', 'IFoS-2001-A2-m03', 'IFoS-2001-A2-m08', 'IFoS-2006-A2-m05', 'IFoS-2005-A2-m05', 'IFoS-2019-A2-m01', 'CSE-2007-A2-m20', 'CSE-2009-A2-m24', 'CSE-2002-A2-m19', 'IFoS-2003-A2-m10', 'CSE-2021-A2-m02'], q: [
  ['In microsporogenesis and microgametogenesis:', ['A diploid microspore mother cell undergoes meiosis to give four microspores, each forming a pollen grain whose generative cell gives two male gametes', 'Pollen forms by mitosis of the egg', 'The anther produces one large megaspore', 'Male gametes form without meiosis'], 0,
    'The pollen grain also has a vegetative (tube) cell.'],
  ['In the common (Polygonum) type of embryo sac development:', ['One of four megaspores survives and three mitoses give an 8-nucleate, 7-celled embryo sac', 'All four megaspores form embryo sacs', 'The embryo sac has two cells', 'No meiosis occurs'], 0,
    'Double fertilisation then gives a diploid zygote and a triploid endosperm nucleus.'],
  ['Vegetative (asexual) reproduction is valuable in crop production because it:', ['Gives genetically uniform progeny and fixes superior heterozygous genotypes', 'Creates new variation every generation', 'Always gives disease-free plants', 'Needs pollinators'], 0,
    'Its drawback is little new variation and carry-over of diseases such as viruses.'],
  ['Dichogamy is:', ['Maturation of anthers and stigma of a flower at different times', 'Presence of separate male and female flowers', 'Self-incompatibility', 'Seed formation without fertilisation'], 0,
    'Protandry (anthers first) occurs in maize and sunflower; protogyny (stigma first) in pearl millet.'],
  ['Dicliny means flowers are unisexual; a dioecious crop is:', ['Papaya, with male and female flowers on separate plants', 'Maize', 'Castor', 'Cucumber'], 0,
    'Maize, castor and cucurbits are monoecious (both sexes on one plant).'],
  ['Apomixis is:', ['Formation of seed without fertilisation, giving offspring identical to the mother', 'Fusion of two male gametes', 'A type of mutation', 'Hybridisation between species'], 0,
    'Adventive embryony gives polyembryony in citrus and some mangoes; apomixis could fix hybrid vigour.'],
  ['Hot-water emasculation in sorghum involves dipping panicles in water at about:', ['42–48 °C for about 10 minutes', '100 °C for 1 minute', '10 °C for an hour', '70 °C for 30 minutes'], 0,
    'Other methods include hand emasculation with forceps, suction, alcohol, male sterility and chemical gametocides.'],
  ['The breeding method chosen depends on the mode of reproduction because:', ['Self-pollinated crops suit pure-line, pedigree and bulk methods, cross-pollinated crops suit population improvement and hybrids, and clonal crops suit clonal selection', 'All crops use the same method', 'Only seed size matters', 'Mode of reproduction never affects breeding'], 0,
    'Genetic structure — homozygous lines versus heterozygous populations — differs with pollination.'],
  ['Endospermic (albuminous) seeds are those that:', ['Keep endosperm as the food store at maturity, as in cereals, castor and coconut', 'Store food only in cotyledons, as in pea and gram', 'Have no embryo', 'Are always recalcitrant'], 0,
    'Seed development passes through histodifferentiation, reserve deposition and maturation drying.'],
  ['Breeding of fruit crops is slow mainly because of:', ['Long juvenile periods, high heterozygosity, large plant size and polyembryony or incompatibility', 'Very short life cycles', 'Lack of any variation', 'Their being annuals'], 0,
    'Hybrids such as Amrapali and Mallika mango were bred at IARI.']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 1, pyq: ['IFoS-2024-A2-m02', 'CSE-2023-A2-m01', 'IFoS-2015-A2-m01', 'CSE-2004-A2-m01'], q: [
  ['The Golgi apparatus is named after:', ['Camillo Golgi; in plant cells its separate stacks are called dictyosomes', 'Robert Hooke', 'Gregor Mendel', 'Robert Brown'], 0,
    'Golgi described it in 1898.'],
  ['In plant cells the Golgi apparatus:', ['Modifies and packages proteins and makes cell-wall polysaccharides such as pectin and hemicellulose', 'Carries out photosynthesis', 'Stores starch', 'Makes ATP by respiration'], 0,
    'Golgi vesicles also help build the cell plate at cytokinesis.'],
  ['Rough endoplasmic reticulum differs from smooth ER in that rough ER:', ['Carries ribosomes and makes proteins for secretion and membranes', 'Makes lipids only', 'Has no membranes', 'Is found only in bacteria'], 0,
    'Smooth ER makes lipids and helps in detoxification.'],
  ['The secretory pathway moves proteins in the order:', ['ER → Golgi (cis to trans) → vesicles → plasma membrane or vacuole', 'Nucleus → chloroplast → ER', 'Vacuole → ER → nucleus', 'Mitochondria → Golgi → nucleus'], 0,
    'Release at the plasma membrane is exocytosis.'],
  ['Endocytosis is:', ['Uptake of material by infolding of the plasma membrane into vesicles, often clathrin-coated', 'Release of proteins outside the cell', 'Division of the nucleus', 'Breakdown of starch'], 0,
    'Phagocytosis takes in particles; pinocytosis takes in fluid.'],
  ['Leucoplasts are colourless plastids that store food; amyloplasts store:', ['Starch', 'Oil', 'Protein', 'Chlorophyll'], 0,
    'Elaioplasts store oils and aleuroplasts store proteins.'],
  ['Chromoplasts give the colours of tomato fruit, carrot root and many flowers because they contain:', ['Carotenoids', 'Chlorophyll only', 'Anthocyanins in the plastid', 'Starch'], 0,
    'Anthocyanins are in the vacuole, not in plastids.'],
  ['All plastids develop from:', ['Proplastids', 'Mitochondria', 'Golgi vesicles', 'Ribosomes'], 0,
    'Dark-grown seedlings have etioplasts, which turn into chloroplasts in light.'],
  ['In plant cells the role of lysosomes is largely performed by the:', ['Lytic vacuole', 'Chloroplast', 'Nucleolus', 'Cell wall'], 0,
    'The vacuole contains hydrolytic enzymes.'],
  ['Glyoxysomes in germinating oilseeds:', ['Convert stored fats into sugars through the glyoxylate cycle', 'Make chlorophyll', 'Store starch', 'Carry out photorespiration'], 0,
    'Leaf peroxisomes take part in photorespiration.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: ['IFoS-2023-A2-m04', 'IFoS-2013-A2-m06', 'IFoS-2000-A2-m04', 'IFoS-2016-A2-m04', 'IFoS-2011-A2-m07', 'CSE-1999-A2-m02', 'CSE-1990-A2-m03', 'IFoS-2012-A2-m06'], q: [
  ['In CAM (crassulacean acid metabolism) plants:', ['Stomata open at night, CO₂ is fixed into malic acid and stored in the vacuole, then released to the Calvin cycle by day', 'Stomata open only by day', 'There is no Calvin cycle', 'CO₂ is fixed only by RuBisCO at night'], 0,
    'The name comes from the family Crassulaceae.'],
  ['CAM plants suit arid habitats because they:', ['Have very high water-use efficiency, keeping stomata shut in the hot day', 'Transpire more than C₃ plants', 'Need waterlogged soil', 'Grow fastest of all plants'], 0,
    'Examples: pineapple, *Agave*, *Opuntia*, *Kalanchoe*.'],
  ['In C₄ plants the first stable product of CO₂ fixation is:', ['Oxaloacetate, a 4-carbon acid formed by PEP carboxylase in mesophyll cells', '3-phosphoglycerate', 'Malic acid in the vacuole at night', 'Glucose'], 0,
    'This Hatch–Slack pathway concentrates CO₂ in bundle-sheath cells.'],
  ['C₃ plants differ from C₄ plants in that C₃ plants:', ['Fix CO₂ directly by RuBisCO into 3-PGA and lose more carbon by photorespiration', 'Have Kranz anatomy', 'Have a lower CO₂ compensation point', 'Use PEP carboxylase first'], 0,
    'Wheat, rice and pulses are C₃.'],
  ['A group of C₄ crops is:', ['Maize, sorghum, sugarcane and pearl millet', 'Wheat, rice and barley', 'Pea, gram and soybean', 'Potato, tomato and brinjal'], 0,
    '*Amaranthus* is also C₄.'],
  ['Kranz anatomy is:', ['A wreath of bundle-sheath cells with large chloroplasts around leaf veins, typical of C₄ plants', 'Thick cuticle in CAM plants', 'Stomata on both leaf surfaces', 'Air spaces in rice roots'], 0,
    'RuBisCO is confined to the bundle sheath.'],
  ['The idea of two photosystems came from:', ['The red drop and the Emerson enhancement effect', 'Mendel\'s experiments', 'The Pasteur effect', 'Blackman\'s law'], 0,
    'Far-red light alone is inefficient; adding red light boosts the rate more than the sum of both.'],
  ['The reaction centre of photosystem II is:', ['P680, which splits water and releases oxygen', 'P700, which reduces NADP⁺', 'Cytochrome c oxidase', 'RuBisCO'], 0,
    'Photosystem I has P700.'],
  ['Photophosphorylation differs from oxidative phosphorylation in that it:', ['Uses light energy in thylakoids, while oxidative phosphorylation uses energy from oxidising NADH in mitochondria', 'Occurs in the cytoplasm', 'Needs no electron transport', 'Makes no ATP'], 0,
    'Both work by chemiosmosis (Peter Mitchell).'],
  ['Compared with C₃ crops, C₄ crops have:', ['Higher water-use efficiency and higher temperature optima for photosynthesis', 'Higher photorespiration', 'Lower yields always', 'No Calvin cycle'], 0,
    'Rising CO₂ benefits C₃ crops more than C₄ crops.']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 1, pyq: ['IFoS-2011-A2-m04', 'IFoS-2014-A2-m04', 'IFoS-2011-A2-m03', 'IFoS-2023-A2-m02', 'IFoS-2013-A2-m08', 'CSE-1990-A2-m02'], q: [
  ['In a complementation (cis–trans) test, if two recessive mutants are crossed and the F₁ is normal:', ['The mutations are in different genes', 'The mutations are in the same gene', 'Both are dominant', 'The F₁ is always mutant'], 0,
    'Seymour Benzer used this test to define the cistron.'],
  ['The modern concept of the gene, following Benzer, divides it into:', ['Cistron (unit of function), muton (unit of mutation) and recon (unit of recombination)', 'Chromosome, chromatid and centromere', 'Exon only', 'Allele and locus only'], 0,
    'The classical concept saw the gene as an indivisible bead on a string.'],
  ['The one gene–one enzyme hypothesis was proposed by:', ['Beadle and Tatum, working with *Neurospora*', 'Watson and Crick', 'Mendel', 'Morgan'], 0,
    'It was later refined to one gene–one polypeptide.'],
  ['Modifying genes (modifiers) are genes that:', ['Alter the expression of another gene without a clear effect of their own, blurring Mendelian ratios', 'Are always lethal', 'Lie only in mitochondria', 'Are never inherited'], 0,
    'They are a reason for variable expression of major genes.'],
  ['Penetrance is:', ['The percentage of individuals with a genotype that show the expected phenotype', 'The degree to which a trait is expressed', 'The number of alleles at a locus', 'The rate of mutation'], 0,
    'Expressivity is the degree or intensity of expression in those that show it.'],
  ['Polygenic traits differ from monogenic traits in that polygenic traits:', ['Show continuous variation from many genes with small effects, strongly influenced by environment', 'Show clear-cut classes', 'Are controlled by one gene', 'Are never affected by environment'], 0,
    'Yield and plant height are typical polygenic traits.'],
  ['Multiple alleles means:', ['More than two alternative forms of a gene in a population, such as the S alleles of self-incompatibility', 'Two genes on one chromosome', 'Many genes affecting one trait', 'Several chromosomes in one cell'], 0,
    'A diploid individual still carries only two of them.'],
  ['Split genes, made of exons and introns, were discovered by:', ['Sharp and Roberts (1977)', 'Mendel (1866)', 'Beadle and Tatum (1941)', 'Avery (1944)'], 0,
    'Introns are removed by RNA splicing.'],
  ['Pleiotropy is:', ['One gene affecting several apparently unrelated traits', 'Several genes affecting one trait', 'Linkage of two genes', 'Loss of a chromosome'], 0,
    'It can cause undesirable side effects when selecting for one trait.'],
  ['In fungi, dikaryotisation differs from diploidisation in that dikaryotisation is:', ['Fusion of compatible hyphae or cells without nuclear fusion, giving paired (n + n) nuclei', 'Fusion of two nuclei into one diploid nucleus', 'Meiosis', 'Spore germination'], 0,
    'Diploidisation (karyogamy) follows later, before meiosis.']
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 2, pyq: ['IFoS-2013-A2-m04', 'IFoS-2000-A2-m06', 'IFoS-2016-A2-m02', 'IFoS-2015-A2-m04', 'IFoS-2015-A2-m02', 'CSE-1996-A2-m01', 'IFoS-2003-A2-m02', 'IFoS-2021-A2-m09', 'CSE-2014-A2-m07', 'CSE-2011-A2-m06'], q: [
  ['Totipotency is:', ['The ability of a single plant cell to regenerate a whole plant', 'The ability to resist all diseases', 'The capacity to fix nitrogen', 'Cell death in culture'], 0,
    'Haberlandt proposed it (1902); F. C. Steward regenerated carrot plants from single cells (1958).'],
  ['The usual stages of micropropagation are:', ['Establishment, multiplication, rooting and hardening (acclimatisation)', 'Sowing, weeding and harvest', 'Budding, grafting and layering', 'Pollination, fertilisation and seed set'], 0,
    'A stage 0 prepares healthy mother plants.'],
  ['The most widely used plant tissue culture medium is:', ['Murashige and Skoog (MS) medium, 1962', 'Nutrient agar', 'Hoagland\'s solution only', 'Potato dextrose agar'], 0,
    'Media contain salts, sugar, vitamins and growth regulators.'],
  ['Skoog and Miller showed that in culture a high cytokinin-to-auxin ratio gives:', ['Shoots', 'Roots', 'Only callus', 'Flowers'], 0,
    'A high auxin-to-cytokinin ratio favours roots; balanced levels give callus.'],
  ['Meristem culture gives virus-free plants because the apical dome:', ['Has no vascular connection and divides fast, so virus is scarce there', 'Is resistant to all viruses', 'Is treated with antibiotics', 'Has no cells'], 0,
    'It is often combined with heat therapy; used in potato, banana, sugarcane and orchids.'],
  ['Somaclonal variation is:', ['Genetic variation among plants regenerated from tissue culture', 'Variation among clones in the field', 'Variation due to cross-pollination', 'A fungal disease'], 0,
    'Larkin and Scowcroft coined the term (1981).'],
  ['Anther culture is used in breeding to:', ['Produce haploids that are doubled to give homozygous lines in one generation', 'Make polyploids', 'Produce hybrids', 'Remove viruses'], 0,
    'Guha and Maheshwari first produced haploids from *Datura* anthers (1964).'],
  ['Embryo rescue is used to:', ['Grow embryos from wide crosses that would abort because the endosperm fails', 'Save seeds from pests', 'Store seeds', 'Increase seed size'], 0,
    'It helps interspecific hybridisation and breeding of early-ripening fruits.'],
  ['India certifies tissue-culture-raised planting material under the:', ['National Certification System for Tissue Culture Raised Plants (NCS-TCP)', 'PPV&FR Act', 'Insecticides Act', 'Biological Diversity Act'], 0,
    'It is run by the Department of Biotechnology under the Seeds Act framework.'],
  ['Somatic embryogenesis differs from organogenesis in that it:', ['Forms bipolar embryo-like structures with both shoot and root poles from somatic cells', 'Forms only shoots', 'Forms only roots', 'Needs fertilisation'], 0,
    'Somatic embryos can be encapsulated to make synthetic seeds.']
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 2, pyq: ['CSE-2024-A2-m01', 'IFoS-2024-A2-m01', 'IFoS-2006-A2-m04', 'IFoS-2014-A2-m01', 'CSE-2007-A2-m01', 'CSE-1989-A2-m06', 'IFoS-2005-A2-m09', 'CSE-2001-A2-m06', 'IFoS-2009-A2-m03'], q: [
  ['Plant biotechnology in crop improvement includes:', ['Tissue culture, genetic engineering, molecular markers, genomics and genome editing', 'Only conventional crossing', 'Only fertiliser use', 'Only irrigation'], 0,
    'It speeds breeding and allows traits from unrelated species.'],
  ['CRISPR–Cas9 genome editing works by:', ['A guide RNA directing the Cas9 nuclease to cut DNA at a chosen site', 'Inserting whole chromosomes', 'Using X-rays at random', 'Crossing two species'], 0,
    'Charpentier and Doudna won the 2020 Nobel Prize in Chemistry for it.'],
  ['India\'s first genome-edited rice varieties, released in 2025, are:', ['DRR Dhan 100 (Kamala) and Pusa DST Rice 1', 'IR8 and Jaya', 'Swarna and Sub1', 'Pusa Basmati 1 and 1121'], 0,
    'Time-sensitive. SDN-1 and SDN-2 edited plants without foreign DNA were exempted from GM rules in 2022.'],
  ['Swarna-Sub1 rice was developed by marker-assisted backcrossing to add:', ['Tolerance to submergence (the SUB1 gene)', 'Bt insect resistance', 'Herbicide tolerance', 'Golden colour'], 0,
    'Marker-assisted backcrossing moves one gene quickly while recovering the parent variety.'],
  ['Golden Rice is engineered to produce:', ['Provitamin A (β-carotene) in the grain', 'Bt toxin', 'More protein', 'Herbicide tolerance'], 0,
    'It uses phytoene synthase and a bacterial carotene desaturase gene.'],
  ['A merit of transgenic crops is that they:', ['Can carry useful genes from unrelated species, such as Bt genes from bacteria', 'Need no regulation', 'Cannot affect the environment', 'Always cost less to develop'], 0,
    'Concerns include biosafety, gene flow, pest resistance and public acceptance.'],
  ['The first commercial GM food, the Flavr Savr tomato (1994), had:', ['An antisense polygalacturonase gene to delay softening', 'A Bt gene', 'A virus coat protein', 'A herbicide tolerance gene'], 0,
    'It was a landmark in genetic engineering of fruit quality.'],
  ['A biotechnological success in fruit crops is:', ['Papaya resistant to papaya ringspot virus, grown in Hawaii', 'Bt mango in India', 'GM banana in every country', 'Seedless guava by grafting'], 0,
    'Micropropagation of banana is another major use.'],
  ['Genomic selection in breeding means:', ['Predicting breeding values from genome-wide DNA markers to select plants early', 'Selecting by visual appearance only', 'Selecting only mutants', 'Crossing two species'], 0,
    'Speed breeding and doubled haploids also shorten breeding cycles.'],
  ['A major application of biotechnology to raise yields under stress is:', ['Developing drought-, flood- and salt-tolerant varieties through markers, transgenes or editing', 'Increasing pesticide use', 'Removing all fertilisers', 'Planting only old varieties'], 0,
    'Biotechnology complements, not replaces, conventional breeding.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: ['IFoS-2003-A2-m01', 'IFoS-2004-A2-m02', 'IFoS-2004-A2-m01', 'CSE-1995-A2-m01', 'IFoS-2005-A2-m01', 'CSE-1996-A2-m11', 'CSE-1996-A2-m23', 'IFoS-2001-A2-m33', 'CSE-1996-A2-m03'], q: [
  ['A typical high-temperature injury in field crops is:', ['Spikelet sterility in rice and forced maturity in wheat from heat at flowering and grain filling', 'Frost cracking of bark', 'Chilling injury of bananas', 'Waterlogging of roots'], 0,
    'Frost is countered by light irrigation, smoking, windbreaks and covers.'],
  ['Climatic factors that most influence crop production are:', ['Temperature, rainfall, light (including day length), humidity and wind', 'Soil colour only', 'Market price', 'Altitude only'], 0,
    'Day length controls flowering in short-day and long-day crops.'],
  ['Crop damage from weather hazards is reduced by:', ['Contingency crop plans, weather-based agro-advisories and crop insurance (PMFBY)', 'Ignoring forecasts', 'Single cropping of one variety', 'Removing windbreaks'], 0,
    'IMD issues district agro-advisories under Gramin Krishi Mausam Seva.'],
  ['India has been divided into agro-ecological regions by:', ['ICAR–NBSS&LUP, into 20 regions', 'The Planning Commission, into 5 regions', 'IMD, into 50 regions', 'FAO, into 2 regions'], 0,
    'The Planning Commission (1989) separately made 15 agro-climatic regions.'],
  ['The main agricultural sources of greenhouse gases are:', ['Methane from flooded rice and ruminants, and nitrous oxide from nitrogen fertilisers', 'Oxygen from photosynthesis', 'Water vapour from irrigation only', 'Nitrogen gas from legumes'], 0,
    'Global warming shortens crop duration and lowers wheat yields in India.'],
  ['ICAR\'s network project on climate-resilient farming, started in 2011, is:', ['NICRA (National Innovations in Climate Resilient Agriculture)', 'NFSM', 'RKVY', 'e-NAM'], 0,
    'It develops district contingency plans and resilient technologies.'],
  ['Remote sensing helps agriculture mainly by:', ['Estimating crop area, condition and yield before harvest, as in the FASAL programme', 'Measuring soil pH directly', 'Spraying pesticides', 'Pollinating crops'], 0,
    'Satellites also map droughts, floods and land use.'],
  ['The Normalised Difference Vegetation Index (NDVI) is calculated as:', ['(NIR − Red) / (NIR + Red)', '(Red − NIR) / Red', 'NIR × Red', 'Blue / Green'], 0,
    'Healthy plants reflect near-infrared strongly and absorb red light.'],
  ['Agro-biodiversity is conserved in situ by:', ['Farmers growing traditional varieties on their farms', 'Storing seeds at −18 °C', 'Tissue culture banks', 'Cryopreservation'], 0,
    'Ex situ conservation uses gene banks such as NBPGR, New Delhi.'],
  ['Cropping pattern is linked to soil type because:', ['Water-holding capacity, drainage and fertility decide which crops perform well', 'Soils have no effect on crops', 'All crops grow equally on all soils', 'Only rainfall matters'], 0,
    'E.g. cotton on black soils, rice on clayey soils, groundnut on light sandy loams.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 2, pyq: ['CSE-1992-A2-m43', 'CSE-1992-A2-m42', 'CSE-1992-A2-m47', 'CSE-1992-A2-m48', 'CSE-1992-A2-m17', 'CSE-1998-A2-m06', 'CSE-1998-A2-m05', 'CSE-2005-A2-m01', 'IFoS-2024-A2-m09', 'CSE-1995-A2-m02', 'IFoS-2002-A2-m07'], q: [
  ['Manures differ from fertilisers in that manures are:', ['Bulky organic materials with low nutrient content that also improve soil structure', 'Concentrated inorganic salts', 'Always synthetic', 'Free of organic matter'], 0,
    'Farmyard manure has about 0.5% N; urea has 46% N.'],
  ['Free-living or associative nitrogen-fixing biofertilisers include:', ['*Azotobacter* and *Azospirillum*', '*Rhizobium* only', '*Trichoderma*', '*Bacillus thuringiensis*'], 0,
    '*Rhizobium* is symbiotic with legumes; blue-green algae and *Azolla*–*Anabaena* fix nitrogen in rice fields.'],
  ['Biofertilisers can partly substitute nitrogen fertilisers because they:', ['Fix atmospheric nitrogen cheaply and renewably, though they rarely meet all crop needs', 'Contain 46% nitrogen', 'Act instantly like urea', 'Are inorganic'], 0,
    'Their effect depends on strain quality, soil and crop.'],
  ['Phosphate-solubilising bacteria and mycorrhizal fungi help crops by:', ['Making soil phosphorus more available and improving its uptake', 'Fixing nitrogen in leaves', 'Killing insects', 'Raising soil salinity'], 0,
    '*Bacillus*, *Pseudomonas* and VAM fungi are examples.'],
  ['The Fertiliser (Control) Order regulates:', ['Quality, standards and sale of fertilisers, under the Essential Commodities Act', 'Seed certification', 'Pesticide registration', 'Crop insurance'], 0,
    'The first order came in 1957; the current FCO dates from 1985.'],
  ['Fertiliser prices are controlled because:', ['Affordable fertilisers raise production; urea has a fixed MRP and P and K come under nutrient-based subsidy (since 2010)', 'Fertilisers are imported free', 'They have no effect on yields', 'Farmers prefer high prices'], 0,
    'Irrigation, high-yielding varieties, credit and crop–fertiliser price ratios drive fertiliser use.'],
  ['Vermicompost is made mainly using earthworms such as:', ['*Eisenia fetida*', '*Pheretima* only in soil', 'Nematodes', 'Termites'], 0,
    'It is rich in nutrients, growth substances and beneficial microbes.'],
  ['Excessive use of fertilisers can:', ['Acidify soil, cause nutrient imbalance and pollute groundwater with nitrate', 'Always raise soil organic matter', 'Prevent all deficiencies', 'Improve soil structure'], 0,
    'Integrated nutrient management balances organic and inorganic sources.'],
  ['Excessive irrigation lowers crop production by causing:', ['Waterlogging, poor aeration, nutrient leaching and salt build-up', 'Better root growth', 'Lower water table', 'More soil oxygen'], 0,
    'Drainage and scheduled irrigation prevent these.'],
  ['Soil colloids (clay and humus) are important because they:', ['Have a huge surface area and negative charges that hold exchangeable cations (CEC)', 'Are larger than sand', 'Hold no nutrients', 'Are positively charged only'], 0,
    'Colloids are smaller than about 1 µm; humus has a much higher CEC than kaolinite.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 1, pyq: ['CSE-2009-A2-m05', 'CSE-1995-A2-m04', 'CSE-2001-A2-m01', 'CSE-1992-A2-m12', 'CSE-1997-A2-m24', 'CSE-1996-A2-m24'], q: [
  ['Precision farming means:', ['Site-specific management of inputs using GPS, GIS, sensors and variable-rate technology', 'Sowing all fields on the same day', 'Using only organic inputs', 'Hand weeding only'], 0,
    'It reduces waste and environmental impact.'],
  ['Organic farming in India is certified under:', ['NPOP for exports and PGS-India for domestic markets', 'The Seeds Act', 'The Insecticides Act', 'FCO only'], 0,
    'Sikkim became India\'s first fully organic state (2016).'],
  ['Sustainable agriculture differs from high-input modern agriculture in that it:', ['Maintains productivity while conserving soil, water and biodiversity for the future', 'Maximises short-term yield at any cost', 'Rejects all technology', 'Uses only chemical inputs'], 0,
    'It balances economic, ecological and social goals.'],
  ['A hazard of continuous use of the same herbicide is:', ['Herbicide-resistant weeds, such as *Phalaris minor* resistant to isoproturon in wheat', 'Higher crop yields every year', 'Fewer weeds forever', 'Better soil structure'], 0,
    'Residues, drift and crop injury are other hazards; herbicides do save labour and allow timely weeding.'],
  ['Glyphosate controls weeds by:', ['Inhibiting the EPSPS enzyme of the shikimate pathway', 'Blocking photosystem II', 'Acting as an auxin', 'Inhibiting cell division in roots only'], 0,
    'It is non-selective and systemic; atrazine and isoproturon block photosystem II.'],
  ['The most energy-intensive input in modern crop production is usually:', ['Nitrogen fertiliser, made by the Haber–Bosch process', 'Seed', 'Farmyard manure', 'Hand labour'], 0,
    'Diesel and electricity for irrigation are other large fossil-energy inputs.'],
  ['Crops typically convert what share of incoming solar energy into biomass?', ['About 1–2%', 'About 50%', 'About 90%', 'Nothing'], 0,
    'Fixation of energy in biomass depends on leaf area, duration and photosynthetic pathway.'],
  ['Energy output per hectare is higher for crops that:', ['Produce large biomass over a long season, such as sugarcane', 'Have short duration and low biomass', 'Are grown without leaves', 'Are harvested as seedlings'], 0,
    'Energy-use efficiency compares energy output with fossil energy input.'],
  ['Biogas from cattle dung is mainly:', ['Methane (about 55–65%) with carbon dioxide', 'Pure oxygen', 'Hydrogen only', 'Nitrogen'], 0,
    'The slurry left behind is a good manure.'],
  ['Natural farming promoted by the National Mission on Natural Farming (2024) relies on:', ['On-farm inputs such as jeevamrit and beejamrit, mulching and diversity', 'High doses of urea', 'Imported pesticides', 'Monoculture'], 0,
    'Time-sensitive scheme.']
] },
{ p: 'A2', t: 'Horticulture — Fruits & Vegetables', w: 2, pyq: ['IFoS-2011-A2-m01', 'IFoS-2010-A2-m01', 'IFoS-2009-A2-m01', 'IFoS-2006-A2-m03', 'IFoS-2004-A2-m03', 'IFoS-2006-A2-m01', 'IFoS-2004-A2-m04', 'CSE-1998-A2-m01', 'IFoS-2012-A2-m02', 'IFoS-2024-A2-m08', 'IFoS-2023-A2-m09', 'IFoS-2005-A2-m17', 'IFoS-2000-A2-m21', 'CSE-2025-A2-m24', 'CSE-2023-A2-m27', 'IFoS-2012-A2-m22', 'IFoS-2011-A2-m27', 'IFoS-2004-A2-m31', 'CSE-2021-A2-m21'], q: [
  ['Timely-sown irrigated wheat in north-western India is sown in:', ['The first fortnight of November, at about 100 kg seed/ha', 'June with the monsoon', 'February', 'August'], 0,
    'The crown root initiation stage (about 21 days after sowing) is the most critical for irrigation.'],
  ['Transplanted rice usually uses:', ['20–25-day-old seedlings, 2–3 per hill at about 20 × 15 cm', '60-day-old seedlings singly', 'Direct broadcasting only', 'Seedlings 5 days old'], 0,
    'The nursery covers about one-tenth to one-twentieth of the main field.'],
  ['Kharif maize is generally sown:', ['With the onset of monsoon, at about 20 kg seed/ha and 60 × 20 cm spacing', 'In December', 'In waterlogged fields', 'As a transplanted crop'], 0,
    'Maize is very sensitive to waterlogging.'],
  ['A seed potato crop is dehaulmed (haulms cut) before harvest to:', ['Keep tubers small and free of aphid-borne viruses and to harden the skin', 'Increase tuber size', 'Make the crop flower', 'Kill weeds'], 0,
    'Seed rate is about 25–30 q tubers/ha; earthing up protects tubers.'],
  ['Tomato is raised by:', ['Sowing in a nursery and transplanting 4–5-week-old seedlings, staking tall types', 'Direct sowing of tubers', 'Stem cuttings only', 'Grafting on mango'], 0,
    'Hybrid seed rate is about 150–200 g/ha.'],
  ['Garden pea is a cool-season crop; Arkel is a well-known:', ['Early, dwarf variety', 'Late tall variety', 'Grain pea for summer', 'Fodder pea'], 0,
    'Seed rate is about 80–100 kg/ha for early types.'],
  ['Japanese mint (*Mentha arvensis*) is propagated mainly by:', ['Suckers (stolons) planted in January–February', 'True seed', 'Leaf cuttings', 'Grafting'], 0,
    'It is grown for menthol; CIMAP varieties such as Kosi are popular. India is the largest producer of mint oil.'],
  ['A major constraint to pulse production in India is that pulses are:', ['Grown largely on rainfed, marginal lands with low inputs and heavy pest losses', 'Always irrigated', 'Grown only with high fertiliser', 'Free of pests'], 0,
    'Cowpea and other pulses also suffer from lack of quality seed of improved varieties.'],
  ['Tea grows best on:', ['Acidic (pH about 4.5–5.5), well-drained hill soils with high rainfall', 'Alkaline black soils', 'Saline coastal soils', 'Waterlogged clay'], 0,
    'Cotton suits black (Vertisol) soils and cashew suits laterite and coastal sandy soils.'],
  ['Protected cultivation in polyhouses has good prospects for:', ['High-value vegetables and cut flowers off-season, despite high costs and pest build-up', 'Field cereals like wheat', 'Forest trees', 'Fodder crops'], 0,
    'Subsidies under MIDH support it.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 1, pyq: ['CSE-2010-A2-m08', 'CSE-1992-A2-m26', 'CSE-1993-A2-m21', 'CSE-1990-A2-m20', 'CSE-1989-A2-m38', 'CSE-1989-A2-m17'], q: [
  ['Cost and return analysis of an orchard uses discounted measures because:', ['Fruit trees take years before bearing, so NPV, benefit–cost ratio and IRR are needed', 'Costs and returns occur in one season', 'Fruits have no costs', 'Only yield matters'], 0,
    'Payback period is also used.'],
  ['The Kisan Credit Card scheme (1998) provides:', ['Timely, flexible short-term credit for crops, later extended to animal husbandry and fisheries', 'Free fertiliser', 'Crop insurance only', 'Land titles'], 0,
    'Time-sensitive: the interest subvention limit was raised from ₹3 lakh to ₹5 lakh in 2025.'],
  ['Under interest subvention, prompt-paying farmers get short-term crop loans at an effective rate of about:', ['4% a year', '12% a year', '0.5% a year', '20% a year'], 0,
    'Loans at 7% get a 3% prompt repayment incentive.'],
  ['India\'s multi-agency approach to rural credit involves:', ['Cooperatives, commercial banks and regional rural banks', 'Only moneylenders', 'Only foreign banks', 'Only NABARD lending directly to farmers'], 0,
    'Regional rural banks began in 1975.'],
  ['NABARD, set up in 1982, mainly:', ['Refinances and supervises rural credit institutions and funds rural infrastructure', 'Sells seeds', 'Fixes MSP', 'Runs fair price shops'], 0,
    'It manages the Rural Infrastructure Development Fund.'],
  ['Farming has not become a business in India mainly because of:', ['Small holdings, subsistence orientation, high risk and weak market links', 'Too much capital', 'Too little labour', 'Excess mechanisation'], 0,
    'Collective marketing and value addition can help.'],
  ['The scheme to form 10,000 Farmer Producer Organisations (2020) aims to:', ['Give small farmers scale in buying inputs and selling produce', 'Provide free land', 'Ban contract farming', 'End MSP'], 0,
    'FPOs are registered as companies or cooperatives.'],
  ['Panchayati Raj institutions got constitutional status, with agriculture among their listed subjects, through the:', ['73rd Constitutional Amendment Act, 1992 (Eleventh Schedule, 29 subjects)', '42nd Amendment, 1976', '1st Amendment, 1951', '86th Amendment, 2002'], 0,
    'Their problems include weak finances and limited devolution; growth in the Green Revolution years came mainly from public investment in irrigation, research and markets.'],
  ['The Agriculture Infrastructure Fund (2020) finances:', ['Post-harvest infrastructure such as warehouses, cold stores and processing units', 'Crop loans only', 'Fertiliser subsidy', 'Seed certification'], 0,
    'It offers interest subvention and credit guarantees.'],
  ['Under PMFBY, farmers pay a premium of:', ['2% for kharif, 1.5% for rabi and 5% for commercial or horticultural crops', '10% for all crops', 'Nothing at all', '25% for kharif'], 0,
    'The rest of the premium is shared by the Centre and states.']
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 1, pyq: ['IFoS-2006-A2-m12', 'IFoS-2009-A2-m04', 'IFoS-2006-A2-m10'], q: [
  ['ICAR was set up in 1929 on the recommendation of the:', ['Royal Commission on Agriculture', 'Planning Commission', 'Green Revolution committee', 'Swaminathan Commission'], 0,
    'It was first called the Imperial Council of Agricultural Research and is under DARE, Ministry of Agriculture.'],
  ['ICAR\'s main functions are to:', ['Plan, coordinate and promote agricultural research, education and frontline extension', 'Fix MSP', 'Run fair price shops', 'Issue fertiliser licences'], 0,
    'It runs All India Coordinated Research Projects and Krishi Vigyan Kendras.'],
  ['The first Krishi Vigyan Kendra was set up in 1974 at:', ['Puducherry', 'New Delhi', 'Ludhiana', 'Hyderabad'], 0,
    'Time-sensitive: there are now over 700 KVKs.'],
  ['ICRISAT, at Patancheru near Hyderabad, was founded in:', ['1972', '1929', '1990', '2005'], 0,
    'Mandate crops: sorghum, pearl millet, chickpea, pigeonpea and groundnut, plus small millets.'],
  ['The international network of agricultural research centres is:', ['CGIAR, formed in 1971', 'FAO', 'WTO', 'IFAD'], 0,
    'It includes IRRI, CIMMYT, CIP, ICRISAT, ICARDA and others.'],
  ['IRRI, the International Rice Research Institute, is located at:', ['Los Baños, Philippines', 'Hyderabad, India', 'Mexico City', 'Lima, Peru'], 0,
    'It released IR8, the "miracle rice", in 1966.'],
  ['CIMMYT, in Mexico, works on:', ['Maize and wheat', 'Rice', 'Potato', 'Sorghum'], 0,
    'Norman Borlaug\'s semi-dwarf wheats came from its programme.'],
  ['The International Potato Center (CIP) is located in:', ['Lima, Peru', 'Shimla, India', 'Ibadan, Nigeria', 'Rome, Italy'], 0,
    'It also works on sweet potato and Andean roots.'],
  ['ICARDA focuses on:', ['Agriculture in dry areas, including barley, lentil, chickpea and wheat', 'Rice in deltas', 'Tropical fruits', 'Forestry only'], 0,
    'It was originally based at Aleppo, Syria.'],
  ['IARI (the "Pusa Institute") was founded in 1905 at Pusa in Bihar and moved to New Delhi in:', ['1936', '1905', '1966', '1947'], 0,
    'It was central to India\'s Green Revolution.']
] },
{ p: 'A2', t: 'Cell Biology & Genetics', w: 1, pyq: ['IFoS-2020-A2-m04', 'IFoS-2013-A2-m10', 'IFoS-2022-A2-m02', 'IFoS-2020-A2-m07', 'IFoS-2015-A2-m08', 'CSE-1993-A2-m02', 'CSE-1990-A2-m01', 'IFoS-2023-A2-m08', 'IFoS-2000-A2-m02', 'CSE-1992-A2-m28', 'CSE-1992-A2-m40', 'CSE-1989-A2-m37', 'IFoS-2024-A2-m23', 'CSE-1990-A2-m21', 'CSE-1993-A2-m20', 'CSE-1993-A2-m15', 'CSE-1990-A2-m18', 'IFoS-2005-A2-m25'], q: [
  ['Mixed revision — an antibody differs from an antigen in that an antibody is:', ['An immunoglobulin made by the body in response to a foreign antigen', 'A foreign substance', 'A plant hormone', 'A virus'], 0,
    'ELISA uses antibodies to detect plant viruses in seed and planting material.'],
  ['Mixed revision — Quality Protein Maize owes its higher lysine and tryptophan to the:', ['*opaque-2* gene', '*Rht* gene', '*Sub1* gene', '*Bt* gene'], 0,
    'It is an example of quality improvement by breeding.'],
  ['Mixed revision — inbreeding depression is the opposite of:', ['Heterosis (hybrid vigour)', 'Mutation', 'Polyploidy', 'Apomixis'], 0,
    'It is severe in cross-pollinated crops such as maize and alfalfa.'],
  ['Mixed revision — meiosis differs from mitosis in that meiosis:', ['Halves the chromosome number and allows crossing over', 'Keeps the chromosome number the same', 'Occurs in all body cells', 'Has only one division'], 0,
    'Mitosis gives identical daughter cells for growth.'],
  ['Mixed revision — pure-line selection differs from mass selection in that pure-line selection:', ['Picks single plants and tests their progenies separately', 'Bulks seed of many plants together', 'Works only in cross-pollinated crops', 'Needs hybridisation'], 0,
    'Johannsen developed the pure-line theory with beans.'],
  ['Mixed revision — a parasitoid differs from a predator in that a parasitoid:', ['Develops on or in a single host and kills it', 'Eats many prey in its life', 'Is always a vertebrate', 'Never kills its host'], 0,
    '*Trichogramma* is a parasitoid; ladybird beetles are predators.'],
  ['Mixed revision — a systemic insecticide differs from a contact insecticide in that it:', ['Moves inside the plant and kills sucking insects that feed on sap', 'Kills only on touch', 'Never enters plants', 'Is used only in storage'], 0,
    'Contact insecticides must hit the insect or the surface it walks on.'],
  ['Mixed revision — an Integrated Farming System (IFS) combines:', ['Crops with livestock, fish, poultry or trees so that wastes of one become inputs of another', 'One crop grown every season', 'Only dairy farming', 'Only horticulture'], 0,
    'It raises income and reduces risk for small farmers.'],
  ['Mixed revision — hardening of nursery seedlings before field planting means:', ['Gradually reducing water and shade so seedlings tolerate field stress', 'Applying heavy nitrogen', 'Keeping them in deep shade', 'Cutting all roots'], 0,
    'Physiology also guides species–site matching in forestry.'],
  ['Mixed revision — a C₄ crop differs from a C₃ crop in having:', ['Kranz anatomy and very low photorespiration', 'RuBisCO as the first enzyme in mesophyll cells', 'Lower water-use efficiency', 'A lower temperature optimum'], 0,
    'Maize and sugarcane are C₄; wheat and rice are C₃.']
] },
{ p: 'A2', t: 'Floriculture & Landscaping', w: 1, pyq: ['CSE-2010-A2-m03', 'IFoS-2003-A2-m15', 'IFoS-2003-A2-m16', 'IFoS-2011-A2-m01', 'CSE-2013-A2-m11'], q: [
  ['For export-quality cut roses, the main growing structure in India is:', ['A naturally ventilated polyhouse', 'Open field in summer', 'A glass house with no ventilation', 'A shade net only'], 0,
    'Bangalore, Pune and Hosur are major export rose clusters.'],
  ['Hybrid tea roses for cut flowers are usually propagated by:', ['T-budding on rootstocks such as *Rosa indica* var. *odorata* or Natal briar', 'True seed', 'Leaf cuttings', 'Air layering only'], 0,
    'Rootstock choice affects vigour and tolerance to soil conditions.'],
  ['"Bending" in polyhouse rose cultivation means:', ['Bending blind and weak shoots down to build leaf area that feeds the flowering shoots', 'Bending flower stems to break them', 'Training on wires like grapes', 'Removing all leaves'], 0,
    'It improves stem length and yield of quality flowers.'],
  ['Roses are usually grown on:', ['Raised beds of well-drained, slightly acidic soil (pH about 6–6.5)', 'Waterlogged clay', 'Strongly alkaline soils', 'Pure sand without nutrients'], 0,
    'Drip fertigation supplies water and nutrients.'],
  ['Cut roses are harvested at the:', ['Tight bud stage, when the first petals begin to unfurl', 'Fully open stage', 'Seed stage', 'Green bud without colour'], 0,
    'Harvest early morning or evening, place stems in water and pre-cool to about 2 °C.'],
  ['A popular Indian-bred rose variety from IARI is:', ['Arjun', 'Pusa Ruby', 'Kufri Jyoti', 'Arka Vikas'], 0,
    'Pusa Ruby is a tomato, Kufri Jyoti a potato and Arka Vikas a tomato.'],
  ['Powdery mildew of rose is favoured by:', ['Dry days with cool, humid nights, and is controlled by sulphur or systemic fungicides', 'Waterlogged roots', 'High light only', 'Heavy rain every day'], 0,
    'It is caused by *Podosphaera pannosa*.'],
  ['Black spot of rose is caused by:', ['*Diplocarpon rosae*', '*Podosphaera pannosa*', '*Botrytis cinerea*', 'A virus'], 0,
    'Rain splash spreads it; remove fallen leaves.'],
  ['Pruning of roses in the north Indian plains is generally done in:', ['October', 'May', 'July', 'January only in the hills'], 0,
    'Pruning times flowering for winter, the main rose season in the plains.'],
  ['India\'s rose exports face the problem of:', ['High freight costs, quality standards and competition from Kenya, Ethiopia and Colombia', 'No foreign demand', 'Too little production area for local use', 'Ban on flower imports abroad'], 0,
    'Valentine\'s Day is the peak export window.']
] },
{ p: 'A2', t: 'Crop Physiology & Growth Regulators', w: 1, pyq: ['CSE-2016-A2-m04', 'CSE-2022-A2-m08', 'CSE-2009-A2-m03'], q: [
  ['Organic solutes are translocated in plants mainly through the:', ['Phloem sieve tubes', 'Xylem vessels', 'Cortex', 'Root hairs'], 0,
    'Sucrose is the main transported sugar.'],
  ['Münch\'s pressure-flow (mass-flow) hypothesis explains phloem transport by:', ['A turgor pressure gradient from source (loading) to sink (unloading)', 'Cytoplasmic streaming only', 'Capillarity', 'Transpiration pull'], 0,
    'Evidence includes aphid stylet exudate under pressure and ringing experiments.'],
  ['Girdling (ringing) a stem shows phloem transport because:', ['Sugars accumulate and the bark swells above the ring', 'Leaves wilt at once', 'Roots grow faster', 'Water stops moving up'], 0,
    'Xylem is left intact, so water still moves.'],
  ['Phloem loading of sucrose in many crops is:', ['Active, by a sucrose–proton symporter driven by an H⁺-ATPase', 'Passive diffusion only', 'Through xylem', 'By osmosis of water only'], 0,
    'Some plants load passively through plasmodesmata (symplastic loading).'],
  ['In leaves, sucrose is synthesised mainly in the:', ['Cytosol, from triose phosphates exported from the chloroplast', 'Chloroplast stroma', 'Vacuole', 'Mitochondria'], 0,
    'Starch is made inside the chloroplast.'],
  ['The enzymes that synthesise sucrose in leaves are:', ['Sucrose-phosphate synthase and sucrose-phosphate phosphatase', 'Invertase and amylase', 'RuBisCO and PEP carboxylase', 'Nitrate reductase'], 0,
    'Sucrose-phosphate synthase is the key regulatory step.'],
  ['In sinks, sucrose is broken down by:', ['Invertase (to glucose and fructose) or sucrose synthase (to UDP-glucose and fructose)', 'RuBisCO', 'Nitrogenase', 'Catalase'], 0,
    'Sucrose synthase supplies UDP-glucose for starch and cellulose.'],
  ['Starch is synthesised in plastids using:', ['ADP-glucose, made by ADP-glucose pyrophosphorylase', 'UDP-galactose', 'Free glucose only', 'Sucrose directly'], 0,
    'Amyloplasts store starch in cereal endosperm and potato tubers.'],
  ['During germination of cereal grains, starch is broken down by:', ['α- and β-amylases, induced by gibberellin from the embryo', 'Lipases', 'Proteases only', 'Cellulase'], 0,
    'The sugars feed the growing seedling.'],
  ['Glycolysis converts glucose to:', ['Two molecules of pyruvate with a net gain of 2 ATP and 2 NADH', 'Carbon dioxide and water directly', 'Lactose', 'Starch'], 0,
    'Pyruvate enters the Krebs cycle in mitochondria under aerobic conditions.']
] }
);
