/* Concept sets for Agriculture II — food security (PDS, NFSA, procurement, production trends, malnutrition, diets), post-harvest processing, cut-flower post-harvest life and IPR. Time-sensitive figures are marked. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Food Security & Nutrition', w: 3, pyq: ['CSE-2024-A2-m27', 'CSE-2020-A2-m26', 'CSE-2016-A2-m32', 'CSE-2015-A2-m33', 'CSE-2014-A2-m30', 'CSE-2009-A2-m27', 'CSE-2005-A2-m22', 'CSE-2016-A2-m33', 'IFoS-2021-A2-m29', 'CSE-2013-A2-m31', 'CSE-2022-A2-m25', 'IFoS-2022-A2-m05', 'IFoS-2020-A2-m05'], q: [
  ['The Targeted Public Distribution System (TPDS) was introduced in:', ['1997, separating BPL and APL households', '1965', '1980', '2013'], 0,
    'PDS began as wartime rationing in the 1940s and grew after the food shortages of the 1960s; the Revamped PDS (1992) targeted hill, tribal and drought-prone blocks.'],
  ['Antyodaya Anna Yojana (AAY), launched in 2000, provides the poorest households with:', ['35 kg of foodgrains per household per month', '5 kg per household per month', '100 kg per household per year', 'Cash only'], 0,
    'AAY households keep this entitlement under the National Food Security Act, 2013.'],
  ['Under the National Food Security Act, 2013, priority households are entitled to:', ['5 kg of foodgrains per person per month', '35 kg per person per month', '1 kg per person per month', '10 kg per household per year'], 0,
    'Time-sensitive: since January 2023 NFSA grains are free under PM Garib Kalyan Anna Yojana, extended for five years from January 2024.'],
  ['"One Nation One Ration Card" allows NFSA beneficiaries to:', ['Draw their ration from any fair price shop in the country', 'Get a second ration card', 'Buy grain in open markets at subsidised rates', 'Receive cash instead of grain'], 0,
    'It helps migrant workers; it relies on Aadhaar-seeded ration cards and ePoS machines.'],
  ['Technology has improved PDS efficiency mainly through:', ['Digitised ration cards, Aadhaar seeding, biometric ePoS authentication and online supply-chain tracking', 'Removing fair price shops', 'Paying farmers directly', 'Using only manual registers'], 0,
    'This reduces fake and duplicate cards and diversion of grain.'],
  ['A long-standing weakness of the PDS has been:', ['Leakages and diversion, and errors that exclude the needy or include the non-poor', 'Too much variety of foods', 'Excessive protein in rations', 'Lack of any central role'], 0,
    'Narrow focus on rice and wheat and poor grain quality are other criticisms.'],
  ['Responsibility for PDS is shared so that the Centre:', ['Procures, stores, transports and allocates grain, while states identify beneficiaries and run fair price shops', 'Runs all fair price shops directly', 'Has no role after procurement', 'Only fixes retail prices'], 0,
    'The Food Corporation of India handles central procurement and movement.'],
  ['A strength of India\'s PDS is that it:', ['Acts as a safety net and stabilises food prices through a large distribution network', 'Covers only urban people', 'Eliminates all malnutrition', 'Has no fiscal cost'], 0,
    'It is one of the world\'s largest food distribution systems.'],
  ['Under NFSA the ration card is issued in the name of:', ['The eldest woman of the household, aged 18 or above', 'The eldest man', 'Any child', 'The village head'], 0,
    'This provision aims at women\'s empowerment.'],
  ['Special schemes providing food to vulnerable groups include:', ['Antyodaya Anna Yojana, PM POSHAN (school meals) and ICDS supplementary nutrition', 'Only MGNREGA', 'Only crop insurance', 'Only e-NAM'], 0,
    'The Mid-Day Meal scheme was renamed PM POSHAN in 2021.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 3, pyq: ['IFoS-2025-A2-Q5e', 'CSE-2022-A2-m25', 'CSE-2020-A2-m27', 'CSE-2018-A2-m27', 'CSE-2014-A2-m31', 'IFoS-2019-A2-m22', 'CSE-2016-A2-m34', 'CSE-2024-A2-m28', 'CSE-2003-A2-m26', 'CSE-2023-A2-m28', 'CSE-2022-A2-m20', 'CSE-2017-A2-m26', 'IFoS-2016-A2-m09', 'IFoS-2005-A2-m04', 'CSE-2025-A2-m02'], q: [
  ['The 1996 World Food Summit defined food security as existing when:', ['All people, at all times, have physical and economic access to sufficient, safe and nutritious food for an active, healthy life', 'A country produces more grain than it eats', 'Food prices are low', 'Everyone grows their own food'], 0,
    'This is the FAO definition used in most answers.'],
  ['The four pillars of food security are:', ['Availability, access, utilisation and stability', 'Production, export, import and storage', 'Rice, wheat, pulses and milk', 'Land, labour, capital and credit'], 0,
    'Utilisation brings in nutrition, health and safe water.'],
  ['The NFSA, 2013 covers up to:', ['75% of the rural and 50% of the urban population', '100% of all people', '25% of the rural population', 'Only BPL households in cities'], 0,
    'This is about two-thirds of India\'s population (around 81 crore people).'],
  ['If entitled foodgrains are not supplied, the NFSA provides for:', ['A food security allowance to the beneficiary', 'No remedy', 'Double grain the next year', 'A tax rebate'], 0,
    'It also sets up State Food Commissions and District Grievance Redressal Officers.'],
  ['The National Food Security Mission (NFSM), launched in 2007–08, aimed to:', ['Raise production of rice, wheat and pulses (later coarse cereals and nutri-cereals) through area expansion and productivity gains', 'Distribute free grain', 'Build warehouses only', 'Fix MSP'], 0,
    'It focuses on districts with high potential but low yields.'],
  ['The Global Hunger Index combines:', ['Undernourishment, child stunting, child wasting and child mortality', 'GDP and inflation', 'Rainfall and yields', 'Literacy and life expectancy'], 0,
    'Time-sensitive: India has ranked low on the index in recent years.'],
  ['At the WTO, the "peace clause" agreed at Bali (2013) relates to:', ['Protecting developing countries\' public food stockholding for food security from legal challenge', 'Banning agricultural exports', 'Removing all tariffs on food', 'Ending MSP'], 0,
    'The WTO Agreement on Agriculture limits trade-distorting ("amber box") support.'],
  ['Sustainable Development Goal 2 aims to:', ['End hunger, achieve food security and improved nutrition, and promote sustainable agriculture by 2030', 'End poverty only', 'Provide clean water', 'Combat climate change'], 0,
    'SDG 1 is no poverty.'],
  ['A major constraint on food and nutrition security in India is:', ['Small farm size, rainfed farming, low crop diversity in diets, and poor sanitation that hampers food utilisation', 'Too many food processing units', 'Excess pulse production', 'Too little rice production'], 0,
    'Poverty limits economic access even when grain stocks are large.'],
  ['Programmes run for food security in India include:', ['NFSA/PDS, PM POSHAN, ICDS, NFSM and PM-KISAN income support', 'Only crop insurance', 'Only export promotion', 'Only irrigation'], 0,
    'Sustainable production also needs soil health, water efficiency and crop diversification.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 3, pyq: ['CSE-2025-A2-m27', 'IFoS-2017-A2-Q6c', 'IFoS-2016-A2-m27', 'CSE-2015-A2-m31', 'IFoS-2015-A2-m34', 'CSE-2006-A2-m26', 'IFoS-2004-A2-m30', 'CSE-2019-A2-m28', 'CSE-2015-A2-m34', 'CSE-1990-A2-m39', 'CSE-1995-A2-m31', 'CSE-2004-A2-m26', 'CSE-2020-A2-m23', 'CSE-2024-A2-m23', 'CSE-2024-A2-m02', 'IFoS-2010-A2-m06', 'IFoS-2006-A2-m13', 'CSE-1991-A2-m19'], q: [
  ['Minimum support prices (MSP) are recommended by the:', ['Commission for Agricultural Costs and Prices (CACP)', 'Food Corporation of India', 'NABARD', 'Reserve Bank of India'], 0,
    'The Cabinet Committee on Economic Affairs announces MSP for 22 mandated crops; sugarcane has a fair and remunerative price.'],
  ['Since 2018–19 the government has fixed MSP at least:', ['1.5 times the A2+FL cost of production', 'Equal to the market price', 'Twice the C2 cost', 'Half the cost of production'], 0,
    'A2 is paid-out cost; FL is the imputed value of family labour.'],
  ['Under decentralised procurement (DCP), introduced in 1997–98:', ['States procure, store and distribute grain on behalf of the Centre', 'FCI alone procures in all states', 'Private traders run the PDS', 'Farmers sell only to exporters'], 0,
    'It cuts transport costs and encourages procurement in more states.'],
  ['Buffer stocks of foodgrains are held mainly to:', ['Ensure food security, meet PDS needs and stabilise prices', 'Export at high prices', 'Feed livestock', 'Produce ethanol only'], 0,
    'Norms are set for stocks on 1 April, 1 July, 1 October and 1 January, including a strategic reserve.'],
  ['The Open Market Sale Scheme (Domestic) is used to:', ['Sell surplus FCI wheat and rice in the open market to cool prices', 'Buy grain from farmers', 'Import grain', 'Fix MSP'], 0,
    'It also reduces storage costs of excess stocks.'],
  ['A key constraint in foodgrain procurement is that it is:', ['Concentrated in a few states and in rice and wheat, leaving many farmers out', 'Spread evenly over all crops', 'Done only by private firms', 'Banned in some states'], 0,
    'Eastern states have weak procurement infrastructure.'],
  ['Grain storage institutions in India include:', ['FCI, the Central Warehousing Corporation (1957) and State Warehousing Corporations', 'NABARD only', 'ICAR only', 'Panchayats only'], 0,
    'The Warehousing (Development and Regulation) Act, 2007 set up WDRA, which promotes negotiable warehouse receipts.'],
  ['CAP storage of foodgrains means:', ['Cover-and-plinth storage: bags stacked on raised plinths and covered with polythene', 'Cold-air processing', 'Controlled-atmosphere packing', 'Storage in steel silos'], 0,
    'It is cheap but has higher losses than covered godowns or silos.'],
  ['Large foodgrain surpluses with FCI arise mainly because of:', ['Assured open-ended procurement of rice and wheat at MSP and record harvests', 'Falling production', 'Low MSP', 'Large imports'], 0,
    'Surpluses raise storage costs and wastage; diversification and exports are suggested remedies.'],
  ['A common cause of food inflation in India is:', ['Supply shocks such as monsoon failure, especially in perishables like tomato, onion and potato', 'High buffer stocks', 'Low demand', 'Falling input costs'], 0,
    'Tools used include buffer stocks, OMSS, export curbs and the Price Stabilisation Fund.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: ['IFoS-2018-A2-Q8a', 'CSE-1996-A2-m28', 'CSE-1989-A2-m46', 'CSE-1992-A2-m46', 'CSE-1990-A2-m37', 'IFoS-2016-A2-m30', 'CSE-1990-A2-m38', 'CSE-2021-A2-m27', 'CSE-1993-A2-m44', 'CSE-1995-A2-m33', 'CSE-2025-A2-m28', 'CSE-2015-A2-m32', 'CSE-1989-A2-m45', 'CSE-2001-A2-m28', 'CSE-1991-A2-m33', 'CSE-2015-A2-m27', 'IFoS-2021-A2-m23', 'IFoS-2020-A2-m06', 'IFoS-2001-A2-m10', 'CSE-1995-A2-m03', 'IFoS-2023-A2-m07', 'IFoS-2004-A2-m10', 'IFoS-2011-A2-m02', 'IFoS-2023-A2-m06', 'IFoS-2005-A2-m06', 'IFoS-2024-A2-m27', 'IFoS-2004-A2-m21', 'CSE-1996-A2-m15', 'CSE-1992-A2-m18', 'CSE-1991-A2-m18', 'CSE-1989-A2-m38', 'IFoS-2001-A2-m01', 'IFoS-2000-A2-m01', 'CSE-1993-A2-m01'], q: [
  ['India\'s foodgrain production has risen from about 50 million tonnes in 1950–51 to:', ['Over 330 million tonnes by 2023–24', 'About 100 million tonnes', 'About 1,000 million tonnes', 'About 150 million tonnes'], 0,
    'Time-sensitive: final estimates for 2023–24 were about 332 Mt, and 2024–25 estimates are higher.'],
  ['The Green Revolution in India was driven mainly by:', ['Dwarf high-yielding wheat and rice varieties with irrigation, fertilisers and assured prices', 'Organic farming', 'Millet expansion in drylands', 'Mechanised tea estates'], 0,
    'Semi-dwarf wheats from Mexico (with Norin-10 genes) and rice IR8 were key; gains were concentrated in Punjab, Haryana and western UP.'],
  ['A major effect of the Green Revolution on Indian diets was:', ['A shift from millets and pulses towards rice and wheat', 'More millet consumption', 'More pulses per person', 'Less cereal consumption overall'], 0,
    'Per capita pulse availability fell as pulse area shrank.'],
  ['Of India\'s total foodgrain output, cereals contribute:', ['Over 90%, with pulses making up most of the rest', 'About 50%', 'Less than 25%', 'Exactly the same as pulses'], 0,
    'Rice and wheat dominate cereal output.'],
  ['"Indian agriculture is a gamble in the monsoon" because:', ['About half the net sown area is rainfed and the south-west monsoon brings most of the annual rain', 'All crops are irrigated', 'Monsoon has no effect on yields', 'Rain falls evenly through the year'], 0,
    'Monsoon failure cuts kharif output, rural incomes and food supply.'],
  ['A structural constraint on Indian food production is:', ['Small and fragmented holdings (average about 1.08 ha in Agriculture Census 2015–16)', 'Too much cultivable land', 'Too many farm machines', 'Excess research spending'], 0,
    'Low input-use efficiency, soil degradation and yield gaps also limit output.'],
  ['The rice–wheat system of the Indo-Gangetic plains faces:', ['Groundwater depletion, residue burning and declining factor productivity', 'Excess soil organic matter', 'Too little irrigation everywhere', 'No pest problems'], 0,
    'It covers about 10 million hectares in India; diversification and conservation agriculture are proposed.'],
  ['Strategies to break yield plateaus include:', ['Hybrids, new plant types, balanced nutrition, conservation agriculture and precision farming', 'Reducing all inputs', 'Growing only traditional varieties', 'Stopping irrigation'], 0,
    'Bringing Green Revolution to Eastern India (2010–11) targeted low-yield regions.'],
  ['The concern that population may outgrow food supply was first set out by:', ['Thomas Malthus', 'Norman Borlaug', 'M. S. Swaminathan', 'Adam Smith'], 0,
    'Time-sensitive: India became the most populous country around 2023 (UN estimate), so demand keeps rising.'],
  ['A scientific approach to crop production boosts food output mainly by:', ['Improved varieties, soil-test-based fertilisers, timely operations and plant protection', 'Leaving land fallow', 'Burning crop residues', 'Planting at random'], 0,
    'Extension links research to farmers\' fields.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 3, pyq: ['CSE-2024-A2-m26', 'CSE-2014-A2-m32', 'CSE-1994-A2-m16', 'CSE-2017-A2-m28', 'CSE-2021-A2-m28', 'IFoS-2025-A2-Q6b', 'CSE-2020-A2-m25', 'CSE-2025-A2-m25', 'CSE-2017-A2-m25', 'IFoS-2022-A2-m27', 'CSE-1993-A2-m39', 'CSE-2023-A2-m22'], q: [
  ['According to NFHS-5 (2019–21), the share of anaemic women aged 15–49 in India is about:', ['57%', '15%', '30%', '85%'], 0,
    'About 67% of children aged 6–59 months were anaemic. Time-sensitive survey figures.'],
  ['Anaemia Mukt Bharat (2018) follows a:', ['6×6×6 strategy — six target groups, six interventions and six institutional mechanisms', 'Single-dose vaccine plan', 'Food export plan', 'Crop insurance plan'], 0,
    'Iron–folic acid supplementation, deworming and testing are core interventions.'],
  ['Vitamin A deficiency causes:', ['Night blindness and xerophthalmia', 'Goitre', 'Scurvy', 'Rickets'], 0,
    'Children aged 9 months to 5 years get vitamin A doses every six months.'],
  ['Iodine deficiency disorders are prevented in India mainly through:', ['Universal iodisation of salt', 'Rice fortification with zinc', 'Vitamin D tablets', 'Milk fortification'], 0,
    'Deficiency causes goitre and cretinism.'],
  ['Marasmus differs from kwashiorkor in that marasmus:', ['Is severe wasting from overall lack of energy and nutrients, without oedema', 'Is caused by protein deficiency with oedema', 'Is a vitamin deficiency', 'Affects only adults'], 0,
    'Both are forms of protein-energy malnutrition.'],
  ['Stunting in children means:', ['Low height for age, reflecting chronic undernutrition', 'Low weight for height', 'Overweight', 'Low birth weight only'], 0,
    'NFHS-5: about 35.5% of under-fives were stunted, 19.3% wasted and 32.1% underweight.'],
  ['"Hidden hunger" is best tackled by combining:', ['Diet diversification, food fortification, biofortification and supplementation', 'More rice alone', 'More sugar', 'Less fruit'], 0,
    'Fortified rice with iron, folic acid and vitamin B12 is now supplied through PDS and school meals.'],
  ['An example of a biofortified variety released in India is:', ['Pearl millet Dhanashakti, rich in iron', 'Rice IR8', 'Wheat Sonalika', 'Bt cotton'], 0,
    'Others include zinc-rich rice DRR Dhan 45 and zinc- and iron-rich wheat varieties.'],
  ['POSHAN Abhiyaan (National Nutrition Mission), launched in 2018, aims to reduce:', ['Stunting, undernutrition, anaemia and low birth weight', 'Food exports', 'Fertiliser use', 'Crop losses'], 0,
    'It uses technology and convergence of schemes through anganwadis.'],
  ['Millets are promoted as "nutri-cereals" for fighting malnutrition because they are:', ['Rich in minerals such as iron and calcium, dietary fibre and have a low glycaemic index', 'High in fat and sugar', 'Free of protein', 'Grown only with heavy irrigation'], 0,
    '2023 was the International Year of Millets, proposed by India.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: ['CSE-1995-A2-m34', 'CSE-2025-A2-m26', 'IFoS-2003-A2-m33', 'CSE-2014-A2-m29', 'CSE-2023-A2-m24', 'CSE-2021-A2-m22', 'IFoS-2015-A2-m30', 'IFoS-2011-A2-m14', 'IFoS-2015-A2-m10', 'IFoS-2015-A2-m06', 'IFoS-2011-A2-m26', 'IFoS-2010-A2-m27'], q: [
  ['Foods are grouped by function into:', ['Energy-giving (cereals, fats, sugar), body-building (pulses, milk, eggs, meat) and protective (fruits, vegetables)', 'Sweet, sour and salty', 'Raw and cooked', 'Local and imported'], 0,
    'Protective foods supply vitamins and minerals.'],
  ['A balanced diet is one that:', ['Supplies all nutrients in the right amounts and proportions for health', 'Has equal weights of all foods', 'Contains only cereals and pulses', 'Avoids all fats'], 0,
    'Dietary Guidelines for Indians are issued by ICMR–National Institute of Nutrition, Hyderabad (latest edition 2024).'],
  ['ICMR–NIN (2020) puts the daily energy need of a sedentary adult man (about 65 kg) at roughly:', ['2,100 kcal', '1,200 kcal', '3,500 kcal', '5,000 kcal'], 0,
    'A sedentary woman (about 55 kg) needs roughly 1,660 kcal; needs rise with activity.'],
  ['The protein requirement of a healthy adult is about:', ['0.8 g per kg body weight per day', '5 g per kg per day', '0.1 g per kg per day', '20 g per kg per day'], 0,
    'ICMR–NIN (2020) suggests 0.83 g/kg/day.'],
  ['Eating cereals with pulses improves protein quality because:', ['Cereals are low in lysine and pulses low in methionine, so they complement each other', 'Both are rich in fat', 'Pulses lack all amino acids', 'Cereals contain no protein'], 0,
    'Dal–rice and roti–dal are traditional complementary meals.'],
  ['Typical protein content of pulses is about:', ['20–25%, with soybean near 40%', '2–3%', '60–70%', '90%'], 0,
    'Cereals have about 7–12% protein.'],
  ['The Indian dietary pattern is characterised by:', ['Heavy reliance on cereals for energy, with low intake of pulses, fruits, vegetables and animal foods among the poor', 'Mostly meat-based diets', 'High fruit intake everywhere', 'Very low cereal intake'], 0,
    'Food-based dietary approaches aim to diversify diets rather than rely on pills.'],
  ['The Integrated Child Development Services (ICDS) scheme, launched in 1975, provides:', ['Supplementary nutrition, immunisation, health check-ups, referral, pre-school and nutrition education through anganwadis', 'Only school meals', 'Only cash transfers', 'Only crop loans'], 0,
    'It serves children under six, pregnant women and nursing mothers.'],
  ['Fruits are important in the diet mainly as sources of:', ['Vitamins (especially C and A), minerals, fibre, sugars and organic acids', 'Protein only', 'Fat only', 'Starch only'], 0,
    'Most fresh fruits are 80–90% water.'],
  ['Among common fruits, an outstanding source of vitamin C is:', ['Aonla (Indian gooseberry)', 'Banana', 'Grape', 'Apple'], 0,
    'Aonla has several hundred mg of vitamin C per 100 g; guava is also rich.']
] },
{ p: 'A2', t: 'Post-harvest & Food Processing', w: 2, pyq: ['CSE-2026-A2-Q8c', 'CSE-2022-A2-m28', 'IFoS-2012-A2-m29', 'CSE-1995-A2-m30', 'IFoS-2003-A2-m32', 'IFoS-2003-A2-m31', 'IFoS-2003-A2-m34', 'CSE-2018-A2-m28', 'IFoS-2016-A2-m29', 'CSE-2010-A2-m29', 'IFoS-2023-A2-m05', 'CSE-1997-A2-m04', 'CSE-1989-A2-m01', 'CSE-1993-A2-m05', 'CSE-1989-A2-m02'], q: [
  ['Major causes of post-harvest losses of fruits and vegetables in India are:', ['High perishability, rough handling, lack of cold chain and storage, and poor transport', 'Excessive processing', 'Too many cold stores', 'Low production'], 0,
    'Grading, proper packaging, pre-cooling and cold chains reduce losses.'],
  ['Spoilage of fruits and vegetables is caused by:', ['Microbes, enzymes, continued respiration and water loss, and mechanical injury', 'Only insects', 'Only sunlight', 'Only freezing'], 0,
    'Preservation methods aim to check microbes and enzymes.'],
  ['Osmo-dehydration of fruits means:', ['Partly removing water by soaking in concentrated sugar or salt solution before drying', 'Drying in direct sun only', 'Freezing and thawing', 'Boiling in water'], 0,
    'It improves colour, flavour and texture compared with sun drying alone.'],
  ['A fruit candy differs from a preserve in that a candy:', ['Is impregnated with more sugar (about 75%), then drained and dried', 'Is kept in heavy syrup', 'Contains no sugar', 'Is made only from juice'], 0,
    'A preserve (murabba) is fruit cooked in heavy syrup till tender and transparent.'],
  ['A ready-to-serve (RTS) fruit beverage must contain at least:', ['10% fruit juice and about 10% total soluble solids', '50% juice', '1% juice', '90% juice'], 0,
    'Acidity is usually around 0.3%; it is drunk without dilution.'],
  ['Canning, which preserves food by heating in hermetically sealed containers, was developed by:', ['Nicolas Appert', 'Louis Pasteur', 'Robert Koch', 'Justus von Liebig'], 0,
    'Appert is called the "father of canning".'],
  ['Vinegar is made by:', ['Alcoholic fermentation by yeast followed by acetic fermentation by *Acetobacter*', 'Lactic fermentation only', 'Boiling fruit juice', 'Adding citric acid to water'], 0,
    'It must contain at least about 4% acetic acid.'],
  ['Bananas should not be kept in a refrigerator because:', ['Temperatures below about 12–13 °C cause chilling injury, blackening the peel and stopping proper ripening', 'They freeze instantly', 'Cold makes them ripen too fast', 'They absorb odours'], 0,
    'Tropical fruits are generally chilling-sensitive.'],
  ['Aflatoxins are:', ['Carcinogenic toxins produced by *Aspergillus flavus* and *A. parasiticus* in groundnut, maize and other produce', 'Bacterial toxins in milk only', 'Plant hormones', 'Pesticide residues'], 0,
    'They were discovered after "Turkey X disease" in England (1960); drying produce quickly prevents them.'],
  ['Before drying, green black-pepper berries are often blanched in hot water for about a minute to:', ['Get a uniform glossy black colour and faster drying', 'Remove the skin', 'Make white pepper', 'Kill the seed embryo for sowing'], 0,
    'Aonla is usually processed (murabba, candy) because the raw fruit is very astringent.']
] },
{ p: 'A2', t: 'Post-harvest & Food Processing', w: 2, pyq: ['CSE-2020-A2-m28', 'IFoS-2016-A2-m28', 'CSE-2018-A2-m17', 'CSE-2026-A2-Q8b'], q: [
  ['The post-harvest life of cut flowers is shortened mainly by:', ['Ethylene, water stress from blocked stems, depleted sugars and high temperature', 'Low temperature storage', 'Clean water', 'Sugar in the vase'], 0,
    'Microbes in vase water block xylem vessels.'],
  ['Silver thiosulphate (STS) extends vase life by:', ['Blocking the action of ethylene', 'Adding sugar', 'Killing insects', 'Raising pH'], 0,
    '1-MCP is another ethylene-action inhibitor; carnation and orchids are very ethylene-sensitive.'],
  ['Pulsing of cut flowers means:', ['A short treatment with a high-sugar solution plus germicide before storage or shipping', 'Cutting stems at intervals', 'Spraying water', 'Storing at high temperature'], 0,
    'It supplies carbohydrates for opening and longevity.'],
  ['A typical vase (holding) solution contains:', ['Sucrose (2–5%), a germicide such as 8-hydroxyquinoline citrate, and an acidifier', 'Only tap water', 'Urea and potash', 'Salt solution'], 0,
    'Low pH (about 3–3.5) improves water uptake.'],
  ['Most cut flowers are best stored at:', ['About 1–4 °C, though tropical flowers like anthurium and orchids need about 12–15 °C', '25–30 °C', '−10 °C', '40 °C'], 0,
    'Tropical flowers suffer chilling injury at low temperatures.'],
  ['"Bent neck" in roses is caused by:', ['Water stress or blocked water flow in the stem just below the flower', 'Too much sugar', 'Ethylene from fruits only', 'Excess light'], 0,
    'Harvesting at the right stage and recutting stems help.'],
  ['Recutting flower stems under water helps because it:', ['Removes air bubbles (embolism) that block water uptake', 'Adds nutrients', 'Kills ethylene', 'Changes flower colour'], 0,
    'A slanting cut also increases the uptake area.'],
  ['Standard carnations for distant markets are harvested at the:', ['"Paint-brush" stage, when petals just show colour', 'Fully open stage', 'Seed stage', 'Tight green bud with no colour'], 0,
    'Roses are cut at the tight bud stage; gladiolus when one to two basal florets show colour.'],
  ['Pre-harvest growing conditions affect vase life because:', ['Light, nutrition (especially calcium) and water supply determine stored sugars and tissue strength', 'They have no effect', 'Only post-harvest handling matters', 'Only flower colour matters'], 0,
    'Excess nitrogen gives soft stems with poor keeping quality.'],
  ['A flower relatively less sensitive to ethylene is:', ['Chrysanthemum', 'Carnation', 'Orchid', 'Sweet pea'], 0,
    'Ethylene-sensitive flowers wilt or drop petals quickly near ripening fruit.']
] },
{ p: 'A2', t: 'Food Security & Nutrition', w: 2, pyq: ['CSE-2023-A2-m26', 'CSE-2021-A2-m26', 'CSE-2018-A2-m26', 'CSE-2016-A2-m31', 'CSE-1996-A2-m27', 'CSE-1995-A2-m32', 'CSE-2022-A2-m19', 'CSE-2016-A2-m23', 'CSE-2017-A2-m24', 'CSE-2013-A2-m30', 'CSE-2012-A2-m01'], q: [
  ['Forms of intellectual property protected in India include:', ['Patents, trademarks, copyrights, geographical indications, designs and plant varieties', 'Only patents', 'Only copyrights', 'Land titles'], 0,
    'Plant varieties are protected under the PPV&FR Act, 2001; GIs under the GI Act, 1999.'],
  ['Article 27.3(b) of the WTO TRIPS Agreement requires members to protect plant varieties by:', ['Patents, an effective sui generis system, or both', 'Copyright only', 'Trademarks only', 'No protection at all'], 0,
    'India chose a sui generis system — the PPV&FR Act.'],
  ['To be registered as new under the PPV&FR Act, a variety must be:', ['Novel, distinct, uniform and stable (DUS)', 'High-yielding only', 'Imported', 'Grown for ten years'], 0,
    'The Act also registers extant varieties, farmers\' varieties and essentially derived varieties.'],
  ['Under the PPV&FR Act, farmers may:', ['Save, use, sow, re-sow, exchange, share and sell their farm produce including seed, but not branded seed of a protected variety', 'Not save seed at all', 'Sell branded seed of any protected variety', 'Only buy certified seed'], 0,
    'Farmers can also claim compensation if a variety fails to perform as claimed.'],
  ['Protection under the PPV&FR Act lasts:', ['18 years for trees and vines and 15 years for other crops', '5 years for all crops', '50 years', 'Forever'], 0,
    'Extant notified varieties get 15 years from notification under the Seeds Act.'],
  ['India\'s first geographical indication (2004) was:', ['Darjeeling tea', 'Basmati rice', 'Alphonso mango', 'Nagpur orange'], 0,
    'GIs protect products whose quality is tied to place of origin.'],
  ['The Traditional Knowledge Digital Library (TKDL) helps by:', ['Documenting traditional knowledge so patent offices can reject claims on it', 'Selling seeds', 'Giving loans', 'Testing soils'], 0,
    'Patents on turmeric for wound healing and on neem were revoked after challenges.'],
  ['The Biological Diversity Act, 2002 regulates:', ['Access to biological resources and associated knowledge, with fair benefit sharing', 'Seed certification', 'Pesticide registration', 'Fertiliser prices'], 0,
    'The National Biodiversity Authority is in Chennai; the Act aligns with the CBD and Nagoya Protocol.'],
  ['GATT was replaced in 1995 by the World Trade Organization, whose Agreement on Agriculture covers:', ['Market access, domestic support and export subsidies', 'Only industrial tariffs', 'Only patents', 'Only fisheries'], 0,
    'TRIPS, also part of the WTO, deals with intellectual property.'],
  ['The PPV&FR Authority honours farming communities that conserve crop genetic resources through the:', ['Plant Genome Saviour Community Award, funded by the National Gene Fund', 'Padma Shri', 'Krishi Karman Award only', 'Bharat Ratna'], 0,
    'Benefit-sharing payments also go to the National Gene Fund.']
] }
);
