/* Concept sets for Botany I — Angiosperm taxonomy. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 3, pyq: ['IFoS-2024-B1-m08', 'CSE-2023-B1-m10', 'IFoS-2023-B1-m07', 'IFoS-2022-B1-m07', 'IFoS-2021-B1-m08', 'IFoS-2019-B1-m06', 'IFoS-2018-B1-Q6a', 'IFoS-2017-B1-Q6a', 'CSE-2017-B1-m06', 'IFoS-2015-B1-m09', 'IFoS-2014-B1-m10', 'IFoS-2012-B1-m13', 'CSE-2007-B1-m07', 'IFoS-2006-B1-m06', 'CSE-2004-B1-m10', 'IFoS-2001-B1-m12', 'IFoS-2000-B1-m10', 'CSE-1996-B1-m09', 'CSE-1995-B1-m07', 'CSE-1990-B1-m17', 'CSE-1988-B1-m08', 'CSE-1986-B1-m11', 'CSE-1985-B1-m13', 'CSE-2024-B1-m09', 'CSE-2019-B1-m05', 'CSE-2018-B1-m06', 'CSE-2016-B1-m10', 'IFoS-2011-B1-m10', 'CSE-2005-B1-m06', 'CSE-2001-B1-m05', 'CSE-2014-B1-m10', 'CSE-2013-B1-m06', 'CSE-1989-B1-m13', 'IFoS-2002-B1-m05'], q: [
  ['Bentham and Hooker published their system in:', ['*Genera Plantarum* (1862–83)', '*Species Plantarum* (1753)', '*Die Natürlichen Pflanzenfamilien*', '*The Families of Flowering Plants*'], 0,
    'It is a natural system with 202 "orders" (families), still used in many Indian herbaria.'],
  ['In Bentham and Hooker\'s system, gymnosperms are placed:', ['Between dicotyledons and monocotyledons', 'Before dicotyledons', 'After monocotyledons', 'Outside seed plants'], 0,
    'This is a major demerit of the system.'],
  ['Bentham and Hooker divided Polypetalae into the series:', ['Thalamiflorae, Disciflorae and Calyciflorae', 'Inferae, Heteromerae and Bicarpellatae', 'Lignosae and Herbaceae', 'Magnoliidae and Rosidae'], 0,
    'Gamopetalae: Inferae, Heteromerae, Bicarpellatae; the third group of dicots is Monochlamydeae.'],
  ['Engler and Prantl treated as primitive the dicots with:', ['Simple unisexual flowers without perianth, such as catkin-bearing Amentiferae', 'Large showy bisexual flowers', 'Zygomorphic flowers', 'Inferior ovaries'], 0,
    'Their system also placed monocots before dicots.'],
  ['Hutchinson divided dicotyledons into:', ['Lignosae (woody) and Herbaceae (herbaceous)', 'Polypetalae and Gamopetalae', 'Magnoliopsida and Liliopsida', 'Eudicots and magnoliids'], 0,
    'He took Magnoliales and Ranales as primitive and stated 24 principles.'],
  ['Cronquist (1981) divided Magnoliophyta into:', ['Magnoliopsida (6 subclasses) and Liliopsida (5 subclasses)', 'Polypetalae and Monochlamydeae', 'Lignosae and Herbaceae', '64 orders'], 0,
    'He used chemical and anatomical data along with morphology.'],
  ['The "Dahlgrenogram" is:', ['A two-dimensional cross-section of a phylogenetic tree with orders as bubbles', 'A floral diagram', 'A pollen chart', 'A key to families'], 0,
    'Rolf Dahlgren used it to map character distribution across superorders.'],
  ['The APG system of classification is based mainly on:', ['Molecular (DNA sequence) phylogenies analysed cladistically', 'Number of stamens', 'Habit alone', 'Economic uses'], 0,
    'Genes such as *rbcL*, *atpB* and 18S rDNA were used.'],
  ['APG IV (2016) recognises:', ['64 orders and 416 families of angiosperms', '202 orders', '24 classes', 'Two subclasses only'], 0,
    'Informal clades include magnoliids, monocots and eudicots.'],
  ['Linnaeus\'s sexual system is called artificial because it:', ['Used a few characters, mainly the number of stamens', 'Was based on DNA', 'Used all available characters', 'Showed evolutionary relationships'], 0,
    'Natural systems use overall similarity; phylogenetic systems use descent.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 3, pyq: ['CSE-2001-B1-m06', 'CSE-1997-B1-m06', 'CSE-1997-B1-m07', 'CSE-1997-B1-m08', 'CSE-1997-B1-m09', 'CSE-1997-B1-m10', 'CSE-2014-B1-m08', 'IFoS-2013-B1-m08', 'IFoS-2010-B1-m15', 'CSE-2004-B1-m06', 'CSE-1995-B1-m10', 'CSE-2022-B1-m06', 'CSE-1990-B1-m18', 'IFoS-2003-B1-m10', 'CSE-1990-B1-m14', 'CSE-1987-B1-m11', 'CSE-1991-B1-m12', 'CSE-2006-B1-m08', 'IFoS-2016-B1-m06', 'CSE-1994-B1-m13', 'CSE-1987-B1-m08', 'CSE-2024-B1-m08', 'IFoS-2016-B1-m07', 'CSE-2010-B1-m09', 'CSE-1988-B1-m10', 'IFoS-2007-B1-m05', 'IFoS-2015-B1-m02', 'CSE-2023-B1-m04', 'IFoS-2024-B1-m05'], q: [
  ['Which set of floral characters is considered primitive?', ['Bisexual, actinomorphic, many free spirally arranged parts and superior ovary', 'Unisexual, zygomorphic, fused parts and inferior ovary', 'Reduced, fused stamens and syncarpy', 'Epigyny with few stamens'], 0,
    'The advanced trend is fusion, reduction, zygomorphy and epigyny.'],
  ['A primitive feature of Magnoliaceae is:', ['An elongated thalamus bearing many spirally arranged stamens and carpels', 'An inferior ovary', 'Pollinia', 'Syngenesious anthers'], 0,
    'Also undifferentiated tepals, broad laminar stamens and monosulcate pollen.'],
  ['The "primitive carpel" of *Degeneria* and *Drimys* is:', ['Conduplicate — a folded leaf with unsealed margins and a stigmatic crest', 'Fully closed with a long style', 'Fused with others', 'Absent'], 0,
    'Classically, a carpel is a megasporophyll folded along its midrib.'],
  ['Axile placentation is explained as arising from:', ['Fusion of the margins of conduplicate carpels at the centre', 'A single carpel', 'Loss of septa', 'Ovules on the ovary wall'], 0,
    'Free-central placentation follows breakdown of septa.'],
  ['Darwin called the sudden rise of angiosperms an:', ['"Abominable mystery"', '"Missing link"', '"Living fossil"', '"Big bang of plants"'], 0,
    'Theories derive them from Bennettitales, Caytoniales, Gnetales or glossopterids.'],
  ['The pseudanthial theory (Wettstein) derives the angiosperm flower from:', ['A compound gnetalean inflorescence', 'A bisexual bennettitalean strobilus', 'A fern sorus', 'A moss capsule'], 0,
    'The euanthial (anthostrobilus) theory of Arber and Parkin starts from a bisexual strobilus.'],
  ['The living plant regarded as sister to all other angiosperms is:', ['*Amborella trichopoda* of New Caledonia', '*Magnolia grandiflora*', '*Arabidopsis thaliana*', '*Nymphaea alba*'], 0,
    'Takhtajan saw the SE Asia–South Pacific region as the "cradle" of flowering plants.'],
  ['*Ranalisma* is cited as a link between dicots and monocots because it:', ['Is an Alismataceae monocot with apocarpous carpels like Ranunculaceae', 'Has two cotyledons', 'Has vessels', 'Has net veins'], 0,
    'Alismatids share free carpels and other features with Ranales.'],
  ['Monophyly of angiosperms is supported by unique shared features such as:', ['Double fertilisation, carpels and sieve tubes with companion cells', 'Seeds only', 'Wood with tracheids', 'Motile sperms'], 0,
    'Molecular phylogenies also support a single origin.'],
  ['Magnoliaceae differ from Ranunculaceae in being:', ['Woody plants with stipules', 'Herbs without stipules', 'Monocots', 'Gamopetalous'], 0,
    'Both have spirally arranged free floral parts.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 3, pyq: ['CSE-2021-B1-m05', 'CSE-2016-B1-m09', 'CSE-2014-B1-m04', 'CSE-2004-B1-m05', 'CSE-1992-B1-m12', 'CSE-1990-B1-m16', 'CSE-2025-B1-m07', 'CSE-2011-B1-m04', 'CSE-1992-B1-m10', 'CSE-2009-B1-m13', 'CSE-2006-B1-m09', 'CSE-1994-B1-m16', 'CSE-1990-B1-m19', 'CSE-1985-B1-m11', 'CSE-1993-B1-m11', 'CSE-1986-B1-m09', 'CSE-1998-B1-m13', 'IFoS-2010-B1-m19', 'CSE-1987-B1-m06', 'CSE-2021-B1-m10', 'CSE-1994-B1-m15', 'CSE-1995-B1-m34', 'CSE-2019-B1-m09', 'CSE-2017-B1-m04', 'CSE-2001-B1-m05', 'IFoS-2021-B1-m09', 'CSE-2021-B1-m06', 'CSE-2007-B1-m06', 'CSE-2017-B1-m08', 'CSE-2023-B1-m11', 'CSE-2018-B1-m11'], q: [
  ['Numerical taxonomy was developed by:', ['Sokal and Sneath (1963)', 'Bentham and Hooker', 'Camp and Gilly', 'Turesson'], 0,
    'It follows Adansonian principles — all characters weighted equally.'],
  ['In numerical taxonomy, the units compared are called:', ['Operational taxonomic units (OTUs)', 'Ecotypes', 'Clades', 'Holotypes'], 0,
    'Similarity coefficients are clustered into a phenogram (dendrogram).'],
  ['A limitation of numerical taxonomy is that:', ['Results depend on which characters are chosen, and equal weighting ignores evolution', 'It needs no data', 'It uses only DNA', 'It cannot use computers'], 0,
    'It is phenetic rather than phylogenetic.'],
  ['Chemotaxonomy uses:', ['Chemical constituents, especially secondary metabolites', 'Only leaf shape', 'Fossil records', 'Chromosome number only'], 0,
    'E.g. alkaloids, flavonoids, glucosinolates of Brassicales.'],
  ['Betalain pigments (instead of anthocyanins) mark most families of:', ['Caryophyllales', 'Rosales', 'Poales', 'Asterales'], 0,
    'Caryophyllaceae and Molluginaceae are exceptions with anthocyanins.'],
  ['Alpha taxonomy is the stage of:', ['Describing and naming species, mainly from morphology', 'Synthesising all data into a final system', 'Molecular cladistics', 'Arranging higher categories'], 0,
    'Omega taxonomy is the ideal final synthesis of all evidence.'],
  ['Biosystematics, a term of Camp and Gilly (1943), studies:', ['Variation, breeding behaviour and cytogenetics of populations', 'Only herbarium specimens', 'Fossils', 'Floral formulae'], 0,
    'Turesson\'s categories: ecotype, ecospecies, coenospecies.'],
  ['Embryological evidence led to the removal of *Trapa* from:', ['Onagraceae', 'Rosaceae', 'Poaceae', 'Fabaceae'], 0,
    '*Paeonia* was similarly removed from Ranunculaceae.'],
  ['Stellate hairs are a useful taxonomic marker in:', ['Malvaceae', 'Poaceae', 'Orchidaceae', 'Liliaceae'], 0,
    'Glandular peltate hairs mark Lamiaceae; anatomy such as Kranz type separates C₄ grasses.'],
  ['Systematics differs from classification in that systematics:', ['Covers the whole study of diversity and relationships, of which classification is one part', 'Is only naming', 'Is only grouping', 'Ignores evolution'], 0,
    'Simpson defined systematics as the scientific study of kinds and diversity of organisms and their relationships.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: ['CSE-2014-B1-m07', 'CSE-2004-B1-m08', 'CSE-2002-B1-m09', 'CSE-1999-B1-m11', 'IFoS-2016-B1-m08', 'CSE-1994-B1-m17', 'CSE-2022-B1-m03', 'IFoS-2009-B1-m12', 'CSE-2021-B1-m07', 'IFoS-2010-B1-m13'], q: [
  ['The column (gynostemium) of an orchid is formed by:', ['Fusion of the stamens with the style and stigma', 'Fusion of petals', 'The labellum', 'The ovary wall'], 0,
    'One part of the stigma forms the rostellum.'],
  ['The labellum of an orchid is:', ['The modified median petal, often the landing platform', 'A sepal', 'A stamen', 'A bract'], 0,
    'It comes to lie lowermost by twisting of the ovary (resupination).'],
  ['Resupination in orchids is:', ['Twisting of the ovary or pedicel through 180°', 'Folding of the labellum', 'Loss of stamens', 'Opening of anthers'], 0,
    'It brings the labellum to the lower side.'],
  ['Orchid pollinia carry a sticky:', ['Viscidium on a stalk (caudicle), which fixes to the insect', 'Translator with corpusculum', 'Wing', 'Pore'], 0,
    'In Asclepiadaceae a translator (corpusculum and retinacula) links pollinia of adjacent anthers.'],
  ['Diandrous orchids such as *Cypripedium* (lady\'s slipper) have:', ['Two fertile stamens', 'One fertile stamen', 'Three fertile stamens', 'No stamens'], 0,
    'Most orchids are monandrous.'],
  ['Orchid seeds are:', ['Minute, without endosperm, and need mycorrhizal fungi to germinate', 'Large and starchy', 'Winged and woody', 'Enclosed in a drupe'], 0,
    'A single capsule can hold millions of seeds.'],
  ['The orchid ovary is:', ['Inferior, unilocular with parietal placentation', 'Superior and trilocular', 'Apocarpous', 'Inferior with axile placentation'], 0,
    'It is tricarpellary and syncarpous.'],
  ['Aerial roots of epiphytic orchids such as *Vanda* have:', ['A velamen that absorbs moisture', 'Root nodules', 'Pneumatophores', 'Haustoria'], 0,
    'Velamen is a multi-layered dead epidermis.'],
  ['Vanilla flavour comes from the fruits of:', ['*Vanilla planifolia*, an orchid', '*Piper nigrum*', '*Elettaria cardamomum*', '*Myristica fragrans*'], 0,
    'Flowers are hand-pollinated outside Mexico.'],
  ['Pseudocopulation, where male bees try to mate with the flower, is seen in:', ['*Ophrys*', '*Hibiscus*', '*Salvia*', '*Euphorbia*'], 0,
    'Orchids show some of the most specialised pollination systems.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: ['IFoS-2013-B1-m09', 'CSE-2002-B1-m08', 'IFoS-2000-B1-m05', 'CSE-1999-B1-m09', 'CSE-1992-B1-m14', 'CSE-1991-B1-m14', 'CSE-1987-B1-m09', 'CSE-1985-B1-m09', 'CSE-2014-B1-m05', 'CSE-1995-B1-m08', 'IFoS-2004-B1-m11', 'IFoS-2005-B1-m07', 'CSE-2007-B1-m18', 'CSE-1991-B1-m05', 'IFoS-2010-B1-m12'], q: [
  ['A cyathium consists of:', ['A cup of bracts with nectar glands, one central female flower and many male flowers', 'A head of ray and disc florets', 'A spike on a fleshy axis', 'A hollow receptacle with flowers inside'], 0,
    'It is the characteristic inflorescence of *Euphorbia*.'],
  ['Each male flower in a cyathium is reduced to:', ['A single stamen jointed to a short pedicel', 'A whorl of five stamens', 'A perianth with stamens', 'A pollinium'], 0,
    'The joint marks where pedicel meets filament.'],
  ['In a cyathium, male flowers are arranged in:', ['Scorpioid cymes (centrifugally)', 'A raceme', 'An umbel', 'A spike'], 0,
    'So the inflorescence is cymose overall.'],
  ['The ovary of Euphorbiaceae is usually:', ['Tricarpellary, syncarpous, superior and trilocular with axile placentation', 'Bicarpellary and inferior', 'Monocarpellary', 'Unilocular with parietal placentation'], 0,
    'The fruit is a regma that splits into three cocci.'],
  ['Euphorbiaceae commonly have:', ['Latex', 'Pollinia', 'Tendrils', 'Velamen'], 0,
    'Asclepiadaceae also have latex but differ in pollinia and gynostegium.'],
  ['Natural rubber comes from:', ['*Hevea brasiliensis*', '*Ricinus communis*', '*Jatropha curcas*', '*Manihot esculenta*'], 0,
    'Castor oil: *Ricinus*; tapioca: *Manihot*; biodiesel: *Jatropha*.'],
  ['The stamens of *Ricinus* are:', ['Polyadelphous and much branched', 'Monadelphous', 'Diadelphous', 'Syngenesious'], 0,
    'The plant is monoecious, with male flowers below and female above.'],
  ['The seed of *Ricinus* bears a fleshy outgrowth called a:', ['Caruncle', 'Aril', 'Hilum', 'Raphe'], 0,
    'It absorbs water during germination.'],
  ['Cassava (tapioca) is the tuberous root of:', ['*Manihot esculenta*', '*Ipomoea batatas*', '*Dioscorea*', '*Colocasia*'], 0,
    'It contains cyanogenic glycosides removed by processing.'],
  ['The cyathium looks like a single flower, so it is an example of a:', ['Pseudanthium', 'Pome', 'Hypanthodium', 'Capsule'], 0,
    'A capitulum is another pseudanthium.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: ['IFoS-2011-B1-m09', 'IFoS-2010-B1-m16', 'CSE-2010-B1-m15', 'IFoS-2004-B1-m10', 'CSE-2001-B1-m08', 'CSE-2000-B1-m06', 'CSE-2024-B1-m03', 'IFoS-2012-B1-m10'], q: [
  ['Stamens of Brassicaceae are:', ['Tetradynamous — four long and two short', 'Didynamous — two long and two short', 'Monadelphous', 'Syngenesious'], 0,
    'The corolla is cruciform with four clawed petals.'],
  ['The ovary of Brassicaceae has:', ['Two carpels, parietal placentation and a false septum (replum)', 'Five carpels and axile placentation', 'One carpel and marginal placentation', 'Three carpels and free-central placentation'], 0,
    'The fruit is a siliqua (long) or silicula (short).'],
  ['The inflorescence of Brassicaceae is usually:', ['An ebracteate raceme, often corymbose at first', 'A cyathium', 'A spadix', 'A capitulum'], 0,
    'Floral formula: Ebr ⊕ ⚥ K2+2 C4 A2+4 G(2).'],
  ['The pungent "mustard oils" of crucifers come from:', ['Glucosinolates', 'Alkaloids', 'Latex', 'Tannins'], 0,
    'They are broken down by the enzyme myrosinase when tissue is damaged.'],
  ['The model plant of plant molecular biology belongs to Brassicaceae:', ['*Arabidopsis thaliana*', '*Nicotiana tabacum*', '*Oryza sativa*', '*Zea mays*'], 0,
    'It has a small genome and a short life cycle.'],
  ['In Solanaceae, the ovary is:', ['Bicarpellary, obliquely placed, with swollen axile placentae', 'Tricarpellary and inferior', 'Monocarpellary', 'Unilocular with parietal placentae'], 0,
    'The fruit is a berry or capsule.'],
  ['Solanaceae flowers have:', ['Five epipetalous stamens', 'Four stamens in two pairs', 'Many free stamens', 'Monadelphous stamens'], 0,
    'Corolla is gamopetalous and usually actinomorphic.'],
  ['Atropine is obtained from:', ['*Atropa belladonna*', '*Solanum tuberosum*', '*Capsicum annuum*', '*Brassica nigra*'], 0,
    'Hyoscyamine from *Hyoscyamus* and *Datura*; nicotine from tobacco.'],
  ['Ashwagandha, a medicinal Solanaceae, is:', ['*Withania somnifera*', '*Rauvolfia serpentina*', '*Ocimum sanctum*', '*Bacopa monnieri*'], 0,
    'Its roots are used as a tonic.'],
  ['Which crops all belong to Brassicaceae?', ['Mustard, cabbage, cauliflower and radish', 'Potato, tomato and brinjal', 'Wheat, rice and maize', 'Pea, gram and lentil'], 0,
    'The second set is Solanaceae; the last is Fabaceae.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: ['IFoS-2015-B1-m07', 'IFoS-2010-B1-m11', 'IFoS-2009-B1-m13', 'CSE-2004-B1-m07', 'CSE-1995-B1-m11', 'IFoS-2012-B1-m11', 'CSE-1992-B1-m15', 'CSE-2025-B1-m03', 'IFoS-2021-B1-m06'], q: [
  ['A grass spikelet has at its base:', ['Two empty bracts called glumes', 'A spathe', 'An involucre', 'A cupule'], 0,
    'Each floret is enclosed by a lemma and a palea.'],
  ['The lodicules of a grass floret are:', ['Reduced perianth scales that swell to open the floret', 'Bracts below the spikelet', 'Sterile stamens', 'Stigma lobes'], 0,
    'There are usually two (three in bamboo).'],
  ['Wheat florets have three stamens, but rice and bamboo have:', ['Six', 'Two', 'One', 'Many'], 0,
    'Anthers are versatile; stigmas are feathery for wind pollination.'],
  ['The grass fruit is a:', ['Caryopsis, with the seed coat fused to the pericarp', 'Siliqua', 'Berry', 'Legume'], 0,
    'It is a one-seeded dry indehiscent fruit.'],
  ['In the grass embryo, the single cotyledon is the:', ['Scutellum', 'Coleoptile', 'Coleorhiza', 'Epiblast'], 0,
    'Coleoptile sheathes the plumule; coleorhiza sheathes the radicle.'],
  ['A grass stem (culm) usually has:', ['Solid nodes and hollow internodes', 'Hollow nodes', 'Secondary growth', 'Latex'], 0,
    'The leaf has a sheath and a ligule.'],
  ['Lemongrass oil comes from:', ['*Cymbopogon*', '*Vetiveria*', '*Saccharum*', '*Dendrocalamus*'], 0,
    'Vetiver root oil is another grass product.'],
  ['Musaceae differ from Poaceae in having:', ['Large herbs with a pseudostem of leaf sheaths and an inferior ovary', 'Culms and spikelets', 'Caryopsis fruits', 'Lodicules'], 0,
    'Banana flowers are zygomorphic with five fertile stamens.'],
  ['The economically most important family of flowering plants for food is:', ['Poaceae', 'Orchidaceae', 'Asteraceae', 'Euphorbiaceae'], 0,
    'Rice, wheat, maize, millets and sugarcane are grasses.'],
  ['Bamboos belong to the grass family and flower:', ['Rarely, often gregariously after many years and then die', 'Every year', 'Only in water', 'Never'], 0,
    'E.g. *Melocanna* flowering in NE India brings rat outbreaks (mautam).']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: ['CSE-2015-B1-m07', 'CSE-2012-B1-m08', 'CSE-2010-B1-m12', 'IFoS-2009-B1-m14', 'CSE-1988-B1-m11', 'CSE-1985-B1-m07', 'CSE-1995-B1-m09', 'IFoS-2001-B1-m08', 'IFoS-2012-B1-m09', 'IFoS-2010-B1-m15', 'IFoS-2019-B1-m01', 'CSE-1991-B1-m06', 'IFoS-2025-B1-m01', 'IFoS-2006-B1-m05'], q: [
  ['Cucurbitaceae are typically:', ['Tendril-climbing herbs with unisexual flowers and an inferior ovary', 'Woody trees with bisexual flowers', 'Aquatic herbs', 'Parasites'], 0,
    'The fruit is a pepo.'],
  ['The ovary of Cucurbitaceae has:', ['Three carpels and parietal placentation', 'Two carpels and axile placentation', 'One carpel and marginal placentation', 'Five free carpels'], 0,
    'Placentae often intrude deep into the cavity.'],
  ['The androecium of *Cucurbita* consists of:', ['Five stamens appearing as three, with twisted (S-shaped) anthers', 'Ten free stamens', 'Diadelphous stamens', 'Tetradynamous stamens'], 0,
    'Two pairs fuse and one stays free; in *Cucurbita* anthers are fused (synandrous).'],
  ['*Cucurbita* stems have vascular bundles that are:', ['Bicollateral', 'Collateral closed', 'Concentric', 'Radial'], 0,
    'Phloem lies on both sides of the xylem.'],
  ['Stamens of Malvaceae are:', ['Monadelphous, forming a staminal tube, with one-celled anthers', 'Diadelphous', 'Syngenesious', 'Tetradynamous'], 0,
    'Anthers are reniform and monothecous.'],
  ['Syngenesious stamens — anthers fused, filaments free — are typical of:', ['Asteraceae', 'Malvaceae', 'Fabaceae', 'Brassicaceae'], 0,
    'They form a tube around the style.'],
  ['Papilionoid legumes have stamens that are:', ['Diadelphous (9)+1', 'Monadelphous', 'Polyadelphous', 'Syngenesious'], 0,
    'Citrus has polyadelphous stamens.'],
  ['The fibrous network of the dried fruit of *Luffa* is used as a:', ['Bath sponge', 'Rope', 'Fuel', 'Dye'], 0,
    'Other cucurbits: bottle gourd (*Lagenaria*), melon (*Cucumis melo*), watermelon (*Citrullus*).'],
  ['In Asclepiadaceae, the stamens fuse with the stigma to form the:', ['Gynostegium', 'Gynostemium', 'Staminal tube', 'Corona only'], 0,
    'Orchids have a gynostemium (column).'],
  ['Epipetalous stamens are those that are:', ['Attached to the petals', 'Free from all parts', 'Fused with the gynoecium', 'Attached to sepals'], 0,
    'Common in gamopetalous families such as Solanaceae and Asteraceae.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: ['IFoS-2005-B1-m07', 'IFoS-2001-B1-m07', 'CSE-2001-B1-m07', 'CSE-1999-B1-m10', 'CSE-2011-B1-m05', 'CSE-1988-B1-m12', 'CSE-1995-B1-m12', 'CSE-1985-B1-m08', 'CSE-1990-B1-m20', 'CSE-1986-B1-m07', 'IFoS-2010-B1-m14', 'CSE-2002-B1-m07', 'IFoS-2014-B1-m07', 'CSE-1987-B1-m07', 'IFoS-2012-B1-m08', 'CSE-2019-B1-m02', 'CSE-1986-B1-m32', 'IFoS-2013-B1-m09', 'IFoS-2000-B1-m06', 'CSE-1991-B1-m07', 'CSE-1985-B1-m04'], q: [
  ['Interpetiolar stipules and opposite leaves are typical of:', ['Rubiaceae', 'Apiaceae', 'Rosaceae', 'Lamiaceae'], 0,
    'Rubiaceae also have an inferior bicarpellary ovary.'],
  ['Which products come from Rubiaceae?', ['Coffee, quinine and madder dye', 'Tea, rubber and jute', 'Pepper, ginger and turmeric', 'Cotton, castor and teak'], 0,
    '*Coffea*, *Cinchona* and *Rubia*.'],
  ['The fruit of Apiaceae (Umbelliferae) is a:', ['Cremocarp splitting into two mericarps on a carpophore', 'Siliqua', 'Pepo', 'Pome'], 0,
    'Its ribs contain oil canals (vittae) — hence spices such as cumin and coriander.'],
  ['The inflorescence of Apiaceae is a:', ['Compound umbel', 'Cyathium', 'Spadix', 'Verticillaster'], 0,
    'Apiaceae is the newer name of Umbelliferae; a stylopodium sits on the inferior ovary.'],
  ['A pome, as in apple, is an accessory fruit because:', ['The fleshy part develops from the thalamus, not the ovary', 'It develops from many flowers', 'It has no seeds', 'It develops from one carpel'], 0,
    'Rosaceae also give drupes (peach) and etaerios (strawberry).'],
  ['A cup formed by fusion of the bases of sepals, petals and stamens is called a:', ['Hypanthium', 'Thalamus', 'Corona', 'Disc'], 0,
    'It gives perigyny or epigyny, as in Rosaceae.'],
  ['Ranunculaceae typically have:', ['Herbaceous habit, many spirally arranged stamens and free carpels', 'Woody habit with stipules', 'Inferior ovary', 'Pollinia'], 0,
    'Fruits are aggregates of achenes or follicles; *Aconitum* is highly poisonous.'],
  ['A verticillaster inflorescence, square stems and didynamous stamens mark:', ['Lamiaceae', 'Solanaceae', 'Malvaceae', 'Rubiaceae'], 0,
    'Lamiaceae also have a gynobasic style; Verbenaceae have a terminal style.'],
  ['In *Salvia*, pollination by bees uses a:', ['Lever (turn-pipe) mechanism of the stamens', 'Explosive keel', 'Trap with hairs', 'Pollinium translator'], 0,
    'A visiting bee pushes the lower lever, bringing the anther down on its back.'],
  ['The corolla of Lamiaceae is usually:', ['Bilabiate (two-lipped)', 'Cruciform', 'Papilionaceous', 'Polypetalous and actinomorphic'], 0,
    'Tulsi, mint and teak (now Lamiaceae) are examples.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: ['CSE-1997-B1-m05', 'CSE-1996-B1-m11', 'CSE-1995-B1-m06', 'CSE-1985-B1-m12', 'CSE-2007-B1-m10', 'CSE-1986-B1-m12', 'IFoS-2000-B1-m07', 'IFoS-2020-B1-m04', 'IFoS-2012-B1-m12'], q: [
  ['A typical Liliaceae flower has:', ['Six tepals in two whorls, six stamens and a superior tricarpellary ovary', 'Five petals and ten stamens', 'A cruciform corolla', 'A spikelet with glumes'], 0,
    'Placentation is axile; the fruit is a capsule or berry.'],
  ['Colchicine is obtained from:', ['*Gloriosa superba* and *Colchicum*', '*Aloe vera*', '*Allium cepa*', '*Asparagus*'], 0,
    'It is used to double chromosomes.'],
  ['The edible part of onion (*Allium cepa*) is a:', ['Bulb of fleshy leaf bases', 'Root tuber', 'Corm', 'Rhizome'], 0,
    '*Allium* is now placed in Amaryllidaceae.'],
  ['Arecaceae (Palmae) usually have:', ['An unbranched woody trunk, large plicate leaves and a spadix in a spathe', 'Climbing stems with tendrils', 'Cyathia', 'Square stems'], 0,
    'Fruits are drupes or berries.'],
  ['In the coconut, the coir comes from the:', ['Fibrous mesocarp', 'Endocarp', 'Endosperm', 'Seed coat'], 0,
    'Coconut water and kernel are liquid and solid endosperm.'],
  ['Which pair matches a palm with its product?', ['*Areca catechu* — betel nut', '*Phoenix dactylifera* — rubber', '*Elaeis guineensis* — sago', '*Borassus* — dates'], 0,
    'Dates: *Phoenix*; oil palm: *Elaeis*; palmyra: *Borassus*.'],
  ['The "stem" of a banana plant is a:', ['Pseudostem of overlapping leaf sheaths', 'Woody trunk', 'Rhizome above ground', 'Tendril'], 0,
    'The true stem is an underground rhizome.'],
  ['Banana flowers have:', ['Five fertile stamens and one staminode, with an inferior ovary', 'Ten stamens and superior ovary', 'Tetradynamous stamens', 'Pollinia'], 0,
    'Flowers are borne in clusters in the axils of large coloured bracts.'],
  ['Cultivated bananas are seedless because they are mostly:', ['Triploid and parthenocarpic', 'Diploid and apomictic', 'Haploid', 'Tetraploid and self-pollinated'], 0,
    'They are propagated by suckers and tissue culture.'],
  ['A floral formula of P3+3 A3+3 G(3) fits:', ['Liliaceae', 'Brassicaceae', 'Solanaceae', 'Fabaceae'], 0,
    'Trimerous flowers are typical of monocots.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: ['IFoS-2023-B1-m08', 'CSE-2020-B1-m06', 'IFoS-2014-B1-m07', 'IFoS-2012-B1-m10', 'IFoS-2010-B1-m13', 'CSE-2004-B1-m07', 'IFoS-2003-B1-m09', 'CSE-1996-B1-m10', 'CSE-1996-B1-m11', 'CSE-1995-B1-m06', 'CSE-1995-B1-m09', 'CSE-1994-B1-m17', 'CSE-2018-B1-m09', 'CSE-2017-B1-m07', 'CSE-2016-B1-m08', 'CSE-2015-B1-m05', 'CSE-2013-B1-m04', 'CSE-1999-B1-m04', 'CSE-1999-B1-m05', 'CSE-1999-B1-m06', 'CSE-1999-B1-m07', 'CSE-2005-B1-m08', 'CSE-2005-B1-m09', 'CSE-2005-B1-m10', 'CSE-1990-B1-m21', 'CSE-1989-B1-m17', 'IFoS-2016-B1-m05', 'CSE-1991-B1-m03', 'CSE-1991-B1-m04', 'CSE-1998-B1-m12', 'CSE-2010-B1-m01'], q: [
  ['In a floral formula, a line drawn above G(2) shows that the ovary is:', ['Inferior', 'Superior', 'Half-inferior', 'Apocarpous'], 0,
    'A line below shows a superior ovary.'],
  ['In a floral diagram, the mother axis is drawn:', ['At the top, with the bract at the bottom', 'At the bottom', 'At the centre', 'Not shown'], 0,
    'The diagram is a ground plan of the flower relative to the axis.'],
  ['Vexillary aestivation, with the standard petal outermost, is typical of:', ['Papilionoid legumes', 'Brassicaceae', 'Malvaceae', 'Liliaceae'], 0,
    'Others: valvate, twisted, imbricate, quincuncial.'],
  ['Match placentation with example: free-central —', ['*Dianthus*', 'Pea', 'Mustard', 'Sunflower'], 0,
    'Marginal: pea; parietal: mustard; basal: sunflower; axile: tomato and *Hibiscus*.'],
  ['A capitulum is:', ['A head of sessile florets on a flat receptacle surrounded by an involucre', 'A spike on a fleshy axis', 'A cup of bracts with one female flower', 'A cluster of umbels'], 0,
    'Typical of Asteraceae, with ray and disc florets.'],
  ['A pollinium is:', ['A coherent mass of pollen grains moved as one unit', 'A single pollen grain', 'A pollen tube', 'A sterile anther'], 0,
    'Found in Asclepiadaceae and Orchidaceae.'],
  ['Geocarpy — ripening of fruits underground — is shown by:', ['Groundnut, whose gynophore pushes the ovary into soil', 'Potato', 'Onion', 'Carrot'], 0,
    '*Commelina benghalensis* also bears underground cleistogamous flowers.'],
  ['Flowers of bird-pollinated trees such as *Butea*, *Erythrina* and *Bombax* are usually:', ['Bright red with much nectar and little scent', 'White and strongly scented at night', 'Small and green', 'Without nectar'], 0,
    'This is ornithophily.'],
  ['A perigynous flower has:', ['The ovary at the centre of a cup-shaped thalamus with other parts on its rim', 'Other parts below a superior ovary on a flat thalamus', 'The ovary sunk and fused with the thalamus', 'No ovary'], 0,
    'Hypogynous: ovary superior on a convex thalamus; epigynous: ovary inferior.'],
  ['Floral symbols ⊕ and % stand for:', ['Actinomorphic and zygomorphic', 'Male and female', 'Superior and inferior', 'Bisexual and unisexual'], 0,
    '⚥ is bisexual; ♂ and ♀ are male and female.']
] }
);
