/* Concept sets for Botany I — Gymnosperms & palaeobotany. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Gymnosperms', w: 3, pyq: ['IFoS-2025-B1-m03', 'CSE-2012-B1-m19', 'IFoS-2007-B1-m17', 'IFoS-2007-B1-m18', 'CSE-2005-B1-m17', 'CSE-2005-B1-m18', 'CSE-2013-B1-m12', 'CSE-1987-B1-m16', 'CSE-1999-B1-m14', 'CSE-1995-B1-m25', 'IFoS-2010-B1-m32', 'CSE-2025-B1-m28', 'CSE-1992-B1-m02', 'CSE-2023-B1-m02', 'CSE-1993-B1-m29', 'CSE-1991-B1-m21', 'CSE-2026-B1-m08'], q: [
  ['In female plants of *Cycas*, megasporophylls:', ['Form a loose rosette at the stem apex and do not make a compact cone', 'Form a compact woody cone', 'Arise singly in leaf axils', 'Are borne on dwarf shoots'], 0,
    'The apex grows on through them; male plants bear a large compact cone.'],
  ['The megasporophyll of *Cycas revoluta* differs from that of *C. circinalis* in having a lamina that is:', ['Deeply pinnately divided and densely hairy', 'Only toothed', 'Entire and glabrous', 'Absent'], 0,
    'Ovules sit on the lower part of the sporophyll; the sterile lamina varies by species.'],
  ['The ovule of *Cycas* is:', ['Orthotropous, with one thick integument of three layers and a nucellar beak', 'Anatropous, with two integuments', 'Campylotropous, without integument', 'Circinotropous'], 0,
    'Outer fleshy, middle stony and inner fleshy layers; a pollen chamber forms in the nucellar beak. *Cycas* ovules are among the largest known.'],
  ['Pollination in *Cycas* is aided by:', ['A pollination drop at the micropyle that draws pollen into the pollen chamber', 'Insects attracted by nectar', 'Water currents', 'Explosive anthers'], 0,
    'Pollination is by wind; the drop dries and pulls the pollen in.'],
  ['The male gametes of *Cycas* are:', ['Large, top-shaped and multiflagellate', 'Non-motile and small', 'Biflagellate', 'Amoeboid'], 0,
    'Cycads and *Ginkgo* show zoidiogamy — motile sperms released from a pollen tube.'],
  ['On a *Cycas* microsporophyll, microsporangia are borne:', ['In groups (sori) on the lower surface', 'Singly on the upper surface', 'Inside a sporocarp', 'On the stem'], 0,
    'This sorus-like grouping is one of the fern-like features of *Cycas*.'],
  ['Which is a fern-like character of *Cycas*?', ['Circinate vernation of young leaves', 'Pycnoxylic wood', 'Needle leaves on dwarf shoots', 'Non-motile male gametes'], 0,
    'Others: pinnate leaves, motile sperms and leaf-like megasporophylls.'],
  ['"Girdle traces" in the *Cycas* stem are:', ['Leaf traces that encircle the stem before entering the leaf base', 'Rings of resin canals', 'Anomalous cambial rings', 'Mucilage ducts'], 0,
    '*Cycas* wood is manoxylic and the leaflet bundles are diploxylic.'],
  ['Compared with Coniferales, Cycadales have:', ['Unbranched stems, pinnate leaves, manoxylic wood and motile sperms', 'Branched stems and needle leaves', 'Pycnoxylic wood and winged pollen', 'Non-motile gametes and resin canals in needles'], 0,
    'Conifers are branched, with simple leaves, compact wood and pollen-tube delivery of gametes.'],
  ['*Cycas beddomei*, an endemic Indian cycad, is found in:', ['The Seshachalam–Tirumala hills of Andhra Pradesh', 'The Andaman Islands', 'Kashmir', 'The Thar desert'], 0,
    '*Cycas* is the only native cycad genus in India; *C. circinalis* is in the Western Ghats.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 3, pyq: ['IFoS-2013-B1-m30', 'CSE-2012-B1-m18', 'CSE-1992-B1-m26', 'IFoS-2014-B1-m21', 'IFoS-2012-B1-m39', 'IFoS-2003-B1-m21', 'IFoS-2014-B1-m24', 'CSE-2024-B1-m21', 'CSE-2018-B1-m15', 'IFoS-2022-B1-m15', 'CSE-1989-B1-m24', 'CSE-1992-B1-m34'], q: [
  ['In *Pinus*, the dwarf (spur) shoot:', ['Has limited growth and bears the needles, with scale leaves at its base', 'Has unlimited growth and bears only needles', 'Bears the female cones only', 'Is underground'], 0,
    'Long shoots have unlimited growth and bear only scale leaves.'],
  ['Needles occur in clusters of five in:', ['*Pinus wallichiana* (blue pine)', '*Pinus roxburghii* (chir pine)', '*Pinus monophylla*', '*Pinus sylvestris*'], 0,
    'Chir pine has three needles, Scots pine two, *P. monophylla* one.'],
  ['A T.S. of a *Pinus* needle shows:', ['Sunken stomata, sclerenchymatous hypodermis, resin canals and plicate mesophyll', 'Large air spaces and no cuticle', 'Kranz anatomy', 'Palisade on both sides with vessels'], 0,
    'All xeromorphic features; a distinct endodermis surrounds transfusion tissue and one or two bundles.'],
  ['Transfusion tissue in the *Pinus* needle:', ['Surrounds the vascular bundles inside the endodermis and conducts laterally', 'Lies under the epidermis and stores water', 'Forms the resin canals', 'Is the photosynthetic tissue'], 0,
    'It is made of tracheids with bordered pits and parenchyma, compensating for the lack of lateral veins.'],
  ['The wood of *Pinus* is:', ['Pycnoxylic and without vessels, with tracheids, resin ducts and narrow rays', 'Manoxylic with vessels', 'Porous with vessels and fibres', 'Without growth rings'], 0,
    'Gymnosperm wood is non-porous "softwood".'],
  ['The pollen grain of *Pinus* is shed at the:', ['Four-celled stage — two prothallial cells, a generative cell and a tube cell — with two wings', 'Single-celled stage without wings', 'Three-celled stage with three pores', 'Two-celled stage without wings'], 0,
    'The air sacs aid wind dispersal.'],
  ['The female gametophyte of *Pinus*:', ['Begins with free-nuclear divisions and bears 2–5 archegonia at the micropylar end', 'Is formed after fertilisation', 'Has no archegonia', 'Is triploid'], 0,
    'It is haploid and later serves as the food store (endosperm) of the seed.'],
  ['In *Pinus*, fertilisation follows pollination after about:', ['One year', 'One day', 'One week', 'Five years'], 0,
    'Seeds mature in the second year, so a cone takes about two years to ripen.'],
  ['In *Pinus*, male gametes reach the egg:', ['Through a pollen tube, as non-motile gametes (siphonogamy)', 'By swimming in water', 'Through the stigma', 'Through insects'], 0,
    'This contrasts with the motile sperms of cycads and *Ginkgo*.'],
  ['In *Pinus*, the male cones occur:', ['In clusters at the base of the current year\'s long shoot', 'Singly at the stem apex', 'On the roots', 'Inside the female cone'], 0,
    'Each microsporophyll bears two microsporangia on its lower surface.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 3, pyq: ['IFoS-2010-B1-m30', 'CSE-1989-B1-m27', 'IFoS-2019-B1-m14', 'CSE-2019-B1-m19', 'IFoS-2014-B1-m22', 'IFoS-2021-B1-m18', 'IFoS-2016-B1-m13', 'CSE-2010-B1-m22', 'CSE-1994-B1-m25', 'CSE-1995-B1-m26', 'CSE-1996-B1-m21', 'IFoS-2011-B1-m23', 'IFoS-2002-B1-m19', 'CSE-2025-B1-m19', 'CSE-2017-B1-m14', 'CSE-1996-B1-m23', 'CSE-2010-B1-m23', 'CSE-1995-B1-m24', 'IFoS-2023-B1-m16', 'CSE-1985-B1-m24', 'CSE-2003-B1-m15', 'CSE-2023-B1-m06', 'IFoS-2024-B1-m03', 'IFoS-2015-B1-m01', 'CSE-2014-B1-m06', 'CSE-2009-B1-m11', 'CSE-1990-B1-m31'], q: [
  ['Which feature of *Gnetum* resembles angiosperms?', ['Vessels in the secondary xylem', 'Naked ovules', 'Haploid endosperm', 'Absence of fruit'], 0,
    'Others: broad net-veined leaves, perianth-like envelopes and no archegonia.'],
  ['Vessels of *Gnetum* are thought to have evolved independently of angiosperm vessels because they:', ['Arise from tracheids with circular bordered pits and have foraminate perforations', 'Have scalariform perforation plates like primitive angiosperms', 'Lack end walls', 'Are made of sieve cells'], 0,
    'Angiosperm vessels derive from scalariform-pitted tracheids; the resemblance is convergent.'],
  ['*Gnetum* remains a gymnosperm because:', ['Its ovules are not enclosed in an ovary', 'It has vessels', 'Its leaves are broad', 'It has male and female strobili'], 0,
    'No carpel, no true fruit, and nutritive tissue is mainly gametophytic.'],
  ['The female gametophyte of *Gnetum* at fertilisation:', ['Is tetrasporic and largely free-nuclear, without archegonia', 'Has 2–5 archegonia', 'Is cellular with a long-necked archegonium', 'Is seven-celled'], 0,
    'Free nuclei near the micropyle act as eggs; the lower part becomes cellular later.'],
  ['The ovule of *Gnetum* has:', ['Three envelopes, the inner one drawn out into a long micropylar tube', 'No integument', 'Two integuments and an ovary', 'An aril only'], 0,
    'The outer envelope becomes fleshy in the seed.'],
  ['On the male strobilus of *Gnetum*, each collar bears:', ['Rings of male flowers and, above them, a ring of sterile ovules', 'Only ovules', 'Sori of sporangia', 'Leafy sporophylls'], 0,
    'Each male flower has a perianth sheath and a stalk with two unilocular anthers.'],
  ['The order Gnetales includes:', ['*Gnetum*, *Ephedra* and *Welwitschia*', '*Ginkgo*, *Cycas* and *Pinus*', '*Taxus*, *Cedrus* and *Abies*', '*Cordaites*, *Pinus* and *Ephedra*'], 0,
    '*Welwitschia mirabilis* grows in the Namib desert with just two strap leaves.'],
  ['A "double fertilisation"-like event in which the second male nucleus fuses with the ventral canal nucleus was reported in:', ['*Ephedra*', '*Pinus*', '*Cycas*', '*Ginkgo*'], 0,
    'Its product does not form endosperm, unlike angiosperms.'],
  ['Indian species of *Gnetum*, such as *G. ula*, are:', ['Woody climbers of the Western Ghats and North-East', 'Desert shrubs of Rajasthan', 'Alpine trees of Ladakh', 'Mangroves'], 0,
    '*Ephedra* is the gnetalean of the dry inner Himalaya.'],
  ['Current molecular phylogenies place Gnetales:', ['Within or close to the conifers, not as the sister of angiosperms', 'Inside the angiosperms', 'With the ferns', 'With the cycads as their ancestors'], 0,
    'Their angiosperm-like features are therefore treated as convergent.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, pyq: ['IFoS-2022-B1-m15', 'CSE-2017-B1-m14', 'CSE-2010-B1-m23', 'CSE-2000-B1-m13', 'CSE-1996-B1-m23', 'CSE-1995-B1-m24', 'CSE-1994-B1-m27', 'CSE-1988-B1-m20', 'CSE-2010-B1-m21', 'IFoS-2025-B1-m04', 'CSE-1994-B1-m26', 'IFoS-2014-B1-m20', 'IFoS-2010-B1-m31', 'CSE-2012-B1-m21', 'CSE-1986-B1-m23', 'CSE-1992-B1-m09'], q: [
  ['The nutritive tissue (endosperm) of a gymnosperm seed is:', ['Haploid female gametophyte formed before fertilisation', 'Triploid, formed by double fertilisation', 'Diploid nucellus', 'Formed by the integument'], 0,
    'Angiosperm endosperm is usually triploid and forms after fertilisation.'],
  ['Archegonia are absent in the female gametophyte of:', ['*Gnetum* and *Welwitschia*', '*Pinus* and *Cycas*', '*Ephedra* and *Pinus*', '*Ginkgo* and *Cycas*'], 0,
    '*Ephedra* has archegonia with long necks.'],
  ['Gymnosperms are called "naked-seeded" because:', ['Their ovules are not enclosed in an ovary', 'Their seeds have no seed coat', 'They have no fruits or cones', 'Their seeds have no embryo'], 0,
    'Ovules sit exposed on megasporophylls or ovuliferous scales.'],
  ['The phloem of gymnosperms has:', ['Sieve cells with albuminous cells and no companion cells', 'Sieve tubes with companion cells', 'Vessels', 'No sieve elements'], 0,
    'Albuminous (Strasburger) cells do the job of companion cells.'],
  ['In most gymnosperms, water is conducted by:', ['Tracheids', 'Vessels', 'Sieve tubes', 'Fibres'], 0,
    'Gnetales are the exception with vessels.'],
  ['A key reproductive difference between gymnosperms and angiosperms is that angiosperms have:', ['Double fertilisation and triploid endosperm', 'Archegonia', 'Pollen chambers', 'Motile sperms'], 0,
    'Gymnosperms have single fertilisation.'],
  ['Reduction of the male gametophyte — from many prothallial cells to none — is seen in the order:', ['*Pinus* (two prothallial cells) → angiosperms (none)', 'Angiosperms → *Pinus*', '*Cycas* → ferns', 'Angiosperms → mosses'], 0,
    '*Cycas* has one prothallial cell; angiosperm pollen is 2- or 3-celled.'],
  ['Motile sperms (zoidiogamy) among living seed plants are found in:', ['Cycads and *Ginkgo*', '*Pinus* and *Cedrus*', '*Gnetum* and *Ephedra*', 'Angiosperms'], 0,
    'They are released from a haustorial pollen tube near the archegonia.'],
  ['In gymnosperms, pollen lands on the:', ['Micropyle of the ovule, often trapped by a pollination drop', 'Stigma', 'Style', 'Ovary wall'], 0,
    'Angiosperms receive pollen on the stigma of a closed carpel.'],
  ['Which supports gymnosperms as ancestral to angiosperms?', ['Both are seed plants with secondary growth, and some fossil seed plants had cupules like carpels', 'Gymnosperms have triploid endosperm', 'Both have motile sperms', 'Both lack seeds'], 0,
    'Caytoniales, Bennettitales and Gnetales have each been proposed — none conclusively.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, pyq: ['CSE-2024-B1-m20', 'CSE-2020-B1-m17', 'CSE-2012-B1-m20', 'CSE-2010-B1-m21', 'IFoS-2001-B1-m18', 'CSE-1986-B1-m19'], q: [
  ['*Ginkgo biloba* is called a living fossil because:', ['It is the sole survivor of an ancient group and has changed little since the Mesozoic', 'It has no living relatives in any group', 'It reproduces only by spores', 'It is found only as fossils'], 0,
    'Ginkgoales go back to the Permian and were diverse in the Jurassic.'],
  ['Leaves of *Ginkgo* are:', ['Fan-shaped with dichotomous venation', 'Needle-like in clusters', 'Pinnately compound', 'Scale-like and whorled'], 0,
    'Hence "maidenhair tree".'],
  ['Motile sperms in *Ginkgo* were discovered by:', ['Hirase (1896)', 'Hofmeister (1851)', 'Nawaschin (1898)', 'Strasburger (1884)'], 0,
    'Ikeno found them in *Cycas* the same year.'],
  ['*Ginkgo* is:', ['Dioecious, with ovules borne in pairs on long stalks', 'Monoecious, with compound cones', 'Bisexual, with flowers', 'Without seeds'], 0,
    'Each ovule sits on a collar at the end of the stalk.'],
  ['The foul smell of fallen *Ginkgo* seeds comes from the:', ['Fleshy outer seed coat (sarcotesta), rich in butyric acid', 'Embryo', 'Leaves', 'Pollen'], 0,
    'Gardeners prefer male trees for this reason.'],
  ['*Ginkgo* is native to:', ['China', 'India', 'Brazil', 'South Africa'], 0,
    'Long kept in temple gardens; it survives pollution well.'],
  ['*Psilotum* is regarded as a living fossil because it:', ['Is rootless, nearly leafless, dichotomous and has synangia like early vascular plants', 'Has seeds', 'Has flowers', 'Lacks vascular tissue'], 0,
    'Molecular data now place it near *Ophioglossum*, so its resemblance to *Rhynia* may be reduction.'],
  ['A conifer known from fossils before being found alive in China in the 1940s is:', ['*Metasequoia glyptostroboides*', '*Pinus roxburghii*', '*Cedrus deodara*', '*Taxus baccata*'], 0,
    'The Wollemi pine (*Wollemia*) was found alive in Australia in 1994.'],
  ['*Ginkgo* leaf extract is used mainly for its:', ['Flavonoids and ginkgolides', 'Ephedrine', 'Taxol', 'Quinine'], 0,
    'It is marketed for memory and circulation.'],
  ['In *Ginkgo*, the embryo may develop after the ovule has fallen because:', ['Fertilisation can happen late, around the time ovules are shed', 'It has no embryo', 'Seeds are dormant for years', 'It is apomictic'], 0,
    'Seeds have little or no dormancy.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, pyq: ['IFoS-2023-B1-m15', 'CSE-2021-B1-m20', 'CSE-2018-B1-m17', 'CSE-2004-B1-m14', 'IFoS-2014-B1-m23', 'CSE-2021-B1-m19', 'CSE-2015-B1-m17', 'IFoS-2022-B1-m14', 'CSE-2009-B1-m21', 'CSE-2018-B1-m16', 'CSE-2014-B1-m19', 'IFoS-2004-B1-m20', 'CSE-2024-B1-m19', 'CSE-2023-B1-m03', 'CSE-2002-B1-m05', 'CSE-1988-B1-m05', 'IFoS-2007-B1-m02', 'IFoS-2000-B1-m04', 'IFoS-2011-B1-m03', 'IFoS-2021-B1-m15', 'IFoS-2000-B1-m17', 'CSE-2010-B1-m18', 'IFoS-2007-B1-m12', 'IFoS-2015-B1-Q4a'], q: [
  ['Cordaitales were:', ['Tall Carboniferous trees with long, strap-shaped, parallel-veined leaves', 'Small herbs of the Cenozoic', 'Mesozoic cycads', 'Aquatic ferns'], 0,
    'Their pith had transverse septa — casts called *Artisia*.'],
  ['The fertile shoots of Cordaitales (*Cordaianthus*) are:', ['Compound strobili with bracts subtending short shoots that bear scales and ovules or pollen sacs', 'Simple cones of sporophylls', 'Flowers with petals', 'Sporocarps'], 0,
    'This compound structure is homologous to the conifer seed cone.'],
  ['Cordaitales are thought to be closest to:', ['Conifers', 'Cycads', 'Ferns', 'Angiosperms'], 0,
    'Pycnoxylic wood and compound cones link them with Coniferales.'],
  ['Progymnosperms, such as *Archaeopteris* and *Aneurophyton*, lived in the:', ['Devonian', 'Cretaceous', 'Quaternary', 'Jurassic'], 0,
    'They had gymnosperm wood but reproduced by spores.'],
  ['A feature separating Bennettitales from Cycadales is:', ['Often bisexual strobili with interseminal scales', 'Pinnate leaves', 'Manoxylic wood', 'Cycad-like habit'], 0,
    'They resemble cycads in habit, leaves and wood but differ in stomata (syndetocheilic) and fructification.'],
  ['The strobilus of *Cycadeoidea* had:', ['Outer bracts, a whorl of pinnate microsporophylls and a central receptacle with stalked ovules', 'Only ovules on an open leaf', 'Sori on the leaf underside', 'Only pollen sacs'], 0,
    'This flower-like structure suggested an angiosperm link.'],
  ['The Indian member of Bennettitales described from the Rajmahal Hills is:', ['*Williamsonia sewardiana*', '*Cycadeoidea dacotensis*', '*Cordaites*', '*Lyginopteris*'], 0,
    'Rajmahal (Jharkhand) is a key Jurassic plant-fossil site.'],
  ['The Permian *Glossopteris* flora is evidence for:', ['Gondwanaland — a once-joined southern supercontinent', 'An ice-free Antarctica today', 'Origin of angiosperms', 'Marine algae'], 0,
    'Glossopterids are seed plants with tongue-shaped leaves.'],
  ['Cordaitales are important because they:', ['Formed much of the Carboniferous coal and link early seed plants with conifers', 'Are the ancestors of mosses', 'Are living plants of India', 'Have flowers'], 0,
    'They dominated drier Carboniferous forests.'],
  ['Progymnosperms are significant because they show:', ['That gymnosperm-type wood evolved before the seed', 'That flowers evolved before seeds', 'That mosses gave rise to ferns', 'That seeds evolved in algae'], 0,
    'Beck (1960) named the group.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, pyq: ['CSE-2014-B1-m18', 'IFoS-2020-B1-m17', 'CSE-1989-B1-m26', 'CSE-2023-B1-m19', 'CSE-2006-B1-m22', 'CSE-1989-B1-m37', 'CSE-2026-B1-m04'], q: [
  ['A petrifaction forms when:', ['Minerals such as silica or calcite infiltrate and replace tissues, preserving internal anatomy', 'A plant leaves only an imprint in mud', 'A plant is preserved in ice', 'Carbon film is left after compression'], 0,
    'Petrifactions let botanists section fossils like living tissue.'],
  ['An impression fossil preserves:', ['Only the surface outline, without plant matter', 'Internal cells', 'The whole 3-D organ in silica', 'DNA'], 0,
    'A compression keeps a carbon film; a cast fills a mould.'],
  ['Coal balls are:', ['Calcareous petrifactions found in Carboniferous coal seams', 'Compressed peat', 'Amber nodules', 'Spore masses'], 0,
    'They preserve coal-swamp plants in cellular detail.'],
  ['Petrifactions are commonly studied by the:', ['Peel technique using acid etching and cellulose acetate', 'Herbarium method', 'Gram stain', 'Flotation method'], 0,
    'Successive peels give serial sections.'],
  ['Radiocarbon (¹⁴C) dating is useful for materials up to about:', ['50,000 years old', '5 million years old', '500 million years old', '50 years old'], 0,
    '¹⁴C half-life is about 5,730 years; older rocks need K–Ar or U–Pb.'],
  ['The epochs of the Cenozoic, oldest to youngest, begin:', ['Palaeocene, Eocene, Oligocene, Miocene, Pliocene', 'Eocene, Palaeocene, Miocene, Oligocene', 'Pliocene, Miocene, Oligocene, Eocene', 'Holocene, Pleistocene, Pliocene'], 0,
    'Then Pleistocene and Holocene.'],
  ['The Carboniferous is called the age of:', ['Pteridophytes — coal-forming lycopod and horsetail forests', 'Angiosperms', 'Mammals', 'Algae'], 0,
    '*Lepidodendron* and *Calamites* were tree-sized.'],
  ['Fossil "form genera" are used because:', ['Organs of one plant are often found separately and named separately', 'Fossils have no names', 'All fossils are one species', 'Fossils cannot be classified'], 0,
    'E.g. *Lepidodendron* (stem), *Stigmaria* (rhizophore), *Lepidostrobus* (cone).'],
  ['The correct order of eras is:', ['Palaeozoic → Mesozoic → Cenozoic', 'Mesozoic → Palaeozoic → Cenozoic', 'Cenozoic → Mesozoic → Palaeozoic', 'Palaeozoic → Cenozoic → Mesozoic'], 0,
    'Palaeozoic flora was pteridophytic; Mesozoic gymnospermous; Cenozoic angiospermous.'],
  ['Petrified fossils are called "marvels" of palaeobotany because they:', ['Preserve cell-level anatomy of extinct plants', 'Show colour of flowers', 'Contain living cells', 'Are always complete plants'], 0,
    'The Rhynie Chert preserves even fungal hyphae inside cells.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, pyq: ['CSE-2021-B1-m18', 'CSE-2017-B1-m15', 'CSE-2015-B1-m18', 'IFoS-2004-B1-m20', 'IFoS-2022-B1-m16', 'CSE-1991-B1-m24', 'CSE-2013-B1-m12', 'CSE-1990-B1-m15', 'CSE-2006-B1-m10'], q: [
  ['Most of India\'s native conifers grow in the:', ['Himalaya', 'Indo-Gangetic plain', 'Thar desert', 'Deccan plateau'], 0,
    'The North-East and Western Ghats hold *Gnetum*, *Podocarpus* and cycads.'],
  ['A conifer of the subtropical Himalaya, tapped for resin and turpentine, is:', ['*Pinus roxburghii*', '*Abies pindrow*', '*Taxus wallichiana*', '*Cedrus deodara*'], 0,
    'Chir pine grows at about 500–2,000 m.'],
  ['*Ephedra* in India grows mainly in:', ['The dry inner Himalaya, such as Ladakh and Lahaul–Spiti', 'Mangroves of the Sundarbans', 'Wet forests of Kerala', 'Andaman Islands'], 0,
    'It is the source of ephedrine.'],
  ['The anticancer drug taxol (paclitaxel) comes from:', ['*Taxus* (yew)', '*Cedrus*', '*Pinus*', '*Ginkgo*'], 0,
    '*Taxus wallichiana* is threatened by over-harvesting of its bark.'],
  ['Edible "chilgoza" nuts are the seeds of:', ['*Pinus gerardiana*', '*Pinus wallichiana*', '*Cycas revoluta*', '*Araucaria*'], 0,
    'It grows in Kinnaur and the north-west Himalaya.'],
  ['Chamberlain divided gymnosperms into:', ['Cycadophyta and Coniferophyta', 'Bryophyta and Pteridophyta', 'Monocots and dicots', 'Gnetopsida and Ginkgopsida only'], 0,
    'Cycadophyta: manoxylic wood, pinnate leaves; Coniferophyta: pycnoxylic wood, simple leaves.'],
  ['The yew (*Taxus*) differs from most conifers in that its seed is:', ['Single, surrounded by a red fleshy aril, not in a woody cone', 'Winged', 'Inside a closed ovary', 'Produced in a sporocarp'], 0,
    'Taxales are sometimes kept as a separate order.'],
  ['The timber tree *Cedrus deodara* belongs to:', ['Pinaceae', 'Cycadaceae', 'Gnetaceae', 'Taxaceae'], 0,
    'Deodar grows in the western Himalaya at about 1,500–3,000 m.'],
  ['The "monkey puzzle" and "Norfolk Island pine" grown as ornamentals belong to:', ['*Araucaria*', '*Pinus*', '*Cupressus*', '*Thuja*'], 0,
    'Araucariaceae are mainly southern-hemisphere conifers.'],
  ['The gymnosperm group most important economically for timber, pulp and resin is:', ['Conifers', 'Cycads', 'Gnetales', 'Ginkgo'], 0,
    'Pines, firs and spruces supply softwood worldwide.']
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, pyq: ['IFoS-2025-B1-m05', 'IFoS-2003-B1-m21', 'CSE-1994-B1-m26', 'IFoS-2005-B1-m23', 'IFoS-2013-B1-m06', 'CSE-2005-B1-m04'], q: [
  ['Manoxylic wood, as in *Cycas*, is:', ['Loose and soft, with much parenchyma and broad rays', 'Compact with narrow rays', 'Porous with vessels', 'Made only of fibres'], 0,
    'Pycnoxylic wood (*Pinus*) is compact, with little parenchyma and narrow rays.'],
  ['In a radial longitudinal section of *Pinus* wood, one sees:', ['Bordered pits on tracheid walls and rays running across as bands', 'Rays as spindle-shaped groups', 'Vessels with perforation plates', 'Annual rings as circles'], 0,
    'RLS shows ray height and the two kinds of ray cells.'],
  ['In a tangential longitudinal section of *Pinus* wood, rays appear as:', ['Spindle-shaped groups, uniseriate or fusiform with resin ducts', 'Long horizontal bands', 'Concentric rings', 'Absent'], 0,
    'TLS cuts rays end-on, showing their width and height.'],
  ['Pits typical of conifer tracheids have:', ['A torus and margo', 'Simple perforations', 'Scalariform plates', 'Sieve plates'], 0,
    'The torus can seal the pit when one side is air-filled.'],
  ['Older stems of *Cycas* may show:', ['Several successive rings of vascular tissue (polyxylic)', 'No secondary growth', 'Vessels', 'Bicollateral bundles'], 0,
    'Extra cambia form outside the first ring.'],
  ['Resin ducts in *Pinus* are:', ['Lined by an epithelium of secretory cells', 'Dead tracheids', 'Air spaces with no lining', 'Sieve cells'], 0,
    'Wounding can produce extra (traumatic) ducts.'],
  ['The wood of *Gnetum* is unusual among gymnosperms because it has:', ['Vessels, and in some species successive cambia', 'No tracheids', 'No rays', 'Sieve tubes in the xylem'], 0,
    '*G. ula* stems show several rings of vascular tissue.'],
  ['Early wood differs from late wood in having:', ['Wider, thinner-walled tracheids', 'Narrow, thick-walled tracheids', 'Vessels', 'No cells'], 0,
    'The sharp change at the end of late wood marks an annual ring.'],
  ['Gymnosperm wood is called "softwood" because it is:', ['Non-porous, lacking vessels', 'Always physically soft', 'Without lignin', 'Rich in fibres'], 0,
    'Dicot "hardwood" is porous with vessels; balsa is a soft hardwood.'],
  ['Ray tracheids and ray parenchyma together form the:', ['Heterogeneous rays of *Pinus*', 'Phloem of *Cycas*', 'Cortex of *Gnetum*', 'Pith of *Ginkgo*'], 0,
    'Ray tracheids have bordered pits; *Pinus* ray tracheids are dentate.']
] }
);
