/* Concept sets for Botany I — Algae. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Algae', w: 3, pyq: ['CSE-2025-B1-m01', 'IFoS-2012-B1-m01', 'IFoS-2001-B1-m01', 'IFoS-2016-B1-m01', 'IFoS-2010-B1-m01', 'IFoS-2005-B1-m01', 'IFoS-2021-B1-m01', 'IFoS-2020-B1-m02', 'CSE-2002-B1-m01'], q: [
  ['A heterocyst is:', ['A thick-walled, pale cell specialised for nitrogen fixation', 'A resting spore rich in food', 'A motile reproductive cell', 'A dead separation disc'], 0,
    'Akinetes are the food-rich resting spores; separation discs break filaments into hormogonia.'],
  ['Heterocysts do not evolve oxygen because they lack:', ['Photosystem II', 'Photosystem I', 'Ribosomes', 'A cell wall'], 0,
    'PSI still makes ATP; nitrogenase is destroyed by oxygen.'],
  ['The polar nodules of a heterocyst are:', ['Cyanophycin plugs at the pores joining neighbouring cells', 'Gas vesicles', 'Carboxysomes', 'Nuclei'], 0,
    'Fixed nitrogen passes to vegetative cells; sugars come back.'],
  ['The extra wall layers of a heterocyst — polysaccharide outside, glycolipid inside — serve to:', ['Limit oxygen entry', 'Store phosphate', 'Aid motility', 'Absorb light'], 0,
    'High respiration inside also uses up oxygen.'],
  ['Heterocyst formation is triggered mainly by:', ['Shortage of combined nitrogen', 'Excess nitrate', 'High phosphate', 'Darkness alone'], 0,
    'The HetR regulator promotes it and the PatS peptide spaces heterocysts along the filament.'],
  ['Compared with a vegetative cell, an akinete is:', ['Larger, thick-walled and food-filled, for surviving bad seasons', 'Smaller and without food', 'The site of nitrogen fixation', 'Motile'], 0,
    'Akinetes germinate into new filaments when conditions improve.'],
  ['Terminal (basal) heterocysts are typical of:', ['*Cylindrospermum*', '*Anabaena*', '*Nostoc*', '*Oscillatoria*'], 0,
    '*Anabaena* and *Nostoc* have intercalary heterocysts; *Oscillatoria* has none.'],
  ['A cyanobacterial cell has:', ['Thylakoids free in the cytoplasm with phycobilisomes, and a peptidoglycan wall', 'Chloroplasts with grana', 'A nucleus with a membrane', 'Mitochondria'], 0,
    'It is prokaryotic with 70S ribosomes.'],
  ['Food reserves of blue-green algae are:', ['Cyanophycean starch and cyanophycin granules', 'True starch in pyrenoids', 'Laminarin and mannitol', 'Paramylon'], 0,
    'Cyanophycean starch is glycogen-like.'],
  ['Besides nitrogen fixation, heterocysts can act as:', ['Points where filaments break into hormogonia', 'Male gametes', 'Gas vacuoles', 'Photosynthetic centres'], 0,
    'Occasionally they even germinate.']
] },
{ p: 'B1', t: 'Algae', w: 3, pyq: ['CSE-2025-B1-m02', 'IFoS-2024-B1-m04', 'CSE-2012-B1-m01', 'CSE-2009-B1-m04', 'CSE-2005-B1-m02', 'CSE-2020-B1-m01', 'CSE-2001-B1-m03', 'IFoS-2009-B1-m01', 'CSE-2015-B1-m02', 'CSE-2019-B1-m01', 'IFoS-2012-B1-m02', 'CSE-1996-B1-m32', 'CSE-1985-B1-m20'], q: [
  ['Match the thallus type with its example: coenobium —', ['*Volvox*', '*Spirogyra*', '*Vaucheria*', '*Ulva*'], 0,
    'A coenobium is a colony with a fixed number of cells.'],
  ['A palmelloid thallus, as in *Tetraspora*, consists of:', ['Non-motile cells embedded in mucilage', 'A branched filament', 'A multinucleate tube', 'A two-layered sheet'], 0,
    '*Chlamydomonas* can also pass through a palmella stage.'],
  ['A siphonous (coenocytic) thallus is found in:', ['*Vaucheria* and *Caulerpa*', '*Ulothrix* and *Spirogyra*', '*Ulva* and *Laminaria*', '*Volvox* and *Pandorina*'], 0,
    'It is a single multinucleate tube without cross-walls.'],
  ['A heterotrichous thallus has:', ['A prostrate creeping system and an erect branched system', 'Only an unbranched filament', 'A single cell', 'A hollow sphere'], 0,
    'E.g. *Stigeoclonium*, *Fritschiella*, *Coleochaete*, *Ectocarpus*.'],
  ['*Fritschiella tuberosa* is important because:', ['It is a terrestrial heterotrichous alga that suggests how land plants arose', 'It is a red alga', 'It is a source of agar', 'It forms red tides'], 0,
    'It has rhizoids, a prostrate system and erect branches on soil.'],
  ['The Volvocales series showing increasing cell number and division of labour is:', ['*Chlamydomonas* → *Gonium* → *Pandorina* → *Eudorina* → *Volvox*', '*Volvox* → *Chlamydomonas* → *Gonium*', '*Spirogyra* → *Ulothrix* → *Volvox*', '*Ulva* → *Volvox* → *Chlamydomonas*'], 0,
    'Sex also moves from isogamy to oogamy along this series.'],
  ['Brown algae differ from green algae in thallus range because brown algae:', ['Are never unicellular and reach complex parenchymatous thalli', 'Are mostly unicellular', 'Never form filaments', 'Lack holdfasts'], 0,
    '*Laminaria* has holdfast, stipe and blade; green algae range from single cells to sheets.'],
  ['"Red snow" on mountains is caused by:', ['*Chlamydomonas nivalis*', '*Volvox*', '*Ulva*', '*Polysiphonia*'], 0,
    'A cryophytic alga coloured by carotenoids.'],
  ['The orange subaerial alga on tree bark and walls is:', ['*Trentepohlia*', '*Spirogyra*', '*Chara*', '*Sargassum*'], 0,
    'Its colour comes from haematochrome.'],
  ['The thallus of *Ulva* is:', ['A parenchymatous sheet two cells thick', 'A branched filament', 'A coenocytic tube', 'A colony of eight cells'], 0,
    'Hence "sea lettuce".']
] },
{ p: 'B1', t: 'Algae', w: 3, pyq: ['CSE-2013-B1-m01', 'IFoS-2003-B1-m01', 'CSE-1994-B1-m02', 'CSE-1992-B1-m03', 'CSE-1986-B1-m02', 'CSE-2021-B1-m03', 'IFoS-2021-B1-m02', 'CSE-2017-B1-m01', 'CSE-1990-B1-m01', 'CSE-2014-B1-m03', 'CSE-2020-B1-m02', 'CSE-1995-B1-m14', 'IFoS-2006-B1-m09', 'IFoS-2005-B1-m22', 'IFoS-2003-B1-m19', 'CSE-2000-B1-m17', 'CSE-1988-B1-m23', 'CSE-1993-B1-m30', 'CSE-1986-B1-m24', 'CSE-1998-B1-m20', 'CSE-1999-B1-m16'], q: [
  ['In a haplontic life cycle, the only diploid stage is the:', ['Zygote', 'Thallus', 'Gamete', 'Spore'], 0,
    'Meiosis is zygotic — e.g. *Chlamydomonas*, *Spirogyra*, *Ulothrix*.'],
  ['A diplontic life cycle with gametic meiosis is found in:', ['*Fucus*', '*Spirogyra*', '*Ulothrix*', '*Polysiphonia*'], 0,
    'Only the gametes are haploid, as in diatoms and animals.'],
  ['Isomorphic alternation of generations is shown by:', ['*Ulva* and *Ectocarpus*', '*Laminaria* and ferns', '*Fucus* and diatoms', '*Spirogyra* and *Chara*'], 0,
    'The two free-living phases look alike.'],
  ['*Laminaria* shows a heteromorphic life cycle with:', ['A large sporophyte and microscopic gametophytes', 'A large gametophyte and microscopic sporophyte', 'No gametophyte', 'Identical phases'], 0,
    'Kelps are the dominant diploid phase.'],
  ['The triphasic life cycle of *Polysiphonia* has:', ['Haploid gametophytes, a diploid carposporophyte and a diploid tetrasporophyte', 'Only a haploid and a diploid phase', 'Three haploid phases', 'Diploid gametophytes'], 0,
    'The carposporophyte lives on the female gametophyte.'],
  ['Tetraspores of *Polysiphonia* are:', ['Haploid, formed by meiosis, and grow into male and female gametophytes', 'Diploid and grow into carposporophytes', 'Male gametes', 'Formed by mitosis on the gametophyte'], 0,
    'Tetrasporangia form on the free-living tetrasporophyte.'],
  ['In *Polysiphonia*, after a spermatium fertilises the carpogonium, the diploid nucleus passes to the:', ['Auxiliary cell, which gives rise to gonimoblast filaments and carposporangia', 'Trichogyne, which forms tetraspores', 'Pericarp, which forms spermatia', 'Pit connection, which forms a zygote'], 0,
    'The pericarp and gonimoblasts together make the cystocarp.'],
  ['In *Ectocarpus*, unilocular sporangia on the sporophyte produce:', ['Haploid zoospores after meiosis', 'Diploid zoospores by mitosis', 'Gametes directly', 'Carpospores'], 0,
    'Plurilocular sporangia make diploid zoospores (or gametes on the gametophyte) by mitosis.'],
  ['Conceptacles of *Fucus* are:', ['Flask-shaped cavities in the receptacles that bear sex organs', 'Air bladders', 'Holdfasts', 'Spore sacs on the stipe'], 0,
    'They open by an ostiole.'],
  ['*Saprolegnia* and *Vaucheria* resemble each other in being coenocytic and oogamous, but differ in that:', ['*Vaucheria* is photosynthetic while *Saprolegnia* is a heterotrophic oomycete', 'Both are photosynthetic', '*Saprolegnia* is a red alga', '*Vaucheria* lacks oogonia'], 0,
    '*Vaucheria* is a xanthophyte; similar form arose independently.']
] },
{ p: 'B1', t: 'Algae', w: 3, pyq: ['IFoS-2023-B1-m01', 'IFoS-2006-B1-m01', 'IFoS-2003-B1-m02', 'IFoS-2000-B1-m01', 'CSE-1988-B1-m01', 'CSE-2022-B1-m02', 'CSE-2007-B1-m01', 'CSE-2005-B1-m01', 'IFoS-2004-B1-m04', 'IFoS-2009-B1-m02', 'IFoS-2005-B1-m02', 'CSE-2015-B1-m01', 'IFoS-2002-B1-m01', 'IFoS-2013-B1-m01', 'IFoS-2022-B1-m01', 'IFoS-2023-B1-m02', 'CSE-2024-B1-m01', 'IFoS-2020-B1-m01', 'CSE-2004-B1-m16', 'IFoS-2003-B1-m24'], q: [
  ['Agar is extracted mainly from:', ['Red algae such as *Gelidium* and *Gracilaria*', 'Brown algae such as *Laminaria*', 'Green algae such as *Ulva*', 'Diatoms'], 0,
    'Agar is used in culture media and food.'],
  ['Alginates come from:', ['Brown algae such as *Laminaria*, *Macrocystis* and *Sargassum*', 'Red algae', 'Cyanobacteria', 'Diatoms'], 0,
    'Used as thickeners and in dental impressions.'],
  ['The red seaweed farmed on India\'s Tamil Nadu coast for carrageenan is:', ['*Kappaphycus alvarezii*', '*Porphyra*', '*Ulva*', '*Chlorella*'], 0,
    'Carrageenan is also obtained from *Chondrus crispus*.'],
  ['Diatomaceous earth is made of:', ['Silica frustules of diatoms', 'Calcium carbonate of *Chara*', 'Dead kelp', 'Cyanobacterial sheaths'], 0,
    'Used in filtration, insulation, polishes and as an absorbent.'],
  ['*Spirulina* is valued as food because it is:', ['Rich in protein (about 60% of dry weight) and vitamins', 'A source of agar', 'Rich in alginates', 'Poisonous'], 0,
    '*Chlorella* is another single-cell protein; *Porphyra* (nori) is eaten in Japan.'],
  ['A microalga that makes large amounts of hydrocarbons, studied for fuel, is:', ['*Botryococcus braunii*', '*Gelidium*', '*Chara*', '*Volvox*'], 0,
    'Oil-rich microalgae are candidates for biodiesel.'],
  ['Blue-green algae used as biofertilizer in rice fields include:', ['*Nostoc*, *Anabaena*, *Tolypothrix* and *Aulosira*', '*Gelidium* and *Gracilaria*', '*Fucus* and *Sargassum*', '*Chlamydomonas* and *Volvox*'], 0,
    'They can add roughly 20–30 kg N/ha per season.'],
  ['Toxic blooms in nutrient-rich fresh water are often formed by:', ['*Microcystis*', '*Chara*', '*Ulva*', '*Gelidium*'], 0,
    'Marine "red tides" are caused by dinoflagellates and can cause shellfish poisoning.'],
  ['In sewage oxidation ponds, algae help mainly by:', ['Releasing oxygen used by bacteria that break down waste', 'Killing all bacteria', 'Producing agar', 'Fixing carbon monoxide'], 0,
    '*Chlorella* and *Scenedesmus* are common in such ponds.'],
  ['Algae such as *Euglena* and *Oscillatoria* abundant in a water body indicate:', ['Organic pollution', 'Very clean water', 'Low temperature', 'High salinity only'], 0,
    'Palmer\'s index uses such genera to rate organic pollution.']
] },
{ p: 'B1', t: 'Algae', w: 2, pyq: ['CSE-2021-B1-m01', 'IFoS-2007-B1-m01', 'CSE-1994-B1-m03', 'IFoS-2013-B1-m02', 'CSE-1989-B1-m02', 'CSE-1986-B1-m01', 'CSE-1997-B1-m01'], q: [
  ['Species of *Chlamydomonas* show the series:', ['Isogamy → anisogamy → oogamy', 'Oogamy → isogamy → anisogamy', 'Only isogamy', 'Only oogamy'], 0,
    '*C. reinhardtii* isogamous, *C. braunii* anisogamous, *C. coccifera* oogamous.'],
  ['Oogamy is fusion of:', ['A large non-motile egg with a small motile male gamete', 'Two identical motile gametes', 'Two non-motile gametes of equal size', 'Two motile gametes of unequal size'], 0,
    'The last option describes anisogamy.'],
  ['Physiological anisogamy means gametes are:', ['Alike in form but differ in behaviour (+ and − strains)', 'Unequal in size', 'Non-motile', 'Produced by meiosis in the zygote'], 0,
    'It is seen in isogamous species with mating types.'],
  ['Gametes in algae are thought to have evolved from:', ['Zoospores', 'Akinetes', 'Heterocysts', 'Holdfast cells'], 0,
    'In some algae, zoospores can behave as gametes.'],
  ['*Oedogonium* is:', ['Oogamous, with a ring of flagella on zoospores and antherozoids', 'Isogamous', 'Without sexual reproduction', 'Coenocytic'], 0,
    'Stephanokont flagellation is a hallmark of Oedogoniales.'],
  ['Nannandrous species of *Oedogonium* have:', ['Dwarf males that grow from androspores on or near the oogonium', 'Male and female organs on the same normal filament', 'No males', 'Only zoospores'], 0,
    'Macrandrous species have normal-sized male filaments.'],
  ['"Cap cells" in *Oedogonium* result from:', ['Its peculiar ring-type cell division', 'Spore formation', 'Fertilisation', 'Heterocyst formation'], 0,
    'Each division leaves a ring scar; many caps mark repeated division.'],
  ['Asexual reproduction in *Chlamydomonas* is mainly by:', ['Zoospores formed inside the parent cell', 'Fragmentation', 'Conidia', 'Tetraspores'], 0,
    'Under stress it forms a palmella stage or aplanospores.'],
  ['*Volvox* is regarded as the peak of the Volvocales series because it:', ['Has division of labour between somatic and reproductive cells and is oogamous', 'Is unicellular', 'Is isogamous', 'Has no chloroplasts'], 0,
    'It is a hollow coenobium of hundreds to thousands of cells.'],
  ['Sex chromosomes (X and Y) were first found in plants in the liverwort:', ['*Sphaerocarpos*', '*Riccia*', '*Funaria*', '*Chara*'], 0,
    'Allen (1917) found them in this dioecious liverwort.']
] },
{ p: 'B1', t: 'Algae', w: 2, pyq: ['CSE-2014-B1-m01', 'CSE-2011-B1-m01', 'CSE-1995-B1-m01', 'CSE-2003-B1-m02', 'CSE-1991-B1-m02'], q: [
  ['In *Chara*, the sex organs at a node are arranged with:', ['The nucule (oogonium) above and the globule (antheridium) below', 'The globule above and nucule below', 'Both side by side on internodes', 'Only nucules on one plant and globules on another always'], 0,
    'Most species are monoecious.'],
  ['The nucule of *Chara* is enclosed by:', ['Five spirally twisted tube cells topped by a corona of five cells', 'Eight shield cells', 'A single cap cell', 'A gelatinous sheath'], 0,
    '*Nitella* has a corona of ten cells in two tiers.'],
  ['The globule of *Chara* has:', ['Eight shield cells, manubria, capitula and antheridial filaments', 'Five tube cells and a corona', 'A trichogyne', 'Sporangia'], 0,
    'Each filament cell makes one biflagellate antherozoid.'],
  ['*Chara* is unique among algae because it has:', ['Nodes and internodes and sex organs with a sterile jacket', 'A unicellular thallus', 'No sexual reproduction', 'Heterocysts'], 0,
    'This complexity makes it look like a higher plant.'],
  ['*Chara* is called a "stonewort" because:', ['Its thallus is encrusted with calcium carbonate', 'It grows on rocks', 'It forms silica frustules', 'Its spores are hard'], 0,
    'It grows in hard fresh water.'],
  ['Charophytes are important in evolution because they:', ['Are the closest algal relatives of land plants', 'Are ancestors of fungi', 'Are cyanobacteria', 'Gave rise to red algae'], 0,
    'Along with *Coleochaete* and Zygnematales.'],
  ['The life cycle of *Chara* is:', ['Haplontic, with meiosis when the zygote germinates', 'Diplontic', 'Isomorphic', 'Triphasic'], 0,
    'The zygote (oospore) is the only diploid cell.'],
  ['Vegetative reproduction in *Chara* is by:', ['Bulbils, amylum stars and secondary protonema', 'Conidia', 'Gemmae cups', 'Tetraspores'], 0,
    'Amylum stars are star-shaped starch-filled nodes.'],
  ['*Nitella* differs from *Chara* in:', ['Lacking cortication and having a ten-celled corona', 'Having heterocysts', 'Being marine', 'Having no nodes'], 0,
    'Both are in Charales.'],
  ['The protonema of *Chara* is:', ['A filament from the germinating oospore that gives rise to the plant', 'A male gamete', 'A sporangium', 'An air bladder'], 0,
    'This parallels the moss protonema.']
] },
{ p: 'B1', t: 'Algae', w: 2, pyq: ['CSE-2003-B1-m01', 'IFoS-2004-B1-m03', 'CSE-2016-B1-m01', 'CSE-2022-B1-m01', 'IFoS-2014-B1-m02', 'IFoS-2003-B1-m22', 'CSE-1999-B1-m03'], q: [
  ['Fritsch (1935) classified algae into eleven classes mainly on the basis of:', ['Pigments, reserve food and flagellation', 'Habitat only', 'Size', 'Mode of nutrition'], 0,
    'E.g. Chlorophyceae: chl a and b, starch, equal flagella.'],
  ['A tinsel flagellum differs from a whiplash flagellum in having:', ['Fine lateral hairs (mastigonemes)', 'No axoneme', 'A 9+0 arrangement', 'No membrane'], 0,
    'Both have the 9+2 axoneme.'],
  ['Zoospores of brown algae have:', ['Two unequal, laterally inserted flagella — one tinsel, one whiplash', 'A ring of flagella', 'No flagella', 'Two equal apical whiplash flagella'], 0,
    'This heterokont pattern marks the Stramenopiles.'],
  ['Match chloroplast shape with genus: spiral ribbon —', ['*Spirogyra*', '*Chlamydomonas*', '*Ulothrix*', '*Zygnema*'], 0,
    'Cup: *Chlamydomonas*; girdle: *Ulothrix*; stellate: *Zygnema*; reticulate: *Oedogonium*.'],
  ['A green-algal chloroplast typically contains:', ['Chlorophylls a and b and pyrenoids surrounded by starch', 'Phycobilisomes and floridean starch', 'Fucoxanthin and laminarin', 'Chlorophyll a only'], 0,
    'This matches land plants and supports their green-algal origin.'],
  ['The eyespot (stigma) of *Chlamydomonas* functions in:', ['Light perception for phototaxis', 'Storage of starch', 'Excretion', 'Nitrogen fixation'], 0,
    'It is a carotenoid-rich region of the chloroplast.'],
  ['The contractile vacuole of *Euglena* is for:', ['Osmoregulation — expelling excess water', 'Food storage', 'Photosynthesis', 'Reproduction'], 0,
    'It empties into the reservoir at the front of the cell.'],
  ['*Euglena* has:', ['A protein pellicle instead of a cell wall and paramylon as reserve', 'A cellulose wall and starch', 'A silica frustule', 'Phycobilins'], 0,
    'It can switch to heterotrophy in the dark.'],
  ['Prokaryotic algae (cyanobacteria) differ from eukaryotic algae in having:', ['70S ribosomes and no membrane-bound organelles', 'Chloroplasts', 'A nuclear membrane', '80S ribosomes'], 0,
    'Eukaryotic algae have chloroplasts thought to come from cyanobacterial endosymbionts.'],
  ['Floridean starch is the reserve food of:', ['Red algae', 'Brown algae', 'Green algae', 'Diatoms'], 0,
    'Brown: laminarin and mannitol; green: starch; diatoms: chrysolaminarin and oil.']
] }
);
