/* Concept sets for Botany I — Fungi & Lichens. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Fungi & Lichens', w: 3, pyq: ['CSE-2023-B1-m18', 'CSE-2021-B1-m16', 'CSE-2020-B1-m14', 'CSE-2018-B1-m14', 'CSE-2011-B1-m11', 'CSE-2010-B1-m20', 'IFoS-2016-B1-m12', 'CSE-2016-B1-m15', 'CSE-1993-B1-m32', 'CSE-2006-B1-m11', 'CSE-2017-B1-Q1d'], q: [
  ['A lichen is a symbiotic association of:', ['A fungus (mycobiont) with a green alga or cyanobacterium (photobiont)', 'A fungus with a plant root', 'A bacterium with a legume', 'Two algae'], 0,
    'The fungus is usually an ascomycete; a few are basidiolichens.'],
  ['Match the lichen form with its example: fruticose —', ['*Usnea*', '*Graphis*', '*Parmelia*', '*Lecanora*'], 0,
    'Crustose: *Graphis*, *Lecanora*; foliose: *Parmelia*, *Physcia*; fruticose: *Usnea*, *Cladonia*.'],
  ['In a heteromerous lichen thallus, the algal cells:', ['Form a distinct layer below the upper cortex', 'Are scattered evenly through the thallus', 'Are absent', 'Lie only in the rhizines'], 0,
    'Homoiomerous thalli (e.g. *Collema*) have algae evenly spread.'],
  ['Cephalodia in lichens are:', ['Small gall-like bodies holding cyanobacteria that fix nitrogen', 'Pores for gas exchange', 'Reproductive cups', 'Root-like holdfasts'], 0,
    'Found in lichens whose main photobiont is a green alga, e.g. *Peltigera aphthosa*.'],
  ['Cyphellae are:', ['Cup-like pores on the lower cortex that aid aeration', 'Spores of lichens', 'Algal cells', 'Fungal fruit bodies'], 0,
    'Typical of *Sticta*; pseudocyphellae lack a cortical lining.'],
  ['Soredia are:', ['Powdery clusters of algal cells wrapped in hyphae, for vegetative spread', 'Sexual spores', 'Outgrowths of the cortex only', 'Fungal conidia'], 0,
    'Isidia are small coral-like outgrowths of the thallus that break off.'],
  ['In the lichen partnership, the photobiont mainly supplies:', ['Carbohydrates — sugar alcohols from green algae or glucose from cyanobacteria', 'Water and minerals', 'Protection from light', 'Spores'], 0,
    'The fungus gives shelter, water and minerals; some call it controlled parasitism (helotism).'],
  ['Lichens are rare or absent in cities mainly because they are:', ['Very sensitive to sulphur dioxide', 'Unable to grow on walls', 'Eaten by birds', 'Dependent on rain only'], 0,
    'They are good indicators of air pollution; city centres can be "lichen deserts".'],
  ['Litmus is obtained from:', ['*Roccella*', '*Usnea*', '*Cladonia*', '*Graphis*'], 0,
    '*Cladonia rangiferina* (reindeer moss) is fodder; *Parmelia* (stone flower) is a spice in India.'],
  ['Crustose lichens are pioneers on bare rock because they:', ['Secrete lichen acids that weather rock and trap soil', 'Need deep soil', 'Shade other plants', 'Fix carbon only at night'], 0,
    'They start xerarch succession, followed by foliose lichens and mosses.']
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 3, pyq: ['IFoS-2023-B1-m14', 'CSE-2012-B1-m11', 'CSE-2010-B1-m19', 'IFoS-2002-B1-m14', 'CSE-1995-B1-m21', 'IFoS-2011-B1-m22', 'CSE-2015-B1-m15', 'IFoS-2002-B1-m15', 'CSE-1989-B1-m22', 'IFoS-2013-B1-m27', 'CSE-2009-B1-m01', 'CSE-2017-B1-Q1c'], q: [
  ['Heterothallism was discovered in *Mucor* by:', ['Blakeslee (1904)', 'Pontecorvo (1952)', 'de Bary (1866)', 'Buller (1931)'], 0,
    'He named the mating strains + and −.'],
  ['A heterothallic fungus is one that:', ['Needs two compatible thalli for sexual reproduction', 'Is self-fertile', 'Has no sexual stage', 'Forms only asexual spores'], 0,
    'Homothallic fungi complete the sexual cycle on one thallus.'],
  ['Physiological heterothallism differs from morphological heterothallism in that:', ['Compatibility depends on mating-type genes, not on separate male and female thalli', 'It needs separate male and female thalli', 'It occurs only in algae', 'No sex organs form'], 0,
    'Morphological heterothallism is simple dioecism.'],
  ['Tetrapolar (bifactorial) heterothallism, as in *Schizophyllum* and *Coprinus*, is controlled by:', ['Two unlinked mating-type loci, A and B', 'One locus with two alleles', 'Cytoplasmic factors', 'A single sex chromosome'], 0,
    'Spores of one fruit body fall into four mating types; bipolar systems have one locus.'],
  ['Match the sexual method with the fungus: gametangial copulation —', ['*Rhizopus*', '*Pythium*', '*Puccinia*', '*Agaricus*'], 0,
    'Gametangial contact: *Pythium*; spermatisation: *Puccinia*; somatogamy: *Agaricus*.'],
  ['The trend in fungal sexuality from lower to higher fungi is:', ['Loss of sex organs, ending in somatogamy', 'Increase in motile gametes', 'Change from somatogamy to motile gametes', 'No change'], 0,
    'Planogametes → gametangial contact or fusion → spermatisation → somatogamy.'],
  ['Antheridiol, a fungal sex hormone of *Achlya*, is:', ['Made by female strains and induces antheridial branches', 'Made by males and induces oogonia', 'A toxin', 'A growth inhibitor'], 0,
    'Oogoniol from males then induces oogonia.'],
  ['Trisporic acid in Mucorales:', ['Induces zygophore formation between compatible strains', 'Attracts zoospores', 'Breaks spore dormancy', 'Inhibits mycelium'], 0,
    'Sirenin attracts male gametes in *Allomyces*.'],
  ['A holocarpic fungus is one in which:', ['The whole thallus turns into a reproductive structure', 'Only part of the thallus becomes reproductive', 'The thallus is septate', 'Reproduction is only asexual'], 0,
    'E.g. *Synchytrium*, *Olpidium*. Eucarpic fungi keep a vegetative part.'],
  ['The main significance of heterothallism is that it:', ['Enforces outbreeding and raises genetic variability', 'Prevents spore formation', 'Allows only selfing', 'Stops mutation'], 0,
    'It is the fungal parallel of self-incompatibility.']
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 2, pyq: ['CSE-2023-B1-m17', 'CSE-2017-B1-m13', 'IFoS-2014-B1-m18', 'CSE-2011-B1-m12', 'IFoS-2012-B1-m35', 'IFoS-2020-B1-m10'], q: [
  ['The parasexual cycle was discovered by:', ['Pontecorvo and Roper (1952) in *Aspergillus nidulans*', 'Blakeslee in *Mucor*', 'Beadle and Tatum in *Neurospora*', 'Lederberg in *E. coli*'], 0,
    'It gives recombination without meiosis.'],
  ['The correct order of events in the parasexual cycle is:', ['Heterokaryosis → nuclear fusion → mitotic crossing over → haploidisation', 'Meiosis → fertilisation → mitosis', 'Plasmogamy → karyogamy → meiosis', 'Haploidisation → heterokaryosis → fusion'], 0,
    'Haploidisation is gradual loss of chromosomes from the diploid.'],
  ['Parasexuality is most important in:', ['Imperfect fungi (Deuteromycetes) that lack a sexual cycle', 'Basidiomycetes only', 'Algae', 'Bryophytes'], 0,
    'E.g. *Aspergillus*, *Penicillium* and many plant pathogens.'],
  ['A practical use of the parasexual cycle is:', ['Genetic mapping and improving industrial strains such as penicillin producers', 'Making seeds', 'Stopping disease', 'Producing haploid plants'], 0,
    'It also explains new races of asexual pathogens.'],
  ['Parasexual recombination differs from sexual recombination in that it:', ['Involves mitotic crossing over and no meiosis', 'Needs gametangia', 'Needs fruiting bodies', 'Forms ascospores'], 0,
    'It happens in vegetative hyphae.'],
  ['In the laboratory, haploidisation of fungal diploids can be induced with:', ['Benomyl or p-fluorophenylalanine', 'Colchicine only', 'Auxin', 'Gibberellin'], 0,
    'These cause chromosome loss.'],
  ['Mitotic crossing over in a heterozygous diploid can produce:', ['Homozygous diploid sectors', 'Triploid nuclei', 'Spores by meiosis', 'Only haploid nuclei'], 0,
    'Sectors with recessive traits reveal this.'],
  ['Parasexuality between two strains needs them to form:', ['A heterokaryon — hyphae with two kinds of nuclei', 'Asci', 'Basidia', 'Zygospores'], 0,
    'Vegetative incompatibility can block this.'],
  ['Zoospores of Oomycetes have:', ['Two flagella — an anterior tinsel and a posterior whiplash', 'One posterior whiplash flagellum', 'One anterior tinsel flagellum', 'No flagella'], 0,
    'Chytrids: one posterior whiplash; Hyphochytrids: one anterior tinsel.'],
  ['Heterokaryosis is:', ['Presence of genetically different nuclei in a common cytoplasm', 'Fusion of two nuclei', 'Loss of chromosomes', 'Formation of a zygote'], 0,
    'It is the first step of the parasexual cycle.']
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 3, pyq: ['CSE-2025-B1-m18', 'CSE-2015-B1-m16', 'CSE-1997-B1-m12', 'CSE-2012-B1-m13', 'IFoS-2007-B1-m16', 'CSE-1987-B1-m15', 'CSE-2014-B1-m17', 'CSE-2011-B1-m13', 'CSE-2012-B1-m15', 'CSE-2014-B1-m15', 'CSE-2009-B1-m19', 'CSE-2019-B1-m17', 'IFoS-2006-B1-m18', 'CSE-1988-B1-m15', 'CSE-2004-B1-m18', 'CSE-1985-B1-m19', 'CSE-2006-B1-m06', 'CSE-1998-B1-m03', 'CSE-1996-B1-m13', 'CSE-1995-B1-m15', 'CSE-1996-B1-m14', 'IFoS-2011-B1-m14', 'IFoS-2022-B1-m11', 'IFoS-2002-B1-m09'], q: [
  ['Match the ascocarp with its example: perithecium —', ['*Neurospora*', '*Peziza*', '*Penicillium*', '*Agaricus*'], 0,
    'Cleistothecium (closed): *Penicillium*, *Erysiphe*; perithecium (flask with ostiole): *Neurospora*, *Claviceps*; apothecium (cup): *Peziza*.'],
  ['In ascus development, the ascogenous hypha forms a hook called a:', ['Crozier', 'Clamp', 'Sterigma', 'Haustorium'], 0,
    'Its penultimate dikaryotic cell becomes the ascus mother cell.'],
  ['After karyogamy in the young ascus, eight ascospores result from:', ['Meiosis followed by one mitosis', 'Two mitoses', 'Meiosis only', 'Budding'], 0,
    'In *Neurospora* the spores lie in an ordered row.'],
  ['An ascus differs from a basidium in that its spores are:', ['Formed inside it, usually eight', 'Formed outside on sterigmata, usually four', 'Not formed by meiosis', 'Motile'], 0,
    'Basidiospores are exogenous.'],
  ['Cleistothecia of *Phyllactinia* bear appendages that are:', ['Needle-like with bulbous bases', 'Hyphae-like (myceloid)', 'Hooked at the tip', 'Branched at the tip'], 0,
    '*Erysiphe*: myceloid; *Uncinula*: hooked; *Microsphaera*: dichotomously branched tips.'],
  ['Powdery mildews differ from downy mildews in being:', ['Ascomycetes with superficial white mycelium and conidia', 'Oomycetes with sporangiophores through stomata', 'Bacteria', 'Rust fungi'], 0,
    'Downy mildews (*Plasmopara*, *Peronospora*, *Sclerospora*) are internal oomycetes.'],
  ['The apothecium of *Peziza* bears a hymenium of:', ['Asci mixed with sterile paraphyses', 'Basidia and cystidia', 'Sporangia', 'Conidiophores'], 0,
    'Asci open by a lid (operculate).'],
  ['Bitunicate asci, with two separable walls, are typical of:', ['Loculoascomycetes with ascostromata', 'Yeasts', 'Powdery mildews', 'Cup fungi'], 0,
    'Most other ascomycetes have unitunicate asci.'],
  ['The ergot of rye is caused by *Claviceps purpurea*, whose sclerotia contain:', ['Ergot alkaloids such as ergotamine', 'Aflatoxin', 'Penicillin', 'Gibberellin'], 0,
    'Ergometrine is used to control post-partum bleeding; perithecia form in stromata from the sclerotia.'],
  ['*Neurospora* was used by Beadle and Tatum because it:', ['Is haploid and gives ordered ascospores', 'Has no sexual stage', 'Is diploid', 'Forms basidia'], 0,
    'Their work led to the one gene–one enzyme idea.']
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 2, pyq: ['CSE-1996-B1-m19', 'CSE-2022-B1-m15', 'IFoS-2020-B1-m15', 'IFoS-2012-B1-m33', 'CSE-1987-B1-m15', 'CSE-1990-B1-m29', 'IFoS-2011-B1-m13'], q: [
  ['The three kinds of mycelia in Basidiomycetes are:', ['Primary (monokaryotic), secondary (dikaryotic) and tertiary (organised fruit-body tissue)', 'Septate, aseptate and coenocytic', 'Haploid, diploid and triploid', 'Aerial, submerged and parasitic'], 0,
    'The secondary mycelium is long-lived and forms the fruit body.'],
  ['Clamp connections help to:', ['Keep the dikaryotic state during cell division', 'Form spores', 'Absorb food', 'Attach to the host'], 0,
    'They are a hallmark of many basidiomycetes.'],
  ['Dikaryotisation in mushrooms usually happens by:', ['Fusion of compatible primary hyphae (somatogamy)', 'Fusion of motile gametes', 'Gametangial copulation', 'Meiosis'], 0,
    'Rusts use spermatisation; the Buller phenomenon is dikaryon–monokaryon mating.'],
  ['In rust fungi, dikaryotisation occurs when:', ['Spermatia fuse with receptive hyphae of the pycnium', 'Teliospores germinate', 'Basidiospores fuse', 'Uredospores fuse'], 0,
    'The aecium then forms dikaryotic aeciospores.'],
  ['In a developing basidium, the sequence is:', ['Karyogamy → meiosis → four nuclei move into sterigmata', 'Meiosis → karyogamy → spores', 'Mitosis only', 'Plasmogamy → mitosis'], 0,
    'Basidiospores are exogenous and usually four.'],
  ['A septate basidium (phragmobasidium) is found in:', ['*Puccinia* and *Auricularia*', '*Agaricus*', '*Polyporus*', '*Lycoperdon*'], 0,
    '*Agaricus* has an aseptate holobasidium.'],
  ['The gills of *Agaricus* bear:', ['A hymenium of basidia with paraphyses and cystidia', 'Asci', 'Sporangia', 'Conidia'], 0,
    'The central tissue of the gill is the trama.'],
  ['Match spore type with how it forms: basidiospore —', ['Exogenously on a basidium after meiosis', 'Inside a sporangium by mitosis', 'Inside an ascus', 'By fusion of gametangia'], 0,
    'Sporangiospores: mitotic, in sporangia; ascospores: in asci after meiosis.'],
  ['Basidiospores of mushrooms are shot off by:', ['A droplet (Buller\'s drop) at the spore base', 'Wind only', 'Insects', 'Bursting of the cap'], 0,
    'Such forcibly discharged spores are ballistospores.'],
  ['Compared with Ascomycota, Basidiomycota have:', ['A long dikaryotic phase and exogenous meiospores', 'Short dikaryotic phase and endogenous spores', 'Motile gametes', 'No fruiting bodies'], 0,
    'Zygomycota form zygospores by gametangial copulation.']
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 2, pyq: ['CSE-2024-B1-m18', 'IFoS-2013-B1-m28', 'IFoS-2020-B1-m14', 'IFoS-2005-B1-m21', 'IFoS-2015-B1-m12', 'CSE-2007-B1-m02', 'CSE-2005-B1-m03', 'CSE-2003-B1-m18', 'CSE-2000-B1-m15', 'CSE-1986-B1-m25', 'CSE-2005-B1-m05', 'IFoS-2006-B1-m12'], q: [
  ['Myxomycetes resemble animals because their vegetative stage is:', ['A wall-less, multinucleate plasmodium that engulfs food', 'A septate mycelium', 'A walled yeast cell', 'A photosynthetic filament'], 0,
    'They are placed with fungi because they form walled spores in sporangia.'],
  ['In a myxomycete life cycle, meiosis occurs:', ['In the sporangium during spore formation', 'In the plasmodium', 'In swarm cells', 'Never'], 0,
    'Spores give myxamoebae or swarm cells that fuse to make a zygote and then a plasmodium.'],
  ['Deuteromycotina is called a "waste-basket" group because:', ['It holds fungi whose sexual stage is unknown, and they move out when one is found', 'All its members are saprophytes', 'Its members cause no disease', 'It has only one genus'], 0,
    'Since 2011 the "one fungus, one name" rule has reduced its use.'],
  ['The conidiophore of *Penicillium* is:', ['Branched like a brush, ending in phialides bearing conidial chains', 'Unbranched with a swollen vesicle', 'A sporangiophore with a columella', 'A basidium'], 0,
    'Penicillus means "little brush".'],
  ['The conidiophore of *Aspergillus* ends in:', ['A swollen vesicle covered with phialides', 'A brush of metulae', 'A sporangium', 'A crozier'], 0,
    'It arises from a foot cell of the mycelium.'],
  ['The mycelium of *Penicillium* is:', ['Septate and branched', 'Coenocytic and aseptate', 'A plasmodium', 'Yeast-like only'], 0,
    'Oomycetes such as *Saprolegnia* are coenocytic.'],
  ['*Pythium* causes:', ['Damping-off of seedlings', 'Ergot', 'Rust of wheat', 'Powdery mildew'], 0,
    'Its zoospores form in a vesicle outside the sporangium; sexual reproduction is by gametangial contact.'],
  ['*Aspergillus niger* is used industrially for:', ['Citric acid', 'Penicillin', 'Ethanol', 'Agar'], 0,
    '*A. flavus* produces aflatoxin.'],
  ['The asexual and sexual stages of a fungus are called:', ['Anamorph and teleomorph', 'Gametophyte and sporophyte', 'Mycelium and spore', 'Haploid and diploid'], 0,
    'The whole fungus is the holomorph.'],
  ['Somatic hybrids from protoplast fusion differ from cybrids in that cybrids have:', ['The nucleus of one parent with cytoplasm of both', 'Nuclei of both parents', 'No cytoplasm', 'Only chloroplasts'], 0,
    'Cybrids are used to transfer cytoplasmic male sterility.']
] },
{ p: 'B1', t: 'Fungi & Lichens', w: 2, pyq: ['CSE-2007-B1-m16', 'CSE-2014-B1-m14', 'CSE-1991-B1-m01', 'CSE-2001-B1-m02', 'CSE-1986-B1-m15'], q: [
  ['A vegetative cell of *Saccharomyces cerevisiae* has:', ['A thin wall, one nucleus, a large vacuole and glycogen and volutin granules', 'Many nuclei and no vacuole', 'Chloroplasts', 'A septate mycelium'], 0,
    'It reproduces mainly by budding.'],
  ['In *S. cerevisiae*, sexual reproduction involves:', ['Fusion of two haploid cells to a diploid that later forms four ascospores by meiosis', 'Zygospore formation', 'Basidiospores', 'Motile gametes'], 0,
    'Both haploid and diploid cells can bud — a haplodiplontic cycle.'],
  ['Penicillin was discovered by Fleming (1928) from:', ['*Penicillium notatum*', '*Aspergillus niger*', '*Saccharomyces*', '*Claviceps*'], 0,
    'Commercial strains are *P. chrysogenum*.'],
  ['The immunosuppressant cyclosporin comes from:', ['*Tolypocladium inflatum*', '*Penicillium roquefortii*', '*Agaricus bisporus*', '*Rhizopus*'], 0,
    'It is used in organ transplants.'],
  ['The paddy-straw mushroom is:', ['*Volvariella volvacea*', '*Agaricus bisporus*', '*Pleurotus*', '*Calocybe indica*'], 0,
    'Button: *Agaricus*; oyster: *Pleurotus*; milky: *Calocybe*.'],
  ['A fungus used widely as a biocontrol agent against soil-borne pathogens is:', ['*Trichoderma*', '*Puccinia*', '*Ustilago*', '*Claviceps*'], 0,
    '*Beauveria* and *Metarhizium* are used against insects.'],
  ['Lovastatin, a cholesterol-lowering drug, is from:', ['*Aspergillus terreus*', '*Saccharomyces*', '*Penicillium notatum*', '*Mucor*'], 0,
    'Statins inhibit HMG-CoA reductase.'],
  ['Gibberellins were first found in the fungus:', ['*Gibberella fujikuroi*, causing bakanae of rice', '*Fusarium oxysporum*, causing wilt', '*Penicillium*', '*Pythium*'], 0,
    'Infected seedlings grow abnormally tall.'],
  ['Blue cheese gets its flavour from:', ['*Penicillium roquefortii*', '*Aspergillus flavus*', '*Rhizopus*', '*Saccharomyces*'], 0,
    'Camembert uses *P. camemberti*.'],
  ['The Himalayan morel ("gucchi") is:', ['*Morchella*, an ascomycete', '*Agaricus*, a basidiomycete', '*Penicillium*', '*Pleurotus*'], 0,
    'It is one of the costliest wild mushrooms.']
] }
);
