/* Concept sets for Botany I — physiology/ecology odds, short-note terms, and a mixed revision set for PYQs whose wording survives only as a header. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Plant Physiology', w: 1, pyq: ['CSE-1998-B1-m17', 'CSE-1996-B1-m17', 'CSE-1988-B1-m18', 'CSE-1986-B1-m16', 'CSE-1985-B1-m14', 'IFoS-2001-B1-m23', 'CSE-1991-B1-m23', 'CSE-1990-B1-m07', 'CSE-1994-B1-m35', 'CSE-1992-B1-m27', 'CSE-1990-B1-m32', 'CSE-1993-B1-m34'], q: [
  ['Leaf abscission is promoted mainly by:', ['Ethylene, while auxin from the leaf delays it', 'Auxin alone', 'Cytokinin', 'Gibberellin'], 0,
    'An abscission zone of small cells forms at the petiole base; a protective layer heals the scar.'],
  ['Leaf senescence can be delayed by:', ['Cytokinins (the Richmond–Lang effect)', 'Ethylene', 'Abscisic acid', 'Darkness'], 0,
    'Senescing leaves export nitrogen and other nutrients before falling.'],
  ['Apical dominance is classically explained by:', ['Auxin from the shoot tip suppressing lateral buds', 'Cytokinin from leaves', 'Gibberellin from roots only', 'Ethylene from fruits'], 0,
    'Cytokinins release buds; strigolactones act as a second messenger.'],
  ['Red and far-red light act on plant development through:', ['Phytochrome, switching between Pr and Pfr forms', 'Cryptochrome only', 'Chlorophyll b', 'Carotenoids'], 0,
    'Blue light acts through cryptochromes and phototropins.'],
  ['In photoperiodism, short-day plants flower when:', ['The night is longer than a critical length', 'The day is longer than a critical length', 'Light is continuous', 'Temperature is high'], 0,
    'Garner and Allard (1920) discovered it in Maryland Mammoth tobacco; the florigen signal is the FT protein.'],
  ['Pneumatophores of mangroves are:', ['Negatively geotropic roots that take in air through lenticels', 'Climbing roots', 'Storage roots', 'Root nodules'], 0,
    'Mangroves also show vivipary and salt-secreting glands.'],
  ['*Utricularia* differs from *Aldrovanda* in that *Utricularia* traps prey in:', ['Bladders with a trapdoor', 'Snapping leaf lobes', 'Sticky hairs', 'Pitchers'], 0,
    '*Aldrovanda* (waterwheel plant, Droseraceae) uses snap traps like Venus flytrap.'],
  ['Commensalism differs from amensalism in that in commensalism:', ['One partner benefits and the other is unaffected', 'One is harmed and the other unaffected', 'Both benefit', 'Both are harmed'], 0,
    'Epiphytes are commensals; allelopathy is a kind of amensalism.'],
  ['A non-green "saprophytic" angiosperm that gets food through mycorrhizal fungi is:', ['*Monotropa*', '*Cuscuta*', '*Viscum*', '*Nepenthes*'], 0,
    'Such plants are now called mycoheterotrophs.'],
  ['Evergreen foliage in hot, wet tropics is possible because:', ['Water and warmth are available all year, so leaves need not be shed together', 'Leaves never die', 'Plants lack abscission zones', 'Photosynthesis stops in summer'], 0,
    'Leaves are replaced gradually rather than in one season.']
] },
{ p: 'B1', t: 'Plant Diversity', w: 1, pyq: ['CSE-1987-B1-m14', 'CSE-1986-B1-m14', 'CSE-1988-B1-m16', 'CSE-1985-B1-m03', 'CSE-2009-B1-m15', 'IFoS-2005-B1-m14', 'CSE-1990-B1-m27', 'IFoS-2005-B1-m11', 'IFoS-2009-B1-m20'], q: [
  ['The technical term for spatial separation of anthers and stigma that prevents selfing is:', ['Herkogamy', 'Dichogamy', 'Cleistogamy', 'Geitonogamy'], 0,
    'Dichogamy is separation in time; geitonogamy is pollination between flowers of one plant.'],
  ['Sterile hairs among sex organs or sporangia (e.g. in *Funaria* or *Peziza*) are called:', ['Paraphyses', 'Elaters', 'Rhizoids', 'Trichogynes'], 0,
    'They protect and keep moist the developing organs.'],
  ['S. R. Kashyap is known as the father of Indian:', ['Bryology', 'Phycology', 'Palaeobotany', 'Embryology'], 0,
    'He wrote *Liverworts of the Western Himalayas and the Panjab Plain*.'],
  ['M. O. P. Iyengar is known for his work on:', ['Algae (Indian phycology)', 'Fungi', 'Fossils', 'Orchids'], 0,
    'Birbal Sahni founded Indian palaeobotany; P. Maheshwari led angiosperm embryology.'],
  ['K. C. Mehta showed that wheat rust in the Indian plains each year comes from:', ['Uredospores surviving in the hills', 'Barberry hosts in the plains', 'Seed-borne infection', 'Soil'], 0,
    'Barberry plays little role in India.'],
  ['E. K. Janaki Ammal is remembered for:', ['Cytogenetics of sugarcane and other crops', 'Discovering penicillin', 'The Green Revolution in wheat', 'Taxonomy of fungi'], 0,
    'She co-authored the *Chromosome Atlas of Cultivated Plants*.'],
  ['A "carnivorous" fungus that traps nematodes with hyphal loops is:', ['*Arthrobotrys*', '*Rhizopus*', '*Penicillium*', '*Agaricus*'], 0,
    'Nematode-trapping fungi are studied as biocontrol agents.'],
  ['The compound zoospore (synzoospore) of *Vaucheria* is:', ['Multinucleate with many pairs of flagella', 'Uninucleate with two flagella', 'Non-motile', 'A gamete'], 0,
    'It forms from the whole contents of a terminal sporangium.'],
  ['Binomial nomenclature was established by:', ['Linnaeus in *Species Plantarum* (1753)', 'Bentham and Hooker', 'Engler', 'Darwin'], 0,
    '1 May 1753 is the starting date for plant names.'],
  ['The father of Indian ecology is:', ['R. Misra', 'Birbal Sahni', 'P. Maheshwari', 'M. S. Swaminathan'], 0,
    'Ramdeo Misra built ecology teaching and research at BHU.']
] },
{ p: 'B1', t: 'Plant Diversity', w: 1, pyq: ['CSE-1994-B1-m07', 'CSE-1993-B1-m09', 'CSE-1989-B1-m11', 'CSE-2011-B1-m07', 'IFoS-2013-B1-m16', 'IFoS-2013-B1-m20', 'IFoS-2009-B1-m18', 'CSE-1995-B1-m19', 'CSE-1993-B1-m15', 'CSE-1992-B1-m22', 'CSE-1991-B1-m18', 'CSE-1990-B1-m24', 'CSE-1989-B1-m18', 'CSE-1995-B1-m35', 'CSE-1989-B1-m33', 'CSE-1989-B1-m35', 'IFoS-2006-B1-m23', 'CSE-2009-B1-m03'], q: [
  ['Mixed revision — the heterocyst of cyanobacteria is the site of:', ['Nitrogen fixation', 'Photosynthetic oxygen release', 'Spore formation', 'Food storage'], 0,
    'It lacks photosystem II.'],
  ['Mixed revision — the sporophyte of *Funaria* is:', ['Dependent on the gametophyte and differentiated into foot, seta and capsule', 'Free-living', 'Absent', 'Haploid'], 0,
    'Mosses have the most elaborate bryophyte sporophyte.'],
  ['Mixed revision — the sporocarp of *Marsilea* is a modified:', ['Leaf segment', 'Stem', 'Root', 'Sporangium'], 0,
    'It bears mixed sori of mega- and microsporangia.'],
  ['Mixed revision — coralloid roots of *Cycas* harbour:', ['Cyanobacteria such as *Anabaena* and *Nostoc*', 'Mycorrhizal fungi', '*Rhizobium*', 'Nematodes'], 0,
    'They fix nitrogen.'],
  ['Mixed revision — the cyathium is the inflorescence of:', ['*Euphorbia*', '*Helianthus*', '*Ficus*', '*Musa*'], 0,
    'A cup of bracts holding one female and many male flowers.'],
  ['Mixed revision — the most common embryo sac type is:', ['*Polygonum* type', '*Allium* type', '*Peperomia* type', '*Oenothera* type'], 0,
    'Monosporic, 8-nucleate and 7-celled.'],
  ['Mixed revision — anomalous secondary growth with successive rings of cambium is seen in:', ['*Boerhaavia*', '*Helianthus*', '*Zea*', '*Pinus*'], 0,
    'Also *Achyranthes* and *Bougainvillea*.'],
  ['Mixed revision — totipotency means:', ['A single cell can regenerate a whole plant', 'Cells cannot divide', 'Only roots can regenerate', 'Seeds are dormant'], 0,
    'It underlies all plant tissue culture.'],
  ['Mixed revision — late blight of potato is caused by:', ['*Phytophthora infestans*', '*Alternaria solani*', '*Puccinia graminis*', '*Ustilago tritici*'], 0,
    'It caused the Irish famine.'],
  ['Mixed revision — semi-moist foods (such as jams) resist spoilage mainly because:', ['Sugar or salt lowers water activity below what most microbes need', 'They are sterile forever', 'They contain antibiotics', 'They are kept frozen'], 0,
    'Humectants keep them soft while limiting microbial growth.']
] }
);
