/* Concept sets for Botany I — Bryophytes. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Bryophytes', w: 3, pyq: ['IFoS-2023-B1-m10', 'CSE-2016-B1-m12', 'CSE-2014-B1-m11', 'CSE-2004-B1-m12', 'IFoS-2020-B1-m09', 'IFoS-2013-B1-m14', 'CSE-1987-B1-m13', 'CSE-2001-B1-m09', 'CSE-1997-B1-m11'], q: [
  ['The sporophyte of a bryophyte is called the:', ['Sporogonium', 'Sporangiophore', 'Strobilus', 'Prothallus'], 0,
    'It is the whole diploid structure — foot, seta and capsule where present.'],
  ['Arranged by increasing complexity of the sporophyte, the classic series is:', ['*Riccia* → *Marchantia* → *Funaria*', '*Funaria* → *Marchantia* → *Riccia*', '*Marchantia* → *Riccia* → *Funaria*', '*Funaria* → *Riccia* → *Marchantia*'], 0,
    'Capsule only → foot, seta and capsule → elaborate capsule with apophysis, columella and peristome.'],
  ['Spores of *Riccia* are released by:', ['Decay of the capsule wall and the surrounding thallus', 'An operculum and peristome', 'Splitting into two valves', 'Explosive discharge'], 0,
    'The capsule stays embedded in the thallus and has no dehiscence mechanism of its own.'],
  ['The *Anthoceros* capsule dehisces by:', ['Splitting into two valves from the tip downwards', 'Shedding an operculum', 'Irregular apical teeth', 'Decay of the thallus'], 0,
    'Splitting proceeds downwards as spores mature from the apex towards the base.'],
  ['Among bryophytes, the sporophyte most independent of the gametophyte for food is that of:', ['*Anthoceros*', '*Riccia*', '*Marchantia*', '*Pellia*'], 0,
    'Its long green capsule has stomata and a basal meristem, so it keeps photosynthesising and growing.'],
  ['The moss whose capsule — with apophysis, columella, peristome and epiphragm — is often called the most elaborate among bryophytes is:', ['*Polytrichum*', '*Riccia*', '*Sphagnum*', '*Marchantia*'], 0,
    'Its peristome has 32 or 64 nematodontous teeth joined at the tips to a membranous epiphragm.'],
  ['The main evolutionary trend from *Riccia* to the mosses is:', ['More sterile tissue and greater photosynthetic independence of the sporophyte', 'Loss of the capsule', 'A more dominant sporophyte than gametophyte', 'Loss of the foot'], 0,
    'The gametophyte still stays dominant in every bryophyte.'],
  ['D. H. Campbell suggested that pteridophytes arose from ancestors resembling the sporophyte of:', ['*Anthoceros*', '*Riccia*', '*Sphagnum*', '*Funaria*'], 0,
    'Its green, stomatal, continuously growing sporophyte lacks only vascular tissue.'],
  ['The foot of a bryophyte sporophyte mainly:', ['Absorbs water and nutrients from the gametophyte', 'Produces spores', 'Makes the gametes', 'Disperses the spores'], 0,
    'Transfer cells at the junction work like a placenta.'],
  ['The "retrogressive" (reduction) view of bryophyte evolution holds that the simple *Riccia* sporophyte is:', ['A reduced form derived from more complex ancestors', 'The most primitive starting point', 'A gametophyte', 'Identical to that of mosses'], 0,
    'Bower’s upgrade theory reads the same series the other way round, from simple to complex.']
] },
{ p: 'B1', t: 'Bryophytes', w: 3, pyq: ['IFoS-2022-B1-m09', 'CSE-2015-B1-m09', 'CSE-2013-B1-m08', 'CSE-2020-B1-m11', 'IFoS-2003-B1-m13', 'CSE-1987-B1-m13', 'IFoS-2023-B1-m09', 'CSE-2007-B1-m13', 'CSE-1999-B1-m12', 'IFoS-2004-B1-m13', 'CSE-2005-B1-m12', 'IFoS-2006-B1-m08', 'CSE-2010-B1-m16', 'CSE-1994-B1-m38', 'CSE-1998-B1-m02', 'CSE-2006-B1-m16', 'CSE-1989-B1-m30', 'CSE-2026-B1-m06'], q: [
  ['A feature that *Anthoceros* shares with green algae (Chlorophyceae) is:', ['A single large chloroplast per cell, with a pyrenoid', 'Phycobilins', 'Floridean starch', 'Motile vegetative cells'], 0,
    'This algal-like plastid is unique among bryophytes.'],
  ['Colonies of *Nostoc* in the *Anthoceros* thallus live in:', ['Mucilage-filled cavities on the ventral side, where they fix nitrogen', 'The capsule wall', 'Air chambers with pores', 'The rhizoids'], 0,
    'Hornworts are among the few bryophytes with cyanobacterial symbionts.'],
  ['The *Anthoceros* thallus, in vertical section, is:', ['Simple and homogeneous, without air chambers, scales or tuberculate rhizoids', 'Divided into air chambers with barrel-shaped pores', 'Leafy with a midrib', 'Differentiated into xylem and phloem'], 0,
    'It bears only smooth-walled rhizoids.'],
  ['The antheridia of *Anthoceros* are:', ['Endogenous — formed from hypodermal cells inside closed chambers', 'Borne on stalked antheridiophores', 'Exposed on leaf axils', 'Formed in gemma cups'], 0,
    'Endogenous antheridia are unique among bryophytes.'],
  ['The archegonium of *Anthoceros*, unlike that of *Funaria*, is:', ['Sunken in the thallus, without a projecting stalk or jacket', 'Long-stalked with a twisted neck', 'Borne on an archegoniophore', 'Absent'], 0,
    '*Funaria* archegonia have a stalk, a massive venter and a long neck.'],
  ['The mature *Anthoceros* sporophyte consists of:', ['A bulbous foot, a basal meristematic zone and a long capsule — no seta', 'Foot, long seta and capsule', 'A capsule only', 'A seta and capsule only'], 0,
    'The meristem keeps adding new capsule tissue from below.'],
  ['The central columella of the *Anthoceros* capsule usually has:', ['Sixteen vertical rows of cells (4 × 4 in cross-section)', 'One cell', 'Many tracheids', 'No cells'], 0,
    'The archesporium arches over it like a dome.'],
  ['In an *Anthoceros* capsule, spores mature:', ['From the tip downwards, so ripe spores lie at the top and young cells at the base', 'All at the same time', 'From the base upwards', 'Only after the capsule falls'], 0,
    'This is possible because the capsule grows continuously from its base.'],
  ['Compared with the *Funaria* sporophyte, the *Anthoceros* sporophyte lacks:', ['A seta, operculum and peristome', 'A foot', 'Spores', 'Stomata'], 0,
    'Both have a columella and stomata in the capsule wall.'],
  ['*Anthoceros* is often called a "synthetic" or connecting genus because:', ['Its plastids are algal-like while its sporophyte has pteridophyte-like features', 'It has vascular tissue', 'It produces seeds', 'It lacks a sporophyte'], 0,
    'Its features straddle algae, other bryophytes and early vascular plants.']
] },
{ p: 'B1', t: 'Bryophytes', w: 3, pyq: ['IFoS-2021-B1-m14', 'IFoS-2014-B1-m12', 'CSE-2011-B1-m08', 'CSE-2019-B1-m12', 'IFoS-2009-B1-m17', 'IFoS-2002-B1-m07', 'CSE-2012-B1-m10', 'CSE-2000-B1-m09', 'IFoS-2023-B1-m09', 'CSE-2007-B1-m13', 'CSE-1999-B1-m12'], q: [
  ['The three regions of a *Funaria* capsule, from base to tip, are:', ['Apophysis, theca and operculum', 'Foot, seta and calyptra', 'Columella, spore sac and annulus', 'Neck, venter and stalk'], 0,
    'The theca is the fertile middle region.'],
  ['In the theca of *Funaria*, the spore sac is separated from the capsule wall by:', ['An air space crossed by green filaments called trabeculae', 'A layer of xylem', 'Solid parenchyma', 'The calyptra'], 0,
    'The trabeculae carry food and water to the spore sac.'],
  ['The columella in the *Funaria* capsule:', ['Is a central sterile tissue that conducts and stores water and food', 'Produces spores', 'Forms the peristome', 'Is absent'], 0,
    'The barrel-shaped spore sac surrounds it.'],
  ['Stomata in the apophysis of *Funaria* are unusual because each has:', ['A single ring-shaped guard cell around the pore', 'Two kidney-shaped guard cells', 'Four subsidiary cells', 'No pore'], 0,
    'The dividing wall of the guard-cell mother cell stays incomplete.'],
  ['The mature *Funaria* capsule is:', ['Pear-shaped, asymmetric and nodding', 'Spherical and erect', 'Cylindrical and green throughout', 'Embedded in the thallus'], 0,
    'It hangs at the top of a long seta.'],
  ['*Funaria hygrometrica* gets its name from:', ['The seta, which twists with changes in humidity', 'Its aquatic habit', 'Its colour', 'Its gemma cups'], 0,
    'It is the "cord moss", common on burnt ground.'],
  ['The calyptra of *Funaria* is:', ['Hood-like (cucullate), split down one side', 'Absent', 'Hairy, as in *Polytrichum*', 'Part of the sporophyte'], 0,
    '*Polytrichum* has a hairy calyptra, hence "hairy-cap moss".'],
  ['The *Funaria* sporophyte is best described as:', ['Partly self-supporting — it photosynthesises but gets water and minerals through the foot', 'Fully independent', 'Wholly parasitic, with no chlorophyll', 'Free-living after the first year'], 0,
    'The green apophysis makes much of its own food.'],
  ['The membranous disc that closes the mouth of a *Polytrichum* capsule beneath its peristome teeth is the:', ['Epiphragm', 'Operculum', 'Annulus', 'Calyptra'], 0,
    'Spores escape through gaps between the teeth around it.'],
  ['The spore sac of *Funaria* develops from the:', ['Outer layer of the endothecium', 'Calyptra', 'Apophysis', 'Seta'], 0,
    'The inner endothecium forms the columella.']
] },
{ p: 'B1', t: 'Bryophytes', w: 3, pyq: ['CSE-2014-B1-m12', 'IFoS-2005-B1-m09', 'CSE-2013-B1-m09', 'IFoS-2001-B1-m13', 'IFoS-2021-B1-m13', 'IFoS-2014-B1-m14', 'IFoS-2013-B1-m12', 'CSE-1985-B1-m16', 'CSE-1994-B1-m03', 'CSE-2002-B1-m02', 'IFoS-2006-B1-m19'], q: [
  ['*Marchantia polymorpha* is:', ['Dioecious, with separate male and female thalli', 'Monoecious with both sex organs on one receptacle', 'Without sex organs', 'Always aquatic'], 0,
    'Sex is determined by U and V sex chromosomes.'],
  ['The antheridiophore of *Marchantia* bears:', ['A stalked, eight-lobed disc with antheridia in cavities on its upper surface', 'Archegonia on its underside', 'Gemma cups', 'Spore capsules'], 0,
    'Rainwater splashing on the disc carries sperms away.'],
  ['On the antheridiophore disc, antheridia develop:', ['In acropetal order — oldest at the centre, youngest at the margin', 'All at once', 'In basipetal order from the margin inwards', 'Only on the stalk'], 0,
    'New antheridia form near the growing margins.'],
  ['The archegoniophore of *Marchantia* has:', ['A stalked disc with finger-like rays, with archegonia hanging neck-down beneath it', 'A flat disc with archegonia on top', 'No stalk', 'Antheridia mixed with archegonia'], 0,
    'Archegonia sit in rows between the rays.'],
  ['The archegonia of *Marchantia* end up on the underside of the disc because:', ['They arise on the upper surface but are turned downwards by growth of the disc’s centre', 'They are formed there from the start', 'The disc is inverted by wind', 'Insects move them'], 0,
    'This is a classic developmental shift.'],
  ['After fertilisation in *Marchantia*, each developing sporophyte is enclosed by a:', ['Pseudoperianth', 'Calyptra only', 'Peristome', 'Columella'], 0,
    'A perichaetium (involucre) encloses each group of archegonia.'],
  ['The capsule wall of the *Marchantia* sporogonium is:', ['One cell thick, with ring-like thickenings', 'Many-layered and green', 'Absent', 'Lignified throughout'], 0,
    'Spores and elaters fill the capsule.'],
  ['The *Marchantia* capsule opens by:', ['Irregular teeth or valves at its tip', 'An operculum', 'Two long valves along its whole length', 'Decay of the thallus'], 0,
    'Elaters then help loosen the spore mass.'],
  ['Antheridia in different liverworts are borne:', ['Sunken in the thallus in *Riccia*, on stalked receptacles in *Marchantia*, and in leaf axils in leafy liverworts', 'Only on stalked receptacles', 'Only inside capsules', 'Only on gemmae'], 0,
    'This variation is a common Mains question.'],
  ['The ventral scales of *Marchantia* are of two kinds:', ['Appendiculate and ligulate', 'Smooth and tuberculate', 'Leafy and amphigastria', 'Hyaline and chlorophyllous'], 0,
    'They protect the growing point and help hold water.']
] },
{ p: 'B1', t: 'Bryophytes', w: 2, pyq: ['IFoS-2005-B1-m10', 'CSE-2012-B1-m09', 'IFoS-2010-B1-m21', 'IFoS-2004-B1-m12'], q: [
  ['In a cross-section of the *Riccia* thallus, the upper region consists of:', ['Vertical rows of green cells separated by narrow air canals', 'Large air chambers with barrel-shaped pores', 'A cuticle-covered epidermis with stomata', 'Xylem and phloem'], 0,
    'The lower region stores food in colourless parenchyma.'],
  ['The *Marchantia* thallus has:', ['Air chambers opening by barrel-shaped pores that cannot close', 'Narrow air canals only', 'True stomata with guard cells', 'No air spaces'], 0,
    'Each pore is ringed by several tiers of cells.'],
  ['The sex organs of *Riccia* are:', ['Embedded in the thallus along its dorsal groove, not on stalked receptacles', 'Borne on antheridiophores and archegoniophores', 'Inside gemma cups', 'On the ventral scales'], 0,
    'This reflects its simple organisation.'],
  ['Vegetative reproduction by gemma cups occurs in:', ['*Marchantia*, but not *Riccia*', '*Riccia*, but not *Marchantia*', 'Both', 'Neither'], 0,
    '*Riccia* spreads by fragmentation and adventitious branches.'],
  ['In the life cycle of *Riccia*, the diploid phase consists of:', ['The zygote and the sporophyte, up to the spore mother cells', 'The thallus', 'The gametes', 'The spores'], 0,
    'Meiosis in spore mother cells restores the haploid phase.'],
  ['The *Riccia* sporophyte is:', ['A capsule embedded in the thallus, with no foot or seta and no elaters', 'Stalked, with elaters', 'Free-living', 'Green with stomata'], 0,
    'Spores are released only when the thallus decays.'],
  ['The ventral scales of *Riccia* are:', ['Simple, in a single row', 'Appendiculate and ligulate', 'Absent', 'Leaf-like in three rows'], 0,
    '*Marchantia* has two kinds of scales in several rows.'],
  ['A floating aquatic species of *Riccia* is:', ['*Riccia fluitans*', '*Riccia glauca*', '*Riccia discolor*', '*Riccia crystallina*'], 0,
    '*Ricciocarpus natans* is another floating liverwort.'],
  ['Compared with *Riccia*, the *Marchantia* sporophyte has:', ['A foot, seta and capsule, with elaters', 'A capsule only', 'No spores', 'An operculum'], 0,
    'It is a step up in sterilisation of sporogenous tissue.'],
  ['The dominant, long-lived generation in both *Riccia* and *Marchantia* is the:', ['Haploid gametophyte (thallus)', 'Diploid sporophyte', 'Protonema', 'Embryo'], 0,
    'The sporophyte lives briefly on the female thallus.']
] },
{ p: 'B1', t: 'Bryophytes', w: 2, pyq: ['CSE-2013-B1-m07', 'IFoS-2000-B1-m11', 'IFoS-2006-B1-m10', 'CSE-2010-B1-m16', 'IFoS-2014-B1-m13', 'CSE-1992-B1-m18', 'CSE-1997-B1-m19', 'CSE-1986-B1-m20', 'CSE-2009-B1-m10', 'CSE-2009-B1-m06', 'CSE-2009-B1-m05'], q: [
  ['The moss gametophyte develops in two stages:', ['A filamentous protonema, then a leafy gametophore', 'A thallus, then a capsule', 'A prothallus, then a cone', 'A seta, then a calyptra'], 0,
    'Buds on the protonema grow into leafy shoots.'],
  ['The moss protonema is heterotrichous: its two kinds of filaments are:', ['Chloronema (cross walls at right angles, many chloroplasts) and caulonema (oblique walls, fewer chloroplasts)', 'Rhizoids and leaves', 'Xylem and phloem', 'Antheridia and archegonia'], 0,
    'Buds for leafy shoots arise mainly on the caulonema.'],
  ['A single moss spore can give rise to:', ['Many leafy gametophores from one protonema', 'Only one gametophore', 'A sporophyte directly', 'A thallus with gemma cups'], 0,
    'This makes mosses spread quickly.'],
  ['*Funaria hygrometrica* is:', ['Monoecious — antheridia at the tip of the main shoot, archegonia on a lateral branch', 'Dioecious', 'Without archegonia', 'Bisexual within each antheridium'], 0,
    'The female branch arises below the male apex.'],
  ['In *Funaria*, the antheridia are mixed with:', ['Paraphyses with swollen terminal cells, inside a rosette of perigonial leaves', 'Elaters', 'Gemmae', 'Spores'], 0,
    'The leafy rosette acts as a splash cup for rain.'],
  ['The archegonial head of *Funaria* is surrounded by:', ['Perichaetial leaves', 'Perigonial leaves', 'A pseudoperianth', 'Ventral scales'], 0,
    'It also contains paraphyses.'],
  ['The archegonium of *Funaria* has:', ['A massive stalk and venter and a long, twisted neck', 'No neck', 'A sunken venter in a thallus', 'A single neck canal cell'], 0,
    'The neck canal cells break down to let sperms in.'],
  ['Moss sperms reach the archegonia:', ['By swimming in water, often helped by rain splash', 'Through a pollen tube', 'Carried by wind', 'Carried by insects only'], 0,
    'Free water is essential for fertilisation.'],
  ['A secondary protonema in mosses arises from:', ['Detached leaves, stems or rhizoids', 'Spores only', 'The capsule wall only', 'Never'], 0,
    'It is a means of vegetative spread.'],
  ['The correct sequence in the *Funaria* life cycle is:', ['Spore → protonema → leafy gametophore → sex organs → zygote → sporophyte → spores', 'Spore → sporophyte → protonema → zygote', 'Zygote → protonema → spore → gametophore', 'Gametophore → spore → zygote → protonema'], 0,
    'Meiosis happens in the capsule as the spores form.']
] },
{ p: 'B1', t: 'Bryophytes', w: 2, pyq: ['CSE-2015-B1-m10', 'IFoS-2007-B1-m09', 'CSE-2003-B1-m10', 'IFoS-2013-B1-m12', 'IFoS-2002-B1-m07', 'CSE-1994-B1-m01'], q: [
  ['The gemmae of *Marchantia* are:', ['Multicellular discs with two lateral notches, formed in cup-shaped receptacles', 'Single-celled spores', 'Diploid buds', 'Underground tubers'], 0,
    'Each notch holds a growing point.'],
  ['Gemmae of *Marchantia* are dispersed mainly by:', ['Raindrops splashing into the gemma cups', 'Wind blowing them out', 'Insects', 'Explosion of the cup'], 0,
    'The cups work as splash cups.'],
  ['The liverwort with crescent-shaped (half-moon) gemma cups is:', ['*Lunularia*', '*Marchantia*', '*Riccia*', '*Pellia*'], 0,
    '*Marchantia* has circular gemma cups.'],
  ['*Riccia* reproduces vegetatively mainly by:', ['Death of older parts, which separates the branches, plus adventitious branches and tubers', 'Gemma cups', 'Bulbils on leaves', 'Spores alone'], 0,
    'Some species form tubers that survive dry periods.'],
  ['Mosses such as *Funaria* reproduce vegetatively by:', ['Secondary protonema and bulbils', 'Gemma cups', 'Adventive embryos', 'Seeds'], 0,
    'Almost any detached part can regrow.'],
  ['In apospory in mosses:', ['Diploid gametophytes grow directly from sporophyte tissue such as the seta, without meiosis', 'A sporophyte forms without fertilisation', 'Spores form without meiosis in the capsule', 'Gemmae become sporophytes'], 0,
    'It can be induced experimentally from wounded setae.'],
  ['When diploid gametophytes from apospory are self-fertilised, the sporophytes produced are:', ['Tetraploid', 'Haploid', 'Diploid', 'Triploid'], 0,
    'The Marchals showed this in mosses in the early 1900s.'],
  ['*Anthoceros* survives dry seasons by forming:', ['Tubers along the thallus margin', 'Gemma cups', 'Bulbils on leaves', 'Seeds'], 0,
    'The tubers grow into new thalli when wet.'],
  ['A germinating *Marchantia* gemma forms rhizoids on:', ['The side touching the soil, and grows from both notches', 'Both surfaces equally', 'Neither side', 'Only the upper side'], 0,
    'Light and gravity decide which side becomes the lower surface.'],
  ['Vegetative reproduction is common in bryophytes because it:', ['Spreads the plant without needing water for fertilisation', 'Needs pollinators', 'Produces new genetic variation', 'Needs a sporophyte'], 0,
    'It is especially useful in dry or uncertain habitats.']
] },
{ p: 'B1', t: 'Bryophytes', w: 2, pyq: ['IFoS-2014-B1-m15', 'CSE-2007-B1-m12', 'CSE-2018-B1-m12', 'IFoS-2013-B1-m13', 'CSE-2005-B1-m11', 'CSE-1998-B1-m14'], q: [
  ['In India, bryophyte diversity is highest in:', ['The Eastern Himalaya and the Western Ghats', 'The Thar desert', 'The Indo-Gangetic plains', 'The Deccan plateau'], 0,
    'Humid montane forests suit them best.'],
  ['Evergreen forests support more bryophytes than deciduous forests because they offer:', ['Continuous shade and humidity', 'Dry, open conditions', 'Frequent fires', 'Saline soils'], 0,
    'Epiphytic mosses and liverworts cover trunks in cloud forests.'],
  ['Bryophytes in deciduous forests survive the dry season mainly by:', ['Tolerating desiccation and reviving when the rains return', 'Shedding leaves like trees', 'Forming seeds', 'Moving to water'], 0,
    'Many mosses dry out completely without dying.'],
  ['The "copper moss" used to indicate copper-rich ground is:', ['*Merceya* (*Scopelophila*) *ligulata*', '*Sphagnum*', '*Funaria*', '*Polytrichum*'], 0,
    'Such mosses tolerate high metal levels.'],
  ['*Sphagnum* growing in a site indicates:', ['Acidic, waterlogged and nutrient-poor conditions', 'Alkaline, dry soil', 'Saline coastal soil', 'Heavily fertilised fields'], 0,
    'It acidifies its own surroundings.'],
  ['Mosses are good biomonitors of atmospheric heavy-metal deposition because they:', ['Take up minerals directly from rain and dust over their surface', 'Have deep roots', 'Have a thick cuticle', 'Never absorb metals'], 0,
    'Metal levels in moss tissue reflect air pollution.'],
  ['The "father of Indian bryology", who wrote on the liverworts of the Western Himalayas and the Punjab plain, is:', ['Shiv Ram Kashyap', 'Birbal Sahni', 'P. Maheshwari', 'R. Misra'], 0,
    'His work appeared in the 1920s and 1930s.'],
  ['Annual species of *Riccia* commonly appear on:', ['Moist soil of fields and banks after the monsoon', 'Tree trunks in deserts', 'Seashores', 'Glaciers'], 0,
    'They complete their life cycle quickly before the soil dries.'],
  ['In Indian forests, epiphytic bryophytes are most abundant in:', ['Montane wet evergreen (cloud) forests', 'Tropical thorn forests', 'Mangroves only', 'Desert scrub'], 0,
    'Constant mist keeps them hydrated.'],
  ['Bryophytes act as indicator plants because they:', ['Respond strongly to soil chemistry, moisture and pollution', 'Grow everywhere equally', 'Are unaffected by the environment', 'Need fertilisers'], 0,
    'Their presence or absence can signal minerals, pH or air quality.']
] },
{ p: 'B1', t: 'Bryophytes', w: 3, pyq: ['CSE-2002-B1-m10', 'CSE-1990-B1-m23', 'CSE-2004-B1-m11', 'IFoS-2022-B1-m10', 'IFoS-2010-B1-m20', 'CSE-2018-B1-m12', 'IFoS-2013-B1-m13', 'CSE-2024-B1-m13', 'CSE-1995-B1-m32', 'CSE-1990-B1-m11', 'CSE-1988-B1-m17'], q: [
  ['*Sphagnum* holds many times its dry weight of water mainly because its leaves have:', ['Large dead hyaline cells with pores and spiral thickenings', 'A thick cuticle', 'Many stomata', 'Waxy scales'], 0,
    'Narrow living green cells lie between the hyaline cells.'],
  ['*Sphagnum* can hold about how many times its dry weight of water?', ['About 20 times', 'About 2 times', 'About 200 times', 'It holds no water'], 0,
    'This is why it is used to pack live plants.'],
  ['During the First World War, *Sphagnum* was used as:', ['Surgical dressing, being absorbent and mildly antiseptic', 'Fuel for ships', 'Food for soldiers', 'Rope'], 0,
    'Its acidic, absorbent tissue resisted infection.'],
  ['Peat, formed mainly from *Sphagnum*, is used as:', ['Fuel and as a soil conditioner in horticulture', 'A building stone', 'A fertiliser rich in nitrogen only', 'Animal fodder'], 0,
    'Ireland and Scotland have long burned peat.'],
  ['"Reindeer moss" is actually:', ['A lichen (*Cladonia rangiferina*)', 'A moss', 'A liverwort', 'A fern'], 0,
    'It is winter food for reindeer and caribou.'],
  ['"Peat moss" refers to:', ['*Sphagnum*', '*Funaria*', '*Polytrichum*', '*Marchantia*'], 0,
    'Its bogs store huge amounts of carbon.'],
  ['*Sphagnum* makes bog water acidic by:', ['Exchanging hydrogen ions for other cations through its cell-wall acids', 'Releasing sulphuric acid', 'Fixing nitrogen', 'Releasing ammonia'], 0,
    'Acidity slows decay, so peat builds up.'],
  ['*Marchantia* was traditionally used against liver ailments because:', ['Its lobed thallus resembled a liver (doctrine of signatures)', 'It contains insulin', 'It fixes nitrogen', 'It is poisonous'], 0,
    'Liverworts get their name from this belief.'],
  ['An indirect use of bryophytes is:', ['Forming soil on rocks and checking erosion', 'Producing timber', 'Producing fibre', 'Producing fruits'], 0,
    'Their mats trap soil and water.'],
  ['Horticulturists use *Sphagnum* as a growing medium for:', ['Orchids and seedlings', 'Cacti only', 'Rice', 'Aquatic weeds'], 0,
    'It is airy, moisture-retentive and nearly sterile.']
] },
{ p: 'B1', t: 'Bryophytes', w: 2, pyq: ['CSE-2019-B1-m11', 'IFoS-2010-B1-m21', 'IFoS-2006-B1-m10', 'CSE-1996-B1-m36', 'CSE-1991-B1-m34', 'IFoS-2024-B1-m06'], q: [
  ['Bryophytes show:', ['Heteromorphic alternation of generations, with a dominant gametophyte', 'Isomorphic alternation', 'A dominant sporophyte', 'No alternation'], 0,
    'The two generations look completely different.'],
  ['The life cycle of a bryophyte is described as:', ['Haplodiplontic', 'Haplontic', 'Diplontic', 'Asexual only'], 0,
    'Both haploid and diploid multicellular phases exist.'],
  ['Meiosis in a bryophyte occurs in:', ['The spore mother cells inside the capsule', 'The antheridia', 'The protonema', 'The gemmae'], 0,
    'This is sporic meiosis.'],
  ['Gametes in bryophytes are formed by:', ['Mitosis in the haploid gametophyte', 'Meiosis in the sporophyte', 'Fusion of spores', 'Budding of the capsule'], 0,
    'The gametophyte is already haploid.'],
  ['Alternation of generations in bryophytes and pteridophytes was first shown by:', ['Wilhelm Hofmeister (1851)', 'Charles Darwin', 'Gregor Mendel', 'Robert Brown'], 0,
    'He compared the life cycles of many plant groups.'],
  ['Compared with pteridophytes, bryophytes differ in that their:', ['Gametophyte is dominant and the sporophyte depends on it', 'Sporophyte is dominant and independent', 'Gametophyte is absent', 'Sporophyte has roots'], 0,
    'Pteridophytes reverse the dominance.'],
  ['Apogamy means:', ['A sporophyte forming from gametophyte cells without fertilisation', 'A gametophyte forming from the sporophyte without meiosis', 'Spore formation without meiosis', 'Two fertilisations'], 0,
    'Apospory is the reverse process.'],
  ['An alga with isomorphic alternation, unlike bryophytes, is:', ['*Ulva*', '*Funaria*', '*Riccia*', '*Marchantia*'], 0,
    'Its two generations look alike.'],
  ['The nutritional link between the two generations in bryophytes is called:', ['Matrotrophy, through placental transfer cells at the foot', 'Parasitism by the gametophyte', 'Independent nutrition', 'Saprophytism'], 0,
    'The mother gametophyte feeds the embryo and sporophyte.'],
  ['In a graphic life cycle of *Riccia*, the stage that marks the change from 2n to n is:', ['Meiosis in the spore mother cells', 'Fertilisation', 'Germination of the spore', 'Formation of sex organs'], 0,
    'Fertilisation marks the change from n back to 2n.']
] }
);
