/* Concept sets for Botany II — Molecular biology. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B2', t: 'Molecular Biology', w: 3, pyq: ['IFoS-2024-B2-m19', 'IFoS-2022-B2-m23', 'CSE-2021-B2-m19', 'IFoS-2020-B2-m19', 'IFoS-2015-B2-m17', 'IFoS-2005-B2-m17', 'CSE-2005-B2-m06', 'CSE-1987-B2-m13', 'CSE-2023-B2-m19', 'CSE-1994-B2-m18', 'IFoS-2007-B2-m17', 'CSE-2020-B2-m16', 'CSE-1989-B2-m17', 'CSE-2015-B2-Q1c'], q: [
  ['Of the 64 codons, the number that code for amino acids is:', ['61', '64', '60', '20'], 0,
    'Three are stop codons — UAA, UAG and UGA.'],
  ['The usual start codon is:', ['AUG, coding methionine', 'UAA', 'GUG only', 'UGA'], 0,
    'In bacteria the first methionine is formylated.'],
  ['The genetic code is described as degenerate because:', ['Most amino acids are coded by more than one codon', 'One codon codes for many amino acids', 'Codons overlap', 'It changes between species'], 0,
    'Leucine, serine and arginine have six codons each; Met and Trp have one.'],
  ['The first codon assigned (UUU = phenylalanine) came from the work of:', ['Nirenberg and Matthaei (1961) using poly-U', 'Watson and Crick', 'Meselson and Stahl', 'Jacob and Monod'], 0,
    'Khorana used synthetic repeating polymers; Nirenberg, Khorana and Holley shared the 1968 Nobel Prize.'],
  ['Crick and Brenner\'s frameshift mutants of phage T4 showed that the code is:', ['Read in non-overlapping triplets from a fixed start', 'Overlapping', 'Read in pairs', 'Read in both directions'], 0,
    'Adding or removing three bases restored function.'],
  ['The wobble hypothesis (Crick, 1966) states that:', ['Pairing at the third codon base is less strict than at the first two', 'The first base of the codon wobbles', 'All tRNAs read all codons', 'Stop codons pair with tRNAs'], 0,
    'This lets one tRNA read several codons.'],
  ['Inosine in the anticodon wobble position can pair with:', ['U, C or A', 'G only', 'A only', 'No base'], 0,
    'It is a modified base in some tRNAs.'],
  ['An exception to the "universal" code is that in mitochondria:', ['UGA codes for tryptophan instead of stop', 'AUG is a stop codon', 'All codons change', 'UUU codes leucine'], 0,
    'Mycoplasma and some ciliates also show changes.'],
  ['The code is "commaless", meaning:', ['There are no punctuation bases between codons', 'There are spacer bases', 'Codons overlap by one base', 'Each gene has commas'], 0,
    'Reading continues codon after codon until a stop.'],
  ['A single codon never codes for two different amino acids, so the code is:', ['Unambiguous', 'Degenerate', 'Overlapping', 'Variable'], 0,
    'Degeneracy is the reverse case — many codons for one amino acid.']
] },
{ p: 'B2', t: 'Molecular Biology', w: 3, pyq: ['IFoS-2024-B2-m21', 'CSE-2019-B2-m22', 'IFoS-2011-B2-m07', 'IFoS-2006-B2-m14', 'CSE-2006-B2-m13', 'CSE-1989-B2-m16', 'CSE-1991-B2-m17'], q: [
  ['Semi-conservative replication was shown by:', ['Meselson and Stahl (1958) using ¹⁵N and CsCl density gradients', 'Hershey and Chase', 'Cairns', 'Okazaki'], 0,
    'After one generation all DNA was hybrid density.'],
  ['DNA replication is semi-discontinuous because:', ['The lagging strand is made in short Okazaki fragments', 'Both strands are made continuously', 'Only one strand is copied', 'Replication stops at random'], 0,
    'Polymerases work only 5′→3′.'],
  ['The enzyme that unwinds DNA at the replication fork is:', ['Helicase', 'Ligase', 'Primase', 'Topoisomerase'], 0,
    'Topoisomerases (gyrase) relieve the supercoiling ahead of the fork.'],
  ['The main replicating polymerase of *E. coli* is:', ['DNA polymerase III', 'DNA polymerase I', 'DNA polymerase II', 'RNA polymerase'], 0,
    'Pol I removes RNA primers and fills the gaps; ligase seals nicks.'],
  ['Replication needs an RNA primer because DNA polymerase:', ['Can only add nucleotides to an existing 3′-OH end', 'Can start chains alone', 'Works 3′→5′', 'Copies RNA only'], 0,
    'Primase makes the short RNA primer.'],
  ['Cairns\'s autoradiographs of *E. coli* DNA showed:', ['Theta-shaped bidirectional replication from one origin', 'Many origins', 'Rolling circles', 'Linear chromosomes'], 0,
    'Eukaryotic chromosomes have many origins (replicons); yeast origins are ARS elements.'],
  ['In eukaryotes, the leading strand is mainly synthesised by:', ['DNA polymerase ε', 'DNA polymerase α', 'DNA polymerase β', 'DNA polymerase γ'], 0,
    'Pol α–primase starts chains; pol δ makes the lagging strand; pol γ copies mtDNA.'],
  ['Telomerase solves the end-replication problem by:', ['Adding telomeric repeats using its own RNA template', 'Removing telomeres', 'Joining Okazaki fragments', 'Unwinding DNA'], 0,
    'It is a reverse transcriptase.'],
  ['Rolling-circle replication is seen in:', ['Some plasmids, phages and viroids', 'Eukaryotic nuclear chromosomes', 'All bacterial chromosomes', 'Chloroplast RNA'], 0,
    'Mitochondrial DNA often replicates via a D-loop.'],
  ['Reverse transcriptase differs from DNA polymerase in that it:', ['Uses an RNA template to make DNA', 'Makes RNA from DNA', 'Needs no primer', 'Works 3′→5′'], 0,
    'RNA polymerase needs no primer; DNA polymerases have 3′→5′ proofreading.']
] },
{ p: 'B2', t: 'Molecular Biology', w: 3, pyq: ['CSE-2014-B2-m17', 'CSE-2012-B2-m21', 'CSE-2011-B2-m24', 'IFoS-2006-B2-m13', 'CSE-1998-B2-m14', 'CSE-1990-B2-m12', 'IFoS-2012-B2-m17', 'CSE-2020-B2-m21', 'CSE-1996-B2-m13'], q: [
  ['The Hershey–Chase experiment (1952) showed that the genetic material of phage T2 is DNA because:', ['³²P-labelled DNA entered the bacteria while ³⁵S-labelled protein stayed outside', 'Protein entered the cells', 'Both entered equally', 'Neither entered'], 0,
    'Avery, MacLeod and McCarty (1944) had shown DNA is the transforming principle.'],
  ['Griffith\'s 1928 experiment with *Streptococcus pneumoniae* showed:', ['Heat-killed virulent cells could transform live harmless cells', 'DNA replicates semi-conservatively', 'Genes are on chromosomes', 'RNA is genetic material'], 0,
    'The transforming substance was identified as DNA later.'],
  ['RNA was shown to be genetic material in TMV by:', ['Fraenkel-Conrat and Singer\'s reconstitution experiments', 'Meselson and Stahl', 'Nirenberg', 'Watson and Crick'], 0,
    'Hybrid viruses produced progeny of the RNA donor type.'],
  ['B-DNA is a right-handed double helix with:', ['About 10 base pairs per turn, a pitch of 3.4 nm and a diameter of 2 nm', '12 base pairs per turn and left-handed', 'A single strand', 'Parallel strands'], 0,
    'Strands are antiparallel, with major and minor grooves.'],
  ['Chargaff\'s rules state that in double-stranded DNA:', ['A = T and G = C', 'A = G and T = C', 'A + T = G + C always', 'All bases are equal'], 0,
    'The A+T : G+C ratio varies between species.'],
  ['Z-DNA is:', ['Left-handed with a zig-zag backbone, favoured by alternating GC sequences', 'Right-handed and wider', 'Single-stranded', 'RNA'], 0,
    'Negative supercoiling during transcription can induce it, suggesting a regulatory role.'],
  ['RNA differs from DNA in having:', ['Ribose with a 2′-OH group and uracil instead of thymine', 'Deoxyribose and thymine', 'Two strands always', 'No phosphate'], 0,
    'The 2′-OH makes RNA less stable.'],
  ['A substance that can serve as hereditary material must be able to:', ['Replicate, store information, express it and change by mutation', 'Only store energy', 'Only form structures', 'Only catalyse reactions'], 0,
    'It must also be chemically stable.'],
  ['The two strands of DNA are held together by:', ['Hydrogen bonds between complementary bases', 'Covalent bonds between bases', 'Ionic bonds with histones', 'Disulphide bridges'], 0,
    'G–C pairs have three hydrogen bonds, A–T pairs two.'],
  ['The DNA double helix model was proposed in 1953 by:', ['Watson and Crick, using X-ray data of Franklin and Wilkins', 'Chargaff', 'Pauling', 'Avery'], 0,
    'Rosalind Franklin\'s Photo 51 was key evidence.']
] },
{ p: 'B2', t: 'Molecular Biology', w: 3, pyq: ['CSE-2025-B2-m17', 'CSE-2022-B2-m21', 'CSE-2019-B2-m23', 'CSE-2012-B2-m25', 'CSE-2023-B2-m20', 'CSE-2012-B2-m26', 'CSE-2003-B2-m14', 'CSE-1996-B2-m11', 'CSE-1989-B2-m15', 'CSE-1985-B2-m10', 'IFoS-2005-B2-m16', 'CSE-2020-B2-m20', 'CSE-2011-B2-m19', 'CSE-2012-B2-m24', 'CSE-2002-B2-m09', 'CSE-2001-B2-m12', 'CSE-1990-B2-m06', 'CSE-2018-B2-m16', 'IFoS-2013-B2-m12', 'CSE-1986-B2-m20', 'CSE-1986-B2-m19', 'IFoS-2014-B2-m03', 'CSE-2014-B2-m01', 'CSE-2010-B2-m01', 'CSE-2022-B2-m01', 'CSE-2020-B2-m01', 'CSE-2018-B2-m02', 'CSE-2016-B2-m01', 'CSE-2016-B2-m02', 'CSE-2014-B2-m03', 'CSE-2017-B2-m03', 'CSE-2019-B2-m02', 'CSE-2026-B2-m14'], q: [
  ['The polymerase chain reaction was invented by:', ['Kary Mullis', 'Frederick Sanger', 'Paul Berg', 'Herbert Boyer'], 0,
    'He shared the 1993 Nobel Prize in Chemistry.'],
  ['The three steps of each PCR cycle, in order, are:', ['Denaturation (~94 °C), annealing (~55 °C), extension (~72 °C)', 'Annealing, denaturation, extension', 'Extension, annealing, denaturation', 'Ligation, cutting, cloning'], 0,
    'The heat-stable *Taq* polymerase comes from *Thermus aquaticus*.'],
  ['PCR primers are:', ['Short single-stranded DNA pieces complementary to the ends of the target', 'Long RNA molecules', 'Restriction enzymes', 'Plasmids'], 0,
    'Usually 18–25 nucleotides; they define what is amplified.'],
  ['Sanger\'s method of DNA sequencing uses:', ['Dideoxynucleotides that stop chain growth', 'Chemical cleavage of bases', 'Restriction enzymes only', 'Hybridisation arrays'], 0,
    'Maxam–Gilbert used chemical cleavage; modern NGS (e.g. Illumina) sequences by synthesis.'],
  ['Shotgun sequencing works by:', ['Breaking the genome into random fragments, sequencing them and assembling by overlaps', 'Sequencing one chromosome end to end', 'Reading proteins', 'Using only RNA'], 0,
    'It was used for many plant genomes.'],
  ['Southern blotting detects:', ['Specific DNA sequences', 'Specific RNA', 'Specific proteins', 'Lipids'], 0,
    'Northern blots detect RNA and Western blots detect proteins.'],
  ['DNA–DNA hybridisation measures relatedness between species from:', ['The melting temperature of hybrid duplexes', 'Leaf shape', 'Chromosome number', 'Protein colour'], 0,
    'Fewer mismatches give more stable hybrids.'],
  ['Restriction enzymes such as *Eco*RI:', ['Cut DNA at specific palindromic sites (GAATTC)', 'Join DNA fragments', 'Copy DNA', 'Cut RNA'], 0,
    'DNA ligase joins the cut fragments into a vector.'],
  ['The first recombinant DNA molecules carried in bacteria were made by:', ['Cohen and Boyer (1973)', 'Mullis', 'Sanger', 'Mendel'], 0,
    'Genetic engineering combines restriction, ligation, vectors and selection.'],
  ['The Flavr Savr tomato was made using:', ['Antisense RNA against polygalacturonase', 'A Bt gene', 'Somaclonal variation', 'Mutation breeding'], 0,
    'Antisense RNA pairs with mRNA and blocks its translation.']
] }
);
