/* Concept sets for Agriculture I — seed and sowing, protected cultivation, plant protection and IPR, and a mixed revision set for PYQs whose wording survives only as a header. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Crop Production', w: 1, pyq: ['IFoS-2012-A1-m24', 'IFoS-2012-A1-m25', 'IFoS-2010-A1-m15', 'IFoS-2004-A1-m08', 'IFoS-2004-A1-m09', 'CSE-2001-A1-m10', 'IFoS-2013-A1-m04'], q: [
  ['Seed replacement rate (SRR) is:', ['The share of crop area sown with fresh certified or quality seed instead of farm-saved seed', 'The seed rate per hectare', 'The germination percentage', 'The rate of seed decay'], 0,
    'Higher SRR generally lifts productivity.'],
  ['Recommended SRR targets are about:', ['25% for self-pollinated, 35% for cross-pollinated crops and 100% for hybrids', '100% for all crops', '5% for all crops', '50% for hybrids'], 0,
    'Hybrid vigour is lost in saved seed, so hybrids need fresh seed each season.'],
  ['A good-quality seed has:', ['High genetic and physical purity, good germination and vigour, and freedom from weeds and disease', 'Large size only', 'High moisture content', 'Mixed varieties'], 0,
    'Safe storage moisture is usually 8–12%.'],
  ['Seed rate needed for a crop depends mainly on:', ['Desired plant population, seed (test) weight and germination percentage', 'Soil colour', 'Market price', 'Day length'], 0,
    'Large-seeded crops such as groundnut need much more seed by weight.'],
  ['Seeds should generally be sown at a depth of about:', ['Two to three times their diameter, in moist, firm soil', 'Ten times their diameter', 'On the soil surface always', 'As deep as possible'], 0,
    'Small seeds are sown shallow.'],
  ['Line sowing with a seed drill is better than broadcasting because it gives:', ['Uniform depth and spacing and allows interculture', 'Random plant stand', 'Higher seed use', 'More weeds'], 0,
    'Ferti-seed drills place fertiliser and seed together.'],
  ['In the Indian seed chain, certified seed is produced from:', ['Foundation seed, which comes from breeder seed', 'Nucleus seed directly', 'Grain from the market', 'Truthfully labelled seed only'], 0,
    'The Seeds Act, 1966 governs seed quality.'],
  ['The only GM crop grown commercially on a large scale in India is:', ['Bt cotton', 'Bt brinjal', 'GM mustard', 'Golden rice'], 0,
    'Time-sensitive: GM mustard DMH-11 received environmental release approval in 2022.'],
  ['GM crops in India are approved by the:', ['Genetic Engineering Appraisal Committee (GEAC)', 'ICAR alone', 'FSSAI alone', 'State agriculture departments'], 0,
    'Concerns include biosafety, gene flow and pest resistance.'],
  ['Direct seeding differs from transplanting in that it:', ['Sows seed straight into the main field without a nursery', 'Raises seedlings in a nursery', 'Uses cuttings', 'Needs puddling always'], 0,
    'It saves labour and water but makes weed control harder.']
] },
{ p: 'A1', t: 'Crop Production', w: 1, pyq: ['CSE-2012-A1-m01', 'CSE-2012-A1-m02', 'CSE-2016-A1-m09', 'CSE-2013-A1-m08', 'IFoS-2016-A1-m20'], q: [
  ['Protected cultivation means:', ['Growing crops under structures such as polyhouses, shade nets or tunnels to control the environment', 'Growing crops in forests', 'Spraying pesticides often', 'Organic farming only'], 0,
    'Temperature, humidity, light and sometimes CO₂ are managed.'],
  ['A main benefit of polyhouse cultivation is:', ['Off-season, high-quality produce with higher yields', 'Lower initial cost', 'No need for irrigation', 'Use only for cereals'], 0,
    'High-value crops like capsicum, tomato, cucumber and cut flowers suit it.'],
  ['A naturally ventilated polyhouse relies on:', ['Roof and side vents to exchange air', 'Air conditioners', 'Fans and pads only', 'Sealed walls'], 0,
    'Fan-and-pad cooling is used in hot dry areas.'],
  ['Low tunnels are mainly used for:', ['Raising early crops such as cucurbits in winter', 'Rice nurseries in summer', 'Storing grain', 'Drying produce'], 0,
    'They trap heat around young plants.'],
  ['Protected cultivation is supported in India under the:', ['Mission for Integrated Development of Horticulture (MIDH)', 'MGNREGA only', 'PMFBY', 'e-NAM'], 0,
    'Subsidies offset high setup costs.'],
  ['Anthurium is grown commercially as a:', ['Cut flower needing shade, high humidity and a porous medium', 'Field cereal', 'Desert shrub', 'Timber tree'], 0,
    'It belongs to Araceae and is propagated by suckers and tissue culture.'],
  ['Citrus decline is caused by:', ['A complex of factors — *Phytophthora*, tristeza, greening, nematodes and nutrient problems', 'Only frost', 'Only over-fertilisation', 'Only birds'], 0,
    'Remedies combine healthy rootstocks, drainage, vector control and balanced nutrition.'],
  ['Citrus greening (huanglongbing) is spread by:', ['The citrus psyllid', 'Aphids only', 'Whiteflies', 'Nematodes'], 0,
    'Citrus tristeza virus is aphid-borne.'],
  ['Drip irrigation in polyhouses helps by:', ['Saving water and allowing fertigation', 'Increasing humidity to harmful levels', 'Wetting leaves', 'Flooding beds'], 0,
    'It also reduces disease.'],
  ['A drawback of polyhouse farming is:', ['High initial investment and need for technical skill', 'No yield gain', 'Need for large land', 'Use only in deserts'], 0,
    'Pest build-up inside also needs management.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 1, pyq: ['IFoS-2013-A1-m28', 'CSE-2012-A1-m03', 'CSE-2012-A1-m04', 'IFoS-2005-A1-m12', 'IFoS-2013-A1-m19', 'IFoS-2012-A1-m07', 'IFoS-2015-A1-m05', 'IFoS-2023-A1-m01', 'CSE-2009-A1-m05'], q: [
  ['Integrated pest management aims to:', ['Keep pests below the economic threshold using all suitable methods together', 'Eradicate all insects', 'Use only pesticides', 'Avoid all control'], 0,
    'It combines cultural, mechanical, biological and need-based chemical methods.'],
  ['The economic threshold level (ETL) is:', ['The pest density at which control should begin to prevent reaching the economic injury level', 'The highest pest level ever seen', 'Zero pests', 'The level at which crops die'], 0,
    'ETL is set below the economic injury level (EIL).'],
  ['India\'s national plant protection organisation is the:', ['Directorate of Plant Protection, Quarantine and Storage, Faridabad', 'ICAR, New Delhi', 'NBPGR only', 'FSSAI'], 0,
    'It enforces the Plant Quarantine Order, 2003.'],
  ['Plant biosecurity is mainly about:', ['Preventing entry, establishment and spread of harmful exotic pests and pathogens', 'Securing farm buildings', 'Crop insurance', 'Seed pricing'], 0,
    'It includes quarantine, surveillance and emergency response.'],
  ['Phytosanitary measures in trade are governed by the WTO:', ['SPS Agreement, with standards from the IPPC', 'TRIPS Agreement', 'Agreement on Agriculture only', 'GATT tariffs only'], 0,
    'Exports need phytosanitary certificates.'],
  ['Disinfection differs from disinfestation in that disinfection:', ['Eliminates a pathogen established within the plant or seed', 'Kills surface insects in stored grain', 'Is fumigation of warehouses', 'Means washing hands'], 0,
    'E.g. hot-water treatment of sugarcane setts; disinfestation removes surface organisms or insects.'],
  ['Plant varieties and farmers\' rights in India are protected under the:', ['PPV&FR Act, 2001', 'Seeds Act, 1966', 'Patents Act only', 'Biological Diversity Act only'], 0,
    'Geographical indications (e.g. Darjeeling tea) protect origin-linked products.'],
  ['Mixed revision — average yield is calculated as:', ['Total production ÷ total area', 'Area ÷ production', 'Production × area', 'Price ÷ area'], 0,
    'Usually expressed in q/ha or t/ha.'],
  ['Mixed revision — Integrated Nutrient Management combines:', ['Fertilisers, organic manures and biofertilisers', 'Only urea', 'Only compost', 'Only biofertilisers'], 0,
    'It sustains yields and soil health.'],
  ['Mixed revision — the main aim of soil and water conservation is to:', ['Reduce runoff and erosion and keep moisture in the soil', 'Increase runoff', 'Remove topsoil', 'Drain all water'], 0,
    'Contour bunding, terracing and vegetative barriers are common measures.']
] }
);
