/* Concept sets for Botany I — Plant anatomy and embryology. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Plant Anatomy', w: 3, pyq: ['CSE-2005-B1-m07', 'CSE-1985-B1-m06', 'CSE-2004-B1-m03', 'CSE-2024-B1-m06', 'CSE-2018-B1-m01', 'CSE-2016-B1-m03', 'CSE-2004-B1-m02', 'CSE-1993-B1-m02', 'CSE-2011-B1-m02', 'CSE-1993-B1-m04', 'CSE-1991-B1-m13', 'CSE-1986-B1-m03', 'CSE-1989-B1-m16', 'CSE-1999-B1-m01', 'CSE-1989-B1-m14'], q: [
  ['In a dicot stem, the complete cambial ring forms when:', ['Fascicular cambium joins interfascicular cambium formed from medullary-ray parenchyma', 'The pericycle divides', 'The epidermis becomes meristematic', 'Pith cells divide'], 0,
    'Interfascicular cambium is a secondary meristem formed by dedifferentiation.'],
  ['Fusiform initials of the vascular cambium give rise to:', ['Axial elements — vessels, tracheids, fibres and sieve elements', 'Ray cells only', 'Cork', 'Root hairs'], 0,
    'Ray initials, short and isodiametric, form the vascular rays.'],
  ['The vascular cambium produces:', ['More secondary xylem inward than secondary phloem outward', 'Only phloem', 'Equal xylem and phloem', 'Only xylem'], 0,
    'Old phloem is crushed while xylem accumulates as wood.'],
  ['The circumference of the cambium increases by:', ['Anticlinal divisions of its initials', 'Periclinal divisions only', 'Cell death', 'Fusion of cells'], 0,
    'Periclinal divisions add cells to xylem and phloem.'],
  ['In a dicot root, the vascular cambium arises from:', ['Conjunctive parenchyma inside the phloem and pericycle opposite the protoxylem', 'The endodermis', 'The epidermis', 'Pith'], 0,
    'It is wavy at first and becomes circular.'],
  ['Protoxylem differs from metaxylem in having:', ['Narrow elements with annular or spiral thickenings, formed first', 'Wide pitted vessels formed later', 'Sieve plates', 'No lignin'], 0,
    'Protoxylem stretches with growing organs.'],
  ['Xylem in stems is endarch, meaning:', ['Protoxylem lies towards the centre and maturation is centrifugal', 'Protoxylem lies towards the periphery', 'Protoxylem is in the middle of metaxylem', 'There is no protoxylem'], 0,
    'Roots are exarch with centripetal development; mesarch occurs in some ferns.'],
  ['Protophloem is:', ['The first-formed phloem, short-lived and often crushed', 'Phloem formed by cambium', 'Phloem with companion cells only in roots', 'Secondary phloem'], 0,
    'Metaphloem matures later and lasts in organs without secondary growth.'],
  ['In the root–stem transition region (hypocotyl), the vascular system changes from:', ['Radial exarch bundles to collateral endarch bundles', 'Collateral to radial', 'Amphivasal to amphicribral', 'Polystele to protostele'], 0,
    'Xylem strands split, twist and invert through the transition.'],
  ['Secondary growth in *Pinus* stem differs from dicots mainly in that its wood has:', ['Tracheids but no vessels', 'Vessels but no tracheids', 'No rays', 'No growth rings'], 0,
    'The cambium itself behaves as in dicots.']
] },
{ p: 'B1', t: 'Plant Anatomy', w: 3, pyq: ['IFoS-2003-B1-m08', 'CSE-1998-B1-m10', 'CSE-1992-B1-m08', 'CSE-2010-B1-m08', 'CSE-1989-B1-m07', 'CSE-1992-B1-m11', 'CSE-2025-B1-m14', 'IFoS-2009-B1-m05', 'CSE-1994-B1-m10', 'CSE-2016-B1-m06', 'CSE-1989-B1-m06', 'IFoS-2001-B1-m03', 'CSE-1993-B1-m13', 'CSE-1992-B1-m24', 'CSE-1994-B1-m20', 'IFoS-2016-B1-Q5f', 'IFoS-2016-B1-Q5b'], q: [
  ['Heartwood differs from sapwood in that heartwood:', ['Is dead, darker and filled with tannins, resins and tyloses', 'Conducts most water', 'Is outermost', 'Contains living parenchyma throughout'], 0,
    'It is more durable; sapwood is the outer functional wood.'],
  ['Tyloses are:', ['Balloon-like outgrowths of parenchyma that block vessels through pits', 'Crystals in fibres', 'Resin ducts', 'Callus on sieve plates'], 0,
    'They form during heartwood formation and after injury.'],
  ['Ring-porous wood has:', ['Large vessels concentrated in early wood', 'Uniform vessels across the growth ring', 'No vessels', 'Vessels only in late wood'], 0,
    'E.g. teak, oak. Diffuse-porous woods (e.g. maple, poplar) have even vessels.'],
  ['Early (spring) wood differs from late (autumn) wood in having:', ['Wider, thinner-walled cells and lower density', 'Narrow, thick-walled cells', 'No vessels', 'Darker colour'], 0,
    'The boundary between the two marks an annual ring.'],
  ['Seasoning of wood means:', ['Lowering its moisture content to prevent warping, splitting and decay', 'Painting it', 'Soaking it in water permanently', 'Burning its surface'], 0,
    'Air seasoning is slow; kiln seasoning is quick and controlled.'],
  ['Paratracheal axial parenchyma is:', ['Associated with vessels, e.g. vasicentric or aliform', 'Scattered without contact with vessels', 'Found only in rays', 'Absent in dicots'], 0,
    'Apotracheal parenchyma (diffuse, banded) is independent of vessels.'],
  ['Storied (stratified) wood results from:', ['Cambial initials arranged in horizontal tiers', 'Many growth rings', 'Absence of rays', 'Fungal infection'], 0,
    'It gives ripple marks on the tangential face.'],
  ['A vessel differs from a tracheid in that a vessel:', ['Is a tube of cells joined end to end through perforation plates', 'Is a single imperforate cell', 'Has living contents', 'Lacks lignin'], 0,
    'Tracheids pass water through pits only.'],
  ['Vessel-less angiosperms include:', ['*Drimys* (Winteraceae) and *Trochodendron*', '*Quercus* and *Tectona*', '*Zea* and *Oryza*', '*Cucurbita* and *Luffa*'], 0,
    'Their wood resembles gymnosperm wood; *Amborella* also lacks vessels.'],
  ['Bast fibres, such as jute and flax, come from the:', ['Phloem (or pericycle)', 'Secondary xylem', 'Seed coat', 'Leaf mesophyll'], 0,
    'Wood fibres (libriform) are part of the xylem.']
] },
{ p: 'B1', t: 'Plant Anatomy', w: 2, pyq: ['CSE-1998-B1-m05', 'CSE-1987-B1-m03', 'CSE-2000-B1-m05', 'CSE-2007-B1-m09', 'CSE-1990-B1-m13', 'CSE-2015-B1-m08', 'IFoS-2018-B1-Q5c', 'IFoS-2016-B1-m02', 'IFoS-2010-B1-m09', 'CSE-2009-B1-m08', 'CSE-1994-B1-m11', 'IFoS-2020-B1-m08', 'CSE-1986-B1-m05', 'CSE-1998-B1-m11', 'IFoS-2005-B1-m18', 'IFoS-2007-B1-m13', 'IFoS-2005-B1-m19'], q: [
  ['In *Dracaena*, secondary growth occurs because:', ['A cambium forms outside the primary bundles and produces secondary bundles and tissue inward', 'Fascicular cambium joins as in dicots', 'The pith divides', 'Phellogen forms xylem'], 0,
    'It is an extra-fascicular cambium in the cortex.'],
  ['Secondary bundles of *Dracaena* are usually:', ['Amphivasal — xylem surrounding phloem', 'Amphicribral', 'Radial', 'Bicollateral'], 0,
    'Amphicribral bundles (phloem round xylem) are typical of ferns.'],
  ['A monocot stem typically has:', ['Scattered closed collateral bundles with bundle sheaths and no cambium', 'A ring of open bundles', 'Radial bundles', 'Bicollateral bundles in a ring'], 0,
    'Maize bundles show a water cavity at the protoxylem.'],
  ['Bicollateral vascular bundles occur in:', ['Cucurbitaceae and Solanaceae', 'Poaceae', 'Ferns', 'Roots of all plants'], 0,
    'Phloem lies on both sides of the xylem.'],
  ['A monocot root differs from a dicot root in having:', ['Many xylem bundles (polyarch) and a large pith, without secondary growth', 'Two to six xylem bundles', 'Secondary growth', 'No pith ever'], 0,
    'Dicot roots are diarch to hexarch with little or no pith.'],
  ['Which monocots show secondary growth from a cambium?', ['*Dracaena*, *Yucca*, *Agave* and *Cordyline*', 'Wheat and rice', 'Banana and ginger', 'Onion and garlic'], 0,
    'Palms thicken by a primary thickening meristem and diffuse growth instead.'],
  ['Cortical vascular bundles are found in:', ['*Nyctanthes*', '*Helianthus*', '*Zea*', '*Pinus*'], 0,
    'They form from leaf traces running through the cortex.'],
  ['Medullary (pith) bundles are found in:', ['*Boerhaavia* and *Achyranthes*', '*Cucurbita*', '*Triticum*', '*Pinus*'], 0,
    'An example of anomalous primary structure.'],
  ['A closed vascular bundle is one that:', ['Has no cambium between xylem and phloem', 'Has a cambium strip', 'Has no phloem', 'Has no xylem'], 0,
    'Typical of monocots; dicot stem bundles are open.'],
  ['Palm trunks thicken mainly through:', ['A primary thickening meristem and sustained growth of ground tissue', 'Vascular cambium', 'Cork cambium', 'Intercalary meristems only'], 0,
    'They reach full width before height growth.']
] },
{ p: 'B1', t: 'Plant Anatomy', w: 2, pyq: ['IFoS-2024-B1-m07', 'IFoS-2010-B1-m04', 'CSE-2007-B1-m04', 'IFoS-2022-B1-m03', 'IFoS-2004-B1-m07', 'IFoS-2000-B1-m02', 'CSE-1994-B1-m09', 'CSE-2022-B1-m07', 'CSE-2018-B1-m07', 'CSE-1989-B1-m15', 'IFoS-2023-B1-m03', 'IFoS-2010-B1-m05', 'CSE-1994-B1-m06', 'CSE-1999-B1-m13', 'IFoS-2012-B1-m25', 'CSE-2011-B1-Q8c', 'IFoS-2009-B1-Q5d'], q: [
  ['Anomocytic (ranunculaceous) stomata have:', ['No distinct subsidiary cells', 'Two subsidiaries parallel to the guard cells', 'Three unequal subsidiaries', 'Two subsidiaries at right angles'], 0,
    'Paracytic: parallel (Rubiaceae); anisocytic: three unequal (Brassicaceae); diacytic: right angles (Caryophyllaceae).'],
  ['Stomata with three subsidiary cells, one smaller than the other two, are:', ['Anisocytic', 'Paracytic', 'Diacytic', 'Anomocytic'], 0,
    'Typical of crucifers.'],
  ['Guard cells of grasses are:', ['Dumb-bell shaped with subsidiary cells', 'Kidney-shaped without subsidiaries', 'Absent', 'Circular'], 0,
    'Dicot guard cells are bean-shaped.'],
  ['Guard cells bow apart on gaining turgor because:', ['Radially arranged cellulose microfibrils and a thicker inner wall restrict their expansion', 'They lose water', 'Their walls are uniform', 'They lack chloroplasts'], 0,
    'This is radial micellation.'],
  ['Mesogenous stomata are those in which:', ['Subsidiary cells come from the same meristemoid as the guard cells', 'Subsidiary cells come from neighbouring cells', 'There are no subsidiaries', 'Guard cells are sunken'], 0,
    'Perigenous: subsidiaries from other cells; mesoperigenous: mixed.'],
  ['Hydathodes are:', ['Water pores at leaf margins that release liquid water (guttation)', 'Stomata on roots', 'Glands secreting nectar', 'Lenticels'], 0,
    'They lie over loose epithem tissue and stay open.'],
  ['An isobilateral leaf, as in maize, usually has stomata:', ['On both surfaces', 'Only on the upper surface', 'Only on the lower surface', 'None'], 0,
    'Dorsiventral dicot leaves have most stomata on the lower side.'],
  ['The periderm is made of:', ['Phellem (cork), phellogen and phelloderm', 'Epidermis and cuticle', 'Xylem and phloem', 'Cortex and pith'], 0,
    'Phellogen forms cork outward and phelloderm inward.'],
  ['Lenticels are:', ['Loose-celled openings in the periderm for gas exchange', 'Water pores', 'Resin ducts', 'Glands'], 0,
    'They usually form below former stomata.'],
  ['In monocots that form cork, such as *Cordyline*, it is often:', ['"Storied cork" from layered divisions of cortical cells', 'From a regular phellogen as in dicots', 'Absent', 'Made by the epidermis only'], 0,
    'Most monocots form little periderm.']
] },
{ p: 'B1', t: 'Plant Anatomy', w: 2, pyq: ['IFoS-2021-B1-m05', 'CSE-2018-B1-m02', 'CSE-1995-B1-m04', 'CSE-1991-B1-m08', 'CSE-1988-B1-m02', 'CSE-2019-B1-m04', 'IFoS-2006-B1-m02', 'IFoS-2004-B1-m06', 'IFoS-2019-B1-m05', 'CSE-2023-B1-m07', 'CSE-2002-B1-m13', 'CSE-1990-B1-m12'], q: [
  ['Kranz anatomy refers to:', ['A wreath of chloroplast-rich bundle-sheath cells around each vein, ringed by mesophyll', 'Palisade on both sides of the leaf', 'Sunken stomata', 'Air spaces in the cortex'], 0,
    '"Kranz" is German for wreath.'],
  ['In NADP-ME type C₄ plants such as maize, bundle-sheath chloroplasts are:', ['Large and agranal (few or no grana)', 'Small and granal', 'Absent', 'Identical to mesophyll ones'], 0,
    'Mesophyll chloroplasts are granal.'],
  ['A C₄ dicot is:', ['*Amaranthus*', '*Triticum*', '*Pisum*', '*Helianthus*'], 0,
    'Others: *Portulaca*, *Salsola*, some *Euphorbia* and *Atriplex*.'],
  ['In C₄ leaves, the first CO₂-fixing enzyme in mesophyll cells is:', ['PEP carboxylase', 'RuBisCO', 'Carbonic anhydrase only', 'PEP carboxykinase'], 0,
    'RuBisCO works in the bundle sheath.'],
  ['C₄ leaves have closely spaced veins, usually with:', ['Only a few mesophyll cells between bundle sheaths', 'Many layers of mesophyll between veins', 'No veins', 'Veins only at the margin'], 0,
    'Short interveinal distance speeds metabolite exchange.'],
  ['Exchange of C₄ acids between mesophyll and bundle sheath happens through:', ['Abundant plasmodesmata', 'Stomata', 'Xylem vessels', 'Sieve tubes'], 0,
    'A suberised lamella in bundle-sheath walls cuts CO₂ leakage in many types.'],
  ['A typical C₃ dicot leaf has:', ['Palisade and spongy mesophyll without a prominent chlorenchymatous bundle sheath', 'Kranz anatomy', 'No mesophyll', 'Only spongy tissue'], 0,
    'Its bundle-sheath cells have few chloroplasts.'],
  ['Kranz anatomy is common in:', ['Poaceae, Cyperaceae and Amaranthaceae', 'Fabaceae', 'Rosaceae', 'Pinaceae'], 0,
    'C₄ evolved many times independently.'],
  ['A main advantage of C₄ plants is:', ['Little photorespiration and higher water-use efficiency in heat', 'Better growth in cold shade', 'No need for light', 'No stomata'], 0,
    'CO₂ is concentrated around RuBisCO.'],
  ['Kranz anatomy was linked to the C₄ pathway after the work of:', ['Hatch and Slack (1966)', 'Calvin and Benson', 'Hill', 'Blackman'], 0,
    'Earlier anatomists had described the wreath layout.']
] },
{ p: 'B1', t: 'Plant Anatomy', w: 3, pyq: ['CSE-2004-B1-m25', 'CSE-1997-B1-m13', 'CSE-1990-B1-m33', 'CSE-1986-B1-m26', 'IFoS-2005-B1-m06', 'IFoS-2010-B1-m03', 'IFoS-2009-B1-m03', 'CSE-2006-B1-m01', 'CSE-2010-B1-m04', 'IFoS-2009-B1-m19'], q: [
  ['The tunica–corpus theory was proposed by:', ['Schmidt (1924)', 'Hanstein (1868)', 'Clowes (1956)', 'Schüepp (1917)'], 0,
    'Tunica: outer layers with anticlinal divisions; corpus: inner core dividing in all planes.'],
  ['Tunica layers mainly divide:', ['Anticlinally, adding surface area', 'Periclinally, adding volume', 'Randomly', 'Not at all'], 0,
    'The corpus adds bulk.'],
  ['Hanstein\'s histogen theory recognises:', ['Dermatogen, periblem and plerome', 'Tunica and corpus', 'Körper and Kappe', 'Central and peripheral zones'], 0,
    'They were said to give epidermis, cortex and stele.'],
  ['The quiescent centre of the root apex is:', ['A group of slowly dividing cells between the root cap and the active meristem', 'The root cap', 'The zone of elongation', 'A dead core'], 0,
    'Clowes (1956); it acts as a reserve of initials.'],
  ['Evidence for the quiescent centre came from:', ['Low uptake of labelled thymidine (little DNA synthesis)', 'High division rate', 'Presence of chloroplasts', 'Root hair formation'], 0,
    'It can reactivate if the meristem is damaged.'],
  ['Zonation of the shoot apex (central mother cells, peripheral zone, rib meristem) was described especially in:', ['Gymnosperms (Foster)', 'Algae', 'Mosses', 'Fungi'], 0,
    'Leaf primordia arise from the peripheral zone.'],
  ['The Körper–Kappe theory explains the organisation of the:', ['Root apex', 'Shoot apex', 'Embryo sac', 'Anther'], 0,
    'Based on the T-divisions of cells (Schüepp).'],
  ['In grasses, the root cap arises from a separate layer called the:', ['Calyptrogen', 'Dermatogen', 'Phellogen', 'Pericycle'], 0,
    'In many dicots the root cap and epidermis share initials.'],
  ['Polarity in differentiation means:', ['Unequal distribution of materials and signals along an axis that sets top and bottom', 'Equal growth in all directions', 'Loss of cell wall', 'Random division'], 0,
    'Seen in the *Fucus* zygote and polar auxin transport.'],
  ['Differentiation of a tracheary element ends with:', ['Secondary wall lignification and programmed cell death', 'Formation of chloroplasts', 'Cell division', 'Formation of a nucleus'], 0,
    'The *Zinnia* mesophyll system shows it in culture with auxin and cytokinin.']
] },
{ p: 'B1', t: 'Plant Anatomy', w: 2, pyq: ['CSE-2009-B1-m20', 'CSE-1990-B1-m08', 'CSE-1998-B1-m18', 'CSE-1989-B1-m28', 'CSE-2002-B1-m17', 'CSE-1987-B1-m04', 'CSE-1992-B1-m06', 'CSE-1994-B1-m12', 'CSE-2009-B1-m12', 'CSE-1985-B1-m22', 'IFoS-2012-B1-m20', 'CSE-1998-B1-m15', 'CSE-1991-B1-m19', 'CSE-2009-B1-m14', 'IFoS-2005-B1-m20'], q: [
  ['Plasmodesmata are:', ['Cytoplasmic channels through cell walls, with a central desmotubule of ER', 'Pores in the nuclear envelope', 'Gaps between cells filled with air', 'Pits in xylem only'], 0,
    'They link cells into the symplast.'],
  ['Secondary plasmodesmata differ from primary ones in that they:', ['Form across walls after cell division', 'Form at the cell plate during division', 'Are dead', 'Contain no ER'], 0,
    'Viruses use movement proteins to widen them.'],
  ['Ectodesmata (teichodes) are:', ['Wall pores in outer epidermal walls, not true cytoplasmic links', 'Same as plasmodesmata', 'Stomata', 'Pits'], 0,
    'They may help absorb sprayed solutions.'],
  ['Medullary rays function mainly in:', ['Radial transport and storage', 'Vertical conduction of water', 'Support only', 'Photosynthesis'], 0,
    'Primary rays run from pith to cortex; secondary rays end within wood.'],
  ['According to Schwendener, stems place mechanical tissue:', ['Towards the periphery, to resist bending', 'At the centre, to resist pulling', 'Randomly', 'Only in leaves'], 0,
    'Roots, which resist pulling, have a central core.'],
  ['The I-girder principle in leaves and stems refers to:', ['Strands of sclerenchyma on both sides of a bundle linked by vascular tissue', 'Hollow pith', 'Thick cuticle', 'Cork layers'], 0,
    'It gives maximum strength with minimum material.'],
  ['Velamen differs from exodermis in that velamen is:', ['A multi-layered dead epidermis that absorbs water in aerial roots', 'A living suberised outer cortex', 'A cork layer', 'An endodermis'], 0,
    'Exodermis replaces the lost epidermis in older roots.'],
  ['A trilacunar node has:', ['Three leaf gaps for three leaf traces', 'One leaf gap', 'Many gaps', 'No gaps'], 0,
    'Sinnott classified nodes into unilacunar, trilacunar and multilacunar.'],
  ['Nodal anatomy is useful in taxonomy because:', ['The node type is fairly constant within families', 'It changes with weather', 'It is identical in all plants', 'It is visible to the naked eye'], 0,
    'The unilacunar two-trace node has been argued as primitive.'],
  ['A megaphyll differs from a microphyll in having:', ['Branched veins and a leaf gap in the stele', 'One unbranched vein and no leaf gap', 'No veins', 'A ligule'], 0,
    'Microphylls are typical of Lycopsida.']
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 3, pyq: ['IFoS-2023-B1-m06', 'IFoS-2013-B1-m05', 'CSE-2009-B1-m09', 'IFoS-2007-B1-m03', 'CSE-2006-B1-m03', 'CSE-1996-B1-m05', 'CSE-1994-B1-m08', 'CSE-1993-B1-m06', 'CSE-1987-B1-m05', 'CSE-2012-B1-m04', 'IFoS-2003-B1-m06', 'CSE-1999-B1-m02', 'CSE-1986-B1-m04', 'CSE-1995-B1-m05', 'IFoS-2010-B1-m07', 'CSE-2019-B1-m10', 'CSE-2022-B1-m10', 'CSE-2016-B1-m22', 'CSE-2021-B1-m08', 'CSE-2003-B1-m05', 'IFoS-2014-B1-m05', 'CSE-2011-B1-m03', 'IFoS-2005-B1-m04', 'IFoS-2006-B1-m02', 'CSE-2010-B1-m11', 'IFoS-2019-B1-m02', 'IFoS-2012-B1-m06', 'CSE-1997-B1-m04', 'IFoS-2012-B1-m26'], q: [
  ['The most common type of embryo sac in angiosperms is the:', ['*Polygonum* type — monosporic, 8-nucleate and 7-celled', '*Allium* type', '*Peperomia* type', '*Oenothera* type'], 0,
    'It occurs in about 70% of studied species.'],
  ['The *Oenothera* type embryo sac is:', ['Monosporic and 4-nucleate', 'Bisporic and 8-nucleate', 'Tetrasporic and 16-nucleate', 'Monosporic and 8-nucleate'], 0,
    'It develops from the micropylar megaspore and has no antipodals.'],
  ['The *Allium* type embryo sac is:', ['Bisporic and 8-nucleate', 'Monosporic and 8-nucleate', 'Tetrasporic and 16-nucleate', 'Monosporic and 4-nucleate'], 0,
    'Two of the four megaspore nuclei take part.'],
  ['A 16-nucleate tetrasporic embryo sac is found in:', ['*Peperomia*', '*Polygonum*', '*Oenothera*', '*Allium*'], 0,
    '*Penaea* and *Drusa* types are also 16-nucleate; *Fritillaria* and *Plumbago* are 8-nucleate tetrasporic.'],
  ['The *Plumbago* type embryo sac is unusual in that it:', ['Lacks synergids', 'Has no egg', 'Has 16 antipodals', 'Is monosporic'], 0,
    'It is tetrasporic with four polar nuclei.'],
  ['Megasporogenesis differs from megagametogenesis in that megasporogenesis:', ['Forms megaspores by meiosis of the megaspore mother cell', 'Forms the embryo sac from the functional megaspore', 'Is the formation of pollen', 'Is fertilisation'], 0,
    'Megagametogenesis follows, forming the female gametophyte.'],
  ['The filiform apparatus of synergids:', ['Guides and receives the pollen tube', 'Stores starch', 'Forms the endosperm', 'Becomes the seed coat'], 0,
    'Synergids secrete attractant peptides (LUREs); one degenerates when the tube enters.'],
  ['The egg apparatus consists of:', ['The egg and two synergids', 'Three antipodals', 'Two polar nuclei', 'The egg alone'], 0,
    'It lies at the micropylar end.'],
  ['The most common ovule type in angiosperms is:', ['Anatropous', 'Orthotropous', 'Circinotropous', 'Amphitropous'], 0,
    'Orthotropous: *Polygonum*, *Piper*; circinotropous: *Opuntia*.'],
  ['A crassinucellate ovule has:', ['Several layers of nucellus around the embryo sac', 'A single layer of nucellus', 'No nucellus', 'No integument'], 0,
    'Tenuinucellate ovules, with thin nucellus, are common in Sympetalae.']
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 3, pyq: ['IFoS-2002-B1-m04', 'CSE-2012-B1-m05', 'CSE-1986-B1-m27', 'CSE-1985-B1-m21', 'CSE-1993-B1-m05', 'IFoS-2011-B1-m01', 'IFoS-2004-B1-m09', 'CSE-1995-B1-m03', 'IFoS-2016-B1-m03', 'CSE-2010-B1-m03', 'IFoS-2021-B1-m16', 'CSE-1998-B1-m16', 'CSE-2011-B1-Q6a'], q: [
  ['From outside inward, the anther wall layers are:', ['Epidermis, endothecium, middle layers, tapetum', 'Tapetum, endothecium, epidermis, middle layers', 'Endothecium, epidermis, tapetum, middle layers', 'Middle layers, tapetum, epidermis, endothecium'], 0,
    'Fibrous thickenings of the endothecium help dehiscence.'],
  ['The tapetum mainly:', ['Nourishes the developing microspores and supplies wall materials', 'Causes dehiscence', 'Protects the anther from insects', 'Forms the pollen tube'], 0,
    'Types: secretory (glandular) and amoeboid (periplasmodial).'],
  ['Microspore tetrads of dicots usually form by:', ['Simultaneous cytokinesis after meiosis', 'Successive cytokinesis', 'Mitosis', 'Budding'], 0,
    'Monocots usually show successive division; tetrads may be tetrahedral, isobilateral and others.'],
  ['The exine of the pollen wall is made mainly of:', ['Sporopollenin', 'Cellulose', 'Pectin only', 'Lignin'], 0,
    'The intine is pecto-cellulosic; exine is absent at germ pores.'],
  ['Exine development begins with a template called the:', ['Primexine', 'Intine', 'Callose wall only', 'Nexine'], 0,
    'Sporopollenin from the tapetum (Ubisch bodies) is laid on it.'],
  ['The "male germ unit" is:', ['The two sperm cells physically linked with the vegetative nucleus', 'The anther wall', 'The tapetum', 'The generative cell alone'], 0,
    'It moves as one unit in the pollen tube.'],
  ['In Cyperaceae, pollen is "pseudomonad" because:', ['Only one of the four meiotic nuclei forms a pollen grain', 'Each microspore forms four pollen grains', 'Pollen forms in tetrads', 'Pollen lacks exine'], 0,
    'The other three nuclei degenerate.'],
  ['Pollen of grasses and crucifers is usually shed at the:', ['Three-celled stage', 'Two-celled stage', 'Single-celled stage', 'Four-celled stage'], 0,
    'Most angiosperms shed two-celled pollen.'],
  ['Cytoplasmic male sterility is caused mainly by:', ['Mitochondrial genes, often leading to tapetal failure', 'Chloroplast genes only', 'Nuclear genes only', 'Viral infection'], 0,
    'It is used to produce hybrid seed.'],
  ['In the dicot type of anther wall formation, the primary parietal layer gives rise to:', ['Endothecium, middle layers and tapetum', 'Epidermis only', 'Sporogenous tissue', 'Connective'], 0,
    'The archesporium divides into primary parietal and primary sporogenous layers.']
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 3, pyq: ['IFoS-2013-B1-m03', 'IFoS-2009-B1-m09', 'IFoS-2004-B1-m08', 'CSE-2001-B1-m04', 'CSE-1998-B1-m07', 'CSE-1998-B1-m06', 'CSE-1996-B1-m01', 'IFoS-2024-B1-m11', 'IFoS-2020-B1-m06', 'CSE-1985-B1-m10', 'CSE-1998-B1-m08'], q: [
  ['Double fertilisation was discovered by:', ['Nawaschin (1898) in *Lilium* and *Fritillaria*', 'Strasburger (1884)', 'Hofmeister (1849)', 'Maheshwari (1950)'], 0,
    'Guignard confirmed it in 1899.'],
  ['Triple fusion is the fusion of:', ['The second male gamete with the two polar nuclei', 'Egg with male gamete', 'Two synergids', 'Antipodals with the egg'], 0,
    'It gives the triploid primary endosperm nucleus.'],
  ['Entry of the pollen tube through the chalaza (chalazogamy) was first seen in:', ['*Casuarina*', '*Cucurbita*', '*Lilium*', '*Zea*'], 0,
    'Porogamy (through the micropyle) is common; mesogamy (through integument) occurs in *Cucurbita*.'],
  ['Inside the embryo sac, the pollen tube discharges into:', ['One of the synergids', 'The egg', 'An antipodal', 'The central cell directly'], 0,
    'The receiving synergid degenerates.'],
  ['In sporophytic pollen–stigma recognition, the recognition proteins lie in the:', ['Exine, coming from the tapetum', 'Intine', 'Generative cell', 'Tube nucleus'], 0,
    'Gametophytic recognition uses intine proteins from the pollen itself.'],
  ['Stigmas of grasses and crucifers are:', ['Dry, with a protein pellicle but no free secretion', 'Wet with copious exudate', 'Absent', 'Hollow'], 0,
    'Wet stigmas occur in Solanaceae and many others.'],
  ['Intra-ovarian pollination involves:', ['Injecting pollen directly into the ovary to bypass stigma and style barriers', 'Hand pollination of the stigma', 'Pollen storage', 'Spraying hormones'], 0,
    'Maheshwari and Kanta used it in *Papaver* and *Argemone*.'],
  ['"Test-tube fertilisation" (in vitro pollination) was first achieved by:', ['Kanta (1960), by placing pollen on cultured ovules', 'Haberlandt', 'Skoog', 'Guha and Maheshwari'], 0,
    'It helps overcome incompatibility barriers.'],
  ['Growth of the pollen tube is:', ['Tip growth guided by chemical signals and a calcium gradient', 'Uniform growth along its length', 'Growth by cell division', 'Passive drift'], 0,
    'Ovule-secreted peptides attract the tube.'],
  ['Double fertilisation results in:', ['A diploid zygote and a triploid primary endosperm nucleus', 'Two zygotes', 'Only endosperm', 'A haploid embryo'], 0,
    'It is a hallmark of angiosperms.']
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 2, pyq: ['CSE-1996-B1-m03', 'CSE-2020-B1-m10', 'IFoS-2021-B1-m12', 'IFoS-2004-B1-m09', 'CSE-2025-B1-m09', 'CSE-1989-B1-m05', 'CSE-1987-B1-m02', 'CSE-1990-B1-m09', 'CSE-1989-B1-m10', 'IFoS-2012-B1-m03', 'IFoS-2022-B1-m04', 'IFoS-2013-B1-m21', 'IFoS-2011-B1-m16', 'IFoS-2007-B1-m14'], q: [
  ['In the *Capsella* (Crucifer) type, the first division of the zygote gives:', ['A terminal cell and a basal cell', 'Two equal embryo cells', 'Four cells', 'A free-nuclear stage'], 0,
    'The basal cell forms the suspensor; its top cell (hypophysis) helps form the radicle and root cap.'],
  ['Johansen\'s classification of embryo types is based on:', ['The plane of division of the terminal cell and the role of the basal cell', 'Number of cotyledons', 'Seed size', 'Endosperm type'], 0,
    'Types: Onagrad (Crucifer), Asterad, Solanad, Caryophyllad, Chenopodiad, Piperad.'],
  ['In a monocot embryo:', ['The single cotyledon is terminal and the plumule is lateral', 'The plumule is terminal between two cotyledons', 'There is no cotyledon', 'The radicle is absent'], 0,
    'In grasses the cotyledon is the scutellum.'],
  ['The suspensor of the embryo:', ['Pushes the embryo into the endosperm and supplies nutrients and hormones', 'Becomes the seed coat', 'Forms the root', 'Is absent in all dicots'], 0,
    'In *Phaseolus* it makes gibberellins.'],
  ['After fertilisation, the integuments develop into the:', ['Seed coat (testa and tegmen)', 'Pericarp', 'Endosperm', 'Embryo'], 0,
    'Ovary becomes the fruit; ovule becomes the seed.'],
  ['Perisperm is:', ['Persistent nucellus in the seed', 'Persistent endosperm', 'Remains of the synergids', 'Fruit wall'], 0,
    'Seen in black pepper and beet.'],
  ['A sorosis, such as pineapple or mulberry, is a:', ['Composite (multiple) fruit from a whole inflorescence', 'Fruit from one apocarpous flower', 'Simple dry fruit', 'False fruit from a thalamus'], 0,
    'A syconus (fig) develops from a hollow hypanthodium.'],
  ['An achene differs from a caryopsis in that in an achene:', ['The pericarp is free from the seed coat', 'The pericarp is fused with the seed coat', 'There are many seeds', 'The fruit is fleshy'], 0,
    'Caryopsis: wheat, rice. Achene: *Clematis*, buckwheat.'],
  ['An aggregate fruit (etaerio) develops from:', ['The free carpels of one flower', 'A whole inflorescence', 'A single carpel', 'The thalamus alone'], 0,
    'E.g. custard apple, strawberry, *Ranunculus*.'],
  ['Fruit development after fertilisation is triggered mainly by:', ['Hormones such as auxins and gibberellins from developing seeds', 'Light only', 'Loss of water', 'Cell death'], 0,
    'Applying these hormones can give parthenocarpic fruit.']
] },
{ p: 'B1', t: 'Embryology & Palynology', w: 2, pyq: ['IFoS-2019-B1-m04', 'CSE-1992-B1-m07', 'IFoS-2006-B1-m03', 'CSE-1988-B1-m06', 'CSE-2023-B1-m08', 'CSE-1991-B1-m10', 'CSE-1986-B1-m06', 'IFoS-2023-B1-m04', 'IFoS-2010-B1-m06', 'CSE-1990-B1-m06', 'IFoS-2011-B1-m05', 'IFoS-2022-B1-m08', 'IFoS-2006-B1-m17', 'CSE-1994-B1-m22'], q: [
  ['In gametophytic self-incompatibility, the pollen\'s behaviour depends on:', ['Its own haploid S allele', 'The S alleles of the parent plant', 'The stigma colour', 'The number of pollen grains'], 0,
    'Seen in Solanaceae and Rosaceae; pollen tubes stop in the style (S-RNase).'],
  ['Sporophytic self-incompatibility is typical of:', ['Brassicaceae, with inhibition on the stigma surface', 'Solanaceae', 'Poaceae', 'Rosaceae'], 0,
    'Pollen phenotype is set by the diploid parent (SRK–SCR system).'],
  ['Self-incompatibility can be bypassed by:', ['Bud pollination before the SI system is active', 'Spraying water', 'Removing petals', 'Pollinating after the flower wilts'], 0,
    'Others: mentor pollen, high CO₂, heat treatment.'],
  ['Self-incompatibility is used in plant breeding for:', ['Producing hybrid seed without emasculation, as in *Brassica*', 'Making haploids', 'Inducing mutations', 'Seed storage'], 0,
    'It enforces cross-pollination.'],
  ['Heterostyly, as in *Primula*, is a device for:', ['Cross-pollination', 'Self-pollination', 'Apomixis', 'Seed dispersal'], 0,
    'Others: dichogamy, herkogamy and dioecy.'],
  ['Anemophilous flowers usually have:', ['Light, dry pollen and large feathery stigmas without nectar', 'Bright petals and scent', 'Sticky pollen', 'Nectar spurs'], 0,
    'Typical of grasses.'],
  ['Bat-pollinated flowers are usually:', ['Large, dull-coloured, open at night with a strong musty smell', 'Small, red and scentless', 'Blue and tubular', 'Green and wind-shaped'], 0,
    'E.g. *Kigelia*, *Adansonia*.'],
  ['Pollination in *Vallisneria* happens:', ['On the water surface (epihydrophily)', 'Under water', 'By wind', 'By birds'], 0,
    '*Zostera* shows pollination under water.'],
  ['Cleistogamous flowers:', ['Never open, ensuring self-pollination', 'Open only at night', 'Need insects', 'Are always sterile'], 0,
    'E.g. *Commelina*, *Viola*, *Oxalis*.'],
  ['Protandry means that:', ['Anthers mature before the stigma', 'Stigma matures first', 'Both mature together', 'There are no anthers'], 0,
    'Protogyny is the reverse; both are forms of dichogamy.']
] }
);
