/* Concept sets for Agriculture I — Cropping systems, tillage and the rice–wheat system. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Agro-climatic Zones & Cropping Systems', w: 3, pyq: ['IFoS-2025-A1-Q1b', 'IFoS-2024-A1-m07', 'IFoS-2012-A1-m03', 'IFoS-2006-A1-m05', 'IFoS-2006-A1-m06', 'IFoS-2005-A1-m03', 'CSE-2001-A1-m05', 'IFoS-2000-A1-m01', 'IFoS-2023-A1-m10', 'IFoS-2021-A1-m09', 'IFoS-2003-A1-m09', 'CSE-2002-A1-m02', 'CSE-2007-A1-m04', 'CSE-1998-A1-m03', 'CSE-2001-A1-m07', 'CSE-1997-A1-m05'], q: [
  ['Intercropping differs from mixed cropping in that intercropping:', ['Grows component crops in a definite row arrangement', 'Mixes seeds and broadcasts them', 'Grows crops one after another', 'Uses only one crop'], 0,
    'Mixed cropping has no distinct row pattern.'],
  ['Relay intercropping means:', ['Sowing the second crop into the standing first crop before it is harvested', 'Sowing crops in alternate strips', 'Mixing seeds', 'Growing one crop each year'], 0,
    'E.g. sowing lentil into standing rice.'],
  ['In an additive intercropping series:', ['The main crop keeps its full population and the intercrop is added', 'Both crops are at half density', 'Only one crop is sown', 'Rows of the main crop are replaced'], 0,
    'Replacement series swap some main-crop rows for the intercrop.'],
  ['A main advantage of intercropping in rainfed areas is:', ['Insurance against total crop failure', 'Easier mechanisation', 'No competition', 'Lower total yield'], 0,
    'Better use of light, water and nutrients and legume nitrogen are others.'],
  ['A good pair of intercrop components usually has:', ['Different durations, rooting depths and canopy heights', 'The same height and duration', 'Two cereals of identical maturity', 'Two climbing crops'], 0,
    'E.g. pigeonpea (long, deep-rooted) + sorghum or groundnut.'],
  ['Land Equivalent Ratio (LER) is the:', ['Sum of the ratios of intercrop yield to sole-crop yield for each component', 'Ratio of land area to crop area', 'Total yield per hectare', 'Ratio of two crop prices'], 0,
    'LER above 1 means intercropping uses land more efficiently.'],
  ['If pigeonpea gives 0.8 and sorghum 0.6 of their sole-crop yields in an intercrop, the LER is:', ['1.4', '0.48', '0.2', '1.0'], 0,
    '0.8 + 0.6 = 1.4 — 40% more land would be needed by sole cropping.'],
  ['A disadvantage of intercropping is that it:', ['Makes mechanised operations and input application harder', 'Always lowers income', 'Increases erosion', 'Removes all pests'], 0,
    'Competition between components can also reduce yields.'],
  ['Autumn-planted sugarcane is often intercropped with:', ['Short-duration rabi crops such as potato, mustard, wheat or sugar beet', 'Rice', 'Cotton', 'Pigeonpea'], 0,
    'Slow early cane growth leaves space for a quick crop.'],
  ['Besides LER, an index used to compare intercrops on time and land is:', ['Area Time Equivalent Ratio (ATER)', 'Harvest index', 'Leaf area index', 'Water use efficiency'], 0,
    'Aggressivity and competitive ratio measure dominance between components.']
] },
{ p: 'A1', t: 'Crop Production', w: 3, pyq: ['CSE-2020-A1-m08', 'IFoS-2014-A1-m09', 'IFoS-2013-A1-m08', 'IFoS-2012-A1-m05', 'IFoS-2006-A1-m03', 'CSE-2024-A1-m09', 'CSE-2004-A1-m06'], q: [
  ['Primary tillage includes:', ['Ploughing with mouldboard or disc ploughs', 'Harrowing', 'Planking', 'Interculture'], 0,
    'Secondary tillage (harrowing, planking, levelling) prepares a fine seedbed.'],
  ['Minimum tillage differs from zero tillage in that minimum tillage:', ['Reduces the number of operations, while zero tillage sows directly into untilled soil', 'Uses more ploughing', 'Is the same as zero tillage', 'Uses only hand tools'], 0,
    'Zero-till drills and the Happy Seeder sow wheat directly after rice.'],
  ['Zero-till wheat after rice is popular in north India because it:', ['Allows timely sowing and saves time, fuel and cost', 'Needs more water', 'Increases *Phalaris minor* always', 'Requires burning straw'], 0,
    'It also tends to reduce *Phalaris minor* emergence.'],
  ['A problem with long-term zero tillage is:', ['Greater reliance on herbicides and build-up of perennial weeds', 'Higher fuel use', 'More soil erosion', 'Lower organic carbon always'], 0,
    'Residue handling can also be difficult.'],
  ['Conservation tillage is usually defined as tillage that leaves:', ['At least 30% of the soil surface covered by residue after planting', 'Bare soil', 'Deep furrows', 'Burnt residue'], 0,
    'Residue cover reduces erosion and evaporation.'],
  ['Mulching benefits crops mainly by:', ['Conserving moisture, moderating soil temperature and suppressing weeds', 'Raising soil salinity', 'Reducing infiltration', 'Increasing evaporation'], 0,
    'Organic, plastic and dust mulches are used.'],
  ['Puddling for transplanted rice:', ['Reduces percolation and aids transplanting, but damages soil structure for the next crop', 'Improves aeration', 'Increases percolation', 'Is used for wheat'], 0,
    'Poor structure later hurts wheat root growth.'],
  ['The main aims of tillage are:', ['Seedbed preparation, weed control and residue incorporation', 'Only to increase erosion', 'To compact the soil', 'To reduce infiltration'], 0,
    'Excess tillage harms soil organic matter.'],
  ['Black polythene mulch is preferred over transparent mulch for:', ['Weed control, as it blocks light', 'Soil solarisation', 'Raising soil temperature most', 'Seed germination in light'], 0,
    'Transparent film is used for solarisation.'],
  ['Tillage that turns the soil completely, burying residues, is done with a:', ['Mouldboard plough', 'Chisel plough', 'Zero-till drill', 'Rotary weeder'], 0,
    'Chisel ploughs loosen without inverting.']
] },
{ p: 'A1', t: 'Crop Production', w: 3, pyq: ['CSE-2020-A1-m12', 'IFoS-2014-A1-m08', 'CSE-2001-A1-m08', 'CSE-2022-A1-m08', 'IFoS-2012-A1-m02', 'IFoS-2009-A1-m03', 'CSE-2002-A1-m03', 'CSE-2014-A1-m11', 'CSE-2010-A1-m08', 'CSE-2008-A1-m06', 'CSE-2001-A1-m06'], q: [
  ['The rice–wheat cropping system of the Indo-Gangetic plains covers in India about:', ['10 million hectares', '1 million hectares', '50 million hectares', '100 million hectares'], 0,
    'About 13.5 Mha across South Asia; it is central to food security.'],
  ['A major problem of the rice–wheat system is:', ['Falling groundwater tables and declining factor productivity', 'Too little rice straw', 'Excess soil organic matter', 'Low labour use'], 0,
    'Others: residue burning, zinc deficiency, herbicide-resistant *Phalaris minor*.'],
  ['Late planting of wheat after rice reduces yield mainly because:', ['High temperatures during grain filling shorten the season', 'Days become shorter', 'Rainfall rises', 'Soil becomes acidic'], 0,
    'Zero tillage and shorter rice varieties help timely sowing.'],
  ['Punjab and Haryana laws of 2009 delaying rice transplanting aim to:', ['Save groundwater by avoiding peak evaporation months', 'Increase pests', 'Increase stubble burning', 'Raise water use'], 0,
    'The trade-off is a tighter window for wheat sowing.'],
  ['Including summer moong in the rice–wheat sequence helps by:', ['Adding nitrogen and organic matter and diversifying income', 'Increasing groundwater use', 'Spreading *Phalaris minor*', 'Raising salinity'], 0,
    'Legume diversification improves soil health.'],
  ['The System of Rice Intensification (SRI) was developed in:', ['Madagascar, by Henri de Laulanié', 'Philippines, by IRRI', 'China, by Yuan Longping', 'India, by Swaminathan'], 0,
    'It was popularised by Norman Uphoff.'],
  ['A key SRI practice is:', ['Transplanting young (8–12 day) single seedlings at wide spacing with intermittent irrigation', 'Continuous flooding', 'Dense planting of old seedlings', 'No weeding'], 0,
    'Mechanical (cono) weeding also aerates the soil.'],
  ['Direct-seeded rice (DSR) saves:', ['Water and labour by avoiding nursery, puddling and transplanting', 'Herbicides', 'Seed', 'Nothing'], 0,
    'Weed control is its biggest challenge.'],
  ['Laser land levelling in rice–wheat fields:', ['Improves irrigation uniformity and saves water', 'Increases runoff', 'Causes erosion', 'Reduces yields'], 0,
    'It also improves input-use efficiency.'],
  ['Integrated plant nutrient supply in rice–wheat combines:', ['Fertilisers with organic manures, green manures and biofertilisers', 'Only urea', 'Only compost', 'No inputs'], 0,
    'Zinc sulphate corrects the common zinc deficiency in rice.']
] }
);
