/* Concept sets for Botany I — Economic botany. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 3, pyq: ['IFoS-2003-B1-m11', 'CSE-2003-B1-m09', 'IFoS-2019-B1-m07', 'CSE-1992-B1-m16', 'CSE-2018-B1-m10', 'IFoS-2009-B1-m23', 'CSE-1994-B1-m23', 'IFoS-2003-B1-m16'], q: [
  ['Black pepper is the dried:', ['Unripe fruit of *Piper nigrum* (Piperaceae)', 'Seed of *Capsicum*', 'Flower bud of *Syzygium*', 'Rhizome of *Zingiber*'], 0,
    'White pepper is the ripe fruit with the outer pericarp removed; the pungent principle is piperine.'],
  ['Clove is the dried:', ['Unopened flower bud of *Syzygium aromaticum* (Myrtaceae)', 'Fruit of *Myristica*', 'Bark of *Cinnamomum*', 'Stigma of *Crocus*'], 0,
    'Its oil is rich in eugenol.'],
  ['Saffron is obtained from the:', ['Dried stigmas of *Crocus sativus* (Iridaceae)', 'Petals of *Carthamus*', 'Seeds of *Bixa*', 'Rhizome of *Curcuma*'], 0,
    'Kashmir (Pampore) is India\'s saffron centre; colour is from crocin.'],
  ['Asafoetida (heeng) is:', ['An oleo-gum-resin from the roots of *Ferula* (Apiaceae)', 'A dried fruit of *Foeniculum*', 'A bark of *Cinnamomum*', 'Latex of *Papaver*'], 0,
    'India imports most of it, though cultivation has begun in Himachal Pradesh.'],
  ['Turmeric and ginger are both:', ['Rhizomes of Zingiberaceae', 'Roots of Apiaceae', 'Fruits of Piperaceae', 'Bulbs of Liliaceae'], 0,
    'Turmeric (*Curcuma longa*) owes its colour to curcumin.'],
  ['The "queen of spices" is:', ['Cardamom (*Elettaria cardamomum*), whose fruits and seeds are used', 'Black pepper', 'Clove', 'Saffron'], 0,
    'Pepper is called the king of spices.'],
  ['Nutmeg and mace both come from *Myristica fragrans*; mace is the:', ['Aril around the seed', 'Seed kernel', 'Fruit wall', 'Bark'], 0,
    'Nutmeg is the seed kernel.'],
  ['True cinnamon is the:', ['Inner bark of *Cinnamomum verum* (Lauraceae)', 'Fruit of *Illicium*', 'Leaf of *Laurus*', 'Seed of *Myristica*'], 0,
    'Cassia bark comes from *C. cassia*.'],
  ['Coriander, fennel and cumin are all:', ['Fruits (cremocarps) of Apiaceae', 'Seeds of Fabaceae', 'Flower buds of Myrtaceae', 'Rhizomes of Zingiberaceae'], 0,
    'Their oils lie in the vittae of the fruit wall.'],
  ['The pungency of chillies (*Capsicum annuum*, Solanaceae) is due to:', ['Capsaicin', 'Piperine', 'Eugenol', 'Curcumin'], 0,
    'It is concentrated in the placenta of the fruit.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 2, pyq: ['IFoS-2020-B1-m03', 'CSE-2019-B1-m08', 'IFoS-2019-B1-m08', 'IFoS-2012-B1-m32', 'IFoS-2010-B1-m28', 'CSE-1993-B1-m18', 'CSE-2016-B1-m14', 'CSE-2004-B1-m09', 'IFoS-2023-B1-m11'], q: [
  ['Fumitories are plants that are:', ['Smoked, such as tobacco', 'Chewed, such as betel nut', 'Drunk as beverages', 'Used as spices'], 0,
    'Masticatories are chewed — betel nut, betel leaf.'],
  ['Tobacco is the cured leaf of:', ['*Nicotiana tabacum* (Solanaceae)', '*Piper betle* (Piperaceae)', '*Cannabis sativa* (Cannabaceae)', '*Areca catechu* (Arecaceae)'], 0,
    'Its main alkaloid is nicotine.'],
  ['Betel nut, a masticatory, is the:', ['Seed (mainly endosperm) of *Areca catechu*', 'Leaf of *Piper betle*', 'Fruit of *Cocos nucifera*', 'Root of *Areca*'], 0,
    'Betel leaf is from *Piper betle*.'],
  ['Tea is obtained from:', ['Leaves of *Camellia sinensis* (Theaceae)', 'Seeds of *Coffea arabica*', 'Seeds of *Theobroma cacao*', 'Leaves of *Ilex paraguariensis* only'], 0,
    'Its stimulant is caffeine (once called theine).'],
  ['Coffee "beans" are the:', ['Seeds of *Coffea* (Rubiaceae)', 'Fruits of *Theobroma*', 'Roots of *Cichorium*', 'Leaves of *Camellia*'], 0,
    'Arabica and robusta (*C. canephora*) are the main species.'],
  ['Cocoa and chocolate come from the seeds of:', ['*Theobroma cacao* (Malvaceae)', '*Coffea arabica*', '*Cola nitida*', '*Areca catechu*'], 0,
    'Theobromine is the main alkaloid.'],
  ['Opium is the dried latex from:', ['Unripe capsules of *Papaver somniferum*', 'Leaves of *Erythroxylum coca*', 'Flowers of *Cannabis*', 'Roots of *Rauvolfia*'], 0,
    'It yields morphine and codeine.'],
  ['Cocaine comes from the leaves of:', ['*Erythroxylum coca*', '*Papaver somniferum*', '*Nicotiana tabacum*', '*Atropa belladonna*'], 0,
    'It is a local anaesthetic and a narcotic.'],
  ['The cashew "apple" is:', ['The swollen fleshy pedicel — a false fruit', 'The true fruit', 'The seed', 'The aril'], 0,
    'The true fruit is the kidney-shaped nut; *Anacardium occidentale*, Anacardiaceae.'],
  ['Cannabis (hemp, bhang) belongs to the family:', ['Cannabaceae', 'Papaveraceae', 'Solanaceae', 'Moraceae'], 0,
    'Hemp fibre comes from its stem; resin from female flowers.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 2, pyq: ['CSE-2010-B1-m07', 'CSE-2020-B1-m08', 'CSE-2015-B1-m13', 'CSE-2005-B1-m14', 'CSE-2023-B1-m14', 'CSE-2024-B1-m15', 'CSE-1990-B1-m05', 'IFoS-2007-B1-m08', 'CSE-2023-B1-m05', 'IFoS-2011-B1-m11', 'IFoS-2010-B1-m17', 'IFoS-2010-B1-m18', 'IFoS-2004-B1-m17'], q: [
  ['The oilseed that buries its own fruits (geocarpy) is:', ['Groundnut (*Arachis hypogaea*)', 'Mustard', 'Sesame', 'Safflower'], 0,
    'The gynophore (peg) pushes the ovary into the soil.'],
  ['Soybean (*Glycine max*) seeds contain about:', ['40% protein and 20% oil', '10% protein and 50% oil', '5% protein and 5% oil', '70% oil'], 0,
    'It is grown mainly in Madhya Pradesh and Maharashtra.'],
  ['Safflower (*Carthamus tinctorius*) belongs to:', ['Asteraceae', 'Pedaliaceae', 'Brassicaceae', 'Fabaceae'], 0,
    'Sesame (*Sesamum indicum*) is Pedaliaceae; mustard is Brassicaceae.'],
  ['The oil crop with the highest oil yield per hectare is:', ['Oil palm (*Elaeis guineensis*)', 'Groundnut', 'Sunflower', 'Linseed'], 0,
    'India is promoting it under the National Mission on Edible Oils – Oil Palm.'],
  ['Pulse proteins are usually rich in lysine but poor in:', ['Sulphur amino acids such as methionine', 'Lysine', 'Nitrogen', 'Water'], 0,
    'Cereals are the opposite, so cereal–pulse diets complement each other.'],
  ['Pigeon pea (arhar/tur) is:', ['*Cajanus cajan*', '*Cicer arietinum*', '*Lens culinaris*', '*Vigna mungo*'], 0,
    'Chickpea: *Cicer*; lentil: *Lens*; urd: *Vigna mungo*; mung: *V. radiata*.'],
  ['Finger millet (ragi, *Eleusine coracana*) is notable for its high:', ['Calcium content', 'Oil content', 'Gluten', 'Sugar'], 0,
    'Millets are now promoted as "nutri-cereals"; 2023 was the International Year of Millets.'],
  ['Millets differ from major cereals mainly in being:', ['Small-grained, hardy crops of dry areas', 'Large-grained irrigated crops', 'Legumes', 'Tuber crops'], 0,
    'E.g. sorghum, pearl millet, finger millet, foxtail millet.'],
  ['Popcorn belongs to the maize group:', ['*Zea mays everta*', '*Zea mays indentata*', '*Zea mays saccharata*', '*Zea mays amylacea*'], 0,
    'Dent: *indentata*; flint: *indurata*; sweet: *saccharata*; flour: *amylacea*; waxy: *ceratina*.'],
  ['Bread wheat (*Triticum aestivum*) is:', ['Hexaploid (2n = 42)', 'Diploid', 'Tetraploid', 'Triploid'], 0,
    'Durum wheat is tetraploid.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 2, pyq: ['CSE-2017-B1-m12', 'IFoS-2010-B1-m25', 'IFoS-2002-B1-m12', 'IFoS-2012-B1-m31', 'CSE-2004-B1-m04', 'CSE-2007-B1-m11', 'IFoS-2021-B1-m11', 'CSE-2009-B1-m17', 'CSE-2020-B1-m12', 'CSE-1993-B1-m17', 'CSE-1994-B1-m24', 'IFoS-2003-B1-m15', 'IFoS-2003-B1-m17'], q: [
  ['Gum arabic is obtained from:', ['*Acacia senegal*', '*Sterculia urens*', '*Pinus roxburghii*', '*Hevea brasiliensis*'], 0,
    'Gum karaya: *Sterculia urens*; guar gum: endosperm of *Cyamopsis tetragonoloba*.'],
  ['Gums differ from resins in that gums are:', ['Polysaccharides that dissolve or swell in water', 'Terpenoids soluble only in organic solvents', 'Proteins', 'Fats'], 0,
    'Resins are water-insoluble and harden in air.'],
  ['Rosin and turpentine are obtained from the oleoresin of:', ['*Pinus roxburghii*', '*Acacia*', '*Shorea robusta*', '*Bixa orellana*'], 0,
    'Turpentine is the volatile fraction; rosin is the residue.'],
  ['Canada balsam, used for mounting slides, comes from:', ['*Abies balsamea*', '*Pinus wallichiana*', '*Copaifera*', '*Boswellia*'], 0,
    'Lac, by contrast, is secreted by the insect *Kerria lacca*.'],
  ['Indigo dye is obtained from the leaves of:', ['*Indigofera tinctoria*', '*Lawsonia inermis*', '*Bixa orellana*', '*Rubia cordifolia*'], 0,
    'Henna: *Lawsonia* leaves (lawsone); madder: *Rubia* roots.'],
  ['Annatto, a food colour, comes from:', ['Seed coats of *Bixa orellana*', 'Heartwood of *Haematoxylum*', 'Roots of *Rubia*', 'Flowers of *Butea*'], 0,
    'Haematoxylin, the tissue stain, is from logwood heartwood.'],
  ['Pyrethrin insecticide is obtained from:', ['Flower heads of *Chrysanthemum* (*Tanacetum*) *cinerariifolium*', 'Roots of *Derris*', 'Leaves of tobacco', 'Seeds of neem'], 0,
    'Rotenone is from *Derris* roots; azadirachtin from neem seeds.'],
  ['Azadirachtin, a botanical pesticide, comes from:', ['Neem (*Azadirachta indica*) seeds', 'Tobacco leaves', '*Derris* roots', 'Marigold flowers'], 0,
    'It acts as an antifeedant and growth regulator.'],
  ['Sandalwood oil, used in perfumery, comes from the:', ['Heartwood and roots of *Santalum album*', 'Leaves of *Santalum*', 'Flowers of *Jasminum*', 'Bark of *Cinnamomum*'], 0,
    'Sandalwood is a root hemiparasite.'],
  ['Essential oils for perfumes are usually extracted by:', ['Steam distillation (or enfleurage for delicate flowers)', 'Fermentation', 'Burning', 'Tapping latex'], 0,
    'Rose attar, vetiver, lemongrass and palmarosa are Indian examples.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 2, pyq: ['CSE-2023-B1-m15', 'IFoS-2020-B1-m13', 'CSE-2021-B1-m13', 'CSE-2024-B1-m14', 'CSE-2023-B1-m13', 'CSE-1989-B1-m21', 'CSE-1993-B1-m12', 'IFoS-2000-B1-m19', 'CSE-2002-B1-m11'], q: [
  ['Para rubber, *Hevea brasiliensis*, is native to:', ['The Amazon basin', 'South-East Asia', 'Africa', 'India'], 0,
    'It belongs to Euphorbiaceae; Kerala is India\'s main rubber state.'],
  ['Rubber latex is collected by:', ['Tapping — a sloping half-spiral cut in the bark that opens laticifers', 'Crushing seeds', 'Boiling leaves', 'Cutting roots'], 0,
    'Latex is coagulated with acid and rolled into sheets.'],
  ['Rubber trees are commercially propagated by:', ['Bud grafting on seedling rootstocks', 'Seeds only', 'Leaf cuttings', 'Spores'], 0,
    'This keeps high-yielding clones true to type.'],
  ['A feature of the "domestication syndrome" in cereals is:', ['Loss of seed shattering', 'Stronger seed dormancy', 'Smaller seeds', 'More toxic compounds'], 0,
    'Others: larger seeds, uniform ripening, compact plants.'],
  ['A negative consequence of domestication is:', ['Loss of genetic diversity through bottlenecks', 'Higher yield', 'Larger fruit', 'Easier harvest'], 0,
    'Wild relatives are therefore conserved as gene sources.'],
  ['Alphonse de Candolle\'s *Origin of Cultivated Plants* (1882) used evidence from:', ['Botany, archaeology, history and linguistics', 'DNA sequences', 'Only fossils', 'Only folk songs'], 0,
    'Vavilov later used diversity centres.'],
  ['The antifungal antibiotic griseofulvin is produced by:', ['*Penicillium griseofulvum*', '*Streptomyces griseus*', '*Aspergillus niger*', '*Bacillus subtilis*'], 0,
    'Streptomycin, an antibacterial, is from *Streptomyces griseus*.'],
  ['Teak (*Tectona grandis*) is now placed in the family:', ['Lamiaceae', 'Dipterocarpaceae', 'Fabaceae', 'Meliaceae'], 0,
    'Sal (*Shorea robusta*) is Dipterocarpaceae; shisham (*Dalbergia sissoo*) is Fabaceae.'],
  ['Red sanders (*Pterocarpus santalinus*), a prized red timber, is endemic to:', ['Southern Eastern Ghats of Andhra Pradesh', 'Western Himalaya', 'Sundarbans', 'Thar desert'], 0,
    'It is heavily smuggled and listed in CITES Appendix II.'],
  ['Subabul (*Leucaena leucocephala*) is popular in agroforestry because it:', ['Is a fast-growing nitrogen-fixing tree giving fodder, fuel and green manure', 'Produces rubber', 'Is a spice', 'Is a fibre plant'], 0,
    'It is a multipurpose tree.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 2, pyq: ['IFoS-2013-B1-m11', 'IFoS-2012-B1-m14', 'IFoS-2012-B1-m15', 'IFoS-2001-B1-m11', 'IFoS-2005-B1-m08', 'IFoS-2000-B1-m09', 'IFoS-2009-B1-m15', 'IFoS-2009-B1-m16', 'IFoS-2006-B1-m07', 'IFoS-2003-B1-m12', 'CSE-2012-B1-m07', 'IFoS-2024-B1-m10', 'IFoS-2002-B1-m16', 'IFoS-2022-B1-m22', 'IFoS-2010-B1-m27', 'IFoS-2010-B1-m26', 'IFoS-2015-B1-m06', 'CSE-1991-B1-m15', 'IFoS-2011-B1-m18', 'IFoS-2004-B1-m18', 'IFoS-2013-B1-m23', 'IFoS-2013-B1-m24', 'IFoS-2011-B1-m17', 'IFoS-2012-B1-m30', 'IFoS-2012-B1-m28', 'IFoS-2011-B1-m19', 'IFoS-2009-B1-m22', 'IFoS-2009-B1-m21', 'IFoS-2010-B1-m22', 'IFoS-2012-B1-m29', 'CSE-1993-B1-m16'], q: [
  ['Sarpagandha, source of reserpine, is:', ['*Rauvolfia serpentina* (Apocynaceae), roots', '*Withania somnifera*, roots', '*Catharanthus roseus*, leaves', '*Andrographis paniculata*, whole plant'], 0,
    'Reserpine lowers blood pressure.'],
  ['Jute fibre is obtained from the stem bast of:', ['*Corchorus capsularis* and *C. olitorius*', '*Crotalaria juncea*', '*Linum usitatissimum*', '*Gossypium*'], 0,
    'Sunn hemp is *Crotalaria*; flax is *Linum*.'],
  ['Kapok floss comes from:', ['Hairs on the inner wall of the fruit of *Ceiba pentandra*', 'Seed hairs of cotton', 'Leaves of *Agave*', 'Coconut husk'], 0,
    'It is light and water-repellent, used in life jackets.'],
  ['Kalmegh, a bitter liver tonic, is:', ['*Andrographis paniculata* (Acanthaceae)', '*Momordica charantia*', '*Tinospora cordifolia*', '*Phyllanthus amarus*'], 0,
    'Its active principle is andrographolide.'],
  ['Isabgol husk comes from the seeds of:', ['*Plantago ovata*', '*Linum usitatissimum*', '*Ocimum basilicum*', '*Salvia hispanica*'], 0,
    'It is a mucilaginous laxative; India is the main producer.'],
  ['Vasaka, used for cough and asthma, is:', ['*Justicia adhatoda*, leaves', '*Ocimum sanctum*, leaves', '*Aegle marmelos*, fruit', '*Azadirachta indica*, bark'], 0,
    'Its alkaloid vasicine is a bronchodilator.'],
  ['Ipecac, an emetic, comes from the roots of:', ['*Carapichea* (*Cephaelis*) *ipecacuanha*, Rubiaceae', '*Rauvolfia*', '*Aconitum*', '*Withania*'], 0,
    'Its alkaloid is emetine.'],
  ['Flax (*Linum usitatissimum*) gives:', ['Linen fibre from the stem and linseed oil from seeds', 'Rubber', 'Jute', 'Coir'], 0,
    'It belongs to Linaceae.'],
  ['Ginseng is the root of:', ['*Panax ginseng* (Araliaceae)', '*Withania somnifera*', '*Glycyrrhiza glabra*', '*Asparagus racemosus*'], 0,
    'It is valued as a tonic in East Asia.'],
  ['Aconite, a deadly poison and drug, comes from the roots of:', ['*Aconitum* (Ranunculaceae)', '*Atropa*', '*Datura*', '*Strychnos*'], 0,
    'Its alkaloid is aconitine.']
] }
);
