/* Concept sets for Botany I — Pteridophytes. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Pteridophytes', w: 3, pyq: ['IFoS-2013-B1-m41', 'CSE-2012-B1-m28', 'IFoS-2010-B1-m38', 'CSE-2010-B1-m29', 'CSE-2006-B1-m26', 'CSE-2004-B1-m24', 'IFoS-2003-B1-m28', 'IFoS-2002-B1-m24', 'CSE-1995-B1-m40', 'CSE-1987-B1-m24', 'CSE-1992-B1-m35', 'IFoS-2001-B1-m25', 'CSE-2022-B1-m27', 'CSE-2020-B1-m15', 'IFoS-2019-B1-m10', 'CSE-2014-B1-m16', 'CSE-2018-B1-m23', 'CSE-1985-B1-m18'], q: [
  ['Morphologically, the sporocarp of *Marsilea* is best interpreted as:', ['A modified fertile leaf segment (folded pinna)', 'A modified stem branch', 'A single enlarged sporangium', 'A modified root'], 0,
    'It is borne on the petiole and is a folded, hardened fertile leaflet enclosing the sori.'],
  ['Inside the *Marsilea* sporocarp, each sorus bears:', ['Megasporangia on the crest of the receptacle and microsporangia on its flanks', 'Only microsporangia', 'Only megasporangia', 'Sporangia scattered without a receptacle'], 0,
    'Each sorus is mixed and covered by a delicate indusium.'],
  ['When a mature *Marsilea* sporocarp is soaked in water, the structure that swells and comes out carrying the sori is the:', ['Sorophore (gelatinous ring)', 'Indusium', 'Annulus', 'Elater'], 0,
    'The mucilaginous sorophore absorbs water, ruptures the hard wall and pulls the sori out in a worm-like chain.'],
  ['The hard sporocarp wall of *Marsilea* is of value because it:', ['Lets spores survive drying for many years', 'Carries out photosynthesis', 'Absorbs mineral nutrients', 'Disperses spores explosively'], 0,
    'Dry sporocarps have germinated after decades in herbarium sheets.'],
  ['*Marsilea* is a:', ['Heterosporous, leptosporangiate water fern', 'Homosporous, eusporangiate fern', 'Heterosporous lycopsid', 'Homosporous horsetail'], 0,
    'With *Salvinia* and *Azolla* it forms the heterosporous water ferns (Salviniales / Marsileales).'],
  ['The leaf of *Marsilea* is typically:', ['Long-petioled with four leaflets and circinate vernation', 'Scale-like and whorled', 'Small, ligulate and sessile', 'Bilobed with an algal cavity'], 0,
    'Hence the name "water clover". Bilobed leaves with *Anabaena* cavities belong to *Azolla*.'],
  ['The rhizome of *Marsilea* has:', ['An amphiphloic siphonostele and air chambers in the cortex', 'A plectostele', 'A polycyclic dictyostele', 'An actinostele with no cortex'], 0,
    'Amphiphloic siphonostele (solenostele) with aerenchyma — a hydrophytic adaptation.'],
  ['The male gametophyte of *Marsilea* produces antherozoids that are:', ['Coiled and multiflagellate', 'Biflagellate', 'Non-motile', 'Uniflagellate'], 0,
    'Each microspore forms a prothallial cell and antheridia, giving 16 coiled, multiflagellate sperms.'],
  ['The female gametophyte of *Marsilea* is:', ['Endosporic, bearing a single archegonium at the apex of the megaspore', 'Exosporic, heart-shaped and green', 'Subterranean and mycorrhizal', 'Filamentous, with many archegonia'], 0,
    'It develops inside the megaspore wall and projects only its apical archegonium.'],
  ['The *Marsilea* sporocarp is not considered a seed because:', ['The megaspore is shed and the gametophyte is fertilised outside, with no integument-covered megasporangium', 'It contains microsporangia as well', 'It has a hard wall', 'Its spores are produced by meiosis'], 0,
    'A seed is an integumented megasporangium retaining the megaspore and holding an embryo.']
] },
{ p: 'B1', t: 'Pteridophytes', w: 3, pyq: ['IFoS-2005-B1-m26', 'CSE-1994-B1-m39', 'CSE-1993-B1-m37', 'IFoS-2015-B1-m19', 'CSE-2012-B1-m27', 'CSE-2011-B1-m17', 'IFoS-2000-B1-m24', 'CSE-1987-B1-m23', 'IFoS-2003-B1-m26', 'CSE-2007-B1-m25', 'CSE-1995-B1-m39', 'IFoS-2001-B1-m24', 'CSE-1990-B1-m10'], q: [
  ['The rhizophore of *Selaginella* arises:', ['From angle meristems at the points of stem branching', 'Endogenously from the pericycle of the root', 'From the base of the ligule', 'From the strobilus axis'], 0,
    'It is a colourless, leafless, positively geotropic axis that produces roots at its tip.'],
  ['Which feature makes the rhizophore of *Selaginella* stem-like rather than root-like?', ['Exogenous origin and no root cap', 'Presence of root hairs', 'Endogenous origin', 'Exarch xylem'], 0,
    'Being exogenous and capless, it is variously called a leafless stem, a root, or an organ sui generis.'],
  ['The ligule in *Selaginella* is found:', ['On the upper (adaxial) side near the base of each leaf and sporophyll', 'At the tip of the rhizophore', 'Only on megasporophylls', 'On the lower surface of the leaf'], 0,
    'Ligulate leaves separate *Selaginella* (and *Isoetes*) from the eligulate *Lycopodium*.'],
  ['In dorsiventral (creeping) species of *Selaginella*, the leaves are:', ['In four rows — two of small dorsal and two of large ventral leaves', 'In whorls fused into a sheath', 'All alike and spirally arranged', 'Absent; the stem photosynthesises'], 0,
    'This anisophylly (heterophylly) is seen in *S. kraussiana*; radial species are isophyllous.'],
  ['In the *Selaginella* stem, the stele is suspended in an air cavity by:', ['Trabeculae — elongated endodermal cells', 'Rhizoids', 'Medullary rays', 'Sclerenchyma girders'], 0,
    'The stele is usually a protostele; some species are polystelic.'],
  ['A megasporangium of *Selaginella* usually contains:', ['Four megaspores from one functional megaspore mother cell', 'Many megaspores', 'One megaspore only, always', 'Microspores and megaspores together'], 0,
    'Other mother cells degenerate; in *S. monospora* only one megaspore matures.'],
  ['In a median L.S. of a *Selaginella* strobilus, megasporangia are usually:', ['Towards the base, with microsporangia above', 'Only at the apex', 'Absent', 'Mixed in the same sporangium as microspores'], 0,
    'Microsporangia are many and mostly in the upper part; the cone is four-angled.'],
  ['Gametophytes of *Selaginella* are:', ['Endosporic and unisexual, with biflagellate antherozoids', 'Exosporic and bisexual', 'Green, free-living and cordate', 'Subterranean and mycorrhizal'], 0,
    'The female gametophyte often begins developing while the megaspore is still in the sporangium.'],
  ['Retention of the megaspore and fertilisation on the parent plant — an approach to the seed habit — is reported in:', ['*Selaginella rupestris* and *S. monospora*', '*Lycopodium clavatum*', '*Equisetum arvense*', '*Marsilea minuta*'], 0,
    'It still lacks an integument and dormancy, so it is not a true seed.'],
  ['The "resurrection plant" that curls when dry and unfolds when wetted is:', ['*Selaginella lepidophylla*', '*Lycopodium cernuum*', '*Equisetum hyemale*', '*Azolla pinnata*'], 0,
    'Also *S. bryopteris* (sanjeevani) in India. Some *Selaginella* species even have vessels.']
] },
{ p: 'B1', t: 'Pteridophytes', w: 2, pyq: ['IFoS-2022-B1-m27', 'CSE-1991-B1-m38', 'CSE-2025-B1-m26'], q: [
  ['The strobilus of *Lycopodium* bears:', ['Spirally arranged sporophylls, each with one kidney-shaped sporangium on the upper side', 'Peltate sporangiophores in whorls', 'Sori covered by indusia', 'Mega- and microsporangia'], 0,
    '*Lycopodium* is homosporous; the cone is terminal on upright branches.'],
  ['Sporangium development in *Lycopodium* is:', ['Eusporangiate — from a group of superficial initials', 'Leptosporangiate — from a single initial', 'Endogenous', 'Absent'], 0,
    'Eusporangiate sporangia have a thick wall and many spores.'],
  ['Match the stele with the *Lycopodium* species: plectostele —', ['*L. clavatum*', '*L. serratum*', '*L. cernuum*', '*L. phlegmaria*'], 0,
    'Actinostele: *L. serratum*; plectostele: *L. clavatum, L. volubile*; mixed protostele: *L. cernuum*.'],
  ['Prothalli of *L. clavatum* type are:', ['Subterranean, non-green, tuberous and mycorrhizal', 'Green, surface-living and lobed', 'Endosporic', 'Filamentous and aquatic'], 0,
    'Three types are recognised: green surface (*L. cernuum*), partly subterranean, and wholly subterranean.'],
  ['Prothalli of *Lycopodium* are hard to collect in nature mainly because:', ['Many are subterranean, mycorrhizal and take years to mature', 'They live only a few hours', 'They grow only on tree trunks', 'They are microscopic and endosporic'], 0,
    'Spore germination may itself take years and depends on a fungal partner.'],
  ['Antherozoids of *Lycopodium* are:', ['Biflagellate', 'Multiflagellate', 'Non-motile', 'Uniflagellate'], 0,
    'Like *Selaginella*; ferns and *Equisetum* have multiflagellate sperms.'],
  ['Compared with *Selaginella*, *Lycopodium* is:', ['Homosporous and eligulate, without rhizophores', 'Heterosporous and ligulate', 'Heterosporous without ligules', 'Homosporous with rhizophores'], 0,
    'Both are microphyllous lycopsids with eusporangiate sporangia and biflagellate sperms.'],
  ['The embryo of *Lycopodium* is:', ['Endoscopic, with a suspensor', 'Exoscopic, without a suspensor', 'Formed without fertilisation always', 'Free-living from the start'], 0,
    'The suspensor pushes the embryo into the gametophyte tissue.'],
  ['"Lycopodium powder" used in fireworks and as a dusting powder is:', ['The spores of *Lycopodium*', 'The ash of the stem', 'The dried rhizome', 'The prothallus'], 0,
    'The oily spores are highly inflammable.'],
  ['Huperzine A, studied for Alzheimer\'s disease, comes from:', ['*Huperzia serrata* (*Lycopodium serratum*)', '*Equisetum arvense*', '*Marsilea minuta*', '*Selaginella bryopteris*'], 0,
    'It is an acetylcholinesterase inhibitor.']
] },
{ p: 'B1', t: 'Pteridophytes', w: 2, pyq: ['IFoS-2014-B1-m30', 'IFoS-2005-B1-m27', 'IFoS-2003-B1-m27', 'CSE-2022-B1-m26', 'IFoS-2001-B1-m26', 'CSE-1986-B1-m31', 'IFoS-2004-B1-m02', 'IFoS-2024-B1-m02', 'CSE-2000-B1-m01'], q: [
  ['In the *Equisetum* stem, carinal canals lie:', ['Opposite the ridges, formed by breakdown of protoxylem', 'Opposite the furrows in the cortex', 'In the centre of the pith', 'In the leaf sheath'], 0,
    'Vallecular canals are cortical and lie opposite the furrows; the centre has a large pith cavity.'],
  ['A xerophytic feature of *Equisetum* is:', ['Silica-rich ridged epidermis with sunken stomata', 'Large vallecular canals', 'A central pith cavity', 'Aerenchyma in the cortex'], 0,
    'Canals and cavities are hydrophytic features; reduced leaves, silica and sunken stomata are xerophytic.'],
  ['Leaves of *Equisetum* are:', ['Small, scale-like and whorled, fused into a sheath at each node', 'Large, compound and circinate', 'Ligulate and spirally arranged', 'Absent altogether'], 0,
    'The green, ribbed stem does most of the photosynthesis.'],
  ['In the *Equisetum* strobilus, sporangia are borne on:', ['The underside of peltate sporangiophores arranged in whorls', 'The upper surface of leafy sporophylls', 'Sori on the lower leaf surface', 'Inside sporocarps'], 0,
    'Each umbrella-shaped sporangiophore carries 5–10 sac-like sporangia; an annulus lies below the cone.'],
  ['Elaters of *Equisetum* spores are:', ['Four hygroscopic bands from the outer spore wall', 'Sterile cells in the capsule', 'Spiral thickenings of tracheids', 'Hairs on the prothallus'], 0,
    'They coil and uncoil with humidity, aiding dispersal. Liverwort elaters are sterile cells instead.'],
  ['Although homosporous, *Equisetum* often forms:', ['Some male and some bisexual gametophytes', 'Only endosporic gametophytes', 'No gametophyte', 'Gametophytes inside the strobilus'], 0,
    'Sex depends on nutrition and crowding — a physiological heterothally.'],
  ['*Equisetum* is called "scouring rush" because:', ['Its silica-rich stems were used to scour pots', 'It grows in fast streams', 'It cleans polluted water', 'Its spores are abrasive'], 0,
    'It is also called horsetail.'],
  ['*Equisetum arvense* shows:', ['Unbranched, non-green fertile shoots and green, branched sterile shoots', 'Only fertile shoots', 'Floating leaves', 'Rhizophores'], 0,
    'Fertile shoots appear in spring and die after shedding spores.'],
  ['*Equisetum* is not regarded as a primitive vascular cryptogam because:', ['It is a specialised, reduced survivor of the tree-sized Carboniferous Sphenopsida', 'It lacks vascular tissue', 'It has seeds', 'It has no alternation of generations'], 0,
    'Whorled branching, sheathing leaves, peltate sporangiophores and elaters are specialisations; *Calamites* was its giant relative.'],
  ['Compared with *Equisetum*, the vascular system of ferns is considered more advanced because ferns have:', ['Megaphylls whose leaf traces leave leaf gaps in a siphonostele or dictyostele', 'A simple protostele', 'No leaf traces', 'Only scale leaves'], 0,
    'Leaf gaps and dissected steles go with the large, complex fern leaf.']
] },
{ p: 'B1', t: 'Pteridophytes', w: 2, pyq: ['IFoS-2013-B1-m39', 'CSE-2019-B1-m28', 'CSE-1998-B1-m25', 'IFoS-2003-B1-m25', 'CSE-2006-B1-m25', 'CSE-1990-B1-m22', 'CSE-2006-B1-m17'], q: [
  ['The typical prothallus of *Dryopteris* or *Pteris* is:', ['Green, heart-shaped and monoecious, with archegonia near the apical notch', 'Subterranean and non-green', 'Endosporic and unisexual', 'Filamentous and dioecious'], 0,
    'Antheridia lie among the rhizoids towards the posterior end.'],
  ['A non-green, tuberous, subterranean mycorrhizal prothallus is typical of:', ['*Ophioglossum* and *Botrychium*', '*Pteris*', '*Marsilea*', '*Azolla*'], 0,
    'Ribbon-like or filamentous prothalli occur in *Vittaria* and *Schizaea*.'],
  ['Formation of a sporophyte from the gametophyte without fertilisation is called:', ['Apogamy', 'Apospory', 'Parthenocarpy', 'Heterospory'], 0,
    'Apospory is the reverse: a gametophyte forms from the sporophyte without meiosis.'],
  ['Fern antherozoids are:', ['Coiled and multiflagellate', 'Biflagellate', 'Non-motile', 'Amoeboid'], 0,
    'Water is needed for fertilisation.'],
  ['A heterosporous life cycle is considered more advanced than a homosporous one because it has:', ['Unisexual, reduced, endosporic gametophytes nourished by the spore', 'Free-living bisexual gametophytes', 'No alternation of generations', 'Larger gametophytes'], 0,
    'It is the step towards the seed habit.'],
  ['The leaf of *Azolla* has:', ['An upper green lobe with a cavity housing *Anabaena azollae* and a lower submerged lobe', 'Four leaflets', 'A ligule', 'A sheath at the node'], 0,
    'The cyanobacterium fixes nitrogen inside the dorsal lobe cavity.'],
  ['*Azolla* is used in rice fields as:', ['A nitrogen-fixing biofertilizer', 'A weedicide', 'A source of potassium only', 'An insect repellent'], 0,
    'It can supply a few tens of kg N/ha per crop and also suppresses weeds; also used as livestock feed.'],
  ['*Azolla* and *Marsilea* were earlier placed in Filicales mainly because they:', ['Are leptosporangiate ferns with megaphylls', 'Are homosporous', 'Lack vascular tissue', 'Have seeds'], 0,
    'Being heterosporous, they are now placed in their own order(s).'],
  ['The "walking fern" habit refers to:', ['Leaf tips that root and form new plants', 'Spores carried by wind', 'Creeping rhizomes with rhizophores', 'Floating fronds'], 0,
    'Seen in *Adiantum caudatum* and *Asplenium rhizophyllum* — a form of vegetative propagation.'],
  ['Isomorphic alternation of generations means:', ['Gametophyte and sporophyte look alike', 'The sporophyte is dependent on the gametophyte', 'Only the gametophyte is free-living', 'The gametophyte is endosporic'], 0,
    'E.g. *Ulva*, *Ectocarpus*. Heteromorphic: unlike phases, e.g. *Laminaria*, ferns.']
] },
{ p: 'B1', t: 'Pteridophytes', w: 2, pyq: ['CSE-2001-B1-m18', 'CSE-1988-B1-m26', 'CSE-1988-B1-m25', 'IFoS-2024-B1-m26', 'IFoS-2013-B1-m40', 'CSE-2006-B1-m25', 'CSE-2006-B1-m24', 'CSE-1985-B1-m01', 'CSE-1992-B1-m01', 'CSE-2016-B1-m02'], q: [
  ['*Rhynia* is known from the:', ['Rhynie Chert of Scotland, Early Devonian', 'Coal Measures of the Carboniferous', 'Jurassic of India', 'Cambrian of China'], 0,
    'Silica petrification preserved even cells and stomata.'],
  ['*Rhynia* had:', ['Leafless, rootless, dichotomous axes with terminal sporangia and a protostele', 'Megaphylls and roots', 'Seeds and cones', 'Ligulate leaves'], 0,
    'Rhizoids from a horizontal rhizome did the work of roots.'],
  ['Earliest known vascular plant fossils, from the Silurian, belong to:', ['*Cooksonia*', '*Calamites*', '*Lepidodendron*', '*Glossopteris*'], 0,
    '*Cooksonia* had naked forked axes with terminal sporangia.'],
  ['The antithetic (interpolation) theory states that the sporophyte:', ['Is a new phase interpolated between successive gametophytes', 'Is a modified gametophyte', 'Evolved from a seed', 'Arose by fusion of two gametophytes'], 0,
    'Čelakovský and Bower. The homologous theory (Pringsheim) holds the two phases were alike from the start.'],
  ['According to the enation theory, microphylls arose as:', ['Surface outgrowths of the stem that later got a vascular trace', 'Flattened branch systems', 'Modified sporangia', 'Fused telomes'], 0,
    'Megaphylls are explained by the telome theory (overtopping, planation, webbing).'],
  ['Progymnosperms such as *Archaeopteris* combined:', ['Gymnosperm-like secondary wood with free-sporing pteridophyte reproduction', 'Seeds with fern leaves', 'Flowers with fern wood', 'Moss gametophytes with fern sporophytes'], 0,
    'Beck (1960) named them; they link pteridophytes and gymnosperms.'],
  ['Archegoniatae includes:', ['Bryophytes, pteridophytes and gymnosperms', 'Algae, fungi and bryophytes', 'Only pteridophytes', 'Angiosperms and gymnosperms'], 0,
    'Cryptogams are the spore plants — algae, fungi, bryophytes and pteridophytes; gymnosperms are not cryptogams.'],
  ['The Indian regions richest in pteridophyte diversity are:', ['The Eastern Himalaya–North-East and the Western Ghats', 'The Thar desert and Kutch', 'The Deccan plateau and Bundelkhand', 'The Gangetic plains'], 0,
    'India has roughly a thousand-plus pteridophyte species (counts vary by source).'],
  ['*Aglaophyton* (formerly *Rhynia major*) is notable because its conducting cells:', ['Lack the thickenings of true tracheids', 'Are vessels', 'Are sieve tubes', 'Are absent'], 0,
    'It is treated as a pre-vascular (protracheophyte) plant.'],
  ['Stomata on the aerial axes of Rhynie Chert plants show that they:', ['Lived on land and exchanged gases with air', 'Were marine algae', 'Were parasitic', 'Were seed plants'], 0,
    'Cuticle, stomata and tracheids are key land adaptations.']
] }
);
