/* Concept sets for Botany II — PYQs added from the newer Drive PYQ Map (CSE 2026) and the integrated Botany catalogue: molecular techniques and genomes, phloem transport, β-oxidation and heat-shock proteins, ecosystems and pollution, phytogeography and forest resources. Time-sensitive figures are marked. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B2', t: 'Molecular Biology', w: 2, pyq: ['CSE-2026-B2-m05', 'CSE-2016-B2-Q1d', 'CSE-2011-B2-Q8b', 'CSE-2011-B2-Q8c', 'CSE-2026-B2-m03', 'CSE-2026-B2-m14', 'CSE-2026-B2-m12'], q: [
  ['DNA fingerprinting was developed by:', ['Alec Jeffreys (1984–85), using minisatellite (VNTR) probes', 'Kary Mullis', 'Frederick Sanger', 'E. M. Southern'], 0,
    'In India, Lalji Singh pioneered it at CCMB; CDFD, Hyderabad now offers the service.'],
  ['In plants, DNA fingerprinting is used mainly for:', ['Identifying varieties, testing genetic purity and protecting breeders\' rights', 'Measuring photosynthesis', 'Counting chromosomes', 'Soil testing'], 0,
    'SSR markers are commonly used for variety profiling.'],
  ['The C-value paradox is that:', ['Genome size does not match organism complexity, because of varying amounts of non-coding and repetitive DNA', 'All plants have the same DNA content', 'DNA content doubles every generation', 'Bacteria have the largest genomes'], 0,
    '*Paris japonica* has one of the largest known genomes, far bigger than the human genome.'],
  ['Reporter genes such as GUS and GFP are used to:', ['Show where and when a gene is expressed, or that transformation worked', 'Increase yield directly', 'Kill bacteria', 'Repair DNA'], 0,
    'GUS (*uidA*) turns blue with X-Gluc; GFP comes from the jellyfish *Aequorea victoria*.'],
  ['To confirm that a cloned gene is expressed, one detects its:', ['mRNA by northern blot or RT-PCR, and protein by western blot', 'DNA by Southern blot only', 'Chromosome number', 'Seed weight'], 0,
    'A Southern blot only shows that the gene is present.'],
  ['Southern, northern and western blots detect respectively:', ['DNA, RNA and protein', 'RNA, DNA and lipid', 'Protein, DNA and RNA', 'Lipid, protein and DNA'], 0,
    'E. M. Southern devised DNA blotting in 1975.'],
  ['The three steps of each PCR cycle are:', ['Denaturation (~94 °C), primer annealing (~50–65 °C) and extension (72 °C) by *Taq* polymerase', 'Cutting, ligating and cloning', 'Transcription, splicing and translation', 'Freezing, thawing and drying'], 0,
    '*Taq* polymerase comes from *Thermus aquaticus*.'],
  ['Fluorescence in situ hybridisation (FISH) is used to:', ['Locate specific DNA sequences on chromosomes with fluorescent probes', 'Measure enzyme activity', 'Sequence proteins', 'Count stomata'], 0,
    'It helps identify chromosomes and genome composition in hybrids.'],
  ['Compared with morphological markers, molecular markers are:', ['Numerous, unaffected by environment and scorable at any growth stage', 'Few and environment-dependent', 'Visible only in flowers', 'Always dominant'], 0,
    'They support marker-assisted selection, mapping and diversity studies.'],
  ['Messenger RNA leaves the nucleus:', ['Through nuclear pore complexes, after capping, splicing and polyadenylation', 'By diffusing through the nuclear membrane', 'Only during mitosis', 'Through mitochondria'], 0,
    'Export receptors carry it; signals in the 3′ untranslated region can direct its location in the cytoplasm.']
] },
{ p: 'B2', t: 'Water Relations & Mineral Nutrition', w: 2, pyq: ['CSE-2026-B2-m17', 'CSE-2018-B2-Q5c', 'CSE-2017-B2-Q5a', 'CSE-2026-B2-m19'], q: [
  ['Münch\'s pressure-flow hypothesis explains phloem transport by:', ['Sugar loading at the source drawing in water and creating turgor that pushes sap to sinks', 'Transpiration pull', 'Root pressure', 'Cytoplasmic streaming only'], 0,
    'Unloading at sinks lowers pressure there.'],
  ['Evidence for pressure flow in the phloem includes:', ['Sap exuding under pressure from cut aphid stylets', 'Guttation from leaf tips', 'Ascent of sap in dead xylem', 'Opening of stomata'], 0,
    'Ringing experiments also show sugars move in the bark.'],
  ['Apoplastic phloem loading uses:', ['A sucrose–proton symporter in companion cells driven by a proton-pumping ATPase', 'Plasmodesmata only', 'Xylem vessels', 'Passive diffusion only'], 0,
    'Symplastic "polymer trapping" (raffinose and stachyose) occurs in cucurbits.'],
  ['Mature sieve tube elements:', ['Lack a nucleus and depend on companion cells', 'Are dead and lignified', 'Have large nuclei', 'Store starch only'], 0,
    'Callose and P-protein seal damaged sieve plates.'],
  ['In plants, β-oxidation of fatty acids occurs mainly in:', ['Glyoxysomes and peroxisomes', 'Mitochondria only', 'Chloroplasts', 'The nucleus'], 0,
    'In animals it is mainly mitochondrial.'],
  ['Each turn of β-oxidation:', ['Removes a two-carbon unit as acetyl-CoA', 'Adds two carbons to the chain', 'Releases glucose', 'Fixes CO₂'], 0,
    'In plants, the first oxidation step forms H₂O₂ through acyl-CoA oxidase.'],
  ['The glyoxylate cycle lets germinating oilseeds:', ['Convert fat-derived acetyl-CoA into succinate and then sugars', 'Fix nitrogen', 'Make chlorophyll', 'Store starch in roots'], 0,
    'Its key enzymes are isocitrate lyase and malate synthase.'],
  ['Heat shock proteins (HSPs) protect cells by:', ['Acting as molecular chaperones that prevent protein misfolding and aggregation', 'Breaking down DNA', 'Closing stomata', 'Making cellulose'], 0,
    'Major families include HSP70, HSP90 and small HSPs.'],
  ['Heat shock genes are switched on by:', ['Heat shock factors (HSFs) binding heat shock elements in their promoters', 'Phytochrome only', 'Cytokinin only', 'Light-harvesting complexes'], 0,
    'Other stresses such as drought and salinity can also induce HSPs.'],
  ['Acquired thermotolerance means:', ['A mild heat exposure induces HSPs that let the plant survive a later, otherwise lethal heat stress', 'Plants are born heat-resistant', 'Heat kills all plants equally', 'Cold improves heat tolerance'], 0,
    'It is important for crops facing terminal heat.']
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 2, pyq: ['CSE-2017-B2-Q5d', 'IFoS-2011-B2-Q8a', 'IFoS-2011-B2-Q5e', 'CSE-2026-B2-m20', 'CSE-2026-B2-m28'], q: [
  ['Biotic factors of an environment include:', ['Interactions such as competition, predation, parasitism, mutualism and allelopathy', 'Temperature and rainfall', 'Soil texture', 'Altitude'], 0,
    'Abiotic factors are the physical and chemical conditions.'],
  ['An ecosystem consists of:', ['Abiotic components and biotic components (producers, consumers and decomposers) linked by energy flow and nutrient cycling', 'Only plants', 'Only animals', 'Only soil'], 0,
    'Tansley coined the term "ecosystem" in 1935.'],
  ['A biome is:', ['A large regional community defined by climate and dominant vegetation, such as tropical rainforest or tundra', 'A single pond', 'One species population', 'A soil horizon'], 0,
    'Whittaker related biomes to mean annual temperature and precipitation.'],
  ['Biogeochemical cycles are classed as gaseous or sedimentary; a sedimentary cycle is that of:', ['Phosphorus', 'Nitrogen', 'Carbon', 'Oxygen'], 0,
    'Phosphorus has no major atmospheric reservoir.'],
  ['In the carbon cycle, carbon returns to the atmosphere mainly by:', ['Respiration, decomposition and burning of fuels', 'Photosynthesis', 'Nitrogen fixation', 'Weathering only'], 0,
    'Oceans and forests are major carbon sinks.'],
  ['Acid rain is caused by:', ['Sulphur dioxide and nitrogen oxides forming sulphuric and nitric acids, giving rain pH below about 5.6', 'Carbon monoxide', 'Ozone in the stratosphere', 'Methane from rice'], 0,
    'It damages leaves, leaches soil nutrients and acidifies lakes.'],
  ['Photochemical smog forms when:', ['Nitrogen oxides and hydrocarbons react in sunlight to give ozone and peroxyacetyl nitrate (PAN)', 'Fog mixes with smoke in winter only', 'Sulphur dioxide dissolves in rain', 'Methane burns'], 0,
    'PAN and ozone cause silvering and bronzing of leaves.'],
  ['Persistent biocides such as DDT become serious pollutants because they:', ['Biomagnify, reaching high levels at the top of food chains', 'Break down within hours', 'Are water-soluble and quickly excreted', 'Help all organisms'], 0,
    'DDT thinned eggshells of fish-eating birds.'],
  ['Renewable energy resources include:', ['Solar, wind, hydro, biomass and geothermal energy', 'Coal and petroleum', 'Natural gas only', 'Uranium only'], 0,
    'Time-sensitive: India targets 500 GW of non-fossil capacity by 2030.'],
  ['Biomass energy is renewable because:', ['Plants regrow and fix the CO₂ released when biomass is burnt', 'It is unlimited without replanting', 'It produces no emissions', 'It comes from fossils'], 0,
    'Biogas, bioethanol and biodiesel are biomass fuels.']
] },
{ p: 'B2', t: 'Plant Geography, Forests & Biodiversity', w: 2, pyq: ['CSE-2026-B2-m31', 'CSE-2026-B2-m32', 'CSE-2026-B2-m34'], q: [
  ['Phytogeography is the study of:', ['The geographical distribution of plants and the climatic, soil and historical factors behind it', 'Plant chemistry', 'Plant hormones', 'Fossil pollen only'], 0,
    'It includes floristic and ecological plant geography.'],
  ['Ronald Good divided the world flora into floral kingdoms, including:', ['Holarctic, Palaeotropical, Neotropical, Australian, Cape and Antarctic', 'Asian, African and European only', 'Tropical and temperate only', 'Northern and southern only'], 0,
    'The tiny Cape kingdom of South Africa is extraordinarily rich.'],
  ['D. Chatterjee\'s phytogeographical regions of India include:', ['Western and Eastern Himalaya, Indus plain, Gangetic plain, Central India, Deccan, Malabar and Assam', 'Only Himalaya and Deccan', 'Only coastal regions', 'Only the Thar Desert'], 0,
    'The Andaman and Nicobar Islands are often treated as a separate region.'],
  ['Disjunct distribution of the southern beech *Nothofagus* in South America, Australia and New Zealand is explained by:', ['Continental drift — the break-up of Gondwana', 'Recent seed dispersal by birds', 'Human planting', 'Glaciation in Asia'], 0,
    'Wegener proposed continental drift.'],
  ['India\'s centres of high plant endemism include:', ['The Western Ghats and the Eastern Himalaya', 'The Indo-Gangetic plain', 'The Thar Desert only', 'The Deccan plateau only'], 0,
    'Both lie in global biodiversity hotspots.'],
  ['Champion and Seth (1968) classified Indian forests into:', ['16 type groups and about 200 forest types', '5 type groups', '50 type groups', '2 type groups'], 0,
    'It remains the standard forest-type classification.'],
  ['According to ISFR 2023, India\'s forest cover is about:', ['21.8% of the geographical area (about 25% with tree cover)', '33%', '10%', '50%'], 0,
    'Time-sensitive; ISFR is published every two years by the Forest Survey of India, Dehradun.'],
  ['The state with the largest forest cover by area is:', ['Madhya Pradesh', 'Kerala', 'Punjab', 'Haryana'], 0,
    'Time-sensitive (ISFR 2023): Arunachal Pradesh and Chhattisgarh follow.'],
  ['The most extensive forest type group in India is:', ['Tropical dry deciduous forest', 'Alpine scrub', 'Littoral and swamp forest', 'Subtropical pine forest'], 0,
    'Tropical moist deciduous forest comes second.'],
  ['The National Forest Policy, 1988 aims at:', ['One-third of the geographical area under forest or tree cover (two-thirds in hills)', '10% forest cover', 'Converting forests to farms', 'Only timber production'], 0,
    'It made ecological security and people\'s needs the priority.']
] }
);
