/* Concept sets for Agriculture I — Extension, farm economics and agricultural policy. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Agricultural Extension', w: 3, pyq: ['CSE-2015-A1-m12', 'IFoS-2012-A1-m21', 'IFoS-2009-A1-m11', 'CSE-2007-A1-m07', 'IFoS-2003-A1-m15', 'IFoS-2002-A1-m03', 'IFoS-2003-A1-m18', 'IFoS-2024-A1-m16', 'IFoS-2021-A1-m12', 'IFoS-2021-A1-m15', 'CSE-2020-A1-m13', 'IFoS-2009-A1-m10', 'IFoS-2020-A1-m16', 'IFoS-2023-A1-m13', 'IFoS-2017-A1-Q8b', 'IFoS-2017-A1-Q8d', 'CSE-2021-A1-m17', 'CSE-2004-A1-m07', 'CSE-2018-A1-m04', 'CSE-1992-A1-m07', 'IFoS-2012-A1-m15', 'IFoS-2011-A1-m13', 'IFoS-2011-A1-m15', 'IFoS-2012-A1-m14', 'IFoS-2012-A1-m11'], q: [
  ['A method demonstration differs from a result demonstration in that it shows:', ['How to carry out a practice, step by step', 'The final benefit of a practice compared with the old one', 'Market prices', 'Only yields'], 0,
    'Result demonstrations prove the worth of a practice; Seaman Knapp popularised demonstrations.'],
  ['Front-line demonstrations (FLDs) are conducted by:', ['Scientists of ICAR institutes, SAUs and KVKs on farmers\' fields', 'Village panchayats only', 'Input dealers', 'Banks'], 0,
    'They show the newest technologies before they reach the general extension system.'],
  ['Which is a mass extension method?', ['Radio and television programmes', 'Farm and home visits', 'Method demonstrations', 'Office calls'], 0,
    'Group methods include meetings, field days and tours; individual methods include farm visits.'],
  ['The Farmers\' Field School approach was developed by FAO in:', ['Indonesia (1989), for rice IPM', 'India (1952)', 'USA (1914)', 'Kenya (2000)'], 0,
    'Farmers learn by discovery through a whole season on a field.'],
  ['A Farmers\' Field School is best described as:', ['Season-long, group-based experiential learning on a farmer\'s field', 'A classroom lecture series', 'A radio programme', 'A credit scheme'], 0,
    'Agro-ecosystem analysis is a key weekly activity.'],
  ['The main role of an extension worker in technology transfer is to:', ['Link research and farmers — diagnose needs, teach, motivate and feed back problems', 'Sell inputs', 'Collect taxes', 'Grant loans'], 0,
    'They also help farmers adapt technologies to local conditions.'],
  ['Competencies needed by an extension worker include:', ['Technical knowledge, communication, human-relations and managerial skills', 'Only technical skills', 'Only accounting', 'Only driving'], 0,
    'Communication is often the deciding skill.'],
  ['In-service training of extension staff is given:', ['During their service to update knowledge and skills', 'Before joining only', 'Only at retirement', 'To farmers only'], 0,
    'Pre-service and induction training come earlier.'],
  ['According to Edgar Dale\'s cone of experience, learning is most effective through:', ['Direct, purposeful experience', 'Verbal symbols only', 'Visual symbols only', 'Reading'], 0,
    'This is why demonstrations and field practice work well.'],
  ['Field days are used mainly to:', ['Let many farmers see results of a technology on demonstration plots', 'Distribute loans', 'Collect soil samples', 'Sell produce'], 0,
    'They are a group extension method.']
] },
{ p: 'A1', t: 'Agricultural Extension', w: 3, pyq: ['CSE-2025-A1-m14', 'IFoS-2024-A1-m20', 'CSE-1999-A1-m09', 'CSE-1990-A1-m11', 'IFoS-2020-A1-m12', 'CSE-2014-A1-m13', 'CSE-1998-A1-m09', 'IFoS-2021-A1-m19', 'IFoS-2013-A1-m25', 'CSE-1994-A1-m10', 'CSE-2024-A1-m15', 'CSE-1998-A1-m07', 'CSE-1996-A1-m06', 'CSE-2007-A1-m10', 'IFoS-2023-A1-m19', 'CSE-2013-A1-m16', 'IFoS-2022-A1-m21', 'CSE-2014-A1-m15', 'IFoS-2016-A1-m22', 'IFoS-2021-A1-m18', 'CSE-2021-A1-m18', 'CSE-1990-A1-m10', 'IFoS-2012-A1-m17', 'IFoS-2005-A1-m08', 'IFoS-2022-A1-m16', 'IFoS-2016-A1-m19', 'IFoS-2011-A1-m12', 'IFoS-2013-A1-m13', 'IFoS-2012-A1-m13', 'IFoS-2012-A1-m10', 'IFoS-2013-A1-m20'], q: [
  ['The Community Development Programme in India was launched on:', ['2 October 1952', '15 August 1947', '26 January 1950', '1 April 1966'], 0,
    'The National Extension Service followed in 1953.'],
  ['The Lab to Land Programme was started by ICAR in:', ['1979, its golden jubilee year', '1952', '1990', '2005'], 0,
    'It aimed at small, marginal farmers and landless labourers.'],
  ['The Training and Visit (T&V) system was designed by:', ['Daniel Benor, with World Bank support', 'M. S. Swaminathan', 'Norman Borlaug', 'Verghese Kurien'], 0,
    'It used fortnightly training of village workers and fixed visits to contact farmers.'],
  ['ATMA (Agricultural Technology Management Agency) works at the:', ['District level, with bottom-up planning through a Strategic Research and Extension Plan', 'Village level only', 'National level only', 'Block level only, without farmers'], 0,
    'It was piloted under NATP (1998) and works through farmer interest groups.'],
  ['The first Krishi Vigyan Kendra was set up in 1974 at:', ['Puducherry', 'New Delhi', 'Pune', 'Ludhiana'], 0,
    'The Mohan Singh Mehta committee recommended KVKs.'],
  ['ICAR\'s "Farmer FIRST" programme stands for:', ['Farm, Innovations, Resources, Science and Technology', 'Farmers First in Rural Schemes and Training', 'Food, Income, Rural Security and Trade', 'First Integrated Rural Scheme'], 0,
    'It builds a farmer–scientist interface for technology development.'],
  ['Commodity-based extension is typified by:', ['Commodity boards such as those for tea, coffee and rubber', 'Village-level workers covering all crops', 'Mass media', 'Panchayats'], 0,
    'Broad-based extension covers all farming enterprises of a household.'],
  ['Market-led extension aims to:', ['Help farmers produce what the market wants, with price and quality information', 'Increase production regardless of demand', 'Ban markets', 'Only distribute seed'], 0,
    'It shifts from production-led to market-led thinking.'],
  ['Technology assessment and refinement at KVKs is done mainly through:', ['On-farm trials', 'Laboratory tests only', 'Radio talks', 'Market surveys'], 0,
    'FLDs then demonstrate refined technologies.'],
  ['The national institute for training in agricultural extension management is:', ['MANAGE, Hyderabad', 'IARI, New Delhi', 'NIRD, Delhi', 'NAARM, Pune'], 0,
    'State-level counterparts are SAMETIs.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 3, pyq: ['CSE-2022-A1-m16', 'CSE-2018-A1-m12', 'CSE-2010-A1-m19', 'CSE-2021-A1-m15', 'IFoS-2019-A1-m17', 'IFoS-2015-A1-m11', 'CSE-2022-A1-m17', 'CSE-2016-A1-m13', 'CSE-2013-A1-m17', 'IFoS-2015-A1-m07', 'IFoS-2013-A1-m23', 'CSE-2019-A1-m14', 'IFoS-2024-A1-m19', 'IFoS-2020-A1-m14', 'CSE-2020-A1-m14', 'CSE-2018-A1-m13'], q: [
  ['Under PMFBY (2016), farmers\' premium for kharif food and oilseed crops is capped at:', ['2% of sum insured', '5%', '1.5%', '10%'], 0,
    'Rabi food and oilseed crops: 1.5%; commercial and horticultural crops: 5%.'],
  ['PMFBY uses an "area approach", meaning:', ['Losses are assessed for a defined insurance unit, such as a village, rather than each field', 'Only large farms are covered', 'Only irrigated areas are covered', 'Each plant is insured'], 0,
    'Localised calamities and post-harvest losses can be assessed individually.'],
  ['The Kisan Credit Card scheme was introduced in:', ['1998, through NABARD', '1969', '2015', '1952'], 0,
    'It was later extended to animal husbandry and fisheries.'],
  ['Soil Health Cards, launched in 2015, give farmers:', ['Soil test results and crop-wise fertiliser recommendations', 'Free fertiliser', 'Insurance cover', 'Loans'], 0,
    'Cards were to be issued at regular intervals.'],
  ['MGNREGA guarantees each rural household:', ['100 days of wage employment a year', '365 days of work', 'Free seed', 'A pension'], 0,
    'Many of its works are for water conservation and land development.'],
  ['e-NAM, launched in April 2016, is:', ['An online trading platform linking APMC mandis', 'A crop insurance scheme', 'A seed portal', 'A weather service'], 0,
    'It aims at "One Nation, One Market".'],
  ['The "Platform of Platforms" under e-NAM:', ['Connects e-NAM with other value-chain platforms such as logistics, assaying and warehousing', 'Replaces all mandis', 'Is a price-support scheme', 'Is a fertiliser portal'], 0,
    'It was launched in 2022.'],
  ['The three farm laws of 2020 were:', ['Repealed in late 2021 after farmer protests', 'Still in force everywhere', 'Never passed', 'Only for plantation crops'], 0,
    'They dealt with trade outside APMCs, contract farming and stock limits.'],
  ['The committee on Doubling Farmers\' Income was chaired by:', ['Ashok Dalwai', 'M. S. Swaminathan', 'Ramesh Chand', 'Y. K. Alagh'], 0,
    'Its strategies include higher productivity, lower costs, better prices and diversification.'],
  ['Restructured Weather-Based Crop Insurance (RWBCIS) pays claims based on:', ['Deviations in weather indices such as rainfall and temperature', 'Actual field yield cuts only', 'Market prices', 'Farm size'], 0,
    'It avoids lengthy crop-cutting experiments.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: ['CSE-2011-A1-m01', 'CSE-2006-A1-m02', 'CSE-2003-A1-m07', 'CSE-2012-A1-m05', 'IFoS-2014-A1-m19', 'CSE-1990-A1-m09', 'IFoS-2014-A1-m20', 'IFoS-2020-A1-m23', 'IFoS-2014-A1-m21', 'CSE-2013-A1-m06'], q: [
  ['FAO\'s four pillars of food security are:', ['Availability, access, utilisation and stability', 'Production, storage, export and import', 'Land, labour, capital and enterprise', 'Rice, wheat, pulses and oil'], 0,
    'Defined at the 1996 World Food Summit.'],
  ['The National Food Security Act, 2013 covers up to:', ['75% of the rural and 50% of the urban population', 'All citizens', '25% of rural people', 'Only BPL families in cities'], 0,
    'Time-sensitive: grain under NFSA is now distributed free.'],
  ['Kwashiorkor differs from marasmus in that kwashiorkor is due mainly to:', ['Protein deficiency, with oedema', 'Calorie deficiency, with severe wasting', 'Vitamin A deficiency', 'Iron deficiency'], 0,
    'Both are forms of protein–energy malnutrition.'],
  ['India\'s largest agricultural import item by value is usually:', ['Edible (vegetable) oils', 'Wheat', 'Rice', 'Tea'], 0,
    'The National Mission on Edible Oils aims to cut this dependence.'],
  ['Post-harvest losses of fruits and vegetables in India are high mainly because of:', ['Poor cold chain, handling and storage', 'Too many processing units', 'Excess demand', 'Over-regulation of exports'], 0,
    'Cold storage and processing capacity are key fixes.'],
  ['Sustainable agriculture aims to:', ['Meet present food needs while conserving soil, water and biodiversity for the future', 'Maximise short-term yields only', 'Use only chemical inputs', 'Stop all farming'], 0,
    'It balances productivity, profitability and environmental health.'],
  ['Heavy use of subsidised electricity in agriculture has mainly led to:', ['Over-pumping and falling groundwater tables', 'Lower irrigation', 'More rainfall', 'Less use of pumps'], 0,
    'Solar pumps under PM-KUSUM are one response.'],
  ['The WTO Agreement on Agriculture (1995) deals with:', ['Market access, domestic support and export subsidies', 'Only seed patents', 'Only fertiliser trade', 'Only fisheries'], 0,
    'Domestic support is classed into amber, blue and green boxes.'],
  ['To raise sugar output without expanding area, the main lever is:', ['Higher cane yield and better sugar recovery through improved varieties and management', 'Planting cane in deserts', 'Reducing ratoons to zero', 'Harvesting immature cane'], 0,
    'Varieties such as Co 0238 raised recovery in north India.'],
  ['Agricultural trade matters to the national economy because it:', ['Earns foreign exchange and supports farm incomes and food supplies', 'Has no economic effect', 'Only adds costs', 'Stops domestic production'], 0,
    'India is a major exporter of rice, spices and marine products.']
] },
{ p: 'A1', t: 'Farm Economics, Marketing & Policy', w: 2, pyq: ['IFoS-2023-A1-m14', 'IFoS-2003-A1-m19', 'CSE-2020-A1-m17', 'CSE-2010-A1-m20', 'IFoS-2010-A1-m11', 'CSE-2002-A1-m06', 'CSE-1996-A1-m07', 'IFoS-2024-A1-m15', 'IFoS-2019-A1-m11', 'IFoS-2013-A1-m12', 'IFoS-2012-A1-m09', 'IFoS-2013-A1-m10'], q: [
  ['Farm records that list all assets and liabilities at a point in time are:', ['Inventory records', 'Production records', 'Labour records', 'Cash diaries'], 0,
    'Records help in farm planning, budgeting and credit.'],
  ['A farmer should keep farm records mainly to:', ['Analyse costs and returns and make better decisions', 'Pay more taxes', 'Satisfy curiosity', 'Avoid planning'], 0,
    'They also support loan applications.'],
  ['In CACP cost concepts, Cost A2 + FL includes:', ['Paid-out costs plus the imputed value of family labour', 'Only paid-out costs', 'All costs including land rent and interest on owned capital', 'Only fixed costs'], 0,
    'Cost C2 adds rent of owned land and interest on owned fixed capital.'],
  ['Since 2018, MSP for kharif crops has been fixed at about:', ['1.5 times Cost A2 + FL', '2 times C2', 'Equal to A1', 'Market price minus 10%'], 0,
    'Time-sensitive policy detail.'],
  ['Fixed costs differ from variable costs in that fixed costs:', ['Do not change with the level of output', 'Rise with output', 'Are zero in the short run', 'Include seeds and fertiliser'], 0,
    'Land rent and depreciation are fixed; seed and fertiliser are variable.'],
  ['Marketable surplus is:', ['The part of produce theoretically available for sale after family needs', 'The total production', 'The amount actually sold', 'The amount lost'], 0,
    'Marketed surplus is what is actually sold.'],
  ['Producer\'s surplus is:', ['The difference between the price received and the minimum price a producer would accept', 'Total revenue', 'Profit after tax', 'Cost of production'], 0,
    'In agricultural marketing it is often used loosely for marketable surplus.'],
  ['Farmer Producer Organisations are commonly registered as:', ['Producer companies under the Companies Act or as cooperatives', 'Private limited companies only', 'Government departments', 'Banks'], 0,
    'A central scheme (2020) aims at forming 10,000 FPOs.'],
  ['"Secondary agriculture" refers to:', ['Value addition and allied activities such as processing, beekeeping and mushroom growing', 'Growing a second crop', 'Weeding', 'Irrigation'], 0,
    'It raises farm incomes beyond primary crop production.'],
  ['In socio-economic surveys, a schedule differs from a questionnaire in that a schedule is:', ['Filled in by the investigator while interviewing', 'Mailed to respondents to fill in', 'A government record', 'A price list'], 0,
    'Sample surveys are cheaper than a full census.']
] }
);
