/* Concept sets for Botany I — Microbiology, viruses & plant pathology. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Microbiology', w: 3, pyq: ['IFoS-2023-B1-m19', 'IFoS-2023-B1-m22', 'CSE-2022-B1-m21', 'CSE-2020-B1-m18', 'IFoS-2009-B1-m27', 'IFoS-2007-B1-m19', 'IFoS-2004-B1-m21', 'IFoS-2024-B1-m21', 'IFoS-2019-B1-m15', 'IFoS-2012-B1-m40', 'CSE-2007-B1-m21', 'IFoS-2002-B1-m20', 'CSE-1997-B1-m20', 'IFoS-2020-B1-m18', 'IFoS-2010-B1-m33', 'CSE-2007-B1-m20', 'CSE-2022-B1-m18', 'IFoS-2013-B1-m33', 'CSE-2002-B1-m15', 'IFoS-2011-B1-m26', 'CSE-2004-B1-m21'], q: [
  ['The cell wall of Gram-positive bacteria has:', ['A thick peptidoglycan layer with teichoic acids and no outer membrane', 'A thin peptidoglycan layer and an outer membrane with LPS', 'No peptidoglycan', 'Cellulose and chitin'], 0,
    'Gram-negative walls have thin peptidoglycan, a periplasm and an LPS outer membrane with porins.'],
  ['The correct order of reagents in Gram staining is:', ['Crystal violet → iodine → alcohol → safranin', 'Safranin → alcohol → iodine → crystal violet', 'Iodine → crystal violet → safranin → alcohol', 'Alcohol → crystal violet → safranin → iodine'], 0,
    'Gram-positive cells stay purple; Gram-negative cells lose the dye and take up pink safranin.'],
  ['Lysozyme damages bacterial walls by:', ['Breaking the β-1,4 links between NAM and NAG in peptidoglycan', 'Blocking protein synthesis', 'Dissolving the outer membrane lipids', 'Inhibiting DNA replication'], 0,
    'Penicillin instead blocks the peptide cross-linking (transpeptidation) of new wall.'],
  ['The flagellar basal body of a Gram-negative bacterium has:', ['Four rings — L, P, MS and C', 'Only two rings', 'No rings', 'A 9+2 axoneme'], 0,
    'Gram-positive cells lack L and P rings. The bacterial flagellum rotates, driven by proton motive force.'],
  ['Peritrichous flagellation means:', ['Flagella all over the cell surface', 'One flagellum at one pole', 'A tuft at one pole', 'One flagellum at each pole'], 0,
    'E.g. *E. coli*. Monotrichous, lophotrichous and amphitrichous are the other types.'],
  ['The sex pilus of bacteria is used for:', ['Making contact for DNA transfer in conjugation', 'Swimming', 'Storing food', 'Spore formation'], 0,
    'Common pili (fimbriae) help cells stick to surfaces.'],
  ['Cocci arranged in cubical packets of eight are called:', ['Sarcinae', 'Streptococci', 'Staphylococci', 'Diplococci'], 0,
    'Chains (streptococci) form from division in one plane; grape-like clusters (staphylococci) from random planes; sarcinae from three planes.'],
  ['Endospores of *Bacillus* resist heat largely because of:', ['Calcium dipicolinate and a dehydrated core', 'A thick capsule', 'Pili', 'Plasmids'], 0,
    'Layers: core, inner membrane, cortex, spore coat and sometimes exosporium.'],
  ['Endospores are produced mainly by:', ['*Bacillus* and *Clostridium*', '*E. coli* and *Salmonella*', '*Rhizobium* and *Azotobacter*', '*Streptococcus* and *Staphylococcus*'], 0,
    'One spore forms per cell — it is a survival, not a multiplication, device.'],
  ['Mesosomes, once described as membrane infoldings for respiration, are now regarded as:', ['Artefacts of chemical fixation for electron microscopy', 'Bacterial mitochondria', 'Sites of photosynthesis', 'Ribosome clusters'], 0,
    'Cryo-fixed cells do not show them.']
] },
{ p: 'B1', t: 'Microbiology', w: 3, pyq: ['IFoS-2024-B1-m19', 'IFoS-2022-B1-m17', 'IFoS-2020-B1-m22', 'IFoS-2017-B1-Q3c', 'CSE-2017-B1-m18', 'IFoS-2015-B1-m17', 'CSE-2013-B1-m16', 'CSE-2000-B1-m14', 'CSE-1990-B1-m45', 'CSE-2021-B1-m22', 'IFoS-2009-B1-m28', 'CSE-2005-B1-m19', 'CSE-1994-B1-m34', 'CSE-1993-B1-m22', 'CSE-1988-B1-m21', 'CSE-2023-B1-m21', 'CSE-1986-B1-m21', 'CSE-2010-B1-m24', 'IFoS-2019-B1-m18', 'CSE-1995-B1-m27', 'CSE-2001-B1-m13', 'IFoS-2004-B1-m22', 'IFoS-2023-B1-m17'], q: [
  ['The three modes of gene transfer in bacteria are:', ['Transformation, conjugation and transduction', 'Mitosis, meiosis and fusion', 'Budding, fission and sporulation', 'Mutation, selection and drift'], 0,
    'None involves fusion of whole cells — bacteria have no true syngamy.'],
  ['Transformation is uptake of:', ['Free DNA from the surroundings by a competent cell', 'DNA through a pilus', 'DNA carried by a phage', 'A whole cell'], 0,
    'Griffith (1928) saw it in *Pneumococcus*; Avery, MacLeod and McCarty (1944) showed the agent is DNA.'],
  ['Conjugation was discovered in *E. coli* by:', ['Lederberg and Tatum (1946)', 'Zinder and Lederberg (1952)', 'Griffith (1928)', 'Hershey and Chase (1952)'], 0,
    'Zinder and Lederberg discovered transduction in *Salmonella*.'],
  ['In an F⁺ × F⁻ cross:', ['The F plasmid is copied into the recipient, which becomes F⁺', 'The whole chromosome is transferred', 'The recipient becomes Hfr', 'No DNA is transferred'], 0,
    'Chromosomal genes are rarely transferred in this cross.'],
  ['An Hfr strain:', ['Has the F factor integrated into its chromosome and transfers chromosomal genes in a fixed order', 'Lacks the F factor', 'Cannot conjugate', 'Transfers only plasmid genes'], 0,
    'The recipient seldom becomes Hfr because the whole chromosome rarely gets across.'],
  ['Interrupted-mating experiments (Wollman and Jacob) map genes by:', ['Time of entry into the recipient', 'Recombination frequency in meiosis', 'Restriction sites', 'Phage plaques'], 0,
    'The map unit is minutes of transfer.'],
  ['Match the plasmid with its function: Ti plasmid —', ['Tumour induction in plants by *Agrobacterium*', 'Antibiotic resistance', 'Colicin production', 'Fertility (F)'], 0,
    'R plasmids carry resistance; Col plasmids make colicins; TOL plasmids of *Pseudomonas* degrade toluene.'],
  ['Plasmids are:', ['Extrachromosomal, self-replicating, usually circular DNA molecules', 'Parts of ribosomes', 'Viral protein coats', 'Linear RNA molecules'], 0,
    'Many carry genes useful only under stress, such as resistance.'],
  ['Bacteria spread antibiotic resistance fast mainly through:', ['Horizontal transfer of R plasmids and transposons', 'Meiosis', 'Spore formation', 'Cell-wall thickening only'], 0,
    'Mechanisms include drug-inactivating enzymes (β-lactamase), efflux pumps and altered targets.'],
  ['After gene transfer, a bacterium carrying part of a donor genome is called a:', ['Merozygote (partial diploid)', 'True zygote', 'Heterokaryon', 'Spheroplast'], 0,
    'Recombination then swaps segments into the recipient chromosome.']
] },
{ p: 'B1', t: 'Microbiology', w: 3, pyq: ['IFoS-2024-B1-m20', 'CSE-2022-B1-m17', 'CSE-2018-B1-m18', 'CSE-2016-B1-m23', 'CSE-1999-B1-m15', 'CSE-2021-B1-m21', 'CSE-2012-B1-m23', 'CSE-1990-B1-m35', 'CSE-2019-B1-m22', 'IFoS-2006-B1-m20', 'IFoS-2001-B1-m22', 'CSE-2025-B1-m20', 'IFoS-2000-B1-m20', 'IFoS-2019-B1-m16', 'CSE-2023-B1-m20', 'CSE-2023-B1-m23'], q: [
  ['Mycoplasmas are:', ['The smallest free-living prokaryotes, without a cell wall', 'Viruses with a protein coat', 'Fungi with a cell wall', 'Algae'], 0,
    'They are pleomorphic and placed in class Mollicutes.'],
  ['Mycoplasmas resist penicillin because they:', ['Have no cell wall', 'Have a thick wall', 'Make β-lactamase always', 'Live in the nucleus'], 0,
    'Plant phytoplasmas respond to tetracyclines.'],
  ['Phytoplasma diseases of plants are usually transmitted by:', ['Leafhoppers and other phloem-feeding insects', 'Wind', 'Soil water', 'Pollen'], 0,
    'Phytoplasmas live in the phloem.'],
  ['Which is a phytoplasma disease?', ['Little leaf of brinjal', 'Late blight of potato', 'Citrus canker', 'Tikka of groundnut'], 0,
    'Others: sandal spike, grassy shoot of sugarcane, sesame phyllody.'],
  ['Unlike mycoplasmas, protoplasts and spheroplasts are:', ['Cells whose wall has been removed artificially (fully or partly)', 'Naturally wall-less', 'Viruses', 'Fungal spores'], 0,
    'Protoplasts come from Gram-positive cells; spheroplasts keep outer-membrane remnants.'],
  ['Viroids are:', ['Small circular single-stranded RNAs with no protein coat', 'Proteins without nucleic acid', 'DNA viruses', 'Bacteria without walls'], 0,
    'Diener (1971) described potato spindle tuber viroid; coconut cadang-cadang is another.'],
  ['Viroids replicate using:', ['The host\'s RNA polymerase by a rolling-circle mechanism', 'Their own replicase', 'Reverse transcriptase', 'Ribosomes'], 0,
    'They code for no protein.'],
  ['Prions are:', ['Infectious misfolded proteins without nucleic acid', 'Small RNAs', 'Wall-less bacteria', 'Satellite viruses'], 0,
    'Prusiner (1982). PrPˢᶜ converts normal PrPᶜ into the misfolded form.'],
  ['A prion disease is:', ['Mad cow disease (BSE)', 'Potato spindle tuber', 'TMV mosaic', 'Little leaf'], 0,
    'Others: scrapie of sheep, Creutzfeldt–Jakob disease and kuru in humans.'],
  ['Virusoids are:', ['Satellite RNAs packaged inside the coat of a helper virus', 'Free viroids', 'Prions', 'Plasmids'], 0,
    'Viroids are naked; virusoids depend on a helper virus.']
] },
{ p: 'B1', t: 'Plant Pathology', w: 2, pyq: ['CSE-1996-B1-m31', 'CSE-1992-B1-m32', 'IFoS-2003-B1-m23', 'IFoS-2020-B1-m23', 'IFoS-2013-B1-m34', 'CSE-2007-B1-m19', 'CSE-2025-B1-m22', 'CSE-1997-B1-m16', 'CSE-1990-B1-m43', 'CSE-2018-B1-m19', 'CSE-1990-B1-m34'], q: [
  ['Yellow vein mosaic of bhindi is caused by a begomovirus spread by:', ['Whitefly (*Bemisia tabaci*)', 'Aphids', 'Nematodes', 'Soil water'], 0,
    'Mungbean yellow mosaic is also whitefly-borne.'],
  ['Papaya leaf curl is transmitted by:', ['Whitefly', 'Aphid', 'Mealy bug', 'Thrips'], 0,
    'Papaya ring spot is aphid-borne.'],
  ['Most plant viruses are transmitted by:', ['Insect vectors, especially aphids', 'Wind', 'Spores', 'Rain splash only'], 0,
    'Others: sap (TMV), nematodes, fungi, seed, grafting and dodder.'],
  ['In non-persistent (stylet-borne) transmission, the vector:', ['Picks up and passes on the virus within minutes and soon loses it', 'Carries the virus for life', 'Must digest the virus', 'Passes it to its eggs'], 0,
    'Persistent (circulative) viruses pass through the gut to the salivary glands.'],
  ['Virus-free planting material is produced mainly by:', ['Meristem-tip culture', 'Spraying fungicides', 'Seed soaking in water', 'Grafting on infected stock'], 0,
    'Apical meristems are often free of virus.'],
  ['Spike disease of sandalwood is caused by:', ['A phytoplasma', 'A fungus', 'A nematode', 'A bacterium with a wall'], 0,
    'It was long thought to be viral.'],
  ['A plant virus disease that is valued by man is:', ['Tulip breaking virus, which streaks the flowers', 'Late blight', 'Citrus canker', 'Rice blast'], 0,
    'Striped "broken" tulips were prized in 17th-century Holland.'],
  ['Most plant viruses with (+) single-stranded RNA:', ['Are translated directly and replicate in the cytoplasm', 'Integrate into host DNA', 'Replicate in the nucleus with DNA polymerase', 'Need reverse transcriptase'], 0,
    'Movement proteins carry them cell to cell through plasmodesmata.'],
  ['Cross protection against a severe virus strain is done by:', ['Prior infection with a mild strain', 'Spraying antibiotics', 'Heat therapy of seeds only', 'Removing vectors'], 0,
    'Used against citrus tristeza and papaya ring spot.'],
  ['Typical symptoms of virus disease include:', ['Mosaic, vein clearing, leaf curl and stunting', 'Powdery spores', 'Rust pustules', 'Sclerotia'], 0,
    'Viruses do not form spores or fruit bodies.']
] },
{ p: 'B1', t: 'Microbiology', w: 2, pyq: ['IFoS-2021-B1-m20', 'CSE-2009-B1-m22', 'CSE-2006-B1-m19', 'CSE-1999-B1-m17', 'CSE-1991-B1-m26', 'CSE-1990-B1-m46', 'CSE-2021-B1-m24', 'CSE-2019-B1-m20', 'CSE-2011-B1-m15', 'CSE-2006-B1-m15', 'IFoS-2004-B1-m23', 'IFoS-2000-B1-m21', 'CSE-1993-B1-m35', 'IFoS-2007-B1-m20'], q: [
  ['Bioremediation is:', ['The use of living organisms, mainly microbes, to remove or detoxify pollutants', 'Burning of waste', 'Chemical neutralisation only', 'Dumping waste in the sea'], 0,
    'Biodegradation is the natural breakdown; bioremediation is its deliberate use.'],
  ['Adding nutrients to boost native pollutant-degrading microbes is called:', ['Biostimulation', 'Bioaugmentation', 'Bioleaching', 'Biomagnification'], 0,
    'Bioaugmentation adds selected or engineered microbes.'],
  ['The "superbug" *Pseudomonas* engineered to digest oil was developed by:', ['Ananda Chakrabarty', 'Har Gobind Khorana', 'M. S. Swaminathan', 'Norman Borlaug'], 0,
    'It became the first patented living organism (US, 1980).'],
  ['Bioleaching uses microbes such as *Acidithiobacillus ferrooxidans* to:', ['Extract metals like copper and uranium from low-grade ores', 'Fix nitrogen', 'Make biogas', 'Degrade plastics'], 0,
    'Bioremediation cleans; bioleaching recovers metals.'],
  ['In secondary sewage treatment by activated sludge, microbes:', ['Form flocs that oxidise organic matter in aerated tanks', 'Are killed by chlorine', 'Settle grit', 'Make agar'], 0,
    'Primary treatment is physical settling.'],
  ['Anaerobic digestion of sludge produces:', ['Biogas rich in methane', 'Oxygen', 'Ammonia only', 'Chlorine'], 0,
    'Methanogenic archaea finish the process.'],
  ['A high BOD of water shows:', ['Much organic pollution', 'Very clean water', 'High dissolved oxygen', 'High salinity'], 0,
    'BOD is the oxygen microbes need to oxidise organic matter.'],
  ['Faecal contamination of drinking water is checked by testing for:', ['Coliform bacteria such as *E. coli*', 'Diatoms', 'Cyanobacteria', 'Actinomycetes'], 0,
    'Water-borne pathogens include *Vibrio cholerae*, *Salmonella typhi* and *Shigella*.'],
  ['Phytoremediation uses:', ['Plants to take up, store or break down pollutants', 'Only bacteria', 'Chemical oxidants', 'Incinerators'], 0,
    'Hyperaccumulators can store heavy metals in shoots.'],
  ['Vegetation helps to control air pollution mainly by:', ['Trapping dust and absorbing gases on leaf surfaces', 'Releasing sulphur dioxide', 'Raising temperature', 'Producing smoke'], 0,
    'Green belts around industries are planted for this reason.']
] },
{ p: 'B1', t: 'Plant Pathology', w: 3, pyq: ['IFoS-2024-B1-m23', 'CSE-2003-B1-m20', 'CSE-1995-B1-m30', 'CSE-1994-B1-m32', 'CSE-1992-B1-m31', 'CSE-2004-B1-m19', 'IFoS-2002-B1-m21', 'CSE-1996-B1-m30', 'CSE-2022-B1-m20'], q: [
  ['Blast of rice is caused by:', ['*Magnaporthe oryzae* (*Pyricularia oryzae*)', '*Bipolaris oryzae*', '*Rhizoctonia solani*', '*Xanthomonas oryzae*'], 0,
    'Spindle-shaped lesions with grey centres; neck blast causes chaffy panicles.'],
  ['Rice blast is favoured by:', ['High nitrogen, humid weather and cool nights', 'Drought and low nitrogen', 'Saline soil', 'Very high temperature'], 0,
    'Tricyclazole and resistant varieties are main controls.'],
  ['Brown spot of rice, linked to the Bengal famine of 1943, is caused by:', ['*Bipolaris oryzae* (*Helminthosporium oryzae*)', '*Magnaporthe oryzae*', '*Ustilaginoidea virens*', '*Colletotrichum falcatum*'], 0,
    'It is worst on nutrient-poor soils; spots are oval and brown.'],
  ['Bacterial leaf blight of rice is caused by:', ['*Xanthomonas oryzae* pv. *oryzae*', '*Pseudomonas syringae*', '*Ralstonia solanacearum*', '*Erwinia carotovora*'], 0,
    'Leaves yellow from the margin; drops of bacterial ooze appear in the morning.'],
  ['The "kresek" phase of bacterial blight is:', ['Wilting of young seedlings soon after transplanting', 'Grain discolouration', 'Neck rot', 'Root galls'], 0,
    'Infection enters through cut leaf tips at transplanting.'],
  ['The resistance gene *Xa21* in rice protects against:', ['Bacterial leaf blight', 'Blast', 'Sheath blight', 'Tungro'], 0,
    'It codes a receptor kinase that recognises the pathogen.'],
  ['Sheath blight of rice is caused by:', ['*Rhizoctonia solani*', '*Pyricularia oryzae*', '*Sclerospora graminicola*', '*Tilletia indica*'], 0,
    'Oval lesions start near the water line; sclerotia spread the disease. Validamycin and hexaconazole are used.'],
  ['Rice tungro disease is spread by the:', ['Green leafhopper (*Nephotettix*)', 'Whitefly', 'Brown planthopper', 'Stem borer'], 0,
    'Leaves turn yellow-orange and plants are stunted.'],
  ['False smut of rice is caused by:', ['*Ustilaginoidea virens*', '*Ustilago tritici*', '*Tilletia caries*', '*Albugo candida*'], 0,
    'Grains turn into velvety green "smut balls".'],
  ['"Khaira" disease of rice is due to:', ['Zinc deficiency', 'A virus', 'A fungus', 'A nematode'], 0,
    'It is corrected with zinc sulphate.']
] },
{ p: 'B1', t: 'Plant Pathology', w: 3, pyq: ['IFoS-2023-B1-m18', 'CSE-2020-B1-m21', 'IFoS-2019-B1-m23', 'CSE-1998-B1-m23', 'CSE-1997-B1-m17', 'CSE-1996-B1-m29', 'CSE-1993-B1-m24', 'CSE-1990-B1-m42', 'CSE-1998-B1-m22', 'CSE-1997-B1-m18', 'CSE-1991-B1-m32', 'CSE-2025-B1-m23', 'IFoS-2021-B1-m26'], q: [
  ['Late blight of potato is caused by:', ['*Phytophthora infestans*', '*Alternaria solani*', '*Synchytrium endobioticum*', '*Ralstonia solanacearum*'], 0,
    'It caused the Irish famine of 1845–47.'],
  ['Late blight spreads fastest in:', ['Cool, humid, cloudy weather', 'Hot, dry weather', 'Frost', 'Drought'], 0,
    'White downy growth appears on the lower leaf surface; tubers also rot. Mancozeb and metalaxyl are used.'],
  ['Early blight of potato is caused by:', ['*Alternaria solani*', '*Phytophthora infestans*', '*Streptomyces scabies*', '*Fusarium*'], 0,
    'It shows concentric "target-board" spots, starting on older leaves.'],
  ['A key difference: early blight lesions have:', ['Concentric rings, while late blight lesions are water-soaked with white growth below', 'White powder on top', 'Galls on roots', 'Oozing bacteria'], 0,
    'Early blight favours warm weather with dew.'],
  ['Wart disease of potato is caused by:', ['*Synchytrium endobioticum*', '*Phytophthora infestans*', '*Meloidogyne*', '*Rhizoctonia*'], 0,
    'Cauliflower-like warts on tubers; in India it is restricted to the Darjeeling hills by quarantine.'],
  ['Bacterial wilt (brown rot) of potato is caused by:', ['*Ralstonia solanacearum*', '*Xanthomonas citri*', '*Agrobacterium tumefaciens*', '*Erwinia amylovora*'], 0,
    'A cut stem in water releases a milky bacterial stream.'],
  ['Root-knot disease is caused by:', ['*Meloidogyne* nematodes, forming galls on roots', 'Fungi rotting the roots', 'Bacteria', 'Viruses'], 0,
    'Root rots are caused by fungi such as *Rhizoctonia*, *Fusarium* and *Macrophomina*.'],
  ['Citrus canker is caused by:', ['*Xanthomonas citri*', '*Phytophthora citrophthora*', '*Colletotrichum*', '*Alternaria citri*'], 0,
    'Raised corky lesions with a yellow halo; leaf-miner wounds help entry.'],
  ['Citrus canker is managed by:', ['Pruning infected twigs and spraying copper oxychloride with streptocycline', 'Flooding the orchard', 'Applying urea', 'Growing in shade'], 0,
    'Leaf-miner control also helps.'],
  ['Common scab of potato is caused by:', ['*Streptomyces scabies*', '*Alternaria solani*', '*Phytophthora*', '*Pythium*'], 0,
    'It is worse in dry, alkaline soils.']
] },
{ p: 'B1', t: 'Plant Pathology', w: 2, pyq: ['IFoS-2015-B1-m18', 'CSE-1996-B1-m28', 'CSE-1994-B1-m31', 'CSE-1990-B1-m40', 'CSE-2018-B1-m24', 'CSE-2013-B1-m17', 'CSE-2003-B1-m19', 'CSE-1992-B1-m29', 'CSE-2019-B1-m23', 'CSE-2013-B1-m18', 'CSE-1992-B1-m30', 'CSE-1990-B1-m44', 'IFoS-2023-B1-m21'], q: [
  ['Tundu (yellow ear rot) of wheat results from:', ['The bacterium *Rathayibacter tritici* carried by the nematode *Anguina tritici*', 'A rust fungus', 'A virus', 'Zinc deficiency'], 0,
    'Yellow slimy ooze covers the ear.'],
  ['Ear-cockle of wheat is caused by:', ['*Anguina tritici*, a nematode that turns grains into galls', '*Puccinia*', '*Ustilago*', '*Tilletia*'], 0,
    'Galls are removed by floating seed in 20% brine.'],
  ['Green ear disease of bajra is caused by:', ['*Sclerospora graminicola* (downy mildew)', '*Claviceps fusiformis*', '*Puccinia*', '*Tolyposporium*'], 0,
    'Floral parts turn into leafy structures (phyllody).'],
  ['Downy mildew of bajra is controlled mainly by:', ['Metalaxyl seed treatment and resistant hybrids', 'Copper sprays only', 'Flooding', 'Burning stubble'], 0,
    'Oospores in soil start the infection.'],
  ['Ergot of bajra is caused by:', ['*Claviceps fusiformis*', '*Claviceps purpurea*', '*Sclerospora*', '*Ustilago*'], 0,
    'A sticky "honeydew" stage precedes the sclerotia. *C. purpurea* causes ergot of rye.'],
  ['Powdery mildew of wheat is caused by:', ['*Blumeria graminis* f. sp. *tritici*', '*Puccinia striiformis*', '*Tilletia indica*', '*Ustilago tritici*'], 0,
    'White powdery patches on leaves, later with black cleistothecia.'],
  ['Karnal bunt of wheat, important in trade quarantine, is caused by:', ['*Tilletia indica*', '*Ustilago tritici*', '*Puccinia graminis*', '*Alternaria*'], 0,
    'Infected grains smell of fish (trimethylamine).'],
  ['Ergot sclerotia are dangerous in food because they contain:', ['Toxic alkaloids', 'Aflatoxin', 'Vitamins', 'Cyanide'], 0,
    'Ergotism causes gangrene and convulsions.'],
  ['The nematode *Anguina tritici* spreads tundu because it:', ['Carries the bacterium on its body into the developing ear', 'Feeds only on roots', 'Lives on leaves only', 'Kills the bacterium'], 0,
    'Both organisms are needed for the disease.'],
  ['Phyllody of floral parts is a typical symptom of:', ['Downy mildews and phytoplasmas', 'Rusts', 'Smuts', 'Root-knot'], 0,
    'Seen in green ear of bajra and sesame phyllody.']
] },
{ p: 'B1', t: 'Plant Pathology', w: 2, pyq: ['CSE-2023-B1-m24', 'CSE-2017-B1-m17', 'IFoS-2016-B1-m20', 'CSE-2015-B1-m22', 'CSE-2015-B1-m23', 'CSE-2013-B1-m19', 'CSE-1997-B1-m15', 'CSE-1992-B1-m28', 'CSE-1998-B1-m21', 'CSE-1995-B1-m29', 'CSE-1991-B1-m29', 'CSE-2014-B1-m23', 'CSE-1993-B1-m27', 'CSE-1991-B1-m30', 'CSE-1994-B1-m30', 'CSE-1994-B1-m33', 'CSE-1997-B1-m14', 'CSE-1989-B1-m29', 'IFoS-2020-B1-m19', 'CSE-1991-B1-m28', 'IFoS-2001-B1-m21'], q: [
  ['Red rot of sugarcane is caused by:', ['*Colletotrichum falcatum*', '*Ustilago scitaminea*', '*Xanthomonas*', '*Fusarium*'], 0,
    'Called the "cancer of sugarcane".'],
  ['A split cane with red rot shows:', ['Red internal tissue with white transverse patches and an alcoholic smell', 'Black whip-like smut', 'Yellow slime', 'Hollow pith only'], 0,
    'Healthy setts, resistant varieties and moist hot-air treatment of setts control it.'],
  ['White rust of crucifers is caused by:', ['*Albugo candida*', '*Puccinia graminis*', '*Erysiphe*', '*Alternaria brassicae*'], 0,
    'White blister-like pustules; swollen, distorted "staghead" inflorescences.'],
  ['White rust differs from black stem rust because white rust is caused by:', ['An oomycete, not a true rust fungus', 'A basidiomycete rust', 'A bacterium', 'A virus'], 0,
    'Black rust is *Puccinia graminis*, a true rust.'],
  ['Black rot of cabbage shows:', ['V-shaped yellow lesions from the leaf margin with blackened veins', 'White pustules', 'Concentric rings', 'Root galls'], 0,
    'Caused by *Xanthomonas campestris* pv. *campestris*.'],
  ['Crown gall, a plant tumour, is caused by:', ['*Agrobacterium tumefaciens*', '*Rhizobium*', '*Ralstonia*', '*Streptomyces*'], 0,
    'Its Ti plasmid transfers T-DNA into the plant genome.'],
  ['Bud rot of coconut is caused by:', ['*Phytophthora palmivora*', '*Ganoderma*', '*Colletotrichum*', '*Xanthomonas*'], 0,
    'The spindle leaf rots and the crown collapses.'],
  ['Damping-off of seedlings is caused mainly by:', ['*Pythium*', '*Puccinia*', '*Ustilago*', '*Erysiphe*'], 0,
    'Pre-emergence (seed rot) and post-emergence (collapse at soil level) phases.'],
  ['A canker is:', ['A localised sunken dead lesion on stem or fruit', 'A general yellowing', 'A tumour', 'A powdery growth'], 0,
    'Blight is rapid browning and death; galls are overgrowths; mosaic is mottling.'],
  ['Sett treatment with moist hot air against red rot works because it:', ['Kills the pathogen inside the setts without killing buds', 'Adds nutrients', 'Kills insects only', 'Breaks dormancy'], 0,
    'It also controls grassy shoot and ratoon stunting.']
] },
{ p: 'B1', t: 'Plant Pathology', w: 3, pyq: ['CSE-2018-B1-m20', 'IFoS-2014-B1-m28', 'CSE-2012-B1-m22', 'IFoS-2012-B1-m41', 'CSE-2017-B1-m16', 'IFoS-2014-B1-m27', 'IFoS-2013-B1-m32', 'IFoS-2010-B1-m35', 'CSE-1990-B1-m37', 'IFoS-2012-B1-m42', 'CSE-2023-B1-m22', 'CSE-1993-B1-m21', 'CSE-2022-B1-m22', 'CSE-1994-B1-m29', 'IFoS-2022-B1-m18', 'IFoS-2023-B1-m20', 'IFoS-2024-B1-m16'], q: [
  ['Koch\'s postulates require that the suspected pathogen be:', ['Always found with the disease, grown in pure culture, cause the disease on inoculation, and be re-isolated', 'Visible to the naked eye', 'Only a bacterium', 'Absent from the diseased plant'], 0,
    'Obligate parasites and viruses need modified postulates.'],
  ['Plant quarantine aims to:', ['Stop entry and spread of pests and pathogens through plant material', 'Increase crop yield directly', 'Control weeds in fields', 'Test fertilisers'], 0,
    'India: Destructive Insects and Pests Act, 1914; Plant Quarantine Order, 2003.'],
  ['A disease that entered India because of weak quarantine is:', ['Late blight of potato', 'Tikka of groundnut', 'Red rot', 'Khaira'], 0,
    'Bunchy top of banana and potato wart are other introductions.'],
  ['Disease forecasting models use:', ['Weather and pathogen data to predict outbreaks and time sprays', 'Only crop price', 'Soil colour', 'Seed size'], 0,
    'E.g. late blight forecasting with temperature and humidity rules.'],
  ['Soil solarisation is:', ['Covering moist soil with transparent polythene in hot months to kill pathogens, nematodes and weeds', 'Burning crop residue', 'Adding lime', 'Flooding fields'], 0,
    'Soil temperature rises well above lethal levels in the top layer.'],
  ['A systemic fungicide is one that:', ['Is absorbed and moved within the plant', 'Acts only on the surface', 'Kills insects', 'Is a fertiliser'], 0,
    'E.g. carbendazim, metalaxyl, tricyclazole. Mancozeb, copper and sulphur are contact fungicides.'],
  ['An ideal fungicide should be:', ['Toxic to the pathogen but safe for the plant, people and environment, stable and cheap', 'Toxic to the plant', 'Very persistent in soil', 'Expensive'], 0,
    'Low phytotoxicity is essential.'],
  ['An antibiotic used against bacterial plant diseases is:', ['Streptomycin (streptocycline)', 'Penicillin', 'Insulin', 'Aflatoxin'], 0,
    'Validamycin (sheath blight) and kasugamycin (blast) are also used.'],
  ['A microbial biopesticide against caterpillars is:', ['*Bacillus thuringiensis*', '*Rhizobium*', '*Azotobacter*', '*Agrobacterium*'], 0,
    'Its Cry proteins are toxic in the insect gut. *Trichoderma* and *Pseudomonas fluorescens* fight fungi.'],
  ['The disease triangle states that disease needs:', ['A susceptible host, a virulent pathogen and a favourable environment', 'Only a pathogen', 'Only weather', 'Host and soil'], 0,
    'Adding time gives the disease tetrahedron.']
] },
{ p: 'B1', t: 'Microbiology', w: 2, pyq: ['CSE-1990-B1-m36', 'IFoS-2021-B1-m25', 'CSE-2019-B1-m21', 'IFoS-2020-B1-m20', 'CSE-2002-B1-m16', 'CSE-1991-B1-m11'], q: [
  ['Monoclonal antibodies are produced by:', ['Hybridomas made by fusing B cells with myeloma cells', 'Plasmids in bacteria', 'Viruses', 'Yeast mating'], 0,
    'Köhler and Milstein (1975).'],
  ['"Plantibodies" are:', ['Antibodies produced in transgenic plants', 'Plant hormones', 'Plant toxins', 'Antibodies against plants'], 0,
    'Plants are a cheap production system.'],
  ['Endophytes are microbes that:', ['Live inside plant tissues without causing disease', 'Always cause disease', 'Live only on leaf surfaces', 'Live in soil only'], 0,
    'They can help growth, stress tolerance and defence.'],
  ['An endophytic fungus reported to make taxol is:', ['*Taxomyces andreanae*', '*Penicillium roquefortii*', '*Rhizopus*', '*Ustilago*'], 0,
    'It was isolated from the bark of Pacific yew.'],
  ['Aminoglycosides such as streptomycin act by:', ['Binding the 30S ribosome subunit and causing misreading', 'Blocking cell-wall synthesis', 'Dissolving membranes', 'Blocking DNA gyrase'], 0,
    'Penicillin blocks wall synthesis; quinolones block DNA gyrase.'],
  ['Chloramphenicol inhibits:', ['Peptidyl transferase of the 50S subunit', 'Cell-wall cross-linking', 'RNA polymerase', 'Folic acid synthesis'], 0,
    'Rifampicin inhibits RNA polymerase; sulpha drugs block folate.'],
  ['Most antibiotics in use come from:', ['*Streptomyces* (actinomycetes)', 'Algae', 'Viruses', 'Mosses'], 0,
    'Streptomycin was found in *S. griseus* by Waksman.'],
  ['A biosensor consists of:', ['A biological sensing element coupled to a transducer', 'Only a chemical dye', 'A plant growing in soil', 'A filter'], 0,
    'E.g. glucose oxidase electrodes.'],
  ['Interferons are:', ['Antiviral proteins made by infected animal cells', 'Fungal toxins', 'Plant hormones', 'Bacterial plasmids'], 0,
    'They now can be made by recombinant microbes.'],
  ['Endophytic fungi in grasses (e.g. *Epichloë*) mainly benefit the host by:', ['Producing alkaloids that deter herbivores', 'Fixing nitrogen', 'Photosynthesis', 'Pollination'], 0,
    'They are transmitted through seed.']
] }
);
