/* Concept sets for Agriculture I — Weed science. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Weed Science', w: 3, pyq: ['IFoS-2020-A1-m30', 'CSE-2019-A1-m27', 'CSE-2018-A1-m22', 'CSE-2017-A1-m17', 'CSE-2015-A1-m24', 'CSE-2014-A1-m26', 'CSE-2021-A1-m28', 'CSE-2004-A1-m09', 'CSE-2022-A1-m27', 'IFoS-2010-A1-m27', 'IFoS-2001-A1-m08'], q: [
  ['Classical biological weed control means:', ['Introducing natural enemies of an exotic weed from its native range', 'Spraying herbicides', 'Hand weeding', 'Burning'], 0,
    'Prickly pear (*Opuntia*) was controlled in Australia by *Cactoblastis cactorum*.'],
  ['The first successful biological control of a weed in India was of *Opuntia* by:', ['The cochineal insect *Dactylopius*', '*Zygogramma*', '*Neochetina*', 'Grass carp'], 0,
    'It dates to the early 19th century.'],
  ['A bioherbicide (mycoherbicide) approach involves:', ['Mass application of a weed pathogen like a herbicide', 'Releasing insects once', 'Planting smother crops', 'Using grazing animals'], 0,
    'This is the inundative strategy.'],
  ['DeVine and Collego are examples of:', ['Fungal bioherbicides', 'Synthetic herbicides', 'Insect agents', 'Safeners'], 0,
    'DeVine is *Phytophthora palmivora*; Collego is *Colletotrichum gloeosporioides*.'],
  ['Water hyacinth is controlled biologically by:', ['*Neochetina eichhorniae* and *N. bruchi* weevils', '*Zygogramma bicolorata*', '*Cactoblastis*', '*Cyrtobagous*'], 0,
    '*Cyrtobagous salviniae* controls *Salvinia molesta* in Kerala.'],
  ['Grass carp is used for control of:', ['Submerged aquatic weeds', 'Parthenium', 'Lantana', 'Striga'], 0,
    'It is a herbivorous fish.'],
  ['The most important criterion in selecting a bioagent is:', ['High host specificity so crops and native plants are safe', 'Ability to feed on many plants', 'Fast spread to all crops', 'Low reproductive rate'], 0,
    'Damage potential, climatic adaptability and ease of rearing also matter.'],
  ['An advantage of biological weed control is that it is:', ['Self-perpetuating and eco-friendly once established', 'Fast and eradicates weeds completely', 'Effective against all weeds', 'Free of any risk'], 0,
    'It is slow and seldom eradicates weeds.'],
  ['A limitation of biological weed control is that it:', ['Acts slowly and usually suppresses rather than eradicates', 'Pollutes soil heavily', 'Needs expensive sprayers every week', 'Kills crops'], 0,
    'It suits large, uncropped or aquatic areas best.'],
  ['Using a fast-growing crop such as cowpea to suppress weeds is called:', ['Smother cropping (competitive replacement)', 'Classical biocontrol', 'Solarisation', 'Stale seedbed'], 0,
    '*Cassia* species are used against *Parthenium*.']
] },
{ p: 'A1', t: 'Weed Science', w: 3, pyq: ['IFoS-2024-A1-m29', 'CSE-2020-A1-m28', 'IFoS-2020-A1-m32', 'CSE-2017-A1-m18', 'CSE-2016-A1-m23', 'CSE-2013-A1-m25', 'IFoS-2002-A1-m10', 'CSE-1999-A1-m14', 'CSE-1995-A1-m16', 'CSE-1992-A1-m14', 'CSE-2019-A1-m28', 'CSE-2025-A1-m26', 'IFoS-2006-A1-m14', 'IFoS-2005-A1-m23', 'CSE-2001-A1-m09', 'IFoS-2003-A1-m01', 'IFoS-2009-A1-m05', 'CSE-2001-A1-m03'], q: [
  ['The critical period of crop–weed competition is:', ['The period during which weeds must be kept down to avoid yield loss', 'The whole crop life', 'The time after harvest', 'The germination day only'], 0,
    'It usually spans the first third to quarter of the crop\'s life.'],
  ['Weeds compete with crops most strongly for:', ['Nitrogen, water, light and space', 'Carbon dioxide only', 'Oxygen only', 'Phosphorus only'], 0,
    'Nitrogen is usually the most contested nutrient.'],
  ['Factors affecting crop–weed competition include:', ['Weed density, weed species, duration of competition and crop spacing', 'Market price', 'Farmer\'s caste', 'Seed colour'], 0,
    'Fertility and moisture also change the outcome.'],
  ['Weed index is calculated as:', ['(Yield of weed-free plot − yield of treated plot) ÷ yield of weed-free plot × 100', 'Weed weight × crop yield', 'Weed count ÷ area', 'Herbicide dose ÷ yield'], 0,
    'It expresses yield loss due to weeds.'],
  ['If a weed-free plot yields 5 t/ha and a treated plot 4 t/ha, the weed index is:', ['20%', '25%', '80%', '1%'], 0,
    '(5 − 4) ÷ 5 × 100 = 20%.'],
  ['Weed control efficiency (WCE) compares:', ['Weed dry matter in the control and treated plots', 'Crop yields only', 'Herbicide costs', 'Seed rates'], 0,
    'WCE = (WDC − WDT) ÷ WDC × 100.'],
  ['If weed dry matter is 200 g/m² in the weedy check and 50 g/m² in a treatment, WCE is:', ['75%', '25%', '50%', '150%'], 0,
    '(200 − 50) ÷ 200 × 100 = 75%.'],
  ['Allelopathy by weeds means:', ['Release of chemicals that inhibit crop germination or growth', 'Competition for light only', 'Parasitism', 'Nitrogen fixation'], 0,
    '*Parthenium* (parthenin) and *Cyperus rotundus* are allelopathic.'],
  ['Weeds cause losses by:', ['Reducing yield and quality, harbouring pests and raising costs', 'Only improving soil', 'Fixing nitrogen for crops', 'Increasing prices'], 0,
    '*Parthenium* also causes dermatitis and allergies.'],
  ['An "obnoxious" weed is one that is:', ['Very harmful and hard to control, such as *Cyperus rotundus*', 'A crop plant growing as a volunteer', 'Easily pulled out', 'Beneficial'], 0,
    'Relative weeds are volunteer crop plants out of place.']
] },
{ p: 'A1', t: 'Weed Science', w: 3, pyq: ['CSE-2020-A1-m27', 'IFoS-2005-A1-m26', 'CSE-2004-A1-m10', 'IFoS-2003-A1-m22', 'CSE-2000-A1-m13', 'CSE-1996-A1-m14', 'CSE-1989-A1-m16', 'CSE-2021-A1-m27', 'IFoS-2020-A1-m31', 'IFoS-2012-A1-m30', 'IFoS-2002-A1-m11', 'IFoS-2000-A1-m08', 'CSE-2025-A1-m28', 'IFoS-2004-A1-m14', 'CSE-1991-A1-m13', 'IFoS-2006-A1-m15', 'IFoS-2005-A1-m25', 'CSE-1990-A1-m14', 'IFoS-2022-A1-m28', 'CSE-2000-A1-m14', 'CSE-2013-A1-m28', 'IFoS-2011-A1-m26', 'CSE-2016-A1-m24', 'CSE-2015-A1-m23', 'CSE-2018-A1-m23', 'CSE-2013-A1-m27', 'CSE-2015-A1-m25'], q: [
  ['A pre-emergence herbicide is applied:', ['After sowing but before weeds (and crop) emerge', 'Before sowing, incorporated into soil', 'After weeds emerge', 'At harvest'], 0,
    'E.g. pendimethalin, atrazine. Fluchloralin is pre-plant incorporated; 2,4-D and glyphosate are post-emergence.'],
  ['A non-selective herbicide is:', ['Glyphosate', '2,4-D', 'Atrazine in maize', 'Isoproturon in wheat'], 0,
    'Paraquat is another non-selective herbicide.'],
  ['Atrazine is selective in maize because maize:', ['Rapidly detoxifies it through glutathione conjugation and benzoxazinones', 'Does not absorb it', 'Lacks chloroplasts', 'Grows faster'], 0,
    'Differential metabolism is the main basis of physiological selectivity.'],
  ['Glyphosate kills plants by inhibiting:', ['EPSP synthase of the shikimate pathway', 'Photosystem II', 'Acetolactate synthase', 'Microtubule assembly'], 0,
    'Herbicide-tolerant crops carry an insensitive EPSPS.'],
  ['Sulfonylurea herbicides inhibit:', ['Acetolactate synthase (ALS)', 'EPSPS', 'Photosystem I', 'ACCase'], 0,
    'They are active at very low doses.'],
  ['2,4-D acts as a:', ['Synthetic auxin, killing broad-leaved weeds in cereals', 'PSII inhibitor', 'ALS inhibitor', 'Contact desiccant'], 0,
    'Grasses are tolerant.'],
  ['Herbicide persistence in soil is reduced mainly by:', ['Microbial degradation, photodecomposition and volatilisation', 'Adding more herbicide', 'Low temperature and drought', 'Strong adsorption'], 0,
    'Persistent residues (e.g. atrazine, some sulfonylureas) can harm the next crop.'],
  ['A herbicide safener:', ['Protects the crop from herbicide injury without protecting weeds', 'Increases herbicide toxicity to crops', 'Is a surfactant only', 'Is a fertiliser'], 0,
    'E.g. fenclorim with pretilachlor in rice.'],
  ['Herbicide efficacy is lowered by:', ['Rain soon after spraying or spraying weeds at a late growth stage', 'Spraying young actively growing weeds', 'Correct dose and coverage', 'Adding an adjuvant'], 0,
    'Soil moisture, nozzle and spray volume also matter.'],
  ['Pendimethalin kills weeds by:', ['Inhibiting microtubule assembly and cell division', 'Blocking EPSPS', 'Inhibiting ALS', 'Acting as auxin'], 0,
    'It is a dinitroaniline pre-emergence herbicide.']
] }
);
