/* Concept sets for Botany II — Genetics, cytogenetics and biostatistics. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B2', t: 'Genetics', w: 3, pyq: ['IFoS-2022-B2-m17', 'IFoS-2020-B2-m18', 'CSE-2019-B2-m17', 'CSE-2016-B2-m20', 'IFoS-2016-B2-m13', 'IFoS-2010-B2-m13', 'CSE-2006-B2-m12', 'IFoS-2004-B2-m14', 'CSE-2003-B2-m10', 'IFoS-2000-B2-m14', 'IFoS-2013-B2-m11', 'CSE-1990-B2-m11', 'CSE-1996-B2-m08', 'CSE-2021-B2-m04', 'IFoS-2023-B2-m05', 'CSE-1993-B2-m14', 'CSE-2001-B2-m16'], q: [
  ['Plastid inheritance was first shown by Correns (1909) in:', ['Variegated *Mirabilis jalapa* (four o\'clock plant)', 'Pea', '*Drosophila*', 'Maize'], 0,
    'Seeds took the leaf type of the branch carrying the female flower.'],
  ['A hallmark of cytoplasmic inheritance is that:', ['Reciprocal crosses give different results', 'Reciprocal crosses give the same result', 'F₂ shows 3:1', 'Traits show linkage to nuclear genes'], 0,
    'Inheritance is usually maternal and non-Mendelian.'],
  ['Repeated backcrossing that replaces the nucleus but keeps a trait shows the trait is:', ['Cytoplasmic', 'Sex-linked', 'Polygenic', 'Epistatic'], 0,
    'This is the nuclear substitution test.'],
  ['Petite mutants of yeast (Ephrussi) result from defects in:', ['Mitochondrial DNA', 'Plastid DNA', 'Nuclear ribosomes', 'Cell wall genes'], 0,
    '"Poky" in *Neurospora* is another mitochondrial trait.'],
  ['The 1970 southern corn leaf blight epidemic in the USA was linked to:', ['Widespread use of Texas (T) male-sterile cytoplasm', 'A nuclear resistance gene', 'Drought', 'An insect'], 0,
    'T-cytoplasm made maize susceptible to *Bipolaris maydis* race T.'],
  ['Shell coiling in the snail *Limnaea* is an example of:', ['Maternal effect, set by the mother\'s nuclear genotype', 'Plastid inheritance', 'Mitochondrial inheritance', 'Sex linkage'], 0,
    'Maternal effect is nuclear, unlike true cytoplasmic inheritance.'],
  ['Kappa particles of *Paramecium* that kill sensitive strains are:', ['Endosymbiotic bacteria in the cytoplasm', 'Nuclear genes', 'Viruses in the nucleus', 'Mitochondria'], 0,
    'Their maintenance needs a nuclear gene K.'],
  ['Genes carried in plastids are called:', ['Plastogenes', 'Holandric genes', 'Polygenes', 'Oncogenes'], 0,
    'Holandric genes are Y-linked, passed from father to son.'],
  ['In *Chlamydomonas*, Sager showed that streptomycin resistance is inherited:', ['Uniparentally, from the mt⁺ parent', 'Equally from both parents', 'From the mt⁻ parent only', 'In a 3:1 ratio'], 0,
    'This is chloroplast inheritance in an isogamous alga.'],
  ['Cytoplasmic male sterility is coded by:', ['Mitochondrial genes', 'Chloroplast genes', 'Nuclear restorer genes', 'Ribosomal RNA'], 0,
    'Nuclear restorer (Rf) genes can suppress it.']
] },
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 3, pyq: ['IFoS-2024-B2-m14', 'IFoS-2022-B2-m20', 'CSE-2016-B2-m21', 'IFoS-2013-B2-m10', 'IFoS-2007-B2-m18', 'IFoS-2004-B2-m16', 'CSE-2000-B2-m09', 'CSE-1999-B2-m07', 'CSE-2005-B2-m05', 'IFoS-2000-B2-m15', 'IFoS-2001-B2-m12', 'IFoS-2010-B2-m17', 'CSE-2010-B2-m08', 'CSE-1995-B2-m19', 'CSE-1993-B2-m16', 'IFoS-2009-B2-m14'], q: [
  ['The term heterosis was coined by:', ['G. H. Shull (1914)', 'Mendel', 'Darwin', 'Borlaug'], 0,
    'It means superiority of the F₁ hybrid over its parents.'],
  ['Heterobeltiosis is superiority of an F₁ over:', ['The better parent', 'The mid-parent value', 'A standard check variety', 'The F₂'], 0,
    'Standard heterosis compares with the best commercial check.'],
  ['The dominance hypothesis explains heterosis as:', ['Masking of harmful recessive alleles of one parent by dominant alleles of the other', 'Superiority of heterozygotes at single loci', 'Cytoplasmic effects', 'Mutation in F₁'], 0,
    'Davenport and Bruce; the overdominance hypothesis (East, Shull) credits heterozygosity itself.'],
  ['Inbreeding depression is caused mainly by:', ['Increased homozygosity exposing deleterious recessive alleles', 'More heterozygosity', 'Polyploidy', 'Cytoplasmic genes'], 0,
    'It is severe in cross-pollinated crops such as maize and alfalfa.'],
  ['Inbreeding depression is slight in:', ['Self-pollinated crops such as rice and wheat', 'Maize', 'Alfalfa', 'Onion'], 0,
    'Natural selfing has already purged harmful recessives.'],
  ['In a diploid, heterosis in the F₂ generation is expected to:', ['Fall to about half of the F₁ level', 'Stay the same', 'Double', 'Disappear completely'], 0,
    'That is why farmers must buy fresh hybrid seed each season.'],
  ['India\'s first sorghum hybrid, CSH-1 (1964), was produced using:', ['Cytoplasmic–genetic male sterility', 'Hand emasculation only', 'Self-incompatibility', 'Apomixis'], 0,
    'Hybrid bajra HB-1 followed in 1965.'],
  ['Hybrid rice technology was pioneered by:', ['Yuan Longping in China', 'M. S. Swaminathan', 'Norman Borlaug', 'G. S. Khush'], 0,
    'It uses CMS (three-line) or environment-sensitive (two-line) systems.'],
  ['The best way to restore vigour lost by inbreeding is:', ['Crossing unrelated inbred lines', 'More selfing', 'Mutation breeding', 'Clonal propagation'], 0,
    'Heterosis acts as the "antidote" to inbreeding depression.'],
  ['Mid-parent heterosis is calculated as:', ['(F₁ − mid-parent value) ÷ mid-parent value × 100', 'F₁ − F₂', 'Better parent ÷ F₁', 'F₁ × F₂'], 0,
    'The mid-parent value is the average of the two parents.']
] },
{ p: 'B2', t: 'Genetics', w: 3, pyq: ['CSE-2023-B2-m18', 'CSE-2022-B2-m17', 'CSE-2018-B2-m13', 'IFoS-2007-B2-m16', 'CSE-1994-B2-m16', 'IFoS-2023-B2-m20', 'CSE-2022-B2-m20', 'CSE-2014-B2-m11', 'CSE-2024-B2-m11', 'CSE-2023-B2-m16', 'IFoS-2004-B2-m11', 'CSE-1997-B2-m09', 'CSE-1994-B2-m13', 'CSE-2000-B2-m11', 'CSE-1988-B2-m14', 'CSE-2019-B2-m20', 'IFoS-2014-B2-m17', 'IFoS-2003-B2-m18', 'CSE-2013-B2-m13', 'IFoS-2005-B2-m12', 'CSE-2019-B2-m19', 'CSE-2018-B2-m12', 'CSE-1990-B2-m14', 'CSE-2014-B2-m22', 'CSE-1993-B2-m17', 'CSE-1992-B2-m03', 'IFoS-2024-B2-m05', 'IFoS-2003-B2-m06', 'CSE-1995-B2-m15'], q: [
  ['Mendel was fortunate in choosing pea because it:', ['Has clear contrasting traits, self-pollinates and can be crossed easily', 'Is cross-pollinated by wind', 'Has a long life cycle', 'Has many linked traits'], 0,
    'Most of his seven traits assorted independently.'],
  ['Incomplete dominance in *Mirabilis* flower colour gives an F₂ ratio of:', ['1 red : 2 pink : 1 white', '3 red : 1 white', '9 : 3 : 3 : 1', '1 : 1'], 0,
    'Phenotype and genotype ratios coincide.'],
  ['Codominance differs from incomplete dominance in that:', ['Both alleles are fully expressed in the heterozygote', 'A blended intermediate appears', 'One allele is hidden', 'No phenotype appears'], 0,
    'E.g. ABO and MN blood groups.'],
  ['A 9:7 ratio in sweet pea flower colour (Bateson and Punnett) shows:', ['Complementary gene action', 'Dominant epistasis', 'Recessive epistasis', 'Duplicate genes'], 0,
    'Both dominant genes are needed for colour.'],
  ['A 12:3:1 ratio, as in summer squash fruit colour, indicates:', ['Dominant epistasis', 'Recessive epistasis', 'Complementary genes', 'Inhibitory genes'], 0,
    '9:3:4 is recessive epistasis; 15:1 duplicate dominant genes; 13:3 inhibitory genes.'],
  ['A 15:1 ratio for capsule shape in shepherd\'s purse indicates:', ['Duplicate dominant genes', 'Complementary genes', 'Dominant epistasis', 'Lethal genes'], 0,
    'Either dominant gene gives the triangular capsule.'],
  ['Multiple alleles are:', ['More than two alternative forms of a gene at one locus in a population', 'Genes at many loci for one trait', 'Linked genes', 'Genes on different chromosomes'], 0,
    'S alleles of self-incompatibility are a plant example.'],
  ['Nilsson-Ehle\'s work on wheat kernel colour showed:', ['Several genes with additive effects produce continuous variation', 'One gene with complete dominance', 'Cytoplasmic inheritance', 'Sex linkage'], 0,
    'This is polygenic (quantitative) inheritance — the multiple factor hypothesis.'],
  ['Pleiotropy is:', ['One gene affecting several unrelated traits', 'Many genes affecting one trait', 'Gene interaction between loci', 'Linkage of genes'], 0,
    'Sickle-cell anaemia is a classic example.'],
  ['The one gene–one enzyme hypothesis came from Beadle and Tatum\'s work on:', ['*Neurospora*', '*Drosophila*', 'Pea', 'Maize'], 0,
    'Each nutritional mutant blocked one enzymatic step.']
] },
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 2, pyq: ['CSE-2023-B2-m14', 'IFoS-2020-B2-m15', 'CSE-2006-B2-m11', 'IFoS-2001-B2-m12', 'IFoS-2024-B2-m18', 'CSE-2021-B2-m16', 'IFoS-2019-B2-m15', 'IFoS-2024-B2-m16', 'IFoS-2000-B2-m17', 'CSE-2009-B2-m07', 'IFoS-2022-B2-m14', 'IFoS-2022-B2-m08', 'IFoS-2020-B2-m06', 'IFoS-2016-B2-m07', 'IFoS-2015-B2-m04', 'IFoS-2011-B2-m03', 'IFoS-2006-B2-m06', 'IFoS-2002-B2-m05', 'IFoS-2021-B2-m10', 'IFoS-2007-B2-m04', 'IFoS-2012-B2-m19', 'IFoS-2019-B2-m05'], q: [
  ['The correlation coefficient (r) ranges from:', ['−1 to +1', '0 to 1', '0 to 100', '−∞ to +∞'], 0,
    'r = 0 means no linear relationship.'],
  ['Pearson\'s correlation coefficient is:', ['Covariance of x and y divided by the product of their standard deviations', 'Mean of x divided by mean of y', 'Variance of x', 'Sum of x and y'], 0,
    'It measures the strength of a linear association.'],
  ['Regression analysis is used to:', ['Predict a dependent variable from an independent one', 'Measure only association without direction', 'Test ratios', 'Find the mode'], 0,
    'The regression coefficient b is the change in y per unit x.'],
  ['The coefficient of determination (r²) tells:', ['The fraction of variation in y explained by x', 'The mean of y', 'The standard error', 'The number of samples'], 0,
    'r² = 0.81 means 81% of variation is explained.'],
  ['The coefficient of variation (CV) is:', ['Standard deviation ÷ mean × 100', 'Mean ÷ standard deviation', 'Variance × mean', 'Range ÷ 2'], 0,
    'Being unit-free, it compares variability of different traits.'],
  ['If a trait has mean 50 and standard deviation 5, its CV is:', ['10%', '5%', '25%', '50%'], 0,
    '5 ÷ 50 × 100 = 10%.'],
  ['The standard error of a mean is:', ['Standard deviation ÷ √n', 'Standard deviation × n', 'Variance ÷ n²', 'Mean ÷ n'], 0,
    'It shrinks as sample size grows.'],
  ['In a normal distribution, about 95% of values lie within:', ['±2 standard deviations of the mean', '±1 standard deviation', '±0.5 standard deviation', '±3 standard errors'], 0,
    'About 68% lie within ±1 SD; mean, median and mode coincide.'],
  ['A Poisson distribution differs from a binomial distribution in that it:', ['Describes rare events, with mean equal to variance', 'Has a fixed small number of trials', 'Is always symmetrical', 'Has no mean'], 0,
    'Binomial needs n trials with probability p each.'],
  ['Standard deviation is:', ['The square root of the variance', 'The square of the variance', 'The mean of deviations', 'The range'], 0,
    'It is expressed in the same units as the data.']
] },
{ p: 'B2', t: 'Genetics', w: 2, pyq: ['IFoS-2020-B2-m16', 'CSE-2017-B2-m12', 'CSE-1992-B2-m08', 'CSE-1986-B2-m15', 'CSE-2025-B2-m14', 'CSE-1992-B2-m12', 'IFoS-2024-B2-m13', 'CSE-1995-B2-m14', 'CSE-2001-B2-m13', 'CSE-1985-B2-m07', 'IFoS-2011-B2-m05', 'CSE-1989-B2-m12', 'CSE-1999-B2-m08', 'CSE-1990-B2-m10', 'CSE-1991-B2-m12', 'CSE-1988-B2-m12', 'IFoS-2012-B2-m04', 'IFoS-2004-B2-m02', 'IFoS-2010-B2-m04', 'IFoS-2001-B2-m03', 'CSE-2014-B2-m02', 'IFoS-2014-B2-m14', 'CSE-2011-B2-m13', 'IFoS-2015-B2-m15'], q: [
  ['A widely used chemical mutagen in plant breeding is:', ['Ethyl methane sulphonate (EMS)', 'Colchicine', 'Gibberellin', 'Auxin'], 0,
    'Physical mutagens include X-rays, gamma rays and neutrons; colchicine doubles chromosomes.'],
  ['Induced mutation was first shown with X-rays by:', ['H. J. Muller (1927) in *Drosophila*', 'Mendel', 'de Vries', 'Morgan'], 0,
    'Stadler showed it in barley and maize in 1928.'],
  ['Sharbati Sonora, an amber-grained wheat, was developed at IARI by:', ['Mutation (irradiation) of Sonora 64', 'Hybridisation with rye', 'Tissue culture', 'Genetic engineering'], 0,
    'An early Indian example of mutation breeding.'],
  ['Seedless watermelon is produced by making:', ['Triploids from tetraploid × diploid crosses', 'Haploids', 'Tetraploids only', 'Aneuploids'], 0,
    'Triploids are sterile; banana is another natural triploid.'],
  ['Bread wheat (AABBDD) is an example of:', ['Allopolyploidy', 'Autopolyploidy', 'Aneuploidy', 'Haploidy'], 0,
    'Cotton (AADD) and *Brassica napus* (AACC) are also allopolyploids.'],
  ['*Raphanobrassica*, made by Karpechenko, is a synthetic:', ['Allotetraploid of radish and cabbage', 'Autotetraploid of radish', 'Triploid of cabbage', 'Haploid hybrid'], 0,
    'It was fertile but combined the wrong ends — cabbage root and radish leaves.'],
  ['According to Ohno, gene duplication aids evolution because:', ['Extra copies are free to mutate and gain new functions', 'Duplicates are always lost', 'It stops mutation', 'It reduces genome size'], 0,
    'This is the basis of multigene families.'],
  ['Gene amplification is:', ['A selective increase in copies of a particular gene', 'Loss of a gene', 'Inversion of a segment', 'Gene silencing'], 0,
    'E.g. rRNA genes in amphibian oocytes; EPSPS copies in glyphosate-resistant weeds.'],
  ['Mutations matter in evolution because they:', ['Supply the raw genetic variation on which selection acts', 'Always improve fitness', 'Are always dominant', 'Prevent recombination'], 0,
    'Most new mutations are neutral or harmful.'],
  ['Mutation breeding is especially useful for:', ['Improving one or two traits in an otherwise good variety', 'Combining whole genomes', 'Producing hybrids', 'Cloning plants'], 0,
    'It is valuable in vegetatively propagated crops too.']
] }
);
