/* Concept sets for Botany II — Plant physiology and biochemistry. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 3, pyq: ['IFoS-2004-B2-m17', 'CSE-1999-B2-m16', 'CSE-1990-B2-m15', 'CSE-2012-B2-m32', 'CSE-1991-B2-m19', 'CSE-2023-B2-m23', 'CSE-1993-B2-m20', 'IFoS-2020-B2-m22', 'CSE-2010-B2-m23', 'IFoS-2024-B2-m25', 'CSE-2000-B2-m15', 'CSE-2013-B2-m28', 'IFoS-2000-B2-m05', 'IFoS-2013-B2-m06', 'IFoS-2019-B2-m08', 'CSE-1988-B2-m11'], q: [
  ['Evidence for two photosystems came from:', ['The red drop and the Emerson enhancement effect', 'The Hill reaction only', 'Calvin\'s ¹⁴C experiments', 'Warburg effect'], 0,
    'Far-red light alone was inefficient but boosted by shorter red light.'],
  ['The reaction-centre chlorophylls of PSII and PSI are:', ['P680 and P700', 'P700 and P680', 'P870 and P680', 'P430 and P700'], 0,
    'P870 is the purple-bacterial reaction centre.'],
  ['In the Z-scheme, electrons pass from PSII to PSI through:', ['Plastoquinone, cytochrome b₆f and plastocyanin', 'Ferredoxin and NADP⁺', 'Cytochrome c and oxygen', 'Ubiquinone and cytochrome c oxidase'], 0,
    'From PSI they go via ferredoxin and FNR to NADP⁺.'],
  ['Oxygen released in photosynthesis comes from water, as shown by:', ['Ruben and Kamen using ¹⁸O', 'Calvin using ¹⁴C', 'Hatch and Slack', 'Blackman'], 0,
    'Hill (1937) showed isolated chloroplasts evolve O₂ with an artificial electron acceptor.'],
  ['Water is split by the oxygen-evolving complex, which contains:', ['A Mn₄CaO₅ cluster cycling through S-states (Kok cycle)', 'Iron–sulphur clusters', 'Copper atoms', 'Magnesium only'], 0,
    'Four photons (four oxidations) release one O₂.'],
  ['Cyclic photophosphorylation differs from non-cyclic in that it:', ['Involves only PSI and makes ATP without NADPH or O₂', 'Makes NADPH and O₂', 'Involves only PSII', 'Needs no light'], 0,
    'It balances the ATP:NADPH ratio needed by the Calvin cycle.'],
  ['Antenna (light-harvesting) pigments pass energy to the reaction centre by:', ['Resonance (Förster) energy transfer', 'Electron transfer', 'Proton pumping', 'Heat'], 0,
    'Only the reaction centre performs charge separation.'],
  ['The herbicide DCMU (diuron) blocks photosynthesis by:', ['Binding the Q_B site of PSII and stopping electron flow to plastoquinone', 'Accepting electrons from PSI', 'Inhibiting RuBisCO', 'Uncoupling ATP synthase'], 0,
    'Paraquat (methyl viologen) diverts electrons from PSI to make toxic oxygen radicals.'],
  ['Photosynthesis in purple and green sulphur bacteria is:', ['Anoxygenic, using donors such as H₂S and a single photosystem', 'Oxygenic with two photosystems', 'Based on chlorophyll b', 'Independent of light'], 0,
    'They use bacteriochlorophylls.'],
  ['The minimum quantum requirement for releasing one O₂ is about:', ['8 photons', '2 photons', '1 photon', '100 photons'], 0,
    'Each of the four electrons needs two photons, one at each photosystem.']
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 3, pyq: ['CSE-2021-B2-m24', 'CSE-2019-B2-m24', 'CSE-1998-B2-m15', 'CSE-1993-B2-m19', 'CSE-2018-B2-m25', 'CSE-2015-B2-m23', 'CSE-2014-B2-m26', 'CSE-2009-B2-m11', 'CSE-2025-B2-m19', 'CSE-2013-B2-m22', 'CSE-1990-B2-m18', 'CSE-2006-B2-m16', 'CSE-1988-B2-m23', 'CSE-1997-B2-m12', 'CSE-1986-B2-m22', 'CSE-2002-B2-m16', 'IFoS-2009-B2-m19', 'CSE-2012-B2-m29', 'IFoS-2010-B2-m24', 'CSE-2025-B2-m21', 'CSE-1991-B2-m04', 'IFoS-2012-B2-m12', 'IFoS-2005-B2-m05', 'IFoS-2016-B2-m10', 'IFoS-2015-B2-m07', 'IFoS-2023-B2-m12', 'IFoS-2007-B2-m12', 'IFoS-2009-B2-m01'], q: [
  ['In C₄ plants, CO₂ is first fixed in mesophyll cells by:', ['PEP carboxylase, giving oxaloacetate', 'RuBisCO, giving 3-PGA', 'Carbonic anhydrase alone', 'PEP carboxykinase, giving pyruvate'], 0,
    'The first stable product is a 4-carbon acid (Hatch and Slack).'],
  ['In the bundle sheath of C₄ plants, C₄ acids are:', ['Decarboxylated to release CO₂ for RuBisCO', 'Stored as starch', 'Exported to roots', 'Converted to fats'], 0,
    'Pyruvate returns to the mesophyll, where PPDK regenerates PEP using ATP.'],
  ['Maize and sugarcane belong to the C₄ subtype that uses:', ['NADP-malic enzyme', 'NAD-malic enzyme', 'PEP carboxykinase', 'RuBisCO only'], 0,
    'NAD-ME types include *Amaranthus*; PEP-CK types include guinea grass.'],
  ['C₄ plants are more efficient in hot, bright conditions mainly because:', ['Concentrating CO₂ around RuBisCO suppresses photorespiration', 'They need less light', 'They lack chlorophyll b', 'They do not use RuBisCO'], 0,
    'They also have high water-use efficiency.'],
  ['The CO₂ compensation point of C₄ plants is:', ['Very low (about 0–10 ppm)', 'About 50–100 ppm, like C₃', 'Higher than C₃', 'Zero in the dark'], 0,
    'Low values reflect almost no photorespiratory CO₂ loss.'],
  ['C₄ fixation costs more energy than C₃, about:', ['5 ATP + 2 NADPH per CO₂, against 3 ATP + 2 NADPH', 'Less ATP than C₃', 'No ATP', '10 NADPH per CO₂'], 0,
    'The extra ATP regenerates PEP.'],
  ['In CAM plants, stomata are:', ['Open at night, when CO₂ is fixed into malate stored in the vacuole', 'Open only at midday', 'Always closed', 'Absent'], 0,
    'By day malate is decarboxylated behind closed stomata.'],
  ['C₄ and CAM pathways differ in that:', ['C₄ separates the two carboxylations in space, CAM in time', 'C₄ separates in time, CAM in space', 'Both lack PEP carboxylase', 'CAM uses only RuBisCO'], 0,
    'Both concentrate CO₂ for RuBisCO.'],
  ['CAM was first described in the family:', ['Crassulaceae', 'Poaceae', 'Fabaceae', 'Brassicaceae'], 0,
    'Pineapple, *Opuntia*, *Agave* and *Kalanchoe* are CAM plants.'],
  ['The first stable product of CO₂ fixation in C₃ plants is:', ['3-phosphoglycerate', 'Oxaloacetate', 'Malate', 'Pyruvate'], 0,
    'RuBisCO adds CO₂ to ribulose-1,5-bisphosphate.']
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 2, pyq: ['CSE-2024-B2-m24', 'CSE-2017-B2-m21', 'IFoS-2010-B2-m27', 'IFoS-2005-B2-m20', 'CSE-2020-B2-m25', 'CSE-1988-B2-m23', 'CSE-1989-B2-m18'], q: [
  ['Photorespiration begins when RuBisCO:', ['Adds O₂ to RuBP, forming 3-PGA and 2-phosphoglycolate', 'Adds CO₂ to PEP', 'Splits water', 'Makes ATP'], 0,
    'Carboxylation and oxygenation compete for the same active site.'],
  ['The photorespiratory (C₂) cycle runs through:', ['Chloroplast, peroxisome and mitochondrion', 'Chloroplast only', 'Nucleus and cytosol', 'Vacuole and Golgi'], 0,
    'This compartmentation is a classic exam point.'],
  ['In peroxisomes during photorespiration, glycolate is converted to:', ['Glyoxylate and then glycine', 'Serine directly', 'Sucrose', 'Malate'], 0,
    'H₂O₂ formed is destroyed by catalase.'],
  ['In mitochondria, two glycine molecules give:', ['Serine, CO₂ and NH₃', 'Glucose', 'Malate and ATP', 'Glutamate'], 0,
    'This is where photorespiratory CO₂ is released.'],
  ['Photorespiration increases at high temperature because:', ['O₂ solubility relative to CO₂ rises and RuBisCO favours oxygenation', 'Light falls', 'CO₂ rises', 'Stomata open wider'], 0,
    'It can waste about a quarter of fixed carbon in C₃ crops.'],
  ['Ammonia released in photorespiration is re-assimilated by:', ['Glutamine synthetase and GOGAT in the chloroplast', 'Nitrate reductase', 'Nitrogenase', 'Urease'], 0,
    'Otherwise nitrogen would be lost.'],
  ['A possible benefit of photorespiration is that it:', ['Dissipates excess light energy and protects the photosynthetic machinery', 'Fixes nitrogen', 'Makes starch', 'Produces more ATP'], 0,
    'It also supplies glycine and serine.'],
  ['The Warburg effect refers to:', ['Inhibition of photosynthesis by oxygen', 'Stimulation by blue light', 'Respiration in the dark', 'Fluorescence of chlorophyll'], 0,
    'It reflects RuBisCO oxygenase activity.'],
  ['C₄ plants show little apparent photorespiration because:', ['High CO₂ in the bundle sheath suppresses RuBisCO oxygenase', 'They lack RuBisCO', 'They have no peroxisomes', 'They photosynthesise only at night'], 0,
    'Any CO₂ released is re-fixed by PEP carboxylase.'],
  ['Photorespiration consumes:', ['Oxygen and releases CO₂ in light', 'CO₂ and releases O₂', 'Only ATP', 'Only water'], 0,
    'Unlike dark respiration, it yields no ATP.']
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 3, pyq: ['IFoS-2020-B2-m23', 'CSE-2017-B2-m23', 'IFoS-2015-B2-m22', 'CSE-2019-B2-m26', 'IFoS-2014-B2-m23', 'CSE-2004-B2-m08', 'IFoS-2003-B2-m22', 'CSE-1999-B2-m17', 'IFoS-2006-B2-m17', 'CSE-1993-B2-m18', 'IFoS-2022-B2-m27', 'CSE-1999-B2-m18', 'CSE-2020-B2-m24', 'IFoS-2014-B2-m21', 'CSE-1987-B2-m20', 'IFoS-2006-B2-m08', 'IFoS-2000-B2-m08', 'IFoS-2003-B2-m20', 'CSE-2012-B2-m16'], q: [
  ['Glycolysis takes place in the:', ['Cytosol, giving 2 pyruvate, 2 ATP (net) and 2 NADH per glucose', 'Mitochondrial matrix', 'Thylakoid lumen', 'Nucleus'], 0,
    'Plastids also have glycolytic enzymes.'],
  ['The key regulatory enzyme of glycolysis is:', ['Phosphofructokinase', 'Hexokinase only', 'Aldolase', 'Enolase'], 0,
    'Plants also use a pyrophosphate-dependent PFP.'],
  ['Alcoholic fermentation in yeast or flooded roots converts pyruvate to:', ['Ethanol and CO₂ via pyruvate decarboxylase and alcohol dehydrogenase', 'Lactate only', 'Acetyl-CoA', 'Citrate'], 0,
    'It regenerates NAD⁺ so glycolysis can continue.'],
  ['The Krebs cycle is called amphibolic because:', ['It both oxidises fuels and supplies intermediates for biosynthesis', 'It works only in light', 'It is purely anabolic', 'It occurs in two organelles'], 0,
    'α-ketoglutarate gives glutamate, oxaloacetate gives aspartate; anaplerotic reactions refill it.'],
  ['One turn of the Krebs cycle yields:', ['3 NADH, 1 FADH₂, 1 ATP (or GTP) and 2 CO₂', '2 NADH and 2 ATP', '6 NADH', '1 NADH only'], 0,
    'It runs twice per glucose.'],
  ['Complete oxidation of one pyruvate to CO₂ releases:', ['3 CO₂ — one by pyruvate dehydrogenase and two in the Krebs cycle', '1 CO₂', '6 CO₂', 'No CO₂'], 0,
    'The PDH complex links glycolysis to the cycle.'],
  ['Current estimates of ATP yield per glucose in aerobic respiration are about:', ['30–32 ATP', '2 ATP', '100 ATP', '8 ATP'], 0,
    'Older textbooks give 36–38.'],
  ['Cyanide-resistant respiration in plants is due to:', ['The alternative oxidase, which passes electrons from ubiquinol directly to O₂', 'Cytochrome c oxidase', 'Complex I', 'ATP synthase'], 0,
    'It bypasses complexes III and IV, so less ATP is made.'],
  ['Heat production in the spadix of *Arum* (thermogenesis) comes from:', ['High alternative oxidase activity', 'Photosynthesis', 'Fermentation', 'Nitrogen fixation'], 0,
    'The warmth volatilises odours that attract pollinators.'],
  ['The respiratory quotient (RQ) for fats is about:', ['0.7', '1.0', '1.3', '4.0'], 0,
    'Carbohydrates give 1.0; organic acids give more than 1.']
] },
{ p: 'B2', t: 'Photosynthesis & Respiration', w: 2, pyq: ['CSE-2020-B2-m29', 'CSE-1997-B2-m14', 'CSE-2023-B2-m28', 'CSE-1994-B2-m24', 'CSE-2016-B2-m25', 'CSE-1991-B2-m21', 'CSE-1985-B2-m03', 'IFoS-2001-B2-m07'], q: [
  ['In plant cells, fatty acids are synthesised mainly in:', ['Plastids', 'Cytosol', 'Mitochondria', 'Peroxisomes'], 0,
    'Animals make them in the cytosol.'],
  ['The first committed step of fatty acid synthesis is catalysed by:', ['Acetyl-CoA carboxylase', 'Fatty acid synthase', 'Lipase', 'Thiolase'], 0,
    'Grass-killing herbicides (e.g. "fops" and "dims") inhibit grass ACCase.'],
  ['During fatty acid synthesis, the growing chain is carried on:', ['Acyl carrier protein (ACP)', 'Coenzyme A only', 'Biotin', 'Ferredoxin'], 0,
    'Plants use a dissociated (type II) fatty acid synthase.'],
  ['The main products of plastid fatty acid synthase are:', ['Palmitate (16:0) and stearate (18:0), with oleate after desaturation', 'Linolenate only', 'Acetate', 'Glycerol'], 0,
    'Further desaturation happens on the ER.'],
  ['In germinating oil seeds, β-oxidation of fatty acids occurs in:', ['Glyoxysomes', 'Mitochondria only', 'Chloroplasts', 'Nucleus'], 0,
    'In animals it is mitochondrial.'],
  ['The glyoxylate cycle allows oil seeds to:', ['Convert fats into sugars for the growing seedling', 'Fix nitrogen', 'Make starch from CO₂', 'Break down protein'], 0,
    'Its key enzymes are isocitrate lyase and malate synthase.'],
  ['Storage triacylglycerols in seeds are held in:', ['Oil bodies coated with oleosins', 'Vacuoles', 'Amyloplasts', 'Peroxisomes'], 0,
    'Oleosins stop oil bodies merging.'],
  ['Linseed oil is a "drying oil" because it is rich in:', ['Linolenic acid, which oxidises and hardens', 'Saturated fatty acids', 'Waxes', 'Glycerol'], 0,
    'Olive and groundnut oils are non-drying.'],
  ['Fatty acid oxidation feeds energy production through:', ['β-oxidation to acetyl-CoA, then the Krebs cycle and electron transport', 'Glycolysis only', 'Photosynthesis', 'Fermentation'], 0,
    'Fats yield more energy per gram than carbohydrates.'],
  ['Double bonds are added to fatty acids by:', ['Desaturases', 'Lipases', 'Kinases', 'Carboxylases'], 0,
    'Cold tolerance often depends on desaturase activity.']
] },
{ p: 'B2', t: 'Plant Hormones & Development', w: 3, pyq: ['IFoS-2022-B2-m29', 'CSE-2005-B2-m08', 'IFoS-2004-B2-m18', 'IFoS-2009-B2-m21', 'IFoS-2005-B2-m19', 'IFoS-2010-B2-m25', 'CSE-1995-B2-m20', 'IFoS-2021-B2-m27', 'CSE-2009-B2-m10', 'CSE-1994-B2-m23', 'CSE-2011-B2-m28', 'CSE-2016-B2-m24', 'IFoS-2006-B2-m19', 'IFoS-2001-B2-m15', 'CSE-1986-B2-m23', 'IFoS-2021-B2-m21', 'CSE-2025-B2-m22', 'CSE-2002-B2-m15', 'CSE-2014-B2-m22', 'IFoS-2015-B2-m05', 'IFoS-2010-B2-m07', 'CSE-1985-B2-m08', 'IFoS-2010-B2-m01'], q: [
  ['The *Avena* curvature test, used to discover auxin, was devised by:', ['F. W. Went (1928)', 'Kurosawa', 'Skoog', 'Darwin alone'], 0,
    'Auxin (IAA) is made mainly from tryptophan.'],
  ['Auxin promotes cell elongation mainly by:', ['Activating plasma-membrane H⁺-ATPases that loosen the wall (acid growth)', 'Dissolving the cell wall', 'Stopping water uptake', 'Blocking photosynthesis'], 0,
    'Expansins act in the acidified wall.'],
  ['Gibberellins were first found in the fungus causing:', ['Bakanae ("foolish seedling") disease of rice', 'Rust of wheat', 'Late blight', 'Crown gall'], 0,
    'Kurosawa (1926), from *Gibberella fujikuroi*.'],
  ['In barley seeds, gibberellin from the embryo induces:', ['α-amylase synthesis in the aleurone layer', 'Dormancy', 'Chlorophyll breakdown', 'Root nodules'], 0,
    'This is used in malting and as a bioassay.'],
  ['The first cytokinin, kinetin, was isolated by Miller and Skoog from:', ['Autoclaved herring sperm DNA', 'Maize grains', 'Coconut milk', 'Rice seedlings'], 0,
    'Zeatin, the first natural cytokinin, came from maize.'],
  ['A typical effect of cytokinin is:', ['Promoting cell division and delaying leaf senescence', 'Closing stomata', 'Causing apical dominance', 'Promoting abscission'], 0,
    'It also releases lateral buds from apical dominance.'],
  ['Abscisic acid is called a stress hormone because it:', ['Closes stomata and induces stress-protective genes during drought', 'Promotes growth', 'Causes fruit ripening', 'Breaks dormancy'], 0,
    'It was found as abscisin II and dormin.'],
  ['Ethylene is made from methionine through:', ['SAM and ACC, by ACC synthase and ACC oxidase', 'Tryptophan and IAA', 'Mevalonate and GGPP', 'Adenine'], 0,
    'Methionine is recycled by the Yang cycle.'],
  ['The "triple response" of pea seedlings to ethylene is:', ['Short thick stem, horizontal growth and an exaggerated hook', 'Tall thin stem', 'Rapid flowering', 'Leaf expansion'], 0,
    'Ethylene is unusual in being a gas.'],
  ['Apical dominance is mainly due to:', ['Auxin from the shoot apex suppressing lateral buds', 'Gibberellin from roots', 'Ethylene from leaves', 'Abscisic acid from seeds'], 0,
    'Cytokinin and strigolactones also take part.']
] },
{ p: 'B2', t: 'Plant Hormones & Development', w: 2, pyq: ['CSE-2024-B2-m26', 'IFoS-2019-B2-m29', 'CSE-2009-B2-m09', 'IFoS-2006-B2-m18', 'CSE-1991-B2-m20', 'CSE-1989-B2-m20', 'IFoS-2023-B2-m23', 'CSE-2021-B2-m25', 'IFoS-2020-B2-m25', 'CSE-2009-B2-m08', 'IFoS-2003-B2-m21', 'CSE-2023-B2-m25', 'CSE-1992-B2-m21', 'CSE-2011-B2-m27', 'CSE-2025-B2-m23', 'CSE-2013-B2-m25', 'CSE-2003-B2-m05', 'CSE-2001-B2-m08', 'IFoS-2013-B2-m04', 'IFoS-2007-B2-m09', 'IFoS-2004-B2-m05', 'CSE-2003-B2-m04', 'CSE-1995-B2-m04', 'IFoS-2007-B2-m13', 'IFoS-2001-B2-m01'], q: [
  ['Monocarpic senescence, as in wheat, is:', ['Death of the whole plant after a single flowering', 'Annual leaf fall', 'Loss of the shoot only', 'Death of the root only'], 0,
    'Deciduous trees show simultaneous leaf senescence; sequential senescence moves up the plant.'],
  ['During leaf senescence:', ['Chlorophyll and proteins are broken down and nutrients moved to young parts', 'Chlorophyll increases', 'Protein synthesis rises', 'Starch builds up'], 0,
    'Ethylene promotes it; cytokinin delays it.'],
  ['Vernalisation is:', ['Promotion of flowering by a period of low temperature', 'Breaking dormancy by light', 'Flowering in long days', 'Seed germination in cold'], 0,
    'Winter wheat and biennials such as cabbage need it.'],
  ['The site of perception of the vernalisation stimulus is the:', ['Shoot apex', 'Root tip', 'Mature leaf', 'Flower'], 0,
    'Photoperiod, by contrast, is perceived by leaves.'],
  ['In *Arabidopsis*, vernalisation works by:', ['Epigenetic silencing of the floral repressor *FLC* through histone changes', 'Destroying chlorophyll', 'Activating ethylene genes', 'Increasing *FLC*'], 0,
    'VIN3 is induced by cold; high temperature right after can devernalise.'],
  ['Gravitropism of roots is explained by the starch–statolith hypothesis, in which:', ['Amyloplasts in root-cap columella cells settle with gravity', 'Chloroplasts move to the light', 'Vacuoles swell', 'Nuclei divide'], 0,
    'Haberlandt and Němec proposed it in 1900.'],
  ['The Cholodny–Went model explains phototropism as:', ['Lateral movement of auxin to the shaded side, which grows faster', 'Destruction of auxin on the lit side only', 'Cytokinin movement', 'Loss of water on the lit side'], 0,
    'Phototropins are the blue-light receptors.'],
  ['Leaf folding of *Mimosa pudica* on touch is:', ['Seismonasty, due to loss of turgor in the pulvinus', 'Phototropism', 'Gravitropism', 'Nyctinasty only'], 0,
    'Nastic movements do not depend on the direction of the stimulus.'],
  ['Sleep movements of leaves (e.g. *Albizia*) are:', ['Nyctinastic movements', 'Thigmotropic', 'Hydrotropic', 'Geotropic'], 0,
    'They follow the day–night cycle.'],
  ['Differentiation differs from growth in that it is:', ['A change in cell structure and function, while growth is an irreversible increase in size', 'An increase in mass only', 'Cell death', 'Cell division only'], 0,
    'Development covers both, from germination to senescence.']
] },
{ p: 'B2', t: 'Water Relations & Mineral Nutrition', w: 3, pyq: ['CSE-2022-B2-m27', 'CSE-2016-B2-m26', 'CSE-2013-B2-m27', 'CSE-1991-B2-m22', 'IFoS-2010-B2-m26', 'CSE-1996-B2-m14', 'IFoS-2024-B2-m24', 'CSE-1994-B2-m20', 'CSE-2015-B2-m21', 'IFoS-2024-B2-m23', 'CSE-2017-B2-m20', 'CSE-1994-B2-m25', 'CSE-1991-B2-m02', 'CSE-2020-B2-m09', 'CSE-1985-B2-m09', 'IFoS-2024-B2-m17', 'CSE-1992-B2-m04', 'CSE-1990-B2-m03', 'IFoS-2021-B2-m12', 'IFoS-2004-B2-m04', 'IFoS-2007-B2-m07', 'CSE-1998-B2-m04', 'CSE-1997-B2-m07'], q: [
  ['Water potential of a plant cell (ignoring gravity) is:', ['Ψw = Ψs + Ψp', 'Ψw = Ψs − Ψp', 'Ψw = Ψp × Ψs', 'Ψw = 0 always'], 0,
    'Pure water at atmospheric pressure has Ψw = 0; water moves to lower Ψw.'],
  ['In older terms, a fully turgid cell has a diffusion pressure deficit (DPD) of:', ['Zero, because turgor pressure equals osmotic pressure', 'Maximum', 'Equal to OP', 'Negative'], 0,
    'DPD = OP − TP.'],
  ['The soil water available to plants lies between:', ['Field capacity and the permanent wilting point', 'Saturation and field capacity', 'Wilting point and oven-dry soil', 'Hygroscopic water only'], 0,
    'Field capacity ≈ −0.03 MPa; permanent wilting point ≈ −1.5 MPa.'],
  ['Transpiration is called a "necessary evil" because it:', ['Wastes water but cools leaves and drives mineral transport', 'Is always harmful', 'Stops photosynthesis', 'Has no use'], 0,
    'Curtis coined the phrase.'],
  ['Stomatal opening is driven mainly by:', ['K⁺ uptake into guard cells, powered by a blue-light-activated H⁺-ATPase', 'Starch formation in guard cells', 'Loss of water from guard cells', 'Ethylene'], 0,
    'Malate and Cl⁻ balance the charge; the older starch–sugar hypothesis is Sayre\'s.'],
  ['During water stress, stomata close because of:', ['Abscisic acid triggering ion loss from guard cells', 'Cytokinin', 'Gibberellin', 'Auxin'], 0,
    'This is a key drought adaptation.'],
  ['The pressure-flow hypothesis of phloem transport was proposed by:', ['Münch (1930)', 'Dixon and Joly', 'Hatch and Slack', 'Went'], 0,
    'Sugar loading at sources and unloading at sinks creates a pressure gradient.'],
  ['Apoplastic phloem loading of sucrose:', ['Uses a sucrose–H⁺ symporter and costs metabolic energy', 'Is passive diffusion', 'Moves raffinose through plasmodesmata', 'Needs no membrane transport'], 0,
    'Symplastic loading by "polymer trapping" (raffinose, stachyose) occurs in cucurbits.'],
  ['Sieve-tube elements are:', ['Living but without a nucleus, joined by sieve plates and served by companion cells', 'Dead cells with lignin', 'Nucleated storage cells', 'Fibres'], 0,
    'P-protein and callose can seal damaged sieve plates.'],
  ['Phloem unloading at sinks such as developing seeds often involves:', ['Movement out of sieve tubes through the apoplast or symplast to sink cells', 'Evaporation', 'Root pressure', 'Guttation'], 0,
    'Sink strength governs where assimilates go.']
] },
{ p: 'B2', t: 'Water Relations & Mineral Nutrition', w: 3, pyq: ['CSE-2024-B2-m21', 'CSE-2017-B2-m24', 'IFoS-2009-B2-m15', 'CSE-1997-B2-m13', 'CSE-2012-B2-m30', 'CSE-1988-B2-m20', 'CSE-1987-B2-m16', 'CSE-2009-B2-m06', 'CSE-2003-B2-m16', 'CSE-2006-B2-m15', 'CSE-1995-B2-m22', 'CSE-1990-B2-m19', 'CSE-2023-B2-m22', 'CSE-1999-B2-m14', 'CSE-2022-B2-m23', 'CSE-2019-B2-m25', 'CSE-2014-B2-m23', 'CSE-2011-B2-m26', 'CSE-2016-B2-m27', 'CSE-2010-B2-m24', 'CSE-2004-B2-m09', 'CSE-2004-B2-m07', 'IFoS-2012-B2-m21', 'CSE-1995-B2-m06', 'IFoS-2015-B2-m09', 'IFoS-2010-B2-m08', 'IFoS-2021-B2-m11', 'IFoS-2002-B2-m09', 'IFoS-2002-B2-m10', 'IFoS-2016-B2-m08', 'IFoS-2019-B2-m09', 'IFoS-2022-B2-m09', 'IFoS-2012-B2-m09', 'CSE-2000-B2-m03', 'CSE-1997-B2-m10'], q: [
  ['Secondary active transport, such as sucrose–H⁺ symport, is powered by:', ['A proton gradient set up by the H⁺-ATPase', 'Direct ATP hydrolysis by the carrier', 'Light alone', 'Diffusion'], 0,
    'Primary active transport uses ATP directly, as in the P-type H⁺-ATPase.'],
  ['Ion channels differ from carriers in that channels:', ['Allow very fast passive flow through a gated pore', 'Bind and change shape for each ion', 'Need ATP', 'Are saturated at low ion levels'], 0,
    'Carriers are slower and saturable.'],
  ['Facilitated diffusion differs from simple diffusion in that it:', ['Uses a membrane protein but still moves solutes down their gradient', 'Uses ATP', 'Moves solutes against their gradient', 'Needs no protein'], 0,
    'Aquaporins facilitate water movement.'],
  ['Epstein\'s ion-uptake kinetics supported the idea that ions are moved by:', ['Carriers following Michaelis–Menten-like kinetics', 'Simple diffusion only', 'Pinocytosis', 'Mass flow'], 0,
    'He found high- and low-affinity (dual) systems.'],
  ['Donnan equilibrium explains how cells accumulate cations because of:', ['Fixed, non-diffusible anions in the cell or wall', 'ATP use', 'Light', 'Water loss'], 0,
    'It is a passive mechanism.'],
  ['The criteria of essentiality for plant nutrients were laid down by:', ['Arnon and Stout (1939)', 'Liebig', 'Sachs', 'Hoagland'], 0,
    'Seventeen elements are generally accepted as essential, including nickel.'],
  ['Chlorosis appearing first in older leaves suggests a deficiency of:', ['A mobile element such as nitrogen or magnesium', 'An immobile element such as iron or calcium', 'Boron', 'Copper'], 0,
    'Iron deficiency gives interveinal chlorosis of young leaves.'],
  ['Match deficiency with disorder: whiptail of cauliflower —', ['Molybdenum', 'Boron', 'Zinc', 'Calcium'], 0,
    'Boron: heart rot of beet; zinc: khaira of rice; calcium: blossom-end rot of tomato.'],
  ['Grasses take up iron mainly by:', ['Releasing phytosiderophores (e.g. mugineic acid) and absorbing Fe(III) complexes', 'Acidifying soil and reducing Fe(III) at the root (Strategy I)', 'Mycorrhizae only', 'Leaf absorption'], 0,
    'Dicots use Strategy I with ferric-chelate reductase and IRT1.'],
  ['Nitrate reductase and nitrogenase both need:', ['Molybdenum', 'Copper', 'Zinc', 'Manganese'], 0,
    'Copper is in plastocyanin; zinc in carbonic anhydrase.']
] },
{ p: 'B2', t: 'Enzymes & Nitrogen Metabolism', w: 2, pyq: ['CSE-2023-B2-m27', 'CSE-1992-B2-m19', 'CSE-2024-B2-m22', 'IFoS-2019-B2-m28', 'CSE-2014-B2-m28', 'CSE-2012-B2-m19'], q: [
  ['Nitrate reductase in leaves reduces:', ['Nitrate to nitrite in the cytosol using NADH', 'Nitrite to ammonia in plastids', 'N₂ to ammonia', 'Ammonia to nitrate'], 0,
    'It contains a molybdenum cofactor.'],
  ['Nitrite reductase works in the:', ['Chloroplast, using reduced ferredoxin', 'Cytosol, using NADH', 'Mitochondria, using FADH₂', 'Vacuole'], 0,
    'It reduces nitrite to ammonium.'],
  ['Nitrate reductase activity rises with:', ['Nitrate supply and light', 'Darkness', 'High ammonium only', 'Drought'], 0,
    'It is also switched off by phosphorylation and 14-3-3 proteins.'],
  ['Glutamine synthetase catalyses:', ['Glutamate + NH₄⁺ + ATP → glutamine', 'Glutamine + 2-oxoglutarate → 2 glutamate', 'Nitrate → nitrite', 'Aspartate → asparagine'], 0,
    'GOGAT then transfers the amide to 2-oxoglutarate.'],
  ['The GS–GOGAT cycle is the main route for:', ['Assimilating ammonium into amino acids', 'Fixing CO₂', 'Breaking down protein', 'Making ethylene'], 0,
    'GOGAT can use ferredoxin (leaves) or NADH (roots).'],
  ['In nitrification, ammonium is oxidised to nitrite by:', ['*Nitrosomonas*', '*Nitrobacter*', '*Rhizobium*', '*Pseudomonas*'], 0,
    '*Nitrobacter* then oxidises nitrite to nitrate.'],
  ['Nitrifying bacteria obtain ATP by:', ['Chemoautotrophic oxidation of ammonium or nitrite', 'Photosynthesis', 'Fermentation', 'Parasitism'], 0,
    'They fix CO₂ using the energy released.'],
  ['Amino groups are passed between amino acids by:', ['Transamination (aminotransferases)', 'Deamination only', 'Decarboxylation', 'Phosphorylation'], 0,
    'Pyridoxal phosphate is the coenzyme.'],
  ['Denitrification returns nitrogen to the air through:', ['Bacteria reducing nitrate to N₂ in waterlogged soils', 'Plants releasing N₂', 'Lightning', 'Nitrifiers'], 0,
    '*Pseudomonas* and *Paracoccus* are examples.'],
  ['Plants absorb nitrogen mainly as:', ['Nitrate and ammonium', 'N₂ gas', 'Urea only', 'Proteins'], 0,
    'Legumes also get it through symbiotic fixation.']
] },
{ p: 'B2', t: 'Enzymes & Nitrogen Metabolism', w: 2, pyq: ['CSE-2023-B2-m26', 'CSE-2020-B2-m28', 'CSE-1999-B2-m18'], q: [
  ['The first law of thermodynamics states that:', ['Energy can be changed in form but not created or destroyed', 'Entropy always decreases', 'Heat flows from cold to hot', 'All reactions are spontaneous'], 0,
    'The second law says total entropy increases in spontaneous processes.'],
  ['Free-energy change combines the two laws as:', ['ΔG = ΔH − TΔS', 'ΔG = ΔH + TΔS', 'ΔG = TΔS', 'ΔG = ΔH × T'], 0,
    'A reaction is spontaneous when ΔG is negative.'],
  ['An exergonic reaction has:', ['Negative ΔG and can proceed spontaneously', 'Positive ΔG', 'ΔG = 0', 'No energy change'], 0,
    'Endergonic reactions need to be coupled to exergonic ones.'],
  ['The standard free-energy change is linked to the equilibrium constant by:', ['ΔG°′ = −RT ln K′eq', 'ΔG°′ = RT × K′eq', 'ΔG°′ = K′eq ÷ RT', 'ΔG°′ = −nF'], 0,
    'A large K′eq means a strongly negative ΔG°′.'],
  ['Hydrolysis of ATP to ADP and Pi has a ΔG°′ of about:', ['−30.5 kJ/mol', '+30.5 kJ/mol', '−3 kJ/mol', '−300 kJ/mol'], 0,
    'Inside cells the actual ΔG is larger, about −50 kJ/mol.'],
  ['Enzymes speed reactions by:', ['Lowering the activation energy without changing ΔG or equilibrium', 'Making ΔG more negative', 'Shifting the equilibrium', 'Supplying energy'], 0,
    'They speed both forward and reverse reactions.'],
  ['For a redox reaction, free energy relates to potential difference by:', ['ΔG°′ = −nFΔE°′', 'ΔG°′ = nFΔE°′', 'ΔG°′ = RT', 'ΔG°′ = ΔE°′'], 0,
    'Electrons flow towards the more positive redox potential.'],
  ['The ultimate source of bioenergy in ecosystems is:', ['Sunlight captured by photosynthesis', 'Geothermal heat', 'ATP from soil', 'Fermentation'], 0,
    'Respiration releases this stored energy as ATP.'],
  ['Coupling of reactions in cells usually works through:', ['A shared intermediate, often a phosphorylated compound from ATP', 'Heat transfer', 'Direct light', 'Diffusion'], 0,
    'This lets ATP drive uphill reactions.'],
  ['Reaction rate (kinetics) differs from equilibrium (thermodynamics) in that rate depends on:', ['Activation energy and catalysis, not on ΔG alone', 'ΔG only', 'Equilibrium constant only', 'Entropy only'], 0,
    'A reaction can be favourable yet very slow.']
] }
);
