/* Concept sets for Agriculture I — Forest products and policy; agronomy of rice, cotton, tobacco, maize, millets, oilseeds and forages. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Agroforestry & Social Forestry', w: 2, pyq: ['CSE-2024-A1-m07', 'CSE-2021-A1-m08', 'CSE-2017-A1-m06', 'CSE-2022-A1-m04', 'CSE-2023-A1-m03', 'IFoS-2003-A1-m05', 'CSE-2025-A1-m04', 'CSE-2025-A1-m05'], q: [
  ['Forests\' ameliorative function refers to:', ['Moderating climate, improving soil and acting as a carbon sink', 'Supplying timber', 'Providing recreation', 'Producing fodder only'], 0,
    'Productive, protective, recreational and aesthetic functions are the others.'],
  ['The protective function of forests includes:', ['Soil and water conservation and shelter from wind', 'Timber sales', 'Tourism income', 'Paper making'], 0,
    'Watershed forests regulate stream flow.'],
  ['India\'s National Forest Policy (1988) aims for forest or tree cover over:', ['One-third of the geographical area (two-thirds in hills)', 'One-tenth of the area', 'Half the area everywhere', 'All land'], 0,
    'Earlier policies were issued in 1894 and 1952.'],
  ['The 1988 forest policy shifted emphasis from revenue to:', ['Ecological stability and meeting local people\'s needs with their participation', 'Timber export', 'Industrial plantations only', 'Mining'], 0,
    'Joint Forest Management followed in 1990.'],
  ['The Forest (Conservation) Act, 1980 requires central approval for:', ['Diverting forest land to non-forest uses', 'Planting trees on farms', 'Collecting NWFP', 'Building schools in cities'], 0,
    'It was amended in 2023 and renamed the Van (Sanrakshan Evam Samvardhan) Adhiniyam.'],
  ['Which is a non-wood forest product?', ['Tendu leaves', 'Teak logs', 'Sal poles', 'Pine timber'], 0,
    'Others: lac, gums, honey, mahua flowers, bamboo and medicinal plants.'],
  ['Non-wood forest products are important to forest dwellers because they:', ['Provide food, medicine and cash income, especially for tribal people', 'Are harmful', 'Have no market', 'Need heavy machinery'], 0,
    'TRIFED runs minimum support prices for minor forest produce.'],
  ['Van Dhan Vikas Kendras (2018) are meant for:', ['Value addition and marketing of minor forest produce by tribal groups', 'Timber felling', 'Forest fire fighting', 'Seed banks'], 0,
    'Value addition raises income from forest products.'],
  ['Vertical layering of a forest into canopy, understorey, shrub, herb and ground layers is called:', ['Stratification', 'Zonation', 'Succession', 'Fragmentation'], 0,
    'Zonation is change in vegetation along a gradient such as altitude.'],
  ['A step for long-term forest conservation is:', ['Protected areas, community management and control of fire and grazing', 'Clear-felling', 'Shifting cultivation on short cycles', 'Unrestricted grazing'], 0,
    'Sustainable harvesting and afforestation of degraded land also help.']
] },
{ p: 'A1', t: 'Crop Production', w: 3, pyq: ['CSE-2017-A1-m07', 'CSE-2018-A1-m06', 'CSE-1989-A1-m14', 'CSE-1996-A1-m10', 'CSE-1996-A1-m09', 'CSE-1991-A1-m12', 'IFoS-2019-A1-m20'], q: [
  ['For transplanted rice, seedlings are usually transplanted at about:', ['20–25 days old, 2–3 per hill', '60 days old, 10 per hill', '5 days old, singly', '90 days old'], 0,
    'SRI uses 8–12-day-old single seedlings.'],
  ['The dapog and mat nurseries are useful for:', ['Raising rice seedlings for mechanical transplanting', 'Wheat sowing', 'Cotton', 'Sugarcane setts'], 0,
    'Seedlings grow on a thin layer and are lifted as mats.'],
  ['Wet direct-seeded rice is sown using:', ['Pre-germinated seed with a drum seeder on puddled soil', 'Dry seed on dry soil only', 'Transplanted seedlings', 'Broadcasting into standing water only'], 0,
    'Dry DSR uses dry seed drilled into unpuddled soil.'],
  ['A major challenge in direct-seeded rice is:', ['Weed control, as there is no standing water at crop establishment', 'Lodging', 'Too much water use', 'Labour for transplanting'], 0,
    'Pre-emergence pendimethalin and post-emergence bispyribac-sodium are used.'],
  ['Rice yields are higher in Punjab than in eastern India partly because:', ['More solar radiation during grain filling under clear skies', 'Less fertiliser use', 'Shorter days', 'More cloud cover'], 0,
    'Cloudy monsoon weather limits yields in the east.'],
  ['Alternate wetting and drying (AWD) in rice:', ['Saves 15–30% water with little or no yield loss', 'Needs continuous flooding', 'Raises methane emissions', 'Is only for upland rice'], 0,
    'Fields are re-flooded when water drops about 15 cm below the surface.'],
  ['Puddling helps transplanted rice by:', ['Reducing percolation losses and suppressing weeds', 'Improving soil aeration', 'Raising soil pH', 'Increasing infiltration'], 0,
    'It harms soil structure for the following crop.'],
  ['The common zinc-deficiency disorder of rice is:', ['Khaira', 'Blast', 'Tungro', 'Bakanae'], 0,
    'It is corrected with zinc sulphate.'],
  ['A popular semi-dwarf rice variety of eastern India is:', ['Swarna (MTU 7029)', 'Sonalika', 'Kalyan Sona', 'HD 2967'], 0,
    'Sonalika, Kalyan Sona and HD 2967 are wheats.'],
  ['The most yield-sensitive stage of rice to water stress is:', ['Flowering (anthesis)', 'Seedling', 'Maturity', 'Early tillering'], 0,
    'Panicle initiation is also sensitive.']
] },
{ p: 'A1', t: 'Crop Production', w: 2, pyq: ['CSE-2025-A1-m10', 'CSE-1989-A1-m06', 'CSE-1997-A1-m03', 'CSE-1991-A1-m04', 'CSE-1996-A1-m03', 'CSE-2015-A1-m06'], q: [
  ['Most of India\'s cotton area today is under:', ['*Gossypium hirsutum* (American upland), largely Bt hybrids', '*G. arboreum*', '*G. herbaceum*', '*G. barbadense*'], 0,
    '*G. arboreum* and *G. herbaceum* are the diploid desi cottons.'],
  ['Extra-long-staple cotton comes mainly from:', ['*Gossypium barbadense* and its hybrids', '*G. herbaceum*', '*G. arboreum*', 'Upland cotton only'], 0,
    'E.g. Suvin, and interspecific hybrids such as DCH-32.'],
  ['The world\'s first commercial cotton hybrid, H-4 (1970), was developed by:', ['C. T. Patel in Gujarat', 'Norman Borlaug', 'M. S. Swaminathan', 'B. P. Pal'], 0,
    'Varalaxmi (1972) was the first interspecific hybrid.'],
  ['Bt cotton was approved for commercial cultivation in India in:', ['2002', '1995', '2010', '2015'], 0,
    'Bollgard carried the *cry1Ac* gene against bollworms.'],
  ['Rainfed cotton on black soils is usually sown:', ['With the onset of the monsoon', 'In winter', 'In April under irrigation only', 'After the monsoon ends'], 0,
    'High-density planting systems are being promoted for rainfed cotton.'],
  ['A common legume intercrop in cotton is:', ['Green gram (or black gram)', 'Wheat', 'Rice', 'Sugarcane'], 0,
    'Short-duration pulses are harvested before cotton spreads.'],
  ['Flue curing is used for:', ['Virginia (cigarette) tobacco', 'Bidi tobacco', 'Cigar tobacco', 'Hookah tobacco'], 0,
    'Bidi, cigar and hookah tobaccos are mostly air- or sun-cured.'],
  ['The stages of flue curing are:', ['Yellowing, colour fixing, leaf drying and stem drying', 'Fermentation, drying and smoking', 'Soaking and boiling', 'Harvest and storage'], 0,
    'Temperature is raised step by step in a barn.'],
  ['Curing tobacco is beneficial because it:', ['Removes moisture and develops colour, aroma and smoking quality', 'Increases nicotine to toxic levels', 'Kills seeds', 'Adds fertiliser'], 0,
    'Starch is converted to sugars during yellowing.'],
  ['India\'s flue-cured Virginia tobacco is grown mainly in:', ['Andhra Pradesh and Karnataka', 'Punjab', 'Assam', 'Rajasthan'], 0,
    'Traditional black-soil and light-soil zones exist.']
] },
{ p: 'A1', t: 'Crop Production', w: 2, pyq: ['IFoS-2023-A1-m08', 'IFoS-2022-A1-m08', 'CSE-2022-A1-m06', 'IFoS-2020-A1-m09', 'CSE-2019-A1-m07'], q: [
  ['Quality protein maize (QPM) has higher lysine and tryptophan because of the:', ['*opaque-2* gene', '*sugary-1* gene', '*waxy* gene', '*Rht* gene'], 0,
    'Shaktiman-1 was India\'s first QPM hybrid.'],
  ['Sweet corn owes its sweetness to genes such as:', ['*sugary-1* and *shrunken-2*', '*opaque-2*', '*Bt*', '*Sub1*'], 0,
    'It is harvested at the milk stage, about 18–20 days after silking.'],
  ['Baby corn is harvested:', ['1–3 days after silk emergence, before fertilisation', 'At full maturity', 'At the milk stage', 'After drying'], 0,
    'Plants are detasselled to avoid pollination.'],
  ['Maize is:', ['A monoecious, protandrous C₄ cereal', 'A dioecious C₃ cereal', 'A self-pollinated legume', 'A CAM plant'], 0,
    'Tassels shed pollen before silks are receptive.'],
  ['Millets suit climate-resilient agriculture because they:', ['Tolerate drought and heat, mature quickly and need few inputs', 'Need heavy irrigation', 'Grow only in cold climates', 'Need high fertiliser'], 0,
    'Most are C₄ plants.'],
  ['India declared millets "nutri-cereals" in:', ['2018', '2000', '1966', '2023'], 0,
    'The UN observed 2023 as the International Year of Millets at India\'s proposal.'],
  ['Biofortification means:', ['Raising the nutrient content of crops through breeding, agronomy or biotechnology', 'Adding vitamins to packaged food', 'Using bio-pesticides', 'Organic farming'], 0,
    'HarvestPlus leads global biofortification work.'],
  ['A biofortified pearl millet variety rich in iron is:', ['Dhanashakti', 'Shaktiman-1', 'Pusa Basmati 1121', 'Swarna'], 0,
    'Zinc-rich rice (e.g. DRR Dhan 45) and wheat have also been released.'],
  ['Golden Rice is biofortified with:', ['Provitamin A (β-carotene) through genetic engineering', 'Iron by breeding', 'Zinc by spraying', 'Lysine'], 0,
    'Orange-fleshed sweet potato is a bred source of provitamin A.'],
  ['Agronomic biofortification of zinc is done by:', ['Soil or foliar application of zinc sulphate', 'Flooding', 'Burning residues', 'Using only urea'], 0,
    'Foliar sprays at grain filling raise grain zinc.']
] },
{ p: 'A1', t: 'Crop Production', w: 2, pyq: ['CSE-2018-A1-m07', 'CSE-2015-A1-m05', 'CSE-2023-A1-m08', 'IFoS-2013-A1-m27', 'IFoS-2023-A1-m22'], q: [
  ['India\'s nine annual oilseed crops include:', ['Groundnut, rapeseed–mustard, soybean, sunflower, sesame, safflower, niger, castor and linseed', 'Coconut and oil palm only', 'Cotton and jute', 'Rice bran and maize'], 0,
    'Soybean, groundnut and mustard dominate production.'],
  ['India meets a large share of its edible-oil needs through:', ['Imports, mainly palm and soybean oil', 'Exports', 'Self-sufficiency', 'Animal fats'], 0,
    'Time-sensitive: imports have run at over half of consumption.'],
  ['A main constraint on oilseed production in India is that:', ['Most oilseeds are grown rainfed with low inputs and low seed replacement', 'They are all irrigated', 'There is no demand', 'Seed is too cheap'], 0,
    'The 1986 Technology Mission on Oilseeds brought the "Yellow Revolution".'],
  ['Gypsum is applied to groundnut at pegging to supply:', ['Calcium and sulphur for pod filling', 'Nitrogen', 'Phosphorus', 'Potassium'], 0,
    'It reduces unfilled pods.'],
  ['Groundnut on calcareous soils often shows:', ['Iron-deficiency chlorosis', 'Aluminium toxicity', 'Nitrogen excess', 'Sodium toxicity'], 0,
    'Foliar ferrous sulphate corrects it.'],
  ['Hay is forage that has been:', ['Dried to below about 15% moisture for storage', 'Fermented in a silo', 'Chopped and fed fresh', 'Pelleted with urea'], 0,
    'Silage is preserved by anaerobic fermentation.'],
  ['Good silage is preserved mainly by:', ['Lactic acid produced in anaerobic fermentation, lowering pH to about 4', 'Drying in the sun', 'Adding salt', 'Freezing'], 0,
    'Maize and sorghum make the best silage.'],
  ['Forage conservation is needed because:', ['Green fodder is scarce in lean seasons', 'Animals prefer stored fodder', 'Fresh fodder is toxic', 'It costs nothing'], 0,
    'It evens out fodder supply through the year.'],
  ['Berseem (Egyptian clover) is known as the:', ['"King of fodders"', '"Queen of forages"', '"Poor man\'s meat"', '"Golden fibre"'], 0,
    'Lucerne (alfalfa) is called the queen of forages.'],
  ['Sesame is called the "queen of oilseeds" because:', ['Its oil keeps well due to natural antioxidants', 'It has the highest yield', 'It is grown only in queenly estates', 'It fixes nitrogen'], 0,
    'Sesamol and sesamin give stability.']
] }
);
