/* Concept sets for Botany II — breeding odds, evolution, plant geography, economic plants (old CSE syllabus), prions and a mixed revision set. Each block is linked to every PYQ that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 2, pyq: ['IFoS-2003-B2-m01', 'IFoS-2002-B2-m01', 'CSE-2003-B2-m03', 'IFoS-2025-B2-m02', 'IFoS-2022-B2-m21', 'CSE-2024-B2-m17', 'CSE-2021-B2-m21', 'CSE-2017-B2-m17', 'CSE-2012-B2-m27', 'IFoS-2021-B2-m08', 'CSE-2009-B2-m05', 'CSE-1987-B2-m15', 'CSE-2015-B2-m17'], q: [
  ['In diplospory, the unreduced embryo sac develops from:', ['The megaspore mother cell without normal meiosis', 'A nucellar cell', 'The synergid', 'The antipodal cell'], 0,
    'E.g. *Taraxacum*. In apospory (e.g. *Hieracium*, *Pennisetum*) it comes from a somatic nucellar cell.'],
  ['Adventive (sporophytic) embryony, as in *Citrus* and mango, means embryos arise from:', ['Nucellus or integument cells outside the embryo sac', 'The egg after fertilisation', 'The synergids', 'Pollen'], 0,
    'It gives polyembryony and true-to-type nucellar seedlings.'],
  ['Apomixis is of great interest to breeders because it can:', ['Fix hybrid vigour so hybrids breed true from seed', 'Increase genetic variation each generation', 'Prevent seed formation', 'Make plants self-incompatible'], 0,
    'Farmers could save hybrid seed without loss of vigour.'],
  ['Haploid plants from anther culture were first produced by:', ['Guha and Maheshwari (1964) in *Datura*', 'Haberlandt', 'Murashige and Skoog', 'Cocking'], 0,
    'Androgenesis is development of a plant from the male gametophyte.'],
  ['A monohaploid differs from a polyhaploid in that a monohaploid has:', ['One basic set of chromosomes (n = x)', 'Half the chromosomes of a polyploid', 'Two sets', 'No chromosomes'], 0,
    'A haploid of hexaploid wheat is a polyhaploid.'],
  ['Doubled haploids are valuable because they:', ['Give completely homozygous lines in one generation', 'Are always sterile', 'Are heterozygous', 'Cannot be produced'], 0,
    'Chromosomes are doubled with colchicine.'],
  ['Wheat haploids can be made by crossing wheat with:', ['Maize, after which maize chromosomes are lost', 'Rice', 'Barley only', 'Soybean'], 0,
    'The *Hordeum bulbosum* method works similarly for barley.'],
  ['Gynogenesis is production of haploids from:', ['Unfertilised ovules or ovaries', 'Anthers', 'Root tips', 'Leaves'], 0,
    'It is used in crops where anther culture fails.'],
  ['Self-incompatibility is used in hybrid seed production of:', ['*Brassica* crops', 'Rice', 'Wheat', 'Barley'], 0,
    'Parent lines are maintained by bud pollination.'],
  ['Haploids help in mutation breeding because:', ['Recessive mutations show up at once', 'They have more chromosomes', 'They are heterozygous', 'They never flower'], 0,
    'There is no dominant allele to mask them.']
] },
{ p: 'B2', t: 'Plant Breeding & Biostatistics', w: 2, pyq: ['CSE-1997-B2-m04', 'CSE-1994-B2-m19', 'CSE-1990-B2-m13', 'CSE-1988-B2-m19', 'CSE-1985-B2-m11', 'CSE-2014-B2-m21', 'CSE-2014-B2-m20', 'CSE-1995-B2-m03', 'CSE-1995-B2-m02', 'CSE-1994-B2-m03'], q: [
  ['Vavilov located centres of origin of crops as regions of:', ['Maximum genetic diversity of the crop and its wild relatives', 'Highest yield today', 'Largest cultivated area', 'Most rainfall'], 0,
    'He called it the differential phytogeographic method.'],
  ['Bread wheat arose by hybridisation of tetraploid wheat with:', ['*Aegilops tauschii*, which gave the D genome', 'Rye', '*Hordeum*', 'Maize'], 0,
    'Wheat was domesticated in the Fertile Crescent of the Near East.'],
  ['The wild progenitor of Asian rice is:', ['*Oryza rufipogon*', '*Oryza glaberrima*', '*Oryza australiensis*', '*Zizania aquatica*'], 0,
    '*O. glaberrima* is African rice.'],
  ['India\'s national gene bank for plant germplasm is maintained by:', ['NBPGR, New Delhi', 'ICRISAT', 'IRRI', 'FAO'], 0,
    'The Svalbard Global Seed Vault in Norway holds back-up samples.'],
  ['Match the CGIAR centre with its mandate: CIMMYT —', ['Wheat and maize', 'Rice', 'Potato', 'Sorghum and chickpea'], 0,
    'IRRI: rice; CIP: potato; ICRISAT (Hyderabad): sorghum, millets, chickpea, pigeonpea, groundnut.'],
  ['The Green Revolution in wheat was based on semi-dwarf varieties carrying dwarfing genes from:', ['Norin 10, used by Norman Borlaug', 'IR-8', 'Sharbati Sonora', 'Kalyan Sona'], 0,
    '*Rht* genes reduce gibberellin response.'],
  ['IR-8, the "miracle rice", was released by:', ['IRRI in 1966', 'ICAR in 1980', 'CIMMYT in 1950', 'NBPGR in 1990'], 0,
    'It was a semi-dwarf, fertiliser-responsive variety.'],
  ['M. S. Swaminathan is known as:', ['The father of India\'s Green Revolution', 'The discoverer of the genetic code', 'The father of Indian palaeobotany', 'The founder of NBPGR\'s seed vault in Norway'], 0,
    'He brought Mexican dwarf wheats to India in the 1960s.'],
  ['H. G. Khorana shared the 1968 Nobel Prize for:', ['Interpreting the genetic code', 'Discovering DNA structure', 'Inventing PCR', 'Discovering plasmids'], 0,
    'He later synthesised the first artificial gene.'],
  ['Breeding a basmati rice for organic farming would focus on:', ['Nutrient-use efficiency and disease and pest resistance while keeping grain quality and aroma', 'Maximum fertiliser response', 'Herbicide tolerance only', 'Dwarfing only'], 0,
    'Marker-assisted backcrossing can add resistance genes to popular basmati types.']
] },
{ p: 'B2', t: 'Evolution', w: 2, pyq: ['IFoS-2006-B2-m05', 'IFoS-2001-B2-m04', 'IFoS-2000-B2-m03', 'CSE-1999-B2-m03', 'CSE-1986-B2-m06', 'CSE-1996-B2-m04', 'CSE-2023-B2-m21', 'CSE-2018-B2-m19', 'CSE-2014-B2-m16'], q: [
  ['Lamarck explained evolution by:', ['Inheritance of acquired characters through use and disuse', 'Natural selection', 'Mutation', 'Genetic drift'], 0,
    'He set it out in *Philosophie Zoologique* (1809).'],
  ['Darwin\'s theory of natural selection rests on:', ['Overproduction, variation, struggle for existence and survival of the fittest', 'Inheritance of acquired traits', 'Sudden large mutations only', 'Divine design'], 0,
    '*On the Origin of Species* appeared in 1859; "survival of the fittest" was Spencer\'s phrase.'],
  ['The modern (synthetic) theory of evolution combines natural selection with:', ['Mendelian genetics — mutation, recombination, drift and isolation', 'Lamarckism', 'Special creation', 'Catastrophism'], 0,
    'Builders include Fisher, Haldane, Wright, Dobzhansky, Mayr and, for plants, Stebbins.'],
  ['De Vries proposed his mutation theory after studying:', ['*Oenothera lamarckiana*', 'Pea', '*Drosophila*', 'Maize'], 0,
    'Many of his "mutations" were later found to be chromosomal rearrangements.'],
  ['Oparin\'s coacervates are:', ['Colloidal droplets proposed as forerunners of cells', 'Fossil bacteria', 'Enzymes', 'Viruses'], 0,
    'Oparin and Haldane independently proposed chemical evolution of life.'],
  ['The Miller–Urey experiment (1953) produced:', ['Amino acids from methane, ammonia, hydrogen and water with electric sparks', 'DNA from proteins', 'Cells from mud', 'Oxygen from water'], 0,
    'It supported the idea of a "primordial soup".'],
  ['"Ontogeny recapitulates phylogeny" is the biogenetic law of:', ['Haeckel', 'Darwin', 'Mendel', 'Lamarck'], 0,
    'It is now seen as an oversimplification.'],
  ['Ribosomal RNA genes are used for phylogeny because they:', ['Occur in all organisms and have both conserved and variable regions', 'Mutate randomly very fast everywhere', 'Are absent in bacteria', 'Code for proteins'], 0,
    'Woese used 16S rRNA to define three domains of life.'],
  ['Homologous organs are those that:', ['Share a common origin but may differ in function', 'Have the same function but different origin', 'Are vestigial only', 'Are found only in animals'], 0,
    'Analogous organs, like tendrils of different origin, show convergence.'],
  ['"An organism is a bundle of adaptations" means that:', ['Its features have been shaped by natural selection to suit its environment', 'It has no variation', 'It cannot evolve', 'It is made of separate organisms'], 0,
    'Adaptations improve survival and reproduction.']
] },
{ p: 'B2', t: 'Evolution', w: 2, pyq: ['IFoS-2024-B2-m06', 'CSE-1994-B2-m04', 'CSE-1993-B2-m03', 'CSE-1989-B2-m08', 'CSE-2014-B2-m10', 'CSE-1999-B2-m11', 'CSE-1998-B2-m11', 'CSE-1992-B2-m11', 'CSE-1991-B2-m16', 'CSE-1990-B2-m09', 'CSE-1988-B2-m18', 'CSE-1986-B2-m16'], q: [
  ['Hardy–Weinberg equilibrium requires:', ['A large randomly mating population with no mutation, migration or selection', 'Small populations', 'Strong selection', 'Frequent migration'], 0,
    'Genotype frequencies are then p², 2pq and q².'],
  ['If 16% of a population shows a recessive trait (q² = 0.16), the frequency of heterozygotes is:', ['0.48', '0.16', '0.40', '0.36'], 0,
    'q = 0.4, p = 0.6, so 2pq = 0.48.'],
  ['Genetic drift is:', ['Random change in allele frequencies, strongest in small populations', 'Directional change by selection', 'Change by mutation only', 'Movement of genes by migration'], 0,
    'Founder effects and bottlenecks are forms of drift (Sewall Wright effect).'],
  ['The biological species concept was formulated by:', ['Ernst Mayr', 'Linnaeus', 'Darwin', 'Mendel'], 0,
    'A species is a group of interbreeding populations reproductively isolated from others.'],
  ['A prezygotic isolating mechanism is:', ['Flowering at different seasons (temporal isolation)', 'Hybrid sterility', 'Hybrid inviability', 'F₂ breakdown'], 0,
    'Others: habitat, mechanical, ethological and gametic isolation.'],
  ['Allopatric speciation occurs when:', ['Populations are separated geographically and diverge', 'Populations diverge in the same area', 'Polyploidy forms a new species instantly', 'Hybrids merge two species'], 0,
    'Sympatric speciation in plants is often through polyploidy.'],
  ['A gene pool is:', ['All the alleles of all genes in a population', 'The genes of one individual', 'A seed bank', 'A chromosome'], 0,
    'Evolution is a change in the gene pool over time.'],
  ['A normal woman whose father had haemophilia marries a normal man. The chance that a son will be haemophilic is:', ['50%', '25%', '0%', '100%'], 0,
    'She is a carrier (XᴴXʰ); each son has a half chance of receiving Xʰ.'],
  ['Postzygotic isolation includes:', ['Hybrid sterility, as in the mule', 'Different pollinators', 'Different flowering times', 'Different habitats'], 0,
    'It acts after fertilisation.'],
  ['Recombination in populations contributes to evolution by:', ['Producing new combinations of existing alleles', 'Creating new genes from nothing', 'Reducing variation always', 'Stopping selection'], 0,
    'Mutation supplies new alleles; recombination reshuffles them.']
] },
{ p: 'B2', t: 'Plant Geography, Forests & Biodiversity', w: 2, pyq: ['CSE-2011-B2-m07', 'CSE-2011-B2-m25'], q: [
  ['The "Age and Area" hypothesis was proposed by:', ['J. C. Willis (1922)', 'Wegener', 'Hooker', 'Hora'], 0,
    'It holds that older species tend to occupy larger areas.'],
  ['The Satpura hypothesis (S. L. Hora, 1949) explains:', ['How Malayan elements reached the Western Ghats via the Satpura–Vindhya ranges', 'Origin of Himalayan conifers', 'Desert flora of Rajasthan', 'Mangrove distribution'], 0,
    'It accounts for discontinuous distribution between the North-East and the Western Ghats.'],
  ['Discontinuous distribution of plant groups across southern continents is best explained by:', ['Continental drift', 'Recent human transport only', 'Wind only', 'Mutation'], 0,
    'Wegener proposed drift in 1912; *Glossopteris* fossils support it.'],
  ['Other explanations of discontinuous distribution include:', ['Long-distance dispersal, former land bridges and extinction in between', 'Only polyploidy', 'Only hybridisation', 'Photoperiod'], 0,
    'Several factors often act together.'],
  ['India\'s phytogeographic regions were described by:', ['D. Chatterjee (1939)', 'Champion and Seth', 'Hora', 'Willis'], 0,
    'He recognised nine regions, from the Western Himalaya to the Andamans.'],
  ['Champion and Seth (1968) classified Indian forests into:', ['16 major forest type groups', '4 biomes', '9 regions', '10 biogeographic zones'], 0,
    'Rodgers and Panwar divided India into 10 biogeographic zones.'],
  ['Palaeoendemics are:', ['Old relict species now confined to small areas', 'Newly evolved local species', 'Introduced weeds', 'Cosmopolitan species'], 0,
    'Neoendemics are recently evolved species not yet spread.'],
  ['On a Himalayan mountain, vegetation zones with rising altitude go:', ['Subtropical → temperate → subalpine → alpine', 'Alpine → temperate → tropical', 'Temperate → tropical → alpine', 'No change'], 0,
    'Temperature falls about 0.6 °C per 100 m.'],
  ['The Western Ghats and Eastern Himalaya are rich in endemics mainly because of:', ['High rainfall, varied terrain and long isolation', 'Low rainfall', 'Recent formation', 'Absence of mountains'], 0,
    'Both are parts of global biodiversity hotspots.'],
  ['The tree line on high mountains is set mainly by:', ['Low temperature during the growing season', 'Lack of soil only', 'Too much rain', 'Grazing only'], 0,
    'Above it lie alpine meadows and scrub.']
] },
{ p: 'B2', t: 'Secondary Metabolites', w: 2, pyq: ['CSE-1999-B2-m04', 'CSE-1999-B2-m05', 'CSE-1997-B2-m03', 'CSE-1995-B2-m05', 'CSE-1994-B2-m06', 'CSE-1994-B2-m08', 'CSE-1989-B2-m05', 'CSE-1989-B2-m07', 'CSE-1988-B2-m08', 'CSE-1988-B2-m05', 'CSE-1986-B2-m11'], q: [
  ['*Holarrhena antidysenterica* (kurchi) bark is used against:', ['Amoebic dysentery, due to the alkaloid conessine', 'Malaria', 'Hypertension', 'Cancer'], 0,
    'It belongs to Apocynaceae.'],
  ['*Catharanthus roseus* yields the anticancer alkaloids:', ['Vinblastine and vincristine', 'Reserpine and ajmalicine only', 'Quinine and quinidine', 'Morphine and codeine'], 0,
    'They are used against leukaemias and lymphomas.'],
  ['*Dioscorea deltoidea* tubers are a source of:', ['Diosgenin, a precursor for steroid drugs', 'Quinine', 'Rubber', 'Starch only'], 0,
    'Used for contraceptives and corticosteroids.'],
  ['Reserpine, an antihypertensive drug, comes from the roots of:', ['*Rauvolfia serpentina*', '*Withania somnifera*', '*Papaver somniferum*', '*Cinchona*'], 0,
    'It was one of the first modern tranquillisers.'],
  ['Java citronella oil, a mosquito repellent, is distilled from:', ['*Cymbopogon winterianus*', '*Vetiveria zizanioides*', '*Mentha arvensis*', '*Ocimum basilicum*'], 0,
    'It is rich in citronellal and geraniol.'],
  ['Vetiver oil is extracted from the:', ['Roots of *Chrysopogon* (*Vetiveria*) *zizanioides*', 'Leaves of lemongrass', 'Flowers of rose', 'Bark of cinnamon'], 0,
    'Vetiver grass is also used to check soil erosion.'],
  ['Pyrethrins, natural insecticides, come from flower heads of:', ['*Chrysanthemum* (*Tanacetum*) *cinerariifolium*', '*Tagetes erecta*', '*Azadirachta indica*', '*Nicotiana*'], 0,
    'They act fast on insect nerves and break down in sunlight.'],
  ['Neem (*Azadirachta indica*) is valued in pest control for:', ['Azadirachtin in its seeds, an antifeedant and growth disruptor', 'Pyrethrin', 'Rotenone', 'Nicotine'], 0,
    'Neem-coated urea also slows nitrogen loss.'],
  ['*Cannabis sativa* gives hemp fibre from its stem and, from female flowers:', ['Cannabinoids such as THC', 'Caffeine', 'Morphine', 'Nicotine'], 0,
    'It belongs to Cannabaceae.'],
  ['Ethnobotany differs from economic botany in that ethnobotany studies:', ['How particular peoples traditionally use and perceive plants', 'Only crops in trade', 'Only timber', 'Only fossil plants'], 0,
    'The two overlap: ethnobotanical leads often become economic plants.']
] },
{ p: 'B2', t: 'Secondary Metabolites', w: 1, pyq: ['CSE-1994-B2-m07', 'CSE-1994-B2-m09', 'CSE-1991-B2-m03', 'CSE-1989-B2-m06', 'CSE-1988-B2-m06', 'CSE-1988-B2-m07', 'CSE-1987-B2-m05', 'CSE-1987-B2-m06', 'CSE-1986-B2-m21', 'CSE-1999-B2-m12', 'CSE-1997-B2-m08', 'CSE-1993-B2-m15', 'CSE-1992-B2-m15', 'CSE-1991-B2-m18', 'CSE-1990-B2-m21', 'CSE-1989-B2-m11', 'CSE-1988-B2-m17', 'CSE-1989-B2-m24'], q: [
  ['Teak (*Tectona grandis*) timber is prized because it is:', ['Durable, strong and resistant to termites', 'Very soft and light', 'Easily decayed', 'Non-woody'], 0,
    'Its oils and tectoquinone resist decay and insects.'],
  ['Leaves of *Diospyros melanoxylon* (tendu) are used for:', ['Wrapping bidis — a major non-timber forest product', 'Making tea', 'Dyeing cloth', 'Producing rubber'], 0,
    'Ebony comes from the heartwood of *D. ebenum*.'],
  ['Palm oil is obtained from the:', ['Fleshy mesocarp of *Elaeis guineensis* fruits', 'Leaves', 'Trunk sap', 'Roots'], 0,
    'Palm kernel oil comes from the seed.'],
  ['Sesame (*Sesamum indicum*, Pedaliaceae) oil keeps well because it contains:', ['The antioxidants sesamol and sesamin', 'High water content', 'No fatty acids', 'Rubber'], 0,
    'It is called the "queen of oilseeds".'],
  ['Besides oil, safflower flowers were used for:', ['A red-yellow dye (carthamin)', 'Rubber', 'Fibre', 'Timber'], 0,
    'Safflower oil is rich in linoleic acid.'],
  ['*Leucaena leucocephala* fodder must be fed with care because it contains:', ['Mimosine, toxic in large amounts', 'Cyanide', 'Nicotine', 'Ricin'], 0,
    'It is otherwise a rich protein fodder.'],
  ['In making black tea, the step that develops colour and flavour is:', ['Fermentation (enzymatic oxidation of polyphenols)', 'Withering only', 'Drying only', 'Sorting'], 0,
    'Green tea is steamed or fired to stop fermentation.'],
  ['Match the useful part with its morphology: coir —', ['Fibrous mesocarp of coconut', 'Seed hairs', 'Stem bast', 'Leaf fibres'], 0,
    'Cotton: seed-coat hairs; jute: stem bast; sisal: leaf fibres.'],
  ['Among India\'s traditional plant-product exports are:', ['Tea, spices and cashew kernels', 'Wheat flour and rubber only', 'Timber and coal', 'Cotton cloth only'], 0,
    'Figures change yearly; check current trade data.'],
  ['Plants used in energy plantations for firewood include:', ['*Leucaena*, *Casuarina* and *Prosopis*', '*Tectona* and *Santalum*', '*Oryza* and *Triticum*', '*Coffea* and *Camellia*'], 0,
    'They grow fast and coppice well.']
] },
{ p: 'B2', t: 'Molecular Biology', w: 1, pyq: ['IFoS-2015-B2-m03', 'IFoS-2007-B2-m19', 'IFoS-2019-B2-m22', 'CSE-2012-B2-m13', 'IFoS-2010-B2-m14', 'CSE-2017-B2-m01', 'CSE-2006-B2-m04', 'CSE-1986-B2-m08', 'CSE-1986-B2-m09', 'CSE-1986-B2-m10', 'CSE-2020-B2-m14', 'CSE-2016-B2-m14', 'CSE-1995-B2-m08', 'CSE-1994-B2-m10', 'CSE-2010-B2-m15', 'IFoS-2015-B2-m20'], q: [
  ['Prions should not be grouped with viruses because they:', ['Have no nucleic acid and are made only of protein', 'Have DNA and a capsid', 'Are bacteria', 'Need a plant host'], 0,
    'They resist UV and nucleases that destroy viruses.'],
  ['Prions multiply by:', ['Misfolded PrPˢᶜ converting normal PrPᶜ into the misfolded form', 'Copying their DNA', 'Reverse transcription', 'Binary fission'], 0,
    'Aggregates form amyloid plaques.'],
  ['Prions changed ideas of inheritance because they showed that:', ['A protein conformation can be transmitted without nucleic acid', 'DNA is not genetic material', 'RNA is always genetic', 'Genes are proteins'], 0,
    'Yeast prions such as [PSI⁺] are inherited through the cytoplasm.'],
  ['Prion diseases are called:', ['Transmissible spongiform encephalopathies', 'Mosaic diseases', 'Rusts', 'Blights'], 0,
    'E.g. BSE, scrapie, CJD and kuru.'],
  ['Mixed revision — cyclin-dependent kinases drive the cell cycle when they:', ['Bind cyclins and are activated by phosphorylation changes', 'Lose their cyclins permanently', 'Bind DNA directly', 'Are degraded'], 0,
    'Cyclin destruction lets cells exit mitosis.'],
  ['Mixed revision — the Calvin cycle is autocatalytic because:', ['It regenerates and can build up its own CO₂ acceptor, RuBP', 'It needs no enzymes', 'It runs in the dark only', 'It makes oxygen'], 0,
    'Five of every six triose phosphates are recycled.'],
  ['Mixed revision — phytochrome exists as:', ['Pr and Pfr forms, switched by red and far-red light', 'Only one form', 'A blue-light receptor', 'A hormone'], 0,
    'Pfr is the active form for most responses.'],
  ['Mixed revision — the lac operon is switched on when:', ['Lactose (allolactose) inactivates the repressor', 'Glucose is high', 'The repressor binds the operator', 'Tryptophan is present'], 0,
    'Low glucose raises cAMP–CAP for full activation.'],
  ['Mixed revision — the chi-square test checks whether:', ['Observed numbers fit expected ratios', 'Two means differ', 'Two traits are correlated', 'Variance is normal'], 0,
    'E.g. testing a 3:1 Mendelian ratio.'],
  ['Mixed revision — hotspots of India include:', ['Himalaya, Indo-Burma, Western Ghats–Sri Lanka and Sundaland (Nicobar)', 'Thar desert and Deccan', 'Gangetic plain only', 'Central India only'], 0,
    'Hotspots combine high endemism with heavy habitat loss.']
] }
);
