/* Concept sets for Botany I — Morphogenesis and tissue culture. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Morphogenesis & Tissue Culture', w: 3, pyq: ['CSE-2025-B1-m24', 'IFoS-2023-B1-m23', 'CSE-2021-B1-m26', 'CSE-2020-B1-m24', 'CSE-2018-B1-m26', 'IFoS-2002-B1-m22', 'CSE-1985-B1-m23', 'IFoS-2019-B1-m24', 'CSE-2014-B1-m26', 'CSE-2009-B1-m24', 'CSE-1987-B1-m21', 'CSE-1989-B1-m38', 'CSE-1992-B1-m33', 'CSE-2012-B1-m25', 'CSE-2023-B1-m16', 'CSE-2023-B1-m25'], q: [
  ['Plant protoplasts are usually isolated by digesting cell walls with:', ['Cellulase and pectinase (macerozyme)', 'Trypsin and pepsin', 'Lysozyme', 'Amylase and lipase'], 0,
    'Cellulase "Onozuka" comes from *Trichoderma*; macerozyme from *Rhizopus*.'],
  ['The first enzymatic isolation of plant protoplasts was by:', ['Cocking (1960), from tomato root tips', 'Klercker (1892)', 'Haberlandt (1902)', 'Takebe (1971)'], 0,
    'Klercker\'s mechanical method gave very low yields.'],
  ['Mannitol or sorbitol is added to the enzyme solution to:', ['Act as an osmoticum and stop protoplasts bursting', 'Feed the cells', 'Digest the wall', 'Kill bacteria'], 0,
    'Typically 0.4–0.8 M.'],
  ['Viable protoplasts are commonly identified by staining with:', ['Fluorescein diacetate (FDA)', 'Iodine', 'Safranin', 'Crystal violet'], 0,
    'Live cells cleave FDA to fluorescent fluorescein; Evans blue stains dead cells.'],
  ['Protoplasts are purified from debris by:', ['Filtration and flotation or centrifugation on sucrose', 'Boiling', 'Freezing', 'Autoclaving'], 0,
    'Intact protoplasts float on a dense sucrose layer.'],
  ['Protoplast yield depends strongly on:', ['Age and condition of the source tissue, enzyme strength, time and osmoticum', 'Colour of the flask', 'Size of the laboratory', 'Season of the year only'], 0,
    'Young, fully expanded leaves from healthy plants give the best yields.'],
  ['After isolation, a cultured protoplast first:', ['Regenerates a new cell wall, then divides into microcolonies', 'Forms a shoot directly', 'Forms pollen', 'Dies always'], 0,
    'Colonies grow into callus that can regenerate plants.'],
  ['Whole plants were first regenerated from mesophyll protoplasts in:', ['Tobacco (Takebe and co-workers, 1971)', 'Rice', 'Wheat', 'Pea'], 0,
    'Solanaceae regenerate most easily.'],
  ['Protoplasts are useful for genetic transformation because they can take up DNA directly by:', ['PEG treatment or electroporation', 'Pollination', 'Grafting', 'Budding'], 0,
    'They are also used for somatic hybridisation and virus studies.'],
  ['Single cells can be isolated from intact leaves by:', ['Mechanical grinding or enzymatic maceration', 'Freezing the leaf', 'Drying the leaf', 'Burning'], 0,
    'Bergmann plating and nurse-callus (paper raft) methods help single cells divide.']
] },
{ p: 'B1', t: 'Morphogenesis & Tissue Culture', w: 3, pyq: ['IFoS-2022-B1-m25', 'IFoS-2020-B1-m24', 'CSE-2019-B1-m25', 'CSE-2002-B1-m19', 'CSE-2001-B1-m17', 'CSE-2000-B1-m19', 'CSE-1995-B1-m36', 'CSE-1990-B1-m47', 'IFoS-2019-B1-m26', 'IFoS-2017-B1-Q8c', 'IFoS-2013-B1-m37', 'IFoS-2011-B1-m30', 'CSE-2006-B1-m23', 'CSE-2005-B1-m20', 'CSE-2022-B1-m23', 'IFoS-2025-B1-m09', 'CSE-2018-B1-m25', 'IFoS-2021-B1-m27', 'CSE-2025-B1-m17', 'CSE-2015-B1-m03', 'CSE-2020-B1-m13', 'IFoS-2004-B1-m01', 'IFoS-2009-B1-m25', 'IFoS-2011-B1-m28', 'IFoS-2012-B1-m38', 'IFoS-2002-B1-m17', 'CSE-2012-B1-m16'], q: [
  ['The most widely used chemical for protoplast fusion is:', ['Polyethylene glycol (PEG)', 'Colchicine', 'Ethidium bromide', 'Mannitol'], 0,
    'Others: high pH with high Ca²⁺, sodium nitrate, and electrofusion.'],
  ['Electrofusion of protoplasts uses:', ['An alternating field to line cells up, then a short DC pulse to fuse them', 'Heat', 'Ultraviolet light', 'Ultrasound only'], 0,
    'It avoids toxic chemicals.'],
  ['A cybrid is formed when, after fusion:', ['The nucleus of one parent is lost but cytoplasm of both is kept', 'Both nuclei fuse', 'Both nuclei are lost', 'No cytoplasm mixes'], 0,
    'A true somatic hybrid has nuclei of both parents fused.'],
  ['Hybrid cells after fusion are often selected by:', ['Complementation, e.g. two different albino mutants giving green colonies', 'Size of the flask', 'Light colour', 'Adding more PEG'], 0,
    'Metabolic inhibitors, fluorescent tags and cell sorting are also used.'],
  ['An asymmetric somatic hybrid is made by:', ['Irradiating the donor protoplasts so only part of their genome is passed on', 'Fusing three protoplasts', 'Using only cytoplasm', 'Avoiding fusion'], 0,
    'Symmetric hybrids carry full genomes of both parents.'],
  ['The first interspecific somatic hybrid plant was:', ['*Nicotiana glauca* + *N. langsdorffii* (Carlson, 1972)', 'Pomato', 'Triticale', '*Raphanobrassica*'], 0,
    'The "pomato" (potato + tomato, Melchers 1978) was an intergeneric somatic hybrid.'],
  ['Cybrids are most useful for transferring:', ['Cytoplasmic male sterility and chloroplast-coded traits', 'Nuclear disease-resistance genes', 'Seed colour', 'Plant height'], 0,
    'E.g. CMS in *Brassica* and atrazine resistance via chloroplasts.'],
  ['Somatic hybrids can be confirmed by:', ['Isozymes, chromosome counts, DNA markers and GISH', 'Smell', 'Leaf colour alone', 'Seed weight'], 0,
    'Flow cytometry measures DNA content.'],
  ['A main advantage of somatic hybridisation is that it:', ['Overcomes sexual incompatibility between species', 'Needs flowers', 'Always gives fertile plants', 'Avoids tissue culture'], 0,
    'Many somatic hybrids are sterile or unstable.'],
  ['The fused cell carrying two separate nuclei is called a:', ['Heterokaryon', 'Synkaryon', 'Homokaryon', 'Cybrid'], 0,
    'When the nuclei fuse it becomes a synkaryon.']
] },
{ p: 'B1', t: 'Morphogenesis & Tissue Culture', w: 3, pyq: ['CSE-2023-B1-m26', 'CSE-2020-B1-m25', 'CSE-2017-B1-m21', 'CSE-2015-B1-m25', 'CSE-2012-B1-m24', 'CSE-2010-B1-m26', 'CSE-2011-B1-m16', 'IFoS-2006-B1-m24', 'CSE-1995-B1-m38', 'CSE-2024-B1-m26'], q: [
  ['The term "somaclonal variation" was coined by:', ['Larkin and Scowcroft (1981)', 'Haberlandt', 'Skoog and Miller', 'Murashige'], 0,
    'It is variation in plants regenerated from somatic cell cultures.'],
  ['A major cause of somaclonal variation is:', ['Chromosomal changes such as aneuploidy, polyploidy and rearrangements', 'Pollination', 'Seed dormancy', 'Photoperiod'], 0,
    'Point mutations, transposon activation and DNA methylation changes also contribute.'],
  ['Somaclonal variation increases with:', ['A long callus phase and high levels of 2,4-D', 'Axillary bud culture', 'Short culture periods', 'Low hormone levels'], 0,
    'Organised meristem cultures stay more stable.'],
  ['Somaclones can be identified by:', ['Morphology, cytology, isozymes and DNA markers such as RAPD or SSR', 'Weighing the flask', 'Leaf counting only', 'Smell'], 0,
    'The same markers test clonal fidelity of micropropagated plants.'],
  ['"Bio-13", a high-oil citronella variety from CIMAP, is an example of:', ['A somaclonal variant', 'A transgenic plant', 'A mutant from gamma rays', 'A haploid'], 0,
    'Somaclones have also given disease-resistant sugarcane and potato.'],
  ['Variation in plants regenerated from anther or pollen culture is called:', ['Gametoclonal variation', 'Somaclonal variation', 'Polyembryony', 'Apomixis'], 0,
    'It arises from gametic cells.'],
  ['For true-to-type micropropagation, somaclonal variation is avoided by:', ['Using axillary bud or meristem proliferation instead of callus', 'Using long callus cultures', 'Adding more 2,4-D', 'Using pollen'], 0,
    'In micropropagation the variation is unwanted.'],
  ['In vitro selection with somaclonal variation is used to obtain:', ['Lines tolerant to salt, herbicides or toxins', 'Seedless fruit', 'Haploids', 'Virus-free plants'], 0,
    'The selective agent is added to the culture medium.'],
  ['Somaclonal variation is valuable to breeders because it:', ['Creates new variation without crossing', 'Always gives uniform plants', 'Removes all mutations', 'Prevents disease'], 0,
    'It is especially useful in vegetatively propagated crops.'],
  ['Epigenetic somaclonal changes often involve:', ['Altered DNA methylation', 'Loss of all chromosomes', 'Plasmid uptake', 'Chloroplast loss'], 0,
    'Some such changes are unstable over generations.']
] },
{ p: 'B1', t: 'Morphogenesis & Tissue Culture', w: 2, pyq: ['CSE-2012-B1-m26', 'CSE-1986-B1-m28', 'CSE-1987-B1-m22', 'CSE-2009-B1-m25', 'IFoS-2011-B1-m29', 'CSE-2024-B1-m17', 'IFoS-2021-B1-m17'], q: [
  ['Polarity in plants means:', ['Differences in structure or behaviour at the two ends of an axis', 'Equal growth at both ends', 'Loss of cell walls', 'Random organ formation'], 0,
    'E.g. stem cuttings form shoots at the apical end and roots at the basal end (Vöchting).'],
  ['In the *Fucus* zygote, polarity is set by:', ['Light, with the rhizoid forming on the shaded side', 'Gravity only', 'Temperature only', 'Contact with sperm only'], 0,
    'Calcium currents and cytoskeleton fix the axis.'],
  ['Polar transport of auxin in shoots is mainly:', ['Basipetal, through PIN efflux carriers', 'Acropetal through xylem', 'Random', 'Through phloem only'], 0,
    'It sets up polarity in tissues and organs.'],
  ['Unequal (asymmetric) cell division is seen when:', ['A microspore forms a small generative cell and a large vegetative cell', 'A zygote forms two identical cells', 'Callus cells divide randomly', 'Root hairs grow'], 0,
    'Stomatal meristemoids also arise by unequal division.'],
  ['Changes that mark polarity induction in a cell include:', ['Shift of the nucleus and organelles and localised wall deposition', 'Loss of chloroplasts', 'Doubling of chromosomes', 'Cell death'], 0,
    'Cytoplasmic streaming changes also occur.'],
  ['Dorsiventral symmetry is typical of:', ['Most dicot leaves, with distinct upper and lower surfaces', 'Cylindrical stems', 'Roots', 'Radial fruits'], 0,
    'Radial symmetry is seen in stems and roots.'],
  ['Skoog and Miller (1957) showed that in tobacco callus a high cytokinin:auxin ratio leads to:', ['Shoot formation', 'Root formation', 'Callus death', 'Flowering'], 0,
    'A high auxin:cytokinin ratio favours roots; balanced levels give callus.'],
  ['Dedifferentiation is:', ['Return of mature cells to a dividing, meristematic state', 'Formation of organs from callus', 'Specialisation of cells', 'Cell death'], 0,
    'Redifferentiation is when such cells specialise again.'],
  ['Morphogenesis is:', ['The development of form and structure in an organism', 'Cell death', 'Seed storage', 'Pollination'], 0,
    'It results from growth and differentiation under genetic and hormonal control.'],
  ['Chlorosis differs from necrosis in that chlorosis is:', ['Yellowing due to loss of chlorophyll, while necrosis is death of tissue', 'Death of tissue', 'Wilting', 'Galling'], 0,
    'Both are symptoms of disease or nutrient deficiency.']
] },
{ p: 'B1', t: 'Morphogenesis & Tissue Culture', w: 3, pyq: ['CSE-2020-B1-m23', 'IFoS-2020-B1-m25', 'CSE-2014-B1-m25', 'CSE-2013-B1-m20', 'IFoS-2009-B1-m30', 'CSE-2007-B1-m23', 'IFoS-2004-B1-m24', 'CSE-2004-B1-m22', 'CSE-1999-B1-m19', 'CSE-1996-B1-m35', 'CSE-1993-B1-m36', 'CSE-1991-B1-m37', 'CSE-1987-B1-m20', 'CSE-1986-B1-m29', 'CSE-2024-B1-m27', 'IFoS-2025-B1-m08', 'IFoS-2013-B1-m36', 'CSE-2016-B1-m24', 'IFoS-2000-B1-m22', 'CSE-1993-B1-m33', 'IFoS-2000-B1-m12', 'IFoS-2007-B1-m11'], q: [
  ['The father of plant tissue culture, who first proposed cell totipotency, is:', ['Gottlieb Haberlandt (1902)', 'F. C. Steward', 'Murashige', 'Cocking'], 0,
    'He could not get his cultured cells to divide.'],
  ['MS medium (Murashige and Skoog, 1962) is known for its:', ['High levels of nitrate and ammonium salts', 'Lack of sugar', 'Lack of minerals', 'Use of soil'], 0,
    'It is the most widely used plant culture medium.'],
  ['Culture media are usually sterilised by:', ['Autoclaving at 121 °C and 15 psi for about 15–20 minutes', 'Boiling for one minute', 'UV light only', 'Freezing'], 0,
    'Explants are surface-sterilised with sodium hypochlorite or mercuric chloride.'],
  ['For callus induction, the auxin most often used is:', ['2,4-D', 'BAP', 'Kinetin', 'GA₃'], 0,
    'BAP and kinetin (cytokinins) promote shoots; IBA and NAA promote rooting.'],
  ['A cell suspension culture is:', ['Single cells and small clumps growing in agitated liquid medium', 'Callus on agar', 'A seed germinating on paper', 'A whole plant in soil'], 0,
    'Batch and continuous (chemostat, turbidostat) systems exist.'],
  ['The first secondary metabolite produced commercially by plant cell culture was:', ['Shikonin from *Lithospermum erythrorhizon*', 'Taxol', 'Quinine', 'Morphine'], 0,
    'Mitsui produced it in Japan in 1983.'],
  ['Somatic embryos differ from organogenic shoots in being:', ['Bipolar, with shoot and root poles and no vascular link to the explant', 'Unipolar', 'Always from pollen', 'Formed by fertilisation'], 0,
    'Somatic embryogenesis was first shown in carrot (Steward; Reinert, 1958).'],
  ['Crown-gall tumour cells can grow in culture:', ['Without added auxin and cytokinin', 'Only with high 2,4-D', 'Only in light', 'Never'], 0,
    'Their T-DNA genes make the hormones; habituated cells behave similarly.'],
  ['Plant material can be stored long-term by cryopreservation in:', ['Liquid nitrogen at −196 °C', 'A refrigerator at 4 °C', 'Dry ice at −20 °C', 'Room temperature'], 0,
    'Cryoprotectants such as DMSO and glycerol are used.'],
  ['Virus-free plants are obtained mainly by:', ['Meristem-tip culture, often with heat therapy', 'Callus culture', 'Protoplast fusion', 'Seed treatment'], 0,
    'Used for potato, banana, sugarcane and orchids.']
] },
{ p: 'B1', t: 'Morphogenesis & Tissue Culture', w: 2, pyq: ['CSE-2020-B1-m05', 'CSE-2022-B1-m04', 'CSE-2025-B1-m04'], q: [
  ['Embryo rescue is used mainly to:', ['Save hybrid embryos that would abort because the endosperm fails in wide crosses', 'Make seeds larger', 'Induce polyploidy', 'Store seed'], 0,
    'The immature embryo is cultured on a nutrient medium.'],
  ['The first interspecific hybrid obtained through embryo culture was:', ['*Linum perenne* × *L. austriacum* (Laibach, 1925)', 'Triticale', 'Pomato', '*Brassica napus*'], 0,
    'Hannig (1904) had first cultured crucifer embryos.'],
  ['Haploid barley is produced by the "bulbosum method", in which:', ['Chromosomes of *Hordeum bulbosum* are lost from the hybrid embryo, which is then rescued', 'Pollen is cultured', 'Seeds are irradiated', 'Protoplasts are fused'], 0,
    'Wheat × maize crosses work similarly.'],
  ['Very young (proembryo) stages are hard to culture because they:', ['Are heterotrophic and need complex media', 'Are autotrophic', 'Are too large', 'Lack cells'], 0,
    'Mature embryos grow on simple media.'],
  ['Coconut milk is added to some culture media because it:', ['Is liquid endosperm with cytokinins such as zeatin', 'Is a source of agar', 'Kills microbes', 'Adds colour'], 0,
    'It supports growth of young embryos and cells.'],
  ['Embryo culture can shorten the breeding cycle by:', ['Bypassing seed dormancy', 'Making plants flower later', 'Preventing germination', 'Increasing ploidy'], 0,
    'Used in *Iris* and many fruit trees.'],
  ['When embryos are too young to excise, breeders use:', ['Ovule (in ovulo) culture', 'Pollen culture', 'Callus culture', 'Protoplast culture'], 0,
    'The ovule tissues nourish the embryo.'],
  ['A disadvantage of embryo rescue is that:', ['It needs skill and sterile facilities, and very young embryos have low success', 'It always fails', 'It needs no laboratory', 'It produces only haploids'], 0,
    'Callus formation during rescue can also cause variation.'],
  ['Zygotic embryos differ from somatic embryos in that zygotic embryos:', ['Arise from fertilisation inside the seed', 'Arise from body cells in culture', 'Lack a shoot pole', 'Lack a root pole'], 0,
    'Somatic embryos can be encapsulated as synthetic seeds.'],
  ['Embryo rescue has been used to produce interspecific hybrids in:', ['Cotton, tomato and many fruit crops', 'Only mosses', 'Only ferns', 'Only algae'], 0,
    'It is a routine tool in wide hybridisation.']
] }
);
