/* Concept sets for Botany I — PYQs added from the newer Drive PYQ Map (CSE 2026) and the integrated Botany catalogue: microbes and the nitrogen cycle, geological time and fossils, classification and nomenclature, chemotaxonomy, disease management and quarantine, tissue-culture methods, anatomy and morphology terms, economic plants. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B1', t: 'Microbiology', w: 2, pyq: ['CSE-2026-B1-m03', 'CSE-2026-B1-m02', 'CSE-2011-B1-Q2b'], q: [
  ['Mineralisation (ammonification) of soil nitrogen is:', ['Microbial breakdown of organic nitrogen in residues and humus to ammonium', 'Fixation of N₂ gas into ammonia', 'Conversion of nitrate to N₂', 'Uptake of nitrate by roots'], 0,
    'It releases nitrogen locked in organic matter for plant use.'],
  ['Nitrification is carried out by:', ['*Nitrosomonas* (ammonium to nitrite) and *Nitrobacter* (nitrite to nitrate)', '*Rhizobium* and *Frankia*', '*Pseudomonas* under waterlogging', '*Azotobacter* only'], 0,
    'Both are chemoautotrophic bacteria that need oxygen.'],
  ['Denitrification returns nitrogen to the air when:', ['Bacteria such as *Pseudomonas* reduce nitrate to N₂ under low-oxygen conditions', 'Legumes fix nitrogen', 'Ammonium is oxidised', 'Lightning fixes nitrogen'], 0,
    'It causes nitrogen loss from waterlogged soils.'],
  ['Symbiotic nitrogen fixation in non-legumes such as *Casuarina* and *Alnus* is done by:', ['*Frankia*, an actinomycete (actinorhizal nodules)', '*Rhizobium*', '*Azotobacter*', '*Nitrobacter*'], 0,
    '*Rhizobium* and *Bradyrhizobium* nodulate legumes.'],
  ['Free-living (non-symbiotic) nitrogen fixers include:', ['*Azotobacter* (aerobic), *Clostridium* (anaerobic) and cyanobacteria such as *Nostoc*', '*Rhizobium* in nodules', '*Frankia* in nodules', '*Nitrosomonas*'], 0,
    'They add smaller amounts of nitrogen than symbiotic systems.'],
  ['Nitrogenase is protected from oxygen in legume nodules by:', ['Leghaemoglobin, which binds oxygen', 'Chlorophyll', 'Heterocysts', 'Cell-wall lignin'], 0,
    'In cyanobacteria, thick-walled heterocysts lacking photosystem II protect it.'],
  ['The *Azolla*–*Anabaena* symbiosis is used:', ['As a nitrogen biofertiliser in rice fields', 'To kill insects', 'As a fungicide', 'To make antibiotics'], 0,
    'The cyanobacterium lives in cavities of the fern\'s leaves.'],
  ['Residues with a high C:N ratio (above about 30) added to soil cause:', ['Temporary immobilisation of soil nitrogen by microbes', 'Immediate release of nitrate', 'Nitrogen fixation', 'Soil alkalinity'], 0,
    'Legume residues with low C:N ratio mineralise quickly.'],
  ['Phage therapy uses:', ['Lytic bacteriophages to kill disease-causing, often antibiotic-resistant, bacteria', 'Viruses to kill fungi', 'Antibiotics from fungi', 'Bacteria to kill viruses'], 0,
    'Bacteriophages were discovered by Twort (1915) and d\'Hérelle (1917); phages are also tools in molecular biology.'],
  ['Moulds are both boon and bane because:', ['*Penicillium* gives penicillin and *Aspergillus niger* citric acid, while *Aspergillus flavus* produces aflatoxins and moulds spoil food', 'They only cause disease', 'They are all edible', 'They fix nitrogen'], 0,
    'Moulds also make cheeses such as Roquefort (*Penicillium roqueforti*).']
] },
{ p: 'B1', t: 'Gymnosperms', w: 2, pyq: ['CSE-2026-B1-m11', 'CSE-2026-B1-m04', 'IFoS-2015-B1-Q4a', 'IFoS-2016-B1-Q5g'], q: [
  ['The geological time scale divides the Phanerozoic into the eras:', ['Palaeozoic, Mesozoic and Cenozoic', 'Archaean, Silurian and Jurassic', 'Cambrian, Devonian and Permian', 'Precambrian and Quaternary only'], 0,
    'The Precambrian came before, with only algae and bacteria.'],
  ['The earliest known vascular land plants, such as *Cooksonia*, appear in the:', ['Silurian period', 'Cretaceous period', 'Tertiary period', 'Permian period'], 0,
    'Early Devonian *Rhynia* is preserved in the Rhynie chert of Scotland.'],
  ['The Carboniferous is called the "Age of Pteridophytes" because:', ['Giant lycopods (*Lepidodendron*) and *Calamites* formed coal-forming swamp forests', 'Angiosperms dominated', 'Only algae existed', 'Gymnosperms first appeared then'], 0,
    'Seed ferns also flourished in the Carboniferous.'],
  ['Angiosperms first appear clearly in the fossil record in the:', ['Early Cretaceous', 'Silurian', 'Carboniferous', 'Pleistocene'], 0,
    'The Mesozoic was the "Age of Gymnosperms"; the Cenozoic is the "Age of Angiosperms".'],
  ['A petrifaction fossil differs from a compression in that a petrifaction:', ['Has its tissues replaced by minerals, preserving cell structure in three dimensions', 'Is a flattened carbon film', 'Is an imprint with no organic matter', 'Is a cast of a hollow mould'], 0,
    'Impressions keep only surface features; coal balls are petrified peat.'],
  ['Fossilisation is most likely when plant parts are:', ['Buried quickly in fine sediment with little oxygen', 'Left exposed on the soil surface', 'Eaten by animals', 'Burnt'], 0,
    'Lack of oxygen slows decay.'],
  ['The Birbal Sahni Institute of Palaeosciences is located at:', ['Lucknow', 'Kolkata', 'Pune', 'Dehradun'], 0,
    'Birbal Sahni described *Pentoxylon* from the Jurassic of the Rajmahal Hills.'],
  ['*Cycadeoidea* (Bennettitales) is notable for:', ['Bisexual, flower-like strobili', 'Free-floating leaves', 'Spores without walls', 'Being a living fossil'], 0,
    'Bennettitales flourished in the Mesozoic.'],
  ['*Cordaites* had:', ['Long strap-shaped leaves with parallel veins and loose cones', 'Pinnate leaves like cycads', 'Needle leaves in bundles', 'Fan-shaped leaves like *Ginkgo*'], 0,
    'Cordaitales were Palaeozoic relatives of conifers.'],
  ['Caytoniales were once thought to be angiosperm ancestors because:', ['Their ovules were enclosed in cup-like cupules', 'They had vessels', 'They had double fertilisation', 'They had true flowers with petals'], 0,
    'Hamshaw Thomas described *Caytonia* (1925); they are Mesozoic seed ferns.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: ['CSE-2026-B1-m12', 'CSE-2014-B1-Q5c', 'IFoS-2016-B1-Q6c', 'CSE-2014-B1-Q5e'], q: [
  ['The APG classification of angiosperms is based mainly on:', ['Molecular phylogeny (DNA sequences) and recognition of monophyletic groups', 'Number of stamens only', 'Habit (tree, shrub, herb)', 'Economic uses'], 0,
    'Genes such as *rbcL*, *atpB* and 18S rDNA were used.'],
  ['APG IV (2016) recognises about:', ['64 orders and 416 families', '20 orders and 100 families', '200 orders and 1,000 families', '7 orders and 50 families'], 0,
    'APG I appeared in 1998.'],
  ['In APG, the earliest-diverging angiosperms form the ANA grade:', ['*Amborella*, Nymphaeales and Austrobaileyales', 'Monocots and eudicots', 'Magnoliids only', 'Asterids and rosids'], 0,
    'Then come magnoliids, monocots and eudicots.'],
  ['In APG, monocots are:', ['A monophyletic clade branching after the ANA grade and magnoliids, before eudicots', 'Placed after all dicots as in Bentham and Hooker', 'Split among many dicot orders', 'The most primitive angiosperms'], 0,
    'Bentham and Hooker placed monocots at the end, after dicots and gymnosperms.'],
  ['"Dicots" are not a natural group in APG because:', ['Magnoliids and the ANA grade fall outside the monophyletic eudicots (with tricolpate pollen)', 'They have one cotyledon', 'They lack vessels', 'They are all trees'], 0,
    'Eudicots are defined by tricolpate pollen.'],
  ['In the taxonomic hierarchy, the standard ending of an order name is:', ['-ales, as in Rosales', '-aceae', '-oideae', '-eae'], 0,
    'Families end in -aceae, subfamilies in -oideae, tribes in -eae.'],
  ['The principal ranks of the taxonomic hierarchy, from highest to lowest, are:', ['Kingdom, division, class, order, family, genus, species', 'Species, genus, family, order, class, division, kingdom', 'Kingdom, family, order, class, genus, species', 'Division, kingdom, class, family, order, genus'], 0,
    'Secondary ranks like subfamily, tribe and section may be added.'],
  ['Typification means that every name is permanently attached to:', ['A type, usually a single herbarium specimen (holotype)', 'A geographical area', 'The author\'s description only', 'A family'], 0,
    'It fixes how a name is applied when taxa are split or merged.'],
  ['When the holotype is missing, a type selected later from the original material is a:', ['Lectotype', 'Isotype', 'Paratype', 'Neotype'], 0,
    'A neotype is chosen only when all original material is lost; an isotype duplicates the holotype.'],
  ['Under the principle of priority, the starting point for names of vascular plants is:', ['Linnaeus\'s *Species Plantarum*, 1 May 1753', 'Darwin\'s *Origin of Species*, 1859', 'Bentham and Hooker\'s *Genera Plantarum*, 1862', 'The ICN of 2018'], 0,
    'The earliest validly published name is generally the correct one.']
] },
{ p: 'B1', t: 'Angiosperm Taxonomy', w: 2, pyq: ['CSE-2026-B1-m05', 'CSE-2011-B1-Q7c', 'CSE-2013-B1-Q5a', 'CSE-2017-B1-m08'], q: [
  ['Chemotaxonomy is:', ['Use of chemical constituents of plants as evidence in classification', 'Classification by habit', 'Naming plants after chemists', 'Study of soil chemistry'], 0,
    'It complements morphology, anatomy and cytology.'],
  ['In chemotaxonomy, micromolecules differ from macromolecules in that micromolecules are:', ['Small secondary metabolites such as alkaloids, flavonoids and terpenoids', 'Proteins and nucleic acids', 'Polysaccharides only', 'Enzymes only'], 0,
    'Proteins and nucleic acids are "semantides" (information-carrying molecules) — a term of Zuckerkandl and Pauling.'],
  ['Betalain pigments are a classic chemotaxonomic marker of:', ['Most Caryophyllales, which lack anthocyanins', 'All monocots', 'Brassicaceae', 'Fabaceae'], 0,
    'Caryophyllaceae and Molluginaceae are exceptions with anthocyanins.'],
  ['Glucosinolates (mustard oils) support grouping:', ['Brassicaceae with Capparaceae in Brassicales', 'Poaceae with Cyperaceae', 'Fabaceae with Rosaceae', 'Solanaceae with Apiaceae'], 0,
    'Iridoids are markers of many asterids.'],
  ['Serological (immunological) taxonomy compares:', ['Proteins of different taxa through antigen–antibody reactions', 'Chromosome numbers', 'Leaf shapes', 'Pollen sizes'], 0,
    'Stronger cross-reaction suggests closer relationship.'],
  ['Alpha taxonomy refers to:', ['Describing and naming species, mainly from morphology and herbarium study', 'Building natural systems from all evidence', 'Molecular phylogeny', 'Numerical clustering'], 0,
    'Turrill (1938) introduced alpha and omega taxonomy.'],
  ['Beta taxonomy is:', ['Arranging species into a natural hierarchy of higher ranks using more evidence', 'Naming new species only', 'Collecting specimens', 'Chemical analysis only'], 0,
    'Omega taxonomy aims to synthesise all available data.'],
  ['Numerical taxonomy (Sneath and Sokal, 1963) uses:', ['Many equally weighted characters and computed similarity among operational taxonomic units (OTUs)', 'A single key character', 'Only DNA', 'Only fossils'], 0,
    'Results are shown as phenograms.'],
  ['Plant DNA barcoding commonly uses the chloroplast genes:', ['*rbcL* and *matK*', '*nifH* and *nodD*', '*cry1Ac* and *cry2Ab*', '*Rht1* and *Sd1*'], 0,
    'The CBOL Plant Working Group recommended them in 2009.'],
  ['A cytoplasmic hybrid (cybrid) differs from a somatic hybrid in that a cybrid:', ['Has the nucleus of one parent with cytoplasm from both', 'Has nuclei of both parents', 'Is produced sexually', 'Has no cytoplasm'], 0,
    'Cybrids are used to transfer cytoplasmic male sterility.']
] },
{ p: 'B1', t: 'Plant Pathology', w: 2, pyq: ['CSE-2026-B1-m09', 'CSE-2026-B1-m13', 'IFoS-2015-B1-Q1a', 'CSE-2011-B1-Q6d', 'IFoS-2013-B1-Q4c', 'CSE-2011-B1-Q4c'], q: [
  ['Charcoal rot of maize, with grey-black sclerotia in shredded pith, is caused by:', ['*Macrophomina phaseolina*', '*Puccinia sorghi*', '*Ustilago maydis*', '*Xanthomonas oryzae*'], 0,
    'Post-flowering stalk rots are also caused by *Fusarium*; *Pythium* causes a pre-flowering stalk rot.'],
  ['Maize stalk rots are favoured by:', ['Moisture stress after flowering, dense planting and high nitrogen with low potassium', 'Cool weather with balanced nutrition', 'Low plant density', 'Excess potassium'], 0,
    'Resistant hybrids, balanced fertilisation and rotation reduce them.'],
  ['Whetzel\'s principles of plant disease control are:', ['Exclusion, eradication, protection and immunisation (resistance)', 'Spraying, dusting and burning', 'Breeding only', 'Irrigation, drainage and tillage'], 0,
    'Avoidance and therapy were added later.'],
  ['Integrated disease management is criticised mainly because it:', ['Needs knowledge, monitoring and timely inputs that small farmers often lack', 'Uses no resistant varieties', 'Depends on one fungicide', 'Cannot reduce disease'], 0,
    'Its strength is durable, eco-friendly control combining resistance, cultural, biological and chemical methods.'],
  ['Plant quarantine is:', ['Legal restriction on movement of plants and plant material to prevent entry and spread of pests and pathogens', 'Spraying at harvest', 'Storing seed in cold rooms', 'Breeding resistant varieties'], 0,
    'India\'s first law was the Destructive Insects and Pests Act, 1914.'],
  ['A historic result of lax quarantine was:', ['Chestnut blight, brought from Asia to the USA, which wiped out the American chestnut', 'Green Revolution wheat', 'Bt cotton spread', 'Rubber in Kerala'], 0,
    'Coffee rust in Sri Lanka and *Parthenium* entry into India (with imported grain in the 1950s) are other examples.'],
  ['Disease forecasting models predict epidemics mainly from:', ['Weather data, host stage and inoculum levels', 'Market prices', 'Soil colour', 'Seed size'], 0,
    'Examples: BLITECAST (USA) and JHULSACAST (India) for potato late blight.'],
  ['Van der Plank described epidemic growth with the:', ['Apparent infection rate (r) of a logistic curve', 'Gene-for-gene model', 'Koch\'s postulates', 'Disease triangle only'], 0,
    'Monocyclic and polycyclic diseases grow differently.'],
  ['*Trichoderma* controls soil-borne pathogens through:', ['Mycoparasitism, antibiosis and competition', 'Nitrogen fixation', 'Producing auxins only', 'Killing insects'], 0,
    '*Pseudomonas fluorescens* acts through siderophores and induced resistance.'],
  ['Seed treatment with fungicides such as thiram or carbendazim protects against:', ['Seed-borne and soil-borne pathogens at germination', 'Air-borne rusts at flowering', 'Viruses carried by aphids', 'Insects in storage only'], 0,
    'It is a cheap protective step in disease management.']
] },
{ p: 'B1', t: 'Morphogenesis & Tissue Culture', w: 2, pyq: ['CSE-2026-B1-m18', 'CSE-2026-B1-m26', 'CSE-2011-B1-Q4b', 'CSE-2026-B1-m24', 'CSE-2026-B1-m27'], q: [
  ['A cell suspension culture is:', ['Single cells and small aggregates grown in agitated liquid medium, usually from friable callus', 'A callus on solid agar', 'A whole plant in soil', 'A pollen grain on stigma'], 0,
    'Flasks are shaken at about 100–120 rpm for aeration.'],
  ['The growth curve of a batch suspension culture shows:', ['Lag, exponential, linear, deceleration and stationary phases', 'Only a linear phase', 'Only death phase', 'Constant cell number'], 0,
    'Cells are subcultured before the stationary phase.'],
  ['Continuous suspension cultures differ from batch cultures in that:', ['Fresh medium is added and spent medium removed continuously, as in chemostats', 'Medium is never changed', 'Cells are grown on agar', 'No agitation is used'], 0,
    'They maintain cells in steady growth.'],
  ['A major use of plant cell suspension culture is:', ['Producing secondary metabolites in bioreactors, such as shikonin and paclitaxel', 'Making fertilisers', 'Grafting fruit trees', 'Seed certification'], 0,
    'Shikonin from *Lithospermum* was the first commercial product (Japan, 1983).'],
  ['Plant tissue culture media contain:', ['Mineral salts, sucrose (2–3%), vitamins, growth regulators and agar (0.6–0.8%) for solid media', 'Only water', 'Only sugar', 'Soil extract only'], 0,
    'MS medium (1962) is the most widely used.'],
  ['To control contamination in micropropagation:', ['Explants are surface-sterilised (ethanol, hypochlorite) and media autoclaved at 121 °C for 15–20 minutes under laminar flow', 'Media are boiled for one minute', 'Antibiotics replace all sterilisation', 'Cultures are kept in open air'], 0,
    'Instruments are flame-sterilised between uses.'],
  ['Browning of explants in culture is reduced by:', ['Activated charcoal, ascorbic acid or PVP, which counter phenolic oxidation', 'More light', 'Higher sugar', 'Removing agar'], 0,
    'Hyperhydricity (vitrification) is reduced by lowering cytokinin and improving ventilation.'],
  ['Micropropagation has been most successful commercially in:', ['Banana, sugarcane, potato and orchids', 'Wheat and rice grain production', 'Cotton fibre', 'Coconut only'], 0,
    'Its gains are mass, true-to-type, disease-free planting material.'],
  ['Totipotency is expressed in culture through:', ['Dedifferentiation to callus and redifferentiation into shoots, roots or somatic embryos', 'Only cell death', 'Seed dormancy', 'Pollination'], 0,
    'Regeneration depends on the auxin–cytokinin balance.'],
  ['Experimental embryology techniques include:', ['Embryo, ovule and endosperm culture and in vitro pollination', 'Only grafting', 'Only seed sowing', 'Only budding'], 0,
    'Endosperm culture can give triploid plants.']
] },
{ p: 'B1', t: 'Plant Anatomy', w: 1, pyq: ['CSE-2026-B1-m22', 'IFoS-2016-B1-Q5c', 'CSE-2014-B1-Q5d', 'CSE-2018-B1-Q1d', 'IFoS-2016-B1-Q5a', 'IFoS-2016-B1-Q5b', 'IFoS-2009-B1-Q5d'], q: [
  ['The components of xylem are:', ['Tracheids, vessels, xylem parenchyma and xylem fibres', 'Sieve tubes and companion cells', 'Cork and phelloderm', 'Guard cells and trichomes'], 0,
    'Vessels are absent in most gymnosperms but present in Gnetales.'],
  ['Tracheary elements are suited to water conduction because they are:', ['Dead at maturity with lignified, thickened walls', 'Living with dense cytoplasm', 'Made of cellulose only', 'Filled with starch'], 0,
    'Xylem also gives mechanical support.'],
  ['A cladode differs from a phyllode in that a cladode is:', ['A flattened green stem of limited growth (e.g. *Ruscus*, *Asparagus*), while a phyllode is a flattened petiole (e.g. Australian *Acacia*)', 'A modified root', 'A modified flower', 'A leaf tendril'], 0,
    'A phylloclade (e.g. *Opuntia*) is a flattened stem of unlimited growth.'],
  ['Eccentric growth rings form when:', ['Reaction wood develops more on one side, as compression wood on the lower side of conifer branches', 'Growth is equal on all sides', 'Trees are in deep shade only', 'Roots are waterlogged'], 0,
    'Annual rings result from early (spring) and late wood.'],
  ['A gynophore is:', ['A stalk raising the ovary above the other floral parts, as in *Capparis* and the groundnut "peg"', 'A stalk bearing stamens', 'A leaf base', 'A modified root'], 0,
    'An androphore raises the stamens; *Cleome* (*Gynandropsis*) has both.'],
  ['Sunken stomata in xerophytes such as *Nerium*:', ['Reduce transpiration by keeping humid air in the pit', 'Increase water loss', 'Absorb water from air', 'Make chlorophyll'], 0,
    'Hairs in stomatal crypts add to the effect.'],
  ['A spadix differs from a spike in having:', ['A fleshy axis, usually enclosed by a large bract (spathe)', 'Stalked flowers', 'A flat head', 'No bracts ever'], 0,
    'It is typical of Araceae (e.g. *Colocasia*).'],
  ['In *Arabidopsis*, embryo development passes through the stages:', ['Globular, heart, torpedo and cotyledonary', 'Spore, protonema and gametophore', 'Coleoptile and mesocotyl only', 'Tetrad and dyad'], 0,
    'The zygote divides into an apical cell (embryo) and a basal cell (suspensor).'],
  ['In red algae, the cystocarp is:', ['The post-fertilisation structure of gonimoblast filaments and carposporangia, often enclosed by a pericarp', 'A male sex organ', 'An asexual spore', 'A holdfast'], 0,
    'In *Coleochaete*, a "spermocarp" is the zygote surrounded by a layer of sterile cells.'],
  ['Isokont zoospores differ from heterokont ones in having:', ['Flagella of equal length, as in *Chlamydomonas*', 'Flagella of unequal length', 'No flagella', 'Many flagella in a ring'], 0,
    'Heterokont flagella mark Xanthophyceae and brown algae.']
] },
{ p: 'B1', t: 'Economic Botany & Plant Resources', w: 1, pyq: ['CSE-2011-B1-Q8a', 'CSE-2026-B1-m17', 'CSE-2026-B1-m19'], q: [
  ['Energy plantations are:', ['Fast-growing trees and shrubs grown for fuelwood and biomass energy, such as *Leucaena*, *Casuarina* and *Prosopis*', 'Solar farms', 'Sugarcane for sugar only', 'Ornamental gardens'], 0,
    'They reduce pressure on natural forests.'],
  ['"Petro-crops", proposed by Melvin Calvin, are plants such as:', ['*Euphorbia lathyris* and *E. tirucalli*, whose latex contains hydrocarbons', 'Rice and wheat', 'Tea and coffee', 'Rose and jasmine'], 0,
    'Non-edible oilseeds such as *Jatropha* and *Pongamia* are biodiesel sources.'],
  ['The botanical name of pearl millet is:', ['*Pennisetum glaucum* (now *Cenchrus americanus*), Poaceae', '*Eleusine coracana*', '*Sorghum bicolor*', '*Setaria italica*'], 0,
    '*Eleusine coracana* is finger millet.'],
  ['Flax, source of linen fibre and linseed oil, is:', ['*Linum usitatissimum*, Linaceae', '*Corchorus capsularis*', '*Hibiscus cannabinus*', '*Crotalaria juncea*'], 0,
    'Jute is *Corchorus*; sunn hemp is *Crotalaria*.'],
  ['Pomegranate is *Punica granatum*, placed in APG in the family:', ['Lythraceae', 'Rosaceae', 'Myrtaceae', 'Rutaceae'], 0,
    'It was earlier kept in its own family, Punicaceae.'],
  ['Bottle gourd is:', ['*Lagenaria siceraria*, Cucurbitaceae', '*Luffa cylindrica*', '*Momordica charantia*', '*Benincasa hispida*'], 0,
    'Bitter gourd is *Momordica*; ash gourd is *Benincasa*.'],
  ['Chickpea is:', ['*Cicer arietinum*, Fabaceae', '*Cajanus cajan*', '*Vigna radiata*', '*Lens culinaris*'], 0,
    'Pigeon pea is *Cajanus*, mung bean *Vigna radiata*, lentil *Lens*.'],
  ['Plant domestication began about 10,000–12,000 years ago in the:', ['Fertile Crescent of West Asia, with wheat, barley, lentil and pea', 'Amazon with rubber', 'Sahara with dates only', 'Arctic'], 0,
    'Other independent centres include China, Mesoamerica and the Andes.'],
  ['The "domestication syndrome" includes:', ['Non-shattering seeds, loss of dormancy, larger seeds and less bitterness', 'More thorns and toxins', 'Smaller seeds', 'Stronger seed dispersal'], 0,
    'These traits suit harvesting and cultivation by humans.'],
  ['Vavilov\'s centres of origin are recognised by:', ['High diversity of a crop and its wild relatives', 'The largest area under the crop today', 'The highest yields', 'The coldest climate'], 0,
    'He proposed eight main centres, including the Indian (Hindustan) centre.']
] }
);
