/* Concept sets for Agriculture I — Soil fertility, manures, fertilisers and biofertilisers. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: ['CSE-2018-A1-m19', 'IFoS-2016-A1-m27', 'CSE-2013-A1-m21', 'CSE-1999-A1-m13', 'CSE-2021-A1-m23', 'CSE-1989-A1-m15', 'CSE-2002-A1-m12', 'CSE-1992-A1-m10', 'IFoS-2001-A1-m05', 'CSE-1991-A1-m11', 'CSE-2023-A1-m23', 'IFoS-2016-A1-m28', 'CSE-1995-A1-m12', 'CSE-1992-A1-m12', 'IFoS-2009-A1-m01', 'IFoS-2000-A1-m02', 'IFoS-2001-A1-m02', 'CSE-2010-A1-m10', 'IFoS-2023-A1-m26', 'IFoS-2016-A1-m08'], q: [
  ['*Rhizobium* is a:', ['Symbiotic nitrogen fixer in legume root nodules', 'Free-living aerobic nitrogen fixer', 'Phosphate solubiliser only', 'Fungus'], 0,
    'Strains are host-specific (cross-inoculation groups).'],
  ['A free-living aerobic nitrogen-fixing biofertiliser is:', ['*Azotobacter*', '*Rhizobium*', '*Glomus*', '*Clostridium*'], 0,
    '*Clostridium* is anaerobic; *Beijerinckia* suits acid soils.'],
  ['*Azospirillum* is mainly recommended for:', ['Cereals and millets as an associative nitrogen fixer', 'Legumes only', 'Sugarcane setts only', 'Rice nurseries only'], 0,
    'It lives in and around the roots.'],
  ['The endophytic nitrogen fixer of sugarcane is:', ['*Gluconacetobacter* (*Acetobacter*) *diazotrophicus*', '*Azotobacter*', '*Frankia*', '*Anabaena*'], 0,
    'It lives inside stems and roots.'],
  ['Stem nodules on *Sesbania rostrata* are formed by:', ['*Azorhizobium caulinodans*', '*Bradyrhizobium japonicum*', '*Frankia*', '*Nostoc*'], 0,
    'It is valued as a green manure for rice.'],
  ['Phosphate-solubilising biofertilisers include:', ['*Pseudomonas striata* and *Bacillus megaterium*', '*Rhizobium* and *Azotobacter*', '*Trichoderma* and *Beauveria*', '*Anabaena* and *Nostoc*'], 0,
    'Mycorrhizal fungi such as *Glomus* mobilise phosphorus.'],
  ['VA mycorrhizae (arbuscular mycorrhizae) mainly help plants absorb:', ['Phosphorus and water', 'Nitrogen gas', 'Carbon dioxide', 'Sodium'], 0,
    'They form arbuscules and vesicles inside root cortical cells.'],
  ['A major constraint in popularising biofertilisers is:', ['Poor-quality inoculants with short shelf life', 'Too high nutrient content', 'They are toxic', 'They are banned'], 0,
    'Liquid formulations and quality control help.'],
  ['For seed inoculation, biofertiliser is usually mixed with:', ['A sticky slurry (e.g. jaggery solution) and the seeds dried in shade before sowing', 'Hot water', 'Pesticide at high dose', 'Urea solution'], 0,
    'Direct sunlight kills the bacteria.'],
  ['A microbial consortium biofertiliser combines:', ['Nitrogen fixers with phosphate- and potash-solubilising microbes', 'Only one strain', 'Only fungicides', 'Chemical fertilisers'], 0,
    'It supplies several nutrients at once.']
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: ['IFoS-2010-A1-m16', 'IFoS-2002-A1-m06', 'IFoS-2015-A1-m15', 'CSE-2020-A1-m22', 'CSE-2008-A1-m07', 'IFoS-2023-A1-m23', 'IFoS-2005-A1-m06', 'CSE-2018-A1-m20', 'CSE-2015-A1-m22'], q: [
  ['Organic materials with a C:N ratio above about 30:1, such as cereal straw, tend to:', ['Immobilise soil nitrogen while they decompose', 'Release nitrogen quickly', 'Raise soil pH sharply', 'Fix nitrogen'], 0,
    'Soil humus has a C:N of about 10–12:1.'],
  ['Well-rotted farmyard manure typically contains about:', ['0.5% N, 0.2% P₂O₅ and 0.5% K₂O', '5% N and 5% P', '46% N', '18% N and 46% P₂O₅'], 0,
    'It is a bulky organic manure.'],
  ['A concentrated organic manure is:', ['Oilcake such as neem cake', 'Farmyard manure', 'Compost', 'Green manure'], 0,
    'Oilcakes contain more nutrients per unit weight.'],
  ['Green manuring in situ uses crops such as:', ['Dhaincha (*Sesbania aculeata*) and sunn hemp (*Crotalaria juncea*)', '*Gliricidia* leaves brought from outside', 'Rice straw', 'Wheat'], 0,
    'Green-leaf manuring brings leaves from trees such as *Gliricidia* and *Pongamia*.'],
  ['Brown manuring in rice is:', ['Sowing *Sesbania* with rice and killing it with 2,4-D at about 25–30 days', 'Burning residue', 'Applying FYM', 'Ploughing in rice straw'], 0,
    'It supplies N and smothers weeds without puddling in.'],
  ['The Indore method of composting was developed by:', ['Albert Howard', 'Acharya', 'Narayan Deotao Pandharipande', 'Liebig'], 0,
    'Bangalore (Acharya) and NADEP are other methods.'],
  ['The earthworm species most used for vermicomposting is:', ['*Eisenia fetida*', '*Pheretima posthuma*', '*Lumbricus terrestris*', '*Megascolex*'], 0,
    'Vermicompost is rich in available nutrients and growth substances.'],
  ['An in-situ option for managing paddy straw is:', ['Sowing wheat with a Happy Seeder into the retained straw', 'Burning it', 'Selling it to power plants', 'Baling and removing it'], 0,
    'Microbial decomposers (e.g. PUSA decomposer) also help.'],
  ['An ex-situ use of rice straw is:', ['Biomass power, mushroom culture or biochar', 'Mulching in the same field', 'Incorporation by rotavator', 'Happy Seeder sowing'], 0,
    'Ex situ means removed from the field.'],
  ['Humus improves soil fertility because it:', ['Has a high cation exchange capacity and stores nutrients and water', 'Is chemically inert', 'Lowers water holding', 'Makes soil compact'], 0,
    'It also improves structure and microbial activity.']
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 3, pyq: ['IFoS-2019-A1-m21', 'CSE-2015-A1-m19', 'IFoS-2009-A1-m15', 'CSE-1997-A1-m07', 'CSE-2014-A1-m22', 'IFoS-2004-A1-m10', 'IFoS-2023-A1-m25', 'CSE-1991-A1-m06', 'IFoS-2022-A1-m24'], q: [
  ['Urea contains about:', ['46% N', '20.6% N', '82% N', '16% N'], 0,
    'Ammonium sulphate has 20.6% N and 24% S; anhydrous ammonia 82% N.'],
  ['DAP (diammonium phosphate) has a grade of:', ['18-46-0', '46-0-0', '10-26-26', '0-0-60'], 0,
    'MOP is 0-0-60; SSP has 16% P₂O₅ and about 12% S.'],
  ['Nitrogen use efficiency of applied fertiliser in Indian crops is often only:', ['30–50%', '90–100%', '70–80%', '5%'], 0,
    'Losses come from volatilisation, leaching, denitrification and runoff.'],
  ['Neem-coated urea improves efficiency mainly by:', ['Slowing nitrification of the released ammonium', 'Adding phosphorus', 'Increasing volatilisation', 'Raising soil pH'], 0,
    'All urea in India has been neem-coated since 2015.'],
  ['A slow-release nitrogen fertiliser is:', ['Sulphur-coated urea', 'Ammonium nitrate', 'Calcium ammonium nitrate', 'Anhydrous ammonia'], 0,
    'IBDU and polymer-coated urea are others.'],
  ['Deep placement of urea supergranules in rice reduces:', ['Ammonia volatilisation and runoff losses', 'Root growth', 'Yield', 'Tillering'], 0,
    'The N stays in the reduced soil layer.'],
  ['A nitrification inhibitor is:', ['Dicyandiamide (DCD)', 'Urease', 'Gypsum', 'Lime'], 0,
    'Nitrapyrin is another.'],
  ['Agronomic efficiency of a nutrient is:', ['Extra yield per unit of nutrient applied', 'Nutrient content of the crop', 'Fertiliser cost per hectare', 'Total yield'], 0,
    'Apparent recovery efficiency is the fraction of applied nutrient taken up.'],
  ['IFFCO\'s nano urea, launched in 2021, is applied as:', ['A liquid foliar spray in small doses', 'Granules in the soil', 'A seed coating only', 'An injection into stems'], 0,
    'Field evidence on its replacement value is still debated.'],
  ['In alkaline soils, surface-applied urea loses nitrogen mainly as:', ['Ammonia gas after hydrolysis by urease', 'Nitrate leaching only', 'N₂O only', 'Organic nitrogen'], 0,
    'Incorporating urea into the soil reduces this loss.']
] },
{ p: 'A1', t: 'Soil Fertility, Fertilisers & INM', w: 2, pyq: ['CSE-1998-A1-m05', 'CSE-1990-A1-m08', 'CSE-2010-A1-m12', 'IFoS-2015-A1-m04', 'CSE-2024-A1-m24', 'IFoS-2014-A1-m30', 'IFoS-2001-A1-m06', 'IFoS-2022-A1-m25', 'CSE-2019-A1-m25'], q: [
  ['Potassium is called the "quality element" because it:', ['Improves grain filling, fruit quality and disease and stress tolerance', 'Is part of chlorophyll', 'Fixes nitrogen', 'Is part of proteins'], 0,
    'It activates enzymes and controls stomata and osmotic balance.'],
  ['Potassium deficiency typically shows as:', ['Scorching of the margins of older leaves', 'Yellowing of young leaves only', 'Purple stems', 'Rosetting of shoots'], 0,
    'K is mobile, so older leaves show it first.'],
  ['Potassium becomes "fixed" (non-exchangeable) mainly in:', ['Interlayers of 2:1 clays such as illite', 'Organic matter', 'Sand grains', 'Kaolinite only'], 0,
    'Water-soluble and exchangeable K are readily available.'],
  ['Gypsum is applied to groundnut at pegging mainly to supply:', ['Calcium and sulphur for pod and kernel development', 'Nitrogen', 'Phosphorus', 'Zinc'], 0,
    'It reduces unfilled pods (pops).'],
  ['Soil test crop response (STCR) recommendations are based on:', ['Targeted-yield equations using soil test values and fertiliser efficiency', 'A fixed blanket dose', 'Crop price only', 'Rainfall only'], 0,
    'Ramamoorthy developed the targeted-yield approach.'],
  ['Available nitrogen in soil testing is commonly estimated by the:', ['Alkaline permanganate method (Subbiah and Asija)', 'Olsen method', 'Ammonium acetate method', 'Bray method'], 0,
    'Olsen extracts P in neutral–alkaline soils; Bray in acid soils; ammonium acetate extracts K.'],
  ['Sulphur is especially important for:', ['Oilseeds and pulses, for oil and protein quality', 'Sugarcane only', 'Cotton fibre only', 'Tea only'], 0,
    'S deficiency has grown with use of S-free fertilisers like urea and DAP.'],
  ['The capacity of a soil to produce food depends on:', ['Its fertility, physical condition, water supply and management', 'Its colour only', 'Its depth only', 'Its location only'], 0,
    'This is the idea of soil productivity and soil health.'],
  ['Secondary nutrients are:', ['Calcium, magnesium and sulphur', 'Nitrogen, phosphorus and potassium', 'Iron, zinc and copper', 'Boron and molybdenum'], 0,
    'Micronutrients are needed in still smaller amounts.'],
  ['Soil health cards report:', ['Macro- and micronutrient status, pH, EC and organic carbon with fertiliser advice', 'Only crop prices', 'Only rainfall', 'Only soil colour'], 0,
    'They support balanced, site-specific fertiliser use.']
] }
);
