/* Concept sets for Botany II — Cell biology. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B2', t: 'Cell Biology', w: 3, pyq: ['CSE-2001-B2-m02', 'CSE-2000-B2-m01', 'CSE-2003-B2-m02', 'CSE-1994-B2-m02', 'CSE-2015-B2-m01', 'CSE-1989-B2-m02', 'IFoS-2022-B2-m05', 'IFoS-2020-B2-m04', 'IFoS-2000-B2-m02', 'IFoS-2013-B2-m02', 'IFoS-2013-B2-m01', 'IFoS-2011-B2-m04', 'CSE-1986-B2-m05'], q: [
  ['The fluid mosaic model of membranes was proposed by:', ['Singer and Nicolson (1972)', 'Danielli and Davson (1935)', 'Robertson (1959)', 'Gorter and Grendel (1925)'], 0,
    'Proteins float in a fluid lipid bilayer.'],
  ['Robertson\'s "unit membrane" model described membranes as:', ['A trilaminar structure about 7.5 nm thick', 'A single protein layer', 'A lipid monolayer', 'A carbohydrate mesh'], 0,
    'Danielli–Davson had earlier proposed a protein–lipid–protein sandwich.'],
  ['Galactolipids (MGDG and DGDG) are the main lipids of:', ['Thylakoid membranes', 'The plasma membrane of animals', 'Mitochondrial inner membrane', 'Myelin'], 0,
    'Phospholipids dominate most other membranes.'],
  ['The main sterols of plant membranes are:', ['Sitosterol and stigmasterol', 'Cholesterol only', 'Ergosterol', 'Lanosterol'], 0,
    'Fungi use ergosterol.'],
  ['Intrinsic (integral) membrane proteins differ from extrinsic ones in that they:', ['Span or sit within the bilayer and come out only with detergents', 'Are loosely bound and removed by salt washes', 'Lie only on the outer surface', 'Are carbohydrates'], 0,
    'Peripheral proteins are held by ionic links to lipid heads or other proteins.'],
  ['Membrane fluidity rises when membranes contain more:', ['Unsaturated fatty acids', 'Saturated fatty acids', 'Long straight chains', 'Cholesterol at high temperature'], 0,
    'Cold-hardy plants increase fatty-acid desaturation.'],
  ['Liposomes are:', ['Artificial phospholipid vesicles used to deliver drugs or DNA', 'Lysosomes of plants', 'Oil bodies of seeds', 'Ribosome clusters'], 0,
    'Lipid-mediated DNA delivery is called lipofection.'],
  ['Freeze-fracture electron microscopy supported the fluid mosaic model by showing:', ['Particles (proteins) inside the split bilayer', 'Only smooth lipid faces', 'Three protein layers', 'Holes in the membrane'], 0,
    'The bilayer splits along its middle.'],
  ['In a lipid bilayer, movement of lipids from one leaflet to the other (flip-flop) is:', ['Very slow unless helped by flippases', 'Faster than lateral diffusion', 'Impossible', 'Driven by light'], 0,
    'Lateral diffusion within one leaflet is fast.'],
  ['Lipid rafts are:', ['Sterol- and sphingolipid-rich microdomains that gather certain proteins', 'Floating oil droplets', 'Cell wall pieces', 'Ribosomes on ER'], 0,
    'They act as platforms for signalling.']
] },
{ p: 'B2', t: 'Cell Biology', w: 3, pyq: ['CSE-2018-B2-m03', 'CSE-2010-B2-m04', 'CSE-1987-B2-m04', 'IFoS-2023-B2-m06', 'CSE-2022-B2-m04', 'CSE-1989-B2-m01', 'CSE-1988-B2-m01'], q: [
  ['The endosymbiotic theory was championed by:', ['Lynn Margulis', 'Robert Hooke', 'Rudolf Virchow', 'Gregor Mendel'], 0,
    'Mitochondria came from α-proteobacteria and chloroplasts from cyanobacteria.'],
  ['Which supports a bacterial origin of mitochondria and chloroplasts?', ['Circular DNA, 70S ribosomes and division by fission', 'Absence of DNA', '80S ribosomes', 'Single membrane'], 0,
    'Their ribosomes are also sensitive to chloramphenicol.'],
  ['Mitochondria and chloroplasts are called semi-autonomous because:', ['They have their own DNA and ribosomes but import most of their proteins', 'They make all their own proteins', 'They have no DNA', 'They live outside cells'], 0,
    'Imported proteins carry targeting sequences recognised by TOM/TIM and TOC/TIC complexes.'],
  ['The large subunit of RuBisCO is coded by:', ['Chloroplast DNA (*rbcL*)', 'Nuclear DNA (*rbcS*)', 'Mitochondrial DNA', 'Plasmids'], 0,
    'The small subunit is nuclear-coded and imported.'],
  ['Plant mitochondrial genomes are notable for being:', ['Large and variable, with frequent recombination', 'Smaller than animal mtDNA', 'Linear and tiny', 'Absent'], 0,
    'They range from about 200 kb to over 2,000 kb; animal mtDNA is about 16 kb.'],
  ['Most plastid genomes are about:', ['120–160 kb with a large inverted repeat', '16 kb', '5 Mb', '1 kb'], 0,
    'They code mainly photosynthesis and gene-expression proteins.'],
  ['Chloroplasts with three or four envelope membranes, as in *Euglena* or brown algae, arose by:', ['Secondary endosymbiosis of a eukaryotic alga', 'Primary endosymbiosis', 'Fusion of mitochondria', 'Folding of the plasma membrane'], 0,
    'Primary plastids of green and red algae have two membranes.'],
  ['Over evolution, many organelle genes have:', ['Moved to the nucleus (endosymbiotic gene transfer)', 'Been gained from viruses only', 'Stayed exactly as in bacteria', 'Moved to ribosomes'], 0,
    'That is why most organelle proteins are nuclear-coded.'],
  ['In most angiosperms, plastids and mitochondria are inherited:', ['Maternally, through the egg cytoplasm', 'Paternally only', 'Equally from both parents', 'Not at all'], 0,
    'Conifers often pass plastids through the father.'],
  ['Mitochondria and chloroplasts resemble each other in having:', ['Double membranes, own DNA and ATP synthase driven by a proton gradient', 'Chlorophyll', 'Cristae and grana together', 'Single membranes'], 0,
    'Both make ATP by chemiosmosis.']
] },
{ p: 'B2', t: 'Cell Biology', w: 3, pyq: ['CSE-2022-B2-m05', 'CSE-2019-B2-m09', 'CSE-2020-B2-m07', 'CSE-2010-B2-m05', 'CSE-1990-B2-m01', 'CSE-2023-B2-m05', 'IFoS-2021-B2-m02', 'IFoS-2020-B2-m01', 'IFoS-2022-B2-m04', 'IFoS-2023-B2-m02', 'IFoS-2000-B2-m01', 'CSE-2014-B2-m05', 'CSE-2013-B2-m03', 'IFoS-2014-B2-m01', 'IFoS-2021-B2-m05', 'CSE-2012-B2-m01', 'IFoS-2012-B2-m03', 'CSE-1986-B2-m14', 'CSE-2015-B2-m10', 'IFoS-2004-B2-m01', 'IFoS-2007-B2-m02', 'IFoS-2003-B2-m07'], q: [
  ['Peroxisomes contain:', ['Oxidases that make H₂O₂ and catalase that breaks it down', 'Acid hydrolases only', 'Chlorophyll', 'DNA and ribosomes'], 0,
    'They have a single membrane.'],
  ['In photorespiration, peroxisomes convert:', ['Glycolate to glyoxylate and then glycine', 'Glucose to pyruvate', 'Fatty acids to sucrose', 'Nitrate to ammonia'], 0,
    'The pathway runs through chloroplast, peroxisome and mitochondrion.'],
  ['Glyoxysomes of germinating oil seeds contain the enzymes:', ['Isocitrate lyase and malate synthase', 'RuBisCO and PEP carboxylase', 'Nitrogenase', 'Amylase and invertase'], 0,
    'The glyoxylate cycle lets fats be turned into sugars.'],
  ['Peroxisomal matrix proteins are imported using:', ['A C-terminal targeting signal (PTS1, e.g. SKL) and peroxin proteins', 'A signal peptide into the ER only', 'Ribosomes inside peroxisomes', 'Their own DNA'], 0,
    'Peroxisomes grow and divide; they lack DNA.'],
  ['Lysosomes were discovered by:', ['Christian de Duve (1955)', 'Camillo Golgi', 'Palade', 'Robert Brown'], 0,
    'They hold acid hydrolases working at about pH 5.'],
  ['In plant cells, the main lytic (lysosome-like) compartment is the:', ['Vacuole', 'Nucleus', 'Chloroplast', 'Golgi'], 0,
    'It has acid hydrolases and digests material by autophagy.'],
  ['The tonoplast keeps the vacuole acidic using:', ['V-type ATPases and pyrophosphatases', 'Photosystem II', 'Aquaporins only', 'Cellulose synthase'], 0,
    'Vacuoles also store pigments, ions and defence chemicals and maintain turgor.'],
  ['Cytoplasmic ribosomes of eukaryotes are 80S, while those of plastids and mitochondria are:', ['70S', '60S', '90S', '40S'], 0,
    'The 80S ribosome has 60S and 40S subunits; 18S rRNA is in the small subunit.'],
  ['Ribosomal RNA genes cluster at the:', ['Nucleolar organiser region, forming the nucleolus', 'Centromere', 'Telomere', 'Plasma membrane'], 0,
    'Ribosome subunits are assembled in the nucleolus.'],
  ['Programmed cell death in plants occurs during:', ['Xylem vessel formation and the hypersensitive response', 'Seed imbibition only', 'Stomatal opening', 'Photosynthesis'], 0,
    'Tapetum breakdown is another example; metacaspases and vacuolar enzymes take part.']
] },
{ p: 'B2', t: 'Cell Biology', w: 2, pyq: ['CSE-2023-B2-m03', 'CSE-2025-B2-m02', 'CSE-2020-B2-m05', 'IFoS-2016-B2-m05', 'IFoS-2015-B2-m02', 'CSE-2018-B2-m06', 'CSE-1988-B2-m02', 'IFoS-2023-B2-m01', 'CSE-1996-B2-m01', 'IFoS-2000-B2-m01', 'IFoS-2012-B2-m01', 'IFoS-2003-B2-m04', 'CSE-2011-B2-m08', 'IFoS-2007-B2-m03', 'CSE-1988-B2-m04', 'CSE-2026-B2-m09', 'CSE-2026-B2-m10'], q: [
  ['Microtubules are made of:', ['α- and β-tubulin dimers forming 13 protofilaments, about 25 nm wide', 'Actin', 'Keratin', 'Cellulose'], 0,
    'They show dynamic instability — rapid growth and shrinkage.'],
  ['Cortical microtubules in plant cells control:', ['The direction in which cellulose microfibrils are laid down', 'Chlorophyll synthesis', 'DNA replication', 'Starch breakdown'], 0,
    'Cellulose synthase complexes move along them.'],
  ['The preprophase band of microtubules marks:', ['The future site of the new cell wall', 'The nucleolus', 'The centromere', 'The chloroplast'], 0,
    'The phragmoplast later guides cell plate formation.'],
  ['Cytoplasmic streaming in plant cells is driven by:', ['Myosin moving along actin filaments', 'Microtubules and dynein', 'Intermediate filaments', 'Cell wall growth'], 0,
    'Angiosperms lack dynein.'],
  ['Which protein severs microtubules?', ['Katanin', 'MAP65', 'Tubulin', 'Actin'], 0,
    'MAP65 bundles microtubules; kinesins are motors.'],
  ['The nuclear pore complex is built of proteins called:', ['Nucleoporins, many with FG repeats', 'Histones', 'Tubulins', 'Lamins only'], 0,
    'It has eightfold symmetry.'],
  ['Large proteins enter the nucleus when they carry:', ['A nuclear localisation signal recognised by importins, powered by the Ran GTPase', 'A signal peptide', 'A transit peptide', 'A KDEL tag'], 0,
    'Exportins carry cargo out.'],
  ['Plasmodesmal opening is narrowed by deposition of:', ['Callose around the neck', 'Lignin', 'Suberin', 'Cutin'], 0,
    'The central desmotubule is continuous with the ER.'],
  ['In differential centrifugation of a homogenate, the first (low-speed) pellet is mainly:', ['Nuclei and unbroken cells', 'Ribosomes', 'Microsomes', 'Soluble proteins'], 0,
    'Higher speeds bring down plastids and mitochondria, then microsomes at about 100,000 g.'],
  ['Plant cells differ from animal cells in having:', ['A cell wall, plastids and a large central vacuole, but no centrioles', 'Centrioles and lysosomes only', 'No mitochondria', 'No nucleus'], 0,
    'They also have plasmodesmata.']
] },
{ p: 'B2', t: 'Cell Biology', w: 2, pyq: ['CSE-2025-B2-m04', 'CSE-2017-B2-m04', 'IFoS-2003-B2-m05', 'IFoS-2016-B2-m03', 'CSE-1992-B2-m01', 'CSE-1985-B2-m01', 'CSE-1987-B2-m03', 'IFoS-2021-B2-m03', 'CSE-1994-B2-m01', 'IFoS-2024-B2-m04', 'IFoS-2006-B2-m04'], q: [
  ['Inside a chloroplast, thylakoids form:', ['Stacked grana linked by stroma lamellae (frets)', 'A single folded tube', 'Cristae', 'Free vesicles only'], 0,
    'The stroma surrounds them inside a double envelope.'],
  ['Photosystem II and LHCII are concentrated in:', ['Appressed grana membranes', 'Stroma lamellae', 'The envelope', 'The stroma'], 0,
    'This uneven spread is called lateral heterogeneity.'],
  ['Photosystem I and ATP synthase are mostly found in:', ['Stroma lamellae and grana margins facing the stroma', 'The core of appressed grana', 'The inner envelope', 'The lumen'], 0,
    'Their bulky stromal parts cannot fit between stacked membranes.'],
  ['The chloroplast stroma contains:', ['RuBisCO, starch grains, plastoglobuli, DNA and 70S ribosomes', 'Cristae', 'Lysosomes', '80S ribosomes'], 0,
    'Calvin cycle reactions happen in the stroma.'],
  ['In dark-grown seedlings, proplastids develop into:', ['Etioplasts with prolamellar bodies', 'Chromoplasts', 'Amyloplasts', 'Mitochondria'], 0,
    'Light converts protochlorophyllide to chlorophyllide (via POR) and thylakoids form.'],
  ['Cyanobacteria differ from chloroplasts in that their thylakoids:', ['Lie free in the cytoplasm with phycobilisomes and no grana', 'Form grana', 'Are absent', 'Are inside mitochondria'], 0,
    'Red algal plastids also bear phycobilisomes.'],
  ['Chromoplasts are plastids that:', ['Store carotenoid pigments in fruits and petals', 'Store starch', 'Store oil', 'Carry out photosynthesis'], 0,
    'Amyloplasts store starch; elaioplasts store oil.'],
  ['Plastids divide using a ring of the protein:', ['FtsZ, inherited from their bacterial ancestor', 'Actin', 'Tubulin', 'Myosin'], 0,
    'Dynamin-like proteins help complete constriction.'],
  ['The fret system of thylakoids is arranged:', ['As helical stroma lamellae winding round the grana', 'As separate grana with no links', 'Parallel to the envelope only', 'Inside the stroma as tubes'], 0,
    'This keeps the thylakoid lumen continuous.'],
  ['Chloroplast biogenesis needs:', ['Proteins coded by both nuclear and plastid genes', 'Only plastid genes', 'Only nuclear genes', 'No genes'], 0,
    'Light and signals from plastid to nucleus coordinate the two.']
] }
);
