/* Concept sets for Agriculture II — Plant breeding methods, resistance breeding, population improvement, germplasm and seed legislation. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: ['IFoS-2024-A2-m18', 'CSE-2022-A2-m11', 'CSE-2021-A2-m09', 'CSE-2020-A2-m10', 'CSE-2018-A2-m07', 'CSE-2009-A2-m16', 'IFoS-2006-A2-m15', 'IFoS-2006-A2-m17', 'CSE-2006-A2-m13', 'IFoS-2005-A2-m18', 'IFoS-2004-A2-m17', 'CSE-2004-A2-m12', 'CSE-2004-A2-m13', 'CSE-2003-A2-m17', 'IFoS-2002-A2-m09', 'IFoS-2002-A2-m10', 'CSE-2002-A2-m14', 'CSE-2002-A2-m16', 'IFoS-2001-A2-m16', 'CSE-2001-A2-m22', 'IFoS-2006-A2-m14', 'IFoS-2021-A2-m17', 'CSE-2016-A2-m12'], q: [
  ['In mass selection, the breeder:', ['Selects phenotypically superior plants and bulks their seed without progeny testing', 'Tests each plant\'s progeny separately', 'Crosses two parents', 'Uses only mutants'], 0,
    'It is quick and cheap but cannot separate genetic from environmental effects.'],
  ['A main limitation of mass selection is that:', ['Selection is on phenotype, so environment can mislead it', 'It produces hybrids', 'It needs a laboratory', 'It works only in clonal crops'], 0,
    'Stratified mass selection (Gardner) reduces field variation in maize.'],
  ['Pure-line selection was based on the work of:', ['Johannsen (1903) on beans', 'Mendel on peas', 'Shull on maize', 'Vavilov on wheat'], 0,
    'Selection within a pure line is ineffective because variation is only environmental.'],
  ['A pure line is:', ['The progeny of a single self-pollinated homozygous plant', 'A mixture of genotypes', 'An F₁ hybrid', 'A clone of a cross-pollinated plant'], 0,
    'It is homozygous, homogeneous and genetically stable.'],
  ['Pure-line selection is mainly used in:', ['Self-pollinated crops', 'Cross-pollinated crops', 'Vegetatively propagated crops only', 'Hybrids'], 0,
    'Many early Indian wheat and rice varieties came from pure-line selection.'],
  ['A progeny test judges a plant by:', ['The performance of its offspring', 'Its own height', 'Its seed colour', 'Its market price'], 0,
    'Vilmorin\'s isolation principle introduced the idea.'],
  ['The ear-to-row method (Hopkins, 1908) is a form of:', ['Progeny selection in maize', 'Backcrossing', 'Mutation breeding', 'Clonal selection'], 0,
    'Ears are planted in separate rows and the best rows kept.'],
  ['Mass selection differs from pure-line selection in that mass selection:', ['Bulks seed of many selected plants, giving a variety with some variation', 'Keeps a single plant progeny', 'Needs progeny tests', 'Gives a hybrid'], 0,
    'Pure lines are uniform; mass-selected varieties are more variable.'],
  ['In cross-pollinated crops, mass selection is useful for:', ['Improving characters of high heritability in a population', 'Producing pure lines', 'Making hybrids directly', 'Creating mutants'], 0,
    'It gives slow, steady improvement.'],
  ['Variation within a pure line is:', ['Environmental, not genetic', 'Mostly genetic', 'Due to mutation only', 'Due to crossing'], 0,
    'So selecting within it does not change the next generation.']
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 2, pyq: ['CSE-2020-A2-m12', 'CSE-2018-A2-m12', 'CSE-2010-A2-m11', 'CSE-2006-A2-m11', 'CSE-2002-A2-m10', 'IFoS-2001-A2-m13', 'CSE-2001-A2-m19', 'CSE-2021-A2-m14', 'IFoS-2021-A2-m15', 'CSE-1992-A2-m25', 'CSE-2003-A2-m15', 'CSE-2014-A2-m17', 'CSE-2013-A2-m06', 'IFoS-2012-A2-m11', 'CSE-2016-A2-m03', 'CSE-2013-A2-m03'], q: [
  ['Self-incompatibility is:', ['The failure of a fertile plant to set seed with its own pollen', 'Male sterility', 'Failure to flower', 'Inability to germinate'], 0,
    'It promotes outcrossing.'],
  ['Gametophytic self-incompatibility, as in *Nicotiana*, is characterised by:', ['Pollen tube arrest in the style, controlled by the pollen\'s own S allele', 'Inhibition on the stigma surface', 'Dominance among S alleles in pollen', 'Different flower forms'], 0,
    'It involves S-RNases.'],
  ['Sporophytic self-incompatibility, typical of *Brassica*, is controlled by:', ['The S genotype of the pollen-producing parent, with inhibition at the stigma', 'The pollen\'s own haploid genotype', 'Cytoplasmic genes', 'Flower colour genes'], 0,
    'Dominance relations among S alleles occur.'],
  ['Self-incompatibility in *Brassica* can be overcome for seed multiplication by:', ['Bud pollination, CO₂ treatment or salt spray', 'Removing anthers', 'Watering', 'Darkness'], 0,
    'Mentor pollen and heat treatment also work.'],
  ['Self-incompatibility is used commercially to produce F₁ hybrids of:', ['Cabbage, cauliflower and broccoli', 'Rice', 'Wheat', 'Tomato'], 0,
    'It avoids hand emasculation.'],
  ['Heteromorphic incompatibility, as in *Primula*, involves:', ['Different flower forms such as pin and thrum (distyly)', 'Identical flowers', 'Male sterility', 'Cleistogamy'], 0,
    'Most self-incompatible species are homomorphic.'],
  ['Often cross-pollinated crops (5–30% outcrossing) include:', ['Cotton, sorghum and pigeonpea', 'Rice and wheat', 'Maize and bajra', 'Potato and sugarcane'], 0,
    'Mode of reproduction decides the breeding method.'],
  ['A mechanism that promotes cross-pollination is:', ['Dichogamy, as protandry in maize', 'Cleistogamy', 'Chasmogamy with self-compatibility', 'Bud pollination'], 0,
    'Others: monoecy, dioecy, herkogamy, SI and male sterility.'],
  ['Pure-line and pedigree methods suit self-pollinated crops because:', ['They are naturally homozygous', 'They are highly heterozygous', 'They are clonal', 'They are sterile'], 0,
    'Cross-pollinated crops use population improvement and hybrids.'],
  ['In angiosperms, pollination differs from fertilisation in that pollination is:', ['Transfer of pollen to the stigma, while fertilisation is fusion of gametes', 'Fusion of gametes', 'Seed formation', 'Germination'], 0,
    'Double fertilisation follows pollen-tube growth.']
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: ['CSE-2019-A2-m16', 'IFoS-2015-A2-m17', 'IFoS-2013-A2-m19', 'CSE-2007-A2-m14', 'CSE-2005-A2-m11', 'CSE-1995-A2-m13', 'IFoS-2020-A2-m21', 'IFoS-2019-A2-m14', 'IFoS-2022-A2-m20', 'CSE-2010-A2-m12', 'IFoS-2024-A2-m20', 'CSE-2023-A2-m12', 'CSE-2001-A2-m21', 'CSE-1993-A2-m19', 'CSE-1989-A2-m25', 'CSE-2017-A2-m18', 'CSE-2010-A2-m10', 'CSE-2003-A2-m12', 'IFoS-2024-A2-m19', 'IFoS-2015-A2-m11', 'CSE-2012-A2-m04', 'CSE-2000-A2-m05', 'IFoS-2016-A2-m11'], q: [
  ['The backcross method is used mainly to:', ['Transfer one or a few genes, such as disease resistance, into an adapted variety', 'Combine many quantitative traits from two poor parents', 'Create mutants', 'Produce haploids'], 0,
    'It was proposed by Harlan and Pope (1922).'],
  ['After the fourth backcross (BC₄), the recurrent parent genome recovered is about:', ['96.9%', '75%', '50%', '87.5%'], 0,
    'Recovery is 1 − (½)ⁿ⁺¹ — 75% after BC₁, 87.5% BC₂, 93.75% BC₃.'],
  ['When the gene being transferred is recessive, backcross breeding needs:', ['Selfing after backcrosses to identify plants carrying the gene', 'No extra step', 'Mutation', 'Grafting'], 0,
    'Dominant genes can be identified directly in each backcross.'],
  ['A test cross is a cross of the F₁ with:', ['The homozygous recessive parent, giving a 1:1 ratio for one gene', 'The dominant parent', 'Another F₁', 'Itself'], 0,
    'A backcross is a cross of the F₁ with either parent.'],
  ['A diallel cross among n parents (no reciprocals) gives:', ['n(n − 1)/2 crosses', 'n² crosses', 'n crosses', '2n crosses'], 0,
    'It estimates general and specific combining ability.'],
  ['Vertical resistance differs from horizontal resistance in that vertical resistance is:', ['Race-specific and usually controlled by major genes', 'Polygenic and durable', 'Effective against all races', 'Not inherited'], 0,
    'Van der Plank defined the terms; horizontal resistance is more durable.'],
  ['The gene-for-gene concept was proposed by:', ['H. H. Flor (1956), working on flax rust', 'Van der Plank', 'Painter', 'Biffen'], 0,
    'Each resistance gene in the host matches an avirulence gene in the pathogen.'],
  ['Painter\'s three mechanisms of insect resistance are:', ['Non-preference (antixenosis), antibiosis and tolerance', 'Avoidance, escape and death', 'Mutation, selection and drift', 'Vertical, horizontal and durable'], 0,
    'Antibiosis harms the insect\'s growth or survival.'],
  ['A drawback of relying on single major-gene resistance is:', ['Breakdown when new pathogen races appear', 'It never works', 'It reduces yield always', 'It cannot be inherited'], 0,
    'Gene pyramiding with markers gives more durable resistance.'],
  ['Systemic acquired resistance is:', ['Whole-plant resistance induced after a local infection, signalled by salicylic acid', 'Resistance inherited from a mutant', 'Resistance from pesticides', 'Resistance only in roots'], 0,
    'It is broad-spectrum and long-lasting.']
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: ['IFoS-2023-A2-m22', 'IFoS-2022-A2-m19', 'CSE-2014-A2-m18', 'IFoS-2013-A2-m16', 'CSE-2003-A2-m16', 'CSE-2000-A2-m24', 'CSE-2010-A2-m13', 'CSE-2020-A2-m11', 'IFoS-2006-A2-m16', 'CSE-1997-A2-m19', 'CSE-1992-A2-m21', 'IFoS-2006-A2-m19', 'IFoS-2001-A2-m14', 'CSE-1989-A2-m19', 'CSE-2009-A2-m18', 'CSE-2016-A2-m02'], q: [
  ['General combining ability (GCA) reflects mainly:', ['Additive gene action — the average performance of a line in crosses', 'Dominance only', 'Epistasis only', 'Cytoplasmic effects'], 0,
    'SCA reflects non-additive action in specific crosses (Sprague and Tatum, 1942).'],
  ['Recurrent selection for SCA uses as tester:', ['An inbred line', 'A broad-based variety', 'A wild relative', 'A mutant'], 0,
    'Recurrent selection for GCA uses a broad-based tester.'],
  ['Reciprocal recurrent selection (Comstock, 1949) improves:', ['Two populations at once for both GCA and SCA', 'Only one inbred', 'Only clones', 'Only self-pollinated crops'], 0,
    'It suits hybrid programmes in maize.'],
  ['Recurrent selection aims to:', ['Raise the frequency of favourable alleles while keeping variability', 'Fix a single genotype', 'Make haploids', 'Produce mutants'], 0,
    'Cycles of selection and intermating are repeated.'],
  ['A synthetic variety is produced by:', ['Open-pollinating a set of inbreds that combine well', 'Crossing two inbreds', 'Mixing seed of unrelated cultivars', 'Mutation of a hybrid'], 0,
    'Farmers can save seed for a few generations with only a modest yield decline.'],
  ['A composite variety differs from a synthetic in that a composite is made from:', ['Mixed genotypes of diverse origin, not necessarily tested inbreds', 'Only inbred lines with known GCA', 'A single cross', 'Clones'], 0,
    'Indian maize composites include Amber and Vijay.'],
  ['A multiline variety is:', ['A mixture of near-isogenic lines differing in disease-resistance genes', 'A single pure line', 'A three-way hybrid', 'A mutant line'], 0,
    'Proposed by Jensen and used by Borlaug; KML 7406 is an Indian wheat multiline.'],
  ['The main advantage of a multiline is:', ['Buffering against new races of a pathogen', 'Uniform resistance from one gene', 'Higher heterosis', 'Easier seed production'], 0,
    'Components can be replaced as races change.'],
  ['Synthetic varieties retain vigour in later generations better than single-cross hybrids because:', ['They are based on several parents and are random-mated', 'They are homozygous', 'They are clones', 'They have no heterozygosity'], 0,
    'Yield decline depends on the number of parent lines.'],
  ['Combining ability analysis helps breeders to:', ['Choose parents and decide breeding methods', 'Measure heritability only', 'Count chromosomes', 'Test germination'], 0,
    'High GCA favours selection; high SCA favours hybrids.']
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 2, pyq: ['CSE-2022-A2-m13', 'CSE-2021-A2-m13', 'CSE-1995-A2-m11', 'CSE-1992-A2-m24', 'CSE-1998-A2-m10', 'CSE-1992-A2-m22', 'CSE-1991-A2-m17', 'IFoS-2011-A2-m22', 'IFoS-2013-A2-m21', 'IFoS-2024-A2-m21', 'CSE-2002-A2-m18'], q: [
  ['Vavilov located the centre of origin of maize and upland cotton in the:', ['Central American (Mexican) centre', 'Indian centre', 'Mediterranean centre', 'Chinese centre'], 0,
    'Potato and tomato are from the South American centre; rice and sugarcane from the Indian centre.'],
  ['Maize was domesticated from:', ['Teosinte in Mexico', 'Wild rice in India', 'Sorghum in Africa', 'Wheat in the Near East'], 0,
    'Its versatility — food, feed, fodder and industrial uses — earns it the name "queen of cereals".'],
  ['Wheat was domesticated in:', ['The Fertile Crescent of the Near East', 'South America', 'Central Africa', 'Australia'], 0,
    '*Gossypium arboreum* (desi cotton) originated in the Indian subcontinent.'],
  ['Domestication is:', ['The process of bringing wild species under human cultivation and selection', 'Planting forests', 'Seed certification', 'Hybrid seed production'], 0,
    'It caused changes such as loss of seed shattering.'],
  ['Germplasm includes:', ['Landraces, obsolete varieties, wild relatives and breeding lines', 'Only released varieties', 'Only hybrids', 'Only fertilisers'], 0,
    'It is the raw material of breeding.'],
  ['Long-term seed storage in gene banks is usually at about:', ['−18 °C with low seed moisture', '+25 °C', '+4 °C only', '−196 °C for all seeds'], 0,
    'Cryopreservation in liquid nitrogen (−196 °C) is used for some tissues and recalcitrant material.'],
  ['On-farm conservation of landraces by farmers is an example of:', ['In situ conservation', 'Ex situ conservation', 'In vitro conservation', 'Cryopreservation'], 0,
    'Field gene banks are ex situ.'],
  ['Characterisation and evaluation of germplasm are needed because:', ['Breeders can use accessions only if their traits are known', 'They increase seed number', 'They are required by law only', 'They kill pathogens'], 0,
    'Core collections (Frankel and Brown) represent diversity with fewer accessions.'],
  ['India\'s national body for plant germplasm is:', ['NBPGR, New Delhi', 'NSC, New Delhi', 'NAARM', 'NIPGR only'], 0,
    'The national gene bank is at NBPGR.'],
  ['An international organisation that coordinates crop research centres is:', ['CGIAR', 'WTO', 'UNICEF', 'WHO'], 0,
    'Its centres include IRRI, CIMMYT and ICRISAT.']
] },
{ p: 'A2', t: 'Plant Breeding Methods', w: 3, pyq: ['CSE-2025-A2-m15', 'CSE-2019-A2-m14', 'CSE-2006-A2-m15', 'CSE-2024-A2-m13', 'IFoS-2019-A2-m13', 'CSE-2002-A2-m15', 'CSE-1996-A2-m14', 'IFoS-2019-A2-m12', 'CSE-2024-A2-m11', 'IFoS-2022-A2-m23', 'IFoS-2004-A2-m18', 'CSE-2025-A2-m13', 'CSE-2002-A2-m04'], q: [
  ['In the pedigree method:', ['Individual plants are selected from F₂ onwards and records of ancestry are kept', 'F₂–F₅ are grown in bulk', 'Only one seed per plant is advanced', 'No selection is done'], 0,
    'It suits traits that are easy to see; record keeping is laborious.'],
  ['In the bulk method (Nilsson-Ehle), the early segregating generations are:', ['Grown as a bulk, with selection delayed to later generations', 'Selected plant by plant', 'Backcrossed', 'Mutated'], 0,
    'Natural selection acts on the bulk; it is cheap.'],
  ['Single seed descent is used to:', ['Advance generations rapidly to homozygosity with one seed per plant', 'Increase seed quantity', 'Produce hybrids', 'Introduce genes from wild species'], 0,
    'It suits greenhouses with off-season generations.'],
  ['The correct order of steps in artificial hybridisation is:', ['Selection of parents, emasculation, bagging, pollination, labelling', 'Pollination, emasculation, bagging', 'Labelling, pollination, selection', 'Bagging, selection, harvest'], 0,
    'Emasculation prevents self-pollination of the female parent.'],
  ['Hot-water emasculation is used in crops with:', ['Very small flowers such as sorghum and rice', 'Large flowers such as cotton', 'Unisexual flowers', 'Cleistogamous flowers'], 0,
    'Pollen is killed while the pistil survives.'],
  ['Genetic variability for breeding can be created by:', ['Hybridisation, mutation, polyploidy, somaclonal variation and transgenics', 'Only fertiliser use', 'Only irrigation', 'Only pruning'], 0,
    'Gene editing is a newer tool.'],
  ['Doubled haploids help breeders because they:', ['Give fully homozygous lines in one generation', 'Are heterozygous', 'Never set seed', 'Are always mutants'], 0,
    'They come from anther culture or wide crosses, doubled with colchicine.'],
  ['Swarna-Sub1, a flood-tolerant rice, was developed by:', ['Marker-assisted backcrossing of the *Sub1* gene into Swarna', 'Mass selection', 'Mutation breeding', 'Somatic hybridisation'], 0,
    'It survives about two weeks of submergence.'],
  ['Two-line hybrid rice uses:', ['Environment-sensitive genic male sterility (EGMS)', 'CMS with maintainer and restorer', 'Hand emasculation', 'Self-incompatibility'], 0,
    'Three-line hybrids use A (CMS), B (maintainer) and R (restorer) lines.'],
  ['A breeding method that crosses the F₁ repeatedly to one parent differs from pedigree breeding in that it:', ['Aims to improve one trait of an adapted variety rather than create new combinations', 'Uses no crossing', 'Needs no selection', 'Produces hybrids'], 0,
    'That method is backcrossing.']
] },
{ p: 'A2', t: 'Seed Technology', w: 3, pyq: ['CSE-2025-A2-m16', 'CSE-2002-A2-m17', 'CSE-2011-A2-m17', 'IFoS-2016-A2-m15', 'IFoS-2012-A2-m20', 'CSE-1990-A2-m19', 'IFoS-2015-A2-m20', 'CSE-2019-A2-m13', 'IFoS-2013-A2-m22', 'CSE-2025-A2-m14', 'CSE-2012-A2-m16', 'CSE-2020-A2-m14'], q: [
  ['Under the Seeds Act, 1966:', ['Labelling of notified varieties sold is compulsory, while certification is voluntary', 'Certification is compulsory for all seed', 'Only hybrids are covered', 'Farmers cannot save seed'], 0,
    'The Seeds (Control) Order, 1983 treats seed as an essential commodity.'],
  ['New crop varieties in India are released after testing in:', ['All India Coordinated Research Project multi-location trials (IVT and AVTs)', 'One farmer\'s field', 'A single laboratory', 'Foreign countries only'], 0,
    'A central sub-committee on crop standards and release recommends notification.'],
  ['A released variety becomes "notified" when:', ['It is published in the Gazette under the Seeds Act', 'A farmer names it', 'It is exported', 'It is patented'], 0,
    'Only notified varieties can be certified.'],
  ['The PPV&FR Act, 2001 protects:', ['Both plant breeders\' rights and farmers\' rights', 'Only foreign breeders', 'Only farmers', 'Only seed companies'], 0,
    'Farmers may save, use, exchange and sell farm-saved seed, but not as branded seed.'],
  ['A variety must pass DUS testing for registration, meaning it must be:', ['Distinct, uniform and stable', 'Disease-free, uniform and sterile', 'Dwarf, uniform and short', 'Durable, useful and safe'], 0,
    'Novelty is also needed for new varieties.'],
  ['India protects plant varieties through a sui generis law rather than patents because:', ['The Patents Act excludes plants and seeds, and TRIPS allows an effective sui generis system', 'India is a UPOV 1991 member', 'Patents are cheaper', 'Plants cannot be bred'], 0,
    'TRIPS Article 27.3(b) gives this option.'],
  ['The international union that standardises plant variety protection is:', ['UPOV', 'WIPO only', 'FAO', 'CGIAR'], 0,
    'India is not a UPOV member.'],
  ['Which is a form of intellectual property used for agricultural products like Basmati and Darjeeling tea?', ['Geographical indication', 'Patent', 'Copyright', 'Trade secret'], 0,
    'Others: patents, trademarks, copyrights, industrial designs, PVP.'],
  ['Farmers\' varieties under the PPV&FR Act are:', ['Traditional varieties cultivated and evolved by farmers, eligible for registration', 'Only hybrids', 'Only imported varieties', 'Not recognised'], 0,
    'Extant and new varieties can also be registered.'],
  ['A patent differs from plant variety protection in that a patent:', ['Requires novelty, inventive step and industrial application and covers inventions', 'Is only for varieties', 'Lasts forever', 'Is free'], 0,
    'PVP is tailored to plant varieties.']
] }
);
