/* Concept sets for Agriculture II — plant diseases: resistance, fungicides, transmission, viruses and phytoplasmas, epidemiology and IDM, diagnosis, and diseases of field, vegetable, fruit and plantation crops. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 3, pyq: ['CSE-2026-A2-Q2a', 'IFoS-2006-A2-m26', 'IFoS-2004-A2-m26', 'IFoS-2001-A2-m21', 'CSE-1993-A2-m32', 'CSE-2022-A2-m18', 'CSE-2016-A2-m26', 'CSE-2013-A2-m29', 'IFoS-2010-A2-m22', 'CSE-1995-A2-m20', 'IFoS-2004-A2-m27', 'CSE-1993-A2-m36', 'IFoS-2013-A2-m30', 'CSE-2012-A2-m22', 'CSE-1991-A2-m28', 'CSE-1993-A2-m35', 'CSE-1995-A2-m25', 'CSE-1993-A2-m37', 'IFoS-2012-A2-m09', 'IFoS-2020-A2-m03', 'IFoS-2011-A2-m11', 'CSE-2000-A2-m02', 'CSE-2022-A2-m01'], q: [
  ['Vertical resistance (Van der Plank) is:', ['Race-specific, usually controlled by one or a few major genes, and often broken by new races', 'Effective against all races and controlled by many minor genes', 'Another name for disease escape', 'Resistance produced by fungicides'], 0,
    'Its sudden breakdown after a new race appears is called the "boom and bust" cycle.'],
  ['Horizontal resistance is generally preferred for long-term use because it:', ['Is polygenic, race non-specific and durable, slowing disease rather than stopping it', 'Gives complete immunity to one race', 'Depends on a single gene', 'Needs no breeding effort'], 0,
    'It puts little selection pressure on the pathogen to evolve new races.'],
  ['Flor\'s gene-for-gene hypothesis, from work on flax rust, states that:', ['For each resistance gene in the host there is a matching avirulence gene in the pathogen', 'Each pathogen gene controls one host enzyme', 'Resistance is always cytoplasmic', 'Host and pathogen share the same genes'], 0,
    'Resistance is expressed only when a matching R gene and Avr gene meet.'],
  ['Disease escape means a plant:', ['Avoids infection because of its timing or habit, such as early maturity before the pathogen peaks, though it is not truly resistant', 'Kills the pathogen inside its tissues', 'Is infected but loses little yield', 'Is immune to all pathogens'], 0,
    'E.g. early potato varieties escaping late blight.'],
  ['A disease-tolerant variety is one that:', ['Gets infected and shows symptoms but suffers little loss in yield', 'Never gets infected', 'Kills the pathogen on contact', 'Avoids infection by early maturity'], 0,
    'Tolerance does not reduce the pathogen\'s multiplication.'],
  ['Phytoalexins are:', ['Low-molecular-weight antimicrobial compounds a plant makes after infection', 'Pre-formed toxins of pathogens', 'Fungicides sprayed on leaves', 'Enzymes secreted by bacteria'], 0,
    'Examples: pisatin (pea), phaseollin (bean), rishitin (potato), glyceollin (soybean). Müller and Börger proposed the idea in 1940.'],
  ['Cross protection is:', ['Protection of a plant from a severe virus strain by first infecting it with a mild strain of the same virus', 'Protection by crossing two varieties', 'Spraying two fungicides together', 'Growing a barrier crop'], 0,
    'It has been used against citrus tristeza and papaya ring spot viruses.'],
  ['A multiline variety slows disease spread because it is:', ['A mixture of near-identical lines carrying different resistance genes, so no single race can attack all plants', 'A single pure line with one resistance gene', 'A hybrid between two species', 'A variety sprayed with many fungicides'], 0,
    'Jensen proposed multilines in oats; Borlaug developed them in wheat.'],
  ['The backcross method is used to add disease resistance because it:', ['Transfers one resistance gene from a donor into an adapted variety while recovering all of that variety\'s other traits', 'Creates new genes', 'Produces polyploids', 'Always gives hybrid vigour'], 0,
    'About six backcrosses to the recurrent parent recover nearly all its genome.'],
  ['Improved Samba Mahsuri rice resists bacterial leaf blight because breeders:', ['Pyramided the resistance genes *Xa21*, *xa13* and *xa5* using marker-assisted selection', 'Sprayed it with antibiotics', 'Induced polyploidy', 'Removed its stomata'], 0,
    'Gene pyramiding makes resistance more durable than a single gene.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, pyq: ['CSE-2015-A2-m26', 'IFoS-2000-A2-m12', 'IFoS-2000-A2-m15', 'CSE-2004-A2-m20', 'IFoS-2003-A2-m27', 'CSE-1990-A2-m30', 'CSE-2001-A2-m18', 'IFoS-2002-A2-m19', 'IFoS-2010-A2-m03'], q: [
  ['Fungicides are classified by chemistry into groups such as:', ['Inorganic (sulphur, copper), dithiocarbamates, benzimidazoles, triazoles and phenylamides', 'Organophosphates and pyrethroids', 'Auxins and gibberellins', 'Urea and DAP'], 0,
    'They are also grouped by use as protectants, eradicants and systemic (therapeutic) chemicals.'],
  ['Bordeaux mixture, the first widely used fungicide, is made from:', ['Copper sulphate and lime in water', 'Sulphur and lime', 'Mercury and copper', 'Zinc and sulphur'], 0,
    'Millardet developed it in France in the 1880s against grape downy mildew; a common strength is 1:1:100.'],
  ['Dithiocarbamates such as mancozeb became popular because they:', ['Are broad-spectrum protectants with multi-site action and low risk of resistance', 'Are systemic and cure established infections', 'Kill insects too', 'Are highly persistent in soil'], 0,
    'Thiram, zineb and ziram belong to the same group.'],
  ['Carbendazim, a benzimidazole, is a:', ['Systemic fungicide that binds β-tubulin, with a high risk of resistance', 'Copper protectant', 'Antibiotic for bacteria', 'Insect growth regulator'], 0,
    'Single-site systemic fungicides should be rotated or mixed with protectants.'],
  ['Metalaxyl is specifically effective against:', ['Oomycetes such as *Phytophthora*, *Pythium* and downy mildews', 'Rust fungi', 'Bacteria', 'Viruses'], 0,
    'Metalaxyl + mancozeb is widely used against late blight of potato.'],
  ['Triazole fungicides such as propiconazole and hexaconazole act by:', ['Inhibiting ergosterol biosynthesis in fungal membranes', 'Blocking insect nerves', 'Inhibiting chitin in insects', 'Releasing copper ions'], 0,
    'Strobilurins such as azoxystrobin instead block mitochondrial respiration.'],
  ['Organomercurial seed dressings such as Ceresan were withdrawn because:', ['Mercury is highly toxic and persists in the food chain', 'They were too cheap', 'They had no effect on seed-borne fungi', 'They caused seed dormancy'], 0,
    'Mercury compounds are banned as pesticides in India.'],
  ['A chemotherapeutant (therapeutic) fungicide is one that:', ['Is absorbed by the plant and checks a pathogen that has already infected it', 'Acts only on the leaf surface before infection', 'Is used only to sterilise soil', 'Is a growth hormone'], 0,
    'Protectants must be applied before infection; eradicants kill the pathogen at the infection site.'],
  ['Streptocycline (streptomycin + tetracycline) is used in plant protection against:', ['Bacterial diseases such as citrus canker and bacterial leaf blight', 'Fungal rusts', 'Insect pests', 'Weeds'], 0,
    'Usually combined with copper oxychloride sprays.'],
  ['Late blight of potato is commonly managed by:', ['Protective mancozeb sprays before blight weather and metalaxyl + mancozeb once it appears', 'Spraying urea', 'Flood irrigation', 'Using insecticides only'], 0,
    'Healthy seed, resistant varieties and haulm cutting also help.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, pyq: ['IFoS-2015-A2-m28', 'IFoS-2006-A2-m25', 'CSE-2006-A2-m20', 'IFoS-2002-A2-m18', 'CSE-1995-A2-m22', 'CSE-1994-A2-m14', 'CSE-1996-A2-m16', 'CSE-1990-A2-m14', 'IFoS-2014-A2-m16', 'CSE-2009-A2-m12', 'CSE-2012-A2-m23', 'CSE-2011-A2-m27', 'IFoS-2014-A2-m05', 'IFoS-2002-A2-m02', 'CSE-1992-A2-m01', 'CSE-2021-A2-m15'], q: [
  ['Loose smut of wheat is an internally seed-borne disease controlled by:', ['Solar or hot-water seed treatment, or systemic fungicides like carboxin or tebuconazole', 'Spraying at flowering only', 'Soil fumigation', 'Insecticides'], 0,
    'The fungus (*Ustilago segetum* var. *tritici*) survives as mycelium inside the embryo.'],
  ['Seed of cabbage and cauliflower is freed of black rot bacteria by:', ['Hot-water treatment at about 50 °C for 25–30 minutes', 'Soaking in urea', 'Freezing', 'Sun-drying for an hour'], 0,
    'Black rot is caused by *Xanthomonas campestris* pv. *campestris*; *Alternaria* leaf spot is also seed-borne.'],
  ['Seed-borne infection is important in epidemics because it:', ['Provides primary inoculum and carries the pathogen to new areas with the seed', 'Only affects seed weight', 'Kills the pathogen', 'Prevents secondary spread'], 0,
    'Seed certification sets limits on seed-borne diseases.'],
  ['Plant viruses are transmitted mainly by:', ['Vectors (insects, mites, nematodes, fungi), sap, grafting, seed, pollen and vegetative parts', 'Wind-blown spores', 'Soil water alone', 'Sunlight'], 0,
    'Insects, especially aphids, whiteflies and leafhoppers, are the largest group of vectors.'],
  ['Non-persistent (stylet-borne) virus transmission is marked by:', ['Acquisition and inoculation within seconds, no latent period, and loss of the virus within minutes', 'A long latent period inside the vector', 'Virus multiplying in the vector', 'Lifelong retention'], 0,
    'E.g. potato virus Y and cucumber mosaic virus by aphids.'],
  ['Tomato leaf curl virus is transmitted by:', ['The whitefly *Bemisia tabaci*, in a persistent circulative manner', 'Aphids, non-persistently', 'Sap and handling', 'Seed'], 0,
    'It is a begomovirus; raising nurseries under insect-proof net helps.'],
  ['NEPO viruses are those that are:', ['Nematode-transmitted with polyhedral particles, e.g. by *Xiphinema* and *Longidorus*', 'Transmitted by aphids with rod particles', 'Seed-borne only', 'Fungal toxins'], 0,
    'NETU (or NETO) viruses are nematode-transmitted tubular or rod-shaped viruses (tobraviruses) carried by *Trichodorus*.'],
  ['Satellite viruses are:', ['Small viruses that need a helper virus to multiply but code for their own coat protein', 'Viruses that orbit the cell', 'Viroids with a coat', 'Bacteria-like pathogens'], 0,
    'E.g. satellite tobacco necrosis virus depends on tobacco necrosis virus; satellite RNAs lack their own coat protein.'],
  ['A fungal vector of a plant virus is:', ['*Olpidium brassicae*, which carries tobacco necrosis virus', '*Trichoderma viride*', '*Penicillium notatum*', '*Rhizobium*'], 0,
    '*Polymyxa graminis* transmits wheat soil-borne mosaic virus.'],
  ['Vector-borne virus diseases in vegetables are best managed by:', ['Virus-free seedlings, vector control, barrier crops like maize, reflective mulches and roguing infected plants', 'Fungicide sprays only', 'Heavy nitrogen', 'Late sowing in hot weather'], 0,
    'Chemicals cannot cure plants once virus-infected.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, pyq: ['CSE-2011-A2-m25', 'CSE-2011-A2-m26', 'CSE-1995-A2-m21', 'CSE-1989-A2-m13', 'CSE-1991-A2-m03', 'IFoS-2012-A2-m25', 'CSE-1991-A2-m06', 'IFoS-2021-A2-m13'], q: [
  ['Viroids are:', ['Small, circular, single-stranded RNA molecules without a protein coat', 'Bacteria without cell walls', 'Viruses with DNA and a coat', 'Fungal spores'], 0,
    'T. O. Diener discovered the first, potato spindle tuber viroid (PSTVd), in 1971.'],
  ['Potato spindle tuber disease produces:', ['Elongated, spindle-shaped tubers with prominent eyes and erect, stunted foliage', 'Black hearts in tubers', 'White powdery leaves', 'Galls on roots'], 0,
    'It spreads by contact, cutting knives, seed tubers and true seed.'],
  ['Banana bunchy top disease is spread by:', ['The banana aphid *Pentalonia nigronervosa* and infected suckers', 'Whiteflies', 'Leafhoppers', 'Soil nematodes'], 0,
    'Leaves become narrow, erect and bunched, with dark green "Morse code" streaks; uproot infected clumps.'],
  ['Cauliflower mosaic virus, type member of caulimoviruses, is notable because:', ['It has double-stranded DNA, replicates via reverse transcription, and its 35S promoter is used in plant transgenics', 'It is a single-stranded RNA virus spread by seed', 'It is a viroid', 'It infects only bacteria'], 0,
    'It is transmitted by aphids.'],
  ['Phytoplasmas (once called mycoplasma-like organisms) are:', ['Wall-less prokaryotes living in phloem, spread by leafhoppers and sensitive to tetracycline', 'Viruses with protein coats', 'Fungi in the xylem', 'Nematodes'], 0,
    'Doi and co-workers in Japan first linked them to plant yellows diseases in 1967.'],
  ['A disease caused by a phytoplasma is:', ['Little leaf of brinjal', 'Late blight of potato', 'Citrus canker', 'Rust of wheat'], 0,
    'Others: sesamum phyllody, sandal spike, grassy shoot of sugarcane.'],
  ['Plant pathogenic bacteria differ from fungi in that bacteria are:', ['Single-celled prokaryotes that multiply by binary fission and enter through wounds or natural openings', 'Eukaryotes with hyphae and spores', 'Obligate parasites with no cells', 'Always seed-borne'], 0,
    'They spread mainly by rain splash, water, insects and tools.'],
  ['Plant viruses differ from bacteria in that viruses:', ['Are nucleoprotein particles with no cells or ribosomes and multiply only inside living cells', 'Can be grown on nutrient agar', 'Divide by binary fission', 'Are killed by penicillin'], 0,
    'W. M. Stanley crystallised tobacco mosaic virus in 1935.'],
  ['"Acellular" plant pathogens include:', ['Viruses and viroids', 'Fungi and bacteria', 'Nematodes and mites', 'Algae and protozoa'], 0,
    'They are naturally transmitted by vectors, seed, pollen, vegetative propagation and contact.'],
  ['Symptoms typical of virus diseases are:', ['Mosaic, mottling, vein clearing, leaf curl, ring spots and stunting, with no visible signs of the pathogen', 'White powdery growth on leaves', 'Rust pustules', 'Bacterial ooze'], 0,
    'Fungi and bacteria often show signs such as spores, mycelium or ooze.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 3, pyq: ['CSE-2016-A2-m25', 'CSE-2014-A2-m25', 'CSE-2004-A2-m06', 'CSE-2009-A2-m11', 'CSE-2023-A2-m23', 'IFoS-2012-A2-m26', 'CSE-1993-A2-m34', 'IFoS-2002-A2-m17', 'CSE-1993-A2-m38', 'CSE-1990-A2-m32', 'IFoS-2005-A2-m30'], q: [
  ['A plant disease epidemic (epiphytotic) is:', ['A sudden, widespread increase of a disease in a host population over a large area', 'A disease always present at low levels in an area', 'A disease of a single plant', 'A disease caused only by viruses'], 0,
    'Endemic diseases are constantly present; sporadic ones appear irregularly.'],
  ['The "disease triangle" shows that disease needs:', ['A susceptible host, a virulent pathogen and a favourable environment together', 'Only a pathogen', 'Only bad weather', 'A vector in every case'], 0,
    'Adding time (and human activity) gives the disease tetrahedron or pyramid.'],
  ['Van der Plank called polycyclic diseases like late blight "compound interest" diseases because:', ['The pathogen completes many infection cycles in a season, so disease builds up rapidly', 'They have one cycle per season', 'They occur only every few years', 'They spread only by seed'], 0,
    'Wilts and smuts with one cycle per season are "simple interest" diseases.'],
  ['A forecasting system for potato late blight developed in India is:', ['JHULSACAST, by ICAR-CPRI, Shimla', 'Mills\' table', 'BLITECAST only for wheat', 'EPIWHEAT'], 0,
    'The older Beaumont period rule uses two days with minimum temperature ≥10 °C and humidity ≥75%; Mills\' table forecasts apple scab.'],
  ['The Bengal famine of 1943 was worsened by an epidemic of:', ['Brown spot of rice (*Cochliobolus miyabeanus*)', 'Late blight of potato', 'Wheat stem rust', 'Coffee rust'], 0,
    'Late blight caused the Irish famine of 1845–47.'],
  ['Whetzel\'s principles of plant disease control are:', ['Exclusion, eradication, protection and immunisation (resistance), later with avoidance and therapy', 'Spraying, dusting and fumigation', 'Ploughing, sowing and harvesting', 'Quarantine only'], 0,
    'Integrated disease management combines these with the least harm to the environment.'],
  ['Integrated disease management (IDM) combines:', ['Resistant varieties, healthy seed, cultural practices, biocontrol agents like *Trichoderma*, and need-based fungicides', 'Only fungicides on a calendar', 'Only resistant varieties', 'Only crop rotation'], 0,
    'Disease forecasting helps time sprays.'],
  ['An alternate host is:', ['A different plant species a heteroecious rust needs to complete its life cycle, such as barberry for wheat stem rust', 'A weed of the same family that harbours a pathogen', 'The main crop host', 'A resistant variety'], 0,
    'In India barberry plays no role; K. C. Mehta showed rust survives the summer on wheat in the hills.'],
  ['A collateral host differs from an alternate host in that it:', ['Is a wild relative or weed that harbours the pathogen but is not needed to complete its life cycle', 'Is required for sexual reproduction of the rust', 'Is never infected', 'Is a vector insect'], 0,
    'Removing collateral hosts reduces carry-over inoculum.'],
  ['Soil-borne diseases (wilts, root rots, damping-off) are best managed by:', ['Crop rotation, soil solarisation, organic amendments, resistant varieties and *Trichoderma* seed or soil treatment', 'Foliar sprays only', 'Heavy irrigation', 'Burning the crop residue on leaves'], 0,
    'Garrett classified soil fungi as soil inhabitants and soil invaders.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, pyq: ['IFoS-2010-A2-m23', 'IFoS-2004-A2-m24', 'CSE-2020-A2-m21', 'CSE-2022-A2-m16', 'CSE-1989-A2-m36', 'CSE-1992-A2-m35', 'CSE-2005-A2-m19', 'CSE-1990-A2-m31', 'IFoS-2002-A2-m19', 'CSE-1990-A2-m30'], q: [
  ['Koch\'s postulates require that the suspected pathogen be:', ['Always found with the disease, isolated in pure culture, able to reproduce the disease on inoculation, and re-isolated', 'Seen under a light microscope only', 'Killed by a fungicide', 'Found in soil near the plant'], 0,
    'They are hard to apply to obligate parasites and viruses, which cannot be cultured on media.'],
  ['Plant diseases are classified by cause into:', ['Infectious (biotic: fungi, bacteria, viruses, phytoplasmas, nematodes) and non-infectious (abiotic: nutrients, temperature, pollutants)', 'Seed-borne and air-borne only', 'Major and minor', 'Annual and perennial'], 0,
    'They can also be classified by symptoms, host crop or mode of spread.'],
  ['Khaira disease of rice is caused by:', ['Zinc deficiency, corrected with zinc sulphate', 'A fungus', 'A virus', 'Nitrogen excess'], 0,
    'Y. L. Nene identified it at Pantnagar in the 1960s; leaves show rusty brown patches.'],
  ['Fluoride injury in plants typically shows as:', ['Scorching of leaf tips and margins where fluoride accumulates', 'Round black spots in the centre of leaves', 'White powder on leaves', 'Root galls'], 0,
    'Gladiolus is a sensitive indicator plant.'],
  ['Black tip of mango is a non-infectious disorder linked to:', ['Fumes from nearby brick kilns', 'A fungus', 'Fruit flies', 'Excess irrigation'], 0,
    'Borax sprays and keeping kilns away from orchards help.'],
  ['A virus disease can be told apart from a nutrient disorder because the virus disease:', ['Can be transmitted by grafting, sap or vectors and spreads from plant to plant', 'Appears evenly on all plants in the field', 'Is cured by fertiliser', 'Always affects old leaves first'], 0,
    'Nutrient disorders often show a regular pattern on old or young leaves.'],
  ['Signs of a plant disease, as against symptoms, are:', ['Visible structures of the pathogen such as mycelium, spores or bacterial ooze', 'Changes in the host such as wilting or yellowing', 'Weather conditions', 'Yield losses'], 0,
    'Symptoms are the host\'s reaction to disease.'],
  ['A systemic disease is one in which:', ['The pathogen spreads through much of the plant, e.g. downy mildew of pearl millet or viruses', 'Damage is limited to one leaf spot', 'Only fruits are affected', 'The disease is caused by soil chemicals'], 0,
    'Systemic diseases are hard to cure once established; seed treatment and resistance matter more.'],
  ['Diseases that most directly reduce photosynthesis include:', ['Leaf spots, blights, rusts, mildews and mosaics that destroy leaf area or chlorophyll', 'Root galls only', 'Seed rots only', 'Storage rots'], 0,
    'Vascular wilts reduce photosynthesis indirectly by blocking water supply.'],
  ['Predisposition in plant pathology means:', ['Environmental conditions before infection that make the host more susceptible', 'Genetic immunity of the host', 'The resting stage of a pathogen', 'Transfer of resistance genes'], 0,
    'E.g. heavy nitrogen predisposes rice to blast.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, pyq: ['CSE-1995-A2-m24', 'CSE-2024-A2-m22', 'IFoS-2001-A2-m23', 'CSE-2002-A2-m25', 'CSE-2000-A2-m34', 'CSE-1998-A2-m17', 'CSE-2019-A2-m24', 'CSE-1989-A2-m26', 'CSE-1996-A2-m08', 'CSE-1998-A2-m18', 'CSE-1989-A2-m44', 'CSE-2009-A2-m01'], q: [
  ['Rice blast is caused by *Magnaporthe oryzae* and is recognised by:', ['Spindle-shaped leaf lesions with grey centres and "neck blast" at panicle base', 'Kresek wilting of seedlings', 'Orange-yellow leaves and stunting', 'Galls on roots'], 0,
    'Heavy nitrogen and cool, humid nights favour it; tricyclazole is a common fungicide.'],
  ['Bacterial leaf blight of rice (*Xanthomonas oryzae* pv. *oryzae*) shows:', ['Yellowing and drying from leaf tips and margins, and "kresek" wilting of young plants', 'Eye-shaped spots', 'White ears', 'Silver shoots'], 0,
    'Bacteria enter through wounds and hydathodes and spread with irrigation water.'],
  ['Rice tungro disease is caused by:', ['Two viruses together (a bacilliform DNA virus and a spherical RNA virus) spread by green leafhopper', 'A fungus spread by wind', 'A bacterium spread by water', 'A nematode'], 0,
    'Infected plants are stunted with orange-yellow leaves; control the vector *Nephotettix virescens* and grow resistant varieties.'],
  ['Grassy stunt and ragged stunt viruses of rice are transmitted by:', ['Brown planthopper', 'Green leafhopper', 'Whitefly', 'Aphids'], 0,
    'Controlling BPH prevents both the pest damage and these viruses.'],
  ['Black (stem) rust of wheat is caused by:', ['*Puccinia graminis* f. sp. *tritici*', '*Puccinia striiformis*', '*Puccinia triticina*', '*Ustilago tritici*'], 0,
    'The Ug99 race of stem rust from Uganda threatened many resistant varieties. *P. striiformis* causes yellow rust and *P. triticina* brown rust.'],
  ['The "Puccinia path" concept in India means:', ['Rust spores move by wind from survival sites in the hills to the plains, so different resistance genes are deployed along the path', 'A path used by insects to spread rust', 'A method of crossing wheat', 'A route for seed distribution'], 0,
    'Nilgiri and Palni hills are sources for southern and central India; the Himalayas for the north.'],
  ['Grain (covered) smut of sorghum is:', ['Externally seed-borne and controlled by seed dressing with sulphur or fungicides', 'Soil-borne and controlled by rotation only', 'Insect-transmitted', 'Caused by a virus'], 0,
    'Grains are replaced by smut sori covered by a membrane.'],
  ['Karnal bunt of wheat is caused by:', ['*Tilletia indica*, and is of quarantine importance', '*Puccinia graminis*', '*Ustilago segetum*', 'A virus'], 0,
    'Only part of the grain is converted into black powder with a fishy smell.'],
  ['Sheath blight of rice is caused by:', ['*Rhizoctonia solani*', '*Xanthomonas oryzae*', '*Pyricularia oryzae*', '*Fusarium fujikuroi*'], 0,
    '*Fusarium fujikuroi* causes bakanae (foolish seedling) disease through gibberellin production.'],
  ['Bacterial plant diseases are controlled mainly by:', ['Clean seed, resistant varieties, field sanitation and copper or streptocycline sprays', 'Systemic insecticides', 'Fungicides such as metalaxyl only', 'Heavy nitrogen'], 0,
    'Avoid flooding from infected fields since bacteria travel in water.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, pyq: ['CSE-2003-A2-m23', 'CSE-1993-A2-m33', 'CSE-1995-A2-m23', 'CSE-1989-A2-m40', 'CSE-1999-A2-m08', 'CSE-2006-A2-m24', 'CSE-2002-A2-m21', 'CSE-1998-A2-m18', 'CSE-1993-A2-m03'], q: [
  ['Red rot of sugarcane, called the "cancer" of sugarcane, is caused by:', ['*Colletotrichum falcatum*', '*Ustilago scitaminea*', '*Xanthomonas* sp.', 'A phytoplasma'], 0,
    'Split canes show red tissue with white cross-bands and smell of alcohol.'],
  ['Red rot is managed by:', ['Healthy setts, resistant varieties and moist hot-air treatment of setts', 'Spraying insecticides', 'Ratooning the infected crop', 'Flood irrigation'], 0,
    'Moist hot-air therapy is about 54 °C for 2½ hours at high humidity; avoid ratooning diseased crops.'],
  ['Whip smut of sugarcane shows:', ['A long black whip-like structure from the top of the cane', 'Red internal tissue', 'Grassy shoots', 'Leaf scald'], 0,
    'Caused by *Sporisorium* (*Ustilago*) *scitamineum*; rogue whips before they burst.'],
  ['Grassy shoot disease of sugarcane is caused by a:', ['Phytoplasma', 'Fungus', 'Nematode', 'Bacterium in the xylem'], 0,
    'Ratoon stunting is caused by the bacterium *Leifsonia xyli* subsp. *xyli*.'],
  ['Black arm (bacterial blight) of cotton is caused by:', ['*Xanthomonas citri* pv. *malvacearum*', '*Fusarium oxysporum*', '*Alternaria macrospora*', 'Cotton leaf curl virus'], 0,
    'It causes angular leaf spots, black lesions on stems ("black arm") and boll rot; acid delinting and seed treatment help.'],
  ['A "disease complex" in cotton refers to:', ['Interaction of two or more pathogens, such as *Fusarium* wilt worsened by root-knot nematodes', 'A disease caused by one virus only', 'A group of insect pests', 'A nutrient deficiency'], 0,
    'Nematode wounds help the wilt fungus enter roots.'],
  ['Pigeon pea (arhar) wilt is caused by:', ['*Fusarium udum*, a soil-borne fungus', '*Puccinia cajani*', 'A virus spread by aphids', '*Rhizobium*'], 0,
    'Resistant varieties (e.g. ICP 8863, Maruti) and rotation with sorghum or tobacco help.'],
  ['Sterility mosaic of pigeon pea is spread by:', ['The eriophyid mite *Aceria cajani*', 'Whiteflies', 'Aphids', 'Seed'], 0,
    'Affected plants are bushy, pale green and do not flower.'],
  ['Tikka disease of groundnut is a:', ['Leaf spot disease caused by *Cercospora* species (early and late leaf spot)', 'Root rot caused by *Rhizobium*', 'Viral bud necrosis', 'Bacterial wilt'], 0,
    'Late leaf spot is caused by *Phaeoisariopsis personata*.'],
  ['White rust of mustard is caused by:', ['*Albugo candida*', '*Alternaria brassicae*', '*Erysiphe cruciferarum*', '*Sclerotinia sclerotiorum*'], 0,
    'It produces white blisters on leaves and "stag head" swelling of inflorescences.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, pyq: ['IFoS-2018-A2-Q7a', 'CSE-2016-A2-m27', 'CSE-2007-A2-m23', 'IFoS-2016-A2-m22', 'IFoS-2012-A2-m26', 'CSE-1993-A2-m34', 'CSE-2010-A2-m06', 'IFoS-2024-A2-m24', 'IFoS-2000-A2-m14', 'IFoS-2023-A2-m16', 'CSE-2000-A2-m15', 'CSE-1989-A2-m12', 'CSE-2012-A2-m21', 'IFoS-2020-A2-m18', 'CSE-2018-A2-m05', 'IFoS-2006-A2-m24', 'CSE-1993-A2-m09'], q: [
  ['Late blight of potato (*Phytophthora infestans*) is favoured by:', ['Cool, humid, cloudy weather, producing water-soaked lesions with white growth on the underside of leaves', 'Hot, dry weather', 'Waterlogged soils only', 'High light intensity'], 0,
    '*Phytophthora* is an oomycete (water mould), not a true fungus.'],
  ['Early blight of potato and tomato (*Alternaria solani*) shows:', ['Brown leaf spots with concentric rings ("target board")', 'White powdery patches', 'Galls on roots', 'Silver leaves'], 0,
    'It starts on older leaves and is favoured by alternating dry and wet periods.'],
  ['Damping-off of vegetable seedlings is caused mainly by:', ['*Pythium*, *Rhizoctonia*, *Phytophthora* and *Fusarium*', 'Rust fungi', 'Viruses', 'Phytoplasmas'], 0,
    'Raised nursery beds, good drainage, seed treatment with *Trichoderma* or captan, and soil solarisation control it.'],
  ['Vascular wilt pathogens such as *Fusarium oxysporum* and *Verticillium* cause wilting by:', ['Colonising and blocking the xylem, causing vascular browning', 'Destroying leaf cuticle', 'Feeding on phloem only', 'Infecting seeds only'], 0,
    'Bacterial wilt (*Ralstonia solanacearum*) also blocks xylem.'],
  ['Bacterial wilt can be told apart from fungal wilt by:', ['The ooze test: a cut stem in clear water releases milky bacterial streams', 'White powder on leaves', 'Slow yellowing from the base over weeks', 'Concentric rings on leaves'], 0,
    'Bacterial wilt causes sudden wilting while leaves are still green.'],
  ['Powdery mildew of cucurbits is controlled with:', ['Wettable sulphur or systemic fungicides such as hexaconazole, with care as some cucurbits are sulphur-sensitive', 'Copper sulphate only', 'Streptocycline', 'Insecticides'], 0,
    'The pathogen (*Podosphaera xanthii* or *Golovinomyces*) forms white powdery growth on leaves.'],
  ['Leaf curl and mosaic in chilli and tomato are managed by:', ['Raising seedlings under insect-proof net, barrier crops like maize, vector control and removing infected plants', 'Fungicide sprays alone', 'Heavy nitrogen', 'Flood irrigation'], 0,
    'Leaf curl is whitefly-borne; mosaic viruses such as CMV are aphid-borne.'],
  ['The golden cyst nematode of potato in the Nilgiris is managed by:', ['Domestic quarantine, crop rotation and resistant varieties such as Kufri Swarna', 'Fungicide sprays', 'Late planting', 'Removing flowers'], 0,
    'It is *Globodera rostochiensis*; cysts survive in soil for years.'],
  ['Rhizome rot of ginger is caused mainly by:', ['*Pythium aphanidermatum*, worsened by waterlogging', 'A rust fungus', 'A phytoplasma', 'An aphid-borne virus'], 0,
    'Seed rhizome treatment with metalaxyl–mancozeb and good drainage help.'],
  ['A disease caused by a *Phytophthora* species is:', ['Foot rot (quick wilt) of black pepper', 'Wheat stem rust', 'Rice blast', 'Citrus canker'], 0,
    'Others: late blight of potato, coconut bud rot, citrus gummosis, colocasia blight. Bordeaux mixture and metalaxyl control them.']
] },
{ p: 'A2', t: 'Crop Diseases & Nematodes', w: 2, pyq: ['IFoS-2000-A2-m13', 'CSE-2003-A2-m04', 'CSE-2013-A2-m11', 'CSE-2000-A2-m17', 'CSE-2000-A2-m16', 'CSE-2001-A2-m09', 'CSE-2015-A2-m10', 'IFoS-2014-A2-m09', 'CSE-2009-A2-m09', 'CSE-2012-A2-m20'], q: [
  ['Citrus canker (*Xanthomonas citri* subsp. *citri*) is managed by:', ['Pruning infected twigs and spraying copper oxychloride with streptocycline', 'Insecticides only', 'Flood irrigation', 'Removing flowers'], 0,
    'Raised corky lesions with a yellow halo appear on leaves, twigs and fruits; leaf miner wounds aid entry.'],
  ['Powdery mildew of grapes is caused by:', ['*Erysiphe* (*Uncinula*) *necator*, controlled by sulphur dusting or sprays', '*Plasmopara viticola*', '*Elsinoë ampelina*', '*Xanthomonas campestris*'], 0,
    '*Plasmopara viticola* causes downy mildew.'],
  ['Powdery mildew of rose is caused by:', ['*Podosphaera* (*Sphaerotheca*) *pannosa*', '*Diplocarpon rosae*', '*Phytophthora*', 'A virus'], 0,
    '*Diplocarpon rosae* causes black spot of rose.'],
  ['Anthracnose of grapes ("bird\'s eye spot") is caused by:', ['*Elsinoë ampelina*', '*Erysiphe necator*', '*Colletotrichum falcatum*', '*Botrytis cinerea*'], 0,
    'Sunken spots with grey centres and dark margins form on berries and shoots; Bordeaux mixture controls it.'],
  ['Sooty mould of mango is:', ['A black fungal coating growing on honeydew excreted by hoppers, mealybugs and scales', 'A parasitic fungus inside leaves', 'A bacterial disease', 'A nutrient disorder'], 0,
    'Control the insects and spray starch (about 2%), which peels off with the mould.'],
  ['Guava wilt is caused by soil-borne fungi such as:', ['*Fusarium oxysporum* f. sp. *psidii*', '*Puccinia psidii*', '*Erysiphe*', 'A virus'], 0,
    'Remove affected trees, improve drainage, apply organic amendments and use tolerant rootstocks.'],
  ['Blister blight of tea is caused by:', ['*Exobasidium vexans*, favoured by cool, cloudy, wet monsoon weather', '*Cephaleuros*', '*Colletotrichum*', 'A bacterium'], 0,
    'Translucent spots on young leaves become blisters; copper fungicides at short intervals control it.'],
  ['Red rust of tea is caused by:', ['A parasitic green alga, *Cephaleuros*', 'A rust fungus', 'A bacterium', 'A virus'], 0,
    'It attacks weak bushes; improving plant vigour and copper sprays help.'],
  ['Apple scab (*Venturia inaequalis*) starts each spring from:', ['Ascospores released from infected fallen leaves', 'Infected seeds', 'Insects', 'Soil nematodes'], 0,
    'Mills\' table predicts infection from leaf wetness and temperature; urea spray on fallen leaves speeds their decay.'],
  ['Panama wilt of banana is caused by:', ['*Fusarium oxysporum* f. sp. *cubense*', '*Ralstonia solanacearum* only', 'Banana bunchy top virus', '*Mycosphaerella musicola*'], 0,
    'Tropical race 4 (TR4) threatens Cavendish bananas; *Mycosphaerella* causes Sigatoka leaf spot.']
] }
);
