/* Concept sets for Botany II — Ecology and environment. Each block is linked to every PYQ (CSE + IFoS, all years) that asks this concept. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'B2', t: 'Ecology & Ecosystems', w: 3, pyq: ['CSE-2021-B2-m10', 'IFoS-2020-B2-m11', 'CSE-2015-B2-m07', 'IFoS-2014-B2-m11', 'CSE-2007-B2-m05', 'CSE-2005-B2-m03', 'CSE-1993-B2-m07', 'CSE-1991-B2-m05', 'CSE-1987-B2-m10', 'CSE-2013-B2-m07', 'IFoS-2015-B2-m10', 'IFoS-2013-B2-m08', 'IFoS-2007-B2-m10', 'IFoS-2002-B2-m08', 'IFoS-2001-B2-m06', 'CSE-1994-B2-m05', 'IFoS-2005-B2-m10', 'CSE-1992-B2-m16'], q: [
  ['The term "social forestry" was first used by:', ['J. C. Westoby (1968)', 'Brandis', 'Champion', 'Troup'], 0,
    'India took it up after the National Commission on Agriculture (1976).'],
  ['Social forestry mainly aims to:', ['Raise trees on non-forest land to meet local fuel, fodder and timber needs with people\'s participation', 'Clear forests for farming', 'Create national parks', 'Export timber'], 0,
    'It eases pressure on natural forests.'],
  ['Planting trees along roads, canals and railway lines is called:', ['Extension forestry', 'Farm forestry', 'Recreational forestry', 'Silvipasture'], 0,
    'Farm forestry is tree growing by farmers on their own land; village woodlots are community forestry.'],
  ['Afforestation differs from reforestation in that afforestation is:', ['Planting forest on land that has not been forest for a long time', 'Replanting a recently cleared forest', 'Felling trees', 'Natural regeneration only'], 0,
    'Deforestation is the permanent removal of forest cover.'],
  ['Shifting cultivation is called "jhum" in the North-East and in Andhra Pradesh and Odisha it is called:', ['Podu', 'Bewar', 'Kumri', 'Taungya'], 0,
    'It is slash-and-burn farming with forest fallows.'],
  ['The main ill-effect of shifting cultivation today is that:', ['Shortened fallow cycles cause soil erosion and forest degradation', 'It increases forest cover', 'It improves soil permanently', 'It reduces runoff'], 0,
    'Traditional long fallows (15–20 years) were sustainable.'],
  ['A criticism of large-scale *Eucalyptus* planting under social forestry was that:', ['Monocultures used much water and gave little fodder for local people', 'It grew too slowly', 'It was a nitrogen fixer', 'It was not saleable'], 0,
    'Mixed multipurpose species are now preferred.'],
  ['Joint Forest Management, launched in India in 1990, involves:', ['Forest departments and village communities sharing protection and benefits', 'Only private companies', 'Only the army', 'Only NGOs'], 0,
    'Village forest committees share produce.'],
  ['A fast-growing nitrogen-fixing tree widely used in social forestry is:', ['*Leucaena leucocephala*', '*Tectona grandis*', '*Shorea robusta*', '*Pinus roxburghii*'], 0,
    '*Casuarina* and *Acacia* are also common.'],
  ['Social forestry differs from agroforestry in that it:', ['Focuses on community and public land with people\'s participation', 'Is only on farmers\' fields with crops', 'Is only in reserved forests', 'Excludes local people'], 0,
    'Farm forestry overlaps both.']
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 3, pyq: ['CSE-2025-B2-m07', 'IFoS-2025-B2-m01', 'IFoS-2022-B2-m13', 'IFoS-2020-B2-m12', 'CSE-2017-B2-m11', 'IFoS-2006-B2-m09', 'CSE-2000-B2-m04', 'CSE-2020-B2-m10', 'CSE-2002-B2-m03', 'CSE-2006-B2-m07', 'CSE-1989-B2-m10', 'CSE-2012-B2-m04', 'CSE-2022-B2-m14', 'IFoS-2006-B2-m10', 'IFoS-2003-B2-m11', 'CSE-1998-B2-m03', 'IFoS-2015-B2-m06'], q: [
  ['Greenhouse gases warm the Earth by:', ['Absorbing outgoing infrared radiation and re-emitting it', 'Reflecting sunlight', 'Blocking ultraviolet only', 'Producing heat by reactions'], 0,
    'CO₂, CH₄, N₂O, CFCs, ozone and water vapour are the main ones.'],
  ['Over 100 years, methane has a global warming potential roughly:', ['28–30 times that of CO₂', 'Equal to CO₂', 'Half that of CO₂', '1,000 times that of CO₂'], 0,
    'N₂O is about 265–300 times; many CFCs are thousands of times.'],
  ['Atmospheric CO₂ has risen from about 280 ppm before industrialisation to roughly:', ['420 ppm in the early 2020s', '300 ppm', '1,000 ppm', '200 ppm'], 0,
    'Time-sensitive: the value keeps rising by about 2–3 ppm a year.'],
  ['A likely consequence of global warming is:', ['Sea-level rise, glacier retreat and shifting species ranges', 'Thicker ozone layer', 'Longer winters everywhere', 'Fewer extreme events'], 0,
    'Coral bleaching and changed crop yields are others.'],
  ['Stratospheric ozone is destroyed mainly by:', ['Chlorine atoms released from CFCs by UV light, acting catalytically', 'Carbon dioxide', 'Water vapour', 'Nitrogen gas'], 0,
    'Polar stratospheric clouds speed the reactions over Antarctica.'],
  ['The ozone layer protects life by absorbing:', ['Ultraviolet-B radiation', 'Infrared radiation', 'Visible light', 'Radio waves'], 0,
    'Ozone is measured in Dobson units.'],
  ['The international treaty to phase out ozone-depleting substances is the:', ['Montreal Protocol (1987)', 'Kyoto Protocol', 'Ramsar Convention', 'Basel Convention'], 0,
    'Its Kigali Amendment (2016) phases down HFCs.'],
  ['The Paris Agreement (2015) aims to hold warming to:', ['Well below 2 °C, pursuing 1.5 °C above pre-industrial levels', '4 °C', '0 °C', '3 °C'], 0,
    'Countries submit nationally determined contributions.'],
  ['Biomes are determined mainly by:', ['Temperature and precipitation', 'Soil colour', 'Altitude alone', 'Day length alone'], 0,
    'Whittaker plotted biomes against these two variables.'],
  ['Sustainable development was defined as meeting present needs without compromising future generations in the:', ['Brundtland Report, *Our Common Future* (1987)', 'Stockholm Conference (1972)', 'Rio Summit (1992)', 'Kyoto Protocol'], 0,
    'Climate change threatens sustainable development goals.']
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 3, pyq: ['CSE-2005-B2-m04', 'IFoS-2003-B2-m14', 'CSE-1996-B2-m03', 'CSE-1987-B2-m07', 'CSE-2014-B2-m09', 'IFoS-2003-B2-m15', 'IFoS-2000-B2-m13', 'CSE-1995-B2-m09', 'CSE-2024-B2-m07', 'CSE-2024-B2-m08', 'CSE-2015-B2-m06', 'CSE-2016-B2-m11', 'CSE-2001-B2-m06', 'IFoS-2015-B2-m12', 'IFoS-2014-B2-m12', 'IFoS-2021-B2-m15', 'CSE-1985-B2-m05', 'CSE-2011-B2-m11', 'CSE-2023-B2-m12', 'CSE-2000-B2-m05', 'CSE-2017-B2-m08', 'CSE-2013-B2-m08', 'CSE-2013-B2-m04', 'CSE-2013-B2-m06', 'CSE-2019-B2-m13', 'CSE-2016-B2-m13', 'CSE-1985-B2-m13', 'CSE-1999-B2-m13', 'IFoS-2004-B2-m07', 'IFoS-2000-B2-m06', 'IFoS-2000-B2-m09', 'CSE-1999-B2-m02', 'IFoS-2001-B2-m09', 'CSE-2011-B2-m01', 'CSE-2026-B2-m28'], q: [
  ['Sulphur dioxide in air comes mainly from:', ['Burning coal and smelting sulphide ores', 'Vehicle tyres', 'Forests', 'Oceans'], 0,
    'It causes leaf necrosis and acid rain.'],
  ['Rain is called acid rain when its pH is below about:', ['5.6', '7.0', '8.5', '3.0'], 0,
    'Normal rain is slightly acidic from dissolved CO₂.'],
  ['Eutrophication of lakes is caused mainly by:', ['Excess nitrogen and phosphorus', 'Excess oxygen', 'Low temperature', 'Heavy metals'], 0,
    'Algal blooms die and decompose, depleting oxygen and killing fish.'],
  ['A pond completely covered by *Eichhornia* is likely to have:', ['Low dissolved oxygen and nutrient enrichment', 'Very clear water', 'High oxygen everywhere', 'Low nutrients'], 0,
    'Water hyacinth is an invasive weed of eutrophic waters.'],
  ['Biomagnification means that a persistent pollutant such as DDT:', ['Increases in concentration at higher trophic levels', 'Decreases up the food chain', 'Stays the same at all levels', 'Disappears quickly'], 0,
    'It caused eggshell thinning in fish-eating birds.'],
  ['A non-point source of water pollution is:', ['Runoff from farm fields', 'A factory outfall pipe', 'A sewage treatment plant outlet', 'A power-plant drain'], 0,
    'Point sources discharge at an identifiable spot.'],
  ['The Environment (Protection) Act of India was passed in:', ['1986, after the Bhopal gas tragedy', '1972', '1980', '2002'], 0,
    'It is an umbrella law for environmental protection.'],
  ['Environmental Impact Assessment is done:', ['Before a development project to predict and reduce its environmental effects', 'After a project is finished only', 'Only for forests', 'Only for rivers'], 0,
    'In India it is governed by the EIA Notification, 2006.'],
  ['Cement dust harms broad-leaved plants mainly by:', ['Coating leaves, blocking stomata and light', 'Adding nitrogen', 'Increasing photosynthesis', 'Lowering soil pH'], 0,
    'The alkaline crust can also injure tissues.'],
  ['Disappearance of lichens from a once lichen-rich area most likely indicates:', ['Rising air pollution, especially SO₂', 'Better air quality', 'More rainfall', 'Soil erosion'], 0,
    'Lichens are sensitive bio-indicators.']
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 2, pyq: ['CSE-2024-B2-m06', 'CSE-2021-B2-m07', 'CSE-2019-B2-m16', 'CSE-2010-B2-m11', 'CSE-2015-B2-m04', 'CSE-2021-B2-m06', 'CSE-2019-B2-m11', 'CSE-1991-B2-m08', 'CSE-1987-B2-m08', 'IFoS-2005-B2-m07'], q: [
  ['A typical trait of an invasive alien plant is:', ['Fast growth, high seed output and few natural enemies in the new range', 'Slow growth and low seed output', 'Narrow habitat tolerance', 'Dependence on one pollinator'], 0,
    'The enemy-release hypothesis explains part of their success.'],
  ['Which is an invasive alien weed in India?', ['*Parthenium hysterophorus*', '*Shorea robusta*', '*Tectona grandis*', '*Azadirachta indica*'], 0,
    'Others: *Lantana camara*, *Eichhornia*, *Prosopis juliflora*, *Mikania*.'],
  ['The beetle used for biological control of *Parthenium* in India is:', ['*Zygogramma bicolorata*', '*Neochetina eichhorniae*', '*Cactoblastis cactorum*', '*Helicoverpa armigera*'], 0,
    '*Neochetina* weevils attack water hyacinth.'],
  ['*Cassia* species (e.g. *C. tora*, *C. sericea*) are used against *Parthenium* by:', ['Competitive displacement and allelopathy', 'Feeding on it', 'Infecting it with fungi', 'Shading only in water'], 0,
    'They grow fast in the same season.'],
  ['The "novel weapons" hypothesis explains invasions by:', ['Allelochemicals to which native plants are not adapted', 'Larger leaves', 'Lack of seeds', 'Dependence on humans'], 0,
    'Propagule pressure also matters.'],
  ['A plant indicator is a species whose presence shows:', ['A particular soil or environmental condition', 'Only the season', 'Only pollinators', 'Only rainfall'], 0,
    'E.g. *Salicornia* indicates saline soil.'],
  ['*Astragalus* species are classic indicators of soils rich in:', ['Selenium', 'Copper', 'Iron', 'Calcium'], 0,
    '*Viola calaminaria* indicates zinc.'],
  ['*Rumex acetosella* commonly indicates:', ['Acidic soils', 'Alkaline soils', 'Saline soils', 'Waterlogged soils'], 0,
    'Indicators help in land evaluation and prospecting.'],
  ['*Lantana camara* became invasive in India mainly after:', ['Introduction as an ornamental hedge plant', 'Use as a food crop', 'Planting as timber', 'Accidental arrival in grain'], 0,
    'It now invades many forest areas.'],
  ['Invasive species threaten biodiversity mainly by:', ['Outcompeting native species and changing habitats', 'Increasing native species', 'Improving soil fertility always', 'Reducing fires always'], 0,
    'They are a major driver of species loss worldwide.']
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 3, pyq: ['IFoS-2007-B2-m15', 'IFoS-2004-B2-m10', 'CSE-1997-B2-m05', 'CSE-1993-B2-m05', 'CSE-1986-B2-m13', 'CSE-2021-B2-m11', 'CSE-2001-B2-m05', 'CSE-1993-B2-m04', 'CSE-1985-B2-m04', 'IFoS-2020-B2-m10', 'CSE-2018-B2-m07', 'CSE-1997-B2-m06', 'CSE-2023-B2-m11', 'CSE-2019-B2-m12', 'CSE-2020-B2-m11', 'CSE-1994-B2-m11', 'CSE-2016-B2-m09', 'CSE-2010-B2-m09', 'CSE-2003-B2-m07', 'IFoS-2002-B2-m13', 'IFoS-2002-B2-m14', 'CSE-1998-B2-m07', 'CSE-2016-B2-m10', 'CSE-2023-B2-m07', 'CSE-2011-B2-m10', 'IFoS-2010-B2-m09', 'CSE-2012-B2-m08', 'CSE-2006-B2-m03', 'CSE-2003-B2-m13', 'CSE-1992-B2-m13', 'CSE-2010-B2-m25', 'CSE-1986-B2-m17'], q: [
  ['The term "ecosystem" was coined by:', ['A. G. Tansley (1935)', 'Haeckel', 'Odum', 'Lindeman'], 0,
    'Haeckel coined "ecology" (1866).'],
  ['Lindeman\'s "ten per cent law" says that:', ['About 10% of energy at one trophic level passes to the next', '10% of species are producers', '10% of nutrients are recycled', '10% of light is absorbed'], 0,
    'Most energy is lost as heat in respiration.'],
  ['The pyramid of energy is always upright because:', ['Energy is lost as heat at every transfer and cannot be recycled', 'Producers are always fewer', 'Consumers are larger', 'Biomass increases upward'], 0,
    'This follows the second law of thermodynamics.'],
  ['An inverted pyramid of biomass is seen in:', ['Open-water aquatic ecosystems, where phytoplankton turn over quickly', 'Grasslands', 'Forests', 'Deserts'], 0,
    'An inverted pyramid of numbers occurs in a tree with many insects.'],
  ['Detritus food chains begin with:', ['Dead organic matter broken down by decomposers', 'Green plants eaten by herbivores', 'Carnivores', 'Parasites'], 0,
    'In forests most energy flows through detritus chains.'],
  ['Hutchinson defined the ecological niche as:', ['An n-dimensional hypervolume of conditions and resources', 'The physical habitat only', 'The trophic role only', 'The home range'], 0,
    'Grinnell stressed habitat; Elton stressed the functional role.'],
  ['Gause\'s competitive exclusion principle states that:', ['Two species with identical niches cannot coexist indefinitely', 'All species coexist', 'Predators remove competition', 'Niches always overlap fully'], 0,
    'Niche overlap leads to competition.'],
  ['Liebig\'s law of the minimum states that growth is limited by:', ['The resource in shortest supply relative to need', 'The most abundant resource', 'Temperature only', 'Light only'], 0,
    'Shelford added upper and lower limits of tolerance.'],
  ['Deep lakes in cold regions do not freeze to the bottom because:', ['Water is densest at 4 °C, so ice floats and insulates the water below', 'Salt prevents freezing', 'Fish produce heat', 'Wind keeps them liquid'], 0,
    'Aquatic life survives under the ice.'],
  ['An ecosystem\'s abiotic components include:', ['Light, temperature, water, soil and nutrients', 'Producers', 'Decomposers', 'Consumers'], 0,
    'Biotic components are producers, consumers and decomposers.']
] },
{ p: 'B2', t: 'Plant Geography, Forests & Biodiversity', w: 3, pyq: ['CSE-2023-B2-m10', 'CSE-2018-B2-m08', 'CSE-2013-B2-m05', 'CSE-2002-B2-m05', 'CSE-1995-B2-m10', 'CSE-2025-B2-m05', 'CSE-2021-B2-m08', 'CSE-2012-B2-m05', 'IFoS-2019-B2-m11', 'IFoS-2010-B2-m11', 'CSE-2014-B2-m06', 'CSE-2017-B2-m07', 'CSE-1991-B2-m07', 'CSE-1988-B2-m10', 'IFoS-2012-B2-m10', 'IFoS-2005-B2-m08'], q: [
  ['Which IUCN category is the most threatened among living wild species?', ['Critically Endangered', 'Endangered', 'Vulnerable', 'Near Threatened'], 0,
    'Order: EX, EW, CR, EN, VU, NT, LC; also DD and NE.'],
  ['"Threatened" species in the IUCN Red List are those in:', ['Critically Endangered, Endangered and Vulnerable', 'Near Threatened and Least Concern', 'Extinct and Extinct in the Wild', 'Data Deficient'], 0,
    'Near Threatened is close to qualifying but not threatened.'],
  ['IUCN Red List criteria A to E are based on:', ['Population decline, range size, small population size, very small population and extinction-risk analysis', 'Plant height', 'Economic value', 'Flower colour'], 0,
    'Each category has quantitative thresholds.'],
  ['The Red Data Book of Indian Plants was published by:', ['The Botanical Survey of India (Nayar and Sastry)', 'The Forest Research Institute', 'ICAR', 'WWF'], 0,
    'IUCN published the first Red Data Books in the 1960s.'],
  ['In the original Red Data Books, pink pages listed:', ['Critically endangered species', 'Recovered species', 'Extinct species', 'Common species'], 0,
    'Green pages listed species that had recovered.'],
  ['Biosphere reserves are designated under UNESCO\'s:', ['Man and the Biosphere (MAB) programme, started in 1971', 'Ramsar Convention', 'World Heritage Convention', 'CITES'], 0,
    'India\'s first was the Nilgiri Biosphere Reserve (1986).'],
  ['A biosphere reserve is zoned into:', ['Core, buffer and transition zones', 'Core zone only', 'Tiger and elephant zones', 'Urban and rural zones'], 0,
    'Human activity is allowed in the buffer and transition zones.'],
  ['India has 18 biosphere reserves, of which the number in UNESCO\'s world network is about:', ['12–13', '2', '18', '30'], 0,
    'Time-sensitive: check the latest UNESCO listing.'],
  ['National parks and wildlife sanctuaries in India are created under the:', ['Wildlife (Protection) Act, 1972', 'Forest Act, 1927', 'Biological Diversity Act, 2002', 'EP Act, 1986'], 0,
    'Conservation and community reserves were added in 2002.'],
  ['The biosphere is:', ['The part of Earth — land, water and air — where life exists', 'Only the oceans', 'Only forests', 'Only the atmosphere'], 0,
    'It includes lithosphere, hydrosphere and atmosphere where they support life.']
] },
{ p: 'B2', t: 'Plant Geography, Forests & Biodiversity', w: 2, pyq: ['IFoS-2020-B2-m08', 'IFoS-2019-B2-m10', 'CSE-2021-B2-m12', 'CSE-2014-B2-m08', 'CSE-2012-B2-m06', 'CSE-2015-B2-m05', 'CSE-1998-B2-m06'], q: [
  ['Alpha diversity refers to:', ['Species diversity within a single habitat or community', 'Change in species between habitats', 'Diversity of a whole region', 'Genetic diversity'], 0,
    'Beta is turnover between habitats; gamma is regional diversity (Whittaker).'],
  ['Beta diversity measures:', ['The change in species composition between habitats', 'Diversity within one plot', 'Total regional diversity', 'Number of genes'], 0,
    'It is high along steep gradients.'],
  ['A commonly used index of species diversity is:', ['Shannon–Wiener index', 'Hardy–Weinberg index', 'Lincoln index', 'Mohs index'], 0,
    'Simpson\'s index is another.'],
  ['The three levels of biodiversity are:', ['Genetic, species and ecosystem diversity', 'Plant, animal and microbe', 'Alpha, beta and gamma only', 'Land, water and air'], 0,
    'Conservation must cover all three.'],
  ['The 17 Sustainable Development Goals were adopted by the UN in:', ['2015', '1992', '2000', '1987'], 0,
    'They run to 2030.'],
  ['Which is a renewable energy source?', ['Wind', 'Coal', 'Natural gas', 'Uranium'], 0,
    'Solar, hydro, biomass, geothermal and tidal are others.'],
  ['Energy plantations are:', ['Fast-growing trees grown for fuelwood or biomass energy', 'Plantations of sugarcane only', 'Solar farms', 'Coal fields'], 0,
    'E.g. *Leucaena*, *Casuarina*, *Eucalyptus*, *Prosopis*.'],
  ['The "option value" of biodiversity refers to:', ['Possible future uses not yet known', 'Present food use', 'Timber sales', 'Tourism income'], 0,
    'Others: consumptive, productive, aesthetic and ethical values.'],
  ['Tropical regions are richer in species than temperate regions partly because they have:', ['Stable climates, high energy input and long evolutionary time', 'Short growing seasons', 'Low rainfall', 'Fewer habitats'], 0,
    'More niches allow finer specialisation.'],
  ['A core idea of sustainable development is:', ['Balancing economic growth, social equity and environmental protection', 'Maximising short-term growth only', 'Stopping all development', 'Using non-renewable resources faster'], 0,
    'Often called the three pillars.']
] },
{ p: 'B2', t: 'Ecology & Ecosystems', w: 2, pyq: ['CSE-2019-B2-m15', 'CSE-2018-B2-m10', 'CSE-2007-B2-m04', 'CSE-1991-B2-m06', 'CSE-2011-B2-m12', 'IFoS-2024-B2-m09', 'CSE-1998-B2-m09', 'CSE-1986-B2-m12', 'CSE-2019-B2-m14', 'IFoS-2014-B2-m10', 'IFoS-2001-B2-m10', 'CSE-1990-B2-m04', 'CSE-1989-B2-m23', 'IFoS-2000-B2-m07'], q: [
  ['The Importance Value Index (IVI) of a species is the sum of its:', ['Relative density, relative frequency and relative dominance', 'Height and girth', 'Number of seeds and leaves', 'Cover and biomass'], 0,
    'It ranks species in a community; maximum is 300.'],
  ['Frequency in community analysis is:', ['The percentage of sample plots in which a species occurs', 'The number of individuals per area', 'The area covered by a species', 'The number of species'], 0,
    'Raunkiaer grouped frequencies into classes A–E.'],
  ['Raunkiaer\'s life forms are classified by:', ['The position of perennating buds during the unfavourable season', 'Leaf size', 'Flower colour', 'Root depth'], 0,
    'Phanerophytes, chamaephytes, hemicryptophytes, cryptophytes and therophytes.'],
  ['Therophytes are:', ['Annuals that survive the bad season as seeds', 'Trees', 'Plants with buds at soil level', 'Underground bulbs'], 0,
    'They dominate deserts.'],
  ['A typical xerophytic adaptation is:', ['Sunken stomata with a thick cuticle', 'Large thin leaves', 'Aerenchyma in roots', 'Floating leaves'], 0,
    'Others: phylloclades, deep roots, CAM and reduced leaves.'],
  ['Desert ephemerals cope with drought by:', ['Completing their life cycle quickly after rain (drought escape)', 'Storing water in stems', 'Deep roots', 'CAM metabolism'], 0,
    'Succulents endure drought by storing water.'],
  ['Pneumatophores, typical of *Avicennia* mangroves, are:', ['Upward-growing roots that take in air', 'Stilt roots', 'Storage roots', 'Buttress roots'], 0,
    '*Rhizophora* has stilt roots; both show vivipary.'],
  ['Mangroves protect coasts because they:', ['Bind sediments and absorb wave and storm energy', 'Increase erosion', 'Lower sea level', 'Grow only inland'], 0,
    'The Sundarbans is the largest mangrove forest.'],
  ['An ecotone is:', ['A transition zone between two communities, often rich in species', 'The centre of a community', 'A desert', 'A climax'], 0,
    'Higher diversity there is called the edge effect.'],
  ['Restoring a barren, drought-prone hill slope usually begins with:', ['Soil and water conservation (contour trenches, check dams) and hardy multipurpose trees', 'Clear-felling', 'Planting water-hungry crops', 'Leaving it bare'], 0,
    'A watershed approach with community involvement works best.']
] }
);
