/* Concept sets for Agriculture II — insect pests and their management: IPM, control methods, semiochemicals, insecticides, formulations, biopesticides, quarantine, and pests of field crops, fruits, vegetables and non-insect pests. */
(window.IFOS_BANK = window.IFOS_BANK || []).push(
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: ['CSE-2023-A2-m25', 'IFoS-2019-A2-m19', 'CSE-2018-A2-m25', 'IFoS-2015-A2-m31', 'CSE-2011-A2-m28', 'IFoS-2011-A2-m24', 'CSE-2010-A2-m25', 'IFoS-2009-A2-m14', 'CSE-2007-A2-m24', 'IFoS-2005-A2-m29', 'CSE-2005-A2-m20', 'CSE-2004-A2-m24', 'IFoS-2003-A2-m28', 'CSE-2002-A2-m23', 'IFoS-2001-A2-m30', 'IFoS-2001-A2-m32', 'CSE-1997-A2-m25', 'CSE-1995-A2-m27', 'CSE-1990-A2-m33', 'IFoS-2023-A2-m34', 'IFoS-2022-A2-m29', 'IFoS-2020-A2-m27', 'IFoS-2017-A2-Q6a', 'IFoS-2006-A2-m28', 'CSE-2000-A2-m32', 'CSE-2021-A2-m25', 'CSE-2016-A2-m29', 'IFoS-2016-A2-m23', 'CSE-2001-A2-m27', 'CSE-1994-A2-m15', 'IFoS-2005-A2-m30'], q: [
  ['Integrated pest management (IPM) aims to:', ['Keep pest populations below the economic injury level by combining compatible methods with least harm to people and environment', 'Eradicate every insect from the field', 'Rely on calendar-based pesticide sprays', 'Use only biological control'], 0,
    'Chemicals are used only when needed, as a last resort, after cultural, mechanical, biological and host-resistance methods.'],
  ['The economic injury level (EIL) is:', ['The lowest pest density at which the damage caused equals the cost of control', 'The pest density at which spraying must start', 'The average pest density over many years', 'Any pest density above zero'], 0,
    'Below EIL, controlling the pest costs more than the crop it saves.'],
  ['The economic threshold level (ETL) differs from EIL in that ETL:', ['Is set below the EIL so control can begin before the pest reaches damaging numbers', 'Is always higher than the EIL', 'Is the same as the EIL', 'Ignores the cost of control'], 0,
    'ETL is the "action threshold"; it gives time for control to work.'],
  ['In Pedigo\'s formula EIL = C / (V × I × D × K), C stands for:', ['Cost of the control measure per unit area', 'Crop yield', 'Number of insects counted', 'Climate index'], 0,
    'V = market value of produce, I = injury per insect, D = damage per unit injury, K = proportion of the pest killed.'],
  ['The general equilibrium position (GEP) of a pest is:', ['Its average population density over a long period, around which numbers fluctuate', 'The density at which it is eradicated', 'The ETL', 'The peak population in an outbreak'], 0,
    'A key pest has its GEP above the EIL; an occasional pest only sometimes crosses it.'],
  ['A commonly used ETL for rice yellow stem borer at the vegetative stage is about:', ['5% dead hearts', '50% dead hearts', '1 egg mass per hectare', '25% white ears'], 0,
    'At the reproductive stage, about 2% white ears (or 1 moth or egg mass per m²) is used.'],
  ['Agro-ecosystem analysis (AESA) in Indian IPM programmes bases spray decisions on:', ['Weekly field observation of crop health, weather, pests and natural enemies (pest–defender ratio)', 'A fixed spray calendar', 'Market prices only', 'Soil test values only'], 0,
    'If defenders are enough to check pests, spraying is skipped.'],
  ['Farmer Field Schools for IPM, now used widely in India, began with:', ['FAO-supported rice IPM in Indonesia in the late 1980s', 'Cotton growers in Punjab in 2010', 'The Green Revolution in 1966', 'Coffee estates in Karnataka'], 0,
    'Farmers learn by observing their own fields through the season.'],
  ['In Bt cotton, a refuge of non-Bt cotton is planted mainly to:', ['Delay the build-up of bollworm resistance to Bt toxins', 'Increase fibre length', 'Attract pollinators', 'Fix nitrogen'], 0,
    'Susceptible moths from the refuge mate with any resistant survivors, diluting resistance genes.'],
  ['A major constraint to adoption of IPM by Indian farmers is:', ['It needs knowledge and timely field monitoring, and bioagents are often not available when needed', 'It always lowers yields', 'It is banned in some states', 'It needs no inputs at all'], 0,
    'Farmers also prefer the quick, visible effect of chemical sprays.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 2, pyq: ['CSE-2022-A2-m23', 'CSE-2000-A2-m30', 'IFoS-2009-A2-m10', 'CSE-2006-A2-m22', 'CSE-2002-A2-m22', 'CSE-2012-A2-m24', 'IFoS-2010-A2-m24', 'CSE-1990-A2-m36', 'CSE-2004-A2-m22', 'CSE-2004-A2-m09', 'CSE-2012-A2-m25'], q: [
  ['Summer (deep) ploughing helps control pests mainly by:', ['Exposing soil-dwelling pupae and larvae to heat and birds', 'Adding nitrogen to soil', 'Attracting natural enemies indoors', 'Killing pests with chemicals'], 0,
    'It is a cultural method, used against cutworms, white grubs and *Helicoverpa* pupae.'],
  ['Sorghum shoot fly damage is reduced culturally by:', ['Early sowing at the onset of monsoon and a higher seed rate', 'Late sowing in October', 'Flood irrigation', 'Removing all weeds by burning'], 0,
    'Adjusting sowing time to escape peak pest activity is a classic cultural control.'],
  ['Yellow sticky traps are mainly used to monitor and trap:', ['Whiteflies and aphids', 'Termites', 'Rats', 'Nematodes'], 0,
    'Blue sticky traps attract thrips; light traps attract night-flying moths and hoppers.'],
  ['Pest resurgence means:', ['An abnormal rise in a pest after insecticide use, because its natural enemies were killed', 'A pest becoming extinct', 'A pest moving to a new country', 'The return of a pest each year at normal levels'], 0,
    'E.g. brown planthopper in rice after repeated synthetic pyrethroid sprays.'],
  ['A secondary pest outbreak occurs when:', ['A minor pest becomes serious after the key pest and its natural enemies are suppressed by sprays', 'Two key pests appear together', 'A pest is introduced from abroad', 'A pest develops a new host'], 0,
    'Spider mites and whiteflies often flare up after broad-spectrum sprays.'],
  ['A feature of modern intensive agriculture that tends to increase pest problems is:', ['Monoculture of high-yielding varieties with heavy nitrogen and irrigation', 'Mixed cropping of local varieties', 'Low fertiliser use', 'Crop rotation with legumes'], 0,
    'Lush, uniform crops favour sucking pests such as BPH and leaf folder in rice.'],
  ['Pest forecasting predicts outbreaks mainly from:', ['Weather data together with pest counts from surveys, light traps and pheromone traps', 'Market prices of pesticides', 'Soil colour', 'Number of farmers in a village'], 0,
    'ICAR-NCIPM, New Delhi, coordinates pest surveillance and forecasting.'],
  ['Legislative control of pests includes:', ['Quarantine laws and laws regulating pesticides, such as the Insecticides Act, 1968', 'Hand picking of larvae', 'Release of predators', 'Crop rotation'], 0,
    'The Destructive Insects and Pests Act, 1914 is the basis of plant quarantine in India.'],
  ['A "pest" in agriculture is best defined as:', ['Any organism whose numbers cause economic loss to crops or produce', 'Any insect found in a field', 'Only insects that bite humans', 'Any organism living in soil'], 0,
    'Pests include insects, mites, nematodes, rodents, birds, snails and weeds.'],
  ['Mechanical or physical control includes:', ['Hand picking, light traps, bagging fruits and heat or cold treatments', 'Spraying neem oil', 'Releasing *Trichogramma*', 'Growing resistant varieties'], 0,
    'Rachel Carson\'s "Silent Spring" (1962) pushed the world towards such non-chemical methods.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 2, pyq: ['CSE-2011-A2-m28', 'CSE-2010-A2-m25', 'IFoS-2001-A2-m30', 'CSE-1995-A2-m27', 'IFoS-2000-A2-m19', 'CSE-1996-A2-m25', 'IFoS-2001-A2-m26', 'CSE-2002-A2-m26', 'CSE-2006-A2-m14', 'CSE-1989-A2-m11', 'CSE-2016-A2-m30', 'CSE-1989-A2-m42', 'IFoS-2015-A2-m07', 'CSE-2002-A2-m02', 'CSE-2009-A2-m04', 'IFoS-2006-A2-m08'], q: [
  ['Pheromones are chemicals that:', ['Are released by an animal and change the behaviour of other members of the same species', 'Are released by plants to kill insects', 'Are synthetic insecticides', 'Act only between different species'], 0,
    'Sex, aggregation, alarm and trail pheromones are the main types.'],
  ['A kairomone is a chemical signal that:', ['Benefits the receiver of another species, not the emitter', 'Benefits only the emitter', 'Benefits both species', 'Acts within one species'], 0,
    'Allomones benefit the emitter (e.g. repellents); synomones benefit both.'],
  ['Pheromone traps in pest management are used for:', ['Monitoring, mass trapping and mating disruption', 'Killing larvae by contact', 'Improving soil fertility', 'Killing fungal spores'], 0,
    'Gossyplure is used for mating disruption of pink bollworm.'],
  ['Methyl eugenol traps are used to attract:', ['Males of the oriental fruit fly *Bactrocera dorsalis*', 'Females of rice stem borer', 'Aphids', 'Termite workers'], 0,
    'Cue-lure attracts male melon flies (*Zeugodacus cucurbitae*).'],
  ['Juvenile hormone (JH) in insects is secreted by the:', ['Corpora allata, and it keeps larval characters during moults', 'Prothoracic glands', 'Salivary glands', 'Malpighian tubules'], 0,
    'JH analogues such as methoprene and pyriproxyfen disrupt metamorphosis.'],
  ['Moulting hormone (ecdysone) is secreted by the:', ['Prothoracic glands, stimulated by brain hormone (PTTH)', 'Corpora allata', 'Fat body', 'Midgut'], 0,
    'High JH with ecdysone gives a larval moult; low JH gives pupa or adult.'],
  ['Diflubenzuron controls insects by:', ['Inhibiting chitin synthesis, so moulting fails', 'Blocking sodium channels', 'Inhibiting acetylcholinesterase', 'Acting as a stomach fumigant'], 0,
    'It is an insect growth regulator (benzoylphenyl urea), safe for vertebrates.'],
  ['Azadirachtin from neem acts on insects mainly as a:', ['Antifeedant, growth regulator and oviposition deterrent', 'Fast knockdown nerve poison', 'Fumigant', 'Fungicide only'], 0,
    'Neem seed kernel extract (5%) and neem oil are widely used botanicals.'],
  ['Pyrethrum, a classical botanical insecticide, is obtained from the flowers of:', ['*Tanacetum (Chrysanthemum) cinerariifolium*', '*Nicotiana tabacum*', '*Derris elliptica*', '*Azadirachta indica*'], 0,
    'Rotenone comes from *Derris* roots and nicotine from tobacco.'],
  ['The sterile insect technique (SIT) controls pests by:', ['Releasing large numbers of radiation-sterilised males that mate without producing offspring', 'Spraying radioactive chemicals on crops', 'Irradiating crops to kill eggs', 'Releasing sterile females only'], 0,
    'E. F. Knipling used it to eradicate the screwworm fly from the USA; gamma rays from cobalt-60 are used.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: ['IFoS-2004-A2-m29', 'CSE-2010-A2-m28', 'CSE-1995-A2-m28', 'IFoS-2019-A2-m21', 'CSE-2024-A2-m24', 'CSE-1993-A2-m43', 'CSE-1989-A2-m43', 'IFoS-2009-A2-m13', 'IFoS-2001-A2-m31', 'CSE-2020-A2-m24', 'CSE-1999-A2-m19', 'CSE-2007-A2-m26', 'CSE-2019-A2-m26', 'CSE-2003-A2-m25', 'CSE-2002-A2-m22', 'CSE-1997-A2-m03', 'CSE-2007-A2-m02', 'CSE-2002-A2-m03', 'IFoS-2012-A2-m08', 'CSE-1996-A2-m04'], q: [
  ['Organophosphate and carbamate insecticides kill insects by:', ['Inhibiting acetylcholinesterase, so acetylcholine builds up at nerve synapses', 'Blocking chitin synthesis', 'Destroying the gut wall', 'Blocking respiration in mitochondria only'], 0,
    'Organophosphates phosphorylate the enzyme (nearly irreversible); carbamates carbamylate it (reversible).'],
  ['Synthetic pyrethroids such as cypermethrin and deltamethrin act by:', ['Keeping voltage-gated sodium channels in nerves open', 'Inhibiting acetylcholinesterase', 'Inhibiting chitin synthesis', 'Acting as juvenile hormones'], 0,
    'They have low mammalian toxicity but are highly toxic to fish and bees.'],
  ['Neonicotinoids such as imidacloprid act on:', ['Nicotinic acetylcholine receptors, as agonists', 'GABA-gated chloride channels', 'Ryanodine receptors', 'Sodium channels'], 0,
    'They are systemic and widely used against sucking pests; fipronil acts on GABA channels, diamides on ryanodine receptors.'],
  ['A systemic insecticide is one that:', ['Is absorbed and moved in the plant sap, so it kills sucking insects feeding on it', 'Kills only on contact with the insect body', 'Acts only as a fumigant in storage', 'Stays on the leaf surface'], 0,
    'Dimethoate and imidacloprid are examples.'],
  ['Carroll Williams (1967) called insect-hormone based insecticides:', ['Third-generation pesticides', 'First-generation pesticides', 'Fourth-generation pesticides', 'Botanical pesticides'], 0,
    'First generation = inorganics and botanicals; second = synthetic organics like DDT; anti-hormones such as precocenes were called fourth generation.'],
  ['Pesticides are classified by target pest; an acaricide is used against:', ['Mites and ticks', 'Nematodes', 'Rodents', 'Snails'], 0,
    'Nematicides kill nematodes, rodenticides rats, molluscicides snails and slugs.'],
  ['Insecticide resistance is:', ['An inherited ability of a pest strain to survive doses that would kill most individuals of a normal population', 'Tolerance of a crop to an insecticide', 'The time an insecticide stays active', 'The repellence of a chemical'], 0,
    'It arises from selection pressure of repeated use of the same chemical.'],
  ['Cross-resistance differs from multiple resistance in that cross-resistance:', ['Arises from one mechanism that also protects against other, related chemicals', 'Needs several independent mechanisms', 'Is resistance in a crop, not a pest', 'Occurs only with biopesticides'], 0,
    'Multiple resistance involves separate mechanisms against different insecticide groups.'],
  ['A common biochemical mechanism of insecticide resistance is:', ['Faster detoxification by enzymes such as esterases, cytochrome P450 oxidases and glutathione S-transferases', 'Thicker plant cuticle', 'Higher soil pH', 'Slower photosynthesis'], 0,
    'Target-site insensitivity (kdr for pyrethroids, altered AChE) and reduced penetration are others.'],
  ['A sound insecticide resistance management practice is to:', ['Rotate insecticides with different modes of action and use them only when ETL is crossed', 'Spray the same chemical at a lower dose every week', 'Mix many chemicals in every spray', 'Increase dose each season'], 0,
    'IRAC mode-of-action group numbers on labels help rotation.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 2, pyq: ['CSE-2022-A2-m21', 'CSE-2021-A2-m23', 'CSE-2006-A2-m23', 'IFoS-2002-A2-m21', 'CSE-2022-A2-m22', 'CSE-1999-A2-m21', 'CSE-2006-A2-m21', 'IFoS-2005-A2-m31', 'CSE-1999-A2-m20', 'CSE-2010-A2-m18', 'CSE-2014-A2-m28', 'IFoS-2021-A2-m28', 'CSE-1997-A2-m01', 'IFoS-2012-A2-m05'], q: [
  ['A pesticide formulation is:', ['The active ingredient mixed with carriers, solvents and adjuvants to make it safe and easy to apply', 'The pure active ingredient', 'The trade name only', 'A mixture of two pesticides'], 0,
    'The active ingredient (a.i.) is the part that kills the pest; the rest are inert ingredients.'],
  ['An emulsifiable concentrate (EC) is:', ['The active ingredient dissolved in an organic solvent with an emulsifier, forming a milky emulsion in water', 'A dry powder that is dusted', 'A granule for soil use', 'A gas for fumigation'], 0,
    'E.g. Chlorpyriphos 20 EC has 20% active ingredient.'],
  ['A wettable powder (WP):', ['Forms a suspension in water and needs constant agitation during spraying', 'Dissolves completely in water', 'Is applied dry without water', 'Is a liquid concentrate'], 0,
    'Soluble powders (SP) dissolve fully; WPs only suspend.'],
  ['Granular formulations are preferred in some situations because they:', ['Are applied to soil or leaf whorls with little drift and safer handling', 'Act instantly on the leaf surface', 'Need large volumes of water', 'Are always cheaper than sprays'], 0,
    'E.g. cartap hydrochloride 4G in rice against stem borer.'],
  ['In India the toxicity label colour for an extremely toxic pesticide is:', ['Red', 'Yellow', 'Blue', 'Green'], 0,
    'Red = extremely toxic, yellow = highly, blue = moderately, green = slightly toxic (Insecticides Rules, 1971).'],
  ['LD50 is the:', ['Dose (mg per kg body weight) that kills 50% of test animals; a lower LD50 means a more toxic chemical', 'Dose that kills all pests', 'Concentration in the spray tank', 'Residue limit in food'], 0,
    'Oral and dermal LD50 are measured separately.'],
  ['The waiting period (pre-harvest interval) is:', ['The time between the last spray and harvest, so residues fall below the maximum residue limit', 'The time a pesticide is stored before use', 'The interval between two sprays', 'The time taken for a pest to die'], 0,
    'It is printed on the label and leaflet.'],
  ['Organophosphate poisoning is treated with:', ['Atropine sulphate, with an oxime such as pralidoxime (2-PAM)', 'Vitamin K', 'BAL (dimercaprol)', 'Sodium bicarbonate only'], 0,
    'Symptoms include salivation, sweating, pinpoint pupils, muscle twitching and breathing difficulty. Vitamin K is the antidote for anticoagulant rodenticides.'],
  ['When seeds need fungicide, insecticide and *Rhizobium* treatment, the correct order is:', ['Fungicide first, then insecticide, and *Rhizobium* last just before sowing', '*Rhizobium* first, then fungicide', 'All mixed together at once', 'Insecticide only, never *Rhizobium*'], 0,
    'The "FIR" order limits harm to the inoculant; many chemicals are toxic to *Rhizobium*.'],
  ['A safe practice in pesticide use is to:', ['Wear protective clothing, spray with the wind behind you, and never eat or smoke while spraying', 'Spray against the wind', 'Store pesticides with food grains', 'Reuse empty containers for water'], 0,
    'Empty containers should be punctured and buried away from water sources.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 3, pyq: ['IFoS-2010-A2-m26', 'CSE-2007-A2-m25', 'IFoS-2006-A2-m27', 'IFoS-2001-A2-m25', 'CSE-2000-A2-m31', 'CSE-2004-A2-m23', 'CSE-1999-A2-m22', 'IFoS-2001-A2-m24', 'IFoS-2021-A2-m25', 'IFoS-2014-A2-m17', 'CSE-2010-A2-m16', 'CSE-2012-A2-m26'], q: [
  ['Biopesticides are:', ['Pest control agents based on living organisms or natural products, such as microbes, botanicals and pheromones', 'Synthetic chemicals with low toxicity', 'Chemical fertilisers', 'Genetically modified crops only'], 0,
    'Microbial pesticides use bacteria, fungi, viruses, protozoa or nematodes.'],
  ['Nuclear polyhedrosis viruses (NPVs) are:', ['Baculoviruses that form polyhedral occlusion bodies in the nuclei of infected larvae', 'Plant viruses spread by aphids', 'Fungi that attack insects', 'Bacteria in insect guts'], 0,
    'HaNPV targets *Helicoverpa armigera*; SlNPV targets *Spodoptera litura*.'],
  ['The dose of HaNPV is commonly expressed as:', ['Larval equivalents (LE) per hectare, e.g. about 250 LE/ha', 'Kilograms of active ingredient', 'Parts per million in soil', 'Litres of EC'], 0,
    'One LE is the virus yield from one fully infected larva.'],
  ['Larvae killed by NPV typically:', ['Climb to the top of plants and hang limp and head-down, with liquefied bodies', 'Become hard and white with fungal growth', 'Turn black and dry immediately', 'Burrow deep into the soil'], 0,
    'This is called "tree-top disease"; sprays are best given in the evening as UV light inactivates the virus.'],
  ['NPV for field use is mass-produced:', ['In live host larvae reared on artificial diet', 'In fermenters with sugar media', 'On rice grains', 'In soil'], 0,
    'Viruses multiply only in living cells, unlike Bt or fungi.'],
  ['White muscardine disease of insects is caused by:', ['*Beauveria bassiana*', '*Metarhizium anisopliae*', '*Bacillus thuringiensis*', '*Trichoderma viride*'], 0,
    '*Metarhizium* causes green muscardine; *Lecanicillium lecanii* attacks aphids and whiteflies.'],
  ['Entomopathogenic fungi differ from bacteria and viruses in that they:', ['Infect by penetrating the insect cuticle directly, so they can kill sucking insects', 'Must be eaten to infect', 'Work best in dry, hot weather', 'Kill only beetles'], 0,
    'They need high humidity for spore germination.'],
  ['A main limitation of microbial pesticides is:', ['Slow action, short shelf life and sensitivity to sunlight', 'High toxicity to humans', 'Leaving harmful residues', 'Killing all natural enemies'], 0,
    'Their strengths are target specificity and safety.'],
  ['Biopesticides in India must be registered under the:', ['Insecticides Act, 1968, through the Central Insecticides Board and Registration Committee (CIB&RC)', 'Seeds Act, 1966', 'Fertiliser Control Order', 'Environment Protection Act only'], 0,
    'Quality issues with unregistered products remain a concern.'],
  ['Microbial control of the American bollworm (*Helicoverpa armigera*) can use:', ['HaNPV and *Bacillus thuringiensis* var. *kurstaki* sprays', '*Trichoderma* seed treatment', '*Rhizobium* inoculation', 'Copper oxychloride'], 0,
    'They fit IPM along with *Trichogramma* releases and pheromone traps.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 2, pyq: ['CSE-2021-A2-m24', 'IFoS-2021-A2-m24', 'CSE-1995-A2-m29', 'CSE-2014-A2-m27', 'CSE-2017-A2-m27', 'CSE-2012-A2-m25', 'CSE-2015-A2-m14', 'CSE-2011-A2-m19'], q: [
  ['Plant quarantine is:', ['Legal restriction on movement of plants and plant products to stop the entry and spread of pests and diseases', 'Spraying pesticides at ports', 'Storing seed in cold rooms', 'Breeding resistant varieties'], 0,
    'It is the first line of defence against exotic pests.'],
  ['India\'s first plant quarantine law was the:', ['Destructive Insects and Pests (DIP) Act, 1914', 'Insecticides Act, 1968', 'Seeds Act, 1966', 'Biological Diversity Act, 2002'], 0,
    'The Plant Quarantine (Regulation of Import into India) Order, 2003 is issued under it.'],
  ['Plant quarantine in India is enforced by the:', ['Directorate of Plant Protection, Quarantine and Storage (DPPQS), Faridabad', 'FSSAI', 'Central Water Commission', 'NABARD'], 0,
    'It runs plant quarantine stations at seaports, airports and land borders.'],
  ['Import of plant germplasm for research in India is quarantined by:', ['ICAR-NBPGR, New Delhi', 'ICAR-IARI only', 'Forest Survey of India', 'State seed corporations'], 0,
    'Imports need an import permit and a phytosanitary certificate from the exporting country.'],
  ['A domestic quarantine in India restricts movement of potato from parts of:', ['West Bengal (Darjeeling) because of potato wart', 'Punjab because of late blight', 'Gujarat because of aphids', 'Bihar because of tuber moth'], 0,
    'Potato wart is caused by *Synchytrium endobioticum*; golden cyst nematode is under domestic quarantine in the Nilgiris.'],
  ['An exotic pest that reached India in 2018 and spread quickly on maize is:', ['Fall armyworm, *Spodoptera frugiperda*', 'Rice yellow stem borer', 'Mustard aphid', 'Red cotton bug'], 0,
    'It was first reported in Karnataka. Earlier introductions include cottony cushion scale and woolly apple aphid.'],
  ['Pest risk analysis (PRA) is used to:', ['Decide, using biological and economic evidence, whether a pest should be regulated and how', 'Calculate pesticide doses', 'Estimate crop yields', 'Fix minimum support prices'], 0,
    'It follows standards of the International Plant Protection Convention (IPPC).'],
  ['Post-entry quarantine means:', ['Growing imported plant material in isolation and watching it for pests before release', 'Destroying all imported seed', 'Fumigating at the border only', 'Quarantining farm workers'], 0,
    'It catches pests that inspection at the border may miss.'],
  ['International rules on phytosanitary measures in trade come from the:', ['WTO SPS Agreement, with standards set by the IPPC', 'Kyoto Protocol', 'Ramsar Convention', 'Montreal Protocol'], 0,
    'Measures must be science-based and not hidden trade barriers.'],
  ['A phytosanitary certificate certifies that a consignment is:', ['Inspected and free from quarantine pests as required by the importing country', 'Of high genetic purity', 'Organically produced', 'Free of pesticide residues'], 0,
    'It is issued by the exporting country\'s national plant protection organisation.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 2, pyq: ['CSE-2013-A2-m34', 'CSE-1993-A2-m40', 'IFoS-2023-A2-m35', 'CSE-2000-A2-m33', 'CSE-2010-A2-m26', 'CSE-2002-A2-m24', 'CSE-2002-A2-m26', 'CSE-1992-A2-m45', 'CSE-1991-A2-m32', 'CSE-1997-A2-m26', 'CSE-2006-A2-m25', 'CSE-1989-A2-m10', 'IFoS-2024-A2-m14', 'CSE-2023-A2-m25', 'CSE-1999-A2-m22', 'CSE-2000-A2-m29', 'IFoS-2006-A2-m07', 'IFoS-2015-A2-m09', 'IFoS-2009-A2-m02', 'IFoS-2002-A2-m01', 'IFoS-2001-A2-m02', 'IFoS-2006-A2-m02'], q: [
  ['The cotton whitefly *Bemisia tabaci* is important mainly because it:', ['Sucks sap, excretes honeydew causing sooty mould, and spreads cotton leaf curl virus', 'Bores into bolls', 'Cuts seedlings at ground level', 'Feeds on roots'], 0,
    'Outbreaks are linked to overuse of synthetic pyrethroids and late sowing.'],
  ['The pink bollworm *Pectinophora gossypiella* is now a major problem in India because it:', ['Has developed resistance to Bt cotton (Bollgard II)', 'Attacks only wheat', 'Has been eradicated', 'Feeds only on leaves'], 0,
    '"Rosette" flowers are a sign of attack; pheromone-based mating disruption helps.'],
  ['Spotted bollworms (*Earias* spp.) damage cotton by:', ['Boring into shoot tips, which wither, and into squares and bolls', 'Sucking leaf sap', 'Mining leaves', 'Feeding on roots'], 0,
    'Removing affected shoots and weeds of Malvaceae reduces them.'],
  ['The invasive cotton mealybug *Phenacoccus solenopsis* is checked naturally by the parasitoid:', ['*Aenasius arizonensis*', '*Trichogramma chilonis*', '*Bracon hebetor*', '*Encarsia formosa*'], 0,
    'It caused outbreaks in Punjab and Gujarat around 2006–07.'],
  ['The chickpea pod borer *Helicoverpa armigera* is managed by:', ['Pheromone traps, bird perches, HaNPV and need-based sprays at ETL', 'Flooding the field', 'Soil solarisation only', 'Removing root nodules'], 0,
    'The larva feeds with its head thrust inside the pod.'],
  ['"Dead heart" at the vegetative stage and "white ear" at the reproductive stage in rice are caused by:', ['The yellow stem borer *Scirpophaga incertulas*', 'Brown planthopper', 'Rice gall midge', 'Rice hispa'], 0,
    'The larva bores into the stem and cuts the central shoot or panicle base.'],
  ['"Hopper burn" in circular patches in rice fields is caused by:', ['Brown planthopper, *Nilaparvata lugens*', 'Rice leaf folder', 'Green leafhopper', 'Rice bug'], 0,
    'Heavy nitrogen and close spacing favour it; draining the field and alleyways help.'],
  ['"Silver shoot" or "onion shoot" in rice is caused by the:', ['Rice gall midge, *Orseolia oryzae*', 'Rice hispa', 'Rice case worm', 'Stem borer'], 0,
    'Resistant varieties are the main control.'],
  ['The sugarcane early shoot borer *Chilo infuscatellus* causes:', ['Dead hearts in young cane that pull out easily and smell foul', 'Bunchy top in mature cane', 'Red rot', 'Whitefly sooty mould'], 0,
    'The top shoot borer *Scirpophaga excerptalis* causes bunchy top in older cane.'],
  ['In wheat, a soil pest that damages roots and crowns, mainly in light, rainfed soils, is:', ['Termites (*Odontotermes*, *Microtermes*)', 'Brown planthopper', 'Pink bollworm', 'Fruit fly'], 0,
    'Aphids are the main foliar pests of wheat; seed treatment helps against termites.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 2, pyq: ['IFoS-2020-A2-m19', 'IFoS-2012-A2-m15', 'IFoS-2010-A2-m12', 'CSE-2002-A2-m07', 'CSE-2000-A2-m20', 'CSE-2017-A2-m11', 'CSE-2007-A2-m06', 'CSE-1999-A2-m05', 'CSE-2013-A2-m09', 'CSE-1999-A2-m07', 'CSE-2011-A2-m29', 'CSE-2001-A2-m27', 'IFoS-2003-A2-m29', 'IFoS-2001-A2-m27'], q: [
  ['Mango hoppers damage the crop mainly by:', ['Sucking sap from inflorescences, causing flower drop and sooty mould on honeydew', 'Boring into the stone', 'Eating roots', 'Making galls on leaves'], 0,
    'Sprays are timed at panicle emergence.'],
  ['Mango mealybug (*Drosicha mangiferae*) nymphs are stopped from climbing trees by:', ['Banding the trunk with polythene sheet and grease in December–January', 'Flooding the orchard', 'Pruning roots', 'Spraying urea'], 0,
    'Raking soil around the trunk exposes eggs.'],
  ['The mango stone weevil is a quarantine concern because:', ['The larva develops inside the seed with no outer sign on the fruit', 'It kills the tree within a week', 'It spreads viruses', 'It attacks only leaves'], 0,
    'Some importing countries need treatments or pest-free area certification.'],
  ['Fruit flies (*Bactrocera* spp.) are managed by:', ['Collecting and destroying fallen fruit, ploughing to expose pupae, lure traps and bait sprays', 'Flooding the field', 'Spraying urea', 'Releasing ladybird beetles'], 0,
    'Methyl eugenol attracts the oriental fruit fly in mango and guava; cue-lure attracts melon fly in cucurbits.'],
  ['The citrus psylla *Diaphorina citri* is especially harmful because it:', ['Spreads citrus greening (huanglongbing)', 'Spreads citrus tristeza virus', 'Bores into the trunk', 'Causes canker'], 0,
    'Other citrus pests include lemon butterfly and citrus leaf miner.'],
  ['Woolly apple aphid (*Eriosoma lanigerum*) is controlled biologically by:', ['The parasitoid *Aphelinus mali* and resistant Merton–Malling rootstocks', '*Trichogramma*', 'HaNPV', 'Bt sprays'], 0,
    'It forms white waxy colonies on stems and galls on roots.'],
  ['The coconut black-headed caterpillar (*Opisina arenosella*) is controlled by releasing:', ['Larval parasitoids such as *Goniozus nephantidis* and *Bracon brevicornis*', 'Ladybird beetles', 'Predatory mites', '*Trichoderma*'], 0,
    'Badly affected outer leaves are cut and burnt.'],
  ['The tea mosquito bug *Helopeltis antonii* is a key pest of:', ['Cashew, sucking tender shoots and panicles and causing dieback', 'Rice', 'Wheat', 'Cotton bolls only'], 0,
    'Sprays are given at flushing, flowering and fruit set.'],
  ['The coconut eriophyid mite *Aceria guerreronis* damages:', ['Young nuts under the perianth, causing triangular patches and cracked husks', 'Roots', 'Leaflets only', 'The trunk'], 0,
    'Neem formulations and root feeding of systemics have been used against it.'],
  ['An IPM schedule for mango includes:', ['Orchard sanitation, trunk banding, monitoring hoppers at flowering and need-based sprays', 'Calendar sprays every week', 'No monitoring at all', 'Spraying only after harvest'], 0,
    'Pollinators must be protected at flowering.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 2, pyq: ['IFoS-2016-A2-m13', 'IFoS-2023-A2-m17', 'CSE-2000-A2-m21', 'IFoS-2024-A2-m26', 'CSE-2024-A2-m09', 'CSE-1998-A2-m19', 'IFoS-2001-A2-m28', 'IFoS-2000-A2-m18', 'IFoS-2019-A2-m10', 'IFoS-2002-A2-m20', 'IFoS-2001-A2-m27'], q: [
  ['Brinjal shoot and fruit borer *Leucinodes orbonalis* is managed by:', ['Clipping wilted shoots and bored fruits, pheromone traps and need-based sprays', 'Flooding the field', 'Soil solarisation only', 'Spraying urea'], 0,
    'Time-sensitive: Bt brinjal is grown in Bangladesh but not approved in India.'],
  ['The diamondback moth *Plutella xylostella* is notable as:', ['The first insect to develop resistance to Bt sprays in the field', 'A pest of rice', 'A beneficial predator', 'A pest only of stored grain'], 0,
    'It is the main pest of cabbage and cauliflower.'],
  ['A trap crop used against diamondback moth in cabbage is:', ['Indian mustard, about 2 rows for every 25 rows of cabbage', 'Maize around the field', 'Marigold inside every row', 'Sorghum'], 0,
    'Mustard is sown before cabbage so it attracts the moths first.'],
  ['African marigold is grown as a trap crop in tomato against:', ['The fruit borer *Helicoverpa armigera*, about 1 row for 16 rows of tomato', 'Whitefly only', 'Root-knot nematode only', 'Aphids only'], 0,
    'Biological control of tomato fruit borer uses *Trichogramma* releases and HaNPV.'],
  ['The South American tomato leaf miner *Tuta absoluta* is:', ['An invasive pest found in India since 2014', 'A native pest of rice', 'A beneficial insect', 'A soil nematode'], 0,
    'Larvae mine leaves and bore fruits; pheromone traps are used to monitor it.'],
  ['The "murda" leaf curl complex of chilli is caused by:', ['The thrips *Scirtothrips dorsalis* and the yellow mite *Polyphagotarsonemus latus*', 'Fruit flies', 'Stem borers', 'Termites'], 0,
    'Thrips curl leaves upwards; mites curl them downwards.'],
  ['The potato tuber moth *Phthorimaea operculella* is reduced in the field by:', ['Earthing up so tubers are not exposed, and harvesting promptly', 'Leaving tubers exposed', 'Flood irrigation at harvest', 'Planting very shallow'], 0,
    'In storage, covering tubers with dried *Lantana* or neem leaves deters it.'],
  ['The green peach aphid *Myzus persicae* matters in potato mainly because it:', ['Spreads potato leaf roll virus and PVY', 'Bores into tubers', 'Causes late blight', 'Feeds on roots'], 0,
    'Seed potatoes are grown in low-aphid periods (seed plot technique).'],
  ['Hadda beetle (*Henosepilachna vigintioctopunctata*) damages brinjal and potato by:', ['Scraping leaf tissue so leaves look like skeletons', 'Boring into fruits', 'Sucking sap', 'Making root galls'], 0,
    'Both adults and grubs feed on leaves.'],
  ['Gregarious caterpillars that defoliate cabbage and are parasitised by *Cotesia glomerata* belong to:', ['The cabbage butterfly, *Pieris brassicae*', 'Diamondback moth', 'Mustard aphid', 'Fruit fly'], 0,
    'Hand picking egg masses and young larvae helps in small plots.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 1, pyq: ['IFoS-2019-A2-m20', 'CSE-1995-A2-m26', 'IFoS-2013-A2-m31', 'IFoS-2000-A2-m17', 'IFoS-2009-A2-m11', 'CSE-2004-A2-m22', 'CSE-2004-A2-m21', 'IFoS-2016-A2-m24', 'CSE-2013-A2-m33', 'CSE-1996-A2-m05', 'IFoS-2011-A2-m06'], q: [
  ['A monophagous pest feeds on:', ['One plant species or genus, e.g. rice yellow stem borer on rice', 'Plants of one family', 'Plants of many families', 'Only dead plant matter'], 0,
    'Oligophagous pests feed within one family (diamondback moth on crucifers); polyphagous pests feed widely (*Helicoverpa armigera*).'],
  ['Insects with chewing mouthparts are best controlled by:', ['Stomach poisons and contact insecticides on the food they eat', 'Systemic insecticides only', 'Fumigants only', 'Pheromones only'], 0,
    'Sucking insects (aphids, bugs, hoppers) are best controlled with systemic insecticides.'],
  ['Boring insects such as stem borers are hard to reach with contact sprays because:', ['The larvae feed hidden inside plant tissue', 'They have no mouthparts', 'They feed only at night on leaves', 'They live only in water'], 0,
    'Granules, systemics and timing sprays at egg hatch work better.'],
  ['Diapause differs from hibernation (quiescence) in that diapause:', ['Is a genetically programmed, hormone-controlled arrest triggered in advance by cues such as day length', 'Is a direct response that ends as soon as conditions improve', 'Occurs only in summer', 'Means death of the insect'], 0,
    'Hibernation and aestivation are responses to cold and heat as they happen.'],
  ['A key pest is one that:', ['Occurs every year at levels above the economic injury level and needs regular control', 'Appears only once in many years', 'Never causes economic loss', 'Is a beneficial insect'], 0,
    'Occasional and potential pests cross the EIL only sometimes or under changed conditions.'],
  ['R. H. Painter grouped the mechanisms of host-plant resistance to insects as:', ['Non-preference (antixenosis), antibiosis and tolerance', 'Avoidance, escape and death', 'Mimicry, camouflage and repellence', 'Vertical, horizontal and diagonal'], 0,
    'Kogan renamed non-preference as antixenosis.'],
  ['Antibiosis as a resistance mechanism means the plant:', ['Harms the insect\'s growth, survival or reproduction after it feeds', 'Is avoided by the insect', 'Grows despite damage', 'Matures before the pest arrives'], 0,
    'E.g. DIMBOA in maize against corn borer.'],
  ['Bollgard II Bt cotton expresses:', ['Two Bt genes, *cry1Ac* and *cry2Ab*', 'Only *cry1Ac*', 'A herbicide tolerance gene only', 'A virus coat protein'], 0,
    'Bollgard I (*cry1Ac*) was approved in India in 2002; Bollgard II followed in 2006.'],
  ['Besides Bt genes, genes used to make transgenic plants resistant to insects include:', ['Protease inhibitors (e.g. cowpea trypsin inhibitor) and lectins (e.g. snowdrop lectin GNA)', 'Genes for male sterility only', 'Genes for nitrogen fixation', 'Chlorophyll genes'], 0,
    'Lectins are useful against sucking pests that Bt toxins do not control well.'],
  ['A biotype of an insect is:', ['A population able to attack a variety that is resistant to other populations of the same species', 'A new species', 'A dead insect sample', 'A type of insecticide'], 0,
    'Brown planthopper biotypes have broken resistance in several rice varieties.']
] },
{ p: 'A2', t: 'Insect Pests & IPM', w: 1, pyq: ['CSE-1990-A2-m34', 'CSE-1998-A2-m20', 'IFoS-2006-A2-m30', 'IFoS-2009-A2-m12', 'CSE-2009-A2-m15', 'IFoS-2022-A2-m15'], q: [
  ['The most destructive field rat of Indian agriculture is the:', ['Lesser bandicoot rat, *Bandicota bengalensis*', 'House mouse', 'Squirrel', 'Gerbil only'], 0,
    'It damages rice, wheat and stored grain, and makes extensive burrows.'],
  ['Zinc phosphide (about 2% bait) kills rats by:', ['Releasing toxic phosphine gas in the acidic stomach', 'Preventing blood clotting', 'Blocking nerve signals', 'Causing sterility'], 0,
    'It is an acute poison; pre-baiting with plain bait for 2–3 days overcomes bait shyness.'],
  ['Bromadiolone is a rodenticide that:', ['Is a single-dose anticoagulant causing internal bleeding over a few days', 'Kills instantly', 'Is a fumigant', 'Is a repellent only'], 0,
    'Because death is delayed, rats do not link it with the bait; vitamin K is the antidote.'],
  ['Bait shyness in rats means:', ['Survivors of a sublethal acute poison dose avoid that bait afterwards', 'Rats prefer fresh baits', 'Rats avoid all food', 'Rats eat only at night'], 0,
    'Pre-baiting and anticoagulants are used to avoid it.'],
  ['Plant-parasitic nematodes feed by:', ['Piercing plant cells with a hollow stylet and sucking the contents', 'Chewing leaves', 'Absorbing nutrients through roots like fungi', 'Photosynthesis'], 0,
    'Most are microscopic roundworms living in soil and roots.'],
  ['Root-knot nematodes (*Meloidogyne* spp.) cause:', ['Galls (knots) on roots, stunting and wilting', 'Leaf spots', 'Fruit rot', 'Stem borer holes'], 0,
    'They are sedentary endoparasites with a very wide host range, serious in vegetables.'],
  ['"Molya" disease of wheat and barley in Rajasthan is caused by the:', ['Cereal cyst nematode, *Heterodera avenae*', 'Ear-cockle nematode only', 'Root-knot nematode', 'A fungus'], 0,
    'The ear-cockle nematode *Anguina tritici* causes seed galls in wheat.'],
  ['A non-chemical method of nematode management is:', ['Soil solarisation, rotation with non-hosts and growing marigold (*Tagetes*)', 'Flood irrigation every day', 'Adding more nitrogen', 'Deep sowing'], 0,
    'Bioagents such as *Purpureocillium* (*Paecilomyces*) *lilacinus* parasitise nematode eggs.'],
  ['Mites need special acaricides because they:', ['Are arachnids, not insects, and many insecticides do not kill them', 'Live only in soil', 'Are viruses', 'Have no legs'], 0,
    'Wettable sulphur, propargite and fenazaquin are examples of acaricides.'],
  ['The giant African snail, a non-insect pest of crops, is controlled with:', ['Metaldehyde baits (a molluscicide) and hand collection', 'Bt sprays', 'Zinc phosphide only', 'Fungicides'], 0,
    'It is an exotic, highly polyphagous pest.']
] }
);
