/* PYQ registry, part 3 — PYQs missing from the first PYQ Map import (added 2026-10-10). Same row format as registry_map.js.
 * CSE 2026 Botany I/II: from the newer Drive "PYQ Map - all questions (filterable).csv" (ids mNN in map order).
 * Others: verified rows of Drive "Botany-catalogue-integrated-v1-2026-10-08.csv" that the map garbled or dropped (ids = printed Q number; sub-parts merged).
 * kind "t" = short topic summary from the catalogue, not verbatim. IDs are referenced by bank files — never renumber. */
(window.IFOS_PYQ = window.IFOS_PYQ || []).push(
  ["CSE-2026-B1-m01", 10, "Blue-green algae are also considered as bacteria. Discuss their major similarities with bacteria.", "v", 19],
  ["CSE-2026-B1-m02", 10, "What do you mean by virus of bacteria? Describe their application in medical sciences.", "v", 31],
  ["CSE-2026-B1-m03", 10, "Describe mineralization, symbiotic and non-symbiotic nitrogen fixation. How do they help in improving the soil quality for agriculture?", "v", 31],
  ["CSE-2026-B1-m04", 10, "Define fossilization. Discuss the major types of fossils that occur in nature.", "v", 30],
  ["CSE-2026-B1-m05", 10, "What is chemotaxonomy? Analyze how chemical evidence contributes to solving taxonomic problems in plant classification.", "v", 21],
  ["CSE-2026-B1-m06", 20, "What are the major characteristics of Anthocerotopsida? Describe the gametophytic and sporophytic generations of Anthoceros.", "v", 23],
  ["CSE-2026-B1-m07", 15, "Describe the salient features and economic importance of Laminariales.", "v", 19],
  ["CSE-2026-B1-m08", 15, "Compare the ovule-bearing structures of Cycas and Pinus with the help of labelled diagrams.", "v", 30],
  ["CSE-2026-B1-m09", 20, "Name the organism that causes stalk rot disease in maize. Describe its symptoms, disease cycle, control and management.", "v", 31],
  ["CSE-2026-B1-m10", 15, "What are Mycoplasmas? How do they differ from spheroplast and protoplast? Describe their salient features.", "v", 31],
  ["CSE-2026-B1-m11", 15, "Write a note on geological time scale. Briefly discuss the plant life in each era.", "v", 30],
  ["CSE-2026-B1-m12", 20, "Explain the APG IV classification. State briefly how it differs from existing classifications. Discuss its merits and demerits.", "v", 21],
  ["CSE-2026-B1-m13", 15, "Describe in brief the major strategies adopted for plant disease control and management.", "v", 31],
  ["CSE-2026-B1-m14", 15, "Compare the sporophyte of Psilotum and Equisetum.", "v", 34],
  ["CSE-2026-B1-m15", 10, "Describe the androecium of Orchidaceae and Asclepiadaceae. Highlight the differences between them.", "v", 21],
  ["CSE-2026-B1-m16", 10, "Discuss the different types of polyembryony in plants and add a note on its importance.", "v", 20],
  ["CSE-2026-B1-m17", 10, "Write the botanical names and families of the following economically important plants: (i) Pearl millet (ii) Flax (iii) Pomegranate (iv) Bottle gourd (v) Chickpea.", "v", 27],
  ["CSE-2026-B1-m18", 10, "Give a detailed account on cell suspension culture and its significance.", "v", 32],
  ["CSE-2026-B1-m19", 10, "Write an explanatory note on the history of plant domestication.", "v", 27],
  ["CSE-2026-B1-m20", 20, "Mention the diagnostic features of family Apiaceae and Solanaceae. Write the botanical names and uses of five members from each family.", "v", 21],
  ["CSE-2026-B1-m21", 15, "\"Botanical gardens are considered as outdoor laboratories for botanists.\" Substantiate the statement.", "v", 21],
  ["CSE-2026-B1-m22", 15, "Describe the components of xylem tissue in plants. What is its role in plant survival and growth?", "v", 20],
  ["CSE-2026-B1-m23", 20, "Briefly explain the method of herbaria preparation. What is its role in modern taxonomic research?", "v", 21],
  ["CSE-2026-B1-m24", 15, "Write an account on types, regulation and significance of totipotency.", "v", 32],
  ["CSE-2026-B1-m25", 15, "Write an account on haploid plant production through tissue culture. What are the advantages of homozygous diploid lines?", "v", 32],
  ["CSE-2026-B1-m26", 20, "What is the role played by media and growth regulators in micropropagation? How to control exudation and contamination problems during micropropagation?", "v", 32],
  ["CSE-2026-B1-m27", 15, "Describe the techniques used in experimental embryology.", "v", 20],
  ["CSE-2026-B1-m28", 15, "Give an outline on the history and progress of ethnobotanical research in India.", "v", 27],
  ["CSE-2026-B2-m01", 10, "Write a short note on: Frame Shift mutation.", "v", 17],
  ["CSE-2026-B2-m02", 10, "Write a short note on: Lampbrush chromosome and its significance.", "v", 17],
  ["CSE-2026-B2-m03", 10, "Write a short note on: Reporter genes.", "v", 35],
  ["CSE-2026-B2-m04", 10, "Write a short note on: Cell signalling and Cell receptors.", "v", 24],
  ["CSE-2026-B2-m05", 10, "Write a short note on: DNA finger printing.", "v", 35],
  ["CSE-2026-B2-m06", 20, "Give a detailed account on sex linked inheritance.", "v", 17],
  ["CSE-2026-B2-m07", 15, "Explain the structural variations of chromosomes and their significance.", "v", 17],
  ["CSE-2026-B2-m08", 15, "Describe the role of Biochemical and Molecular basis of Mutation.", "v", 17],
  ["CSE-2026-B2-m09", 10, "Write in detail the chemical composition of microtubules.", "v", 24],
  ["CSE-2026-B2-m10", 10, "Elaborate the functions of cytoplasmic microtubules.", "v", 24],
  ["CSE-2026-B2-m11", 15, "Explain the different means of passive transport across the plasma membrane.", "v", 24],
  ["CSE-2026-B2-m12", 8, "Elaborate on the significance of molecular markers.", "v", 35],
  ["CSE-2026-B2-m13", 7, "Explain the significance of polyploidy in Agriculture.", "v", 17],
  ["CSE-2026-B2-m14", 20, "Discuss on the tools and techniques involved in PCR and FISH.", "v", 22],
  ["CSE-2026-B2-m15", 15, "Explain the causes of Heterosis and its impact in Agriculture.", "v", 36],
  ["CSE-2026-B2-m16", 15, "Describe the various evidences supporting organic evolution.", "v", 28],
  ["CSE-2026-B2-m17", 10, "Write a short note on: Munch hypothesis.", "v", 33],
  ["CSE-2026-B2-m18", 10, "Write a short note on: Correlation and Regression.", "v", 5],
  ["CSE-2026-B2-m19", 10, "Write a short note on: Heat Shock Proteins (HSPs).", "v", 33],
  ["CSE-2026-B2-m20", 10, "Write a short note on: Biogeochemical cycle.", "v", 26],
  ["CSE-2026-B2-m21", 10, "Write a short note on: Regulation of NIF genes.", "v", 35],
  ["CSE-2026-B2-m22", 10, "Explain the significance of Nod factors and the process of root nodule formation.", "v", 33],
  ["CSE-2026-B2-m23", 10, "Describe the process of amino acid biosynthesis in nitrogen metabolism.", "v", 33],
  ["CSE-2026-B2-m24", 15, "Differentiate between photophosphorylation and oxidative phosphorylation.", "v", 33],
  ["CSE-2026-B2-m25", 15, "Discuss the biochemical and physiological changes during the process of fruit ripening.", "v", 33],
  ["CSE-2026-B2-m26", 10, "Explain the factors affecting enzyme activity.", "v", 33],
  ["CSE-2026-B2-m27", 10, "Describe the mechanism of enzyme action.", "v", 33],
  ["CSE-2026-B2-m28", 15, "Explain the following: (i) Acid rain (ii) Biocide as pollutant (iii) Photochemical smog.", "v", 26],
  ["CSE-2026-B2-m29", 8, "Describe seed dormancy and explain how is it getting regulated.", "v", 33],
  ["CSE-2026-B2-m30", 7, "Explain biochemical changes taking place during the seed germination.", "v", 33],
  ["CSE-2026-B2-m31", 5, "What is the basic concept of phytogeography?", "v", 37],
  ["CSE-2026-B2-m32", 15, "Give a detailed account on various phytogeographical regions of India.", "v", 37],
  ["CSE-2026-B2-m33", 15, "Give an account on farmers rights and intellectual property rights.", "v", 36],
  ["CSE-2026-B2-m34", 15, "Discuss on the present status of forest resources of India. Give the factors responsible for deforestation.", "v", 26],
  ["CSE-2012-B1-Q8c", 0, "Ethnobotany has provided important clues to discovery of modern drugs. Give an account of ethnobotany taking some suitable examples.", "v", 27],
  ["CSE-2012-B1-Q8d", 0, "Compare and contrast the floral characters of the three sub-families of Leguminosae.", "v", 21],
  ["CSE-2018-B2-Q5a", 0, "Water potential", "t", 33],
  ["CSE-2018-B2-Q5c", 0, "Phloem loading", "t", 33],
  ["CSE-2017-B2-Q5a", 0, "Explain the following: beta-oxidation.", "v", 33],
  ["CSE-2017-B2-Q5b", 0, "Explain the following: GS-GOGAT system.", "v", 33],
  ["CSE-2017-B2-Q5d", 0, "Explain the following: biotic factors.", "v", 26],
  ["CSE-2016-B2-Q1d", 0, "Explain the following: C-value paradox.", "v", 35],
  ["CSE-2013-B1-Q3c", 0, "Draw well-labelled diagram: Section through a sorus of fern.", "v", 34],
  ["CSE-2013-B1-Q5a", 0, "Beta taxonomy", "t", 21],
  ["CSE-2013-B2-Q4b", 0, "Briefly describe characteristics and importance of Neo-darwinism.", "v", 35],
  ["CSE-2013-B2-Q4d", 0, "Briefly describe characteristics and importance of Chi-square test.", "v", 36],
  ["IFoS-2015-B1-Q1a", 0, "What is plant quarantine?", "v", 31],
  ["IFoS-2015-B1-Q4a", 0, "Draw scientifically accurate diagrams of the following and label the parts: (i) Flower of Cycadeoidea. / Draw scientifically accurate diagrams of the following and label the parts: (ii) LS of Pinus seed. / Draw scientifically accurate diagrams of the following and label the parts: (iii) TS of leaf of Cordaites.", "v", 30],
  ["IFoS-2016-B1-Q5a", 0, "Distinguish between the following : (i) Rust and Smut (ii) Cladode and Phyllode", "v", 5],
  ["IFoS-2016-B1-Q5b", 0, "Differentiate between the following : (i) Isokont and Heterokont (ii) Centric and Eccentric growth rings", "v", 5],
  ["IFoS-2016-B1-Q5c", 0, "Draw well-labelled diagrams of the following : (i) Flower showing androphore and gynophore (ii) Winged pollen of Pinus", "v", 5],
  ["IFoS-2016-B1-Q5e", 0, "Differentiate between the following : (i) Descending and Ascending imbricate aestivation (ii) Hypanthium and Hypanthodium", "v", 21],
  ["IFoS-2016-B1-Q5f", 0, "Draw well-labelled diagrams of the following : (i) Male flower of Euphorbia (ii) Tyloses", "v", 5],
  ["IFoS-2016-B1-Q5g", 0, "Discuss briefly the following : (i) Taxonomic position of Caytoniales (ii) Peristome teeth of Funaria", "v", 5],
  ["IFoS-2016-B1-Q5h", 0, "Explain briefly the following : (i) Coenocytic mycelium (ii) Parasitism in fungi", "v", 29],
  ["IFoS-2016-B1-Q6a", 0, "Explain the progressive sterilization of the sporogenous tissue in Bryophytes.", "v", 23],
  ["IFoS-2016-B1-Q6c", 0, "Taxonomic Hierarchy", "t", 21],
  ["CSE-2014-B1-Q5c", 0, "Position of monocots in APG classification", "t", 21],
  ["CSE-2014-B1-Q5d", 0, "Embryo development in Arabidopsis", "t", 20],
  ["CSE-2014-B1-Q5e", 0, "Importance of typification in plant nomenclature", "t", 21],
  ["CSE-2014-B1-Q7d", 0, "Rubiaceae floral structure + 3 species names and uses", "t", 21],
  ["CSE-2015-B1-Q1d", 0, "Chemical nature of viroids; transmission in plants", "t", 31],
  ["CSE-2017-B1-Q1c", 0, "Tetrapolar heterothallism", "t", 29],
  ["CSE-2017-B1-Q1d", 0, "Salient features of lichens", "t", 29],
  ["CSE-2017-B1-Q4c", 0, "Modes of transmission of plant viruses", "t", 31],
  ["CSE-2017-B1-Q5c", 0, "Symmetry in plants in relation to morphogenesis", "t", 32],
  ["CSE-2015-B2-Q1c", 0, "Genetic code", "t", 35],
  ["CSE-2015-B2-Q1d", 0, "Hybrid vigour", "t", 9],
  ["CSE-2015-B2-Q5a", 0, "ATP synthase", "t", 33],
  ["CSE-2018-B1-Q1d", 0, "Spermocarp and cystocarp", "t", 19],
  ["CSE-2018-B1-Q4c", 0, "Distinguishing characters of Dipterocarpaceae Asteraceae Orchidaceae", "v", 21],
  ["CSE-2018-B1-Q5c", 0, "Development and functions of endosperm", "t", 20],
  ["CSE-2011-B1-Q2a", 0, "Prions and need for thorough understanding with examples", "v", 31],
  ["CSE-2011-B1-Q2b", 0, "Moulds as bane and boon for humans with examples", "t", 29],
  ["CSE-2011-B1-Q2c", 0, "Embryo rescue for successful raising of recombinants", "t", 32],
  ["CSE-2011-B1-Q4b", 0, "Success of micropropagation in achieving goals", "t", 32],
  ["CSE-2011-B1-Q4c", 0, "Modelling and disease forecasting", "t", 31],
  ["CSE-2011-B1-Q6a", 0, "What are Ubisch bodies / Ubisch body formation location and role", "v", 20],
  ["CSE-2011-B1-Q6b", 0, "What is interxylary phloem / Formation of interxylary phloem / Interxylary phloem examples and at least one diagram", "v", 20],
  ["CSE-2011-B1-Q6c", 0, "Features of component used to identify basic honey sources", "v", 20],
  ["CSE-2011-B1-Q6d", 0, "Disastrous effects of quarantine laxity with examples", "t", 31],
  ["CSE-2011-B1-Q7a", 0, "Need to combine ethnobotany with IPR with examples", "t", 27],
  ["CSE-2011-B1-Q7b", 0, "Mechanisms for hybrids between incompatible species", "t", 9],
  ["CSE-2011-B1-Q7c", 0, "Macro and micro biomolecules in taxonomy", "t", 21],
  ["CSE-2011-B1-Q7e", 0, "Nemec phenomenon and significance", "t", 20],
  ["CSE-2011-B1-Q8a", 0, "Energy plantations", "t", 27],
  ["CSE-2011-B1-Q8b", 0, "Gynoecium of Asclepiadaceae Brassicaceae Poaceae", "t", 21],
  ["CSE-2011-B1-Q8c", 0, "Stomatal apparatus in Brassica Dianthus Poa", "t", 20],
  ["CSE-2011-B2-Q8b", 0, "Identify expression of cloned gene", "t", 22],
  ["CSE-2011-B2-Q8c", 0, "RNA transport within eukaryotic cell", "t", 35],
  ["CSE-2011-B2-Q8d", 0, "CO2 and ethylene production pattern in climacteric fruit", "v", 33],
  ["IFoS-2009-B1-Q5c", 0, "Vavilov centres of origin | Pollen allergy", "t", 5],
  ["IFoS-2009-B1-Q5d", 0, "Why some plants have sunken stomata | Spike versus spadix", "v", 5],
  ["IFoS-2010-B1-Q3a", 0, "Molecular basis of infection in plants", "t", 31],
  ["IFoS-2010-B2-Q1a", 0, "x versus n versus 2n chromosome numbers", "t", 17],
  ["IFoS-2010-B2-Q1b", 0, "Degree of freedom versus probability", "t", 36],
  ["IFoS-2011-B2-Q5a", 0, "Stomatal movement", "t", 33],
  ["IFoS-2011-B2-Q5c", 0, "Secondary metabolites", "t", 33],
  ["IFoS-2011-B2-Q5d", 0, "ABA in seed maturation", "t", 33],
  ["IFoS-2011-B2-Q5e", 0, "Renewable energy resources", "t", 26],
  ["IFoS-2011-B2-Q6a", 0, "Biochemical steps in nitrogen fixation; two associated special structures", "v", 33],
  ["IFoS-2011-B2-Q6b", 0, "Metabolic details of CO2 fixation in CAM plants", "t", 33],
  ["IFoS-2011-B2-Q7a", 0, "Chemiosmotic ATP synthesis; net ATP from one glucose", "t", 33],
  ["IFoS-2011-B2-Q7b", 0, "Growth regulators in parthenocarpy", "t", 33],
  ["IFoS-2011-B2-Q8a", 0, "Biotic and abiotic components of a biome", "t", 26],
  ["IFoS-2011-B2-Q8b", 0, "National and international biodiversity protection and preservation efforts", "v", 37],
  ["IFoS-2013-B1-Q4c", 0, "Integrated disease management: critical comment", "t", 31]
);
