/* PYQ registry: [id, marks, text, kind]. id = EXAM-YEAR-PAPER-Qno.
 * marks 0 = not legible in the source. kind "v" = official wording (OCR lightly cleaned; "…" = cut off in the source); "t" = topic summary only, not verbatim.
 * Sources: IFoS 2017-18 papers and IFoS 2025 anchors from the six Comprehensive volumes (Drive, 9 Sep 2026);
 * CSE 2026 Agriculture I/II from the Answer Construction Booklets (Ed.4) §14. */
(window.IFOS_PYQ = window.IFOS_PYQ || []).push(
  ["CSE-2026-A1-Q1a", 10, "What are the major sources of water pollution in India? What are the ways to check it?", "v"],
  ["CSE-2026-A1-Q1b", 10, "What are the basic concepts of a farming system? Briefly explain three major indigenous farming systems followed in India.", "v"],
  ["CSE-2026-A1-Q1c", 10, "Write down the names and characteristics of tree species suitable for agroforestry.", "v"],
  ["CSE-2026-A1-Q1d", 10, "Write down the dissemination of weeds with appropriate examples.", "v"],
  ["CSE-2026-A1-Q1e", 10, "Write down the functions and deficiency symptoms of secondary nutrients in plants.", "v"],
  ["CSE-2026-A1-Q2a", 20, "Give an account of greenhouse gas (GHG) emissions from agriculture. State the mitigation strategies for reducing greenhouse gas (GHG) emissions in agriculture.", "v"],
  ["CSE-2026-A1-Q2b", 20, "Give a lucid account on the scope of precision farming in India. Enumerate its benefits and limitations in the Indian scenario.", "v"],
  ["CSE-2026-A1-Q2c", 10, "How can GIS be utilised for land use analysis and micro-watershed planning?", "v"],
  ["CSE-2026-A1-Q3a", 20, "Discuss the vegetative propagation methods adopted in forest plants with suitable examples and their limitations.", "v"],
  ["CSE-2026-A1-Q3b", 20, "Discuss in detail the management practices in the ratoon crop of sugarcane.", "v"],
  ["CSE-2026-A1-Q3c", 10, "Suggest suitable chemical weed management practices for the following crops: (i) Maize (ii) Moong (iii) Cotton (iv) Sugarcane", "v"],
  ["CSE-2026-A1-Q4a", 20, "What do you mean by soil consistency and soil plasticity? Briefly discuss the various forms of soil consistency found in soils.", "v"],
  ["CSE-2026-A1-Q4b", 20, "What is nitrification? Describe the factors affecting nitrification process in soil.", "v"],
  ["CSE-2026-A1-Q4c", 10, "Briefly discuss the reasons responsible for increasing available phosphorus after flooding, in most of the soils.", "v"],
  ["CSE-2026-A1-Q5a", 10, "Write down the approaches for soil conservation.", "v"],
  ["CSE-2026-A1-Q5b", 10, "Briefly discuss the criteria for irrigation scheduling in crop plants.", "v"],
  ["CSE-2026-A1-Q5c", 10, "Describe the various components of the drip irrigation system with the help of a schematic diagram.", "v"],
  ["CSE-2026-A1-Q5d", 10, "How are prices regulated through agricultural price policy?", "v"],
  ["CSE-2026-A1-Q5e", 10, "Write the steps involved in farm planning.", "v"],
  ["CSE-2026-A1-Q6a", 10, "On the basis of Boron content, classify irrigation water suitability for various soils and crops.", "v"],
  ["CSE-2026-A1-Q6b", 20, "Categorise industrial effluents and briefly discuss their effects on soil properties.", "v"],
  ["CSE-2026-A1-Q6c", 20, "Briefly discuss the problems associated with dryland agriculture in India. What are the ways to increase production and productivity in dryland areas?", "v"],
  ["CSE-2026-A1-Q7a", 20, "What are the various factors affecting farm profits? Discuss the decisions which are critical to attain good farm profits.", "v"],
  ["CSE-2026-A1-Q7b", 20, "Differentiate between extension education and extension services. Discuss extension education as an applied science.", "v"],
  ["CSE-2026-A1-Q7c", 10, "Write down the practices involved in ‘Integrated Watershed Management’ for improving livelihood security.", "v"],
  ["CSE-2026-A1-Q8a", 20, "Differentiate between monitoring and evaluation of extension programmes. Discuss the various types of evaluation of extension programmes.", "v"],
  ["CSE-2026-A1-Q8b", 20, "Discuss the rationale of Farmers’ markets in India. Enlist the impact of farmers’ markets on various stakeholders with suitable examples.", "v"],
  ["CSE-2026-A1-Q8c", 10, "Briefly discuss the measures to control soil erosion by wind.", "v"],
  ["CSE-2026-A2-Q1a", 10, "What is somatic hybridization? Explain its steps in production of hybrid plants.", "v"],
  ["CSE-2026-A2-Q1b", 10, "What are the biochemical changes that take place in seeds under prolonged storage?", "v"],
  ["CSE-2026-A2-Q1c", 10, "Describe the factors influencing nutrient absorption in plants from the soil.", "v"],
  ["CSE-2026-A2-Q1d", 10, "Describe the characteristics of a clone.", "v"],
  ["CSE-2026-A2-Q1e", 10, "Define mutagens. Explain the different mutagen groups.", "v"],
  ["CSE-2026-A2-Q2a", 20, "Describe the causes and sources of disease resistance in plants.", "v"],
  ["CSE-2026-A2-Q2b", 20, "Explain the functions and structure of mitochondria with suitable diagram.", "v"],
  ["CSE-2026-A2-Q2c", 10, "Describe the importance of molecular markers in plant improvements.", "v"],
  ["CSE-2026-A2-Q3a", 20, "Define heritability. What do you mean by broad sense and narrow sense heritability? Explain its applications in crop improvement.", "v"],
  ["CSE-2026-A2-Q3b", 20, "Discuss the principles and practices of seed production in self-pollinated and cross- pollinated crops.", "v"],
  ["CSE-2026-A2-Q3c", 10, "Define cytoplasmic inheritance. Explain briefly about sex-influenced and sex-limited traits.", "v"],
  ["CSE-2026-A2-Q4a", 20, "Discuss about the problems and intricacies in the profitable marketing of seeds.", "v"],
  ["CSE-2026-A2-Q4b", 20, "Explain the factors that affect the amount of soil water available for plants.", "v"],
  ["CSE-2026-A2-Q4c", 10, "Describe the different seed enhancement techniques used in seed industry and their benefits.", "v"],
  ["CSE-2026-A2-Q5a", 10, "What is topiary? Describe the characteristics of plants ideal for it.", "v"],
  ["CSE-2026-A2-Q5b", 10, "Describe terrace garden and moon garden.", "v"],
  ["CSE-2026-A2-Q5c", 10, "Discuss the quality indices for cauliflower, cabbage and broccoli.", "v"],
  ["CSE-2026-A2-Q5d", 10, "Discuss the major constraints for enhancing food grain production in India.", "v"],
  ["CSE-2026-A2-Q5e", 10, "Discuss the role of osmoprotectants in plants with reference to salt and water stress.", "v"],
  ["CSE-2026-A2-Q6a", 20, "What is high density orcharding? Describe management practices for high density orcharding in citrus group.", "v"],
  ["CSE-2026-A2-Q6b", 20, "Explain the biosynthetic pathways of chlorophylls and carotenoids in plants. How do environmental factors influence plant pigments?", "v"],
  ["CSE-2026-A2-Q6c", 10, "What do you mean by nutrient deficiency in humans? Write the major causes of nutrient deficiencies in India.", "v"],
  ["CSE-2026-A2-Q7a", 20, "Describe the scientific cultivation of mango with reference to regular bearer varieties, propagation, transplanting time, management of mealy bug and …", "v"],
  ["CSE-2026-A2-Q7b", 20, "What are the major causes of poverty in India? Describe the role of Agriculture in poverty alleviation and employment generation.", "v"],
  ["CSE-2026-A2-Q7c", 10, "Explain the different types of seed dormancy. What are the factors that are responsible for dormancy in seeds?", "v"],
  ["CSE-2026-A2-Q8a", 20, "Explain the factors encouraging infestation of pests during storage. Discuss control measures for pest infestation during storage.", "v"],
  ["CSE-2026-A2-Q8b", 20, "Discuss the production technology of carnation for cut flower in relation to improved varieties, growing requirements and season, flower regulation, p…", "v"],
  ["CSE-2026-A2-Q8c", 10, "Discuss the steps taken by the Government of India for improving the food processing industry.", "v"],
  ["IFoS-2018-B1-Q1a", 8, "Distinguish between Bacteria and Archaea.", "v"],
  ["IFoS-2018-B1-Q1b", 8, "Comment on why Albugo candida and Phytophthora infestans are not considered as fungi.", "v"],
  ["IFoS-2018-B1-Q1c", 8, "Distinguish between Chlorophyta and Rhodophyta.", "v"],
  ["IFoS-2018-B1-Q1d", 8, "What is peristome? Describe its formation and role.", "v"],
  ["IFoS-2018-B1-Q1e", 8, "What are coralloid roots? Where are these found and what important role do they play?", "v"],
  ["IFoS-2018-B1-Q2a", 15, "Compare loose smut with covered smut of wheat on the basis of symptoms, causal organism, disease cycle and disease management.", "v"],
  ["IFoS-2018-B1-Q2b", 15, "Describe the evolutionary significance of various stelar structures found in Pteridophytes. Give one suitable example in each case.", "v"],
  ["IFoS-2018-B1-Q2c", 10, "Describe the diversity of photosynthetic pigments found in the major classes of Algae.", "v"],
  ["IFoS-2018-B1-Q3a", 15, "What are the recent developments in the use of microbes in industrial products? Why do microbes serve as most ideal organisms in industrial applications?", "v"],
  ["IFoS-2018-B1-Q3b", 10, "Explain the progressive sterilization of potentially sporogenous tissue found in Bryophyta. Add a note on the role of elaters.", "v"],
  ["IFoS-2018-B1-Q3c", 15, "Describe the structure and chemical composition of TMV. How does it infect the host?", "v"],
  ["IFoS-2018-B1-Q4a", 15, "Describe the organization of female cone in Pinus. Discuss the morphological nature of ovuliferous scale.", "v"],
  ["IFoS-2018-B1-Q4b", 10, "Comment on how far Selaginella advances towards seed habit.", "v"],
  ["IFoS-2018-B1-Q4c", 15, "What is Systemic Acquired Resistance (SAR)? Discuss the role of salicylic acid in SAR.", "v"],
  ["IFoS-2018-B1-Q5a", 8, "How do you justify Asteraceae as a phylogenetically advanced family in dicotyledons?", "v"],
  ["IFoS-2018-B1-Q5b", 8, "Explain 'Nemec phenomenon' and its significance.", "v"],
  ["IFoS-2018-B1-Q5c", 8, "What are cortical vascular bundles? How are they formed?", "v"],
  ["IFoS-2018-B1-Q5d", 8, "Discuss the role of Botanical Gardens in conservation of plants.", "v"],
  ["IFoS-2018-B1-Q5e", 8, "What is haploid cell culture? How is this technique useful in agriculture?", "v"],
  ["IFoS-2018-B1-Q6a", 15, "Give an account of Cronquist's classification of flowering plants. Add a note on merits and demerits of this system of classification.", "v"],
  ["IFoS-2018-B1-Q6b", 15, "What is totipotency? Give an experimental evidence to demonstrate it.", "v"],
  ["IFoS-2018-B1-Q6c", 10, "What is Helobial type of endosperm? Describe the process of its development.", "v"],
  ["IFoS-2018-B1-Q7a", 15, "What is polyembryony? How is it induced? Discuss its applications.", "v"],
  ["IFoS-2018-B1-Q7b", 15, "Write the botanical name, family, economically important plant part and uses of: Cinnamon, Clove, Saffron, Nutmeg, Lesser Cardamom.", "v"],
  ["IFoS-2018-B1-Q7c", 10, "Compare the floral characters of Malvaceae and Solanaceae. Give the floral diagrams of the two families.", "v"],
  ["IFoS-2018-B1-Q8a", 15, "Name the four types of tea recognized in the trade. What are their properties and methods of processing?", "v"],
  ["IFoS-2018-B1-Q8b", 15, "Describe the organization of essential organs of Asclepiadaceae family. Discuss the pollination mechanism in it.", "v"],
  ["IFoS-2018-B1-Q8c", 10, "Give an account of hydrocarbon plants and their potential as a source of sustainable energy.", "v"],
  ["IFoS-2017-B1-Q1a", 8, "Distinguish between Prokaryotes and Eukaryotes.", "v"],
  ["IFoS-2017-B1-Q1b", 8, "What is Aflatoxin? State its importance.", "v"],
  ["IFoS-2017-B1-Q1c", 8, "Explain the pigments observed in Rhodophyceae.", "v"],
  ["IFoS-2017-B1-Q1d", 8, "Discuss Ammonification, Nitrification and Denitrification, stating the names of bacteria responsible for each step.", "v"],
  ["IFoS-2017-B1-Q1e", 8, "Explain the developmental stages of Pinus male gametophyte.", "v"],
  ["IFoS-2017-B1-Q2a", 10, "Describe Algal Phylogeny.", "v"],
  ["IFoS-2017-B1-Q2b", 10, "Describe sporophyte development in bryophytes with suitable illustrations.", "v"],
  ["IFoS-2017-B1-Q2c", 10, "Discuss the molecular basis of plant-pathogen interaction, with examples.", "v"],
  ["IFoS-2017-B1-Q2d", 10, "Describe the role of bacteria in pharmaceuticals, agriculture and industry.", "v"],
  ["IFoS-2017-B1-Q3a", 10, "Distinguish between Simple and Cleavage Polyembryony. With labelled diagrams, compare the embryogeny of Pinus and Cycas.", "v"],
  ["IFoS-2017-B1-Q3b", 10, "Enumerate the sporophytic and gametophytic features of Psilotum. Comment on its systematic position.", "v"],
  ["IFoS-2017-B1-Q3c", 10, "Discuss the role of transduction in genetic recombination in bacteria.", "v"],
  ["IFoS-2017-B1-Q3d", 10, "Characterize the different types of Mycorrhiza with examples. Discuss its role in agriculture and forestry.", "v"],
  ["IFoS-2017-B1-Q4a", 10, "Define Telome. Discuss Zimmermann's telome concept citing examples from major pteridophytic groups.", "v"],
  ["IFoS-2017-B1-Q4b", 10, "Describe briefly the symptoms and control measures of black stem rust of wheat. Name the causal organism. Why is it known as macrocyclic rust?", "v"],
  ["IFoS-2017-B1-Q4c", 10, "Distinguish between Lytic and Lysogenic cycles. Explain briefly the steps of multiplication of T4-bacteriophage by lytic cycle.", "v"],
  ["IFoS-2017-B1-Q4d", 10, "Discuss the role of amphibious plants in the evolution of land plants.", "v"],
  ["IFoS-2017-B1-Q5a", 8, "Explain with examples, the different provisions of author citations.", "v"],
  ["IFoS-2017-B1-Q5b", 8, "Discuss Vavilov's Centres of diversity.", "v"],
  ["IFoS-2017-B1-Q5c", 8, "Give five botanical names of fibre yielding plants and mention the parts from where fibres are obtained.", "v"],
  ["IFoS-2017-B1-Q5d", 8, "Discuss in brief, the distinctive flora of the Mesozoic Era.", "v"],
  ["IFoS-2017-B1-Q5e", 8, "Give a concept on the Inflorescence of Musaceae.", "v"],
  ["IFoS-2017-B1-Q6a", 10, "Discuss the basic outline of classification according to the principles of Bentham and Hooker. State its merits and demerits.", "v"],
  ["IFoS-2017-B1-Q6b", 10, "Compare the floral characteristics of Fabaceae and Asclepiadaceae. Give floral diagrams and name an economically important plant of each.", "v"],
  ["IFoS-2017-B1-Q6c", 10, "What do you mean by Palynology? Give an account of application of palynology.", "v"],
  ["IFoS-2017-B1-Q6d", 10, "Define Ethnobotany. Describe the role of ethnobotany in the discovery of modern drugs, citing examples.", "v"],
  ["IFoS-2017-B1-Q7a", 15, "Write the botanical names, active constituents and uses of five plants of economic importance belonging to each of the families Fabaceae, Rosaceae and Brassicaceae.", "v"],
  ["IFoS-2017-B1-Q7b", 15, "Discuss the different levels of biodiversity. Comment briefly on in situ and ex situ conservation. State the role of cryopreservation in conservation of plant biodiversity.", "v"],
  ["IFoS-2017-B1-Q7c", 10, "What is Apomixis? Discuss different apomictic developmental pathways with suitable illustrations. Give a note on genetics of apomixis.", "v"],
  ["IFoS-2017-B1-Q8a", 15, "What is meant by Anomalous Secondary Growth? Compare normal and anomalous secondary growth in dicots with examples and illustrations.", "v"],
  ["IFoS-2017-B1-Q8b", 10, "Define Botanical Garden and state how it differs from other gardens. Name two internationally reputed botanical gardens. Discuss the role of an ideal botanical garden in education.", "v"],
  ["IFoS-2017-B1-Q8c", 15, "Write notes on: Micropropagation (definition, stages, application); Callus culture (origin, application); Protoplast fusion (origin, merits, demerits).", "v"],
  ["IFoS-2018-B2-Q1a", 8, "Packaging of DNA in chromatin.", "v"],
  ["IFoS-2018-B2-Q1b", 8, "Chloroplast dimorphism.", "v"],
  ["IFoS-2018-B2-Q1c", 8, "Post-transcriptional modifications of mRNA.", "v"],
  ["IFoS-2018-B2-Q1d", 8, "Role of endoplasmic reticulum in protein sorting and targeting.", "v"],
  ["IFoS-2018-B2-Q1e", 8, "Objectives and properties of probability.", "v"],
  ["IFoS-2018-B2-Q2a", 20, "Describe the molecular basis of cell cycle transitions with suitable illustrations. Explain the role of CDKs in controlling transitions between cell cycle stages.", "v"],
  ["IFoS-2018-B2-Q2b", 20, "Discuss the mechanism of transport of molecules across the cell membrane by uniport, symport and antiport. Add a note on co-transport by symporter and uniporter.", "v"],
  ["IFoS-2018-B2-Q3a", 20, "Describe the molecular mechanism of gene linkage and crossing-over. Explain how a gene map is constructed using gene linkage, with suitable diagrams.", "v"],
  ["IFoS-2018-B2-Q3b", 20, "Describe different methods of selection and hybridization in plant breeding. Give a note on heterosis breeding.", "v"],
  ["IFoS-2018-B2-Q4a", 20, "Describe different stages of micropropagation in detail, mentioning the significance of each stage. Give a brief account of commercial micropropagation.", "v"],
  ["IFoS-2018-B2-Q4b", 20, "Describe the initiation of translation in prokaryotes with suitable illustrations. How does it differ from eukaryotes?", "v"],
  ["IFoS-2018-B2-Q5a", 8, "Role of Rubisco in carbon metabolism.", "v"],
  ["IFoS-2018-B2-Q5b", 8, "Importance of different types of secondary metabolites in plant defense and as pharmaceuticals.", "v"],
  ["IFoS-2018-B2-Q5c", 8, "Endemism and endangered plant species.", "v"],
  ["IFoS-2018-B2-Q5d", 8, "Hot spots in India: characteristics and conservation.", "v"],
  ["IFoS-2018-B2-Q5e", 8, "Allosteric enzymes and metabolic control.", "v"],
  ["IFoS-2018-B2-Q6a", 20, "Illustrate the structure of ATP synthase and discuss the mechanism of ATP synthesis in higher plants.", "v"],
  ["IFoS-2018-B2-Q6b", 20, "Explain the molecular basis of fruit ripening. How can this process be manipulated?", "v"],
  ["IFoS-2018-B2-Q7a", 20, "Discuss the mechanism of nitrogen fixation associated with legumes and elaborate the factors controlling the process.", "v"],
  ["IFoS-2018-B2-Q7b", 20, "Describe the adaptive responses at the morphological and physiological levels in higher plants to water deficit stress.", "v"],
  ["IFoS-2018-B2-Q8a", 20, "Explain the ecological characteristics of different types of forests found in India. Describe briefly the dominance of vegetation types of tropical and alpine forests.", "v"],
  ["IFoS-2018-B2-Q8b", 20, "Discuss the concept of climax community. Write a note on succession of estuarine ecosystem.", "v"],
  ["IFoS-2017-B2-Q1a", 8, "Complexes in electron transport chain of mitochondria.", "v"],
  ["IFoS-2017-B2-Q1b", 8, "Molecular basis of sex determination.", "v"],
  ["IFoS-2017-B2-Q1c", 8, "Significance of accessory chromosomes.", "v"],
  ["IFoS-2017-B2-Q1d", 8, "Merits and demerits of GM plants in India.", "v"],
  ["IFoS-2017-B2-Q1e", 8, "Chi-square test.", "v"],
  ["IFoS-2017-B2-Q2a", 20, "Describe the numerical and structural variations in chromosomes. Add a note on their significance.", "v"],
  ["IFoS-2017-B2-Q2b", 20, "Describe with illustrations chromosomal behaviour during meiosis with translocation, inversion and duplication.", "v"],
  ["IFoS-2017-B2-Q3a", 20, "Elucidate the role of RNA in the origin and evolution of living organisms.", "v"],
  ["IFoS-2017-B2-Q3b", 20, "With suitable example, explain tripartite sex-determination.", "v"],
  ["IFoS-2017-B2-Q4a", 20, "Explain the biochemical and molecular basis of mutations.", "v"],
  ["IFoS-2017-B2-Q4b", 20, "Narrate briefly the various methods of gene transfer in plants.", "v"],
  ["IFoS-2017-B2-Q5a", 8, "Allelopathy.", "v"],
  ["IFoS-2017-B2-Q5b", 8, "Intellectual property rights.", "v"],
  ["IFoS-2017-B2-Q5c", 8, "Molecular markers in plant breeding.", "v"],
  ["IFoS-2017-B2-Q5d", 8, "Role of carotenoids in plants.", "v"],
  ["IFoS-2017-B2-Q5e", 8, "Evidences of organic evolution.", "v"],
  ["IFoS-2017-B2-Q6a", 20, "\"Calvin cycle is said to be autocatalytic\" — justify. Compare CO2 assimilation in C3 and C4 plants. How does the C4 pathway differ from C3 in efficiency?", "v"],
  ["IFoS-2017-B2-Q6b", 20, "Describe the role of phytohormones in agri-horticulture.", "v"],
  ["IFoS-2017-B2-Q7a", 20, "With illustration describe the structure of phytochrome. Explain the role of phytochrome in flower development.", "v"],
  ["IFoS-2017-B2-Q7b", 20, "Describe the methods of breaking seed dormancy. Trace the physiological changes during seed germination.", "v"],
  ["IFoS-2017-B2-Q8a", 20, "Phytoremediation is not an ultimate solution to all the maladies of air and water. Explain in detail with specific examples.", "v"],
  ["IFoS-2017-B2-Q8b", 20, "Describe the phytogeographical zones of India and their salient features. A region has high temperature and rainfall, restricted snowfall, plus Rhododendron, oaks, orchids and ferns — what is your inference?", "v"],
  ["IFoS-2018-A1-Q1a", 8, "Enlist the agroclimatic zones of India and give their important cropping patterns.", "v"],
  ["IFoS-2018-A1-Q1b", 8, "What is rainfed farming? Discuss the technologies for stabilizing agricultural production in rainfed areas.", "v"],
  ["IFoS-2018-A1-Q1c", 8, "Maintenance of soil health needs regular recycling of lignocellulolytic materials to the soil. Justify.", "v"],
  ["IFoS-2018-A1-Q1d", 8, "What is multiple cropping? Give its significance in increasing crop production.", "v"],
  ["IFoS-2018-A1-Q1e", 8, "Discuss the effect of environmental factors on crop distribution and production.", "v"],
  ["IFoS-2018-A1-Q2a", 10, "Discuss how the agroforestry system helps in improving the livelihood of rural people.", "v"],
  ["IFoS-2018-A1-Q2b", 10, "Mention the principles of weed management and give their merits and demerits.", "v"],
  ["IFoS-2018-A1-Q2c", 10, "Define runoff, give factors affecting it and explain the soil loss equation during water erosion.", "v"],
  ["IFoS-2018-A1-Q2d", 10, "Highlight the effects of environmental pollution on living beings.", "v"],
  ["IFoS-2018-A1-Q3a", 10, "Justify the importance of forms of nutrients, their concentrations and ratios to other nutrients in soil for their uptake and crop growth.", "v"],
  ["IFoS-2018-A1-Q3b", 10, "Discuss how contingent crop planning helps in dryland agriculture.", "v"],
  ["IFoS-2018-A1-Q3c", 10, "Explain green-house effect and sources of their emission.", "v"],
  ["IFoS-2018-A1-Q3d", 10, "Describe aquatic weeds and their control management.", "v"],
  ["IFoS-2018-A1-Q4a", 10, "Discuss the major constraints in pulse production in India.", "v"],
  ["IFoS-2018-A1-Q4b", 10, "What is propagation? Give advantages of micro-propagation with reference to plantation plants.", "v"],
  ["IFoS-2018-A1-Q4c", 10, "What is soil genesis? Discuss the role of factors of soil formation.", "v"],
  ["IFoS-2018-A1-Q4d", 10, "What soil and water conservation practices are required to be adopted in hilly regions?", "v"],
  ["IFoS-2018-A1-Q5a", 8, "Define and explain consumptive use of water, evapotranspiration and water use efficiency.", "v"],
  ["IFoS-2018-A1-Q5b", 8, "Discuss the significance of advance farm planning for optimum use of resources.", "v"],
  ["IFoS-2018-A1-Q5c", 8, "What is agricultural cooperative farming? In what way is cooperative farming helpful to small and marginal farmers?", "v"],
  ["IFoS-2018-A1-Q5d", 8, "Describe agricultural price policy and instruments of price policy.", "v"],
  ["IFoS-2018-A1-Q5e", 8, "Discuss the role of farmers' participation in identifying needs of the area for planning and development.", "v"],
  ["IFoS-2018-A1-Q6a", 10, "What are drip and sprinkler irrigation? Give their merits and demerits.", "v"],
  ["IFoS-2018-A1-Q6b", 10, "How does the principle of opportunity cost help farmers to decide what to grow?", "v"],
  ["IFoS-2018-A1-Q6c", 10, "Explain marketing of farm products and marketing functions.", "v"],
  ["IFoS-2018-A1-Q6d", 10, "What is programme planning? Explain its evaluation.", "v"],
  ["IFoS-2018-A1-Q7a", 10, "How is drainage important? Explain its types.", "v"],
  ["IFoS-2018-A1-Q7b", 10, "What is farm budgeting? How is it important to farmers?", "v"],
  ["IFoS-2018-A1-Q7c", 10, "Give different approaches to study marketing and problems in marketing of agricultural produce.", "v"],
  ["IFoS-2018-A1-Q7d", 10, "How do self-help groups help to provide economic empowerment to rural women?", "v"],
  ["IFoS-2018-A1-Q8a", 10, "What is selective mechanization and progress of farm mechanization? Explain advantages and disadvantages of farm mechanization.", "v"],
  ["IFoS-2018-A1-Q8b", 10, "How is indigenous technical knowledge (ITK) useful to formulate future programmes?", "v"],
  ["IFoS-2018-A1-Q8c", 10, "Specify the criteria for time of irrigation.", "v"],
  ["IFoS-2018-A1-Q8d", 10, "Discuss the importance of farm management and its scope, with characteristics.", "v"],
  ["IFoS-2017-A1-Q1a", 8, "What are the climatic parameters affecting crop productivity according to which farmers follow the cropping pattern in the western zone of the country?", "v"],
  ["IFoS-2017-A1-Q1b", 8, "Justify the plant ecology and edaphic factors influencing sustainable agriculture.", "v"],
  ["IFoS-2017-A1-Q1c", 8, "What are the problems of herbicide-resistance in wheat crop?", "v"],
  ["IFoS-2017-A1-Q1d", 8, "Diversification and intensification are important in present day agriculture. Explain.", "v"],
  ["IFoS-2017-A1-Q1e", 8, "What is the importance of agroforestry and social forestry in the changing environment?", "v"],
  ["IFoS-2017-A1-Q2a", 10, "Package of practices (planting pattern, sowing time and spacing, weed and nutrient management, productivity) of Chickpea.", "v"],
  ["IFoS-2017-A1-Q2b", 10, "Package of practices (planting pattern, sowing time and spacing, weed and nutrient management, productivity) of Wheat.", "v"],
  ["IFoS-2017-A1-Q2c", 10, "Package of practices (planting pattern, sowing time and spacing, weed and nutrient management, productivity) of Lucerne.", "v"],
  ["IFoS-2017-A1-Q2d", 10, "Package of practices (planting pattern, sowing time and spacing, weed and nutrient management, productivity) of Sunflower.", "v"],
  ["IFoS-2017-A1-Q3a", 10, "What are the essential elements of plant nutrients? State the significance of C:N ratio in crop productivity.", "v"],
  ["IFoS-2017-A1-Q3b", 10, "Describe crop management practices in the early stage of saline and alkaline soils.", "v"],
  ["IFoS-2017-A1-Q3c", 10, "Describe phosphorus fixation in relation to soil pH.", "v"],
  ["IFoS-2017-A1-Q3d", 10, "Soil solarization is an important tool for weed control. Justify.", "v"],
  ["IFoS-2017-A1-Q4a", 10, "Describe dryland technology and rainfed agriculture for stabilizing production.", "v"],
  ["IFoS-2017-A1-Q4b", 10, "Define land degradation and discuss the major factors affecting it.", "v"],
  ["IFoS-2017-A1-Q4c", 10, "Explain the need of Integrated Nutrient Management (INM) in present day agriculture.", "v"],
  ["IFoS-2017-A1-Q4d", 10, "Enumerate the agronomic measures for soil and water conservation and practices adopted by the farmers.", "v"],
  ["IFoS-2017-A1-Q5a", 8, "Discuss the role of drip/sprinkler irrigation system in increasing water use efficiency and productivity.", "v"],
  ["IFoS-2017-A1-Q5b", 8, "Describe cropping systems, intercropping and relay cropping in agriculture, with examples.", "v"],
  ["IFoS-2017-A1-Q5c", 8, "Explain the current water pollution issues in agriculture with suitable remedies.", "v"],
  ["IFoS-2017-A1-Q5d", 8, "Vermicompost is important in sustainable agriculture. Justify.", "v"],
  ["IFoS-2017-A1-Q5e", 8, "Discuss water harvesting and the role of the Government and NGOs for its promotion.", "v"],
  ["IFoS-2017-A1-Q6a", 10, "Explain the short term and long term effects of agricultural mechanization.", "v"],
  ["IFoS-2017-A1-Q6b", 10, "Define farm management and explain the role of the farm manager in planning intensive agriculture.", "v"],
  ["IFoS-2017-A1-Q6c", 10, "Explain rural employment for women through agriculture.", "v"],
  ["IFoS-2017-A1-Q6d", 10, "Price fluctuations of agricultural products have an impact on small and marginal farmers. Justify.", "v"],
  ["IFoS-2017-A1-Q7a", 10, "What are the problems faced by landless agricultural labourers? What steps has the Government taken to intervene?", "v"],
  ["IFoS-2017-A1-Q7b", 10, "Discuss the role of Krishi Vigyan Kendras (KVK) in transfer of technologies to end users.", "v"],
  ["IFoS-2017-A1-Q7c", 10, "Explain management of wasteland for promoting agricultural production.", "v"],
  ["IFoS-2017-A1-Q7d", 10, "What is contract farming? What are its merits and demerits in present day agriculture?", "v"],
  ["IFoS-2018-A2-Q1a", 8, "What is the 'powerhouse' of a cell? Describe its structure with a labelled diagram.", "v"],
  ["IFoS-2018-A2-Q1b", 8, "Describe Mendel's laws of inheritance by giving suitable examples.", "v"],
  ["IFoS-2018-A2-Q1c", 8, "Describe the process of certified seed production in field crops.", "v"],
  ["IFoS-2018-A2-Q1d", 8, "Describe the conditions to maintain seed quality during post-harvest processing and storage.", "v"],
  ["IFoS-2018-A2-Q1e", 8, "Discuss the role of metal ions in enzyme activity.", "v"],
  ["IFoS-2018-A2-Q2a", 10, "Distinguish: seed production in self-pollinated and cross-pollinated crops (with examples).", "v"],
  ["IFoS-2018-A2-Q2b", 10, "Distinguish: heterosis breeding and mutation breeding.", "v"],
  ["IFoS-2018-A2-Q2c", 10, "Distinguish: ribonucleic acid and deoxyribonucleic acid.", "v"],
  ["IFoS-2018-A2-Q2d", 10, "Distinguish: enzymes and plant pigments.", "v"],
  ["IFoS-2018-A2-Q3a", 10, "Describe the methods and significance of maintenance breeding in the seed production system.", "v"],
  ["IFoS-2018-A2-Q3b", 10, "\"C4 plants are more water-use efficient compared to C3 plants.\" Explain citing suitable examples.", "v"],
  ["IFoS-2018-A2-Q3c", 10, "\"Transpiration is a necessary evil.\" Explain and justify.", "v"],
  ["IFoS-2018-A2-Q3d", 10, "Describe the significance of male sterility in hybrid seed production. Mention different types of male sterility.", "v"],
  ["IFoS-2018-A2-Q4a", 10, "Illustrate the plant and animal cells.", "v"],
  ["IFoS-2018-A2-Q4b", 10, "What is the significance of β-oxidation in germinating seeds?", "v"],
  ["IFoS-2018-A2-Q4c", 10, "Discuss orthodox and recalcitrant seeds with examples.", "v"],
  ["IFoS-2018-A2-Q4d", 10, "Write down the yield components and parameters of cereals, pulses and oilseeds.", "v"],
  ["IFoS-2018-A2-Q5a", 8, "Discuss the process of minimizing pesticide residue effects in vegetables.", "v"],
  ["IFoS-2018-A2-Q5b", 8, "Seed plot technique for virus-free potato seed production.", "v"],
  ["IFoS-2018-A2-Q5c", 8, "Describe the physiological role of gibberellic acid in seed germination.", "v"],
  ["IFoS-2018-A2-Q5d", 8, "Mango malformation.", "v"],
  ["IFoS-2018-A2-Q5e", 8, "Importance of carrot and guava in human nutrition.", "v"],
  ["IFoS-2018-A2-Q6a", 10, "Calculate the amount of Malathion 50 EC to treat 50 hectares of a flower crop @ 800 litres per hectare at 0.01% concentration.", "v"],
  ["IFoS-2018-A2-Q6b", 10, "Discuss the problems involved in marketing of vegetables and fruits.", "v"],
  ["IFoS-2018-A2-Q6c", 10, "What is pruning? Discuss its principles and significance in fruit crops.", "v"],
  ["IFoS-2018-A2-Q6d", 10, "What is biological control of plant diseases? Discuss its principles. Name important biocontrol agents and their application against important crop diseases.", "v"],
  ["IFoS-2018-A2-Q7a", 10, "Distinguish: fungal wilt and bacterial wilt of vegetables.", "v"],
  ["IFoS-2018-A2-Q7b", 10, "Distinguish: insect parasitoids and predators.", "v"],
  ["IFoS-2018-A2-Q7c", 10, "Distinguish: formal and informal gardens.", "v"],
  ["IFoS-2018-A2-Q7d", 10, "Distinguish: seed germination and seed dormancy.", "v"],
  ["IFoS-2018-A2-Q8a", 15, "Describe the food production constraints in the Indian agricultural system.", "v"],
  ["IFoS-2018-A2-Q8b", 15, "Mention the important storage insects of pulses and cereals, and their management practices.", "v"],
  ["IFoS-2018-A2-Q8c", 10, "Describe the principles and methods of post-harvest management of important fruits.", "v"],
  ["IFoS-2017-A2-Q1a", 8, "Describe the mode of origin and growth of cell wall.", "v"],
  ["IFoS-2017-A2-Q1b", 8, "Define allopolyploidy. Give its applications in crop improvement.", "v"],
  ["IFoS-2017-A2-Q1c", 8, "Write the factors affecting seed quality.", "v"],
  ["IFoS-2017-A2-Q1d", 8, "Enlist the enzymes requiring metal activators.", "v"],
  ["IFoS-2017-A2-Q1e", 8, "Describe chemically induced male sterility.", "v"],
  ["IFoS-2017-A2-Q2a", 0, "Distinguish between epistasis and dominance. Explain gene interaction.", "v"],
  ["IFoS-2017-A2-Q2b", 0, "From germination and purity data of seed samples of a crop, which sample would you recommend to a grower? (pure live seed)", "v"],
  ["IFoS-2017-A2-Q2c", 0, "Discuss cyclic and non-cyclic photophosphorylation.", "v"],
  ["IFoS-2017-A2-Q3a", 0, "Distinguish: diffusion and osmosis.", "v"],
  ["IFoS-2017-A2-Q3b", 0, "Distinguish: sex-influenced and sex-limited characters.", "v"],
  ["IFoS-2017-A2-Q3c", 0, "Distinguish: synchrony in flowering and planting ratio of parents (hybrid seed production).", "v"],
  ["IFoS-2017-A2-Q4a", 15, "What is phytochrome? Enlist different processes mediated by phytochrome.", "v"],
  ["IFoS-2017-A2-Q4b", 0, "Give the advantages of molecular markers over other genetic markers.", "v"],
  ["IFoS-2017-A2-Q4c", 0, "Describe seed certification and seed quality assurance in India.", "v"],
  ["IFoS-2017-A2-Q5a", 8, "Importance of pinching in quality production of carnation.", "v"],
  ["IFoS-2017-A2-Q5b", 8, "Preventive and curative methods against stored grain pests.", "v"],
  ["IFoS-2017-A2-Q5c", 8, "Integrated management of Fusarium and Verticillium.", "v"],
  ["IFoS-2017-A2-Q5d", 8, "Entomopathogenic bacteria for pest control.", "v"],
  ["IFoS-2017-A2-Q5e", 8, "Describe the preservation methods of important fruits.", "v"],
  ["IFoS-2017-A2-Q6a", 0, "Give major insect pests of cauliflower and their management.", "v"],
  ["IFoS-2017-A2-Q6b", 0, "Find the quantity of Chlorpyriphos 20 EC for an area requiring 1000 litres of spray fluid at 0.02% strength.", "v"],
  ["IFoS-2017-A2-Q6c", 0, "Discuss the procurement and processing constraints of food grains.", "v"],
  ["IFoS-2017-A2-Q7a", 15, "Distinguish: olericulture and pomology.", "v"],
  ["IFoS-2017-A2-Q7b", 0, "Distinguish: mildews and blights.", "v"],
  ["IFoS-2017-A2-Q7c", 0, "Distinguish: inoculative and augmentative releases of natural enemies.", "v"],
  ["IFoS-2017-A2-Q8a", 0, "What are the critical components that need adequate attention while planning an orchard?", "v"],
  ["IFoS-2017-A2-Q8b", 0, "Discuss Protein-Energy Malnutrition.", "v"],
  ["IFoS-2017-A2-Q8c", 0, "Discuss various methods of training in chrysanthemum.", "v"],
  ["IFoS-2025-B1-Q1a", 8, "Differences between mosses and liverworts.", "t"],
  ["IFoS-2025-B1-Q1c", 8, "Cyanobacteria combine characters historically treated as algal and bacterial.", "t"],
  ["IFoS-2025-B1-Q1d", 8, "Micro-organisms used for ethanol, citric acid, bacitracin and cellulase production.", "t"],
  ["IFoS-2025-B1-Q1e", 8, "Seed-fern order (Pteridospermales / Cycadofilicales) and its characters.", "t"],
  ["IFoS-2025-B1-Q2a", 10, "Ecological importance of bryophytes.", "t"],
  ["IFoS-2025-B1-Q2b", 15, "Laminaria: thallus structure and sexual reproduction.", "t"],
  ["IFoS-2025-B1-Q3b", 15, "Tikka disease of groundnut: pathogen, disease cycle and management.", "t"],
  ["IFoS-2025-B1-Q3c", 15, "Ophioglossaceae: Ophioglossum fertile spike and sporangium.", "t"],
  ["IFoS-2025-B1-Q4a", 10, "Fungal enzymes and toxins.", "t"],
  ["IFoS-2025-B1-Q4b", 15, "Zygomycetes: characters and sexual reproduction.", "t"],
  ["IFoS-2025-B1-Q5a", 8, "Adventive embryony and haploid parthenogenesis.", "t"],
  ["IFoS-2025-B1-Q5b", 8, "Development of the male gametophyte.", "t"],
  ["IFoS-2025-B1-Q5d", 8, "Dye-yielding plants.", "t"],
  ["IFoS-2025-B1-Q5e", 8, "Herbarium and virtual herbarium.", "t"],
  ["IFoS-2025-B1-Q6a", 10, "Anomalous secondary growth in Boerhavia diffusa and Salvadora.", "t"],
  ["IFoS-2025-B1-Q6b", 15, "Fabaceae: sub-families, floral formulae and floral diagrams.", "t"],
  ["IFoS-2025-B1-Q6c", 15, "Economic botany of fig, tea, oats, oil palm and clove.", "t"],
  ["IFoS-2025-B1-Q7a", 10, "Ethnobotany in India.", "t"],
  ["IFoS-2025-B1-Q8a", 10, "Botanical gardens and their role.", "t"],
  ["IFoS-2025-B2-Q1a", 8, "Cell adhesion.", "t"],
  ["IFoS-2025-B2-Q1b", 8, "Generation of ATP in mitochondria.", "t"],
  ["IFoS-2025-B2-Q1c", 8, "Sex linkage.", "t"],
  ["IFoS-2025-B2-Q1d", 8, "Tests of significance.", "t"],
  ["IFoS-2025-B2-Q1e", 8, "Male sterility.", "t"],
  ["IFoS-2025-B2-Q2a", 20, "Numerical and structural changes in chromosomes.", "t"],
  ["IFoS-2025-B2-Q2b", 10, "Multigene families.", "t"],
  ["IFoS-2025-B2-Q2c", 10, "Backcross and pedigree methods of breeding.", "t"],
  ["IFoS-2025-B2-Q3a", 20, "Regulation of gene expression.", "t"],
  ["IFoS-2025-B2-Q3b", 10, "Polytene and B chromosomes.", "t"],
  ["IFoS-2025-B2-Q3c", 10, "Role of RNA in the origin and evolution of life.", "t"],
  ["IFoS-2025-B2-Q4a", 20, "Cell signalling and receptors.", "t"],
  ["IFoS-2025-B2-Q4b", 10, "Extracellular matrix.", "t"],
  ["IFoS-2025-B2-Q4c", 10, "Gene mapping.", "t"],
  ["IFoS-2025-B2-Q5b", 8, "Photoperiodism.", "t"],
  ["IFoS-2025-B2-Q5c", 8, "Rubisco.", "t"],
  ["IFoS-2025-B2-Q5d", 8, "Sovereign rights over biological resources and IPR.", "t"],
  ["IFoS-2025-B2-Q5e", 8, "Phosphorus and nitrogen cycles.", "t"],
  ["IFoS-2025-B2-Q6a", 20, "Direct and indirect methods of gene transfer.", "t"],
  ["IFoS-2025-B2-Q6b", 10, "Enzymes and coenzymes.", "t"],
  ["IFoS-2025-B2-Q6c", 10, "Threats to plant diversity and its conservation.", "t"],
  ["IFoS-2025-B2-Q7a", 20, "Ecological succession.", "t"],
  ["IFoS-2025-B2-Q7c", 10, "Micropropagation.", "t"],
  ["IFoS-2025-B2-Q8b", 10, "Nif genes and regulation of nitrogen fixation.", "t"],
  ["IFoS-2025-B2-Q8c", 10, "Pentose phosphate pathway and glycolysis.", "t"],
  ["IFoS-2025-A1-Q1a", 8, "Soil structure, including prismatic structure.", "t"],
  ["IFoS-2025-A1-Q1b", 8, "Hedgerow intercropping.", "t"],
  ["IFoS-2025-A1-Q1c", 8, "Biotic and abiotic factors affecting crops.", "t"],
  ["IFoS-2025-A1-Q1d", 8, "Short-duration crop varieties.", "t"],
  ["IFoS-2025-A1-Q1e", 8, "Calculation of residual sodium carbonate (RSC) of irrigation water.", "t"],
  ["IFoS-2025-A1-Q2a", 15, "Agroforestry and social forestry.", "t"],
  ["IFoS-2025-A1-Q2b", 15, "Soil organic matter and soil microbiological properties.", "t"],
  ["IFoS-2025-A1-Q2c", 10, "Climate change and crops.", "t"],
  ["IFoS-2025-A1-Q3a", 15, "Wheat cultivation under specified headings.", "t"],
  ["IFoS-2025-A1-Q3b", 15, "Characters of weeds and exotic weeds affecting biodiversity.", "t"],
  ["IFoS-2025-A1-Q3c", 10, "Nitrogen losses from soil and denitrification.", "t"],
  ["IFoS-2025-A1-Q4a", 15, "Soil and water pollution.", "t"],
  ["IFoS-2025-A1-Q4b", 15, "Short notes including agroclimatic zones, cotton leaf reddening and jute retting.", "t"],
  ["IFoS-2025-A1-Q4c", 10, "Causes of micronutrient deficiency.", "t"],
  ["IFoS-2025-A1-Q5a", 8, "Steps of extension programme planning (Leagans, 1967).", "t"],
  ["IFoS-2025-A1-Q5b", 8, "Types of farming.", "t"],
  ["IFoS-2025-A1-Q5c", 8, "Bunding for soil conservation.", "t"],
  ["IFoS-2025-A1-Q5d", 8, "Cooperative marketing.", "t"],
  ["IFoS-2025-A1-Q5e", 8, "Critical stages of crops for irrigation (including groundnut).", "t"],
  ["IFoS-2025-A1-Q6a", 15, "mKrishi and ICT in extension.", "t"],
  ["IFoS-2025-A1-Q6b", 15, "Farm planning and its limitations.", "t"],
  ["IFoS-2025-A1-Q6c", 10, "Classes of gullies.", "t"],
  ["IFoS-2025-A1-Q7a", 15, "Irrigation-water quality: EC, SAR and tolerant crops.", "t"],
  ["IFoS-2025-A1-Q7b", 15, "Watershed management.", "t"],
  ["IFoS-2025-A1-Q7c", 10, "Contract farming.", "t"],
  ["IFoS-2025-A1-Q8a", 15, "Irrigation scheduling and frequency.", "t"],
  ["IFoS-2025-A2-Q1a", 8, "Variation: its components and methods of creating variation.", "t"],
  ["IFoS-2025-A2-Q1b", 8, "Public-sector seed institutions.", "t"],
  ["IFoS-2025-A2-Q1c", 8, "Transpiration.", "t"],
  ["IFoS-2025-A2-Q1d", 8, "Cell organelles and cell wall (with diagram).", "t"],
  ["IFoS-2025-A2-Q1e", 8, "Hybrids in cereals and their productivity.", "t"],
  ["IFoS-2025-A2-Q2a", 15, "History of plant breeding and genetic engineering.", "t"],
  ["IFoS-2025-A2-Q2b", 15, "Conservation and use of plant genetic resources.", "t"],
  ["IFoS-2025-A2-Q2c", 10, "C3 and C4 crops in relation to climate.", "t"],
  ["IFoS-2025-A2-Q3a", 15, "Gene pools.", "t"],
  ["IFoS-2025-A2-Q3b", 15, "Breeding for resistance, with examples.", "t"],
  ["IFoS-2025-A2-Q3c", 10, "Mendelian dominance.", "t"],
  ["IFoS-2025-A2-Q4a", 15, "Distinctions in modes of inheritance.", "t"],
  ["IFoS-2025-A2-Q4b", 15, "Field standards for seed production in cross-pollinated crops.", "t"],
  ["IFoS-2025-A2-Q4c", 10, "Male sterility in vegetable crops.", "t"],
  ["IFoS-2025-A2-Q5a", 8, "Plug-tray nursery.", "t"],
  ["IFoS-2025-A2-Q5b", 8, "Fungal and bacterial diseases of solanaceous crops.", "t"],
  ["IFoS-2025-A2-Q5c", 8, "Fungi of stored pulses.", "t"],
  ["IFoS-2025-A2-Q5d", 8, "Microbial toxins.", "t"],
  ["IFoS-2025-A2-Q5e", 8, "National Food Security Act.", "t"],
  ["IFoS-2025-A2-Q6a", 15, "Pomegranate: package of practices and challenges in arid regions.", "t"],
  ["IFoS-2025-A2-Q6b", 15, "Millets and nutrition.", "t"],
  ["IFoS-2025-A2-Q6c", 10, "Types of seed dormancy and methods of breaking it.", "t"],
  ["IFoS-2025-A2-Q7a", 15, "Marketing of horticultural produce and TOP (tomato–onion–potato) price stabilisation.", "t"],
  ["IFoS-2025-A2-Q7b", 15, "Kharif okra cultivation.", "t"],
  ["IFoS-2025-A2-Q7c", 10, "Photoperiodism and vernalisation.", "t"],
  ["IFoS-2025-A2-Q8a", 15, "Procurement and food policy.", "t"],
  ["IFoS-2025-A2-Q8b", 15, "IPM for thrips and mites, including biocontrol.", "t"]
);
